MSPM0G3507HallSensoredTrapMotorControlLibrary: Hall Trap
Hall Trap
Data Structures
struct Halltrap_Instance
Defines a halltrap instance.
Macros
#define HALLTRAP_HALT_TIME_US (1e6)
Defines the halt time before changing the motor direction.
Enumerations
enum HALL {
HALL_A = 0,
HALL_B,
HALL_C,
HALL_MAX
}
enum MOTOR_DIR {
MOTOR_DIR_FORWARD = 0,
MOTOR_DIR_REVERSE
}
enum MOTOR_BRAKE_TYPE {
MOTOR_BRAKE_TYPE_COAST = 0,
MOTOR_BRAKE_TYPE_BRAKE
}
enum MOTOR_STATE {
MOTOR_STATE_RUN = 0,
MOTOR_STATE_STOP
}
enum HALLTRAP_COMM_STATE {
HALLTRAP_COMM_STATE_C_TO_A = 1,
HALLTRAP_COMM_STATE_A_TO_B = 2,
HALLTRAP_COMM_STATE_C_TO_B = 3,
HALLTRAP_COMM_STATE_B_TO_C = 4,
HALLTRAP_COMM_STATE_B_TO_A = 5,
HALLTRAP_COMM_STATE_A_TO_C = 6
}
Functions
void Halltrap_Init (Halltrap_Instance *hallTrap)
Initialize the halltrap module.
void Halltrap_PWMUpdate (Halltrap_Instance *hallTrap, MOTOR_DIR dir, uint16_t pwmDuty)
Updates the PWM.
uint32_t Halltrap_calculateMotorSpeed (Halltrap_Instance *hallTrap, uint32_t poles)
Calculates motor speed.
__STATIC_INLINE void Halltrap_setDeadband (Halltrap_Instance *hallTrap, uint16_t deadtime_ns)
Sets the deadband in all phases.
__STATIC_INLINE void Halltrap_setPWMFreq (Halltrap_Instance *hallTrap, uint32_t pwmFreq)
Sets the pwm frequency in all phases.
__STATIC_INLINE void Halltrap_stopMotor (Halltrap_Instance *hallTrap, MOTOR_BRAKE_TYPE brakeType)
Stops the motor.
__STATIC_INLINE void Halltrap_disablePWM (Halltrap_Instance *hallTrap)
Disable the PWM output.
__STATIC_INLINE void Halltrap_changeMotorDirection (Halltrap_Instance *hallTrap, MOTOR_DIR dir)
Changes the motor direction.
Detailed Description
Enumeration Type Documentation
HALL
enum HALL
Enumerator
HALL_A
Defines hall A.
HALL_B
Defines hall B.
HALL_C
Defines hall C.
HALL_MAX
Maximum hall signals.
MOTOR_DIR
enum MOTOR_DIR
Enumerator
MOTOR_DIR_FORWARD
Defines Motor Directions Forward.
MOTOR_DIR_REVERSE
Defines Motor Directions Reverse.
MOTOR_BRAKE_TYPE
enum MOTOR_BRAKE_TYPE
Enumerator
MOTOR_BRAKE_TYPE_COAST
Defines Motor Brake Type Coast.
MOTOR_BRAKE_TYPE_BRAKE
Defines Motor Brake Type Brake.
MOTOR_STATE
enum MOTOR_STATE
Enumerator
MOTOR_STATE_RUN
Defines Motor Run.
MOTOR_STATE_STOP
Defines Motor Stop.
HALLTRAP_COMM_STATE
enum HALLTRAP_COMM_STATE
Enumerator
HALLTRAP_COMM_STATE_C_TO_A
current from C to A in forward control and A to C in reverse control, phase B is open
HALLTRAP_COMM_STATE_A_TO_B
current from A to B in forward control and B to A in reverse control, phase C is open
HALLTRAP_COMM_STATE_C_TO_B
current from C to B in forward control and B to C in reverse control, phase A is open
HALLTRAP_COMM_STATE_B_TO_C
current from B to C in forward control and C to B in reverse control, phase A is open
HALLTRAP_COMM_STATE_B_TO_A
current from B to A in forward control and A to B in reverse control, phase C is open
HALLTRAP_COMM_STATE_A_TO_C
current from A to C in forward control and C to A in reverse control, phase B is open
Function Documentation
Halltrap_Init()
void Halltrap_Init (Halltrap_Instance * hallTrap)
Initialize the halltrap module.
Parameters
[in] hallTrap The halltrap instance
References Halltrap_Instance::captureInput, HAL_enableCaptureInterrupt(), HAL_enableGPIOInterrupt(), HAL_updatePWM(), Halltrap_Instance::hallA, Halltrap_Instance::hallB, Halltrap_Instance::hallC, HALLTRAP_COMM_STATE_A_TO_B, HALLTRAP_COMM_STATE_A_TO_C, HALLTRAP_COMM_STATE_B_TO_A, HALLTRAP_COMM_STATE_B_TO_C, HALLTRAP_COMM_STATE_C_TO_A, HALLTRAP_COMM_STATE_C_TO_B, Halltrap_Instance::phaseA, Halltrap_Instance::phaseB, and Halltrap_Instance::phaseC.
Halltrap_PWMUpdate()
void Halltrap_PWMUpdate (Halltrap_Instance * hallTrap, MOTOR_DIR dir, uint16_t pwmDuty)
Updates the PWM.
Parameters
[in] hallTrap The halltrap instance
[in] dir Motor direction of rotation
[in] pwmDuty PWMDuty in percentage
References HAL_readGPIOPin(), HALL_A, HALL_B, HALL_C, HALL_MAX, Halltrap_Instance::hallA, Halltrap_Instance::hallB, Halltrap_Instance::hallC, and MOTOR_DIR_FORWARD.
Referenced by Halltrap_changeMotorDirection().
Halltrap_calculateMotorSpeed()
uint32_t Halltrap_calculateMotorSpeed (Halltrap_Instance * hallTrap, uint32_t poles)
Calculates motor speed.
Parameters
[in] hallTrap The halltrap instance
[in] poles Number of motor poles
Returns
Speed
References Halltrap_Instance::captureInput, and HAL_getCaptureFrequency().
Halltrap_setDeadband()
__STATIC_INLINE void Halltrap_setDeadband (Halltrap_Instance * hallTrap, uint16_t deadtime_ns)
Sets the deadband in all phases.
Parameters
[in] hallTrap The halltrap instance
[in] deadtime_ns Delay time in nanoseconds
References HAL_setDeadband(), Halltrap_Instance::phaseA, Halltrap_Instance::phaseB, and Halltrap_Instance::phaseC.
Halltrap_setPWMFreq()
__STATIC_INLINE void Halltrap_setPWMFreq (Halltrap_Instance * hallTrap, uint32_t pwmFreq)
Sets the pwm frequency in all phases.
Parameters
[in] hallTrap The halltrap instance
[in] pwmFreq The frequency of PWM
References HAL_setPWMFreq(), Halltrap_Instance::phaseA, Halltrap_Instance::phaseB, and Halltrap_Instance::phaseC.
Halltrap_stopMotor()
__STATIC_INLINE void Halltrap_stopMotor (Halltrap_Instance * hallTrap, MOTOR_BRAKE_TYPE brakeType)
Stops the motor.
Parameters
[in] hallTrap The halltrap instance
[in] brakeType Type of braking applied
References HAL_PWMOutputHigh(), HAL_PWMOutputLow(), MOTOR_BRAKE_TYPE_COAST, Halltrap_Instance::phaseA, Halltrap_Instance::phaseB, and Halltrap_Instance::phaseC.
Halltrap_disablePWM()
__STATIC_INLINE void Halltrap_disablePWM (Halltrap_Instance * hallTrap)
Disable the PWM output.
Parameters
[in] hallTrap The halltrap instance
References HAL_PWMOutputLow(), Halltrap_Instance::phaseA, Halltrap_Instance::phaseB, and Halltrap_Instance::phaseC.
Halltrap_changeMotorDirection()
__STATIC_INLINE void Halltrap_changeMotorDirection (Halltrap_Instance * hallTrap, MOTOR_DIR dir)
Changes the motor direction.
Parameters
[in] hallTrap The halltrap instance
[in] dir Motor direction of rotation
References HAL_delayMicroSeconds(), HAL_PWMOutputLow(), HALLTRAP_HALT_TIME_US, Halltrap_PWMUpdate(), Halltrap_Instance::phaseA, Halltrap_Instance::phaseB, and Halltrap_Instance::phaseC.
© Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale