MSPM0Gxx0xEdgeAIAPIDocument: uart_comm_target.h File Reference
uart_comm_target.h File Reference
Detailed Description
UART communication Module.
Overview
APIs for UART communication module
#include "ti_msp_dl_config.h"
#include "device_agent_protocol/dap_interface.h"
#include <stdbool.h>
Data Structures
struct BufferInfo
Buffer info structure.
struct UART_Instance
UART instance.
Macros
#define START_IDX (0)
Start index.
#define START_BYTE_SIZE (1)
Start byte size.
#define FRAME_START_BYTE (0xED)
Frame start byte.
#define PREAMBLE_BYTE_SIZE (1)
Preamble byte size.
#define CMD_IDX (START_IDX + START_BYTE_SIZE)
Command index.
#define CMD_SIZE (1)
Command size.
#define HEADER_SIZE (START_BYTE_SIZE + CMD_SIZE)
Header size.
#define LEN_IDX (CMD_IDX + CMD_SIZE)
Length Byte index.
#define MAX_LEN_IDX (3)
Max Length Byte size.
#define PAYLOAD_IDX (LEN_IDX + MAX_LEN_IDX)
Payload index.
#define END_OFFSET (1)
End offset.
#define FRAME_END_BYTE (0x9E)
Frame end byte.
#define END_BYTE_SIZE (1)
End byte size.
#define TRAILER_SIZE (END_BYTE_SIZE)
Trailer size.
#define PACKET_FIXED_PART_SIZE (4)
Packet Fixed part size.
#define DMA_RX_TRANSFER_SIZE (64 + PACKET_FIXED_PART_SIZE)
DMA receive transfer size.
#define MAX_BUFFER_SIZE (600)
Maximum buffer size.
#define CRC_INIT_VALUE (0x66)
CRC Initial Value as per device agent protocol spec.
Enumerations
enum UART_Status {
UART_STATUS_IDLE = 0,
UART_STATUS_RX_BUFFERING,
UART_STATUS_PROCESS_FRAME,
UART_STATUS_TX_TRANSMITTING
}
UART status.
enum ErrorType {
ERROR_TYPE_NONE = 0x00,
ERROR_TYPE_MISMATCH_START_BYTE = 0xE1,
ERROR_TYPE_MISMATCH_END_BYTE = 0xE2,
ERROR_TYPE_MISMATCH_CRC = 0xE3
}
UART ERROR types.
Functions
void UART_init (UART_Instance *UART_handle)
Initializes the UART module.
void UART_checkForCommand (UART_Instance *UART_handle)
Checks the Rx Buffer for commands.
void DMA_RX_init (UART_Instance *UART_handle)
Initializes DMA to store the command in RX Buffer.
void UART_clearBuffer (BufferInfo *frame)
Clears the Buffer.
void UART_sendBuffer (BufferInfo *frame)
Initializes DMA to send the response stored in Tx Buffer.
uint8_t CRC_calc8 (uint8_t *ptr, uint16_t len)
Computes 8-bit CRC on the input message array.
void UART_reSync (UART_Instance *UART_handle)
Resets pointer and length of the buffer to synchronize with controller.
Enumeration Type Documentation
UART_Status
enum UART_Status
UART status.
Enumerator
UART_STATUS_IDLE
UART IDLE state
UART_STATUS_RX_BUFFERING
UART RX buffering state
UART_STATUS_PROCESS_FRAME
UART process frame state
UART_STATUS_TX_TRANSMITTING
UART TX transmitting state
ErrorType
enum ErrorType
UART ERROR types.
Note
Error numbers are not defined in DAP v1.0
Update the Enum accordingly once the error numbers are defined
Enumerator
ERROR_TYPE_NONE
No error
ERROR_TYPE_MISMATCH_START_BYTE
Mismatch Start byte error
ERROR_TYPE_MISMATCH_END_BYTE
Mismatch end byte error
ERROR_TYPE_MISMATCH_CRC
Mismatch CRC error
Function Documentation
UART_init()
void UART_init (UART_Instance * UART_handle)
Initializes the UART module.
Parameters
[in] UART_handle A pointer to UART_Instance
References UART_Instance::dataLen, DMA_RX_init(), UART_Instance::error, ERROR_TYPE_NONE, UART_Instance::isCrc, UART_Instance::rxMsg, UART_Instance::RxStatus, UART_Instance::txMsg, UART_Instance::TxStatus, UART_clearBuffer(), and UART_STATUS_IDLE.
UART_checkForCommand()
void UART_checkForCommand (UART_Instance * UART_handle)
Checks the Rx Buffer for commands.
Parameters
[in] UART_handle A pointer to UART_Instance
References DMA_RX_TRANSFER_SIZE, BufferInfo::len, UART_Instance::rxMsg, UART_Instance::RxStatus, UART_STATUS_PROCESS_FRAME, and UART_STATUS_RX_BUFFERING.
DMA_RX_init()
void DMA_RX_init (UART_Instance * UART_handle)
Initializes DMA to store the command in RX Buffer.
Parameters
[in] UART_handle Pointer to UART_Instance
References DMA_RX_TRANSFER_SIZE, and UART_Instance::rxMsg.
Referenced by UART_init().
UART_clearBuffer()
void UART_clearBuffer (BufferInfo * frame)
Clears the Buffer.
Parameters
[in] frame Pointer to BufferInfo
Clears the Buffer.
Parameters
[in] frame Pointer to BufferInfo (Rx,Tx)
References BufferInfo::len, and BufferInfo::ptr.
Referenced by UART_init().
UART_sendBuffer()
void UART_sendBuffer (BufferInfo * frame)
Initializes DMA to send the response stored in Tx Buffer.
Parameters
[in] frame Pointer to BufferInfo (Tx)
References BufferInfo::len.
CRC_calc8()
uint8_t CRC_calc8 (uint8_t * ptr, uint16_t len)
Computes 8-bit CRC on the input message array.
Parameters
ptr Buffer which holds the input message (array of bytes)
len Length of the data in the Buffer (array)
Returns
crc 8-bit CRC calculated on the input message, CCITT Polynomial x^8 + x^2 + x + 1
References CRC_INIT_VALUE.
UART_reSync()
void UART_reSync (UART_Instance * UART_handle)
Resets pointer and length of the buffer to synchronize with controller.
Parameters
[in] UART_handle Pointer to UART_Instance
References DMA_RX_TRANSFER_SIZE, FRAME_END_BYTE, and UART_Instance::rxMsg.
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale