MSPM0L11XX_L13XX Driver Library: General Purpose Amplifier (GPAMP)
General Purpose Amplifier (GPAMP)
Data Structures
struct DL_GPAMP_Config
Configuration struct for DL_GPAMP_init.
Enumerations
enum DL_GPAMP_NSEL {
DL_GPAMP_NSEL_OUTPUT_PIN = SYSCTL_PMUOPAMP_NSEL_SEL0,
DL_GPAMP_NSEL_IN_NEG = SYSCTL_PMUOPAMP_NSEL_SEL1,
DL_GPAMP_NSEL_INTERNAL_OUTPUT = SYSCTL_PMUOPAMP_NSEL_SEL2,
DL_GPAMP_NSEL_OPEN = SYSCTL_PMUOPAMP_NSEL_SEL3
}
enum DL_GPAMP_PSEL {
DL_GPAMP_PSEL_OPEN = SYSCTL_PMUOPAMP_PCHENABLE_FALSE,
DL_GPAMP_PSEL_IN_POS = SYSCTL_PMUOPAMP_PCHENABLE_TRUE
}
enum DL_GPAMP_OUTPUT_PIN_STATE {
DL_GPAMP_OUTPUT_PIN_STATE_DISABLED = SYSCTL_PMUOPAMP_OUTENABLE_FALSE,
DL_GPAMP_OUTPUT_PIN_STATE_ENABLED = SYSCTL_PMUOPAMP_OUTENABLE_TRUE
}
enum DL_GPAMP_RRI_MODE {
DL_GPAMP_RRI_MODE_PMOS_INPUT = SYSCTL_PMUOPAMP_RRI_MODE0,
DL_GPAMP_RRI_MODE_NMOS_INPUT = SYSCTL_PMUOPAMP_RRI_MODE1,
DL_GPAMP_RRI_MODE_RAIL_TO_RAIL = SYSCTL_PMUOPAMP_RRI_MODE2,
DL_GPAMP_RRI_MODE_SAMPLE_CHANNEL_0 = SYSCTL_PMUOPAMP_RRI_MODE3
}
enum DL_GPAMP_CHOPPING_FREQ {
DL_GPAMP_CHOPPING_FREQ_16KHZ = SYSCTL_PMUOPAMP_CHOPCLKFREQ_CLK16KHZ,
DL_GPAMP_CHOPPING_FREQ_8KHZ = SYSCTL_PMUOPAMP_CHOPCLKFREQ_CLK8KHZ,
DL_GPAMP_CHOPPING_FREQ_4KHZ = SYSCTL_PMUOPAMP_CHOPCLKFREQ_CLK4KHZ,
DL_GPAMP_CHOPPING_FREQ_2KHZ = SYSCTL_PMUOPAMP_CHOPCLKFREQ_CLK2KHZ
}
enum DL_GPAMP_CHOPPING_MODE {
DL_GPAMP_CHOPPING_MODE_DISABLED = SYSCTL_PMUOPAMP_CHOPCLKMODE_CHOPDISABLED,
DL_GPAMP_CHOPPING_MODE_STANDARD = SYSCTL_PMUOPAMP_CHOPCLKMODE_REGCHOP,
DL_GPAMP_CHOPPING_MODE_ADC_ASSISTED
}
Functions
__STATIC_INLINE void DL_GPAMP_enable (void)
Enable the GPAMP peripheral.
__STATIC_INLINE bool DL_GPAMP_isEnabled (void)
Checks if the GPAMP peripheral is enabled.
__STATIC_INLINE void DL_GPAMP_disable (void)
Disable the GPAMP peripheral.
__STATIC_INLINE void DL_GPAMP_init (DL_GPAMP_Config *config)
Initialize the GPAmp peripheral.
__STATIC_INLINE void DL_GPAMP_enableNonInvertingInputChannel (void)
Enable the non-inverting input channel.
__STATIC_INLINE bool DL_GPAMP_isNonInvertingInputChannelEnabled (void)
Checks if the non-inverting input channel is enabled.
__STATIC_INLINE void DL_GPAMP_disableNonInvertingInputChannel (void)
Disable the non-inverting input channel.
__STATIC_INLINE void DL_GPAMP_setInvertingInputChannel (DL_GPAMP_NSEL inputChannel)
Set the inverting input channel.
__STATIC_INLINE DL_GPAMP_NSEL DL_GPAMP_getInvertingInputChannel (void)
Get the inverting input channel.
__STATIC_INLINE void DL_GPAMP_setRailToRailInputMode (DL_GPAMP_RRI_MODE mode)
Set the rail-to-rail input (RRI) mode.
__STATIC_INLINE DL_GPAMP_RRI_MODE DL_GPAMP_getRailToRailInputMode (void)
Get the rail-to-rail input (RRI) mode.
__STATIC_INLINE void DL_GPAMP_enableOutputToPad (void)
Enable output to pad.
__STATIC_INLINE bool DL_GPAMP_isOutputToPadEnabled (void)
Checks if output to pad is enabled.
__STATIC_INLINE void DL_GPAMP_disableOutputToPad (void)
Disable output to pad.
__STATIC_INLINE void DL_GPAMP_setChoppingFrequency (DL_GPAMP_CHOPPING_FREQ frequency)
Set the chopping clock frequency.
__STATIC_INLINE DL_GPAMP_CHOPPING_FREQ DL_GPAMP_getChoppingFrequency (void)
Get the chopping clock frequency.
__STATIC_INLINE void DL_GPAMP_setChoppingMode (DL_GPAMP_CHOPPING_MODE mode)
Set the chopping mode.
__STATIC_INLINE DL_GPAMP_CHOPPING_MODE DL_GPAMP_getChoppingMode (void)
Get the chopping mode.
Detailed Description
Enumeration Type Documentation
DL_GPAMP_NSEL
enum DL_GPAMP_NSEL
Enumerator
DL_GPAMP_NSEL_OUTPUT_PIN
Inverting input channel is the output pin
DL_GPAMP_NSEL_IN_NEG
Inverting input channel is the IN- pin
DL_GPAMP_NSEL_INTERNAL_OUTPUT
Inverting input channel is internal GPAMP output
DL_GPAMP_NSEL_OPEN
No channel selected for the inverting input channel
DL_GPAMP_PSEL
enum DL_GPAMP_PSEL
Enumerator
DL_GPAMP_PSEL_OPEN
Non-Inverting input channel is disabled
DL_GPAMP_PSEL_IN_POS
Non-Inverting input channel is enabled
DL_GPAMP_OUTPUT_PIN_STATE
enum DL_GPAMP_OUTPUT_PIN_STATE
Enumerator
DL_GPAMP_OUTPUT_PIN_STATE_DISABLED
Output pin is disabled
DL_GPAMP_OUTPUT_PIN_STATE_ENABLED
Output pin is enabled
DL_GPAMP_RRI_MODE
enum DL_GPAMP_RRI_MODE
Enumerator
DL_GPAMP_RRI_MODE_PMOS_INPUT
RRI mode is PMOS input pairs mode
DL_GPAMP_RRI_MODE_NMOS_INPUT
RRI mode is NMOS input pairs
DL_GPAMP_RRI_MODE_RAIL_TO_RAIL
RRI mode is rail to rail
DL_GPAMP_RRI_MODE_SAMPLE_CHANNEL_0
RRI mode is sample channel 0
DL_GPAMP_CHOPPING_FREQ
enum DL_GPAMP_CHOPPING_FREQ
Enumerator
DL_GPAMP_CHOPPING_FREQ_16KHZ
Chopping clock frequency is 16KHZ
DL_GPAMP_CHOPPING_FREQ_8KHZ
Chopping clock frequency is 8KHZ
DL_GPAMP_CHOPPING_FREQ_4KHZ
Chopping clock frequency is 4KHZ
DL_GPAMP_CHOPPING_FREQ_2KHZ
Chopping clock frequency is 2KHZ
DL_GPAMP_CHOPPING_MODE
enum DL_GPAMP_CHOPPING_MODE
Enumerator
DL_GPAMP_CHOPPING_MODE_DISABLED
Chopping is disabled
DL_GPAMP_CHOPPING_MODE_STANDARD
Chopping mode is standard chop
DL_GPAMP_CHOPPING_MODE_ADC_ASSISTED
Chopping mode is ADC assisted chop
Function Documentation
DL_GPAMP_isEnabled()
__STATIC_INLINE bool DL_GPAMP_isEnabled (void)
Checks if the GPAMP peripheral is enabled.
Returns
Returns the enabled status of the GPAMP
Return values
true The GPAMP peripheral is enabled
false The GPAMP peripheral is disabled
DL_GPAMP_init()
__STATIC_INLINE void DL_GPAMP_init (DL_GPAMP_Config * config)
Initialize the GPAmp peripheral.
Initializes all the common configurable options for the GPAmp peripheral. Any other custom configuration can be done after calling this API. The GPAmp is not enabled in this API.
Parameters
[in] config Configuration for gpamp peripheral
References DL_GPAMP_Config::choppingFreq, DL_GPAMP_Config::choppingMode, DL_Common_updateReg(), DL_GPAMP_Config::nselChannel, DL_GPAMP_Config::outputPinState, and DL_GPAMP_Config::pselChannel.
DL_GPAMP_isNonInvertingInputChannelEnabled()
__STATIC_INLINE bool DL_GPAMP_isNonInvertingInputChannelEnabled (void)
Checks if the non-inverting input channel is enabled.
Returns
Returns the enabled status of the GPAMP
Return values
true The non-inverting input channel is enabled
false The non-inverting input channel is disabled
DL_GPAMP_setInvertingInputChannel()
__STATIC_INLINE void DL_GPAMP_setInvertingInputChannel (DL_GPAMP_NSEL inputChannel)
Set the inverting input channel.
Parameters
[in] inputChannel The inverting input channel to set. One of DL_GPAMP_NSEL.
References DL_Common_updateReg().
DL_GPAMP_getInvertingInputChannel()
__STATIC_INLINE DL_GPAMP_NSEL DL_GPAMP_getInvertingInputChannel (void)
Get the inverting input channel.
Returns
The current inverting input channel
Return values
One of DL_GPAMP_NSEL
DL_GPAMP_setRailToRailInputMode()
__STATIC_INLINE void DL_GPAMP_setRailToRailInputMode (DL_GPAMP_RRI_MODE mode)
Set the rail-to-rail input (RRI) mode.
Parameters
[in] mode The RRI mode to set. One of DL_GPAMP_RRI_MODE.
References DL_Common_updateReg().
DL_GPAMP_getRailToRailInputMode()
__STATIC_INLINE DL_GPAMP_RRI_MODE DL_GPAMP_getRailToRailInputMode (void)
Get the rail-to-rail input (RRI) mode.
Returns
The current RRI mode
Return values
One of DL_GPAMP_RRI_MODE
DL_GPAMP_isOutputToPadEnabled()
__STATIC_INLINE bool DL_GPAMP_isOutputToPadEnabled (void)
Checks if output to pad is enabled.
Returns
Returns if output to pad is enabled
Return values
true Output to pad is enabled
false Output to pad is disabled
DL_GPAMP_setChoppingFrequency()
__STATIC_INLINE void DL_GPAMP_setChoppingFrequency (DL_GPAMP_CHOPPING_FREQ frequency)
Set the chopping clock frequency.
Parameters
[in] frequency The chopping frequency to set. One of DL_GPAMP_CHOPPING_FREQ
References DL_Common_updateReg().
DL_GPAMP_getChoppingFrequency()
__STATIC_INLINE DL_GPAMP_CHOPPING_FREQ DL_GPAMP_getChoppingFrequency (void)
Get the chopping clock frequency.
Returns
The current chopping frequency
Return values
One of DL_GPAMP_CHOPPING_FREQ
DL_GPAMP_setChoppingMode()
__STATIC_INLINE void DL_GPAMP_setChoppingMode (DL_GPAMP_CHOPPING_MODE mode)
Set the chopping mode.
Parameters
[in] mode The chopping mode to set. One of DL_GPAMP_CHOPPING_MODE
References DL_Common_updateReg().
DL_GPAMP_getChoppingMode()
__STATIC_INLINE DL_GPAMP_CHOPPING_MODE DL_GPAMP_getChoppingMode (void)
Get the chopping mode.
Returns
The current chopping mode
Return values
One of DL_GPAMP_CHOPPING_MODE
© Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale