StepperMotorControlLibrary: Motor_Driver/DRV8889Q1
Motor_Driver/DRV8889Q1
Data Structures
struct DRV8889Q1_Instance
Define drv8889-q1 structure.
Macros
#define DRV8889Q1_SPI_READY_DELAY_MS (1)
Delay to wait for the SPI to be ready when the DRV is powered on.
#define DRV8889Q1_STEP_DUTYCYCLE (50)
Step pin Dutycycle in percentage.
#define DRV8889Q1_MAX_SET_FREQ (300000)
Max Timer frequency limit.
#define DRV8889Q1_REG_FAULT_STATUS_FAULT_OFS (7)
Defines the offset for fault bit.
#define DRV8889Q1_REG_FAULT_STATUS_SPI_ERROR_OFS (6)
Defines the offset for spi error bit.
#define DRV8889Q1_REG_FAULT_STATUS_UVLO_OFS (5)
Defines the offset for under voltage fault bit.
#define DRV8889Q1_REG_FAULT_STATUS_CPUV_OFS (4)
Defines the offset for charge pump under voltage fault bit.
#define DRV8889Q1_REG_FAULT_STATUS_OCP_OFS (3)
Defines the offset for over current fault bit.
#define DRV8889Q1_REG_FAULT_STATUS_STL_OFS (2)
Defines the offset for motor stall fault bit.
#define DRV8889Q1_REG_FAULT_STATUS_TF_OFS (1)
Defines the offset for over temperature warning or under temperature warning or over temperature shutdown fault bit.
#define DRV8889Q1_REG_FAULT_STATUS_OL_OFS (0)
Defines the offset for open load fault bit.
#define DRV8889Q1_REG_FAULT_STATUS_FAULT_MASK (1<<DRV8889Q1_REG_FAULT_STATUS_FAULT_OFS)
Defines the offset for fault bit.
#define DRV8889Q1_REG_FAULT_STATUS_SPI_ERROR_MASK (1<<DRV8889Q1_REG_FAULT_STATUS_SPI_ERROR_OFS)
Defines the mask for spi error bit.
#define DRV8889Q1_REG_FAULT_STATUS_UVLO_MASK (1<<DRV8889Q1_REG_FAULT_STATUS_UVLO_OFS)
Defines the mask for under voltage fault bit.
#define DRV8889Q1_REG_FAULT_STATUS_CPUV_MASK (1<<DRV8889Q1_REG_FAULT_STATUS_CPUV_OFS)
Defines the mask for Charge pump under voltage fault bit.
#define DRV8889Q1_REG_FAULT_STATUS_OCP_MASK (1<<DRV8889Q1_REG_FAULT_STATUS_OCP_OFS)
Defines the mask for over current fault bit.
#define DRV8889Q1_REG_FAULT_STATUS_STL_MASK (1<<DRV8889Q1_REG_FAULT_STATUS_STL_OFS)
Defines the mask for motor stall fault bit.
#define DRV8889Q1_REG_FAULT_STATUS_TF_MASK (1<<DRV8889Q1_REG_FAULT_STATUS_TF_OFS)
Defines the mask for over temperature warning or under temperature warning or over temperature shutdown fault bit.
#define DRV8889Q1_REG_FAULT_STATUS_OL_MASK (1<<DRV8889Q1_REG_FAULT_STATUS_OL_OFS)
Defines the mask for open load bit.
#define DRV8889Q1_REG_DIAG_STATUS_1_OCP_LS2_B_OFS (7)
Defines the offset for overcurrent fault on the low-side FET of half bridge 2 in BOUT.
#define DRV8889Q1_REG_DIAG_STATUS_1_OCP_HS2_B_OFS (6)
Defines the offset for overcurrent fault on the high-side FET of half bridge 2 in BOUT.
#define DRV8889Q1_REG_DIAG_STATUS_1_OCP_LS1_B_OFS (5)
Defines the offset for overcurrent fault on the low-side FET of half bridge 1 in BOUT.
#define DRV8889Q1_REG_DIAG_STATUS_1_OCP_HS1_B_OFS (4)
Defines the offset for overcurrent fault on the high-side FET of half bridge 1 in BOUT.
#define DRV8889Q1_REG_DIAG_STATUS_1_OCP_LS2_A_OFS (3)
Defines the offset for overcurrent fault on the low-side FET of half bridge 2 in AOUT.
#define DRV8889Q1_REG_DIAG_STATUS_1_OCP_HS2_A_OFS (2)
Defines the offset for overcurrent fault on the high-side FET of half bridge 2 in AOUT.
#define DRV8889Q1_REG_DIAG_STATUS_1_OCP_LS1_A_OFS (1)
Defines the offset for overcurrent fault on the low-side FET of half bridge 1 in AOUT.
#define DRV8889Q1_REG_DIAG_STATUS_1_OCP_HS1_A_OFS (0)
Defines the offset for overcurrent fault on the high-side FET of half bridge 1 in AOUT.
#define DRV8889Q1_REG_DIAG_STATUS_1_OCP_LS2_B_MASK (1<<DRV8889Q1_REG_DIAG_STATUS_1_OCP_LS2_B_OFS)
Defines the mask for overcurrent fault on the low-side FET of half bridge 2 in BOUT.
#define DRV8889Q1_REG_DIAG_STATUS_1_OCP_HS2_B_MASK (1<<DRV8889Q1_REG_DIAG_STATUS_1_OCP_HS2_B_OFS)
Defines the mask for overcurrent fault on the high-side FET of half bridge 2 in BOUT.
#define DRV8889Q1_REG_DIAG_STATUS_1_OCP_LS1_B_MASK (1<<DRV8889Q1_REG_DIAG_STATUS_1_OCP_LS1_B_OFS)
Defines the mask for overcurrent fault on the low-side FET of half bridge 1 in BOUT.
#define DRV8889Q1_REG_DIAG_STATUS_1_OCP_HS1_B_MASK (1<<DRV8889Q1_REG_DIAG_STATUS_1_OCP_HS1_B_OFS)
Defines the mask for overcurrent fault on the high-side FET of half bridge 1 in BOUT.
#define DRV8889Q1_REG_DIAG_STATUS_1_OCP_LS2_A_MASK (1<<DRV8889Q1_REG_DIAG_STATUS_1_OCP_LS2_A_OFS)
Defines the mask for overcurrent fault on the low-side FET of half bridge 2 in AOUT.
#define DRV8889Q1_REG_DIAG_STATUS_1_OCP_HS2_A_MASK (1<<DRV8889Q1_REG_DIAG_STATUS_1_OCP_HS2_A_OFS)
Defines the mask for overcurrent fault on the high-side FET of half bridge 2 in AOUT.
#define DRV8889Q1_REG_DIAG_STATUS_1_OCP_LS1_A_MASK (1<<DRV8889Q1_REG_DIAG_STATUS_1_OCP_LS1_A_OFS)
Defines the mask for overcurrent fault on the low-side FET of half bridge 1 in AOUT.
#define DRV8889Q1_REG_DIAG_STATUS_1_OCP_HS1_A_MASK (1<<DRV8889Q1_REG_DIAG_STATUS_1_OCP_HS1_A_OFS)
Defines the mask for overcurrent fault on the high-side FET of half bridge 1 in AOUT.
#define DRV8889Q1_REG_DIAG_STATUS_2_UTW_OFS (7)
Defines the offset for undertemperature warning bit.
#define DRV8889Q1_REG_DIAG_STATUS_2_OTW_OFS (6)
Defines the offset for overtemperature warning bit.
#define DRV8889Q1_REG_DIAG_STATUS_2_OTS_OFS (5)
Defines the offset for overtemperature shutdown bit.
#define DRV8889Q1_REG_DIAG_STATUS_2_STL_LRN_OK_OFS (4)
Defines the offset for stall learning is successful bit.
#define DRV8889Q1_REG_DIAG_STATUS_2_STALL_OFS (3)
Defines the offset for motor stall condition bit.
#define DRV8889Q1_REG_DIAG_STATUS_2_OL_B_OFS (1)
Defines the offset for open load detection on BOUT.
#define DRV8889Q1_REG_DIAG_STATUS_2_OL_A_OFS (0)
Defines the offset for open load detection on AOUT.
#define DRV8889Q1_REG_DIAG_STATUS_2_UTW_MASK (1<<DRV8889Q1_REG_DIAG_STATUS_2_UTW_OFS)
Defines the mask for undertemperature warning bit.
#define DRV8889Q1_REG_DIAG_STATUS_2_OTW_MASK (1<<DRV8889Q1_REG_DIAG_STATUS_2_OTW_OFS)
Defines the mask for overtemperature warning bit.
#define DRV8889Q1_REG_DIAG_STATUS_2_OTS_MASK (1<<DRV8889Q1_REG_DIAG_STATUS_2_OTS_OFS)
Defines the mask for overtemperature shutdown bit.
#define DRV8889Q1_REG_DIAG_STATUS_2_STL_LRN_OK_MASK (1<<DRV8889Q1_REG_DIAG_STATUS_2_STL_LRN_OK_OFS)
Defines the mask for stall learning is successful bit.
#define DRV8889Q1_REG_DIAG_STATUS_2_STALL_MASK (1<<DRV8889Q1_REG_DIAG_STATUS_2_STALL_OFS)
Defines the mask for motor stall condition bit.
#define DRV8889Q1_REG_DIAG_STATUS_2_OL_B_MASK (1<<DRV8889Q1_REG_DIAG_STATUS_2_OL_B_OFS)
Defines the mask for open load detection on BOUT.
#define DRV8889Q1_REG_DIAG_STATUS_2_OL_A_MASK (1<<DRV8889Q1_REG_DIAG_STATUS_2_OL_A_OFS)
Defines the mask for open load detection on AOUT.
#define DRV8889Q1_REG_CTRL1_TRQ_DAC_OFS (4)
Defines the offset for TRQ DAC bit.
#define DRV8889Q1_REG_CTRL1_SLEW_RATE_OFS (0)
Defines the offset for slew rate selection bit.
#define DRV8889Q1_REG_CTRL1_TRQ_DAC_MASK (15<<DRV8889Q1_REG_CTRL1_TRQ_DAC_OFS)
Defines the mask for TRQ DAC bit.
#define DRV8889Q1_REG_CTRL1_SLEW_RATE_MASK (3<<DRV8889Q1_REG_CTRL1_SLEW_RATE_OFS)
Defines the mask for slew rate selection bit.
#define DRV8889Q1_REG_CTRL2_DIS_OUT_OFS (7)
Defines the offset output disable bit.
#define DRV8889Q1_REG_CTRL2_TOFF_OFS (3)
Defines the offset TOFF selection bit.
#define DRV8889Q1_REG_CTRL2_DECAY_OFS (0)
Defines the offset for decay selection bit.
#define DRV8889Q1_REG_CTRL2_DIS_OUT_MASK (1<<DRV8889Q1_REG_CTRL2_DIS_OUT_OFS)
Defines the mask output disable bit.
#define DRV8889Q1_REG_CTRL2_TOFF_MASK (3<<DRV8889Q1_REG_CTRL2_TOFF_OFS)
Defines the mask TOFF selection bit.
#define DRV8889Q1_REG_CTRL2_DECAY_MASK (7<<DRV8889Q1_REG_CTRL2_DECAY_OFS)
Defines the mask for decay selection bit.
#define DRV8889Q1_REG_CTRL3_DIR_OFS (7)
Defines the offset for direction input bit.
#define DRV8889Q1_REG_CTRL3_STEP_OFS (6)
Defines the offset for step input bit.
#define DRV8889Q1_REG_CTRL3_SPI_DIR_OFS (5)
Defines the offset for direction input selection bit.
#define DRV8889Q1_REG_CTRL3_SPI_STEP_OFS (4)
Defines the offset for step input selection bit.
#define DRV8889Q1_REG_CTRL3_MICROSTEP_MODE_OFS (0)
Defines the offset for microstep mode selection bit.
#define DRV8889Q1_REG_CTRL3_DIR_MASK (1<<DRV8889Q1_REG_CTRL3_DIR_OFS)
Defines the mask for direction input bit.
#define DRV8889Q1_REG_CTRL3_STEP_MAS (1<<DRV8889Q1_REG_CTRL3_STEP_OFS)
Defines the mask for step input bit.
#define DRV8889Q1_REG_CTRL3_SPI_DIR_MASK (1<<DRV8889Q1_REG_CTRL3_SPI_DIR_OFS)
Defines the mask for direction input selection bit.
#define DRV8889Q1_REG_CTRL3_SPI_STEP_MASK (1<<DRV8889Q1_REG_CTRL3_SPI_STEP_OFS)
Defines the mask for step input selection bit.
#define DRV8889Q1_REG_CTRL3_MICROSTEP_MODE_MASK (15<<DRV8889Q1_REG_CTRL3_MICROSTEP_MODE_OFS)
Defines the mask for microstep mode selection bit.
#define DRV8889Q1_REG_CTRL4_CLR_FLT_OFS (7)
Defines the offset for clear fault bit.
#define DRV8889Q1_REG_CTRL4_LOCK_OFS (4)
Defines the offset for lock settings bit.
#define DRV8889Q1_REG_CTRL4_EN_OL_OFS (3)
Defines the offset for enable open load bit.
#define DRV8889Q1_REG_CTRL4_OCP_MODE_OFS (2)
Defines the offset for overcurrent mode selection bit.
#define DRV8889Q1_REG_CTRL4_OTSD_MODE_OFS (1)
Defines the offset for overtemperature mode selection bit.
#define DRV8889Q1_REG_CTRL4_TW_REP_OFS (0)
Defines the offset for over or under temperature reporting selection bit.
#define DRV8889Q1_REG_CTRL4_CLR_FLT_MASK (1<<DRV8889Q1_REG_CTRL4_CLR_FLT_OFS)
Defines the mask for clear fault bit.
#define DRV8889Q1_REG_CTRL4_LOCK_MASK (7<<DRV8889Q1_REG_CTRL4_LOCK_OFS)
Defines the mask for lock settings bit.
#define DRV8889Q1_REG_CTRL4_EN_OL_MASK (1<<DRV8889Q1_REG_CTRL4_EN_OL_OFS)
Defines the mask for enable open load bit.
#define DRV8889Q1_REG_CTRL4_OCP_MODE_MASK (1<<DRV8889Q1_REG_CTRL4_OCP_MODE_OFS)
Defines the mask for overcurrent mode selection bit.
#define DRV8889Q1_REG_CTRL4_OTSD_MODE_MASK (1<<DRV8889Q1_REG_CTRL4_OTSD_MODE_OFS)
Defines the mask for overtemperature mode selection bit.
#define DRV8889Q1_REG_CTRL4_TW_REP_MASK (1<<DRV8889Q1_REG_CTRL4_TW_REP_OFS)
Defines the mask for over or under temperature reporting selection bit.
#define DRV8889Q1_REG_CTRL5_STL_LRN_OFS (5)
Defines the offset for stall learn bit.
#define DRV8889Q1_REG_CTRL5_EN_STL_OFS (4)
Defines the offset for enable stall detection bit.
#define DRV8889Q1_REG_CTRL5_STL_REP_OFS (3)
Defines the offset for stall detection reporting selection bit.
#define DRV8889Q1_REG_CTRL5_STL_LRN_MASK (1<<DRV8889Q1_REG_CTRL5_STL_LRN_OFS)
Defines the mask for stall learn bit.
#define DRV8889Q1_REG_CTRL5_EN_STL_MASK (1<<DRV8889Q1_REG_CTRL5_EN_STL_OFS)
Defines the mask for enable stall detection bit.
#define DRV8889Q1_REG_CTRL5_STL_REP_MASK (1<<DRV8889Q1_REG_CTRL5_STL_REP_OFS)
Defines the mask for stall detection reporting selection bit.
#define DRV8889Q1_REG_CTRL6_STALL_TH_OFS (0)
Defines the offset for stall threshold bit.
#define DRV8889Q1_REG_CTRL6_STALL_TH_MASK (0xFF<<DRV8889Q1_REG_CTRL6_STALL_TH_OFS)
Defines the mask for stall threshold bit.
#define DRV8889Q1_REG_CTRL7_TRQ_COUNT_OFS (0)
Defines the offset for TRQ COUNT bit.
#define DRV8889Q1_REG_CTRL7_TRQ_COUNT_MASK (0xFF<<DRV8889Q1_REG_CTRL7_TRQ_COUNT_OFS)
Defines the mask for TRQ COUNT bit.
#define DRV8889Q1_REG_CTRL8_REV_ID_OFS (0)
Defines the offset for silicon revision identification bit.
#define DRV8889Q1_REG_CTRL8_REV_ID_MASK (15<<DRV8889Q1_REG_CTRL8_REV_ID_OFS)
Defines the mask for silicon revision identification bit.
#define DRV8889Q1_SPI_CMD_OFS (14)
Defines the offset for SPI command bit.
#define DRV8889Q1_SPI_ADDR_OFS (9)
Defines the offset for SPI register address.
#define DRV8889Q1_SPI_ADDR_MASK (0xFF<<DRV8889Q1_SPI_ADDR_OFS)
Defines the offset for SPI register address.
#define DRV8889Q1_STALL_LEARN_EL_CYCLES (16)
Number of Electrical cycles for stall auto learning.
Enumerations
enum DRV8889Q1_REG_ADDR {
DRV8889Q1_REG_ADDR_FAULT_STATUS = 0,
DRV8889Q1_REG_ADDR_DIAG_STATUS_1,
DRV8889Q1_REG_ADDR_DIAG_STATUS_2,
DRV8889Q1_REG_ADDR_CTRL1,
DRV8889Q1_REG_ADDR_CTRL2,
DRV8889Q1_REG_ADDR_CTRL3,
DRV8889Q1_REG_ADDR_CTRL4,
DRV8889Q1_REG_ADDR_CTRL5,
DRV8889Q1_REG_ADDR_CTRL6,
DRV8889Q1_REG_ADDR_CTRL7,
DRV8889Q1_REG_ADDR_CTRL8,
DRV8889Q1_REG_ADDR_CTRL9
}
enum DRV8889Q1_SPI_CMD {
DRV8889Q1_SPI_CMD_WRITE = 0,
DRV8889Q1_SPI_CMD_READ
}
enum DRV8889Q1_REG_CTRL4_LOCK {
DRV8889Q1_REG_CTRL4_LOCK_UNLOCK = 3,
DRV8889Q1_REG_CTRL4_LOCK_LOCK = 6
}
enum DRV8889Q1_DIR {
DRV8889Q1_DIR_REVERSE = 0,
DRV8889Q1_DIR_FORWARD
}
enum DRV8889Q1_STEP {
DRV8889Q1_STEP_FULL_STEP = 0,
DRV8889Q1_STEP_FULL_STEP_71,
DRV8889Q1_STEP_NC_HALF_STEP,
DRV8889Q1_STEP_HALF_STEP,
DRV8889Q1_STEP_1BY4_STEP,
DRV8889Q1_STEP_1BY8_STEP,
DRV8889Q1_STEP_1BY16_STEP,
DRV8889Q1_STEP_1BY32_STEP,
DRV8889Q1_STEP_1BY64_STEP,
DRV8889Q1_STEP_1BY128_STEP,
DRV8889Q1_STEP_1BY256_STEP
}
enum DRV8889Q1_SLEW_RATE {
DRV8889Q1_SLEW_RATE_10VUS = 0,
DRV8889Q1_SLEW_RATE_35VUS,
DRV8889Q1_SLEW_RATE_50VUS,
DRV8889Q1_SLEW_RATE_105VUS
}
enum DRV8889Q1_DECAY {
DRV8889Q1_DECAY_INC_SLOW_DEC_SLOW = 0,
DRV8889Q1_DECAY_INC_SLOW_DEC_MIXED_30,
DRV8889Q1_DECAY_INC_SLOW_DEC_MIXED_60,
DRV8889Q1_DECAY_INC_SLOW_DEC_FAST,
DRV8889Q1_DECAY_INC_MIXED_30_DEC_MIXED_30,
DRV8889Q1_DECAY_INC_MIXED_60_DEC_MIXED_60,
DRV8889Q1_DECAY_SMART_TUNE_DYNAMIC,
DRV8889Q1_DECAY_SMART_TUNE_RIPPLE_CTRL
}
enum DRV8889Q1_TRQ_DAC {
DRV8889Q1_TRQ_DAC_100 = 0,
DRV8889Q1_TRQ_DAC_93P75,
DRV8889Q1_TRQ_DAC_87P5,
DRV8889Q1_TRQ_DAC_81P25,
DRV8889Q1_TRQ_DAC_75,
DRV8889Q1_TRQ_DAC_68P75,
DRV8889Q1_TRQ_DAC_62P5,
DRV8889Q1_TRQ_DAC_56P25,
DRV8889Q1_TRQ_DAC_50,
DRV8889Q1_TRQ_DAC_43P75,
DRV8889Q1_TRQ_DAC_37P5,
DRV8889Q1_TRQ_DAC_31P25,
DRV8889Q1_TRQ_DAC_25,
DRV8889Q1_TRQ_DAC_18P75,
DRV8889Q1_TRQ_DAC_12P5,
DRV8889Q1_TRQ_DAC_6P25
}
enum DRV8889Q1_TOFF {
DRV8889Q1_TOFF_7US = 0,
DRV8889Q1_TOFF_16US,
DRV8889Q1_TOFF_24US,
DRV8889Q1_TOFF_32US
}
enum DRV8889Q1_CONTROL_MODE {
DRV8889Q1_CONTROL_MODE_SPIN = 0,
DRV8889Q1_CONTROL_MODE_STEP
}
enum DRV8889Q1_DRIVE {
DRV8889Q1_DRIVE_DISABLED = 0,
DRV8889Q1_DRIVE_PWM
}
Functions
void DRV8889Q1_init (DRV8889Q1_Instance *handle)
Enables the necessary interrupts.
uint16_t DRV8889Q1_createSPIDataWord (DRV8889Q1_SPI_CMD wrCmd, DRV8889Q1_REG_ADDR addr, uint8_t data)
Creates a data word to be send through SPI.
void DRV8889Q1_spiWrite (DRV8889Q1_Instance *handle, DRV8889Q1_REG_ADDR addr, uint8_t data)
Writes the data to the SPI register.
uint8_t DRV8889Q1_spiRead (DRV8889Q1_Instance *handle, DRV8889Q1_REG_ADDR addr)
Reads the data in the SPI register.
void DRV8889Q1_spiUpdateRegister (DRV8889Q1_Instance *handle, DRV8889Q1_REG_ADDR addr, uint32_t mask, uint8_t data)
Update only some bits in the SPI register.
void DRV8889Q1_setSPIRegisterLock (DRV8889Q1_Instance *handle, DRV8889Q1_REG_CTRL4_LOCK lock)
Unlock or lock settings of the DRV.
void DRV8889Q1_setDirection (DRV8889Q1_Instance *handle, DRV8889Q1_DIR dir)
Sets the direction of motor.
void DRV8889Q1_setStepMode (DRV8889Q1_Instance *handle, DRV8889Q1_STEP stepMode)
Sets the step mode.
void DRV8889Q1_setDecayMode (DRV8889Q1_Instance *handle, DRV8889Q1_DECAY decayMode)
Sets the decay mode.
void DRV8889Q1_setSpeed (DRV8889Q1_Instance *handle, uint32_t timFreq)
Sets the motor speed by setting the timer frequency.
void DRV8889Q1_setFSCurr (DRV8889Q1_Instance *handle, _iq15 fsCurr)
Sets full scale current.
void DRV8889Q1_setSlewRate (DRV8889Q1_Instance *handle, DRV8889Q1_SLEW_RATE slewRate)
Sets Slew rate.
void DRV8889Q1_setNSleep (DRV8889Q1_Instance *handle)
Sets DRV to awake.
void DRV8889Q1_clearNSleep (DRV8889Q1_Instance *handle)
Sets DRV to sleep.
void DRV8889Q1_enableOutput (DRV8889Q1_Instance *handle)
Enables the drv driver output.
void DRV8889Q1_disableOutput (DRV8889Q1_Instance *handle)
Disables the drv driver output.
void DRV8889Q1_startMotor (DRV8889Q1_Instance *handle)
Starts the motor.
void DRV8889Q1_stopMotor (DRV8889Q1_Instance *handle)
Stops the motor.
bool DRV8889Q1_isMotorRunning (DRV8889Q1_Instance *handle)
Checks if the motor is currently running.
bool DRV8889Q1_isFaultOccurred (DRV8889Q1_Instance *handle)
Gets if any fault occurred at the instant.
void DRV8889Q1_setControlMode (DRV8889Q1_Instance *handle, DRV8889Q1_CONTROL_MODE ctrl_mode)
Sets the control mode.
void DRV8889Q1_checkStep (DRV8889Q1_Instance *handle)
Checks if motor has moved the required steps in step mode.
void DRV8889Q1_setStepDuty (DRV8889Q1_Instance *handle)
Sets the step duty cycle specified in DRV8889Q1_STEP_DUTYCYCLE.
void DRV8889Q1_setStepDrive (DRV8889Q1_Instance *handle, DRV8889Q1_DRIVE drive)
Sets the step drive state.
void DRV8889Q1_setStep (DRV8889Q1_Instance *handle, uint16_t setSteps)
Sets the steps to move in step mode.
void DRV8889Q1_setTrqDac (DRV8889Q1_Instance *handle, DRV8889Q1_TRQ_DAC trqDac)
Sets TRQ DAC value. Used to scale the full scale current.
void DRV8889Q1_setToff (DRV8889Q1_Instance *handle, DRV8889Q1_TOFF toff)
Sets toff value.
void DRV8889Q1_clearFaults (DRV8889Q1_Instance *handle)
Clears the SPI fault status registers.
uint8_t DRV8889Q1_getStallThres (DRV8889Q1_Instance *handle)
Gets the stall threshold value from spi register.
void DRV8889Q1_setStallThres (DRV8889Q1_Instance *handle, uint8_t stallThres)
Set the stall threshold value in spi register.
uint8_t DRV8889Q1_getTrqCount (DRV8889Q1_Instance *handle)
Gets the trq count.
void DRV8889Q1_enableStallDet (DRV8889Q1_Instance *handle)
Enables the stall detection.
void DRV8889Q1_disableStallDet (DRV8889Q1_Instance *handle)
Disables the stall detection.
void DRV8889Q1_enableOlDet (DRV8889Q1_Instance *handle)
Enables the open load detection.
void DRV8889Q1_disableOlDet (DRV8889Q1_Instance *handle)
Disables the open load detection.
void DRV8889Q1_setLearnStall (DRV8889Q1_Instance *handle)
Starts auto stall learning.
bool DRV8889Q1_isStallLearnSuccess (DRV8889Q1_Instance *handle)
Checks if auto stall learning is completed successfully.
void DRV8889Q1_setVrefRefVoltage (DRV8889Q1_Instance *handle, _iq15 refVoltage)
Sets the reference voltage for the vref output.
Detailed Description
Enumeration Type Documentation
DRV8889Q1_REG_ADDR
enum DRV8889Q1_REG_ADDR
DRV8889Q1_SPI_CMD
enum DRV8889Q1_SPI_CMD
DRV8889Q1_REG_CTRL4_LOCK
enum DRV8889Q1_REG_CTRL4_LOCK
Enumerator
DRV8889Q1_REG_CTRL4_LOCK_UNLOCK
Unlock value
DRV8889Q1_REG_CTRL4_LOCK_LOCK
Lock value
DRV8889Q1_DIR
enum DRV8889Q1_DIR
Enumerator
DRV8889Q1_DIR_REVERSE
Reverse direction
DRV8889Q1_DIR_FORWARD
Forward direction
DRV8889Q1_STEP
enum DRV8889Q1_STEP
Enumerator
DRV8889Q1_STEP_FULL_STEP
Full step mode 100% current
DRV8889Q1_STEP_FULL_STEP_71
Full step mode 71% current
DRV8889Q1_STEP_NC_HALF_STEP
Half step mode non circular
DRV8889Q1_STEP_HALF_STEP
half step mode circular
DRV8889Q1_STEP_1BY4_STEP
1 by 4 step mode
DRV8889Q1_STEP_1BY8_STEP
1 by 8 step mode
DRV8889Q1_STEP_1BY16_STEP
1 by 16 step mode
DRV8889Q1_STEP_1BY32_STEP
1 by 32 step mode
DRV8889Q1_STEP_1BY64_STEP
1 by 64 step mode
DRV8889Q1_STEP_1BY128_STEP
1 by 128 step mode
DRV8889Q1_STEP_1BY256_STEP
1 by 256 step mode
DRV8889Q1_SLEW_RATE
enum DRV8889Q1_SLEW_RATE
Enumerator
DRV8889Q1_SLEW_RATE_10VUS
Set 10V/us slew rate
DRV8889Q1_SLEW_RATE_35VUS
Set 35V/us slew rate
DRV8889Q1_SLEW_RATE_50VUS
Set 50V/us slew rate
DRV8889Q1_SLEW_RATE_105VUS
Set 105V/us slew rate
DRV8889Q1_DECAY
enum DRV8889Q1_DECAY
Enumerator
DRV8889Q1_DECAY_INC_SLOW_DEC_SLOW
Set Slow decay in increasing steps and slow decay in decreasing steps
DRV8889Q1_DECAY_INC_SLOW_DEC_MIXED_30
Set Slow decay in increasing steps and mixed 30% fast decay in decreasing steps
DRV8889Q1_DECAY_INC_SLOW_DEC_MIXED_60
Set Slow decay in increasing steps and mixed 60% fast decay in decreasing steps
DRV8889Q1_DECAY_INC_SLOW_DEC_FAST
Set Slow decay in increasing steps and fast decay in decreasing steps
DRV8889Q1_DECAY_INC_MIXED_30_DEC_MIXED_30
Set mixed 30% fast decay in increasing steps and mixed 60% fast decay in decreasing steps
DRV8889Q1_DECAY_INC_MIXED_60_DEC_MIXED_60
Set mixed 60% fast decay in increasing steps and mixed 60% fast decay in decreasing steps
DRV8889Q1_DECAY_SMART_TUNE_DYNAMIC
Set smart tune dynamic decay
DRV8889Q1_DECAY_SMART_TUNE_RIPPLE_CTRL
Set smart tune ripple control decay
DRV8889Q1_TRQ_DAC
enum DRV8889Q1_TRQ_DAC
Enumerator
DRV8889Q1_TRQ_DAC_100
100% Full scale current
DRV8889Q1_TRQ_DAC_93P75
93.75% Full scale current
DRV8889Q1_TRQ_DAC_87P5
87.5% Full scale current
DRV8889Q1_TRQ_DAC_81P25
81.25% Full scale current
DRV8889Q1_TRQ_DAC_75
75% Full scale current
DRV8889Q1_TRQ_DAC_68P75
68.75% Full scale current
DRV8889Q1_TRQ_DAC_62P5
62.5% Full scale current
DRV8889Q1_TRQ_DAC_56P25
56.25% Full scale current
DRV8889Q1_TRQ_DAC_50
50% Full scale current
DRV8889Q1_TRQ_DAC_43P75
43.75% Full scale current
DRV8889Q1_TRQ_DAC_37P5
37.5% Full scale current
DRV8889Q1_TRQ_DAC_31P25
31.25% Full scale current
DRV8889Q1_TRQ_DAC_25
25% Full scale current
DRV8889Q1_TRQ_DAC_18P75
18.75% Full scale current
DRV8889Q1_TRQ_DAC_12P5
12.5% Full scale current
DRV8889Q1_TRQ_DAC_6P25
6.25% Full scale current
DRV8889Q1_TOFF
enum DRV8889Q1_TOFF
Enumerator
DRV8889Q1_TOFF_7US
TOFF value 7us
DRV8889Q1_TOFF_16US
TOFF value 16us
DRV8889Q1_TOFF_24US
TOFF value 24us
DRV8889Q1_TOFF_32US
TOFF value 32us
DRV8889Q1_CONTROL_MODE
enum DRV8889Q1_CONTROL_MODE
Enumerator
DRV8889Q1_CONTROL_MODE_SPIN
Spin mode
DRV8889Q1_CONTROL_MODE_STEP
Step mode
DRV8889Q1_DRIVE
enum DRV8889Q1_DRIVE
Enumerator
DRV8889Q1_DRIVE_DISABLED
Disabled mode
DRV8889Q1_DRIVE_PWM
PWM mode
Function Documentation
DRV8889Q1_init()
void DRV8889Q1_init (DRV8889Q1_Instance * handle)
Enables the necessary interrupts.
Parameters
[in] handle A pointer to drv8889-q1 instance
References DRV8889Q1_REG_CTRL4_LOCK_UNLOCK, DRV8889Q1_setSPIRegisterLock(), HAL_enablePWMInterrupt(), and DRV8889Q1_Instance::step.
DRV8889Q1_createSPIDataWord()
uint16_t DRV8889Q1_createSPIDataWord (DRV8889Q1_SPI_CMD wrCmd, DRV8889Q1_REG_ADDR addr, uint8_t data)
Creates a data word to be send through SPI.
Parameters
[in] wrCmd SPI read or write command. One of DRV8889Q1_SPI_CMD
[in] addr A SPI register address. One of DRV8889Q1_REG_ADDR
[in] data Data to be written to the SPI register.
Returns
Return created SPI word
References DRV8889Q1_SPI_ADDR_MASK, DRV8889Q1_SPI_ADDR_OFS, and DRV8889Q1_SPI_CMD_OFS.
Referenced by DRV8889Q1_spiRead(), and DRV8889Q1_spiWrite().
DRV8889Q1_spiWrite()
void DRV8889Q1_spiWrite (DRV8889Q1_Instance * handle, DRV8889Q1_REG_ADDR addr, uint8_t data)
Writes the data to the SPI register.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] addr A SPI register address. One of DRV8889Q1_REG_ADDR
[in] data Data to be written to the SPI register.
References DRV8889Q1_createSPIDataWord().
Referenced by DRV8889Q1_spiUpdateRegister().
DRV8889Q1_spiRead()
uint8_t DRV8889Q1_spiRead (DRV8889Q1_Instance * handle, DRV8889Q1_REG_ADDR addr)
Reads the data in the SPI register.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] addr A SPI register address. One of DRV8889Q1_REG_ADDR
Returns
Returns the data in spi register
References DRV8889Q1_createSPIDataWord(), HAL_SPI_clearRXFifo(), DRV8889Q1_Instance::spi, and DRV8889Q1_Instance::spiCS.
Referenced by DRV8889Q1_getStallThres(), DRV8889Q1_getTrqCount(), DRV8889Q1_isStallLearnSuccess(), and DRV8889Q1_spiUpdateRegister().
DRV8889Q1_spiUpdateRegister()
void DRV8889Q1_spiUpdateRegister (DRV8889Q1_Instance * handle, DRV8889Q1_REG_ADDR addr, uint32_t mask, uint8_t data)
Update only some bits in the SPI register.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] addr A SPI register address. One of DRV8889Q1_REG_ADDR
[in] mask Mask for the bits to change
[in] data Data to be written to the SPI register
References DRV8889Q1_spiRead(), and DRV8889Q1_spiWrite().
Referenced by DRV8889Q1_clearFaults(), DRV8889Q1_disableOlDet(), DRV8889Q1_disableOutput(), DRV8889Q1_disableStallDet(), DRV8889Q1_enableOlDet(), DRV8889Q1_enableOutput(), DRV8889Q1_enableStallDet(), DRV8889Q1_setDecayMode(), DRV8889Q1_setLearnStall(), DRV8889Q1_setSlewRate(), DRV8889Q1_setSPIRegisterLock(), DRV8889Q1_setStallThres(), DRV8889Q1_setStepMode(), DRV8889Q1_setToff(), and DRV8889Q1_setTrqDac().
DRV8889Q1_setSPIRegisterLock()
void DRV8889Q1_setSPIRegisterLock (DRV8889Q1_Instance * handle, DRV8889Q1_REG_CTRL4_LOCK lock)
Unlock or lock settings of the DRV.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] lock Lock or Unlock value. One of DRV8889Q1_REG_CTRL4_LOCK
References DRV8889Q1_spiUpdateRegister().
Referenced by DRV8889Q1_init().
DRV8889Q1_setDirection()
void DRV8889Q1_setDirection (DRV8889Q1_Instance * handle, DRV8889Q1_DIR dir)
Sets the direction of motor.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] dir New direction to be set. One of DRV8889Q1_DIR
References DRV8889Q1_Instance::dir, DRV8889Q1_DIR_FORWARD, DRV8889Q1_DIR_REVERSE, HAL_GPIO_VALUE_HIGH, HAL_GPIO_VALUE_LOW, and HAL_setGPIOVal().
DRV8889Q1_setStepMode()
void DRV8889Q1_setStepMode (DRV8889Q1_Instance * handle, DRV8889Q1_STEP stepMode)
Sets the step mode.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] stepMode Step mode to be set. One of DRV8889Q1_STEP
References DRV8889Q1_spiUpdateRegister().
DRV8889Q1_setDecayMode()
void DRV8889Q1_setDecayMode (DRV8889Q1_Instance * handle, DRV8889Q1_DECAY decayMode)
Sets the decay mode.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] decayMode Decay mode to be set. One of DRV8889Q1_DECAY
References DRV8889Q1_spiUpdateRegister().
DRV8889Q1_setSpeed()
void DRV8889Q1_setSpeed (DRV8889Q1_Instance * handle, uint32_t timFreq)
Sets the motor speed by setting the timer frequency.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] timFreq Timer frequency to be set
References DRV8889Q1_MAX_SET_FREQ, DRV8889Q1_setStepDuty(), HAL_setPWMFreq(), DRV8889Q1_Instance::setFreq, and DRV8889Q1_Instance::step.
DRV8889Q1_setFSCurr()
void DRV8889Q1_setFSCurr (DRV8889Q1_Instance * handle, _iq15 fsCurr)
Sets full scale current.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] fsCurr Full scale current value to be set in IQ
References HAL_setDACVoltage(), and DRV8889Q1_Instance::vref.
DRV8889Q1_setSlewRate()
void DRV8889Q1_setSlewRate (DRV8889Q1_Instance * handle, DRV8889Q1_SLEW_RATE slewRate)
Sets Slew rate.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] slewRate New slew rate to be set. One of DRV8889Q1_SLEW_RATE
References DRV8889Q1_spiUpdateRegister().
DRV8889Q1_setNSleep()
void DRV8889Q1_setNSleep (DRV8889Q1_Instance * handle)
Sets DRV to awake.
Parameters
[in] handle A pointer to drv8889q1 instance
References DRV8889Q1_SPI_READY_DELAY_MS, HAL_delayMilliSeconds(), HAL_GPIO_VALUE_HIGH, HAL_setGPIOVal(), and DRV8889Q1_Instance::nsleep.
DRV8889Q1_clearNSleep()
void DRV8889Q1_clearNSleep (DRV8889Q1_Instance * handle)
Sets DRV to sleep.
Parameters
[in] handle A pointer to drv8889q1 instance
References HAL_GPIO_VALUE_LOW, HAL_setGPIOVal(), and DRV8889Q1_Instance::nsleep.
DRV8889Q1_enableOutput()
void DRV8889Q1_enableOutput (DRV8889Q1_Instance * handle)
Enables the drv driver output.
Parameters
[in] handle A pointer to drv8889q1 instance
References DRV8889Q1_spiUpdateRegister(), DRV8889Q1_Instance::drvOff, HAL_GPIO_VALUE_LOW, and HAL_setGPIOVal().
DRV8889Q1_disableOutput()
void DRV8889Q1_disableOutput (DRV8889Q1_Instance * handle)
Disables the drv driver output.
Parameters
[in] handle A pointer to drv8889q1 instance
References DRV8889Q1_spiUpdateRegister(), DRV8889Q1_Instance::drvOff, HAL_GPIO_VALUE_HIGH, and HAL_setGPIOVal().
DRV8889Q1_startMotor()
void DRV8889Q1_startMotor (DRV8889Q1_Instance * handle)
Starts the motor.
Parameters
[in] handle A pointer to drv8889q1 instance
References DRV8889Q1_Instance::driveState, DRV8889Q1_DRIVE_PWM, DRV8889Q1_setStepDrive(), HAL_startPWMCounter(), and DRV8889Q1_Instance::step.
DRV8889Q1_stopMotor()
void DRV8889Q1_stopMotor (DRV8889Q1_Instance * handle)
Stops the motor.
Parameters
[in] handle A pointer to drv8889q1 instance
References DRV8889Q1_Instance::driveState, DRV8889Q1_DRIVE_DISABLED, DRV8889Q1_setStepDrive(), HAL_stopPWMCounter(), and DRV8889Q1_Instance::step.
Referenced by DRV8889Q1_checkStep().
DRV8889Q1_isMotorRunning()
bool DRV8889Q1_isMotorRunning (DRV8889Q1_Instance * handle)
Checks if the motor is currently running.
Parameters
[in] handle A pointer to drv8889q1 instance
Returns
Returns the running status of motor
Return values
true Motor is currently running
false Motor is not currently running
References HAL_isPWMCounterRunning(), and DRV8889Q1_Instance::step.
DRV8889Q1_isFaultOccurred()
bool DRV8889Q1_isFaultOccurred (DRV8889Q1_Instance * handle)
Gets if any fault occurred at the instant.
Parameters
[in] handle A pointer to drv8889q1 instance
Returns
Returns if fault occurred
Return values
true Fault currently present
false No fault is currently present
References HAL_GPIO_VALUE_LOW, HAL_readGPIOVal(), and DRV8889Q1_Instance::nfault.
DRV8889Q1_setControlMode()
void DRV8889Q1_setControlMode (DRV8889Q1_Instance * handle, DRV8889Q1_CONTROL_MODE ctrl_mode)
Sets the control mode.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] ctrl_mode Control mode to be set. One of DRV8889Q1_CONTROL_MODE
References DRV8889Q1_Instance::controlMode.
DRV8889Q1_checkStep()
void DRV8889Q1_checkStep (DRV8889Q1_Instance * handle)
Checks if motor has moved the required steps in step mode.
Parameters
[in] handle A pointer to drv8889q1 instance
References DRV8889Q1_Instance::controlMode, DRV8889Q1_CONTROL_MODE_STEP, DRV8889Q1_stopMotor(), DRV8889Q1_Instance::setStep, and DRV8889Q1_Instance::stepCount.
DRV8889Q1_setStepDuty()
void DRV8889Q1_setStepDuty (DRV8889Q1_Instance * handle)
Sets the step duty cycle specified in DRV8889Q1_STEP_DUTYCYCLE.
Parameters
[in] handle A pointer to drv8889q1 instance
References DRV8889Q1_STEP_DUTYCYCLE, HA_setPWMDutyCycle(), and DRV8889Q1_Instance::step.
Referenced by DRV8889Q1_setSpeed().
DRV8889Q1_setStepDrive()
void DRV8889Q1_setStepDrive (DRV8889Q1_Instance * handle, DRV8889Q1_DRIVE drive)
Sets the step drive state.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] drive New drive state to be set. One of DRV8889Q1_DRIVE
References DRV8889Q1_DRIVE_DISABLED, DRV8889Q1_DRIVE_PWM, HAL_configurePWMPin(), HAL_PWM_CHANNEL_MODE_FORCED_LOW, HAL_PWM_CHANNEL_MODE_PWM, and DRV8889Q1_Instance::step.
Referenced by DRV8889Q1_startMotor(), and DRV8889Q1_stopMotor().
DRV8889Q1_setStep()
void DRV8889Q1_setStep (DRV8889Q1_Instance * handle, uint16_t setSteps)
Sets the steps to move in step mode.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] setSteps Steps to move in step mode
References DRV8889Q1_Instance::setStep.
DRV8889Q1_setTrqDac()
void DRV8889Q1_setTrqDac (DRV8889Q1_Instance * handle, DRV8889Q1_TRQ_DAC trqDac)
Sets TRQ DAC value. Used to scale the full scale current.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] trqDac New TRQ DAC value to be set. One of DRV8889Q1_TRQ_DAC
References DRV8889Q1_spiUpdateRegister().
DRV8889Q1_setToff()
void DRV8889Q1_setToff (DRV8889Q1_Instance * handle, DRV8889Q1_TOFF toff)
Sets toff value.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] toff New toff value to be set. One of DRV8889Q1_TOFF
References DRV8889Q1_spiUpdateRegister().
DRV8889Q1_clearFaults()
void DRV8889Q1_clearFaults (DRV8889Q1_Instance * handle)
Clears the SPI fault status registers.
Parameters
[in] handle A pointer to drv8889q1 instance
References DRV8889Q1_spiUpdateRegister().
DRV8889Q1_getStallThres()
uint8_t DRV8889Q1_getStallThres (DRV8889Q1_Instance * handle)
Gets the stall threshold value from spi register.
Parameters
[in] handle A pointer to drv8889q1 instance
Returns
Returns the stall threshold
References DRV8889Q1_spiRead().
DRV8889Q1_setStallThres()
void DRV8889Q1_setStallThres (DRV8889Q1_Instance * handle, uint8_t stallThres)
Set the stall threshold value in spi register.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] stallThres new stall threshold to be set
References DRV8889Q1_spiUpdateRegister().
DRV8889Q1_getTrqCount()
uint8_t DRV8889Q1_getTrqCount (DRV8889Q1_Instance * handle)
Gets the trq count.
Parameters
[in] handle A pointer to drv8889q1 instance
Returns
Returns the trq couht
References DRV8889Q1_spiRead().
DRV8889Q1_enableStallDet()
void DRV8889Q1_enableStallDet (DRV8889Q1_Instance * handle)
Enables the stall detection.
Parameters
[in] handle A pointer to drv8889q1 instance
References DRV8889Q1_spiUpdateRegister().
DRV8889Q1_disableStallDet()
void DRV8889Q1_disableStallDet (DRV8889Q1_Instance * handle)
Disables the stall detection.
Parameters
[in] handle A pointer to drv8889q1 instance
References DRV8889Q1_spiUpdateRegister().
DRV8889Q1_enableOlDet()
void DRV8889Q1_enableOlDet (DRV8889Q1_Instance * handle)
Enables the open load detection.
Parameters
[in] handle A pointer to drv8889q1 instance
References DRV8889Q1_spiUpdateRegister().
DRV8889Q1_disableOlDet()
void DRV8889Q1_disableOlDet (DRV8889Q1_Instance * handle)
Disables the open load detection.
Parameters
[in] handle A pointer to drv8889q1 instance
References DRV8889Q1_spiUpdateRegister().
DRV8889Q1_setLearnStall()
void DRV8889Q1_setLearnStall (DRV8889Q1_Instance * handle)
Starts auto stall learning.
Parameters
[in] handle A pointer to drv8889q1 instance
References DRV8889Q1_spiUpdateRegister().
DRV8889Q1_isStallLearnSuccess()
bool DRV8889Q1_isStallLearnSuccess (DRV8889Q1_Instance * handle)
Checks if auto stall learning is completed successfully.
Parameters
[in] handle A pointer to drv8889q1 instance
Returns
Returns if stall learning is completed successfully
Return values
true Stall learning is not complete
false Stall learning is completed successfully
References DRV8889Q1_spiRead().
DRV8889Q1_setVrefRefVoltage()
void DRV8889Q1_setVrefRefVoltage (DRV8889Q1_Instance * handle, _iq15 refVoltage)
Sets the reference voltage for the vref output.
Parameters
[in] handle A pointer to drv8889q1 instance
[in] refVoltage Reference voltage to be set in IQ
References HAL_setDacRefVoltage(), and DRV8889Q1_Instance::vref.
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale