StepperMotorControlLibrary: Stepper_Library
Stepper_Library
Data Structures
struct INDEXER_Instance
Define indexer structure.
Macros
#define STEPPER_INDEXER_MAX_COUNT (1024)
Maximum count for the indexer.
#define STEPPER_INDEXER_0_BY_8 (0)
Value corresponding to 0/8 of indexer max count.
#define STEPPER_INDEXER_1_BY_8 (STEPPER_INDEXER_MAX_COUNT >> 3)
Value corresponding to 1/8 of indexer max count.
#define STEPPER_INDEXER_2_BY_8 (2 * STEPPER_INDEXER_1_BY_8)
Value corresponding to 2/8 of indexer max count.
#define STEPPER_INDEXER_3_BY_8 (3 * STEPPER_INDEXER_1_BY_8)
Value corresponding to 3/8 of indexer max count.
#define STEPPER_INDEXER_4_BY_8 (4 * STEPPER_INDEXER_1_BY_8)
Value corresponding to 4/8 of indexer max count.
#define STEPPER_INDEXER_5_BY_8 (5 * STEPPER_INDEXER_1_BY_8)
Value corresponding to 5/8 of indexer max count.
#define STEPPER_INDEXER_6_BY_8 (6 * STEPPER_INDEXER_1_BY_8)
Value corresponding to 6/8 of indexer max count.
#define STEPPER_INDEXER_7_BY_8 (7 * STEPPER_INDEXER_1_BY_8)
Value corresponding to 7/8 of indexer max count.
#define STEPPER_2PI (6.2831853071f)
Value for 2*Pi.
Enumerations
enum STEPPER_STEP_INC_DEC {
STEPPER_STEP_INC_DEC_FULL_STEP = 256,
STEPPER_STEP_INC_DEC_HALF_STEP = 128,
STEPPER_STEP_INC_DEC_1BY4_STEP = 64,
STEPPER_STEP_INC_DEC_1BY8_STEP = 32,
STEPPER_STEP_INC_DEC_1BY16_STEP = 16,
STEPPER_STEP_INC_DEC_1BY32_STEP = 8,
STEPPER_STEP_INC_DEC_1BY64_STEP = 4,
STEPPER_STEP_INC_DEC_1BY128_STEP = 2,
STEPPER_STEP_INC_DEC_1BY256_STEP = 1
}
enum STEPPER_DRIVE {
STEPPER_DRIVE_DISABLE = 0,
STEPPER_DRIVE_DECAY,
STEPPER_DRIVE_FORWARD,
STEPPER_DRIVE_REVERSE
}
enum STEPPER_STEP_TYPE {
STEPPER_STEP_TYPE_CIR = 0,
STEPPER_STEP_TYPE_NONCIR
}
enum STEPPER_DIR {
STEPPER_DIR_FORWARD = 0,
STEPPER_DIR_REVERSE
}
Functions
void STEPPER_init (void)
Calculates the angle scale factor.
__STATIC_INLINE void STEPPER_setIndexerDir (INDEXER_Instance *handle, STEPPER_DIR dir)
Sets the direction for the indexer.
__STATIC_INLINE void STEPPER_setIndexerIncVal (INDEXER_Instance *handle, STEPPER_STEP_INC_DEC incDecVal)
Sets the direction for the indexer.
__STATIC_INLINE void STEPPER_setStepType (INDEXER_Instance *handle, STEPPER_STEP_TYPE stepType)
Sets the step type.
__STATIC_INLINE void STEPPER_setMotorDrives (INDEXER_Instance *handle, STEPPER_DRIVE IaDrive, STEPPER_DRIVE IbDrive)
Sets the motor drive states.
__STATIC_INLINE void STEPPER_cirStepPhaseGen (INDEXER_Instance *handle)
Updates phase drive state in circular mode.
__STATIC_INLINE void STEPPER_nonCirPhaseGen (INDEXER_Instance *handle)
Updates phase drive state in non circular mode.
__STATIC_INLINE void STEPPER_indexer (INDEXER_Instance *handle)
Increments the indexer counter and updates the phase reference calculation.
Variables
_iq18 angleSf
Extern angleSf.
Detailed Description
Enumeration Type Documentation
STEPPER_STEP_INC_DEC
enum STEPPER_STEP_INC_DEC
Enumerator
STEPPER_STEP_INC_DEC_FULL_STEP
Increment or decrement value associated to full step
STEPPER_STEP_INC_DEC_HALF_STEP
Increment or decrement value associated to half step
STEPPER_STEP_INC_DEC_1BY4_STEP
Increment or decrement value associated to 1/4 step
STEPPER_STEP_INC_DEC_1BY8_STEP
Increment or decrement value associated to 1/8 step
STEPPER_STEP_INC_DEC_1BY16_STEP
Increment or decrement value associated to 1/16 step
STEPPER_STEP_INC_DEC_1BY32_STEP
Increment or decrement value associated to 1/32 step
STEPPER_STEP_INC_DEC_1BY64_STEP
Increment or decrement value associated to 1/64 step
STEPPER_STEP_INC_DEC_1BY128_STEP
Increment or decrement value associated to 1/128 step
STEPPER_STEP_INC_DEC_1BY256_STEP
Increment or decrement value associated to 1/256 step
STEPPER_DRIVE
enum STEPPER_DRIVE
Enumerator
STEPPER_DRIVE_DISABLE
Disable the Drive
STEPPER_DRIVE_DECAY
Drive in decay state
STEPPER_DRIVE_FORWARD
Drive in forward current state
STEPPER_DRIVE_REVERSE
Drive in reverse current state
STEPPER_STEP_TYPE
enum STEPPER_STEP_TYPE
Enumerator
STEPPER_STEP_TYPE_CIR
Circular step mode
STEPPER_STEP_TYPE_NONCIR
Non circular step mode
STEPPER_DIR
enum STEPPER_DIR
Enumerator
STEPPER_DIR_FORWARD
Forward direction
STEPPER_DIR_REVERSE
Forward direction
Function Documentation
STEPPER_setIndexerDir()
__STATIC_INLINE void STEPPER_setIndexerDir (INDEXER_Instance * handle, STEPPER_DIR dir)
Sets the direction for the indexer.
Parameters
[in] handle A pointer to indexer instance
[in] dir New direction to be set. One of STEPPER_DIR
References INDEXER_Instance::dir.
Referenced by DRV8411A_setDirection().
STEPPER_setIndexerIncVal()
__STATIC_INLINE void STEPPER_setIndexerIncVal (INDEXER_Instance * handle, STEPPER_STEP_INC_DEC incDecVal)
Sets the direction for the indexer.
Parameters
[in] handle A pointer to indexer instance
[in] incDecVal Increment or decrement value to be set. One of STEPPER_STEP_INC_DEC
References INDEXER_Instance::indexIncDec.
Referenced by DRV8411A_setStepMode().
STEPPER_setStepType()
__STATIC_INLINE void STEPPER_setStepType (INDEXER_Instance * handle, STEPPER_STEP_TYPE stepType)
Sets the step type.
Parameters
[in] handle A pointer to indexer instance
[in] stepType Step type value to be set. One of STEPPER_STEP_TYPE
References INDEXER_Instance::stepType.
Referenced by DRV8411A_setStepMode().
STEPPER_setMotorDrives()
__STATIC_INLINE void STEPPER_setMotorDrives (INDEXER_Instance * handle, STEPPER_DRIVE IaDrive, STEPPER_DRIVE IbDrive)
Sets the motor drive states.
Parameters
[in] handle A pointer to indexer instance
[in] IaDrive Drive state for IA phase. One of STEPPER_DRIVE
[in] IbDrive Drive state for IB phase. One of STEPPER_DRIVE
References INDEXER_Instance::IaDrive, and INDEXER_Instance::IbDrive.
Referenced by STEPPER_cirStepPhaseGen(), and STEPPER_nonCirPhaseGen().
STEPPER_cirStepPhaseGen()
__STATIC_INLINE void STEPPER_cirStepPhaseGen (INDEXER_Instance * handle)
Updates phase drive state in circular mode.
Parameters
[in] handle A pointer to indexer instance
References INDEXER_Instance::counter, STEPPER_DRIVE_FORWARD, STEPPER_DRIVE_REVERSE, STEPPER_INDEXER_0_BY_8, STEPPER_INDEXER_2_BY_8, STEPPER_INDEXER_4_BY_8, STEPPER_INDEXER_6_BY_8, and STEPPER_setMotorDrives().
Referenced by STEPPER_indexer().
STEPPER_nonCirPhaseGen()
__STATIC_INLINE void STEPPER_nonCirPhaseGen (INDEXER_Instance * handle)
Updates phase drive state in non circular mode.
Parameters
[in] handle A pointer to indexer instance
References INDEXER_Instance::counter, STEPPER_DRIVE_DECAY, STEPPER_DRIVE_FORWARD, STEPPER_DRIVE_REVERSE, STEPPER_INDEXER_0_BY_8, STEPPER_INDEXER_1_BY_8, STEPPER_INDEXER_2_BY_8, STEPPER_INDEXER_3_BY_8, STEPPER_INDEXER_4_BY_8, STEPPER_INDEXER_5_BY_8, STEPPER_INDEXER_6_BY_8, STEPPER_INDEXER_7_BY_8, and STEPPER_setMotorDrives().
Referenced by STEPPER_indexer().
STEPPER_indexer()
__STATIC_INLINE void STEPPER_indexer (INDEXER_Instance * handle)
Increments the indexer counter and updates the phase reference calculation.
Parameters
[in] handle A pointer to indexer instance
References INDEXER_Instance::counter, INDEXER_Instance::dir, INDEXER_Instance::indexIncDec, STEPPER_cirStepPhaseGen(), STEPPER_DIR_FORWARD, STEPPER_INDEXER_MAX_COUNT, STEPPER_nonCirPhaseGen(), STEPPER_STEP_TYPE_CIR, STEPPER_STEP_TYPE_NONCIR, and INDEXER_Instance::stepType.
Referenced by DRV8411A_setComm().
© Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale