IQMathLibrary: _IQNtoa.c File Reference
_IQNtoa.c File Reference
Detailed Description
Functions to convert an IQ number to a string.
#include <stdint.h>
#include "../support/support.h"
Functions
int_fast16_t __IQNtoa (char *string, const char *format, int_fast32_t iqNInput, int_fast16_t q_value)
Convert an IQ number to a string.
int16_t _IQ31toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ31 number to a string.
int16_t _IQ30toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ30 number to a string.
int16_t _IQ29toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ29 number to a string.
int16_t _IQ28toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ28 number to a string.
int16_t _IQ27toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ27 number to a string.
int16_t _IQ26toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ26 number to a string.
int16_t _IQ25toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ25 number to a string.
int16_t _IQ24toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ24 number to a string.
int16_t _IQ23toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ23 number to a string.
int16_t _IQ22toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ22 number to a string.
int16_t _IQ21toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ21 number to a string.
int16_t _IQ20toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ20 number to a string.
int16_t _IQ19toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ19 number to a string.
int16_t _IQ18toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ18 number to a string.
int16_t _IQ17toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ17 number to a string.
int16_t _IQ16toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ16 number to a string.
int16_t _IQ15toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ15 number to a string.
int16_t _IQ14toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ14 number to a string.
int16_t _IQ13toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ13 number to a string.
int16_t _IQ12toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ12 number to a string.
int16_t _IQ11toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ11 number to a string.
int16_t _IQ10toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ10 number to a string.
int16_t _IQ9toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ9 number to a string.
int16_t _IQ8toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ8 number to a string.
int16_t _IQ7toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ7 number to a string.
int16_t _IQ6toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ6 number to a string.
int16_t _IQ5toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ5 number to a string.
int16_t _IQ4toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ4 number to a string.
int16_t _IQ3toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ3 number to a string.
int16_t _IQ2toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ2 number to a string.
int16_t _IQ1toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ1 number to a string.
int16_t _IQ0toa (char *string, const char *format, int32_t iqNInput)
Convert an IQ0 number to a string.
Function Documentation
__IQNtoa()
int_fast16_t __IQNtoa (char * string, const char * format, int_fast32_t iqNInput, int_fast16_t q_value)
Convert an IQ number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQN type input.
q_value IQ format.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
Referenced by _IQ0toa(), _IQ10toa(), _IQ11toa(), _IQ12toa(), _IQ13toa(), _IQ14toa(), _IQ15toa(), _IQ16toa(), _IQ17toa(), _IQ18toa(), _IQ19toa(), _IQ1toa(), _IQ20toa(), _IQ21toa(), _IQ22toa(), _IQ23toa(), _IQ24toa(), _IQ25toa(), _IQ26toa(), _IQ27toa(), _IQ28toa(), _IQ29toa(), _IQ2toa(), _IQ30toa(), _IQ31toa(), _IQ3toa(), _IQ4toa(), _IQ5toa(), _IQ6toa(), _IQ7toa(), _IQ8toa(), and _IQ9toa().
_IQ31toa()
int16_t _IQ31toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ31 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ31 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ30toa()
int16_t _IQ30toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ30 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ30 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ29toa()
int16_t _IQ29toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ29 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ29 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ28toa()
int16_t _IQ28toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ28 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ28 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ27toa()
int16_t _IQ27toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ27 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ27 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ26toa()
int16_t _IQ26toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ26 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ26 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ25toa()
int16_t _IQ25toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ25 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ25 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ24toa()
int16_t _IQ24toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ24 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ24 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ23toa()
int16_t _IQ23toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ23 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ23 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ22toa()
int16_t _IQ22toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ22 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ22 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ21toa()
int16_t _IQ21toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ21 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ21 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ20toa()
int16_t _IQ20toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ20 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ20 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ19toa()
int16_t _IQ19toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ19 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ19 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ18toa()
int16_t _IQ18toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ18 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ18 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ17toa()
int16_t _IQ17toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ17 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ17 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ16toa()
int16_t _IQ16toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ16 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ16 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ15toa()
int16_t _IQ15toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ15 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ15 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ14toa()
int16_t _IQ14toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ14 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ14 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ13toa()
int16_t _IQ13toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ13 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ13 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ12toa()
int16_t _IQ12toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ12 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ12 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ11toa()
int16_t _IQ11toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ11 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ11 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ10toa()
int16_t _IQ10toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ10 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ10 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ9toa()
int16_t _IQ9toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ9 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ9 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ8toa()
int16_t _IQ8toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ8 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ8 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ7toa()
int16_t _IQ7toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ7 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ7 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ6toa()
int16_t _IQ6toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ6 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ6 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ5toa()
int16_t _IQ5toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ5 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ5 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ4toa()
int16_t _IQ4toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ4 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ4 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ3toa()
int16_t _IQ3toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ3 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ3 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ2toa()
int16_t _IQ2toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ2 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ2 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ1toa()
int16_t _IQ1toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ1 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ1 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
_IQ0toa()
int16_t _IQ0toa (char * string, const char * format, int32_t iqNInput)
Convert an IQ0 number to a string.
Parameters
string Pointer to the buffer to store the converted IQ number.
format The format string specifying how to convert the IQ number.
iqNInput IQ0 type input.
Returns
Returns 0 if there is no error, 1 if the width is too small to hold the integer characters, and 2 if an illegal format was specified.
References __IQNtoa().
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale