IQMathLibrary: _IQNdiv.c File Reference
_IQNdiv.c File Reference
Detailed Description
Functions to divide two values of IQN type.
#include "_IQNdiv.h"
Functions
int32_t _IQ31div (int32_t a, int32_t b)
Divides two values of IQ31 format.
int32_t _IQ30div (int32_t a, int32_t b)
Divides two values of IQ30 format.
int32_t _IQ29div (int32_t a, int32_t b)
Divides two values of IQ29 format.
int32_t _IQ28div (int32_t a, int32_t b)
Divides two values of IQ28 format.
int32_t _IQ27div (int32_t a, int32_t b)
Divides two values of IQ27 format.
int32_t _IQ26div (int32_t a, int32_t b)
Divides two values of IQ26 format.
int32_t _IQ25div (int32_t a, int32_t b)
Divides two values of IQ25 format.
int32_t _IQ24div (int32_t a, int32_t b)
Divides two values of IQ24 format.
int32_t _IQ23div (int32_t a, int32_t b)
Divides two values of IQ23 format.
int32_t _IQ22div (int32_t a, int32_t b)
Divides two values of IQ22 format.
int32_t _IQ21div (int32_t a, int32_t b)
Divides two values of IQ21 format.
int32_t _IQ20div (int32_t a, int32_t b)
Divides two values of IQ20 format.
int32_t _IQ19div (int32_t a, int32_t b)
Divides two values of IQ19 format.
int32_t _IQ18div (int32_t a, int32_t b)
Divides two values of IQ18 format.
int32_t _IQ17div (int32_t a, int32_t b)
Divides two values of IQ17 format.
int32_t _IQ16div (int32_t a, int32_t b)
Divides two values of IQ16 format.
int32_t _IQ15div (int32_t a, int32_t b)
Divides two values of IQ15 format.
int32_t _IQ14div (int32_t a, int32_t b)
Divides two values of IQ14 format.
int32_t _IQ13div (int32_t a, int32_t b)
Divides two values of IQ13 format.
int32_t _IQ12div (int32_t a, int32_t b)
Divides two values of IQ12 format.
int32_t _IQ11div (int32_t a, int32_t b)
Divides two values of IQ11 format.
int32_t _IQ10div (int32_t a, int32_t b)
Divides two values of IQ10 format.
int32_t _IQ9div (int32_t a, int32_t b)
Divides two values of IQ9 format.
int32_t _IQ8div (int32_t a, int32_t b)
Divides two values of IQ8 format.
int32_t _IQ7div (int32_t a, int32_t b)
Divides two values of IQ7 format.
int32_t _IQ6div (int32_t a, int32_t b)
Divides two values of IQ6 format.
int32_t _IQ5div (int32_t a, int32_t b)
Divides two values of IQ5 format.
int32_t _IQ4div (int32_t a, int32_t b)
Divides two values of IQ4 format.
int32_t _IQ3div (int32_t a, int32_t b)
Divides two values of IQ3 format.
int32_t _IQ2div (int32_t a, int32_t b)
Divides two values of IQ2 format.
int32_t _IQ1div (int32_t a, int32_t b)
Divides two values of IQ1 format.
int32_t _IQ0div (int32_t a, int32_t b)
Divides two values of IQ0 format.
uint32_t _UIQ31div (uint32_t a, uint32_t b)
Divides two values of IQ31 format, without sign checks.
Function Documentation
_IQ31div()
int32_t _IQ31div (int32_t a, int32_t b)
Divides two values of IQ31 format.
Parameters
a IQ31 type value numerator to be divided.
b IQ31 type value denominator to divide by.
Returns
IQ31 type result of the multiplication.
Referenced by _IQ0div().
_IQ30div()
int32_t _IQ30div (int32_t a, int32_t b)
Divides two values of IQ30 format.
Parameters
a IQ30 type value numerator to be divided.
b IQ30 type value denominator to divide by.
Returns
IQ30 type result of the multiplication.
Referenced by _IQ0div().
_IQ29div()
int32_t _IQ29div (int32_t a, int32_t b)
Divides two values of IQ29 format.
Parameters
a IQ29 type value numerator to be divided.
b IQ29 type value denominator to divide by.
Returns
IQ29 type result of the multiplication.
Referenced by _IQ0div().
_IQ28div()
int32_t _IQ28div (int32_t a, int32_t b)
Divides two values of IQ28 format.
Parameters
a IQ28 type value numerator to be divided.
b IQ28 type value denominator to divide by.
Returns
IQ28 type result of the multiplication.
Referenced by __IQNatan2(), and _IQ0div().
_IQ27div()
int32_t _IQ27div (int32_t a, int32_t b)
Divides two values of IQ27 format.
Parameters
a IQ27 type value numerator to be divided.
b IQ27 type value denominator to divide by.
Returns
IQ27 type result of the multiplication.
Referenced by _IQ0div().
_IQ26div()
int32_t _IQ26div (int32_t a, int32_t b)
Divides two values of IQ26 format.
Parameters
a IQ26 type value numerator to be divided.
b IQ26 type value denominator to divide by.
Returns
IQ26 type result of the multiplication.
Referenced by _IQ0div().
_IQ25div()
int32_t _IQ25div (int32_t a, int32_t b)
Divides two values of IQ25 format.
Parameters
a IQ25 type value numerator to be divided.
b IQ25 type value denominator to divide by.
Returns
IQ25 type result of the multiplication.
Referenced by _IQ0div().
_IQ24div()
int32_t _IQ24div (int32_t a, int32_t b)
Divides two values of IQ24 format.
Parameters
a IQ24 type value numerator to be divided.
b IQ24 type value denominator to divide by.
Returns
IQ24 type result of the multiplication.
Referenced by _IQ0div().
_IQ23div()
int32_t _IQ23div (int32_t a, int32_t b)
Divides two values of IQ23 format.
Parameters
a IQ23 type value numerator to be divided.
b IQ23 type value denominator to divide by.
Returns
IQ23 type result of the multiplication.
Referenced by _IQ0div().
_IQ22div()
int32_t _IQ22div (int32_t a, int32_t b)
Divides two values of IQ22 format.
Parameters
a IQ22 type value numerator to be divided.
b IQ22 type value denominator to divide by.
Returns
IQ22 type result of the multiplication.
Referenced by _IQ0div().
_IQ21div()
int32_t _IQ21div (int32_t a, int32_t b)
Divides two values of IQ21 format.
Parameters
a IQ21 type value numerator to be divided.
b IQ21 type value denominator to divide by.
Returns
IQ21 type result of the multiplication.
Referenced by _IQ0div().
_IQ20div()
int32_t _IQ20div (int32_t a, int32_t b)
Divides two values of IQ20 format.
Parameters
a IQ20 type value numerator to be divided.
b IQ20 type value denominator to divide by.
Returns
IQ20 type result of the multiplication.
Referenced by _IQ0div().
_IQ19div()
int32_t _IQ19div (int32_t a, int32_t b)
Divides two values of IQ19 format.
Parameters
a IQ19 type value numerator to be divided.
b IQ19 type value denominator to divide by.
Returns
IQ19 type result of the multiplication.
Referenced by _IQ0div().
_IQ18div()
int32_t _IQ18div (int32_t a, int32_t b)
Divides two values of IQ18 format.
Parameters
a IQ18 type value numerator to be divided.
b IQ18 type value denominator to divide by.
Returns
IQ18 type result of the multiplication.
Referenced by _IQ0div().
_IQ17div()
int32_t _IQ17div (int32_t a, int32_t b)
Divides two values of IQ17 format.
Parameters
a IQ17 type value numerator to be divided.
b IQ17 type value denominator to divide by.
Returns
IQ17 type result of the multiplication.
Referenced by _IQ0div().
_IQ16div()
int32_t _IQ16div (int32_t a, int32_t b)
Divides two values of IQ16 format.
Parameters
a IQ16 type value numerator to be divided.
b IQ16 type value denominator to divide by.
Returns
IQ16 type result of the multiplication.
Referenced by _IQ0div().
_IQ15div()
int32_t _IQ15div (int32_t a, int32_t b)
Divides two values of IQ15 format.
Parameters
a IQ15 type value numerator to be divided.
b IQ15 type value denominator to divide by.
Returns
IQ15 type result of the multiplication.
Referenced by _IQ0div().
_IQ14div()
int32_t _IQ14div (int32_t a, int32_t b)
Divides two values of IQ14 format.
Parameters
a IQ14 type value numerator to be divided.
b IQ14 type value denominator to divide by.
Returns
IQ14 type result of the multiplication.
Referenced by _IQ0div().
_IQ13div()
int32_t _IQ13div (int32_t a, int32_t b)
Divides two values of IQ13 format.
Parameters
a IQ13 type value numerator to be divided.
b IQ13 type value denominator to divide by.
Returns
IQ13 type result of the multiplication.
Referenced by _IQ0div().
_IQ12div()
int32_t _IQ12div (int32_t a, int32_t b)
Divides two values of IQ12 format.
Parameters
a IQ12 type value numerator to be divided.
b IQ12 type value denominator to divide by.
Returns
IQ12 type result of the multiplication.
Referenced by _IQ0div().
_IQ11div()
int32_t _IQ11div (int32_t a, int32_t b)
Divides two values of IQ11 format.
Parameters
a IQ11 type value numerator to be divided.
b IQ11 type value denominator to divide by.
Returns
IQ11 type result of the multiplication.
Referenced by _IQ0div().
_IQ10div()
int32_t _IQ10div (int32_t a, int32_t b)
Divides two values of IQ10 format.
Parameters
a IQ10 type value numerator to be divided.
b IQ10 type value denominator to divide by.
Returns
IQ10 type result of the multiplication.
Referenced by _IQ0div().
_IQ9div()
int32_t _IQ9div (int32_t a, int32_t b)
Divides two values of IQ9 format.
Parameters
a IQ9 type value numerator to be divided.
b IQ9 type value denominator to divide by.
Returns
IQ9 type result of the multiplication.
Referenced by _IQ0div().
_IQ8div()
int32_t _IQ8div (int32_t a, int32_t b)
Divides two values of IQ8 format.
Parameters
a IQ8 type value numerator to be divided.
b IQ8 type value denominator to divide by.
Returns
IQ8 type result of the multiplication.
Referenced by _IQ0div().
_IQ7div()
int32_t _IQ7div (int32_t a, int32_t b)
Divides two values of IQ7 format.
Parameters
a IQ7 type value numerator to be divided.
b IQ7 type value denominator to divide by.
Returns
IQ7 type result of the multiplication.
Referenced by _IQ0div().
_IQ6div()
int32_t _IQ6div (int32_t a, int32_t b)
Divides two values of IQ6 format.
Parameters
a IQ6 type value numerator to be divided.
b IQ6 type value denominator to divide by.
Returns
IQ6 type result of the multiplication.
Referenced by _IQ0div().
_IQ5div()
int32_t _IQ5div (int32_t a, int32_t b)
Divides two values of IQ5 format.
Parameters
a IQ5 type value numerator to be divided.
b IQ5 type value denominator to divide by.
Returns
IQ5 type result of the multiplication.
Referenced by _IQ0div().
_IQ4div()
int32_t _IQ4div (int32_t a, int32_t b)
Divides two values of IQ4 format.
Parameters
a IQ4 type value numerator to be divided.
b IQ4 type value denominator to divide by.
Returns
IQ4 type result of the multiplication.
Referenced by _IQ0div().
_IQ3div()
int32_t _IQ3div (int32_t a, int32_t b)
Divides two values of IQ3 format.
Parameters
a IQ3 type value numerator to be divided.
b IQ3 type value denominator to divide by.
Returns
IQ3 type result of the multiplication.
Referenced by _IQ0div().
_IQ2div()
int32_t _IQ2div (int32_t a, int32_t b)
Divides two values of IQ2 format.
Parameters
a IQ2 type value numerator to be divided.
b IQ2 type value denominator to divide by.
Returns
IQ2 type result of the multiplication.
Referenced by _IQ0div().
_IQ1div()
int32_t _IQ1div (int32_t a, int32_t b)
Divides two values of IQ1 format.
Parameters
a IQ1 type value numerator to be divided.
b IQ1 type value denominator to divide by.
Returns
IQ1 type result of the multiplication.
Referenced by _IQ0div().
_IQ0div()
int32_t _IQ0div (int32_t a, int32_t b)
Divides two values of IQ0 format.
Parameters
a IQ0 type value numerator to be divided.
b IQ0 type value denominator to divide by.
Returns
IQ0 type result of the multiplication.
References _IQ10div(), _IQ11div(), _IQ12div(), _IQ13div(), _IQ14div(), _IQ15div(), _IQ16div(), _IQ17div(), _IQ18div(), _IQ19div(), _IQ1div(), _IQ20div(), _IQ21div(), _IQ22div(), _IQ23div(), _IQ24div(), _IQ25div(), _IQ26div(), _IQ27div(), _IQ28div(), _IQ29div(), _IQ2div(), _IQ30div(), _IQ31div(), _IQ3div(), _IQ4div(), _IQ5div(), _IQ6div(), _IQ7div(), _IQ8div(), and _IQ9div().
_UIQ31div()
uint32_t _UIQ31div (uint32_t a, uint32_t b)
Divides two values of IQ31 format, without sign checks.
Parameters
a IQ31 type value numerator to be divided.
b IQ31 type value denominator to divide by.
Returns
IQ31 type result of the multiplication.
Referenced by __IQNatan2().
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale