IQMathLibrary: _IQNatan2.c File Reference
_IQNatan2.c File Reference
Detailed Description
Functions to compute the 4-quadrant arctangent of the input and return the result.
#include <stdint.h>
#include "../support/support.h"
#include "_IQNtables.h"
#include "../include/IQmathLib.h"
#include "_IQNmpy.h"
#include "_IQNdiv.h"
Macros
#define PI (3.1415926536)
The value of PI.
#define TYPE_PU (0)
Used to specify per-unit result.
#define TYPE_RAD (1)
Used to specify result in radians.
Functions
__STATIC_INLINE int_fast32_t __IQNatan2 (int_fast32_t iqNInputY, int_fast32_t iqNInputX, const uint8_t type, const int8_t q_value)
Compute the 4-quadrant arctangent of the IQN input and return the result.
int32_t _IQ29atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ29 input and return the result, in radians.
int32_t _IQ28atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ28 input and return the result, in radians.
int32_t _IQ27atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ27 input and return the result, in radians.
int32_t _IQ26atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ26 input and return the result, in radians.
int32_t _IQ25atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ25 input and return the result, in radians.
int32_t _IQ24atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ24 input and return the result, in radians.
int32_t _IQ23atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ23 input and return the result, in radians.
int32_t _IQ22atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ22 input and return the result, in radians.
int32_t _IQ21atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ21 input and return the result, in radians.
int32_t _IQ20atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ20 input and return the result, in radians.
int32_t _IQ19atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ19 input and return the result, in radians.
int32_t _IQ18atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ18 input and return the result, in radians.
int32_t _IQ17atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ17 input and return the result, in radians.
int32_t _IQ16atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ16 input and return the result, in radians.
int32_t _IQ15atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ15 input and return the result, in radians.
int32_t _IQ14atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ14 input and return the result, in radians.
int32_t _IQ13atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ13 input and return the result, in radians.
int32_t _IQ12atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ12 input and return the result, in radians.
int32_t _IQ11atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ11 input and return the result, in radians.
int32_t _IQ10atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ10 input and return the result, in radians.
int32_t _IQ9atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ9 input and return the result, in radians.
int32_t _IQ8atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ8 input and return the result, in radians.
int32_t _IQ7atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ7 input and return the result, in radians.
int32_t _IQ6atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ6 input and return the result, in radians.
int32_t _IQ5atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ5 input and return the result, in radians.
int32_t _IQ4atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ4 input and return the result, in radians.
int32_t _IQ3atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ3 input and return the result, in radians.
int32_t _IQ2atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ2 input and return the result, in radians.
int32_t _IQ1atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ1 input and return the result, in radians.
int32_t _IQ31atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ31 input and return the result.
int32_t _IQ30atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ30 input and return the result.
int32_t _IQ29atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ29 input and return the result.
int32_t _IQ28atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ28 input and return the result.
int32_t _IQ27atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ27 input and return the result.
int32_t _IQ26atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ26 input and return the result.
int32_t _IQ25atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ25 input and return the result.
int32_t _IQ24atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ24 input and return the result.
int32_t _IQ23atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ23 input and return the result.
int32_t _IQ22atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ22 input and return the result.
int32_t _IQ21atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ21 input and return the result.
int32_t _IQ20atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ20 input and return the result.
int32_t _IQ19atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ19 input and return the result.
int32_t _IQ18atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ18 input and return the result.
int32_t _IQ17atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ17 input and return the result.
int32_t _IQ16atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ16 input and return the result.
int32_t _IQ15atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ15 input and return the result.
int32_t _IQ14atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ14 input and return the result.
int32_t _IQ13atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ13 input and return the result.
int32_t _IQ12atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ12 input and return the result.
int32_t _IQ11atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ11 input and return the result.
int32_t _IQ10atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ10 input and return the result.
int32_t _IQ9atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ9 input and return the result.
int32_t _IQ8atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ8 input and return the result.
int32_t _IQ7atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ7 input and return the result.
int32_t _IQ6atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ6 input and return the result.
int32_t _IQ5atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ5 input and return the result.
int32_t _IQ4atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ4 input and return the result.
int32_t _IQ3atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ3 input and return the result.
int32_t _IQ2atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ2 input and return the result.
int32_t _IQ1atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ1 input and return the result.
Function Documentation
__IQNatan2()
__STATIC_INLINE int_fast32_t __IQNatan2 (int_fast32_t iqNInputY, int_fast32_t iqNInputX, const uint8_t type, const int8_t q_value)
Compute the 4-quadrant arctangent of the IQN input and return the result.
Parameters
iqNInputY IQN type input y.
iqNInputX IQN type input x.
type Specifies radians or per-unit operation.
q_value IQ format.
Returns
IQN type result of 4-quadrant arctangent.
References _IQ28div(), _IQ28mpy(), _IQabs, _UIQ31div(), and TYPE_PU.
Referenced by _IQ10atan2(), _IQ10atan2PU(), _IQ11atan2(), _IQ11atan2PU(), _IQ12atan2(), _IQ12atan2PU(), _IQ13atan2(), _IQ13atan2PU(), _IQ14atan2(), _IQ14atan2PU(), _IQ15atan2(), _IQ15atan2PU(), _IQ16atan2(), _IQ16atan2PU(), _IQ17atan2(), _IQ17atan2PU(), _IQ18atan2(), _IQ18atan2PU(), _IQ19atan2(), _IQ19atan2PU(), _IQ1atan2(), _IQ1atan2PU(), _IQ20atan2(), _IQ20atan2PU(), _IQ21atan2(), _IQ21atan2PU(), _IQ22atan2(), _IQ22atan2PU(), _IQ23atan2(), _IQ23atan2PU(), _IQ24atan2(), _IQ24atan2PU(), _IQ25atan2(), _IQ25atan2PU(), _IQ26atan2(), _IQ26atan2PU(), _IQ27atan2(), _IQ27atan2PU(), _IQ28atan2(), _IQ28atan2PU(), _IQ29atan2(), _IQ29atan2PU(), _IQ2atan2(), _IQ2atan2PU(), _IQ30atan2PU(), _IQ31atan2PU(), _IQ3atan2(), _IQ3atan2PU(), _IQ4atan2(), _IQ4atan2PU(), _IQ5atan2(), _IQ5atan2PU(), _IQ6atan2(), _IQ6atan2PU(), _IQ7atan2(), _IQ7atan2PU(), _IQ8atan2(), _IQ8atan2PU(), _IQ9atan2(), and _IQ9atan2PU().
_IQ29atan2()
int32_t _IQ29atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ29 input and return the result, in radians.
Parameters
y IQ29 type input y.
x IQ29 type input x.
Returns
IQ29 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ28atan2()
int32_t _IQ28atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ28 input and return the result, in radians.
Parameters
y IQ28 type input y.
x IQ28 type input x.
Returns
IQ28 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ27atan2()
int32_t _IQ27atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ27 input and return the result, in radians.
Parameters
y IQ27 type input y.
x IQ27 type input x.
Returns
IQ27 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ26atan2()
int32_t _IQ26atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ26 input and return the result, in radians.
Parameters
y IQ26 type input y.
x IQ26 type input x.
Returns
IQ26 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ25atan2()
int32_t _IQ25atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ25 input and return the result, in radians.
Parameters
y IQ25 type input y.
x IQ25 type input x.
Returns
IQ25 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ24atan2()
int32_t _IQ24atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ24 input and return the result, in radians.
Parameters
y IQ24 type input y.
x IQ24 type input x.
Returns
IQ24 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ23atan2()
int32_t _IQ23atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ23 input and return the result, in radians.
Parameters
y IQ23 type input y.
x IQ23 type input x.
Returns
IQ23 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ22atan2()
int32_t _IQ22atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ22 input and return the result, in radians.
Parameters
y IQ22 type input y.
x IQ22 type input x.
Returns
IQ22 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ21atan2()
int32_t _IQ21atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ21 input and return the result, in radians.
Parameters
y IQ21 type input y.
x IQ21 type input x.
Returns
IQ21 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ20atan2()
int32_t _IQ20atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ20 input and return the result, in radians.
Parameters
y IQ20 type input y.
x IQ20 type input x.
Returns
IQ20 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ19atan2()
int32_t _IQ19atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ19 input and return the result, in radians.
Parameters
y IQ19 type input y.
x IQ19 type input x.
Returns
IQ19 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ18atan2()
int32_t _IQ18atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ18 input and return the result, in radians.
Parameters
y IQ18 type input y.
x IQ18 type input x.
Returns
IQ18 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ17atan2()
int32_t _IQ17atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ17 input and return the result, in radians.
Parameters
y IQ17 type input y.
x IQ17 type input x.
Returns
IQ17 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ16atan2()
int32_t _IQ16atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ16 input and return the result, in radians.
Parameters
y IQ16 type input y.
x IQ16 type input x.
Returns
IQ16 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ15atan2()
int32_t _IQ15atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ15 input and return the result, in radians.
Parameters
y IQ15 type input y.
x IQ15 type input x.
Returns
IQ15 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ14atan2()
int32_t _IQ14atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ14 input and return the result, in radians.
Parameters
y IQ14 type input y.
x IQ14 type input x.
Returns
IQ14 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ13atan2()
int32_t _IQ13atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ13 input and return the result, in radians.
Parameters
y IQ13 type input y.
x IQ13 type input x.
Returns
IQ13 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ12atan2()
int32_t _IQ12atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ12 input and return the result, in radians.
Parameters
y IQ12 type input y.
x IQ12 type input x.
Returns
IQ12 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ11atan2()
int32_t _IQ11atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ11 input and return the result, in radians.
Parameters
y IQ11 type input y.
x IQ11 type input x.
Returns
IQ11 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ10atan2()
int32_t _IQ10atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ10 input and return the result, in radians.
Parameters
y IQ10 type input y.
x IQ10 type input x.
Returns
IQ10 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ9atan2()
int32_t _IQ9atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ9 input and return the result, in radians.
Parameters
y IQ9 type input y.
x IQ9 type input x.
Returns
IQ9 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ8atan2()
int32_t _IQ8atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ8 input and return the result, in radians.
Parameters
y IQ8 type input y.
x IQ8 type input x.
Returns
IQ8 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ7atan2()
int32_t _IQ7atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ7 input and return the result, in radians.
Parameters
y IQ7 type input y.
x IQ7 type input x.
Returns
IQ7 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ6atan2()
int32_t _IQ6atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ6 input and return the result, in radians.
Parameters
y IQ6 type input y.
x IQ6 type input x.
Returns
IQ6 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ5atan2()
int32_t _IQ5atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ5 input and return the result, in radians.
Parameters
y IQ5 type input y.
x IQ5 type input x.
Returns
IQ5 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ4atan2()
int32_t _IQ4atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ4 input and return the result, in radians.
Parameters
y IQ4 type input y.
x IQ4 type input x.
Returns
IQ4 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ3atan2()
int32_t _IQ3atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ3 input and return the result, in radians.
Parameters
y IQ3 type input y.
x IQ3 type input x.
Returns
IQ3 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ2atan2()
int32_t _IQ2atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ2 input and return the result, in radians.
Parameters
y IQ2 type input y.
x IQ2 type input x.
Returns
IQ2 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ1atan2()
int32_t _IQ1atan2 (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ1 input and return the result, in radians.
Parameters
y IQ1 type input y.
x IQ1 type input x.
Returns
IQ1 type result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_RAD.
_IQ31atan2PU()
int32_t _IQ31atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ31 input and return the result.
Parameters
y IQ31 type input y.
x IQ31 type input x.
Returns
IQ31 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ30atan2PU()
int32_t _IQ30atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ30 input and return the result.
Parameters
y IQ30 type input y.
x IQ30 type input x.
Returns
IQ30 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ29atan2PU()
int32_t _IQ29atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ29 input and return the result.
Parameters
y IQ29 type input y.
x IQ29 type input x.
Returns
IQ29 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ28atan2PU()
int32_t _IQ28atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ28 input and return the result.
Parameters
y IQ28 type input y.
x IQ28 type input x.
Returns
IQ28 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ27atan2PU()
int32_t _IQ27atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ27 input and return the result.
Parameters
y IQ27 type input y.
x IQ27 type input x.
Returns
IQ27 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ26atan2PU()
int32_t _IQ26atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ26 input and return the result.
Parameters
y IQ26 type input y.
x IQ26 type input x.
Returns
IQ26 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ25atan2PU()
int32_t _IQ25atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ25 input and return the result.
Parameters
y IQ25 type input y.
x IQ25 type input x.
Returns
IQ25 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ24atan2PU()
int32_t _IQ24atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ24 input and return the result.
Parameters
y IQ24 type input y.
x IQ24 type input x.
Returns
IQ24 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ23atan2PU()
int32_t _IQ23atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ23 input and return the result.
Parameters
y IQ23 type input y.
x IQ23 type input x.
Returns
IQ23 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ22atan2PU()
int32_t _IQ22atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ22 input and return the result.
Parameters
y IQ22 type input y.
x IQ22 type input x.
Returns
IQ22 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ21atan2PU()
int32_t _IQ21atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ21 input and return the result.
Parameters
y IQ21 type input y.
x IQ21 type input x.
Returns
IQ21 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ20atan2PU()
int32_t _IQ20atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ20 input and return the result.
Parameters
y IQ20 type input y.
x IQ20 type input x.
Returns
IQ20 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ19atan2PU()
int32_t _IQ19atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ19 input and return the result.
Parameters
y IQ19 type input y.
x IQ19 type input x.
Returns
IQ19 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ18atan2PU()
int32_t _IQ18atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ18 input and return the result.
Parameters
y IQ18 type input y.
x IQ18 type input x.
Returns
IQ18 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ17atan2PU()
int32_t _IQ17atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ17 input and return the result.
Parameters
y IQ17 type input y.
x IQ17 type input x.
Returns
IQ17 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ16atan2PU()
int32_t _IQ16atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ16 input and return the result.
Parameters
y IQ16 type input y.
x IQ16 type input x.
Returns
IQ16 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ15atan2PU()
int32_t _IQ15atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ15 input and return the result.
Parameters
y IQ15 type input y.
x IQ15 type input x.
Returns
IQ15 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ14atan2PU()
int32_t _IQ14atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ14 input and return the result.
Parameters
y IQ14 type input y.
x IQ14 type input x.
Returns
IQ14 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ13atan2PU()
int32_t _IQ13atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ13 input and return the result.
Parameters
y IQ13 type input y.
x IQ13 type input x.
Returns
IQ13 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ12atan2PU()
int32_t _IQ12atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ12 input and return the result.
Parameters
y IQ12 type input y.
x IQ12 type input x.
Returns
IQ12 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ11atan2PU()
int32_t _IQ11atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ11 input and return the result.
Parameters
y IQ11 type input y.
x IQ11 type input x.
Returns
IQ11 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ10atan2PU()
int32_t _IQ10atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ10 input and return the result.
Parameters
y IQ10 type input y.
x IQ10 type input x.
Returns
IQ10 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ9atan2PU()
int32_t _IQ9atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ9 input and return the result.
Parameters
y IQ9 type input y.
x IQ9 type input x.
Returns
IQ9 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ8atan2PU()
int32_t _IQ8atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ8 input and return the result.
Parameters
y IQ8 type input y.
x IQ8 type input x.
Returns
IQ8 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ7atan2PU()
int32_t _IQ7atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ7 input and return the result.
Parameters
y IQ7 type input y.
x IQ7 type input x.
Returns
IQ7 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ6atan2PU()
int32_t _IQ6atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ6 input and return the result.
Parameters
y IQ6 type input y.
x IQ6 type input x.
Returns
IQ6 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ5atan2PU()
int32_t _IQ5atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ5 input and return the result.
Parameters
y IQ5 type input y.
x IQ5 type input x.
Returns
IQ5 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ4atan2PU()
int32_t _IQ4atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ4 input and return the result.
Parameters
y IQ4 type input y.
x IQ4 type input x.
Returns
IQ4 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ3atan2PU()
int32_t _IQ3atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ3 input and return the result.
Parameters
y IQ3 type input y.
x IQ3 type input x.
Returns
IQ3 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ2atan2PU()
int32_t _IQ2atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ2 input and return the result.
Parameters
y IQ2 type input y.
x IQ2 type input x.
Returns
IQ2 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
_IQ1atan2PU()
int32_t _IQ1atan2PU (int32_t y, int32_t x)
Compute the 4-quadrant arctangent of the IQ1 input and return the result.
Parameters
y IQ1 type input y.
x IQ1 type input x.
Returns
IQ1 type per-unit result of 4-quadrant arctangent.
References __IQNatan2(), and TYPE_PU.
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale