IQMathLibrary: _IQNsqrt.c File Reference
_IQNsqrt.c File Reference
Detailed Description
Functions to compute square root, inverse square root and the magnitude of two IQN inputs.
#include <stdint.h>
#include "../support/support.h"
#include "_IQNtables.h"
#include "../include/IQmathLib.h"
Macros
#define TYPE_ISQRT (0)
Specifies inverse square root operation type.
#define TYPE_SQRT (1)
Specifies square root operation type.
#define TYPE_MAG (2)
Specifies magnitude operation type.
#define TYPE_IMAG (3)
Specifies inverse magnitude operation type.
Functions
__STATIC_INLINE int_fast32_t __IQNsqrt (int_fast32_t iqNInputX, int_fast32_t iqNInputY, const int8_t q_value, const int8_t type)
Calculate square root, inverse square root and the magnitude of two inputs.
int32_t _IQ31sqrt (int32_t a)
Calculate square root of an IQ31 input.
int32_t _IQ30sqrt (int32_t a)
Calculate square root of an IQ30 input.
int32_t _IQ29sqrt (int32_t a)
Calculate square root of an IQ29 input.
int32_t _IQ28sqrt (int32_t a)
Calculate square root of an IQ28 input.
int32_t _IQ27sqrt (int32_t a)
Calculate square root of an IQ27 input.
int32_t _IQ26sqrt (int32_t a)
Calculate square root of an IQ26 input.
int32_t _IQ25sqrt (int32_t a)
Calculate square root of an IQ25 input.
int32_t _IQ24sqrt (int32_t a)
Calculate square root of an IQ24 input.
int32_t _IQ23sqrt (int32_t a)
Calculate square root of an IQ23 input.
int32_t _IQ22sqrt (int32_t a)
Calculate square root of an IQ22 input.
int32_t _IQ21sqrt (int32_t a)
Calculate square root of an IQ21 input.
int32_t _IQ20sqrt (int32_t a)
Calculate square root of an IQ20 input.
int32_t _IQ19sqrt (int32_t a)
Calculate square root of an IQ19 input.
int32_t _IQ18sqrt (int32_t a)
Calculate square root of an IQ18 input.
int32_t _IQ17sqrt (int32_t a)
Calculate square root of an IQ17 input.
int32_t _IQ16sqrt (int32_t a)
Calculate square root of an IQ16 input.
int32_t _IQ15sqrt (int32_t a)
Calculate square root of an IQ15 input.
int32_t _IQ14sqrt (int32_t a)
Calculate square root of an IQ14 input.
int32_t _IQ13sqrt (int32_t a)
Calculate square root of an IQ13 input.
int32_t _IQ12sqrt (int32_t a)
Calculate square root of an IQ12 input.
int32_t _IQ11sqrt (int32_t a)
Calculate square root of an IQ11 input.
int32_t _IQ10sqrt (int32_t a)
Calculate square root of an IQ10 input.
int32_t _IQ9sqrt (int32_t a)
Calculate square root of an IQ9 input.
int32_t _IQ8sqrt (int32_t a)
Calculate square root of an IQ8 input.
int32_t _IQ7sqrt (int32_t a)
Calculate square root of an IQ7 input.
int32_t _IQ6sqrt (int32_t a)
Calculate square root of an IQ6 input.
int32_t _IQ5sqrt (int32_t a)
Calculate square root of an IQ5 input.
int32_t _IQ4sqrt (int32_t a)
Calculate square root of an IQ4 input.
int32_t _IQ3sqrt (int32_t a)
Calculate square root of an IQ3 input.
int32_t _IQ2sqrt (int32_t a)
Calculate square root of an IQ2 input.
int32_t _IQ1sqrt (int32_t a)
Calculate square root of an IQ1 input.
int32_t _IQ0sqrt (int32_t a)
Calculate square root of an IQ0 input.
int32_t _IQ30isqrt (int32_t a)
Calculate inverse square root of an IQ30 input.
int32_t _IQ29isqrt (int32_t a)
Calculate inverse square root of an IQ29 input.
int32_t _IQ28isqrt (int32_t a)
Calculate inverse square root of an IQ28 input.
int32_t _IQ27isqrt (int32_t a)
Calculate inverse square root of an IQ27 input.
int32_t _IQ26isqrt (int32_t a)
Calculate inverse square root of an IQ26 input.
int32_t _IQ25isqrt (int32_t a)
Calculate inverse square root of an IQ25 input.
int32_t _IQ24isqrt (int32_t a)
Calculate inverse square root of an IQ24 input.
int32_t _IQ23isqrt (int32_t a)
Calculate inverse square root of an IQ23 input.
int32_t _IQ22isqrt (int32_t a)
Calculate inverse square root of an IQ22 input.
int32_t _IQ21isqrt (int32_t a)
Calculate inverse square root of an IQ21 input.
int32_t _IQ20isqrt (int32_t a)
Calculate inverse square root of an IQ20 input.
int32_t _IQ19isqrt (int32_t a)
Calculate inverse square root of an IQ19 input.
int32_t _IQ18isqrt (int32_t a)
Calculate inverse square root of an IQ18 input.
int32_t _IQ17isqrt (int32_t a)
Calculate inverse square root of an IQ17 input.
int32_t _IQ16isqrt (int32_t a)
Calculate inverse square root of an IQ16 input.
int32_t _IQ15isqrt (int32_t a)
Calculate inverse square root of an IQ15 input.
int32_t _IQ14isqrt (int32_t a)
Calculate inverse square root of an IQ14 input.
int32_t _IQ13isqrt (int32_t a)
Calculate inverse square root of an IQ13 input.
int32_t _IQ12isqrt (int32_t a)
Calculate inverse square root of an IQ12 input.
int32_t _IQ11isqrt (int32_t a)
Calculate inverse square root of an IQ11 input.
int32_t _IQ10isqrt (int32_t a)
Calculate inverse square root of an IQ10 input.
int32_t _IQ9isqrt (int32_t a)
Calculate inverse square root of an IQ9 input.
int32_t _IQ8isqrt (int32_t a)
Calculate inverse square root of an IQ8 input.
int32_t _IQ7isqrt (int32_t a)
Calculate inverse square root of an IQ7 input.
int32_t _IQ6isqrt (int32_t a)
Calculate inverse square root of an IQ6 input.
int32_t _IQ5isqrt (int32_t a)
Calculate inverse square root of an IQ5 input.
int32_t _IQ4isqrt (int32_t a)
Calculate inverse square root of an IQ4 input.
int32_t _IQ3isqrt (int32_t a)
Calculate inverse square root of an IQ3 input.
int32_t _IQ2isqrt (int32_t a)
Calculate inverse square root of an IQ2 input.
int32_t _IQ1isqrt (int32_t a)
Calculate inverse square root of an IQ1 input.
int32_t _IQmag (int32_t a, int32_t b)
Calculate the magnitude of two IQ31 inputs.
int32_t _IQ30imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ29imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ28imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ27imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ26imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ25imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ24imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ23imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ22imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ21imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ20imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ19imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ18imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ17imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ16imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ15imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ14imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ13imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ12imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ11imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ10imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ9imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ8imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ7imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ6imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ5imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ4imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ3imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ2imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
int32_t _IQ1imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Function Documentation
__IQNsqrt()
__STATIC_INLINE int_fast32_t __IQNsqrt (int_fast32_t iqNInputX, int_fast32_t iqNInputY, const int8_t q_value, const int8_t type)
Calculate square root, inverse square root and the magnitude of two inputs.
Parameters
iqNInputX IQN type input x.
iqNInputY IQN type input y.
type Operation type.
q_value IQ format.
Returns
IQN type result of the square root or magnitude operation.
References TYPE_IMAG, TYPE_MAG, and TYPE_SQRT.
Referenced by _IQ0sqrt(), _IQ10imag(), _IQ10isqrt(), _IQ10sqrt(), _IQ11imag(), _IQ11isqrt(), _IQ11sqrt(), _IQ12imag(), _IQ12isqrt(), _IQ12sqrt(), _IQ13imag(), _IQ13isqrt(), _IQ13sqrt(), _IQ14imag(), _IQ14isqrt(), _IQ14sqrt(), _IQ15imag(), _IQ15isqrt(), _IQ15sqrt(), _IQ16imag(), _IQ16isqrt(), _IQ16sqrt(), _IQ17imag(), _IQ17isqrt(), _IQ17sqrt(), _IQ18imag(), _IQ18isqrt(), _IQ18sqrt(), _IQ19imag(), _IQ19isqrt(), _IQ19sqrt(), _IQ1imag(), _IQ1isqrt(), _IQ1sqrt(), _IQ20imag(), _IQ20isqrt(), _IQ20sqrt(), _IQ21imag(), _IQ21isqrt(), _IQ21sqrt(), _IQ22imag(), _IQ22isqrt(), _IQ22sqrt(), _IQ23imag(), _IQ23isqrt(), _IQ23sqrt(), _IQ24imag(), _IQ24isqrt(), _IQ24sqrt(), _IQ25imag(), _IQ25isqrt(), _IQ25sqrt(), _IQ26imag(), _IQ26isqrt(), _IQ26sqrt(), _IQ27imag(), _IQ27isqrt(), _IQ27sqrt(), _IQ28imag(), _IQ28isqrt(), _IQ28sqrt(), _IQ29imag(), _IQ29isqrt(), _IQ29sqrt(), _IQ2imag(), _IQ2isqrt(), _IQ2sqrt(), _IQ30imag(), _IQ30isqrt(), _IQ30sqrt(), _IQ31sqrt(), _IQ3imag(), _IQ3isqrt(), _IQ3sqrt(), _IQ4imag(), _IQ4isqrt(), _IQ4sqrt(), _IQ5imag(), _IQ5isqrt(), _IQ5sqrt(), _IQ6imag(), _IQ6isqrt(), _IQ6sqrt(), _IQ7imag(), _IQ7isqrt(), _IQ7sqrt(), _IQ8imag(), _IQ8isqrt(), _IQ8sqrt(), _IQ9imag(), _IQ9isqrt(), _IQ9sqrt(), and _IQmag().
_IQ31sqrt()
int32_t _IQ31sqrt (int32_t a)
Calculate square root of an IQ31 input.
Parameters
a IQ31 type input.
Returns
IQ31 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by __IQNasin(), and _IQ0sqrt().
_IQ30sqrt()
int32_t _IQ30sqrt (int32_t a)
Calculate square root of an IQ30 input.
Parameters
a IQ30 type input.
Returns
IQ30 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ29sqrt()
int32_t _IQ29sqrt (int32_t a)
Calculate square root of an IQ29 input.
Parameters
a IQ29 type input.
Returns
IQ29 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ28sqrt()
int32_t _IQ28sqrt (int32_t a)
Calculate square root of an IQ28 input.
Parameters
a IQ28 type input.
Returns
IQ28 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ27sqrt()
int32_t _IQ27sqrt (int32_t a)
Calculate square root of an IQ27 input.
Parameters
a IQ27 type input.
Returns
IQ27 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ26sqrt()
int32_t _IQ26sqrt (int32_t a)
Calculate square root of an IQ26 input.
Parameters
a IQ26 type input.
Returns
IQ26 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ25sqrt()
int32_t _IQ25sqrt (int32_t a)
Calculate square root of an IQ25 input.
Parameters
a IQ25 type input.
Returns
IQ25 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ24sqrt()
int32_t _IQ24sqrt (int32_t a)
Calculate square root of an IQ24 input.
Parameters
a IQ24 type input.
Returns
IQ24 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ23sqrt()
int32_t _IQ23sqrt (int32_t a)
Calculate square root of an IQ23 input.
Parameters
a IQ23 type input.
Returns
IQ23 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ22sqrt()
int32_t _IQ22sqrt (int32_t a)
Calculate square root of an IQ22 input.
Parameters
a IQ22 type input.
Returns
IQ22 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ21sqrt()
int32_t _IQ21sqrt (int32_t a)
Calculate square root of an IQ21 input.
Parameters
a IQ21 type input.
Returns
IQ21 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ20sqrt()
int32_t _IQ20sqrt (int32_t a)
Calculate square root of an IQ20 input.
Parameters
a IQ20 type input.
Returns
IQ20 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ19sqrt()
int32_t _IQ19sqrt (int32_t a)
Calculate square root of an IQ19 input.
Parameters
a IQ19 type input.
Returns
IQ19 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ18sqrt()
int32_t _IQ18sqrt (int32_t a)
Calculate square root of an IQ18 input.
Parameters
a IQ18 type input.
Returns
IQ18 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ17sqrt()
int32_t _IQ17sqrt (int32_t a)
Calculate square root of an IQ17 input.
Parameters
a IQ17 type input.
Returns
IQ17 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ16sqrt()
int32_t _IQ16sqrt (int32_t a)
Calculate square root of an IQ16 input.
Parameters
a IQ16 type input.
Returns
IQ16 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ15sqrt()
int32_t _IQ15sqrt (int32_t a)
Calculate square root of an IQ15 input.
Parameters
a IQ15 type input.
Returns
IQ15 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ14sqrt()
int32_t _IQ14sqrt (int32_t a)
Calculate square root of an IQ14 input.
Parameters
a IQ14 type input.
Returns
IQ14 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ13sqrt()
int32_t _IQ13sqrt (int32_t a)
Calculate square root of an IQ13 input.
Parameters
a IQ13 type input.
Returns
IQ13 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ12sqrt()
int32_t _IQ12sqrt (int32_t a)
Calculate square root of an IQ12 input.
Parameters
a IQ12 type input.
Returns
IQ12 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ11sqrt()
int32_t _IQ11sqrt (int32_t a)
Calculate square root of an IQ11 input.
Parameters
a IQ11 type input.
Returns
IQ11 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ10sqrt()
int32_t _IQ10sqrt (int32_t a)
Calculate square root of an IQ10 input.
Parameters
a IQ10 type input.
Returns
IQ10 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ9sqrt()
int32_t _IQ9sqrt (int32_t a)
Calculate square root of an IQ9 input.
Parameters
a IQ9 type input.
Returns
IQ9 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ8sqrt()
int32_t _IQ8sqrt (int32_t a)
Calculate square root of an IQ8 input.
Parameters
a IQ8 type input.
Returns
IQ8 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ7sqrt()
int32_t _IQ7sqrt (int32_t a)
Calculate square root of an IQ7 input.
Parameters
a IQ7 type input.
Returns
IQ7 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ6sqrt()
int32_t _IQ6sqrt (int32_t a)
Calculate square root of an IQ6 input.
Parameters
a IQ6 type input.
Returns
IQ6 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ5sqrt()
int32_t _IQ5sqrt (int32_t a)
Calculate square root of an IQ5 input.
Parameters
a IQ5 type input.
Returns
IQ5 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ4sqrt()
int32_t _IQ4sqrt (int32_t a)
Calculate square root of an IQ4 input.
Parameters
a IQ4 type input.
Returns
IQ4 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ3sqrt()
int32_t _IQ3sqrt (int32_t a)
Calculate square root of an IQ3 input.
Parameters
a IQ3 type input.
Returns
IQ3 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ2sqrt()
int32_t _IQ2sqrt (int32_t a)
Calculate square root of an IQ2 input.
Parameters
a IQ2 type input.
Returns
IQ2 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ1sqrt()
int32_t _IQ1sqrt (int32_t a)
Calculate square root of an IQ1 input.
Parameters
a IQ1 type input.
Returns
IQ1 type result of the square root operation.
References __IQNsqrt(), and TYPE_SQRT.
Referenced by _IQ0sqrt().
_IQ0sqrt()
int32_t _IQ0sqrt (int32_t a)
Calculate square root of an IQ0 input.
Parameters
a IQ0 type input.
Returns
IQ0 type result of the square root operation.
References __IQNsqrt(), _IQ10sqrt(), _IQ11sqrt(), _IQ12sqrt(), _IQ13sqrt(), _IQ14sqrt(), _IQ15sqrt(), _IQ16sqrt(), _IQ17sqrt(), _IQ18sqrt(), _IQ19sqrt(), _IQ1sqrt(), _IQ20sqrt(), _IQ21sqrt(), _IQ22sqrt(), _IQ23sqrt(), _IQ24sqrt(), _IQ25sqrt(), _IQ26sqrt(), _IQ27sqrt(), _IQ28sqrt(), _IQ29sqrt(), _IQ2sqrt(), _IQ30sqrt(), _IQ31sqrt(), _IQ3sqrt(), _IQ4sqrt(), _IQ5sqrt(), _IQ6sqrt(), _IQ7sqrt(), _IQ8sqrt(), _IQ9sqrt(), and TYPE_SQRT.
_IQ30isqrt()
int32_t _IQ30isqrt (int32_t a)
Calculate inverse square root of an IQ30 input.
Parameters
a IQ30 type input.
Returns
IQ30 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ29isqrt()
int32_t _IQ29isqrt (int32_t a)
Calculate inverse square root of an IQ29 input.
Parameters
a IQ29 type input.
Returns
IQ29 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ28isqrt()
int32_t _IQ28isqrt (int32_t a)
Calculate inverse square root of an IQ28 input.
Parameters
a IQ28 type input.
Returns
IQ28 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ27isqrt()
int32_t _IQ27isqrt (int32_t a)
Calculate inverse square root of an IQ27 input.
Parameters
a IQ27 type input.
Returns
IQ27 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ26isqrt()
int32_t _IQ26isqrt (int32_t a)
Calculate inverse square root of an IQ26 input.
Parameters
a IQ26 type input.
Returns
IQ26 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ25isqrt()
int32_t _IQ25isqrt (int32_t a)
Calculate inverse square root of an IQ25 input.
Parameters
a IQ25 type input.
Returns
IQ25 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ24isqrt()
int32_t _IQ24isqrt (int32_t a)
Calculate inverse square root of an IQ24 input.
Parameters
a IQ24 type input.
Returns
IQ24 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ23isqrt()
int32_t _IQ23isqrt (int32_t a)
Calculate inverse square root of an IQ23 input.
Parameters
a IQ23 type input.
Returns
IQ23 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ22isqrt()
int32_t _IQ22isqrt (int32_t a)
Calculate inverse square root of an IQ22 input.
Parameters
a IQ22 type input.
Returns
IQ22 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ21isqrt()
int32_t _IQ21isqrt (int32_t a)
Calculate inverse square root of an IQ21 input.
Parameters
a IQ21 type input.
Returns
IQ21 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ20isqrt()
int32_t _IQ20isqrt (int32_t a)
Calculate inverse square root of an IQ20 input.
Parameters
a IQ20 type input.
Returns
IQ20 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ19isqrt()
int32_t _IQ19isqrt (int32_t a)
Calculate inverse square root of an IQ19 input.
Parameters
a IQ19 type input.
Returns
IQ19 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ18isqrt()
int32_t _IQ18isqrt (int32_t a)
Calculate inverse square root of an IQ18 input.
Parameters
a IQ18 type input.
Returns
IQ18 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ17isqrt()
int32_t _IQ17isqrt (int32_t a)
Calculate inverse square root of an IQ17 input.
Parameters
a IQ17 type input.
Returns
IQ17 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ16isqrt()
int32_t _IQ16isqrt (int32_t a)
Calculate inverse square root of an IQ16 input.
Parameters
a IQ16 type input.
Returns
IQ16 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ15isqrt()
int32_t _IQ15isqrt (int32_t a)
Calculate inverse square root of an IQ15 input.
Parameters
a IQ15 type input.
Returns
IQ15 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ14isqrt()
int32_t _IQ14isqrt (int32_t a)
Calculate inverse square root of an IQ14 input.
Parameters
a IQ14 type input.
Returns
IQ14 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ13isqrt()
int32_t _IQ13isqrt (int32_t a)
Calculate inverse square root of an IQ13 input.
Parameters
a IQ13 type input.
Returns
IQ13 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ12isqrt()
int32_t _IQ12isqrt (int32_t a)
Calculate inverse square root of an IQ12 input.
Parameters
a IQ12 type input.
Returns
IQ12 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ11isqrt()
int32_t _IQ11isqrt (int32_t a)
Calculate inverse square root of an IQ11 input.
Parameters
a IQ11 type input.
Returns
IQ11 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ10isqrt()
int32_t _IQ10isqrt (int32_t a)
Calculate inverse square root of an IQ10 input.
Parameters
a IQ10 type input.
Returns
IQ10 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ9isqrt()
int32_t _IQ9isqrt (int32_t a)
Calculate inverse square root of an IQ9 input.
Parameters
a IQ9 type input.
Returns
IQ9 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ8isqrt()
int32_t _IQ8isqrt (int32_t a)
Calculate inverse square root of an IQ8 input.
Parameters
a IQ8 type input.
Returns
IQ8 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ7isqrt()
int32_t _IQ7isqrt (int32_t a)
Calculate inverse square root of an IQ7 input.
Parameters
a IQ7 type input.
Returns
IQ7 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ6isqrt()
int32_t _IQ6isqrt (int32_t a)
Calculate inverse square root of an IQ6 input.
Parameters
a IQ6 type input.
Returns
IQ6 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ5isqrt()
int32_t _IQ5isqrt (int32_t a)
Calculate inverse square root of an IQ5 input.
Parameters
a IQ5 type input.
Returns
IQ5 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ4isqrt()
int32_t _IQ4isqrt (int32_t a)
Calculate inverse square root of an IQ4 input.
Parameters
a IQ4 type input.
Returns
IQ4 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ3isqrt()
int32_t _IQ3isqrt (int32_t a)
Calculate inverse square root of an IQ3 input.
Parameters
a IQ3 type input.
Returns
IQ3 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ2isqrt()
int32_t _IQ2isqrt (int32_t a)
Calculate inverse square root of an IQ2 input.
Parameters
a IQ2 type input.
Returns
IQ2 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQ1isqrt()
int32_t _IQ1isqrt (int32_t a)
Calculate inverse square root of an IQ1 input.
Parameters
a IQ1 type input.
Returns
IQ1 type result of the inverse square root operation.
References __IQNsqrt(), and TYPE_ISQRT.
_IQmag()
int32_t _IQmag (int32_t a, int32_t b)
Calculate the magnitude of two IQ31 inputs.
Parameters
a IQ31 type input.
b IQ31 type input.
Returns
IQ31 type result of the magnitude operation.
References __IQNsqrt(), and TYPE_MAG.
_IQ30imag()
int32_t _IQ30imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ30 type input.
b IQ30 type input.
Returns
IQ30 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ29imag()
int32_t _IQ29imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ29 type input.
b IQ29 type input.
Returns
IQ29 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ28imag()
int32_t _IQ28imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ28 type input.
b IQ28 type input.
Returns
IQ28 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ27imag()
int32_t _IQ27imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ27 type input.
b IQ27 type input.
Returns
IQ27 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ26imag()
int32_t _IQ26imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ26 type input.
b IQ26 type input.
Returns
IQ26 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ25imag()
int32_t _IQ25imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ25 type input.
b IQ25 type input.
Returns
IQ25 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ24imag()
int32_t _IQ24imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ24 type input.
b IQ24 type input.
Returns
IQ24 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ23imag()
int32_t _IQ23imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ23 type input.
b IQ23 type input.
Returns
IQ23 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ22imag()
int32_t _IQ22imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ22 type input.
b IQ22 type input.
Returns
IQ22 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ21imag()
int32_t _IQ21imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ21 type input.
b IQ21 type input.
Returns
IQ21 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ20imag()
int32_t _IQ20imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ20 type input.
b IQ20 type input.
Returns
IQ20 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ19imag()
int32_t _IQ19imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ19 type input.
b IQ19 type input.
Returns
IQ19 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ18imag()
int32_t _IQ18imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ18 type input.
b IQ18 type input.
Returns
IQ18 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ17imag()
int32_t _IQ17imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ17 type input.
b IQ17 type input.
Returns
IQ17 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ16imag()
int32_t _IQ16imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ16 type input.
b IQ16 type input.
Returns
IQ16 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ15imag()
int32_t _IQ15imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ15 type input.
b IQ15 type input.
Returns
IQ15 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ14imag()
int32_t _IQ14imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ14 type input.
b IQ14 type input.
Returns
IQ14 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ13imag()
int32_t _IQ13imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ13 type input.
b IQ13 type input.
Returns
IQ13 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ12imag()
int32_t _IQ12imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ12 type input.
b IQ12 type input.
Returns
IQ12 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ11imag()
int32_t _IQ11imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ11 type input.
b IQ11 type input.
Returns
IQ11 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ10imag()
int32_t _IQ10imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ10 type input.
b IQ10 type input.
Returns
IQ10 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ9imag()
int32_t _IQ9imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ9 type input.
b IQ9 type input.
Returns
IQ9 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ8imag()
int32_t _IQ8imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ8 type input.
b IQ8 type input.
Returns
IQ8 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ7imag()
int32_t _IQ7imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ7 type input.
b IQ7 type input.
Returns
IQ7 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ6imag()
int32_t _IQ6imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ6 type input.
b IQ6 type input.
Returns
IQ6 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ5imag()
int32_t _IQ5imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ5 type input.
b IQ5 type input.
Returns
IQ5 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ4imag()
int32_t _IQ4imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ4 type input.
b IQ4 type input.
Returns
IQ4 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ3imag()
int32_t _IQ3imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ3 type input.
b IQ3 type input.
Returns
IQ3 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ2imag()
int32_t _IQ2imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ2 type input.
b IQ2 type input.
Returns
IQ2 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
_IQ1imag()
int32_t _IQ1imag (int32_t a, int32_t b)
Calculate inverse magnitude of two inputs.
Parameters
a IQ1 type input.
b IQ1 type input.
Returns
IQ1 type result of the inverse magnitude operation.
References __IQNsqrt(), and TYPE_IMAG.
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale