IQMathLibrary: _IQNlog.c File Reference
_IQNlog.c File Reference
Detailed Description
Functions to compute the base-e logarithm of an IQN number.
#include <stdint.h>
#include "../support/support.h"
#include "_IQNtables.h"
Functions
__STATIC_INLINE int_fast32_t __IQNlog (int_fast32_t iqNInput, const int_fast32_t iqNMin, const int8_t q_value)
Computes the base-e logarithm of an IQN input.
int32_t _IQ30log (int32_t a)
Computes the base-e logarithm of an IQ30 input.
int32_t _IQ29log (int32_t a)
Computes the base-e logarithm of an IQ29 input.
int32_t _IQ28log (int32_t a)
Computes the base-e logarithm of an IQ28 input.
int32_t _IQ27log (int32_t a)
Computes the base-e logarithm of an IQ27 input.
int32_t _IQ26log (int32_t a)
Computes the base-e logarithm of an IQ26 input.
int32_t _IQ25log (int32_t a)
Computes the base-e logarithm of an IQ25 input.
int32_t _IQ24log (int32_t a)
Computes the base-e logarithm of an IQ24 input.
int32_t _IQ23log (int32_t a)
Computes the base-e logarithm of an IQ23 input.
int32_t _IQ22log (int32_t a)
Computes the base-e logarithm of an IQ22 input.
int32_t _IQ21log (int32_t a)
Computes the base-e logarithm of an IQ21 input.
int32_t _IQ20log (int32_t a)
Computes the base-e logarithm of an IQ20 input.
int32_t _IQ19log (int32_t a)
Computes the base-e logarithm of an IQ19 input.
int32_t _IQ18log (int32_t a)
Computes the base-e logarithm of an IQ18 input.
int32_t _IQ17log (int32_t a)
Computes the base-e logarithm of an IQ17 input.
int32_t _IQ16log (int32_t a)
Computes the base-e logarithm of an IQ16 input.
int32_t _IQ15log (int32_t a)
Computes the base-e logarithm of an IQ15 input.
int32_t _IQ14log (int32_t a)
Computes the base-e logarithm of an IQ14 input.
int32_t _IQ13log (int32_t a)
Computes the base-e logarithm of an IQ13 input.
int32_t _IQ12log (int32_t a)
Computes the base-e logarithm of an IQ12 input.
int32_t _IQ11log (int32_t a)
Computes the base-e logarithm of an IQ11 input.
int32_t _IQ10log (int32_t a)
Computes the base-e logarithm of an IQ10 input.
int32_t _IQ9log (int32_t a)
Computes the base-e logarithm of an IQ9 input.
int32_t _IQ8log (int32_t a)
Computes the base-e logarithm of an IQ8 input.
int32_t _IQ7log (int32_t a)
Computes the base-e logarithm of an IQ7 input.
int32_t _IQ6log (int32_t a)
Computes the base-e logarithm of an IQ6 input.
int32_t _IQ5log (int32_t a)
Computes the base-e logarithm of an IQ5 input.
int32_t _IQ4log (int32_t a)
Computes the base-e logarithm of an IQ4 input.
int32_t _IQ3log (int32_t a)
Computes the base-e logarithm of an IQ3 input.
int32_t _IQ2log (int32_t a)
Computes the base-e logarithm of an IQ2 input.
int32_t _IQ1log (int32_t a)
Computes the base-e logarithm of an IQ1 input.
Function Documentation
__IQNlog()
__STATIC_INLINE int_fast32_t __IQNlog (int_fast32_t iqNInput, const int_fast32_t iqNMin, const int8_t q_value)
Computes the base-e logarithm of an IQN input.
Parameters
iqNInput IQN type input.
iqNMin Minimum parameter value.
q_value IQ format.
Returns
IQN type result of exponential.
Referenced by _IQ10log(), _IQ11log(), _IQ12log(), _IQ13log(), _IQ14log(), _IQ15log(), _IQ16log(), _IQ17log(), _IQ18log(), _IQ19log(), _IQ1log(), _IQ20log(), _IQ21log(), _IQ22log(), _IQ23log(), _IQ24log(), _IQ25log(), _IQ26log(), _IQ27log(), _IQ28log(), _IQ29log(), _IQ2log(), _IQ30log(), _IQ3log(), _IQ4log(), _IQ5log(), _IQ6log(), _IQ7log(), _IQ8log(), and _IQ9log().
_IQ30log()
int32_t _IQ30log (int32_t a)
Computes the base-e logarithm of an IQ30 input.
Parameters
a IQ30 type input.
Returns
IQ30 type result of exponential.
References __IQNlog().
_IQ29log()
int32_t _IQ29log (int32_t a)
Computes the base-e logarithm of an IQ29 input.
Parameters
a IQ29 type input.
Returns
IQ29 type result of exponential.
References __IQNlog().
_IQ28log()
int32_t _IQ28log (int32_t a)
Computes the base-e logarithm of an IQ28 input.
Parameters
a IQ28 type input.
Returns
IQ28 type result of exponential.
References __IQNlog().
_IQ27log()
int32_t _IQ27log (int32_t a)
Computes the base-e logarithm of an IQ27 input.
Parameters
a IQ27 type input.
Returns
IQ27 type result of exponential.
References __IQNlog().
_IQ26log()
int32_t _IQ26log (int32_t a)
Computes the base-e logarithm of an IQ26 input.
Parameters
a IQ26 type input.
Returns
IQ26 type result of exponential.
References __IQNlog().
_IQ25log()
int32_t _IQ25log (int32_t a)
Computes the base-e logarithm of an IQ25 input.
Parameters
a IQ25 type input.
Returns
IQ25 type result of exponential.
References __IQNlog().
_IQ24log()
int32_t _IQ24log (int32_t a)
Computes the base-e logarithm of an IQ24 input.
Parameters
a IQ24 type input.
Returns
IQ24 type result of exponential.
References __IQNlog().
_IQ23log()
int32_t _IQ23log (int32_t a)
Computes the base-e logarithm of an IQ23 input.
Parameters
a IQ23 type input.
Returns
IQ23 type result of exponential.
References __IQNlog().
_IQ22log()
int32_t _IQ22log (int32_t a)
Computes the base-e logarithm of an IQ22 input.
Parameters
a IQ22 type input.
Returns
IQ22 type result of exponential.
References __IQNlog().
_IQ21log()
int32_t _IQ21log (int32_t a)
Computes the base-e logarithm of an IQ21 input.
Parameters
a IQ21 type input.
Returns
IQ21 type result of exponential.
References __IQNlog().
_IQ20log()
int32_t _IQ20log (int32_t a)
Computes the base-e logarithm of an IQ20 input.
Parameters
a IQ20 type input.
Returns
IQ20 type result of exponential.
References __IQNlog().
_IQ19log()
int32_t _IQ19log (int32_t a)
Computes the base-e logarithm of an IQ19 input.
Parameters
a IQ19 type input.
Returns
IQ19 type result of exponential.
References __IQNlog().
_IQ18log()
int32_t _IQ18log (int32_t a)
Computes the base-e logarithm of an IQ18 input.
Parameters
a IQ18 type input.
Returns
IQ18 type result of exponential.
References __IQNlog().
_IQ17log()
int32_t _IQ17log (int32_t a)
Computes the base-e logarithm of an IQ17 input.
Parameters
a IQ17 type input.
Returns
IQ17 type result of exponential.
References __IQNlog().
_IQ16log()
int32_t _IQ16log (int32_t a)
Computes the base-e logarithm of an IQ16 input.
Parameters
a IQ16 type input.
Returns
IQ16 type result of exponential.
References __IQNlog().
_IQ15log()
int32_t _IQ15log (int32_t a)
Computes the base-e logarithm of an IQ15 input.
Parameters
a IQ15 type input.
Returns
IQ15 type result of exponential.
References __IQNlog().
_IQ14log()
int32_t _IQ14log (int32_t a)
Computes the base-e logarithm of an IQ14 input.
Parameters
a IQ14 type input.
Returns
IQ14 type result of exponential.
References __IQNlog().
_IQ13log()
int32_t _IQ13log (int32_t a)
Computes the base-e logarithm of an IQ13 input.
Parameters
a IQ13 type input.
Returns
IQ13 type result of exponential.
References __IQNlog().
_IQ12log()
int32_t _IQ12log (int32_t a)
Computes the base-e logarithm of an IQ12 input.
Parameters
a IQ12 type input.
Returns
IQ12 type result of exponential.
References __IQNlog().
_IQ11log()
int32_t _IQ11log (int32_t a)
Computes the base-e logarithm of an IQ11 input.
Parameters
a IQ11 type input.
Returns
IQ11 type result of exponential.
References __IQNlog().
_IQ10log()
int32_t _IQ10log (int32_t a)
Computes the base-e logarithm of an IQ10 input.
Parameters
a IQ10 type input.
Returns
IQ10 type result of exponential.
References __IQNlog().
_IQ9log()
int32_t _IQ9log (int32_t a)
Computes the base-e logarithm of an IQ9 input.
Parameters
a IQ9 type input.
Returns
IQ9 type result of exponential.
References __IQNlog().
_IQ8log()
int32_t _IQ8log (int32_t a)
Computes the base-e logarithm of an IQ8 input.
Parameters
a IQ8 type input.
Returns
IQ8 type result of exponential.
References __IQNlog().
_IQ7log()
int32_t _IQ7log (int32_t a)
Computes the base-e logarithm of an IQ7 input.
Parameters
a IQ7 type input.
Returns
IQ7 type result of exponential.
References __IQNlog().
_IQ6log()
int32_t _IQ6log (int32_t a)
Computes the base-e logarithm of an IQ6 input.
Parameters
a IQ6 type input.
Returns
IQ6 type result of exponential.
References __IQNlog().
_IQ5log()
int32_t _IQ5log (int32_t a)
Computes the base-e logarithm of an IQ5 input.
Parameters
a IQ5 type input.
Returns
IQ5 type result of exponential.
References __IQNlog().
_IQ4log()
int32_t _IQ4log (int32_t a)
Computes the base-e logarithm of an IQ4 input.
Parameters
a IQ4 type input.
Returns
IQ4 type result of exponential.
References __IQNlog().
_IQ3log()
int32_t _IQ3log (int32_t a)
Computes the base-e logarithm of an IQ3 input.
Parameters
a IQ3 type input.
Returns
IQ3 type result of exponential.
References __IQNlog().
_IQ2log()
int32_t _IQ2log (int32_t a)
Computes the base-e logarithm of an IQ2 input.
Parameters
a IQ2 type input.
Returns
IQ2 type result of exponential.
References __IQNlog().
_IQ1log()
int32_t _IQ1log (int32_t a)
Computes the base-e logarithm of an IQ1 input.
Parameters
a IQ1 type input.
Returns
IQ1 type result of exponential.
References __IQNlog().
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale