IQMathLibrary: _IQNtoF.c File Reference
_IQNtoF.c File Reference
Detailed Description
Functions to convert IQN type to floating point.
#include <stdint.h>
#include "../support/support.h"
Functions
__STATIC_INLINE float __IQNtoF (int_fast32_t iqNInput, int8_t q_value)
Converts IQN type to floating point.
float _IQ30toF (int32_t a)
Converts input to floating point using IQ30 format.
float _IQ29toF (int32_t a)
Converts input to floating point using IQ29 format.
float _IQ28toF (int32_t a)
Converts input to floating point using IQ28 format.
float _IQ27toF (int32_t a)
Converts input to floating point using IQ27 format.
float _IQ26toF (int32_t a)
Converts input to floating point using IQ26 format.
float _IQ25toF (int32_t a)
Converts input to floating point using IQ25 format.
float _IQ24toF (int32_t a)
Converts input to floating point using IQ24 format.
float _IQ23toF (int32_t a)
Converts input to floating point using IQ23 format.
float _IQ22toF (int32_t a)
Converts input to floating point using IQ22 format.
float _IQ21toF (int32_t a)
Converts input to floating point using IQ21 format.
float _IQ20toF (int32_t a)
Converts input to floating point using IQ20 format.
float _IQ19toF (int32_t a)
Converts input to floating point using IQ19 format.
float _IQ18toF (int32_t a)
Converts input to floating point using IQ18 format.
float _IQ17toF (int32_t a)
Converts input to floating point using IQ17 format.
float _IQ16toF (int32_t a)
Converts input to floating point using IQ16 format.
float _IQ15toF (int32_t a)
Converts input to floating point using IQ15 format.
float _IQ14toF (int32_t a)
Converts input to floating point using IQ14 format.
float _IQ13toF (int32_t a)
Converts input to floating point using IQ13 format.
float _IQ12toF (int32_t a)
Converts input to floating point using IQ12 format.
float _IQ11toF (int32_t a)
Converts input to floating point using IQ11 format.
float _IQ10toF (int32_t a)
Converts input to floating point using IQ10 format.
float _IQ9toF (int32_t a)
Converts input to floating point using IQ9 format.
float _IQ8toF (int32_t a)
Converts input to floating point using IQ8 format.
float _IQ7toF (int32_t a)
Converts input to floating point using IQ7 format.
float _IQ6toF (int32_t a)
Converts input to floating point using IQ6 format.
float _IQ5toF (int32_t a)
Converts input to floating point using IQ5 format.
float _IQ4toF (int32_t a)
Converts input to floating point using IQ4 format.
float _IQ3toF (int32_t a)
Converts input to floating point using IQ3 format.
float _IQ2toF (int32_t a)
Converts input to floating point using IQ2 format.
float _IQ1toF (int32_t a)
Converts input to floating point using IQ1 format.
Function Documentation
__IQNtoF()
__STATIC_INLINE float __IQNtoF (int_fast32_t iqNInput, int8_t q_value)
Converts IQN type to floating point.
Parameters
iqNInput IQN type value input to be converted.
q_value IQ format.
Returns
Conversion of iqNInput to floating point.
Referenced by _IQ10toF(), _IQ11toF(), _IQ12toF(), _IQ13toF(), _IQ14toF(), _IQ15toF(), _IQ16toF(), _IQ17toF(), _IQ18toF(), _IQ19toF(), _IQ1toF(), _IQ20toF(), _IQ21toF(), _IQ22toF(), _IQ23toF(), _IQ24toF(), _IQ25toF(), _IQ26toF(), _IQ27toF(), _IQ28toF(), _IQ29toF(), _IQ2toF(), _IQ30toF(), _IQ3toF(), _IQ4toF(), _IQ5toF(), _IQ6toF(), _IQ7toF(), _IQ8toF(), and _IQ9toF().
_IQ30toF()
float _IQ30toF (int32_t a)
Converts input to floating point using IQ30 format.
Parameters
a IQ30 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ29toF()
float _IQ29toF (int32_t a)
Converts input to floating point using IQ29 format.
Parameters
a IQ29 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ28toF()
float _IQ28toF (int32_t a)
Converts input to floating point using IQ28 format.
Parameters
a IQ28 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ27toF()
float _IQ27toF (int32_t a)
Converts input to floating point using IQ27 format.
Parameters
a IQ27 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ26toF()
float _IQ26toF (int32_t a)
Converts input to floating point using IQ26 format.
Parameters
a IQ26 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ25toF()
float _IQ25toF (int32_t a)
Converts input to floating point using IQ25 format.
Parameters
a IQ25 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ24toF()
float _IQ24toF (int32_t a)
Converts input to floating point using IQ24 format.
Parameters
a IQ24 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ23toF()
float _IQ23toF (int32_t a)
Converts input to floating point using IQ23 format.
Parameters
a IQ23 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ22toF()
float _IQ22toF (int32_t a)
Converts input to floating point using IQ22 format.
Parameters
a IQ22 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ21toF()
float _IQ21toF (int32_t a)
Converts input to floating point using IQ21 format.
Parameters
a IQ21 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ20toF()
float _IQ20toF (int32_t a)
Converts input to floating point using IQ20 format.
Parameters
a IQ20 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ19toF()
float _IQ19toF (int32_t a)
Converts input to floating point using IQ19 format.
Parameters
a IQ19 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ18toF()
float _IQ18toF (int32_t a)
Converts input to floating point using IQ18 format.
Parameters
a IQ18 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ17toF()
float _IQ17toF (int32_t a)
Converts input to floating point using IQ17 format.
Parameters
a IQ17 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ16toF()
float _IQ16toF (int32_t a)
Converts input to floating point using IQ16 format.
Parameters
a IQ16 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ15toF()
float _IQ15toF (int32_t a)
Converts input to floating point using IQ15 format.
Parameters
a IQ15 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ14toF()
float _IQ14toF (int32_t a)
Converts input to floating point using IQ14 format.
Parameters
a IQ14 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ13toF()
float _IQ13toF (int32_t a)
Converts input to floating point using IQ13 format.
Parameters
a IQ13 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ12toF()
float _IQ12toF (int32_t a)
Converts input to floating point using IQ12 format.
Parameters
a IQ12 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ11toF()
float _IQ11toF (int32_t a)
Converts input to floating point using IQ11 format.
Parameters
a IQ11 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ10toF()
float _IQ10toF (int32_t a)
Converts input to floating point using IQ10 format.
Parameters
a IQ10 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ9toF()
float _IQ9toF (int32_t a)
Converts input to floating point using IQ9 format.
Parameters
a IQ9 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ8toF()
float _IQ8toF (int32_t a)
Converts input to floating point using IQ8 format.
Parameters
a IQ8 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ7toF()
float _IQ7toF (int32_t a)
Converts input to floating point using IQ7 format.
Parameters
a IQ7 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ6toF()
float _IQ6toF (int32_t a)
Converts input to floating point using IQ6 format.
Parameters
a IQ6 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ5toF()
float _IQ5toF (int32_t a)
Converts input to floating point using IQ5 format.
Parameters
a IQ5 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ4toF()
float _IQ4toF (int32_t a)
Converts input to floating point using IQ4 format.
Parameters
a IQ4 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ3toF()
float _IQ3toF (int32_t a)
Converts input to floating point using IQ3 format.
Parameters
a IQ3 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ2toF()
float _IQ2toF (int32_t a)
Converts input to floating point using IQ2 format.
Parameters
a IQ2 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
_IQ1toF()
float _IQ1toF (int32_t a)
Converts input to floating point using IQ1 format.
Parameters
a IQ1 type value to be converted.
Returns
Conversion of input to floating point.
References __IQNtoF().
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale