MSPM0G3507HallSensoredTrapMotorControlLibrary: Motor Driver/DRV8329
Motor Driver/DRV8329
Data Structures
struct DRV8329_Instance
Defines drv8329 instance.
Macros
#define DRV8329_MAXIMUM_WAKEUP_TIME (2000)
Defines the time to wakeup the drv after reset.
#define DRV8329_VOLTAGE_CONV_CONST _IQ20(23.044)
Defines voltage conversion constant.
#define DRV8329_CSA_REF_VOLTAGE (3300)
Defines CSA reference voltage.
#define DRV8329_CSAGAIN_5_IQ _IQ20(5)
Defines CSA gains 5 in IQ20.
#define DRV8329_CSAGAIN_10_IQ _IQ20(10)
Defines CSA gains 10 in IQ20.
#define DRV8329_CSAGAIN_20_IQ _IQ20(20)
Defines CSA gains 20 in IQ20.
#define DRV8329_CSAGAIN_40_IQ _IQ20(40)
Defines CSA gains 40 in IQ20.
Enumerations
enum DRV8329_CSAGAIN {
DRV8329_CSAGAIN_5 = 0 << 0,
DRV8329_CSAGAIN_10 = 1 << 0,
DRV8329_CSAGAIN_20 = 2 << 0,
DRV8329_CSAGAIN_40 = 3 << 0
}
enum DRV8329_DRVOFF_PIN_STAT {
DRV8329_DRVOFF_PIN_LOW = HAL_GPIO_PIN_LOW,
DRV8329_DRVOFF_PIN_HIGH = HAL_GPIO_PIN_HIGH
}
enum DRV8329_DRV_NSLEEP_STAT {
DRV8329_DRV_NSLEEP_SLEEP = HAL_GPIO_PIN_LOW,
DRV8329_DRV_NSLEEP_AWAKE = HAL_GPIO_PIN_HIGH
}
Represents NSLEEP Pin State.
Functions
__STATIC_INLINE void DRV8329_setDrvoff (DRV8329_Instance *drvHandle, DRV8329_DRVOFF_PIN_STAT value)
set drvoff
__STATIC_INLINE void DRV8329_setnSleep (DRV8329_Instance *drvHandle, DRV8329_DRV_NSLEEP_STAT value)
set nSleep
__STATIC_INLINE _iq20 DRV8329_getcsaVref (uint16_t vRef)
get Current reference in IQ20
void DRV8329_init (DRV8329_Instance *drvHandle)
initialize the drv8329 module
void DRV8329_enable (DRV8329_Instance *drvHandle)
Enable DRV.
void DRV8329_updateCSAScaleFactor (DRV8329_Instance *drvHandle, DRV8329_CSAGAIN csa, uint16_t rSense)
updates the current gain scale factor
_iq20 DRV8329_getVoltage (HAL_ADC_CHAN chan)
Get voltage from adc channel.
_iq20 DRV8329_getCurrent (HAL_ADC_CHAN chan, DRV8329_Instance *drvHandle, _iq20 vRef)
Get current from adc channel.
void DRV8329_ADCVRefSel (HAL_ADC_VREF adcRef, HAL_ADC_CHAN chan, HAL_ADC_INT_VREF internalVRef, uint16_t externalVRef)
updates the adc voltage reference
Detailed Description
Enumeration Type Documentation
DRV8329_CSAGAIN
enum DRV8329_CSAGAIN
Enumerator
DRV8329_CSAGAIN_5
Define DRV8329 CSA GAIN 5 Setting.
DRV8329_CSAGAIN_10
Define DRV8329 CSA GAIN 10 Setting.
DRV8329_CSAGAIN_20
Define DRV8329 CSA GAIN 20 Setting.
DRV8329_CSAGAIN_40
Define DRV8329 CSA GAIN 40 Setting.
DRV8329_DRVOFF_PIN_STAT
enum DRV8329_DRVOFF_PIN_STAT
Enumerator
DRV8329_DRVOFF_PIN_LOW
Define DRVOFF PIN LOW
DRV8329_DRVOFF_PIN_HIGH
Define DRVOFF PIN HIGH
DRV8329_DRV_NSLEEP_STAT
enum DRV8329_DRV_NSLEEP_STAT
Represents NSLEEP Pin State.
Enumerator
DRV8329_DRV_NSLEEP_SLEEP
Define NSLEEP PIN LOW.
DRV8329_DRV_NSLEEP_AWAKE
Define NSLEEP PIN HIGH.
Function Documentation
DRV8329_setDrvoff()
__STATIC_INLINE void DRV8329_setDrvoff (DRV8329_Instance * drvHandle, DRV8329_DRVOFF_PIN_STAT value)
set drvoff
Parameters
[in] drvHandle The drv instance
[in] value drvoff value
References DRV8329_DRVOFF_PIN_HIGH, DRV8329_DRVOFF_PIN_LOW, DRV8329_Instance::drvoff, HAL_GPIO_PIN_HIGH, HAL_GPIO_PIN_LOW, and HAL_writeGPIOPin().
Referenced by DRV8329_enable().
DRV8329_setnSleep()
__STATIC_INLINE void DRV8329_setnSleep (DRV8329_Instance * drvHandle, DRV8329_DRV_NSLEEP_STAT value)
set nSleep
Parameters
[in] drvHandle The drv instance
[in] value nSleep value
References DRV8329_DRV_NSLEEP_AWAKE, DRV8329_DRV_NSLEEP_SLEEP, DRV8329_MAXIMUM_WAKEUP_TIME, HAL_delayMicroSeconds(), HAL_GPIO_PIN_HIGH, HAL_GPIO_PIN_LOW, HAL_writeGPIOPin(), and DRV8329_Instance::nsleep.
Referenced by DRV8329_enable().
DRV8329_getcsaVref()
__STATIC_INLINE _iq20 DRV8329_getcsaVref (uint16_t vRef)
get Current reference in IQ20
Parameters
[in] vRef CSA reference voltage in milli volts
Returns
_iq20 CSA reference voltage in _iq20 format
References DRV8329_ADCVRefSel(), DRV8329_enable(), DRV8329_getCurrent(), DRV8329_getVoltage(), DRV8329_init(), and DRV8329_updateCSAScaleFactor().
DRV8329_init()
void DRV8329_init (DRV8329_Instance * drvHandle)
initialize the drv8329 module
Parameters
[in] drvHandle The drv8329 instance
References HAL_enableADCInterrupt(), DRV8329_Instance::Isen, DRV8329_Instance::Vsen, DRV8329_Instance::VsenA, DRV8329_Instance::VsenB, and DRV8329_Instance::VsenC.
Referenced by DRV8329_getcsaVref().
DRV8329_enable()
void DRV8329_enable (DRV8329_Instance * drvHandle)
Enable DRV.
Parameters
[in] drvHandle The drv8329 instance
References DRV8329_DRV_NSLEEP_AWAKE, DRV8329_DRV_NSLEEP_SLEEP, DRV8329_DRVOFF_PIN_LOW, DRV8329_setDrvoff(), and DRV8329_setnSleep().
Referenced by DRV8329_getcsaVref().
DRV8329_updateCSAScaleFactor()
void DRV8329_updateCSAScaleFactor (DRV8329_Instance * drvHandle, DRV8329_CSAGAIN csa, uint16_t rSense)
updates the current gain scale factor
Parameters
[in] drvHandle The drv8329 instance
[in] csa drv8329 CSA gain value
[in] rSense shunt resistance
References DRV8329_Instance::csa_sf, DRV8329_CSAGAIN_10, DRV8329_CSAGAIN_10_IQ, DRV8329_CSAGAIN_20, DRV8329_CSAGAIN_20_IQ, DRV8329_CSAGAIN_40, DRV8329_CSAGAIN_40_IQ, DRV8329_CSAGAIN_5, and DRV8329_CSAGAIN_5_IQ.
Referenced by DRV8329_getcsaVref().
DRV8329_getVoltage()
_iq20 DRV8329_getVoltage (HAL_ADC_CHAN chan)
Get voltage from adc channel.
Parameters
[in] chan The ADC channel name
Returns
Return
References DRV8329_VOLTAGE_CONV_CONST, and HAL_getIQ20VoltageFromADC().
Referenced by DRV8329_getcsaVref().
DRV8329_getCurrent()
_iq20 DRV8329_getCurrent (HAL_ADC_CHAN chan, DRV8329_Instance * drvHandle, _iq20 vRef)
Get current from adc channel.
Parameters
[in] chan The ADC channel name
[in] drvHandle The drv instance
[in] vRef voltage reference for current
Returns
Return
References DRV8329_Instance::csa_sf, and HAL_getIQ20VoltageFromADC().
Referenced by DRV8329_getcsaVref().
DRV8329_ADCVRefSel()
void DRV8329_ADCVRefSel (HAL_ADC_VREF adcRef, HAL_ADC_CHAN chan, HAL_ADC_INT_VREF internalVRef, uint16_t externalVRef)
updates the adc voltage reference
Parameters
[in] adcRef ADC voltage reference
[in] chan The ADC channel name
[in] internalVRef Internal reference voltage
[in] externalVRef External reference voltage
References HAL_ADC_VREF_EXTERNAL, HAL_ADC_VREF_INTERNAL, HAL_ADC_VREF_VDDA, HAL_setADCVRefExternal(), HAL_setADCVRefInternal(), and HAL_setADCVRefVDDA().
Referenced by DRV8329_getcsaVref().
© Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale