BrushedMotorControlLibrary: DRV8706-Q1 - Motor Driver Module
DRV8706-Q1 - Motor Driver Module
Data Structures
struct DRV8706Q1_INSTANCE
Internal structure that represents a specific DRV8706-Q1.
Enumerations
enum DRV8706Q1_MODES {
DRV8706Q1_H_BRIDGE = 0,
DRV8706Q1_PH_EN,
DRV8706Q1_HALF_BRIDGE,
DRV8706Q1_SPLIT_SOLENOID
}
Represents the four different input control modes the DRV8706-Q1 supports.
enum DRV8706Q1_H_BRIDGE_DRIVES {
DRV8706Q1_H_BRIDGE_COAST = 0,
DRV8706Q1_H_BRIDGE_REVERSE,
DRV8706Q1_H_BRIDGE_FORWARD,
DRV8706Q1_H_BRIDGE_ACTIVE_FREEWHEEL
}
Represents all the different configurations the H-Bridge control mode supports.
enum DRV8706Q1_PHASE_DRIVES {
DRV8706Q1_PHASE_REVERSE = 0,
DRV8706Q1_PHASE_FORWARD,
DRV8706Q1_PHASE_ACTIVE_FREEWHEEL
}
Represents all the different configurations the Phase Enable control mode supports.
enum DRV8706Q1_SOLENOID_DRIVES {
DRV8706Q1_SOLENOID_DISABLE = 0,
DRV8706Q1_SOLENOID_PWM
}
Represents all the different configurations the Solenoid control mode supports.
enum DRV8706Q1_HALF_BRIDGE_DRIVES {
DRV8706Q1_HALF_BRIDGE_HI_Z = 0,
DRV8706Q1_HALF_BRIDGE_PWM
}
Represents all the different configurations the Half Bridge control mode supports.
enum DRV8706Q1_PWM_CHANNELS {
DRV8706Q1_PWM_CHANNEL_0 = 0,
DRV8706Q1_PWM_CHANNEL_1
}
Represents the motor driver's input pins that expects a PWM signal.
enum DRV8706Q1_SPI_ADDR {
DRV8706Q1_SPI_ADDR_IC_STAT_1 = 0,
DRV8706Q1_SPI_ADDR_VGS_VDS_STAT,
DRV8706Q1_SPI_ADDR_IC_STAT_2,
DRV8706Q1_SPI_ADDR_RSVD_STAT,
DRV8706Q1_SPI_ADDR_IC_CTRL,
DRV8706Q1_SPI_ADDR_BRG_CTRL,
DRV8706Q1_SPI_ADDR_DRV_CTRL_1,
DRV8706Q1_SPI_ADDR_DRV_CTRL_2,
DRV8706Q1_SPI_ADDR_DRV_CTRL_3,
DRV8706Q1_SPI_ADDR_VDS_CTRL_1,
DRV8706Q1_SPI_ADDR_VDS_CTRL_2,
DRV8706Q1_SPI_ADDR_OLSC_CTRL,
DRV8706Q1_SPI_ADDR_UVOV_CTRL,
DRV8706Q1_SPI_ADDR_CSA_CTRL
}
Represents the addresses for all the SPI registers.
enum DRV8706Q1_CSA_GAINS {
DRV8706Q1_CSA_GAIN_10 = 10,
DRV8706Q1_CSA_GAIN_20 = 20,
DRV8706Q1_CSA_GAIN_40 = 40,
DRV8706Q1_CSA_GAIN_80 = 80
}
Represents all the current sense amplifier gain settings.
enum DRV8706Q1_CSA_DIV {
DRV8706Q1_CSA_DIV_2 = 2,
DRV8706Q1_CSA_DIV_8 = 8
}
Represents all the current sense amplifier reference voltage divider settings.
Functions
void DRV8706Q1_init (DRV8706Q1_INSTANCE *drv)
Initialized critical structure representing specific instance of the motor driver. Important Not calling this function will result in unexpected results.
uint16_t DRV8706Q1_switchToHBridgeDrive (DRV8706Q1_INSTANCE *drv, DRV8706Q1_H_BRIDGE_DRIVES drive)
Function will program the motor driver to switch to H-bridge control mode and reconfigure the pin to the selected H-bridge mode pin configuration to use. Important Note this function updates the motor driver registers via SPI.
void DRV8706Q1_changeHBridgeDrive (DRV8706Q1_INSTANCE drv, DRV8706Q1_H_BRIDGE_DRIVES drive)
Function will reconfigure the pins for the specific H-bridge mode configuration. Unlike DRV8706Q1_switchToHBridgeDrive this function does not update the control mode via SPI. So the device must be configured to H-bridge mode already.
uint16_t DRV8706Q1_switchToPhaseDrive (DRV8706Q1_INSTANCE *drv, DRV8706Q1_PHASE_DRIVES drive)
Function will program the motor driver to switch to Phase control mode and reconfigure the pin to the selected Phase mode pin configuration to use. Note this function updates the motor driver registers via SPI.
void DRV8706Q1_changePhaseDrive (DRV8706Q1_INSTANCE drv, DRV8706Q1_PHASE_DRIVES drive)
Function will reconfigure the pins for the specific Phase enable mode configuration. Unlike DRV8706Q1_switchToPhaseDrive this function does not update the control mode via SPI. So the device must be configured to Phase enable mode already.
void DRV8706Q1_changeSolenoidDrive (DRV8706Q1_INSTANCE drv, DRV8706Q1_SOLENOID_DRIVES drive)
Function will reconfigure the pins for the specific Solenoid mode configuration. Unlike DRV8706Q1_switchToSolenoidDrive this function does not update the control mode via SPI. So the device must be configured to solenoid already.
void DRV8706Q1_changeHalfBridgeDrive (DRV8706Q1_INSTANCE drv, DRV8706Q1_PWM_CHANNELS drvChan, DRV8706Q1_HALF_BRIDGE_DRIVES drive)
Function will reconfigure the pins for the specific Half Bridge mode configuration. Unlike DRV8706Q1_switchToHalfBridgeDrive this function does not update the control mode via SPI. So the device must be configured to Phase enable mode already.
uint16_t DRV8706Q1_switchToHalfBridgeDrive (DRV8706Q1_INSTANCE *drv, DRV8706Q1_HALF_BRIDGE_DRIVES driveChan0, DRV8706Q1_HALF_BRIDGE_DRIVES driveChan1)
Function will reconfigure the pins for the specific Half Bridge mode configuration. Also the control mode will be updated via SPI.
uint16_t DRV8706Q1_switchToSolenoidDrive (DRV8706Q1_INSTANCE *drv, DRV8706Q1_SOLENOID_DRIVES drive)
Function will program the motor driver to switch to Solenoid control mode and reconfigure the pin to the selected Solenoid mode pin configuration to use. Note this function updates the motor driver registers via SPI.
uint16_t DRV8706Q1_spiUpdateRegister (DRV8706Q1_INSTANCE drv, DRV8706Q1_SPI_ADDR addr, uint8_t mask, uint8_t value)
Function to allow a user to modify a specific bitfield in one of the motor driver's registers. This function automatically converts the parameters to the data format needed for SPI communication with the DRV8706-Q1.
__STATIC_INLINE uint16_t DRV8706Q1_spiWriteCmd (DRV8706Q1_INSTANCE drv, DRV8706Q1_SPI_ADDR addr, uint8_t data)
Perform a SPI write operation. This function already converts the address and data to the data format required by the motor driver. Note that if the motor driver is sleeping then the motor driver will ignore the spi operation.
__STATIC_INLINE uint16_t DRV8706Q1_spiReadCmd (DRV8706Q1_INSTANCE drv, DRV8706Q1_SPI_ADDR addr)
Perform a SPI read operation. This function converts the address to the data format required by the motor driver. Note that if the motor driver is sleeping then the motor driver will ignore the spi operation and you will read back 0x0.
_iq20 DRV8706Q1_getCurrent (DRV8706Q1_INSTANCE drv)
Return the current read from the DRV8706-Q1 motor driver.
void DRV8706Q1_setDrivePWMFreq (DRV8706Q1_INSTANCE drv, DRV8706Q1_PWM_CHANNELS drvPwmChan, uint32_t value)
Sets the PWM frequency for the correct channel based on the drive specified.
void DRV8706Q1_setDriveDutyCycle (DRV8706Q1_INSTANCE drv, DRV8706Q1_PWM_CHANNELS drvPwmChan, uint8_t value)
Sets the duty cycle for the correct channel based on the drive specified.
void DRV8706Q1_reset (DRV8706Q1_INSTANCE *drv)
This functions resets the SPI registers of the motor driver by putting it to sleep, delaying and waking it up. Note that when this function is called the motor driver sleep pin will be high. This functional internally calls DRV8706Q1_powerOnResetVal.
void DRV8706Q1_powerOnResetVal (DRV8706Q1_INSTANCE *drv)
Reset internal DRV structure variables to sync with the motor driver registers power on reset value.
__STATIC_INLINE void DRV8706Q1_setNSleep (DRV8706Q1_INSTANCE drv, bool value)
Help function that controls the MCU pin connected to nSleep pin on the motor driver. Note if you manually set nSLEEP low for more than 1 ms then all the register values will be reset to their default values. Therefore, it would be important to immediately call DRV8706Q1_powerOnResetVal whenver you set nSLEEP to high to make sure internal structures are sync.
__STATIC_INLINE void DRV8706Q1_setDrvOff (DRV8706Q1_INSTANCE drv, bool value)
Help function that controls the MCU pin connected to DrvOff pin on the motor driver.
__STATIC_INLINE void DRV8706Q1_setNHiZ1 (DRV8706Q1_INSTANCE drv, bool value)
Help function that controls the MCU pin connected to nHiZ1 pin on the motor driver.
__STATIC_INLINE void DRV8706Q1_setNHiZ2 (DRV8706Q1_INSTANCE drv, bool value)
Help function that controls the MCU pin connected to nHiZ2 pin on the motor driver.
void DRV8706Q1_setAnalogReference (DRV8706Q1_INSTANCE *drv, _iq20 aRef_V)
Set voltage connected to the motor driver's AREF pin. This value is needed to properly calculate the motor's current.
uint16_t DRV8706Q1_setAnalogReferenceDivider (DRV8706Q1_INSTANCE *drv, DRV8706Q1_CSA_DIV csaDiv)
Set current shunt amplifier reference voltage divider. This function will update the CSA_CTRL.CSA_DIV register bitfield to the specified voltage divider.
uint16_t DRV8706Q1_setCurrentSenseGain (DRV8706Q1_INSTANCE *drv, DRV8706Q1_CSA_GAINS gcsa)
Configure the CSA to the gain setting specified. This function will update the CSA_CTRL.CSA_GAIN register bitfield with the gain you specified.
void DRV8706Q1_setCurrentShuntResistor (DRV8706Q1_INSTANCE *drv, _iq20 rShunt)
Set the current shunt resistor value used by the current sense amplifier. This value needs to be set based on the used by your hardware.
Detailed Description
Overview
The DRV8706-Q1 motor driver module utilizes the HAL's apis to control the drv8706-q1 brushed motor driver.
Enumeration Type Documentation
DRV8706Q1_MODES
enum DRV8706Q1_MODES
Represents the four different input control modes the DRV8706-Q1 supports.
Enumerator
DRV8706Q1_H_BRIDGE
DRV8706-Q1 H-Bridge Control Mode
DRV8706Q1_PH_EN
DRV8706-Q1 Phase Enable Control Mode
DRV8706Q1_HALF_BRIDGE
DRV8706-Q1 Half Bridge Control Mode
DRV8706Q1_SPLIT_SOLENOID
DRV8706-Q1 Solenoid Control Mode
DRV8706Q1_H_BRIDGE_DRIVES
enum DRV8706Q1_H_BRIDGE_DRIVES
Represents all the different configurations the H-Bridge control mode supports.
Enumerator
DRV8706Q1_H_BRIDGE_COAST
H-Bridge Mode Coast Configuration
DRV8706Q1_H_BRIDGE_REVERSE
H-Bridge Mode Reverse Configuration
DRV8706Q1_H_BRIDGE_FORWARD
H-Bridge Mode Forward Configuration
DRV8706Q1_H_BRIDGE_ACTIVE_FREEWHEEL
H-Bridge Mode Freewheel Configuration
DRV8706Q1_PHASE_DRIVES
enum DRV8706Q1_PHASE_DRIVES
Represents all the different configurations the Phase Enable control mode supports.
Enumerator
DRV8706Q1_PHASE_REVERSE
Phase Enable Mode Reverse Configuration
DRV8706Q1_PHASE_FORWARD
Phase Enable Mode Forward Configuration
DRV8706Q1_PHASE_ACTIVE_FREEWHEEL
Phase Enable Mode Freewheel Configuration
DRV8706Q1_SOLENOID_DRIVES
enum DRV8706Q1_SOLENOID_DRIVES
Represents all the different configurations the Solenoid control mode supports.
Enumerator
DRV8706Q1_SOLENOID_DISABLE
Solenoid Mode Disable Configuration
DRV8706Q1_SOLENOID_PWM
Solenoid Mode PWM Configuration
DRV8706Q1_HALF_BRIDGE_DRIVES
enum DRV8706Q1_HALF_BRIDGE_DRIVES
Represents all the different configurations the Half Bridge control mode supports.
Enumerator
DRV8706Q1_HALF_BRIDGE_HI_Z
Half-Bridge Mode Hi-Z Configuration
DRV8706Q1_HALF_BRIDGE_PWM
Half-Bridge Mode PWM Configuration
DRV8706Q1_PWM_CHANNELS
enum DRV8706Q1_PWM_CHANNELS
Represents the motor driver's input pins that expects a PWM signal.
Enumerator
DRV8706Q1_PWM_CHANNEL_0
MCU PWM pin connected to IN1/EN
DRV8706Q1_PWM_CHANNEL_1
MCU PWM pin connected to IN2/PH
DRV8706Q1_SPI_ADDR
enum DRV8706Q1_SPI_ADDR
Represents the addresses for all the SPI registers.
Enumerator
DRV8706Q1_SPI_ADDR_IC_STAT_1
Address value for IC_STAT_1 register
DRV8706Q1_SPI_ADDR_VGS_VDS_STAT
Address value for VGS_VDS_STAT register
DRV8706Q1_SPI_ADDR_IC_STAT_2
Address value for IC_STAT_2 register
DRV8706Q1_SPI_ADDR_RSVD_STAT
Address value for RSVD_STAT register
DRV8706Q1_SPI_ADDR_IC_CTRL
Address value for IC_CTRL register
DRV8706Q1_SPI_ADDR_BRG_CTRL
Address value for BRG_CTRL register
DRV8706Q1_SPI_ADDR_DRV_CTRL_1
Address value for DRV_CTRL_1 register
DRV8706Q1_SPI_ADDR_DRV_CTRL_2
Address value for DRV_CTRL_2 register
DRV8706Q1_SPI_ADDR_DRV_CTRL_3
Address value for DRV_CTRL_3 register
DRV8706Q1_SPI_ADDR_VDS_CTRL_1
Address value for VDS_CTRL_1 register
DRV8706Q1_SPI_ADDR_VDS_CTRL_2
Address value for VDS_CTRL_2 register
DRV8706Q1_SPI_ADDR_OLSC_CTRL
Address value for OLSC_CTRL register
DRV8706Q1_SPI_ADDR_UVOV_CTRL
Address value for UVOV_CTRL register
DRV8706Q1_SPI_ADDR_CSA_CTRL
Address value for CSA_CTRL register
DRV8706Q1_CSA_GAINS
enum DRV8706Q1_CSA_GAINS
Represents all the current sense amplifier gain settings.
Enumerator
DRV8706Q1_CSA_GAIN_10
For 10.15 V/V Gain Setting
DRV8706Q1_CSA_GAIN_20
For 20 V/V Gain Setting
DRV8706Q1_CSA_GAIN_40
For 40 V/V Gain Setting
DRV8706Q1_CSA_GAIN_80
For 80 V/V Gain Setting
DRV8706Q1_CSA_DIV
enum DRV8706Q1_CSA_DIV
Represents all the current sense amplifier reference voltage divider settings.
Enumerator
DRV8706Q1_CSA_DIV_2
Current shunt amplifier reference divided by 2
DRV8706Q1_CSA_DIV_8
Current shunt amplifier reference divided by 8
Function Documentation
DRV8706Q1_init()
void DRV8706Q1_init (DRV8706Q1_INSTANCE * drv)
Initialized critical structure representing specific instance of the motor driver. Important Not calling this function will result in unexpected results.
Parameters
drv Motor driver instances to use
References DRV8706Q1_INSTANCE::aRef_V, DRV8706Q1_INSTANCE::csaSF, DRV8706Q1_powerOnResetVal(), DRV8706Q1_PWM_CHANNEL_0, DRV8706Q1_PWM_CHANNEL_1, HAL_setDutyCycle(), HAL_setPWMFreq(), DRV8706Q1_INSTANCE::in1En, DRV8706Q1_INSTANCE::in2Ph, and DRV8706Q1_INSTANCE::shuntRes.
DRV8706Q1_switchToHBridgeDrive()
uint16_t DRV8706Q1_switchToHBridgeDrive (DRV8706Q1_INSTANCE * drv, DRV8706Q1_H_BRIDGE_DRIVES drive)
Function will program the motor driver to switch to H-bridge control mode and reconfigure the pin to the selected H-bridge mode pin configuration to use. Important Note this function updates the motor driver registers via SPI.
Parameters
drv Motor driver instances to use
drive H-Bridge configuration to use when the mode is switch.
Returns
SPI value (uint16_t) returned when performing the write operation
References DRV8706Q1_INSTANCE::driveMode, DRV8706Q1_changeHBridgeDrive(), DRV8706Q1_H_BRIDGE, DRV8706Q1_SPI_ADDR_BRG_CTRL, and DRV8706Q1_spiUpdateRegister().
DRV8706Q1_changeHBridgeDrive()
void DRV8706Q1_changeHBridgeDrive (DRV8706Q1_INSTANCE drv, DRV8706Q1_H_BRIDGE_DRIVES drive)
Function will reconfigure the pins for the specific H-bridge mode configuration. Unlike DRV8706Q1_switchToHBridgeDrive this function does not update the control mode via SPI. So the device must be configured to H-bridge mode already.
Parameters
drv Motor driver instances to use
drive H-Bridge configuration to use when the mode is switch.
References DRV8706Q1_H_BRIDGE_ACTIVE_FREEWHEEL, DRV8706Q1_H_BRIDGE_COAST, DRV8706Q1_H_BRIDGE_FORWARD, DRV8706Q1_H_BRIDGE_REVERSE, HAL_configurePWMPin(), DRV8706Q1_INSTANCE::in1En, DRV8706Q1_INSTANCE::in2Ph, PIN_MODE_OUTPUT_HIGH, PIN_MODE_OUTPUT_LOW, and PIN_MODE_PERIPHERAL.
Referenced by DRV8706Q1_switchToHBridgeDrive().
DRV8706Q1_switchToPhaseDrive()
uint16_t DRV8706Q1_switchToPhaseDrive (DRV8706Q1_INSTANCE * drv, DRV8706Q1_PHASE_DRIVES drive)
Function will program the motor driver to switch to Phase control mode and reconfigure the pin to the selected Phase mode pin configuration to use. Note this function updates the motor driver registers via SPI.
Parameters
drv Motor driver instances to use
drive Phase Enable configuration to use when the mode is switched.
Returns
SPI value (uint16_t) returned when performing the write operation
References DRV8706Q1_INSTANCE::driveMode, DRV8706Q1_changePhaseDrive(), DRV8706Q1_PH_EN, DRV8706Q1_SPI_ADDR_BRG_CTRL, and DRV8706Q1_spiUpdateRegister().
DRV8706Q1_changePhaseDrive()
void DRV8706Q1_changePhaseDrive (DRV8706Q1_INSTANCE drv, DRV8706Q1_PHASE_DRIVES drive)
Function will reconfigure the pins for the specific Phase enable mode configuration. Unlike DRV8706Q1_switchToPhaseDrive this function does not update the control mode via SPI. So the device must be configured to Phase enable mode already.
Parameters
drv Motor driver instances to use
drive Phase enable configuration to use when the mode is switch.
References DRV8706Q1_PHASE_ACTIVE_FREEWHEEL, DRV8706Q1_PHASE_FORWARD, DRV8706Q1_PHASE_REVERSE, HAL_configurePWMPin(), DRV8706Q1_INSTANCE::in1En, DRV8706Q1_INSTANCE::in2Ph, PIN_MODE_OUTPUT_HIGH, PIN_MODE_OUTPUT_LOW, and PIN_MODE_PERIPHERAL.
Referenced by DRV8706Q1_switchToPhaseDrive().
DRV8706Q1_changeSolenoidDrive()
void DRV8706Q1_changeSolenoidDrive (DRV8706Q1_INSTANCE drv, DRV8706Q1_SOLENOID_DRIVES drive)
Function will reconfigure the pins for the specific Solenoid mode configuration. Unlike DRV8706Q1_switchToSolenoidDrive this function does not update the control mode via SPI. So the device must be configured to solenoid already.
Parameters
drv Motor driver instances to use
drive Solenoid mode configuration to use.
References DRV8706Q1_SOLENOID_DISABLE, DRV8706Q1_SOLENOID_PWM, HAL_configurePWMPin(), HAL_setGPIOOutput(), DRV8706Q1_INSTANCE::in1En, DRV8706Q1_INSTANCE::in2Ph, DRV8706Q1_INSTANCE::nHiz1, DRV8706Q1_INSTANCE::nHiz2, PIN_MODE_OUTPUT_HIGH, PIN_MODE_OUTPUT_LOW, and PIN_MODE_PERIPHERAL.
Referenced by DRV8706Q1_switchToSolenoidDrive().
DRV8706Q1_changeHalfBridgeDrive()
void DRV8706Q1_changeHalfBridgeDrive (DRV8706Q1_INSTANCE drv, DRV8706Q1_PWM_CHANNELS drvChan, DRV8706Q1_HALF_BRIDGE_DRIVES drive)
Function will reconfigure the pins for the specific Half Bridge mode configuration. Unlike DRV8706Q1_switchToHalfBridgeDrive this function does not update the control mode via SPI. So the device must be configured to Phase enable mode already.
Parameters
drv Motor driver instances to use
drvChan The DRV PWM channel being configured
drive Half Bridge drive configuration to use when the mode is switch.
References DRV8706Q1_HALF_BRIDGE_HI_Z, DRV8706Q1_HALF_BRIDGE_PWM, DRV8706Q1_PWM_CHANNEL_0, DRV8706Q1_PWM_CHANNEL_1, HAL_configurePWMPin(), HAL_setGPIOOutput(), DRV8706Q1_INSTANCE::in1En, DRV8706Q1_INSTANCE::in2Ph, DRV8706Q1_INSTANCE::nHiz1, DRV8706Q1_INSTANCE::nHiz2, PIN_MODE_OUTPUT_HIGH, PIN_MODE_OUTPUT_LOW, and PIN_MODE_PERIPHERAL.
Referenced by DRV8706Q1_switchToHalfBridgeDrive().
DRV8706Q1_switchToHalfBridgeDrive()
uint16_t DRV8706Q1_switchToHalfBridgeDrive (DRV8706Q1_INSTANCE * drv, DRV8706Q1_HALF_BRIDGE_DRIVES driveChan0, DRV8706Q1_HALF_BRIDGE_DRIVES driveChan1)
Function will reconfigure the pins for the specific Half Bridge mode configuration. Also the control mode will be updated via SPI.
Parameters
drv Motor driver instances to use
driveChan0 Half Bridge drive configuration for PWM channel 0 to use when the mode is switch.
driveChan1 Half Bridge drive configuration for PWM channel 1 to use when the mode is switch.
Returns
SPI value (uint16_t) returned when performing the write operation
References DRV8706Q1_INSTANCE::driveMode, DRV8706Q1_changeHalfBridgeDrive(), DRV8706Q1_HALF_BRIDGE, DRV8706Q1_PWM_CHANNEL_0, DRV8706Q1_PWM_CHANNEL_1, DRV8706Q1_SPI_ADDR_BRG_CTRL, and DRV8706Q1_spiUpdateRegister().
DRV8706Q1_switchToSolenoidDrive()
uint16_t DRV8706Q1_switchToSolenoidDrive (DRV8706Q1_INSTANCE * drv, DRV8706Q1_SOLENOID_DRIVES drive)
Function will program the motor driver to switch to Solenoid control mode and reconfigure the pin to the selected Solenoid mode pin configuration to use. Note this function updates the motor driver registers via SPI.
Parameters
drv Motor driver instances to use
drive Solenoid configuration to use when the mode is switched.
Returns
SPI value (uint16_t) returned when performing the write operation
References DRV8706Q1_INSTANCE::csaGain, DRV8706Q1_INSTANCE::csaSF, DRV8706Q1_INSTANCE::driveMode, DRV8706Q1_changeSolenoidDrive(), DRV8706Q1_SPI_ADDR_BRG_CTRL, DRV8706Q1_spiUpdateRegister(), DRV8706Q1_SPLIT_SOLENOID, HAL_readSPI16withTimeout(), HAL_writeSPI16withTimeout(), and DRV8706Q1_INSTANCE::shuntRes.
DRV8706Q1_spiUpdateRegister()
uint16_t DRV8706Q1_spiUpdateRegister (DRV8706Q1_INSTANCE drv, DRV8706Q1_SPI_ADDR addr, uint8_t mask, uint8_t value)
Function to allow a user to modify a specific bitfield in one of the motor driver's registers. This function automatically converts the parameters to the data format needed for SPI communication with the DRV8706-Q1.
Parameters
drv
addr Register address DRV8706Q1_SPI_ADDR
mask Mask for the bitfield you want to update. Mask passed in should already be shifted so that it can be ~ANDed against the previously read register value. For example, if you want to create a mask for DRV_CTRL_3.VGS_TDRV (bit 5-4) you would write (3 << 4) or 0x30 for the mask.
value Bitfield value to write. Value passed in should already be shifted so that it can be ORed against the previously read register value. For example, if you want to set DRV_CTRL_3.VGS_TDRV (bit 5-4) to 4 us (10b). You would set value to (2<<4) or 0x20
Returns
uint16_t
References DRV8706Q1_spiReadCmd(), and DRV8706Q1_spiWriteCmd().
Referenced by DRV8706Q1_setAnalogReferenceDivider(), DRV8706Q1_setCurrentSenseGain(), DRV8706Q1_switchToHalfBridgeDrive(), DRV8706Q1_switchToHBridgeDrive(), DRV8706Q1_switchToPhaseDrive(), and DRV8706Q1_switchToSolenoidDrive().
DRV8706Q1_spiWriteCmd()
__STATIC_INLINE uint16_t DRV8706Q1_spiWriteCmd (DRV8706Q1_INSTANCE drv, DRV8706Q1_SPI_ADDR addr, uint8_t data)
Perform a SPI write operation. This function already converts the address and data to the data format required by the motor driver. Note that if the motor driver is sleeping then the motor driver will ignore the spi operation.
Parameters
drv The motor driver instances
addr The motor driver SPI address to be written to.
data The value to be written to the specific motor driver SPI address. Note this function will overwrite the entire register value with the value you passed here. If you only want to update a specific bitfield use DRV8706Q1_spiUpdateRegister instead.
Returns
Return the 16 bit value returned by the motor driver when reading SPI.
References DRV8706Q1_INSTANCE::spiChan, and DRV8706Q1_INSTANCE::spiCS.
Referenced by DRV8706Q1_spiUpdateRegister().
DRV8706Q1_spiReadCmd()
__STATIC_INLINE uint16_t DRV8706Q1_spiReadCmd (DRV8706Q1_INSTANCE drv, DRV8706Q1_SPI_ADDR addr)
Perform a SPI read operation. This function converts the address to the data format required by the motor driver. Note that if the motor driver is sleeping then the motor driver will ignore the spi operation and you will read back 0x0.
Parameters
drv The motor driver instances
addr The motor driver SPI address to be read
Returns
Return the 16 bit value returned by the motor driver when reading SPI.
References DRV8706Q1_getCurrent(), DRV8706Q1_powerOnResetVal(), DRV8706Q1_reset(), DRV8706Q1_setDriveDutyCycle(), DRV8706Q1_setDrivePWMFreq(), DRV8706Q1_INSTANCE::spiChan, and DRV8706Q1_INSTANCE::spiCS.
Referenced by DRV8706Q1_spiUpdateRegister().
DRV8706Q1_getCurrent()
_iq20 DRV8706Q1_getCurrent (DRV8706Q1_INSTANCE drv)
Return the current read from the DRV8706-Q1 motor driver.
Parameters
drv
Returns
_iq20
References DRV8706Q1_INSTANCE::adcChan, DRV8706Q1_INSTANCE::aRef_V, DRV8706Q1_INSTANCE::csaDiv, DRV8706Q1_INSTANCE::csaSF, DRV8706Q1_CSA_DIV_2, and HAL_getIQ20VoltageFromADC().
Referenced by DRV8706Q1_spiReadCmd().
DRV8706Q1_setDrivePWMFreq()
void DRV8706Q1_setDrivePWMFreq (DRV8706Q1_INSTANCE drv, DRV8706Q1_PWM_CHANNELS drvPwmChan, uint32_t value)
Sets the PWM frequency for the correct channel based on the drive specified.
Parameters
drv Motor driver instance
drvPwmChan The value for this parameter only matters when using half-bridge mode which is the only mode that the PWM frequency should be different.
value PWM frequency specified. Note that the value you set here and the actual output frequency is dependent on the timer's clock configuration.
References DRV8706Q1_INSTANCE::driveMode, DRV8706Q1_H_BRIDGE, DRV8706Q1_HALF_BRIDGE, DRV8706Q1_PH_EN, DRV8706Q1_PWM_CHANNEL_0, DRV8706Q1_PWM_CHANNEL_1, and DRV8706Q1_SPLIT_SOLENOID.
Referenced by DRV8706Q1_spiReadCmd().
DRV8706Q1_setDriveDutyCycle()
void DRV8706Q1_setDriveDutyCycle (DRV8706Q1_INSTANCE drv, DRV8706Q1_PWM_CHANNELS drvPwmChan, uint8_t value)
Sets the duty cycle for the correct channel based on the drive specified.
Parameters
drv Motor driver instance
drvPwmChan The value for this parameter only matters when using half-bridge mode which is the only mode that the duty cycle can be different for each channel.
value Duty Cycle to use. Valid values are 0-100. Using any other value can cause unexpected behavior.
References DRV8706Q1_INSTANCE::driveMode, DRV8706Q1_H_BRIDGE, DRV8706Q1_HALF_BRIDGE, DRV8706Q1_PH_EN, DRV8706Q1_PWM_CHANNEL_0, DRV8706Q1_PWM_CHANNEL_1, and DRV8706Q1_SPLIT_SOLENOID.
Referenced by DRV8706Q1_spiReadCmd().
DRV8706Q1_reset()
void DRV8706Q1_reset (DRV8706Q1_INSTANCE * drv)
This functions resets the SPI registers of the motor driver by putting it to sleep, delaying and waking it up. Note that when this function is called the motor driver sleep pin will be high. This functional internally calls DRV8706Q1_powerOnResetVal.
Parameters
drv Motor driver instance.
References DRV8706Q1_powerOnResetVal(), DRV8706Q1_setNSleep(), HAL_delayMilliSeconds(), HIGH, and LOW.
Referenced by DRV8706Q1_spiReadCmd().
DRV8706Q1_powerOnResetVal()
void DRV8706Q1_powerOnResetVal (DRV8706Q1_INSTANCE * drv)
Reset internal DRV structure variables to sync with the motor driver registers power on reset value.
Parameters
drv Motor driver instance.
References DRV8706Q1_INSTANCE::csaDiv, DRV8706Q1_INSTANCE::csaGain, DRV8706Q1_INSTANCE::driveMode, DRV8706Q1_CSA_DIV_2, DRV8706Q1_CSA_GAIN_20, and DRV8706Q1_HALF_BRIDGE.
Referenced by DRV8706Q1_init(), DRV8706Q1_reset(), and DRV8706Q1_spiReadCmd().
DRV8706Q1_setNSleep()
__STATIC_INLINE void DRV8706Q1_setNSleep (DRV8706Q1_INSTANCE drv, bool value)
Help function that controls the MCU pin connected to nSleep pin on the motor driver. Note if you manually set nSLEEP low for more than 1 ms then all the register values will be reset to their default values. Therefore, it would be important to immediately call DRV8706Q1_powerOnResetVal whenver you set nSLEEP to high to make sure internal structures are sync.
Parameters
drv Motor driver instance
value True = pin is HIGH or False = pin is LOW
References HAL_delayMilliSeconds(), HAL_setGPIOOutput(), and DRV8706Q1_INSTANCE::nSleep.
Referenced by DRV8706Q1_reset().
DRV8706Q1_setDrvOff()
__STATIC_INLINE void DRV8706Q1_setDrvOff (DRV8706Q1_INSTANCE drv, bool value)
Help function that controls the MCU pin connected to DrvOff pin on the motor driver.
Parameters
drv Motor driver instance
value True = pin is HIGH or False = pin is LOW
References DRV8706Q1_INSTANCE::drvOff, and HAL_setGPIOOutput().
DRV8706Q1_setNHiZ1()
__STATIC_INLINE void DRV8706Q1_setNHiZ1 (DRV8706Q1_INSTANCE drv, bool value)
Help function that controls the MCU pin connected to nHiZ1 pin on the motor driver.
Parameters
drv Motor driver instance
value True = pin is HIGH or False = pin is LOW
References HAL_setGPIOOutput(), and DRV8706Q1_INSTANCE::nHiz1.
DRV8706Q1_setNHiZ2()
__STATIC_INLINE void DRV8706Q1_setNHiZ2 (DRV8706Q1_INSTANCE drv, bool value)
Help function that controls the MCU pin connected to nHiZ2 pin on the motor driver.
Parameters
drv Motor driver instance
value True = pin is HIGH or False = pin is LOW
References DRV8706Q1_setAnalogReference(), DRV8706Q1_setAnalogReferenceDivider(), DRV8706Q1_setCurrentSenseGain(), DRV8706Q1_setCurrentShuntResistor(), HAL_setGPIOOutput(), and DRV8706Q1_INSTANCE::nHiz2.
DRV8706Q1_setAnalogReference()
void DRV8706Q1_setAnalogReference (DRV8706Q1_INSTANCE * drv, _iq20 aRef_V)
Set voltage connected to the motor driver's AREF pin. This value is needed to properly calculate the motor's current.
Parameters
drv Reference to the motor driver instance
aRef_V Analog voltage reference in _iq20 format. Use the function _IQ20() to convert the voltage from a int or float to _iq20 before passing it as a parameter. Otherwise the calculations will be incorrect.
References DRV8706Q1_INSTANCE::aRef_V.
Referenced by DRV8706Q1_setNHiZ2().
DRV8706Q1_setAnalogReferenceDivider()
uint16_t DRV8706Q1_setAnalogReferenceDivider (DRV8706Q1_INSTANCE * drv, DRV8706Q1_CSA_DIV csaDiv)
Set current shunt amplifier reference voltage divider. This function will update the CSA_CTRL.CSA_DIV register bitfield to the specified voltage divider.
Parameters
drv Reference to motor driver instance
csaDiv Analog reference voltage divider
Returns
uint16_t This function will return the SPI value returned after writing the SPI register.
References DRV8706Q1_INSTANCE::csaDiv, DRV8706Q1_CSA_DIV_2, DRV8706Q1_SPI_ADDR_CSA_CTRL, and DRV8706Q1_spiUpdateRegister().
Referenced by DRV8706Q1_setNHiZ2().
DRV8706Q1_setCurrentSenseGain()
uint16_t DRV8706Q1_setCurrentSenseGain (DRV8706Q1_INSTANCE * drv, DRV8706Q1_CSA_GAINS gcsa)
Configure the CSA to the gain setting specified. This function will update the CSA_CTRL.CSA_GAIN register bitfield with the gain you specified.
Parameters
drv Reference to motor driver instance
gcsa Gain setting you want to use.
Returns
uint16_t This function will return the SPI value returned after writing the SPI register.
References DRV8706Q1_INSTANCE::csaGain, DRV8706Q1_CSA_GAIN_10, DRV8706Q1_CSA_GAIN_20, DRV8706Q1_CSA_GAIN_40, DRV8706Q1_CSA_GAIN_80, DRV8706Q1_SPI_ADDR_CSA_CTRL, and DRV8706Q1_spiUpdateRegister().
Referenced by DRV8706Q1_setNHiZ2().
DRV8706Q1_setCurrentShuntResistor()
void DRV8706Q1_setCurrentShuntResistor (DRV8706Q1_INSTANCE * drv, _iq20 rShunt)
Set the current shunt resistor value used by the current sense amplifier. This value needs to be set based on the used by your hardware.
Parameters
drv Reference to motor driver instance
rShunt Current shunt resistor value in mOhms in _iq20 format. Use the function _IQ20() to convert the voltage from a int or float to _iq20 before passing it as a parameter. Otherwise the calculations will be incorrect.
References DRV8706Q1_INSTANCE::shuntRes.
Referenced by DRV8706Q1_setNHiZ2().
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale