MSPM0L211X_L112X Driver Library: DriverLib Common APIs
DriverLib Common APIs
Functions
__STATIC_INLINE void DL_Common_updateReg (volatile uint32_t *reg, uint32_t val, uint32_t mask)
Writes value to specified register - retaining bits unaffected by mask.
void DL_Common_delayCycles (uint32_t cycles)
Consumes the number of CPU cycles specified.
Detailed Description
Overview
APIs used across multiple DriverLib modules
Function Documentation
DL_Common_updateReg()
__STATIC_INLINE void DL_Common_updateReg (volatile uint32_t * reg, uint32_t val, uint32_t mask)
Writes value to specified register - retaining bits unaffected by mask.
Parameters
[in] reg Pointer to the register overlay for the peripheral.
[in] val Value to be written to the register.
[in] mask Mask defines which bits will be altered.
References DL_Common_delayCycles().
Referenced by DL_ADC12_configHwAverage(), DL_ADC12_disableForcingSYSOSCOnInRunMode(), DL_ADC12_disableForcingSYSOSCOnInStopMode(), DL_ADC12_initSeqSample(), DL_ADC12_initSingleSample(), DL_ADC12_setDMASamplesCnt(), DL_ADC12_setEndAddress(), DL_ADC12_setPowerDownMode(), DL_ADC12_setStartAddress(), DL_AESADV_resumeAADPhase(), DL_AESADV_resumeDataPhase(), DL_AESADV_setCCMCounterWidth(), DL_AESADV_setCCMTagWidth(), DL_AESADV_setCounterWidth(), DL_AESADV_setDirection(), DL_AESADV_setFeedbackWidth(), DL_AESADV_setKeySize(), DL_AESADV_setMode(), DL_DMA_configMode(), DL_DMA_getDestWidth(), DL_DMA_setBurstSize(), DL_DMA_setDestIncrement(), DL_DMA_setDestWidth(), DL_DMA_setExtendedMode(), DL_DMA_setSrcIncrement(), DL_DMA_setSrcWidth(), DL_DMA_setTransferMode(), DL_DMA_setTrigger(), DL_FlashCTL_setBankSelect(), DL_FlashCTL_setRegionSelect(), DL_GPIO_configSubscriber(), DL_GPIO_disableDMAAccess(), DL_GPIO_enableDMAAccess(), DL_GPIO_setWakeupCompareValue(), DL_I2CC_selectClockDivider(), DL_I2CC_selectClockSource(), DL_I2CC_setAddressingMode(), DL_I2CC_setDigitalGlitchFilterPulseWidth(), DL_I2CC_setDirection(), DL_I2CC_setPECCountValue(), DL_I2CC_setRXFIFOThreshold(), DL_I2CC_setTargetAddress(), DL_I2CC_setTimeoutACount(), DL_I2CC_setTimeoutBCount(), DL_I2CC_setTransactionLength(), DL_I2CC_setTXFIFOThreshold(), DL_I2CC_startTransfer(), DL_I2CC_startTransferAdvanced(), DL_I2CT_selectClockDivider(), DL_I2CT_selectClockSource(), DL_I2CT_setACKOverrideValue(), DL_I2CT_setAddressingMode(), DL_I2CT_setDigitalGlitchFilterPulseWidth(), DL_I2CT_setOwnAddress(), DL_I2CT_setOwnAddressAlternate(), DL_I2CT_setOwnAddressAlternateMask(), DL_I2CT_setPECCountValue(), DL_I2CT_setRXFIFOThreshold(), DL_I2CT_setTimeoutACount(), DL_I2CT_setTimeoutBCount(), DL_I2CT_setTXFIFOThreshold(), DL_KEYSTORECTL_setDestinationKeySize(), DL_KEYSTORECTL_setDestinationKeySlot(), DL_KEYSTORECTL_setNumberOf256Keys(), DL_KEYSTORECTL_setSourceKeySize(), DL_KEYSTORECTL_setSourceKeySlot(), DL_LFSS_IWDT_setClockDivider(), DL_LFSS_IWDT_setTimerPeriod(), DL_LFSS_TamperIO_setEdgeDetectionPolarity(), DL_LFSS_TamperIO_setGlitchFilterWidth(), DL_LFSS_TamperIO_setHeartBeatInterval(), DL_LFSS_TamperIO_setHeartBeatMode(), DL_LFSS_TamperIO_setHeartBeatPulseWidth(), DL_LFSS_TamperIO_setMode(), DL_LFSS_TamperIO_setOutputSource(), DL_LFSS_TamperIO_setOutputValue(), DL_LFSS_writeScratchPadData8(), DL_RTC_Common_getPublisherChanID(), DL_RTC_Common_setAlarm1DayOfMonthBCD(), DL_RTC_Common_setAlarm1DayOfMonthBinary(), DL_RTC_Common_setAlarm1DayOfWeekBCD(), DL_RTC_Common_setAlarm1DayOfWeekBinary(), DL_RTC_Common_setAlarm2DayOfMonthBCD(), DL_RTC_Common_setAlarm2DayOfMonthBinary(), DL_RTC_Common_setAlarm2DayOfWeekBCD(), DL_RTC_Common_setAlarm2DayOfWeekBinary(), DL_RTC_Common_setCalendarDayOfMonthBCD(), DL_RTC_Common_setCalendarDayOfMonthBinary(), DL_RTC_Common_setCalendarDayOfWeekBCD(), DL_RTC_Common_setCalendarDayOfWeekBinary(), DL_RTC_Common_setIntervalAlarm(), DL_RTC_Common_setOffsetCalibrationAdjValue(), DL_RTC_Common_setOffsetCalibrationFrequency(), DL_RTC_Common_setPeriodicAlarm0(), DL_RTC_Common_setPeriodicAlarm1(), DL_RTC_Common_setPeriodicAlarm2(), DL_SPGSS_setLoopbackConfig(), DL_SPI_flushRXFIFO(), DL_SPI_flushTXFIFO(), DL_SPI_setBitOrder(), DL_SPI_setBitRateSerialClockDivider(), DL_SPI_setChipSelect(), DL_SPI_setControllerCommandDataModeConfig(), DL_SPI_setDataSize(), DL_SPI_setDelayedSampling(), DL_SPI_setFIFOThreshold(), DL_SPI_setFrameFormat(), DL_SPI_setMode(), DL_SPI_setParity(), DL_SPI_setPeripheralReceiveTimeout(), DL_SPI_setRepeatTransmit(), DL_SYSCTL_enableExternalClock(), DL_SYSCTL_setFCCPeriods(), DL_SYSCTL_setFlashDEDErrorBehavior(), DL_SYSCTL_setFlashWaitState(), DL_SYSCTL_setHFCLKDividerForMFPCLK(), DL_SYSCTL_setHFXTFrequencyRange(), DL_SYSCTL_setHFXTStartupTime(), DL_SYSCTL_setMCLKDivider(), DL_SYSCTL_setMFPCLKSource(), DL_SYSCTL_setShutdownStorageByte(), DL_SYSCTL_setSYSOSCFreq(), DL_SYSCTL_setVBOOSTConfig(), DL_SYSCTL_setWWDT0ErrorBehavior(), DL_Timer_configCrossTriggerEnable(), DL_Timer_configCrossTriggerInputCond(), DL_Timer_configCrossTriggerSrc(), DL_Timer_configFaultCounter(), DL_Timer_configFaultOutputAction(), DL_Timer_setCCPOutputDisabled(), DL_Timer_setCCPOutputDisabledAdv(), DL_Timer_setCounterControl(), DL_Timer_setCounterMode(), DL_Timer_setCounterRepeatMode(), DL_Timer_setCounterValueAfterEnable(), DL_Timer_setDebugReleaseBehavior(), DL_Timer_setExternalTriggerEvent(), DL_Timer_setFaultConfig(), DL_UART_enableLINCounterCompareMatch(), DL_UART_enableLINFallingEdgeCapture(), DL_UART_enableLINReceptionCountControl(), DL_UART_enableLINSyncFieldValidationCounterControl(), DL_UART_setAddress(), DL_UART_setAddressMask(), DL_UART_setBaudRateDivisor(), DL_UART_setCommunicationMode(), DL_UART_setDigitalPulseWidth(), DL_UART_setDirection(), DL_UART_setExternalDriverHold(), DL_UART_setExternalDriverSetup(), DL_UART_setFlowControl(), DL_UART_setIrDARXPulsePolarity(), DL_UART_setIrDATXPulseClockSelect(), DL_UART_setLINCounterCompareValue(), DL_UART_setLINCounterValue(), DL_UART_setOversampling(), DL_UART_setParityMode(), DL_UART_setRTSOutput(), DL_UART_setRXFIFOThreshold(), DL_UART_setRXInterruptTimeout(), DL_UART_setStopBits(), DL_UART_setTransmitPinManualOutput(), DL_UART_setTXFIFOThreshold(), and DL_UART_setWordLength().
DL_Common_delayCycles()
void DL_Common_delayCycles (uint32_t cycles)
Consumes the number of CPU cycles specified.
Parameters
[in] cycles Floor number of cycles to delay. Specifying zero will result in the maximum possible delay. Note that guarantees at least this number of cycles will be delayed, not that exactly this number of cycles will be delayed. If a more precise number of cycle delay value is needed, GPTimer is recommended.
Typical variance from this function is 10 cycles or less assuming that the function is located in flash and that caching is enabled. Disabling caching may result in wait-states when fetching from flash. Other variance occurs due:
Amount of register stacking/unstacking around API entry/exit
Value of cycles relative to 4-cycle loop counter
Placement of code on a 2- or 4-byte aligned boundary
Referenced by DL_Common_updateReg().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale