MSPM0Gxx0xEnergyMetrology: ADS131M0x
ADS131M0x
Data Structures
struct ADS_channelData
Defines ADS Channel data.
struct ADS_Errors
Structure to store the ADS error counts.
struct ADS_Instance
ADS_Instance.
Macros
#define ADS131M02_CLOCK_ADDRESS_DATA CLOCK_CH1_EN_ENABLED | CLOCK_CH0_EN_ENABLED | CLOCK_XTAL_DIS_ENABLED | CLOCK_EXTREF_EN_DISABLED | CLOCK_OSR_512 | CLOCK_PWR_HR
Default clock address data.
#define ADS131M02_MODE_ADDRESS_DATA MODE_REG_CRC_EN_DISABLED | MODE_RX_CRC_EN_DISABLED | MODE_CRC_TYPE_16BIT_CCITT | MODE_RESET_NO_RESET | MODE_WLENGTH_24BIT | MODE_TIMEOUT_ENABLED | MODE_DRDY_SEL_MOST_LAGGING | MODE_DRDY_HiZ_LOGIC_HIGH | MODE_DRDY_FMT_LOGIC_LOW
Default mode address data.
#define ADS131M02_GAIN1_ADDRESS_DATA GAIN1_PGAGAIN3_1 | GAIN1_PGAGAIN2_1 | GAIN1_PGAGAIN1_1 | GAIN1_PGAGAIN0_32
Default gain1 address data.
#define ADS131M02_CFG_ADDRESS_DATA CFG_GC_DLY_16 | CFG_GC_EN_DISABLED | CFG_CD_ALLCH_ANY_CHANNEL | CFG_CD_NUM_1 | CFG_CD_LEN_128 | CFG_CD_EN_DISABLED
Default CFG address data.
#define ADS131M02_THRSHLD_MSB_ADDRESS_DATA THRSHLD_MSB_DEFAULT
Default THRSHLD MSB address data.
#define ADS131M02_THRSHLD_LSB_ADDRESS_DATA THRSHLD_LSB_DCBLOCK_DISABLED
Default THRSHLD LSB address data.
#define ADS131M02_CH0_CFG_ADDRESS_DATA CH0_CFG_DEFAULT
Default CH0_CFG address data.
#define ADS131M02_CH0_OCAL_MSB_ADDRESS_DATA CH0_OCAL_MSB_DEFAULT
Default CH0 OCAL_MSB address data.
#define ADS131M02_CH0_OCAL_LSB_ADDRESS_DATA CH0_OCAL_LSB_DEFAULT
Default CH0 OCAL_LSB address data.
#define ADS131M02_CH0_GCAL_MSB_ADDRESS_DATA CH0_GCAL_MSB_DEFAULT
Default CH0 GCAL_MSB address data.
#define ADS131M02_CH0_GCAL_LSB_ADDRESS_DATA CH0_GCAL_LSB_DEFAULT
Default CH0 GCAL_LSB address data.
#define ADS131M02_CH1_CFG_ADDRESS_DATA CH1_CFG_DEFAULT
Default CH1_CFG address data.
#define ADS131M02_CH1_OCAL_MSB_ADDRESS_DATA CH1_OCAL_MSB_DEFAULT
Default CH1 OCAL_MSB address data.
#define ADS131M02_CH1_OCAL_LSB_ADDRESS_DATA CH1_OCAL_LSB_DEFAULT
Default CH1 OCAL_LSB address data.
#define ADS131M02_CH1_GCAL_MSB_ADDRESS_DATA CH1_GCAL_MSB_DEFAULT
Default CH1 GCAL_MSB address data.
#define ADS131M02_CH1_GCAL_LSB_ADDRESS_DATA CH1_GCAL_LSB_DEFAULT
Default CH1 GCAL_LSB address data.
#define ADS131M03_CLOCK_ADDRESS_DATA CLOCK_CH2_EN_ENABLED | CLOCK_CH1_EN_ENABLED | CLOCK_CH0_EN_ENABLED | CLOCK_XTAL_DIS_ENABLED | CLOCK_EXTREF_EN_DISABLED | CLOCK_OSR_512 | CLOCK_PWR_HR
Default clock address data.
#define ADS131M03_MODE_ADDRESS_DATA MODE_REG_CRC_EN_DISABLED | MODE_RX_CRC_EN_DISABLED | MODE_CRC_TYPE_16BIT_CCITT | MODE_RESET_NO_RESET | MODE_WLENGTH_24BIT | MODE_TIMEOUT_ENABLED | MODE_DRDY_SEL_MOST_LAGGING | MODE_DRDY_HiZ_LOGIC_HIGH | MODE_DRDY_FMT_LOGIC_LOW
Default mode address data.
#define ADS131M03_GAIN1_ADDRESS_DATA GAIN1_PGAGAIN3_1 | GAIN1_PGAGAIN2_1 | GAIN1_PGAGAIN1_1 | GAIN1_PGAGAIN0_1
Default gain1 address data.
#define ADS131M03_CFG_ADDRESS_DATA CFG_GC_DLY_16 | CFG_GC_EN_DISABLED | CFG_CD_ALLCH_ANY_CHANNEL | CFG_CD_NUM_1 | CFG_CD_LEN_128 | CFG_CD_EN_DISABLED
Default CFG address data.
#define ADS131M03_THRSHLD_MSB_ADDRESS_DATA THRSHLD_MSB_DEFAULT
Default THRSHLD MSB address data.
#define ADS131M03_THRSHLD_LSB_ADDRESS_DATA THRSHLD_LSB_DCBLOCK_DISABLED
Default THRSHLD LSB address data.
#define ADS131M03_CH0_CFG_ADDRESS_DATA CH0_CFG_DEFAULT
Default CH0_CFG address data.
#define ADS131M03_CH0_OCAL_MSB_ADDRESS_DATA CH0_OCAL_MSB_DEFAULT
Default CH0 OCAL_MSB address data.
#define ADS131M03_CH0_OCAL_LSB_ADDRESS_DATA CH0_OCAL_LSB_DEFAULT
Default CH0 OCAL_LSB address data.
#define ADS131M03_CH0_GCAL_MSB_ADDRESS_DATA CH0_GCAL_MSB_DEFAULT
Default CH0 GCAL_MSB address data.
#define ADS131M03_CH0_GCAL_LSB_ADDRESS_DATA CH0_GCAL_LSB_DEFAULT
Default CH0 GCAL_LSB address data.
#define ADS131M03_CH1_CFG_ADDRESS_DATA CH1_CFG_DEFAULT
Default CH1_CFG address data.
#define ADS131M03_CH1_OCAL_MSB_ADDRESS_DATA CH1_OCAL_MSB_DEFAULT
Default CH1 OCAL_MSB address data.
#define ADS131M03_CH1_OCAL_LSB_ADDRESS_DATA CH1_OCAL_LSB_DEFAULT
Default CH1 OCAL_LSB address data.
#define ADS131M03_CH1_GCAL_MSB_ADDRESS_DATA CH1_GCAL_MSB_DEFAULT
Default CH1 GCAL_MSB address data.
#define ADS131M03_CH1_GCAL_LSB_ADDRESS_DATA CH1_GCAL_LSB_DEFAULT
Default CH1 GCAL_LSB address data.
#define ADS131M03_CH2_CFG_ADDRESS_DATA CH2_CFG_DEFAULT
Default CH2_CFG address data.
#define ADS131M03_CH2_OCAL_MSB_ADDRESS_DATA CH2_OCAL_MSB_DEFAULT
Default CH2 OCAL_MSB address data.
#define ADS131M03_CH2_OCAL_LSB_ADDRESS_DATA CH2_OCAL_LSB_DEFAULT
Default CH2 OCAL_LSB address data.
#define ADS131M03_CH2_GCAL_MSB_ADDRESS_DATA CH2_GCAL_MSB_DEFAULT
Default CH2 GCAL_MSB address data.
#define ADS131M03_CH2_GCAL_LSB_ADDRESS_DATA CH2_GCAL_LSB_DEFAULT
Default CH2 GCAL_LSB address data.
#define ADS131M04_CLOCK_ADDRESS_DATA CLOCK_CH3_EN_DISABLED | CLOCK_CH2_EN_ENABLED | CLOCK_CH1_EN_ENABLED | CLOCK_CH0_EN_ENABLED | CLOCK_XTAL_DIS_ENABLED | CLOCK_EXTREF_EN_DISABLED | CLOCK_OSR_512 | CLOCK_PWR_HR
Default clock address data.
#define ADS131M04_MODE_ADDRESS_DATA MODE_REG_CRC_EN_DISABLED | MODE_RX_CRC_EN_DISABLED | MODE_CRC_TYPE_16BIT_CCITT | MODE_RESET_NO_RESET | MODE_WLENGTH_24BIT | MODE_TIMEOUT_ENABLED | MODE_DRDY_SEL_MOST_LAGGING | MODE_DRDY_HiZ_LOGIC_HIGH | MODE_DRDY_FMT_LOGIC_LOW
Default mode address data.
#define ADS131M04_GAIN1_ADDRESS_DATA GAIN1_PGAGAIN3_1 | GAIN1_PGAGAIN2_1 | GAIN1_PGAGAIN1_1 | GAIN1_PGAGAIN0_1
Default gain1 address data.
#define ADS131M04_CFG_ADDRESS_DATA CFG_GC_DLY_16 | CFG_GC_EN_DISABLED | CFG_CD_ALLCH_ANY_CHANNEL | CFG_CD_NUM_1 | CFG_CD_LEN_128 | CFG_CD_EN_DISABLED
Default CFG address data.
#define ADS131M04_THRSHLD_MSB_ADDRESS_DATA THRSHLD_MSB_DEFAULT
Default THRSHLD MSB address data.
#define ADS131M04_THRSHLD_LSB_ADDRESS_DATA THRSHLD_LSB_DCBLOCK_DISABLED
Default THRSHLD LSB address data.
#define ADS131M04_CH0_CFG_ADDRESS_DATA CH0_CFG_DEFAULT
Default CH0_CFG address data.
#define ADS131M04_CH0_OCAL_MSB_ADDRESS_DATA CH0_OCAL_MSB_DEFAULT
Default CH0 OCAL_MSB address data.
#define ADS131M04_CH0_OCAL_LSB_ADDRESS_DATA CH0_OCAL_LSB_DEFAULT
Default CH0 OCAL_LSB address data.
#define ADS131M04_CH0_GCAL_MSB_ADDRESS_DATA CH0_GCAL_MSB_DEFAULT
Default CH0 GCAL_MSB address data.
#define ADS131M04_CH0_GCAL_LSB_ADDRESS_DATA CH0_GCAL_LSB_DEFAULT
Default CH0 GCAL_LSB address data.
#define ADS131M04_CH1_CFG_ADDRESS_DATA CH1_CFG_DEFAULT
Default CH1_CFG address data.
#define ADS131M04_CH1_OCAL_MSB_ADDRESS_DATA CH1_OCAL_MSB_DEFAULT
Default CH1 OCAL_MSB address data.
#define ADS131M04_CH1_OCAL_LSB_ADDRESS_DATA CH1_OCAL_LSB_DEFAULT
Default CH1 OCAL_LSB address data.
#define ADS131M04_CH1_GCAL_MSB_ADDRESS_DATA CH1_GCAL_MSB_DEFAULT
Default CH1 GCAL_MSB address data.
#define ADS131M04_CH1_GCAL_LSB_ADDRESS_DATA CH1_GCAL_LSB_DEFAULT
Default CH1 GCAL_LSB address data.
#define ADS131M04_CH2_CFG_ADDRESS_DATA CH2_CFG_DEFAULT
Default CH2_CFG address data.
#define ADS131M04_CH2_OCAL_MSB_ADDRESS_DATA CH2_OCAL_MSB_DEFAULT
Default CH2 OCAL_MSB address data.
#define ADS131M04_CH2_OCAL_LSB_ADDRESS_DATA CH2_OCAL_LSB_DEFAULT
Default CH2 OCAL_LSB address data.
#define ADS131M04_CH2_GCAL_MSB_ADDRESS_DATA CH2_GCAL_MSB_DEFAULT
Default CH2 GCAL_MSB address data.
#define ADS131M04_CH2_GCAL_LSB_ADDRESS_DATA CH2_GCAL_LSB_DEFAULT
Default CH2 GCAL_LSB address data.
#define ADS131M04_CH3_CFG_ADDRESS_DATA CH3_CFG_DEFAULT
Default CH3_CFG address data.
#define ADS131M04_CH3_OCAL_MSB_ADDRESS_DATA CH3_OCAL_MSB_DEFAULT
Default CH3 OCAL_MSB address data.
#define ADS131M04_CH3_OCAL_LSB_ADDRESS_DATA CH3_OCAL_LSB_DEFAULT
Default CH3 OCAL_LSB address data.
#define ADS131M04_CH3_GCAL_MSB_ADDRESS_DATA CH3_GCAL_MSB_DEFAULT
Default CH3 GCAL_MSB address data.
#define ADS131M04_CH3_GCAL_LSB_ADDRESS_DATA CH3_GCAL_LSB_DEFAULT
Default CH3 GCAL_LSB address data.
#define ADS131M08_CLOCK_ADDRESS_DATA CLOCK_CH7_EN_DISABLED | CLOCK_CH6_EN_ENABLED | CLOCK_CH5_EN_ENABLED | CLOCK_CH4_EN_ENABLED | CLOCK_CH3_EN_ENABLED | CLOCK_CH2_EN_ENABLED | CLOCK_CH1_EN_ENABLED | CLOCK_CH0_EN_ENABLED | CLOCK_XTAL_DIS_ENABLED | CLOCK_EXTREF_EN_DISABLED | CLOCK_OSR_512 | CLOCK_PWR_HR
Default clock address data.
#define ADS131M08_MODE_ADDRESS_DATA MODE_REG_CRC_EN_DISABLED | MODE_RX_CRC_EN_DISABLED | MODE_CRC_TYPE_16BIT_CCITT | MODE_RESET_NO_RESET | MODE_WLENGTH_24BIT | MODE_TIMEOUT_ENABLED | MODE_DRDY_SEL_MOST_LAGGING | MODE_DRDY_HiZ_LOGIC_HIGH | MODE_DRDY_FMT_LOGIC_LOW
Default mode address data.
#define ADS131M08_GAIN1_ADDRESS_DATA GAIN1_PGAGAIN3_1 | GAIN1_PGAGAIN2_1 | GAIN1_PGAGAIN1_1 | GAIN1_PGAGAIN0_1
Default gain1 address data.
#define ADS131M08_GAIN2_ADDRESS_DATA GAIN2_PGAGAIN7_1 | GAIN2_PGAGAIN6_1 | GAIN2_PGAGAIN5_1 | GAIN2_PGAGAIN4_1
Default gain2 address data.
#define ADS131M08_CFG_ADDRESS_DATA CFG_GC_DLY_16 | CFG_GC_EN_DISABLED | CFG_CD_ALLCH_ANY_CHANNEL | CFG_CD_NUM_1 | CFG_CD_LEN_128 | CFG_CD_EN_DISABLED
Default CFG address data.
#define ADS131M08_THRSHLD_MSB_ADDRESS_DATA THRSHLD_MSB_DEFAULT
Default THRSHLD MSB address data.
#define ADS131M08_THRSHLD_LSB_ADDRESS_DATA THRSHLD_LSB_DCBLOCK_DISABLED
Default THRSHLD LSB address data.
#define ADS131M08_CH0_CFG_ADDRESS_DATA CH0_CFG_DEFAULT
Default CH0_CFG address data.
#define ADS131M08_CH0_OCAL_MSB_ADDRESS_DATA CH0_OCAL_MSB_DEFAULT
Default CH0 OCAL_MSB address data.
#define ADS131M08_CH0_OCAL_LSB_ADDRESS_DATA CH0_OCAL_LSB_DEFAULT
Default CH0 OCAL_LSB address data.
#define ADS131M08_CH0_GCAL_MSB_ADDRESS_DATA CH0_GCAL_MSB_DEFAULT
Default CH0 GCAL_MSB address data.
#define ADS131M08_CH0_GCAL_LSB_ADDRESS_DATA CH0_GCAL_LSB_DEFAULT
Default CH0 GCAL_LSB address data.
#define ADS131M08_CH1_CFG_ADDRESS_DATA CH1_CFG_DEFAULT
Default CH1_CFG address data.
#define ADS131M08_CH1_OCAL_MSB_ADDRESS_DATA CH1_OCAL_MSB_DEFAULT
Default CH1 OCAL_MSB address data.
#define ADS131M08_CH1_OCAL_LSB_ADDRESS_DATA CH1_OCAL_LSB_DEFAULT
Default CH1 OCAL_LSB address data.
#define ADS131M08_CH1_GCAL_MSB_ADDRESS_DATA CH1_GCAL_MSB_DEFAULT
Default CH1 GCAL_MSB address data.
#define ADS131M08_CH1_GCAL_LSB_ADDRESS_DATA CH1_GCAL_LSB_DEFAULT
Default CH1 GCAL_LSB address data.
#define ADS131M08_CH2_CFG_ADDRESS_DATA CH2_CFG_DEFAULT
Default CH2_CFG address data.
#define ADS131M08_CH2_OCAL_MSB_ADDRESS_DATA CH2_OCAL_MSB_DEFAULT
Default CH2 OCAL_MSB address data.
#define ADS131M08_CH2_OCAL_LSB_ADDRESS_DATA CH2_OCAL_LSB_DEFAULT
Default CH2 OCAL_LSB address data.
#define ADS131M08_CH2_GCAL_MSB_ADDRESS_DATA CH2_GCAL_MSB_DEFAULT
Default CH2 GCAL_MSB address data.
#define ADS131M08_CH2_GCAL_LSB_ADDRESS_DATA CH2_GCAL_LSB_DEFAULT
Default CH2 GCAL_LSB address data.
#define ADS131M08_CH3_CFG_ADDRESS_DATA CH3_CFG_DEFAULT
Default CH3_CFG address data.
#define ADS131M08_CH3_OCAL_MSB_ADDRESS_DATA CH3_OCAL_MSB_DEFAULT
Default CH3 OCAL_MSB address data.
#define ADS131M08_CH3_OCAL_LSB_ADDRESS_DATA CH3_OCAL_LSB_DEFAULT
Default CH3 OCAL_LSB address data.
#define ADS131M08_CH3_GCAL_MSB_ADDRESS_DATA CH3_GCAL_MSB_DEFAULT
Default CH3 GCAL_MSB address data.
#define ADS131M08_CH3_GCAL_LSB_ADDRESS_DATA CH3_GCAL_LSB_DEFAULT
Default CH3 GCAL_LSB address data.
#define ADS131M08_CH4_CFG_ADDRESS_DATA CH4_CFG_DEFAULT
Default CH4_CFG address data.
#define ADS131M08_CH4_OCAL_MSB_ADDRESS_DATA CH4_OCAL_MSB_DEFAULT
Default CH4 OCAL_MSB address data.
#define ADS131M08_CH4_OCAL_LSB_ADDRESS_DATA CH4_OCAL_LSB_DEFAULT
Default CH4 OCAL_LSB address data.
#define ADS131M08_CH4_GCAL_MSB_ADDRESS_DATA CH4_GCAL_MSB_DEFAULT
Default CH4 GCAL_MSB address data.
#define ADS131M08_CH4_GCAL_LSB_ADDRESS_DATA CH4_GCAL_LSB_DEFAULT
Default CH4 GCAL_LSB address data.
#define ADS131M08_CH5_CFG_ADDRESS_DATA CH5_CFG_DEFAULT
Default CH5_CFG address data.
#define ADS131M08_CH5_OCAL_MSB_ADDRESS_DATA CH5_OCAL_MSB_DEFAULT
Default CH5 OCAL_MSB address data.
#define ADS131M08_CH5_OCAL_LSB_ADDRESS_DATA CH5_OCAL_LSB_DEFAULT
Default CH5 OCAL_LSB address data.
#define ADS131M08_CH5_GCAL_MSB_ADDRESS_DATA CH5_GCAL_MSB_DEFAULT
Default CH5 GCAL_MSB address data.
#define ADS131M08_CH5_GCAL_LSB_ADDRESS_DATA CH5_GCAL_LSB_DEFAULT
Default CH5 GCAL_LSB address data.
#define ADS131M08_CH6_CFG_ADDRESS_DATA CH6_CFG_DEFAULT
Default CH6_CFG address data.
#define ADS131M08_CH6_OCAL_MSB_ADDRESS_DATA CH6_OCAL_MSB_DEFAULT
Default CH6 OCAL_MSB address data.
#define ADS131M08_CH6_OCAL_LSB_ADDRESS_DATA CH6_OCAL_LSB_DEFAULT
Default CH6 OCAL_LSB address data.
#define ADS131M08_CH6_GCAL_MSB_ADDRESS_DATA CH6_GCAL_MSB_DEFAULT
Default CH6 GCAL_MSB address data.
#define ADS131M08_CH6_GCAL_LSB_ADDRESS_DATA CH6_GCAL_LSB_DEFAULT
Default CH6 GCAL_LSB address data.
#define ADS131M08_CH7_CFG_ADDRESS_DATA CH7_CFG_DEFAULT
Default CH7_CFG address data.
#define ADS131M08_CH7_OCAL_MSB_ADDRESS_DATA CH7_OCAL_MSB_DEFAULT
Default CH7 OCAL_MSB address data.
#define ADS131M08_CH7_OCAL_LSB_ADDRESS_DATA CH7_OCAL_LSB_DEFAULT
Default CH7 OCAL_LSB address data.
#define ADS131M08_CH7_GCAL_MSB_ADDRESS_DATA CH7_GCAL_MSB_DEFAULT
Default CH7 GCAL_MSB address data.
#define ADS131M08_CH7_GCAL_LSB_ADDRESS_DATA CH7_GCAL_LSB_DEFAULT
Default CH7 GCAL_LSB address data.
#define ADS_CHANNELCOUNT (8)
ADS channel count.
#define ADS_DMA_TRANSFER_DONE 0x01
ADS DMA Transfer Done.
#define ADS_DMA_TRANSFER_READY 0x00
ADS DMA Ready to transfer.
#define ADS_DMA_WAITING 0x01
ADS DMA waiting for dma interrupt.
#define ADS_DMA_IDLE 0x00
ADS DMA is in idle state.
#define ADS_REG_WORD_LENGTH_16BIT (2)
ADS register word length 16 bit.
#define ADS_REG_WORD_LENGTH_24BIT (3)
ADS register word length 24 bit.
#define ADS_REG_WORD_LENGTH_32BIT_SIGN_EXTEND (4)
ADS register word length 32 bit sign extended.
#define ADS_REG_WORD_LENGTH_32BIT_ZERO_PADDED (4)
ADS register word length 16 bit zero padded.
#define ADS_CMDLENGTH (1)
ADS command word length.
#define ADS_CRCLENGTH (1)
ADS CRC word length.
#define ADS_WORDLENGTH ADS_REG_WORD_LENGTH_24BIT
ADS data word length.
#define NUM_REGISTERS (64)
ADS number of registers.
#define ADS_BYTELENGTH ((ADS_CMDLENGTH + ADS_CRCLENGTH + ADS_CHANNELCOUNT) * ADS_WORDLENGTH)
ADS byte length.
#define ADS_CRC_INITAL_VALUE (0xFFFF)
ADS CRC initial value.
#define ADS_UPPER_BYTE_MASK (0xFF00)
upper byte mask for uint16_t
#define ADS_LOWER_BYTE_MASK (0x00FF)
lower byte mask for uint16_t
#define ADS_RESET_US (300)
ADS reset time.
#define ADS_WAKEUP_US (35)
ADS wakeup time.
#define ADS_SYNC_US (1)
ADS sync pulse time.
#define ID_ADDRESS ((uint8_t) 0x00)
Defines ID register address.
#define ID_DEFAULT ((uint16_t) 0x2000 | (ADS_CHANNELCOUNT << 8))
Defines ID register defaults.
#define ID_RESERVED_MASK ((uint16_t) 0xF000)
Defines ID register reserved mask.
#define ID_CHANCNT_MASK ((uint16_t) 0x0F00)
Defines ID register channel count mask.
#define ID_CHANCNT_4CH ((uint16_t) 0x0004 << 8)
Defines ID register channel count 4.
#define ID_CHANCNT_6CH ((uint16_t) 0x0006 << 8)
Defines ID register channel count 6.
#define ID_CHANCNT_8CH ((uint16_t) 0x0008 << 8)
Defines ID register channel count 8.
#define ID_REVID_MASK ((uint16_t) 0x00FF)
Defines ID register reserved mask.
#define ID_REVID_REVA ((uint16_t) 0x0000 << 0) /* DEFAULT */
Defines ID register reserved default.
#define STATUS_ADDRESS ((uint8_t) 0x01)
Defines status register address.
#define STATUS_DEFAULT ((uint16_t) 0x0500)
Defines status register default value.
#define STATUS_LOCK_MASK ((uint16_t) 0x8000)
Defines status register lock mask.
#define STATUS_LOCK_UNLOCKED ((uint16_t) 0x0000 << 15) /* DEFAULT */
Defines status register unlocked.
#define STATUS_LOCK_LOCKED ((uint16_t) 0x0001 << 15)
Defines status register locked.
#define STATUS_F_RESYNC_MASK ((uint16_t) 0x4000)
Defines status register resync mask.
#define STATUS_F_RESYNC_NO_FAULT ((uint16_t) 0x0000 << 14) /* DEFAULT */
Defines status register resync no fault.
#define STATUS_F_RESYNC_FAULT ((uint16_t) 0x0001 << 14)
Defines status register resync fault.
#define STATUS_REG_MAP_MASK ((uint16_t) 0x2000)
Defines status register reg map mask.
#define STATUS_REG_MAP_NO_CHANGE_CRC ((uint16_t) 0x0000 << 13) /* DEFAULT */
Defines status register reg map no CRC change.
#define STATUS_REG_MAP_CHANGED_CRC ((uint16_t) 0x0001 << 13)
Defines status register reg map CRC change.
#define STATUS_CRC_ERR_MASK ((uint16_t) 0x1000)
Defines status register CRC error mask.
#define STATUS_CRC_ERR_NO_CRC_ERROR ((uint16_t) 0x0000 << 12) /* DEFAULT */
Defines status register no CRC error.
#define STATUS_CRC_ERR_INPUT_CRC_ERROR ((uint16_t) 0x0001 << 12)
Defines status register CRC error.
#define STATUS_CRC_TYPE_MASK ((uint16_t) 0x0800)
Defines status register CRC type mask.
#define STATUS_CRC_TYPE_16BIT_CCITT ((uint16_t) 0x0000 << 11) /* DEFAULT */
Defines status register CRC type 16 bit CCITT.
#define STATUS_CRC_TYPE_16BIT_ANSI ((uint16_t) 0x0001 << 11)
Defines status register CRC type 16 bit ANSI.
#define STATUS_RESET_MASK ((uint16_t) 0x0400)
Defines status register reset mask.
#define STATUS_RESET_NO_RESET ((uint16_t) 0x0000 << 10)
Defines status register no reset.
#define STATUS_RESET_RESET_OCCURRED ((uint16_t) 0x0001 << 10) /* DEFAULT */
Defines status register reset.
#define STATUS_WLENGTH_MASK ((uint16_t) 0x0300)
Defines status register word length mask.
#define STATUS_WLENGTH_16BIT ((uint16_t) 0x0000 << 8)
Defines status register word length 16 bit.
#define STATUS_WLENGTH_24BIT ((uint16_t) 0x0001 << 8) /* DEFAULT */
Defines status register word length 24 bit.
#define STATUS_WLENGTH_32BIT_LSB_ZEROES ((uint16_t) 0x0002 << 8)
Defines status register word length 32 bits.
#define STATUS_WLENGTH_32BIT_MSB_SIGN_EXT ((uint16_t) 0x0003 << 8)
Defines status register word length 32 bit.
#define STATUS_DRDY7_MASK ((uint16_t) 0x0080)
Defines status register DRDY7 mask.
#define STATUS_DRDY7_NO_NEW_DATA ((uint16_t) 0x0000 << 7)
Defines status register DRDY7 no new data.
#define STATUS_DRDY7_NEW_DATA ((uint16_t) 0x0001 << 7)
Defines status register DRDY7 new data.
#define STATUS_DRDY6_MASK ((uint16_t) 0x0040)
Defines status register DRDY6 mask.
#define STATUS_DRDY6_NO_NEW_DATA ((uint16_t) 0x0000 << 6)
Defines status register DRDY6 no new data.
#define STATUS_DRDY6_NEW_DATA ((uint16_t) 0x0001 << 6)
Defines status register DRDY6 new data.
#define STATUS_DRDY5_MASK ((uint16_t) 0x0020)
Defines status register DRDY5 mask.
#define STATUS_DRDY5_NO_NEW_DATA ((uint16_t) 0x0000 << 5)
Defines status register DRDY5 no new data.
#define STATUS_DRDY5_NEW_DATA ((uint16_t) 0x0001 << 5)
Defines status register DRDY5 new data.
#define STATUS_DRDY4_MASK ((uint16_t) 0x0010)
Defines status register DRDY4 mask.
#define STATUS_DRDY4_NO_NEW_DATA ((uint16_t) 0x0000 << 4)
Defines status register DRDY4 no new data.
#define STATUS_DRDY4_NEW_DATA ((uint16_t) 0x0001 << 4)
Defines status register DRDY4 new data.
#define STATUS_DRDY3_MASK ((uint16_t) 0x0008)
Defines status register DRDY3 mask.
#define STATUS_DRDY3_NO_NEW_DATA ((uint16_t) 0x0000 << 3)
Defines status register DRDY3 no new data.
#define STATUS_DRDY3_NEW_DATA ((uint16_t) 0x0001 << 3)
Defines status register DRDY3 new data.
#define STATUS_DRDY2_MASK ((uint16_t) 0x0004)
Defines status register DRDY2 mask.
#define STATUS_DRDY2_NO_NEW_DATA ((uint16_t) 0x0000 << 2)
Defines status register DRDY2 no new data.
#define STATUS_DRDY2_NEW_DATA ((uint16_t) 0x0001 << 2)
Defines status register DRDY2 new data.
#define STATUS_DRDY1_MASK ((uint16_t) 0x0002)
Defines status register DRDY1 mask.
#define STATUS_DRDY1_NO_NEW_DATA ((uint16_t) 0x0000 << 1)
Defines status register DRDY1 no new data.
#define STATUS_DRDY1_NEW_DATA ((uint16_t) 0x0001 << 1)
Defines status register DRDY1 new data.
#define STATUS_DRDY0_MASK ((uint16_t) 0x0001)
Defines status register DRDY0 mask.
#define STATUS_DRDY0_NO_NEW_DATA ((uint16_t) 0x0000 << 0)
Defines status register DRDY0 no new data.
#define STATUS_DRDY0_NEW_DATA ((uint16_t) 0x0001 << 0)
Defines status register DRDY0 new data.
#define MODE_ADDRESS ((uint8_t) 0x02)
Defines mode register address.
#define MODE_DEFAULT ((uint16_t) 0x0510)
Defines mode register default.
#define MODE_RESERVED0_MASK ((uint16_t) 0xC000)
Defines mode register reserved mask.
#define MODE_REG_CRC_EN_MASK ((uint16_t) 0x2000)
Defines mode register CRC EN mask.
#define MODE_REG_CRC_EN_DISABLED ((uint16_t) 0x0000 << 13) /* DEFAULT */
Defines mode register CRC EN disabled.
#define MODE_REG_CRC_EN_ENABLED ((uint16_t) 0x0001 << 13)
Defines mode register CRC EN enabled.
#define MODE_RX_CRC_EN_MASK ((uint16_t) 0x1000)
Defines mode register RX CRC EN mask.
#define MODE_RX_CRC_EN_DISABLED ((uint16_t) 0x0000 << 12) /* DEFAULT */
Defines mode register RX CRC EN disabled.
#define MODE_RX_CRC_EN_ENABLED ((uint16_t) 0x0001 << 12)
Defines mode register RX CRC EN enabled.
#define MODE_CRC_TYPE_MASK ((uint16_t) 0x0800)
Defines mode register CRC type mask.
#define MODE_CRC_TYPE_16BIT_CCITT ((uint16_t) 0x0000 << 11) /* DEFAULT */
Defines mode register CRC type 16 bit CCITT.
#define MODE_CRC_TYPE_16BIT_ANSI ((uint16_t) 0x0001 << 11)
Defines mode register CRC type 16 bit ANSI.
#define MODE_RESET_MASK ((uint16_t) 0x0400)
Defines mode register reset mask.
#define MODE_RESET_NO_RESET ((uint16_t) 0x0000 << 10)
Defines mode register no reset.
#define MODE_RESET_RESET_OCCURRED ((uint16_t) 0x0001 << 10) /* DEFAULT */
Defines mode register reset occured.
#define MODE_WLENGTH_MASK ((uint16_t) 0x0300)
Defines mode register word length mask.
#define MODE_WLENGTH_16BIT ((uint16_t) 0x0000 << 8)
Defines mode register word length 16 bit.
#define MODE_WLENGTH_24BIT ((uint16_t) 0x0001 << 8)
Defines mode register word length 24 bit.
#define MODE_WLENGTH_32BIT_LSB_ZEROES ((uint16_t) 0x0002 << 8)
Defines mode register word length 32 bits.
#define MODE_WLENGTH_32BIT_MSB_SIGN_EXT ((uint16_t) 0x0003 << 8)
Defines mode register word length 32 bit.
#define MODE_RESERVED1_MASK ((uint16_t) 0x00E0)
Defines mode register reserved mask.
#define MODE_TIMEOUT_MASK ((uint16_t) 0x0010)
Defines mode register timeout mask.
#define MODE_TIMEOUT_DISABLED ((uint16_t) 0x0000 << 4)
Defines mode register timeout disabled.
#define MODE_TIMEOUT_ENABLED ((uint16_t) 0x0001 << 4) /* DEFAULT */
Defines mode register timeout enabled.
#define MODE_DRDY_SEL_MASK ((uint16_t) 0x000C)
Defines mode register DRDY_SEL mask.
#define MODE_DRDY_SEL_MOST_LAGGING ((uint16_t) 0x0000 << 2) /* DEFAULT */
Defines mode register DRDY_SEL most lagging.
#define MODE_DRDY_SEL_LOGIC_OR ((uint16_t) 0x0001 << 2)
Defines mode register DRDY_SEL logic OR.
#define MODE_DRDY_SEL_MOST_LEADING ((uint16_t) 0x0002 << 2)
Defines mode register DRDY_SEL most leading.
#define MODE_DRDY_HiZ_MASK ((uint16_t) 0x0002)
Defines mode register DRDY_HiZ mask.
#define MODE_DRDY_HiZ_LOGIC_HIGH ((uint16_t) 0x0000 << 1) /* DEFAULT */
Defines mode register DRDY_HiZ logic high.
#define MODE_DRDY_HiZ_HIGH_IMPEDANCE ((uint16_t) 0x0001 << 1)
Defines mode register DRDY_HiZ high impedence.
#define MODE_DRDY_FMT_MASK ((uint16_t) 0x0001)
Defines mode register DRDY_FMT mask.
#define MODE_DRDY_FMT_LOGIC_LOW ((uint16_t) 0x0000 << 0) /* DEFAULT */
Defines mode register DRDY_FMT low.
#define MODE_DRDY_FMT_NEG_PULSE_FIXED_WIDTH ((uint16_t) 0x0001 << 0)
Defines mode register DRDY_FMT neg pulse fixed width.
#define CLOCK_ADDRESS ((uint8_t) 0x03)
Defines clock register address.
#define CLOCK_DEFAULT ((uint16_t) 0xFF0E)
Defines clock register default.
#define CLOCK_CH7_EN_MASK ((uint16_t) 0x8000)
Defines clock register CH7 EN mask.
#define CLOCK_CH7_EN_DISABLED ((uint16_t) 0x0000 << 15)
Defines clock register CH7 EN Disabled.
#define CLOCK_CH7_EN_ENABLED ((uint16_t) 0x0001 << 15)
Defines clock register CH7 EN enabled.
#define CLOCK_CH6_EN_MASK ((uint16_t) 0x4000)
Defines clock register CH6 EN mask.
#define CLOCK_CH6_EN_DISABLED ((uint16_t) 0x0000 << 14)
Defines clock register CH6 EN Disabled.
#define CLOCK_CH6_EN_ENABLED ((uint16_t) 0x0001 << 14)
Defines clock register CH6 EN enabled.
#define CLOCK_CH5_EN_MASK ((uint16_t) 0x2000)
Defines clock register CH5 EN mask.
#define CLOCK_CH5_EN_DISABLED ((uint16_t) 0x0000 << 13)
Defines clock register CH5 EN Disabled.
#define CLOCK_CH5_EN_ENABLED ((uint16_t) 0x0001 << 13)
Defines clock register CH5 EN enabled.
#define CLOCK_CH4_EN_MASK ((uint16_t) 0x1000)
Defines clock register CH4 EN mask.
#define CLOCK_CH4_EN_DISABLED ((uint16_t) 0x0000 << 12)
Defines clock register CH4 EN Disabled.
#define CLOCK_CH4_EN_ENABLED ((uint16_t) 0x0001 << 12)
Defines clock register CH4 EN enabled.
#define CLOCK_CH3_EN_MASK ((uint16_t) 0x0800)
Defines clock register CH3 EN mask.
#define CLOCK_CH3_EN_DISABLED ((uint16_t) 0x0000 << 11)
Defines clock register CH3 EN Disabled.
#define CLOCK_CH3_EN_ENABLED ((uint16_t) 0x0001 << 11)
Defines clock register CH3 EN enabled.
#define CLOCK_CH2_EN_MASK ((uint16_t) 0x0400)
Defines clock register CH2 EN mask.
#define CLOCK_CH2_EN_DISABLED ((uint16_t) 0x0000 << 10)
Defines clock register CH2 EN Disabled.
#define CLOCK_CH2_EN_ENABLED ((uint16_t) 0x0001 << 10)
Defines clock register CH2 EN enabled.
#define CLOCK_CH1_EN_MASK ((uint16_t) 0x0200)
Defines clock register CH1 EN mask.
#define CLOCK_CH1_EN_DISABLED ((uint16_t) 0x0000 << 9)
Defines clock register CH1 EN Disabled.
#define CLOCK_CH1_EN_ENABLED ((uint16_t) 0x0001 << 9)
Defines clock register CH1 EN enabled.
#define CLOCK_CH0_EN_MASK ((uint16_t) 0x0100)
Defines clock register CH0 EN mask.
#define CLOCK_CH0_EN_DISABLED ((uint16_t) 0x0000 << 8)
Defines clock register CH0 EN Disabled.
#define CLOCK_CH0_EN_ENABLED ((uint16_t) 0x0001 << 8) /* DEFAULT */
Defines clock register CH0 EN enabled.
#define CLOCK_RESERVED_MASK_M04 ((uint16_t) 0x00E0)
Defines clock register reserved mask 04.
#define CLOCK_RESERVED_MASK_M08 ((uint16_t) 0x0020)
Defines clock register reserved mask 08.
#define CLOCK_XTAL_DIS_MASK ((uint16_t) 0x0080)
Defines clock register XTAL DIS mask.
#define CLOCK_XTAL_DIS_ENABLED ((uint16_t) 0x0000 << 7) /* DEFAULT */
Defines clock register XTAL DIS enabled.
#define CLOCK_XTAL_DIS_DISABLED ((uint16_t) 0x0001 << 7)
Defines clock register XTAL DIS disabled.
#define CLOCK_EXTREF_EN_MASK ((uint16_t) 0x0040)
Defines clock register EXTREF_EN mask.
#define CLOCK_EXTREF_EN_DISABLED ((uint16_t) 0x0000 << 6) /* DEFAULT */
Defines clock register EXTREF_EN disabled.
#define CLOCK_EXTREF_EN_ENABLED ((uint16_t) 0x0001 << 6)
Defines clock register EXTREF_EN enabled.
#define CLOCK_OSR_MASK ((uint16_t) 0x001C)
Defines clock register OSR mask.
#define CLOCK_OSR_128 ((uint16_t) 0x0000 << 2)
Defines clock register 128 mask.
#define CLOCK_OSR_256 ((uint16_t) 0x0001 << 2)
Defines clock register 256 mask.
#define CLOCK_OSR_512 ((uint16_t) 0x0002 << 2)
Defines clock register 512 mask.
#define CLOCK_OSR_1024 ((uint16_t) 0x0003 << 2) /* DEFAULT */
Defines clock register 1024 mask.
#define CLOCK_OSR_2048 ((uint16_t) 0x0004 << 2)
Defines clock register 2048 mask.
#define CLOCK_OSR_4096 ((uint16_t) 0x0005 << 2)
Defines clock register 4096 mask.
#define CLOCK_OSR_8192 ((uint16_t) 0x0006 << 2)
Defines clock register 8192 mask.
#define CLOCK_OSR_16384 ((uint16_t) 0x0007 << 2)
Defines clock register 16384 mask.
#define CLOCK_PWR_MASK ((uint16_t) 0x0003)
Defines clock register PWR mask.
#define CLOCK_PWR_VLP ((uint16_t) 0x0000 << 0)
Defines clock register PWR VLP.
#define CLOCK_PWR_LP ((uint16_t) 0x0001 << 0)
Defines clock register PWR LP.
#define CLOCK_PWR_HR ((uint16_t) 0x0002 << 0) /* DEFAULT */
Defines clock register PWR HR.
#define GAIN1_ADDRESS ((uint8_t) 0x04)
Defines GAIN1 register Address.
#define GAIN1_DEFAULT ((uint16_t) 0x0000)
Defines GAIN1 register Defaults.
#define GAIN1_RESERVED0_MASK ((uint16_t) 0x8000)
Defines GAIN1 register reserved0 mask.
#define GAIN1_PGAGAIN3_MASK ((uint16_t) 0x7000)
Defines GAIN1 register PGAGAIB3 mask.
#define GAIN1_PGAGAIN3_1 ((uint16_t) 0x0000 << 12) /* DEFAULT */
Defines GAIN1 register PGAGAIB3 1.
#define GAIN1_PGAGAIN3_2 ((uint16_t) 0x0001 << 12)
Defines GAIN1 register PGAGAIB3 2.
#define GAIN1_PGAGAIN3_4 ((uint16_t) 0x0002 << 12)
Defines GAIN1 register PGAGAIB3 4.
#define GAIN1_PGAGAIN3_8 ((uint16_t) 0x0003 << 12)
Defines GAIN1 register PGAGAIB3 8.
#define GAIN1_PGAGAIN3_16 ((uint16_t) 0x0004 << 12)
Defines GAIN1 register PGAGAIB3 16.
#define GAIN1_PGAGAIN3_32 ((uint16_t) 0x0005 << 12)
Defines GAIN1 register PGAGAIB3 32.
#define GAIN1_PGAGAIN3_64 ((uint16_t) 0x0006 << 12)
Defines GAIN1 register PGAGAIB3 64.
#define GAIN1_PGAGAIN3_128 ((uint16_t) 0x0007 << 12)
Defines GAIN1 register PGAGAIB3 mas128k.
#define GAIN1_RESERVED1_MASK ((uint16_t) 0x0800)
Defines GAIN1 register reserved1 mask.
#define GAIN1_PGAGAIN2_MASK ((uint16_t) 0x0700)
Defines GAIN1 register PGAGAIB2 mask.
#define GAIN1_PGAGAIN2_1 ((uint16_t) 0x0000 << 8) /* DEFAULT */
Defines GAIN1 register PGAGAIB2 1.
#define GAIN1_PGAGAIN2_2 ((uint16_t) 0x0001 << 8)
Defines GAIN1 register PGAGAIB2 2.
#define GAIN1_PGAGAIN2_4 ((uint16_t) 0x0002 << 8)
Defines GAIN1 register PGAGAIB2 4.
#define GAIN1_PGAGAIN2_8 ((uint16_t) 0x0003 << 8)
Defines GAIN1 register PGAGAIB2 8.
#define GAIN1_PGAGAIN2_16 ((uint16_t) 0x0004 << 8)
Defines GAIN1 register PGAGAIB2 16.
#define GAIN1_PGAGAIN2_32 ((uint16_t) 0x0005 << 8)
Defines GAIN1 register PGAGAIB2 32.
#define GAIN1_PGAGAIN2_64 ((uint16_t) 0x0006 << 8)
Defines GAIN1 register PGAGAIB2 64.
#define GAIN1_PGAGAIN2_128 ((uint16_t) 0x0007 << 8)
Defines GAIN1 register PGAGAIB2 128.
#define GAIN1_RESERVED2_MASK ((uint16_t) 0x0080)
Defines GAIN1 register reserved2 mask.
#define GAIN1_PGAGAIN1_MASK ((uint16_t) 0x0070)
Defines GAIN1 register PGAGAIB1 mask.
#define GAIN1_PGAGAIN1_1 ((uint16_t) 0x0000 << 4) /* DEFAULT */
Defines GAIN1 register PGAGAIB1 1.
#define GAIN1_PGAGAIN1_2 ((uint16_t) 0x0001 << 4)
Defines GAIN1 register PGAGAIB1 2.
#define GAIN1_PGAGAIN1_4 ((uint16_t) 0x0002 << 4)
Defines GAIN1 register PGAGAIB1 4.
#define GAIN1_PGAGAIN1_8 ((uint16_t) 0x0003 << 4)
Defines GAIN1 register PGAGAIB1 8.
#define GAIN1_PGAGAIN1_16 ((uint16_t) 0x0004 << 4)
Defines GAIN1 register PGAGAIB1 16.
#define GAIN1_PGAGAIN1_32 ((uint16_t) 0x0005 << 4)
Defines GAIN1 register PGAGAIB1 32.
#define GAIN1_PGAGAIN1_64 ((uint16_t) 0x0006 << 4)
Defines GAIN1 register PGAGAIB1 64.
#define GAIN1_PGAGAIN1_128 ((uint16_t) 0x0007 << 4)
Defines GAIN1 register PGAGAIB1 128.
#define GAIN1_RESERVED3_MASK ((uint16_t) 0x0008)
Defines GAIN1 register reserved3 mask.
#define GAIN1_PGAGAIN0_MASK ((uint16_t) 0x0007)
Defines GAIN1 register PGAGAIB0 mask.
#define GAIN1_PGAGAIN0_1 ((uint16_t) 0x0000 << 0) /* DEFAULT */
Defines GAIN1 register PGAGAIB0 1.
#define GAIN1_PGAGAIN0_2 ((uint16_t) 0x0001 << 0)
Defines GAIN1 register PGAGAIB0 2.
#define GAIN1_PGAGAIN0_4 ((uint16_t) 0x0002 << 0)
Defines GAIN1 register PGAGAIB0 4.
#define GAIN1_PGAGAIN0_8 ((uint16_t) 0x0003 << 0)
Defines GAIN1 register PGAGAIB0 8.
#define GAIN1_PGAGAIN0_16 ((uint16_t) 0x0004 << 0)
Defines GAIN1 register PGAGAIB0 16.
#define GAIN1_PGAGAIN0_32 ((uint16_t) 0x0005 << 0)
Defines GAIN1 register PGAGAIB0 32.
#define GAIN1_PGAGAIN0_64 ((uint16_t) 0x0006 << 0)
Defines GAIN1 register PGAGAIB0 64.
#define GAIN1_PGAGAIN0_128 ((uint16_t) 0x0007 << 0)
Defines GAIN1 register PGAGAIB0 128.
#define GAIN2_ADDRESS ((uint8_t) 0x05)
Defines GAIN2 register Address.
#define GAIN2_DEFAULT ((uint16_t) 0x0000)
Defines GAIN2 register Default.
#define GAIN2_RESERVED0_MASK ((uint16_t) 0x8000)
Defines GAIN2 register reserved0 mask.
#define GAIN2_PGAGAIN7_MASK ((uint16_t) 0x7000)
Defines GAIN2 register PGAGAIN7 mask.
#define GAIN2_PGAGAIN7_1 ((uint16_t) 0x0000 << 12) /* DEFAULT */
Defines GAIN2 register PGAGAIN7 1.
#define GAIN2_PGAGAIN7_2 ((uint16_t) 0x0001 << 12)
Defines GAIN2 register PGAGAIN7 2.
#define GAIN2_PGAGAIN7_4 ((uint16_t) 0x0002 << 12)
Defines GAIN2 register PGAGAIN7 4.
#define GAIN2_PGAGAIN7_8 ((uint16_t) 0x0003 << 12)
Defines GAIN2 register PGAGAIN7 8.
#define GAIN2_PGAGAIN7_16 ((uint16_t) 0x0004 << 12)
Defines GAIN2 register PGAGAIN7 16.
#define GAIN2_PGAGAIN7_32 ((uint16_t) 0x0005 << 12)
Defines GAIN2 register PGAGAIN7 32.
#define GAIN2_PGAGAIN7_64 ((uint16_t) 0x0006 << 12)
Defines GAIN2 register PGAGAIN7 64.
#define GAIN2_PGAGAIN7_128 ((uint16_t) 0x0007 << 12)
Defines GAIN2 register PGAGAIN7 128.
#define GAIN2_RESERVED1_MASK ((uint16_t) 0x0800)
Defines GAIN2 register reserved1 mask.
#define GAIN2_PGAGAIN6_MASK ((uint16_t) 0x0700)
Defines GAIN2 register PGAGAIN6 mask.
#define GAIN2_PGAGAIN6_1 ((uint16_t) 0x0000 << 8) /* DEFAULT */
Defines GAIN2 register PGAGAIN6 1.
#define GAIN2_PGAGAIN6_2 ((uint16_t) 0x0001 << 8)
Defines GAIN2 register PGAGAIN6 2.
#define GAIN2_PGAGAIN6_4 ((uint16_t) 0x0002 << 8)
Defines GAIN2 register PGAGAIN6 4.
#define GAIN2_PGAGAIN6_8 ((uint16_t) 0x0003 << 8)
Defines GAIN2 register PGAGAIN6 8.
#define GAIN2_PGAGAIN6_16 ((uint16_t) 0x0004 << 8)
Defines GAIN2 register PGAGAIN6 16.
#define GAIN2_PGAGAIN6_32 ((uint16_t) 0x0005 << 8)
Defines GAIN2 register PGAGAIN6 32.
#define GAIN2_PGAGAIN6_64 ((uint16_t) 0x0006 << 8)
Defines GAIN2 register PGAGAIN6 64.
#define GAIN2_PGAGAIN6_128 ((uint16_t) 0x0007 << 8)
Defines GAIN2 register PGAGAIN6 128.
#define GAIN2_RESERVED2_MASK ((uint16_t) 0x0080)
Defines GAIN2 register reserved2 mask.
#define GAIN2_PGAGAIN5_MASK ((uint16_t) 0x0070)
Defines GAIN2 register PGAGAIN5 mask.
#define GAIN2_PGAGAIN5_1 ((uint16_t) 0x0000 << 4) /* DEFAULT */
Defines GAIN2 register PGAGAIN5 1.
#define GAIN2_PGAGAIN5_2 ((uint16_t) 0x0001 << 4)
Defines GAIN2 register PGAGAIN5 2.
#define GAIN2_PGAGAIN5_4 ((uint16_t) 0x0002 << 4)
Defines GAIN2 register PGAGAIN5 4.
#define GAIN2_PGAGAIN5_8 ((uint16_t) 0x0003 << 4)
Defines GAIN2 register PGAGAIN5 8.
#define GAIN2_PGAGAIN5_16 ((uint16_t) 0x0004 << 4)
Defines GAIN2 register PGAGAIN5 16.
#define GAIN2_PGAGAIN5_32 ((uint16_t) 0x0005 << 4)
Defines GAIN2 register PGAGAIN5 32.
#define GAIN2_PGAGAIN5_64 ((uint16_t) 0x0006 << 4)
Defines GAIN2 register PGAGAIN5 64.
#define GAIN2_PGAGAIN5_128 ((uint16_t) 0x0007 << 4)
Defines GAIN2 register PGAGAIN5 128.
#define GAIN2_RESERVED3_MASK ((uint16_t) 0x0008)
Defines GAIN2 register reserved3 mask.
#define GAIN2_PGAGAIN4_MASK ((uint16_t) 0x0007)
Defines GAIN2 register PGAGAIN4 mask.
#define GAIN2_PGAGAIN4_1 ((uint16_t) 0x0000 << 0) /* DEFAULT */
Defines GAIN2 register PGAGAIN4 1.
#define GAIN2_PGAGAIN4_2 ((uint16_t) 0x0001 << 0)
Defines GAIN2 register PGAGAIN4 2.
#define GAIN2_PGAGAIN4_4 ((uint16_t) 0x0002 << 0)
Defines GAIN2 register PGAGAIN4 4.
#define GAIN2_PGAGAIN4_8 ((uint16_t) 0x0003 << 0)
Defines GAIN2 register PGAGAIN4 8.
#define GAIN2_PGAGAIN4_16 ((uint16_t) 0x0004 << 0)
Defines GAIN2 register PGAGAIN4 16.
#define GAIN2_PGAGAIN4_32 ((uint16_t) 0x0005 << 0)
Defines GAIN2 register PGAGAIN4 32.
#define GAIN2_PGAGAIN4_64 ((uint16_t) 0x0006 << 0)
Defines GAIN2 register PGAGAIN4 64.
#define GAIN2_PGAGAIN4_128 ((uint16_t) 0x0007 << 0)
Defines GAIN2 register PGAGAIN4 128.
#define CFG_ADDRESS ((uint8_t) 0x06)
Defines CFG register Address.
#define CFG_DEFAULT ((uint16_t) 0x0600)
Defines CFG register defaults.
#define CFG_RESERVED0_MASK ((uint16_t) 0xE000)
Defines CFG register reserved mask.
#define CFG_GC_DLY_MASK ((uint16_t) 0x1E00)
Defines CFG register GC DLY mask.
#define CFG_GC_DLY_2 ((uint16_t) 0x0000 << 9)
Defines CFG register GC DLY 2.
#define CFG_GC_DLY_4 ((uint16_t) 0x0001 << 9)
Defines CFG register GC DLY 4.
#define CFG_GC_DLY_8 ((uint16_t) 0x0002 << 9)
Defines CFG register GC DLY 8.
#define CFG_GC_DLY_16 ((uint16_t) 0x0003 << 9) /* DEFAULT */
Defines CFG register GC DLY 16.
#define CFG_GC_DLY_32 ((uint16_t) 0x0004 << 9)
Defines CFG register GC DLY 32.
#define CFG_GC_DLY_64 ((uint16_t) 0x0005 << 9)
Defines CFG register GC DLY 64.
#define CFG_GC_DLY_128 ((uint16_t) 0x0006 << 9)
Defines CFG register GC DLY 128.
#define CFG_GC_DLY_256 ((uint16_t) 0x0007 << 9)
Defines CFG register GC DLY 256.
#define CFG_GC_DLY_512 ((uint16_t) 0x0008 << 9)
Defines CFG register GC DLY 512.
#define CFG_GC_DLY_1024 ((uint16_t) 0x0009 << 9)
Defines CFG register GC DLY 1024.
#define CFG_GC_DLY_2048 ((uint16_t) 0x000A << 9)
Defines CFG register GC DLY 2048.
#define CFG_GC_DLY_4096 ((uint16_t) 0x000B << 9)
Defines CFG register GC DLY 4096.
#define CFG_GC_DLY_8192 ((uint16_t) 0x000C << 9)
Defines CFG register GC DLY 8192.
#define CFG_GC_DLY_16484 ((uint16_t) 0x000D << 9)
Defines CFG register GC DLY 16484.
#define CFG_GC_DLY_32768 ((uint16_t) 0x000E << 9)
Defines CFG register GC DLY 32768.
#define CFG_GC_DLY_65536 ((uint16_t) 0x000F << 9)
Defines CFG register GC DLY 65536.
#define CFG_GC_EN_MASK ((uint16_t) 0x0100)
Defines CFG register GC EN mask.
#define CFG_GC_EN_DISABLED ((uint16_t) 0x0000 << 8) /* DEFAULT */
Defines CFG register GC EN disabled.
#define CFG_GC_EN_ENABLED ((uint16_t) 0x0001 << 8)
Defines CFG register GC EN enabled.
#define CFG_CD_ALLCH_MASK ((uint16_t) 0x0080)
Defines CFG register CD ALLCH mask.
#define CFG_CD_ALLCH_ANY_CHANNEL ((uint16_t) 0x0000 << 7) /* DEFAULT */
Defines CFG register CD ALLCH any.
#define CFG_CD_ALLCH_ALL_CHANNELS ((uint16_t) 0x0001 << 7)
Defines CFG register CD ALLCH all.
#define CFG_CD_NUM_MASK ((uint16_t) 0x0070)
Defines CFG register CD NUM mask.
#define CFG_CD_NUM_1 ((uint16_t) 0x0000 << 4) /* DEFAULT */
Defines CFG register CD NUM 1.
#define CFG_CD_NUM_2 ((uint16_t) 0x0001 << 4)
Defines CFG register CD NUM 2.
#define CFG_CD_NUM_4 ((uint16_t) 0x0002 << 4)
Defines CFG register CD NUM 4.
#define CFG_CD_NUM_8 ((uint16_t) 0x0003 << 4)
Defines CFG register CD NUM 8.
#define CFG_CD_NUM_16 ((uint16_t) 0x0004 << 4)
Defines CFG register CD NUM 16.
#define CFG_CD_NUM_32 ((uint16_t) 0x0005 << 4)
Defines CFG register CD NUM 32.
#define CFG_CD_NUM_64 ((uint16_t) 0x0006 << 4)
Defines CFG register CD NUM 64.
#define CFG_CD_NUM_128 ((uint16_t) 0x0007 << 4)
Defines CFG register CD NUM 128.
#define CFG_CD_LEN_MASK ((uint16_t) 0x000E)
Defines CFG register CD LEn mask.
#define CFG_CD_LEN_128 ((uint16_t) 0x0000 << 1) /* DEFAULT */
Defines CFG register CD LEn 128.
#define CFG_CD_LEN_256 ((uint16_t) 0x0001 << 1)
Defines CFG register CD LEn 256.
#define CFG_CD_LEN_512 ((uint16_t) 0x0002 << 1)
Defines CFG register CD LEn 512.
#define CFG_CD_LEN_768 ((uint16_t) 0x0003 << 1)
Defines CFG register CD LEn 768.
#define CFG_CD_LEN_1280 ((uint16_t) 0x0004 << 1)
Defines CFG register CD LEn 1280.
#define CFG_CD_LEN_1792 ((uint16_t) 0x0005 << 1)
Defines CFG register CD LEn 1790.
#define CFG_CD_LEN_2560 ((uint16_t) 0x0006 << 1)
Defines CFG register CD LEn 2560.
#define CFG_CD_LEN_3584 ((uint16_t) 0x0007 << 1)
Defines CFG register CD LEn 3584.
#define CFG_CD_EN_MASK ((uint16_t) 0x0001)
Defines CFG register CD EN mask.
#define CFG_CD_EN_DISABLED ((uint16_t) 0x0000 << 0) /* DEFAULT */
Defines CFG register CD EN disabled.
#define CFG_CD_EN_ENABLED ((uint16_t) 0x0001 << 0)
Defines CFG register CD EN enabled.
#define THRSHLD_MSB_ADDRESS ((uint8_t) 0x07)
Defines THRSHLD_MSB register address.
#define THRSHLD_MSB_DEFAULT ((uint16_t) 0x0000)
Defines THRSHLD_MSB register default.
#define THRSHLD_MSB_CD_TH_MSB_MASK ((uint16_t) 0xFFFF)
Defines THRSHLD_MSB register mask.
#define THRSHLD_LSB_ADDRESS ((uint8_t) 0x08)
Defines THRSHLD_LSB register address.
#define THRSHLD_LSB_DEFAULT ((uint16_t) 0x0000)
Defines THRSHLD_LSB register default.
#define THRSHLD_LSB_CD_TH_LSB_MASK ((uint16_t) 0xFF00)
Defines THRSHLD_LSB register mask.
#define THRSHLD_LSB_RESERVED0_MASK ((uint16_t) 0x00F0)
Defines THRSHLD_LSB register reserved mask.
#define THRSHLD_LSB_DCBLOCK_MASK ((uint16_t) 0x000F)
Defines THRSHLD_LSB register DCBLOCk mask.
#define THRSHLD_LSB_DCBLOCK_DISABLED ((uint16_t) 0x0000 << 0)
Defines THRSHLD_LSB register DCBLOCk disabled.
#define THRSHLD_LSB_DCBLOCK_181P0Hz ((uint16_t) 0x0001 << 0)
Defines THRSHLD_LSB register DCBLOCk 181P0.
#define THRSHLD_LSB_DCBLOCK_84p8Hz ((uint16_t) 0x0002 << 0)
Defines THRSHLD_LSB register DCBLOCk 84P8.
#define THRSHLD_LSB_DCBLOCK_41p1Hz ((uint16_t) 0x0003 << 0)
Defines THRSHLD_LSB register DCBLOCk 41P1.
#define THRSHLD_LSB_DCBLOCK_20p2Hz ((uint16_t) 0x0004 << 0)
Defines THRSHLD_LSB register DCBLOCk 20P2.
#define THRSHLD_LSB_DCBLOCK_10p0Hz ((uint16_t) 0x0005 << 0)
Defines THRSHLD_LSB register DCBLOCk 10P0.
#define THRSHLD_LSB_DCBLOCK_4p99Hz ((uint16_t) 0x0006 << 0)
Defines THRSHLD_LSB register DCBLOCk 4P99.
#define THRSHLD_LSB_DCBLOCK_2p49Hz ((uint16_t) 0x0007 << 0)
Defines THRSHLD_LSB register DCBLOCk 2P49.
#define THRSHLD_LSB_DCBLOCK_1p24Hz ((uint16_t) 0x0008 << 0)
Defines THRSHLD_LSB register DCBLOCk 1P24.
#define THRSHLD_LSB_DCBLOCK_622mHz ((uint16_t) 0x0009 << 0)
Defines THRSHLD_LSB register DCBLOCk 622m.
#define THRSHLD_LSB_DCBLOCK_311mHz ((uint16_t) 0x000A << 0)
Defines THRSHLD_LSB register DCBLOCk 311m.
#define THRSHLD_LSB_DCBLOCK_155mHz ((uint16_t) 0x000B << 0)
Defines THRSHLD_LSB register DCBLOCk 155m.
#define THRSHLD_LSB_DCBLOCK_77p7mHz ((uint16_t) 0x000C << 0)
Defines THRSHLD_LSB register DCBLOCk 77P7m.
#define THRSHLD_LSB_DCBLOCK_38p9mHz ((uint16_t) 0x000D << 0)
Defines THRSHLD_LSB register DCBLOCk 38p9m.
#define THRSHLD_LSB_DCBLOCK_19p4mHz ((uint16_t) 0x000F << 0)
Defines THRSHLD_LSB register DCBLOCk 19P4m.
#define THRSHLD_LSB_DCBLOCK_9p70mHz ((uint16_t) 0x0007 << 0)
Defines THRSHLD_LSB register DCBLOCk 9P7m.
#define CH0_CFG_ADDRESS ((uint8_t) 0x09)
Define CH0 CFG register Address.
#define CH0_CFG_DEFAULT ((uint16_t) 0x0000)
Define CH0 CFG register deafult.
#define CH0_CFG_PHASE0_MASK ((uint16_t) 0xFFC0)
Define CH0 CFG register Phase0 mask.
#define PHASEn_SHIFT (6)
Define CH0 CFG register Phase0 shift.
#define SET_PHASE_REGISTER_VALUE(phase_shift) ((phase_shift)<<PHASEn_SHIFT)
Define CH0 CFG register Phase0 register value.
#define CH0_CFG_RESERVED0_MASK ((uint16_t) 0x003C)
Define CH0 CFG register reserved mask.
#define CH0_CFG_MUX0_MASK ((uint16_t) 0x0003)
Define CH0 CFG register MUX0 mask.
#define CH0_CFG_MUX0_AIN0P_AIN0N ((uint16_t) 0x0000 << 0) /* DEFAULT */
Define CH0 CFG register MUX0 AIN0P_AIN0N.
#define CH0_CFG_MUX0_ADC_INPUT_SHORT ((uint16_t) 0x0001 << 0)
Define CH0 CFG register MUX0 ADC input short.
#define CH0_CFG_MUX0_DC_DIAGNOSTIC ((uint16_t) 0x0002 << 0)
Define CH0 CFG register MUX0 DC DIAGNOSTIC.
#define CH0_CFG_MUX0_AC_DIAGNOSTIC ((uint16_t) 0x0003 << 0)
Define CH0 CFG register MUX0 AC DIAGNOSTIC.
#define CH0_OCAL_MSB_ADDRESS ((uint8_t) 0x0A)
Define CH0 OCAL MSB register Address.
#define CH0_OCAL_MSB_DEFAULT ((uint16_t) 0x0000)
Define CH0 OCAL MSB register default.
#define CH0_OCAL_MSB_OCAL0_MSB_MASK ((uint16_t) 0xFFFF)
Define CH0 OCAL MSB register mask.
#define CH0_OCAL_LSB_ADDRESS ((uint8_t) 0x0B)
Define CH0 OCAL LSB register Address.
#define CH0_OCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH0 OCAL LSB register default.
#define CH0_OCAL_LSB_OCAL0_LSB_MASK ((uint16_t) 0xFF00)
Define CH0 OCAL LSB register mask.
#define CH0_OCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH0 OCAL LSB register reserved mask.
#define CH0_GCAL_MSB_ADDRESS ((uint8_t) 0x0C)
Define CH0 GCAL MSB register Address.
#define CH0_GCAL_MSB_DEFAULT ((uint16_t) 0x8000)
Define CH0 GCAL MSB register default.
#define CH0_GCAL_MSB_GCAL0_MSB_MASK ((uint16_t) 0xFFFF)
Define CH0 GCAL MSB register mask.
#define CH0_GCAL_LSB_ADDRESS ((uint8_t) 0x0D)
Define CH0 GCAL LSB register Address.
#define CH0_GCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH0 GCAL LSB register default.
#define CH0_GCAL_LSB_GCAL0_LSB_MASK ((uint16_t) 0xFF00)
Define CH0 GCAL LSB register mask.
#define CH0_GCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH0 GCAL LSB register reserved mask.
#define CH1_CFG_ADDRESS ((uint8_t) 0x0E)
Define CH1 CFG register Address.
#define CH1_CFG_DEFAULT ((uint16_t) 0x0000)
Define CH1 CFG register Default.
#define CH1_CFG_PHASE1_MASK ((uint16_t) 0xFFC0)
Define CH1 CFG register phase1 mask.
#define CH1_CFG_RESERVED0_MASK ((uint16_t) 0x003C)
Define CH1 CFG register reserved mask.
#define CH1_CFG_MUX1_MASK ((uint16_t) 0x0003)
Define CH1 CFG register MUX1 mask.
#define CH1_CFG_MUX1_AIN1P_AIN1N ((uint16_t) 0x0000 << 0) /* DEFAULT */
Define CH1 CFG register MUX1 AIN1P_AIN1N.
#define CH1_CFG_MUX1_ADC_INPUT_SHORT ((uint16_t) 0x0001 << 0)
Define CH1 CFG register MUX1 ADC input short.
#define CH1_CFG_MUX1_DC_DIAGNOSTIC ((uint16_t) 0x0002 << 0)
Define CH1 CFG register MUX1 dc diagnostic.
#define CH1_CFG_MUX1_AC_DIAGNOSTIC ((uint16_t) 0x0003 << 0)
Define CH1 CFG register MUX1 ac diagnostic.
#define CH1_OCAL_MSB_ADDRESS ((uint8_t) 0x0F)
Define CH1 OCAL MSB register Address.
#define CH1_OCAL_MSB_DEFAULT ((uint16_t) 0x0000)
Define CH1 OCAL MSB register default.
#define CH1_OCAL_MSB_OCAL1_MSB_MASK ((uint16_t) 0xFFFF)
Define CH1 OCAL MSB register mask.
#define CH1_OCAL_LSB_ADDRESS ((uint8_t) 0x10)
Define CH1 OCAL LSB register Address.
#define CH1_OCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH1 OCAL LSB register Defaullt.
#define CH1_OCAL_LSB_OCAL1_LSB_MASK ((uint16_t) 0xFF00)
Define CH1 OCAL LSB register mask.
#define CH1_OCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH1 OCAL LSB register reserved mask.
#define CH1_GCAL_MSB_ADDRESS ((uint8_t) 0x11)
Define CH1 GCAL MSB register Address.
#define CH1_GCAL_MSB_DEFAULT ((uint16_t) 0x8000)
Define CH1 GCAL MSB register default.
#define CH1_GCAL_MSB_GCAL1_MSB_MASK ((uint16_t) 0xFFFF)
Define CH1 GCAL MSB register mask.
#define CH1_GCAL_LSB_ADDRESS ((uint8_t) 0x12)
Define CH1 GCAL LSB register Address.
#define CH1_GCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH1 GCAL LSB register default.
#define CH1_GCAL_LSB_GCAL1_LSB_MASK ((uint16_t) 0xFF00)
Define CH1 GCAL LSB register mask.
#define CH1_GCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH1 GCAL LSB register reserved mask.
#define CH2_CFG_ADDRESS ((uint8_t) 0x13)
Define CH2 CFG register Address.
#define CH2_CFG_DEFAULT ((uint16_t) 0x0000)
Define CH2 CFG register Default.
#define CH2_CFG_PHASE2_MASK ((uint16_t) 0xFFC0)
Define CH2 CFG register Phase2 mask.
#define CH2_CFG_RESERVED0_MASK ((uint16_t) 0x003C)
Define CH2 CFG register reserved0 mask.
#define CH2_CFG_MUX2_MASK ((uint16_t) 0x0003)
Define CH2 CFG register MUX mask.
#define CH2_CFG_MUX2_AIN2P_AIN2N ((uint16_t) 0x0000 << 0) /* DEFAULT */
Define CH2 CFG register MUX AIN2P_AIN2N.
#define CH2_CFG_MUX2_ADC_INPUT_SHORT ((uint16_t) 0x0001 << 0)
Define CH2 CFG register MUX ADC input short.
#define CH2_CFG_MUX2_DC_DIAGNOSTIC ((uint16_t) 0x0002 << 0)
Define CH2 CFG register MUX dc diagnostic.
#define CH2_CFG_MUX2_AC_DIAGNOSTIC ((uint16_t) 0x0003 << 0)
Define CH2 CFG register MUX ac diagnostic.
#define CH2_OCAL_MSB_ADDRESS ((uint8_t) 0x14)
Define CH2 OCAL MSB register Address.
#define CH2_OCAL_MSB_DEFAULT ((uint16_t) 0x0000)
Define CH2 OCAL MSB register default.
#define CH2_OCAL_MSB_OCAL2_MSB_MASK ((uint16_t) 0xFFFF)
Define CH2 OCAL MSB register mask.
#define CH2_OCAL_LSB_ADDRESS ((uint8_t) 0x15)
Define CH2 OCAL LSB register Address.
#define CH2_OCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH2 OCAL LSB register default.
#define CH2_OCAL_LSB_OCAL2_LSB_MASK ((uint16_t) 0xFF00)
Define CH2 OCAL LSB register mask.
#define CH2_OCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH2 OCAL LSB register reserved0 mask.
#define CH2_GCAL_MSB_ADDRESS ((uint8_t) 0x16)
Define CH2 GCAL MSB register Address.
#define CH2_GCAL_MSB_DEFAULT ((uint16_t) 0x8000)
Define CH2 GCAL MSB register default.
#define CH2_GCAL_MSB_GCAL2_MSB_MASK ((uint16_t) 0xFFFF)
Define CH2 GCAL MSB register mask.
#define CH2_GCAL_LSB_ADDRESS ((uint8_t) 0x17)
Define CH2 GCAL LSB register Address.
#define CH2_GCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH2 GCAL LSB register default.
#define CH2_GCAL_LSB_GCAL2_LSB_MASK ((uint16_t) 0xFF00)
Define CH2 GCAL LSB register mask.
#define CH2_GCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH2 GCAL LSB register reserved mask.
#define CH3_CFG_ADDRESS ((uint8_t) 0x18)
Define CH3 CFG register Address.
#define CH3_CFG_DEFAULT ((uint16_t) 0x0000)
Define CH3 CFG register Default.
#define CH3_CFG_PHASE3_MASK ((uint16_t) 0xFFC0)
Define CH3 CFG register phase3 mask.
#define CH3_CFG_RESERVED0_MASK ((uint16_t) 0x003C)
Define CH3 CFG register resereved mask.
#define CH3_CFG_MUX3_MASK ((uint16_t) 0x0003)
Define CH3 CFG register MUX3 mask.
#define CH3_CFG_MUX3_AIN3P_AIN3N ((uint16_t) 0x0000 << 0) /* DEFAULT */
Define CH3 CFG register MUX3 AIN3P_AIN3N.
#define CH3_CFG_MUX3_ADC_INPUT_SHORT ((uint16_t) 0x0001 << 0)
Define CH3 CFG register MUX3 ADC input short.
#define CH3_CFG_MUX3_DC_DIAGNOSTIC ((uint16_t) 0x0002 << 0)
Define CH3 CFG register MUX3 dc diagnostic.
#define CH3_CFG_MUX3_AC_DIAGNOSTIC ((uint16_t) 0x0003 << 0)
Define CH3 CFG register MUX3 ac diagnostic.
#define CH3_OCAL_MSB_ADDRESS ((uint8_t) 0x19)
Define CH3 OCAL MSB register Address.
#define CH3_OCAL_MSB_DEFAULT ((uint16_t) 0x0000)
Define CH3 OCAL MSB register Deafault.
#define CH3_OCAL_MSB_OCAL3_MSB_MASK ((uint16_t) 0xFFFF)
Define CH3 OCAL MSB register mask.
#define CH3_OCAL_LSB_ADDRESS ((uint8_t) 0x1A)
Define CH3 OCAL LSB register Address.
#define CH3_OCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH3 OCAL LSB register default.
#define CH3_OCAL_LSB_OCAL3_LSB_MASK ((uint16_t) 0xFF00)
Define CH3 OCAL LSB register mask.
#define CH3_OCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH3 OCAL LSB register reserved mask.
#define CH3_GCAL_MSB_ADDRESS ((uint8_t) 0x1B)
Define CH3 GCAL MSB register Address.
#define CH3_GCAL_MSB_DEFAULT ((uint16_t) 0x8000)
Define CH3 GCAL MSB register default.
#define CH3_GCAL_MSB_GCAL3_MSB_MASK ((uint16_t) 0xFFFF)
Define CH3 GCAL MSB register mask.
#define CH3_GCAL_LSB_ADDRESS ((uint8_t) 0x1C)
Define CH3 GCAL LSB register Address.
#define CH3_GCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH3 GCAL MSB register default.
#define CH3_GCAL_LSB_GCAL3_LSB_MASK ((uint16_t) 0xFF00)
Define CH3 GCAL MSB register mask.
#define CH3_GCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH3 GCAL MSB register reserved mask.
#define CH4_CFG_ADDRESS ((uint8_t) 0x1D)
Define CH4 CFG register Address.
#define CH4_CFG_DEFAULT ((uint16_t) 0x0000)
Define CH4 CFG register default.
#define CH4_CFG_PHASE4_MASK ((uint16_t) 0xFFC0)
Define CH4 CFG register phase 4 mask.
#define CH4_CFG_RESERVED0_MASK ((uint16_t) 0x003C)
Define CH4 CFG register reserved mask.
#define CH4_CFG_MUX4_MASK ((uint16_t) 0x0003)
Define CH4 CFG register mux4 mask.
#define CH4_CFG_MUX4_AIN4P_AIN4N ((uint16_t) 0x0000 << 0) /* DEFAULT */
Define CH4 CFG register mux4 AIN4P_AIN4N.
#define CH4_CFG_MUX4_ADC_INPUT_SHORT ((uint16_t) 0x0001 << 0)
Define CH4 CFG register mux4 adc input short.
#define CH4_CFG_MUX4_DC_DIAGNOSTIC ((uint16_t) 0x0002 << 0)
Define CH4 CFG register mux4 dc diagnostic.
#define CH4_CFG_MUX4_AC_DIAGNOSTIC ((uint16_t) 0x0003 << 0)
Define CH4 CFG register mux4 ac diagnostic.
#define CH4_OCAL_MSB_ADDRESS ((uint8_t) 0x1E)
Define CH4 OCAL MSB register Address.
#define CH4_OCAL_MSB_DEFAULT ((uint16_t) 0x0000)
Define CH4 OCAL MSB register default.
#define CH4_OCAL_MSB_OCAL4_MSB_MASK ((uint16_t) 0xFFFF)
Define CH4 OCAL MSB register mask.
#define CH4_OCAL_LSB_ADDRESS ((uint8_t) 0x1F)
Define CH4 OCAL LSB register Address.
#define CH4_OCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH4 OCAL LSB register default.
#define CH4_OCAL_LSB_OCAL4_LSB_MASK ((uint16_t) 0xFF00)
Define CH4 OCAL LSB register mask.
#define CH4_OCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH4 OCAL LSB register reserved mask.
#define CH4_GCAL_MSB_ADDRESS ((uint8_t) 0x20)
Define CH4 GCAL MSB register Address.
#define CH4_GCAL_MSB_DEFAULT ((uint16_t) 0x8000)
Define CH4 GCAL MSB register default.
#define CH4_GCAL_MSB_GCAL4_MSB_MASK ((uint16_t) 0xFFFF)
Define CH4 GCAL MSB register mask.
#define CH4_GCAL_LSB_ADDRESS ((uint8_t) 0x21)
Define CH4 GCAL LSB register Address.
#define CH4_GCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH4 GCAL LSB register default.
#define CH4_GCAL_LSB_GCAL4_LSB_MASK ((uint16_t) 0xFF00)
Define CH4 GCAL LSB register mask.
#define CH4_GCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH4 GCAL LSB register reserved mask.
#define CH5_CFG_ADDRESS ((uint8_t) 0x22)
Define CH5 CFG register Address.
#define CH5_CFG_DEFAULT ((uint16_t) 0x0000)
Define CH5 CFG register default.
#define CH5_CFG_PHASE5_MASK ((uint16_t) 0xFFC0)
Define CH5 CFG register mask.
#define CH5_CFG_RESERVED0_MASK ((uint16_t) 0x003C)
Define CH5 CFG register reserved mask.
#define CH5_CFG_MUX5_MASK ((uint16_t) 0x0003)
Define CH5 CFG register MUX5 mask.
#define CH5_CFG_MUX5_AIN5P_AIN5N ((uint16_t) 0x0000 << 0) /* DEFAULT */
Define CH5 CFG register MUX5 AIN5P_AIN5N.
#define CH5_CFG_MUX5_ADC_INPUT_SHORT ((uint16_t) 0x0001 << 0)
Define CH5 CFG register MUX5 adc input short.
#define CH5_CFG_MUX5_DC_DIAGNOSTIC ((uint16_t) 0x0002 << 0)
Define CH5 CFG register MUX5 dc diagnostic.
#define CH5_CFG_MUX5_AC_DIAGNOSTIC ((uint16_t) 0x0003 << 0)
Define CH5 CFG register MUX5 ac diagnostic.
#define CH5_OCAL_MSB_ADDRESS ((uint8_t) 0x23)
Define CH5 OCAL MSB register Address.
#define CH5_OCAL_MSB_DEFAULT ((uint16_t) 0x0000)
Define CH5 OCAL MSB register default.
#define CH5_OCAL_MSB_OCAL5_MSB_MASK ((uint16_t) 0xFFFF)
Define CH5 OCAL MSB register mask.
#define CH5_OCAL_LSB_ADDRESS ((uint8_t) 0x24)
Define CH5 OCAL LSB register Address.
#define CH5_OCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH5 OCAL LSB register default.
#define CH5_OCAL_LSB_OCAL5_LSB_MASK ((uint16_t) 0xFF00)
Define CH5 OCAL LSB register mask.
#define CH5_OCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH5 OCAL LSB register reserved mask.
#define CH5_GCAL_MSB_ADDRESS ((uint8_t) 0x25)
Define CH5 GCAL MSB register Address.
#define CH5_GCAL_MSB_DEFAULT ((uint16_t) 0x8000)
Define CH5 GCAL MSB register default.
#define CH5_GCAL_MSB_GCAL5_MSB_MASK ((uint16_t) 0xFFFF)
Define CH5 GCAL MSB register mask.
#define CH5_GCAL_LSB_ADDRESS ((uint8_t) 0x26)
Define CH5 GCAL LSB register Address.
#define CH5_GCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH5 GCAL LSB register default.
#define CH5_GCAL_LSB_GCAL5_LSB_MASK ((uint16_t) 0xFF00)
Define CH5 GCAL LSB register mask.
#define CH5_GCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH5 GCAL LSB register reserved mask.
#define CH6_CFG_ADDRESS ((uint8_t) 0x27)
Define CH6 CFG register Address.
#define CH6_CFG_DEFAULT ((uint16_t) 0x0000)
Define CH6 CFG register defaults.
#define CH6_CFG_PHASE6_MASK ((uint16_t) 0xFFC0)
Define CH6 CFG register phase6 mask.
#define CH6_CFG_RESERVED0_MASK ((uint16_t) 0x003C)
Define CH6 CFG register reserved mask.
#define CH6_CFG_MUX6_MASK ((uint16_t) 0x0003)
Define CH6 CFG register MUX6 mask.
#define CH6_CFG_MUX6_AIN6P_AIN6N ((uint16_t) 0x0000 << 0) /* DEFAULT */
Define CH6 CFG register MUX6 AIN6P_AIN6N.
#define CH6_CFG_MUX6_ADC_INPUT_SHORT ((uint16_t) 0x0001 << 0)
Define CH6 CFG register MUX6 adc input short.
#define CH6_CFG_MUX6_DC_DIAGNOSTIC ((uint16_t) 0x0002 << 0)
Define CH6 CFG register MUX6 dc diagnostic.
#define CH6_CFG_MUX6_AC_DIAGNOSTIC ((uint16_t) 0x0003 << 0)
Define CH6 CFG register MUX6 ac diagnostic.
#define CH6_OCAL_MSB_ADDRESS ((uint8_t) 0x28)
Define CH6 OCAL MSB register Address.
#define CH6_OCAL_MSB_DEFAULT ((uint16_t) 0x0000)
Define CH6 OCAL MSB register default.
#define CH6_OCAL_MSB_OCAL6_MSB_MASK ((uint16_t) 0xFFFF)
Define CH6 OCAL MSB register mask.
#define CH6_OCAL_LSB_ADDRESS ((uint8_t) 0x29)
Define CH6 OCAL LSB register Address.
#define CH6_OCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH6 OCAL LSB register default.
#define CH6_OCAL_LSB_OCAL6_LSB_MASK ((uint16_t) 0xFF00)
Define CH6 OCAL LSB register mask.
#define CH6_OCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH6 OCAL LSB register reserved mask.
#define CH6_GCAL_MSB_ADDRESS ((uint8_t) 0x2A)
Define CH6 GCAL MSB register Address.
#define CH6_GCAL_MSB_DEFAULT ((uint16_t) 0x8000)
Define CH6 GCAL MSB register default.
#define CH6_GCAL_MSB_GCAL6_MSB_MASK ((uint16_t) 0xFFFF)
Define CH6 GCAL MSB register mask.
#define CH6_GCAL_LSB_ADDRESS ((uint8_t) 0x2B)
Define CH6 GCAL LSB register Address.
#define CH6_GCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH6 GCAL LSB register default.
#define CH6_GCAL_LSB_GCAL6_LSB_MASK ((uint16_t) 0xFF00)
Define CH6 GCAL LSB register mask.
#define CH6_GCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH6 GCAL LSB register reserved mask.
#define CH7_CFG_ADDRESS ((uint8_t) 0x2C)
Define CH7 CFG register Address.
#define CH7_CFG_DEFAULT ((uint16_t) 0x0000)
Define CH7 CFG register default.
#define CH7_CFG_PHASE7_MASK ((uint16_t) 0xFFC0)
Define CH7 CFG register phase7 mask.
#define CH7_CFG_RESERVED0_MASK ((uint16_t) 0x003C)
Define CH7 CFG register reserved mask.
#define CH7_CFG_MUX7_MASK ((uint16_t) 0x0003)
Define CH7 CFG register MUX7 mask.
#define CH7_CFG_MUX7_AIN7P_AIN7N ((uint16_t) 0x0000 << 0) /* DEFAULT */
Define CH7 CFG register MUX7 AIN7P_AIN7N.
#define CH7_CFG_MUX7_ADC_INPUT_SHORT ((uint16_t) 0x0001 << 0)
Define CH7 CFG register MUX7 adc input short.
#define CH7_CFG_MUX7_DC_DIAGNOSTIC ((uint16_t) 0x0002 << 0)
Define CH7 CFG register MUX7 dc diagnostic.
#define CH7_CFG_MUX7_AC_DIAGNOSTIC ((uint16_t) 0x0003 << 0)
Define CH7 CFG register MUX7 ac diagnostic.
#define CH7_OCAL_MSB_ADDRESS ((uint8_t) 0x2D)
Define CH7 OCAL MSB register Address.
#define CH7_OCAL_MSB_DEFAULT ((uint16_t) 0x0000)
Define CH7 OCAL MSB register default.
#define CH7_OCAL_MSB_OCAL7_MSB_MASK ((uint16_t) 0xFFFF)
Define CH7 OCAL MSB register mask.
#define CH7_OCAL_LSB_ADDRESS ((uint8_t) 0x2E)
Define CH7 OCAL LSB register Address.
#define CH7_OCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH7 OCAL LSB register default.
#define CH7_OCAL_LSB_OCAL7_LSB_MASK ((uint16_t) 0xFF00)
Define CH7 OCAL LSB register mask.
#define CH7_OCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH7 OCAL LSB register reserved mask.
#define CH7_GCAL_MSB_ADDRESS ((uint8_t) 0x2F)
Define CH7 GCAL MSB register Address.
#define CH7_GCAL_MSB_DEFAULT ((uint16_t) 0x8000)
Define CH7 GCAL MSB register default.
#define CH7_GCAL_MSB_GCAL7_MSB_MASK ((uint16_t) 0xFFFF)
Define CH7 GCAL MSB register mask.
#define CH7_GCAL_LSB_ADDRESS ((uint8_t) 0x30)
Define CH7 GCAL LSB register Address.
#define CH7_GCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH7 GCAL LSB register default.
#define CH7_GCAL_LSB_GCAL7_LSB_MASK ((uint16_t) 0xFF00)
Define CH7 GCAL LSB register mask.
#define CH7_GCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH7 GCAL LSB register reserved mask.
#define REGMAP_CRC_ADDRESS ((uint8_t) 0x3E)
Define REGMAP CRC register Address.
#define REGMAP_CRC_DEFAULT ((uint16_t) 0x0000)
Define REGMAP CRC register default.
#define REGMAP_CRC_REG_CRC_MASK ((uint16_t) 0xFFFF)
Define REGMAP CRC register mask.
#define CHANCNT(x) ((uint8_t) ((getRegisterValue(ID_ADDRESS, x) & ID_CHANCNT_MASK) >> 8))
Return channel count.
#define REVISION_ID(x) ((uint8_t) ((getRegisterValue(ID_ADDRESS, x) & ID_REVID_MASK) >> 0))
Return revID.
#define SPI_LOCKED(x) ((bool) (getRegisterValue(STATUS_ADDRESS, x) & STATUS_LOCK_LOCKED))
Return SPI locked.
#define WLENGTH(x) ((uint8_t) ((getRegisterValue(MODE_ADDRESS, x) & STATUS_WLENGTH_MASK) >> 8))
Return word length.
#define REGMAP_CRC_ENABLED(x) ((bool) (getRegisterValue(MODE_ADDRESS, x) & MODE_REG_CRC_EN_ENABLED))
Return CRC status.
#define SPI_CRC_ENABLED(x) ((bool) (getRegisterValue(MODE_ADDRESS, x) & MODE_RX_CRC_EN_ENABLED))
Return SPI CRC status.
#define SPI_CRC_TYPE(x) ((bool) (getRegisterValue(MODE_ADDRESS, x) & MODE_CRC_TYPE_MASK))
Return CRC type.
#define OSR_INDEX(x) ((uint8_t) ((getRegisterValue(CLOCK_ADDRESS, x) & CLOCK_OSR_MASK) >> 2))
Return OSR index.
#define POWER_MODE(x) ((uint8_t) ((getRegisterValue(CLOCK_ADDRESS, x) & CLOCK_PWR_MASK) >> 0))
Return power mode.
Enumerations
enum ADS_CRC_TYPE {
ADS_CRC_TYPE_CCITT = 0,
ADS_CRC_TYPE_ANSI
}
enum ADS_CRC {
ADS_CRC_DISABLE = 0,
ADS_CRC_ENABLE
}
enum ADS_OPCODES {
ADS_OPCODE_NULL = 0x0000,
ADS_OPCODE_RESET = 0x0011,
ADS_OPCODE_STANDBY = 0x0022,
ADS_OPCODE_WAKEUP = 0x0033,
ADS_OPCODE_LOCK = 0x0555,
ADS_OPCODE_UNLOCK = 0x0655,
ADS_OPCODE_RREG = 0xA000,
ADS_OPCODE_WREG = 0x6000
}
Functions
bool ADS131M02_init (volatile ADS_Instance *adsHandle)
Initialize ADS131M02 Registers.
bool ADS131M03_init (volatile ADS_Instance *adsHandle)
Initialize ADS131M03 Registers.
bool ADS131M04_init (volatile ADS_Instance *adsHandle)
Initialize ADS131M04 Registers.
bool ADS131M08_init (volatile ADS_Instance *adsHandle)
Initialize ADS131M08 Registers.
bool ADS_writeSingleSPIReg (volatile ADS_Instance *adsHandle, uint8_t regAddr, uint16_t data, bool readCheck)
Write to a single register.
uint16_t ADS_readSingleSPIReg (volatile ADS_Instance *adsHandle, uint8_t regAddr)
Read a single register.
void ADS_resetDevice (volatile ADS_Instance *adsHandle)
Reset ADS.
bool ADS_lockRegisters (volatile ADS_Instance *adsHandle)
Lock ADS Registers.
bool ADS_unlockRegisters (volatile ADS_Instance *adsHandle)
Unlock ADS Registers.
void ADS_standbymode (volatile ADS_Instance *adsHandle)
ADS standby mode.
void ADS_wakeupCommand (volatile ADS_Instance *adsHandle)
Wakeup ADS.
void ADS_reset (volatile ADS_Instance *adsHandle)
Reset ADS.
void ADS_toggleSYNC (volatile ADS_Instance *adsHandle)
Sync ADS.
void ADS_startDataCollection (volatile ADS_Instance *adsHandle)
Start Data Collection.
void ADS_startDMADataTransfer (volatile ADS_Instance *adsHandle)
Start DMA Transfer.
void ADS_getChannelData (volatile ADS_Instance *adsHandle)
Get ADS Channel Data.
void ADS_initalizeADSRegisters (volatile ADS_Instance *adsHandle)
Initialize ADS Registers.
void ADS_verifyADSCRC (volatile ADS_Instance *adsHandle, volatile ADS_channelData *adsData)
verify CRC for channel data
void ADS_checkStatusRegister (volatile ADS_Errors error, uint16_t data)
check status registers for faults
Detailed Description
Enumeration Type Documentation
ADS_CRC_TYPE
enum ADS_CRC_TYPE
Enumerator
ADS_CRC_TYPE_CCITT
ADS CRC type CCITT.
ADS_CRC_TYPE_ANSI
ADS CRC type ANSI.
ADS_CRC
enum ADS_CRC
Enumerator
ADS_CRC_DISABLE
ADS CRC disable.
ADS_CRC_ENABLE
ADS CRC enable.
ADS_OPCODES
enum ADS_OPCODES
Enumerator
ADS_OPCODE_NULL
opcode to read status register
ADS_OPCODE_RESET
opcode to reset ADS
ADS_OPCODE_STANDBY
opcode to set ADS in standby mode
ADS_OPCODE_WAKEUP
opcode to wakeup the ADS
ADS_OPCODE_LOCK
opcode to lock ADS
ADS_OPCODE_UNLOCK
opcode to unlock ADS
ADS_OPCODE_RREG
opcode to read ADS registers
ADS_OPCODE_WREG
opcode to write ADS registers
Function Documentation
ADS131M02_init()
bool ADS131M02_init (volatile ADS_Instance * adsHandle)
Initialize ADS131M02 Registers.
Parameters
[in] adsHandle The ADS Instance
Returns
status
References ADS131M02_CFG_ADDRESS_DATA, ADS131M02_CH0_CFG_ADDRESS_DATA, ADS131M02_CH0_GCAL_LSB_ADDRESS_DATA, ADS131M02_CH0_GCAL_MSB_ADDRESS_DATA, ADS131M02_CH0_OCAL_LSB_ADDRESS_DATA, ADS131M02_CH0_OCAL_MSB_ADDRESS_DATA, ADS131M02_CH1_CFG_ADDRESS_DATA, ADS131M02_CH1_GCAL_LSB_ADDRESS_DATA, ADS131M02_CH1_GCAL_MSB_ADDRESS_DATA, ADS131M02_CH1_OCAL_LSB_ADDRESS_DATA, ADS131M02_CH1_OCAL_MSB_ADDRESS_DATA, ADS131M02_CLOCK_ADDRESS_DATA, ADS131M02_GAIN1_ADDRESS_DATA, ADS131M02_MODE_ADDRESS_DATA, ADS131M02_THRSHLD_LSB_ADDRESS_DATA, ADS131M02_THRSHLD_MSB_ADDRESS_DATA, ADS_unlockRegisters(), ADS_writeSingleSPIReg(), CFG_ADDRESS, CH0_CFG_ADDRESS, CH0_GCAL_LSB_ADDRESS, CH0_GCAL_MSB_ADDRESS, CH0_OCAL_LSB_ADDRESS, CH0_OCAL_MSB_ADDRESS, CH1_CFG_ADDRESS, CH1_GCAL_LSB_ADDRESS, CH1_GCAL_MSB_ADDRESS, CH1_OCAL_LSB_ADDRESS, CH1_OCAL_MSB_ADDRESS, CLOCK_ADDRESS, GAIN1_ADDRESS, MODE_ADDRESS, THRSHLD_LSB_ADDRESS, THRSHLD_MSB_ADDRESS, and TRUE.
ADS131M03_init()
bool ADS131M03_init (volatile ADS_Instance * adsHandle)
Initialize ADS131M03 Registers.
Parameters
[in] adsHandle The ADS Instance
Returns
status
References ADS131M03_CFG_ADDRESS_DATA, ADS131M03_CH0_CFG_ADDRESS_DATA, ADS131M03_CH0_GCAL_LSB_ADDRESS_DATA, ADS131M03_CH0_GCAL_MSB_ADDRESS_DATA, ADS131M03_CH0_OCAL_LSB_ADDRESS_DATA, ADS131M03_CH0_OCAL_MSB_ADDRESS_DATA, ADS131M03_CH1_CFG_ADDRESS_DATA, ADS131M03_CH1_GCAL_LSB_ADDRESS_DATA, ADS131M03_CH1_GCAL_MSB_ADDRESS_DATA, ADS131M03_CH1_OCAL_LSB_ADDRESS_DATA, ADS131M03_CH1_OCAL_MSB_ADDRESS_DATA, ADS131M03_CH2_CFG_ADDRESS_DATA, ADS131M03_CH2_GCAL_LSB_ADDRESS_DATA, ADS131M03_CH2_GCAL_MSB_ADDRESS_DATA, ADS131M03_CH2_OCAL_LSB_ADDRESS_DATA, ADS131M03_CH2_OCAL_MSB_ADDRESS_DATA, ADS131M03_CLOCK_ADDRESS_DATA, ADS131M03_GAIN1_ADDRESS_DATA, ADS131M03_MODE_ADDRESS_DATA, ADS131M03_THRSHLD_LSB_ADDRESS_DATA, ADS131M03_THRSHLD_MSB_ADDRESS_DATA, ADS_unlockRegisters(), ADS_writeSingleSPIReg(), CFG_ADDRESS, CH0_CFG_ADDRESS, CH0_GCAL_LSB_ADDRESS, CH0_GCAL_MSB_ADDRESS, CH0_OCAL_LSB_ADDRESS, CH0_OCAL_MSB_ADDRESS, CH1_CFG_ADDRESS, CH1_GCAL_LSB_ADDRESS, CH1_GCAL_MSB_ADDRESS, CH1_OCAL_LSB_ADDRESS, CH1_OCAL_MSB_ADDRESS, CH2_CFG_ADDRESS, CH2_GCAL_LSB_ADDRESS, CH2_GCAL_MSB_ADDRESS, CH2_OCAL_LSB_ADDRESS, CH2_OCAL_MSB_ADDRESS, CLOCK_ADDRESS, GAIN1_ADDRESS, MODE_ADDRESS, THRSHLD_LSB_ADDRESS, THRSHLD_MSB_ADDRESS, and TRUE.
ADS131M04_init()
bool ADS131M04_init (volatile ADS_Instance * adsHandle)
Initialize ADS131M04 Registers.
Parameters
[in] adsHandle The ADS Instance
Returns
status
References ADS131M04_CFG_ADDRESS_DATA, ADS131M04_CH0_CFG_ADDRESS_DATA, ADS131M04_CH0_GCAL_LSB_ADDRESS_DATA, ADS131M04_CH0_GCAL_MSB_ADDRESS_DATA, ADS131M04_CH0_OCAL_LSB_ADDRESS_DATA, ADS131M04_CH0_OCAL_MSB_ADDRESS_DATA, ADS131M04_CH1_CFG_ADDRESS_DATA, ADS131M04_CH1_GCAL_LSB_ADDRESS_DATA, ADS131M04_CH1_GCAL_MSB_ADDRESS_DATA, ADS131M04_CH1_OCAL_LSB_ADDRESS_DATA, ADS131M04_CH1_OCAL_MSB_ADDRESS_DATA, ADS131M04_CH2_CFG_ADDRESS_DATA, ADS131M04_CH2_GCAL_LSB_ADDRESS_DATA, ADS131M04_CH2_GCAL_MSB_ADDRESS_DATA, ADS131M04_CH2_OCAL_LSB_ADDRESS_DATA, ADS131M04_CH2_OCAL_MSB_ADDRESS_DATA, ADS131M04_CH3_CFG_ADDRESS_DATA, ADS131M04_CH3_GCAL_LSB_ADDRESS_DATA, ADS131M04_CH3_GCAL_MSB_ADDRESS_DATA, ADS131M04_CH3_OCAL_LSB_ADDRESS_DATA, ADS131M04_CH3_OCAL_MSB_ADDRESS_DATA, ADS131M04_CLOCK_ADDRESS_DATA, ADS131M04_GAIN1_ADDRESS_DATA, ADS131M04_MODE_ADDRESS_DATA, ADS131M04_THRSHLD_LSB_ADDRESS_DATA, ADS131M04_THRSHLD_MSB_ADDRESS_DATA, ADS_unlockRegisters(), ADS_writeSingleSPIReg(), CFG_ADDRESS, CH0_CFG_ADDRESS, CH0_GCAL_LSB_ADDRESS, CH0_GCAL_MSB_ADDRESS, CH0_OCAL_LSB_ADDRESS, CH0_OCAL_MSB_ADDRESS, CH1_CFG_ADDRESS, CH1_GCAL_LSB_ADDRESS, CH1_GCAL_MSB_ADDRESS, CH1_OCAL_LSB_ADDRESS, CH1_OCAL_MSB_ADDRESS, CH2_CFG_ADDRESS, CH2_GCAL_LSB_ADDRESS, CH2_GCAL_MSB_ADDRESS, CH2_OCAL_LSB_ADDRESS, CH2_OCAL_MSB_ADDRESS, CH3_CFG_ADDRESS, CH3_GCAL_LSB_ADDRESS, CH3_GCAL_MSB_ADDRESS, CH3_OCAL_LSB_ADDRESS, CH3_OCAL_MSB_ADDRESS, CLOCK_ADDRESS, GAIN1_ADDRESS, MODE_ADDRESS, THRSHLD_LSB_ADDRESS, THRSHLD_MSB_ADDRESS, and TRUE.
ADS131M08_init()
bool ADS131M08_init (volatile ADS_Instance * adsHandle)
Initialize ADS131M08 Registers.
Parameters
[in] adsHandle The ADS Instance
Returns
status
References ADS131M08_CFG_ADDRESS_DATA, ADS131M08_CH0_CFG_ADDRESS_DATA, ADS131M08_CH0_GCAL_LSB_ADDRESS_DATA, ADS131M08_CH0_GCAL_MSB_ADDRESS_DATA, ADS131M08_CH0_OCAL_LSB_ADDRESS_DATA, ADS131M08_CH0_OCAL_MSB_ADDRESS_DATA, ADS131M08_CH1_CFG_ADDRESS_DATA, ADS131M08_CH1_GCAL_LSB_ADDRESS_DATA, ADS131M08_CH1_GCAL_MSB_ADDRESS_DATA, ADS131M08_CH1_OCAL_LSB_ADDRESS_DATA, ADS131M08_CH1_OCAL_MSB_ADDRESS_DATA, ADS131M08_CH2_CFG_ADDRESS_DATA, ADS131M08_CH2_GCAL_LSB_ADDRESS_DATA, ADS131M08_CH2_GCAL_MSB_ADDRESS_DATA, ADS131M08_CH2_OCAL_LSB_ADDRESS_DATA, ADS131M08_CH2_OCAL_MSB_ADDRESS_DATA, ADS131M08_CH3_CFG_ADDRESS_DATA, ADS131M08_CH3_GCAL_LSB_ADDRESS_DATA, ADS131M08_CH3_GCAL_MSB_ADDRESS_DATA, ADS131M08_CH3_OCAL_LSB_ADDRESS_DATA, ADS131M08_CH3_OCAL_MSB_ADDRESS_DATA, ADS131M08_CH4_CFG_ADDRESS_DATA, ADS131M08_CH4_GCAL_LSB_ADDRESS_DATA, ADS131M08_CH4_GCAL_MSB_ADDRESS_DATA, ADS131M08_CH4_OCAL_LSB_ADDRESS_DATA, ADS131M08_CH4_OCAL_MSB_ADDRESS_DATA, ADS131M08_CH5_CFG_ADDRESS_DATA, ADS131M08_CH5_GCAL_LSB_ADDRESS_DATA, ADS131M08_CH5_GCAL_MSB_ADDRESS_DATA, ADS131M08_CH5_OCAL_LSB_ADDRESS_DATA, ADS131M08_CH5_OCAL_MSB_ADDRESS_DATA, ADS131M08_CH6_CFG_ADDRESS_DATA, ADS131M08_CH6_GCAL_LSB_ADDRESS_DATA, ADS131M08_CH6_GCAL_MSB_ADDRESS_DATA, ADS131M08_CH6_OCAL_LSB_ADDRESS_DATA, ADS131M08_CH6_OCAL_MSB_ADDRESS_DATA, ADS131M08_CH7_CFG_ADDRESS_DATA, ADS131M08_CH7_GCAL_LSB_ADDRESS_DATA, ADS131M08_CH7_GCAL_MSB_ADDRESS_DATA, ADS131M08_CH7_OCAL_LSB_ADDRESS_DATA, ADS131M08_CH7_OCAL_MSB_ADDRESS_DATA, ADS131M08_CLOCK_ADDRESS_DATA, ADS131M08_GAIN1_ADDRESS_DATA, ADS131M08_GAIN2_ADDRESS_DATA, ADS131M08_MODE_ADDRESS_DATA, ADS131M08_THRSHLD_LSB_ADDRESS_DATA, ADS131M08_THRSHLD_MSB_ADDRESS_DATA, ADS_unlockRegisters(), ADS_writeSingleSPIReg(), CFG_ADDRESS, CH0_CFG_ADDRESS, CH0_GCAL_LSB_ADDRESS, CH0_GCAL_MSB_ADDRESS, CH0_OCAL_LSB_ADDRESS, CH0_OCAL_MSB_ADDRESS, CH1_CFG_ADDRESS, CH1_GCAL_LSB_ADDRESS, CH1_GCAL_MSB_ADDRESS, CH1_OCAL_LSB_ADDRESS, CH1_OCAL_MSB_ADDRESS, CH2_CFG_ADDRESS, CH2_GCAL_LSB_ADDRESS, CH2_GCAL_MSB_ADDRESS, CH2_OCAL_LSB_ADDRESS, CH2_OCAL_MSB_ADDRESS, CH3_CFG_ADDRESS, CH3_GCAL_LSB_ADDRESS, CH3_GCAL_MSB_ADDRESS, CH3_OCAL_LSB_ADDRESS, CH3_OCAL_MSB_ADDRESS, CH4_CFG_ADDRESS, CH4_GCAL_LSB_ADDRESS, CH4_GCAL_MSB_ADDRESS, CH4_OCAL_LSB_ADDRESS, CH4_OCAL_MSB_ADDRESS, CH5_CFG_ADDRESS, CH5_GCAL_LSB_ADDRESS, CH5_GCAL_MSB_ADDRESS, CH5_OCAL_LSB_ADDRESS, CH5_OCAL_MSB_ADDRESS, CH6_CFG_ADDRESS, CH6_GCAL_LSB_ADDRESS, CH6_GCAL_MSB_ADDRESS, CH6_OCAL_LSB_ADDRESS, CH6_OCAL_MSB_ADDRESS, CH7_CFG_ADDRESS, CH7_GCAL_LSB_ADDRESS, CH7_GCAL_MSB_ADDRESS, CH7_OCAL_LSB_ADDRESS, CH7_OCAL_MSB_ADDRESS, CLOCK_ADDRESS, GAIN1_ADDRESS, GAIN2_ADDRESS, MODE_ADDRESS, THRSHLD_LSB_ADDRESS, THRSHLD_MSB_ADDRESS, and TRUE.
ADS_writeSingleSPIReg()
bool ADS_writeSingleSPIReg (volatile ADS_Instance * adsHandle, uint8_t regAddr, uint16_t data, bool readCheck)
Write to a single register.
Parameters
[in] adsHandle The ADS Instance
[in] regAddr The register address
[in] data Data to be written
[in] readCheck write check
Returns
Write status
References ADS_BYTELENGTH, ADS_DMA_TRANSFER_DONE, ADS_DMA_TRANSFER_READY, ADS_DMA_WAITING, ADS_OPCODE_WREG, ADS_readSingleSPIReg(), ADS_Instance::DMAStatus, ADS_Instance::DMAWait, HAL_startSPIDataTransfer(), ADS_Instance::spiChan, and ADS_Instance::spiCs.
Referenced by ADS131M02_init(), ADS131M03_init(), ADS131M04_init(), and ADS131M08_init().
ADS_readSingleSPIReg()
uint16_t ADS_readSingleSPIReg (volatile ADS_Instance * adsHandle, uint8_t regAddr)
Read a single register.
Parameters
[in] adsHandle The ADS Instance
[in] regAddr The register address
Returns
Register Data
References ADS_BYTELENGTH, ADS_DMA_TRANSFER_DONE, ADS_DMA_TRANSFER_READY, ADS_DMA_WAITING, ADS_OPCODE_RREG, ADS_Instance::DMAStatus, ADS_Instance::DMAWait, HAL_startSPIDataTransfer(), ADS_Instance::spiChan, and ADS_Instance::spiCs.
Referenced by ADS_lockRegisters(), ADS_unlockRegisters(), and ADS_writeSingleSPIReg().
ADS_resetDevice()
void ADS_resetDevice (volatile ADS_Instance * adsHandle)
Reset ADS.
Parameters
[in] adsHandle The ADS Instance
References ADS_BYTELENGTH, ADS_DMA_TRANSFER_DONE, ADS_DMA_TRANSFER_READY, ADS_DMA_WAITING, ADS_OPCODE_RESET, ADS_Instance::DMAStatus, ADS_Instance::DMAWait, HAL_startSPIDataTransfer(), ADS_Instance::spiChan, and ADS_Instance::spiCs.
ADS_lockRegisters()
bool ADS_lockRegisters (volatile ADS_Instance * adsHandle)
Lock ADS Registers.
Parameters
[in] adsHandle The ADS Instance
Returns
Register status
References ADS_BYTELENGTH, ADS_DMA_TRANSFER_DONE, ADS_DMA_TRANSFER_READY, ADS_DMA_WAITING, ADS_OPCODE_LOCK, ADS_readSingleSPIReg(), ADS_Instance::DMAStatus, ADS_Instance::DMAWait, HAL_startSPIDataTransfer(), ADS_Instance::spiChan, ADS_Instance::spiCs, STATUS_ADDRESS, and STATUS_LOCK_MASK.
ADS_unlockRegisters()
bool ADS_unlockRegisters (volatile ADS_Instance * adsHandle)
Unlock ADS Registers.
Parameters
[in] adsHandle The ADS Instance
Returns
Register status
References ADS_BYTELENGTH, ADS_DMA_TRANSFER_DONE, ADS_DMA_TRANSFER_READY, ADS_DMA_WAITING, ADS_OPCODE_UNLOCK, ADS_readSingleSPIReg(), ADS_Instance::DMAStatus, ADS_Instance::DMAWait, HAL_startSPIDataTransfer(), ADS_Instance::spiChan, ADS_Instance::spiCs, STATUS_ADDRESS, and STATUS_LOCK_MASK.
Referenced by ADS131M02_init(), ADS131M03_init(), ADS131M04_init(), and ADS131M08_init().
ADS_standbymode()
void ADS_standbymode (volatile ADS_Instance * adsHandle)
ADS standby mode.
Parameters
[in] adsHandle The ADS Instance
References ADS_BYTELENGTH, ADS_DMA_TRANSFER_DONE, ADS_DMA_TRANSFER_READY, ADS_DMA_WAITING, ADS_OPCODE_STANDBY, ADS_Instance::DMAStatus, ADS_Instance::DMAWait, HAL_startSPIDataTransfer(), ADS_Instance::spiChan, and ADS_Instance::spiCs.
ADS_wakeupCommand()
void ADS_wakeupCommand (volatile ADS_Instance * adsHandle)
Wakeup ADS.
Parameters
[in] adsHandle The ADS Instance
References ADS_BYTELENGTH, ADS_DMA_TRANSFER_DONE, ADS_DMA_TRANSFER_READY, ADS_DMA_WAITING, ADS_OPCODE_WAKEUP, ADS_Instance::DMAStatus, ADS_Instance::DMAWait, HAL_startSPIDataTransfer(), ADS_Instance::spiChan, and ADS_Instance::spiCs.
ADS_reset()
void ADS_reset (volatile ADS_Instance * adsHandle)
Reset ADS.
Parameters
[in] adsHandle The ADS Instance
References ADS_RESET_US, ADS_WAKEUP_US, HAL_delayMicroSeconds(), HAL_GPIO_PIN_HIGH, HAL_GPIO_PIN_LOW, HAL_writeGPIOPin(), and ADS_Instance::sync.
ADS_toggleSYNC()
void ADS_toggleSYNC (volatile ADS_Instance * adsHandle)
Sync ADS.
Parameters
[in] adsHandle The ADS Instance
References ADS_SYNC_US, HAL_delayMicroSeconds(), HAL_GPIO_PIN_HIGH, HAL_GPIO_PIN_LOW, HAL_writeGPIOPin(), and ADS_Instance::sync.
Referenced by ADS_startDataCollection().
ADS_startDataCollection()
void ADS_startDataCollection (volatile ADS_Instance * adsHandle)
Start Data Collection.
Parameters
[in] adsHandle The ADS Instance
References ADS_toggleSYNC(), ADS_Instance::datacollectionStatus, HAL_enableGPIOInterrupt(), and ADS_Instance::ready.
ADS_startDMADataTransfer()
void ADS_startDMADataTransfer (volatile ADS_Instance * adsHandle)
Start DMA Transfer.
Parameters
[in] adsHandle The ADS Instance
References ADS_BYTELENGTH, HAL_startSPIDataTransfer(), ADS_Instance::rawdata, ADS_Instance::spiChan, and ADS_Instance::spiCs.
ADS_getChannelData()
void ADS_getChannelData (volatile ADS_Instance * adsHandle)
Get ADS Channel Data.
Parameters
[in] adsHandle The ADS Instance
References ADS_CHANNELCOUNT, ADS_checkStatusRegister(), ADS_CMDLENGTH, ADS_verifyADSCRC(), ADS_channelData::chan0, ADS_channelData::chan1, ADS_channelData::chan2, ADS_channelData::chan3, ADS_channelData::chan4, ADS_channelData::chan5, ADS_channelData::chan6, ADS_channelData::chan7, ADS_Instance::channelData, ADS_channelData::crc, ADS_Instance::errors, ADS_Instance::rawdata, and ADS_channelData::response.
ADS_initalizeADSRegisters()
void ADS_initalizeADSRegisters (volatile ADS_Instance * adsHandle)
Initialize ADS Registers.
Parameters
[in] adsHandle The ADS Instance
References ADS_DMA_TRANSFER_DONE, ADS_DMA_TRANSFER_READY, ADS_DMA_WAITING, ADS_Instance::ADS_initRegData, ADS_Instance::DMAStatus, ADS_Instance::DMAWait, HAL_startSPIDataTransfer(), NUM_REGISTERS, ADS_Instance::spiChan, and ADS_Instance::spiCs.
ADS_verifyADSCRC()
void ADS_verifyADSCRC (volatile ADS_Instance * adsHandle, volatile ADS_channelData * adsData)
verify CRC for channel data
Parameters
[in] adsHandle The ADS Instance
[in] adsData The ADS channel data
References ADS_CHANNELCOUNT, ADS_CMDLENGTH, ADS_channelData::crc, CRC_IN_ADDRESS, ADS_Instance::crcFailCount, ADS_Instance::crcPassCount, HAL_CRC_0, HAL_getCRCOut(), HAL_setCRCSeed(), and ADS_Instance::rawdata.
Referenced by ADS_getChannelData().
ADS_checkStatusRegister()
void ADS_checkStatusRegister (volatile ADS_Errors error, uint16_t data)
check status registers for faults
Parameters
[in] error The ADS errors
[in] data status register data
References ADS_Errors::crcErrorCount, ADS_Errors::fResyncCount, ADS_Errors::regMapCount, ADS_Errors::resetCount, ADS_Errors::rstAckCount, ADS_Errors::rstnAckCount, STATUS_CRC_ERR_MASK, STATUS_F_RESYNC_MASK, STATUS_REG_MAP_MASK, STATUS_RESET_MASK, and ADS_Errors::totalComparisions.
Referenced by ADS_getChannelData().
Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale