MSPM0Gxx0xEnergyMetrology: LCD_LCD_153_115_ND
LCD_LCD_153_115_ND
Data Structures
struct LCD_pin
Defines LCD pins for each position.
struct LCD_instance
Defines LCD instance.
Macros
#define ASCII_DIGIT_OFFSET (48)
ASCII offset for digits.
#define ASCII_LETTER_OFFSET (65)
ASCII offset for letters.
Enumerations
enum LCD_POSITION {
LCD_POSITION_NULL = -1,
LCD_POSITION_1 = 0,
LCD_POSITION_2,
LCD_POSITION_3,
LCD_POSITION_4,
LCD_POSITION_5,
LCD_POSITION_6,
LCD_POSITION_7,
LCD_POSITION_8,
LCD_POSITION_MAX
}
Functions
void LCD_init (LCD_instance *lcdHandle)
initialize LCD pin configuration
void LCD_clearDisplay (LCD_instance *lcdHandle)
Clear all positions in display.
void LCD_showChar (LCD_instance *lcdHandle, char ch, LCD_pin lcdPinPosition)
show char on LCD
void LCD_showDP (LCD_instance *lcdHandle, LCD_pin lcdPinPosition)
show DP on LCD
void LCD_showCA (LCD_instance *lcdHandle, LCD_pin lcdPinPosition)
show CA on LCD
void LCD_clearDP (LCD_instance *lcdHandle, LCD_pin lcdPinPosition)
Clear a particular DP on LCD.
void LCD_clearCA (LCD_instance *lcdHandle, LCD_pin lcdPinPosition)
Clear a particular CA on LCD.
Detailed Description
Enumeration Type Documentation
LCD_POSITION
enum LCD_POSITION
Enumerator
LCD_POSITION_NULL
Segment A position Null.
LCD_POSITION_1
Position 1 on LCD.
LCD_POSITION_2
Position 2 on LCD.
LCD_POSITION_3
Position 3 on LCD.
LCD_POSITION_4
Position 4 on LCD.
LCD_POSITION_5
Position 5 on LCD.
LCD_POSITION_6
Position 6 on LCD.
LCD_POSITION_7
Position 7 on LCD.
LCD_POSITION_8
Position 8 on LCD.
LCD_POSITION_MAX
Max positions on LCD.
Function Documentation
LCD_init()
void LCD_init (LCD_instance * lcdHandle)
initialize LCD pin configuration
Parameters
[in] lcdHandle The LCD instance
References LCD_POSITION_1, LCD_POSITION_2, LCD_POSITION_3, LCD_POSITION_4, LCD_POSITION_5, LCD_POSITION_6, LCD_POSITION_7, LCD_POSITION_8, LCD_instance::lcdPin1, LCD_instance::lcdPin10, LCD_instance::lcdPin11, LCD_instance::lcdPin12, LCD_instance::lcdPin13, LCD_instance::lcdPin14, LCD_instance::lcdPin15, LCD_instance::lcdPin16, LCD_instance::lcdPin2, LCD_instance::lcdPin21, LCD_instance::lcdPin22, LCD_instance::lcdPin23, LCD_instance::lcdPin24, LCD_instance::lcdPin25, LCD_instance::lcdPin26, LCD_instance::lcdPin27, LCD_instance::lcdPin28, LCD_instance::lcdPin29, LCD_instance::lcdPin3, LCD_instance::lcdPin30, LCD_instance::lcdPin31, LCD_instance::lcdPin32, LCD_instance::lcdPin33, LCD_instance::lcdPin34, LCD_instance::lcdPin35, LCD_instance::lcdPin36, LCD_instance::lcdPin4, LCD_instance::lcdPin5, LCD_instance::lcdPin6, LCD_instance::lcdPin7, LCD_instance::lcdPin8, LCD_instance::lcdPin9, LCD_instance::lcdPinPosition, LCD_pin::pin1, LCD_pin::pin2, LCD_pin::pin3, and LCD_pin::pin4.
LCD_clearDisplay()
void LCD_clearDisplay (LCD_instance * lcdHandle)
Clear all positions in display.
Parameters
[in] lcdHandle The LCD instance
References LCD_clearCA(), LCD_clearDP(), LCD_POSITION_1, LCD_POSITION_MAX, LCD_showChar(), and LCD_instance::lcdPinPosition.
LCD_showChar()
void LCD_showChar (LCD_instance * lcdHandle, char ch, LCD_pin lcdPinPosition)
show char on LCD
Parameters
[in] lcdHandle The LCD instance
[in] ch The character to display on LCD
[in] lcdPinPosition The position on LCD
References ASCII_DIGIT_OFFSET, ASCII_LETTER_OFFSET, LCD_instance::lcdChan, LCD_pin::pin1, LCD_pin::pin2, LCD_pin::pin3, and LCD_pin::pin4.
Referenced by LCD_clearDisplay().
LCD_showDP()
void LCD_showDP (LCD_instance * lcdHandle, LCD_pin lcdPinPosition)
show DP on LCD
Parameters
[in] lcdHandle The LCD instance
[in] lcdPinPosition The position on LCD
References LCD_instance::lcdChan, and LCD_pin::pin3.
LCD_showCA()
void LCD_showCA (LCD_instance * lcdHandle, LCD_pin lcdPinPosition)
show CA on LCD
Parameters
[in] lcdHandle The LCD instance
[in] lcdPinPosition The position on LCD
References LCD_instance::lcdChan, and LCD_pin::pin1.
LCD_clearDP()
void LCD_clearDP (LCD_instance * lcdHandle, LCD_pin lcdPinPosition)
Clear a particular DP on LCD.
Parameters
[in] lcdHandle The LCD instance
[in] lcdPinPosition position on LCD
References LCD_instance::lcdChan, and LCD_pin::pin3.
Referenced by LCD_clearDisplay().
LCD_clearCA()
void LCD_clearCA (LCD_instance * lcdHandle, LCD_pin lcdPinPosition)
Clear a particular CA on LCD.
Parameters
[in] lcdHandle The LCD instance
[in] lcdPinPosition position on LCD
References LCD_instance::lcdChan, and LCD_pin::pin1.
Referenced by LCD_clearDisplay().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale