MSPM0Gxx0xEnergyMetrology: Metrology
Metrology
Data Structures
struct currentSensorCalibrationData
Defines current sensor calibration data.
struct phaseCalibrationData
Defines phase calibration data.
struct calibrationData
Defines calibration data.
struct nvParam
Defines calibration parameters.
struct infoMem
Defines nv memory.
struct phaseReadings
Define Phase Readings.
struct neutralReadings
Defines neutral readings.
struct TotalPowerReadings
Defines Total Power readings.
struct energyIntegrator
Defines energy integrator parameters.
struct LLReadings
Defines Line Parameters.
struct phaseCorrection
Defines Phase Correction Parameters.
struct currentDPSet
Defines current dot product set.
struct voltageDPSet
Defines voltage dot product set.
struct cyclePhaseDPSet
Defines cycle voltage product set.
struct neutralDPSet
Defines neutral dot product set.
struct currentParams
current parameters
struct mainsParams
Defines mains parameters.
struct phaseParams
Defines Phase parameters.
struct neutralParams
Defines neutral Params.
struct energyPulse
struct phaseEnergy
Defines Energy Directions.
struct phaseMetrology
Defines Phase metrology.
struct neutralMetrology
Defines Neutral Metrology.
struct totalParams
Defines Total Parameters.
struct metrologyData
Defines Metrology Data.
Macros
#define PI2 _IQ23(6.28318530718)
Defines 2 * PI.
#define calInfo (&nvParams.seg_a.s.calData)
Defines nv params call data.
#define CONFIG_INIT_FLAG (0xABCD)
Defines a flag data to check the availability of data in flash.
#define DEFAULT_BASE_PHASE_A_CORRECTION ((int) 0)
#define DEFAULT_BASE_PHASE_B_CORRECTION ((int) 0)
#define DEFAULT_BASE_PHASE_C_CORRECTION ((int) 0)
#define DEFAULT_BASE_NEUTRAL_PHASE_CORRECTION ((int) 0)
#define V_ADC_MIN _IQ23(-0.9)
Defines Minimum Voltage ADC input in per units.
#define V_ADC_MAX _IQ23(0.9)
Defines Maximum Voltage ADC input in per units.
#define I_ADC_MIN _IQ23(-0.9)
Defines Minimum Current ADC input in per units.
#define I_ADC_MAX _IQ23(0.9)
Defines Maximum Current ADC input in per units.
#define ENDSTOP_HITS_FOR_OVERLOAD (20)
Defines Number of Overload hits.
#define MAX_PER_SAMPLE_VOLTAGE_SLEW _IQ23(1)
Defines Minimum Voltage Slew rate.
#define PHASE_SHIFT_FIR_TABLE_ELEMENTS (256)
Defines Maximum number of FIR table elements.
#define V_HISTORY_MASK (0x3F)
Defines Voltage history array mask.
#define RMS_VOLTAGE_OVERRANGE (0xFFFFFF)
Defines RMS Voltage over range value.
#define RMS_CURRENT_OVERRANGE (0xFFFFFF)
Defines RMS Current over range value.
#define POWER_OVERRANGE (0xFFFFFF)
Defines RMS Power over range value.
#define TOTAL_RESIDUAL_POWER_CUTOFF _IQ13(0.5)
Defines minimum power measured in watts.
#define I_HISTORY_STEPS 2
Defines current history samples to be stored.
#define SAMPLES_PER_SECOND SAMPLE_RATE
Defines sampling rate.
#define SAMPLES_PER_10_SECONDS (F_SAMPLE_RATE * 10.0f)
Defines samples per 10 seconds.
#define ENERGY_100mWATT_HOUR_THRESHOLD (360)
Defines Energy threshold value 100 milliwatts-hr` 100 milliwatt-hr = 360 watt-sec.
#define ENERGY_100mWATT_HOUR_THRESHOLD_IQ _IQ13(360)
Defines Energy threshold in IQ.
#define MAINS_NOMINAL_VOLTAGE_IQ19 _IQ19(MAINS_NOMINAL_VOLTAGE)
Mains nominal voltage in IQ15 format.
#define MAINS_BASIS_CURRENT 10
Mains basic current.
#define MAINS_MAXIMUM_CURRENT 100
Mians maximum current.
#define SAG_THRESHOLD (20)
Defines sag threshold value in percentage.
#define SAG_HYSTERESIS _IQ15(1)
Defines sag hysteresis value in milli volts.
#define SWELL_THRESHOLD (20)
Defines swell threshold value in percentage.
#define SWELL_HYSTERESIS _IQ19(1)
Defines swell hysteresis value in milli volts.
#define MIN_SAG_VOLTAGE _IQ19(100)
Defines minimum voltage in milli volts to be considered as sag.
#define INTERRUPTION_HYSTERESIS _IQ19(100)
Hysteresis voltage amount for an event to be considered a voltage interruption.
#define MAINS_MAX_FREQUENCY_PER_10_SEC MAINS_MAX_FREQUENCY / 10.0f
Defines max frequency in 10 sec.
#define MAINS_MIN_FREQUENCY_PER_10_SEC MAINS_MIN_FREQUENCY / 10.0f
Defines min frequency in 10 sec.
#define METROLOGY_MIN_CYCLE_SAMPLES (int32_t)(256.0f * SAMPLES_PER_10_SECONDS / MAINS_MAX_FREQUENCY_PER_10_SEC)
Defines minimum samples per cycle.
#define METROLOGY_MAX_CYCLE_SAMPLES (int32_t)(256.0f * SAMPLES_PER_10_SECONDS / MAINS_MIN_FREQUENCY_PER_10_SEC)
Defines maximum samples per cycle.
#define TWICE_CYCLES_PER_NOMINAL_FREQUENCY (int)((2.0f * SAMPLES_PER_10_SECONDS)/(10.0f * MAINS_NOMINAL_FREQUENCY))
Defines two times the samples per cycle.
#define CYCLES_PER_COMPUTATION (12)
Defines cycles per computations.
#define ENERGY_PULSE_DURATION (20)
The duration of the LED on time for an energy pulse. This is measured in ADC samples, giving a duration = (ENERGY_PULSE_DURATION - 1)/SAMPLE_RATE). The maximum allowed is 255.
#define TOTAL_ACTIVE_ENERGY_PULSES_PER_KW_HOUR ENERGY_PULSE_CONSTANT
Defines active energy pulses per kwh.
#define TOTAL_REACTIVE_ENERGY_PULSES_PER_KW_HOUR ENERGY_PULSE_CONSTANT
Defines reactive energy pulses per kwh.
#define TOTAL_ACTIVE_ENERGY_PULSE_THRESHOLD ((int64_t)ENERGY_100mWATT_HOUR_THRESHOLD * 1000L * SAMPLE_RATE * 10000LL)/(TOTAL_ACTIVE_ENERGY_PULSES_PER_KW_HOUR)
Defines active energy pulse threshlod.
#define TOTAL_REACTIVE_ENERGY_PULSE_THRESHOLD ((int64_t)ENERGY_100mWATT_HOUR_THRESHOLD * 1000L * SAMPLE_RATE * 10000LL)/(TOTAL_REACTIVE_ENERGY_PULSES_PER_KW_HOUR)
Defines reactive energy pulse threshlod.
#define METROLOGY_DDS_BIT_RESOLUTION 8
Defines sin table bit resolution.
#define METROLOGY_DDS_TABLE_RESOLUTION 24
Defines sin table resolution.
#define METROLOGY_DDS_STEPS (1 << METROLOGY_DDS_BIT_RESOLUTION)
Defines steps in sin table.
#define METROLOGY_DDS_BIT_SHIFT (32 - 2 - METROLOGY_DDS_BIT_RESOLUTION)
Defines DDS bit shifted.
#define METROLOGY_IQ19_TO_MICROAMPS _IQ19(1.9073486328125)
Defines conversion factor from IQ19 to micro amps.
#define METROLOGY_IQ13_TO_MILLIWATTS _IQ13(0.1220703125)
Defines conversion factor from IQ13 to milli watts.
Typedefs
typedef struct infoMem infoMem
Defines nv memory.
Enumerations
enum PHASES { MAX_PHASES }
enum METROLOGY_STATUS {
METROLOGY_STATUS_POWER_DOWN = 0x0004,
METROLOGY_STATUS_REVERSED = 0x0100,
METROLOGY_STATUS_EARTHED = 0x0200,
METROLOGY_STATUS_PHASE_VOLTAGE_OK = 0x0400,
METROLOGY_STATUS_BATTERY_OK = 0x0800
}
enum OPERATING_MODES {
OPERATING_MODE_NORMAL = 0,
OPERATING_MODE_AMR_ONLY = 3,
OPERATING_MODE_LCD_ONLY = 4,
OPERATING_MODE_POWERFAIL = 5
}
enum SAG_SWELL_EVENTS {
SAG_SWELL_VOLTAGE_INTERRUPTION_CONTINUING = -4,
SAG_SWELL_VOLTAGE_INTERRUPTION_ONSET = -3,
SAG_SWELL_VOLTAGE_SAG_CONTINUING = -2,
SAG_SWELL_VOLTAGE_SAG_ONSET = -1,
SAG_SWELL_VOLTAGE_NORMAL = 0,
SAG_SWELL_VOLTAGE_SWELL_ONSET = 1,
SAG_SWELL_VOLTAGE_SWELL_CONTINUING = 2,
SAG_SWELL_VOLTAGE_POWER_DOWN_OK = 3
}
enum PHASE_STATUS {
PHASE_STATUS_NEW_LOG = 0x0001,
PHASE_STATUS_V_POS = 0x0002,
PHASE_STATUS_I_POS = 0x0004,
PHASE_STATUS_ENERGY_LOGABLE = 0x0008,
PHASE_STATUS_V_OVERRANGE = 0x0010,
PHASE_STATUS_I_OVERRANGE = 0x0020,
PHASE_STATUS_I_REVERSED = 0x0040,
PHASE_STATUS_I_NEUTRAL_OVERRANGE = 0x0080,
PHASE_STATUS_I_NEUTRAL_REVERSED = 0x0100,
PHASE_STATUS_CURRENT_FROM_NEUTRAL = 0x0200,
PHASE_STATUS_I_NEUTRAL_POS = 0x0800,
PHASE_STATUS_REVERSED = 0x1000,
PHASE_STATUS_UNBALANCED = 0x2000,
PHASE_STATUS_ZERO_CROSSING_MISSED = 0x4000
}
Functions
void Metrology_perSampleProcessing (metrologyData *workingData)
Metrology per phase sampling.
void Metrology_perSampleEnergyPulseProcessing (metrologyData *workingData)
Metrology per sample energy pulse processing.
__STATIC_INLINE _iq23 metrology_dcFilter (int64_t *p, _iq23 x)
dc_filter() Simple 1st order DC filter y(n) = y(n-1) + (x(n) - y(n-1))/2^14 xfilt(n) = x(n) - y(n) where: x(n) = most recent ADC sample y(n) = filter tap xfilt(n) = DC filtered output
_iq19 calculateRMSVoltage (phaseMetrology *phase, phaseCalibrationData *phaseCal)
calculate RMS Voltage
_iq19 calculateRMSCurrent (phaseMetrology *phase, phaseCalibrationData *phaseCal)
calculate RMS Current
_iq13 calculateActivePower (phaseMetrology *phase, phaseCalibrationData *phaseCal)
calculate active power
_iq13 calculateReactivePower (phaseMetrology *phase, phaseCalibrationData *phaseCal)
calculate active power
_iq13 calculateApparentPower (phaseMetrology *phase)
calculate apparent power
_iq19 calculateFundamentalRMSVoltage (phaseMetrology *phase, phaseCalibrationData *phaseCal)
calculate fundamental RMS Voltage
_iq19 calculateFundamentalRMSCurrent (phaseMetrology *phase, phaseCalibrationData *phaseCal)
calculate fundamental RMS Current
_iq13 calculateFundamentalActivePower (phaseMetrology *phase, phaseCalibrationData *phaseCal)
calculate fundamental active Power
_iq13 calculateFundamentalReactivePower (phaseMetrology *phase, phaseCalibrationData *phaseCal)
calculate fundamental reactive Power
_iq13 calculateFundamentalApparentPower (phaseMetrology *phase)
calculate fundamental apparent Power
void accumulateActiveEnergy (metrologyData *workingData, PHASES ph)
accumulate active energy
void accumulateReactiveEnergy (metrologyData *workingData, PHASES ph)
accumulate reactive energy
void accumulateApparentEnergy (metrologyData *workingData, PHASES ph)
accumulate appparent energy
void accumulateFundamentalActiveEnergy (metrologyData *workingData, PHASES ph)
accumulate fundamental active energy
void accumulateFundamentalReactiveEnergy (metrologyData *workingData, PHASES ph)
accumulate fundamental reactive energy
void accumulateFundamentalApparentEnergy (metrologyData *workingData, PHASES ph)
accumulate fundamental apparent energy
_iq13 calculatePowerFactor (phaseMetrology *phase)
calculate power factor
_iq15 calculateAngleVoltagetoCurrent (phaseMetrology *phase)
calculate power factor angle
_iq19 calculateOverDeviation (phaseMetrology *phase)
calculate voltage over deviation
_iq19 calculateUnderDeviation (phaseMetrology *phase)
calculate voltage under deviation
_iq19 calculateVoltageTHD (phaseMetrology *phase)
calculate voltage THD
_iq19 calculateCurrentTHD (phaseMetrology *phase)
calculate current THD
_iq15 calculateMainsfrequency (phaseMetrology *phase, phaseCalibrationData *phaseCal)
calculate mains frequency
_iq13 calculateTotalActivePower (metrologyData *workingData)
Calculate total active power.
_iq13 calculateTotalReactivePower (metrologyData *workingData)
Calculate total reactive power.
_iq13 calculateTotalApparentPower (metrologyData *workingData)
Calculate total apparent power.
_iq13 calculateTotalFundamentalActivePower (metrologyData *workingData)
Calculate total fundamental active power.
_iq13 calculateTotalFundamentalReactivePower (metrologyData *workingData)
Calculate total fundamental reactive power.
_iq13 calculateTotalFundamentalApparentPower (metrologyData *workingData)
Calculate total fundamental apparent power.
_iq19 calculateLinetoLineVoltage (phaseMetrology *phase1, phaseMetrology *phase2)
Calculate line to line voltage.
_iq19 calculateFundamentalLinetoLineVoltage (phaseMetrology *phase1, phaseMetrology *phase2)
Calculate fundamental line to line voltage.
_iq13 calculateAggregatePowerfactor (metrologyData *workingData)
Calculate aggregate power factor.
_iq19 calculateVectorCurrentSum (metrologyData *workingData)
Calculate current vector sum.
_iq19 calculateNeutralRMSCurrent (neutralMetrology *neutral, currentSensorCalibrationData *neutralCal)
calculate Neutral RMS Current
void readLinetoLineVoltage (metrologyData *workingData)
Read Line to Line Voltage param[in] workingData The metrology instance.
void readFundamentalLinetoLineVoltage (metrologyData *workingData)
Read Fundamental Line to Line Voltage param[in] workingData The metrology instance.
uint64_t integratePowertoEnergy (energyIntegrator *en, _iq13 power, uint32_t samples)
Integrate Power to Energy.
_iq19 calculateCycleRMSVoltage (metrologyData *workingData, PHASES ph)
Cycle RMS Voltage Calculation.
void checkSagSwellEvents (metrologyData *workingData, PHASES ph)
Check for sag swell events.
_iq19 calculateVdcEstimate (phaseMetrology *phase, phaseCalibrationData *phaseCal)
calculate dc estimate voltage
_iq19 calculateIdcEstimate (phaseMetrology *phase, phaseCalibrationData *phaseCal)
calculate dc estimate current
_iq19 calculateNeutralIdcEstimate (neutralMetrology *neutral, currentSensorCalibrationData *neutralCal)
calculate neutral dc estimate current
void Metrology_setDefaultCalibrationData ()
Set default calibration data to flash.
void Metrology_initializeCalibrationData ()
Load calibration data from flash.
int16_t Metrology_getPhaseInitialVdcEstimate (metrologyData *workingData, PHASES ph)
Reads phase voltage dc estimate.
int16_t Metrology_getPhaseInitialIdcEstimate (metrologyData *workingData, PHASES ph)
Reads phase current dc estimate.
int32_t Metrology_getPhaseVacOffset (metrologyData *workingData, PHASES ph)
Reads phase voltage AC offset.
int32_t Metrology_getPhaseIacOffset (metrologyData *workingData, PHASES ph)
Reads phase current AC offset.
int32_t Metrology_getPhasePOffset (metrologyData *workingData, PHASES ph)
Reads phase active power offset.
int32_t Metrology_getPhaseQOffset (metrologyData *workingData, PHASES ph)
Reads phase reactive power offset.
int32_t Metrology_getPhaseFundPOffset (metrologyData *workingData, PHASES ph)
Reads phase fundamental active power offset.
int32_t Metrology_getPhaseFundQOffset (metrologyData *workingData, PHASES ph)
Reads phase fundamental reactive power offset.
int32_t Metrology_getPhaseFundVOffset (metrologyData *workingData, PHASES ph)
Reads phase fundamental voltage offset.
int32_t Metrology_getPhaseFundIOffset (metrologyData *workingData, PHASES ph)
Reads phase fundamental current offset.
int16_t Metrology_getPhaseCorrectionParameters (metrologyData *workingData, PHASES ph)
Reads phase correction parameters.
uint32_t Metrology_getPhaseVRMSScaling (metrologyData *workingData, PHASES ph)
Reads voltage scale factor.
uint32_t Metrology_getPhaseIRMSScaling (metrologyData *workingData, PHASES ph)
Reads current scale factor.
uint32_t Metrology_getPhasePScaling (metrologyData *workingData, PHASES ph)
Reads power scale factor.
int16_t Metrology_getNeutralInitialIdcEstimate (metrologyData *workingData)
Reads neutral current dc estimate.
int32_t Metrology_getNeutralIacOffset (metrologyData *workingData)
Reads neutral current ac offset.
int32_t Metrology_getNeutralPOffset (metrologyData *workingData)
Reads neutral active power offset.
int32_t Metrology_getNeutralQOffset (metrologyData *workingData)
Reads neutral reactive power offset.
int32_t Metrology_getNeutralFundPOffset (metrologyData *workingData)
Reads neutral fundamental active power offset.
int32_t Metrology_getNeutralFundQOffset (metrologyData *workingData)
Reads neutral fundamental reactive power offset.
int32_t Metrology_getNeutralFundVOffset (metrologyData *workingData)
Reads neutral fundamental voltage offset.
int32_t Metrology_getNeutralFundIOffset (metrologyData *workingData)
Reads neutral fundamental current offset.
uint32_t Metrology_getNeutralIRMSScaling (metrologyData *workingData)
Reads neutral current scale factor.
uint32_t Metrology_getNeutralPScaling (metrologyData *workingData)
Reads neutral power scale factor.
int16_t Metrology_getNeutralCorrectionParameters (metrologyData *workingData)
Reads neutral correction data.
int32_t Metrology_getCalibrationStatus (metrologyData *workingData)
Reads calibration status.
void Metrology_setCalibrationStatus (metrologyData *workingData, int32_t status)
Update calibration data.
void Metrology_setPhaseVacOffset (metrologyData *workingData, int32_t data, PHASES ph)
Update Phase voltage offset.
void Metrology_setPhaseFundVOffset (metrologyData *workingData, int32_t data, PHASES ph)
Update Phase fundamental voltage offset.
void Metrology_setPhaseVdcEstimate (metrologyData *workingData, int16_t data, PHASES ph)
Update Phase voltage DC estimate.
void Metrology_setPhaseVRMSScaling (metrologyData *workingData, uint32_t data, PHASES ph)
Update Phase voltage scale factor.
void Metrology_setPhaseIacOffset (metrologyData *workingData, int32_t data, PHASES ph)
Update Phase current offset.
void Metrology_setPhaseFundIOffset (metrologyData *workingData, int32_t data, PHASES ph)
Update Phase fundamental current offset.
void Metrology_setPhaseIdcEstimate (metrologyData *workingData, int16_t data, PHASES ph)
Update Phase current DC estimate.
void Metrology_setPhaseIRMSScaling (metrologyData *workingData, uint32_t data, PHASES ph)
Update Phase current scale factor.
void Metrology_setPhasePScaling (metrologyData *workingData, uint32_t data, PHASES ph)
Update Phase power scale factor.
void Metrology_setPhaseFundPOffset (metrologyData *workingData, int32_t data, PHASES ph)
Update Phase fundamental active power offset.
void Metrology_setPhaseFundQOffset (metrologyData *workingData, int32_t data, PHASES ph)
Update Phase fundamental reactive power offset.
void Metrology_setPhasePOffset (metrologyData *workingData, int32_t data, PHASES ph)
Update Phase active power offset.
void Metrology_setPhaseQOffset (metrologyData *workingData, int32_t data, PHASES ph)
Update Phase reactive power offset.
void Metrology_setPhaseOffset (metrologyData *workingData, int16_t data, PHASES ph)
Update Phase calibration offset.
void Metrology_setNeutralIacOffset (metrologyData *workingData, int32_t data)
Update Neutral current offset.
void Metrology_setNeutralFundIOffset (metrologyData *workingData, int32_t data)
Update neutral fundamental current offset.
void Metrology_setNeutralIdcEstimate (metrologyData *workingData, int16_t data)
Update neutral current dc estimate.
void Metrology_setNeutralIRMSScaling (metrologyData *workingData, uint32_t data)
Update neutral current scale factor.
void Metrology_setNeutralPScaling (metrologyData *workingData, uint32_t data)
Update neutral power scale factor.
void Metrology_setNeutralFundPOffset (metrologyData *workingData, int32_t data)
Update neutral fundamental active power offset.
void Metrology_setNeutralFundQOffset (metrologyData *workingData, int32_t data)
Update neutral fundamental reactive power offset.
void Metrology_setNeutralPOffset (metrologyData *workingData, int32_t data)
Update neutral active power offset.
void Metrology_setNeutralQOffset (metrologyData *workingData, int32_t data)
Update neutral reactive power offset.
void Metrology_setNeutralOffset (metrologyData *workingData, int16_t data)
Update neutral calibration offset.
void Metrology_clearCalibrationData (metrologyData *workingData)
Clear calibration data.
void Metrology_updateCalibrationData (metrologyData *workingData)
Update calibration data.
int32_t Metrology_ddsSinLookup (uint32_t phase)
Metrology sin lookup.
__STATIC_INLINE int64_t int64mpy (int32_t Input1, int32_t Input2)
64 bit multiplication
void Metrology_calculatePhaseReadings (metrologyData *workingData, PHASES ph)
Calculate phase parameters.
void Metrology_calculateThreePhaseParameters (metrologyData *workingData)
Calculate three phase parameters.
void Metrology_calculateTotalParameters (metrologyData *workingData)
Calculate total parameters.
void Metrology_calculateNeutralReadings (metrologyData *workingData)
Calculate neutral parameters.
void Metrology_sagSwellDetection (metrologyData *workingData, PHASES ph)
Sag Swell Detection.
int32_t Metrology_getRMSVoltage (metrologyData *workingData, PHASES ph)
Read RMS Voltage.
int32_t Metrology_getRMSCurrent (metrologyData *workingData, PHASES ph)
Read RMS Current.
int32_t Metrology_getActivePower (metrologyData *workingData, PHASES ph)
Read Active Power.
int32_t Metrology_getReactivePower (metrologyData *workingData, PHASES ph)
Read Reactive Power.
int32_t Metrology_getApparentPower (metrologyData *workingData, PHASES ph)
Read Apparent Power.
int32_t Metrology_getFundamentalRMSVoltage (metrologyData *workingData, PHASES ph)
Read Fundamental RMS Voltage.
int32_t Metrology_getFundamentalRMSCurrent (metrologyData *workingData, PHASES ph)
Read Fundamental RMS Current.
int32_t Metrology_getFundamentalActivePower (metrologyData *workingData, PHASES ph)
Read Fundamental Active Power.
int32_t Metrology_getFundamentalReactivePower (metrologyData *workingData, PHASES ph)
Read Fundamental Reactive Power.
int32_t Metrology_getFundamentalApparentPower (metrologyData *workingData, PHASES ph)
Read Fundamental Apparent Power.
int16_t Metrology_getPowerFactor (metrologyData *workingData, PHASES ph)
Read phase power factor.
int16_t Metrology_getAngleVoltagetoCurrent (metrologyData *workingData, PHASES ph)
Read phase power factor angle.
int16_t Metrology_getOverDeviation (metrologyData *workingData, PHASES ph)
Read voltage over deviation.
int16_t Metrology_getUnderDeviation (metrologyData *workingData, PHASES ph)
Read voltage under deviation.
int16_t Metrology_getVoltageTHD (metrologyData *workingData, PHASES ph)
Read voltage THD.
int16_t Metrology_getCurrentTHD (metrologyData *workingData, PHASES ph)
Read current THD.
int16_t Metrology_getMainsFrequency (metrologyData *workingData, PHASES ph)
Read mains frequency.
int32_t Metrology_getMaxSwellValue (metrologyData *workingData, PHASES ph)
Read maximum swell voltage.
int32_t Metrology_getMinSagValue (metrologyData *workingData, PHASES ph)
Read minimum sag voltage.
uint16_t Metrology_getSagEvents (metrologyData *workingData, PHASES ph)
Read number of sag events.
uint32_t Metrology_getSagDuration (metrologyData *workingData, PHASES ph)
Read Sag duration.
uint16_t Metrology_getSwellEvents (metrologyData *workingData, PHASES ph)
Read number of swell events.
uint32_t Metrology_getSwellDuration (metrologyData *workingData, PHASES ph)
Read swell duration.
uint16_t Metrology_getInterruptionEvents (metrologyData *workingData, PHASES ph)
Read number of interruption events.
uint32_t Metrology_getInterruptionDuration (metrologyData *workingData, PHASES ph)
Read interruption duration.
int32_t Metrology_getTotalActivePower (metrologyData *workingData)
Read total active power.
int32_t Metrology_getTotalReactivePower (metrologyData *workingData)
Read total reactive power.
int32_t Metrology_getTotalApparentPower (metrologyData *workingData)
Read total apparent power.
int32_t Metrology_getTotalFundamentalActivePower (metrologyData *workingData)
Read total fundamental active power.
int32_t Metrology_getTotalFundamentalReactivePower (metrologyData *workingData)
Read total fundamental reactive power.
int32_t Metrology_getTotalFundamentalApparentPower (metrologyData *workingData)
Read total fundamental apparent power.
uint64_t Metrology_getActiveEnergyImported (metrologyData *workingData, PHASES ph)
Read active energy imported.
uint64_t Metrology_getActiveEnergyExported (metrologyData *workingData, PHASES ph)
Read active energy exported.
uint64_t Metrology_getFundamentalActiveEnergyImported (metrologyData *workingData, PHASES ph)
Read fundamental active energy imported.
uint64_t Metrology_getFundamentalActiveEnergyExported (metrologyData *workingData, PHASES ph)
Read fundamental active energy exported.
uint64_t Metrology_getReactiveEnergyFirstQuadrant (metrologyData *workingData, PHASES ph)
Read reactive energy frist quadrant.
uint64_t Metrology_getReactiveEnergySecondQuadrant (metrologyData *workingData, PHASES ph)
Read reactive energy second quadrant.
uint64_t Metrology_getReactiveEnergyThirdQuadrant (metrologyData *workingData, PHASES ph)
Read reactive energy third quadrant.
uint64_t Metrology_getReactiveEnergyFourthQuadrant (metrologyData *workingData, PHASES ph)
Read reactive energy fourth quadrant.
uint64_t Metrology_getFundamentalReactiveEnergyFirstQuadrant (metrologyData *workingData, PHASES ph)
Read fundamental reactive energy frist quadrant.
uint64_t Metrology_getFundamentalReactiveEnergySecondQuadrant (metrologyData *workingData, PHASES ph)
Read fundamental reactive energy second quadrant.
uint64_t Metrology_getFundamentalReactiveEnergyThirdQuadrant (metrologyData *workingData, PHASES ph)
Read fundamental reactive energy third quadrant.
uint64_t Metrology_getFundamentalReactiveEnergyFourthQuadrant (metrologyData *workingData, PHASES ph)
Read fundamental reactive energy fourth quadrant.
uint64_t Metrology_getApparentEnergyImported (metrologyData *workingData, PHASES ph)
Read apparent energy imported.
uint64_t Metrology_getApparentEnergyExported (metrologyData *workingData, PHASES ph)
Read apparent energy exported.
uint64_t Metrology_getFundamentalApparentEnergyImported (metrologyData *workingData, PHASES ph)
Read fundamental apparent energy imported.
uint64_t Metrology_getFundamentalApparentEnergyExported (metrologyData *workingData, PHASES ph)
Read fundamental apparent energy exported.
_iq8 Metrology_getVdcEstimate (metrologyData *workingData, PHASES ph)
Read DC voltage estimate.
_iq8 Metrology_getIdcEstimate (metrologyData *workingData, PHASES ph)
Read DC current estimate.
_iq8 Metrology_getNeutralIdcEstimate (metrologyData *workingData)
Read Neutral DC current estimate.
int16_t Metrology_getPhasetoPhaseAngle (metrologyData *workingData, PHASES ph)
Read Phase to phase angle.
uint64_t Metrology_getTotalActiveEnergyImported (metrologyData *workingData)
Read total active energy imported.
uint64_t Metrology_getTotalActiveEnergyExported (metrologyData *workingData)
Read total active energy exported.
uint64_t Metrology_getTotalFundamentalActiveEnergyImported (metrologyData *workingData)
Read total fundamental active energy imported.
uint64_t Metrology_getTotalFundamentalActiveEnergyExported (metrologyData *workingData)
Read total fundamental active energy exported.
uint64_t Metrology_getTotalReactiveEnergyFirstQuadrant (metrologyData *workingData)
Read total reactive energy in quadrant I.
uint64_t Metrology_getTotalReactiveEnergySecondQuadrant (metrologyData *workingData)
Read total reactive energy in quadrant II.
uint64_t Metrology_getTotalReactiveEnergyThirdQuadrant (metrologyData *workingData)
Read total reactive energy in quadrant III.
uint64_t Metrology_getTotalReactiveEnergyFourthQuadrant (metrologyData *workingData)
Read total reactive energy in quadrant IV.
uint64_t Metrology_getTotalApparentEnergyImported (metrologyData *workingData)
Read total apparent energy imported.
uint64_t Metrology_getTotalApparentEnergyExported (metrologyData *workingData)
Read total apparent energy exported.
int32_t Metrology_getLinetoLineVoltagePhase0toPhase1 (metrologyData *workingData)
Read line to line voltage phase 0 to phase 1.
int32_t Metrology_getLinetoLineVoltagePhase1toPhase2 (metrologyData *workingData)
Read line to line voltage phase 1 to phase 2.
int32_t Metrology_getLinetoLineVoltagePhase2toPhase0 (metrologyData *workingData)
Read line to line voltage phase 2 to phase 0.
int32_t Metrology_getFundamentalLinetoLineVoltagePhase0toPhase1 (metrologyData *workingData)
Read fundamental line to line voltage phase 0 to phase 1.
int32_t Metrology_getFundamentalLinetoLineVoltagePhase1toPhase2 (metrologyData *workingData)
Read fundamental line to line voltage phase 1 to phase 2.
int32_t Metrology_getFundamentalLinetoLineVoltagePhase2toPhase0 (metrologyData *workingData)
Read fundamental line to line voltage phase 2 to phase0.
int32_t Metrology_getCurrentVectorSum (metrologyData *workingData)
Read current vector sum.
int64_t Metrology_getRawActivePower (metrologyData *workingData, uint16_t *samples, PHASES ph)
Read raw active power.
int64_t Metrology_getRawReactivePower (metrologyData *workingData, uint16_t *samples, PHASES ph)
Read raw reactive power.
int32_t Metrology_getNeutralRMSCurrent (metrologyData *workingData)
Read Neutral RMS Current.
void Metrology_init (metrologyData *workingData)
Metrology Init.
void Metrology_initNVData (metrologyData *workingData)
Metrology Init nv data.
void Metrology_alignwithNVData (metrologyData *workingData)
Metrology Align with nv data.
void Metrology_setPhaseCorrection (phaseCorrection *phCorr, int32_t correction)
Set phase Correction.
void Metrology_alignWithCalibrationData (metrologyData *workingData)
Metrology Align with calibration data.
Variables
struct infoMem nvParams
Defines nvParams struct.
calibrationData calibrationDefaults
structure to store default calibration parameters
static const int32_t sineTable [METROLOGY_DDS_STEPS+1]
Defines First quarter Sine Table in Q(METROLOGY_DDS_TABLE_RESOLUTION-1) sin(x) for x = [0, PI/4] for (i = 0; i < METROLOGY_DDS_STEPS; i++) { sineTable[i] = sin(i * PI/(2 * METROLOGY_DDS_STEPS)) * 2^(METROLOGY_DDS_TABLE_RESOLUTION-1) }.
const int32_t phase_shift_fir_coeffs [PHASE_SHIFT_FIR_TABLE_ELEMENTS][2]
FIR coefficients to correct specific phase shift angles at 50 Hz and sampling 2000 times per second. There are 256 steps in this table.
Detailed Description
Macro Definition Documentation
DEFAULT_BASE_PHASE_A_CORRECTION
#define DEFAULT_BASE_PHASE_A_CORRECTION ((int) 0)
Defines holds the value for phase correction to compensate for delay due to the current transformer and/or front-end circuitry at phase A. This can be set to a value that is in fairly acceptable range, and it will be fine tuned under phase correction during calibration.
DEFAULT_BASE_PHASE_B_CORRECTION
#define DEFAULT_BASE_PHASE_B_CORRECTION ((int) 0)
Defines holds the value for phase correction to compensate for delay due to the current transformer and/or front-end circuitry at phase B. This can be set to a value that is in fairly acceptable range, and it will be fine tuned under phase correction during calibration.
DEFAULT_BASE_PHASE_C_CORRECTION
#define DEFAULT_BASE_PHASE_C_CORRECTION ((int) 0)
Defines holds the value for phase correction to compensate for delay due to the current transformer and/or front-end circuitry at phase C. This can be set to a value that is in fairly acceptable range, and it will be fine tuned under phase correction during calibration.
DEFAULT_BASE_NEUTRAL_PHASE_CORRECTION
#define DEFAULT_BASE_NEUTRAL_PHASE_CORRECTION ((int) 0)
Defines holds the value for phase correction to compensate for delay due to the current transformer and/or front-end circuitry at neutral. This can be set to a value that is in fairly acceptable range, and it will be fine tuned under phase correction during calibration.
METROLOGY_IQ19_TO_MICROAMPS
#define METROLOGY_IQ19_TO_MICROAMPS _IQ19(1.9073486328125)
Defines conversion factor from IQ19 to micro amps.
current in micro amps = current in IQ19 * 1000000 / 2pow(19)
Referenced by Metrology_getCurrentVectorSum(), Metrology_getFundamentalRMSCurrent(), Metrology_getNeutralRMSCurrent(), and Metrology_getRMSCurrent().
METROLOGY_IQ13_TO_MILLIWATTS
#define METROLOGY_IQ13_TO_MILLIWATTS _IQ13(0.1220703125)
Defines conversion factor from IQ13 to milli watts.
power in milli watts = power in IQ13 * 1000 / 2pow(13)
Referenced by Metrology_getActivePower(), Metrology_getApparentPower(), Metrology_getFundamentalActivePower(), Metrology_getFundamentalApparentPower(), Metrology_getFundamentalReactivePower(), Metrology_getReactivePower(), Metrology_getTotalActivePower(), Metrology_getTotalApparentPower(), Metrology_getTotalFundamentalActivePower(), Metrology_getTotalFundamentalApparentPower(), Metrology_getTotalFundamentalReactivePower(), and Metrology_getTotalReactivePower().
Enumeration Type Documentation
PHASES
enum PHASES
Enumerator
MAX_PHASES
Total number of phases.
METROLOGY_STATUS
enum METROLOGY_STATUS
Enumerator
METROLOGY_STATUS_POWER_DOWN
This bit indicates the meter is in the power down state.
METROLOGY_STATUS_REVERSED
This bit indicates the current status of the meter is "current flow is reversed", after all persistence checking, and other safeguards, have been used to check the validity of the reverse indication.
METROLOGY_STATUS_EARTHED
This bit indicates the current status of the meter is "current flow is earthed", after all persistence checking, and other safeguards, have been used to check the validity of the earthed indication.
METROLOGY_STATUS_PHASE_VOLTAGE_OK
This bit indicates the phase voltage is OK.
METROLOGY_STATUS_BATTERY_OK
This bit indicates the battery condition is OK. If battery monitoring is not enabled, this bit is not used.
OPERATING_MODES
enum OPERATING_MODES
Enumerator
OPERATING_MODE_NORMAL
The meter is operating normally
OPERATING_MODE_AMR_ONLY
The meter is in a battery powered state with automated meter reading, LCD and RTC functioning.
OPERATING_MODE_LCD_ONLY
The meter is in a battery powered state with only the LCD and RTC functioning.
OPERATING_MODE_POWERFAIL
The meter is in a battery powered state with only the minimum of features (probably just the RTC) functioning.
SAG_SWELL_EVENTS
enum SAG_SWELL_EVENTS
Enumerator
SAG_SWELL_VOLTAGE_INTERRUPTION_CONTINUING
Voltage interruptions continuing.
SAG_SWELL_VOLTAGE_INTERRUPTION_ONSET
Voltage interruptions onset.
SAG_SWELL_VOLTAGE_SAG_CONTINUING
Voltage sag continuing.
SAG_SWELL_VOLTAGE_SAG_ONSET
Voltage sag onset.
SAG_SWELL_VOLTAGE_NORMAL
Voltage normal.
SAG_SWELL_VOLTAGE_SWELL_ONSET
Voltage swell onset.
SAG_SWELL_VOLTAGE_SWELL_CONTINUING
Voltage swell continuing.
SAG_SWELL_VOLTAGE_POWER_DOWN_OK
Voltage power down.
PHASE_STATUS
enum PHASE_STATUS
Enumerator
PHASE_STATUS_NEW_LOG
This flag in a channel's status variable indicates there is fresh gathered data from the background activity to be post-processed by the foreground activity.
PHASE_STATUS_V_POS
This flag in a channel's status variable indicates the voltage signal is currently in the positive half of its cycle.
PHASE_STATUS_I_POS
This flag in a channel's status variable indicates the current signal is currently in the positive half of its cycle.
PHASE_STATUS_V_OVERRANGE
This flag in a channel's status variable indicates the voltage signal was in overload during the last logged interval. Overload is determined by an excessive number of samples hitting the end-stops of the ADC's range.
PHASE_STATUS_I_OVERRANGE
This flag in a channel's status variable indicates the phase current signal was in overload during the last logged interval. Overload is determined by an excessive number of samples hitting the end-stops of the ADC's range.
PHASE_STATUS_I_REVERSED
This flag in a channel's status variable indicates the phase current signal was reversed during the last logged interval.
PHASE_STATUS_I_NEUTRAL_OVERRANGE
This flag in a channel's status variable indicates the phase current signal was in overload during the last logged interval. Overload is determined by an excessive number of samples hitting the end-stops of the ADC's range. This is only used if the meter supports monitoring of both the live and neutral leads for anti-tamper management.
PHASE_STATUS_I_NEUTRAL_REVERSED
This flag in a channel's status variable indicates the neutral current signal was reversed during the last logged interval. This is only used if the meter supports monitoring of both the live and neutral leads for anti-tamper management.
PHASE_STATUS_CURRENT_FROM_NEUTRAL
This flag in a channel's status variable indicates the neutral current is the one currently being used. This means it has been judged by the anti-tamper logic to be the measurement which can best be trusted. This is only used if the meter supports monitoring of both the live and neutral leads for anti-tamper management.
PHASE_STATUS_I_NEUTRAL_POS
This flag in a channel's status variable indicates the neutral current signal is currently in the positive half of its cycle. This is only used if the meter supports monitoring of both the live and neutral leads for anti-tamper management.
PHASE_STATUS_REVERSED
This flag in a channel's status variable indicates the power has been declared to be reversed, after the anti-tamper logic has processed the raw indications. Live neutral or both leads may be reversed when this bit is set.
PHASE_STATUS_UNBALANCED
This flag in a channel's status variable indicates the power (current in limp mode) has been declared to be unbalanced, after the anti-tamper logic has processed the raw indications.
Function Documentation
Metrology_perSampleProcessing()
void Metrology_perSampleProcessing (metrologyData * workingData)
Metrology per phase sampling.
Parameters
[in] workingData The metrology data
References currentDPSet::activePower, phaseParams::crossSum, phaseParams::current, currentParams::currentEndStops, metrologyData::currentIntegrationData, currentDPSet::currentSq, phaseParams::cycleDotProd, phaseParams::cycleDpSet, mainsParams::cyclePeriod, cyclePhaseDPSet::cycleSampleCount, mainsParams::cycleSamples, phaseMetrology::cycleStatus, cyclePhaseDPSet::cycleVoltageSq, currentParams::dotProd, phaseParams::dotProd, phaseParams::dpSet, currentDPSet::FActivePower, phaseCorrection::firBeta, currentDPSet::FReactivePower, voltageDPSet::fVoltageSq, I_ADC_MAX, I_ADC_MIN, currentParams::I_dc_estimate, currentParams::I_dc_estimate_integral, currentParams::IHistory, int64mpy(), metrologyData::lastRawCurrentData, phaseParams::lastVoltageSample, MAX_PER_SAMPLE_VOLTAGE_SLEW, MAX_PHASES, metrology_dcFilter(), Metrology_ddsSinLookup(), METROLOGY_MAX_CYCLE_SAMPLES, OPERATING_MODE_NORMAL, metrologyData::operatingMode, phaseMetrology::params, PHASE_STATUS_V_POS, currentParams::phaseCorrection, metrologyData::phases, phaseParams::purePhase, phaseParams::purePhaseRate, currentParams::quadratureCorrection, metrologyData::rawCurrentData, metrologyData::rawVoltageData, currentDPSet::reactivePower, currentDPSet::sampleCount, voltageDPSet::sampleCount, phaseMetrology::status, phaseCorrection::step, V_ADC_MAX, V_ADC_MIN, phaseParams::V_dc_estimate, phaseParams::V_dc_estimate1, V_HISTORY_MASK, phaseParams::vHistory, phaseParams::vHistoryIndex, phaseParams::voltageEndStops, phaseParams::voltagePeriod, and voltageDPSet::voltageSq.
Metrology_perSampleEnergyPulseProcessing()
void Metrology_perSampleEnergyPulseProcessing (metrologyData * workingData)
Metrology per sample energy pulse processing.
Parameters
[in] workingData The metrology data
References phaseEnergy::activeEnergyPulse, TotalPowerReadings::activePower, totalParams::energy, ENERGY_PULSE_DURATION, energyPulse::integrator, energyPulse::pulseRemainingTime, phaseEnergy::reactiveEnergyPulse, TotalPowerReadings::reactivePower, totalParams::readings, TOTAL_ACTIVE_ENERGY_PULSE_THRESHOLD, TOTAL_REACTIVE_ENERGY_PULSE_THRESHOLD, and metrologyData::totals.
metrology_dcFilter()
__STATIC_INLINE _iq23 metrology_dcFilter (int64_t * p, _iq23 x)
dc_filter() Simple 1st order DC filter y(n) = y(n-1) + (x(n) - y(n-1))/2^14 xfilt(n) = x(n) - y(n) where: x(n) = most recent ADC sample y(n) = filter tap xfilt(n) = DC filtered output
Parameters
[in,out] p pointer to filter tap data
[in] x pointer to input data
Returns
filtered output
Referenced by Metrology_perSampleProcessing().
calculateRMSVoltage()
_iq19 calculateRMSVoltage (phaseMetrology * phase, phaseCalibrationData * phaseCal)
calculate RMS Voltage
Parameters
[in] phase The phase metrology
[in] phaseCal The phase calibration data
Returns
RMS Voltage in volts (IQ19 format)
References phaseParams::dotProd, phaseParams::dpSet, phaseMetrology::params, PHASE_STATUS_V_OVERRANGE, RMS_VOLTAGE_OVERRANGE, voltageDPSet::sampleCount, phaseMetrology::status, phaseCalibrationData::VacOffset, voltageDPSet::voltageSq, and phaseCalibrationData::VscaleFactor.
Referenced by Metrology_calculatePhaseReadings().
calculateRMSCurrent()
_iq19 calculateRMSCurrent (phaseMetrology * phase, phaseCalibrationData * phaseCal)
calculate RMS Current
Parameters
[in] phase The phase metrology
[in] phaseCal The phase calibration data
Returns
RMS Current in amps (IQ19 format)
References phaseCalibrationData::current, phaseParams::current, currentDPSet::currentSq, currentParams::dotProd, phaseParams::dpSet, currentSensorCalibrationData::IacOffset, currentSensorCalibrationData::IscaleFactor, phaseMetrology::params, PHASE_STATUS_I_OVERRANGE, RMS_CURRENT_OVERRANGE, currentDPSet::sampleCount, and phaseMetrology::status.
Referenced by Metrology_calculatePhaseReadings().
calculateActivePower()
_iq13 calculateActivePower (phaseMetrology * phase, phaseCalibrationData * phaseCal)
calculate active power
Parameters
[in] phase The phase metrology
[in] phaseCal The phase calibration data
Returns
Active Power in watts (IQ13 format)
References currentDPSet::activePower, currentSensorCalibrationData::activePowerOffset, phaseCalibrationData::current, phaseParams::current, currentParams::dotProd, phaseParams::dpSet, phaseCorrection::firGain, phaseMetrology::params, PHASE_STATUS_I_OVERRANGE, PHASE_STATUS_V_OVERRANGE, currentParams::phaseCorrection, POWER_OVERRANGE, currentSensorCalibrationData::PscaleFactor, currentDPSet::sampleCount, and phaseMetrology::status.
Referenced by Metrology_calculatePhaseReadings().
calculateReactivePower()
_iq13 calculateReactivePower (phaseMetrology * phase, phaseCalibrationData * phaseCal)
calculate active power
Parameters
[in] phase The phase metrology
[in] phaseCal The phase calibration data
Returns
Reactive Power in VAR (IQ13 format)
References phaseCalibrationData::current, phaseParams::current, currentParams::dotProd, phaseParams::dpSet, phaseCorrection::firGain, phaseMetrology::params, PHASE_STATUS_I_OVERRANGE, PHASE_STATUS_V_OVERRANGE, POWER_OVERRANGE, currentSensorCalibrationData::PscaleFactor, currentParams::quadratureCorrection, currentDPSet::reactivePower, currentSensorCalibrationData::reactivePowerOffset, currentDPSet::sampleCount, and phaseMetrology::status.
Referenced by Metrology_calculatePhaseReadings().
calculateApparentPower()
_iq13 calculateApparentPower (phaseMetrology * phase)
calculate apparent power
Parameters
[in] phase The phase metrology
Returns
Apparent Power in VA (IQ13 format)
References phaseReadings::activePower, phaseReadings::reactivePower, and phaseMetrology::readings.
Referenced by Metrology_calculatePhaseReadings().
calculateFundamentalRMSVoltage()
_iq19 calculateFundamentalRMSVoltage (phaseMetrology * phase, phaseCalibrationData * phaseCal)
calculate fundamental RMS Voltage
Parameters
[in] phase The phase metrology
[in] phaseCal The phase calibration data
Returns
Fundamental RMS Voltage in volts (IQ19 format)
References phaseParams::current, phaseParams::dotProd, phaseParams::dpSet, phaseCorrection::firGain, voltageDPSet::fVoltageSq, phaseMetrology::params, PHASE_STATUS_V_OVERRANGE, currentParams::phaseCorrection, RMS_VOLTAGE_OVERRANGE, voltageDPSet::sampleCount, phaseMetrology::status, phaseCalibrationData::VFundamentalAcOffset, and phaseCalibrationData::VscaleFactor.
Referenced by Metrology_calculatePhaseReadings().
calculateFundamentalRMSCurrent()
_iq19 calculateFundamentalRMSCurrent (phaseMetrology * phase, phaseCalibrationData * phaseCal)
calculate fundamental RMS Current
Parameters
[in] phase The phase metrology
[in] phaseCal The phase calibration data
Returns
Fundamental RMS Current in amps (IQ19 format)
References phaseCalibrationData::current, phaseReadings::FApparentPower, phaseReadings::FRMSVoltage, currentSensorCalibrationData::IFAcOffset, PHASE_STATUS_I_OVERRANGE, phaseMetrology::readings, RMS_CURRENT_OVERRANGE, and phaseMetrology::status.
Referenced by Metrology_calculatePhaseReadings().
calculateFundamentalActivePower()
_iq13 calculateFundamentalActivePower (phaseMetrology * phase, phaseCalibrationData * phaseCal)
calculate fundamental active Power
Parameters
[in] phase The phase metrology
[in] phaseCal The phase calibration data
Returns
Fundamental Active Power in watts (IQ13 format)
References phaseCalibrationData::current, phaseParams::current, currentParams::dotProd, phaseParams::dotProd, phaseParams::dpSet, currentDPSet::FActivePower, phaseCorrection::firGain, voltageDPSet::fVoltageSq, phaseMetrology::params, PHASE_STATUS_I_OVERRANGE, PHASE_STATUS_V_OVERRANGE, currentParams::phaseCorrection, POWER_OVERRANGE, currentSensorCalibrationData::PscaleFactor, currentDPSet::sampleCount, and phaseMetrology::status.
Referenced by Metrology_calculatePhaseReadings().
calculateFundamentalReactivePower()
_iq13 calculateFundamentalReactivePower (phaseMetrology * phase, phaseCalibrationData * phaseCal)
calculate fundamental reactive Power
Parameters
[in] phase The phase metrology
[in] phaseCal The phase calibration data
Returns
Fundamental Reactive Power in VAR (IQ13 format)
References phaseCalibrationData::current, phaseParams::current, currentParams::dotProd, phaseParams::dotProd, phaseParams::dpSet, phaseCorrection::firGain, currentDPSet::FReactivePower, voltageDPSet::fVoltageSq, phaseMetrology::params, PHASE_STATUS_I_OVERRANGE, PHASE_STATUS_V_OVERRANGE, currentParams::phaseCorrection, POWER_OVERRANGE, currentSensorCalibrationData::PscaleFactor, currentDPSet::sampleCount, and phaseMetrology::status.
Referenced by Metrology_calculatePhaseReadings().
calculateFundamentalApparentPower()
_iq13 calculateFundamentalApparentPower (phaseMetrology * phase)
calculate fundamental apparent Power
Parameters
[in] phase The phase metrology
Returns
Fundamental Apparent Power in VA (IQ13 format)
References phaseReadings::FActivePower, phaseReadings::FReactivePower, and phaseMetrology::readings.
Referenced by Metrology_calculatePhaseReadings().
accumulateActiveEnergy()
void accumulateActiveEnergy (metrologyData * workingData, PHASES ph)
accumulate active energy
Parameters
[in] workingData The Metrology Instance
[in] ph Phase number
References phaseEnergy::activeEnergyExported, phaseEnergy::activeEnergyImported, phaseReadings::activePower, phaseParams::current, currentParams::dotProd, phaseParams::dpSet, energyIntegrator::energy, phaseMetrology::energy, totalParams::energy, integratePowertoEnergy(), phaseMetrology::params, metrologyData::phases, phaseMetrology::readings, currentDPSet::sampleCount, and metrologyData::totals.
Referenced by Metrology_calculatePhaseReadings().
accumulateReactiveEnergy()
void accumulateReactiveEnergy (metrologyData * workingData, PHASES ph)
accumulate reactive energy
Parameters
[in] workingData The Metrology Instance
[in] ph Phase number
References phaseReadings::activePower, phaseParams::current, currentParams::dotProd, phaseParams::dpSet, energyIntegrator::energy, phaseMetrology::energy, totalParams::energy, integratePowertoEnergy(), phaseMetrology::params, metrologyData::phases, phaseEnergy::reactiveEnergyQuardrantI, phaseEnergy::reactiveEnergyQuardrantII, phaseEnergy::reactiveEnergyQuardrantIII, phaseEnergy::reactiveEnergyQuardrantIV, phaseReadings::reactivePower, phaseMetrology::readings, currentDPSet::sampleCount, and metrologyData::totals.
Referenced by Metrology_calculatePhaseReadings().
accumulateApparentEnergy()
void accumulateApparentEnergy (metrologyData * workingData, PHASES ph)
accumulate appparent energy
Parameters
[in] workingData The Metrology Instance
[in] ph Phase number
References phaseReadings::activePower, phaseReadings::apparentPower, phaseEnergy::appparentEnergyExported, phaseEnergy::appparentEnergyImported, phaseParams::current, currentParams::dotProd, phaseParams::dpSet, energyIntegrator::energy, phaseMetrology::energy, totalParams::energy, integratePowertoEnergy(), phaseMetrology::params, metrologyData::phases, phaseMetrology::readings, currentDPSet::sampleCount, and metrologyData::totals.
Referenced by Metrology_calculatePhaseReadings().
accumulateFundamentalActiveEnergy()
void accumulateFundamentalActiveEnergy (metrologyData * workingData, PHASES ph)
accumulate fundamental active energy
Parameters
[in] workingData The Metrology Instance
[in] ph Phase number
References phaseParams::current, currentParams::dotProd, phaseParams::dpSet, energyIntegrator::energy, phaseMetrology::energy, totalParams::energy, phaseReadings::FActivePower, phaseEnergy::fundamentalActiveEnergyExported, phaseEnergy::fundamentalActiveEnergyImported, integratePowertoEnergy(), phaseMetrology::params, metrologyData::phases, phaseMetrology::readings, currentDPSet::sampleCount, and metrologyData::totals.
Referenced by Metrology_calculatePhaseReadings().
accumulateFundamentalReactiveEnergy()
void accumulateFundamentalReactiveEnergy (metrologyData * workingData, PHASES ph)
accumulate fundamental reactive energy
Parameters
[in] workingData The Metrology Instance
[in] ph Phase number
References phaseReadings::activePower, phaseParams::current, currentParams::dotProd, phaseParams::dpSet, energyIntegrator::energy, phaseMetrology::energy, totalParams::energy, phaseReadings::FReactivePower, phaseEnergy::fundamentalReactiveEnergyQuardrantI, phaseEnergy::fundamentalReactiveEnergyQuardrantII, phaseEnergy::fundamentalReactiveEnergyQuardrantIII, phaseEnergy::fundamentalReactiveEnergyQuardrantIV, integratePowertoEnergy(), phaseMetrology::params, metrologyData::phases, phaseMetrology::readings, currentDPSet::sampleCount, and metrologyData::totals.
Referenced by Metrology_calculatePhaseReadings().
accumulateFundamentalApparentEnergy()
void accumulateFundamentalApparentEnergy (metrologyData * workingData, PHASES ph)
accumulate fundamental apparent energy
Parameters
[in] workingData The Metrology Instance
[in] ph Phase number
References phaseParams::current, currentParams::dotProd, phaseParams::dpSet, energyIntegrator::energy, phaseMetrology::energy, totalParams::energy, phaseReadings::FApparentPower, phaseEnergy::fundamentalAppparentEnergyExported, phaseEnergy::fundamentalAppparentEnergyImported, integratePowertoEnergy(), phaseMetrology::params, metrologyData::phases, phaseMetrology::readings, currentDPSet::sampleCount, and metrologyData::totals.
Referenced by Metrology_calculatePhaseReadings().
calculatePowerFactor()
_iq13 calculatePowerFactor (phaseMetrology * phase)
calculate power factor
Parameters
[in] phase The phase metrology
Returns
Power factor (IQ13 format)
References phaseReadings::activePower, phaseReadings::apparentPower, phaseReadings::reactivePower, and phaseMetrology::readings.
Referenced by Metrology_calculatePhaseReadings().
calculateAngleVoltagetoCurrent()
_iq15 calculateAngleVoltagetoCurrent (phaseMetrology * phase)
calculate power factor angle
Parameters
[in] phase The phase metrology
Returns
Power factor angle in per unit with base value of 180 degrees(3.14 radians) 180 degrees corresponds to 1 -180 degrees corresponds to -1
References phaseReadings::activePower, phaseReadings::reactivePower, and phaseMetrology::readings.
Referenced by Metrology_calculatePhaseReadings().
calculateOverDeviation()
_iq19 calculateOverDeviation (phaseMetrology * phase)
calculate voltage over deviation
Parameters
[in] phase The phase metrology
Returns
Voltage over deviation in percentage (IQ19 format)
References MAINS_NOMINAL_VOLTAGE_IQ19, phaseMetrology::readings, and phaseReadings::RMSVoltage.
Referenced by Metrology_calculatePhaseReadings().
calculateUnderDeviation()
_iq19 calculateUnderDeviation (phaseMetrology * phase)
calculate voltage under deviation
Parameters
[in] phase The phase metrology
Returns
Voltage under deviation in percentage (IQ19 format)
References MAINS_NOMINAL_VOLTAGE_IQ19, phaseMetrology::readings, and phaseReadings::RMSVoltage.
Referenced by Metrology_calculatePhaseReadings().
calculateVoltageTHD()
_iq19 calculateVoltageTHD (phaseMetrology * phase)
calculate voltage THD
Parameters
[in] phase The phase metrology
Returns
Voltage THD in percentage (IQ19 format)
References phaseReadings::FRMSVoltage, phaseMetrology::readings, and phaseReadings::RMSVoltage.
Referenced by Metrology_calculatePhaseReadings().
calculateCurrentTHD()
_iq19 calculateCurrentTHD (phaseMetrology * phase)
calculate current THD
Parameters
[in] phase The phase metrology
Returns
Current THD in percentage (IQ19 format)
References phaseReadings::FRMSCurrent, phaseMetrology::readings, and phaseReadings::RMSCurrent.
Referenced by Metrology_calculatePhaseReadings().
calculateMainsfrequency()
_iq15 calculateMainsfrequency (phaseMetrology * phase, phaseCalibrationData * phaseCal)
calculate mains frequency
Parameters
[in] phase The phase metrology
[in] phaseCal The phase calibration data
Returns
Mains Frequency (IQ15 format)
References phaseCalibrationData::current, phaseParams::current, phaseParams::interruptionLevel, phaseParams::interruptionLevelHalf, Metrology_setPhaseCorrection(), MIN_SAG_VOLTAGE, phaseMetrology::params, mainsParams::period, currentSensorCalibrationData::phaseOffset, phaseParams::purePhaseRate, currentParams::quadratureCorrection, SAMPLES_PER_10_SECONDS, phaseParams::voltagePeriod, and phaseCalibrationData::VscaleFactor.
Referenced by Metrology_calculatePhaseReadings().
calculateTotalActivePower()
_iq13 calculateTotalActivePower (metrologyData * workingData)
Calculate total active power.
Parameters
[in] workingData The metrology instance
Returns
Total Active Power in watts (IQ13 format)
References phaseReadings::activePower, MAX_PHASES, metrologyData::phases, phaseMetrology::readings, and TOTAL_RESIDUAL_POWER_CUTOFF.
Referenced by Metrology_calculateTotalParameters().
calculateTotalReactivePower()
_iq13 calculateTotalReactivePower (metrologyData * workingData)
Calculate total reactive power.
Parameters
[in] workingData The metrology instance
Returns
Total Reactive Power in VAR (IQ13 format)
References MAX_PHASES, metrologyData::phases, phaseReadings::reactivePower, phaseMetrology::readings, and TOTAL_RESIDUAL_POWER_CUTOFF.
Referenced by Metrology_calculateTotalParameters().
calculateTotalApparentPower()
_iq13 calculateTotalApparentPower (metrologyData * workingData)
Calculate total apparent power.
Parameters
[in] workingData The metrology instance
Returns
Total Apparent Power in VA (IQ13 format)
References phaseReadings::apparentPower, MAX_PHASES, metrologyData::phases, phaseMetrology::readings, and TOTAL_RESIDUAL_POWER_CUTOFF.
Referenced by Metrology_calculateTotalParameters().
calculateTotalFundamentalActivePower()
_iq13 calculateTotalFundamentalActivePower (metrologyData * workingData)
Calculate total fundamental active power.
Parameters
[in] workingData The metrology instance
Returns
Total Fundamental Active Power in watts (IQ13 format)
References phaseReadings::FActivePower, MAX_PHASES, metrologyData::phases, phaseMetrology::readings, and TOTAL_RESIDUAL_POWER_CUTOFF.
Referenced by Metrology_calculateTotalParameters().
calculateTotalFundamentalReactivePower()
_iq13 calculateTotalFundamentalReactivePower (metrologyData * workingData)
Calculate total fundamental reactive power.
Parameters
[in] workingData The metrology instance
Returns
Total Fundamental Reactive Power in VAR (IQ13 format)
References phaseReadings::FReactivePower, MAX_PHASES, metrologyData::phases, phaseMetrology::readings, and TOTAL_RESIDUAL_POWER_CUTOFF.
Referenced by Metrology_calculateTotalParameters().
calculateTotalFundamentalApparentPower()
_iq13 calculateTotalFundamentalApparentPower (metrologyData * workingData)
Calculate total fundamental apparent power.
Parameters
[in] workingData The metrology instance
Returns
Total Fundamental Apparent Power in VA (IQ13 format)
References phaseReadings::FApparentPower, MAX_PHASES, metrologyData::phases, phaseMetrology::readings, and TOTAL_RESIDUAL_POWER_CUTOFF.
Referenced by Metrology_calculateTotalParameters().
calculateLinetoLineVoltage()
_iq19 calculateLinetoLineVoltage (phaseMetrology * phase1, phaseMetrology * phase2)
Calculate line to line voltage.
Parameters
[in] phase1 The phase1 metrology
[in] phase2 The phase2 metrology
Returns
line to line voltage in volts (IQ19 format)
References phaseReadings::phasetoPhaseAngle, phaseMetrology::readings, and phaseReadings::RMSVoltage.
Referenced by readLinetoLineVoltage().
calculateFundamentalLinetoLineVoltage()
_iq19 calculateFundamentalLinetoLineVoltage (phaseMetrology * phase1, phaseMetrology * phase2)
Calculate fundamental line to line voltage.
Parameters
[in] phase1 The phase1 metrology
[in] phase2 The phase2 metrology
Returns
fundamental line to line voltage in volts (IQ19 format)
References phaseReadings::FRMSVoltage, phaseReadings::phasetoPhaseAngle, and phaseMetrology::readings.
Referenced by readFundamentalLinetoLineVoltage().
calculateAggregatePowerfactor()
_iq13 calculateAggregatePowerfactor (metrologyData * workingData)
Calculate aggregate power factor.
Parameters
[in] workingData The metrology instance
Returns
Aggregate power factor in IQ13 format
References TotalPowerReadings::activePower, TotalPowerReadings::apparentPower, TotalPowerReadings::reactivePower, totalParams::readings, and metrologyData::totals.
Referenced by Metrology_calculateThreePhaseParameters().
calculateVectorCurrentSum()
_iq19 calculateVectorCurrentSum (metrologyData * workingData)
Calculate current vector sum.
Parameters
[in] workingData The metrology instance
Returns
Current vector sum in amps (IQ19 format)
References metrologyData::phases, phaseReadings::phasetoPhaseAngle, phaseReadings::powerFactorAngle, phaseMetrology::readings, and phaseReadings::RMSCurrent.
Referenced by Metrology_calculateThreePhaseParameters().
calculateNeutralRMSCurrent()
_iq19 calculateNeutralRMSCurrent (neutralMetrology * neutral, currentSensorCalibrationData * neutralCal)
calculate Neutral RMS Current
Parameters
[in] neutral The neutral metrology
[in] neutralCal The neutral calibration data
Returns
Neutral RMS current in amps (IQ19 format)
References neutralDPSet::currentSq, neutralParams::dotProd, neutralParams::dpSet, currentSensorCalibrationData::IacOffset, currentSensorCalibrationData::IscaleFactor, neutralMetrology::params, and neutralDPSet::sampleCount.
Referenced by Metrology_calculateNeutralReadings().
integratePowertoEnergy()
uint64_t integratePowertoEnergy (energyIntegrator * en, _iq13 power, uint32_t samples)
Integrate Power to Energy.
Parameters
[in] en The energy instance
[in] power Power
[in] samples Number of samples
Returns
energy steps
References ENERGY_100mWATT_HOUR_THRESHOLD_IQ, and energyIntegrator::energyResidual.
Referenced by accumulateActiveEnergy(), accumulateApparentEnergy(), accumulateFundamentalActiveEnergy(), accumulateFundamentalApparentEnergy(), accumulateFundamentalReactiveEnergy(), and accumulateReactiveEnergy().
calculateCycleRMSVoltage()
_iq19 calculateCycleRMSVoltage (metrologyData * workingData, PHASES ph)
Cycle RMS Voltage Calculation.
Parameters
[in] workingData The Metrology Instance
[in] ph Phase number
Returns
cycle RMS Voltage in volts (IQ19 format)
References calInfo, phaseParams::cycleDotProd, phaseParams::cycleDpSet, cyclePhaseDPSet::cycleSampleCount, cyclePhaseDPSet::cycleVoltageSq, phaseMetrology::params, metrologyData::phases, phaseMetrology::readings, phaseReadings::RMSVoltageCycle, phaseCalibrationData::VacOffset, and phaseCalibrationData::VscaleFactor.
Referenced by checkSagSwellEvents().
checkSagSwellEvents()
void checkSagSwellEvents (metrologyData * workingData, PHASES ph)
Check for sag swell events.
Parameters
[in] workingData The Metrology Instance
[in] ph Phase number
References calculateCycleRMSVoltage(), phaseParams::interruptionDuration, phaseParams::interruptionEvents, phaseMetrology::params, metrologyData::phases, SAG_SWELL_VOLTAGE_INTERRUPTION_CONTINUING, SAG_SWELL_VOLTAGE_INTERRUPTION_ONSET, SAG_SWELL_VOLTAGE_NORMAL, SAG_SWELL_VOLTAGE_SAG_CONTINUING, SAG_SWELL_VOLTAGE_SAG_ONSET, SAG_SWELL_VOLTAGE_SWELL_CONTINUING, SAG_SWELL_VOLTAGE_SWELL_ONSET, phaseParams::sagDuration, phaseParams::sagEvents, phaseParams::sagMinVoltage, phaseParams::sagSwellState, phaseParams::sagThresholdStop, phaseParams::sagValue, phaseParams::swellDuration, phaseParams::swellEvents, phaseParams::swellThresholdStart, and phaseParams::swellValue.
Referenced by Metrology_sagSwellDetection().
calculateVdcEstimate()
_iq19 calculateVdcEstimate (phaseMetrology * phase, phaseCalibrationData * phaseCal)
calculate dc estimate voltage
Parameters
[in] phase The phase metrology
[in] phaseCal The phase calibration data
Returns
DC Estimate Voltage in volts (IQ19 format)
References phaseMetrology::params, phaseParams::V_dc_estimate, and phaseCalibrationData::VscaleFactor.
Referenced by Metrology_calculatePhaseReadings().
calculateIdcEstimate()
_iq19 calculateIdcEstimate (phaseMetrology * phase, phaseCalibrationData * phaseCal)
calculate dc estimate current
Parameters
[in] phase The phase metrology
[in] phaseCal The phase calibration data
Returns
DC Estimate current in amps (IQ19 format)
References phaseCalibrationData::current, phaseParams::current, currentParams::I_dc_estimate, currentSensorCalibrationData::IscaleFactor, and phaseMetrology::params.
Referenced by Metrology_calculatePhaseReadings().
calculateNeutralIdcEstimate()
_iq19 calculateNeutralIdcEstimate (neutralMetrology * neutral, currentSensorCalibrationData * neutralCal)
calculate neutral dc estimate current
Parameters
[in] neutral The neutral metrology
[in] neutralCal The neutral calibration data
Returns
Neutral DC Estimate current in amps (IQ19 format)
References neutralParams::I_dc_estimate, currentSensorCalibrationData::IscaleFactor, and neutralMetrology::params.
Referenced by Metrology_calculateNeutralReadings().
Metrology_getPhaseInitialVdcEstimate()
int16_t Metrology_getPhaseInitialVdcEstimate (metrologyData * workingData, PHASES ph)
Reads phase voltage dc estimate.
Parameters
[in] workingData The Metrology instance
[in] ph The phase number
Returns
Phase voltage dc estimate
References calInfo.
Metrology_getPhaseInitialIdcEstimate()
int16_t Metrology_getPhaseInitialIdcEstimate (metrologyData * workingData, PHASES ph)
Reads phase current dc estimate.
Parameters
[in] workingData The Metrology instance
[in] ph The phase number
Returns
Phase current dc estimate
References calInfo.
Metrology_getPhaseVacOffset()
int32_t Metrology_getPhaseVacOffset (metrologyData * workingData, PHASES ph)
Reads phase voltage AC offset.
Parameters
[in] workingData The Metrology instance
[in] ph The phase number
Returns
Phase voltage AC offset in milli volts
References calInfo.
Metrology_getPhaseIacOffset()
int32_t Metrology_getPhaseIacOffset (metrologyData * workingData, PHASES ph)
Reads phase current AC offset.
Parameters
[in] workingData The Metrology instance
[in] ph The phase number
Returns
Phase current AC offset in micro amps
References calInfo.
Metrology_getPhasePOffset()
int32_t Metrology_getPhasePOffset (metrologyData * workingData, PHASES ph)
Reads phase active power offset.
Parameters
[in] workingData The Metrology instance
[in] ph The phase number
Returns
Phase active power offset in milli watts
References calInfo.
Metrology_getPhaseQOffset()
int32_t Metrology_getPhaseQOffset (metrologyData * workingData, PHASES ph)
Reads phase reactive power offset.
Parameters
[in] workingData The Metrology instance
[in] ph The phase number
Returns
Phase reactive power offset in milli VAR
References calInfo.
Metrology_getPhaseFundPOffset()
int32_t Metrology_getPhaseFundPOffset (metrologyData * workingData, PHASES ph)
Reads phase fundamental active power offset.
Parameters
[in] workingData The Metrology instance
[in] ph The phase number
Returns
Phase fundamental active power offset in milli watts
References calInfo.
Metrology_getPhaseFundQOffset()
int32_t Metrology_getPhaseFundQOffset (metrologyData * workingData, PHASES ph)
Reads phase fundamental reactive power offset.
Parameters
[in] workingData The Metrology instance
[in] ph The phase number
Returns
Phase fundamental reactive power offset in milli VAR
References calInfo.
Metrology_getPhaseFundVOffset()
int32_t Metrology_getPhaseFundVOffset (metrologyData * workingData, PHASES ph)
Reads phase fundamental voltage offset.
Parameters
[in] workingData The Metrology instance
[in] ph The phase number
Returns
Phase fundamental voltage offset in milli volts
References calInfo.
Metrology_getPhaseFundIOffset()
int32_t Metrology_getPhaseFundIOffset (metrologyData * workingData, PHASES ph)
Reads phase fundamental current offset.
Parameters
[in] workingData The Metrology instance
[in] ph The phase number
Returns
Phase fundamental current offset in micro amps
References calInfo.
Metrology_getPhaseCorrectionParameters()
int16_t Metrology_getPhaseCorrectionParameters (metrologyData * workingData, PHASES ph)
Reads phase correction parameters.
Parameters
[in] workingData The Metrology instance
[in] ph The phase number
Returns
Phase correction parameters
References calInfo.
Metrology_getPhaseVRMSScaling()
uint32_t Metrology_getPhaseVRMSScaling (metrologyData * workingData, PHASES ph)
Reads voltage scale factor.
Parameters
[in] workingData The Metrology instance
[in] ph The phase number
Returns
Voltage scale factor
References calInfo.
Metrology_getPhaseIRMSScaling()
uint32_t Metrology_getPhaseIRMSScaling (metrologyData * workingData, PHASES ph)
Reads current scale factor.
Parameters
[in] workingData The Metrology instance
[in] ph The phase number
Returns
Current scale factor
References calInfo.
Metrology_getPhasePScaling()
uint32_t Metrology_getPhasePScaling (metrologyData * workingData, PHASES ph)
Reads power scale factor.
Parameters
[in] workingData The Metrology instance
[in] ph The phase number
Returns
Power scale factor
References calInfo.
Metrology_getNeutralInitialIdcEstimate()
int16_t Metrology_getNeutralInitialIdcEstimate (metrologyData * workingData)
Reads neutral current dc estimate.
Parameters
[in] workingData The Metrology instance
Returns
Neutral current dc estimate
References calInfo.
Metrology_getNeutralIacOffset()
int32_t Metrology_getNeutralIacOffset (metrologyData * workingData)
Reads neutral current ac offset.
Parameters
[in] workingData The Metrology instance
Returns
Neutral current ac offset
References calInfo.
Metrology_getNeutralPOffset()
int32_t Metrology_getNeutralPOffset (metrologyData * workingData)
Reads neutral active power offset.
Parameters
[in] workingData The Metrology instance
Returns
Neutral active power offset
References calInfo.
Metrology_getNeutralQOffset()
int32_t Metrology_getNeutralQOffset (metrologyData * workingData)
Reads neutral reactive power offset.
Parameters
[in] workingData The Metrology instance
Returns
Neutral reactive power offset
References calInfo.
Metrology_getNeutralFundPOffset()
int32_t Metrology_getNeutralFundPOffset (metrologyData * workingData)
Reads neutral fundamental active power offset.
Parameters
[in] workingData The Metrology instance
Returns
Neutral fundamental active power offset
References calInfo.
Metrology_getNeutralFundQOffset()
int32_t Metrology_getNeutralFundQOffset (metrologyData * workingData)
Reads neutral fundamental reactive power offset.
Parameters
[in] workingData The Metrology instance
Returns
Neutral fundamental reactive power offset
References calInfo.
Metrology_getNeutralFundVOffset()
int32_t Metrology_getNeutralFundVOffset (metrologyData * workingData)
Reads neutral fundamental voltage offset.
Parameters
[in] workingData The Metrology instance
Returns
Neutral fundamental voltage offset
Metrology_getNeutralFundIOffset()
int32_t Metrology_getNeutralFundIOffset (metrologyData * workingData)
Reads neutral fundamental current offset.
Parameters
[in] workingData The Metrology instance
Returns
Neutral fundamental current offset
References calInfo.
Metrology_getNeutralIRMSScaling()
uint32_t Metrology_getNeutralIRMSScaling (metrologyData * workingData)
Reads neutral current scale factor.
Parameters
[in] workingData The Metrology instance
Returns
Neutral current scale factor
References calInfo.
Metrology_getNeutralPScaling()
uint32_t Metrology_getNeutralPScaling (metrologyData * workingData)
Reads neutral power scale factor.
Parameters
[in] workingData The Metrology instance
Returns
Neutral power scale factor
References calInfo.
Metrology_getNeutralCorrectionParameters()
int16_t Metrology_getNeutralCorrectionParameters (metrologyData * workingData)
Reads neutral correction data.
Parameters
[in] workingData The Metrology instance
Returns
Neutral correction parameter
References calInfo.
Metrology_getCalibrationStatus()
int32_t Metrology_getCalibrationStatus (metrologyData * workingData)
Reads calibration status.
Parameters
[in] workingData The Metrology instance
Returns
Calibration status
References nvParam::calibrationStatus, infoMem::s, and infoMem::seg_a.
Metrology_setCalibrationStatus()
void Metrology_setCalibrationStatus (metrologyData * workingData, int32_t status)
Update calibration data.
Parameters
[in] workingData The Metrology instance
[in] status Calibration status
References nvParam::calibrationStatus, infoMem::s, and infoMem::seg_a.
Metrology_setPhaseVacOffset()
void Metrology_setPhaseVacOffset (metrologyData * workingData, int32_t data, PHASES ph)
Update Phase voltage offset.
Parameters
[in] workingData The metrology instance
[in] data The voltage offset in milli volts
[in] ph The phase number
References calibrationData::phases, and phaseCalibrationData::VacOffset.
Metrology_setPhaseFundVOffset()
void Metrology_setPhaseFundVOffset (metrologyData * workingData, int32_t data, PHASES ph)
Update Phase fundamental voltage offset.
Parameters
[in] workingData The metrology instance
[in] data The fundamental voltage offset
[in] ph The phase number
References calibrationData::phases, and phaseCalibrationData::VFundamentalAcOffset.
Metrology_setPhaseVdcEstimate()
void Metrology_setPhaseVdcEstimate (metrologyData * workingData, int16_t data, PHASES ph)
Update Phase voltage DC estimate.
Parameters
[in] workingData The metrology instance
[in] data The voltage DC estimate
[in] ph The phase number
References calibrationData::phases, and phaseCalibrationData::VinitialDcEstimate.
Metrology_setPhaseVRMSScaling()
void Metrology_setPhaseVRMSScaling (metrologyData * workingData, uint32_t data, PHASES ph)
Update Phase voltage scale factor.
Parameters
[in] workingData The metrology instance
[in] data The voltage scale factor
[in] ph The phase number
References calibrationData::phases, and phaseCalibrationData::VscaleFactor.
Metrology_setPhaseIacOffset()
void Metrology_setPhaseIacOffset (metrologyData * workingData, int32_t data, PHASES ph)
Update Phase current offset.
Parameters
[in] workingData The metrology instance
[in] data The current offset
[in] ph The phase number
References phaseCalibrationData::current, currentSensorCalibrationData::IacOffset, and calibrationData::phases.
Metrology_setPhaseFundIOffset()
void Metrology_setPhaseFundIOffset (metrologyData * workingData, int32_t data, PHASES ph)
Update Phase fundamental current offset.
Parameters
[in] workingData The metrology instance
[in] data The fundamental current offset
[in] ph The phase number
References phaseCalibrationData::current, currentSensorCalibrationData::IFAcOffset, and calibrationData::phases.
Metrology_setPhaseIdcEstimate()
void Metrology_setPhaseIdcEstimate (metrologyData * workingData, int16_t data, PHASES ph)
Update Phase current DC estimate.
Parameters
[in] workingData The metrology instance
[in] data The current DC estimate
[in] ph The phase number
References phaseCalibrationData::current, currentSensorCalibrationData::IinitialDcEstimate, and calibrationData::phases.
Metrology_setPhaseIRMSScaling()
void Metrology_setPhaseIRMSScaling (metrologyData * workingData, uint32_t data, PHASES ph)
Update Phase current scale factor.
Parameters
[in] workingData The metrology instance
[in] data The current scale factor
[in] ph The phase number
References phaseCalibrationData::current, currentSensorCalibrationData::IscaleFactor, and calibrationData::phases.
Metrology_setPhasePScaling()
void Metrology_setPhasePScaling (metrologyData * workingData, uint32_t data, PHASES ph)
Update Phase power scale factor.
Parameters
[in] workingData The metrology instance
[in] data The power scale factor
[in] ph The phase number
References phaseCalibrationData::current, calibrationData::phases, and currentSensorCalibrationData::PscaleFactor.
Metrology_setPhaseFundPOffset()
void Metrology_setPhaseFundPOffset (metrologyData * workingData, int32_t data, PHASES ph)
Update Phase fundamental active power offset.
Parameters
[in] workingData The metrology instance
[in] data The fundamental active power offset
[in] ph The phase number
References phaseCalibrationData::current, currentSensorCalibrationData::FActivePowerOffset, and calibrationData::phases.
Metrology_setPhaseFundQOffset()
void Metrology_setPhaseFundQOffset (metrologyData * workingData, int32_t data, PHASES ph)
Update Phase fundamental reactive power offset.
Parameters
[in] workingData The metrology instance
[in] data The fundamental reactive power offset
[in] ph The phase number
References phaseCalibrationData::current, currentSensorCalibrationData::FReactivePowerOffset, and calibrationData::phases.
Metrology_setPhasePOffset()
void Metrology_setPhasePOffset (metrologyData * workingData, int32_t data, PHASES ph)
Update Phase active power offset.
Parameters
[in] workingData The metrology instance
[in] data The active power offset
[in] ph The phase number
References currentSensorCalibrationData::activePowerOffset, phaseCalibrationData::current, and calibrationData::phases.
Metrology_setPhaseQOffset()
void Metrology_setPhaseQOffset (metrologyData * workingData, int32_t data, PHASES ph)
Update Phase reactive power offset.
Parameters
[in] workingData The metrology instance
[in] data The reactive power offset
[in] ph The phase number
References phaseCalibrationData::current, calibrationData::phases, and currentSensorCalibrationData::reactivePowerOffset.
Metrology_setPhaseOffset()
void Metrology_setPhaseOffset (metrologyData * workingData, int16_t data, PHASES ph)
Update Phase calibration offset.
Parameters
[in] workingData The metrology instance
[in] data The phase calibration offset
[in] ph The phase number
References phaseCalibrationData::current, currentSensorCalibrationData::phaseOffset, and calibrationData::phases.
Metrology_setNeutralIacOffset()
void Metrology_setNeutralIacOffset (metrologyData * workingData, int32_t data)
Update Neutral current offset.
Parameters
[in] workingData The metrology instance
[in] data The current offset
References currentSensorCalibrationData::IacOffset, and calibrationData::neutral.
Metrology_setNeutralFundIOffset()
void Metrology_setNeutralFundIOffset (metrologyData * workingData, int32_t data)
Update neutral fundamental current offset.
Parameters
[in] workingData The metrology instance
[in] data The fundamental current offset
References currentSensorCalibrationData::IFAcOffset, and calibrationData::neutral.
Metrology_setNeutralIdcEstimate()
void Metrology_setNeutralIdcEstimate (metrologyData * workingData, int16_t data)
Update neutral current dc estimate.
Parameters
[in] workingData The metrology instance
[in] data The current dc estimate
References currentSensorCalibrationData::IinitialDcEstimate, and calibrationData::neutral.
Metrology_setNeutralIRMSScaling()
void Metrology_setNeutralIRMSScaling (metrologyData * workingData, uint32_t data)
Update neutral current scale factor.
Parameters
[in] workingData The metrology instance
[in] data The current scale factor
References currentSensorCalibrationData::IscaleFactor, and calibrationData::neutral.
Metrology_setNeutralPScaling()
void Metrology_setNeutralPScaling (metrologyData * workingData, uint32_t data)
Update neutral power scale factor.
Parameters
[in] workingData The metrology instance
[in] data The power scale factor
References calibrationData::neutral, and currentSensorCalibrationData::PscaleFactor.
Metrology_setNeutralFundPOffset()
void Metrology_setNeutralFundPOffset (metrologyData * workingData, int32_t data)
Update neutral fundamental active power offset.
Parameters
[in] workingData The metrology instance
[in] data The fundamental active power offset
References currentSensorCalibrationData::FActivePowerOffset, and calibrationData::neutral.
Metrology_setNeutralFundQOffset()
void Metrology_setNeutralFundQOffset (metrologyData * workingData, int32_t data)
Update neutral fundamental reactive power offset.
Parameters
[in] workingData The metrology instance
[in] data The fundamental reactive power offset
References currentSensorCalibrationData::FReactivePowerOffset, and calibrationData::neutral.
Metrology_setNeutralPOffset()
void Metrology_setNeutralPOffset (metrologyData * workingData, int32_t data)
Update neutral active power offset.
Parameters
[in] workingData The metrology instance
[in] data The active power offset
References currentSensorCalibrationData::activePowerOffset, and calibrationData::neutral.
Metrology_setNeutralQOffset()
void Metrology_setNeutralQOffset (metrologyData * workingData, int32_t data)
Update neutral reactive power offset.
Parameters
[in] workingData The metrology instance
[in] data The reactive power offset
References calibrationData::neutral, and currentSensorCalibrationData::reactivePowerOffset.
Metrology_setNeutralOffset()
void Metrology_setNeutralOffset (metrologyData * workingData, int16_t data)
Update neutral calibration offset.
Parameters
[in] workingData The metrology instance
[in] data The neutral calibration offset
References calibrationData::neutral, and currentSensorCalibrationData::phaseOffset.
Metrology_clearCalibrationData()
void Metrology_clearCalibrationData (metrologyData * workingData)
Clear calibration data.
Parameters
[in] workingData The Metrology instance
References calibrationDefaults, HAL_clearMemoryBlock(), HAL_copyMemoryBlock(), and HAL_secureMemoryBlock().
Metrology_updateCalibrationData()
void Metrology_updateCalibrationData (metrologyData * workingData)
Update calibration data.
Parameters
[in] workingData The Metrology instance
References HAL_clearMemoryBlock(), HAL_copyMemoryBlock(), and HAL_secureMemoryBlock().
Metrology_ddsSinLookup()
int32_t Metrology_ddsSinLookup (uint32_t phase)
Metrology sin lookup.
Parameters
[in] phase The phase angle
Returns
sinvalue
References metrologyData::activePulse, HAL_writeGPIOPin(), METROLOGY_DDS_BIT_SHIFT, METROLOGY_DDS_STEPS, metrologyData::reactivePulse, and sineTable.
Referenced by Metrology_perSampleProcessing().
int64mpy()
__STATIC_INLINE int64_t int64mpy (int32_t Input1, int32_t Input2)
64 bit multiplication
Parameters
[in] Input1 first input
[in] Input2 second input
Returns
multiplication result
Referenced by Metrology_perSampleProcessing().
Metrology_calculatePhaseReadings()
void Metrology_calculatePhaseReadings (metrologyData * workingData, PHASES ph)
Calculate phase parameters.
Parameters
[in] workingData The metrology instance
[in] ph phase number
References accumulateActiveEnergy(), accumulateApparentEnergy(), accumulateFundamentalActiveEnergy(), accumulateFundamentalApparentEnergy(), accumulateFundamentalReactiveEnergy(), accumulateReactiveEnergy(), phaseReadings::activePower, phaseReadings::apparentPower, calculateActivePower(), calculateAngleVoltagetoCurrent(), calculateApparentPower(), calculateCurrentTHD(), calculateFundamentalActivePower(), calculateFundamentalApparentPower(), calculateFundamentalReactivePower(), calculateFundamentalRMSCurrent(), calculateFundamentalRMSVoltage(), calculateIdcEstimate(), calculateMainsfrequency(), calculateOverDeviation(), calculatePowerFactor(), calculateReactivePower(), calculateRMSCurrent(), calculateRMSVoltage(), calculateUnderDeviation(), calculateVdcEstimate(), calculateVoltageTHD(), calInfo, phaseParams::current, phaseReadings::currentTHD, phaseReadings::FActivePower, phaseReadings::FApparentPower, phaseReadings::FReactivePower, phaseReadings::frequency, phaseReadings::FRMSCurrent, phaseReadings::FRMSVoltage, currentParams::I_dc_estimate_logged, phaseReadings::overdeviation, phaseMetrology::params, metrologyData::phases, phaseReadings::powerFactor, phaseReadings::powerFactorAngle, phaseReadings::reactivePower, phaseMetrology::readings, phaseReadings::RMSCurrent, phaseReadings::RMSVoltage, phaseReadings::underdeviation, phaseParams::V_dc_estimate_logged, and phaseReadings::voltageTHD.
Metrology_calculateThreePhaseParameters()
void Metrology_calculateThreePhaseParameters (metrologyData * workingData)
Calculate three phase parameters.
Parameters
[in] workingData The metrology instance
References calculateAggregatePowerfactor(), calculateVectorCurrentSum(), totalParams::currentVectorSum, totalParams::powerFactor, readFundamentalLinetoLineVoltage(), readLinetoLineVoltage(), and metrologyData::totals.
Metrology_calculateTotalParameters()
void Metrology_calculateTotalParameters (metrologyData * workingData)
Calculate total parameters.
Parameters
[in] workingData The metrology instance
References TotalPowerReadings::activePower, TotalPowerReadings::apparentPower, calculateTotalActivePower(), calculateTotalApparentPower(), calculateTotalFundamentalActivePower(), calculateTotalFundamentalApparentPower(), calculateTotalFundamentalReactivePower(), calculateTotalReactivePower(), TotalPowerReadings::fundamentalActivePower, TotalPowerReadings::fundamentalApparentPower, TotalPowerReadings::fundamentalReactivePower, TotalPowerReadings::reactivePower, totalParams::readings, and metrologyData::totals.
Metrology_calculateNeutralReadings()
void Metrology_calculateNeutralReadings (metrologyData * workingData)
Calculate neutral parameters.
Parameters
[in] workingData The metrology instance
References calculateNeutralIdcEstimate(), calculateNeutralRMSCurrent(), calInfo, neutralParams::I_dc_estimate_logged, metrologyData::neutral, neutralMetrology::params, neutralMetrology::readings, and neutralReadings::RMSCurrent.
Metrology_sagSwellDetection()
void Metrology_sagSwellDetection (metrologyData * workingData, PHASES ph)
Sag Swell Detection.
Parameters
[in] workingData The metrology instance
[in] ph phase number
References checkSagSwellEvents().
Metrology_getRMSVoltage()
int32_t Metrology_getRMSVoltage (metrologyData * workingData, PHASES ph)
Read RMS Voltage.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
RMS voltage in milli volts (int32_t)
References metrologyData::phases, phaseMetrology::readings, and phaseReadings::RMSVoltage.
Metrology_getRMSCurrent()
int32_t Metrology_getRMSCurrent (metrologyData * workingData, PHASES ph)
Read RMS Current.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
RMS Current in micro ampere (int32_t)
References METROLOGY_IQ19_TO_MICROAMPS, metrologyData::phases, phaseMetrology::readings, and phaseReadings::RMSCurrent.
Metrology_getActivePower()
int32_t Metrology_getActivePower (metrologyData * workingData, PHASES ph)
Read Active Power.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Active Power in milli watts (int32_t)
References phaseReadings::activePower, METROLOGY_IQ13_TO_MILLIWATTS, metrologyData::phases, and phaseMetrology::readings.
Metrology_getReactivePower()
int32_t Metrology_getReactivePower (metrologyData * workingData, PHASES ph)
Read Reactive Power.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Reactive Power in milli VAR (int32_t)
References METROLOGY_IQ13_TO_MILLIWATTS, metrologyData::phases, phaseReadings::reactivePower, and phaseMetrology::readings.
Metrology_getApparentPower()
int32_t Metrology_getApparentPower (metrologyData * workingData, PHASES ph)
Read Apparent Power.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Apparent Power in milli VA (int32_t)
References phaseReadings::apparentPower, METROLOGY_IQ13_TO_MILLIWATTS, metrologyData::phases, and phaseMetrology::readings.
Metrology_getFundamentalRMSVoltage()
int32_t Metrology_getFundamentalRMSVoltage (metrologyData * workingData, PHASES ph)
Read Fundamental RMS Voltage.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Fundamental RMS Voltage in milli volts (int32_t)
References phaseReadings::FRMSVoltage, metrologyData::phases, and phaseMetrology::readings.
Metrology_getFundamentalRMSCurrent()
int32_t Metrology_getFundamentalRMSCurrent (metrologyData * workingData, PHASES ph)
Read Fundamental RMS Current.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Fundamental RMS Current in micro ampere (int32_t)
References phaseReadings::FRMSCurrent, METROLOGY_IQ19_TO_MICROAMPS, metrologyData::phases, and phaseMetrology::readings.
Metrology_getFundamentalActivePower()
int32_t Metrology_getFundamentalActivePower (metrologyData * workingData, PHASES ph)
Read Fundamental Active Power.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Fundamental Active Power in milli watts (int32_t)
References phaseReadings::FActivePower, METROLOGY_IQ13_TO_MILLIWATTS, metrologyData::phases, and phaseMetrology::readings.
Metrology_getFundamentalReactivePower()
int32_t Metrology_getFundamentalReactivePower (metrologyData * workingData, PHASES ph)
Read Fundamental Reactive Power.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Fundamental Reactive Power in milli VAR (int32_t)
References phaseReadings::FReactivePower, METROLOGY_IQ13_TO_MILLIWATTS, metrologyData::phases, and phaseMetrology::readings.
Metrology_getFundamentalApparentPower()
int32_t Metrology_getFundamentalApparentPower (metrologyData * workingData, PHASES ph)
Read Fundamental Apparent Power.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Fundamental Apparent Power in milli VA (int32_t)
References phaseReadings::FApparentPower, METROLOGY_IQ13_TO_MILLIWATTS, metrologyData::phases, and phaseMetrology::readings.
Metrology_getPowerFactor()
int16_t Metrology_getPowerFactor (metrologyData * workingData, PHASES ph)
Read phase power factor.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Power factor in steps of 0.0001 (int16_t)
References metrologyData::phases, phaseReadings::powerFactor, and phaseMetrology::readings.
Metrology_getAngleVoltagetoCurrent()
int16_t Metrology_getAngleVoltagetoCurrent (metrologyData * workingData, PHASES ph)
Read phase power factor angle.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Power factor angle in per units (int16_t) 0x0000 corresponds to 0 degrees 0x7FFF corresponds to 179.99 degrees 0x8000 corresponds to -180 degrees
Conversion inside GUI angle in degrees = angle * 180 / 2^15
References metrologyData::phases, phaseReadings::powerFactorAngle, and phaseMetrology::readings.
Metrology_getOverDeviation()
int16_t Metrology_getOverDeviation (metrologyData * workingData, PHASES ph)
Read voltage over deviation.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
voltage over deviation in steps of 0.01% (int16_t)
References phaseReadings::overdeviation, metrologyData::phases, and phaseMetrology::readings.
Metrology_getUnderDeviation()
int16_t Metrology_getUnderDeviation (metrologyData * workingData, PHASES ph)
Read voltage under deviation.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
voltage under deviation in steps of 0.01% (int16_t)
References metrologyData::phases, phaseMetrology::readings, and phaseReadings::underdeviation.
Metrology_getVoltageTHD()
int16_t Metrology_getVoltageTHD (metrologyData * workingData, PHASES ph)
Read voltage THD.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
voltage THD in steps of 0.01% (int16_t)
References metrologyData::phases, phaseMetrology::readings, and phaseReadings::voltageTHD.
Metrology_getCurrentTHD()
int16_t Metrology_getCurrentTHD (metrologyData * workingData, PHASES ph)
Read current THD.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
current THD in steps of 0.01% (int16_t)
References phaseReadings::currentTHD, metrologyData::phases, and phaseMetrology::readings.
Metrology_getMainsFrequency()
int16_t Metrology_getMainsFrequency (metrologyData * workingData, PHASES ph)
Read mains frequency.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Mains frequency in steps of 0.01 (int16_t)
References phaseReadings::frequency, metrologyData::phases, and phaseMetrology::readings.
Metrology_getMaxSwellValue()
int32_t Metrology_getMaxSwellValue (metrologyData * workingData, PHASES ph)
Read maximum swell voltage.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Maximum swell voltage in milli volts (int32_t)
References phaseMetrology::params, metrologyData::phases, and phaseParams::swellValue.
Metrology_getMinSagValue()
int32_t Metrology_getMinSagValue (metrologyData * workingData, PHASES ph)
Read minimum sag voltage.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Minimum sag voltage in milli volts (int32_t)
References phaseMetrology::params, metrologyData::phases, and phaseParams::sagValue.
Metrology_getSagEvents()
uint16_t Metrology_getSagEvents (metrologyData * workingData, PHASES ph)
Read number of sag events.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Number of sag events
References phaseMetrology::params, metrologyData::phases, and phaseParams::sagEvents.
Metrology_getSagDuration()
uint32_t Metrology_getSagDuration (metrologyData * workingData, PHASES ph)
Read Sag duration.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Sag duration
References phaseMetrology::params, metrologyData::phases, and phaseParams::sagDuration.
Metrology_getSwellEvents()
uint16_t Metrology_getSwellEvents (metrologyData * workingData, PHASES ph)
Read number of swell events.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Number of swell events
References phaseMetrology::params, metrologyData::phases, and phaseParams::swellEvents.
Metrology_getSwellDuration()
uint32_t Metrology_getSwellDuration (metrologyData * workingData, PHASES ph)
Read swell duration.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Swell duration
References phaseMetrology::params, metrologyData::phases, and phaseParams::swellDuration.
Metrology_getInterruptionEvents()
uint16_t Metrology_getInterruptionEvents (metrologyData * workingData, PHASES ph)
Read number of interruption events.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Number of interruption events
References phaseParams::interruptionEvents, phaseMetrology::params, and metrologyData::phases.
Metrology_getInterruptionDuration()
uint32_t Metrology_getInterruptionDuration (metrologyData * workingData, PHASES ph)
Read interruption duration.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
interruption duration
References phaseParams::interruptionDuration, phaseMetrology::params, and metrologyData::phases.
Metrology_getTotalActivePower()
int32_t Metrology_getTotalActivePower (metrologyData * workingData)
Read total active power.
Parameters
[in] workingData The metrology instance
Returns
Total active power in milli watts (int32_t)
References TotalPowerReadings::activePower, METROLOGY_IQ13_TO_MILLIWATTS, totalParams::readings, and metrologyData::totals.
Metrology_getTotalReactivePower()
int32_t Metrology_getTotalReactivePower (metrologyData * workingData)
Read total reactive power.
Parameters
[in] workingData The metrology instance
Returns
Total reactive power in milli VAR (int32_t)
References METROLOGY_IQ13_TO_MILLIWATTS, TotalPowerReadings::reactivePower, totalParams::readings, and metrologyData::totals.
Metrology_getTotalApparentPower()
int32_t Metrology_getTotalApparentPower (metrologyData * workingData)
Read total apparent power.
Parameters
[in] workingData The metrology instance
Returns
Total apparent power in milli VA (int32_t)
References TotalPowerReadings::apparentPower, METROLOGY_IQ13_TO_MILLIWATTS, totalParams::readings, and metrologyData::totals.
Metrology_getTotalFundamentalActivePower()
int32_t Metrology_getTotalFundamentalActivePower (metrologyData * workingData)
Read total fundamental active power.
Parameters
[in] workingData The metrology instance
Returns
Total fundamental active power in milli watts (int32_t)
References TotalPowerReadings::fundamentalActivePower, METROLOGY_IQ13_TO_MILLIWATTS, totalParams::readings, and metrologyData::totals.
Metrology_getTotalFundamentalReactivePower()
int32_t Metrology_getTotalFundamentalReactivePower (metrologyData * workingData)
Read total fundamental reactive power.
Parameters
[in] workingData The metrology instance
Returns
Total fundamental reactive power in milli VAR (int32_t)
References TotalPowerReadings::fundamentalReactivePower, METROLOGY_IQ13_TO_MILLIWATTS, totalParams::readings, and metrologyData::totals.
Metrology_getTotalFundamentalApparentPower()
int32_t Metrology_getTotalFundamentalApparentPower (metrologyData * workingData)
Read total fundamental apparent power.
Parameters
[in] workingData The metrology instance
Returns
Total fundamental apparent power in milli VA (int32_t)
References TotalPowerReadings::fundamentalApparentPower, METROLOGY_IQ13_TO_MILLIWATTS, totalParams::readings, and metrologyData::totals.
Metrology_getActiveEnergyImported()
uint64_t Metrology_getActiveEnergyImported (metrologyData * workingData, PHASES ph)
Read active energy imported.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Active energy imported in 100milli watt-hr (uint64_t)
References phaseEnergy::activeEnergyImported, energyIntegrator::energy, phaseMetrology::energy, and metrologyData::phases.
Metrology_getActiveEnergyExported()
uint64_t Metrology_getActiveEnergyExported (metrologyData * workingData, PHASES ph)
Read active energy exported.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Active energy exported in 100milli watt-hr (uint64_t)
References phaseEnergy::activeEnergyExported, energyIntegrator::energy, phaseMetrology::energy, and metrologyData::phases.
Metrology_getFundamentalActiveEnergyImported()
uint64_t Metrology_getFundamentalActiveEnergyImported (metrologyData * workingData, PHASES ph)
Read fundamental active energy imported.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Fundamental active energy imported in 100milli watt-hr (uint64_t)
References energyIntegrator::energy, phaseMetrology::energy, phaseEnergy::fundamentalActiveEnergyImported, and metrologyData::phases.
Metrology_getFundamentalActiveEnergyExported()
uint64_t Metrology_getFundamentalActiveEnergyExported (metrologyData * workingData, PHASES ph)
Read fundamental active energy exported.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Fundamental active energy exported in 100milli watt-hr (uint64_t)
References energyIntegrator::energy, phaseMetrology::energy, phaseEnergy::fundamentalActiveEnergyExported, and metrologyData::phases.
Metrology_getReactiveEnergyFirstQuadrant()
uint64_t Metrology_getReactiveEnergyFirstQuadrant (metrologyData * workingData, PHASES ph)
Read reactive energy frist quadrant.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Reactive energy frist quadrant in 100milli VAR-hr (uint64_t)
References energyIntegrator::energy, phaseMetrology::energy, metrologyData::phases, and phaseEnergy::reactiveEnergyQuardrantI.
Metrology_getReactiveEnergySecondQuadrant()
uint64_t Metrology_getReactiveEnergySecondQuadrant (metrologyData * workingData, PHASES ph)
Read reactive energy second quadrant.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Reactive energy second quadrant in 100milli VAR-hr (uint64_t)
References energyIntegrator::energy, phaseMetrology::energy, metrologyData::phases, and phaseEnergy::reactiveEnergyQuardrantII.
Metrology_getReactiveEnergyThirdQuadrant()
uint64_t Metrology_getReactiveEnergyThirdQuadrant (metrologyData * workingData, PHASES ph)
Read reactive energy third quadrant.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Reactive energy third quadrant in 100milli VAR-hr (uint64_t)
References energyIntegrator::energy, phaseMetrology::energy, metrologyData::phases, and phaseEnergy::reactiveEnergyQuardrantIII.
Metrology_getReactiveEnergyFourthQuadrant()
uint64_t Metrology_getReactiveEnergyFourthQuadrant (metrologyData * workingData, PHASES ph)
Read reactive energy fourth quadrant.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Reactive energy fourth quadrant in 100milli VAR-hr (uint64_t)
References energyIntegrator::energy, phaseMetrology::energy, metrologyData::phases, and phaseEnergy::reactiveEnergyQuardrantIV.
Metrology_getFundamentalReactiveEnergyFirstQuadrant()
uint64_t Metrology_getFundamentalReactiveEnergyFirstQuadrant (metrologyData * workingData, PHASES ph)
Read fundamental reactive energy frist quadrant.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Fundamental reactive energy frist quadrant in 100milli VAR-hr (uint64_t)
References energyIntegrator::energy, phaseMetrology::energy, phaseEnergy::fundamentalReactiveEnergyQuardrantI, and metrologyData::phases.
Metrology_getFundamentalReactiveEnergySecondQuadrant()
uint64_t Metrology_getFundamentalReactiveEnergySecondQuadrant (metrologyData * workingData, PHASES ph)
Read fundamental reactive energy second quadrant.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Fundamental reactive energy second quadrant in 100milli VAR-hr (uint64_t)
References energyIntegrator::energy, phaseMetrology::energy, phaseEnergy::fundamentalReactiveEnergyQuardrantII, and metrologyData::phases.
Metrology_getFundamentalReactiveEnergyThirdQuadrant()
uint64_t Metrology_getFundamentalReactiveEnergyThirdQuadrant (metrologyData * workingData, PHASES ph)
Read fundamental reactive energy third quadrant.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Fundamental reactive energy third quadrant in 100milli VAR-hr (uint64_t)
References energyIntegrator::energy, phaseMetrology::energy, phaseEnergy::fundamentalReactiveEnergyQuardrantIII, and metrologyData::phases.
Metrology_getFundamentalReactiveEnergyFourthQuadrant()
uint64_t Metrology_getFundamentalReactiveEnergyFourthQuadrant (metrologyData * workingData, PHASES ph)
Read fundamental reactive energy fourth quadrant.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Fundamental reactive energy fourth quadrant in 100milli VAR-hr (uint64_t)
References energyIntegrator::energy, phaseMetrology::energy, phaseEnergy::fundamentalReactiveEnergyQuardrantIV, and metrologyData::phases.
Metrology_getApparentEnergyImported()
uint64_t Metrology_getApparentEnergyImported (metrologyData * workingData, PHASES ph)
Read apparent energy imported.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Apparent energy imported in 100milli VA-hr (uint64_t)
References phaseEnergy::appparentEnergyImported, energyIntegrator::energy, phaseMetrology::energy, and metrologyData::phases.
Metrology_getApparentEnergyExported()
uint64_t Metrology_getApparentEnergyExported (metrologyData * workingData, PHASES ph)
Read apparent energy exported.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Apparent energy exported in 100milli VA-hr (uint64_t)
References phaseEnergy::appparentEnergyExported, energyIntegrator::energy, phaseMetrology::energy, and metrologyData::phases.
Metrology_getFundamentalApparentEnergyImported()
uint64_t Metrology_getFundamentalApparentEnergyImported (metrologyData * workingData, PHASES ph)
Read fundamental apparent energy imported.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Fundamental apparent energy imported in 100milli VA-hr (uint64_t)
References energyIntegrator::energy, phaseMetrology::energy, phaseEnergy::fundamentalAppparentEnergyImported, and metrologyData::phases.
Metrology_getFundamentalApparentEnergyExported()
uint64_t Metrology_getFundamentalApparentEnergyExported (metrologyData * workingData, PHASES ph)
Read fundamental apparent energy exported.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Fundamental apparent energy exported in 100milli VA-hr (uint64_t)
References energyIntegrator::energy, phaseMetrology::energy, phaseEnergy::fundamentalAppparentEnergyExported, and metrologyData::phases.
Metrology_getVdcEstimate()
_iq8 Metrology_getVdcEstimate (metrologyData * workingData, PHASES ph)
Read DC voltage estimate.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
DC voltage estimate in volts (IQ8 format)
References phaseMetrology::params, metrologyData::phases, and phaseParams::V_dc_estimate_logged.
Metrology_getIdcEstimate()
_iq8 Metrology_getIdcEstimate (metrologyData * workingData, PHASES ph)
Read DC current estimate.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
DC current estimate in amps (IQ8 format)
References phaseParams::current, currentParams::I_dc_estimate_logged, phaseMetrology::params, and metrologyData::phases.
Metrology_getNeutralIdcEstimate()
_iq8 Metrology_getNeutralIdcEstimate (metrologyData * workingData)
Read Neutral DC current estimate.
Parameters
[in] workingData The metrology instance
Returns
Neutral DC current estimate in amps (IQ8 format)
References neutralParams::I_dc_estimate_logged, metrologyData::neutral, and neutralMetrology::params.
Metrology_getPhasetoPhaseAngle()
int16_t Metrology_getPhasetoPhaseAngle (metrologyData * workingData, PHASES ph)
Read Phase to phase angle.
Parameters
[in] workingData The metrology instance
[in] ph Phase number
Returns
Phase to Phase angle in per units (int16_t) 0x0000 corresponds to 0 degrees 0x7FFF corresponds to 179.99 degrees 0x8000 corresponds to -180 degrees
Conversion inside GUI angle in degrees = angle * 180 / 2^15
References metrologyData::phases, phaseReadings::phasetoPhaseAngle, and phaseMetrology::readings.
Metrology_getTotalActiveEnergyImported()
uint64_t Metrology_getTotalActiveEnergyImported (metrologyData * workingData)
Read total active energy imported.
Parameters
[in] workingData The metrology instance
Returns
Total active energy imported in 100milli watt-hr (uint64_t)
References phaseEnergy::activeEnergyImported, energyIntegrator::energy, totalParams::energy, and metrologyData::totals.
Metrology_getTotalActiveEnergyExported()
uint64_t Metrology_getTotalActiveEnergyExported (metrologyData * workingData)
Read total active energy exported.
Parameters
[in] workingData The metrology instance
Returns
Total active energy exported in 100milli watt-hr (uint64_t)
References phaseEnergy::activeEnergyExported, energyIntegrator::energy, totalParams::energy, and metrologyData::totals.
Metrology_getTotalFundamentalActiveEnergyImported()
uint64_t Metrology_getTotalFundamentalActiveEnergyImported (metrologyData * workingData)
Read total fundamental active energy imported.
Parameters
[in] workingData The metrology instance
Returns
Total fundamental active energy imported in 100milli watt-hr (uint64_t)
References energyIntegrator::energy, totalParams::energy, phaseEnergy::fundamentalActiveEnergyImported, and metrologyData::totals.
Metrology_getTotalFundamentalActiveEnergyExported()
uint64_t Metrology_getTotalFundamentalActiveEnergyExported (metrologyData * workingData)
Read total fundamental active energy exported.
Parameters
[in] workingData The metrology instance
Returns
Total fundamental active energy exported in 100milli watt-hr (uint64_t)
References energyIntegrator::energy, totalParams::energy, phaseEnergy::fundamentalActiveEnergyExported, and metrologyData::totals.
Metrology_getTotalReactiveEnergyFirstQuadrant()
uint64_t Metrology_getTotalReactiveEnergyFirstQuadrant (metrologyData * workingData)
Read total reactive energy in quadrant I.
Parameters
[in] workingData The metrology instance
Returns
Total reactive energy in quadrant I in 100milli VAR-hr (uint64_t)
References energyIntegrator::energy, totalParams::energy, phaseEnergy::reactiveEnergyQuardrantI, and metrologyData::totals.
Metrology_getTotalReactiveEnergySecondQuadrant()
uint64_t Metrology_getTotalReactiveEnergySecondQuadrant (metrologyData * workingData)
Read total reactive energy in quadrant II.
Parameters
[in] workingData The metrology instance
Returns
Total reactive energy in quadrant II in 100milli VAR-hr (uint64_t)
References energyIntegrator::energy, totalParams::energy, phaseEnergy::reactiveEnergyQuardrantII, and metrologyData::totals.
Metrology_getTotalReactiveEnergyThirdQuadrant()
uint64_t Metrology_getTotalReactiveEnergyThirdQuadrant (metrologyData * workingData)
Read total reactive energy in quadrant III.
Parameters
[in] workingData The metrology instance
Returns
Total reactive energy in quadrant III in 100milli VAR-hr (uint64_t)
References energyIntegrator::energy, totalParams::energy, phaseEnergy::reactiveEnergyQuardrantIII, and metrologyData::totals.
Metrology_getTotalReactiveEnergyFourthQuadrant()
uint64_t Metrology_getTotalReactiveEnergyFourthQuadrant (metrologyData * workingData)
Read total reactive energy in quadrant IV.
Parameters
[in] workingData The metrology instance
Returns
Total reactive energy in quadrant IV in 100milli VAR-hr (uint64_t)
References energyIntegrator::energy, totalParams::energy, phaseEnergy::reactiveEnergyQuardrantIV, and metrologyData::totals.
Metrology_getTotalApparentEnergyImported()
uint64_t Metrology_getTotalApparentEnergyImported (metrologyData * workingData)
Read total apparent energy imported.
Parameters
[in] workingData The metrology instance
Returns
Total apparent energy imported in 100milli VA-hr (uint64_t)
References phaseEnergy::appparentEnergyImported, energyIntegrator::energy, totalParams::energy, and metrologyData::totals.
Metrology_getTotalApparentEnergyExported()
uint64_t Metrology_getTotalApparentEnergyExported (metrologyData * workingData)
Read total apparent energy exported.
Parameters
[in] workingData The metrology instance
Returns
Total apparent energy exported in 100milli VA-hr (uint64_t)
References phaseEnergy::appparentEnergyExported, energyIntegrator::energy, totalParams::energy, and metrologyData::totals.
Metrology_getLinetoLineVoltagePhase0toPhase1()
int32_t Metrology_getLinetoLineVoltagePhase0toPhase1 (metrologyData * workingData)
Read line to line voltage phase 0 to phase 1.
Parameters
[in] workingData The metrology instance
Returns
Phase 0 to Phase 1 line to line voltage in milli volts (int32_t)
References metrologyData::LLReadings, and LLReadings::LLRMSVoltage_ab.
Metrology_getLinetoLineVoltagePhase1toPhase2()
int32_t Metrology_getLinetoLineVoltagePhase1toPhase2 (metrologyData * workingData)
Read line to line voltage phase 1 to phase 2.
Parameters
[in] workingData The metrology instance
Returns
Phase 1 to Phase 2 line to line voltage in milli volts (int32_t)
References metrologyData::LLReadings, and LLReadings::LLRMSVoltage_bc.
Metrology_getLinetoLineVoltagePhase2toPhase0()
int32_t Metrology_getLinetoLineVoltagePhase2toPhase0 (metrologyData * workingData)
Read line to line voltage phase 2 to phase 0.
Parameters
[in] workingData The metrology instance
Returns
Phase 2 to Phase 0 line to line voltage in milli volts (int32_t)
References metrologyData::LLReadings, and LLReadings::LLRMSVoltage_ca.
Metrology_getFundamentalLinetoLineVoltagePhase0toPhase1()
int32_t Metrology_getFundamentalLinetoLineVoltagePhase0toPhase1 (metrologyData * workingData)
Read fundamental line to line voltage phase 0 to phase 1.
Parameters
[in] workingData The metrology instance
Returns
Phase 0 to Phase 1 fundamental line to line voltage in milli volts (int32_t)
References LLReadings::FLLRMSVoltage_ab, and metrologyData::LLReadings.
Metrology_getFundamentalLinetoLineVoltagePhase1toPhase2()
int32_t Metrology_getFundamentalLinetoLineVoltagePhase1toPhase2 (metrologyData * workingData)
Read fundamental line to line voltage phase 1 to phase 2.
Parameters
[in] workingData The metrology instance
Returns
Phase 0 to Phase 1 fundamental line to line voltage in milli volts (int32_t)
References LLReadings::FLLRMSVoltage_bc, and metrologyData::LLReadings.
Metrology_getFundamentalLinetoLineVoltagePhase2toPhase0()
int32_t Metrology_getFundamentalLinetoLineVoltagePhase2toPhase0 (metrologyData * workingData)
Read fundamental line to line voltage phase 2 to phase0.
Parameters
[in] workingData The metrology instance
Returns
Phase 0 to Phase 1 fundamental line to line voltage in milli volts (int32_t)
References LLReadings::FLLRMSVoltage_ca, and metrologyData::LLReadings.
Metrology_getCurrentVectorSum()
int32_t Metrology_getCurrentVectorSum (metrologyData * workingData)
Read current vector sum.
Parameters
[in] workingData The metrology instance
Returns
current vector sum in micro ampere (int32_t)
References totalParams::currentVectorSum, METROLOGY_IQ19_TO_MICROAMPS, and metrologyData::totals.
Metrology_getRawActivePower()
int64_t Metrology_getRawActivePower (metrologyData * workingData, uint16_t * samples, PHASES ph)
Read raw active power.
Parameters
[in] workingData The metrology instance
[in] samples pointer to store number of samples
[in] ph The phase number
Returns
Raw active power
References currentDPSet::activePower, phaseParams::current, currentParams::dotProd, phaseMetrology::params, metrologyData::phases, and currentDPSet::sampleCount.
Metrology_getRawReactivePower()
int64_t Metrology_getRawReactivePower (metrologyData * workingData, uint16_t * samples, PHASES ph)
Read raw reactive power.
Parameters
[in] workingData The metrology instance
[in] samples pointer to store number of samples
[in] ph The phase number
Returns
Raw reactive power
References phaseParams::current, currentParams::dotProd, phaseMetrology::params, metrologyData::phases, currentDPSet::reactivePower, and currentDPSet::sampleCount.
Metrology_getNeutralRMSCurrent()
int32_t Metrology_getNeutralRMSCurrent (metrologyData * workingData)
Read Neutral RMS Current.
Parameters
[in] workingData The metrology instance
Returns
Neutral RMS Current in micro ampere in micro ampere (int32_t)
References METROLOGY_IQ19_TO_MICROAMPS, metrologyData::neutral, neutralMetrology::readings, and neutralReadings::RMSCurrent.
Metrology_init()
void Metrology_init (metrologyData * workingData)
Metrology Init.
Parameters
[in] workingData The metrology data
References Metrology_alignwithNVData(), Metrology_initializeCalibrationData(), and Metrology_initNVData().
Metrology_initNVData()
void Metrology_initNVData (metrologyData * workingData)
Metrology Init nv data.
Parameters
[in] workingData The metrology data
References calInfo, phaseCalibrationData::current, phaseParams::current, currentParams::currentEndStops, neutralParams::currentEndStops, mainsParams::cyclePeriod, ENDSTOP_HITS_FOR_OVERLOAD, currentParams::I_dc_estimate, neutralParams::I_dc_estimate, currentSensorCalibrationData::IinitialDcEstimate, currentSensorCalibrationData::IscaleFactor, MAX_PHASES, metrologyData::neutral, phaseMetrology::params, neutralMetrology::params, mainsParams::period, metrologyData::phases, phaseParams::V_dc_estimate, phaseCalibrationData::VinitialDcEstimate, phaseParams::voltageEndStops, phaseParams::voltagePeriod, and phaseCalibrationData::VscaleFactor.
Referenced by Metrology_init().
Metrology_alignwithNVData()
void Metrology_alignwithNVData (metrologyData * workingData)
Metrology Align with nv data.
Parameters
[in] workingData The metrology data
References calInfo, phaseCalibrationData::current, phaseParams::current, phaseParams::interruptionLevel, phaseParams::interruptionLevelHalf, MAINS_NOMINAL_VOLTAGE_IQ19, MAX_PHASES, Metrology_setPhaseCorrection(), METROLOGY_STATUS_PHASE_VOLTAGE_OK, metrologyData::metrologyState, MIN_SAG_VOLTAGE, metrologyData::neutral, OPERATING_MODE_NORMAL, metrologyData::operatingMode, phaseMetrology::params, neutralMetrology::params, mainsParams::period, currentParams::phaseCorrection, neutralParams::phaseCorrection, currentSensorCalibrationData::phaseOffset, metrologyData::phases, SAG_HYSTERESIS, SAG_SWELL_VOLTAGE_NORMAL, SAG_THRESHOLD, phaseParams::sagMinVoltage, phaseParams::sagSwellState, phaseParams::sagThresholdStart, phaseParams::sagThresholdStop, phaseParams::sagValue, SWELL_HYSTERESIS, SWELL_THRESHOLD, phaseParams::swellThresholdStart, phaseParams::swellThresholdStop, phaseParams::swellValue, phaseParams::voltagePeriod, and phaseCalibrationData::VscaleFactor.
Referenced by Metrology_init().
Metrology_setPhaseCorrection()
void Metrology_setPhaseCorrection (phaseCorrection * phCorr, int32_t correction)
Set phase Correction.
Parameters
[in] phCorr The phase correction data
[in] correction correction value
References phaseCorrection::firBeta, phaseCorrection::firGain, I_HISTORY_STEPS, phase_shift_fir_coeffs, PHASE_SHIFT_FIR_TABLE_ELEMENTS, and phaseCorrection::step.
Referenced by calculateMainsfrequency(), Metrology_alignWithCalibrationData(), and Metrology_alignwithNVData().
Metrology_alignWithCalibrationData()
void Metrology_alignWithCalibrationData (metrologyData * workingData)
Metrology Align with calibration data.
Parameters
[in] workingData The metrology data
References calInfo, phaseCalibrationData::current, phaseParams::current, MAX_PHASES, Metrology_setPhaseCorrection(), metrologyData::neutral, phaseMetrology::params, neutralMetrology::params, currentParams::phaseCorrection, neutralParams::phaseCorrection, currentSensorCalibrationData::phaseOffset, and metrologyData::phases.
Variable Documentation
calibrationDefaults
calibrationData calibrationDefaults
structure to store default calibration parameters
Default calibration data to store in flash.
Referenced by Metrology_clearCalibrationData().
Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale