MSPM0G511X Driver Library: Unified Communication Module (UNICOMM)
Unified Communication Module (UNICOMM)
Enumerations
enum DL_UNICOMM_IP_MODE_SEL {
DL_UNICOMM_UART = UNICOMM_IPMODE_SELECT_UART,
DL_UNICOMM_SPI = UNICOMM_IPMODE_SELECT_SPI,
DL_UNICOMM_I2C_CONTROLLER = UNICOMM_IPMODE_SELECT_I2C_CONTROLLER,
DL_UNICOMM_I2C_TARGET = UNICOMM_IPMODE_SELECT_I2C_PERIPHERAL
}
Functions
__STATIC_INLINE void DL_UNICOMM_enablePower (UNICOMM_Inst_Regs *unicomm)
Enables power on unicomm module.
__STATIC_INLINE void DL_UNICOMM_disablePower (UNICOMM_Inst_Regs *unicomm)
Disables power on unicomm module.
__STATIC_INLINE bool DL_UNICOMM_isPowerEnabled (UNICOMM_Inst_Regs *unicomm)
Returns if power on unicomm module.
__STATIC_INLINE void DL_UNICOMM_reset (UNICOMM_Inst_Regs *unicomm)
Resets unicomm peripheral.
__STATIC_INLINE bool DL_UNICOMM_isReset (UNICOMM_Inst_Regs *unicomm)
Returns if unicomm peripheral was reset.
__STATIC_INLINE void DL_UNICOMM_setIPMode (UNICOMM_Inst_Regs *unicomm, DL_UNICOMM_IP_MODE_SEL ipMode)
Configure the unicomm peripheral for specified ip mode.
__STATIC_INLINE DL_UNICOMM_IP_MODE_SEL DL_UNICOMM_getIPMode (UNICOMM_Inst_Regs *unicomm)
Returns ip mode the unicomm peripheral is configured to.
Detailed Description
Overview
The Unified Communication Module (UNICOMM) Driver Library allows full configuration of the UNICOMM module. UNICOMM is a highly flexible peripheral which can be configured as a UART, SPI, I2C Controller, or I2C Target function.
Enumeration Type Documentation
DL_UNICOMM_IP_MODE_SEL
enum DL_UNICOMM_IP_MODE_SEL
Enumerator
DL_UNICOMM_UART
Select UART functionality
DL_UNICOMM_SPI
Select SPI functionality
DL_UNICOMM_I2C_CONTROLLER
Select I2C functionality in controller mode
DL_UNICOMM_I2C_TARGET
Select I2C functionality in target mode
Function Documentation
DL_UNICOMM_enablePower()
__STATIC_INLINE void DL_UNICOMM_enablePower (UNICOMM_Inst_Regs * unicomm)
Enables power on unicomm module.
Parameters
unicomm Pointer to the register overlay for the peripheral
Referenced by DL_I2CC_enablePower(), DL_I2CT_enablePower(), DL_SPI_enablePower(), and DL_UART_enablePower().
DL_UNICOMM_disablePower()
__STATIC_INLINE void DL_UNICOMM_disablePower (UNICOMM_Inst_Regs * unicomm)
Disables power on unicomm module.
Parameters
unicomm Pointer to the register overlay for the peripheral
Referenced by DL_I2CC_disablePower(), DL_I2CT_disablePower(), DL_SPI_disablePower(), and DL_UART_disablePower().
DL_UNICOMM_isPowerEnabled()
__STATIC_INLINE bool DL_UNICOMM_isPowerEnabled (UNICOMM_Inst_Regs * unicomm)
Returns if power on unicomm module.
Parameters
unicomm Pointer to the register overlay for the peripheral
Returns
true if power is enabled
false if power is disabled
Referenced by DL_I2CC_isPowerEnabled(), DL_I2CT_isPowerEnabled(), DL_SPI_isPowerEnabled(), and DL_UART_isPowerEnabled().
DL_UNICOMM_reset()
__STATIC_INLINE void DL_UNICOMM_reset (UNICOMM_Inst_Regs * unicomm)
Resets unicomm peripheral.
Parameters
unicomm Pointer to the register overlay for the UNICOMM peripheral
Referenced by DL_I2CC_reset(), DL_I2CT_reset(), DL_SPI_reset(), and DL_UART_reset().
DL_UNICOMM_isReset()
__STATIC_INLINE bool DL_UNICOMM_isReset (UNICOMM_Inst_Regs * unicomm)
Returns if unicomm peripheral was reset.
Parameters
unicomm Pointer to the register overlay for the UNICOMM peripheral
Returns
true if peripheral was reset
false if peripheral wasn't reset
Referenced by DL_I2CC_isReset(), DL_I2CT_isReset(), DL_SPI_isReset(), and DL_UART_isReset().
DL_UNICOMM_setIPMode()
__STATIC_INLINE void DL_UNICOMM_setIPMode (UNICOMM_Inst_Regs * unicomm, DL_UNICOMM_IP_MODE_SEL ipMode)
Configure the unicomm peripheral for specified ip mode.
Parameters
unicomm Pointer to the register overlay for the UNICOMM peripheral
ipMode Specifies IP mode functionality. One of DL_UNICOMM_IP_MODE_SEL
Referenced by DL_I2CC_enablePower(), DL_I2CT_enablePower(), DL_SPI_enablePower(), and DL_UART_enablePower().
DL_UNICOMM_getIPMode()
__STATIC_INLINE DL_UNICOMM_IP_MODE_SEL DL_UNICOMM_getIPMode (UNICOMM_Inst_Regs * unicomm)
Returns ip mode the unicomm peripheral is configured to.
Parameters
unicomm Pointer to the register overlay for the UNICOMM peripheral
Returns
Configured IP mode selection
Return values
One of DL_UNICOMM_IP_MODE_SEL
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale