MSPM0G511X Driver Library: Unified Communication Module (UNICOMM) - Inter-Integrated Circuit Target (I2CT)
Unified Communication Module (UNICOMM) - Inter-Integrated Circuit Target (I2CT)
Modules
DL_I2CT_STATUS
DL_I2CT_INTERRUPT
DL_I2CT_DMA_INTERRUPT
Data Structures
struct DL_I2CT_ClockConfig
Configuration struct for DL_I2CT_setClockConfig.
Macros
#define DL_I2CT_TX_FIFO_COUNT_MAXIMUM ((uint32_t)UNICOMMI2CT_SYS_FENTRIES << 8)
I2CT number of bytes which could be put into the TX FIFO.
#define DL_I2CT_RX_FIFO_COUNT_MAXIMUM ((uint32_t)UNICOMMI2CT_SYS_FENTRIES)
I2CT number of bytes which could be put into the RX FIFO.
Enumerations
enum DL_I2CT_EVENT_ROUTE {
DL_I2CT_EVENT_ROUTE_1 = 0,
DL_I2CT_EVENT_ROUTE_2 = 12
}
enum DL_I2CT_CLOCK {
DL_I2CT_CLOCK_BUSCLK = UNICOMMI2CT_CLKSEL_BUSCLK_SEL_ENABLE,
DL_I2CT_CLOCK_MFCLK = UNICOMMI2CT_CLKSEL_MFCLK_SEL_ENABLE,
DL_I2CT_CLOCK_ASYNC_SYSCLK = UNICOMMI2CT_CLKSEL_ASYNC_SYSCLK_SEL_ENABLE,
DL_I2CT_CLOCK_ASYNC_HFCLK = UNICOMMI2CT_CLKSEL_ASYNC_HFCLK_SEL_ENABLE,
DL_I2CT_CLOCK_ASYNC_PLL = UNICOMMI2CT_CLKSEL_ASYNC_PLL_SEL_ENABLE
}
enum DL_I2CT_CLOCK_DIVIDE {
DL_I2CT_CLOCK_DIVIDE_1 = UNICOMMI2CT_CLKDIV_RATIO_DIV_BY_1,
DL_I2CT_CLOCK_DIVIDE_2 = UNICOMMI2CT_CLKDIV_RATIO_DIV_BY_2,
DL_I2CT_CLOCK_DIVIDE_3 = UNICOMMI2CT_CLKDIV_RATIO_DIV_BY_3,
DL_I2CT_CLOCK_DIVIDE_4 = UNICOMMI2CT_CLKDIV_RATIO_DIV_BY_4,
DL_I2CT_CLOCK_DIVIDE_5 = UNICOMMI2CT_CLKDIV_RATIO_DIV_BY_5,
DL_I2CT_CLOCK_DIVIDE_6 = UNICOMMI2CT_CLKDIV_RATIO_DIV_BY_6,
DL_I2CT_CLOCK_DIVIDE_7 = UNICOMMI2CT_CLKDIV_RATIO_DIV_BY_7,
DL_I2CT_CLOCK_DIVIDE_8 = UNICOMMI2CT_CLKDIV_RATIO_DIV_BY_8
}
enum DL_I2CT_ADDRESSING_MODE {
DL_I2CT_ADDRESSING_MODE_7_BIT = UNICOMMI2CT_OAR_MODE_MODE7,
DL_I2CT_ADDRESSING_MODE_10_BIT = UNICOMMI2CT_OAR_MODE_MODE10
}
enum DL_I2CT_PEC_STATUS {
DL_I2CT_PEC_STATUS_CHECKED = UNICOMMI2CT_PECSR_PECSTS_CHECK_SET,
DL_I2CT_PEC_STATUS_NOT_CHECKED = UNICOMMI2CT_PECSR_PECSTS_CHECK_CLEARED
}
enum DL_I2CT_PEC_CHECK_ERROR {
DL_I2CT_PEC_CHECK_ERROR_CLEARED = UNICOMMI2CT_PECSR_PECSTS_ERROR_CLEARED,
DL_I2CT_PEC_CHECK_ERROR_SET = UNICOMMI2CT_PECSR_PECSTS_ERROR_SET
}
enum DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH {
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH_DISABLED,
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_1,
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_2,
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_3,
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_4,
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_8,
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_16,
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_31
}
enum DL_I2CT_TX_FIFO_LEVEL {
DL_I2CT_TX_FIFO_LEVEL_3_4_EMPTY = UNICOMMI2CT_IFLS_TXIFLSEL_LVL_3_4,
DL_I2CT_TX_FIFO_LEVEL_1_2_EMPTY = UNICOMMI2CT_IFLS_TXIFLSEL_LVL_1_2,
DL_I2CT_TX_FIFO_LEVEL_1_4_EMPTY = UNICOMMI2CT_IFLS_TXIFLSEL_LVL_1_4,
DL_I2CT_TX_FIFO_LEVEL_ONE_ENTRY = UNICOMMI2CT_IFLS_TXIFLSEL_LVL_NOT_FULL,
DL_I2CT_TX_FIFO_LEVEL_EMPTY = UNICOMMI2CT_IFLS_TXIFLSEL_LVL_EMPTY,
DL_I2CT_TX_FIFO_LEVEL_ALMOST_EMPTY,
DL_I2CT_TX_FIFO_LEVEL_ALMOST_FULL
}
enum DL_I2CT_RX_FIFO_LEVEL {
DL_I2CT_RX_FIFO_LEVEL_3_4_FULL = UNICOMMI2CT_IFLS_RXIFLSEL_LVL_3_4,
DL_I2CT_RX_FIFO_LEVEL_1_2_FULL = UNICOMMI2CT_IFLS_RXIFLSEL_LVL_1_2,
DL_I2CT_RX_FIFO_LEVEL_1_4_FULL = UNICOMMI2CT_IFLS_RXIFLSEL_LVL_1_4,
DL_I2CT_RX_FIFO_LEVEL_ONE_ENTRY = UNICOMMI2CT_IFLS_RXIFLSEL_LVL_NOT_EMPTY,
DL_I2CT_RX_FIFO_LEVEL_FULL = UNICOMMI2CT_IFLS_RXIFLSEL_LVL_FULL,
DL_I2CT_RX_FIFO_LEVEL_ALMOST_FULL,
DL_I2CT_RX_FIFO_LEVEL_ALMOST_EMPTY
}
enum DL_I2CT_RESPONSE_OVERRIDE_VALUE {
DL_I2CT_RESPONSE_OVERRIDE_VALUE_ACK = UNICOMMI2CT_ACKCTL_ACKOVAL_DISABLE,
DL_I2CT_RESPONSE_OVERRIDE_VALUE_NACK = UNICOMMI2CT_ACKCTL_ACKOVAL_ENABLE
}
enum DL_I2CT_IIDX {
DL_I2CT_IIDX_NO_INT = UNICOMMI2CT_IIDX_STAT_NO_INTR,
DL_I2CT_IIDX_TIMEOUT_A = UNICOMMI2CT_IIDX_STAT_TIMEOUTA,
DL_I2CT_IIDX_TIMEOUT_B = UNICOMMI2CT_IIDX_STAT_TIMEOUTB,
DL_I2CT_IIDX_RX_DONE = UNICOMMI2CT_IIDX_STAT_RXDONEFG,
DL_I2CT_IIDX_TX_DONE = UNICOMMI2CT_IIDX_STAT_TXDONEFG,
DL_I2CT_IIDX_RXFIFO_TRIGGER = UNICOMMI2CT_IIDX_STAT_RXTRG,
DL_I2CT_IIDX_TXFIFO_TRIGGER = UNICOMMI2CT_IIDX_STAT_TXTRG,
DL_I2CT_IIDX_RXFIFO_FULL = UNICOMMI2CT_IIDX_STAT_RXFULL,
DL_I2CT_IIDX_TXFIFO_EMPTY = UNICOMMI2CT_IIDX_STAT_TXEMPTY,
DL_I2CT_IIDX_START = UNICOMMI2CT_IIDX_STAT_STARTFG,
DL_I2CT_IIDX_STOP = UNICOMMI2CT_IIDX_STAT_STOPFG,
DL_I2CT_IIDX_GENERAL_CALL = UNICOMMI2CT_IIDX_STAT_GENCALL,
DL_I2CT_IIDX_EVENT1_DMA_DONE = UNICOMMI2CT_IIDX_STAT_DMA_DONE_TX,
DL_I2CT_IIDX_EVENT2_DMA_DONE = UNICOMMI2CT_IIDX_STAT_DMA_DONE_RX,
DL_I2CT_IIDX_PREEMPT_INT_TX = UNICOMMI2CT_IIDX_STAT_DMA_PREIRQ_TX,
DL_I2CT_IIDX_PREEMPT_INT_RX = UNICOMMI2CT_IIDX_STAT_DMA_PREIRQ_RX,
DL_I2CT_IIDX_PEC_RX_ERROR = UNICOMMI2CT_IIDX_STAT_PEC_RX_ERR,
DL_I2CT_IIDX_TXFIFO_UNDERFLOW = UNICOMMI2CT_IIDX_STAT_TX_UNFL,
DL_I2CT_IIDX_RXFIFO_OVERFLOW = UNICOMMI2CT_IIDX_STAT_RX_OVFL,
DL_I2CT_IIDX_ARBITRATION_LOST = UNICOMMI2CT_IIDX_STAT_ARBLOSTFG
}
Functions
void DL_I2CT_setClockConfig (UNICOMM_Inst_Regs *unicomm, DL_I2CT_ClockConfig *config)
Configure I2CT source clock.
void DL_I2CT_getClockConfig (UNICOMM_Inst_Regs *unicomm, DL_I2CT_ClockConfig *config)
Get I2CT source clock configuration.
__STATIC_INLINE bool DL_I2CT_isTXFIFOFull (UNICOMM_Inst_Regs *unicomm)
Checks if TX FIFO is full.
__STATIC_INLINE bool DL_I2CT_isTXFIFOEmpty (UNICOMM_Inst_Regs *unicomm)
Checks if TX FIFO is empty.
__STATIC_INLINE bool DL_I2CT_isRXFIFOFull (UNICOMM_Inst_Regs *unicomm)
Checks if RX FIFO is full.
__STATIC_INLINE bool DL_I2CT_isRXFIFOEmpty (UNICOMM_Inst_Regs *unicomm)
Checks if RX FIFO is empty.
uint8_t DL_I2CT_fillTXFIFO (UNICOMM_Inst_Regs *unicomm, uint8_t *buffer, uint8_t count)
Fills the TX FIFO with data.
void DL_I2CT_flushTXFIFO (UNICOMM_Inst_Regs *unicomm)
Flushes/removes all elements in the TX FIFO.
void DL_I2CT_flushRXFIFO (UNICOMM_Inst_Regs *unicomm)
Flushes/removes all elements in the RX FIFO.
__STATIC_INLINE void DL_I2CT_stopFlushTXFIFO (UNICOMM_Inst_Regs *unicomm)
Stop TX FIFO flush.
__STATIC_INLINE void DL_I2CT_startFlushTXFIFO (UNICOMM_Inst_Regs *unicomm)
Start TX FIFO flush.
__STATIC_INLINE void DL_I2CT_stopFlushRXFIFO (UNICOMM_Inst_Regs *unicomm)
Stop RX FIFO flush.
__STATIC_INLINE void DL_I2CT_startFlushRXFIFO (UNICOMM_Inst_Regs *unicomm)
Start RX FIFO flush.
void DL_I2CT_transmitDataBlocking (UNICOMM_Inst_Regs *unicomm, uint8_t data)
Transmit data, waiting until transmit request.
bool DL_I2CT_transmitDataCheck (UNICOMM_Inst_Regs *unicomm, uint8_t data)
Transmit data.
uint8_t DL_I2CT_receiveDataBlocking (UNICOMM_Inst_Regs *unicomm)
Receive data, waiting until receive request.
bool DL_I2CT_receiveDataCheck (UNICOMM_Inst_Regs *unicomm, uint8_t *buffer)
Receive data.
__STATIC_INLINE void DL_I2CT_enablePower (UNICOMM_Inst_Regs *unicomm)
Enables power on UNICOMM I2C module.
__STATIC_INLINE void DL_I2CT_disablePower (UNICOMM_Inst_Regs *unicomm)
Disables power on UNICOMM I2C module.
__STATIC_INLINE bool DL_I2CT_isPowerEnabled (UNICOMM_Inst_Regs *unicomm)
Returns if power on UNICOMM I2C module.
__STATIC_INLINE void DL_I2CT_reset (UNICOMM_Inst_Regs *unicomm)
Resets UNICOMM I2C peripheral.
__STATIC_INLINE bool DL_I2CT_isReset (UNICOMM_Inst_Regs *unicomm)
Returns if UNICOMM I2C peripheral was reset.
__STATIC_INLINE void DL_I2CT_selectClockSource (UNICOMM_Inst_Regs *unicomm, DL_I2CT_CLOCK clockSource)
Set Clock Source.
__STATIC_INLINE void DL_I2CT_selectClockDivider (UNICOMM_Inst_Regs *unicomm, DL_I2CT_CLOCK_DIVIDE clockDivider)
Set Clock Divider.
__STATIC_INLINE DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH DL_I2CT_getDigitalGlitchFilterPulseWidth (UNICOMM_Inst_Regs *unicomm)
Get Digital Glitch Suppression Pulse Width.
__STATIC_INLINE void DL_I2CT_setDigitalGlitchFilterPulseWidth (UNICOMM_Inst_Regs *unicomm, DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH filterWidth)
Set Digital Glitch Suppression Pulse Width.
__STATIC_INLINE void DL_I2CT_disableAnalogGlitchFilter (UNICOMM_Inst_Regs *unicomm)
Disable Analog Glitch Suppression.
__STATIC_INLINE bool DL_I2CT_isAnalogGlitchFilterEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if analog glitch suppression is enabled.
__STATIC_INLINE void DL_I2CT_enableAnalogGlitchFilter (UNICOMM_Inst_Regs *unicomm)
Enable Analog Glitch Suppression.
__STATIC_INLINE void DL_I2CT_setOwnAddress (UNICOMM_Inst_Regs *unicomm, uint32_t addr)
Set own address.
__STATIC_INLINE uint32_t DL_I2CT_getOwnAddress (UNICOMM_Inst_Regs *unicomm)
Get own address.
__STATIC_INLINE void DL_I2CT_enableOwnAddress (UNICOMM_Inst_Regs *unicomm)
Enable own address.
__STATIC_INLINE void DL_I2CT_disableOwnAddress (UNICOMM_Inst_Regs *unicomm)
Disable own address.
__STATIC_INLINE bool DL_I2CT_isOwnAddressEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if own address is enabled.
__STATIC_INLINE void DL_I2CT_setAddressingMode (UNICOMM_Inst_Regs *unicomm, DL_I2CT_ADDRESSING_MODE mode)
Set addressing mode.
__STATIC_INLINE DL_I2CT_ADDRESSING_MODE DL_I2CT_getAddressingMode (UNICOMM_Inst_Regs *unicomm)
Get addressing mode.
__STATIC_INLINE uint32_t UNICOMMI2CT_getOwnAddressAlternate (UNICOMM_Inst_Regs *unicomm)
Get own address alternate.
__STATIC_INLINE void DL_I2CT_setOwnAddressAlternate (UNICOMM_Inst_Regs *unicomm, uint32_t addr)
Set own address alternate.
__STATIC_INLINE uint32_t DL_I2CT_getOwnAddressAlternateMask (UNICOMM_Inst_Regs *unicomm)
Get own address alternate mask.
__STATIC_INLINE void DL_I2CT_setOwnAddressAlternateMask (UNICOMM_Inst_Regs *unicomm, uint32_t addressMask)
Set own address alternate mask.
__STATIC_INLINE void DL_I2CT_disableOwnAddressAlternate (UNICOMM_Inst_Regs *unicomm)
Disable usage of own address alternate.
__STATIC_INLINE bool DL_I2CT_isOwnAddressAlternateEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if own address alternate is enabled.
__STATIC_INLINE void DL_I2CT_enableOwnAddressAlternate (UNICOMM_Inst_Regs *unicomm)
Enable usage of own address alternate.
__STATIC_INLINE uint32_t DL_I2CT_getAddressMatch (UNICOMM_Inst_Regs *unicomm)
Get the address for which address match happened.
__STATIC_INLINE void DL_I2CT_disableClockStretching (UNICOMM_Inst_Regs *unicomm)
Disable clock stretching.
__STATIC_INLINE bool DL_I2CT_isClockStretchingEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if clock stretching is enabled.
__STATIC_INLINE void DL_I2CT_enableClockStretching (UNICOMM_Inst_Regs *unicomm)
Enable clock stretching.
__STATIC_INLINE void DL_I2CT_disableTXEmptyOnTXRequest (UNICOMM_Inst_Regs *unicomm)
Disable TX empty interrupt on transmit request.
__STATIC_INLINE bool DL_I2CT_isTXEmptyOnTXRequestEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if TX empty interrupt on transmit request is enabled.
__STATIC_INLINE void DL_I2CT_enableTXEmptyOnTXRequest (UNICOMM_Inst_Regs *unicomm)
Enable TX empty interrupt on transmit request.
__STATIC_INLINE void DL_I2CT_disableTXTriggerInTXMode (UNICOMM_Inst_Regs *unicomm)
Disable TX trigger in TX mode.
__STATIC_INLINE bool DL_I2CT_isTXTriggerInTXModeEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if TX trigger in TX mode is enabled.
__STATIC_INLINE void DL_I2CT_enableTXTriggerInTXMode (UNICOMM_Inst_Regs *unicomm)
Enable TX trigger when is in TX mode.
__STATIC_INLINE void DL_I2CT_disableTXWaitWhenTXFIFOStale (UNICOMM_Inst_Regs *unicomm)
Disable TX transfer waits when stale data in TX FIFO.
__STATIC_INLINE bool DL_I2CT_isTXWaitWhenTXFIFOStaleEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if TX transfer waits when stale data in TX FIFO is enabled.
__STATIC_INLINE void DL_I2CT_enableTXWaitWhenTXFIFOStale (UNICOMM_Inst_Regs *unicomm)
Enable TX transfer waits when stale data in TX FIFO.
__STATIC_INLINE void DL_I2CT_disableRXFullOnRXRequest (UNICOMM_Inst_Regs *unicomm)
Disable RX full interrupt on receive request.
__STATIC_INLINE bool DL_I2CT_isRXFullOnRXRequestEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if RX full interrupt on receive request is enabled.
__STATIC_INLINE void DL_I2CT_enableRXFullOnRXRequest (UNICOMM_Inst_Regs *unicomm)
Enable RX full interrupt on receive request.
__STATIC_INLINE void DL_I2CT_disableDefaultHostAddress (UNICOMM_Inst_Regs *unicomm)
Disable SMBus/PMBus default host address of 000 1000b.
__STATIC_INLINE bool DL_I2CT_isDefaultHostAddressEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if SMBus/PMBus default host address of 000 1000b is enabled.
__STATIC_INLINE void DL_I2CT_enableDefaultHostAddress (UNICOMM_Inst_Regs *unicomm)
Enable SMBus/PMBus default host address of 000 1000b.
__STATIC_INLINE void DL_I2CT_disableAlertResponseAddress (UNICOMM_Inst_Regs *unicomm)
Disable SMBus/PMBus Alert response address (ARA) of 000 1100b.
__STATIC_INLINE bool DL_I2CT_isAlertResponseAddressEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if SMBus/PMBus Alert response address (ARA) of 000 1100b is enabled.
__STATIC_INLINE void DL_I2CT_enableAlertResponseAddress (UNICOMM_Inst_Regs *unicomm)
Enable SMBus/PMBus Alert response address (ARA) of 000 1100b.
__STATIC_INLINE void DL_I2CT_disableDefaultDeviceAddress (UNICOMM_Inst_Regs *unicomm)
Disable SMBus/PMBus default device address of 110 0001b.
__STATIC_INLINE bool DL_I2CT_isDefaultDeviceAddressEnabled (UNICOMM_Inst_Regs *unicomm)
Checks SMBus/PMBus default device address of 110 0001b is enabled.
__STATIC_INLINE void DL_I2CT_enableDefaultDeviceAddress (UNICOMM_Inst_Regs *unicomm)
Enable SMBus/PMBus default device address of 110 0001b.
__STATIC_INLINE void DL_I2CT_disableWakeup (UNICOMM_Inst_Regs *unicomm)
Disable wakeup.
__STATIC_INLINE bool DL_I2CT_isWakeupEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if wakeup is enabled.
__STATIC_INLINE void DL_I2CT_enableWakeup (UNICOMM_Inst_Regs *unicomm)
Enable wakeup.
__STATIC_INLINE void DL_I2CT_disable (UNICOMM_Inst_Regs *unicomm)
Disable target.
__STATIC_INLINE bool DL_I2CT_isEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if target is enabled.
__STATIC_INLINE void DL_I2CT_enable (UNICOMM_Inst_Regs *unicomm)
Enable target.
__STATIC_INLINE void DL_I2CT_disableGeneralCall (UNICOMM_Inst_Regs *unicomm)
Disable general call address of 000 0000b.
__STATIC_INLINE bool DL_I2CT_isGeneralCallEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if general call address of 000 0000b is enabled.
__STATIC_INLINE void DL_I2CT_enableGeneralCall (UNICOMM_Inst_Regs *unicomm)
Enable usage of general call address of 000 0000b.
__STATIC_INLINE uint32_t DL_I2CT_getStatus (UNICOMM_Inst_Regs *unicomm)
Get status of I2CT bus controller for target.
__STATIC_INLINE uint8_t DL_I2CT_receiveData (UNICOMM_Inst_Regs *unicomm)
Get byte of data from UNICOMMI2CT.
__STATIC_INLINE void DL_I2CT_transmitData (UNICOMM_Inst_Regs *unicomm, uint8_t data)
Set next byte to be transferred during the next transaction.
__STATIC_INLINE void DL_I2CT_disableACKOverride (UNICOMM_Inst_Regs *unicomm)
Disable ACK override.
__STATIC_INLINE bool DL_I2CT_isACKOverrideEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if ACK override is enabled.
__STATIC_INLINE void DL_I2CT_enableACKOverride (UNICOMM_Inst_Regs *unicomm)
Enable ACK override.
__STATIC_INLINE DL_I2CT_RESPONSE_OVERRIDE_VALUE DL_I2CT_getACKOverrideValue (UNICOMM_Inst_Regs *unicomm)
Get acknowledge override value.
__STATIC_INLINE void DL_I2CT_setACKOverrideValue (UNICOMM_Inst_Regs *unicomm, DL_I2CT_RESPONSE_OVERRIDE_VALUE value)
Set acknowledge override value.
__STATIC_INLINE void DL_I2CT_disableACKOverrideOnStart (UNICOMM_Inst_Regs *unicomm)
Disable ACK override on Start Condition.
__STATIC_INLINE bool DL_I2CT_isACKOverrideOnStartEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if ACK override on Start condition is enabled.
__STATIC_INLINE void DL_I2CT_enableACKOverrideOnStart (UNICOMM_Inst_Regs *unicomm)
Enable ACK override on Start condition.
__STATIC_INLINE void DL_I2CT_disableACKOverrideOnPECNext (UNICOMM_Inst_Regs *unicomm)
Disable ACK override when SMBus/PMBus PEC is next byte.
__STATIC_INLINE bool DL_I2CT_isACKOverrideOnPECNextEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if ACK override when SMBus/PMBus PEC is next byte is enabled.
__STATIC_INLINE void DL_I2CT_enableACKOverrideOnPECNext (UNICOMM_Inst_Regs *unicomm)
Enable ACK override when SMBus/PMBus PEC is next byte.
__STATIC_INLINE void DL_I2CT_disableACKOverrideOnPECDone (UNICOMM_Inst_Regs *unicomm)
Disable ACK override when SMBus/PMBus PEC is next byte.
__STATIC_INLINE bool DL_I2CT_isACKOverrideOnPECDoneEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if ACK override when SMBus/PMBus PEC is next byte is enabled.
__STATIC_INLINE void DL_I2CT_enableACKOverrideOnPECDone (UNICOMM_Inst_Regs *unicomm)
Enable ACK override when SMBus/PMBus PEC is done.
__STATIC_INLINE uint32_t DL_I2CT_getPECCountValue (UNICOMM_Inst_Regs *unicomm)
Get the SMBus/PMBus Packet Error Checking (PEC) count value.
__STATIC_INLINE void DL_I2CT_setPECCountValue (UNICOMM_Inst_Regs *unicomm, uint32_t count)
Set the SMBus/PMBus Packet Error Checking (PEC) count value.
__STATIC_INLINE void DL_I2CT_disablePEC (UNICOMM_Inst_Regs *unicomm)
Disable SMBus/PMBus Packet Error Checking (PEC)
__STATIC_INLINE bool DL_I2CT_isPECEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if SMBus/PMBus Packet Error Checking (PEC) is enabled.
__STATIC_INLINE void DL_I2CT_enablePEC (UNICOMM_Inst_Regs *unicomm)
Enable SMBus/PMBus Packet Error Checking (PEC)
__STATIC_INLINE uint32_t DL_I2CT_getCurrentPECCount (UNICOMM_Inst_Regs *unicomm)
Get the current SMBus/PMBus PEC byte count of the state machine.
__STATIC_INLINE DL_I2CT_PEC_STATUS DL_I2CT_getPECCheckedStatus (UNICOMM_Inst_Regs *unicomm)
Get status if SMBus/PMBus PEC was checked in last transaction.
__STATIC_INLINE DL_I2CT_PEC_CHECK_ERROR DL_I2CT_getPECCheckError (UNICOMM_Inst_Regs *unicomm)
Get status if SMBus/PMBus PEC had an error.
__STATIC_INLINE DL_I2CT_TX_FIFO_LEVEL DL_I2CT_getTXFIFOThreshold (UNICOMM_Inst_Regs *unicomm)
Get TX FIFO threshold level.
__STATIC_INLINE void DL_I2CT_setTXFIFOThreshold (UNICOMM_Inst_Regs *unicomm, DL_I2CT_TX_FIFO_LEVEL level)
Set TX FIFO threshold level.
__STATIC_INLINE DL_I2CT_RX_FIFO_LEVEL DL_I2CT_getRXFIFOThreshold (UNICOMM_Inst_Regs *unicomm)
Get RX FIFO threshold level.
__STATIC_INLINE void DL_I2CT_setRXFIFOThreshold (UNICOMM_Inst_Regs *unicomm, DL_I2CT_RX_FIFO_LEVEL level)
Set RX FIFO threshold level.
__STATIC_INLINE void DL_I2CT_enableInterrupt (UNICOMM_Inst_Regs *unicomm, uint32_t interruptMask)
Enable I2CT interrupts.
__STATIC_INLINE void DL_I2CT_disableInterrupt (UNICOMM_Inst_Regs *unicomm, uint32_t interruptMask)
Disable I2CT interrupts.
__STATIC_INLINE uint32_t DL_I2CT_getEnabledInterrupts (UNICOMM_Inst_Regs *unicomm, uint32_t interruptMask)
Check which I2CT interrupts are enabled.
__STATIC_INLINE uint32_t DL_I2CT_getEnabledInterruptStatus (UNICOMM_Inst_Regs *unicomm, uint32_t interruptMask)
Check interrupt flag of enabled I2CT interrupts.
__STATIC_INLINE uint32_t DL_I2CT_getRawInterruptStatus (UNICOMM_Inst_Regs *unicomm, uint32_t interruptMask)
Check interrupt flag of any I2CT interrupt.
__STATIC_INLINE DL_I2CT_IIDX DL_I2CT_getPendingInterrupt (UNICOMM_Inst_Regs *unicomm)
Get highest priority pending I2CT interrupt.
__STATIC_INLINE void DL_I2CT_clearInterruptStatus (UNICOMM_Inst_Regs *unicomm, uint32_t interruptMask)
Clear pending I2CT interrupts.
__STATIC_INLINE void DL_I2CT_enableDMAEvent (UNICOMM_Inst_Regs *unicomm, DL_I2CT_EVENT_ROUTE index, uint32_t interrupt)
Enables I2CT interrupt for triggering DMA events.
__STATIC_INLINE void DL_I2CT_disableDMAEvent (UNICOMM_Inst_Regs *unicomm, DL_I2CT_EVENT_ROUTE index, uint32_t interrupt)
Disables I2CT interrupt from triggering DMA events.
__STATIC_INLINE uint32_t DL_I2CT_getEnabledDMAEvents (UNICOMM_Inst_Regs *unicomm, DL_I2CT_EVENT_ROUTE index, uint32_t interruptMask)
Check which I2CT interrupt for DMA receive events is enabled.
__STATIC_INLINE uint32_t DL_I2CT_getEnabledDMAEventStatus (UNICOMM_Inst_Regs *unicomm, DL_I2CT_EVENT_ROUTE index, uint32_t interruptMask)
Check interrupt flag of enabled I2CT interrupt for DMA event.
__STATIC_INLINE uint32_t DL_I2CT_getRawDMAEventStatus (UNICOMM_Inst_Regs *unicomm, DL_I2CT_EVENT_ROUTE index, uint32_t interruptMask)
Check interrupt flag of any I2CT interrupt for DMA event.
__STATIC_INLINE uint32_t DL_I2CT_getTimeoutACount (UNICOMM_Inst_Regs *unicomm)
Get the Timeout Counter A value.
__STATIC_INLINE void DL_I2CT_setTimeoutACount (UNICOMM_Inst_Regs *unicomm, uint32_t count)
Set the Timeout Counter A value.
__STATIC_INLINE void DL_I2CT_disableTimeoutA (UNICOMM_Inst_Regs *unicomm)
Disable Timeout Counter A.
__STATIC_INLINE bool DL_I2CT_isTimeoutAEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if Timeout Counter A is enabled.
__STATIC_INLINE void DL_I2CT_enableTimeoutA (UNICOMM_Inst_Regs *unicomm)
Enable Timeout Counter A.
__STATIC_INLINE uint32_t DL_I2CT_getCurrentTimeoutACounter (UNICOMM_Inst_Regs *unicomm)
Get the current Timer Counter A value.
__STATIC_INLINE uint32_t DL_I2CT_getTimeoutBCount (UNICOMM_Inst_Regs *unicomm)
Get the Timeout Counter B value.
__STATIC_INLINE void DL_I2CT_setTimeoutBCount (UNICOMM_Inst_Regs *unicomm, uint32_t count)
Set the Timeout Counter B value.
__STATIC_INLINE void DL_I2CT_disableTimeoutB (UNICOMM_Inst_Regs *unicomm)
Disable Timeout Counter B.
__STATIC_INLINE bool DL_I2CT_isTimeoutBEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if Timeout Counter B is enabled.
__STATIC_INLINE void DL_I2CT_enableTimeoutB (UNICOMM_Inst_Regs *unicomm)
Enable Timeout Counter B.
__STATIC_INLINE uint32_t DL_I2CT_getCurrentTimeoutBCounter (UNICOMM_Inst_Regs *unicomm)
Get the current Timer Counter B value.
Detailed Description
Overview
Unified Communication Module Inter-Integrated Circuit Target Driver Library allows full configuration of the UNICOMM I2CT module.
This Inter-Integrated Circuit Target (I2CT) module provides a standardized interface to transfer data, as a target, between devices and other external devices with the I2C interface.
Macro Definition Documentation
DL_I2CT_TX_FIFO_COUNT_MAXIMUM
#define DL_I2CT_TX_FIFO_COUNT_MAXIMUM ((uint32_t)UNICOMMI2CT_SYS_FENTRIES << 8)
I2CT number of bytes which could be put into the TX FIFO.
This variable is device specific and is calculated using the system parameter UNICOMMI2CT_SYS_FENTRIES defined in each devices header file.
DL_I2CT_RX_FIFO_COUNT_MAXIMUM
#define DL_I2CT_RX_FIFO_COUNT_MAXIMUM ((uint32_t)UNICOMMI2CT_SYS_FENTRIES)
I2CT number of bytes which could be put into the RX FIFO.
This variable is device specific and is calculated using the system parameter UNICOMMI2CT_SYS_FENTRIES defined in each devices header file.
Enumeration Type Documentation
DL_I2CT_EVENT_ROUTE
enum DL_I2CT_EVENT_ROUTE
Enumerator
DL_I2CT_EVENT_ROUTE_1
I2CT event route 1
DL_I2CT_EVENT_ROUTE_2
I2CT event route 2
DL_I2CT_CLOCK
enum DL_I2CT_CLOCK
Enumerator
DL_I2CT_CLOCK_BUSCLK
BUSCLK enabled as I2CT clock source
DL_I2CT_CLOCK_MFCLK
MFCLK enabled as I2CT clock source
DL_I2CT_CLOCK_ASYNC_SYSCLK
Asynchronous SYSCLK enabled as I2CT clock source
DL_I2CT_CLOCK_ASYNC_HFCLK
Asynchronous HFCLK enabled as I2CT clock source
DL_I2CT_CLOCK_ASYNC_PLL
Asynchronous PLL enabled as I2CT clock source
DL_I2CT_CLOCK_DIVIDE
enum DL_I2CT_CLOCK_DIVIDE
Enumerator
DL_I2CT_CLOCK_DIVIDE_1
I2CT Clock Divided by 1
DL_I2CT_CLOCK_DIVIDE_2
I2CT Clock Divided by 2
DL_I2CT_CLOCK_DIVIDE_3
I2CT Clock Divided by 3
DL_I2CT_CLOCK_DIVIDE_4
I2CT Clock Divided by 4
DL_I2CT_CLOCK_DIVIDE_5
I2CT Clock Divided by 5
DL_I2CT_CLOCK_DIVIDE_6
I2CT Clock Divided by 6
DL_I2CT_CLOCK_DIVIDE_7
I2CT Clock Divided by 7
DL_I2CT_CLOCK_DIVIDE_8
I2CT Clock Divided by 8
DL_I2CT_ADDRESSING_MODE
enum DL_I2CT_ADDRESSING_MODE
Enumerator
DL_I2CT_ADDRESSING_MODE_7_BIT
Enable in 7-bit addressing mode
DL_I2CT_ADDRESSING_MODE_10_BIT
Enable in 10-bit addressing mode
DL_I2CT_PEC_STATUS
enum DL_I2CT_PEC_STATUS
Enumerator
DL_I2CT_PEC_STATUS_CHECKED
I2CT SMBus/PMBus PEC was checked in the transaction that occurred before the last Stop
DL_I2CT_PEC_STATUS_NOT_CHECKED
I2CT SMBus/PMBus PEC was not checked in the transaction that occurred before the last Stop
DL_I2CT_PEC_CHECK_ERROR
enum DL_I2CT_PEC_CHECK_ERROR
Enumerator
DL_I2CT_PEC_CHECK_ERROR_CLEARED
Indicates PEC check error did not occurr in the transaction that occurred before the last Stop
DL_I2CT_PEC_CHECK_ERROR_SET
Indicates PEC check error occurred in the transaction that occurred before the last Stop
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH
enum DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH
Enumerator
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH_DISABLED
Pulses filtering disabled.
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_1
Pulses shorter than 1 functional clock tick in length are filtered.
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_2
Pulses shorter than 2 functional clock ticks in length are filtered.
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_3
Pulses shorter than 3 functional clock ticks in length are filtered.
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_4
Pulses shorter than 4 functional clock ticks in length are filtered.
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_8
Pulses shorter than 8 functional clock ticks in length are filtered.
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_16
Pulses shorter than 16 functional clock ticks in length are filtered.
DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_31
Pulses shorter than 31 functional clock ticks in length are filtered.
DL_I2CT_TX_FIFO_LEVEL
enum DL_I2CT_TX_FIFO_LEVEL
Enumerator
DL_I2CT_TX_FIFO_LEVEL_3_4_EMPTY
Interrupt triggers when FIFO <= 3/4 empty
DL_I2CT_TX_FIFO_LEVEL_1_2_EMPTY
Interrupt triggers when FIFO <= 1/2 empty
DL_I2CT_TX_FIFO_LEVEL_1_4_EMPTY
Interrupt triggers when FIFO <= 1/4 empty
DL_I2CT_TX_FIFO_LEVEL_ONE_ENTRY
Interrupt triggers when FIFO is not full
DL_I2CT_TX_FIFO_LEVEL_EMPTY
Interrupt triggers when FIFO is empty
DL_I2CT_TX_FIFO_LEVEL_ALMOST_EMPTY
Interrupt triggers when FIFO is almost empty (FIFO <= 1)
DL_I2CT_TX_FIFO_LEVEL_ALMOST_FULL
Interrupt triggers when FIFO is almost full (FIFO >= (MAX_FIFO_LEN - 1))
DL_I2CT_RX_FIFO_LEVEL
enum DL_I2CT_RX_FIFO_LEVEL
Enumerator
DL_I2CT_RX_FIFO_LEVEL_3_4_FULL
Interrupt triggers when FIFO >= 3/4 full
DL_I2CT_RX_FIFO_LEVEL_1_2_FULL
Interrupt triggers when FIFO >= 1/2 full
DL_I2CT_RX_FIFO_LEVEL_1_4_FULL
Interrupt triggers when FIFO >= 1/4 full
DL_I2CT_RX_FIFO_LEVEL_ONE_ENTRY
Interrupt triggers when FIFO is not empty
DL_I2CT_RX_FIFO_LEVEL_FULL
Interrupt triggers when FIFO is full
DL_I2CT_RX_FIFO_LEVEL_ALMOST_FULL
Interrupt triggers when FIFO is almost full (FIFO >= (MAX_FIFO_LEN - 1))
DL_I2CT_RX_FIFO_LEVEL_ALMOST_EMPTY
Interrupt triggers when FIFO is almost empty (FIFO <= 1)
DL_I2CT_RESPONSE_OVERRIDE_VALUE
enum DL_I2CT_RESPONSE_OVERRIDE_VALUE
Enumerator
DL_I2CT_RESPONSE_OVERRIDE_VALUE_ACK
manual ACK for valid data or command.
DL_I2CT_RESPONSE_OVERRIDE_VALUE_NACK
manual NACK for invalid data or command.
DL_I2CT_IIDX
enum DL_I2CT_IIDX
Enumerator
DL_I2CT_IIDX_NO_INT
Interrupt index for I2CT if no interrupt is pending
DL_I2CT_IIDX_TIMEOUT_A
Interrupt index for I2CT Timeout A Event
DL_I2CT_IIDX_TIMEOUT_B
Interrupt index for I2CT Timeout B Event
DL_I2CT_IIDX_RX_DONE
Interrupt index for I2CT Receive Data
DL_I2CT_IIDX_TX_DONE
Interrupt index for I2CT Transmit Transaction completed
DL_I2CT_IIDX_RXFIFO_TRIGGER
Interrupt index for I2CT Receive FIFO Trigger
DL_I2CT_IIDX_TXFIFO_TRIGGER
Interrupt index for I2CT Transmit FIFO Trigger
DL_I2CT_IIDX_RXFIFO_FULL
Interrupt index for I2CT RX FIFO full
DL_I2CT_IIDX_TXFIFO_EMPTY
Interrupt index for I2CT TX FIFO empty. All data in Transmit FIFO shifted out and transmit goes into idle mode.
DL_I2CT_IIDX_START
Interrupt index for I2CT Start Condition detected
DL_I2CT_IIDX_STOP
Interrupt index for I2CT Stop Condition detected
DL_I2CT_IIDX_GENERAL_CALL
Interrupt index for I2CT General Call
DL_I2CT_IIDX_EVENT1_DMA_DONE
Interrupt index for I2CT Event 1 DMA Done
DL_I2CT_IIDX_EVENT2_DMA_DONE
Interrupt index for I2CT Event 2 DMA Done
DL_I2CT_IIDX_PREEMPT_INT_TX
Interrupt index for I2CT receive pre-emptive interrupt
DL_I2CT_IIDX_PREEMPT_INT_RX
Interrupt index for I2CT receive pre-emptive interrupt
DL_I2CT_IIDX_PEC_RX_ERROR
Interrupt index for I2CT SMBus/PMBus PEC Receive Error Event
DL_I2CT_IIDX_TXFIFO_UNDERFLOW
Interrupt index for I2CT TX FIFO underflow event
DL_I2CT_IIDX_RXFIFO_OVERFLOW
Interrupt index for I2CT RX FIFO overflow event
DL_I2CT_IIDX_ARBITRATION_LOST
Interrupt index for I2CT arbitration lost event
Function Documentation
DL_I2CT_setClockConfig()
void DL_I2CT_setClockConfig (UNICOMM_Inst_Regs * unicomm, DL_I2CT_ClockConfig * config)
Configure I2CT source clock.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] config Pointer to the clock configuration struct DL_I2CT_ClockConfig.
DL_I2CT_getClockConfig()
void DL_I2CT_getClockConfig (UNICOMM_Inst_Regs * unicomm, DL_I2CT_ClockConfig * config)
Get I2CT source clock configuration.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] config Pointer to the clock configuration struct DL_I2CT_ClockConfig.
DL_I2CT_isTXFIFOFull()
__STATIC_INLINE bool DL_I2CT_isTXFIFOFull (UNICOMM_Inst_Regs * unicomm)
Checks if TX FIFO is full.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If TX FIFO is full
Return values
true if TX FIFO is full
false if TX FIFO is not full
DL_I2CT_isTXFIFOEmpty()
__STATIC_INLINE bool DL_I2CT_isTXFIFOEmpty (UNICOMM_Inst_Regs * unicomm)
Checks if TX FIFO is empty.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If TX FIFO is empty
Return values
true if TX FIFO is empty
false if TX FIFO is not empty
DL_I2CT_isRXFIFOFull()
__STATIC_INLINE bool DL_I2CT_isRXFIFOFull (UNICOMM_Inst_Regs * unicomm)
Checks if RX FIFO is full.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If RX FIFO is full
Return values
true if RX FIFO is full
false if RX FIFO is not full
DL_I2CT_isRXFIFOEmpty()
__STATIC_INLINE bool DL_I2CT_isRXFIFOEmpty (UNICOMM_Inst_Regs * unicomm)
Checks if RX FIFO is empty.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If RX FIFO is empty
Return values
true if RX FIFO is empty
false if RX FIFO is not empty
References DL_I2CT_fillTXFIFO(), DL_I2CT_flushRXFIFO(), and DL_I2CT_flushTXFIFO().
DL_I2CT_fillTXFIFO()
uint8_t DL_I2CT_fillTXFIFO (UNICOMM_Inst_Regs * unicomm, uint8_t * buffer, uint8_t count)
Fills the TX FIFO with data.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] buffer Pointer to buffer of bytes
[in] count Number of bytes to fill TX FIFO from buffer
Returns
Number of bytes that were successfully written
Referenced by DL_I2CT_isRXFIFOEmpty().
DL_I2CT_flushTXFIFO()
void DL_I2CT_flushTXFIFO (UNICOMM_Inst_Regs * unicomm)
Flushes/removes all elements in the TX FIFO.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Referenced by DL_I2CT_isRXFIFOEmpty().
DL_I2CT_flushRXFIFO()
void DL_I2CT_flushRXFIFO (UNICOMM_Inst_Regs * unicomm)
Flushes/removes all elements in the RX FIFO.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Referenced by DL_I2CT_isRXFIFOEmpty().
DL_I2CT_stopFlushTXFIFO()
__STATIC_INLINE void DL_I2CT_stopFlushTXFIFO (UNICOMM_Inst_Regs * unicomm)
Stop TX FIFO flush.
Before stopping the flush, check if DL_I2CT_isTXFIFOEmpty, indicating flush is complete.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_startFlushTXFIFO()
__STATIC_INLINE void DL_I2CT_startFlushTXFIFO (UNICOMM_Inst_Regs * unicomm)
Start TX FIFO flush.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_stopFlushRXFIFO()
__STATIC_INLINE void DL_I2CT_stopFlushRXFIFO (UNICOMM_Inst_Regs * unicomm)
Stop RX FIFO flush.
Before stopping the flush, check if DL_I2CT_isRXFIFOEmpty, indicating flush is complete.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_startFlushRXFIFO()
__STATIC_INLINE void DL_I2CT_startFlushRXFIFO (UNICOMM_Inst_Regs * unicomm)
Start RX FIFO flush.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
References DL_I2CT_receiveDataBlocking(), DL_I2CT_receiveDataCheck(), DL_I2CT_transmitDataBlocking(), and DL_I2CT_transmitDataCheck().
DL_I2CT_transmitDataBlocking()
void DL_I2CT_transmitDataBlocking (UNICOMM_Inst_Regs * unicomm, uint8_t data)
Transmit data, waiting until transmit request.
Note
Setting own addresses and enabling should be done separately.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] data Byte of data to transmit
Referenced by DL_I2CT_startFlushRXFIFO().
DL_I2CT_transmitDataCheck()
bool DL_I2CT_transmitDataCheck (UNICOMM_Inst_Regs * unicomm, uint8_t data)
Transmit data.
Note
Setting own addresses and enabling should be done separately.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] data Byte of data to transmit
Returns
Whether data could be transmitted or not
Return values
true if data could be transmitted
false if data could not be transmitted
Referenced by DL_I2CT_startFlushRXFIFO().
DL_I2CT_receiveDataBlocking()
uint8_t DL_I2CT_receiveDataBlocking (UNICOMM_Inst_Regs * unicomm)
Receive data, waiting until receive request.
Note
Setting own addresses and enabling should be done separately.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Data received from
Referenced by DL_I2CT_startFlushRXFIFO().
DL_I2CT_receiveDataCheck()
bool DL_I2CT_receiveDataCheck (UNICOMM_Inst_Regs * unicomm, uint8_t * buffer)
Receive data.
Note
Setting own addresses and enabling should be done separately.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] buffer Pointer to where byte of received data should be stored
Returns
Whether data could be received or not
Return values
true if data could be received
false if data could not be received
Referenced by DL_I2CT_startFlushRXFIFO().
DL_I2CT_enablePower()
__STATIC_INLINE void DL_I2CT_enablePower (UNICOMM_Inst_Regs * unicomm)
Enables power on UNICOMM I2C module.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
References DL_UNICOMM_enablePower(), DL_UNICOMM_I2C_TARGET, and DL_UNICOMM_setIPMode().
DL_I2CT_disablePower()
__STATIC_INLINE void DL_I2CT_disablePower (UNICOMM_Inst_Regs * unicomm)
Disables power on UNICOMM I2C module.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
References DL_UNICOMM_disablePower().
DL_I2CT_isPowerEnabled()
__STATIC_INLINE bool DL_I2CT_isPowerEnabled (UNICOMM_Inst_Regs * unicomm)
Returns if power on UNICOMM I2C module.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
true if power is enabled
false if power is disabled
References DL_UNICOMM_isPowerEnabled().
DL_I2CT_reset()
__STATIC_INLINE void DL_I2CT_reset (UNICOMM_Inst_Regs * unicomm)
Resets UNICOMM I2C peripheral.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
References DL_UNICOMM_reset().
DL_I2CT_isReset()
__STATIC_INLINE bool DL_I2CT_isReset (UNICOMM_Inst_Regs * unicomm)
Returns if UNICOMM I2C peripheral was reset.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
true if peripheral was reset
false if peripheral wasn't reset
References DL_UNICOMM_isReset().
DL_I2CT_selectClockSource()
__STATIC_INLINE void DL_I2CT_selectClockSource (UNICOMM_Inst_Regs * unicomm, DL_I2CT_CLOCK clockSource)
Set Clock Source.
Clock sources depend on device and clock should be enabled
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] clockSource One of DL_I2CT_CLOCK.
References DL_Common_updateReg().
DL_I2CT_selectClockDivider()
__STATIC_INLINE void DL_I2CT_selectClockDivider (UNICOMM_Inst_Regs * unicomm, DL_I2CT_CLOCK_DIVIDE clockDivider)
Set Clock Divider.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] clockDivider One of DL_I2CT_CLOCK_DIVIDE.
References DL_Common_updateReg().
DL_I2CT_getDigitalGlitchFilterPulseWidth()
__STATIC_INLINE DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH DL_I2CT_getDigitalGlitchFilterPulseWidth (UNICOMM_Inst_Regs * unicomm)
Get Digital Glitch Suppression Pulse Width.
Pulse width for the digital glitch suppression on SCL/SDA lines. Values are in terms of functional clock ticks.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Digital glitch suppression pulse width
Return values
One of DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH.
DL_I2CT_setDigitalGlitchFilterPulseWidth()
__STATIC_INLINE void DL_I2CT_setDigitalGlitchFilterPulseWidth (UNICOMM_Inst_Regs * unicomm, DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH filterWidth)
Set Digital Glitch Suppression Pulse Width.
Pulse width for the digital glitch suppression on SCL/SDA lines. Values are in terms of functional clock ticks.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] filterWidth One of DL_I2CT_DIGITAL_GLITCH_FILTER_WIDTH.
References DL_Common_updateReg().
DL_I2CT_disableAnalogGlitchFilter()
__STATIC_INLINE void DL_I2CT_disableAnalogGlitchFilter (UNICOMM_Inst_Regs * unicomm)
Disable Analog Glitch Suppression.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isAnalogGlitchFilterEnabled()
__STATIC_INLINE bool DL_I2CT_isAnalogGlitchFilterEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if analog glitch suppression is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If analog glitch suppression is enabled
Return values
true if analog glitch suppression is enabled
false if analog glitch suppression is disabled
DL_I2CT_enableAnalogGlitchFilter()
__STATIC_INLINE void DL_I2CT_enableAnalogGlitchFilter (UNICOMM_Inst_Regs * unicomm)
Enable Analog Glitch Suppression.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_setOwnAddress()
__STATIC_INLINE void DL_I2CT_setOwnAddress (UNICOMM_Inst_Regs * unicomm, uint32_t addr)
Set own address.
This field specifies bits A9 through A0 of the own address.
In 7-bit addressing mode as selected by DL_I2CT_setAddressingMode, the top 3 bits are don't care
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] addr Value of own address [0x00, 0x3FF]
References DL_Common_updateReg().
DL_I2CT_getOwnAddress()
__STATIC_INLINE uint32_t DL_I2CT_getOwnAddress (UNICOMM_Inst_Regs * unicomm)
Get own address.
Get bits A9 through A0 of the own address.
In 7-bit addressing mode as selected by DL_I2CT_setAddressingMode, the top 3 bits are don't care
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
own address
Return values
[0x00,0x3FF]
DL_I2CT_enableOwnAddress()
__STATIC_INLINE void DL_I2CT_enableOwnAddress (UNICOMM_Inst_Regs * unicomm)
Enable own address.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
See also
DL_I2CT_setOwnAddress
DL_I2CT_disableOwnAddress()
__STATIC_INLINE void DL_I2CT_disableOwnAddress (UNICOMM_Inst_Regs * unicomm)
Disable own address.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isOwnAddressEnabled()
__STATIC_INLINE bool DL_I2CT_isOwnAddressEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if own address is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If own address is enabled
Return values
true if own address is enabled
false if own address is disabled
DL_I2CT_setAddressingMode()
__STATIC_INLINE void DL_I2CT_setAddressingMode (UNICOMM_Inst_Regs * unicomm, DL_I2CT_ADDRESSING_MODE mode)
Set addressing mode.
Selects the addressing mode to be used when device is configured as a
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] mode Addressing mode to set the to. One of DL_I2CT_ADDRESSING_MODE.
References DL_Common_updateReg().
DL_I2CT_getAddressingMode()
__STATIC_INLINE DL_I2CT_ADDRESSING_MODE DL_I2CT_getAddressingMode (UNICOMM_Inst_Regs * unicomm)
Get addressing mode.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Addressing mode the is set to
Return values
One of DL_I2CT_ADDRESSING_MODE
UNICOMMI2CT_getOwnAddressAlternate()
__STATIC_INLINE uint32_t UNICOMMI2CT_getOwnAddressAlternate (UNICOMM_Inst_Regs * unicomm)
Get own address alternate.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
own address alternate
Return values
[0x00,0x7f]
DL_I2CT_setOwnAddressAlternate()
__STATIC_INLINE void DL_I2CT_setOwnAddressAlternate (UNICOMM_Inst_Regs * unicomm, uint32_t addr)
Set own address alternate.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] addr Value of own address alternate [0x00, 0x7f]
References DL_Common_updateReg().
DL_I2CT_getOwnAddressAlternateMask()
__STATIC_INLINE uint32_t DL_I2CT_getOwnAddressAlternateMask (UNICOMM_Inst_Regs * unicomm)
Get own address alternate mask.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Which bits of the address are matched
Return values
Bit mask with each bit corresponding to bits A6 through A0 of the address. Value between [0x00, 0x7F]
DL_I2CT_setOwnAddressAlternateMask()
__STATIC_INLINE void DL_I2CT_setOwnAddressAlternateMask (UNICOMM_Inst_Regs * unicomm, uint32_t addressMask)
Set own address alternate mask.
This field specifies bits A6 through A0 of the address. The bits with a value of 1 in the SOAR2.OAR2_MASK field will make the corresponding incoming address bits to match by default regardless of the value inside SOAR2.OAR2 i.e. corresponding SOAR2.OAR2 bit is a don't care.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] addressMask Bit mask of address bits to match. Value between [0x00, 0x7F]
References DL_Common_updateReg().
DL_I2CT_disableOwnAddressAlternate()
__STATIC_INLINE void DL_I2CT_disableOwnAddressAlternate (UNICOMM_Inst_Regs * unicomm)
Disable usage of own address alternate.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isOwnAddressAlternateEnabled()
__STATIC_INLINE bool DL_I2CT_isOwnAddressAlternateEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if own address alternate is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If own address alternate is enabled
Return values
true if own address alternate is enabled
false if own address alternate is disabled
DL_I2CT_enableOwnAddressAlternate()
__STATIC_INLINE void DL_I2CT_enableOwnAddressAlternate (UNICOMM_Inst_Regs * unicomm)
Enable usage of own address alternate.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_getAddressMatch()
__STATIC_INLINE uint32_t DL_I2CT_getAddressMatch (UNICOMM_Inst_Regs * unicomm)
Get the address for which address match happened.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Matched address
Return values
Bit mask with each bit corresponding to the address. Value between [0x00, 0x7F] in 7-bit mode, or [0x00, 0x3FF] in 10-bit mode.
DL_I2CT_disableClockStretching()
__STATIC_INLINE void DL_I2CT_disableClockStretching (UNICOMM_Inst_Regs * unicomm)
Disable clock stretching.
Clock stretching should be enabled to be compliant with I2CT specification and the SCL will be stretched when data must be read or written from the FIFO. It can optionally be disabled if a controller does not support it or to achieve maximum I2CT frequency; however the developer should ensure that the FIFO is written or read on time.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isClockStretchingEnabled()
__STATIC_INLINE bool DL_I2CT_isClockStretchingEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if clock stretching is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If clock stretching is enabled
Return values
true if clock stretching is enabled
false if clock stretching is disabled
DL_I2CT_enableClockStretching()
__STATIC_INLINE void DL_I2CT_enableClockStretching (UNICOMM_Inst_Regs * unicomm)
Enable clock stretching.
Clock stretching should be enabled to be compliant with I2CT specification and the SCL will be stretched when data must be read or written from the FIFO. It can optionally be disabled if a controller does not support it or to achieve maximum I2CT frequency; however the developer should ensure that the FIFO is written or read on time.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_disableTXEmptyOnTXRequest()
__STATIC_INLINE void DL_I2CT_disableTXEmptyOnTXRequest (UNICOMM_Inst_Regs * unicomm)
Disable TX empty interrupt on transmit request.
When disabled, RIS.STXEMPTY will be set when only the TX FIFO is empty. This allows the STXEMPTY interrupt to be used to indicate that the I2CT bus is being clock stretched and that TX data is required.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
See also
DL_I2CT_isClockStretchEnabled
DL_I2CT_isTXEmptyOnTXRequestEnabled()
__STATIC_INLINE bool DL_I2CT_isTXEmptyOnTXRequestEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if TX empty interrupt on transmit request is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If TX empty interrupt on transmit request is enabled
Return values
true if TX empty interrupt on transmit request is enabled
false if TX empty interrupt on transmit request disabled
DL_I2CT_enableTXEmptyOnTXRequest()
__STATIC_INLINE void DL_I2CT_enableTXEmptyOnTXRequest (UNICOMM_Inst_Regs * unicomm)
Enable TX empty interrupt on transmit request.
When enabled, RIS.STXEMPTY will be set when the state machine is in the TX_WAIT state which occurs when the TX FIFO is empty AND the UNICOMMI2CT transaction is clock stretched waiting for the FIFO to receive data.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_disableTXTriggerInTXMode()
__STATIC_INLINE void DL_I2CT_disableTXTriggerInTXMode (UNICOMM_Inst_Regs * unicomm)
Disable TX trigger in TX mode.
When disabled, RIS.TXFIFOTRG will only be set when the TX FIFO is at or above the trigger level.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isTXTriggerInTXModeEnabled()
__STATIC_INLINE bool DL_I2CT_isTXTriggerInTXModeEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if TX trigger in TX mode is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If TX trigger in TX mode is enabled
Return values
true if TX trigger in TX mode is enabled
false if TX trigger in TX mode is disabled
DL_I2CT_enableTXTriggerInTXMode()
__STATIC_INLINE void DL_I2CT_enableTXTriggerInTXMode (UNICOMM_Inst_Regs * unicomm)
Enable TX trigger when is in TX mode.
When enabled, RIS.TXFIFOTRG will be set when the TX FIFO has reached the trigger level AND the state machine is in the TXMODE as defined in the SSR register. When cleared RIS.TXFIFOTRG will be set when the TX FIFO is at or above the trigger level. This setting can be used to hold off the TX DMA until a transaction starts. This allows the DMA to be configured when the I2CT is idle but have it wait till the transaction starts to load the TX FIFO, so it can load from a memory buffer that might be changing over time.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
See also
DL_I2CT_INTERRUPT_TXFIFO_TRIGGER
DL_I2CT_disableTXWaitWhenTXFIFOStale()
__STATIC_INLINE void DL_I2CT_disableTXWaitWhenTXFIFOStale (UNICOMM_Inst_Regs * unicomm)
Disable TX transfer waits when stale data in TX FIFO.
When disabled, the TX FIFO empty signal to the state machine indicates that the TX FIFO is empty.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isTXWaitWhenTXFIFOStaleEnabled()
__STATIC_INLINE bool DL_I2CT_isTXWaitWhenTXFIFOStaleEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if TX transfer waits when stale data in TX FIFO is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If TX transfer waits when stale data in TX FIFO is enabled
Return values
true if TX transfer waits when stale data in TX FIFO is enabled
false if TX transfer waits when stale data in TX FIFO is disabled
DL_I2CT_enableTXWaitWhenTXFIFOStale()
__STATIC_INLINE void DL_I2CT_enableTXWaitWhenTXFIFOStale (UNICOMM_Inst_Regs * unicomm)
Enable TX transfer waits when stale data in TX FIFO.
When enabled, the TX FIFO empty signal to the state machine will indicate that the TX FIFO is empty or that the TX FIFO data is stale. The TX FIFO data is determined to be stale when there is data in the TX FIFO when the state machine leaves the TXMODE as defined in the SSR register. This can occur is a Stop or timeout occur when there are bytes left in the TX FIFO.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_disableRXFullOnRXRequest()
__STATIC_INLINE void DL_I2CT_disableRXFullOnRXRequest (UNICOMM_Inst_Regs * unicomm)
Disable RX full interrupt on receive request.
When disabled, RIS.SRXFULL will be set when only the RX FIFO is full. This allows the SRXFULL interrupt to be used to indicate that the I2CT bus is being clock stretched and that the FW must either read the RX FIFO or ACK/NACK the current RX byte.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
See also
DL_I2CT_isClockStretchEnabled
DL_I2CT_isRXFullOnRXRequestEnabled()
__STATIC_INLINE bool DL_I2CT_isRXFullOnRXRequestEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if RX full interrupt on receive request is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If RX full interrupt on receive request enabled
Return values
true if RX full interrupt on receive request enabled
false if RX full interrupt on receive request disabled
DL_I2CT_enableRXFullOnRXRequest()
__STATIC_INLINE void DL_I2CT_enableRXFullOnRXRequest (UNICOMM_Inst_Regs * unicomm)
Enable RX full interrupt on receive request.
When enabled, RIS.SRXFULL will be set when the state machine is in the RX_WAIT or RX_ACK_WAIT states which occurs when the I2CT transaction is clock stretched because the RX FIFO is full or the ACKOEN has been set and the state machine is waiting for FW to ACK/NACK the current byte.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_disableDefaultHostAddress()
__STATIC_INLINE void DL_I2CT_disableDefaultHostAddress (UNICOMM_Inst_Regs * unicomm)
Disable SMBus/PMBus default host address of 000 1000b.
When disabled, the default host address is not matched. NOTE: The host address may still be matched if programmed as an own address. The I2CT module can still be addressed as a if enabled and own address match is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isDefaultHostAddressEnabled()
__STATIC_INLINE bool DL_I2CT_isDefaultHostAddressEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if SMBus/PMBus default host address of 000 1000b is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If default host address is enabled
Return values
true if default host address is enabled
false if default host address disabled
DL_I2CT_enableDefaultHostAddress()
__STATIC_INLINE void DL_I2CT_enableDefaultHostAddress (UNICOMM_Inst_Regs * unicomm)
Enable SMBus/PMBus default host address of 000 1000b.
When enabled, default host address of 0x0001000 is always matched by the address match logic
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_disableAlertResponseAddress()
__STATIC_INLINE void DL_I2CT_disableAlertResponseAddress (UNICOMM_Inst_Regs * unicomm)
Disable SMBus/PMBus Alert response address (ARA) of 000 1100b.
When disabled, the alert response address 0x0001100 is not matched. NOTE: The alert response address may still be matched if programmed as an own address. The I2CT module can still be addressed as a if enabled and own address match is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isAlertResponseAddressEnabled()
__STATIC_INLINE bool DL_I2CT_isAlertResponseAddressEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if SMBus/PMBus Alert response address (ARA) of 000 1100b is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If alert response address is enabled
Return values
true if alert response address is enabled
false if alert response address disabled
DL_I2CT_enableAlertResponseAddress()
__STATIC_INLINE void DL_I2CT_enableAlertResponseAddress (UNICOMM_Inst_Regs * unicomm)
Enable SMBus/PMBus Alert response address (ARA) of 000 1100b.
When enabled, default alert response address of 0x0001100 is always matched by the address match logic
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_disableDefaultDeviceAddress()
__STATIC_INLINE void DL_I2CT_disableDefaultDeviceAddress (UNICOMM_Inst_Regs * unicomm)
Disable SMBus/PMBus default device address of 110 0001b.
Used for Address Resolution Protocol. When disabled, the default device address is not matched. NOTE: The host address may still be matched if programmed as an own address. The I2CT module can still be addressed as a if enabled and own address match is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isDefaultDeviceAddressEnabled()
__STATIC_INLINE bool DL_I2CT_isDefaultDeviceAddressEnabled (UNICOMM_Inst_Regs * unicomm)
Checks SMBus/PMBus default device address of 110 0001b is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If default device address is enabled
Return values
true if default device address is enabled
false if default device address disabled
DL_I2CT_enableDefaultDeviceAddress()
__STATIC_INLINE void DL_I2CT_enableDefaultDeviceAddress (UNICOMM_Inst_Regs * unicomm)
Enable SMBus/PMBus default device address of 110 0001b.
Used for Address Resolution Protocol. When enabled, default device address of 110 0001b is always matched by the address match logic.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_disableWakeup()
__STATIC_INLINE void DL_I2CT_disableWakeup (UNICOMM_Inst_Regs * unicomm)
Disable wakeup.
When disabled, the is not allowed to clock stretch on START detection.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isWakeupEnabled()
__STATIC_INLINE bool DL_I2CT_isWakeupEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if wakeup is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If wakeup is enabled
Return values
true if wakeup is enabled
false if wakeup disabled
DL_I2CT_enableWakeup()
__STATIC_INLINE void DL_I2CT_enableWakeup (UNICOMM_Inst_Regs * unicomm)
Enable wakeup.
Enables low-power wake-up, however it is recommended to enable clock stretching to stretch the clock while the module is waking up.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
See also
DL_I2CT_enableClockStretching
DL_I2CT_disable()
__STATIC_INLINE void DL_I2CT_disable (UNICOMM_Inst_Regs * unicomm)
Disable target.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isEnabled()
__STATIC_INLINE bool DL_I2CT_isEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if target is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If functionality is enabled
Return values
true if functionality is enabled
false if functionality is disabled
DL_I2CT_enable()
__STATIC_INLINE void DL_I2CT_enable (UNICOMM_Inst_Regs * unicomm)
Enable target.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_disableGeneralCall()
__STATIC_INLINE void DL_I2CT_disableGeneralCall (UNICOMM_Inst_Regs * unicomm)
Disable general call address of 000 0000b.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isGeneralCallEnabled()
__STATIC_INLINE bool DL_I2CT_isGeneralCallEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if general call address of 000 0000b is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If general call is enabled
Return values
true if general call is enabled
false if general call is disabled
DL_I2CT_enableGeneralCall()
__STATIC_INLINE void DL_I2CT_enableGeneralCall (UNICOMM_Inst_Regs * unicomm)
Enable usage of general call address of 000 0000b.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_getStatus()
__STATIC_INLINE uint32_t DL_I2CT_getStatus (UNICOMM_Inst_Regs * unicomm)
Get status of I2CT bus controller for target.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Status of I2CT bus controller for target
Return values
Bitwise OR of DL_I2CT_STATUS
DL_I2CT_receiveData()
__STATIC_INLINE uint8_t DL_I2CT_receiveData (UNICOMM_Inst_Regs * unicomm)
Get byte of data from UNICOMMI2CT.
If using FIFO, it is first byte from the RX FIFO.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Last received byte of data
Return values
[0x00,0xff]
DL_I2CT_transmitData()
__STATIC_INLINE void DL_I2CT_transmitData (UNICOMM_Inst_Regs * unicomm, uint8_t data)
Set next byte to be transferred during the next transaction.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] data Byte of data to be transferred during the next transaction. [0x00, 0xff]
DL_I2CT_disableACKOverride()
__STATIC_INLINE void DL_I2CT_disableACKOverride (UNICOMM_Inst_Regs * unicomm)
Disable ACK override.
Disable manual ACK override to automatically ACK all received bytes until the RX FIFO is full.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isACKOverrideEnabled()
__STATIC_INLINE bool DL_I2CT_isACKOverrideEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if ACK override is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If ACK override is enabled
Return values
true if ACK override is enabled
false if ACK override is disabled
DL_I2CT_enableACKOverride()
__STATIC_INLINE void DL_I2CT_enableACKOverride (UNICOMM_Inst_Regs * unicomm)
Enable ACK override.
When manual ACK override is enabled, the I2CT SCL is pulled low after the last data is received until the ACK override value (through DL_I2CT_setACKOverrideValue) is written. Disable manual ACK override to automatically ACK all received bytes until the RX FIFO is full.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_getACKOverrideValue()
__STATIC_INLINE DL_I2CT_RESPONSE_OVERRIDE_VALUE DL_I2CT_getACKOverrideValue (UNICOMM_Inst_Regs * unicomm)
Get acknowledge override value.
Note
for General Call this bit will be ignored if set to NACK and continues to receive data.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
What type of response will be generated
Return values
One of DL_I2CT_RESPONSE_OVERRIDE_VALUE.
DL_I2CT_setACKOverrideValue()
__STATIC_INLINE void DL_I2CT_setACKOverrideValue (UNICOMM_Inst_Regs * unicomm, DL_I2CT_RESPONSE_OVERRIDE_VALUE value)
Set acknowledge override value.
Note
for General Call this bit will be ignored if set to NACK and continues to receive data.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] value Indicates what type of response will be generated. One of DL_I2CT_RESPONSE_OVERRIDE_VALUE.
See also
DL_I2CT_enableACKOverride
References DL_Common_updateReg().
DL_I2CT_disableACKOverrideOnStart()
__STATIC_INLINE void DL_I2CT_disableACKOverrideOnStart (UNICOMM_Inst_Regs * unicomm)
Disable ACK override on Start Condition.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isACKOverrideOnStartEnabled()
__STATIC_INLINE bool DL_I2CT_isACKOverrideOnStartEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if ACK override on Start condition is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If ACK override on Start condition is enabled
Return values
true if ACK override on Start condition is enabled
false if ACK override on Start condition is disabled
DL_I2CT_enableACKOverrideOnStart()
__STATIC_INLINE void DL_I2CT_enableACKOverrideOnStart (UNICOMM_Inst_Regs * unicomm)
Enable ACK override on Start condition.
When enabled, this bit will automatically turn on the ACKOEN field following a Start condition.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
See also
DL_I2CT_enableACKOverride
DL_I2CT_disableACKOverrideOnPECNext()
__STATIC_INLINE void DL_I2CT_disableACKOverrideOnPECNext (UNICOMM_Inst_Regs * unicomm)
Disable ACK override when SMBus/PMBus PEC is next byte.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isACKOverrideOnPECNextEnabled()
__STATIC_INLINE bool DL_I2CT_isACKOverrideOnPECNextEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if ACK override when SMBus/PMBus PEC is next byte is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If ACK override when PEC is next byte is enabled
Return values
true if ACK override when PEC is next byte is enabled
false if ACK override when PEC is next byte is disabled
DL_I2CT_enableACKOverrideOnPECNext()
__STATIC_INLINE void DL_I2CT_enableACKOverrideOnPECNext (UNICOMM_Inst_Regs * unicomm)
Enable ACK override when SMBus/PMBus PEC is next byte.
When enabled, this bit will automatically turn on the ACKOEN field following the ACK/NACK of the byte received just prior to the PEC byte. Note that when ACKOEN is set, the PEC byte will not automatically be ACKed/NACKed by the state machine and FW must perform this function by writing SLAVE_SACKCTL.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
See also
DL_I2CT_enableACKOverride
DL_I2CT_disableACKOverrideOnPECDone()
__STATIC_INLINE void DL_I2CT_disableACKOverrideOnPECDone (UNICOMM_Inst_Regs * unicomm)
Disable ACK override when SMBus/PMBus PEC is next byte.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isACKOverrideOnPECDoneEnabled()
__STATIC_INLINE bool DL_I2CT_isACKOverrideOnPECDoneEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if ACK override when SMBus/PMBus PEC is next byte is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If ACK override when PEC is next byte is enabled
Return values
true if ACK override when PEC is next byte is enabled
false if ACK override when PEC is next byte is disabled
DL_I2CT_enableACKOverrideOnPECDone()
__STATIC_INLINE void DL_I2CT_enableACKOverrideOnPECDone (UNICOMM_Inst_Regs * unicomm)
Enable ACK override when SMBus/PMBus PEC is done.
When enabled, this bit will automatically turn on the ACKOEN field following the ACK/NACK of the received PEC byte.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
See also
DL_I2CT_enableACKOverride
DL_I2CT_getPECCountValue()
__STATIC_INLINE uint32_t DL_I2CT_getPECCountValue (UNICOMM_Inst_Regs * unicomm)
Get the SMBus/PMBus Packet Error Checking (PEC) count value.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
The value the PEC count is set to
Return values
Value between [0x0, 0x01FF]
DL_I2CT_setPECCountValue()
__STATIC_INLINE void DL_I2CT_setPECCountValue (UNICOMM_Inst_Regs * unicomm, uint32_t count)
Set the SMBus/PMBus Packet Error Checking (PEC) count value.
When this field is non zero, the number of I2CT data bytes are counted. Refer to the device TRM for more details.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] count The value to set the PEC count to. Value between [0x0, 0x01FF]
References DL_Common_updateReg().
DL_I2CT_disablePEC()
__STATIC_INLINE void DL_I2CT_disablePEC (UNICOMM_Inst_Regs * unicomm)
Disable SMBus/PMBus Packet Error Checking (PEC)
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isPECEnabled()
__STATIC_INLINE bool DL_I2CT_isPECEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if SMBus/PMBus Packet Error Checking (PEC) is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If PEC is enabled
Return values
true if PEC is enabled
false if PEC is disabled
DL_I2CT_enablePEC()
__STATIC_INLINE void DL_I2CT_enablePEC (UNICOMM_Inst_Regs * unicomm)
Enable SMBus/PMBus Packet Error Checking (PEC)
When enabled, the PEC is calculated on all bits accept the Start, Stop, ACK and NACK. The PEC LSFR and the Byte Counter is set to 0 when the State Machine is in the IDLE state, which occurs following a Stop or when a timeout occurs. The Counter is also set to 0 after the PEC byte is sent or received. Note that the NACK is automatically sent following a PEC byte that results in a PEC error. The PEC Polynomial is x^8 + x^2 + x^1 + 1.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_getCurrentPECCount()
__STATIC_INLINE uint32_t DL_I2CT_getCurrentPECCount (UNICOMM_Inst_Regs * unicomm)
Get the current SMBus/PMBus PEC byte count of the state machine.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
The current PEC byte count of the state macione
Return values
Value between [0x0, 0x01FF]
DL_I2CT_getPECCheckedStatus()
__STATIC_INLINE DL_I2CT_PEC_STATUS DL_I2CT_getPECCheckedStatus (UNICOMM_Inst_Regs * unicomm)
Get status if SMBus/PMBus PEC was checked in last transaction.
The status indicates if the PEC was checked in the transaction that occurred before the last Stop. Latched on Stop.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Status of PEC checked
Return values
One of DL_I2CT_PEC_STATUS
DL_I2CT_getPECCheckError()
__STATIC_INLINE DL_I2CT_PEC_CHECK_ERROR DL_I2CT_getPECCheckError (UNICOMM_Inst_Regs * unicomm)
Get status if SMBus/PMBus PEC had an error.
The status indicates if a PEC check error occurred in the transaction that occurred before the last Stop. Latched on Stop.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Status of PEC error check
Return values
One of DL_I2CT_PEC_CHECK_ERROR
DL_I2CT_getTXFIFOThreshold()
__STATIC_INLINE DL_I2CT_TX_FIFO_LEVEL DL_I2CT_getTXFIFOThreshold (UNICOMM_Inst_Regs * unicomm)
Get TX FIFO threshold level.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Indicates at what fill level in the TX FIFO a threshold will be generated
Return values
One of DL_I2CT_TX_FIFO_LEVEL
DL_I2CT_setTXFIFOThreshold()
__STATIC_INLINE void DL_I2CT_setTXFIFOThreshold (UNICOMM_Inst_Regs * unicomm, DL_I2CT_TX_FIFO_LEVEL level)
Set TX FIFO threshold level.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] level Indicates at what fill level in the TX FIFO a threshold will be generated. One of DL_I2CT_TX_FIFO_LEVEL.
References DL_Common_updateReg().
DL_I2CT_getRXFIFOThreshold()
__STATIC_INLINE DL_I2CT_RX_FIFO_LEVEL DL_I2CT_getRXFIFOThreshold (UNICOMM_Inst_Regs * unicomm)
Get RX FIFO threshold level.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Indicates at what fill level in the RX FIFO a threshold will be generated
Return values
One of DL_I2CT_RX_FIFO_LEVEL
DL_I2CT_setRXFIFOThreshold()
__STATIC_INLINE void DL_I2CT_setRXFIFOThreshold (UNICOMM_Inst_Regs * unicomm, DL_I2CT_RX_FIFO_LEVEL level)
Set RX FIFO threshold level.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] level Indicates at what fill level in the RX FIFO a threshold will be generated. One of DL_I2CT_RX_FIFO_LEVEL.
References DL_Common_updateReg().
DL_I2CT_enableInterrupt()
__STATIC_INLINE void DL_I2CT_enableInterrupt (UNICOMM_Inst_Regs * unicomm, uint32_t interruptMask)
Enable I2CT interrupts.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to enable. Bitwise OR of DL_I2CT_INTERRUPT.
DL_I2CT_disableInterrupt()
__STATIC_INLINE void DL_I2CT_disableInterrupt (UNICOMM_Inst_Regs * unicomm, uint32_t interruptMask)
Disable I2CT interrupts.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to disable. Bitwise OR of DL_I2CT_INTERRUPT.
DL_I2CT_getEnabledInterrupts()
__STATIC_INLINE uint32_t DL_I2CT_getEnabledInterrupts (UNICOMM_Inst_Regs * unicomm, uint32_t interruptMask)
Check which I2CT interrupts are enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2CT_INTERRUPT.
Returns
Which of the requested I2CT interrupts are enabled
Return values
Bitwise OR of DL_I2CT_INTERRUPT values
DL_I2CT_getEnabledInterruptStatus()
__STATIC_INLINE uint32_t DL_I2CT_getEnabledInterruptStatus (UNICOMM_Inst_Regs * unicomm, uint32_t interruptMask)
Check interrupt flag of enabled I2CT interrupts.
Checks if any of the I2CT interrupts that were previously enabled are pending.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2CT_INTERRUPT.
Returns
Which of the requested I2CT interrupts are pending
Return values
Bitwise OR of DL_I2CT_INTERRUPT values
See also
DL_I2CT_enableInterrupt
DL_I2CT_getRawInterruptStatus()
__STATIC_INLINE uint32_t DL_I2CT_getRawInterruptStatus (UNICOMM_Inst_Regs * unicomm, uint32_t interruptMask)
Check interrupt flag of any I2CT interrupt.
Checks if any of the I2CT interrupts are pending. Interrupts do not have to be previously enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2CT_INTERRUPT.
Returns
Which of the requested I2CT interrupts are pending
Return values
Bitwise OR of DL_I2CT_INTERRUPT values
DL_I2CT_getPendingInterrupt()
__STATIC_INLINE DL_I2CT_IIDX DL_I2CT_getPendingInterrupt (UNICOMM_Inst_Regs * unicomm)
Get highest priority pending I2CT interrupt.
Checks if any of the I2CT interrupts are pending. Interrupts do not have to be previously enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
The highest priority pending I2CT interrupt
Return values
One of DL_I2CT_IIDX
DL_I2CT_clearInterruptStatus()
__STATIC_INLINE void DL_I2CT_clearInterruptStatus (UNICOMM_Inst_Regs * unicomm, uint32_t interruptMask)
Clear pending I2CT interrupts.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to clear. Bitwise OR of DL_I2CT_INTERRUPT.
DL_I2CT_enableDMAEvent()
__STATIC_INLINE void DL_I2CT_enableDMAEvent (UNICOMM_Inst_Regs * unicomm, DL_I2CT_EVENT_ROUTE index, uint32_t interrupt)
Enables I2CT interrupt for triggering DMA events.
Enables the I2CT interrupt to be used as the condition to generate an event to directly trigger the DMA.
Each event publisher DL_I2CT_EVENT_ROUTE can set any one of DL_I2CT_DMA_INTERRUPT.
Note
Only one interrupt source should be enabled at a time.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] index Specifies the register event publisher to configure
[in] interrupt Interrupt to enable as the trigger condition for the DMA. One of DL_I2CT_DMA_INTERRUPT.
References DL_I2CT_EVENT_ROUTE_1, and DL_I2CT_EVENT_ROUTE_2.
DL_I2CT_disableDMAEvent()
__STATIC_INLINE void DL_I2CT_disableDMAEvent (UNICOMM_Inst_Regs * unicomm, DL_I2CT_EVENT_ROUTE index, uint32_t interrupt)
Disables I2CT interrupt from triggering DMA events.
Disables the I2CT interrupt from being used as the condition to generate an event to directly trigger the DMA.
Each event publisher DL_I2CT_EVENT_ROUTE can set any one of DL_I2CT_DMA_INTERRUPT.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] index Specifies the register event publisher to configure
[in] interrupt Interrupt to disable as the trigger condition for the DMA. One of DL_I2CT_DMA_INTERRUPT.
References DL_I2CT_EVENT_ROUTE_1, and DL_I2CT_EVENT_ROUTE_2.
DL_I2CT_getEnabledDMAEvents()
__STATIC_INLINE uint32_t DL_I2CT_getEnabledDMAEvents (UNICOMM_Inst_Regs * unicomm, DL_I2CT_EVENT_ROUTE index, uint32_t interruptMask)
Check which I2CT interrupt for DMA receive events is enabled.
This API checks the event publisher register as selected by DL_I2CT_EVENT_ROUTE, which are used for triggering the DMA for Controller or and receive or transmit events.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] index Specifies the register event publisher to configure
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2CT_DMA_INTERRUPT.
Note
Only one interrupt source should be enabled at a time.
Returns
The requested I2CT interrupt status
Return values
One of DL_I2CT_DMA_INTERRUPT
DL_I2CT_getEnabledDMAEventStatus()
__STATIC_INLINE uint32_t DL_I2CT_getEnabledDMAEventStatus (UNICOMM_Inst_Regs * unicomm, DL_I2CT_EVENT_ROUTE index, uint32_t interruptMask)
Check interrupt flag of enabled I2CT interrupt for DMA event.
Checks if any of the I2CT interrupts for the DMA receive event that were previously enabled are pending. This API checks the event publisher register as selected by DL_I2CT_EVENT_ROUTE, which are used for triggering the DMA for Controller or and receive or transmit events.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] index Specifies the register event publisher to configure
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2CT_DMA_INTERRUPT.
Note
Only one interrupt source should be enabled at a time.
Returns
The requested I2CT interrupt status
Return values
One of DL_I2CT_DMA_INTERRUPT
See also
DL_I2CT_enableDMAEvent
DL_I2CT_getRawDMAEventStatus()
__STATIC_INLINE uint32_t DL_I2CT_getRawDMAEventStatus (UNICOMM_Inst_Regs * unicomm, DL_I2CT_EVENT_ROUTE index, uint32_t interruptMask)
Check interrupt flag of any I2CT interrupt for DMA event.
Checks if any of the I2CT interrupts for DMA receive event are pending. Interrupts do not have to be previously enabled. This API checks the event publisher register as selected by DL_I2CT_EVENT_ROUTE, which are used for triggering the DMA for Controller or and receive or transmit events.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] index Specifies the register event publisher to configure
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2CT_DMA_INTERRUPT.
Returns
Which of the requested I2CT interrupts are pending
Return values
Bitwise OR of DL_I2CT_DMA_INTERRUPT values
DL_I2CT_getTimeoutACount()
__STATIC_INLINE uint32_t DL_I2CT_getTimeoutACount (UNICOMM_Inst_Regs * unicomm)
Get the Timeout Counter A value.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
The Timeout A counter value
Return values
Value between [0x0, 0xFF]
DL_I2CT_setTimeoutACount()
__STATIC_INLINE void DL_I2CT_setTimeoutACount (UNICOMM_Inst_Regs * unicomm, uint32_t count)
Set the Timeout Counter A value.
Timeout A is used for SCL low detection. This field contains the upper 8 bits of a 12-bit pre-load value for the Timeout A count. NOTE: The value of the counter must be greater than 1 to enable the timeout. Each count is equal to 520 times the timeout period of the functional clock. For example, with 8MHz functional clock and a 100KHz operating I2CT clock, one timeout period will be equal to (1 / 8MHz) * 520 = 65us.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] count The value to set the Timeout A counter to. Value between [0x0, 0xFF]
References DL_Common_updateReg().
DL_I2CT_disableTimeoutA()
__STATIC_INLINE void DL_I2CT_disableTimeoutA (UNICOMM_Inst_Regs * unicomm)
Disable Timeout Counter A.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isTimeoutAEnabled()
__STATIC_INLINE bool DL_I2CT_isTimeoutAEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if Timeout Counter A is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If Timeout Counter A is enabled
Return values
true if Timeout Counter A is enabled
false if Timeout Counter A is disabled
DL_I2CT_enableTimeoutA()
__STATIC_INLINE void DL_I2CT_enableTimeoutA (UNICOMM_Inst_Regs * unicomm)
Enable Timeout Counter A.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_getCurrentTimeoutACounter()
__STATIC_INLINE uint32_t DL_I2CT_getCurrentTimeoutACounter (UNICOMM_Inst_Regs * unicomm)
Get the current Timer Counter A value.
This field contains the upper 8 bits of a 12-bit current counter for Timeout Counter A.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
The Timeout A counter value
Return values
Value between [0x0, 0xFF]
DL_I2CT_getTimeoutBCount()
__STATIC_INLINE uint32_t DL_I2CT_getTimeoutBCount (UNICOMM_Inst_Regs * unicomm)
Get the Timeout Counter B value.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
The Timeout B counter value
Return values
Value between [0x0, 0xFF]
DL_I2CT_setTimeoutBCount()
__STATIC_INLINE void DL_I2CT_setTimeoutBCount (UNICOMM_Inst_Regs * unicomm, uint32_t count)
Set the Timeout Counter B value.
Timeout B is used for SCL high detection. This field contains the upper 8 bits of a 12-bit pre-load value for the Timeout A count. NOTE: The value of the counter must be greater than 1 to enable the timeout. Each count is equal to 1* clock period. For example, with 10MHz functional clock one timeout period will be equal to 1 * 10ns.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] count The value to set the Timeout A counter to. Value between [0x0, 0xFF]
References DL_Common_updateReg().
DL_I2CT_disableTimeoutB()
__STATIC_INLINE void DL_I2CT_disableTimeoutB (UNICOMM_Inst_Regs * unicomm)
Disable Timeout Counter B.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_isTimeoutBEnabled()
__STATIC_INLINE bool DL_I2CT_isTimeoutBEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if Timeout Counter B is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If Timeout Counter B is enabled
Return values
true if Timeout Counter B is enabled
false if Timeout Counter B is disabled
DL_I2CT_enableTimeoutB()
__STATIC_INLINE void DL_I2CT_enableTimeoutB (UNICOMM_Inst_Regs * unicomm)
Enable Timeout Counter B.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CT_getCurrentTimeoutBCounter()
__STATIC_INLINE uint32_t DL_I2CT_getCurrentTimeoutBCounter (UNICOMM_Inst_Regs * unicomm)
Get the current Timer Counter B value.
This field contains the upper 8 bits of a 12-bit current counter for Timeout Counter B.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
The Timeout B counter value
Return values
Value between [0x0, 0xFF]
Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale