MSPM0G511X Driver Library: Inter-Integrated Circuit Sound (I2S)
Inter-Integrated Circuit Sound (I2S)
Modules
DL_I2S_INTERRUPT
DL_I2S_DMA_INTERRUPT
Data Structures
struct DL_I2S_ClockConfig
Configuration struct for DL_I2S_setClockConfig.
struct DL_I2S_Config
Configuration struct for DL_I2S_init.
Macros
#define DEVICE_HAS_MULTIPLE_DATA_PIN
Device supports multiple data pins.
#define DL_I2S_MDIV_MINIMUM ((uint32_t)2U)
I2S Minimum factor of the division ratio used to generate the controller clock (MCLK). The minimum is 2, since 0 is evaluated as 1024, which is the maximum factor, and 1 is invalid.
#define DL_I2S_MDIV_MAXIMUM ((uint32_t)0U)
I2S Maximum factor of the division ratio used to generate the controller clock (MCLK). The maximum is 0, which is interpreted as 1024.
#define DL_I2S_MDIV_INVALID ((uint32_t)1U)
I2S Invalid factor of the division ratio used to generate the controller clock (MCLK). This is 1.
#define DL_I2S_BDIV_MINIMUM ((uint32_t)2U)
I2S Minimum factor of the division ratio used to generate BCLK. The minimum is 2, since the 0 is interpreted as 1024, which is the maximum factor, and 1 is invalid.
#define DL_I2S_BDIV_MAXIMUM ((uint32_t)0U)
I2S Maximum factor of the division ratio used to generate BCLK. The maximum is 0, which is interpreted as 1024.
#define DL_I2S_BDIV_INVALID ((uint32_t)1U)
I2S Invalid factor of the division ratio used to generate BCLK. This is 1.
Enumerations
enum DL_I2S_WORD_BAUD_CLOCK_SOURCE {
DL_I2S_WORD_BAUD_CLOCK_SOURCE_NONE = I2S_WCLKSRC_WBCLKSRC_NONE,
DL_I2S_WORD_BAUD_CLOCK_SOURCE_EXTERNAL = I2S_WCLKSRC_WBCLKSRC_EXT,
DL_I2S_WORD_BAUD_CLOCK_SOURCE_INTERNAL = I2S_WCLKSRC_WBCLKSRC_INT
}
enum DL_I2S_CLOCK_SOURCE {
DL_I2S_CLOCK_SOURCE_SYSOSC = I2S_CLKCFG_DAICLK_SYSOSC,
DL_I2S_CLOCK_SOURCE_HFXT = I2S_CLKCFG_DAICLK_HFXT,
DL_I2S_CLOCK_SOURCE_PLL = I2S_CLKCFG_DAICLK_PLL
}
enum DL_I2S_WCLK_INVERSION {
DL_I2S_WCLK_INVERSION_DISABLED = I2S_WCLKSRC_WCLKINV_NOT_INVERTED,
DL_I2S_WCLK_INVERSION_ENABLED = I2S_WCLKSRC_WCLKINV_INVERTED
}
enum DL_I2S_PHASE {
DL_I2S_PHASE_SINGLE = I2S_FMTCFG_DUALPHASE_SINGLEPHASE,
DL_I2S_PHASE_DUAL = I2S_FMTCFG_DUALPHASE_DUALPHASE
}
enum DL_I2S_SAMPLE_EDGE {
DL_I2S_SAMPLE_EDGE_NEG = I2S_FMTCFG_SMPLEDGE_NEGEDGE,
DL_I2S_SAMPLE_EDGE_POS = I2S_FMTCFG_SMPLEDGE_POSEDGE
}
enum DL_I2S_MEMORY_LENGTH {
DL_I2S_MEMORY_LENGTH_16_BIT = I2S_FMTCFG_MEMLEN32_16BIT,
DL_I2S_MEMORY_LENGTH_32_BIT = I2S_FMTCFG_MEMLEN32_32BIT
}
enum DL_I2S_DATA_DELAY {
DL_I2S_DATA_DELAY_ZERO = I2S_FMTCFG_DATADLY_ZERO,
DL_I2S_DATA_DELAY_ONE = I2S_FMTCFG_DATADLY_ONE,
DL_I2S_DATA_DELAY_TWO = I2S_FMTCFG_DATADLY_TWO,
DL_I2S_DATA_DELAY_MAX = I2S_FMTCFG_DATADLY_MAX
}
enum DL_I2S_EMPTY_SLOT_OUTPUT {
DL_I2S_EMPTY_SLOT_OUTPUT_ZERO = I2S_FMTCFG_EMPTYSLOTOUTPUT_ZERO,
DL_I2S_EMPTY_SLOT_OUTPUT_ONE = I2S_FMTCFG_EMPTYSLOTOUTPUT_ONE,
DL_I2S_EMPTY_SLOT_OUTPUT_TRISTATE = I2S_FMTCFG_EMPTYSLOTOUTPUT_TRISTATE
}
enum DL_I2S_WCLK_PHASE {
DL_I2S_WCLK_PHASE_SINGLE = (0U << I2S_CLKCTL_WCLKPHASE_OFS),
DL_I2S_WCLK_PHASE_DUAL = (1U << I2S_CLKCTL_WCLKPHASE_OFS),
DL_I2S_WCLK_PHASE_CUSTOM = (2U << I2S_CLKCTL_WCLKPHASE_OFS)
}
enum DL_I2S_MODE {
DL_I2S_MODE_CONTROLLER = 0U,
DL_I2S_MODE_TARGET = 1U
}
enum DL_I2S_DATA_PIN_DIRECTION {
DL_I2S_DATA_PIN_DIRECTION_UNUSED = 0U,
DL_I2S_DATA_PIN_DIRECTION_INPUT = 1U,
DL_I2S_DATA_PIN_DIRECTION_OUTPUT = 2U
}
enum DL_I2S_TX_FIFO_LEVEL {
DL_I2S_TX_FIFO_LEVEL_3_4_EMPTY = I2S_IFLS_TXIFLSEL_LVL_3_4,
DL_I2S_TX_FIFO_LEVEL_1_2_EMPTY = I2S_IFLS_TXIFLSEL_LVL_1_2,
DL_I2S_TX_FIFO_LEVEL_1_4_EMPTY = I2S_IFLS_TXIFLSEL_LVL_1_4,
DL_I2S_TX_FIFO_LEVEL_EMPTY = I2S_IFLS_TXIFLSEL_LVL_EMPTY,
DL_I2S_TX_FIFO_LEVEL_ONE_ENTRY = I2S_IFLS_TXIFLSEL_LVL_ALMOST_EMPTY,
DL_I2S_TX_FIFO_LEVEL_ALMOST_FULL = I2S_IFLS_TXIFLSEL_LVL_ALMOST_FULL
}
enum DL_I2S_RX_FIFO_LEVEL {
DL_I2S_RX_FIFO_LEVEL_1_4_FULL = I2S_IFLS_RXIFLSEL_LVL_1_4,
DL_I2S_RX_FIFO_LEVEL_1_2_FULL = I2S_IFLS_RXIFLSEL_LVL_1_2,
DL_I2S_RX_FIFO_LEVEL_3_4_FULL = I2S_IFLS_RXIFLSEL_LVL_3_4,
DL_I2S_RX_FIFO_LEVEL_FULL = I2S_IFLS_RXIFLSEL_LVL_FULL,
DL_I2S_RX_FIFO_LEVEL_ALMOST_FULL = I2S_IFLS_RXIFLSEL_LVL_ALMOST_FULL,
DL_I2S_RX_FIFO_LEVEL_ONE_ENTRY = I2S_IFLS_RXIFLSEL_LVL_ALMOST_EMPTY
}
enum DL_I2S_IIDX {
DL_I2S_IIDX_NO_INT = I2S_IIDX_STAT_NO_INTR,
DL_I2S_IIDX_WCLK_ERR = I2S_IIDX_STAT_WCLKERR,
DL_I2S_IIDX_RX_DONE = I2S_IIDX_STAT_RXIFG,
DL_I2S_IIDX_TX_DONE = I2S_IIDX_STAT_TXIFG,
DL_I2S_IIDX_RXFIFO_OVERFLOW = I2S_IIDX_STAT_RXFIFO_OVF_EVT,
DL_I2S_IIDX_TXFIFO_UNDERFLOW = I2S_IIDX_STAT_TXFIFO_UNF_EVT,
DL_I2S_IIDX_DMA_DONE_RX = I2S_IIDX_STAT_DMA_DONE_RX,
DL_I2S_IIDX_DMA_DONE_TX = I2S_IIDX_STAT_DMA_DONE_TX
}
Functions
void DL_I2S_setClockConfig (I2S_Regs *i2s, const DL_I2S_ClockConfig *config)
Configure I2S audio clocks (WCLK and BCLK)
void DL_I2S_getClockConfig (const I2S_Regs *i2s, DL_I2S_ClockConfig *config)
Get I2S audio clocks configuration (WCLK and BCLK)
void DL_I2S_init (I2S_Regs *i2s, const DL_I2S_Config *config)
Initialize the I2S peripheral.
__STATIC_INLINE void DL_I2S_transmitData8 (I2S_Regs *i2s, uint8_t data)
Writes 8-bit data into the TX FIFO for transmit.
__STATIC_INLINE void DL_I2S_transmitData16 (I2S_Regs *i2s, uint16_t data)
Writes 16-bit data into the TX FIFO for transmit.
__STATIC_INLINE void DL_I2S_transmitData32 (I2S_Regs *i2s, uint32_t data)
Writes 32-bit data into the TX FIFO for transmit.
__STATIC_INLINE uint8_t DL_I2S_receiveData8 (const I2S_Regs *i2s)
Reads 8-bit data from the RX FIFO.
__STATIC_INLINE uint16_t DL_I2S_receiveData16 (const I2S_Regs *i2s)
Reads 16-bit data from the RX FIFO.
__STATIC_INLINE uint32_t DL_I2S_receiveData32 (const I2S_Regs *i2s)
Reads 32-bit data from the RX FIFO.
void DL_I2S_transmitDataBlocking8 (I2S_Regs *i2s, uint8_t data)
Blocks to ensure transmit is ready before sending data.
void DL_I2S_transmitDataBlocking16 (I2S_Regs *i2s, uint16_t data)
Blocks to ensure transmit is ready before sending data.
void DL_I2S_transmitDataBlocking32 (I2S_Regs *i2s, uint32_t data)
Blocks to ensure transmit is ready before sending data.
uint8_t DL_I2S_receiveDataBlocking8 (const I2S_Regs *i2s)
Blocks to ensure receive is ready before reading data.
uint16_t DL_I2S_receiveDataBlocking16 (const I2S_Regs *i2s)
Blocks to ensure receive is ready before reading data.
uint32_t DL_I2S_receiveDataBlocking32 (const I2S_Regs *i2s)
Blocks to ensure receive is ready before reading data.
bool DL_I2S_transmitDataCheck8 (I2S_Regs *i2s, uint8_t data)
Checks the TX FIFO before trying to transmit data.
bool DL_I2S_transmitDataCheck16 (I2S_Regs *i2s, uint16_t data)
Checks the TX FIFO before trying to transmit data.
bool DL_I2S_transmitDataCheck32 (I2S_Regs *i2s, uint32_t data)
Checks the TX FIFO before trying to transmit data.
bool DL_I2S_receiveDataCheck8 (const I2S_Regs *i2s, uint8_t *buffer)
Checks the RX FIFO before trying to receive data.
bool DL_I2S_receiveDataCheck16 (const I2S_Regs *i2s, uint16_t *buffer)
Checks the RX FIFO before trying to receive data.
bool DL_I2S_receiveDataCheck32 (const I2S_Regs *i2s, uint32_t *buffer)
Checks the RX FIFO before trying to receive data.
uint32_t DL_I2S_drainRXFIFO8 (const I2S_Regs *i2s, uint8_t *buffer, uint32_t maxCount)
Read all available data out of the RX FIFO using 8 bit access.
uint32_t DL_I2S_drainRXFIFO16 (const I2S_Regs *i2s, uint16_t *buffer, uint32_t maxCount)
Read all available data out of the RX FIFO using 16 bit access.
uint32_t DL_I2S_drainRXFIFO32 (const I2S_Regs *i2s, uint32_t *buffer, uint32_t maxCount)
Read all available data out of the RX FIFO using 32 bit access.
uint32_t DL_I2S_fillTXFIFO8 (I2S_Regs *i2s, const uint8_t *buffer, uint32_t count)
Fill the TX FIFO using 8 bit access.
uint32_t DL_I2S_fillTXFIFO16 (I2S_Regs *i2s, const uint16_t *buffer, uint32_t count)
Fill the TX FIFO using 16 bit access.
uint32_t DL_I2S_fillTXFIFO32 (I2S_Regs *i2s, const uint32_t *buffer, uint32_t count)
Fill the TX FIFO using 32 bit access.
void DL_I2S_clearTXFIFO (I2S_Regs *i2s)
Clears contents of TX FIFO.
void DL_I2S_clearRXFIFO (I2S_Regs *i2s)
Clears contents of RX FIFO.
__STATIC_INLINE bool DL_I2S_isTXFIFOFull (const I2S_Regs *i2s)
Checks if TX FIFO is full.
__STATIC_INLINE bool DL_I2S_isTXFIFOEmpty (const I2S_Regs *i2s)
Checks if TX FIFO is empty.
__STATIC_INLINE bool DL_I2S_isRXFIFOFull (const I2S_Regs *i2s)
Checks if RX FIFO is full.
__STATIC_INLINE bool DL_I2S_isRXFIFOEmpty (const I2S_Regs *i2s)
Checks if RX FIFO is empty.
__STATIC_INLINE void DL_I2S_enablePower (I2S_Regs *i2s)
Enables the Peripheral Write Enable (PWREN) register for the I2S.
__STATIC_INLINE void DL_I2S_disablePower (I2S_Regs *i2s)
Disables the Peripheral Write Enable (PWREN) register for the I2S.
__STATIC_INLINE bool DL_I2S_isPowerEnabled (const I2S_Regs *i2s)
Returns if the Peripheral Write Enable (PWREN) register for the I2S is enabled.
__STATIC_INLINE void DL_I2S_reset (I2S_Regs *i2s)
Resets I2S peripheral.
__STATIC_INLINE bool DL_I2S_isReset (const I2S_Regs *i2s)
Returns if I2S peripheral was reset.
__STATIC_INLINE void DL_I2S_enable (I2S_Regs *i2s)
Enable the I2S peripheral.
__STATIC_INLINE void DL_I2S_disable (I2S_Regs *i2s)
Disable the I2S peripheral.
__STATIC_INLINE bool DL_I2S_isEnabled (const I2S_Regs *i2s)
Checks if the I2S peripheral is enabled.
__STATIC_INLINE void DL_I2S_enableFreeRun (I2S_Regs *i2s)
Enable free run control.
__STATIC_INLINE void DL_I2S_disableFreeRun (I2S_Regs *i2s)
Disable free run control.
__STATIC_INLINE bool DL_I2S_isFreeRunEnabled (const I2S_Regs *i2s)
Returns if free run control is enabled.
DL_I2S_MODE DL_I2S_getMode (const I2S_Regs *i2s)
Get the current mode for the I2S (controller/target)
void DL_I2S_setMode (I2S_Regs *i2s, DL_I2S_MODE mode)
Set whether the device should be in controller/target mode.
__STATIC_INLINE void DL_I2S_enableWBCLKGeneration (I2S_Regs *i2s)
Enable WCLK and BCLK generation.
__STATIC_INLINE void DL_I2S_disableWBCLKGeneration (I2S_Regs *i2s)
Disable WCLK and BCLK generation.
__STATIC_INLINE bool DL_I2S_isWBCLKGenerationEnabled (const I2S_Regs *i2s)
Returns if WCLK and BCLK generation is enabled.
__STATIC_INLINE void DL_I2S_enableMCLKGeneration (I2S_Regs *i2s)
Enable MCLK generation.
__STATIC_INLINE void DL_I2S_disableMCLKGeneration (I2S_Regs *i2s)
Disable MCLK generation.
__STATIC_INLINE bool DL_I2S_isMCLKGenerationEnabled (const I2S_Regs *i2s)
Returns if MCLK generation is enabled.
__STATIC_INLINE DL_I2S_WORD_BAUD_CLOCK_SOURCE DL_I2S_getWBCLKSource (const I2S_Regs *i2s)
Get source of WCLK and BCLK.
__STATIC_INLINE void DL_I2S_setWBCLKSource (I2S_Regs *i2s, DL_I2S_WORD_BAUD_CLOCK_SOURCE clockSource)
Set source of WCLK and BCLK.
__STATIC_INLINE DL_I2S_WCLK_INVERSION DL_I2S_getWCLKInversion (const I2S_Regs *i2s)
Get WCLK inversion status.
__STATIC_INLINE void DL_I2S_setWCLKInversion (I2S_Regs *i2s, DL_I2S_WCLK_INVERSION wclkInversion)
Invert WCLK.
__STATIC_INLINE DL_I2S_WCLK_PHASE DL_I2S_getWCLKPhase (const I2S_Regs *i2s)
Get WCLK phase.
__STATIC_INLINE void DL_I2S_setWCLKPhase (I2S_Regs *i2s, DL_I2S_WCLK_PHASE wclkPhase)
Set WCLK phase.
__STATIC_INLINE void DL_I2S_setMCLKDivider (I2S_Regs *i2s, uint32_t mclkDivider)
Set MCLK divider.
__STATIC_INLINE uint32_t DL_I2S_getMCLKDivider (const I2S_Regs *i2s)
Get MCLK divider.
__STATIC_INLINE void DL_I2S_setWCLKDivider (I2S_Regs *i2s, uint32_t wclkDivider)
Set WCLK divider.
__STATIC_INLINE uint32_t DL_I2S_getWCLKDivider (const I2S_Regs *i2s)
Get WCLK divider.
__STATIC_INLINE void DL_I2S_setBCLKDivider (I2S_Regs *i2s, uint32_t bclkDivider)
Set BCLK divider.
__STATIC_INLINE uint32_t DL_I2S_getBCLKDivider (const I2S_Regs *i2s)
Get BCLK divider.
__STATIC_INLINE void DL_I2S_setSampleWordLength (I2S_Regs *i2s, uint32_t sampleWordLength)
Sets the sample word length in bits. In single-phase format, this is the exact number of bits per word. In dual-phase format, this is the maximum number of bits per word.
__STATIC_INLINE uint32_t DL_I2S_getSampleWordLength (const I2S_Regs *i2s)
Get the sample word length in bits.
__STATIC_INLINE void DL_I2S_setFormatPhase (I2S_Regs *i2s, DL_I2S_PHASE phase)
Set between single or dual-phase format.
__STATIC_INLINE DL_I2S_PHASE DL_I2S_getFormatPhase (const I2S_Regs *i2s)
Get the sampling phase being used.
__STATIC_INLINE void DL_I2S_setSampleEdge (I2S_Regs *i2s, DL_I2S_SAMPLE_EDGE edge)
Set the sample edge of data on BCLK.
__STATIC_INLINE DL_I2S_SAMPLE_EDGE DL_I2S_getSampleEdge (const I2S_Regs *i2s)
Gets the sample edge being used.
__STATIC_INLINE void DL_I2S_setMemoryLength (I2S_Regs *i2s, DL_I2S_MEMORY_LENGTH length)
Set the size of each sample word stored to or loaded from memory.
__STATIC_INLINE DL_I2S_MEMORY_LENGTH DL_I2S_getMemoryLength (const I2S_Regs *i2s)
Get the size of sample words stored to or loaded from memory.
__STATIC_INLINE void DL_I2S_setDataDelay (I2S_Regs *i2s, DL_I2S_DATA_DELAY dataDelay)
Set the number of BCLK periods to wait between a WCLK edge and the MSB of the first word in a phase.
__STATIC_INLINE DL_I2S_DATA_DELAY DL_I2S_getDataDelay (const I2S_Regs *i2s)
Gets the data delay being used.
__STATIC_INLINE void DL_I2S_setEmptySlotOutput (I2S_Regs *i2s, DL_I2S_EMPTY_SLOT_OUTPUT output)
Set the data pin behavior during empty slots.
__STATIC_INLINE DL_I2S_EMPTY_SLOT_OUTPUT DL_I2S_getEmptySlotOutput (const I2S_Regs *i2s)
Get the data pin behavior during empty slots.
__STATIC_INLINE void DL_I2S_setDataPinsDirection (I2S_Regs *i2s, DL_I2S_DATA_PIN_DIRECTION dataPin0Direction, DL_I2S_DATA_PIN_DIRECTION dataPin1Direction)
Set the direction of the data pins.
__STATIC_INLINE void DL_I2S_setDataPin0Direction (I2S_Regs *i2s, DL_I2S_DATA_PIN_DIRECTION direction)
Set the direction of data pin 0.
__STATIC_INLINE void DL_I2S_setDataPin1Direction (I2S_Regs *i2s, DL_I2S_DATA_PIN_DIRECTION direction)
Set the direction of data pin 1.
__STATIC_INLINE DL_I2S_DATA_PIN_DIRECTION DL_I2S_getDataPin0Direction (const I2S_Regs *i2s)
Get the direction of data pin 0.
__STATIC_INLINE DL_I2S_DATA_PIN_DIRECTION DL_I2S_getDataPin1Direction (const I2S_Regs *i2s)
Get the direction of data pin 1.
__STATIC_INLINE void DL_I2S_setDataPin0ChannelMask (I2S_Regs *i2s, uint32_t channelMask)
Set the valid channel mask of data pin 0.
__STATIC_INLINE void DL_I2S_setDataPin1ChannelMask (I2S_Regs *i2s, uint32_t channelMask)
Set the valid channel mask of data pin 1.
__STATIC_INLINE uint32_t DL_I2S_getDataPin0ChannelMask (const I2S_Regs *i2s)
Get the valid channel mask of data pin 0.
__STATIC_INLINE uint32_t DL_I2S_getDataPin1ChannelMask (const I2S_Regs *i2s)
Get the valid channel mask of data pin 1.
__STATIC_INLINE DL_I2S_TX_FIFO_LEVEL DL_I2S_getTXFIFOThreshold (const I2S_Regs *i2s)
Get TX FIFO threshold level.
__STATIC_INLINE void DL_I2S_setTXFIFOThreshold (I2S_Regs *i2s, DL_I2S_TX_FIFO_LEVEL level)
Set TX FIFO threshold level.
__STATIC_INLINE DL_I2S_RX_FIFO_LEVEL DL_I2S_getRXFIFOThreshold (const I2S_Regs *i2s)
Get RX FIFO threshold level.
__STATIC_INLINE void DL_I2S_setRXFIFOThreshold (I2S_Regs *i2s, DL_I2S_RX_FIFO_LEVEL level)
Set RX FIFO threshold level.
__STATIC_INLINE bool DL_I2S_isRXFIFOClearComplete (const I2S_Regs *i2s)
Checks if RX FIFO clear is complete.
__STATIC_INLINE bool DL_I2S_isTXFIFOClearComplete (const I2S_Regs *i2s)
Checks if TX FIFO clear is complete.
__STATIC_INLINE void DL_I2S_enableInterrupt (I2S_Regs *i2s, uint32_t interruptMask)
Enable I2S interrupts.
__STATIC_INLINE void DL_I2S_disableInterrupt (I2S_Regs *i2s, uint32_t interruptMask)
Disable I2S interrupts.
__STATIC_INLINE uint32_t DL_I2S_getEnabledInterrupts (const I2S_Regs *i2s, uint32_t interruptMask)
Check which I2S interrupts are enabled.
__STATIC_INLINE uint32_t DL_I2S_getEnabledInterruptStatus (const I2S_Regs *i2s, uint32_t interruptMask)
Check interrupt flag of enabled I2S interrupts.
__STATIC_INLINE uint32_t DL_I2S_getRawInterruptStatus (const I2S_Regs *i2s, uint32_t interruptMask)
Check interrupt flag of any I2S interrupt.
__STATIC_INLINE DL_I2S_IIDX DL_I2S_getPendingInterrupt (const I2S_Regs *i2s)
Get highest priority pending I2S interrupt.
__STATIC_INLINE void DL_I2S_clearInterruptStatus (I2S_Regs *i2s, uint32_t interruptMask)
Clear pending I2S interrupts.
__STATIC_INLINE void DL_I2S_enableDMAReceiveEvent (I2S_Regs *i2s, uint32_t interrupt)
Enables I2S interrupt for triggering the DMA receive event.
__STATIC_INLINE void DL_I2S_enableDMATransmitEvent (I2S_Regs *i2s, uint32_t interrupt)
Enables I2S interrupt for triggering the DMA transmit event.
__STATIC_INLINE void DL_I2S_disableDMAReceiveEvent (I2S_Regs *i2s, uint32_t interrupt)
Disables I2S interrupt from triggering the DMA receive event.
__STATIC_INLINE void DL_I2S_disableDMATransmitEvent (I2S_Regs *i2s, uint32_t interrupt)
Disables I2S interrupt from triggering the DMA transmit event.
__STATIC_INLINE uint32_t DL_I2S_getEnabledDMAReceiveEvent (const I2S_Regs *i2s, uint32_t interruptMask)
Check which I2S interrupt for DMA receive events is enabled.
__STATIC_INLINE uint32_t DL_I2S_getEnabledDMATransmitEvent (const I2S_Regs *i2s, uint32_t interruptMask)
Check which I2S interrupt for DMA transmit events is enabled.
__STATIC_INLINE uint32_t DL_I2S_getEnabledDMAReceiveEventStatus (const I2S_Regs *i2s, uint32_t interruptMask)
Check interrupt flag of enabled I2S interrupt for DMA receive event.
__STATIC_INLINE uint32_t DL_I2S_getEnabledDMATransmitEventStatus (const I2S_Regs *i2s, uint32_t interruptMask)
Check interrupt flag of enabled I2S interrupt for DMA transmit event.
__STATIC_INLINE uint32_t DL_I2S_getRawDMAReceiveEventStatus (const I2S_Regs *i2s, uint32_t interruptMask)
Check interrupt flag of any I2S interrupt for DMA receive event.
__STATIC_INLINE uint32_t DL_I2S_getRawDMATransmitEventStatus (const I2S_Regs *i2s, uint32_t interruptMask)
Check interrupt flag of any I2S interrupt for DMA transmit event.
__STATIC_INLINE void DL_I2S_suspend (I2S_Regs *i2s)
Suspend external communication.
__STATIC_INLINE void DL_I2S_resume (I2S_Regs *i2s)
Resume functional mode.
__STATIC_INLINE void DL_I2S_setClockSource (I2S_Regs *i2s, DL_I2S_CLOCK_SOURCE clockSource)
Set the clock source for the I2S peripheral.
__STATIC_INLINE DL_I2S_CLOCK_SOURCE DL_I2S_getClockSource (const I2S_Regs *i2s)
Get I2S audio clock configuration.
Detailed Description
Overview
The I2S Library allows full configuration of the MSPM0 I2S module. The I2S module provides a standardized serial interface to transfer audio data between MSP devices and other external devices (such as an audio amplifier).
Enumeration Type Documentation
DL_I2S_WORD_BAUD_CLOCK_SOURCE
enum DL_I2S_WORD_BAUD_CLOCK_SOURCE
Enumerator
DL_I2S_WORD_BAUD_CLOCK_SOURCE_NONE
No source for audio clocks WCLK and BCLK
DL_I2S_WORD_BAUD_CLOCK_SOURCE_EXTERNAL
External source for audio clocks WCLK and BCLK from pin
DL_I2S_WORD_BAUD_CLOCK_SOURCE_INTERNAL
Internal source for audio clocks WCLK and BCLK from module PRCM
DL_I2S_CLOCK_SOURCE
enum DL_I2S_CLOCK_SOURCE
Enumerator
DL_I2S_CLOCK_SOURCE_SYSOSC
Select SYSOSC as the clock source for I2S
DL_I2S_CLOCK_SOURCE_HFXT
Select HFXT as the clock source for I2S
DL_I2S_CLOCK_SOURCE_PLL
Select PLL as the clock source for I2S
DL_I2S_WCLK_INVERSION
enum DL_I2S_WCLK_INVERSION
Enumerator
DL_I2S_WCLK_INVERSION_DISABLED
WCLK is not inverted
DL_I2S_WCLK_INVERSION_ENABLED
WCLK is inverted
DL_I2S_PHASE
enum DL_I2S_PHASE
Enumerator
DL_I2S_PHASE_SINGLE
I2S Single-Phase (DSP format)
DL_I2S_PHASE_DUAL
I2S Dual-Phase (I2S, LJF and RJF)
DL_I2S_SAMPLE_EDGE
enum DL_I2S_SAMPLE_EDGE
Enumerator
DL_I2S_SAMPLE_EDGE_NEG
Data sampled on negative edge, clocked out on positive edge
DL_I2S_SAMPLE_EDGE_POS
Data sampled on positive edge, clocked out on negative edge
DL_I2S_MEMORY_LENGTH
enum DL_I2S_MEMORY_LENGTH
Enumerator
DL_I2S_MEMORY_LENGTH_16_BIT
16-bit memory access per sample
DL_I2S_MEMORY_LENGTH_32_BIT
32-bit memory access per sample
DL_I2S_DATA_DELAY
enum DL_I2S_DATA_DELAY
Enumerator
DL_I2S_DATA_DELAY_ZERO
Zero BCLK period delay between WCLK edge and MSB of first word
DL_I2S_DATA_DELAY_ONE
One BCLK period delay between WCLK edge and MSB of first word
DL_I2S_DATA_DELAY_TWO
Two BCLK periods delay between WCLK edge and MSB of first word
DL_I2S_DATA_DELAY_MAX
Max BCLK periods delay between WCLK edge and MSB of first word
DL_I2S_EMPTY_SLOT_OUTPUT
enum DL_I2S_EMPTY_SLOT_OUTPUT
Enumerator
DL_I2S_EMPTY_SLOT_OUTPUT_ZERO
Send out zeroes in empty slots
DL_I2S_EMPTY_SLOT_OUTPUT_ONE
Send out ones in empty slots
DL_I2S_EMPTY_SLOT_OUTPUT_TRISTATE
Tristate data pin line during empty slot
DL_I2S_WCLK_PHASE
enum DL_I2S_WCLK_PHASE
Enumerator
DL_I2S_WCLK_PHASE_SINGLE
Calculate WCLK division ratio for single phase operation
DL_I2S_WCLK_PHASE_DUAL
Calculate WCLK division ratio for dual phase operation
DL_I2S_WCLK_PHASE_CUSTOM
Calculate user-defined custom WCLK division ratio
DL_I2S_MODE
enum DL_I2S_MODE
Enumerator
DL_I2S_MODE_CONTROLLER
I2S controller mode. Module outputs audio clock signals (WCLK, BCLK)
DL_I2S_MODE_TARGET
I2S target mode. Audio clock signals are inputs (WCLK, BCLK)
DL_I2S_DATA_PIN_DIRECTION
enum DL_I2S_DATA_PIN_DIRECTION
Enumerator
DL_I2S_DATA_PIN_DIRECTION_UNUSED
Data pin not in use (disabled)
DL_I2S_DATA_PIN_DIRECTION_INPUT
Data pin acts as input
DL_I2S_DATA_PIN_DIRECTION_OUTPUT
Data pin acts as output
DL_I2S_TX_FIFO_LEVEL
enum DL_I2S_TX_FIFO_LEVEL
Enumerator
DL_I2S_TX_FIFO_LEVEL_3_4_EMPTY
Trigger when the TX FIFO <= 3/4 empty
DL_I2S_TX_FIFO_LEVEL_1_2_EMPTY
Trigger when TX FIFO <= 1/2 empty (default)
DL_I2S_TX_FIFO_LEVEL_1_4_EMPTY
Trigger when TX FIFO <= 1/4 empty
DL_I2S_TX_FIFO_LEVEL_EMPTY
Trigger when TX FIFO is empty
DL_I2S_TX_FIFO_LEVEL_ONE_ENTRY
Trigger when TX FIFO <= 1
DL_I2S_TX_FIFO_LEVEL_ALMOST_FULL
Trigger when TX FIFO >= (MAX_FIFO_LEN - 1)
DL_I2S_RX_FIFO_LEVEL
enum DL_I2S_RX_FIFO_LEVEL
Enumerator
DL_I2S_RX_FIFO_LEVEL_1_4_FULL
Trigger when RX FIFO >= 1/4 full
DL_I2S_RX_FIFO_LEVEL_1_2_FULL
Trigger when RX FIFO >= 1/2 full (default)
DL_I2S_RX_FIFO_LEVEL_3_4_FULL
Trigger when RX FIFO >= 3/4 full
DL_I2S_RX_FIFO_LEVEL_FULL
Trigger when RX FIFO is full
DL_I2S_RX_FIFO_LEVEL_ALMOST_FULL
Trigger when RX FIFO >= (MAX_FIFO_LEN - 1)
DL_I2S_RX_FIFO_LEVEL_ONE_ENTRY
Trigger when RX FIFO <= 1
DL_I2S_IIDX
enum DL_I2S_IIDX
Enumerator
DL_I2S_IIDX_NO_INT
Interrupt index for I2S if no interrupt is pending
DL_I2S_IIDX_WCLK_ERR
Interrupt index for I2S WCLK Error
DL_I2S_IIDX_RX_DONE
Interrupt index for I2S Receive Interrupt
DL_I2S_IIDX_TX_DONE
Interrupt index for I2S Transmit Interrupt
DL_I2S_IIDX_RXFIFO_OVERFLOW
Interrupt index for I2S RXFIFO Overflow Event
DL_I2S_IIDX_TXFIFO_UNDERFLOW
Interrupt index for I2S TXFIFO Underflow Event
DL_I2S_IIDX_DMA_DONE_RX
Interrupt index for DMA Done on RX
DL_I2S_IIDX_DMA_DONE_TX
Interrupt index for DMA Done on TX
Function Documentation
DL_I2S_setClockConfig()
void DL_I2S_setClockConfig (I2S_Regs * i2s, const DL_I2S_ClockConfig * config)
Configure I2S audio clocks (WCLK and BCLK)
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] config Pointer to the clock configuration struct DL_I2S_ClockConfig.
DL_I2S_getClockConfig()
void DL_I2S_getClockConfig (const I2S_Regs * i2s, DL_I2S_ClockConfig * config)
Get I2S audio clocks configuration (WCLK and BCLK)
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[out] config Pointer to the clock configuration struct DL_I2S_ClockConfig.
DL_I2S_init()
void DL_I2S_init (I2S_Regs * i2s, const DL_I2S_Config * config)
Initialize the I2S peripheral.
Initializes all the common configurable options for the I2S peripheral. Any other custom configuration can be done after calling this API. The I2S is not enabled in this API.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] config Configuration for I2S peripheral
DL_I2S_transmitData8()
__STATIC_INLINE void DL_I2S_transmitData8 (I2S_Regs * i2s, uint8_t data)
Writes 8-bit data into the TX FIFO for transmit.
Puts the data into the TX FIFO without checking its status. Use if already sure the TX FIFO has space for the write. See related APIs for additional transmit options.
Can be used for any data transfers that are less than or equal to 8 bits.
Parameters
[in] i2s pointer to the register overlay for the peripheral
[in] data data to send
See also
DL_I2S_transmitDataBlocking8
DL_I2S_transmitDataCheck8
DL_I2S_transmitData16()
__STATIC_INLINE void DL_I2S_transmitData16 (I2S_Regs * i2s, uint16_t data)
Writes 16-bit data into the TX FIFO for transmit.
Puts the data into the TX FIFO without checking its status. Use if already sure the TX FIFO has space for the write. See related APIs for additional transmit options.
Can be used for any data transfers that are less than or equal to 16 bits.
Parameters
[in] i2s pointer to the register overlay for the peripheral
[in] data data to send
See also
DL_I2S_transmitDataBlocking16
DL_I2S_transmitDataCheck16
DL_I2S_transmitData32()
__STATIC_INLINE void DL_I2S_transmitData32 (I2S_Regs * i2s, uint32_t data)
Writes 32-bit data into the TX FIFO for transmit.
Puts the data into the TX FIFO without checking its status. Use if already sure the TX FIFO has space for the write. See related APIs for additional transmit options.
Can be used for any data transfers that are less than or equal to 32 bits.
NOTE: A 32-bit write will be written as one FIFO entry. The application can choose to pack two 16-bit frames into one word.
Parameters
[in] i2s pointer to the register overlay for the peripheral
[in] data data to send
See also
DL_I2S_transmitDataBlocking32
DL_I2S_transmitDataCheck32
DL_I2S_receiveData8()
__STATIC_INLINE uint8_t DL_I2S_receiveData8 (const I2S_Regs * i2s)
Reads 8-bit data from the RX FIFO.
Reads the data from the RX FIFO without checking its status. Use if already sure the RX FIFO has data available. See related APIs for additional receive options.
Can be used for any data transfers that are less than or equal to 8 bits.
Parameters
[in] i2s pointer to the register overlay for the peripheral
Returns
The data in the RX FIFO
See also
DL_I2S_receiveDataBlocking8
DL_I2S_receiveDataCheck8
DL_I2S_receiveData16()
__STATIC_INLINE uint16_t DL_I2S_receiveData16 (const I2S_Regs * i2s)
Reads 16-bit data from the RX FIFO.
Reads the data from the RX FIFO without checking its status. Use if already sure the RX FIFO has data available. See related APIs for additional receive options.
Can be used for any data transfers that are less than or equal to 16 bits.
Parameters
[in] i2s pointer to the register overlay for the peripheral
Returns
The data in the RX FIFO
See also
DL_I2S_receiveDataBlocking16
DL_I2S_receiveDataCheck16
DL_I2S_receiveData32()
__STATIC_INLINE uint32_t DL_I2S_receiveData32 (const I2S_Regs * i2s)
Reads 32-bit data from the RX FIFO.
Reads the data from the RX FIFO without checking its status. Use if already sure the RX FIFO has data available. See related APIs for additional receive options.
Can be used for any data transfers that are less than or equal to 32 bits.
Parameters
[in] i2s pointer to the register overlay for the peripheral
Returns
The data in the RX FIFO
See also
DL_I2S_receiveDataBlocking32
DL_I2S_receiveDataCheck32
References DL_I2S_clearRXFIFO(), DL_I2S_clearTXFIFO(), DL_I2S_drainRXFIFO16(), DL_I2S_drainRXFIFO32(), DL_I2S_drainRXFIFO8(), DL_I2S_fillTXFIFO16(), DL_I2S_fillTXFIFO32(), DL_I2S_fillTXFIFO8(), DL_I2S_receiveDataBlocking16(), DL_I2S_receiveDataBlocking32(), DL_I2S_receiveDataBlocking8(), DL_I2S_receiveDataCheck16(), DL_I2S_receiveDataCheck32(), DL_I2S_receiveDataCheck8(), DL_I2S_transmitDataBlocking16(), DL_I2S_transmitDataBlocking32(), DL_I2S_transmitDataBlocking8(), DL_I2S_transmitDataCheck16(), DL_I2S_transmitDataCheck32(), and DL_I2S_transmitDataCheck8().
DL_I2S_transmitDataBlocking8()
void DL_I2S_transmitDataBlocking8 (I2S_Regs * i2s, uint8_t data)
Blocks to ensure transmit is ready before sending data.
Puts the data into the TX FIFO after blocking to ensure the TX FIFO is not full. Will wait indefinitely until there is space in the TX FIFO. See related APIs for additional transmit options.
Can be used for any data transfers that are less than or equal to 8 bits.
Parameters
[in] i2s pointer to the register overlay for the peripheral
[in] data data to send
See also
DL_I2S_transmitData8
DL_I2S_transmitDataCheck8
Referenced by DL_I2S_receiveData32().
DL_I2S_transmitDataBlocking16()
void DL_I2S_transmitDataBlocking16 (I2S_Regs * i2s, uint16_t data)
Blocks to ensure transmit is ready before sending data.
Puts the data into the TX FIFO after blocking to ensure the TX FIFO is not full. Will wait indefinitely until there is space in the TX FIFO. See related APIs for additional transmit options.
Can be used for any data transfers that are less than or equal to 16 bits.
Parameters
[in] i2s pointer to the register overlay for the peripheral
[in] data data to send
See also
DL_I2S_transmitData16
DL_I2S_transmitDataCheck16
Referenced by DL_I2S_receiveData32().
DL_I2S_transmitDataBlocking32()
void DL_I2S_transmitDataBlocking32 (I2S_Regs * i2s, uint32_t data)
Blocks to ensure transmit is ready before sending data.
Puts the data into the TX FIFO after blocking to ensure the TX FIFO is not full. Will wait indefinitely until there is space in the TX FIFO. See related APIs for additional transmit options.
Can be used for any data transfers that are less than or equal to 32 bits.
NOTE: A 32-bit write will be written as one FIFO entry. The application can choose to pack two 16-bit frames into one word.
Parameters
[in] i2s pointer to the register overlay for the peripheral
[in] data data to send
See also
DL_I2S_transmitData32
DL_I2S_transmitDataCheck32
Referenced by DL_I2S_receiveData32().
DL_I2S_receiveDataBlocking8()
uint8_t DL_I2S_receiveDataBlocking8 (const I2S_Regs * i2s)
Blocks to ensure receive is ready before reading data.
Reads the data from the RX FIFO after blocking to ensure the RX FIFO is not empty. Will wait indefinitely until there is data in the RX FIFO. See related APIs for additional receive options.
Can be used for any data transfers that are less than or equal to 8 bits.
Parameters
[in] i2s pointer to the register overlay for the peripheral
Returns
The data in the RX FIFO
See also
DL_I2S_receiveData16
DL_I2S_receiveDataCheck16
Referenced by DL_I2S_receiveData32().
DL_I2S_receiveDataBlocking16()
uint16_t DL_I2S_receiveDataBlocking16 (const I2S_Regs * i2s)
Blocks to ensure receive is ready before reading data.
Reads the data from the RX FIFO after blocking to ensure the RX FIFO is not empty. Will wait indefinitely until there is data in the RX FIFO. See related APIs for additional receive options.
Can be used for any data transfers that are less than or equal to 16 bits.
Parameters
[in] i2s pointer to the register overlay for the peripheral
Returns
The data in the RX FIFO
See also
DL_I2S_receiveData16
DL_I2S_receiveDataCheck16
Referenced by DL_I2S_receiveData32().
DL_I2S_receiveDataBlocking32()
uint32_t DL_I2S_receiveDataBlocking32 (const I2S_Regs * i2s)
Blocks to ensure receive is ready before reading data.
Reads the data from the RX FIFO after blocking to ensure the RX FIFO is not empty. Will wait indefinitely until there is data in the RX FIFO. See related APIs for additional receive options.
Can be used for any data transfers that are less than or equal to 32 bits.
Parameters
[in] i2s pointer to the register overlay for the peripheral
Returns
The data in the RX FIFO
See also
DL_I2S_receiveData32
DL_I2S_receiveDataCheck32
Referenced by DL_I2S_receiveData32().
DL_I2S_transmitDataCheck8()
bool DL_I2S_transmitDataCheck8 (I2S_Regs * i2s, uint8_t data)
Checks the TX FIFO before trying to transmit data.
Checks if the TX FIFO is already full before trying to add new data to the FIFO. Exits immediately if full rather than trying to block. See related APIs for additional transmit options.
Can be used for any data transfers that are less than or equal to 8 bits.
Parameters
[in] i2s pointer to the register overlay for the peripheral
[in] data data to send
Returns
If the transmit occurred
Return values
true if data was added to the TX FIFO
false if the TX FIFO was full and data was not added
See also
DL_I2S_transmitData8
DL_I2S_transmitDataBlocking8
Referenced by DL_I2S_receiveData32().
DL_I2S_transmitDataCheck16()
bool DL_I2S_transmitDataCheck16 (I2S_Regs * i2s, uint16_t data)
Checks the TX FIFO before trying to transmit data.
Checks if the TX FIFO is already full before trying to add new data to the FIFO. Exits immediately if full rather than trying to block. See related APIs for additional transmit options.
Can be used for any data transfers that are less than or equal to 16 bits.
Parameters
[in] i2s pointer to the register overlay for the peripheral
[in] data data to send
Returns
If the transmit occurred
Return values
true if data was added to the TX FIFO
false if the TX FIFO was full and data was not added
See also
DL_I2S_transmitData16
DL_I2S_transmitDataBlocking16
Referenced by DL_I2S_receiveData32().
DL_I2S_transmitDataCheck32()
bool DL_I2S_transmitDataCheck32 (I2S_Regs * i2s, uint32_t data)
Checks the TX FIFO before trying to transmit data.
Checks if the TX FIFO is already full before trying to add new data to the FIFO. Exits immediately if full rather than trying to block. See related APIs for additional transmit options.
Can be used for any data transfers that are less than or equal to 32 bits.
NOTE: A 32-bit write will be written as one FIFO entry. The application can choose to pack two 16-bit frames into one word.
Parameters
[in] i2s pointer to the register overlay for the peripheral
[in] data data to send
Returns
If the transmit occurred
Return values
true if data was added to the TX FIFO
false if the TX FIFO was full and data was not added
See also
DL_I2S_transmitData32
DL_I2S_transmitDataBlocking32
Referenced by DL_I2S_receiveData32().
DL_I2S_receiveDataCheck8()
bool DL_I2S_receiveDataCheck8 (const I2S_Regs * i2s, uint8_t * buffer)
Checks the RX FIFO before trying to receive data.
Checks if the RX FIFO is already empty before trying to read new data from the FIFO. Exits immediately if empty rather than trying to block. See related APIs for additional receive options.
Can be used for any data transfers that are less than or equal to 8 bits.
Parameters
[in] i2s pointer to the register overlay for the peripheral
[out] buffer a buffer to write the received data into
Returns
If the receive occurred
Return values
true if data was read from the RX FIFO
false if the RX FIFO was empty and data was not read
See also
DL_I2S_receiveData8
DL_I2S_receiveDataBlocking8
Referenced by DL_I2S_receiveData32().
DL_I2S_receiveDataCheck16()
bool DL_I2S_receiveDataCheck16 (const I2S_Regs * i2s, uint16_t * buffer)
Checks the RX FIFO before trying to receive data.
Checks if the RX FIFO is already empty before trying to read new data from the FIFO. Exits immediately if empty rather than trying to block. See related APIs for additional receive options.
Can be used for any data transfers that are less than or equal to 16 bits.
Parameters
[in] i2s pointer to the register overlay for the peripheral
[out] buffer a buffer to write the received data into
Returns
If the receive occurred
Return values
true if data was read from the RX FIFO
false if the RX FIFO was empty and data was not read
See also
DL_I2S_receiveData16
DL_I2S_receiveDataBlocking16
Referenced by DL_I2S_receiveData32().
DL_I2S_receiveDataCheck32()
bool DL_I2S_receiveDataCheck32 (const I2S_Regs * i2s, uint32_t * buffer)
Checks the RX FIFO before trying to receive data.
Checks if the RX FIFO is already empty before trying to read new data from the FIFO. Exits immediately if empty rather than trying to block. See related APIs for additional receive options.
Can be used for any data transfers that are less than or equal to 32 bits.
Parameters
[in] i2s pointer to the register overlay for the peripheral
[out] buffer a buffer to write the received data into
Returns
If the receive occurred
Return values
true if data was read from the RX FIFO
false if the RX FIFO was empty and data was not read
See also
DL_I2S_receiveData32
DL_I2S_receiveDataBlocking32
Referenced by DL_I2S_receiveData32().
DL_I2S_drainRXFIFO8()
uint32_t DL_I2S_drainRXFIFO8 (const I2S_Regs * i2s, uint8_t * buffer, uint32_t maxCount)
Read all available data out of the RX FIFO using 8 bit access.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[out] buffer Buffer to write received data into
[in] maxCount Max number of halfwords to read from the RX FIFO
Returns
Number of bytes read from the RX FIFO
Referenced by DL_I2S_receiveData32().
DL_I2S_drainRXFIFO16()
uint32_t DL_I2S_drainRXFIFO16 (const I2S_Regs * i2s, uint16_t * buffer, uint32_t maxCount)
Read all available data out of the RX FIFO using 16 bit access.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[out] buffer Buffer to write received data into
[in] maxCount Max number of halfwords to read from the RX FIFO
Returns
Number of halfwords read from the RX FIFO
Referenced by DL_I2S_receiveData32().
DL_I2S_drainRXFIFO32()
uint32_t DL_I2S_drainRXFIFO32 (const I2S_Regs * i2s, uint32_t * buffer, uint32_t maxCount)
Read all available data out of the RX FIFO using 32 bit access.
NOTE: A 32-bit write will be written as one FIFO entry. The application can choose to pack two 16-bit frames into one word.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[out] buffer Buffer to write received data into
[in] maxCount Max number of words to read from the RX FIFO
Returns
Number of words read from the RX FIFO
Referenced by DL_I2S_receiveData32().
DL_I2S_fillTXFIFO8()
uint32_t DL_I2S_fillTXFIFO8 (I2S_Regs * i2s, const uint8_t * buffer, uint32_t count)
Fill the TX FIFO using 8 bit access.
Continuously write data into the TX FIFO until it is filled up or count has been reached.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] buffer Buffer of data to write to the TX FIFO
[in] count Max number of halfwords to write to the TX FIFO
Returns
Number of bytes written to the TX FIFO
Referenced by DL_I2S_receiveData32().
DL_I2S_fillTXFIFO16()
uint32_t DL_I2S_fillTXFIFO16 (I2S_Regs * i2s, const uint16_t * buffer, uint32_t count)
Fill the TX FIFO using 16 bit access.
Continuously write data into the TX FIFO until it is filled up or count has been reached.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] buffer Buffer of data to write to the TX FIFO
[in] count Max number of halfwords to write to the TX FIFO
Returns
Number of halfwords written to the TX FIFO
Referenced by DL_I2S_receiveData32().
DL_I2S_fillTXFIFO32()
uint32_t DL_I2S_fillTXFIFO32 (I2S_Regs * i2s, const uint32_t * buffer, uint32_t count)
Fill the TX FIFO using 32 bit access.
Continuously write data into the TX FIFO until it is filled up or count has been reached.
NOTE: A 32-bit write will be written as one FIFO entry. The application can choose to pack two 16-bit frames into one word.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] buffer Buffer of data to write to the TX FIFO
[in] count Max number of words to write to the TX FIFO
Returns
Number of words written to the TX FIFO
Referenced by DL_I2S_receiveData32().
DL_I2S_clearTXFIFO()
void DL_I2S_clearTXFIFO (I2S_Regs * i2s)
Clears contents of TX FIFO.
Note
When a FIFO clear has been initiated, do not try to re-clear again.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Referenced by DL_I2S_receiveData32().
DL_I2S_clearRXFIFO()
void DL_I2S_clearRXFIFO (I2S_Regs * i2s)
Clears contents of RX FIFO.
Note
When a FIFO clear has been initiated, do not try to re-clear again.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Referenced by DL_I2S_receiveData32().
DL_I2S_isTXFIFOFull()
__STATIC_INLINE bool DL_I2S_isTXFIFOFull (const I2S_Regs * i2s)
Checks if TX FIFO is full.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
If TX FIFO is full
Return values
true if TX FIFO is full
false if TX FIFO is not full
DL_I2S_isTXFIFOEmpty()
__STATIC_INLINE bool DL_I2S_isTXFIFOEmpty (const I2S_Regs * i2s)
Checks if TX FIFO is empty.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
If TX FIFO is empty
Return values
true if TX FIFO is empty
false if TX FIFO is not empty
DL_I2S_isRXFIFOFull()
__STATIC_INLINE bool DL_I2S_isRXFIFOFull (const I2S_Regs * i2s)
Checks if RX FIFO is full.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
If RX FIFO is full
Return values
true if RX FIFO is full
false if RX FIFO is not full
DL_I2S_isRXFIFOEmpty()
__STATIC_INLINE bool DL_I2S_isRXFIFOEmpty (const I2S_Regs * i2s)
Checks if RX FIFO is empty.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
If RX FIFO is empty
Return values
true if RX FIFO is empty
false if RX FIFO is not empty
DL_I2S_enablePower()
__STATIC_INLINE void DL_I2S_enablePower (I2S_Regs * i2s)
Enables the Peripheral Write Enable (PWREN) register for the I2S.
Before any peripheral registers can be configured by software, the peripheral itself must be enabled by writing the ENABLE bit together with the appropriate KEY value to the peripheral's PWREN register.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
DL_I2S_disablePower()
__STATIC_INLINE void DL_I2S_disablePower (I2S_Regs * i2s)
Disables the Peripheral Write Enable (PWREN) register for the I2S.
When the PWREN.ENABLE bit is cleared, the peripheral's registers are not accessible for read/write operations.
Note
This API does not provide large power savings. For power savings, please refer to DL_I2S_enable
Parameters
[in] i2s Pointer to the register overlay for the peripheral
DL_I2S_isPowerEnabled()
__STATIC_INLINE bool DL_I2S_isPowerEnabled (const I2S_Regs * i2s)
Returns if the Peripheral Write Enable (PWREN) register for the I2S is enabled.
Before any peripheral registers can be configured by software, the peripheral itself must be enabled by writing the ENABLE bit together with the appropriate KEY value to the peripheral's PWREN register.
When the PWREN.ENABLE bit is cleared, the peripheral's registers are not accessible for read/write operations.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
Whether power is enabled
Return values
true if peripheral register access is enabled
false if peripheral register access is disabled
DL_I2S_reset()
__STATIC_INLINE void DL_I2S_reset (I2S_Regs * i2s)
Resets I2S peripheral.
Parameters
i2s Pointer to the register overlay for the peripheral
DL_I2S_isReset()
__STATIC_INLINE bool DL_I2S_isReset (const I2S_Regs * i2s)
Returns if I2S peripheral was reset.
Parameters
i2s Pointer to the register overlay for the peripheral
Returns
Whether module was reset
Return values
true if module was reset
false if module wasn't reset
DL_I2S_enable()
__STATIC_INLINE void DL_I2S_enable (I2S_Regs * i2s)
Enable the I2S peripheral.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
DL_I2S_disable()
__STATIC_INLINE void DL_I2S_disable (I2S_Regs * i2s)
Disable the I2S peripheral.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
DL_I2S_isEnabled()
__STATIC_INLINE bool DL_I2S_isEnabled (const I2S_Regs * i2s)
Checks if the I2S peripheral is enabled.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
Returns the enabled status of the I2S
Return values
true The I2S peripheral is enabled
false The I2S peripheral is disabled
DL_I2S_enableFreeRun()
__STATIC_INLINE void DL_I2S_enableFreeRun (I2S_Regs * i2s)
Enable free run control.
When enabled, the module will continue to free run and ignores the state of the CPU halted debug state
Parameters
[in] i2s Pointer to the register overlay for the peripheral
References DL_Common_updateReg().
DL_I2S_disableFreeRun()
__STATIC_INLINE void DL_I2S_disableFreeRun (I2S_Regs * i2s)
Disable free run control.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
References DL_Common_updateReg().
DL_I2S_isFreeRunEnabled()
__STATIC_INLINE bool DL_I2S_isFreeRunEnabled (const I2S_Regs * i2s)
Returns if free run control is enabled.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
Whether free run is enabled
Return values
true if free run is enabled
false if free run is disabled
References DL_I2S_getMode(), and DL_I2S_setMode().
DL_I2S_getMode()
DL_I2S_MODE DL_I2S_getMode (const I2S_Regs * i2s)
Get the current mode for the I2S (controller/target)
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
The currently configured mode for I2S (controller/target)
Return values
One of DL_I2S_MODE
Referenced by DL_I2S_isFreeRunEnabled().
DL_I2S_setMode()
void DL_I2S_setMode (I2S_Regs * i2s, DL_I2S_MODE mode)
Set whether the device should be in controller/target mode.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] mode Mode to configure the I2S into. One of DL_I2S_MODE
See also
DL_I2S_init
Referenced by DL_I2S_isFreeRunEnabled().
DL_I2S_enableWBCLKGeneration()
__STATIC_INLINE void DL_I2S_enableWBCLKGeneration (I2S_Regs * i2s)
Enable WCLK and BCLK generation.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
DL_I2S_disableWBCLKGeneration()
__STATIC_INLINE void DL_I2S_disableWBCLKGeneration (I2S_Regs * i2s)
Disable WCLK and BCLK generation.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
DL_I2S_isWBCLKGenerationEnabled()
__STATIC_INLINE bool DL_I2S_isWBCLKGenerationEnabled (const I2S_Regs * i2s)
Returns if WCLK and BCLK generation is enabled.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
Whether clock generation is enabled
Return values
true if clock generation is enabled
false if clock generation is disabled
DL_I2S_enableMCLKGeneration()
__STATIC_INLINE void DL_I2S_enableMCLKGeneration (I2S_Regs * i2s)
Enable MCLK generation.
MCLK only applies when I2S is operating in controller mode. MCLK is an optional clock output signal
Parameters
[in] i2s Pointer to the register overlay for the peripheral
See also
DL_I2S_init
DL_I2S_setMode
DL_I2S_disableMCLKGeneration()
__STATIC_INLINE void DL_I2S_disableMCLKGeneration (I2S_Regs * i2s)
Disable MCLK generation.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
DL_I2S_isMCLKGenerationEnabled()
__STATIC_INLINE bool DL_I2S_isMCLKGenerationEnabled (const I2S_Regs * i2s)
Returns if MCLK generation is enabled.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
Whether clock generation is enabled
Return values
true if clock generation is enabled
false if clock generation is disabled
DL_I2S_getWBCLKSource()
__STATIC_INLINE DL_I2S_WORD_BAUD_CLOCK_SOURCE DL_I2S_getWBCLKSource (const I2S_Regs * i2s)
Get source of WCLK and BCLK.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
Source of WCLK and BCLK
Return values
One of DL_I2S_WORD_BAUD_CLOCK_SOURCE
DL_I2S_setWBCLKSource()
__STATIC_INLINE void DL_I2S_setWBCLKSource (I2S_Regs * i2s, DL_I2S_WORD_BAUD_CLOCK_SOURCE clockSource)
Set source of WCLK and BCLK.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] clockSource Source of WCLK and BCLK. One of DL_I2S_WORD_BAUD_CLOCK_SOURCE.
References DL_Common_updateReg().
DL_I2S_getWCLKInversion()
__STATIC_INLINE DL_I2S_WCLK_INVERSION DL_I2S_getWCLKInversion (const I2S_Regs * i2s)
Get WCLK inversion status.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
WCLK inversion status
Return values
One of DL_I2S_WCLK_INVERSION
DL_I2S_setWCLKInversion()
__STATIC_INLINE void DL_I2S_setWCLKInversion (I2S_Regs * i2s, DL_I2S_WCLK_INVERSION wclkInversion)
Invert WCLK.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] wclkInversion WCLK inversion status. One of DL_I2S_WCLK_INVERSION.
References DL_Common_updateReg().
DL_I2S_getWCLKPhase()
__STATIC_INLINE DL_I2S_WCLK_PHASE DL_I2S_getWCLKPhase (const I2S_Regs * i2s)
Get WCLK phase.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
WCLK phase
Return values
One of DL_I2S_WCLK_PHASE
DL_I2S_setWCLKPhase()
__STATIC_INLINE void DL_I2S_setWCLKPhase (I2S_Regs * i2s, DL_I2S_WCLK_PHASE wclkPhase)
Set WCLK phase.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] wclkPhase WCLK phase. One of DL_I2S_WCLK_PHASE.
References DL_Common_updateReg().
DL_I2S_setMCLKDivider()
__STATIC_INLINE void DL_I2S_setMCLKDivider (I2S_Regs * i2s, uint32_t mclkDivider)
Set MCLK divider.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] mclkDivider MCLK divider. [ DL_I2S_MDIV_MINIMUM, DL_I2S_MDIV_MAXIMUM ]
See also
DL_I2S_MDIV_INVALID
References DL_Common_updateReg().
DL_I2S_getMCLKDivider()
__STATIC_INLINE uint32_t DL_I2S_getMCLKDivider (const I2S_Regs * i2s)
Get MCLK divider.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
MCLK divider
Return values
[ DL_I2S_MDIV_MINIMUM, DL_I2S_MDIV_MAXIMUM ]
See also
DL_I2S_MDIV_INVALID
DL_I2S_setWCLKDivider()
__STATIC_INLINE void DL_I2S_setWCLKDivider (I2S_Regs * i2s, uint32_t wclkDivider)
Set WCLK divider.
Note
For single-phase and dual-phase frame formats, WDIV[9:0] are used for the clock calcuation, making 1023 the maximum factor of the division ratio.
For user-defined frame formats such as PCM (long) and TDM formats, WCLK is high for WDIV[7:0] and low for WDIV[15:8], making both high and low portions have a maximum factor of 255.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] wclkDivider WCLK divider to set. [0x1, 0xFFFF]
References DL_Common_updateReg().
DL_I2S_getWCLKDivider()
__STATIC_INLINE uint32_t DL_I2S_getWCLKDivider (const I2S_Regs * i2s)
Get WCLK divider.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
WCLK divider
Return values
[0x1,0xFFFF]
DL_I2S_setBCLKDivider()
__STATIC_INLINE void DL_I2S_setBCLKDivider (I2S_Regs * i2s, uint32_t bclkDivider)
Set BCLK divider.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] bclkDivider BCLK divider. [ DL_I2S_BDIV_MINIMUM, DL_I2S_BDIV_MAXIMUM ]
See also
DL_I2S_BDIV_INVALID
References DL_Common_updateReg().
DL_I2S_getBCLKDivider()
__STATIC_INLINE uint32_t DL_I2S_getBCLKDivider (const I2S_Regs * i2s)
Get BCLK divider.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
BCLK divider
Return values
[ DL_I2S_BDIV_MINIMUM, DL_I2S_BDIV_MAXIMUM ]
See also
DL_I2S_BDIV_INVALID
DL_I2S_setSampleWordLength()
__STATIC_INLINE void DL_I2S_setSampleWordLength (I2S_Regs * i2s, uint32_t sampleWordLength)
Sets the sample word length in bits. In single-phase format, this is the exact number of bits per word. In dual-phase format, this is the maximum number of bits per word.
Note
Values written to the hardware should be 1 less than the desired sample word length e.g. a desired sample word length of 8 bits requires the value of 7 to be written. Sample word lengths less than 8 and above 32 bits will result in undefined behavior.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] sampleWordLength Sample word length (in bits) to set. [7, 31]
References DL_Common_updateReg().
DL_I2S_getSampleWordLength()
__STATIC_INLINE uint32_t DL_I2S_getSampleWordLength (const I2S_Regs * i2s)
Get the sample word length in bits.
Note
Values read from the hardware will be 1 less than the true sample word length e.g. a value of 7 read from the hardware means that the sample word length is 8 bits.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
Sample word length in bits
Return values
Value in range [7, 31]
DL_I2S_setFormatPhase()
__STATIC_INLINE void DL_I2S_setFormatPhase (I2S_Regs * i2s, DL_I2S_PHASE phase)
Set between single or dual-phase format.
Note
Single-phase: DSP format
Dual-phase: I2S, LJF and RJF formats
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] phase The sampling phase to use. One of DL_I2S_PHASE
References DL_Common_updateReg().
DL_I2S_getFormatPhase()
__STATIC_INLINE DL_I2S_PHASE DL_I2S_getFormatPhase (const I2S_Regs * i2s)
Get the sampling phase being used.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
The sampling phase being used
Return values
One of DL_I2S_PHASE
DL_I2S_setSampleEdge()
__STATIC_INLINE void DL_I2S_setSampleEdge (I2S_Regs * i2s, DL_I2S_SAMPLE_EDGE edge)
Set the sample edge of data on BCLK.
Note
On negative sample edge, data is sampled on the negative edge of BCLK and clocked out on the positive edge.
On positive sample edge, data is sampled on the positive edge of BCLK and clocked out on the negative edge.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] edge The sample edge to use. One of DL_I2S_SAMPLE_EDGE
References DL_Common_updateReg().
DL_I2S_getSampleEdge()
__STATIC_INLINE DL_I2S_SAMPLE_EDGE DL_I2S_getSampleEdge (const I2S_Regs * i2s)
Gets the sample edge being used.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
The sample edge being used
Return values
One of DL_I2S_SAMPLE_EDGE
DL_I2S_setMemoryLength()
__STATIC_INLINE void DL_I2S_setMemoryLength (I2S_Regs * i2s, DL_I2S_MEMORY_LENGTH length)
Set the size of each sample word stored to or loaded from memory.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] length The memory access length to use. One of DL_I2S_MEMORY_LENGTH
References DL_Common_updateReg().
DL_I2S_getMemoryLength()
__STATIC_INLINE DL_I2S_MEMORY_LENGTH DL_I2S_getMemoryLength (const I2S_Regs * i2s)
Get the size of sample words stored to or loaded from memory.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
The memory access length being used
Return values
One of DL_I2S_MEMORY_LENGTH
DL_I2S_setDataDelay()
__STATIC_INLINE void DL_I2S_setDataDelay (I2S_Regs * i2s, DL_I2S_DATA_DELAY dataDelay)
Set the number of BCLK periods to wait between a WCLK edge and the MSB of the first word in a phase.
Note
Data delay of 0 - LJF and DSP formats
Data delay of 1 - I2S and DSP formats
Data delay of 2 (minimum) - RJF format
Data delay of 255 (maximum) - RJF format
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] dataDelay The data delay to use. One of DL_I2S_DATA_DELAY
References DL_Common_updateReg().
DL_I2S_getDataDelay()
__STATIC_INLINE DL_I2S_DATA_DELAY DL_I2S_getDataDelay (const I2S_Regs * i2s)
Gets the data delay being used.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
The data delay being used
Return values
One of DL_I2S_DATA_DELAY
DL_I2S_setEmptySlotOutput()
__STATIC_INLINE void DL_I2S_setEmptySlotOutput (I2S_Regs * i2s, DL_I2S_EMPTY_SLOT_OUTPUT output)
Set the data pin behavior during empty slots.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] output The empty slot output behavior. One of DL_I2S_EMPTY_SLOT_OUTPUT
References DL_Common_updateReg().
DL_I2S_getEmptySlotOutput()
__STATIC_INLINE DL_I2S_EMPTY_SLOT_OUTPUT DL_I2S_getEmptySlotOutput (const I2S_Regs * i2s)
Get the data pin behavior during empty slots.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
The empty slot output behavior being used
Return values
One of DL_I2S_EMPTY_SLOT_OUTPUT
DL_I2S_setDataPinsDirection()
__STATIC_INLINE void DL_I2S_setDataPinsDirection (I2S_Regs * i2s, DL_I2S_DATA_PIN_DIRECTION dataPin0Direction, DL_I2S_DATA_PIN_DIRECTION dataPin1Direction)
Set the direction of the data pins.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] dataPin0Direction Data pin 0 (AD0) direction. One of DL_I2S_DATA_PIN_DIRECTION
[in] dataPin1Direction Data pin 1 (AD1) direction. One of DL_I2S_DATA_PIN_DIRECTION
References DL_Common_updateReg().
DL_I2S_setDataPin0Direction()
__STATIC_INLINE void DL_I2S_setDataPin0Direction (I2S_Regs * i2s, DL_I2S_DATA_PIN_DIRECTION direction)
Set the direction of data pin 0.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] direction Data pin direction. One of DL_I2S_DATA_PIN_DIRECTION
References DL_Common_updateReg().
DL_I2S_setDataPin1Direction()
__STATIC_INLINE void DL_I2S_setDataPin1Direction (I2S_Regs * i2s, DL_I2S_DATA_PIN_DIRECTION direction)
Set the direction of data pin 1.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] direction Data pin direction. One of DL_I2S_DATA_PIN_DIRECTION
References DL_Common_updateReg().
DL_I2S_getDataPin0Direction()
__STATIC_INLINE DL_I2S_DATA_PIN_DIRECTION DL_I2S_getDataPin0Direction (const I2S_Regs * i2s)
Get the direction of data pin 0.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
Direction of the data pin
Return values
One of DL_I2S_DATA_PIN_DIRECTION
DL_I2S_getDataPin1Direction()
__STATIC_INLINE DL_I2S_DATA_PIN_DIRECTION DL_I2S_getDataPin1Direction (const I2S_Regs * i2s)
Get the direction of data pin 1.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
Direction of the data pin
Return values
One of DL_I2S_DATA_PIN_DIRECTION
DL_I2S_setDataPin0ChannelMask()
__STATIC_INLINE void DL_I2S_setDataPin0ChannelMask (I2S_Regs * i2s, uint32_t channelMask)
Set the valid channel mask of data pin 0.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] channelMask Valid channel mask of the data pin
DL_I2S_setDataPin1ChannelMask()
__STATIC_INLINE void DL_I2S_setDataPin1ChannelMask (I2S_Regs * i2s, uint32_t channelMask)
Set the valid channel mask of data pin 1.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] channelMask Valid channel mask of the data pin
DL_I2S_getDataPin0ChannelMask()
__STATIC_INLINE uint32_t DL_I2S_getDataPin0ChannelMask (const I2S_Regs * i2s)
Get the valid channel mask of data pin 0.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
Valid channel mask of the data pin
Return values
The valid channel mask of the data pin with the range [0, 0xFF]. For single-phase mode, each bit represents 1 channel. For dual-phase mode, only the first 2 LSBs are considered.
DL_I2S_getDataPin1ChannelMask()
__STATIC_INLINE uint32_t DL_I2S_getDataPin1ChannelMask (const I2S_Regs * i2s)
Get the valid channel mask of data pin 1.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
Valid channel mask of the data pin
Return values
The valid channel mask of the data pin with the range [0, 0xFF]. For single-phase mode, each bit represents 1 channel. For dual-phase mode, only the first 2 LSBs are considered.
DL_I2S_getTXFIFOThreshold()
__STATIC_INLINE DL_I2S_TX_FIFO_LEVEL DL_I2S_getTXFIFOThreshold (const I2S_Regs * i2s)
Get TX FIFO threshold level.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
Indicates at what fill level in the TX FIFO a threshold will be generated
Return values
One of DL_I2S_TX_FIFO_LEVEL
DL_I2S_setTXFIFOThreshold()
__STATIC_INLINE void DL_I2S_setTXFIFOThreshold (I2S_Regs * i2s, DL_I2S_TX_FIFO_LEVEL level)
Set TX FIFO threshold level.
Note
Randomly changing FIFO levels when FIFO has contents might lead to unexpected behavior. It is recommended to clear the FIFO before changing FIFO threshold levels.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] level Indicates at what fill level in the TX FIFO a threshold will be generated. One of DL_I2S_TX_FIFO_LEVEL.
See also
DL_I2S_clearTXFIFO
References DL_Common_updateReg().
DL_I2S_getRXFIFOThreshold()
__STATIC_INLINE DL_I2S_RX_FIFO_LEVEL DL_I2S_getRXFIFOThreshold (const I2S_Regs * i2s)
Get RX FIFO threshold level.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
Indicates at what fill level in the RX FIFO a threshold will be generated
Return values
One of DL_I2S_RX_FIFO_LEVEL
DL_I2S_setRXFIFOThreshold()
__STATIC_INLINE void DL_I2S_setRXFIFOThreshold (I2S_Regs * i2s, DL_I2S_RX_FIFO_LEVEL level)
Set RX FIFO threshold level.
Note
Randomly changing FIFO levels when FIFO has contents might lead to unexpected behavior. It is recommended to clear the FIFO before changing FIFO threshold levels.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] level Indicates at what fill level in the RX FIFO a threshold will be generated. One of DL_I2S_RX_FIFO_LEVEL.
See also
DL_I2S_clearRXFIFO
References DL_Common_updateReg().
DL_I2S_isRXFIFOClearComplete()
__STATIC_INLINE bool DL_I2S_isRXFIFOClearComplete (const I2S_Regs * i2s)
Checks if RX FIFO clear is complete.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
If RX FIFO clear is complete
Return values
true if RX FIFO clear is complete
false if RX FIFO clear is complete
DL_I2S_isTXFIFOClearComplete()
__STATIC_INLINE bool DL_I2S_isTXFIFOClearComplete (const I2S_Regs * i2s)
Checks if TX FIFO clear is complete.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
If TX FIFO clear is complete
Return values
true if TX FIFO clear is complete
false if TX FIFO clear is complete
DL_I2S_enableInterrupt()
__STATIC_INLINE void DL_I2S_enableInterrupt (I2S_Regs * i2s, uint32_t interruptMask)
Enable I2S interrupts.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to enable. Bitwise OR of DL_I2S_INTERRUPT.
DL_I2S_disableInterrupt()
__STATIC_INLINE void DL_I2S_disableInterrupt (I2S_Regs * i2s, uint32_t interruptMask)
Disable I2S interrupts.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to disable. Bitwise OR of DL_I2S_INTERRUPT.
DL_I2S_getEnabledInterrupts()
__STATIC_INLINE uint32_t DL_I2S_getEnabledInterrupts (const I2S_Regs * i2s, uint32_t interruptMask)
Check which I2S interrupts are enabled.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2S_INTERRUPT.
Returns
Which of the requested I2S interrupts are enabled
Return values
Bitwise OR of DL_I2S_INTERRUPT values
DL_I2S_getEnabledInterruptStatus()
__STATIC_INLINE uint32_t DL_I2S_getEnabledInterruptStatus (const I2S_Regs * i2s, uint32_t interruptMask)
Check interrupt flag of enabled I2S interrupts.
Checks if any of the I2S interrupts that were previously enabled are pending.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2S_INTERRUPT.
Returns
Which of the requested I2S interrupts are pending
Return values
Bitwise OR of DL_I2S_INTERRUPT values
See also
DL_I2S_enableInterrupt
DL_I2S_getRawInterruptStatus()
__STATIC_INLINE uint32_t DL_I2S_getRawInterruptStatus (const I2S_Regs * i2s, uint32_t interruptMask)
Check interrupt flag of any I2S interrupt.
Checks if any of the I2S interrupts are pending. Interrupts do not have to be previously enabled.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2S_INTERRUPT.
Returns
Which of the requested I2S interrupts are pending
Return values
Bitwise OR of DL_I2S_INTERRUPT values
DL_I2S_getPendingInterrupt()
__STATIC_INLINE DL_I2S_IIDX DL_I2S_getPendingInterrupt (const I2S_Regs * i2s)
Get highest priority pending I2S interrupt.
Checks if any of the I2S interrupts are pending. Interrupts do not have to be previously enabled.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
The highest priority pending I2S interrupt
Return values
One of DL_I2S_IIDX
DL_I2S_clearInterruptStatus()
__STATIC_INLINE void DL_I2S_clearInterruptStatus (I2S_Regs * i2s, uint32_t interruptMask)
Clear pending I2S interrupts.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to clear. Bitwise OR of DL_I2S_INTERRUPT.
DL_I2S_enableDMAReceiveEvent()
__STATIC_INLINE void DL_I2S_enableDMAReceiveEvent (I2S_Regs * i2s, uint32_t interrupt)
Enables I2S interrupt for triggering the DMA receive event.
Enables the I2S interrupt to be used as the condition to generate an event to directly trigger the DMA. This API configures the DMA_TRIG_RX register, which is the event publisher used for triggering the DMA to do a receive data transfer.
Note
Only one interrupt source should be enabled at a time.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] interrupt Interrupt to enable as the trigger condition for the DMA. One of DL_I2S_DMA_INTERRUPT.
DL_I2S_enableDMATransmitEvent()
__STATIC_INLINE void DL_I2S_enableDMATransmitEvent (I2S_Regs * i2s, uint32_t interrupt)
Enables I2S interrupt for triggering the DMA transmit event.
Enables the I2S interrupt to be used as the condition to generate an event to directly trigger the DMA. This API configures the DMA_TRIG_TX register, which is the event publisher used for triggering the DMA to do a transmit data transfer.
Note
Only one interrupt source should be enabled at a time.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] interrupt Interrupt to enable as the trigger condition for the DMA. One of DL_I2S_DMA_INTERRUPT.
DL_I2S_disableDMAReceiveEvent()
__STATIC_INLINE void DL_I2S_disableDMAReceiveEvent (I2S_Regs * i2s, uint32_t interrupt)
Disables I2S interrupt from triggering the DMA receive event.
Disables the I2S interrupt from being used as the condition to generate an event to directly trigger the DMA. This API configures the DMA_TRIG_RX register, which is the event publisher used for triggering the DMA to do a receive data transfer.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] interrupt Interrupt to disable as the trigger condition for the DMA. One of DL_I2S_DMA_INTERRUPT.
DL_I2S_disableDMATransmitEvent()
__STATIC_INLINE void DL_I2S_disableDMATransmitEvent (I2S_Regs * i2s, uint32_t interrupt)
Disables I2S interrupt from triggering the DMA transmit event.
Disables the I2S interrupt from being used as the condition to generate an event to directly trigger the DMA. This API configures the DMA_TRIG_TX register, which is the event publisher used for triggering the DMA to do a transmit data transfer.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] interrupt Interrupt to disable as the trigger condition for the DMA. One of DL_I2S_DMA_INTERRUPT.
DL_I2S_getEnabledDMAReceiveEvent()
__STATIC_INLINE uint32_t DL_I2S_getEnabledDMAReceiveEvent (const I2S_Regs * i2s, uint32_t interruptMask)
Check which I2S interrupt for DMA receive events is enabled.
This API checks the DMA_TRIG_RX register, which is used for triggering the DMA to do a receive data transfer.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2S_DMA_INTERRUPT.
Note
Only one interrupt source should be enabled at a time.
Returns
The requested I2S interrupt status
Return values
One of DL_I2S_DMA_INTERRUPT
DL_I2S_getEnabledDMATransmitEvent()
__STATIC_INLINE uint32_t DL_I2S_getEnabledDMATransmitEvent (const I2S_Regs * i2s, uint32_t interruptMask)
Check which I2S interrupt for DMA transmit events is enabled.
This API checks the DMA_TRIG_TX register, which is used for triggering the DMA to do a transmit data transfer.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2S_DMA_INTERRUPT.
Note
Only one interrupt source should be enabled at a time.
Returns
The requested I2S interrupt status
Return values
One of DL_I2S_DMA_INTERRUPT
DL_I2S_getEnabledDMAReceiveEventStatus()
__STATIC_INLINE uint32_t DL_I2S_getEnabledDMAReceiveEventStatus (const I2S_Regs * i2s, uint32_t interruptMask)
Check interrupt flag of enabled I2S interrupt for DMA receive event.
Checks if any of the I2S interrupts for the DMA receive event that were previously enabled are pending. This API checks the DMA_TRIG_RX register, which is used for triggering the DMA to do a receive event.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2S_DMA_INTERRUPT.
Note
Only one interrupt source should be enabled at a time.
Returns
The requested I2S interrupt status
Return values
One of DL_I2S_DMA_INTERRUPT
See also
DL_I2S_enableDMAReceiveEvent
DL_I2S_getEnabledDMATransmitEventStatus()
__STATIC_INLINE uint32_t DL_I2S_getEnabledDMATransmitEventStatus (const I2S_Regs * i2s, uint32_t interruptMask)
Check interrupt flag of enabled I2S interrupt for DMA transmit event.
Checks if any of the I2S interrupts for the DMA transmit event that were previously enabled are pending. This API checks the DMA_TRIG_TX register, which is used for triggering the DMA to do a transmit event.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2S_DMA_INTERRUPT.
Note
Only one interrupt source should be enabled at a time.
Returns
The requested I2S interrupt status
Return values
One of DL_I2S_DMA_INTERRUPT
See also
DL_I2S_enableDMATransmitEvent
DL_I2S_getRawDMAReceiveEventStatus()
__STATIC_INLINE uint32_t DL_I2S_getRawDMAReceiveEventStatus (const I2S_Regs * i2s, uint32_t interruptMask)
Check interrupt flag of any I2S interrupt for DMA receive event.
Checks if any of the I2S interrupts for DMA receive event are pending. Interrupts do not have to be previously enabled. This API checks the DMA_TRIG_RX register, which is used for triggering the DMA to do a receive event.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2S_DMA_INTERRUPT.
Returns
Which of the requested I2S interrupts are pending
Return values
Bitwise OR of DL_I2S_DMA_INTERRUPT values
DL_I2S_getRawDMATransmitEventStatus()
__STATIC_INLINE uint32_t DL_I2S_getRawDMATransmitEventStatus (const I2S_Regs * i2s, uint32_t interruptMask)
Check interrupt flag of any I2S interrupt for DMA transmit event.
Checks if any of the I2S interrupts for DMA transmit event are pending. Interrupts do not have to be previously enabled. This API checks the DMA_TRIG_TX register, which is used for triggering the DMA to do a transmit event.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2S_DMA_INTERRUPT.
Returns
Which of the requested I2S interrupts are pending
Return values
Bitwise OR of DL_I2S_DMA_INTERRUPT values
DL_I2S_suspend()
__STATIC_INLINE void DL_I2S_suspend (I2S_Regs * i2s)
Suspend external communication.
Ongoing communication will complete, and further external communications are stopped. Tranmit line(s) will be driven to idle state, and further toggles on the receive line(s) will not be processed. Once suspend is requested, the CPU should poll to ensure that the device has reached idle. When the device is idle, the transmit FIFO should be flushed, and the receive FIFO should be drained prior to disabling the module. After suspending the module, the I2S register configurations are retained.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
See also
DL_I2S_disable
DL_I2S_resume
References DL_Common_updateReg().
DL_I2S_resume()
__STATIC_INLINE void DL_I2S_resume (I2S_Regs * i2s)
Resume functional mode.
Functional communication can be resumed by calling this API, and enabling the module
Parameters
[in] i2s Pointer to the register overlay for the peripheral
See also
DL_I2S_enable
DL_I2S_suspend
References DL_Common_updateReg().
DL_I2S_setClockSource()
__STATIC_INLINE void DL_I2S_setClockSource (I2S_Regs * i2s, DL_I2S_CLOCK_SOURCE clockSource)
Set the clock source for the I2S peripheral.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
[in] clockSource Source of the clock for I2S. One of DL_I2S_CLOCK_SOURCE.
DL_I2S_getClockSource()
__STATIC_INLINE DL_I2S_CLOCK_SOURCE DL_I2S_getClockSource (const I2S_Regs * i2s)
Get I2S audio clock configuration.
Parameters
[in] i2s Pointer to the register overlay for the peripheral
Returns
The currently configured clock for I2S
Return values
One of DL_I2S_CLOCK_SOURCE
Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale