MSPM0G1X0X_G3X0X Driver Library: Digital to Analog Converter (DAC12)
Digital to Analog Converter (DAC12)
Modules
DL_DAC12_INTERRUPT
DL_DAC12_EVENT
Data Structures
struct DL_DAC12_Config
Configuration struct for DL_DAC12_init.
Enumerations
enum DL_DAC12_OUTPUT {
DL_DAC12_OUTPUT_DISABLED = DAC12_CTL1_OPS_NOC0,
DL_DAC12_OUTPUT_ENABLED = DAC12_CTL1_OPS_OUT0
}
enum DL_DAC12_REPRESENTATION {
DL_DAC12_REPRESENTATION_BINARY = DAC12_CTL0_DFM_BINARY,
DL_DAC12_REPRESENTATION_TWOS_COMPLEMENT = DAC12_CTL0_DFM_TWOS_COMP
}
enum DL_DAC12_RESOLUTION {
DL_DAC12_RESOLUTION_12BIT = DAC12_CTL0_RES__12BITS,
DL_DAC12_RESOLUTION_8BIT = DAC12_CTL0_RES__8BITS
}
enum DL_DAC12_AMP {
DL_DAC12_AMP_OFF_TRISTATE = DAC12_CTL1_AMPHIZ_HIZ,
DL_DAC12_AMP_OFF_0V = DAC12_CTL1_AMPHIZ_PULLDOWN,
DL_DAC12_AMP_ON = DAC12_CTL1_AMPEN_ENABLE
}
enum DL_DAC12_VREF_SOURCE {
DL_DAC12_VREF_SOURCE_VDDA_VEREFN,
DL_DAC12_VREF_SOURCE_VEREFP_VEREFN,
DL_DAC12_VREF_SOURCE_VDDA_VSSA,
DL_DAC12_VREF_SOURCE_VEREFP_VSSA
}
enum DL_DAC12_SAMPLETIMER {
DL_DAC12_SAMPLETIMER_DISABLE = DAC12_CTL3_STIMEN_CLR,
DL_DAC12_SAMPLETIMER_ENABLE = DAC12_CTL3_STIMEN_SET
}
enum DL_DAC12_SAMPLES_PER_SECOND {
DL_DAC12_SAMPLES_PER_SECOND_500 = DAC12_CTL3_STIMCONFIG__500SPS,
DL_DAC12_SAMPLES_PER_SECOND_1K = DAC12_CTL3_STIMCONFIG__1KSPS,
DL_DAC12_SAMPLES_PER_SECOND_2K = DAC12_CTL3_STIMCONFIG__2KSPS,
DL_DAC12_SAMPLES_PER_SECOND_4K = DAC12_CTL3_STIMCONFIG__4KSPS,
DL_DAC12_SAMPLES_PER_SECOND_8K = DAC12_CTL3_STIMCONFIG__8KSPS,
DL_DAC12_SAMPLES_PER_SECOND_16K = DAC12_CTL3_STIMCONFIG__16KSPS,
DL_DAC12_SAMPLES_PER_SECOND_100K = DAC12_CTL3_STIMCONFIG__100KSPS,
DL_DAC12_SAMPLES_PER_SECOND_200K = DAC12_CTL3_STIMCONFIG__200KSPS,
DL_DAC12_SAMPLES_PER_SECOND_500K = DAC12_CTL3_STIMCONFIG__500KSPS,
DL_DAC12_SAMPLES_PER_SECOND_1M = DAC12_CTL3_STIMCONFIG__1MSPS
}
enum DL_DAC12_FIFO {
DL_DAC12_FIFO_DISABLED = DAC12_CTL2_FIFOEN_CLR,
DL_DAC12_FIFO_ENABLED = DAC12_CTL2_FIFOEN_SET
}
enum DL_DAC12_FIFO_THRESHOLD {
DL_DAC12_FIFO_THRESHOLD_ONE_QTR_EMPTY = DAC12_CTL2_FIFOTH_LOW,
DL_DAC12_FIFO_THRESHOLD_TWO_QTRS_EMPTY = DAC12_CTL2_FIFOTH_MED,
DL_DAC12_FIFO_THRESHOLD_THREE_QTRS_EMPTY = DAC12_CTL2_FIFOTH_HIGH
}
enum DL_DAC12_FIFO_TRIGGER {
DL_DAC12_FIFO_TRIGGER_SAMPLETIMER = DAC12_CTL2_FIFOTRIGSEL_STIM,
DL_DAC12_FIFO_TRIGGER_HWTRIG0 = DAC12_CTL2_FIFOTRIGSEL_TRIG0
}
enum DL_DAC12_DMA_TRIGGER {
DL_DAC12_DMA_TRIGGER_DISABLED = DAC12_CTL2_DMATRIGEN_CLR,
DL_DAC12_DMA_TRIGGER_ENABLED = DAC12_CTL2_DMATRIGEN_SET
}
enum DL_DAC12_CALIBRATION {
DL_DAC12_CALIBRATION_FACTORY = DAC12_CALCTL_CALSEL_FACTORYTRIM,
DL_DAC12_CALIBRATION_SELF = DAC12_CALCTL_CALSEL_SELFCALIBRATIONTRIM
}
enum DL_DAC12_IIDX {
DL_DAC12_IIDX_NO_INT = DAC12_CPU_INT_IIDX_STAT_NO_INTR,
DL_DAC12_IIDX_MODULE_READY = DAC12_CPU_INT_IIDX_STAT_MODRDYIFG,
DL_DAC12_IIDX_FIFO_FULL = DAC12_CPU_INT_IIDX_STAT_FIFOFULLIFG,
DL_DAC12_IIDX_FIFO_1_4_EMPTY = DAC12_CPU_INT_IIDX_STAT_FIFO1B4IFG,
DL_DAC12_IIDX_FIFO_1_2_EMPTY = DAC12_CPU_INT_IIDX_STAT_FIFO1B2IFG,
DL_DAC12_IIDX_FIFO_3_4_EMPTY = DAC12_CPU_INT_IIDX_STAT_FIFO3B4IFG,
DL_DAC12_IIDX_FIFO_EMPTY = DAC12_CPU_INT_IIDX_STAT_FIFOEMPTYIFG,
DL_DAC12_IIDX_FIFO_UNDERRUN = DAC12_CPU_INT_IIDX_STAT_FIFOURUNIFG,
DL_DAC12_IIDX_DMA_DONE = DAC12_CPU_INT_IIDX_STAT_DMADONEIFG
}
enum DL_DAC12_SUBSCRIBER_INDEX { DL_DAC12_SUBSCRIBER_INDEX_0 = 0 }
enum DL_DAC12_EVENT_ROUTE { DL_DAC12_EVENT_ROUTE_1 = 0 }
Functions
void DL_DAC12_init (DAC12_Regs *dac12, DL_DAC12_Config *config)
Initialize the DAC module.
__STATIC_INLINE void DL_DAC12_enablePower (DAC12_Regs *dac12)
Enables power on DAC12 module.
__STATIC_INLINE void DL_DAC12_disablePower (DAC12_Regs *dac12)
Disables power on dac12 module.
__STATIC_INLINE bool DL_DAC12_isPowerEnabled (DAC12_Regs *dac12)
Returns if power on dac12 module.
__STATIC_INLINE void DL_DAC12_reset (DAC12_Regs *dac12)
Resets dac12 peripheral.
__STATIC_INLINE bool DL_DAC12_isReset (DAC12_Regs *dac12)
Returns if dac12 peripheral was reset.
__STATIC_INLINE void DL_DAC12_enable (DAC12_Regs *dac12)
Enables the DAC module.
__STATIC_INLINE void DL_DAC12_disable (DAC12_Regs *dac12)
Disables the DAC Module.
__STATIC_INLINE bool DL_DAC12_isEnabled (DAC12_Regs *dac12)
Checks the enable bit of the DAC.
__STATIC_INLINE void DL_DAC12_configDataFormat (DAC12_Regs *dac12, DL_DAC12_REPRESENTATION rep, DL_DAC12_RESOLUTION res)
Sets all elements of the input data format at once.
__STATIC_INLINE DL_DAC12_AMP DL_DAC12_getAmplifier (DAC12_Regs *dac12)
Gets the currently configured amplifier setting.
__STATIC_INLINE void DL_DAC12_setAmplifier (DAC12_Regs *dac12, DL_DAC12_AMP ampVal)
Sets the DAC and output amplifer setting.
__STATIC_INLINE DL_DAC12_VREF_SOURCE DL_DAC12_getReferenceVoltageSource (DAC12_Regs *dac12)
Gets the currently configured reference voltage source.
__STATIC_INLINE void DL_DAC12_setReferenceVoltageSource (DAC12_Regs *dac12, DL_DAC12_VREF_SOURCE refsVal)
Set the reference voltage source of the DAC.
__STATIC_INLINE void DL_DAC12_enableOutputPin (DAC12_Regs *dac12)
Enables the DAC output by connecting it to the OUT0 pin.
__STATIC_INLINE void DL_DAC12_disableOutputPin (DAC12_Regs *dac12)
Disable the DAC output by disconnecting it from the OUT0 pin.
__STATIC_INLINE bool DL_DAC12_isOutputPinEnabled (DAC12_Regs *dac12)
Checks to see whether the output is connected.
__STATIC_INLINE void DL_DAC12_enableFIFO (DAC12_Regs *dac12)
Enables the FIFO module.
__STATIC_INLINE void DL_DAC12_disableFIFO (DAC12_Regs *dac12)
Disables the FIFO.
__STATIC_INLINE bool DL_DAC12_isFIFOEnabled (DAC12_Regs *dac12)
Checks whether the FIFO is enabled.
__STATIC_INLINE DL_DAC12_FIFO_THRESHOLD DL_DAC12_getFIFOThreshold (DAC12_Regs *dac12)
Gets the FIFO threshold.
__STATIC_INLINE void DL_DAC12_setFIFOThreshold (DAC12_Regs *dac12, DL_DAC12_FIFO_THRESHOLD fifoThreshold)
Sets the FIFO threshold.
__STATIC_INLINE DL_DAC12_FIFO_TRIGGER DL_DAC12_getFIFOTriggerSource (DAC12_Regs *dac12)
Gets the FIFO read trigger source.
__STATIC_INLINE void DL_DAC12_setFIFOTriggerSource (DAC12_Regs *dac12, DL_DAC12_FIFO_TRIGGER fifoTrig)
Sets the FIFO read trigger source.
__STATIC_INLINE void DL_DAC12_enableDMATrigger (DAC12_Regs *dac12)
Enables the DMA trigger generator.
__STATIC_INLINE void DL_DAC12_disableDMATrigger (DAC12_Regs *dac12)
Disables the DMA trigger generator.
__STATIC_INLINE bool DL_DAC12_isDMATriggerEnabled (DAC12_Regs *dac12)
Checks whether the DMA trigger generator is enabled.
__STATIC_INLINE void DL_DAC12_enableSampleTimeGenerator (DAC12_Regs *dac12)
Enables the sample time generator.
__STATIC_INLINE void DL_DAC12_disableSampleTimeGenerator (DAC12_Regs *dac12)
Disables the sample time generator.
__STATIC_INLINE bool DL_DAC12_isSampleTimeGeneratorEnabled (DAC12_Regs *dac12)
Checks whether the sample time trigger generator is enabled.
__STATIC_INLINE DL_DAC12_SAMPLES_PER_SECOND DL_DAC12_getSampleRate (DAC12_Regs *dac12)
Gets the sample trigger rate of the sample time generator.
__STATIC_INLINE void DL_DAC12_setSampleRate (DAC12_Regs *dac12, DL_DAC12_SAMPLES_PER_SECOND sampleRate)
Sets the sample triggering rate of the sample time generator.
__STATIC_INLINE bool DL_DAC12_isCalibrationRunning (DAC12_Regs *dac12)
Checks whether a calibration sequence is currently running.
__STATIC_INLINE void DL_DAC12_startCalibration (DAC12_Regs *dac12)
Initiates the DAC offset error calibration sequence.
__STATIC_INLINE uint32_t DL_DAC12_getCalibrationData (DAC12_Regs *dac12)
Gets the DAC Calibration offset.
void DL_DAC12_performSelfCalibrationBlocking (DAC12_Regs *dac12)
Perform calibration sequence.
__STATIC_INLINE void DL_DAC12_output8 (DAC12_Regs *dac12, uint8_t dataValue)
Outputs an 8-bit data value.
__STATIC_INLINE void DL_DAC12_output12 (DAC12_Regs *dac12, uint32_t dataValue)
Outputs a 12-bit Data Value.
uint32_t DL_DAC12_fillFIFO8 (DAC12_Regs *dac12, uint8_t *buffer, uint32_t count)
Fills the DAC fifo with 8-bit data values from the buffer.
uint32_t DL_DAC12_fillFIFO12 (DAC12_Regs *dac12, uint16_t *buffer, uint32_t count)
Fills the DAC fifo with 12-bit data values from the buffer.
void DL_DAC12_outputBlocking8 (DAC12_Regs *dac12, uint8_t data)
Blocking 8-bit output to the DAC FIFO.
void DL_DAC12_outputBlocking12 (DAC12_Regs *dac12, uint16_t data)
Blocking 12-bit output to the DAC FIFO.
__STATIC_INLINE uint32_t DL_DAC12_getInterruptStatus (DAC12_Regs *dac12, uint32_t interruptMask)
Checks the raw interrupt status of one or more interrupts.
__STATIC_INLINE void DL_DAC12_clearInterruptStatus (DAC12_Regs *dac12, uint32_t interruptMask)
Clears the interrupt status of one or more interrupts.
__STATIC_INLINE void DL_DAC12_enableInterrupt (DAC12_Regs *dac12, uint32_t interruptMask)
Enables one or more interrupts.
__STATIC_INLINE void DL_DAC12_disableInterrupt (DAC12_Regs *dac12, uint32_t interruptMask)
Disables one or more interrupts.
__STATIC_INLINE DL_DAC12_IIDX DL_DAC12_getPendingInterrupt (DAC12_Regs *dac12)
Gets the highest priority pending interrupt.
__STATIC_INLINE bool DL_DAC12_isFIFOFull (DAC12_Regs *dac12)
Checks if the DAC FIFO is currently full.
__STATIC_INLINE void DL_DAC12_setPublisherChanID (DAC12_Regs *dac12, uint8_t chanID)
Sets the event publisher channel id.
__STATIC_INLINE uint8_t DL_DAC12_getPublisherChanID (DAC12_Regs *dac12)
Gets the event publisher channel id.
__STATIC_INLINE void DL_DAC12_setSubscriberChanID (DAC12_Regs *dac12, DL_DAC12_SUBSCRIBER_INDEX index, uint8_t chanID)
Sets the event subscriber channel id.
__STATIC_INLINE uint8_t DL_DAC12_getSubscriberChanID (DAC12_Regs *dac12, DL_DAC12_SUBSCRIBER_INDEX index)
Gets the event subscriber channel id.
__STATIC_INLINE void DL_DAC12_enableEvent (DAC12_Regs *dac12, uint32_t eventMask)
Enable DAC event.
__STATIC_INLINE void DL_DAC12_disableEvent (DAC12_Regs *dac12, uint32_t eventMask)
Disable DAC event.
__STATIC_INLINE uint32_t DL_DAC12_getEnabledEvents (DAC12_Regs *dac12, uint32_t eventMask)
Check which DAC events are enabled.
__STATIC_INLINE uint32_t DL_DAC12_getEnabledEventStatus (DAC12_Regs *dac12, uint32_t eventMask)
Check event flag of enabled DAC event.
__STATIC_INLINE uint32_t DL_DAC12_getRawEventsStatus (DAC12_Regs *dac12, uint32_t eventMask)
Check interrupt flag of any DAC event.
__STATIC_INLINE void DL_DAC12_clearEventsStatus (DAC12_Regs *dac12, uint32_t eventMask)
Clear pending DAC events.
Detailed Description
Overview
The Digital to Analog Converter Driver Library allows full configuration of the MSPM0 DAC12 module. The DAC module is a 12-bit voltage-output digital-to-analog converter (DAC).
Enumeration Type Documentation
DL_DAC12_OUTPUT
enum DL_DAC12_OUTPUT
Enumerator
DL_DAC12_OUTPUT_DISABLED
DAC output is disconnected from output pin
DL_DAC12_OUTPUT_ENABLED
DAC output is available on output pin
DL_DAC12_REPRESENTATION
enum DL_DAC12_REPRESENTATION
Enumerator
DL_DAC12_REPRESENTATION_BINARY
Binary representation
DL_DAC12_REPRESENTATION_TWOS_COMPLEMENT
Two's complement representation
DL_DAC12_RESOLUTION
enum DL_DAC12_RESOLUTION
Enumerator
DL_DAC12_RESOLUTION_12BIT
12-bit input resolution
DL_DAC12_RESOLUTION_8BIT
8-bit input resolution
DL_DAC12_AMP
enum DL_DAC12_AMP
Enumerator
DL_DAC12_AMP_OFF_TRISTATE
Output amplifier off with high impedance tristate output
DL_DAC12_AMP_OFF_0V
Output amplifier off with output pulled to ground
DL_DAC12_AMP_ON
Output amplifier enabled
DL_DAC12_VREF_SOURCE
enum DL_DAC12_VREF_SOURCE
Enumerator
DL_DAC12_VREF_SOURCE_VDDA_VEREFN
Positive reference is VDDA, negative reference is VeREF-
DL_DAC12_VREF_SOURCE_VEREFP_VEREFN
Positive reference is VeREF+, negative reference is VeREF-
DL_DAC12_VREF_SOURCE_VDDA_VSSA
Positive reference is VDDA, negative reference is VSSA
DL_DAC12_VREF_SOURCE_VEREFP_VSSA
Positive reference is VeREF+, negative reference is VSSA
DL_DAC12_SAMPLETIMER
enum DL_DAC12_SAMPLETIMER
Enumerator
DL_DAC12_SAMPLETIMER_DISABLE
DAC sample timer generator is disabled
DL_DAC12_SAMPLETIMER_ENABLE
DAC sample timer generator is enabled
DL_DAC12_SAMPLES_PER_SECOND
enum DL_DAC12_SAMPLES_PER_SECOND
Enumerator
DL_DAC12_SAMPLES_PER_SECOND_500
Sample Time Trigger rate of 500 Samples Per Second
DL_DAC12_SAMPLES_PER_SECOND_1K
Sample Time Trigger rate of 1,000 Samples Per Second
DL_DAC12_SAMPLES_PER_SECOND_2K
Sample Time Trigger rate of 2,000 Samples Per Second
DL_DAC12_SAMPLES_PER_SECOND_4K
Sample Time Trigger rate of 4,000 Samples Per Second
DL_DAC12_SAMPLES_PER_SECOND_8K
Sample Time Trigger rate of 8,000 Samples Per Second
DL_DAC12_SAMPLES_PER_SECOND_16K
Sample Time Trigger rate of 16,000 Samples Per Second
DL_DAC12_SAMPLES_PER_SECOND_100K
Sample Time Trigger rate of 100,000 Samples Per Second
DL_DAC12_SAMPLES_PER_SECOND_200K
Sample Time Trigger rate of 200,000 Samples Per Second
DL_DAC12_SAMPLES_PER_SECOND_500K
Sample Time Trigger rate of 500,000 Samples Per Second
DL_DAC12_SAMPLES_PER_SECOND_1M
Sample Time Trigger rate of 1,000,000 Samples Per Second
DL_DAC12_FIFO
enum DL_DAC12_FIFO
Enumerator
DL_DAC12_FIFO_DISABLED
DAC FIFO is disabled
DL_DAC12_FIFO_ENABLED
DAC FIFO is enabled
DL_DAC12_FIFO_THRESHOLD
enum DL_DAC12_FIFO_THRESHOLD
Enumerator
DL_DAC12_FIFO_THRESHOLD_ONE_QTR_EMPTY
DAC FIFO threshold for DMA Trigger Generation where 1/4th of location are empty
DL_DAC12_FIFO_THRESHOLD_TWO_QTRS_EMPTY
DAC FIFO threshold for DMA Trigger Generation where 2/4th of locations are empty
DL_DAC12_FIFO_THRESHOLD_THREE_QTRS_EMPTY
DAC FIFO threshold for DMA Trigger Generation where 3/4th of locations are empty
DL_DAC12_FIFO_TRIGGER
enum DL_DAC12_FIFO_TRIGGER
Enumerator
DL_DAC12_FIFO_TRIGGER_SAMPLETIMER
DAC FIFO read trigger sourced from the sample time generator
DL_DAC12_FIFO_TRIGGER_HWTRIG0
DAC FIFO read trigger sourced from the hardware trigger 0 event fabric
DL_DAC12_DMA_TRIGGER
enum DL_DAC12_DMA_TRIGGER
Enumerator
DL_DAC12_DMA_TRIGGER_DISABLED
DMA trigger mechanism for DAC is disabled
DL_DAC12_DMA_TRIGGER_ENABLED
DMA trigger mechanism for DAC is enabled
DL_DAC12_CALIBRATION
enum DL_DAC12_CALIBRATION
Enumerator
DL_DAC12_CALIBRATION_FACTORY
Factory Trim
DL_DAC12_CALIBRATION_SELF
Self Trim (last calibration result)
DL_DAC12_IIDX
enum DL_DAC12_IIDX
Enumerator
DL_DAC12_IIDX_NO_INT
DAC interrupt index for no interrupt pending
DL_DAC12_IIDX_MODULE_READY
DAC interrupt index when module is ready
DL_DAC12_IIDX_FIFO_FULL
DAC interrupt index when FIFO is full
DL_DAC12_IIDX_FIFO_1_4_EMPTY
DAC interrupt index when FIFO is 1/4 empty
DL_DAC12_IIDX_FIFO_1_2_EMPTY
DAC interrupt index when FIFO is 1/2 empty
DL_DAC12_IIDX_FIFO_3_4_EMPTY
DAC interrupt index when FIFO is 3/4 empty
DL_DAC12_IIDX_FIFO_EMPTY
DAC interrupt index when FIFO is empty
DL_DAC12_IIDX_FIFO_UNDERRUN
DAC interrupt index if there is FIFO underrun
DL_DAC12_IIDX_DMA_DONE
DAC interrupt index for DMA transfer done
DL_DAC12_SUBSCRIBER_INDEX
enum DL_DAC12_SUBSCRIBER_INDEX
Enumerator
DL_DAC12_SUBSCRIBER_INDEX_0
DAC12 Subscriber index 0
DL_DAC12_EVENT_ROUTE
enum DL_DAC12_EVENT_ROUTE
Enumerator
DL_DAC12_EVENT_ROUTE_1
DAC12 event route 1
Function Documentation
DL_DAC12_init()
void DL_DAC12_init (DAC12_Regs * dac12, DL_DAC12_Config * config)
Initialize the DAC module.
Initializes all the common configurable options for the DAC module. Any other custom configuration can be done after this initialization.
Postcondition
DAC is not enabled
Parameters
[in] dac12 Pointer to the register overlay for the peripheral
[in] config Configuration for DAC12 peripheral
DL_DAC12_enablePower()
__STATIC_INLINE void DL_DAC12_enablePower (DAC12_Regs * dac12)
Enables power on DAC12 module.
Parameters
dac12 Pointer to the register overlay for the peripheral
DL_DAC12_disablePower()
__STATIC_INLINE void DL_DAC12_disablePower (DAC12_Regs * dac12)
Disables power on dac12 module.
Parameters
dac12 Pointer to the register overlay for the peripheral
DL_DAC12_isPowerEnabled()
__STATIC_INLINE bool DL_DAC12_isPowerEnabled (DAC12_Regs * dac12)
Returns if power on dac12 module.
Parameters
dac12 Pointer to the register overlay for the peripheral
Returns
true if power is enabled
false if power is disabled
DL_DAC12_reset()
__STATIC_INLINE void DL_DAC12_reset (DAC12_Regs * dac12)
Resets dac12 peripheral.
Parameters
dac12 Pointer to the register overlay for the peripheral
DL_DAC12_isReset()
__STATIC_INLINE bool DL_DAC12_isReset (DAC12_Regs * dac12)
Returns if dac12 peripheral was reset.
Parameters
dac12 Pointer to the register overlay for the peripheral
Returns
true if peripheral was reset
false if peripheral wasn't reset
DL_DAC12_enable()
__STATIC_INLINE void DL_DAC12_enable (DAC12_Regs * dac12)
Enables the DAC module.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
DL_DAC12_disable()
__STATIC_INLINE void DL_DAC12_disable (DAC12_Regs * dac12)
Disables the DAC Module.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
DL_DAC12_isEnabled()
__STATIC_INLINE bool DL_DAC12_isEnabled (DAC12_Regs * dac12)
Checks the enable bit of the DAC.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
Returns
Whether the DAC module is enabled
Return values
true Module enabled
false Module disabled
DL_DAC12_configDataFormat()
__STATIC_INLINE void DL_DAC12_configDataFormat (DAC12_Regs * dac12, DL_DAC12_REPRESENTATION rep, DL_DAC12_RESOLUTION res)
Sets all elements of the input data format at once.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
[in] rep Data Representation. One of DL_DAC12_REPRESENTATION
[in] res Data Resolution. One of DL_DAC12_RESOLUTION
References DL_Common_updateReg().
DL_DAC12_getAmplifier()
__STATIC_INLINE DL_DAC12_AMP DL_DAC12_getAmplifier (DAC12_Regs * dac12)
Gets the currently configured amplifier setting.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
Returns
Currently configured amplifier setting
Return values
One of DL_DAC12_AMP
DL_DAC12_setAmplifier()
__STATIC_INLINE void DL_DAC12_setAmplifier (DAC12_Regs * dac12, DL_DAC12_AMP ampVal)
Sets the DAC and output amplifer setting.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
[in] ampVal amplifier configuration value. One of DL_DAC12_AMP
References DL_Common_updateReg().
DL_DAC12_getReferenceVoltageSource()
__STATIC_INLINE DL_DAC12_VREF_SOURCE DL_DAC12_getReferenceVoltageSource (DAC12_Regs * dac12)
Gets the currently configured reference voltage source.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
Returns
Currently configured reference voltage
Return values
Bitwise OR of DL_DAC12_VREF_SOURCE
DL_DAC12_setReferenceVoltageSource()
__STATIC_INLINE void DL_DAC12_setReferenceVoltageSource (DAC12_Regs * dac12, DL_DAC12_VREF_SOURCE refsVal)
Set the reference voltage source of the DAC.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
[in] refsVal reference voltage source. Bitwise OR of DL_DAC12_VREF_SOURCE
References DL_Common_updateReg().
DL_DAC12_enableOutputPin()
__STATIC_INLINE void DL_DAC12_enableOutputPin (DAC12_Regs * dac12)
Enables the DAC output by connecting it to the OUT0 pin.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
DL_DAC12_disableOutputPin()
__STATIC_INLINE void DL_DAC12_disableOutputPin (DAC12_Regs * dac12)
Disable the DAC output by disconnecting it from the OUT0 pin.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
DL_DAC12_isOutputPinEnabled()
__STATIC_INLINE bool DL_DAC12_isOutputPinEnabled (DAC12_Regs * dac12)
Checks to see whether the output is connected.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
Returns
Status of output connection
Return values
true Output is connected
false Output is not connected
DL_DAC12_enableFIFO()
__STATIC_INLINE void DL_DAC12_enableFIFO (DAC12_Regs * dac12)
Enables the FIFO module.
Enables the FIFO and the FIFO hardware control state machine
Parameters
[in] dac12 pointer to the register overlay of the peripheral
DL_DAC12_disableFIFO()
__STATIC_INLINE void DL_DAC12_disableFIFO (DAC12_Regs * dac12)
Disables the FIFO.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
See also
DL_DAC12_enableFIFO
DL_DAC12_isFIFOEnabled()
__STATIC_INLINE bool DL_DAC12_isFIFOEnabled (DAC12_Regs * dac12)
Checks whether the FIFO is enabled.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
Returns
Current status of the FIFO
Return values
true FIFO is enabled
false FIFO is not enabled
DL_DAC12_getFIFOThreshold()
__STATIC_INLINE DL_DAC12_FIFO_THRESHOLD DL_DAC12_getFIFOThreshold (DAC12_Regs * dac12)
Gets the FIFO threshold.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
Returns
Currently configured FIFO Threshold
Return values
One of DL_DAC12_FIFO_THRESHOLD
See also
DL_DAC12_setFIFOThreshold
DL_DAC12_setFIFOThreshold()
__STATIC_INLINE void DL_DAC12_setFIFOThreshold (DAC12_Regs * dac12, DL_DAC12_FIFO_THRESHOLD fifoThreshold)
Sets the FIFO threshold.
Determines the FIFO threshold In case of DMA based operation, DAC generates new DMA trigger when the number of empty locations in FIFO match the selected FIFO threshold level. In the case of CPU based operation, the FIFO threshold bits are don't care and FIFO level is directly indicated through the respective bits in the RIS register
Parameters
[in] dac12 pointer to the register overlay of the peripheral
[in] fifoThreshold Threshold value. One of DL_DAC12_FIFO_THRESHOLD
References DL_Common_updateReg().
DL_DAC12_getFIFOTriggerSource()
__STATIC_INLINE DL_DAC12_FIFO_TRIGGER DL_DAC12_getFIFOTriggerSource (DAC12_Regs * dac12)
Gets the FIFO read trigger source.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
Returns
Currently configured trigger source
Return values
One of DL_DAC12_FIFO_TRIGGER
See also
DL_DAC12_setFIFOTriggerSource
DL_DAC12_setFIFOTriggerSource()
__STATIC_INLINE void DL_DAC12_setFIFOTriggerSource (DAC12_Regs * dac12, DL_DAC12_FIFO_TRIGGER fifoTrig)
Sets the FIFO read trigger source.
Selects the source for FIFO read trigger by the DAC. When the selected FIFO read trigger is asserted, the data from FIFO (as indicated by read pointer) is moved into internal DAC data register
Parameters
[in] dac12 pointer to the register overlay of the peripheral
[in] fifoTrig Read Trigger Source. One of DL_DAC12_FIFO_TRIGGER
References DL_Common_updateReg().
DL_DAC12_enableDMATrigger()
__STATIC_INLINE void DL_DAC12_enableDMATrigger (DAC12_Regs * dac12)
Enables the DMA trigger generator.
When this is and the FIFO are enabled, the DMA trigger is generated based on the empty FIFO locations qualified by the selected FIFO Threshold settings. This bit is automatically cleared by hardware when the DMA done event is asserted with DMA status signal value being nonzero
Parameters
[in] dac12 pointer to the register overlay of the peripheral
See also
DL_DAC12_enableFIFO
DL_DAC12_setFIFOThreshold
DL_DAC12_disableDMATrigger()
__STATIC_INLINE void DL_DAC12_disableDMATrigger (DAC12_Regs * dac12)
Disables the DMA trigger generator.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
See also
DL_DAC12_enableDMATriggerGenerator
DL_DAC12_isDMATriggerEnabled()
__STATIC_INLINE bool DL_DAC12_isDMATriggerEnabled (DAC12_Regs * dac12)
Checks whether the DMA trigger generator is enabled.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
Returns
Current status of the DMA trigger generator
Return values
true DMA Trigger enabled
false DMA Trigger not enabled
DL_DAC12_enableSampleTimeGenerator()
__STATIC_INLINE void DL_DAC12_enableSampleTimeGenerator (DAC12_Regs * dac12)
Enables the sample time generator.
The sample time generator can be selected as the FIFO Trigger DL_DAC12_setFIFOTriggerSource and control the rate at which the DAC will consume inputs from the FIFO
Parameters
[in] dac12 pointer to the register overlay of the peripheral
DL_DAC12_disableSampleTimeGenerator()
__STATIC_INLINE void DL_DAC12_disableSampleTimeGenerator (DAC12_Regs * dac12)
Disables the sample time generator.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
See also
DL_DAC12_enableSampleTimeGenerator
DL_DAC12_isSampleTimeGeneratorEnabled()
__STATIC_INLINE bool DL_DAC12_isSampleTimeGeneratorEnabled (DAC12_Regs * dac12)
Checks whether the sample time trigger generator is enabled.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
Returns
Current status of the sample time generator
Return values
true Sample time generator is enabled
false Sample time generator is not enabled
DL_DAC12_getSampleRate()
__STATIC_INLINE DL_DAC12_SAMPLES_PER_SECOND DL_DAC12_getSampleRate (DAC12_Regs * dac12)
Gets the sample trigger rate of the sample time generator.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
Returns
Currently configured sample rate
Return values
One of DL_DAC12_SAMPLES_PER_SECOND
DL_DAC12_setSampleRate()
__STATIC_INLINE void DL_DAC12_setSampleRate (DAC12_Regs * dac12, DL_DAC12_SAMPLES_PER_SECOND sampleRate)
Sets the sample triggering rate of the sample time generator.
Sets the sample trigger rate of the sample time generator. The sample time generator can be selected as the FIFO Trigger DL_DAC12_setFIFOTriggerSource and control the rate at which the DAC will consume inputs from the FIFO
Parameters
[in] dac12 pointer to the register overlay of the peripheral
[in] sampleRate Desired sample rate. One of DL_DAC12_SAMPLES_PER_SECOND
References DL_Common_updateReg().
DL_DAC12_isCalibrationRunning()
__STATIC_INLINE bool DL_DAC12_isCalibrationRunning (DAC12_Regs * dac12)
Checks whether a calibration sequence is currently running.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
Returns
Current status of an active calibration sequence
Return values
true Calibration Sequence is currently running
false Calibration Sequence is not running
See also
DL_DAC12_startCalibration
DL_DAC12_startCalibration()
__STATIC_INLINE void DL_DAC12_startCalibration (DAC12_Regs * dac12)
Initiates the DAC offset error calibration sequence.
Initiates the DAC offset error calibration sequence and the CALON_ACTIVE bit is automatically reset when the offset error calibration completes. Upon completion, the correct calibration will be put into the CALDATA register. This sequence can be started either on the fly (once the module is ready) or during setup (where this is called directy after enabling the DAC).
In order for the calibration to be successful, the AMP must already be configured and the LOCK bit must be cleared for the value to be written successfully. The output is also tri-stated during calibration.
A negative offset will mean that low input values will have a output of 0. A positive offset will mean that an input of 0 will result in a non-zero output.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
DL_DAC12_getCalibrationData()
__STATIC_INLINE uint32_t DL_DAC12_getCalibrationData (DAC12_Regs * dac12)
Gets the DAC Calibration offset.
Reads of the CALDATA register should only be performed after the calibration sequence has completed. During calibration, this register is continuously written to, and inaccurate values could be obtained.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
Returns
Current error calibration offset
Return values
-64 to +63 in two's complement
References DL_DAC12_performSelfCalibrationBlocking().
DL_DAC12_performSelfCalibrationBlocking()
void DL_DAC12_performSelfCalibrationBlocking (DAC12_Regs * dac12)
Perform calibration sequence.
Enables writes, and then starts the calibration sequence. Should only be called after the DAC module is enabled. This will only return when the calibration sequence has completed.
Precondition
Amplifier settings should be configured. DL_DAC12_setAmplifier
Postcondition
Calibration is complete, and CALDATA is locked to prevent writes.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
Referenced by DL_DAC12_getCalibrationData().
DL_DAC12_output8()
__STATIC_INLINE void DL_DAC12_output8 (DAC12_Regs * dac12, uint8_t dataValue)
Outputs an 8-bit data value.
Using the CPU to control the DAC, this register can be written to if a fixed output voltage is desired (ex. DC Generation) with the FIFO disabled, or it can write with variable output (ex. AC Generation) by enabling the FIFO and writing to this register. The value will then be written to the FIFO internally. With FIFO enabled with DL_DAC12_enableFIFO, the FIFO-specific interrupts will be generated inside the DAC.
The DMA trigger generation mechanism must be kept disabled when CPU is used to load data into DAC
Parameters
[in] dac12 pointer to the register overlay of the peripheral
[in] dataValue value to be written to the bit-field from 0x0 to 0xFF. It can be either binary or two's complement
DL_DAC12_output12()
__STATIC_INLINE void DL_DAC12_output12 (DAC12_Regs * dac12, uint32_t dataValue)
Outputs a 12-bit Data Value.
Using the CPU to control the DAC, this register can be written to if a fixed output voltage is desired (ex. DC Generation) with the FIFO disabled, or it can write with variable output (ex. AC Generation) by enabling the FIFO and writing to this register. The value will then be written to the FIFO internally. With FIFO enabled with DL_DAC12_enableFIFO, the FIFO-specific interrupts will be generated inside the DAC.
The DMA trigger generation mechanism must be kept disabled when CPU is used to load data into DAC
Parameters
[in] dac12 pointer to the register overlay of the peripheral
[in] dataValue value to be written to the bit-field from 0x0 to 0xFFF. It can be either binary or two's complement
References DL_DAC12_fillFIFO12(), DL_DAC12_fillFIFO8(), DL_DAC12_outputBlocking12(), and DL_DAC12_outputBlocking8().
DL_DAC12_fillFIFO8()
uint32_t DL_DAC12_fillFIFO8 (DAC12_Regs * dac12, uint8_t * buffer, uint32_t count)
Fills the DAC fifo with 8-bit data values from the buffer.
Writes as many values from the data buffer to the FIFO as possible, and then exits when either the count is matched or the FIFO is full.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
[in] buffer array containing the data values (0x00 - 0xFF) to be written
[in] count length of the buffer, or maximum desired transfer
Returns
Count successfully transferred to the FIFO
Return values
0 - max(number of empty fifo slots, count)
Referenced by DL_DAC12_output12().
DL_DAC12_fillFIFO12()
uint32_t DL_DAC12_fillFIFO12 (DAC12_Regs * dac12, uint16_t * buffer, uint32_t count)
Fills the DAC fifo with 12-bit data values from the buffer.
Writes as many values from the data buffer to the FIFO as possible, and then exits when either the count is matched or the FIFO is full.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
[in] buffer array containing the data values (0x00 - 0xFFF) to be written
[in] count length of the buffer, or maximum desired transfer
Returns
Count successfully transfered to the FIFO
Return values
0 - max(number of empty fifo slots, count)
Referenced by DL_DAC12_output12().
DL_DAC12_outputBlocking8()
void DL_DAC12_outputBlocking8 (DAC12_Regs * dac12, uint8_t data)
Blocking 8-bit output to the DAC FIFO.
Waits until the FIFO is not full, then writes a single value
Parameters
[in] dac12 pointer to the register overlay of the peripheral
[in] data data value (0x00 - 0xFF) to be written
Referenced by DL_DAC12_output12().
DL_DAC12_outputBlocking12()
void DL_DAC12_outputBlocking12 (DAC12_Regs * dac12, uint16_t data)
Blocking 12-bit output to the DAC FIFO.
Waits until the FIFO is not full, then writes a single value
Parameters
[in] dac12 pointer to the register overlay of the peripheral
[in] data data value (0x000 - 0xFFF) to be written
Referenced by DL_DAC12_output12().
DL_DAC12_getInterruptStatus()
__STATIC_INLINE uint32_t DL_DAC12_getInterruptStatus (DAC12_Regs * dac12, uint32_t interruptMask)
Checks the raw interrupt status of one or more interrupts.
The raw interrupt status is independent of whether a specific interrupt is enabled.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
[in] interruptMask the desired interrupt(s). One or more of DL_DAC12_INTERRUPT
Returns
currently asserted interrupts (whether enabled or not) bit-wise AND with the inputted interrupts
Return values
0 no interrupts that were inputted are currently asserted
not 0 a bit-wise OR of the inputted DL_DAC12_INTERRUPT registers that are currently asserted.
Referenced by DL_DAC12_isFIFOFull().
DL_DAC12_clearInterruptStatus()
__STATIC_INLINE void DL_DAC12_clearInterruptStatus (DAC12_Regs * dac12, uint32_t interruptMask)
Clears the interrupt status of one or more interrupts.
Accesses the write only interrupt clear (ICLR) register and writes a 1 to the bits specified. Any bit that has 1 written to it will clear that pending interrupt if it is currently pending.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
[in] interruptMask the desired interrupt(s). One or more of DL_DAC12_INTERRUPT
DL_DAC12_enableInterrupt()
__STATIC_INLINE void DL_DAC12_enableInterrupt (DAC12_Regs * dac12, uint32_t interruptMask)
Enables one or more interrupts.
Access and write to the IMASK register to enable the interrupts specified.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
[in] interruptMask the desired interrupt(s). One or more of DL_DAC12_INTERRUPT
DL_DAC12_disableInterrupt()
__STATIC_INLINE void DL_DAC12_disableInterrupt (DAC12_Regs * dac12, uint32_t interruptMask)
Disables one or more interrupts.
Access and write to the IMASK register to disable the interrupts specified.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
[in] interruptMask the desired interrupt(s). One or more of DL_DAC12_INTERRUPT
DL_DAC12_getPendingInterrupt()
__STATIC_INLINE DL_DAC12_IIDX DL_DAC12_getPendingInterrupt (DAC12_Regs * dac12)
Gets the highest priority pending interrupt.
Accesses and reads the IIDX register to obtain the highest currently pending interrupt. Interrupts with lower offsets (and smaller values) are higher priority than interrupts with higher offsets (and larger values). In order for the interrupt to be pending, it must have been enabled and asserted. Clearing the interrupt should will un-pend the interrupt.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
Returns
highest priority pending interrupt
Return values
One of DL_DAC12_IIDX
DL_DAC12_isFIFOFull()
__STATIC_INLINE bool DL_DAC12_isFIFOFull (DAC12_Regs * dac12)
Checks if the DAC FIFO is currently full.
Accesses the raw interrupt status (RIS) register in order to get the current state of the FIFOFull Interrupt flag.
Parameters
[in] dac12 pointer to the register overlay of the peripheral
Returns
status of FIFO full interrupt flag
Return values
true FIFO is currently full
false FIFO is not full
References DL_DAC12_getInterruptStatus(), and DL_DAC12_INTERRUPT_FIFO_FULL.
DL_DAC12_setPublisherChanID()
__STATIC_INLINE void DL_DAC12_setPublisherChanID (DAC12_Regs * dac12, uint8_t chanID)
Sets the event publisher channel id.
Parameters
[in] dac12 Pointer to the register overlay for the peripheral
[in] chanID Channel ID number. Valid range 0-15. If ChanID == 0 publisher is disconnected.
DL_DAC12_getPublisherChanID()
__STATIC_INLINE uint8_t DL_DAC12_getPublisherChanID (DAC12_Regs * dac12)
Gets the event publisher channel id.
Parameters
[in] dac12 Pointer to the register overlay for the peripheral
Returns
Event publisher channel ID
DL_DAC12_setSubscriberChanID()
__STATIC_INLINE void DL_DAC12_setSubscriberChanID (DAC12_Regs * dac12, DL_DAC12_SUBSCRIBER_INDEX index, uint8_t chanID)
Sets the event subscriber channel id.
Parameters
[in] dac12 Pointer to the register overlay for the peripheral
[in] index Specifies the register event index to be configured
[in] chanID Channel ID number. Valid range 0-15. If ChanID == 0 subscriber is disconnected.
DL_DAC12_getSubscriberChanID()
__STATIC_INLINE uint8_t DL_DAC12_getSubscriberChanID (DAC12_Regs * dac12, DL_DAC12_SUBSCRIBER_INDEX index)
Gets the event subscriber channel id.
Parameters
[in] dac12 Pointer to the register overlay for the peripheral
[in] index Specifies the register event index to be configured
Returns
Event subscriber channel ID
DL_DAC12_enableEvent()
__STATIC_INLINE void DL_DAC12_enableEvent (DAC12_Regs * dac12, uint32_t eventMask)
Enable DAC event.
Parameters
[in] dac12 Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to enable. Bitwise OR of DL_DAC12_EVENT.
DL_DAC12_disableEvent()
__STATIC_INLINE void DL_DAC12_disableEvent (DAC12_Regs * dac12, uint32_t eventMask)
Disable DAC event.
Parameters
[in] dac12 Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to enable. Bitwise OR of DL_DAC12_EVENT.
DL_DAC12_getEnabledEvents()
__STATIC_INLINE uint32_t DL_DAC12_getEnabledEvents (DAC12_Regs * dac12, uint32_t eventMask)
Check which DAC events are enabled.
Parameters
[in] dac12 Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to check. Bitwise OR of DL_DAC12_EVENT.
Returns
Which of the requested DAC interrupts are enabled
Return values
Bitwise OR of DL_DAC12_EVENT values
DL_DAC12_getEnabledEventStatus()
__STATIC_INLINE uint32_t DL_DAC12_getEnabledEventStatus (DAC12_Regs * dac12, uint32_t eventMask)
Check event flag of enabled DAC event.
Checks if any of the DAC events that were previously enabled are pending.
Parameters
[in] dac12 Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to check. Bitwise OR of DL_DAC12_EVENT.
Returns
Which of the requested DAC interrupts are pending
Return values
Bitwise OR of DL_DAC12_EVENT values
See also
DL_DAC12_enableInterrupt
DL_DAC12_getRawEventsStatus()
__STATIC_INLINE uint32_t DL_DAC12_getRawEventsStatus (DAC12_Regs * dac12, uint32_t eventMask)
Check interrupt flag of any DAC event.
Checks if any events are pending. Events do not have to be previously enabled.
Parameters
[in] dac12 Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to check. Bitwise OR of DL_DAC12_EVENT.
Returns
Which of the requested DAC interrupts are pending
Return values
Bitwise OR of DL_DAC12_EVENT values
DL_DAC12_clearEventsStatus()
__STATIC_INLINE void DL_DAC12_clearEventsStatus (DAC12_Regs * dac12, uint32_t eventMask)
Clear pending DAC events.
Parameters
[in] dac12 Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to clear. Bitwise OR of DL_DAC12_EVENT.
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale