MSPM0C110X Driver Library: dl_core.h File Reference
dl_core.h File Reference
Detailed Description
CPU Core Driver Library.
#include <stdint.h>
#include <ti/devices/msp/msp.h>
Macros
#define DL_CORE_CACHE_ENABLED (CPUSS_CTL_ICACHE_ENABLE)
Enables instruction caching on flash access.
#define DL_CORE_CACHE_DISABLED (CPUSS_CTL_ICACHE_DISABLE)
Disables instruction caching on flash access.
#define DL_CORE_PREFETCH_ENABLED (CPUSS_CTL_PREFETCH_ENABLE)
Enables instruction prefetch to Flash.
#define DL_CORE_PREFETCH_DISABLED (CPUSS_CTL_PREFETCH_DISABLE)
Disables instruction prefetch to Flash.
#define DL_CORE_LITERAL_CACHE_ENABLED (CPUSS_CTL_LITEN_ENABLE)
Enables caching and prefetching of literals. This is set only if the ICACHE or PREFETCH bits have been set respectively.
#define DL_CORE_LITERAL_CACHE_DISABLED (CPUSS_CTL_LITEN_DISABLE)
Disables caching and prefetching of literals.
#define delay_cycles(cycles) DL_Common_delayCycles(cycles)
Alias for DL_Common_delayCycles.
Functions
__STATIC_INLINE uint32_t DL_CORE_getImplementer (void)
Get the implementer code for the processor.
__STATIC_INLINE uint32_t DL_CORE_getVariant (void)
Get the major revision number 'n' in the 'npm' revision status.
__STATIC_INLINE uint32_t DL_CORE_getArchitecture (void)
Get the architecture of the processor.
__STATIC_INLINE uint32_t DL_CORE_getPartNumber (void)
Get part number of the processor (not the device)
__STATIC_INLINE uint32_t DL_CORE_getRevision (void)
Get the minor revision number 'm' in the 'npm' revision status.
__STATIC_INLINE void DL_CORE_configInstruction (uint32_t icache, uint32_t prefetch, uint32_t litCache)
Configures instruction caching in flash accesses and instruction prefetch to flash.
__STATIC_INLINE uint32_t DL_CORE_getInstructionConfig (void)
Returns instruction caching, prefetch, and literal cache configuration.
Function Documentation
DL_CORE_getImplementer()
__STATIC_INLINE uint32_t DL_CORE_getImplementer (void)
Get the implementer code for the processor.
Returns
The implementer code
Return values
0x41 for ARM
DL_CORE_getVariant()
__STATIC_INLINE uint32_t DL_CORE_getVariant (void)
Get the major revision number 'n' in the 'npm' revision status.
Returns
The major revision number
Return values
0x00 for revision 0
DL_CORE_getArchitecture()
__STATIC_INLINE uint32_t DL_CORE_getArchitecture (void)
Get the architecture of the processor.
Returns
Value that defines the architecture of the processor
Return values
0x0C for ARMv6-M architecture
DL_CORE_getPartNumber()
__STATIC_INLINE uint32_t DL_CORE_getPartNumber (void)
Get part number of the processor (not the device)
Returns
Value that defines the processor
Return values
0x0C60 for Cortex-M0+
DL_CORE_getRevision()
__STATIC_INLINE uint32_t DL_CORE_getRevision (void)
Get the minor revision number 'm' in the 'npm' revision status.
Returns
The minor revision number
Return values
0x01 for patch 1
DL_CORE_configInstruction()
__STATIC_INLINE void DL_CORE_configInstruction (uint32_t icache, uint32_t prefetch, uint32_t litCache)
Configures instruction caching in flash accesses and instruction prefetch to flash.
Parameters
icache [in] Instruction cache option DL_CORE_CACHE
prefetch [in] Instruction prefetch option DL_CORE_PREFETCH
litCache [in] Literal cache option DL_CORE_LITERAL_CACHE
Referenced by DL_FactoryRegion_getBOOTCRCData(), DL_FactoryRegion_getBSLPinI2CSCLFunction(), DL_FactoryRegion_getBSLPinI2CSCLPad(), DL_FactoryRegion_getBSLPinI2CSDAFunction(), DL_FactoryRegion_getBSLPinI2CSDAPad(), DL_FactoryRegion_getBSLPinInvokeGPIOLevel(), DL_FactoryRegion_getBSLPinInvokeGPIOModule(), DL_FactoryRegion_getBSLPinInvokeGPIOModulePad(), DL_FactoryRegion_getBSLPinInvokeGPIOPin(), DL_FactoryRegion_getBSLPinUARTRXDFunction(), DL_FactoryRegion_getBSLPinUARTRXDPad(), DL_FactoryRegion_getBSLPinUARTTXDFunction(), DL_FactoryRegion_getBSLPinUARTTXDPad(), DL_FactoryRegion_getDATAFlashSize(), DL_FactoryRegion_getMAINFlashSize(), DL_FactoryRegion_getManufacturerCode(), DL_FactoryRegion_getNumBanks(), DL_FactoryRegion_getPartNumber(), DL_FactoryRegion_getSRAMFlashSize(), DL_FactoryRegion_getTemperatureVoltage(), DL_FactoryRegion_getTraceID(), DL_FactoryRegion_getUserIDMajorRev(), DL_FactoryRegion_getUserIDMinorRev(), DL_FactoryRegion_getUserIDPart(), DL_FactoryRegion_getUserIDVariant(), and DL_FactoryRegion_getVersion().
DL_CORE_getInstructionConfig()
__STATIC_INLINE uint32_t DL_CORE_getInstructionConfig (void)
Returns instruction caching, prefetch, and literal cache configuration.
Returns
Bitwise OR of DL_CORE_CACHE and DL_CORE_PREFETCH and DL_CORE_LITERAL_CACHE
Referenced by DL_FactoryRegion_getBOOTCRCData(), DL_FactoryRegion_getBSLPinI2CSCLFunction(), DL_FactoryRegion_getBSLPinI2CSCLPad(), DL_FactoryRegion_getBSLPinI2CSDAFunction(), DL_FactoryRegion_getBSLPinI2CSDAPad(), DL_FactoryRegion_getBSLPinInvokeGPIOLevel(), DL_FactoryRegion_getBSLPinInvokeGPIOModule(), DL_FactoryRegion_getBSLPinInvokeGPIOModulePad(), DL_FactoryRegion_getBSLPinInvokeGPIOPin(), DL_FactoryRegion_getBSLPinUARTRXDFunction(), DL_FactoryRegion_getBSLPinUARTRXDPad(), DL_FactoryRegion_getBSLPinUARTTXDFunction(), DL_FactoryRegion_getBSLPinUARTTXDPad(), DL_FactoryRegion_getDATAFlashSize(), DL_FactoryRegion_getMAINFlashSize(), DL_FactoryRegion_getManufacturerCode(), DL_FactoryRegion_getNumBanks(), DL_FactoryRegion_getPartNumber(), DL_FactoryRegion_getSRAMFlashSize(), DL_FactoryRegion_getTemperatureVoltage(), DL_FactoryRegion_getTraceID(), DL_FactoryRegion_getUserIDMajorRev(), DL_FactoryRegion_getUserIDMinorRev(), DL_FactoryRegion_getUserIDPart(), DL_FactoryRegion_getUserIDVariant(), and DL_FactoryRegion_getVersion().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale