MSPM0L122X_L222X Driver Library: True Random Number Generator (TRNG)
True Random Number Generator (TRNG)
Modules
DL_TRNG_INTERRUPT
DL_TRNG_HEALTH_TEST_SUCCESS
Data Structures
struct DL_TRNG_backupConfig
Configuration structure to backup TRNG peripheral state before going to STOP/STANDBY mode. Not required after PG 1.0 silicon. Used by DL_TRNG_saveConfiguration.
Enumerations
enum DL_TRNG_IIDX {
DL_TRNG_IIDX_HEALTH_FAIL = TRNG_IIDX_STAT_IRQ_HEALTH_FAIL,
DL_TRNG_IIDX_CMD_DONE = TRNG_IIDX_STAT_IRQ_CMD_DONE,
DL_TRNG_IIDX_CMD_FAIL = TRNG_IIDX_STAT_IRQ_CMD_FAIL,
DL_TRNG_IIDX_CAPTURED_READY = TRNG_IIDX_STAT_IRQ_CAPTURED_RDY
}
enum DL_TRNG_DECIMATION_RATE {
DL_TRNG_DECIMATION_RATE_1 = 0x0,
DL_TRNG_DECIMATION_RATE_2 = 0x1,
DL_TRNG_DECIMATION_RATE_3 = 0x2,
DL_TRNG_DECIMATION_RATE_4 = 0x3,
DL_TRNG_DECIMATION_RATE_5 = 0x4,
DL_TRNG_DECIMATION_RATE_6 = 0x5,
DL_TRNG_DECIMATION_RATE_7 = 0x6,
DL_TRNG_DECIMATION_RATE_8 = 0x7
}
enum DL_TRNG_CMD {
DL_TRNG_CMD_PWROFF = TRNG_CTL_CMD_PWR_OFF,
DL_TRNG_CMD_TEST_DIG = TRNG_CTL_CMD_PWRUP_DIG,
DL_TRNG_CMD_TEST_ANA = TRNG_CTL_CMD_PWRUP_ANA,
DL_TRNG_CMD_NORM_FUNC = TRNG_CTL_CMD_NORM_FUNC
}
enum DL_TRNG_CLOCK_DIVIDE {
DL_TRNG_CLOCK_DIVIDE_1 = TRNG_CLKDIVIDE_RATIO_DIV_BY_1,
DL_TRNG_CLOCK_DIVIDE_2 = TRNG_CLKDIVIDE_RATIO_DIV_BY_2,
DL_TRNG_CLOCK_DIVIDE_4 = TRNG_CLKDIVIDE_RATIO_DIV_BY_4,
DL_TRNG_CLOCK_DIVIDE_6 = TRNG_CLKDIVIDE_RATIO_DIV_BY_6,
DL_TRNG_CLOCK_DIVIDE_8 = TRNG_CLKDIVIDE_RATIO_DIV_BY_8
}
enum DL_TRNG_STATE {
DL_TRNG_STATE_OFF = 0x0,
DL_TRNG_STATE_PWRUP_ES = 0x1,
DL_TRNG_STATE_NORM_FUNC = 0x3,
DL_TRNG_STATE_TEST_DIG = 0x7,
DL_TRNG_STATE_TEST_ANA = 0xB,
DL_TRNG_STATE_ERROR = 0xA,
DL_TRNG_STATE_PWRDOWN = 0x2
}
Functions
__STATIC_INLINE void DL_TRNG_enablePower (TRNG_Regs *trng)
Enables power on TRNG module.
__STATIC_INLINE void DL_TRNG_disablePower (TRNG_Regs *trng)
Disable power on TRNG module.
__STATIC_INLINE DL_TRNG_CLOCK_DIVIDE DL_TRNG_getClockDivider (TRNG_Regs *trng)
Get the clock divider on the TRNG module.
__STATIC_INLINE void DL_TRNG_setClockDivider (TRNG_Regs *trng, DL_TRNG_CLOCK_DIVIDE clockDivider)
Set the clock divider on the TRNG module.
__STATIC_INLINE void DL_TRNG_reset (TRNG_Regs *trng)
Resets the TRNG module.
__STATIC_INLINE bool DL_TRNG_isReset (TRNG_Regs *trng)
Returns if TRNG peripheral was reset.
__STATIC_INLINE bool DL_TRNG_isCaptureReady (TRNG_Regs *trng)
Returns if the data capture is ready.
__STATIC_INLINE bool DL_TRNG_isCommandDone (TRNG_Regs *trng)
Returns if the issued TRNG command is done.
__STATIC_INLINE bool DL_TRNG_isCommandFail (TRNG_Regs *trng)
Returns if the issued TRNG command failed.
__STATIC_INLINE bool DL_TRNG_isHealthTestFail (TRNG_Regs *trng)
Returns if a health test failed.
__STATIC_INLINE void DL_TRNG_setDecimationRate (TRNG_Regs *trng, DL_TRNG_DECIMATION_RATE decimationRate)
Set the decimation rate.
__STATIC_INLINE DL_TRNG_DECIMATION_RATE DL_TRNG_getDecimationRate (TRNG_Regs *trng)
Get the decimation rate.
__STATIC_INLINE uint8_t DL_TRNG_getDigitalHealthTestResults (TRNG_Regs *trng)
Get the digital health test results.
__STATIC_INLINE uint8_t DL_TRNG_getAnalogHealthTestResults (TRNG_Regs *trng)
Get the analog health test results.
__STATIC_INLINE uint32_t DL_TRNG_getCurrentState (TRNG_Regs *trng)
Get the current state of the TRNG front end FSM.
__STATIC_INLINE uint32_t DL_TRNG_getIssuedCommand (TRNG_Regs *trng)
Get the last accepted command that was issued to the TRNG.
__STATIC_INLINE bool DL_TRNG_isRepetitionTestFail (TRNG_Regs *trng)
Indicates if the repetition counter test caused the most recent failure.
__STATIC_INLINE bool DL_TRNG_isAdaptiveTestFail (TRNG_Regs *trng)
Indicates if the Adaptive Proportion Test (1,2,3, or 4-bit counters) caused the most recent failure.
__STATIC_INLINE void DL_TRNG_enableInterrupt (TRNG_Regs *trng, uint32_t interruptMask)
Enable TRNG interrupt.
__STATIC_INLINE void DL_TRNG_disableInterrupt (TRNG_Regs *trng, uint32_t interruptMask)
Disable TRNG interrupt.
__STATIC_INLINE uint32_t DL_TRNG_getEnabledInterrupts (TRNG_Regs *trng, uint32_t interruptMask)
Check which TRNG interrupts are enabled.
__STATIC_INLINE uint32_t DL_TRNG_getEnabledInterruptStatus (TRNG_Regs *trng, uint32_t interruptMask)
Check interrupt flag of enabled TRNG interrupt.
__STATIC_INLINE uint32_t DL_TRNG_getRawInterruptStatus (TRNG_Regs *trng, uint32_t interruptMask)
Check interrupt flag of any TRNG interrupt.
__STATIC_INLINE DL_TRNG_IIDX DL_TRNG_getPendingInterrupt (TRNG_Regs *trng)
Get highest priority pending TRNG interrupt.
__STATIC_INLINE void DL_TRNG_clearInterruptStatus (TRNG_Regs *trng, uint32_t interruptMask)
Clear pending TRNG interrupt.
__STATIC_INLINE void DL_TRNG_sendCommand (TRNG_Regs *trng, DL_TRNG_CMD cmd)
Update control register's command bits to send a TRNG command.
__STATIC_INLINE uint32_t DL_TRNG_getCapture (TRNG_Regs *trng)
Get word capture from TRNG.
bool DL_TRNG_saveConfiguration (TRNG_Regs *trng, DL_TRNG_backupConfig *ptr)
Save TRNG configuration before entering a power loss state. Only necessary for PG 1.0 silicon.
bool DL_TRNG_restoreConfiguration (TRNG_Regs *trng, DL_TRNG_backupConfig *ptr)
Restore TRNG configuration after leaving a power loss state. Upon restoration, if the TRNG was not originally in OFF state, then the TRNG will be set to the normal operating mode. Only necessary for PG 1.0 silicon.
Detailed Description
Overview
The True Random Number Generator Driver Library allows full configuration of the MSPM0 TRNG module. The true random number generator (TRNG) block is an entropy source which can be used to generate random bit sequences.
Enumeration Type Documentation
DL_TRNG_IIDX
enum DL_TRNG_IIDX
Enumerator
DL_TRNG_IIDX_HEALTH_FAIL
TRNG interrupt index for health fail
DL_TRNG_IIDX_CMD_DONE
TRNG interrupt index for command done
DL_TRNG_IIDX_CMD_FAIL
TRNG interrupt index for command fail
DL_TRNG_IIDX_CAPTURED_READY
TRNG interrupt index indicating the capture buffer is ready
DL_TRNG_DECIMATION_RATE
enum DL_TRNG_DECIMATION_RATE
Enumerator
DL_TRNG_DECIMATION_RATE_1
Decimation by 1 (no decimation)
DL_TRNG_DECIMATION_RATE_2
Decimation rate 2 – take every other sample
DL_TRNG_DECIMATION_RATE_3
Decimation rate 3 – take every third sample
DL_TRNG_DECIMATION_RATE_4
Decimation rate 4 – take every fourth sample
DL_TRNG_DECIMATION_RATE_5
Decimation rate 5 – take every fifth sample
DL_TRNG_DECIMATION_RATE_6
Decimation rate 6 – take every sixth sample
DL_TRNG_DECIMATION_RATE_7
Decimation rate 7 – take every seventh sample
DL_TRNG_DECIMATION_RATE_8
Decimation rate 8 – take every eighth sample
DL_TRNG_CMD
enum DL_TRNG_CMD
Enumerator
DL_TRNG_CMD_PWROFF
TRNG command to power off analog blocks and digital blocks are gated
DL_TRNG_CMD_TEST_DIG
TRNG command to execute digital power-on self-tests
DL_TRNG_CMD_TEST_ANA
TRNG command to execute digital power-on self-tests
DL_TRNG_CMD_NORM_FUNC
TRNG command to go into normal operating mode
DL_TRNG_CLOCK_DIVIDE
enum DL_TRNG_CLOCK_DIVIDE
Enumerator
DL_TRNG_CLOCK_DIVIDE_1
Clock divide by 1
DL_TRNG_CLOCK_DIVIDE_2
Clock divide by 2
DL_TRNG_CLOCK_DIVIDE_4
Clock divide by 4
DL_TRNG_CLOCK_DIVIDE_6
Clock divide by 6
DL_TRNG_CLOCK_DIVIDE_8
Clock divide by 8
DL_TRNG_STATE
enum DL_TRNG_STATE
Enumerator
DL_TRNG_STATE_OFF
Current state of the TRNG is OFF
DL_TRNG_STATE_PWRUP_ES
Current state of the TRNG is PWRUP_ES
DL_TRNG_STATE_NORM_FUNC
Current state of the TRNG is NORM_FUNC
DL_TRNG_STATE_TEST_DIG
Current state of the TRNG is TEST_DIG
DL_TRNG_STATE_TEST_ANA
Current state of the TRNG is TEST_ANA
DL_TRNG_STATE_ERROR
Current state of the TRNG is ERROR
DL_TRNG_STATE_PWRDOWN
Current state of the TRNG is PWRDOWN_ES
Function Documentation
DL_TRNG_enablePower()
__STATIC_INLINE void DL_TRNG_enablePower (TRNG_Regs * trng)
Enables power on TRNG module.
Parameters
trng Pointer to the register overlay for the peripheral
DL_TRNG_disablePower()
__STATIC_INLINE void DL_TRNG_disablePower (TRNG_Regs * trng)
Disable power on TRNG module.
Parameters
trng Pointer to the register overlay for the peripheral
DL_TRNG_getClockDivider()
__STATIC_INLINE DL_TRNG_CLOCK_DIVIDE DL_TRNG_getClockDivider (TRNG_Regs * trng)
Get the clock divider on the TRNG module.
Parameters
trng Pointer to the register overlay for the peripheral
Returns
Clock divider value for the TRNG module
DL_TRNG_setClockDivider()
__STATIC_INLINE void DL_TRNG_setClockDivider (TRNG_Regs * trng, DL_TRNG_CLOCK_DIVIDE clockDivider)
Set the clock divider on the TRNG module.
Parameters
trng Pointer to the register overlay for the peripheral
clockDivider Clock divider value for the TRNG module. One of DL_TRNG_CLOCK_DIVIDE
DL_TRNG_reset()
__STATIC_INLINE void DL_TRNG_reset (TRNG_Regs * trng)
Resets the TRNG module.
Parameters
trng Pointer to the register overlay for the peripheral
DL_TRNG_isReset()
__STATIC_INLINE bool DL_TRNG_isReset (TRNG_Regs * trng)
Returns if TRNG peripheral was reset.
Parameters
trng Pointer to the register overlay for the peripheral
Returns
true if peripheral was reset
false if peripheral wasn't reset
DL_TRNG_isCaptureReady()
__STATIC_INLINE bool DL_TRNG_isCaptureReady (TRNG_Regs * trng)
Returns if the data capture is ready.
Parameters
trng Pointer to the register overlay for the peripheral
Returns
true if the data capture is ready
false if the data capture is not ready
DL_TRNG_isCommandDone()
__STATIC_INLINE bool DL_TRNG_isCommandDone (TRNG_Regs * trng)
Returns if the issued TRNG command is done.
Parameters
trng Pointer to the register overlay for the peripheral
Returns
true if the issued command is done
false if the issued command is not done
DL_TRNG_isCommandFail()
__STATIC_INLINE bool DL_TRNG_isCommandFail (TRNG_Regs * trng)
Returns if the issued TRNG command failed.
Parameters
trng Pointer to the register overlay for the peripheral
Returns
true if the issued command failed
false if the issued command failed
DL_TRNG_isHealthTestFail()
__STATIC_INLINE bool DL_TRNG_isHealthTestFail (TRNG_Regs * trng)
Returns if a health test failed.
Parameters
trng Pointer to the register overlay for the peripheral
Returns
true if a health test is failed
false if a health test did not fail
DL_TRNG_setDecimationRate()
__STATIC_INLINE void DL_TRNG_setDecimationRate (TRNG_Regs * trng, DL_TRNG_DECIMATION_RATE decimationRate)
Set the decimation rate.
Parameters
trng Pointer to the register overlay for the peripheral
decimationRate Decimation rate to set. One of DL_TRNG_DECIMATION_RATE
References DL_Common_updateReg().
DL_TRNG_getDecimationRate()
__STATIC_INLINE DL_TRNG_DECIMATION_RATE DL_TRNG_getDecimationRate (TRNG_Regs * trng)
Get the decimation rate.
Parameters
[in] trng Pointer to the register overlay for the peripheral
Returns
The decimation rate of the TRNG module
Return values
One of DL_TRNG_DECIMATION_RATE
DL_TRNG_getDigitalHealthTestResults()
__STATIC_INLINE uint8_t DL_TRNG_getDigitalHealthTestResults (TRNG_Regs * trng)
Get the digital health test results.
The test sequence includes eight tests, and each test reports its status in an individual result bit. As each test passes, the corresponding bit is set.
Parameters
trng Pointer to the register overlay for the peripheral
Returns
The results of the digital health tests
Return values
DL_TRNG_DIGITAL_HEALTH_TEST_SUCCESS if all tests passed, otherwise a bitmask of which tests passed
DL_TRNG_getAnalogHealthTestResults()
__STATIC_INLINE uint8_t DL_TRNG_getAnalogHealthTestResults (TRNG_Regs * trng)
Get the analog health test results.
Parameters
trng Pointer to the register overlay for the peripheral
Returns
The results of the analog health test
Return values
DL_TRNG_ANALOG_HEALTH_TEST_SUCCESS if success
0 if test failed
DL_TRNG_getCurrentState()
__STATIC_INLINE uint32_t DL_TRNG_getCurrentState (TRNG_Regs * trng)
Get the current state of the TRNG front end FSM.
This API should be called twice since two reads of the state are required as there is a chance of metastability when reading this register.
Parameters
trng Pointer to the register overlay for the peripheral
Returns
The current state of the TRNG
Return values
One of DL_TRNG_STATE
DL_TRNG_getIssuedCommand()
__STATIC_INLINE uint32_t DL_TRNG_getIssuedCommand (TRNG_Regs * trng)
Get the last accepted command that was issued to the TRNG.
Parameters
trng Pointer to the register overlay for the peripheral
Returns
The last issued accepted command
Return values
One of DL_TRNG_CMD
DL_TRNG_isRepetitionTestFail()
__STATIC_INLINE bool DL_TRNG_isRepetitionTestFail (TRNG_Regs * trng)
Indicates if the repetition counter test caused the most recent failure.
Parameters
trng Pointer to the register overlay for the peripheral
Returns
The status of the repetition test
Return values
true if the repetition test failed
false if the repetition test did not fail
DL_TRNG_isAdaptiveTestFail()
__STATIC_INLINE bool DL_TRNG_isAdaptiveTestFail (TRNG_Regs * trng)
Indicates if the Adaptive Proportion Test (1,2,3, or 4-bit counters) caused the most recent failure.
Parameters
trng Pointer to the register overlay for the peripheral
Returns
The status of the Adaptive Proportion Test
Return values
true if the repetition test failed
false if the repetition test did not fail
DL_TRNG_enableInterrupt()
__STATIC_INLINE void DL_TRNG_enableInterrupt (TRNG_Regs * trng, uint32_t interruptMask)
Enable TRNG interrupt.
Parameters
[in] trng Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_TRNG_INTERRUPT.
DL_TRNG_disableInterrupt()
__STATIC_INLINE void DL_TRNG_disableInterrupt (TRNG_Regs * trng, uint32_t interruptMask)
Disable TRNG interrupt.
Parameters
[in] trng Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_TRNG_INTERRUPT.
DL_TRNG_getEnabledInterrupts()
__STATIC_INLINE uint32_t DL_TRNG_getEnabledInterrupts (TRNG_Regs * trng, uint32_t interruptMask)
Check which TRNG interrupts are enabled.
Parameters
[in] trng Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_TRNG_IIDX.
Returns
Which of the requested TRNG interrupts are enabled
Return values
Bitwise OR of DL_TRNG_INTERRUPT values
DL_TRNG_getEnabledInterruptStatus()
__STATIC_INLINE uint32_t DL_TRNG_getEnabledInterruptStatus (TRNG_Regs * trng, uint32_t interruptMask)
Check interrupt flag of enabled TRNG interrupt.
Checks if the TRNG interrupt that was previously enabled is pending.
Parameters
[in] trng Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_TRNG_INTERRUPT.
Returns
If the enabled TRNG interrupt is pending
See also
DL_TRNG_enableInterrupt
DL_TRNG_getRawInterruptStatus()
__STATIC_INLINE uint32_t DL_TRNG_getRawInterruptStatus (TRNG_Regs * trng, uint32_t interruptMask)
Check interrupt flag of any TRNG interrupt.
Checks if the TRNG interrupt is pending. Interrupt does not have to be previously enabled.
Parameters
[in] trng Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_TRNG_INTERRUPT.
Returns
If the trng interrupt is pending
DL_TRNG_getPendingInterrupt()
__STATIC_INLINE DL_TRNG_IIDX DL_TRNG_getPendingInterrupt (TRNG_Regs * trng)
Get highest priority pending TRNG interrupt.
Checks if any of the TRNG interrupts are pending. Interrupts do not have to be previously enabled.
Parameters
[in] trng Pointer to the register overlay for the peripheral
Returns
The highest priority pending TRNG interrupt
Return values
One of DL_TRNG_IIDX
DL_TRNG_clearInterruptStatus()
__STATIC_INLINE void DL_TRNG_clearInterruptStatus (TRNG_Regs * trng, uint32_t interruptMask)
Clear pending TRNG interrupt.
Parameters
[in] trng Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_TRNG_INTERRUPT.
DL_TRNG_sendCommand()
__STATIC_INLINE void DL_TRNG_sendCommand (TRNG_Regs * trng, DL_TRNG_CMD cmd)
Update control register's command bits to send a TRNG command.
Parameters
[in] trng Pointer to the register overlay for the peripheral
[in] cmd Command to update the control register with
References DL_Common_updateReg().
DL_TRNG_getCapture()
__STATIC_INLINE uint32_t DL_TRNG_getCapture (TRNG_Regs * trng)
Get word capture from TRNG.
Gets the captured data from the decimation block.
Parameters
[in] trng Pointer to the register overlay for the peripheral
Return values
TRNG capture value
Precondition
The IRQ_CAPTURED_RDY IRQ should be asserted first, indicating that random bits are available for read-out.
See also
DL_TRNG_isCaptureReady
References DL_TRNG_restoreConfiguration(), and DL_TRNG_saveConfiguration().
DL_TRNG_saveConfiguration()
bool DL_TRNG_saveConfiguration (TRNG_Regs * trng, DL_TRNG_backupConfig * ptr)
Save TRNG configuration before entering a power loss state. Only necessary for PG 1.0 silicon.
Parameters
[in] trng Pointer to the register overlay for the peripheral
[in] ptr Configuration backup setup structure. See DL_TRNG_backupConfig.
Return values
FALSE if a configuration already exists in ptr (will not be overwritten). TRUE if a configuration was successfully saved
Referenced by DL_TRNG_getCapture().
DL_TRNG_restoreConfiguration()
bool DL_TRNG_restoreConfiguration (TRNG_Regs * trng, DL_TRNG_backupConfig * ptr)
Restore TRNG configuration after leaving a power loss state. Upon restoration, if the TRNG was not originally in OFF state, then the TRNG will be set to the normal operating mode. Only necessary for PG 1.0 silicon.
Parameters
[in] trng Pointer to the register overlay for the peripheral
[in] ptr Configuration backup setup structure. See DL_TRNG_backupConfig.
Return values
FALSE if a configuration does not exist in ptr (will not be loaded). TRUE if a configuration successfully loaded
Referenced by DL_TRNG_getCapture().
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale