MSPM0L122X_L222X Driver Library: Liquid Crystal Display (LCD)
Liquid Crystal Display (LCD)
Modules
DL_LCD_INTERRUPT
DL_LCD_SEGMENT_LINE
DL_LCD_MEMORY_BIT
DL_LCD_BLINK_MEMORY_BIT
Data Structures
struct DL_LCD_Config
Configuration struct for DL_LCD_init.
Enumerations
enum DL_LCD_FREQ_DIVIDE {
DL_LCD_FREQ_DIVIDE_1 = LCD_LCDCTL0_LCDDIVX_DIV_BY_1,
DL_LCD_FREQ_DIVIDE_2 = LCD_LCDCTL0_LCDDIVX_DIV_BY_2,
DL_LCD_FREQ_DIVIDE_3 = LCD_LCDCTL0_LCDDIVX_DIV_BY_3,
DL_LCD_FREQ_DIVIDE_4 = LCD_LCDCTL0_LCDDIVX_DIV_BY_4,
DL_LCD_FREQ_DIVIDE_5 = LCD_LCDCTL0_LCDDIVX_DIV_BY_5,
DL_LCD_FREQ_DIVIDE_6 = LCD_LCDCTL0_LCDDIVX_DIV_BY_6,
DL_LCD_FREQ_DIVIDE_7 = LCD_LCDCTL0_LCDDIVX_DIV_BY_7,
DL_LCD_FREQ_DIVIDE_8 = LCD_LCDCTL0_LCDDIVX_DIV_BY_8,
DL_LCD_FREQ_DIVIDE_9 = LCD_LCDCTL0_LCDDIVX_DIV_BY_9,
DL_LCD_FREQ_DIVIDE_10 = LCD_LCDCTL0_LCDDIVX_DIV_BY_10,
DL_LCD_FREQ_DIVIDE_11 = LCD_LCDCTL0_LCDDIVX_DIV_BY_11,
DL_LCD_FREQ_DIVIDE_12 = LCD_LCDCTL0_LCDDIVX_DIV_BY_12,
DL_LCD_FREQ_DIVIDE_13 = LCD_LCDCTL0_LCDDIVX_DIV_BY_13,
DL_LCD_FREQ_DIVIDE_14 = LCD_LCDCTL0_LCDDIVX_DIV_BY_14,
DL_LCD_FREQ_DIVIDE_15 = LCD_LCDCTL0_LCDDIVX_DIV_BY_15,
DL_LCD_FREQ_DIVIDE_16 = LCD_LCDCTL0_LCDDIVX_DIV_BY_16,
DL_LCD_FREQ_DIVIDE_17 = LCD_LCDCTL0_LCDDIVX_DIV_BY_17,
DL_LCD_FREQ_DIVIDE_18 = LCD_LCDCTL0_LCDDIVX_DIV_BY_18,
DL_LCD_FREQ_DIVIDE_19 = LCD_LCDCTL0_LCDDIVX_DIV_BY_19,
DL_LCD_FREQ_DIVIDE_20 = LCD_LCDCTL0_LCDDIVX_DIV_BY_20,
DL_LCD_FREQ_DIVIDE_21 = LCD_LCDCTL0_LCDDIVX_DIV_BY_21,
DL_LCD_FREQ_DIVIDE_22 = LCD_LCDCTL0_LCDDIVX_DIV_BY_22,
DL_LCD_FREQ_DIVIDE_23 = LCD_LCDCTL0_LCDDIVX_DIV_BY_23,
DL_LCD_FREQ_DIVIDE_24 = LCD_LCDCTL0_LCDDIVX_DIV_BY_24,
DL_LCD_FREQ_DIVIDE_25 = LCD_LCDCTL0_LCDDIVX_DIV_BY_25,
DL_LCD_FREQ_DIVIDE_26 = LCD_LCDCTL0_LCDDIVX_DIV_BY_26,
DL_LCD_FREQ_DIVIDE_27 = LCD_LCDCTL0_LCDDIVX_DIV_BY_27,
DL_LCD_FREQ_DIVIDE_28 = LCD_LCDCTL0_LCDDIVX_DIV_BY_28,
DL_LCD_FREQ_DIVIDE_29 = LCD_LCDCTL0_LCDDIVX_DIV_BY_29,
DL_LCD_FREQ_DIVIDE_30 = LCD_LCDCTL0_LCDDIVX_DIV_BY_30,
DL_LCD_FREQ_DIVIDE_31 = LCD_LCDCTL0_LCDDIVX_DIV_BY_31,
DL_LCD_FREQ_DIVIDE_32 = LCD_LCDCTL0_LCDDIVX_DIV_BY_32
}
enum DL_LCD_MUX_RATE {
DL_LCD_MUX_RATE_STATIC = LCD_LCDCTL0_LCDMXX_MX_STATIC,
DL_LCD_MUX_RATE_2 = LCD_LCDCTL0_LCDMXX_MX_2,
DL_LCD_MUX_RATE_3 = LCD_LCDCTL0_LCDMXX_MX_3,
DL_LCD_MUX_RATE_4 = LCD_LCDCTL0_LCDMXX_MX_4,
DL_LCD_MUX_RATE_5 = LCD_LCDCTL0_LCDMXX_MX_5,
DL_LCD_MUX_RATE_6 = LCD_LCDCTL0_LCDMXX_MX_6,
DL_LCD_MUX_RATE_7 = LCD_LCDCTL0_LCDMXX_MX_7,
DL_LCD_MUX_RATE_8 = LCD_LCDCTL0_LCDMXX_MX_8
}
enum DL_LCD_WAVEFORM_POWERMODE {
DL_LCD_WAVEFORM_POWERMODE_LOWPOWER = LCD_LCDCTL0_LCDLP_LP_LCD,
DL_LCD_WAVEFORM_POWERMODE_STANDARD = LCD_LCDCTL0_LCDLP_STD_LCD
}
enum DL_LCD_BLINKING_DIVIDE {
DL_LCD_BLINKING_DIVIDE_BY_2 = LCD_LCDBLKCTL_LCDBLKPREX_DIV_BY_2,
DL_LCD_BLINKING_DIVIDE_BY_4 = LCD_LCDBLKCTL_LCDBLKPREX_DIV_BY_4,
DL_LCD_BLINKING_DIVIDE_BY_8 = LCD_LCDBLKCTL_LCDBLKPREX_DIV_BY_8,
DL_LCD_BLINKING_DIVIDE_BY_16 = LCD_LCDBLKCTL_LCDBLKPREX_DIV_BY_16,
DL_LCD_BLINKING_DIVIDE_BY_32 = LCD_LCDBLKCTL_LCDBLKPREX_DIV_BY_32,
DL_LCD_BLINKING_DIVIDE_BY_64 = LCD_LCDBLKCTL_LCDBLKPREX_DIV_BY_64,
DL_LCD_BLINKING_DIVIDE_BY_128 = LCD_LCDBLKCTL_LCDBLKPREX_DIV_BY_128,
DL_LCD_BLINKING_DIVIDE_BY_256 = LCD_LCDBLKCTL_LCDBLKPREX_DIV_BY_256
}
enum DL_LCD_BLINKING_MODE {
DL_LCD_BLINKING_MODE_DISABLED = LCD_LCDBLKCTL_LCDBLKMODX_BLINK_DISABLE,
DL_LCD_BLINKING_MODE_INDIVIDUAL_SEGMENTS,
DL_LCD_BLINKING_MODE_ALL_SEGMENTS = LCD_LCDBLKCTL_LCDBLKMODX_BLINK_ALL,
DL_LCD_BLINKING_MODE_TOGGLE = LCD_LCDBLKCTL_LCDBLKMODX_BKINK_TOGGLE
}
enum DL_LCD_CHARGE_PUMP_FREQUENCY {
DL_LCD_CHARGE_PUMP_FREQUENCY_4096HZ = LCD_LCDVCTL_LCDCPFSELX_DIV_BY_1_BY_8,
DL_LCD_CHARGE_PUMP_FREQUENCY_2048HZ = LCD_LCDVCTL_LCDCPFSELX_DIV_BY_2_BY_8,
DL_LCD_CHARGE_PUMP_FREQUENCY_1365HZ = LCD_LCDVCTL_LCDCPFSELX_DIV_BY_3_BY_8,
DL_LCD_CHARGE_PUMP_FREQUENCY_1024HZ = LCD_LCDVCTL_LCDCPFSELX_DIV_BY_4_BY_8,
DL_LCD_CHARGE_PUMP_FREQUENCY_819HZ = LCD_LCDVCTL_LCDCPFSELX_DIV_BY_5_BY_8,
DL_LCD_CHARGE_PUMP_FREQUENCY_682HZ = LCD_LCDVCTL_LCDCPFSELX_DIV_BY_6_BY_8,
DL_LCD_CHARGE_PUMP_FREQUENCY_585HZ = LCD_LCDVCTL_LCDCPFSELX_DIV_BY_7_BY_8,
DL_LCD_CHARGE_PUMP_FREQUENCY_512HZ = LCD_LCDVCTL_LCDCPFSELX_DIV_BY_8_BY_8,
DL_LCD_CHARGE_PUMP_FREQUENCY_455HZ = LCD_LCDVCTL_LCDCPFSELX_DIV_BY_9_BY_8,
DL_LCD_CHARGE_PUMP_FREQUENCY_409HZ = LCD_LCDVCTL_LCDCPFSELX_DIV_BY_10_BY_8,
DL_LCD_CHARGE_PUMP_FREQUENCY_372HZ = LCD_LCDVCTL_LCDCPFSELX_DIV_BY_11_BY_8,
DL_LCD_CHARGE_PUMP_FREQUENCY_341HZ = LCD_LCDVCTL_LCDCPFSELX_DIV_BY_12_BY_8,
DL_LCD_CHARGE_PUMP_FREQUENCY_315HZ = LCD_LCDVCTL_LCDCPFSELX_DIV_BY_13_BY_8,
DL_LCD_CHARGE_PUMP_FREQUENCY_292HZ = LCD_LCDVCTL_LCDCPFSELX_DIV_BY_14_BY_8,
DL_LCD_CHARGE_PUMP_FREQUENCY_273HZ = LCD_LCDVCTL_LCDCPFSELX_DIV_BY_15_BY_8,
DL_LCD_CHARGE_PUMP_FREQUENCY_256HZ = LCD_LCDVCTL_LCDCPFSELX_DIV_BY_16_BY_8
}
enum DL_LCD_VREF_INTERNAL {
DL_LCD_VREF_INTERNAL_2_60V = LCD_LCDVCTL_VLCDX_SEL_2P60V,
DL_LCD_VREF_INTERNAL_2_66V = LCD_LCDVCTL_VLCDX_SEL_2P66V,
DL_LCD_VREF_INTERNAL_2_72V = LCD_LCDVCTL_VLCDX_SEL_2P72V,
DL_LCD_VREF_INTERNAL_2_78V = LCD_LCDVCTL_VLCDX_SEL_2P78V,
DL_LCD_VREF_INTERNAL_2_84V = LCD_LCDVCTL_VLCDX_SEL_2P84V,
DL_LCD_VREF_INTERNAL_2_90V = LCD_LCDVCTL_VLCDX_SEL_2P90V,
DL_LCD_VREF_INTERNAL_2_96V = LCD_LCDVCTL_VLCDX_SEL_2P96V,
DL_LCD_VREF_INTERNAL_3_02V = LCD_LCDVCTL_VLCDX_SEL_3P02V,
DL_LCD_VREF_INTERNAL_3_08V = LCD_LCDVCTL_VLCDX_SEL_3P08V,
DL_LCD_VREF_INTERNAL_3_14V = LCD_LCDVCTL_VLCDX_SEL_3P14V,
DL_LCD_VREF_INTERNAL_3_20V = LCD_LCDVCTL_VLCDX_SEL_3P20V,
DL_LCD_VREF_INTERNAL_3_26V = LCD_LCDVCTL_VLCDX_SEL_3P26V,
DL_LCD_VREF_INTERNAL_3_32V = LCD_LCDVCTL_VLCDX_SEL_3P32V,
DL_LCD_VREF_INTERNAL_3_38V = LCD_LCDVCTL_VLCDX_SEL_3P38V,
DL_LCD_VREF_INTERNAL_3_44V = LCD_LCDVCTL_VLCDX_SEL_3P44V,
DL_LCD_VREF_INTERNAL_3_50V = LCD_LCDVCTL_VLCDX_SEL_3P50V
}
enum DL_LCD_R33_SOURCE {
DL_LCD_R33_SOURCE_EXTERNAL = LCD_LCDVCTL_LCDSELVDD_SEL_EXT_SUPPLY,
DL_LCD_R33_SOURCE_INTERNAL = LCD_LCDVCTL_LCDSELVDD_SEL_AVDD
}
enum DL_LCD_POWER_MODE {
DL_LCD_POWER_MODE_LOW = LCD_LCDVCTL_LCD_HP_LP_LP_MODE,
DL_LCD_POWER_MODE_HIGH = LCD_LCDVCTL_LCD_HP_LP_HP_MODE
}
enum DL_LCD_BIAS_VOLTAGE_SOURCE {
DL_LCD_BIAS_VOLTAGE_SOURCE_R33 = LCD_LCDVCTL_VLCDSEL_VDD_R33_SEL_R33,
DL_LCD_BIAS_VOLTAGE_SOURCE_AVDD = LCD_LCDVCTL_VLCDSEL_VDD_R33_SEL_AVDD
}
enum DL_LCD_BIAS {
DL_LCD_BIAS_ONE_THIRD = LCD_LCDVCTL_LCDBIASSEL_ONE_BY_3_BIAS,
DL_LCD_BIAS_ONE_FOURTH = LCD_LCDVCTL_LCDBIASSEL_ONE_BY_4_BIAS
}
enum DL_LCD_REFERENCE_MODE {
DL_LCD_REFERENCE_MODE_STATIC = LCD_LCDVCTL_LCDREFMODE_STATIC_MODE,
DL_LCD_REFERENCE_MODE_SWITCHED = LCD_LCDVCTL_LCDREFMODE_SWITCHED_MODE
}
enum DL_LCD_DISP {
DL_LCD_DISPLAY_REGISTERS_MEMORY = LCD_LCDMEMCTL_LCDDISP_SEL_LCD_MEM_REGS,
DL_LCD_DISPLAY_REGISTERS_BLINKING_MEMORY
}
enum DL_LCD_EVENT_LINE_MODE {
DL_LCD_EVENT_LINE_MODE_DISABLED = LCD_EVT_MODE_INT0_CFG_DISABLE,
DL_LCD_EVENT_LINE_MODE_SOFTWARE = LCD_EVT_MODE_INT0_CFG_SOFTWARE,
DL_LCD_EVENT_LINE_MODE_HARDWARE = LCD_EVT_MODE_INT0_CFG_HARDWARE
}
enum DL_LCD_IIDX {
DL_LCD_IIDX_NO_INT = LCD_IIDX_STAT_NO_INTR,
DL_LCD_IIDX_FRAME_START = LCD_IIDX_STAT_FRAME_START,
DL_LCD_IIDX_BLINKING_SEGMENTS_OFF = LCD_IIDX_STAT_BLK_OFF,
DL_LCD_IIDX_BLINKING_SEGMENTS_ON = LCD_IIDX_STAT_BLK_ON
}
enum DL_LCD_MEMORY {
DL_LCD_MEMORY_0 = 0,
DL_LCD_MEMORY_1 = 1,
DL_LCD_MEMORY_2 = 2,
DL_LCD_MEMORY_3 = 3,
DL_LCD_MEMORY_4 = 4,
DL_LCD_MEMORY_5 = 5,
DL_LCD_MEMORY_6 = 6,
DL_LCD_MEMORY_7 = 7,
DL_LCD_MEMORY_8 = 8,
DL_LCD_MEMORY_9 = 9,
DL_LCD_MEMORY_10 = 10,
DL_LCD_MEMORY_11 = 11,
DL_LCD_MEMORY_12 = 12,
DL_LCD_MEMORY_13 = 13,
DL_LCD_MEMORY_14 = 14,
DL_LCD_MEMORY_15 = 15,
DL_LCD_MEMORY_16 = 16,
DL_LCD_MEMORY_17 = 17,
DL_LCD_MEMORY_18 = 18,
DL_LCD_MEMORY_19 = 19,
DL_LCD_MEMORY_20 = 20,
DL_LCD_MEMORY_21 = 21,
DL_LCD_MEMORY_22 = 22,
DL_LCD_MEMORY_23 = 23,
DL_LCD_MEMORY_24 = 24,
DL_LCD_MEMORY_25 = 25,
DL_LCD_MEMORY_26 = 26,
DL_LCD_MEMORY_27 = 27,
DL_LCD_MEMORY_28 = 28,
DL_LCD_MEMORY_29 = 29,
DL_LCD_MEMORY_30 = 30,
DL_LCD_MEMORY_31 = 31,
DL_LCD_MEMORY_32 = 32,
DL_LCD_MEMORY_33 = 33,
DL_LCD_MEMORY_34 = 34,
DL_LCD_MEMORY_35 = 35,
DL_LCD_MEMORY_36 = 36,
DL_LCD_MEMORY_37 = 37,
DL_LCD_MEMORY_38 = 38,
DL_LCD_MEMORY_39 = 39,
DL_LCD_MEMORY_40 = 40,
DL_LCD_MEMORY_41 = 41,
DL_LCD_MEMORY_42 = 42,
DL_LCD_MEMORY_43 = 43,
DL_LCD_MEMORY_44 = 44,
DL_LCD_MEMORY_45 = 45,
DL_LCD_MEMORY_46 = 46,
DL_LCD_MEMORY_47 = 47,
DL_LCD_MEMORY_48 = 48,
DL_LCD_MEMORY_49 = 49,
DL_LCD_MEMORY_50 = 50,
DL_LCD_MEMORY_51 = 51,
DL_LCD_MEMORY_52 = 52,
DL_LCD_MEMORY_53 = 53,
DL_LCD_MEMORY_54 = 54,
DL_LCD_MEMORY_55 = 55,
DL_LCD_MEMORY_56 = 56,
DL_LCD_MEMORY_57 = 57,
DL_LCD_MEMORY_58 = 58,
DL_LCD_MEMORY_59 = 59,
DL_LCD_MEMORY_60 = 60,
DL_LCD_MEMORY_61 = 61,
DL_LCD_MEMORY_62 = 62,
DL_LCD_MEMORY_63 = 63
}
enum DL_LCD_BLINKING_MEMORY {
DL_LCD_BLINKING_MEMORY_0 = 0,
DL_LCD_BLINKING_MEMORY_1 = 1,
DL_LCD_BLINKING_MEMORY_2 = 2,
DL_LCD_BLINKING_MEMORY_3 = 3,
DL_LCD_BLINKING_MEMORY_4 = 4,
DL_LCD_BLINKING_MEMORY_5 = 5,
DL_LCD_BLINKING_MEMORY_6 = 6,
DL_LCD_BLINKING_MEMORY_7 = 7,
DL_LCD_BLINKING_MEMORY_8 = 8,
DL_LCD_BLINKING_MEMORY_9 = 9,
DL_LCD_BLINKING_MEMORY_10 = 10,
DL_LCD_BLINKING_MEMORY_11 = 11,
DL_LCD_BLINKING_MEMORY_12 = 12,
DL_LCD_BLINKING_MEMORY_13 = 13,
DL_LCD_BLINKING_MEMORY_14 = 14,
DL_LCD_BLINKING_MEMORY_15 = 15,
DL_LCD_BLINKING_MEMORY_16 = 16,
DL_LCD_BLINKING_MEMORY_17 = 17,
DL_LCD_BLINKING_MEMORY_18 = 18,
DL_LCD_BLINKING_MEMORY_19 = 19,
DL_LCD_BLINKING_MEMORY_20 = 20,
DL_LCD_BLINKING_MEMORY_21 = 21,
DL_LCD_BLINKING_MEMORY_22 = 22,
DL_LCD_BLINKING_MEMORY_23 = 23,
DL_LCD_BLINKING_MEMORY_24 = 24,
DL_LCD_BLINKING_MEMORY_25 = 25,
DL_LCD_BLINKING_MEMORY_26 = 26,
DL_LCD_BLINKING_MEMORY_27 = 27,
DL_LCD_BLINKING_MEMORY_28 = 28,
DL_LCD_BLINKING_MEMORY_29 = 29,
DL_LCD_BLINKING_MEMORY_30 = 30,
DL_LCD_BLINKING_MEMORY_31 = 31
}
enum DL_LCD_COM {
DL_LCD_COM_0 = 0x01,
DL_LCD_COM_1 = 0x02,
DL_LCD_COM_2 = 0x04,
DL_LCD_COM_3 = 0x08,
DL_LCD_COM_4 = 0x10,
DL_LCD_COM_5 = 0x20,
DL_LCD_COM_6 = 0x40,
DL_LCD_COM_7 = 0x80
}
enum DL_LCD_VREFGEN_CYCLES {
DL_LCD_VREFGEN_CYCLES_16 = LCD_LCDVREFCFG_ONTIME_ONTIME16,
DL_LCD_VREFGEN_CYCLES_32 = LCD_LCDVREFCFG_ONTIME_ONTIME32,
DL_LCD_VREFGEN_CYCLES_128 = LCD_LCDVREFCFG_ONTIME_ONTIME128,
DL_LCD_VREFGEN_CYCLES_256 = LCD_LCDVREFCFG_ONTIME_ONTIME256
}
Functions
void DL_LCD_init (LCD_Regs *lcd, DL_LCD_Config *config)
Initialize the LCD peripheral.
void DL_LCD_setPinAsLCDFunction (LCD_Regs *lcd, uint32_t pin)
Enable a pin as LCD function.
void DL_LCD_setPinAsPortFunction (LCD_Regs *lcd, uint8_t pin)
Enable a pin as port function.
void DL_LCD_setPinAsCommon (LCD_Regs *lcd, uint8_t pin, uint32_t com)
Enable an LCD function pin as COM.
void DL_LCD_setPinAsSegment (LCD_Regs *lcd, uint8_t pin)
Enable an LCD function pin as Segment.
__STATIC_INLINE void DL_LCD_enablePower (LCD_Regs *lcd)
Enables power to the LCD module.
__STATIC_INLINE void DL_LCD_disablePower (LCD_Regs *lcd)
Disables power to the LCD module.
__STATIC_INLINE bool DL_LCD_isPowerEnabled (LCD_Regs *lcd)
Checks if power module on LCD is enabled.
__STATIC_INLINE void DL_LCD_reset (LCD_Regs *lcd)
Resets LCD peripheral.
__STATIC_INLINE bool DL_LCD_isReset (LCD_Regs *lcd)
Checks if LCD peripheral was reset.
__STATIC_INLINE DL_LCD_EVENT_LINE_MODE DL_LCD_getEventLineMode (LCD_Regs *lcd)
Get the event line mode.
__STATIC_INLINE DL_LCD_IIDX DL_LCD_getPendingInterrupt (LCD_Regs *lcd)
Gets the highest priority pending interrupt.
__STATIC_INLINE void DL_LCD_enableInterrupt (LCD_Regs *lcd, uint32_t interruptMask)
Enable LCD interrupts.
__STATIC_INLINE void DL_LCD_disableInterrupt (LCD_Regs *lcd, uint32_t interruptMask)
Disable LCD interrupts.
__STATIC_INLINE uint32_t DL_LCD_getEnabledInterrupts (LCD_Regs *lcd, uint32_t interruptMask)
Check which LCD interrupts are enabled.
__STATIC_INLINE uint32_t DL_LCD_getRawInterruptStatus (LCD_Regs *lcd, uint32_t interruptMask)
Check interrupt flag of any LCD interrupt.
__STATIC_INLINE uint32_t DL_LCD_getEnabledInterruptStatus (LCD_Regs *lcd, uint32_t interruptMask)
Check interrupt flag of enabled LCD interrupts.
__STATIC_INLINE void DL_LCD_setInterrupts (LCD_Regs *lcd, uint32_t interruptMask)
Set LCD interrupts.
__STATIC_INLINE void DL_LCD_clearInterruptStatus (LCD_Regs *lcd, uint32_t interruptMask)
Clear pending LCD interrupts.
__STATIC_INLINE void DL_LCD_enableExternalSync (LCD_Regs *lcd)
Enable external synchronization.
__STATIC_INLINE void DL_LCD_disableExternalSync (LCD_Regs *lcd)
Disable external synchronization.
__STATIC_INLINE bool DL_LCD_isExternalSyncEnabled (LCD_Regs *lcd)
Checks if external synchronization is enabled.
__STATIC_INLINE void DL_LCD_setFreqDiv (LCD_Regs *lcd, DL_LCD_FREQ_DIVIDE fDiv)
Set the LCD frequency divider.
__STATIC_INLINE DL_LCD_FREQ_DIVIDE DL_LCD_getFreqDiv (LCD_Regs *lcd)
Get the LCD frequency divider.
__STATIC_INLINE void DL_LCD_setMuxRate (LCD_Regs *lcd, DL_LCD_MUX_RATE muxRate)
Set the LCD mux rate.
__STATIC_INLINE DL_LCD_MUX_RATE DL_LCD_getMuxRate (LCD_Regs *lcd)
Get the LCD mux rate.
__STATIC_INLINE void DL_LCD_turnSegmentsOn (LCD_Regs *lcd)
Turns LCD segments on.
__STATIC_INLINE void DL_LCD_turnSegmentsOff (LCD_Regs *lcd)
Turns LCD segments off.
__STATIC_INLINE void DL_LCD_setWaveformPowerMode (LCD_Regs *lcd, DL_LCD_WAVEFORM_POWERMODE waveformPowerMode)
Set the waveform power mode.
__STATIC_INLINE DL_LCD_WAVEFORM_POWERMODE DL_LCD_getWaveformPowerMode (LCD_Regs *lcd)
Get the waveform power mode.
__STATIC_INLINE void DL_LCD_enable (LCD_Regs *lcd)
Enables the LCD module.
__STATIC_INLINE void DL_LCD_disable (LCD_Regs *lcd)
Disables the LCD module.
__STATIC_INLINE void DL_LCD_setBlinkingControl (LCD_Regs *lcd, DL_LCD_BLINKING_DIVIDE blinkFreqDiv, DL_LCD_BLINKING_MODE blinkMode)
Set the blinking frequency divider and blinking mode.
__STATIC_INLINE DL_LCD_BLINKING_DIVIDE DL_LCD_getBlinkingFreqDiv (LCD_Regs *lcd)
Get the blinking frequency divider.
__STATIC_INLINE DL_LCD_BLINKING_MODE DL_LCD_getBlinkingMode (LCD_Regs *lcd)
Get the blinking mode.
__STATIC_INLINE void DL_LCD_clearAllBlinkingMemoryRegs (LCD_Regs *lcd)
Clear LCD blinking memory.
__STATIC_INLINE void DL_LCD_clearAllMemoryRegs (LCD_Regs *lcd)
Clear LCD memory.
__STATIC_INLINE void DL_LCD_selectMemRegsForDisplay (LCD_Regs *lcd, DL_LCD_DISP dispSel)
Select LCD memory registers for display.
__STATIC_INLINE DL_LCD_DISP DL_LCD_getSelectedMemRegsForDisplay (LCD_Regs *lcd)
Get the LCD memory registers selected for display.
__STATIC_INLINE void DL_LCD_enableVBOOST (LCD_Regs *lcd)
Enables VBOOST on LCD module.
__STATIC_INLINE void DL_LCD_disableVBOOST (LCD_Regs *lcd)
Disables VBOOST on LCD module.
__STATIC_INLINE void DL_LCD_setChargePumpFreq (LCD_Regs *lcd, DL_LCD_CHARGE_PUMP_FREQUENCY chargePumpFreq)
Set charge pump frequency.
__STATIC_INLINE DL_LCD_CHARGE_PUMP_FREQUENCY DL_LCD_getChargePumpFreq (LCD_Regs *lcd)
Get the charge pump frequency.
__STATIC_INLINE void DL_LCD_setVREFInternal (LCD_Regs *lcd, DL_LCD_VREF_INTERNAL vrefInternal)
Set internal reference voltage.
__STATIC_INLINE DL_LCD_VREF_INTERNAL DL_LCD_getVREFInternal (LCD_Regs *lcd)
Get the internal reference voltage.
__STATIC_INLINE void DL_LCD_enableChargePump (LCD_Regs *lcd)
Enables charge pump.
__STATIC_INLINE void DL_LCD_disableChargePump (LCD_Regs *lcd)
Disables charge pump.
__STATIC_INLINE void DL_LCD_enableVREFInternal (LCD_Regs *lcd)
Enables internal reference voltage.
__STATIC_INLINE void DL_LCD_disableVREFInternal (LCD_Regs *lcd)
Disables internal reference voltage.
__STATIC_INLINE void DL_LCD_setR33source (LCD_Regs *lcd, DL_LCD_R33_SOURCE r33Source)
Set source for R33.
__STATIC_INLINE DL_LCD_R33_SOURCE DL_LCD_getR33Source (LCD_Regs *lcd)
Get the source for R33.
__STATIC_INLINE void DL_LCD_setInternalBiasPowerMode (LCD_Regs *lcd, DL_LCD_POWER_MODE powerMode)
Select internal bias power mode.
__STATIC_INLINE DL_LCD_POWER_MODE DL_LCD_getPowerMode (LCD_Regs *lcd)
Get power mode.
__STATIC_INLINE void DL_LCD_setBiasVoltageSource (LCD_Regs *lcd, DL_LCD_BIAS_VOLTAGE_SOURCE biasVoltageSource)
Set bias voltage source.
__STATIC_INLINE DL_LCD_BIAS_VOLTAGE_SOURCE DL_LCD_getBiasVoltageSource (LCD_Regs *lcd)
Get bias voltage source.
__STATIC_INLINE void DL_LCD_enableInternalBias (LCD_Regs *lcd)
Enables internal bias voltage resistor divider.
__STATIC_INLINE void DL_LCD_disableInternalBias (LCD_Regs *lcd)
Disables internal bias voltage resistor divider.
__STATIC_INLINE void DL_LCD_setBias (LCD_Regs *lcd, DL_LCD_BIAS biasSel)
Select LCD bias.
__STATIC_INLINE DL_LCD_BIAS DL_LCD_getBias (LCD_Regs *lcd)
Get bias for LCD.
__STATIC_INLINE void DL_LCD_setRefMode (LCD_Regs *lcd, DL_LCD_REFERENCE_MODE refMode)
Set reference mode for R13 voltage.
__STATIC_INLINE DL_LCD_REFERENCE_MODE DL_LCD_getRefMode (LCD_Regs *lcd)
Get reference mode for R13 voltage.
__STATIC_INLINE void DL_LCD_writeMemory (LCD_Regs *lcd, DL_LCD_MEMORY memIndex, uint32_t mask)
Write to bits in LCD memory index register.
__STATIC_INLINE void DL_LCD_setMemory (LCD_Regs *lcd, DL_LCD_MEMORY memIndex, uint32_t mask)
Set bits in LCD memory index register.
__STATIC_INLINE void DL_LCD_toggleMemory (LCD_Regs *lcd, DL_LCD_MEMORY memIndex, uint32_t mask)
Toggle bits in LCD memory index register.
__STATIC_INLINE void DL_LCD_clearMemory (LCD_Regs *lcd, DL_LCD_MEMORY memIndex, uint32_t mask)
Clear bits in LCD memory index register.
__STATIC_INLINE uint32_t DL_LCD_getMemory (LCD_Regs *lcd, DL_LCD_MEMORY memIndex)
Get bits in LCD memory index register.
__STATIC_INLINE void DL_LCD_writeBlinkingMemory (LCD_Regs *lcd, DL_LCD_BLINKING_MEMORY memIndex, uint32_t mask)
Write to bits in LCD blinking memory index register.
__STATIC_INLINE void DL_LCD_setBlinkingMemory (LCD_Regs *lcd, DL_LCD_BLINKING_MEMORY memIndex, uint32_t mask)
Set bits in LCD blinking memory index register.
__STATIC_INLINE void DL_LCD_toggleBlinkingMemory (LCD_Regs *lcd, DL_LCD_BLINKING_MEMORY memIndex, uint32_t mask)
Toggle bits in LCD blinking memory index register.
__STATIC_INLINE void DL_LCD_clearBlinkingMemory (LCD_Regs *lcd, DL_LCD_BLINKING_MEMORY memIndex, uint32_t mask)
Clear bits in LCD blinking memory index register.
__STATIC_INLINE uint32_t DL_LCD_getBlinkingMemory (LCD_Regs *lcd, DL_LCD_BLINKING_MEMORY memIndex)
Get bits in LCD blinking memory index register.
__STATIC_INLINE void DL_LCD_setVrefOnTimeCycles (LCD_Regs *lcd, DL_LCD_VREFGEN_CYCLES cycles)
Set number of cycles to enable voltage generation circuitry.
__STATIC_INLINE DL_LCD_VREFGEN_CYCLES DL_LCD_getVrefOnTimeCycles (LCD_Regs *lcd)
Get the number of cycles set to enable voltage generation circuitry.
Detailed Description
Overview
The LCD Library allows full configuration of the MSPM0 LCD module. The LCD controller creates the AC segment and common voltage signals to directly drive LCD displays.
Enumeration Type Documentation
DL_LCD_FREQ_DIVIDE
enum DL_LCD_FREQ_DIVIDE
Enumerator
DL_LCD_FREQ_DIVIDE_1
Divide fLCD by 1
DL_LCD_FREQ_DIVIDE_2
Divide fLCD by 2
DL_LCD_FREQ_DIVIDE_3
Divide fLCD by 3
DL_LCD_FREQ_DIVIDE_4
Divide fLCD by 4
DL_LCD_FREQ_DIVIDE_5
Divide fLCD by 5
DL_LCD_FREQ_DIVIDE_6
Divide fLCD by 6
DL_LCD_FREQ_DIVIDE_7
Divide fLCD by 7
DL_LCD_FREQ_DIVIDE_8
Divide fLCD by 8
DL_LCD_FREQ_DIVIDE_9
Divide fLCD by 9
DL_LCD_FREQ_DIVIDE_10
Divide fLCD by 10
DL_LCD_FREQ_DIVIDE_11
Divide fLCD by 11
DL_LCD_FREQ_DIVIDE_12
Divide fLCD by 12
DL_LCD_FREQ_DIVIDE_13
Divide fLCD by 13
DL_LCD_FREQ_DIVIDE_14
Divide fLCD by 14
DL_LCD_FREQ_DIVIDE_15
Divide fLCD by 15
DL_LCD_FREQ_DIVIDE_16
Divide fLCD by 16
DL_LCD_FREQ_DIVIDE_17
Divide fLCD by 17
DL_LCD_FREQ_DIVIDE_18
Divide fLCD by 18
DL_LCD_FREQ_DIVIDE_19
Divide fLCD by 19
DL_LCD_FREQ_DIVIDE_20
Divide fLCD by 20
DL_LCD_FREQ_DIVIDE_21
Divide fLCD by 21
DL_LCD_FREQ_DIVIDE_22
Divide fLCD by 22
DL_LCD_FREQ_DIVIDE_23
Divide fLCD by 23
DL_LCD_FREQ_DIVIDE_24
Divide fLCD by 24
DL_LCD_FREQ_DIVIDE_25
Divide fLCD by 25
DL_LCD_FREQ_DIVIDE_26
Divide fLCD by 26
DL_LCD_FREQ_DIVIDE_27
Divide fLCD by 27
DL_LCD_FREQ_DIVIDE_28
Divide fLCD by 28
DL_LCD_FREQ_DIVIDE_29
Divide fLCD by 29
DL_LCD_FREQ_DIVIDE_30
Divide fLCD by 30
DL_LCD_FREQ_DIVIDE_31
Divide fLCD by 31
DL_LCD_FREQ_DIVIDE_32
Divide fLCD by 32
DL_LCD_MUX_RATE
enum DL_LCD_MUX_RATE
Enumerator
DL_LCD_MUX_RATE_STATIC
Select LCD Mode: static
DL_LCD_MUX_RATE_2
Select LCD Mode: 2-mux
DL_LCD_MUX_RATE_3
Select LCD Mode: 3-mux
DL_LCD_MUX_RATE_4
Select LCD Mode: 4-mux
DL_LCD_MUX_RATE_5
Select LCD Mode: 5-mux
DL_LCD_MUX_RATE_6
Select LCD Mode: 6-mux
DL_LCD_MUX_RATE_7
Select LCD Mode: 7-mux
DL_LCD_MUX_RATE_8
Select LCD Mode: 8-mux
DL_LCD_WAVEFORM_POWERMODE
enum DL_LCD_WAVEFORM_POWERMODE
Enumerator
DL_LCD_WAVEFORM_POWERMODE_LOWPOWER
Select low power LCD waveforms
DL_LCD_WAVEFORM_POWERMODE_STANDARD
Select standard LCD waveforms
DL_LCD_BLINKING_DIVIDE
enum DL_LCD_BLINKING_DIVIDE
Enumerator
DL_LCD_BLINKING_DIVIDE_BY_2
Divide LCD blinking frequency by 2
DL_LCD_BLINKING_DIVIDE_BY_4
Divide LCD blinking frequency by 4
DL_LCD_BLINKING_DIVIDE_BY_8
Divide LCD blinking frequency by 8
DL_LCD_BLINKING_DIVIDE_BY_16
Divide LCD blinking frequency by 16
DL_LCD_BLINKING_DIVIDE_BY_32
Divide LCD blinking frequency by 32
DL_LCD_BLINKING_DIVIDE_BY_64
Divide LCD blinking frequency by 64
DL_LCD_BLINKING_DIVIDE_BY_128
Divide LCD blinking frequency by 128
DL_LCD_BLINKING_DIVIDE_BY_256
Divide LCD blinking frequency by 256
DL_LCD_BLINKING_MODE
enum DL_LCD_BLINKING_MODE
Enumerator
DL_LCD_BLINKING_MODE_DISABLED
Blinking disabled
DL_LCD_BLINKING_MODE_INDIVIDUAL_SEGMENTS
Blinking of individual segments as enabled in LCDBMx
DL_LCD_BLINKING_MODE_ALL_SEGMENTS
Blinking of all segments
DL_LCD_BLINKING_MODE_TOGGLE
Switch between display contents stored in LCDMx and LCDMBx
DL_LCD_CHARGE_PUMP_FREQUENCY
enum DL_LCD_CHARGE_PUMP_FREQUENCY
Enumerator
DL_LCD_CHARGE_PUMP_FREQUENCY_4096HZ
32.768 kHz / 1 / 8 = 4.096 kHz
DL_LCD_CHARGE_PUMP_FREQUENCY_2048HZ
32.768 kHz / 2 / 8 = 2.048 kHz
DL_LCD_CHARGE_PUMP_FREQUENCY_1365HZ
32.768 kHz / 3 / 8 = 1.365 kHz
DL_LCD_CHARGE_PUMP_FREQUENCY_1024HZ
32.768 kHz / 4 / 8 = 1.024 kHz
DL_LCD_CHARGE_PUMP_FREQUENCY_819HZ
32.768 kHz / 5 / 8 = 819 Hz
DL_LCD_CHARGE_PUMP_FREQUENCY_682HZ
32.768 kHz / 6 / 8 = 682 Hz
DL_LCD_CHARGE_PUMP_FREQUENCY_585HZ
32.768 kHz / 7 / 8 = 585 Hz
DL_LCD_CHARGE_PUMP_FREQUENCY_512HZ
32.768 kHz / 8 / 8 = 512 Hz
DL_LCD_CHARGE_PUMP_FREQUENCY_455HZ
32.768 kHz / 9 / 8 = 455 Hz
DL_LCD_CHARGE_PUMP_FREQUENCY_409HZ
32.768 kHz / 10 / 8 = 409 Hz
DL_LCD_CHARGE_PUMP_FREQUENCY_372HZ
32.768 kHz / 11 / 8 = 372 Hz
DL_LCD_CHARGE_PUMP_FREQUENCY_341HZ
32.768 kHz / 12 / 8 = 341 Hz
DL_LCD_CHARGE_PUMP_FREQUENCY_315HZ
32.768 kHz / 13 / 8 = 315 Hz
DL_LCD_CHARGE_PUMP_FREQUENCY_292HZ
32.768 kHz / 14 / 8 = 292 Hz
DL_LCD_CHARGE_PUMP_FREQUENCY_273HZ
32.768 kHz / 15 / 8 = 273 Hz
DL_LCD_CHARGE_PUMP_FREQUENCY_256HZ
32.768 kHz / 16 / 8 = 256 Hz
DL_LCD_VREF_INTERNAL
enum DL_LCD_VREF_INTERNAL
Enumerator
DL_LCD_VREF_INTERNAL_2_60V
2.60 V internal reference voltage select on R13
DL_LCD_VREF_INTERNAL_2_66V
2.66 V internal reference voltage select on R13
DL_LCD_VREF_INTERNAL_2_72V
2.72 V internal reference voltage select on R13
DL_LCD_VREF_INTERNAL_2_78V
2.78 V internal reference voltage select on R13
DL_LCD_VREF_INTERNAL_2_84V
2.84 V internal reference voltage select on R13
DL_LCD_VREF_INTERNAL_2_90V
2.90 V internal reference voltage select on R13
DL_LCD_VREF_INTERNAL_2_96V
2.96 V internal reference voltage select on R13
DL_LCD_VREF_INTERNAL_3_02V
3.02 V internal reference voltage select on R13
DL_LCD_VREF_INTERNAL_3_08V
3.08 V internal reference voltage select on R13
DL_LCD_VREF_INTERNAL_3_14V
3.14 V internal reference voltage select on R13
DL_LCD_VREF_INTERNAL_3_20V
3.20 V internal reference voltage select on R13
DL_LCD_VREF_INTERNAL_3_26V
3.26 V internal reference voltage select on R13
DL_LCD_VREF_INTERNAL_3_32V
3.32 V internal reference voltage select on R13
DL_LCD_VREF_INTERNAL_3_38V
3.38 V internal reference voltage select on R13
DL_LCD_VREF_INTERNAL_3_44V
3.44 V internal reference voltage select on R13
DL_LCD_VREF_INTERNAL_3_50V
3.50 V internal reference voltage select on R13
DL_LCD_R33_SOURCE
enum DL_LCD_R33_SOURCE
Enumerator
DL_LCD_R33_SOURCE_EXTERNAL
R33 is supplied from charge pump
DL_LCD_R33_SOURCE_INTERNAL
R33 is supplied from AVDD internally
DL_LCD_POWER_MODE
enum DL_LCD_POWER_MODE
Enumerator
DL_LCD_POWER_MODE_LOW
Low power resistor ladder generates bias voltage for the LCD
DL_LCD_POWER_MODE_HIGH
Higher power resistor ladder generates bias voltage for the LCD
DL_LCD_BIAS_VOLTAGE_SOURCE
enum DL_LCD_BIAS_VOLTAGE_SOURCE
Enumerator
DL_LCD_BIAS_VOLTAGE_SOURCE_R33
Bias voltage sourced from R33 pin
DL_LCD_BIAS_VOLTAGE_SOURCE_AVDD
Bias voltage sourced from internal supply voltage AVDD
DL_LCD_BIAS
enum DL_LCD_BIAS
Enumerator
DL_LCD_BIAS_ONE_THIRD
For 5-mux to 8-mux modes only. 1/3 bias
DL_LCD_BIAS_ONE_FOURTH
For 5-mux to 8-mux modes only. 1/4 bias
DL_LCD_REFERENCE_MODE
enum DL_LCD_REFERENCE_MODE
Enumerator
DL_LCD_REFERENCE_MODE_STATIC
R13 voltage in static mode
DL_LCD_REFERENCE_MODE_SWITCHED
R13 voltage in switched mode
DL_LCD_DISP
enum DL_LCD_DISP
Enumerator
DL_LCD_DISPLAY_REGISTERS_MEMORY
Display content of LCD memory registers LCDMx
DL_LCD_DISPLAY_REGISTERS_BLINKING_MEMORY
Display content of LCD blinking memory registers LCDBMx
DL_LCD_EVENT_LINE_MODE
enum DL_LCD_EVENT_LINE_MODE
Enumerator
DL_LCD_EVENT_LINE_MODE_DISABLED
The interrupt or event line is disabled.
DL_LCD_EVENT_LINE_MODE_SOFTWARE
The interrupt/event line is in sw mode. Software must clear the RIS.
DL_LCD_EVENT_LINE_MODE_HARDWARE
The interrupt/event line is in hw mode. The hardware clears RIS flag.
DL_LCD_IIDX
enum DL_LCD_IIDX
Enumerator
DL_LCD_IIDX_NO_INT
LCD interrupt index for no interrupt pending
DL_LCD_IIDX_FRAME_START
LCD interrupt index when start of new frame interrupt
DL_LCD_IIDX_BLINKING_SEGMENTS_OFF
LCD interrupt index when blinking segments off
DL_LCD_IIDX_BLINKING_SEGMENTS_ON
LCD interrupt index when blinking segments on
DL_LCD_MEMORY
enum DL_LCD_MEMORY
Enumerator
DL_LCD_MEMORY_0
Index to access LCD memory register 0
DL_LCD_MEMORY_1
Index to access LCD memory register 1
DL_LCD_MEMORY_2
Index to access LCD memory register 2
DL_LCD_MEMORY_3
Index to access LCD memory register 3
DL_LCD_MEMORY_4
Index to access LCD memory register 4
DL_LCD_MEMORY_5
Index to access LCD memory register 5
DL_LCD_MEMORY_6
Index to access LCD memory register 6
DL_LCD_MEMORY_7
Index to access LCD memory register 7
DL_LCD_MEMORY_8
Index to access LCD memory register 8
DL_LCD_MEMORY_9
Index to access LCD memory register 9
DL_LCD_MEMORY_10
Index to access LCD memory register 10
DL_LCD_MEMORY_11
Index to access LCD memory register 11
DL_LCD_MEMORY_12
Index to access LCD memory register 12
DL_LCD_MEMORY_13
Index to access LCD memory register 13
DL_LCD_MEMORY_14
Index to access LCD memory register 14
DL_LCD_MEMORY_15
Index to access LCD memory register 15
DL_LCD_MEMORY_16
Index to access LCD memory register 16
DL_LCD_MEMORY_17
Index to access LCD memory register 17
DL_LCD_MEMORY_18
Index to access LCD memory register 18
DL_LCD_MEMORY_19
Index to access LCD memory register 19
DL_LCD_MEMORY_20
Index to access LCD memory register 20
DL_LCD_MEMORY_21
Index to access LCD memory register 21
DL_LCD_MEMORY_22
Index to access LCD memory register 22
DL_LCD_MEMORY_23
Index to access LCD memory register 23
DL_LCD_MEMORY_24
Index to access LCD memory register 24
DL_LCD_MEMORY_25
Index to access LCD memory register 25
DL_LCD_MEMORY_26
Index to access LCD memory register 26
DL_LCD_MEMORY_27
Index to access LCD memory register 27
DL_LCD_MEMORY_28
Index to access LCD memory register 28
DL_LCD_MEMORY_29
Index to access LCD memory register 29
DL_LCD_MEMORY_30
Index to access LCD memory register 30
DL_LCD_MEMORY_31
Index to access LCD memory register 31
DL_LCD_MEMORY_32
Index to access LCD memory register 32
DL_LCD_MEMORY_33
Index to access LCD memory register 33
DL_LCD_MEMORY_34
Index to access LCD memory register 34
DL_LCD_MEMORY_35
Index to access LCD memory register 35
DL_LCD_MEMORY_36
Index to access LCD memory register 36
DL_LCD_MEMORY_37
Index to access LCD memory register 37
DL_LCD_MEMORY_38
Index to access LCD memory register 38
DL_LCD_MEMORY_39
Index to access LCD memory register 39
DL_LCD_MEMORY_40
Index to access LCD memory register 40
DL_LCD_MEMORY_41
Index to access LCD memory register 41
DL_LCD_MEMORY_42
Index to access LCD memory register 42
DL_LCD_MEMORY_43
Index to access LCD memory register 43
DL_LCD_MEMORY_44
Index to access LCD memory register 44
DL_LCD_MEMORY_45
Index to access LCD memory register 45
DL_LCD_MEMORY_46
Index to access LCD memory register 46
DL_LCD_MEMORY_47
Index to access LCD memory register 47
DL_LCD_MEMORY_48
Index to access LCD memory register 48
DL_LCD_MEMORY_49
Index to access LCD memory register 49
DL_LCD_MEMORY_50
Index to access LCD memory register 50
DL_LCD_MEMORY_51
Index to access LCD memory register 51
DL_LCD_MEMORY_52
Index to access LCD memory register 52
DL_LCD_MEMORY_53
Index to access LCD memory register 53
DL_LCD_MEMORY_54
Index to access LCD memory register 54
DL_LCD_MEMORY_55
Index to access LCD memory register 55
DL_LCD_MEMORY_56
Index to access LCD memory register 56
DL_LCD_MEMORY_57
Index to access LCD memory register 57
DL_LCD_MEMORY_58
Index to access LCD memory register 58
DL_LCD_MEMORY_59
Index to access LCD memory register 59
DL_LCD_MEMORY_60
Index to access LCD memory register 60
DL_LCD_MEMORY_61
Index to access LCD memory register 61
DL_LCD_MEMORY_62
Index to access LCD memory register 62
DL_LCD_MEMORY_63
Index to access LCD memory register 63
DL_LCD_BLINKING_MEMORY
enum DL_LCD_BLINKING_MEMORY
Enumerator
DL_LCD_BLINKING_MEMORY_0
Index to access LCD blink memory register 0
DL_LCD_BLINKING_MEMORY_1
Index to access LCD blink memory register 1
DL_LCD_BLINKING_MEMORY_2
Index to access LCD blink memory register 2
DL_LCD_BLINKING_MEMORY_3
Index to access LCD blink memory register 3
DL_LCD_BLINKING_MEMORY_4
Index to access LCD blink memory register 4
DL_LCD_BLINKING_MEMORY_5
Index to access LCD blink memory register 5
DL_LCD_BLINKING_MEMORY_6
Index to access LCD blink memory register 6
DL_LCD_BLINKING_MEMORY_7
Index to access LCD blink memory register 7
DL_LCD_BLINKING_MEMORY_8
Index to access LCD blink memory register 8
DL_LCD_BLINKING_MEMORY_9
Index to access LCD blink memory register 9
DL_LCD_BLINKING_MEMORY_10
Index to access LCD blink memory register 10
DL_LCD_BLINKING_MEMORY_11
Index to access LCD blink memory register 11
DL_LCD_BLINKING_MEMORY_12
Index to access LCD blink memory register 12
DL_LCD_BLINKING_MEMORY_13
Index to access LCD blink memory register 13
DL_LCD_BLINKING_MEMORY_14
Index to access LCD blink memory register 14
DL_LCD_BLINKING_MEMORY_15
Index to access LCD blink memory register 15
DL_LCD_BLINKING_MEMORY_16
Index to access LCD blink memory register 16
DL_LCD_BLINKING_MEMORY_17
Index to access LCD blink memory register 17
DL_LCD_BLINKING_MEMORY_18
Index to access LCD blink memory register 18
DL_LCD_BLINKING_MEMORY_19
Index to access LCD blink memory register 19
DL_LCD_BLINKING_MEMORY_20
Index to access LCD blink memory register 20
DL_LCD_BLINKING_MEMORY_21
Index to access LCD blink memory register 21
DL_LCD_BLINKING_MEMORY_22
Index to access LCD blink memory register 22
DL_LCD_BLINKING_MEMORY_23
Index to access LCD blink memory register 23
DL_LCD_BLINKING_MEMORY_24
Index to access LCD blink memory register 24
DL_LCD_BLINKING_MEMORY_25
Index to access LCD blink memory register 25
DL_LCD_BLINKING_MEMORY_26
Index to access LCD blink memory register 26
DL_LCD_BLINKING_MEMORY_27
Index to access LCD blink memory register 27
DL_LCD_BLINKING_MEMORY_28
Index to access LCD blink memory register 28
DL_LCD_BLINKING_MEMORY_29
Index to access LCD blink memory register 29
DL_LCD_BLINKING_MEMORY_30
Index to access LCD blink memory register 30
DL_LCD_BLINKING_MEMORY_31
Index to access LCD blink memory register 31
DL_LCD_COM
enum DL_LCD_COM
Enumerator
DL_LCD_COM_0
Index to access COM 0
DL_LCD_COM_1
Index to access COM 1
DL_LCD_COM_2
Index to access COM 2
DL_LCD_COM_3
Index to access COM 3
DL_LCD_COM_4
Index to access COM 4
DL_LCD_COM_5
Index to access COM 5
DL_LCD_COM_6
Index to access COM 6
DL_LCD_COM_7
Index to access COM 7
DL_LCD_VREFGEN_CYCLES
enum DL_LCD_VREFGEN_CYCLES
Enumerator
DL_LCD_VREFGEN_CYCLES_16
Turn on VREF generation circuitry for 16 clock cycles
DL_LCD_VREFGEN_CYCLES_32
Turn on VREF generation circuitry for 32 clock cycles
DL_LCD_VREFGEN_CYCLES_128
Turn on VREF generation circuitry for 128 clock cycles
DL_LCD_VREFGEN_CYCLES_256
Turn on VREF generation circuitry for 256 clock cycles
Function Documentation
DL_LCD_init()
void DL_LCD_init (LCD_Regs * lcd, DL_LCD_Config * config)
Initialize the LCD peripheral.
Initializes all the common configurable options for the LCD peripheral. Any other custom configuration can be done after calling this API. The LCD is not enabled in this API.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] config Configuration for LCD peripheral
DL_LCD_setPinAsLCDFunction()
void DL_LCD_setPinAsLCDFunction (LCD_Regs * lcd, uint32_t pin)
Enable a pin as LCD function.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] pin Pin to set as LCD function One of DL_LCD_SEGMENT_LINE
Note
This function will disable power to the LCD module. If needed, enable the module after by calling DL_LCD_enable
DL_LCD_setPinAsPortFunction()
void DL_LCD_setPinAsPortFunction (LCD_Regs * lcd, uint8_t pin)
Enable a pin as port function.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] pin Pin to set as port function. One of DL_LCD_SEGMENT_LINE
Note
This function will disable power to the LCD module. If needed, enable the module after by calling DL_LCD_enable
DL_LCD_setPinAsCommon()
void DL_LCD_setPinAsCommon (LCD_Regs * lcd, uint8_t pin, uint32_t com)
Enable an LCD function pin as COM.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] pin Pin to set as common. One of DL_LCD_SEGMENT_LINE
[in] com The selected COM number for the common line. One of DL_LCD_COM
DL_LCD_setPinAsSegment()
void DL_LCD_setPinAsSegment (LCD_Regs * lcd, uint8_t pin)
Enable an LCD function pin as Segment.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] pin Pin to set as segment line. One of DL_LCD_SEGMENT_LINE
DL_LCD_enablePower()
__STATIC_INLINE void DL_LCD_enablePower (LCD_Regs * lcd)
Enables power to the LCD module.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
DL_LCD_disablePower()
__STATIC_INLINE void DL_LCD_disablePower (LCD_Regs * lcd)
Disables power to the LCD module.
Parameters
lcd Pointer to the register overlay for the peripheral
DL_LCD_isPowerEnabled()
__STATIC_INLINE bool DL_LCD_isPowerEnabled (LCD_Regs * lcd)
Checks if power module on LCD is enabled.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
If power module on LCD is enabled
Return values
true if power module on LCD is enabled
false if power module on LCD is disabled
DL_LCD_reset()
__STATIC_INLINE void DL_LCD_reset (LCD_Regs * lcd)
Resets LCD peripheral.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
DL_LCD_isReset()
__STATIC_INLINE bool DL_LCD_isReset (LCD_Regs * lcd)
Checks if LCD peripheral was reset.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
If peripheral was reset
Return values
true if peripheral was reset since this bit was last cleared by RESETSTKYCLR in the RSTCTL register
false if peripheral was not reset since the last bit clear
DL_LCD_getEventLineMode()
__STATIC_INLINE DL_LCD_EVENT_LINE_MODE DL_LCD_getEventLineMode (LCD_Regs * lcd)
Get the event line mode.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
event line mode
Return values
One of DL_LCD_EVENT_LINE_MODE
DL_LCD_getPendingInterrupt()
__STATIC_INLINE DL_LCD_IIDX DL_LCD_getPendingInterrupt (LCD_Regs * lcd)
Gets the highest priority pending interrupt.
Accesses and reads the IIDX register to obtain the highest currently pending interrupt. A read clears the corresponding interrupt flag in RIS and MIS.
Parameters
[in] lcd pointer to the register overlay of the peripheral
Returns
The highest priority pending interrupt
Return values
One of DL_LCD_IIDX
DL_LCD_enableInterrupt()
__STATIC_INLINE void DL_LCD_enableInterrupt (LCD_Regs * lcd, uint32_t interruptMask)
Enable LCD interrupts.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to enable. Bitwise OR of DL_LCD_INTERRUPT.
DL_LCD_disableInterrupt()
__STATIC_INLINE void DL_LCD_disableInterrupt (LCD_Regs * lcd, uint32_t interruptMask)
Disable LCD interrupts.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to disable. Bitwise OR of DL_LCD_INTERRUPT.
DL_LCD_getEnabledInterrupts()
__STATIC_INLINE uint32_t DL_LCD_getEnabledInterrupts (LCD_Regs * lcd, uint32_t interruptMask)
Check which LCD interrupts are enabled.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_LCD_INTERRUPT.
Returns
Which of the requested LCD interrupts are enabled
Return values
Bitwise OR of DL_LCD_INTERRUPT values
DL_LCD_getRawInterruptStatus()
__STATIC_INLINE uint32_t DL_LCD_getRawInterruptStatus (LCD_Regs * lcd, uint32_t interruptMask)
Check interrupt flag of any LCD interrupt.
Checks if any of the LCD interrupts are pending. Interrupts do not have to be previously enabled.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_LCD_INTERRUPT.
Returns
Which of the requested LCD interrupts are pending
Return values
Bitwise OR of DL_LCD_INTERRUPT values
DL_LCD_getEnabledInterruptStatus()
__STATIC_INLINE uint32_t DL_LCD_getEnabledInterruptStatus (LCD_Regs * lcd, uint32_t interruptMask)
Check interrupt flag of enabled LCD interrupts.
Checks if any of the LCD interrupts that were previously enabled are pending.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_LCD_INTERRUPT.
Returns
Which of the requested LCD interrupts are pending
Return values
Bitwise OR of DL_LCD_INTERRUPT values
See also
DL_LCD_enableInterrupt
DL_LCD_setInterrupts()
__STATIC_INLINE void DL_LCD_setInterrupts (LCD_Regs * lcd, uint32_t interruptMask)
Set LCD interrupts.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to set. Bitwise OR of DL_LCD_INTERRUPT.
DL_LCD_clearInterruptStatus()
__STATIC_INLINE void DL_LCD_clearInterruptStatus (LCD_Regs * lcd, uint32_t interruptMask)
Clear pending LCD interrupts.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to clear. Bitwise OR of DL_LCD_INTERRUPT.
DL_LCD_enableExternalSync()
__STATIC_INLINE void DL_LCD_enableExternalSync (LCD_Regs * lcd)
Enable external synchronization.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
DL_LCD_disableExternalSync()
__STATIC_INLINE void DL_LCD_disableExternalSync (LCD_Regs * lcd)
Disable external synchronization.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
DL_LCD_isExternalSyncEnabled()
__STATIC_INLINE bool DL_LCD_isExternalSyncEnabled (LCD_Regs * lcd)
Checks if external synchronization is enabled.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
If external synchronization is enabled
Return values
true if external synchronization enabled
false if external synchronization is disabled
DL_LCD_setFreqDiv()
__STATIC_INLINE void DL_LCD_setFreqDiv (LCD_Regs * lcd, DL_LCD_FREQ_DIVIDE fDiv)
Set the LCD frequency divider.
fLCD = fSOURCE / ((LCDDIVx + 1) Value[LCDMXx])
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] fDiv The frequency divider to set. One of DL_LCD_FREQ_DIVIDE
Precondition
The LCD module must be off (LCDCTL0.LCDON == 0) before setting this configuration.
References DL_Common_updateReg().
DL_LCD_getFreqDiv()
__STATIC_INLINE DL_LCD_FREQ_DIVIDE DL_LCD_getFreqDiv (LCD_Regs * lcd)
Get the LCD frequency divider.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
The current frequency divider
Return values
One of DL_LCD_FREQ_DIVIDE
DL_LCD_setMuxRate()
__STATIC_INLINE void DL_LCD_setMuxRate (LCD_Regs * lcd, DL_LCD_MUX_RATE muxRate)
Set the LCD mux rate.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] muxRate The mux rate to set. One of DL_LCD_MUX_RATE
Precondition
The LCD module must be off (LCDCTL0.LCDON == 0) before setting this configuration. The LCD module can be disabled by calling DL_LCD_disableModule.
References DL_Common_updateReg().
DL_LCD_getMuxRate()
__STATIC_INLINE DL_LCD_MUX_RATE DL_LCD_getMuxRate (LCD_Regs * lcd)
Get the LCD mux rate.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
The mux rate
Return values
One of DL_LCD_MUX_RATE
DL_LCD_turnSegmentsOn()
__STATIC_INLINE void DL_LCD_turnSegmentsOn (LCD_Regs * lcd)
Turns LCD segments on.
Parameters
lcd Pointer to the register overlay for the peripheral
DL_LCD_turnSegmentsOff()
__STATIC_INLINE void DL_LCD_turnSegmentsOff (LCD_Regs * lcd)
Turns LCD segments off.
Can be used to flash LCD applications by turning off segment lines and leaving LCD timing generator and R33 enabled.
Parameters
lcd Pointer to the register overlay for the peripheral
DL_LCD_setWaveformPowerMode()
__STATIC_INLINE void DL_LCD_setWaveformPowerMode (LCD_Regs * lcd, DL_LCD_WAVEFORM_POWERMODE waveformPowerMode)
Set the waveform power mode.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] waveformPowerMode The power mode for LCD waveforms. One of DL_LCD_WAVEFORM_POWERMODE
Precondition
The LCD module must be in 1/3 bias mode (LCDBIASSEL == 0) before setting this configuration.
References DL_Common_updateReg().
DL_LCD_getWaveformPowerMode()
__STATIC_INLINE DL_LCD_WAVEFORM_POWERMODE DL_LCD_getWaveformPowerMode (LCD_Regs * lcd)
Get the waveform power mode.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
The waveform power mode
Return values
One of DL_LCD_WAVEFORM_POWERMODE
DL_LCD_enable()
__STATIC_INLINE void DL_LCD_enable (LCD_Regs * lcd)
Enables the LCD module.
Parameters
lcd Pointer to the register overlay for the peripheral
DL_LCD_disable()
__STATIC_INLINE void DL_LCD_disable (LCD_Regs * lcd)
Disables the LCD module.
Parameters
lcd Pointer to the register overlay for the peripheral
DL_LCD_setBlinkingControl()
__STATIC_INLINE void DL_LCD_setBlinkingControl (LCD_Regs * lcd, DL_LCD_BLINKING_DIVIDE blinkFreqDiv, DL_LCD_BLINKING_MODE blinkMode)
Set the blinking frequency divider and blinking mode.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] blinkFreqDiv The blinking frequency divider to set. One of DL_LCD_BLINKING_DIVIDE
[in] blinkMode The blinking mode to select. One of DL_LCD_BLINKING_MODE
References DL_Common_updateReg().
DL_LCD_getBlinkingFreqDiv()
__STATIC_INLINE DL_LCD_BLINKING_DIVIDE DL_LCD_getBlinkingFreqDiv (LCD_Regs * lcd)
Get the blinking frequency divider.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
The current blinking frequency divider
Return values
One of DL_LCD_BLINKING_DIVIDE
DL_LCD_getBlinkingMode()
__STATIC_INLINE DL_LCD_BLINKING_MODE DL_LCD_getBlinkingMode (LCD_Regs * lcd)
Get the blinking mode.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
The current blinking mode
Return values
One of DL_LCD_BLINKING_MODE
DL_LCD_clearAllBlinkingMemoryRegs()
__STATIC_INLINE void DL_LCD_clearAllBlinkingMemoryRegs (LCD_Regs * lcd)
Clear LCD blinking memory.
Clears all blinking memory registers LCDBMx. The bit is automatically reset when blinking memory cleared.
Parameters
lcd Pointer to the register overlay for the peripheral
References DL_Common_updateReg().
DL_LCD_clearAllMemoryRegs()
__STATIC_INLINE void DL_LCD_clearAllMemoryRegs (LCD_Regs * lcd)
Clear LCD memory.
Clears all memory registers LCDMx. The bit is automatically reset when LCD memory cleared.
Parameters
lcd Pointer to the register overlay for the peripheral
References DL_Common_updateReg().
DL_LCD_selectMemRegsForDisplay()
__STATIC_INLINE void DL_LCD_selectMemRegsForDisplay (LCD_Regs * lcd, DL_LCD_DISP dispSel)
Select LCD memory registers for display.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] dispSel The memory registers to select. One of DL_LCD_DISP
Precondition
LCDDISP can only be set by software when LCDBLKMODx is disabled. Bit cleared/cannot be changed by software when LCDBLKMODx == DL_LCD_BLINKING_MODE_INDIVIDUAL_SEGMENTS, DL_LCD_BLINKING_MODE_ALL_SEGMENTS or if a mux mode = 5 selected.
References DL_Common_updateReg().
DL_LCD_getSelectedMemRegsForDisplay()
__STATIC_INLINE DL_LCD_DISP DL_LCD_getSelectedMemRegsForDisplay (LCD_Regs * lcd)
Get the LCD memory registers selected for display.
When LCDBLKMODx = DL_LCD_BLINKING_MODE_TOGGLE, this bit reflects the currently displayed memory but cannot be changed by software. When returning to LCDBLKMODx is disabled, bit is cleared.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
LCD memory registers selected for display
Return values
One of DL_LCD_DISP
DL_LCD_enableVBOOST()
__STATIC_INLINE void DL_LCD_enableVBOOST (LCD_Regs * lcd)
Enables VBOOST on LCD module.
Parameters
lcd Pointer to the register overlay for the peripheral
DL_LCD_disableVBOOST()
__STATIC_INLINE void DL_LCD_disableVBOOST (LCD_Regs * lcd)
Disables VBOOST on LCD module.
Parameters
lcd Pointer to the register overlay for the peripheral
DL_LCD_setChargePumpFreq()
__STATIC_INLINE void DL_LCD_setChargePumpFreq (LCD_Regs * lcd, DL_LCD_CHARGE_PUMP_FREQUENCY chargePumpFreq)
Set charge pump frequency.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] chargePumpFreq The charge pump frequency to select. One of DL_LCD_CHARGE_PUMP_FREQUENCY
References DL_Common_updateReg().
DL_LCD_getChargePumpFreq()
__STATIC_INLINE DL_LCD_CHARGE_PUMP_FREQUENCY DL_LCD_getChargePumpFreq (LCD_Regs * lcd)
Get the charge pump frequency.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
The current charge pump frequency
Return values
One of DL_LCD_CHARGE_PUMP_FREQUENCY
DL_LCD_setVREFInternal()
__STATIC_INLINE void DL_LCD_setVREFInternal (LCD_Regs * lcd, DL_LCD_VREF_INTERNAL vrefInternal)
Set internal reference voltage.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] vrefInternal The internal reference voltage to select. One of DL_LCD_VREF_INTERNAL
References DL_Common_updateReg().
DL_LCD_getVREFInternal()
__STATIC_INLINE DL_LCD_VREF_INTERNAL DL_LCD_getVREFInternal (LCD_Regs * lcd)
Get the internal reference voltage.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
The current internal reference voltage
Return values
One of DL_LCD_VREF_INTERNAL
DL_LCD_enableChargePump()
__STATIC_INLINE void DL_LCD_enableChargePump (LCD_Regs * lcd)
Enables charge pump.
Parameters
lcd Pointer to the register overlay for the peripheral
Precondition
VLCD must be generated internally (VLCDEXT = 0) and VLCD > 0 or VLCDREFx > 0 in order to use this configuration.
DL_LCD_disableChargePump()
__STATIC_INLINE void DL_LCD_disableChargePump (LCD_Regs * lcd)
Disables charge pump.
Parameters
lcd Pointer to the register overlay for the peripheral
DL_LCD_enableVREFInternal()
__STATIC_INLINE void DL_LCD_enableVREFInternal (LCD_Regs * lcd)
Enables internal reference voltage.
Parameters
lcd Pointer to the register overlay for the peripheral
DL_LCD_disableVREFInternal()
__STATIC_INLINE void DL_LCD_disableVREFInternal (LCD_Regs * lcd)
Disables internal reference voltage.
Parameters
lcd Pointer to the register overlay for the peripheral
DL_LCD_setR33source()
__STATIC_INLINE void DL_LCD_setR33source (LCD_Regs * lcd, DL_LCD_R33_SOURCE r33Source)
Set source for R33.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] r33Source The internal reference voltage to select. One of DL_LCD_R33_SOURCE
References DL_Common_updateReg().
DL_LCD_getR33Source()
__STATIC_INLINE DL_LCD_R33_SOURCE DL_LCD_getR33Source (LCD_Regs * lcd)
Get the source for R33.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
The current source for R33
Return values
One of DL_LCD_R33_SOURCE
DL_LCD_setInternalBiasPowerMode()
__STATIC_INLINE void DL_LCD_setInternalBiasPowerMode (LCD_Regs * lcd, DL_LCD_POWER_MODE powerMode)
Select internal bias power mode.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] powerMode The power mode to use for generating bias voltage for LCD. One of DL_LCD_POWER_MODE
Precondition
The user must first enable the internal bias voltage resistor divider by calling DL_LCD_enableInternalBias
References DL_Common_updateReg().
DL_LCD_getPowerMode()
__STATIC_INLINE DL_LCD_POWER_MODE DL_LCD_getPowerMode (LCD_Regs * lcd)
Get power mode.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
The power mode
Return values
One of DL_LCD_POWER_MODE
DL_LCD_setBiasVoltageSource()
__STATIC_INLINE void DL_LCD_setBiasVoltageSource (LCD_Regs * lcd, DL_LCD_BIAS_VOLTAGE_SOURCE biasVoltageSource)
Set bias voltage source.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] biasVoltageSource The bias voltage source. One of DL_LCD_BIAS_VOLTAGE_SOURCE
Precondition
The user must first enable the internal bias voltage resistor divider by calling DL_LCD_enableInternalBias
References DL_Common_updateReg().
DL_LCD_getBiasVoltageSource()
__STATIC_INLINE DL_LCD_BIAS_VOLTAGE_SOURCE DL_LCD_getBiasVoltageSource (LCD_Regs * lcd)
Get bias voltage source.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
The bias voltage source
Return values
One of DL_LCD_BIAS_VOLTAGE_SOURCE
DL_LCD_enableInternalBias()
__STATIC_INLINE void DL_LCD_enableInternalBias (LCD_Regs * lcd)
Enables internal bias voltage resistor divider.
Parameters
lcd Pointer to the register overlay for the peripheral
DL_LCD_disableInternalBias()
__STATIC_INLINE void DL_LCD_disableInternalBias (LCD_Regs * lcd)
Disables internal bias voltage resistor divider.
Parameters
lcd Pointer to the register overlay for the peripheral
DL_LCD_setBias()
__STATIC_INLINE void DL_LCD_setBias (LCD_Regs * lcd, DL_LCD_BIAS biasSel)
Select LCD bias.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] biasSel The bias. One of DL_LCD_BIAS
Note
This bit (LCDBIASSEL) is ignored in static mode and for 2-mux, 3-mux, and 4-mux LCD modes
References DL_Common_updateReg().
DL_LCD_getBias()
__STATIC_INLINE DL_LCD_BIAS DL_LCD_getBias (LCD_Regs * lcd)
Get bias for LCD.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
The bias for the LCD
Return values
One of DL_LCD_BIAS
DL_LCD_setRefMode()
__STATIC_INLINE void DL_LCD_setRefMode (LCD_Regs * lcd, DL_LCD_REFERENCE_MODE refMode)
Set reference mode for R13 voltage.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] refMode Ref mode. One of DL_LCD_REFERENCE_MODE
References DL_Common_updateReg().
DL_LCD_getRefMode()
__STATIC_INLINE DL_LCD_REFERENCE_MODE DL_LCD_getRefMode (LCD_Regs * lcd)
Get reference mode for R13 voltage.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
Voltage reference mode
Return values
One of DL_LCD_REFERENCE_MODE
DL_LCD_writeMemory()
__STATIC_INLINE void DL_LCD_writeMemory (LCD_Regs * lcd, DL_LCD_MEMORY memIndex, uint32_t mask)
Write to bits in LCD memory index register.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] memIndex Index of LCDMx register to write to. One of DL_LCD_MEMORY.
[in] mask Registers to set in LCDMx register. Bitwise OR of DL_LCD_MEMORY_BIT.
DL_LCD_setMemory()
__STATIC_INLINE void DL_LCD_setMemory (LCD_Regs * lcd, DL_LCD_MEMORY memIndex, uint32_t mask)
Set bits in LCD memory index register.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] memIndex Index of LCDMx register to write to. One of DL_LCD_MEMORY.
[in] mask Registers to set in LCDMx register. Bitwise OR of DL_LCD_MEMORY_BIT.
DL_LCD_toggleMemory()
__STATIC_INLINE void DL_LCD_toggleMemory (LCD_Regs * lcd, DL_LCD_MEMORY memIndex, uint32_t mask)
Toggle bits in LCD memory index register.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] memIndex Index of LCDMx register to write to. One of DL_LCD_MEMORY.
[in] mask Registers to set in LCDMx register. Bitwise OR of DL_LCD_MEMORY_BIT.
DL_LCD_clearMemory()
__STATIC_INLINE void DL_LCD_clearMemory (LCD_Regs * lcd, DL_LCD_MEMORY memIndex, uint32_t mask)
Clear bits in LCD memory index register.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] memIndex Index of LCDMx register to write to. One of DL_LCD_MEMORY.
[in] mask Registers to set in LCDMx register. Bitwise OR of DL_LCD_MEMORY_BIT.
DL_LCD_getMemory()
__STATIC_INLINE uint32_t DL_LCD_getMemory (LCD_Regs * lcd, DL_LCD_MEMORY memIndex)
Get bits in LCD memory index register.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] memIndex Index of LCDMx register to read from.
Return values
32 bit value of register
See also
DL_LCD_MEMORY_BIT
DL_LCD_writeBlinkingMemory()
__STATIC_INLINE void DL_LCD_writeBlinkingMemory (LCD_Regs * lcd, DL_LCD_BLINKING_MEMORY memIndex, uint32_t mask)
Write to bits in LCD blinking memory index register.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] memIndex Index of LCDMx register to write to. One of DL_LCD_BLINKING_MEMORY.
[in] mask Registers to set in LCDBMx register. Bitwise OR of DL_LCD_BLINK_MEMORY_BIT.
DL_LCD_setBlinkingMemory()
__STATIC_INLINE void DL_LCD_setBlinkingMemory (LCD_Regs * lcd, DL_LCD_BLINKING_MEMORY memIndex, uint32_t mask)
Set bits in LCD blinking memory index register.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] memIndex Index of LCDMx register to write to. One of DL_LCD_BLINKING_MEMORY.
[in] mask Registers to set in LCDBMx register. Bitwise OR of DL_LCD_BLINK_MEMORY_BIT.
DL_LCD_toggleBlinkingMemory()
__STATIC_INLINE void DL_LCD_toggleBlinkingMemory (LCD_Regs * lcd, DL_LCD_BLINKING_MEMORY memIndex, uint32_t mask)
Toggle bits in LCD blinking memory index register.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] memIndex Index of LCDMx register to write to. One of DL_LCD_BLINKING_MEMORY.
[in] mask Registers to set in LCDBMx register. Bitwise OR of DL_LCD_BLINK_MEMORY_BIT.
DL_LCD_clearBlinkingMemory()
__STATIC_INLINE void DL_LCD_clearBlinkingMemory (LCD_Regs * lcd, DL_LCD_BLINKING_MEMORY memIndex, uint32_t mask)
Clear bits in LCD blinking memory index register.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] memIndex Index of LCDMx register to write to. One of DL_LCD_BLINKING_MEMORY.
[in] mask Registers to set in LCDBMx register. Bitwise OR of DL_LCD_BLINK_MEMORY_BIT.
DL_LCD_getBlinkingMemory()
__STATIC_INLINE uint32_t DL_LCD_getBlinkingMemory (LCD_Regs * lcd, DL_LCD_BLINKING_MEMORY memIndex)
Get bits in LCD blinking memory index register.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] memIndex Index of LCDMx register to read from.
Return values
32 bit value of register
See also
DL_LCD_BLINK_MEMORY_BIT
DL_LCD_setVrefOnTimeCycles()
__STATIC_INLINE void DL_LCD_setVrefOnTimeCycles (LCD_Regs * lcd, DL_LCD_VREFGEN_CYCLES cycles)
Set number of cycles to enable voltage generation circuitry.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
[in] cycles The number of cycles to enable voltage generation circuitry. One of DL_LCD_VREFGEN_CYCLES.
References DL_Common_updateReg().
DL_LCD_getVrefOnTimeCycles()
__STATIC_INLINE DL_LCD_VREFGEN_CYCLES DL_LCD_getVrefOnTimeCycles (LCD_Regs * lcd)
Get the number of cycles set to enable voltage generation circuitry.
Parameters
[in] lcd Pointer to the register overlay for the peripheral
Returns
The number of cycles
Return values
One of DL_LCD_VREFGEN_CYCLES
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale