MSPM0L122X_L222X Driver Library: RTC_Common
RTC_Common
Modules
DL_RTC_COMMON_INTERRUPT
DL_RTC_COMMON_EVENT
DL_RTC_COMMON_TIME_STAMP_EVENT_CAUSE
DL_RTC_COMMON_TIME_STAMP_EVENT_SOURCE
Data Structures
struct DL_RTC_Common_CalendarAlarm
Alarm struct to use in DL_RTC_Common_setCalendarAlarm.
struct DL_RTC_Common_Calendar
Calendar struct to use in DL_RTC_Common_initCalendar()
Enumerations
enum DL_RTC_COMMON_STATUS {
DL_RTC_COMMON_STATUS_READY = RTC_STA_RTCRDY_READY,
DL_RTC_COMMON_STATUS_NOT_READY = RTC_STA_RTCRDY_NOT_READY
}
enum DL_RTC_COMMON_COMPENSATION_STATUS {
DL_RTC_COMMON_COMPENSATION_STATUS_READY = RTC_STA_RTCTCRDY_READY,
DL_RTC_COMMON_COMPENSATION_STATUS_NOT_READY = RTC_STA_RTCTCRDY_NOT_READY
}
enum DL_RTC_COMMON_COMPENSATION_WRITE_RESULT {
DL_RTC_COMMON_COMPENSATION_WRITE_RESULT_OK = RTC_STA_RTCTCOK_OK,
DL_RTC_COMMON_COMPENSATION_WRITE_RESULT_NOT_OK = RTC_STA_RTCTCOK_NOT_OK
}
enum DL_RTC_COMMON_OFFSET_CALIBRATION_SIGN {
DL_RTC_COMMON_OFFSET_CALIBRATION_SIGN_DOWN = RTC_CAL_RTCOCALS_DOWN,
DL_RTC_COMMON_OFFSET_CALIBRATION_SIGN_UP = RTC_CAL_RTCOCALS_UP
}
enum DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY {
DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY_32_KHZ = LFSS_CAL_RTCCALFX_F32KHZ,
DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY_512 = RTC_CAL_RTCCALFX_F512HZ,
DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY_256 = RTC_CAL_RTCCALFX_F256HZ,
DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY_1 = RTC_CAL_RTCCALFX_F1HZ
}
enum DL_RTC_COMMON_TEMP_CALIBRATION {
DL_RTC_COMMON_TEMP_CALIBRATION_DOWN1PPM = RTC_TCMP_RTCTCMPS_DOWN,
DL_RTC_COMMON_TEMP_CALIBRATION_UP1PPM = RTC_TCMP_RTCTCMPS_UP
}
enum DL_RTC_COMMON_FORMAT {
DL_RTC_COMMON_FORMAT_BINARY = RTC_CTL_RTCBCD_BINARY,
DL_RTC_COMMON_FORMAT_BCD = RTC_CTL_RTCBCD_BCD
}
enum DL_RTC_COMMON_INTERVAL_ALARM {
DL_RTC_COMMON_INTERVAL_ALARM_MINUTECHANGE = RTC_CTL_RTCTEVTX_MINUTE,
DL_RTC_COMMON_INTERVAL_ALARM_HOURCHANGE = RTC_CTL_RTCTEVTX_HOUR,
DL_RTC_COMMON_INTERVAL_ALARM_NOON = RTC_CTL_RTCTEVTX_NOON,
DL_RTC_COMMON_INTERVAL_ALARM_MIDNIGHT = RTC_CTL_RTCTEVTX_MIDNIGHT
}
enum DL_RTC_COMMON_PRESCALER0_DIVIDE {
DL_RTC_COMMON_PRESCALER0_DIVIDE_8 = RTC_PSCTL_RT0IP_DIV8,
DL_RTC_COMMON_PRESCALER0_DIVIDE_16 = RTC_PSCTL_RT0IP_DIV16,
DL_RTC_COMMON_PRESCALER0_DIVIDE_32 = RTC_PSCTL_RT0IP_DIV32,
DL_RTC_COMMON_PRESCALER0_DIVIDE_64 = RTC_PSCTL_RT0IP_DIV64,
DL_RTC_COMMON_PRESCALER0_DIVIDE_128 = RTC_PSCTL_RT0IP_DIV128,
DL_RTC_COMMON_PRESCALER0_DIVIDE_256 = RTC_PSCTL_RT0IP_DIV256
}
enum DL_RTC_COMMON_PRESCALER1_DIVIDE {
DL_RTC_COMMON_PRESCALER1_DIVIDE_2 = RTC_PSCTL_RT1IP_DIV2,
DL_RTC_COMMON_PRESCALER1_DIVIDE_4 = RTC_PSCTL_RT1IP_DIV4,
DL_RTC_COMMON_PRESCALER1_DIVIDE_8 = RTC_PSCTL_RT1IP_DIV8,
DL_RTC_COMMON_PRESCALER1_DIVIDE_16 = RTC_PSCTL_RT1IP_DIV16,
DL_RTC_COMMON_PRESCALER1_DIVIDE_32 = RTC_PSCTL_RT1IP_DIV32,
DL_RTC_COMMON_PRESCALER1_DIVIDE_64 = RTC_PSCTL_RT1IP_DIV64,
DL_RTC_COMMON_PRESCALER1_DIVIDE_128 = RTC_PSCTL_RT1IP_DIV128,
DL_RTC_COMMON_PRESCALER1_DIVIDE_256 = RTC_PSCTL_RT1IP_DIV256
}
enum DL_RTC_COMMON_PRESCALER2_DIVIDE {
DL_RTC_COMMON_PRESCALER2_4_SEC = RTC_EXTPSCTL_RT2PS_INT4S,
DL_RTC_COMMON_PRESCALER2_8_SEC = RTC_EXTPSCTL_RT2PS_INT8S,
DL_RTC_COMMON_PRESCALER2_16_SEC = RTC_EXTPSCTL_RT2PS_INT16S
}
enum DL_RTC_COMMON_IIDX {
DL_RTC_COMMON_IIDX_ALARM1 = RTC_CPU_INT_IIDX_STAT_RTCA1,
DL_RTC_COMMON_IIDX_ALARM2 = RTC_CPU_INT_IIDX_STAT_RTCA2,
DL_RTC_COMMON_IIDX_PRESCALER0 = RTC_CPU_INT_IIDX_STAT_RT0PS,
DL_RTC_COMMON_IIDX_PRESCALER1 = RTC_CPU_INT_IIDX_STAT_RT1PS,
DL_RTC_COMMON_IIDX_PRESCALER2 = RTC_CPU_INT_IIDX_STAT_RT2PS,
DL_RTC_COMMON_IIDX_INTERVAL_TIMER = RTC_CPU_INT_IIDX_STAT_RTCTEV,
DL_RTC_COMMON_IIDX_READY = RTC_CPU_INT_IIDX_STAT_RTCRDY,
DL_RTC_COMMON_IIDX_TSEVT = RTC_CPU_INT_IIDX_STAT_TSEVT,
DL_RTC_COMMON_IIDX_TAMPER_IO_0 = RTC_CPU_INT_IIDX_STAT_TIO0,
DL_RTC_COMMON_IIDX_TAMPER_IO_1 = RTC_CPU_INT_IIDX_STAT_TIO1,
DL_RTC_COMMON_IIDX_TAMPER_IO_2 = RTC_CPU_INT_IIDX_STAT_TIO2,
DL_RTC_COMMON_IIDX_TAMPER_IO_3 = RTC_CPU_INT_IIDX_STAT_TIO3,
DL_RTC_COMMON_IIDX_TAMPER_IO_4 = RTC_CPU_INT_IIDX_STAT_TIO4,
DL_RTC_COMMON_IIDX_TAMPER_IO_5 = RTC_CPU_INT_IIDX_STAT_TIO5,
DL_RTC_COMMON_IIDX_TAMPER_IO_6 = RTC_CPU_INT_IIDX_STAT_TIO6,
DL_RTC_COMMON_IIDX_TAMPER_IO_7 = RTC_CPU_INT_IIDX_STAT_TIO7,
DL_RTC_COMMON_IIDX_TAMPER_IO_8 = RTC_CPU_INT_IIDX_STAT_TIO8,
DL_RTC_COMMON_IIDX_TAMPER_IO_9 = RTC_CPU_INT_IIDX_STAT_TIO9,
DL_RTC_COMMON_IIDX_TAMPER_IO_10 = RTC_CPU_INT_IIDX_STAT_TIO10,
DL_RTC_COMMON_IIDX_TAMPER_IO_11 = RTC_CPU_INT_IIDX_STAT_TIO11,
DL_RTC_COMMON_IIDX_TAMPER_IO_12 = RTC_CPU_INT_IIDX_STAT_TIO12,
DL_RTC_COMMON_IIDX_TAMPER_IO_13 = RTC_CPU_INT_IIDX_STAT_TIO13,
DL_RTC_COMMON_IIDX_TAMPER_IO_14 = RTC_CPU_INT_IIDX_STAT_TIO14,
DL_RTC_COMMON_IIDX_TAMPER_IO_15 = RTC_CPU_INT_IIDX_STAT_TIO15
}
enum DL_RTC_COMMON_TIME_STAMP_EVENT_CAPTURE {
DL_RTC_COMMON_TIME_STAMP_EVENT_CAPTURE_FIRST = RTC_TSCTL_TSCAPTURE_FIRST,
DL_RTC_COMMON_TIME_STAMP_EVENT_CAPTURE_LAST = RTC_TSCTL_TSCAPTURE_LAST
}
Functions
__STATIC_INLINE bool DL_RTC_Common_isClockSourceLFCLK (const RTC_Regs *rtc_common)
Returns if LFCLK is selected as clock source.
__STATIC_INLINE void DL_RTC_Common_enableClockControl (RTC_Regs *rtc_common)
Enables the supply of the 32kHz clock to the RTC Common. It will not power up the 32kHz crystal oscillator. This needs to be done in the Clock System Module.
__STATIC_INLINE void DL_RTC_Common_disableClockControl (RTC_Regs *rtc_common)
Disables the supply of the 32kHz clock to the RTC Common.
__STATIC_INLINE void DL_RTC_Common_enablePower (RTC_Regs *rtc_common)
Enables the Peripheral Write Enable (PWREN) register for the RTC.
__STATIC_INLINE void DL_RTC_Common_disablePower (RTC_Regs *rtc_common)
Disables the Peripheral Write Enable (PWREN) register for the RTC.
__STATIC_INLINE bool DL_RTC_Common_isPowerEnabled (const RTC_Regs *rtc_common)
Returns if the Peripheral Write Enable (PWREN) register for the RTC is enabled.
__STATIC_INLINE void DL_RTC_Common_reset (RTC_Regs *rtc_common)
Resets all registers in the RTC Common module.
__STATIC_INLINE bool DL_RTC_Common_isReset (const RTC_Regs *rtc_common)
Returns if the RTC Common module was reset.
__STATIC_INLINE void DL_RTC_Common_enableDebugInterrupts (RTC_Regs *rtc_common)
Enables interrupts when the CPU is in debug mode. Interrupt requests are signaled to the interrupt controller.
__STATIC_INLINE void DL_RTC_Common_disableDebugInterrupts (RTC_Regs *rtc_common)
Disables interrupts when the CPU is in debug mode. Interrupts of the RTC Common module will not be captured. There will be no updates to the RTCRIS, RTCMISC and RTCIIDX registers.
__STATIC_INLINE void DL_RTC_Common_enableDebugMode (RTC_Regs *rtc_common)
Enables the RTC Common modules debug mode.
__STATIC_INLINE void DL_RTC_Common_disableDebugMode (RTC_Regs *rtc_common)
Disables the RTC Common modules debug mode.
__STATIC_INLINE void DL_RTC_Common_setClockFormat (RTC_Regs *rtc_common, DL_RTC_COMMON_FORMAT formatSelect)
Set the format of the real-time clock.
__STATIC_INLINE DL_RTC_COMMON_FORMAT DL_RTC_Common_getClockFormat (const RTC_Regs *rtc_common)
Get the format currently being used for counting the real-time clock.
__STATIC_INLINE void DL_RTC_Common_setIntervalAlarm (RTC_Regs *rtc_common, DL_RTC_COMMON_INTERVAL_ALARM alarmEvent)
Sets the interval alarm event condition.
__STATIC_INLINE DL_RTC_COMMON_INTERVAL_ALARM DL_RTC_Common_getIntervalAlarm (const RTC_Regs *rtc_common)
Gets the interval alarm event condition.
__STATIC_INLINE bool DL_RTC_Common_isSafeToRead (const RTC_Regs *rtc_common)
Checks if RTC Common is safe for reading.
__STATIC_INLINE bool DL_RTC_Common_isReadyToCalibrate (const RTC_Regs *rtc_common)
Checks if RTC Common is ready to get new calibration values.
__STATIC_INLINE bool DL_RTC_Common_isCalibrationWriteResultOK (const RTC_Regs *rtc_common)
Checks if RTC Common new calibration values were written OK.
__STATIC_INLINE void DL_RTC_Common_setOffsetCalibrationFrequency (RTC_Regs *rtc_common, DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY offsetFrequency)
Sets output frequency for offset calibration.
__STATIC_INLINE void DL_RTC_Common_setOffsetCalibrationAdjValue (RTC_Regs *rtc_common, DL_RTC_COMMON_OFFSET_CALIBRATION_SIGN offsetSign, uint8_t offsetValue)
Sets the offset error calibration adjustment value.
__STATIC_INLINE void DL_RTC_Common_setOffsetCalibration (RTC_Regs *rtc_common, DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY offsetFrequency, DL_RTC_COMMON_OFFSET_CALIBRATION_SIGN offsetSign, uint8_t offsetValue)
Sets the offset error calibration.
__STATIC_INLINE DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY DL_RTC_Common_getOffsetCalibrationFrequency (const RTC_Regs *rtc_common)
Gets the offset calibration frequency.
__STATIC_INLINE DL_RTC_COMMON_OFFSET_CALIBRATION_SIGN DL_RTC_Common_getOffsetCalibrationSign (const RTC_Regs *rtc_common)
Gets the offset calibration sign.
__STATIC_INLINE void DL_RTC_Common_setTemperatureCompensation (RTC_Regs *rtc_common, DL_RTC_COMMON_TEMP_CALIBRATION offsetDirection, uint32_t offsetValue)
Set the specified RTC Common temperature compensation.
__STATIC_INLINE uint32_t DL_RTC_Common_getTemperatureCompensation (const RTC_Regs *rtc_common)
Get the RTC Common temperature compensation.
__STATIC_INLINE void DL_RTC_Common_setCalendarSecondsBCD (RTC_Regs *rtc_common, uint8_t seconds)
Set the seconds in BCD in the RTC Common calendar.
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarSecondsBCD (const RTC_Regs *rtc_common)
Get the seconds in in BCD the RTC Common calendar.
__STATIC_INLINE void DL_RTC_Common_setCalendarMinutesBCD (RTC_Regs *rtc_common, uint8_t minutes)
Set the minutes in in BCD the RTC Common calendar.
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarMinutesBCD (const RTC_Regs *rtc_common)
Get the minutes in in BCD the RTC Common calendar.
__STATIC_INLINE void DL_RTC_Common_setCalendarHoursBCD (RTC_Regs *rtc_common, uint8_t hours)
Set the hours in in BCD the RTC Common calendar.
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarHoursBCD (const RTC_Regs *rtc_common)
Get the hours in in BCD the RTC Common calendar.
__STATIC_INLINE void DL_RTC_Common_setCalendarDayOfWeekBCD (RTC_Regs *rtc_common, uint8_t day)
Set the day of the week in BCD in the RTC Common calendar.
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarDayOfWeekBCD (const RTC_Regs *rtc_common)
Get the day of the week in BCD in the RTC Common calendar.
__STATIC_INLINE void DL_RTC_Common_setCalendarDayOfMonthBCD (RTC_Regs *rtc_common, uint8_t day)
Set the day of the month in BCD in the RTC Common calendar.
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarDayOfMonthBCD (const RTC_Regs *rtc_common)
Get the day of the month in BCD in the RTC Common calendar.
__STATIC_INLINE void DL_RTC_Common_setCalendarMonthBCD (RTC_Regs *rtc_common, uint8_t month)
Set the month in in BCD the RTC Common calendar.
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarMonthBCD (const RTC_Regs *rtc_common)
Get the month of the year in BCD in the RTC Common calendar.
__STATIC_INLINE void DL_RTC_Common_setCalendarYearBCD (RTC_Regs *rtc_common, uint16_t year)
Set the year in in BCD the RTC Common calendar.
__STATIC_INLINE uint16_t DL_RTC_Common_getCalendarYearBCD (const RTC_Regs *rtc_common)
Get the year in in BCD the RTC Common calendar.
__STATIC_INLINE void DL_RTC_Common_enableAlarm1MinutesBCD (RTC_Regs *rtc_common)
Enable minutes in BCD for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_disableAlarm1MinutesBCD (RTC_Regs *rtc_common)
Disable minutes in BCD for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_setAlarm1MinutesBCD (RTC_Regs *rtc_common, uint8_t minutes)
Set the minutes in BCD for RTC Common Calendar Alarm 1.
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm1MinutesBCD (const RTC_Regs *rtc_common)
Get the minutes in BCD for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_enableAlarm1HoursBCD (RTC_Regs *rtc_common)
Enable hours in BCD for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_disableAlarm1HoursBCD (RTC_Regs *rtc_common)
Disable hours in BCD for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_setAlarm1HoursBCD (RTC_Regs *rtc_common, uint8_t hours)
Set the hours in BCD for RTC Common Calendar Alarm 1.
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm1HoursBCD (const RTC_Regs *rtc_common)
Get the hours in BCD for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_enableAlarm1DayOfWeekBCD (RTC_Regs *rtc_common)
Enable day of the week in BCD for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_disableAlarm1DayOfWeekBCD (RTC_Regs *rtc_common)
Disable day of the week in BCD for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_setAlarm1DayOfWeekBCD (RTC_Regs *rtc_common, uint8_t day)
Set the day of the week in BCD for RTC Common Calendar Alarm 1.
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm1DayOfWeekBCD (const RTC_Regs *rtc_common)
Get the day of the week in BCD for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_enableAlarm1DayOfMonthBCD (RTC_Regs *rtc_common)
Enable day of the month in BCD for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_disableAlarm1DayOfMonthBCD (RTC_Regs *rtc_common)
Disable day of the month in BCD for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_setAlarm1DayOfMonthBCD (RTC_Regs *rtc_common, uint8_t day)
Set the day of the month in BCD for RTC Common Calendar Alarm 1.
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm1DayOfMonthBCD (const RTC_Regs *rtc_common)
Get the day of the month in BCD for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_enableAlarm2MinutesBCD (RTC_Regs *rtc_common)
Enable minutes in BCD for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_disableAlarm2MinutesBCD (RTC_Regs *rtc_common)
Disable minutes in BCD for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_setAlarm2MinutesBCD (RTC_Regs *rtc_common, uint8_t minutes)
Set the minutes in BCD for RTC Common Calendar Alarm 2.
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm2MinutesBCD (const RTC_Regs *rtc_common)
Get the minutes in BCD for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_enableAlarm2HoursBCD (RTC_Regs *rtc_common)
Enable hours in BCD for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_disableAlarm2HoursBCD (RTC_Regs *rtc_common)
Disable hours in BCD for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_setAlarm2HoursBCD (RTC_Regs *rtc_common, uint8_t hours)
Set the hours in BCD for RTC Common Calendar Alarm 2.
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm2HoursBCD (const RTC_Regs *rtc_common)
Get the hours in BCD for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_enableAlarm2DayOfWeekBCD (RTC_Regs *rtc_common)
Enable day of the week in BCD for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_disableAlarm2DayOfWeekBCD (RTC_Regs *rtc_common)
Disable day of the week in BCD for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_setAlarm2DayOfWeekBCD (RTC_Regs *rtc_common, uint8_t day)
Set the day of the week in BCD for RTC Common Calendar Alarm 2.
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm2DayOfWeekBCD (const RTC_Regs *rtc_common)
Get the day of the week in BCD for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_enableAlarm2DayOfMonthBCD (RTC_Regs *rtc_common)
Enable day of the month in BCD for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_disableAlarm2DayOfMonthBCD (RTC_Regs *rtc_common)
Disable day of the month in BCD for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_setAlarm2DayOfMonthBCD (RTC_Regs *rtc_common, uint8_t day)
Set the day of the month in BCD for RTC Common Calendar Alarm 2.
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm2DayOfMonthBCD (const RTC_Regs *rtc_common)
Get the day of the month in BCD for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_setCalendarSecondsBinary (RTC_Regs *rtc_common, uint8_t seconds)
Set the seconds in binary the RTC Common calendar.
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarSecondsBinary (const RTC_Regs *rtc_common)
Get the seconds in binary in the RTC Common calendar.
__STATIC_INLINE void DL_RTC_Common_setCalendarMinutesBinary (RTC_Regs *rtc_common, uint8_t minutes)
Set the minutes in binary in the RTC Common calendar.
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarMinutesBinary (const RTC_Regs *rtc_common)
Get the minutes in binary in the RTC Common calendar.
__STATIC_INLINE void DL_RTC_Common_setCalendarHoursBinary (RTC_Regs *rtc_common, uint8_t hours)
Set the hours in binary in the RTC Common calendar.
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarHoursBinary (const RTC_Regs *rtc_common)
Get the hours in binary in the RTC Common calendar.
__STATIC_INLINE void DL_RTC_Common_setCalendarDayOfWeekBinary (RTC_Regs *rtc_common, uint8_t day)
Set the day of the week in binary in the RTC Common calendar.
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarDayOfWeekBinary (const RTC_Regs *rtc_common)
Get the day of the week in binary in the RTC Common calendar.
__STATIC_INLINE void DL_RTC_Common_setCalendarDayOfMonthBinary (RTC_Regs *rtc_common, uint8_t day)
Set the day of the month in binary in the RTC Common calendar.
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarDayOfMonthBinary (const RTC_Regs *rtc_common)
Get the day of the month in binary in the RTC Common calendar.
__STATIC_INLINE void DL_RTC_Common_setCalendarMonthBinary (RTC_Regs *rtc_common, uint8_t month)
Set the month in binary in the RTC Common calendar.
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarMonthBinary (const RTC_Regs *rtc_common)
Get the month of the year in binary in the RTC Common calendar.
__STATIC_INLINE void DL_RTC_Common_setCalendarYearBinary (RTC_Regs *rtc_common, uint16_t year)
Set the year in binary in the RTC Common calendar.
__STATIC_INLINE uint16_t DL_RTC_Common_getCalendarYearBinary (const RTC_Regs *rtc_common)
Get the year in binary in the RTC Common calendar.
__STATIC_INLINE void DL_RTC_Common_enableAlarm1MinutesBinary (RTC_Regs *rtc_common)
Enable minutes in binary in binary for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_disableAlarm1MinutesBinary (RTC_Regs *rtc_common)
Disable minutes in binary for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_setAlarm1MinutesBinary (RTC_Regs *rtc_common, uint8_t minutes)
Set the minutes in binary for RTC Common Calendar Alarm 1.
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm1MinutesBinary (const RTC_Regs *rtc_common)
Get the minutes in binary for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_enableAlarm1HoursBinary (RTC_Regs *rtc_common)
Enable hours in binary for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_disableAlarm1HoursBinary (RTC_Regs *rtc_common)
Disable hours in binary for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_setAlarm1HoursBinary (RTC_Regs *rtc_common, uint8_t hours)
Set the hours in binary for RTC Common Calendar Alarm 1.
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm1HoursBinary (const RTC_Regs *rtc_common)
Get the hours in binary for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_enableAlarm1DayOfWeekBinary (RTC_Regs *rtc_common)
Enable day of the week in binary for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_disableAlarm1DayOfWeekBinary (RTC_Regs *rtc_common)
Disable day of the week in binary for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_setAlarm1DayOfWeekBinary (RTC_Regs *rtc_common, uint8_t day)
Set the day of the week in binary for RTC Common Calendar Alarm 1.
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm1DayOfWeekBinary (const RTC_Regs *rtc_common)
Get the day of the week in binary for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_enableAlarm1DayOfMonthBinary (RTC_Regs *rtc_common)
Enable day of the month in binary for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_disableAlarm1DayOfMonthBinary (RTC_Regs *rtc_common)
Disable day of the month in binary for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_setAlarm1DayOfMonthBinary (RTC_Regs *rtc_common, uint8_t day)
Set the day of the month in binary for RTC Common Calendar Alarm 1.
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm1DayOfMonthBinary (const RTC_Regs *rtc_common)
Get the day of the month in binary for RTC Common Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_Common_enableAlarm2MinutesBinary (RTC_Regs *rtc_common)
Enable minutes in binary for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_disableAlarm2MinutesBinary (RTC_Regs *rtc_common)
Disable minutes in binary for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_setAlarm2MinutesBinary (RTC_Regs *rtc_common, uint8_t minutes)
Set the minutes in binary for RTC Common Calendar Alarm 2.
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm2MinutesBinary (const RTC_Regs *rtc_common)
Get the minutes in binary for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_enableAlarm2HoursBinary (RTC_Regs *rtc_common)
Enable hours in binary for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_disableAlarm2HoursBinary (RTC_Regs *rtc_common)
Disable hours in binary for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_setAlarm2HoursBinary (RTC_Regs *rtc_common, uint8_t hours)
Set the hours in binary for RTC Common Calendar Alarm 2.
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm2HoursBinary (const RTC_Regs *rtc_common)
Get the hours in binary for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_enableAlarm2DayOfWeekBinary (RTC_Regs *rtc_common)
Enable day of the week in binary for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_disableAlarm2DayOfWeekBinary (RTC_Regs *rtc_common)
Disable day of the week in binary for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_setAlarm2DayOfWeekBinary (RTC_Regs *rtc_common, uint8_t day)
Set the day of the week in binary for RTC Common Calendar Alarm 2.
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm2DayOfWeekBinary (const RTC_Regs *rtc_common)
Get the day of the week in binary for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_enableAlarm2DayOfMonthBinary (RTC_Regs *rtc_common)
Enable day of the month in binary for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_disableAlarm2DayOfMonthBinary (RTC_Regs *rtc_common)
Disable day of the month in binary for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_setAlarm2DayOfMonthBinary (RTC_Regs *rtc_common, uint8_t day)
Set the day of the month in binary for RTC Common Calendar Alarm 2.
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm2DayOfMonthBinary (const RTC_Regs *rtc_common)
Get the day of the month in binary for RTC Common Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_Common_setPrescalerEvents (RTC_Regs *rtc_common, DL_RTC_COMMON_PRESCALER0_DIVIDE prescaler0Divider, DL_RTC_COMMON_PRESCALER1_DIVIDE prescaler1Divider, DL_RTC_COMMON_PRESCALER2_DIVIDE prescaler2Divider)
Set prescale interrupt interval for timer 0, 1, and 2.
__STATIC_INLINE void DL_RTC_Common_setPeriodicAlarm0 (RTC_Regs *rtc_common, DL_RTC_COMMON_PRESCALER0_DIVIDE prescaler0Divider)
Set periodic alarm 0.
__STATIC_INLINE void DL_RTC_Common_setPeriodicAlarm1 (RTC_Regs *rtc_common, DL_RTC_COMMON_PRESCALER1_DIVIDE prescaler1Divider)
Set periodic alarm 1.
__STATIC_INLINE void DL_RTC_Common_setPeriodicAlarm2 (RTC_Regs *rtc_common, DL_RTC_COMMON_PRESCALER2_DIVIDE prescaler2Divider)
Set periodic alarm 2.
__STATIC_INLINE DL_RTC_COMMON_PRESCALER0_DIVIDE DL_RTC_Common_getPrescaler0 (const RTC_Regs *rtc_common)
Get prescaler 0 interrupt interval.
__STATIC_INLINE DL_RTC_COMMON_PRESCALER1_DIVIDE DL_RTC_Common_getPrescaler1 (const RTC_Regs *rtc_common)
Get prescaler 1 interrupt interval.
__STATIC_INLINE DL_RTC_COMMON_PRESCALER2_DIVIDE DL_RTC_Common_getPrescaler2 (const RTC_Regs *rtc_common)
Get prescaler 2 interrupt interval.
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampSecondsBCD (const RTC_Regs *rtc_common)
Get the seconds in BCD in the time stamp.
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampMinutesBCD (const RTC_Regs *rtc_common)
Get the minutes in BCD in the time stamp.
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampHoursBCD (const RTC_Regs *rtc_common)
Get the hours in BCD in the time stamp.
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampDayOfWeekBCD (const RTC_Regs *rtc_common)
Get the day of the week in BCD in the time stamp.
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampDayOfMonthBCD (const RTC_Regs *rtc_common)
Get the day of the month in BCD in the time stamp.
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampMonthBCD (const RTC_Regs *rtc_common)
Get the month of the year in BCD in the time stamp.
__STATIC_INLINE uint16_t DL_RTC_Common_getTimeStampYearBCD (const RTC_Regs *rtc_common)
Get the year in BCD in the time stamp.
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampSecondsBinary (const RTC_Regs *rtc_common)
Get the seconds in binary in the time stamp.
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampMinutesBinary (const RTC_Regs *rtc_common)
Get the minutes in binary in the time stamp.
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampHoursBinary (const RTC_Regs *rtc_common)
Get the hours in binary in the time stamp.
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampDayOfWeekBinary (const RTC_Regs *rtc_common)
Get the day of the week in binary in the time stamp.
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampDayOfMonthBinary (const RTC_Regs *rtc_common)
Get the day of the month in binary in the time stamp.
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampMonthBinary (const RTC_Regs *rtc_common)
Get the month of the year in binary in the time stamp.
__STATIC_INLINE uint16_t DL_RTC_Common_getTimeStampYearBinary (const RTC_Regs *rtc_common)
Get the year in binary in the time stamp.
__STATIC_INLINE void DL_RTC_Common_enableInterrupt (RTC_Regs *rtc_common, uint32_t interruptMask)
Enable RTC Common interrupts.
__STATIC_INLINE void DL_RTC_Common_disableInterrupt (RTC_Regs *rtc_common, uint32_t interruptMask)
Disable RTC Common interrupts.
__STATIC_INLINE uint32_t DL_RTC_Common_getEnabledInterrupts (const RTC_Regs *rtc_common, uint32_t interruptMask)
Check which RTC Common interrupts are enabled.
__STATIC_INLINE uint32_t DL_RTC_Common_getEnabledInterruptStatus (const RTC_Regs *rtc_common, uint32_t interruptMask)
Check interrupt flag of enabled RTC Common interrupts.
__STATIC_INLINE uint32_t DL_RTC_Common_getRawInterruptStatus (const RTC_Regs *rtc_common, uint32_t interruptMask)
Check interrupt flag of any RTC Common interrupt.
__STATIC_INLINE DL_RTC_COMMON_IIDX DL_RTC_Common_getPendingInterrupt (const RTC_Regs *rtc_common)
Get highest priority pending RTC Common interrupt.
__STATIC_INLINE void DL_RTC_Common_clearInterruptStatus (RTC_Regs *rtc_common, uint32_t interruptMask)
Clear pending RTC Common interrupts.
__STATIC_INLINE void DL_RTC_Common_enableEvent (RTC_Regs *rtc_common, uint32_t eventMask)
Enable RTC Common event.
__STATIC_INLINE void DL_RTC_Common_disableEvent (RTC_Regs *rtc_common, uint32_t eventMask)
Disable RTC Common event.
__STATIC_INLINE uint32_t DL_RTC_Common_getEnabledEvents (const RTC_Regs *rtc_common, uint32_t eventMask)
Check which RTC Common events are enabled.
__STATIC_INLINE uint32_t DL_RTC_Common_getEnabledEventStatus (const RTC_Regs *rtc_common, uint32_t eventMask)
Check event flag of enabled RTC Common event.
__STATIC_INLINE uint32_t DL_RTC_Common_getRawEventsStatus (const RTC_Regs *rtc_common, uint32_t eventMask)
Check interrupt flag of any RTC Common event.
__STATIC_INLINE void DL_RTC_Common_clearEventsStatus (RTC_Regs *rtc_common, uint32_t eventMask)
Clear pending RTC Common events.
__STATIC_INLINE void DL_RTC_Common_setPublisherChanID (RTC_Regs *rtc_common, uint8_t chanID)
Sets the event publisher channel ID.
__STATIC_INLINE uint8_t DL_RTC_Common_getPublisherChanID (const RTC_Regs *rtc_common)
Gets the event publisher channel ID.
__STATIC_INLINE uint32_t DL_RTC_Common_getTimeStampEventCause (const RTC_Regs *rtc_common, uint32_t tsEventMask)
Gets the cause of the time stamp event.
void DL_RTC_Common_initCalendar (RTC_Regs *rtc_common, DL_RTC_Common_Calendar calendarTime, DL_RTC_COMMON_FORMAT formatSelect)
Initializes the settings to operate the RTC Common in Calendar mode.
DL_RTC_Common_Calendar DL_RTC_Common_getCalendarTime (const RTC_Regs *rtc_common)
Returns the Calendar Time.
void DL_RTC_Common_setCalendarAlarm1 (RTC_Regs *rtc_common, DL_RTC_Common_CalendarAlarm alarmTime)
Set calendar alarm 1.
DL_RTC_Common_CalendarAlarm DL_RTC_Common_getCalendarAlarm1 (const RTC_Regs *rtc_common)
Get calendar alarm 1.
void DL_RTC_Common_enableCalendarAlarm1 (RTC_Regs *rtc_common)
Enable calendar alarm 1.
void DL_RTC_Common_disableCalendarAlarm1 (RTC_Regs *rtc_common)
Disable calendar alarm 1.
void DL_RTC_Common_setCalendarAlarm2 (RTC_Regs *rtc_common, DL_RTC_Common_CalendarAlarm alarmTime)
Set calendar alarm 2.
DL_RTC_Common_CalendarAlarm DL_RTC_Common_getCalendarAlarm2 (const RTC_Regs *rtc_common)
Get calendar alarm 2.
void DL_RTC_Common_enableCalendarAlarm2 (RTC_Regs *rtc_common)
Enable calendar alarm 2.
void DL_RTC_Common_disableCalendarAlarm2 (RTC_Regs *rtc_common)
Disable calendar alarm 2.
__STATIC_INLINE void DL_RTC_Common_setTimeStampEventSource (RTC_Regs *rtc_common, uint32_t sourceMask)
Set the sources to trigger a time stamp capture event.
__STATIC_INLINE uint32_t DL_RTC_Common_getTimeStampEventSource (const RTC_Regs *rtc_common, uint32_t sourceMask)
Get the sources that can trigger a time stamp capture event.
__STATIC_INLINE void DL_RTC_Common_setTimeStampEventCapture (RTC_Regs *rtc_common, DL_RTC_COMMON_TIME_STAMP_EVENT_CAPTURE capture)
Set the capture method when a time stamp capture event occurs.
__STATIC_INLINE DL_RTC_COMMON_TIME_STAMP_EVENT_CAPTURE DL_RTC_Common_getTimeStampEventCapture (const RTC_Regs *rtc_common)
Get the capture method when a time stamp capture event occurs.
__STATIC_INLINE void DL_RTC_Common_clearTimeStamp (RTC_Regs *rtc_common)
Clear the time stamp and time stamp event status.
__STATIC_INLINE void DL_RTC_Common_enableWriteProtect (RTC_Regs *rtc_common)
Enable write protection lock of the CLKCTL, SEC, MIN, HOUR, DAY, MON, YEAR and LFSSRST registers from accidental updates.
__STATIC_INLINE bool DL_RTC_Common_isWriteProtectEnabled (const RTC_Regs *rtc_common)
Checks if write protection lock of the CLKCTL, SEC, MIN, HOUR, DAY, MON, YEAR and LFSSRST registers is enabled.
__STATIC_INLINE void DL_RTC_Common_disableWriteProtect (RTC_Regs *rtc_common)
Disable write protection lock of the CLKCTL, SEC, MIN, HOUR, DAY, MON, YEAR and LFSSRST registers.
Detailed Description
Enumeration Type Documentation
DL_RTC_COMMON_STATUS
enum DL_RTC_COMMON_STATUS
Enumerator
DL_RTC_COMMON_STATUS_READY
RTC Common is safe for reading
DL_RTC_COMMON_STATUS_NOT_READY
RTC Common is not safe for reading
DL_RTC_COMMON_COMPENSATION_STATUS
enum DL_RTC_COMMON_COMPENSATION_STATUS
Enumerator
DL_RTC_COMMON_COMPENSATION_STATUS_READY
RTC Common ready to get new compensation values
DL_RTC_COMMON_COMPENSATION_STATUS_NOT_READY
RTC Common not ready to get new compensaiton values
DL_RTC_COMMON_COMPENSATION_WRITE_RESULT
enum DL_RTC_COMMON_COMPENSATION_WRITE_RESULT
Enumerator
DL_RTC_COMMON_COMPENSATION_WRITE_RESULT_OK
Compensation write successful
DL_RTC_COMMON_COMPENSATION_WRITE_RESULT_NOT_OK
Compensation write unsuccessful
DL_RTC_COMMON_OFFSET_CALIBRATION_SIGN
enum DL_RTC_COMMON_OFFSET_CALIBRATION_SIGN
Enumerator
DL_RTC_COMMON_OFFSET_CALIBRATION_SIGN_DOWN
Calibration frequency adjusted down
DL_RTC_COMMON_OFFSET_CALIBRATION_SIGN_UP
Calibration frequency adjusted up
DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY
enum DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY
Enumerator
DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY_32_KHZ
32 kHz frequency output to RTCLK pin
DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY_512
512 Hz frequency output to RTCLK pin
DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY_256
256 Hz frequency output to RTCLK pin
DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY_1
1 Hz frequency output to RTCLK pin
DL_RTC_COMMON_TEMP_CALIBRATION
enum DL_RTC_COMMON_TEMP_CALIBRATION
Enumerator
DL_RTC_COMMON_TEMP_CALIBRATION_DOWN1PPM
Calibrate at steps of -1
DL_RTC_COMMON_TEMP_CALIBRATION_UP1PPM
Calibrate at steps of +1
DL_RTC_COMMON_FORMAT
enum DL_RTC_COMMON_FORMAT
Enumerator
DL_RTC_COMMON_FORMAT_BINARY
Select binary format for the real-time clock
DL_RTC_COMMON_FORMAT_BCD
Select BCD format for the real-time clock
DL_RTC_COMMON_INTERVAL_ALARM
enum DL_RTC_COMMON_INTERVAL_ALARM
Enumerator
DL_RTC_COMMON_INTERVAL_ALARM_MINUTECHANGE
Assert Calendar interrupt on every minute
DL_RTC_COMMON_INTERVAL_ALARM_HOURCHANGE
Assert Calendar interrupt on every hour
DL_RTC_COMMON_INTERVAL_ALARM_NOON
Assert Calendar interrupt when hour is 12
DL_RTC_COMMON_INTERVAL_ALARM_MIDNIGHT
Assert Calendar interrupt when hour is 0
DL_RTC_COMMON_PRESCALER0_DIVIDE
enum DL_RTC_COMMON_PRESCALER0_DIVIDE
Enumerator
DL_RTC_COMMON_PRESCALER0_DIVIDE_8
Prescaler 0 Divide by 8
DL_RTC_COMMON_PRESCALER0_DIVIDE_16
Prescaler 0 Divide by 16
DL_RTC_COMMON_PRESCALER0_DIVIDE_32
Prescaler 0 Divide by 32
DL_RTC_COMMON_PRESCALER0_DIVIDE_64
Prescaler 0 Divide by 64
DL_RTC_COMMON_PRESCALER0_DIVIDE_128
Prescaler 0 Divide by 128
DL_RTC_COMMON_PRESCALER0_DIVIDE_256
Prescaler 0 Divide by 256
DL_RTC_COMMON_PRESCALER1_DIVIDE
enum DL_RTC_COMMON_PRESCALER1_DIVIDE
Enumerator
DL_RTC_COMMON_PRESCALER1_DIVIDE_2
Prescaler 1 Divide by 2
DL_RTC_COMMON_PRESCALER1_DIVIDE_4
Prescaler 1 Divide by 4
DL_RTC_COMMON_PRESCALER1_DIVIDE_8
Prescaler 1 Divide by 8
DL_RTC_COMMON_PRESCALER1_DIVIDE_16
Prescaler 1 Divide by 16
DL_RTC_COMMON_PRESCALER1_DIVIDE_32
Prescaler 1 Divide by 32
DL_RTC_COMMON_PRESCALER1_DIVIDE_64
Prescaler 1 Divide by 64
DL_RTC_COMMON_PRESCALER1_DIVIDE_128
Prescaler 1 Divide by 128
DL_RTC_COMMON_PRESCALER1_DIVIDE_256
Prescaler 1 Divide by 256
DL_RTC_COMMON_PRESCALER2_DIVIDE
enum DL_RTC_COMMON_PRESCALER2_DIVIDE
Enumerator
DL_RTC_COMMON_PRESCALER2_4_SEC
Interval every 4 seconds
DL_RTC_COMMON_PRESCALER2_8_SEC
Interval every 8 seconds
DL_RTC_COMMON_PRESCALER2_16_SEC
Interval every 16 seconds
DL_RTC_COMMON_IIDX
enum DL_RTC_COMMON_IIDX
Enumerator
DL_RTC_COMMON_IIDX_ALARM1
RTC Common interrupt index for alarm 1
DL_RTC_COMMON_IIDX_ALARM2
RTC Common interrupt index for alarm 2
DL_RTC_COMMON_IIDX_PRESCALER0
RTC Common interrupt index for prescaler 0
DL_RTC_COMMON_IIDX_PRESCALER1
RTC Common interrupt index for prescaler 1
DL_RTC_COMMON_IIDX_PRESCALER2
RTC Common interrupt index for prescaler 2
DL_RTC_COMMON_IIDX_INTERVAL_TIMER
RTC Common interrupt index for interval timer
DL_RTC_COMMON_IIDX_READY
RTC Common interrupt index for RTC Common ready
DL_RTC_COMMON_IIDX_TSEVT
RTC Common interrupt index for Time Stamp
DL_RTC_COMMON_IIDX_TAMPER_IO_0
RTC Common interrupt index for Tamper IO 0
DL_RTC_COMMON_IIDX_TAMPER_IO_1
RTC Common interrupt index for Tamper IO 1
DL_RTC_COMMON_IIDX_TAMPER_IO_2
RTC Common interrupt index for Tamper IO 2
DL_RTC_COMMON_IIDX_TAMPER_IO_3
RTC Common interrupt index for Tamper IO 3
DL_RTC_COMMON_IIDX_TAMPER_IO_4
RTC Common interrupt index for Tamper IO 4
DL_RTC_COMMON_IIDX_TAMPER_IO_5
RTC Common interrupt index for Tamper IO 5
DL_RTC_COMMON_IIDX_TAMPER_IO_6
RTC Common interrupt index for Tamper IO 6
DL_RTC_COMMON_IIDX_TAMPER_IO_7
RTC Common interrupt index for Tamper IO 7
DL_RTC_COMMON_IIDX_TAMPER_IO_8
RTC Common interrupt index for Tamper IO 8
DL_RTC_COMMON_IIDX_TAMPER_IO_9
RTC Common interrupt index for Tamper IO 9
DL_RTC_COMMON_IIDX_TAMPER_IO_10
RTC Common interrupt index for Tamper IO 10
DL_RTC_COMMON_IIDX_TAMPER_IO_11
RTC Common interrupt index for Tamper IO 11
DL_RTC_COMMON_IIDX_TAMPER_IO_12
RTC Common interrupt index for Tamper IO 12
DL_RTC_COMMON_IIDX_TAMPER_IO_13
RTC Common interrupt index for Tamper IO 13
DL_RTC_COMMON_IIDX_TAMPER_IO_14
RTC Common interrupt index for Tamper IO 14
DL_RTC_COMMON_IIDX_TAMPER_IO_15
RTC Common interrupt index for Tamper IO 15
DL_RTC_COMMON_TIME_STAMP_EVENT_CAPTURE
enum DL_RTC_COMMON_TIME_STAMP_EVENT_CAPTURE
Enumerator
DL_RTC_COMMON_TIME_STAMP_EVENT_CAPTURE_FIRST
Time stamp holds RTC capture at first occurrence of time stamp event
DL_RTC_COMMON_TIME_STAMP_EVENT_CAPTURE_LAST
Time stamp holds RTC capture at last occurrence of time stamp event
Function Documentation
DL_RTC_Common_isClockSourceLFCLK()
__STATIC_INLINE bool DL_RTC_Common_isClockSourceLFCLK (const RTC_Regs * rtc_common)
Returns if LFCLK is selected as clock source.
If the LFCLK is enabled, the RTC Common module will select it as the clock source.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
true If LFCLK is selected as the clock source
false If LFCLK is not selected as the clock source
DL_RTC_Common_enableClockControl()
__STATIC_INLINE void DL_RTC_Common_enableClockControl (RTC_Regs * rtc_common)
Enables the supply of the 32kHz clock to the RTC Common. It will not power up the 32kHz crystal oscillator. This needs to be done in the Clock System Module.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableClockControl()
__STATIC_INLINE void DL_RTC_Common_disableClockControl (RTC_Regs * rtc_common)
Disables the supply of the 32kHz clock to the RTC Common.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_enablePower()
__STATIC_INLINE void DL_RTC_Common_enablePower (RTC_Regs * rtc_common)
Enables the Peripheral Write Enable (PWREN) register for the RTC.
Before any peripheral registers can be configured by software, the peripheral itself must be enabled by writing the ENABLE bit together with the appropriate KEY value to the peripheral's PWREN register.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disablePower()
__STATIC_INLINE void DL_RTC_Common_disablePower (RTC_Regs * rtc_common)
Disables the Peripheral Write Enable (PWREN) register for the RTC.
When the PWREN.ENABLE bit is cleared, the peripheral's registers are not accessible for read/write operations.
Note
This API does not provide large power savings.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_isPowerEnabled()
__STATIC_INLINE bool DL_RTC_Common_isPowerEnabled (const RTC_Regs * rtc_common)
Returns if the Peripheral Write Enable (PWREN) register for the RTC is enabled.
Before any peripheral registers can be configured by software, the peripheral itself must be enabled by writing the ENABLE bit together with the appropriate KEY value to the peripheral's PWREN register.
When the PWREN.ENABLE bit is cleared, the peripheral's registers are not accessible for read/write operations.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
true if peripheral register access is enabled
false if peripheral register access is disabled
DL_RTC_Common_reset()
__STATIC_INLINE void DL_RTC_Common_reset (RTC_Regs * rtc_common)
Resets all registers in the RTC Common module.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_isReset()
__STATIC_INLINE bool DL_RTC_Common_isReset (const RTC_Regs * rtc_common)
Returns if the RTC Common module was reset.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
true if module was reset
false if module was not reset
DL_RTC_Common_enableDebugInterrupts()
__STATIC_INLINE void DL_RTC_Common_enableDebugInterrupts (RTC_Regs * rtc_common)
Enables interrupts when the CPU is in debug mode. Interrupt requests are signaled to the interrupt controller.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableDebugInterrupts()
__STATIC_INLINE void DL_RTC_Common_disableDebugInterrupts (RTC_Regs * rtc_common)
Disables interrupts when the CPU is in debug mode. Interrupts of the RTC Common module will not be captured. There will be no updates to the RTCRIS, RTCMISC and RTCIIDX registers.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_enableDebugMode()
__STATIC_INLINE void DL_RTC_Common_enableDebugMode (RTC_Regs * rtc_common)
Enables the RTC Common modules debug mode.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableDebugMode()
__STATIC_INLINE void DL_RTC_Common_disableDebugMode (RTC_Regs * rtc_common)
Disables the RTC Common modules debug mode.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setClockFormat()
__STATIC_INLINE void DL_RTC_Common_setClockFormat (RTC_Regs * rtc_common, DL_RTC_COMMON_FORMAT formatSelect)
Set the format of the real-time clock.
The format must be selected before the time is set.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] formatSelect Selectable format the RTC Common peripheral will provide time in. One of DL_RTC_COMMON_FORMAT
DL_RTC_Common_getClockFormat()
__STATIC_INLINE DL_RTC_COMMON_FORMAT DL_RTC_Common_getClockFormat (const RTC_Regs * rtc_common)
Get the format currently being used for counting the real-time clock.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
Format for counting the real-time clock.
Return values
One of DL_RTC_COMMON_FORMAT
DL_RTC_Common_setIntervalAlarm()
__STATIC_INLINE void DL_RTC_Common_setIntervalAlarm (RTC_Regs * rtc_common, DL_RTC_COMMON_INTERVAL_ALARM alarmEvent)
Sets the interval alarm event condition.
The interval alarm can be configured to generate an interval alarm event when one of the following events occurs:
MIN changes
HOUR changes
Every day at midnight (00:00:00)
Every day at noon (12:00:00)
The interval alarm sources the DL_RTC_COMMON_INTERRUPT_INTERVAL_ALARM interrupt
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] alarmEvent The interval alarm interrupt condition. One of DL_RTC_COMMON_INTERVAL_ALARM
References DL_Common_updateReg().
DL_RTC_Common_getIntervalAlarm()
__STATIC_INLINE DL_RTC_COMMON_INTERVAL_ALARM DL_RTC_Common_getIntervalAlarm (const RTC_Regs * rtc_common)
Gets the interval alarm event condition.
The interval alarm can be configured to generate an interval alarm event when one of the following events occurs:
MIN changes
HOUR changes
Every day at midnight (00:00:00)
Every day at noon (12:00:00)
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
DL_RTC_COMMON_INTERVAL_ALARM
DL_RTC_Common_isSafeToRead()
__STATIC_INLINE bool DL_RTC_Common_isSafeToRead (const RTC_Regs * rtc_common)
Checks if RTC Common is safe for reading.
This API checks if the counter/calender registers can be safely read.
The RTC Common counter/calendar registers are updated once per second. To prevent reading any counter/calendar register at the time of an update (which could result in an invalid time being read), a keep-out window is provided. The keep-out window is approximately 128/32768 seconds before the counters update.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
true if RTC Common is safe for reading
false if RTC Common values are in transition
DL_RTC_Common_isReadyToCalibrate()
__STATIC_INLINE bool DL_RTC_Common_isReadyToCalibrate (const RTC_Regs * rtc_common)
Checks if RTC Common is ready to get new calibration values.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
true if RTC Common can get new calibration values
false if RTC Common is not ready to get new calibration values
DL_RTC_Common_isCalibrationWriteResultOK()
__STATIC_INLINE bool DL_RTC_Common_isCalibrationWriteResultOK (const RTC_Regs * rtc_common)
Checks if RTC Common new calibration values were written OK.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
true if calibration write was successful
false if calibration write was unsuccessful
DL_RTC_Common_setOffsetCalibrationFrequency()
__STATIC_INLINE void DL_RTC_Common_setOffsetCalibrationFrequency (RTC_Regs * rtc_common, DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY offsetFrequency)
Sets output frequency for offset calibration.
Sets the frequency output to RTC_OUT pin for calibration measurement. The corresponding port must be configured for the peripheral module function.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] offsetFrequency The frequency of offset calibration. Valid values are one of DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY
References DL_Common_updateReg().
DL_RTC_Common_setOffsetCalibrationAdjValue()
__STATIC_INLINE void DL_RTC_Common_setOffsetCalibrationAdjValue (RTC_Regs * rtc_common, DL_RTC_COMMON_OFFSET_CALIBRATION_SIGN offsetSign, uint8_t offsetValue)
Sets the offset error calibration adjustment value.
Each LSB represents approximately +1ppm (RTCOCALXS = 1) or -1ppm (RTCOCALXS = 0) adjustment in frequency. Maximum effective calibration value is +/-240ppm. Excess values written above +/-240ppm will be ignored by hardware.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] offsetSign The sign of offset calibration. Valid values are one of DL_RTC_COMMON_OFFSET_CALIBRATION_SIGN
[in] offsetValue The value that the offset will be a factor of. Must be any integer from 1-240.
References DL_Common_updateReg().
DL_RTC_Common_setOffsetCalibration()
__STATIC_INLINE void DL_RTC_Common_setOffsetCalibration (RTC_Regs * rtc_common, DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY offsetFrequency, DL_RTC_COMMON_OFFSET_CALIBRATION_SIGN offsetSign, uint8_t offsetValue)
Sets the offset error calibration.
Each LSB represents approximately +1ppm (RTCOCALXS = 1) or -1ppm (RTCOCALXS = 0) adjustment in frequency. Maximum effective calibration value is +/-240ppm. Excess values written above +/-240ppm will be ignored by hardware.
Sets the frequency output to RTCCLK pin for calibration measurement. The corresponding port must be configured for the peripheral module function.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] offsetFrequency The frequency of offset calibration. Valid values are one of DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY
[in] offsetSign The sign of offset calibration. Valid values are one of DL_RTC_COMMON_OFFSET_CALIBRATION_SIGN
[in] offsetValue The value that the offset will be a factor of. Must be any integer from 1-240.
DL_RTC_Common_getOffsetCalibrationFrequency()
__STATIC_INLINE DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY DL_RTC_Common_getOffsetCalibrationFrequency (const RTC_Regs * rtc_common)
Gets the offset calibration frequency.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
Frequency used in offset calibration.
Return values
One of DL_RTC_COMMON_OFFSET_CALIBRATION_FREQUENCY
DL_RTC_Common_getOffsetCalibrationSign()
__STATIC_INLINE DL_RTC_COMMON_OFFSET_CALIBRATION_SIGN DL_RTC_Common_getOffsetCalibrationSign (const RTC_Regs * rtc_common)
Gets the offset calibration sign.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
Sign used in offset calibration.
Return values
One of DL_RTC_COMMON_OFFSET_CALIBRATION_SIGN
DL_RTC_Common_setTemperatureCompensation()
__STATIC_INLINE void DL_RTC_Common_setTemperatureCompensation (RTC_Regs * rtc_common, DL_RTC_COMMON_TEMP_CALIBRATION offsetDirection, uint32_t offsetValue)
Set the specified RTC Common temperature compensation.
This function sets the calibration offset to make the RTC Common as accurate as possible. The offsetDirection can be either +1-ppm or -1-ppm, and the offsetValue should be from 1-240 and is multiplied by the direction setting (i.e. +1-ppm * 8 (offsetValue) = +8-ppm).
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] offsetDirection The direction that the calibration offset will go. Valid values are one of DL_RTC_COMMON_TEMP_CALIBRATION
[in] offsetValue The value that the offset will be a factor of. Must be any integer from 1-240.
DL_RTC_Common_getTemperatureCompensation()
__STATIC_INLINE uint32_t DL_RTC_Common_getTemperatureCompensation (const RTC_Regs * rtc_common)
Get the RTC Common temperature compensation.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The cumulative temperature compensation
Return values
Signed addition of RTCOCALX and RTCTCMPX values, and the updated sign bit (RTCTCMPS) of the addition result.
DL_RTC_Common_setCalendarSecondsBCD()
__STATIC_INLINE void DL_RTC_Common_setCalendarSecondsBCD (RTC_Regs * rtc_common, uint8_t seconds)
Set the seconds in BCD in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] seconds Value for the seconds of the RTC Common calendar Valid values are 0x0-0x59.
DL_RTC_Common_getCalendarSecondsBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarSecondsBCD (const RTC_Regs * rtc_common)
Get the seconds in in BCD the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The seconds in the RTC Common calendar
Return values
Value in range: 0x0-0x59
DL_RTC_Common_setCalendarMinutesBCD()
__STATIC_INLINE void DL_RTC_Common_setCalendarMinutesBCD (RTC_Regs * rtc_common, uint8_t minutes)
Set the minutes in in BCD the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] minutes Value for the minutes of the RTC Common calendar Valid values are 0x0-0x59.
DL_RTC_Common_getCalendarMinutesBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarMinutesBCD (const RTC_Regs * rtc_common)
Get the minutes in in BCD the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The minutes in the RTC Common calendar
Return values
Value in range: 0x0-0x59
DL_RTC_Common_setCalendarHoursBCD()
__STATIC_INLINE void DL_RTC_Common_setCalendarHoursBCD (RTC_Regs * rtc_common, uint8_t hours)
Set the hours in in BCD the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] hours Value for the hours of the RTC Common calendar Valid values are 0x0-0x23
DL_RTC_Common_getCalendarHoursBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarHoursBCD (const RTC_Regs * rtc_common)
Get the hours in in BCD the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The hours in the RTC Common calendar
Return values
Value in range: 0x0-0x23
DL_RTC_Common_setCalendarDayOfWeekBCD()
__STATIC_INLINE void DL_RTC_Common_setCalendarDayOfWeekBCD (RTC_Regs * rtc_common, uint8_t day)
Set the day of the week in BCD in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] day Value for the day of the week of the RTC Common calendar Valid values are 0x0-0x6
References DL_Common_updateReg().
DL_RTC_Common_getCalendarDayOfWeekBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarDayOfWeekBCD (const RTC_Regs * rtc_common)
Get the day of the week in BCD in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The day of the week in the RTC Common calendar
Return values
Value in range: 0x0-0x6
DL_RTC_Common_setCalendarDayOfMonthBCD()
__STATIC_INLINE void DL_RTC_Common_setCalendarDayOfMonthBCD (RTC_Regs * rtc_common, uint8_t day)
Set the day of the month in BCD in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] day Value for the day of the month of the RTC Common calendar Valid values are 0x1-0x31
References DL_Common_updateReg().
DL_RTC_Common_getCalendarDayOfMonthBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarDayOfMonthBCD (const RTC_Regs * rtc_common)
Get the day of the month in BCD in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The day of the month in the RTC Common calendar
Return values
Value in range: 0x1-0x31
DL_RTC_Common_setCalendarMonthBCD()
__STATIC_INLINE void DL_RTC_Common_setCalendarMonthBCD (RTC_Regs * rtc_common, uint8_t month)
Set the month in in BCD the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] month Value for the month of the RTC Common calendar Valid values are 0x1-0x12
DL_RTC_Common_getCalendarMonthBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarMonthBCD (const RTC_Regs * rtc_common)
Get the month of the year in BCD in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The month of the year in the RTC Common calendar
Return values
Value in range: 0x1-0x12
DL_RTC_Common_setCalendarYearBCD()
__STATIC_INLINE void DL_RTC_Common_setCalendarYearBCD (RTC_Regs * rtc_common, uint16_t year)
Set the year in in BCD the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] year Value for the year of the RTC Common calendar Valid values are 0x0-0x4095
DL_RTC_Common_getCalendarYearBCD()
__STATIC_INLINE uint16_t DL_RTC_Common_getCalendarYearBCD (const RTC_Regs * rtc_common)
Get the year in in BCD the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The year in the RTC Common calendar
Return values
Value in range: 0x0-0x4095
DL_RTC_Common_enableAlarm1MinutesBCD()
__STATIC_INLINE void DL_RTC_Common_enableAlarm1MinutesBCD (RTC_Regs * rtc_common)
Enable minutes in BCD for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableAlarm1MinutesBCD()
__STATIC_INLINE void DL_RTC_Common_disableAlarm1MinutesBCD (RTC_Regs * rtc_common)
Disable minutes in BCD for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setAlarm1MinutesBCD()
__STATIC_INLINE void DL_RTC_Common_setAlarm1MinutesBCD (RTC_Regs * rtc_common, uint8_t minutes)
Set the minutes in BCD for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] minutes Value for the minutes of alarm 1 Valid values are 0x0-0x59
DL_RTC_Common_getAlarm1MinutesBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm1MinutesBCD (const RTC_Regs * rtc_common)
Get the minutes in BCD for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The minutes of alarm 1
Return values
Value in range: 0x0-0x59
DL_RTC_Common_enableAlarm1HoursBCD()
__STATIC_INLINE void DL_RTC_Common_enableAlarm1HoursBCD (RTC_Regs * rtc_common)
Enable hours in BCD for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableAlarm1HoursBCD()
__STATIC_INLINE void DL_RTC_Common_disableAlarm1HoursBCD (RTC_Regs * rtc_common)
Disable hours in BCD for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setAlarm1HoursBCD()
__STATIC_INLINE void DL_RTC_Common_setAlarm1HoursBCD (RTC_Regs * rtc_common, uint8_t hours)
Set the hours in BCD for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] hours Value for the hours of alarm 1 Valid values are 0x0-0x23
DL_RTC_Common_getAlarm1HoursBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm1HoursBCD (const RTC_Regs * rtc_common)
Get the hours in BCD for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The hours of alarm 1
Return values
Value in range: 0x0-0x23
DL_RTC_Common_enableAlarm1DayOfWeekBCD()
__STATIC_INLINE void DL_RTC_Common_enableAlarm1DayOfWeekBCD (RTC_Regs * rtc_common)
Enable day of the week in BCD for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableAlarm1DayOfWeekBCD()
__STATIC_INLINE void DL_RTC_Common_disableAlarm1DayOfWeekBCD (RTC_Regs * rtc_common)
Disable day of the week in BCD for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setAlarm1DayOfWeekBCD()
__STATIC_INLINE void DL_RTC_Common_setAlarm1DayOfWeekBCD (RTC_Regs * rtc_common, uint8_t day)
Set the day of the week in BCD for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] day Value for the day of the week of the RTC Common calendar Valid values are 0x0-0x6
References DL_Common_updateReg().
DL_RTC_Common_getAlarm1DayOfWeekBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm1DayOfWeekBCD (const RTC_Regs * rtc_common)
Get the day of the week in BCD for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The day of the week in the RTC Common calendar
Return values
Value in range: 0x0-0x6
DL_RTC_Common_enableAlarm1DayOfMonthBCD()
__STATIC_INLINE void DL_RTC_Common_enableAlarm1DayOfMonthBCD (RTC_Regs * rtc_common)
Enable day of the month in BCD for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableAlarm1DayOfMonthBCD()
__STATIC_INLINE void DL_RTC_Common_disableAlarm1DayOfMonthBCD (RTC_Regs * rtc_common)
Disable day of the month in BCD for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setAlarm1DayOfMonthBCD()
__STATIC_INLINE void DL_RTC_Common_setAlarm1DayOfMonthBCD (RTC_Regs * rtc_common, uint8_t day)
Set the day of the month in BCD for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] day Value for the day of the month of the RTC Common calendar Valid values are 0x1-0x31
References DL_Common_updateReg().
DL_RTC_Common_getAlarm1DayOfMonthBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm1DayOfMonthBCD (const RTC_Regs * rtc_common)
Get the day of the month in BCD for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The day of the month in the RTC Common calendar
Return values
Value in range: 0x1-0x31
DL_RTC_Common_enableAlarm2MinutesBCD()
__STATIC_INLINE void DL_RTC_Common_enableAlarm2MinutesBCD (RTC_Regs * rtc_common)
Enable minutes in BCD for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableAlarm2MinutesBCD()
__STATIC_INLINE void DL_RTC_Common_disableAlarm2MinutesBCD (RTC_Regs * rtc_common)
Disable minutes in BCD for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setAlarm2MinutesBCD()
__STATIC_INLINE void DL_RTC_Common_setAlarm2MinutesBCD (RTC_Regs * rtc_common, uint8_t minutes)
Set the minutes in BCD for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] minutes Value for the minutes of alarm 2 Valid values are 0x0-0x59
DL_RTC_Common_getAlarm2MinutesBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm2MinutesBCD (const RTC_Regs * rtc_common)
Get the minutes in BCD for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The minutes of alarm 2
Return values
Value in range: 0x0-0x59
DL_RTC_Common_enableAlarm2HoursBCD()
__STATIC_INLINE void DL_RTC_Common_enableAlarm2HoursBCD (RTC_Regs * rtc_common)
Enable hours in BCD for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableAlarm2HoursBCD()
__STATIC_INLINE void DL_RTC_Common_disableAlarm2HoursBCD (RTC_Regs * rtc_common)
Disable hours in BCD for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setAlarm2HoursBCD()
__STATIC_INLINE void DL_RTC_Common_setAlarm2HoursBCD (RTC_Regs * rtc_common, uint8_t hours)
Set the hours in BCD for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] hours Value for the hours of alarm 2 Valid values are 0x0-0x23
DL_RTC_Common_getAlarm2HoursBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm2HoursBCD (const RTC_Regs * rtc_common)
Get the hours in BCD for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The hours of alarm 2
Return values
Value in range: 0x0-0x23
DL_RTC_Common_enableAlarm2DayOfWeekBCD()
__STATIC_INLINE void DL_RTC_Common_enableAlarm2DayOfWeekBCD (RTC_Regs * rtc_common)
Enable day of the week in BCD for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableAlarm2DayOfWeekBCD()
__STATIC_INLINE void DL_RTC_Common_disableAlarm2DayOfWeekBCD (RTC_Regs * rtc_common)
Disable day of the week in BCD for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setAlarm2DayOfWeekBCD()
__STATIC_INLINE void DL_RTC_Common_setAlarm2DayOfWeekBCD (RTC_Regs * rtc_common, uint8_t day)
Set the day of the week in BCD for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] day Value for the day of the week of the RTC Common calendar Valid values are 0x0-0x6
References DL_Common_updateReg().
DL_RTC_Common_getAlarm2DayOfWeekBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm2DayOfWeekBCD (const RTC_Regs * rtc_common)
Get the day of the week in BCD for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The day of the week in the RTC Common calendar
Return values
Value in range: 0x0-0x6
DL_RTC_Common_enableAlarm2DayOfMonthBCD()
__STATIC_INLINE void DL_RTC_Common_enableAlarm2DayOfMonthBCD (RTC_Regs * rtc_common)
Enable day of the month in BCD for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableAlarm2DayOfMonthBCD()
__STATIC_INLINE void DL_RTC_Common_disableAlarm2DayOfMonthBCD (RTC_Regs * rtc_common)
Disable day of the month in BCD for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setAlarm2DayOfMonthBCD()
__STATIC_INLINE void DL_RTC_Common_setAlarm2DayOfMonthBCD (RTC_Regs * rtc_common, uint8_t day)
Set the day of the month in BCD for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] day Value for the day of the month of the RTC Common calendar Valid values are 0x1-0x31
References DL_Common_updateReg().
DL_RTC_Common_getAlarm2DayOfMonthBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm2DayOfMonthBCD (const RTC_Regs * rtc_common)
Get the day of the month in BCD for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The day of the month in the RTC Common calendar
Return values
Value in range: 0x1-0x31
DL_RTC_Common_setCalendarSecondsBinary()
__STATIC_INLINE void DL_RTC_Common_setCalendarSecondsBinary (RTC_Regs * rtc_common, uint8_t seconds)
Set the seconds in binary the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] seconds Value for the seconds of the RTC Common calendar Valid values are 0-59
DL_RTC_Common_getCalendarSecondsBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarSecondsBinary (const RTC_Regs * rtc_common)
Get the seconds in binary in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The seconds in the RTC Common calendar
Return values
Value in range: 0-59
DL_RTC_Common_setCalendarMinutesBinary()
__STATIC_INLINE void DL_RTC_Common_setCalendarMinutesBinary (RTC_Regs * rtc_common, uint8_t minutes)
Set the minutes in binary in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] minutes Value for the minutes of the RTC Common calendar Valid values are 0-59
DL_RTC_Common_getCalendarMinutesBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarMinutesBinary (const RTC_Regs * rtc_common)
Get the minutes in binary in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The minutes in the RTC Common calendar
Return values
Value in range: 0-59
DL_RTC_Common_setCalendarHoursBinary()
__STATIC_INLINE void DL_RTC_Common_setCalendarHoursBinary (RTC_Regs * rtc_common, uint8_t hours)
Set the hours in binary in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] hours Value for the hours of the RTC Common calendar Valid values are 0-23
DL_RTC_Common_getCalendarHoursBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarHoursBinary (const RTC_Regs * rtc_common)
Get the hours in binary in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The hours in the RTC Common calendar
Return values
Value in range: 0-23
DL_RTC_Common_setCalendarDayOfWeekBinary()
__STATIC_INLINE void DL_RTC_Common_setCalendarDayOfWeekBinary (RTC_Regs * rtc_common, uint8_t day)
Set the day of the week in binary in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] day Value for the day of the week of the RTC Common calendar Valid values are 0-6
References DL_Common_updateReg().
DL_RTC_Common_getCalendarDayOfWeekBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarDayOfWeekBinary (const RTC_Regs * rtc_common)
Get the day of the week in binary in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The day of the week in the RTC Common calendar
Return values
Value in range: 0-6
DL_RTC_Common_setCalendarDayOfMonthBinary()
__STATIC_INLINE void DL_RTC_Common_setCalendarDayOfMonthBinary (RTC_Regs * rtc_common, uint8_t day)
Set the day of the month in binary in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] day Value for the day of the month of the RTC Common calendar Valid values are 1-31
References DL_Common_updateReg().
DL_RTC_Common_getCalendarDayOfMonthBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarDayOfMonthBinary (const RTC_Regs * rtc_common)
Get the day of the month in binary in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The day of the month in the RTC Common calendar
Return values
Value in range: 1-31
DL_RTC_Common_setCalendarMonthBinary()
__STATIC_INLINE void DL_RTC_Common_setCalendarMonthBinary (RTC_Regs * rtc_common, uint8_t month)
Set the month in binary in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] month Value for the month of the RTC Common calendar Valid values are 1-12
DL_RTC_Common_getCalendarMonthBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getCalendarMonthBinary (const RTC_Regs * rtc_common)
Get the month of the year in binary in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The month of the year in the RTC Common calendar
Return values
Value in range: 1-12
DL_RTC_Common_setCalendarYearBinary()
__STATIC_INLINE void DL_RTC_Common_setCalendarYearBinary (RTC_Regs * rtc_common, uint16_t year)
Set the year in binary in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] year Value for the year of the RTC Common calendar Valid values are 0-4095
DL_RTC_Common_getCalendarYearBinary()
__STATIC_INLINE uint16_t DL_RTC_Common_getCalendarYearBinary (const RTC_Regs * rtc_common)
Get the year in binary in the RTC Common calendar.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The year in the RTC Common calendar
Return values
Value in range: 0-4095
DL_RTC_Common_enableAlarm1MinutesBinary()
__STATIC_INLINE void DL_RTC_Common_enableAlarm1MinutesBinary (RTC_Regs * rtc_common)
Enable minutes in binary in binary for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableAlarm1MinutesBinary()
__STATIC_INLINE void DL_RTC_Common_disableAlarm1MinutesBinary (RTC_Regs * rtc_common)
Disable minutes in binary for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setAlarm1MinutesBinary()
__STATIC_INLINE void DL_RTC_Common_setAlarm1MinutesBinary (RTC_Regs * rtc_common, uint8_t minutes)
Set the minutes in binary for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] minutes Value for the minutes of alarm 1 Valid values are 0-59
DL_RTC_Common_getAlarm1MinutesBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm1MinutesBinary (const RTC_Regs * rtc_common)
Get the minutes in binary for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The minutes of alarm 1
Return values
Value in range: 0-59
DL_RTC_Common_enableAlarm1HoursBinary()
__STATIC_INLINE void DL_RTC_Common_enableAlarm1HoursBinary (RTC_Regs * rtc_common)
Enable hours in binary for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableAlarm1HoursBinary()
__STATIC_INLINE void DL_RTC_Common_disableAlarm1HoursBinary (RTC_Regs * rtc_common)
Disable hours in binary for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setAlarm1HoursBinary()
__STATIC_INLINE void DL_RTC_Common_setAlarm1HoursBinary (RTC_Regs * rtc_common, uint8_t hours)
Set the hours in binary for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] hours Value for the hours of alarm 1 Valid values are 0-23
DL_RTC_Common_getAlarm1HoursBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm1HoursBinary (const RTC_Regs * rtc_common)
Get the hours in binary for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The hours of alarm 1
Return values
Value in range: 0-23
DL_RTC_Common_enableAlarm1DayOfWeekBinary()
__STATIC_INLINE void DL_RTC_Common_enableAlarm1DayOfWeekBinary (RTC_Regs * rtc_common)
Enable day of the week in binary for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableAlarm1DayOfWeekBinary()
__STATIC_INLINE void DL_RTC_Common_disableAlarm1DayOfWeekBinary (RTC_Regs * rtc_common)
Disable day of the week in binary for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setAlarm1DayOfWeekBinary()
__STATIC_INLINE void DL_RTC_Common_setAlarm1DayOfWeekBinary (RTC_Regs * rtc_common, uint8_t day)
Set the day of the week in binary for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] day Value for the day of the week of the RTC Common calendar Valid values are 0-6
References DL_Common_updateReg().
DL_RTC_Common_getAlarm1DayOfWeekBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm1DayOfWeekBinary (const RTC_Regs * rtc_common)
Get the day of the week in binary for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The day of the week in the RTC Common calendar
Return values
Value in range: 0-6
DL_RTC_Common_enableAlarm1DayOfMonthBinary()
__STATIC_INLINE void DL_RTC_Common_enableAlarm1DayOfMonthBinary (RTC_Regs * rtc_common)
Enable day of the month in binary for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableAlarm1DayOfMonthBinary()
__STATIC_INLINE void DL_RTC_Common_disableAlarm1DayOfMonthBinary (RTC_Regs * rtc_common)
Disable day of the month in binary for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setAlarm1DayOfMonthBinary()
__STATIC_INLINE void DL_RTC_Common_setAlarm1DayOfMonthBinary (RTC_Regs * rtc_common, uint8_t day)
Set the day of the month in binary for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] day Value for the day of the month of the RTC Common calendar Valid values are 1-31
References DL_Common_updateReg().
DL_RTC_Common_getAlarm1DayOfMonthBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm1DayOfMonthBinary (const RTC_Regs * rtc_common)
Get the day of the month in binary for RTC Common Calendar Alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The day of the month in the RTC Common calendar
Return values
Value in range: 1-31
DL_RTC_Common_enableAlarm2MinutesBinary()
__STATIC_INLINE void DL_RTC_Common_enableAlarm2MinutesBinary (RTC_Regs * rtc_common)
Enable minutes in binary for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableAlarm2MinutesBinary()
__STATIC_INLINE void DL_RTC_Common_disableAlarm2MinutesBinary (RTC_Regs * rtc_common)
Disable minutes in binary for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setAlarm2MinutesBinary()
__STATIC_INLINE void DL_RTC_Common_setAlarm2MinutesBinary (RTC_Regs * rtc_common, uint8_t minutes)
Set the minutes in binary for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] minutes Value for the minutes of alarm 2 Valid values are 0-59
DL_RTC_Common_getAlarm2MinutesBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm2MinutesBinary (const RTC_Regs * rtc_common)
Get the minutes in binary for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The minutes of alarm 2
Return values
Value in range: 0-59
DL_RTC_Common_enableAlarm2HoursBinary()
__STATIC_INLINE void DL_RTC_Common_enableAlarm2HoursBinary (RTC_Regs * rtc_common)
Enable hours in binary for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableAlarm2HoursBinary()
__STATIC_INLINE void DL_RTC_Common_disableAlarm2HoursBinary (RTC_Regs * rtc_common)
Disable hours in binary for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setAlarm2HoursBinary()
__STATIC_INLINE void DL_RTC_Common_setAlarm2HoursBinary (RTC_Regs * rtc_common, uint8_t hours)
Set the hours in binary for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] hours Value for the hours of alarm 2 Valid values are 0-23
DL_RTC_Common_getAlarm2HoursBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm2HoursBinary (const RTC_Regs * rtc_common)
Get the hours in binary for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The hours of alarm 2
Return values
Value in range: 0-23
DL_RTC_Common_enableAlarm2DayOfWeekBinary()
__STATIC_INLINE void DL_RTC_Common_enableAlarm2DayOfWeekBinary (RTC_Regs * rtc_common)
Enable day of the week in binary for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableAlarm2DayOfWeekBinary()
__STATIC_INLINE void DL_RTC_Common_disableAlarm2DayOfWeekBinary (RTC_Regs * rtc_common)
Disable day of the week in binary for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setAlarm2DayOfWeekBinary()
__STATIC_INLINE void DL_RTC_Common_setAlarm2DayOfWeekBinary (RTC_Regs * rtc_common, uint8_t day)
Set the day of the week in binary for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] day Value for the day of the week of the RTC Common calendar Valid values are 0-6
References DL_Common_updateReg().
DL_RTC_Common_getAlarm2DayOfWeekBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm2DayOfWeekBinary (const RTC_Regs * rtc_common)
Get the day of the week in binary for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The day of the week in the RTC Common calendar
Return values
Value in range: 0-6
DL_RTC_Common_enableAlarm2DayOfMonthBinary()
__STATIC_INLINE void DL_RTC_Common_enableAlarm2DayOfMonthBinary (RTC_Regs * rtc_common)
Enable day of the month in binary for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_disableAlarm2DayOfMonthBinary()
__STATIC_INLINE void DL_RTC_Common_disableAlarm2DayOfMonthBinary (RTC_Regs * rtc_common)
Disable day of the month in binary for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_setAlarm2DayOfMonthBinary()
__STATIC_INLINE void DL_RTC_Common_setAlarm2DayOfMonthBinary (RTC_Regs * rtc_common, uint8_t day)
Set the day of the month in binary for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] day Value for the day of the month of the RTC Common calendar Valid values are 1-31
References DL_Common_updateReg().
DL_RTC_Common_getAlarm2DayOfMonthBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getAlarm2DayOfMonthBinary (const RTC_Regs * rtc_common)
Get the day of the month in binary for RTC Common Calendar Alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The day of the month in the RTC Common calendar
Return values
Value in range: 1-31
DL_RTC_Common_setPrescalerEvents()
__STATIC_INLINE void DL_RTC_Common_setPrescalerEvents (RTC_Regs * rtc_common, DL_RTC_COMMON_PRESCALER0_DIVIDE prescaler0Divider, DL_RTC_COMMON_PRESCALER1_DIVIDE prescaler1Divider, DL_RTC_COMMON_PRESCALER2_DIVIDE prescaler2Divider)
Set prescale interrupt interval for timer 0, 1, and 2.
Set prescale timer interrupt interval to DL_RTC_COMMON_PRESCALE_NONE to keep the timer disabled.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] prescaler0Divider Value to set for prescaler 0 interrupt interval One of DL_RTC_COMMON_PRESCALER0_DIVIDE
[in] prescaler1Divider Value to set for prescaler 1 interrupt interval One of DL_RTC_COMMON_PRESCALER1_DIVIDE
[in] prescaler2Divider Value to set for prescaler 2 interrupt interval. One of DL_RTC_COMMON_PRESCALER2_DIVIDE
DL_RTC_Common_setPeriodicAlarm0()
__STATIC_INLINE void DL_RTC_Common_setPeriodicAlarm0 (RTC_Regs * rtc_common, DL_RTC_COMMON_PRESCALER0_DIVIDE prescaler0Divider)
Set periodic alarm 0.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] prescaler0Divider Value to set for prescaler 0 interrupt interval. One of DL_RTC_COMMON_PRESCALER0_DIVIDE
References DL_Common_updateReg().
DL_RTC_Common_setPeriodicAlarm1()
__STATIC_INLINE void DL_RTC_Common_setPeriodicAlarm1 (RTC_Regs * rtc_common, DL_RTC_COMMON_PRESCALER1_DIVIDE prescaler1Divider)
Set periodic alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] prescaler1Divider Value to set for prescaler 1 interrupt interval. One of DL_RTC_COMMON_PRESCALER1_DIVIDE
References DL_Common_updateReg().
DL_RTC_Common_setPeriodicAlarm2()
__STATIC_INLINE void DL_RTC_Common_setPeriodicAlarm2 (RTC_Regs * rtc_common, DL_RTC_COMMON_PRESCALER2_DIVIDE prescaler2Divider)
Set periodic alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] prescaler2Divider Value to set for prescaler 2 interrupt interval. One of DL_RTC_COMMON_PRESCALER2_DIVIDE
References DL_Common_updateReg().
DL_RTC_Common_getPrescaler0()
__STATIC_INLINE DL_RTC_COMMON_PRESCALER0_DIVIDE DL_RTC_Common_getPrescaler0 (const RTC_Regs * rtc_common)
Get prescaler 0 interrupt interval.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
Value for prescaler 0 interrupt interval
Return values
One of DL_RTC_COMMON_PRESCALER0_DIVIDE
DL_RTC_Common_getPrescaler1()
__STATIC_INLINE DL_RTC_COMMON_PRESCALER1_DIVIDE DL_RTC_Common_getPrescaler1 (const RTC_Regs * rtc_common)
Get prescaler 1 interrupt interval.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
Value for prescaler 1 interrupt interval
Return values
One of DL_RTC_COMMON_PRESCALER1_DIVIDE
DL_RTC_Common_getPrescaler2()
__STATIC_INLINE DL_RTC_COMMON_PRESCALER2_DIVIDE DL_RTC_Common_getPrescaler2 (const RTC_Regs * rtc_common)
Get prescaler 2 interrupt interval.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
Value for prescaler 2 interrupt interval
Return values
One of DL_RTC_COMMON_PRESCALER2_DIVIDE
DL_RTC_Common_getTimeStampSecondsBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampSecondsBCD (const RTC_Regs * rtc_common)
Get the seconds in BCD in the time stamp.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The seconds in the time stamp
Return values
Value in range: 0x0-0x59
DL_RTC_Common_getTimeStampMinutesBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampMinutesBCD (const RTC_Regs * rtc_common)
Get the minutes in BCD in the time stamp.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The minutes in the time stamp
Return values
Value in range: 0x0-0x59
DL_RTC_Common_getTimeStampHoursBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampHoursBCD (const RTC_Regs * rtc_common)
Get the hours in BCD in the time stamp.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The hours in the time stamp
Return values
Value in range: 0x0-0x23
DL_RTC_Common_getTimeStampDayOfWeekBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampDayOfWeekBCD (const RTC_Regs * rtc_common)
Get the day of the week in BCD in the time stamp.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The day of the week in the time stamp
Return values
Value in range: 0x0-0x6
DL_RTC_Common_getTimeStampDayOfMonthBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampDayOfMonthBCD (const RTC_Regs * rtc_common)
Get the day of the month in BCD in the time stamp.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The day of the month in the time stamp
Return values
Value in range: 0x1-0x31
DL_RTC_Common_getTimeStampMonthBCD()
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampMonthBCD (const RTC_Regs * rtc_common)
Get the month of the year in BCD in the time stamp.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The month of the year in the time stamp
Return values
Value in range: 0x1-0x12
DL_RTC_Common_getTimeStampYearBCD()
__STATIC_INLINE uint16_t DL_RTC_Common_getTimeStampYearBCD (const RTC_Regs * rtc_common)
Get the year in BCD in the time stamp.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The year in the time stamp
Return values
Value in range: 0x0-0x4095
DL_RTC_Common_getTimeStampSecondsBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampSecondsBinary (const RTC_Regs * rtc_common)
Get the seconds in binary in the time stamp.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The seconds in the time stamp
Return values
Value in range: 0-59
DL_RTC_Common_getTimeStampMinutesBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampMinutesBinary (const RTC_Regs * rtc_common)
Get the minutes in binary in the time stamp.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The minutes in the time stamp
Return values
Value in range: 0-59
DL_RTC_Common_getTimeStampHoursBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampHoursBinary (const RTC_Regs * rtc_common)
Get the hours in binary in the time stamp.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The hours in the time stamp
Return values
Value in range: 0-23
DL_RTC_Common_getTimeStampDayOfWeekBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampDayOfWeekBinary (const RTC_Regs * rtc_common)
Get the day of the week in binary in the time stamp.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The day of the week in the time stamp
Return values
Value in range: 0-6
DL_RTC_Common_getTimeStampDayOfMonthBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampDayOfMonthBinary (const RTC_Regs * rtc_common)
Get the day of the month in binary in the time stamp.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The day of the month in the time stamp
Return values
Value in range: 1-31
DL_RTC_Common_getTimeStampMonthBinary()
__STATIC_INLINE uint8_t DL_RTC_Common_getTimeStampMonthBinary (const RTC_Regs * rtc_common)
Get the month of the year in binary in the time stamp.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The month of the year in the time stamp
Return values
Value in range: 1-12
DL_RTC_Common_getTimeStampYearBinary()
__STATIC_INLINE uint16_t DL_RTC_Common_getTimeStampYearBinary (const RTC_Regs * rtc_common)
Get the year in binary in the time stamp.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_Common_isSafeToRead to ensure that the registers are safe to read.
Returns
The year in the time stamp
Return values
Value in range: 0-4095
DL_RTC_Common_enableInterrupt()
__STATIC_INLINE void DL_RTC_Common_enableInterrupt (RTC_Regs * rtc_common, uint32_t interruptMask)
Enable RTC Common interrupts.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] interruptMask Bit mask of interrupts to enable. Logical OR of DL_RTC_COMMON_INTERRUPT.
DL_RTC_Common_disableInterrupt()
__STATIC_INLINE void DL_RTC_Common_disableInterrupt (RTC_Regs * rtc_common, uint32_t interruptMask)
Disable RTC Common interrupts.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] interruptMask Bit mask of interrupts to enable. Logical OR of DL_RTC_COMMON_INTERRUPT
DL_RTC_Common_getEnabledInterrupts()
__STATIC_INLINE uint32_t DL_RTC_Common_getEnabledInterrupts (const RTC_Regs * rtc_common, uint32_t interruptMask)
Check which RTC Common interrupts are enabled.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] interruptMask Bit mask of interrupts to check. Logical OR of DL_RTC_COMMON_INTERRUPT
Returns
Which of the requested RTC Common interrupts are enabled
Return values
Logical OR of DL_RTC_COMMON_INTERRUPT values
DL_RTC_Common_getEnabledInterruptStatus()
__STATIC_INLINE uint32_t DL_RTC_Common_getEnabledInterruptStatus (const RTC_Regs * rtc_common, uint32_t interruptMask)
Check interrupt flag of enabled RTC Common interrupts.
Checks if any of the RTC Common interrupts that were previously enabled are pending.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] interruptMask Bit mask of interrupts to check. Logical OR of DL_RTC_COMMON_INTERRUPT
Returns
Which of the requested RTC Common interrupts are pending
Return values
Logical OR of DL_RTC_COMMON_INTERRUPT values
See also
DL_RTC_COMMON_enableInterrupt
DL_RTC_Common_getRawInterruptStatus()
__STATIC_INLINE uint32_t DL_RTC_Common_getRawInterruptStatus (const RTC_Regs * rtc_common, uint32_t interruptMask)
Check interrupt flag of any RTC Common interrupt.
Checks if any of the RTC Common interrupts are pending. Interrupts do not have to be previously enabled.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] interruptMask Bit mask of interrupts to check. Logical OR of DL_RTC_COMMON_INTERRUPT
Returns
Which of the requested RTC Common interrupts are pending
Return values
Logical OR of DL_RTC_COMMON_INTERRUPT values
DL_RTC_Common_getPendingInterrupt()
__STATIC_INLINE DL_RTC_COMMON_IIDX DL_RTC_Common_getPendingInterrupt (const RTC_Regs * rtc_common)
Get highest priority pending RTC Common interrupt.
Checks if any of the RTC Common interrupts are pending. Interrupts do not have to be previously enabled.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The highest priority pending RTC Common interrupt
Return values
One of DL_RTC_COMMON_IIDX
DL_RTC_Common_clearInterruptStatus()
__STATIC_INLINE void DL_RTC_Common_clearInterruptStatus (RTC_Regs * rtc_common, uint32_t interruptMask)
Clear pending RTC Common interrupts.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] interruptMask Bit mask of interrupts to check. Logical OR of DL_RTC_COMMON_INTERRUPT
DL_RTC_Common_enableEvent()
__STATIC_INLINE void DL_RTC_Common_enableEvent (RTC_Regs * rtc_common, uint32_t eventMask)
Enable RTC Common event.
Parameters
[in] rtc_common Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to enable. Bitwise OR of DL_RTC_COMMON_EVENT.
DL_RTC_Common_disableEvent()
__STATIC_INLINE void DL_RTC_Common_disableEvent (RTC_Regs * rtc_common, uint32_t eventMask)
Disable RTC Common event.
Parameters
[in] rtc_common Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to enable. Bitwise OR of DL_RTC_COMMON_EVENT.
DL_RTC_Common_getEnabledEvents()
__STATIC_INLINE uint32_t DL_RTC_Common_getEnabledEvents (const RTC_Regs * rtc_common, uint32_t eventMask)
Check which RTC Common events are enabled.
Parameters
[in] rtc_common Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to check. Bitwise OR of DL_RTC_COMMON_EVENT.
Returns
Which of the requested RTC Common interrupts are enabled
Return values
Bitwise OR of DL_RTC_COMMON_EVENT values
DL_RTC_Common_getEnabledEventStatus()
__STATIC_INLINE uint32_t DL_RTC_Common_getEnabledEventStatus (const RTC_Regs * rtc_common, uint32_t eventMask)
Check event flag of enabled RTC Common event.
Checks if any of the RTC Common events that were previously enabled are pending.
Parameters
[in] rtc_common Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to check. Bitwise OR of DL_RTC_COMMON_EVENT.
Returns
Which of the requested RTC Common interrupts are pending
Return values
Bitwise OR of DL_RTC_COMMON_EVENT values
See also
DL_RTC_COMMON_enableInterrupt
DL_RTC_Common_getRawEventsStatus()
__STATIC_INLINE uint32_t DL_RTC_Common_getRawEventsStatus (const RTC_Regs * rtc_common, uint32_t eventMask)
Check interrupt flag of any RTC Common event.
Checks if any events are pending. Events do not have to be previously enabled.
Parameters
[in] rtc_common Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to check. Bitwise OR of DL_RTC_COMMON_EVENT.
Returns
Which of the requested RTC Common interrupts are pending
Return values
Bitwise OR of DL_RTC_COMMON_EVENT values
DL_RTC_Common_clearEventsStatus()
__STATIC_INLINE void DL_RTC_Common_clearEventsStatus (RTC_Regs * rtc_common, uint32_t eventMask)
Clear pending RTC Common events.
Parameters
[in] rtc_common Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to clear. Bitwise OR of DL_RTC_COMMON_EVENT.
DL_RTC_Common_setPublisherChanID()
__STATIC_INLINE void DL_RTC_Common_setPublisherChanID (RTC_Regs * rtc_common, uint8_t chanID)
Sets the event publisher channel ID.
Parameters
[in] rtc_common Pointer to the register overlay for the peripheral
[in] chanID Channel ID number. Valid range 0-15. If ChanID == 0 publisher is disconnected.
DL_RTC_Common_getPublisherChanID()
__STATIC_INLINE uint8_t DL_RTC_Common_getPublisherChanID (const RTC_Regs * rtc_common)
Gets the event publisher channel ID.
Parameters
[in] rtc_common Pointer to the register overlay for the peripheral
Returns
Event publisher channel ID
DL_RTC_Common_getTimeStampEventCause()
__STATIC_INLINE uint32_t DL_RTC_Common_getTimeStampEventCause (const RTC_Regs * rtc_common, uint32_t tsEventMask)
Gets the cause of the time stamp event.
Parameters
[in] rtc_common Pointer to the register overlay for the peripheral
[in] tsEventMask Bit mask of events to check. Logical OR of DL_RTC_COMMON_TIME_STAMP_EVENT_CAUSE.
Returns
The cause of the time stamp event
Return values
Logical OR of DL_RTC_COMMON_TIME_STAMP_EVENT_CAUSE values
References DL_RTC_Common_disableCalendarAlarm1(), DL_RTC_Common_disableCalendarAlarm2(), DL_RTC_Common_enableCalendarAlarm1(), DL_RTC_Common_enableCalendarAlarm2(), DL_RTC_Common_getCalendarAlarm1(), DL_RTC_Common_getCalendarAlarm2(), DL_RTC_Common_getCalendarTime(), DL_RTC_Common_initCalendar(), DL_RTC_Common_setCalendarAlarm1(), and DL_RTC_Common_setCalendarAlarm2().
DL_RTC_Common_initCalendar()
void DL_RTC_Common_initCalendar (RTC_Regs * rtc_common, DL_RTC_Common_Calendar calendarTime, DL_RTC_COMMON_FORMAT formatSelect)
Initializes the settings to operate the RTC Common in Calendar mode.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] calendarTime Structure containing the values for the Calendar to be initialized to
[in] formatSelect Selectable format the RTC Common peripheral will provide time in. DL_RTC_COMMON_FORMAT
Referenced by DL_RTC_Common_getTimeStampEventCause().
DL_RTC_Common_getCalendarTime()
DL_RTC_Common_Calendar DL_RTC_Common_getCalendarTime (const RTC_Regs * rtc_common)
Returns the Calendar Time.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
This function returns the current Calendar Time in the form of a Calendar structure. The time returned will be in the previously selected format.
Returns
A Calendar structure containing the current time.
Referenced by DL_RTC_Common_getTimeStampEventCause().
DL_RTC_Common_setCalendarAlarm1()
void DL_RTC_Common_setCalendarAlarm1 (RTC_Regs * rtc_common, DL_RTC_Common_CalendarAlarm alarmTime)
Set calendar alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] alarmTime Structure containing the values for the alarm to be set to
Referenced by DL_RTC_Common_getTimeStampEventCause().
DL_RTC_Common_getCalendarAlarm1()
DL_RTC_Common_CalendarAlarm DL_RTC_Common_getCalendarAlarm1 (const RTC_Regs * rtc_common)
Get calendar alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
A Alarm structure containing the set time for alarm 1
Referenced by DL_RTC_Common_getTimeStampEventCause().
DL_RTC_Common_enableCalendarAlarm1()
void DL_RTC_Common_enableCalendarAlarm1 (RTC_Regs * rtc_common)
Enable calendar alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Referenced by DL_RTC_Common_getTimeStampEventCause().
DL_RTC_Common_disableCalendarAlarm1()
void DL_RTC_Common_disableCalendarAlarm1 (RTC_Regs * rtc_common)
Disable calendar alarm 1.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Referenced by DL_RTC_Common_getTimeStampEventCause().
DL_RTC_Common_setCalendarAlarm2()
void DL_RTC_Common_setCalendarAlarm2 (RTC_Regs * rtc_common, DL_RTC_Common_CalendarAlarm alarmTime)
Set calendar alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] alarmTime Structure containing the values for the alarm to be set to
Referenced by DL_RTC_Common_getTimeStampEventCause().
DL_RTC_Common_getCalendarAlarm2()
DL_RTC_Common_CalendarAlarm DL_RTC_Common_getCalendarAlarm2 (const RTC_Regs * rtc_common)
Get calendar alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
A Alarm structure containing the set time for alarm 2
Referenced by DL_RTC_Common_getTimeStampEventCause().
DL_RTC_Common_enableCalendarAlarm2()
void DL_RTC_Common_enableCalendarAlarm2 (RTC_Regs * rtc_common)
Enable calendar alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Referenced by DL_RTC_Common_getTimeStampEventCause().
DL_RTC_Common_disableCalendarAlarm2()
void DL_RTC_Common_disableCalendarAlarm2 (RTC_Regs * rtc_common)
Disable calendar alarm 2.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Referenced by DL_RTC_Common_getTimeStampEventCause().
DL_RTC_Common_setTimeStampEventSource()
__STATIC_INLINE void DL_RTC_Common_setTimeStampEventSource (RTC_Regs * rtc_common, uint32_t sourceMask)
Set the sources to trigger a time stamp capture event.
The timestamp event can be triggered by an edge detection of any of the tamper IO. This API sets which source(s) will trigger a time stamp capture event.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] sourceMask The sources that can trigger a time stamp capture event. Logical OR of DL_RTC_COMMON_TIME_STAMP_EVENT_SOURCE
DL_RTC_Common_getTimeStampEventSource()
__STATIC_INLINE uint32_t DL_RTC_Common_getTimeStampEventSource (const RTC_Regs * rtc_common, uint32_t sourceMask)
Get the sources that can trigger a time stamp capture event.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] sourceMask The sources that can trigger a time stamp capture event. Logical OR of DL_RTC_COMMON_TIME_STAMP_EVENT_SOURCE
Returns
The sources of the time stamp event
Return values
Logical OR of DL_RTC_COMMON_TIME_STAMP_EVENT_SOURCE values
DL_RTC_Common_setTimeStampEventCapture()
__STATIC_INLINE void DL_RTC_Common_setTimeStampEventCapture (RTC_Regs * rtc_common, DL_RTC_COMMON_TIME_STAMP_EVENT_CAPTURE capture)
Set the capture method when a time stamp capture event occurs.
The timestamp event can be triggered by an edge detection of any of the tamper IO. This API sets whether the first or last occurrence of the event is captured.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
[in] capture The capture method for the time stamp event. One of DL_RTC_COMMON_TIME_STAMP_EVENT_CAPTURE
References DL_Common_updateReg().
DL_RTC_Common_getTimeStampEventCapture()
__STATIC_INLINE DL_RTC_COMMON_TIME_STAMP_EVENT_CAPTURE DL_RTC_Common_getTimeStampEventCapture (const RTC_Regs * rtc_common)
Get the capture method when a time stamp capture event occurs.
The timestamp event can be triggered by an edge detection of any of the tamper IO. This API sets whether the first or last occurrence of the event is captured.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
The capture method for a time stamp capture event
Return values
One of DL_RTC_COMMON_TIME_STAMP_EVENT_CAPTURE
DL_RTC_Common_clearTimeStamp()
__STATIC_INLINE void DL_RTC_Common_clearTimeStamp (RTC_Regs * rtc_common)
Clear the time stamp and time stamp event status.
The time stamp and the time stamp event status are sticky, and will stay active until cleared by software.
Parameters
[in] rtc_common Pointer to the register overlay for the peripheral
DL_RTC_Common_enableWriteProtect()
__STATIC_INLINE void DL_RTC_Common_enableWriteProtect (RTC_Regs * rtc_common)
Enable write protection lock of the CLKCTL, SEC, MIN, HOUR, DAY, MON, YEAR and LFSSRST registers from accidental updates.
When enabled, the CLKCTL, SEC, MIN, HOUR, DAY, MON, YEAR and LFSSRST registers will have read-only properties.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
DL_RTC_Common_isWriteProtectEnabled()
__STATIC_INLINE bool DL_RTC_Common_isWriteProtectEnabled (const RTC_Regs * rtc_common)
Checks if write protection lock of the CLKCTL, SEC, MIN, HOUR, DAY, MON, YEAR and LFSSRST registers is enabled.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Returns
Returns the enabled status of the write protection lock
Return values
true Write protection lock is enabled
false Write protection lock is disabled
DL_RTC_Common_disableWriteProtect()
__STATIC_INLINE void DL_RTC_Common_disableWriteProtect (RTC_Regs * rtc_common)
Disable write protection lock of the CLKCTL, SEC, MIN, HOUR, DAY, MON, YEAR and LFSSRST registers.
Parameters
[in] rtc_common Pointer to the register overlay for the RTC Common peripheral
Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale