MSPM0G518xTinyUSBLibrary: CDC_DEVICE
CDC_DEVICE
Data Structures
struct TU_ATTR_PACKED
Configuration structure for CDC FIFO persistence options.
Macros
#define CFG_TUD_CDC_EP_BUFSIZE (TUD_OPT_HIGH_SPEED ? 512 : 64)
Size of CDC endpoint buffer.
Typedefs
typedef struct TU_ATTR_PACKED tud_cdc_configure_fifo_t
Configuration structure for CDC FIFO persistence options.
Functions
bool tud_cdc_configure_fifo (tud_cdc_configure_fifo_t const *cfg)
Configure CDC FIFO persistence behavior.
bool tud_cdc_n_ready (uint8_t itf)
Check if CDC interface is ready for communication.
bool tud_cdc_n_connected (uint8_t itf)
Check if terminal is connected to this CDC port.
uint8_t tud_cdc_n_get_line_state (uint8_t itf)
Get current line state for a CDC interface.
void tud_cdc_n_get_line_coding (uint8_t itf, cdc_line_coding_t *coding)
Get current line coding parameters for a CDC interface.
void tud_cdc_n_set_wanted_char (uint8_t itf, char wanted)
Set special character that will trigger a callback when received.
uint32_t tud_cdc_n_available (uint8_t itf)
Get the number of bytes available for reading.
uint32_t tud_cdc_n_read (uint8_t itf, void *buffer, uint32_t bufsize)
Read data from CDC interface receive buffer.
static TU_ATTR_ALWAYS_INLINE int32_t tud_cdc_n_read_char (uint8_t itf)
Read a single character from CDC interface.
void tud_cdc_n_read_flush (uint8_t itf)
Clear the received data FIFO buffer.
bool tud_cdc_n_peek (uint8_t itf, uint8_t *ui8)
Peek at the next byte in the receive buffer without removing it.
uint32_t tud_cdc_n_write (uint8_t itf, void const *buffer, uint32_t bufsize)
Write data to CDC interface transmit buffer.
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_n_write_char (uint8_t itf, char ch)
Write a single character to CDC interface.
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_n_write_str (uint8_t itf, char const *str)
Write a null-terminated string to CDC interface.
uint32_t tud_cdc_n_write_flush (uint8_t itf)
Force sending data if possible.
uint32_t tud_cdc_n_write_available (uint8_t itf)
Return the number of bytes available for writing to TX FIFO buffer.
bool tud_cdc_n_write_clear (uint8_t itf)
Clear the transmit FIFO buffer.
static TU_ATTR_ALWAYS_INLINE bool tud_cdc_ready (void)
Check if the default CDC interface is ready for communication.
static TU_ATTR_ALWAYS_INLINE bool tud_cdc_connected (void)
Check if terminal is connected to the default CDC port.
static TU_ATTR_ALWAYS_INLINE uint8_t tud_cdc_get_line_state (void)
Get current line state for the default CDC interface.
static TU_ATTR_ALWAYS_INLINE void tud_cdc_get_line_coding (cdc_line_coding_t *coding)
Get current line coding parameters for the default CDC interface.
static TU_ATTR_ALWAYS_INLINE void tud_cdc_set_wanted_char (char wanted)
Set special character that will trigger a callback when received.
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_available (void)
Get the number of bytes available for reading from the default CDC interface.
static TU_ATTR_ALWAYS_INLINE int32_t tud_cdc_read_char (void)
Read a single character from the default CDC interface.
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_read (void *buffer, uint32_t bufsize)
Read data from the default CDC interface.
static TU_ATTR_ALWAYS_INLINE void tud_cdc_read_flush (void)
Flush the default CDC interface's receive buffer.
static TU_ATTR_ALWAYS_INLINE bool tud_cdc_peek (uint8_t *ui8)
Peek at the next byte in the default CDC interface's receive buffer.
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_write_char (char ch)
Write a single character to the default CDC interface.
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_write (void const *buffer, uint32_t bufsize)
Write data to the default CDC interface.
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_write_str (char const *str)
Write a null-terminated string to the default CDC interface.
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_write_flush (void)
Flush the default CDC interface's transmit buffer.
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_write_available (void)
Get the available space in the default CDC interface's transmit buffer.
static TU_ATTR_ALWAYS_INLINE bool tud_cdc_write_clear (void)
Clear the default CDC interface's transmit buffer.
TU_ATTR_WEAK void tud_cdc_rx_cb (uint8_t itf)
Callback function invoked when CDC interface receives data from host.
TU_ATTR_WEAK void tud_cdc_rx_wanted_cb (uint8_t itf, char wanted_char)
Callback function invoked when a specific character is received.
TU_ATTR_WEAK void tud_cdc_tx_complete_cb (uint8_t itf)
Callback function invoked when a CDC transmit operation completes.
TU_ATTR_WEAK void tud_cdc_line_state_cb (uint8_t itf, bool dtr, bool rts)
Callback function invoked when CDC line state changes.
TU_ATTR_WEAK void tud_cdc_line_coding_cb (uint8_t itf, cdc_line_coding_t const *p_line_coding)
Callback function invoked when CDC line coding parameters change.
TU_ATTR_WEAK void tud_cdc_send_break_cb (uint8_t itf, uint16_t duration_ms)
Callback function invoked when a break signal is received.
void cdcd_init (void)
Initialize CDC device driver.
bool cdcd_deinit (void)
Deinitialize CDC device driver.
void cdcd_reset (uint8_t rhport)
Reset CDC device driver.
uint16_t cdcd_open (uint8_t rhport, tusb_desc_interface_t const *itf_desc, uint16_t max_len)
Open CDC device interface.
bool cdcd_control_xfer_cb (uint8_t rhport, uint8_t stage, tusb_control_request_t const *request)
CDC device control transfer callback.
bool cdcd_xfer_cb (uint8_t rhport, uint8_t ep_addr, xfer_result_t result, uint32_t xferred_bytes)
CDC device data transfer callback.
Detailed Description
Typedef Documentation
tud_cdc_configure_fifo_t
typedef struct TU_ATTR_PACKED tud_cdc_configure_fifo_t
Configuration structure for CDC FIFO persistence options.
This structure defines configuration options for CDC FIFO persistence across USB bus reset or disconnect events. The structure uses bit fields to minimize memory usage.
Function Documentation
tud_cdc_configure_fifo()
bool tud_cdc_configure_fifo (tud_cdc_configure_fifo_t const * cfg)
Configure CDC FIFO persistence behavior.
This function configures how the CDC FIFOs behave during USB bus reset or disconnect events. By default, FIFOs are cleared on reset/disconnect, but this behavior can be modified to maintain data integrity in certain applications.
Parameters
[in] cfg Pointer to configuration structure containing persistence options. Set rx_persistent to keep RX FIFO data on reset/disconnect. Set tx_persistent to keep TX FIFO data on reset/disconnect.
Returns
bool true if configuration was successful, false if cfg pointer is NULL
tud_cdc_n_ready()
bool tud_cdc_n_ready (uint8_t itf)
Check if CDC interface is ready for communication.
This function checks if the specified CDC interface is ready for data transfer. An interface is considered ready when the device is connected to a host, the USB stack is ready, and both IN and OUT endpoints are configured.
Parameters
[in] itf CDC interface number (zero-based)
Returns
bool true if the interface is ready for data transfer, false if not ready or not properly configured
Referenced by tud_cdc_ready().
tud_cdc_n_connected()
bool tud_cdc_n_connected (uint8_t itf)
Check if terminal is connected to this CDC port.
This function checks if a terminal client (like a serial terminal program) is connected to the specified CDC interface. The connection state is determined by checking the DTR (Data Terminal Ready) bit in the line state.
Parameters
[in] itf CDC interface number (zero-based)
Returns
bool true if a terminal is connected (DTR bit is active), false otherwise
Referenced by tud_cdc_connected().
tud_cdc_n_get_line_state()
uint8_t tud_cdc_n_get_line_state (uint8_t itf)
Get current line state for a CDC interface.
This function returns the current line state control signals for the specified CDC interface. The line state contains information about the DTR (Data Terminal Ready) and RTS (Request To Send) signals from the host.
Parameters
[in] itf CDC interface number (zero-based)
Returns
uint8_t The current line state with bit fields:
Bit 0: DTR (Data Terminal Ready) signal
Bit 1: RTS (Request To Send) signal A value of 1 indicates the signal is active
Referenced by tud_cdc_get_line_state().
tud_cdc_n_get_line_coding()
void tud_cdc_n_get_line_coding (uint8_t itf, cdc_line_coding_t * coding)
Get current line coding parameters for a CDC interface.
This function retrieves the current line coding parameters for the specified CDC interface. Line coding includes communication parameters such as baud rate, number of data bits, stop bits, and parity type.
Parameters
[in] itf CDC interface number (zero-based)
[out] coding Pointer to a cdc_line_coding_t structure where the line coding parameters will be stored
Referenced by tud_cdc_get_line_coding().
tud_cdc_n_set_wanted_char()
void tud_cdc_n_set_wanted_char (uint8_t itf, char wanted)
Set special character that will trigger a callback when received.
This function configures a specific character that, when received on the specified CDC interface, will trigger the tud_cdc_rx_wanted_cb() callback. This provides a convenient way to detect and respond to special characters in the incoming data stream without having to manually scan the received data.
Parameters
[in] itf CDC interface number (zero-based)
[in] wanted The character to detect in the incoming data stream
Referenced by tud_cdc_set_wanted_char().
tud_cdc_n_available()
uint32_t tud_cdc_n_available (uint8_t itf)
Get the number of bytes available for reading.
This function returns the number of bytes currently available in the receive buffer of the specified CDC interface. These bytes have been received from the host and are ready to be read by the application.
Parameters
[in] itf CDC interface number (zero-based)
Returns
uint32_t The number of bytes available to read from the receive buffer
Referenced by tud_cdc_available().
tud_cdc_n_read()
uint32_t tud_cdc_n_read (uint8_t itf, void * buffer, uint32_t bufsize)
Read data from CDC interface receive buffer.
This function reads data that has been received from the host on the specified CDC interface. It transfers bytes from the internal receive FIFO buffer to the provided application buffer.
Parameters
[in] itf CDC interface number (zero-based)
[out] buffer Pointer to the buffer where data will be stored
[in] bufsize Maximum number of bytes to read
Returns
uint32_t The actual number of bytes read, which may be less than requested if fewer bytes are available
Referenced by tud_cdc_n_read_char(), and tud_cdc_read().
tud_cdc_n_read_char()
static TU_ATTR_ALWAYS_INLINE int32_t tud_cdc_n_read_char (uint8_t itf) inline static
Read a single character from CDC interface.
This function reads a single byte (character) from the receive buffer of the specified CDC interface. It's a convenience function for applications that process data one character at a time.
Parameters
[in] itf CDC interface number (zero-based)
Returns
int32_t The read character (0-255) if data is available, or -1 if no data is available
References tud_cdc_n_peek(), tud_cdc_n_read(), tud_cdc_n_read_flush(), and tud_cdc_n_write().
Referenced by tud_cdc_read_char().
tud_cdc_n_read_flush()
void tud_cdc_n_read_flush (uint8_t itf)
Clear the received data FIFO buffer.
This function clears (discards) all data in the receive FIFO buffer for the specified CDC interface. It's useful when you want to ignore previously received data and start fresh.
Parameters
[in] itf CDC interface number (zero-based)
Referenced by tud_cdc_n_read_char(), and tud_cdc_read_flush().
tud_cdc_n_peek()
bool tud_cdc_n_peek (uint8_t itf, uint8_t * ui8)
Peek at the next byte in the receive buffer without removing it.
This function allows examining the next byte in the receive buffer of the specified CDC interface without actually removing it from the buffer. This is useful when you need to look ahead in the data stream without consuming the data.
Parameters
[in] itf CDC interface number (zero-based)
[out] ui8 Pointer to a byte variable where the peeked data will be stored
Returns
bool true if data was available and stored in ui8, false if no data is available
Referenced by tud_cdc_n_read_char(), and tud_cdc_peek().
tud_cdc_n_write()
uint32_t tud_cdc_n_write (uint8_t itf, void const * buffer, uint32_t bufsize)
Write data to CDC interface transmit buffer.
This function writes data to the transmit buffer of the specified CDC interface. The data will be sent to the host when the buffer is sufficiently full or when explicitly flushed.
Parameters
[in] itf CDC interface number (zero-based)
[in] buffer Pointer to the data to be written
[in] bufsize Number of bytes to write
Returns
uint32_t The number of bytes actually written to the buffer, which may be less than requested if there's not enough space in the buffer
Referenced by tud_cdc_n_read_char(), tud_cdc_n_write_char(), tud_cdc_n_write_str(), and tud_cdc_write().
tud_cdc_n_write_char()
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_n_write_char (uint8_t itf, char ch) inline static
Write a single character to CDC interface.
This function writes a single byte (character) to the transmit buffer of the specified CDC interface. It's a convenience wrapper around tud_cdc_n_write() for applications that process data one character at a time.
Parameters
[in] itf CDC interface number (zero-based)
[in] ch The character to write
Returns
uint32_t 1 if the character was written successfully, 0 if there was no space in the buffer
References tud_cdc_n_write().
Referenced by tud_cdc_write_char().
tud_cdc_n_write_str()
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_n_write_str (uint8_t itf, char const * str) inline static
Write a null-terminated string to CDC interface.
This function writes a null-terminated string to the transmit buffer of the specified CDC interface. It's a convenience wrapper around tud_cdc_n_write() for applications that need to send string data.
Parameters
[in] itf CDC interface number (zero-based)
[in] str Pointer to the null-terminated string to write
Returns
uint32_t The number of bytes written to the buffer, which may be less than the string length if there's not enough space
References tud_cdc_n_write(), tud_cdc_n_write_available(), tud_cdc_n_write_clear(), and tud_cdc_n_write_flush().
Referenced by tud_cdc_write_str().
tud_cdc_n_write_flush()
uint32_t tud_cdc_n_write_flush (uint8_t itf)
Force sending data if possible.
This function attempts to send any data currently in the transmit buffer of the specified CDC interface to the host. It initiates a USB transfer with the buffered data.
Parameters
[in] itf CDC interface number (zero-based)
Returns
uint32_t The number of bytes sent in this transfer, or 0 if no transfer was initiated (e.g., if USB is not ready or if there's no data to send)
Referenced by tud_cdc_n_write_str(), and tud_cdc_write_flush().
tud_cdc_n_write_available()
uint32_t tud_cdc_n_write_available (uint8_t itf)
Return the number of bytes available for writing to TX FIFO buffer.
This function returns the amount of free space available in the transmit FIFO buffer of the specified CDC interface. Applications can use this to determine how much data can be written in a single call to tud_cdc_n_write().
Parameters
[in] itf CDC interface number (zero-based)
Returns
uint32_t The number of bytes that can be written to the transmit buffer
Referenced by tud_cdc_n_write_str(), and tud_cdc_write_available().
tud_cdc_n_write_clear()
bool tud_cdc_n_write_clear (uint8_t itf)
Clear the transmit FIFO buffer.
This function clears (discards) all data in the transmit FIFO buffer for the specified CDC interface. It's useful when you want to abort a pending transmission and start fresh.
Parameters
[in] itf CDC interface number (zero-based)
Returns
bool true if the operation was successful, false otherwise
Referenced by tud_cdc_n_write_str(), and tud_cdc_write_clear().
tud_cdc_ready()
static TU_ATTR_ALWAYS_INLINE bool tud_cdc_ready (void) inline static
Check if the default CDC interface is ready for communication.
This function checks if the default CDC interface (interface 0) is ready for data transfer. An interface is considered ready when the device is connected to a host, the USB stack is ready, and both IN and OUT endpoints are configured.
Returns
bool true if the default CDC interface is ready for data transfer, false if not ready or not properly configured
References tud_cdc_n_ready().
tud_cdc_connected()
static TU_ATTR_ALWAYS_INLINE bool tud_cdc_connected (void) inline static
Check if terminal is connected to the default CDC port.
This function checks if a terminal client (like a serial terminal program) is connected to the default CDC interface (interface 0). The connection state is determined by checking the DTR (Data Terminal Ready) bit in the line state.
Returns
bool true if a terminal is connected (DTR bit is active), false otherwise
References tud_cdc_n_connected().
tud_cdc_get_line_state()
static TU_ATTR_ALWAYS_INLINE uint8_t tud_cdc_get_line_state (void) inline static
Get current line state for the default CDC interface.
This function returns the current line state control signals for the default CDC interface (interface 0). The line state contains information about the DTR (Data Terminal Ready) and RTS (Request To Send) signals from the host.
Returns
uint8_t The current line state with bit fields:
Bit 0: DTR (Data Terminal Ready) signal
Bit 1: RTS (Request To Send) signal A value of 1 indicates the signal is active
References tud_cdc_n_get_line_state().
tud_cdc_get_line_coding()
static TU_ATTR_ALWAYS_INLINE void tud_cdc_get_line_coding (cdc_line_coding_t * coding) inline static
Get current line coding parameters for the default CDC interface.
This function retrieves the current line coding parameters for the default CDC interface (interface 0). Line coding includes communication parameters such as baud rate, number of data bits, stop bits, and parity type.
Parameters
[out] coding Pointer to a cdc_line_coding_t structure where the line coding parameters will be stored
References tud_cdc_n_get_line_coding().
tud_cdc_set_wanted_char()
static TU_ATTR_ALWAYS_INLINE void tud_cdc_set_wanted_char (char wanted) inline static
Set special character that will trigger a callback when received.
This function configures a specific character that, when received on the default CDC interface (interface 0), will trigger the tud_cdc_rx_wanted_cb() callback. This provides a convenient way to detect and respond to special characters in the incoming data stream without having to manually scan the received data.
Parameters
[in] wanted The character to detect in the incoming data stream
References tud_cdc_n_set_wanted_char().
tud_cdc_available()
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_available (void) inline static
Get the number of bytes available for reading from the default CDC interface.
This function returns the number of bytes currently available in the receive buffer of the default CDC interface (interface 0). These bytes have been received from the host and are ready to be read by the application.
Returns
uint32_t The number of bytes available to read from the receive buffer
References tud_cdc_n_available().
tud_cdc_read_char()
static TU_ATTR_ALWAYS_INLINE int32_t tud_cdc_read_char (void) inline static
Read a single character from the default CDC interface.
This function reads a single byte (character) from the receive buffer of the default CDC interface (interface 0). It's a convenience function for applications that process data one character at a time.
Returns
int32_t The read character (0-255) if data is available, or -1 if no data is available
References tud_cdc_n_read_char().
tud_cdc_read()
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_read (void * buffer, uint32_t bufsize) inline static
Read data from the default CDC interface.
This function reads data from the receive buffer of the default CDC interface (interface 0). It transfers up to 'bufsize' bytes from the CDC receive FIFO into the provided buffer.
Parameters
[out] buffer Pointer to the buffer where read data will be stored
[in] bufsize Maximum number of bytes to read
Returns
uint32_t The number of bytes actually read from the receive buffer
References tud_cdc_n_read().
tud_cdc_read_flush()
static TU_ATTR_ALWAYS_INLINE void tud_cdc_read_flush (void) inline static
Flush the default CDC interface's receive buffer.
This function discards all data in the receive buffer of the default CDC interface (interface 0).
Returns
bool true if successful, false otherwise
References tud_cdc_n_read_flush().
tud_cdc_peek()
static TU_ATTR_ALWAYS_INLINE bool tud_cdc_peek (uint8_t * ui8) inline static
Peek at the next byte in the default CDC interface's receive buffer.
This function looks at the next byte in the receive buffer of the default CDC interface (interface 0) without removing it from the buffer.
Parameters
[out] ui8 Pointer to store the peeked character
Returns
bool true if a character was successfully peeked, false if the buffer is empty
References tud_cdc_n_peek().
tud_cdc_write_char()
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_write_char (char ch) inline static
Write a single character to the default CDC interface.
This function writes a single character to the transmit buffer of the default CDC interface (interface 0).
Parameters
[in] ch The character to write
Returns
uint32_t 1 if character was successfully written, 0 if the buffer is full
References tud_cdc_n_write_char().
tud_cdc_write()
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_write (void const * buffer, uint32_t bufsize) inline static
Write data to the default CDC interface.
This function writes data to the transmit buffer of the default CDC interface (interface 0). It transfers up to 'bufsize' bytes from the provided buffer into the CDC transmit FIFO.
Parameters
[in] buffer Pointer to the data to be written
[in] bufsize Number of bytes to write
Returns
uint32_t The number of bytes actually written to the transmit buffer
References tud_cdc_n_write().
tud_cdc_write_str()
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_write_str (char const * str) inline static
Write a null-terminated string to the default CDC interface.
This function writes a null-terminated string to the transmit buffer of the default CDC interface (interface 0). It calls tud_cdc_n_write_str with interface ID 0.
Parameters
[in] str Pointer to the null-terminated string to be written
Returns
uint32_t The number of bytes written to the transmit buffer
References tud_cdc_n_write_str().
tud_cdc_write_flush()
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_write_flush (void) inline static
Flush the default CDC interface's transmit buffer.
This function attempts to send all buffered data in the transmit buffer of the default CDC interface (interface 0) to the host. It ensures that any pending data is actually transmitted.
Returns
bool true if successful, false otherwise
References tud_cdc_n_write_flush().
tud_cdc_write_available()
static TU_ATTR_ALWAYS_INLINE uint32_t tud_cdc_write_available (void) inline static
Get the available space in the default CDC interface's transmit buffer.
This function returns the number of bytes that can be written to the transmit buffer of the default CDC interface (interface 0) without overflowing.
Returns
uint32_t The number of bytes available in the transmit buffer
References tud_cdc_n_write_available().
tud_cdc_write_clear()
static TU_ATTR_ALWAYS_INLINE bool tud_cdc_write_clear (void) inline static
Clear the default CDC interface's transmit buffer.
This function discards all data in the transmit buffer of the default CDC interface (interface 0). Any pending data waiting to be sent will be lost.
Returns
bool true if successful, false otherwise
References cdcd_control_xfer_cb(), cdcd_deinit(), cdcd_init(), cdcd_open(), cdcd_reset(), cdcd_xfer_cb(), tud_cdc_line_coding_cb(), tud_cdc_line_state_cb(), tud_cdc_n_write_clear(), tud_cdc_rx_cb(), tud_cdc_rx_wanted_cb(), tud_cdc_send_break_cb(), and tud_cdc_tx_complete_cb().
tud_cdc_rx_cb()
TU_ATTR_WEAK void tud_cdc_rx_cb (uint8_t itf)
Callback function invoked when CDC interface receives data from host.
This callback is called when new data has been received from the USB host on the specified CDC interface. Application code should implement this function to process the received data. The received data can be retrieved using the tud_cdc_read() or tud_cdc_n_read() functions.
Parameters
[in] itf CDC interface number on which data was received
Referenced by tud_cdc_write_clear().
tud_cdc_rx_wanted_cb()
TU_ATTR_WEAK void tud_cdc_rx_wanted_cb (uint8_t itf, char wanted_char)
Callback function invoked when a specific character is received.
This callback is triggered when the character previously set by tud_cdc_set_wanted_char() is received on the specified CDC interface. This provides an efficient way to detect special characters in the incoming data stream without having to manually scan all received data.
Parameters
[in] itf CDC interface number on which the character was received
[in] wanted_char The specific character that was detected in the data stream
Referenced by tud_cdc_write_clear().
tud_cdc_tx_complete_cb()
TU_ATTR_WEAK void tud_cdc_tx_complete_cb (uint8_t itf)
Callback function invoked when a CDC transmit operation completes.
This callback is triggered when all pending data in the CDC transmit buffer has been successfully sent to the USB host. It can be used to implement flow control or to initiate the next data transmission.
Parameters
[in] itf CDC interface number on which the transmission completed
Referenced by tud_cdc_write_clear().
tud_cdc_line_state_cb()
TU_ATTR_WEAK void tud_cdc_line_state_cb (uint8_t itf, bool dtr, bool rts)
Callback function invoked when CDC line state changes.
This callback is triggered when the USB host changes the CDC line state, specifically the DTR (Data Terminal Ready) and RTS (Request To Send) signals. It can be used to detect when a terminal program connects or disconnects from the CDC interface.
Parameters
[in] itf CDC interface number
[in] dtr True if Data Terminal Ready (DTR) is active
[in] rts True if Request To Send (RTS) is active
Referenced by tud_cdc_write_clear().
tud_cdc_line_coding_cb()
TU_ATTR_WEAK void tud_cdc_line_coding_cb (uint8_t itf, cdc_line_coding_t const * p_line_coding)
Callback function invoked when CDC line coding parameters change.
This callback is triggered when the USB host changes the line coding parameters such as baud rate, data bits, parity, and stop bits. It allows the device to respond to these configuration changes.
Parameters
[in] itf CDC interface number
[in] p_line_coding Pointer to the new line coding parameters structure (cdc_line_coding_t)
Referenced by tud_cdc_write_clear().
tud_cdc_send_break_cb()
TU_ATTR_WEAK void tud_cdc_send_break_cb (uint8_t itf, uint16_t duration_ms)
Callback function invoked when a break signal is received.
This callback is triggered when the USB host sends a break signal through the CDC interface. The duration parameter indicates the length of the break signal in milliseconds.
Parameters
[in] itf CDC interface number
[in] duration_ms Duration of the break signal in milliseconds
Referenced by tud_cdc_write_clear().
cdcd_init()
void cdcd_init (void)
Initialize CDC device driver.
This internal function initializes the CDC device driver data structures and buffers. It's called during the USB device stack initialization process and should not be called directly by applications.
The function:
Clears CDC interface structures
Sets default line coding parameters (115200 baud, 8N1)
Configures RX and TX FIFOs with appropriate buffer sizes
Sets up mutex protection for the FIFOs if OSAL_MUTEX_REQUIRED is enabled
Referenced by tud_cdc_write_clear().
cdcd_deinit()
bool cdcd_deinit (void)
Deinitialize CDC device driver.
This internal function deinitializes the CDC device driver, releasing any resources that were allocated during initialization. It's called during the USB device stack deinitialization process and should not be called directly by applications.
The function:
Releases any allocated buffers
Clears CDC interface state information
Destroys mutex protection for the FIFOs if OSAL_MUTEX_REQUIRED is enabled
Returns
bool true if deinitialization was successful, false otherwise
Referenced by tud_cdc_write_clear().
cdcd_reset()
void cdcd_reset (uint8_t rhport)
Reset CDC device driver.
This internal function resets the CDC device driver to its initial state. It's called when a USB bus reset occurs or when the device is disconnected. The function resets all CDC interfaces to their default states without deallocating resources.
Parameters
[in] rhport USB root hub port where the device is connected
Referenced by tud_cdc_write_clear().
cdcd_open()
uint16_t cdcd_open (uint8_t rhport, tusb_desc_interface_t const * itf_desc, uint16_t max_len)
Open CDC device interface.
This internal function is called when a CDC interface is opened by the USB host. It prepares the specified CDC interface for operation by initializing its state and preparing the data structures needed for communication.
Parameters
[in] rhport USB root hub port where the device is connected
[in] itf_desc Interface descriptor
[in] max_len Maximum length of the descriptor that can be processed
Returns
uint16_t Number of bytes processed from the descriptor, or 0 if the descriptor cannot be processed
Referenced by tud_cdc_write_clear().
cdcd_control_xfer_cb()
bool cdcd_control_xfer_cb (uint8_t rhport, uint8_t stage, tusb_control_request_t const * request)
CDC device control transfer callback.
This internal function handles USB control transfers specific to CDC interfaces. It processes CDC-specific requests such as SET_LINE_CODING, GET_LINE_CODING, SET_CONTROL_LINE_STATE, and SEND_BREAK.
Parameters
[in] rhport USB root hub port where the device is connected
[in] stage Current stage of the control transfer (setup, data, ack)
[in,out] request USB setup packet containing the control request
Returns
bool true if the control request was handled, false otherwise
Referenced by tud_cdc_write_clear().
cdcd_xfer_cb()
bool cdcd_xfer_cb (uint8_t rhport, uint8_t ep_addr, xfer_result_t result, uint32_t xferred_bytes)
CDC device data transfer callback.
This internal function is called when a data transfer on a CDC endpoint completes. It handles both IN and OUT endpoint transfers, updating the appropriate FIFOs and invoking user callbacks when necessary.
Parameters
[in] rhport USB root hub port where the device is connected
[in] ep_addr Endpoint address (including direction bit)
[in] result Result of the transfer operation
[in] xferred_bytes Number of bytes transferred
Returns
bool true if the transfer was handled successfully, false otherwise
Referenced by tud_cdc_write_clear().
Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale