MSPM0G1507HallSensoredTrapMotorControlLibrary: Motor Driver/DRV8323
Motor Driver/DRV8323
Data Structures
struct DRV8323_Instance
Defines drv8323 instance.
Macros
#define DRV8323_MAXIMUM_WAKEUP_TIME (2000)
Defines the time to wakeup the drv after reset.
#define DRV8323_VOLTAGE_CONV_CONST _IQ20(17.433)
Defines voltage conversion constant.
#define DRV8323_CSA_REF_VOLTAGE (3300)
Defines CSA reference voltage.
#define DRV8323_CSAGAIN_5_IQ _IQ20(5)
Defines CSA gains 5 in IQ20.
#define DRV8323_CSAGAIN_10_IQ _IQ20(10)
Defines CSA gains 10 in IQ20.
#define DRV8323_CSAGAIN_20_IQ _IQ20(20)
Defines CSA gains 20 in IQ20.
#define DRV8323_CSAGAIN_40_IQ _IQ20(40)
Defines CSA gains 40 in IQ20.
Enumerations
enum DRV8323_CSAGAIN {
DRV8323_CSAGAIN_5 = 0 << 0,
DRV8323_CSAGAIN_10 = 1 << 0,
DRV8323_CSAGAIN_20 = 2 << 0,
DRV8323_CSAGAIN_40 = 3 << 0
}
enum DRV8323_DRVOFF_PIN_STAT {
DRV8323_DRVOFF_PIN_LOW = HAL_GPIO_PIN_LOW,
DRV8323_DRVOFF_PIN_HIGH = HAL_GPIO_PIN_HIGH
}
enum DRV8323_DRV_NSLEEP_STAT {
DRV8323_DRV_NSLEEP_SLEEP = HAL_GPIO_PIN_LOW,
DRV8323_DRV_NSLEEP_AWAKE = HAL_GPIO_PIN_HIGH
}
Represents NSLEEP Pin State.
Functions
__STATIC_INLINE void DRV8323_setnSleep (DRV8323_Instance *drvHandle, DRV8323_DRV_NSLEEP_STAT value)
set nSleep
__STATIC_INLINE _iq20 DRV8323_getcsaVref (uint16_t vRef)
get Current reference in IQ20
void DRV8323_init (DRV8323_Instance *drvHandle)
initialize the drv8323 module
void DRV8323_enable (DRV8323_Instance *drvHandle)
Enable DRV.
void DRV8323_updateCSAScaleFactor (DRV8323_Instance *drvHandle, DRV8323_CSAGAIN csa, uint16_t rSense)
updates the current gain scale factor
_iq20 DRV8323_getVoltage (HAL_ADC_CHAN chan)
Get voltage from adc channel.
_iq20 DRV8323_getCurrent (HAL_ADC_CHAN chan, DRV8323_Instance *drvHandle, _iq20 vRef)
Get current from adc channel.
void DRV8323_ADCVRefSel (HAL_ADC_VREF adcRef, HAL_ADC_CHAN chan, HAL_ADC_INT_VREF internalVRef, uint16_t externalVRef)
updates the adc voltage reference
Detailed Description
Enumeration Type Documentation
DRV8323_CSAGAIN
enum DRV8323_CSAGAIN
Enumerator
DRV8323_CSAGAIN_5
Define DRV8323 CSA GAIN 5 Setting.
DRV8323_CSAGAIN_10
Define DRV8323 CSA GAIN 10 Setting.
DRV8323_CSAGAIN_20
Define DRV8323 CSA GAIN 20 Setting.
DRV8323_CSAGAIN_40
Define DRV8323 CSA GAIN 40 Setting.
DRV8323_DRVOFF_PIN_STAT
enum DRV8323_DRVOFF_PIN_STAT
Enumerator
DRV8323_DRVOFF_PIN_LOW
Define DRVOFF PIN LOW
DRV8323_DRVOFF_PIN_HIGH
Define DRVOFF PIN HIGH
DRV8323_DRV_NSLEEP_STAT
enum DRV8323_DRV_NSLEEP_STAT
Represents NSLEEP Pin State.
Enumerator
DRV8323_DRV_NSLEEP_SLEEP
Define NSLEEP PIN LOW.
DRV8323_DRV_NSLEEP_AWAKE
Define NSLEEP PIN HIGH.
Function Documentation
DRV8323_setnSleep()
__STATIC_INLINE void DRV8323_setnSleep (DRV8323_Instance * drvHandle, DRV8323_DRV_NSLEEP_STAT value)
set nSleep
Parameters
[in] drvHandle The drv instance
[in] value nSleep value
References DRV8323_DRV_NSLEEP_AWAKE, DRV8323_DRV_NSLEEP_SLEEP, DRV8323_MAXIMUM_WAKEUP_TIME, HAL_delayMicroSeconds(), HAL_GPIO_PIN_HIGH, HAL_GPIO_PIN_LOW, HAL_writeGPIOPin(), and DRV8323_Instance::nsleep.
Referenced by DRV8323_enable().
DRV8323_getcsaVref()
__STATIC_INLINE _iq20 DRV8323_getcsaVref (uint16_t vRef)
get Current reference in IQ20
Parameters
[in] vRef CSA reference voltage in milli volts
Returns
_iq20 CSA reference voltage in _iq20 format
References DRV8323_ADCVRefSel(), DRV8323_enable(), DRV8323_getCurrent(), DRV8323_getVoltage(), DRV8323_init(), and DRV8323_updateCSAScaleFactor().
DRV8323_init()
void DRV8323_init (DRV8323_Instance * drvHandle)
initialize the drv8323 module
Parameters
[in] drvHandle The drv8323 instance
References HAL_enableADCInterrupt(), DRV8323_Instance::IsenA, DRV8323_Instance::IsenB, DRV8323_Instance::IsenC, DRV8323_Instance::Vsen, DRV8323_Instance::VsenA, DRV8323_Instance::VsenB, and DRV8323_Instance::VsenC.
Referenced by DRV8323_getcsaVref().
DRV8323_enable()
void DRV8323_enable (DRV8323_Instance * drvHandle)
Enable DRV.
Parameters
[in] drvHandle The drv8323 instance
References DRV8323_DRV_NSLEEP_AWAKE, DRV8323_DRV_NSLEEP_SLEEP, and DRV8323_setnSleep().
Referenced by DRV8323_getcsaVref().
DRV8323_updateCSAScaleFactor()
void DRV8323_updateCSAScaleFactor (DRV8323_Instance * drvHandle, DRV8323_CSAGAIN csa, uint16_t rSense)
updates the current gain scale factor
Parameters
[in] drvHandle The drv8323 instance
[in] csa drv8323 CSA gain value
[in] rSense shunt resistance
References DRV8323_Instance::csa_sf, DRV8323_CSAGAIN_10, DRV8323_CSAGAIN_10_IQ, DRV8323_CSAGAIN_20, DRV8323_CSAGAIN_20_IQ, DRV8323_CSAGAIN_40, DRV8323_CSAGAIN_40_IQ, DRV8323_CSAGAIN_5, and DRV8323_CSAGAIN_5_IQ.
Referenced by DRV8323_getcsaVref().
DRV8323_getVoltage()
_iq20 DRV8323_getVoltage (HAL_ADC_CHAN chan)
Get voltage from adc channel.
Parameters
[in] chan The ADC channel name
Returns
Return
References DRV8323_VOLTAGE_CONV_CONST, and HAL_getIQ20VoltageFromADC().
Referenced by DRV8323_getcsaVref().
DRV8323_getCurrent()
_iq20 DRV8323_getCurrent (HAL_ADC_CHAN chan, DRV8323_Instance * drvHandle, _iq20 vRef)
Get current from adc channel.
Parameters
[in] chan The ADC channel name
[in] drvHandle The drv instance
[in] vRef voltage reference for current
Returns
Return
References DRV8323_Instance::csa_sf, and HAL_getIQ20VoltageFromADC().
Referenced by DRV8323_getcsaVref().
DRV8323_ADCVRefSel()
void DRV8323_ADCVRefSel (HAL_ADC_VREF adcRef, HAL_ADC_CHAN chan, HAL_ADC_INT_VREF internalVRef, uint16_t externalVRef)
updates the adc voltage reference
Parameters
[in] adcRef ADC voltage reference
[in] chan The ADC channel name
[in] internalVRef Internal reference voltage
[in] externalVRef External reference voltage
References HAL_ADC_VREF_EXTERNAL, HAL_ADC_VREF_INTERNAL, HAL_ADC_VREF_VDDA, HAL_setADCVRefExternal(), HAL_setADCVRefInternal(), and HAL_setADCVRefVDDA().
Referenced by DRV8323_getcsaVref().
© Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale