MSPM0G1507HallSensoredTrapMotorControlLibrary: Motor Driver/DRV8300
Motor Driver/DRV8300
Data Structures
struct DRV8300_Instance
Defines DRV8300 instance.
Macros
#define DRV8300_VOLTAGE_CONV_CONST _IQ20(33.425)
Defines voltage conversion constant.
#define DRV8300_CSA_REF_VOLTAGE (3300)
Defines CSA reference voltage.
Functions
void DRV8300_init (DRV8300_Instance *drvHandle)
initialize the drv8300 module
void DRV8300_enable (DRV8300_Instance *drvHandle)
Enable DRV.
void DRV8300_updateCSAScaleFactor (DRV8300_Instance *drvHandle, uint16_t csa)
updates the current gain scale factor
_iq20 DRV8300_getVoltage (HAL_ADC_CHAN chan)
Get voltage from adc channel.
_iq20 DRV8300_getCurrent (HAL_ADC_CHAN chan, DRV8300_Instance *drvHandle, _iq20 vRef)
Get current from adc channel.
void DRV8300_ADCVRefSel (HAL_ADC_VREF adcRef, HAL_ADC_CHAN chan, HAL_ADC_INT_VREF internalVRef, uint16_t externalVRef)
updates the adc voltage reference
__STATIC_INLINE _iq20 DRV8300_getcsaVref (uint16_t vRef)
get Current reference in IQ20
Detailed Description
Function Documentation
DRV8300_init()
void DRV8300_init (DRV8300_Instance * drvHandle)
initialize the drv8300 module
Parameters
[in] drvHandle The drv instance
References HAL_enableADCInterrupt(), DRV8300_Instance::IsenA, DRV8300_Instance::IsenB, DRV8300_Instance::IsenC, DRV8300_Instance::Vsen, DRV8300_Instance::VsenA, DRV8300_Instance::VsenB, and DRV8300_Instance::VsenC.
DRV8300_enable()
void DRV8300_enable (DRV8300_Instance * drvHandle)
Enable DRV.
Parameters
[in] drvHandle The drv instance
DRV8300_updateCSAScaleFactor()
void DRV8300_updateCSAScaleFactor (DRV8300_Instance * drvHandle, uint16_t csa)
updates the current gain scale factor
Parameters
[in] drvHandle The drv instance
[in] csa DRV8300 CSA gain value
References DRV8300_Instance::csa_sf.
DRV8300_getVoltage()
_iq20 DRV8300_getVoltage (HAL_ADC_CHAN chan)
Get voltage from adc channel.
Parameters
[in] chan The ADC channel name
Returns
Return
References DRV8300_VOLTAGE_CONV_CONST, and HAL_getIQ20VoltageFromADC().
DRV8300_getCurrent()
_iq20 DRV8300_getCurrent (HAL_ADC_CHAN chan, DRV8300_Instance * drvHandle, _iq20 vRef)
Get current from adc channel.
Parameters
[in] chan The ADC channel name
[in] drvHandle The drv instance
[in] vRef voltage reference for current
Returns
Return
References DRV8300_Instance::csa_sf, and HAL_getIQ20VoltageFromADC().
DRV8300_ADCVRefSel()
void DRV8300_ADCVRefSel (HAL_ADC_VREF adcRef, HAL_ADC_CHAN chan, HAL_ADC_INT_VREF internalVRef, uint16_t externalVRef)
updates the adc voltage reference
Parameters
[in] adcRef ADC voltage reference
[in] chan ADC channel name
[in] internalVRef Internal reference voltage
[in] externalVRef External reference voltage
References HAL_ADC_VREF_EXTERNAL, HAL_ADC_VREF_INTERNAL, HAL_ADC_VREF_VDDA, HAL_setADCVRefExternal(), HAL_setADCVRefInternal(), and HAL_setADCVRefVDDA().
DRV8300_getcsaVref()
__STATIC_INLINE _iq20 DRV8300_getcsaVref (uint16_t vRef)
get Current reference in IQ20
Parameters
[in] vRef CSA reference voltage in milli volts
Returns
_iq20 CSA reference voltage in _iq20 format
© Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale