StepperMotorControlLibrary: Motor_Driver/DRV8411A
Motor_Driver/DRV8411A
Data Structures
struct DRV8411A_Instance
Define drv8411a structure.
Macros
#define DRV8411A_A_IPROPI (200)
value of AIropoi in uA/A
#define DRV8411A_MAX_SET_FREQ (80000)
Max Timer frequency limit.
Enumerations
enum DRV8411A_DIR {
DRV8411A_DIR_FORWARD = 0,
DRV8411A_DIR_REVERSE
}
enum DRV8411A_STEP {
DRV8411A_STEP_FULL_STEP = 0,
DRV8411A_STEP_HALF_STEP_NC,
DRV8411A_STEP_MAX
}
enum DRV8411A_DECAY {
DRV8411A_DECAY_SLOW = 0,
DRV8411A_DECAY_FAST
}
enum DRV8411A_CONTROL_MODE {
DRV8411A_CONTROL_MODE_SPIN = 0,
DRV8411A_CONTROL_MODE_STEP
}
enum DRV8411A_DRIVE {
DRV8411A_DRIVE_DISABLED =0,
DRV8411A_DRIVE_ENABLED
}
Functions
__STATIC_INLINE void DRV8411A_init (DRV8411A_Instance *handle)
Enables the necessary interrupts.
void DRV8411A_enableDrive (DRV8411A_Instance *handle)
Enables the drive.
void DRV8411A_disableDrive (DRV8411A_Instance *handle)
Disables the drive.
void DRV8411A_startMotor (DRV8411A_Instance *handle)
Starts the motor.
void DRV8411A_stopMotor (DRV8411A_Instance *handle)
Stops the motor.
bool DRV8411A_isMotorRunning (DRV8411A_Instance *handle)
Checks if the motor is currently running.
bool DRV8411A_isFaultOccurred (DRV8411A_Instance *handle)
Gets if any fault occurred at the instant.
void DRV8411A_setDirection (DRV8411A_Instance *handle, DRV8411A_DIR dir)
Sets the direction of motor.
void DRV8411A_setStepMode (DRV8411A_Instance *handle, DRV8411A_STEP stepMode)
Sets the step mode.
__STATIC_INLINE void DRV8411A_setDecayMode (DRV8411A_Instance *handle, DRV8411A_DECAY decayMode)
Sets the decay mode.
void DRV8411A_setSpeed (DRV8411A_Instance *handle, uint32_t timFreq)
Sets the motor speed by setting the timer frequency.
__STATIC_INLINE void DRV8411A_setItripSf (DRV8411A_Instance *handle)
Sets Itrip scale factor.
__STATIC_INLINE void DRV8411A_setISf (DRV8411A_Instance *handle, _iq15 _1ByAIpropoi)
Sets Phase current scale factors.
__STATIC_INLINE void DRV8411A_setRIPROPI (DRV8411A_Instance *handle, uint32_t value)
Sets ripropi value.
__STATIC_INLINE void DRV8411A_setItrip (DRV8411A_Instance *handle, _iq15 itrip)
Sets trip current.
__STATIC_INLINE void DRV8411A_setPhaseCurrentRefVoltage (DRV8411A_Instance *handle, _iq15 refVoltage)
Sets the reference voltage for the current measurements.
__STATIC_INLINE void DRV8411A_setVrefRefVoltage (DRV8411A_Instance *handle, _iq15 refVoltage)
Sets the reference voltage for the vref output.
__STATIC_INLINE _iq15 DRV8411A_getIA (DRV8411A_Instance *handle)
Gets the converted IA current.
__STATIC_INLINE _iq15 DRV8411A_getIB (DRV8411A_Instance *handle)
Gets the converted IB current.
__STATIC_INLINE void DRV8411A_setStep (DRV8411A_Instance *handle, uint16_t setSteps)
Sets the steps to move in step mode.
__STATIC_INLINE void DRV8411A_setControlMode (DRV8411A_Instance *handle, DRV8411A_CONTROL_MODE ctrl_mode)
Sets the control mode.
__STATIC_INLINE void DRV8411A_checkStep (DRV8411A_Instance *handle)
Checks if motor has moved the required steps in step mode.
__STATIC_INLINE void DRV8411A_setPWMDrive (HAL_GPIO_OUT_PIN in1, HAL_GPIO_OUT_PIN in2, STEPPER_DRIVE drive, DRV8411A_DECAY decayMode)
Updates both phase drive states if drv state is enabled.
__STATIC_INLINE void DRV8411A_setPWMDrives (DRV8411A_Instance *handle)
Updates both phase drive states if drv state is enabled.
__STATIC_INLINE void DRV8411A_setComm (DRV8411A_Instance *handle)
Calls the indexer to update the commutation state.
Detailed Description
Enumeration Type Documentation
DRV8411A_DIR
enum DRV8411A_DIR
Enumerator
DRV8411A_DIR_FORWARD
Forward direction
DRV8411A_DIR_REVERSE
Reverse direction
DRV8411A_STEP
enum DRV8411A_STEP
Enumerator
DRV8411A_STEP_FULL_STEP
Full step mode
DRV8411A_STEP_HALF_STEP_NC
Half step mode
DRV8411A_STEP_MAX
Total number of step mode
DRV8411A_DECAY
enum DRV8411A_DECAY
Enumerator
DRV8411A_DECAY_SLOW
Slow decay mode
DRV8411A_DECAY_FAST
Fast decay mode
DRV8411A_CONTROL_MODE
enum DRV8411A_CONTROL_MODE
Enumerator
DRV8411A_CONTROL_MODE_SPIN
Spin mode
DRV8411A_CONTROL_MODE_STEP
Step mode
DRV8411A_DRIVE
enum DRV8411A_DRIVE
Enumerator
DRV8411A_DRIVE_DISABLED
Disabled mode
DRV8411A_DRIVE_ENABLED
Enabled mode
Function Documentation
DRV8411A_init()
__STATIC_INLINE void DRV8411A_init (DRV8411A_Instance * handle)
Enables the necessary interrupts.
Parameters
[in] handle A pointer to drv8411a instance
References DRV8411A_Instance::ADCTriggerTimer, DRV8411A_Instance::aipropi, DRV8411A_Instance::bipropi, DRV8411A_disableDrive(), DRV8411A_enableDrive(), DRV8411A_isFaultOccurred(), DRV8411A_isMotorRunning(), DRV8411A_setDirection(), DRV8411A_setStepMode(), DRV8411A_startMotor(), DRV8411A_stopMotor(), HAL_enableADCInterrupt(), HAL_enableTIMInterrupt(), and DRV8411A_Instance::indexerTimer.
DRV8411A_enableDrive()
void DRV8411A_enableDrive (DRV8411A_Instance * handle)
Enables the drive.
Parameters
[in] handle A pointer to drv8411a instance
References DRV8411A_Instance::ain1, DRV8411A_Instance::ain2, DRV8411A_Instance::bin1, DRV8411A_Instance::bin2, DRV8411A_Instance::decayMode, DRV8411A_Instance::driveState, DRV8411A_DRIVE_ENABLED, DRV8411A_setPWMDrive(), INDEXER_Instance::IaDrive, INDEXER_Instance::IbDrive, DRV8411A_Instance::indexer, and STEPPER_DRIVE_FORWARD.
Referenced by DRV8411A_init().
DRV8411A_disableDrive()
void DRV8411A_disableDrive (DRV8411A_Instance * handle)
Disables the drive.
Parameters
[in] handle A pointer to drv8411a instance
References DRV8411A_Instance::driveState, DRV8411A_DRIVE_DISABLED, DRV8411A_setPWMDrives(), INDEXER_Instance::IaDrive, INDEXER_Instance::IbDrive, DRV8411A_Instance::indexer, and STEPPER_DRIVE_DISABLE.
Referenced by DRV8411A_init().
DRV8411A_startMotor()
void DRV8411A_startMotor (DRV8411A_Instance * handle)
Starts the motor.
Parameters
[in] handle A pointer to drv8411a instance
References DRV8411A_Instance::controlMode, DRV8411A_CONTROL_MODE_STEP, HAL_startTIMCounter(), DRV8411A_Instance::indexerTimer, and DRV8411A_Instance::setStep.
Referenced by DRV8411A_init().
DRV8411A_stopMotor()
void DRV8411A_stopMotor (DRV8411A_Instance * handle)
Stops the motor.
Parameters
[in] handle A pointer to drv8411a instance
References HAL_stopTIMCounter(), and DRV8411A_Instance::indexerTimer.
Referenced by DRV8411A_checkStep(), and DRV8411A_init().
DRV8411A_isMotorRunning()
bool DRV8411A_isMotorRunning (DRV8411A_Instance * handle)
Checks if the motor is currently running.
Parameters
[in] handle A pointer to drv8411a instance
Returns
Returns the running status of motor
Return values
true Motor is currently running
false Motor is not currently running
References HAL_isTIMCounterRunning(), and DRV8411A_Instance::indexerTimer.
Referenced by DRV8411A_init().
DRV8411A_isFaultOccurred()
bool DRV8411A_isFaultOccurred (DRV8411A_Instance * handle)
Gets if any fault occurred at the instant.
Parameters
[in] handle A pointer to drv8411a instance
Returns
Returns if fault occurred
Return values
true Fault currently present
false No fault is currently present
References HAL_GPIO_VALUE_LOW, HAL_readGPIOVal(), and DRV8411A_Instance::nfault.
Referenced by DRV8411A_init().
DRV8411A_setDirection()
void DRV8411A_setDirection (DRV8411A_Instance * handle, DRV8411A_DIR dir)
Sets the direction of motor.
Parameters
[in] handle A pointer to drv8411a instance
[in] dir New direction to be set. One of DRV8411A_DIR
References DRV8411A_DIR_FORWARD, DRV8411A_DIR_REVERSE, DRV8411A_Instance::indexer, STEPPER_DIR_FORWARD, STEPPER_DIR_REVERSE, and STEPPER_setIndexerDir().
Referenced by DRV8411A_init().
DRV8411A_setStepMode()
void DRV8411A_setStepMode (DRV8411A_Instance * handle, DRV8411A_STEP stepMode)
Sets the step mode.
Parameters
[in] handle A pointer to drv8411a instance
[in] stepMode Step mode to be set. One of DRV8411A_STEP
References DRV8411A_setSpeed(), DRV8411A_STEP_FULL_STEP, DRV8411A_STEP_HALF_STEP_NC, DRV8411A_Instance::indexer, DRV8411A_Instance::setFreq, DRV8411A_Instance::stepMode, STEPPER_setIndexerIncVal(), STEPPER_setStepType(), STEPPER_STEP_INC_DEC_FULL_STEP, STEPPER_STEP_INC_DEC_HALF_STEP, STEPPER_STEP_TYPE_CIR, and STEPPER_STEP_TYPE_NONCIR.
Referenced by DRV8411A_init().
DRV8411A_setDecayMode()
__STATIC_INLINE void DRV8411A_setDecayMode (DRV8411A_Instance * handle, DRV8411A_DECAY decayMode)
Sets the decay mode.
Parameters
[in] handle A pointer to drv8411a instance
[in] decayMode Decay mode to be set. One of DRV8411A_DECAY
References DRV8411A_Instance::decayMode, and DRV8411A_setSpeed().
DRV8411A_setSpeed()
void DRV8411A_setSpeed (DRV8411A_Instance * handle, uint32_t timFreq)
Sets the motor speed by setting the timer frequency.
Parameters
[in] handle A pointer to drv8411a instance
[in] timFreq Timer frequency to be set
References DRV8411A_MAX_SET_FREQ, HAL_setTIMFreq(), DRV8411A_Instance::indexerTimer, DRV8411A_Instance::setFreq, and DRV8411A_Instance::stepMode.
Referenced by DRV8411A_setDecayMode(), and DRV8411A_setStepMode().
DRV8411A_setItripSf()
__STATIC_INLINE void DRV8411A_setItripSf (DRV8411A_Instance * handle)
Sets Itrip scale factor.
Parameters
[in] handle A pointer to drv8411a instance
References DRV8411A_Instance::iSf, DRV8411A_Instance::itripSf, and DRV8411A_Instance::ripropiVal.
Referenced by DRV8411A_setRIPROPI().
DRV8411A_setISf()
__STATIC_INLINE void DRV8411A_setISf (DRV8411A_Instance * handle, _iq15 _1ByAIpropoi)
Sets Phase current scale factors.
Parameters
[in] handle A pointer to drv8411a instance
[in] _1ByAIpropoi Value of 1/AIpropi to be set as scale factor
References DRV8411A_Instance::iSf.
DRV8411A_setRIPROPI()
__STATIC_INLINE void DRV8411A_setRIPROPI (DRV8411A_Instance * handle, uint32_t value)
Sets ripropi value.
Parameters
[in] handle A pointer to drv8411a instance
[in] value Ripropi value to be set
References DRV8411A_setItripSf(), and DRV8411A_Instance::ripropiVal.
DRV8411A_setItrip()
__STATIC_INLINE void DRV8411A_setItrip (DRV8411A_Instance * handle, _iq15 itrip)
Sets trip current.
Parameters
[in] handle A pointer to drv8411a instance
[in] itrip Trip current value to be set in IQ
References HAL_setDACVoltage(), DRV8411A_Instance::itripSf, and DRV8411A_Instance::vref.
DRV8411A_setPhaseCurrentRefVoltage()
__STATIC_INLINE void DRV8411A_setPhaseCurrentRefVoltage (DRV8411A_Instance * handle, _iq15 refVoltage)
Sets the reference voltage for the current measurements.
Parameters
[in] handle A pointer to drv8411a instance
[in] refVoltage Reference voltage to be set in IQ
References DRV8411A_Instance::aipropi, DRV8411A_Instance::bipropi, and HAL_setADCRefVoltage().
DRV8411A_setVrefRefVoltage()
__STATIC_INLINE void DRV8411A_setVrefRefVoltage (DRV8411A_Instance * handle, _iq15 refVoltage)
Sets the reference voltage for the vref output.
Parameters
[in] handle A pointer to drv8411a instance
[in] refVoltage Reference voltage to be set in IQ
References HAL_setDacRefVoltage(), and DRV8411A_Instance::vref.
DRV8411A_getIA()
__STATIC_INLINE _iq15 DRV8411A_getIA (DRV8411A_Instance * handle)
Gets the converted IA current.
Parameters
[in] handle A pointer to drv8411a instance
Returns
Returns the converted IA current in IQ
References DRV8411A_Instance::aipropi, HAL_getADCResult(), DRV8411A_Instance::iSf, and DRV8411A_Instance::ripropiVal.
DRV8411A_getIB()
__STATIC_INLINE _iq15 DRV8411A_getIB (DRV8411A_Instance * handle)
Gets the converted IB current.
Parameters
[in] handle A pointer to drv8411a instance
Returns
Returns the converted IB current in IQ
References DRV8411A_Instance::bipropi, HAL_getADCResult(), DRV8411A_Instance::iSf, and DRV8411A_Instance::ripropiVal.
DRV8411A_setStep()
__STATIC_INLINE void DRV8411A_setStep (DRV8411A_Instance * handle, uint16_t setSteps)
Sets the steps to move in step mode.
Parameters
[in] handle A pointer to drv8411a instance
[in] setSteps Steps to move in step mode
References DRV8411A_Instance::setStep.
DRV8411A_setControlMode()
__STATIC_INLINE void DRV8411A_setControlMode (DRV8411A_Instance * handle, DRV8411A_CONTROL_MODE ctrl_mode)
Sets the control mode.
Parameters
[in] handle A pointer to drv8411a instance
[in] ctrl_mode Control mode to be set. One of DRV8411A_CONTROL_MODE_STEP
References DRV8411A_Instance::controlMode.
DRV8411A_checkStep()
__STATIC_INLINE void DRV8411A_checkStep (DRV8411A_Instance * handle)
Checks if motor has moved the required steps in step mode.
Parameters
[in] handle A pointer to drv8411a instance
References DRV8411A_Instance::controlMode, DRV8411A_CONTROL_MODE_STEP, DRV8411A_stopMotor(), DRV8411A_Instance::setStep, and DRV8411A_Instance::stepCount.
Referenced by DRV8411A_setComm().
DRV8411A_setPWMDrive()
__STATIC_INLINE void DRV8411A_setPWMDrive (HAL_GPIO_OUT_PIN in1, HAL_GPIO_OUT_PIN in2, STEPPER_DRIVE drive, DRV8411A_DECAY decayMode)
Updates both phase drive states if drv state is enabled.
Parameters
[in] in1 GPIO pin for input 1
[in] in2 GPIO pin for input 2
[in] drive New drive state to be set. One of STEPPER_DRIVE
[in] decayMode A decay mode. One of DRV8411A_DECAY
References DRV8411A_DECAY_SLOW, HAL_GPIO_VALUE_HIGH, HAL_GPIO_VALUE_LOW, HAL_setGPIOVal(), STEPPER_DRIVE_DECAY, STEPPER_DRIVE_DISABLE, STEPPER_DRIVE_FORWARD, and STEPPER_DRIVE_REVERSE.
Referenced by DRV8411A_enableDrive(), and DRV8411A_setPWMDrives().
DRV8411A_setPWMDrives()
__STATIC_INLINE void DRV8411A_setPWMDrives (DRV8411A_Instance * handle)
Updates both phase drive states if drv state is enabled.
Parameters
[in] handle A pointer to drv8411a instance
References DRV8411A_Instance::ain1, DRV8411A_Instance::ain2, DRV8411A_Instance::bin1, DRV8411A_Instance::bin2, DRV8411A_Instance::decayMode, DRV8411A_Instance::driveState, DRV8411A_DRIVE_DISABLED, DRV8411A_setPWMDrive(), INDEXER_Instance::IaDrive, INDEXER_Instance::IbDrive, DRV8411A_Instance::indexer, and STEPPER_DRIVE_DISABLE.
Referenced by DRV8411A_disableDrive(), and DRV8411A_setComm().
DRV8411A_setComm()
__STATIC_INLINE void DRV8411A_setComm (DRV8411A_Instance * handle)
Calls the indexer to update the commutation state.
Parameters
[in] handle A pointer to drv8411a instance
References DRV8411A_checkStep(), DRV8411A_setPWMDrives(), DRV8411A_Instance::indexer, and STEPPER_indexer().
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale