StepperMotorControlLibrary: HAL/LP_MSPM0L1306
HAL/LP_MSPM0L1306
Data Structures
struct HAL_SPI
Define SPI instance.
struct HAL_DAC
Define DAC instance.
struct HAL_ADC
Define ADC instance.
struct HAL_PWM
Define PWM instance.
struct HAL_TIM
Define TIM instance.
struct HAL_GPIO
Define GPIO instance.
Macros
#define HAL_MCU_CLK_SPEED_HZ (32000000)
MCU clock frequency.
#define HAL_CYCLES_TO_1_MS_DELAY (HAL_MCU_CLK_SPEED_HZ/1000)
Cycles for 1 ms delay.
#define HAL_ADC_MAX_VALUE (4095)
Maximum value of data from the ADC.
#define HAL_DAC_MAX_VALUE (255)
Maximum value of data set to DAC.
#define HAL_ADC_DEFAULT_REF_VOLTAGE (3.3f)
Value of default ADC reference voltage in volts.
#define HAL_DAC_DEFAULT_REF_VOLTAGE (3.3f)
Value of default DAC reference voltage in volts.
#define HAL_TIM_PERIPHERAL_CLOCK_SOURCE (32000000)
Value of the source clock for the timer peripherals.
Enumerations
enum HAL_PWM_CHANNEL {
HAL_PWM_CHANNEL_0 = 0,
HAL_PWM_CHANNEL_1,
HAL_PWM_CHANNEL_MAX
}
enum HAL_TIM_CHANNEL {
HAL_TIM_CHANNEL_0 = 0,
HAL_TIM_CHANNEL_1,
HAL_TIM_CHANNEL_MAX
}
enum HAL_ADC_CHANNEL {
HAL_ADC_CHANNEL_0 = 0,
HAL_ADC_CHANNEL_1,
HAL_ADC_CHANNEL_MAX
}
enum HAL_DAC_CHANNEL {
HAL_DAC_CHANNEL_0 = 0,
HAL_DAC_CHANNEL_MAX
}
enum HAL_GPIO_IN_PIN {
HAL_GPIO_IN_PIN_0 = 0,
HAL_GPIO_IN_PIN_MAX
}
enum HAL_GPIO_OUT_PIN {
HAL_GPIO_OUT_PIN_0 = 0,
HAL_GPIO_OUT_PIN_1,
HAL_GPIO_OUT_PIN_2,
HAL_GPIO_OUT_PIN_3,
HAL_GPIO_OUT_PIN_4,
HAL_GPIO_OUT_PIN_5,
HAL_GPIO_OUT_PIN_6,
HAL_GPIO_OUT_PIN_7,
HAL_GPIO_OUT_PIN_8,
HAL_GPIO_OUT_PIN_9,
HAL_GPIO_OUT_PIN_MAX
}
enum HAL_SPI_CHANNEL {
HAL_SPI_CHANNEL_0 = 0,
HAL_SPI_CHANNEL_MAX
}
enum HAL_SPI_CS {
HAL_SPI_CS_0 = 0,
HAL_SPI_CS_1,
HAL_SPI_CS_2,
HAL_SPI_CS_3,
HAL_SPI_CS_MAX
}
enum HAL_GPIO_VALUE {
HAL_GPIO_VALUE_LOW = 0,
HAL_GPIO_VALUE_HIGH
}
enum HAL_PWM_CHANNEL_MODE {
HAL_PWM_CHANNEL_MODE_PWM = GPTIMER_CCACT_01_SWFRCACT_DISABLED,
HAL_PWM_CHANNEL_MODE_FORCED_HIGH = GPTIMER_CCACT_01_SWFRCACT_CCP_HIGH,
HAL_PWM_CHANNEL_MODE_FORCED_LOW = GPTIMER_CCACT_01_SWFRCACT_CCP_LOW
}
enum HAL_PIN_MODE {
HAL_PIN_MODE_OUTPUT_LOW = 0,
HAL_PIN_MODE_OUTPUT_HIGH,
HAL_PIN_MODE_INPUT_PU,
HAL_PIN_MODE_INPUT_PD,
HAL_PIN_MODE_INPUT_HZ
}
Functions
void HAL_init (void)
Initializes the hal module.
void HAL_setADCRefVoltage (HAL_ADC_CHANNEL adcChan, _iq15 value)
Sets the ADC reference voltage.
void HAL_setDacRefVoltage (HAL_DAC_CHANNEL dacChan, _iq15 value)
Sets the DAC reference voltage.
void HAL_setADCSf (void)
Sets the ADC scale factor.
void HAL_checkAndEnableIRQ (IRQn_Type irqn)
If the IRQ is disabled it is enabled.
void HAL_enableADCInterrupt (HAL_ADC_CHANNEL adcChan)
Enable ADC interrupt.
void HAL_disableADCInterrupt (HAL_ADC_CHANNEL adcChan)
Disable ADC interrupt.
void HAL_enablePWMInterrupt (HAL_PWM_CHANNEL pwmChan)
Enable PWM interrupt.
void HAL_disablePWMInterrupts (HAL_PWM_CHANNEL pwmChan)
Disable PWM interrupt.
void HAL_enableTIMInterrupt (HAL_TIM_CHANNEL timChan)
Enable TIM interrupt.
void HAL_disableTIMInterrupt (HAL_TIM_CHANNEL timChan)
Disable TIM interrupt.
__STATIC_INLINE void HAL_setGPIOVal (HAL_GPIO_OUT_PIN gpioPin, HAL_GPIO_VALUE value)
Set value to GPIO pin.
HAL_GPIO_VALUE HAL_readGPIOVal (HAL_GPIO_IN_PIN gpioPin)
Read GPIO pin.
void HAL_configurePin (GPIO_Regs *port, IOMUX_PINCM iomux, uint32_t pin, HAL_PIN_MODE mode)
Configure pin.
void HAL_configureGPIOOUTPin (HAL_GPIO_OUT_PIN gpioPin, HAL_PIN_MODE mode)
Configure GPIO OUT pin.
void HAL_configureGPIOINPin (HAL_GPIO_IN_PIN gpioPin, HAL_PIN_MODE mode)
Configure GPIO IN pin.
void HAL_setDACVoltage (HAL_DAC_CHANNEL dacChan, _iq15 volt)
Set voltage on DAC channel.
uint32_t HAL_getPWMLoadValue (HAL_PWM_CHANNEL pwmChan)
Gets the Load value of the timer associated with the PWM channel.
void HAL_startPWMCounter (HAL_PWM_CHANNEL pwmChan)
Start the timer associated with the PWM channel.
void HAL_stopPWMCounter (HAL_PWM_CHANNEL pwmChan)
Stops the timer associated with the PWM channel.
void HAL_startTIMCounter (HAL_TIM_CHANNEL timChan)
Start the timer associated with the TIM channel.
void HAL_stopTIMCounter (HAL_TIM_CHANNEL timChan)
Stops the timer associated with the TIM channel.
bool HAL_isPWMCounterRunning (HAL_PWM_CHANNEL pwmChan)
Checks if the timer counter is running.
bool HAL_isTIMCounterRunning (HAL_TIM_CHANNEL timChan)
Checks if the timer counter is running.
void HA_setPWMDutyCycle (HAL_PWM_CHANNEL pwmChan, uint8_t dutycycle)
Set dutycycle to a pwm channel.
void HAL_setPWMFreq (HAL_PWM_CHANNEL pwmChan, uint32_t freq)
Set the frequency of the timer associated with the PWM channel.
void HAL_setTIMFreq (HAL_TIM_CHANNEL timChan, uint32_t freq)
Set the frequency of the timer associated with the TIM channel.
void HAL_setPWMLoadVal (HAL_PWM_CHANNEL pwmChan, uint32_t loadValue)
Set the Load value of the timer associated with the PWM channel.
void HAL_setTIMLoadVal (HAL_TIM_CHANNEL timChan, uint32_t loadValue)
Set the Load value of the timer associated with the TIM channel.
void HAL_setFreq (GPTIMER_Regs *timerInst, uint32_t freq)
Set the frequency for timer peripheral.
void HAL_setLoadVal (GPTIMER_Regs *timerInst, uint32_t loadValue)
Set the Load value of a timer peripheral.
uint16_t HAL_getADCData (HAL_ADC_CHANNEL adcChan)
Gets the ADC sampled value.
_iq15 HAL_getADCResult (HAL_ADC_CHANNEL adcChan)
Gets the converted value in adc.
DL_ADC12_IIDX HAL_processADCIRQ (ADC12_Regs *adcInst)
Collects the ADC data if the adc convertion is over.
void HAL_delayMilliSeconds (uint32_t num_ms)
Blocks for the specified delay time.
void HAL_configurePWMPin (HAL_PWM_CHANNEL pwmChan, HAL_PWM_CHANNEL_MODE pwmMode)
Change the configuration of PWM channel.
bool HAL_isSPIRxFifoEmpty (HAL_SPI_CHANNEL spiPeripheral)
Gets status of RX Fifo.
uint16_t HAL_receiveSPIData16 (HAL_SPI_CHANNEL spiPeripheral, HAL_SPI_CS cs)
Reads 16 bit data in SPI peripheral.
void HAL_transmitSPIData16 (HAL_SPI_CHANNEL spiPeripheral, HAL_SPI_CS cs, uint16_t data)
Writes 16 bit data in SPI peripheral.
bool HAL_isSPIBusy (HAL_SPI_CHANNEL spiPeripheral)
Gets busy status of SPI peripheral.
__STATIC_INLINE void HAL_SPI_clearRXFifo (HAL_SPI_CHANNEL spiPeripheral, HAL_SPI_CS cs)
Clears the RX Fifo if the SPI peripheral.
Variables
HAL_GPIO gpioOUT [HAL_GPIO_OUT_PIN_MAX]
Array for storing the ouput GPIO pin instances.
Detailed Description
Enumeration Type Documentation
HAL_PWM_CHANNEL
enum HAL_PWM_CHANNEL
Enumerator
HAL_PWM_CHANNEL_0
Index associated to PWM channel 0
HAL_PWM_CHANNEL_1
Index associated to PWM channel 1
HAL_PWM_CHANNEL_MAX
Total number of PWM channels
HAL_TIM_CHANNEL
enum HAL_TIM_CHANNEL
Enumerator
HAL_TIM_CHANNEL_0
Index associated to Timer channel 0
HAL_TIM_CHANNEL_1
Index associated to Timer channel 1
HAL_TIM_CHANNEL_MAX
Total number of Timer channels
HAL_ADC_CHANNEL
enum HAL_ADC_CHANNEL
Enumerator
HAL_ADC_CHANNEL_0
Index associated to ADC channel 0
HAL_ADC_CHANNEL_1
Index associated to ADC channel 1
HAL_ADC_CHANNEL_MAX
Total number of ADC channels
HAL_DAC_CHANNEL
enum HAL_DAC_CHANNEL
Enumerator
HAL_DAC_CHANNEL_0
Index associated to DAC channel 0
HAL_DAC_CHANNEL_MAX
Total number of DAC channels
HAL_GPIO_IN_PIN
enum HAL_GPIO_IN_PIN
Enumerator
HAL_GPIO_IN_PIN_0
Index associated to input GPIO PIN 0
HAL_GPIO_IN_PIN_MAX
Total number of input GPIO pins
HAL_GPIO_OUT_PIN
enum HAL_GPIO_OUT_PIN
Enumerator
HAL_GPIO_OUT_PIN_0
Index associated to output GPIO PIN 0
HAL_GPIO_OUT_PIN_1
Index associated to output GPIO PIN 1
HAL_GPIO_OUT_PIN_2
Index associated to output GPIO PIN 2
HAL_GPIO_OUT_PIN_3
Index associated to output GPIO PIN 3
HAL_GPIO_OUT_PIN_4
Index associated to output GPIO PIN 4
HAL_GPIO_OUT_PIN_5
Index associated to output GPIO PIN 5
HAL_GPIO_OUT_PIN_6
Index associated to output GPIO PIN 6
HAL_GPIO_OUT_PIN_7
Index associated to output GPIO PIN 7
HAL_GPIO_OUT_PIN_8
Index associated to output GPIO PIN 8
HAL_GPIO_OUT_PIN_9
Index associated to output GPIO PIN 9
HAL_GPIO_OUT_PIN_MAX
Total number of output GPIO pins
HAL_SPI_CHANNEL
enum HAL_SPI_CHANNEL
Enumerator
HAL_SPI_CHANNEL_0
Index associated to SPI channel 0
HAL_SPI_CHANNEL_MAX
Total number of SPI channels
HAL_SPI_CS
enum HAL_SPI_CS
HAL_GPIO_VALUE
enum HAL_GPIO_VALUE
Enumerator
HAL_GPIO_VALUE_LOW
GPIO set to low
HAL_GPIO_VALUE_HIGH
GPIO set to high
HAL_PWM_CHANNEL_MODE
enum HAL_PWM_CHANNEL_MODE
Enumerator
HAL_PWM_CHANNEL_MODE_PWM
PWM channel in PWM mode
HAL_PWM_CHANNEL_MODE_FORCED_HIGH
PWM channel forced to high
HAL_PWM_CHANNEL_MODE_FORCED_LOW
PWM channel forced to low
HAL_PIN_MODE
enum HAL_PIN_MODE
Enumerator
HAL_PIN_MODE_OUTPUT_LOW
Indicates you want pin set as a gpio output and with a low value
HAL_PIN_MODE_OUTPUT_HIGH
Indicates you want pin set as a gpio output and with a high value
HAL_PIN_MODE_INPUT_PU
Indicates you want pin set as a gpio input with a pullup
HAL_PIN_MODE_INPUT_PD
Indicates you want pin set as a gpio input with a pulldown
HAL_PIN_MODE_INPUT_HZ
Indicates you want pin set as a gpio input
Function Documentation
HAL_setADCRefVoltage()
void HAL_setADCRefVoltage (HAL_ADC_CHANNEL adcChan, _iq15 value)
Sets the ADC reference voltage.
Parameters
[in] adcChan An ADC Channel. One of HAL_ADC_CHANNEL
[in] value Reference volatage to be set in IQ
References HAL_ADC::refVoltage.
Referenced by DRV8411A_setPhaseCurrentRefVoltage().
HAL_setDacRefVoltage()
void HAL_setDacRefVoltage (HAL_DAC_CHANNEL dacChan, _iq15 value)
Sets the DAC reference voltage.
Parameters
[in] dacChan An DAC Channel. One of HAL_DAC_CHANNEL
[in] value Reference volatage to be set in IQ
References HAL_DAC::refVoltage.
Referenced by DRV8411A_setVrefRefVoltage(), and DRV8889Q1_setVrefRefVoltage().
HAL_checkAndEnableIRQ()
void HAL_checkAndEnableIRQ (IRQn_Type irqn)
If the IRQ is disabled it is enabled.
Parameters
[in] irqn An IRQn.
Referenced by HAL_enableADCInterrupt(), HAL_enablePWMInterrupt(), and HAL_enableTIMInterrupt().
HAL_enableADCInterrupt()
void HAL_enableADCInterrupt (HAL_ADC_CHANNEL adcChan)
Enable ADC interrupt.
Parameters
[in] adcChan An ADC Channel. One of HAL_ADC_CHANNEL
References HAL_checkAndEnableIRQ().
Referenced by DRV8411A_init().
HAL_disableADCInterrupt()
void HAL_disableADCInterrupt (HAL_ADC_CHANNEL adcChan)
Disable ADC interrupt.
Parameters
[in] adcChan An ADC Channel. One of HAL_ADC_CHANNEL
HAL_enablePWMInterrupt()
void HAL_enablePWMInterrupt (HAL_PWM_CHANNEL pwmChan)
Enable PWM interrupt.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
References HAL_checkAndEnableIRQ().
Referenced by DRV8889Q1_init().
HAL_disablePWMInterrupts()
void HAL_disablePWMInterrupts (HAL_PWM_CHANNEL pwmChan)
Disable PWM interrupt.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
HAL_enableTIMInterrupt()
void HAL_enableTIMInterrupt (HAL_TIM_CHANNEL timChan)
Enable TIM interrupt.
Parameters
[in] timChan A TIM channel. One of HAL_TIM_CHANNEL
References HAL_checkAndEnableIRQ().
Referenced by DRV8411A_init().
HAL_disableTIMInterrupt()
void HAL_disableTIMInterrupt (HAL_TIM_CHANNEL timChan)
Disable TIM interrupt.
Parameters
[in] timChan A TIM channel. One of HAL_TIM_CHANNEL
HAL_setGPIOVal()
__STATIC_INLINE void HAL_setGPIOVal (HAL_GPIO_OUT_PIN gpioPin, HAL_GPIO_VALUE value)
Set value to GPIO pin.
Parameters
[in] gpioPin A GPIO pin. One of HAL_GPIO_OUT_PIN
[in] value Value to be set to pin. One of HAL_GPIO_VALUE
References HA_setPWMDutyCycle(), HAL_configureGPIOINPin(), HAL_configureGPIOOUTPin(), HAL_configurePin(), HAL_configurePWMPin(), HAL_delayMilliSeconds(), HAL_getADCData(), HAL_getADCResult(), HAL_getPWMLoadValue(), HAL_GPIO_VALUE_HIGH, HAL_isPWMCounterRunning(), HAL_isSPIBusy(), HAL_isSPIRxFifoEmpty(), HAL_isTIMCounterRunning(), HAL_processADCIRQ(), HAL_readGPIOVal(), HAL_receiveSPIData16(), HAL_setDACVoltage(), HAL_setFreq(), HAL_setLoadVal(), HAL_setPWMFreq(), HAL_setPWMLoadVal(), HAL_setTIMFreq(), HAL_setTIMLoadVal(), HAL_startPWMCounter(), HAL_startTIMCounter(), HAL_stopPWMCounter(), HAL_stopTIMCounter(), and HAL_transmitSPIData16().
Referenced by DRV8411A_setPWMDrive(), DRV8889Q1_clearNSleep(), DRV8889Q1_disableOutput(), DRV8889Q1_enableOutput(), DRV8889Q1_setDirection(), and DRV8889Q1_setNSleep().
HAL_readGPIOVal()
HAL_GPIO_VALUE HAL_readGPIOVal (HAL_GPIO_IN_PIN gpioPin)
Read GPIO pin.
Parameters
[in] gpioPin A GPIO pin. One of HAL_GPIO_IN_PIN
Returns
Returns the value of the GPIO pin. One of HAL_GPIO_VALUE
References HAL_GPIO_VALUE_HIGH, and HAL_GPIO_VALUE_LOW.
Referenced by DRV8411A_isFaultOccurred(), DRV8889Q1_isFaultOccurred(), and HAL_setGPIOVal().
HAL_configurePin()
void HAL_configurePin (GPIO_Regs * port, IOMUX_PINCM iomux, uint32_t pin, HAL_PIN_MODE mode)
Configure pin.
Parameters
[in] port GPIO Port for the pin
[in] iomux IOMUX for the pin
[in] pin Port of the pin
[in] mode Mode to set. One of HAL_PIN_MODE
References HAL_PIN_MODE_INPUT_HZ, HAL_PIN_MODE_INPUT_PD, HAL_PIN_MODE_INPUT_PU, HAL_PIN_MODE_OUTPUT_HIGH, and HAL_PIN_MODE_OUTPUT_LOW.
Referenced by HAL_configureGPIOINPin(), HAL_configureGPIOOUTPin(), and HAL_setGPIOVal().
HAL_configureGPIOOUTPin()
void HAL_configureGPIOOUTPin (HAL_GPIO_OUT_PIN gpioPin, HAL_PIN_MODE mode)
Configure GPIO OUT pin.
Parameters
[in] gpioPin A GPIO OUT pin. One of HAL_GPIO_OUT_PIN
[in] mode Mode to set. One of HAL_PIN_MODE
References HAL_configurePin().
Referenced by HAL_setGPIOVal().
HAL_configureGPIOINPin()
void HAL_configureGPIOINPin (HAL_GPIO_IN_PIN gpioPin, HAL_PIN_MODE mode)
Configure GPIO IN pin.
Parameters
[in] gpioPin A GPIO IN pin. One of HAL_GPIO_IN_PIN
[in] mode Mode to set. One of HAL_PIN_MODE
References HAL_configurePin().
Referenced by HAL_setGPIOVal().
HAL_setDACVoltage()
void HAL_setDACVoltage (HAL_DAC_CHANNEL dacChan, _iq15 volt)
Set voltage on DAC channel.
Parameters
[in] dacChan A DAC channel. One of HAL_DAC_CHANNEL
[in] volt Voltage to be set on DAC in _iq15.
References HAL_DAC_MAX_VALUE.
Referenced by DRV8411A_setItrip(), DRV8889Q1_setFSCurr(), and HAL_setGPIOVal().
HAL_getPWMLoadValue()
uint32_t HAL_getPWMLoadValue (HAL_PWM_CHANNEL pwmChan)
Gets the Load value of the timer associated with the PWM channel.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
Returns
Returns the load register value of the timer instance of the specified PWM channel
Referenced by HAL_setGPIOVal().
HAL_startPWMCounter()
void HAL_startPWMCounter (HAL_PWM_CHANNEL pwmChan)
Start the timer associated with the PWM channel.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
Referenced by DRV8889Q1_startMotor(), and HAL_setGPIOVal().
HAL_stopPWMCounter()
void HAL_stopPWMCounter (HAL_PWM_CHANNEL pwmChan)
Stops the timer associated with the PWM channel.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
Referenced by DRV8889Q1_stopMotor(), and HAL_setGPIOVal().
HAL_startTIMCounter()
void HAL_startTIMCounter (HAL_TIM_CHANNEL timChan)
Start the timer associated with the TIM channel.
Parameters
[in] timChan A TIM channel. One of HAL_TIM_CHANNEL
Referenced by DRV8411A_startMotor(), and HAL_setGPIOVal().
HAL_stopTIMCounter()
void HAL_stopTIMCounter (HAL_TIM_CHANNEL timChan)
Stops the timer associated with the TIM channel.
Parameters
[in] timChan A TIM channel. One of HAL_PWM_CHANNEL
Referenced by DRV8411A_stopMotor(), and HAL_setGPIOVal().
HAL_isPWMCounterRunning()
bool HAL_isPWMCounterRunning (HAL_PWM_CHANNEL pwmChan)
Checks if the timer counter is running.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
Returns
Returns the running status of timer
Return values
true Timer is running
false Timer is not running
Referenced by DRV8889Q1_isMotorRunning(), and HAL_setGPIOVal().
HAL_isTIMCounterRunning()
bool HAL_isTIMCounterRunning (HAL_TIM_CHANNEL timChan)
Checks if the timer counter is running.
Parameters
[in] timChan A TIM channel. One of HAL_TIM_CHANNEL
Returns
Returns the running status of timer
Return values
true Timer is running
false Timer is not running
Referenced by DRV8411A_isMotorRunning(), and HAL_setGPIOVal().
HA_setPWMDutyCycle()
void HA_setPWMDutyCycle (HAL_PWM_CHANNEL pwmChan, uint8_t dutycycle)
Set dutycycle to a pwm channel.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
[in] dutycycle Percentage dutycycle to be set in the PWM channel .
References HAL_PWM::inst.
Referenced by DRV8889Q1_setStepDuty(), and HAL_setGPIOVal().
HAL_setPWMFreq()
void HAL_setPWMFreq (HAL_PWM_CHANNEL pwmChan, uint32_t freq)
Set the frequency of the timer associated with the PWM channel.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
[in] freq PWM frequency to be set.
References HAL_setFreq().
Referenced by DRV8889Q1_setSpeed(), and HAL_setGPIOVal().
HAL_setTIMFreq()
void HAL_setTIMFreq (HAL_TIM_CHANNEL timChan, uint32_t freq)
Set the frequency of the timer associated with the TIM channel.
Parameters
[in] timChan A TIM channel. One of HAL_TIM_CHANNEL
[in] freq TIM frequency to be set.
References HAL_setFreq().
Referenced by DRV8411A_setSpeed(), and HAL_setGPIOVal().
HAL_setPWMLoadVal()
void HAL_setPWMLoadVal (HAL_PWM_CHANNEL pwmChan, uint32_t loadValue)
Set the Load value of the timer associated with the PWM channel.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
[in] loadValue Load value to be set to the specified PWM channel.
References HAL_setLoadVal(), and HAL_PWM::inst.
Referenced by HAL_setGPIOVal().
HAL_setTIMLoadVal()
void HAL_setTIMLoadVal (HAL_TIM_CHANNEL timChan, uint32_t loadValue)
Set the Load value of the timer associated with the TIM channel.
Parameters
[in] timChan A TIM channel. One of HAL_TIM_CHANNEL
[in] loadValue Load value to be set to the specified TIM channel.
References HAL_setLoadVal(), and HAL_TIM::inst.
Referenced by HAL_setGPIOVal().
HAL_setFreq()
void HAL_setFreq (GPTIMER_Regs * timerInst, uint32_t freq)
Set the frequency for timer peripheral.
Parameters
[in] timerInst Pointer to a timer peripheral.
[in] freq Frequency to be set to peripheral.
References HAL_setLoadVal(), and HAL_TIM_PERIPHERAL_CLOCK_SOURCE.
Referenced by HAL_setGPIOVal(), HAL_setPWMFreq(), and HAL_setTIMFreq().
HAL_setLoadVal()
void HAL_setLoadVal (GPTIMER_Regs * timerInst, uint32_t loadValue)
Set the Load value of a timer peripheral.
Parameters
[in] timerInst Pointer to a timer peripheral.
[in] loadValue Load value to be set to the timer peripheral.
Referenced by HAL_setFreq(), HAL_setGPIOVal(), HAL_setPWMLoadVal(), and HAL_setTIMLoadVal().
HAL_getADCData()
uint16_t HAL_getADCData (HAL_ADC_CHANNEL adcChan)
Gets the ADC sampled value.
Parameters
[in] adcChan An ADC Channel. One of HAL_ADC_CHANNEL
Returns
Returns the ADC sampled value
Referenced by HAL_processADCIRQ(), and HAL_setGPIOVal().
HAL_getADCResult()
_iq15 HAL_getADCResult (HAL_ADC_CHANNEL adcChan)
Gets the converted value in adc.
Parameters
[in] adcChan An ADC Channel. One of HAL_ADC_CHANNEL
Returns
Returns the converted value in adc
Referenced by DRV8411A_getIA(), DRV8411A_getIB(), and HAL_setGPIOVal().
HAL_processADCIRQ()
DL_ADC12_IIDX HAL_processADCIRQ (ADC12_Regs * adcInst)
Collects the ADC data if the adc convertion is over.
Parameters
[in] adcInst Pointer to a ADC peripheral
Returns
DL_ADC12_IIDX returns interrupt information that caused the IRQ to fire.
References HAL_ADC_CHANNEL_MAX, HAL_getADCData(), and HAL_ADC::value.
Referenced by HAL_setGPIOVal().
HAL_delayMilliSeconds()
void HAL_delayMilliSeconds (uint32_t num_ms)
Blocks for the specified delay time.
Parameters
[in] num_ms Delay in ms
References HAL_CYCLES_TO_1_MS_DELAY.
Referenced by DRV8889Q1_setNSleep(), and HAL_setGPIOVal().
HAL_configurePWMPin()
void HAL_configurePWMPin (HAL_PWM_CHANNEL pwmChan, HAL_PWM_CHANNEL_MODE pwmMode)
Change the configuration of PWM channel.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
[in] pwmMode PWM Mode to be set. One of HAL_PWM_CHANNEL_MODE
References HAL_PWM::CCIndex, and HAL_PWM::inst.
Referenced by DRV8889Q1_setStepDrive(), and HAL_setGPIOVal().
HAL_isSPIRxFifoEmpty()
bool HAL_isSPIRxFifoEmpty (HAL_SPI_CHANNEL spiPeripheral)
Gets status of RX Fifo.
Parameters
[in] spiPeripheral A SPI peripheral. One of HAL_SPI_CHANNEL
Returns
Returns empty status of RX Fifo
Return values
true The RX FIFO is empty
false The RX FIFO is not empty
Referenced by HAL_setGPIOVal(), and HAL_SPI_clearRXFifo().
HAL_receiveSPIData16()
uint16_t HAL_receiveSPIData16 (HAL_SPI_CHANNEL spiPeripheral, HAL_SPI_CS cs)
Reads 16 bit data in SPI peripheral.
Parameters
[in] spiPeripheral A SPI peripheral. One of HAL_SPI_CHANNEL
[in] cs A SPI chip select. One of HAL_SPI_CS
Returns
Data received in SPI peripheral
Referenced by HAL_setGPIOVal(), and HAL_SPI_clearRXFifo().
HAL_transmitSPIData16()
void HAL_transmitSPIData16 (HAL_SPI_CHANNEL spiPeripheral, HAL_SPI_CS cs, uint16_t data)
Writes 16 bit data in SPI peripheral.
Parameters
[in] spiPeripheral A SPI peripheral. One of HAL_SPI_CHANNEL
[in] cs A SPI chip select. One of HAL_SPI_CS
[in] data Data to be written in to the SPI peripheral
Referenced by HAL_setGPIOVal().
HAL_isSPIBusy()
bool HAL_isSPIBusy (HAL_SPI_CHANNEL spiPeripheral)
Gets busy status of SPI peripheral.
Parameters
[in] spiPeripheral A SPI peripheral. One of HAL_SPI_CHANNEL
Returns
Returns busy status of RX Fifo
Return values
true The SPI peripheral is currently busy with transmitting data
false The SPI peripheral is in idle
Referenced by HAL_setGPIOVal().
HAL_SPI_clearRXFifo()
__STATIC_INLINE void HAL_SPI_clearRXFifo (HAL_SPI_CHANNEL spiPeripheral, HAL_SPI_CS cs)
Clears the RX Fifo if the SPI peripheral.
Parameters
[in] spiPeripheral A SPI peripheral. One of HAL_SPI_CHANNEL
[in] cs A SPI chip select. One of HAL_SPI_CS
References HAL_isSPIRxFifoEmpty(), and HAL_receiveSPIData16().
Referenced by DRV8889Q1_spiRead().
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale