MSPM0GX218_GX207 Driver Library: Basic Timer (BTIM)
Basic Timer (BTIM)
Modules
DL_TIMERB_INTERRUPT
DL_TIMERB_EVENT
Data Structures
struct DL_TimerB_TimerConfig
Configuration struct for DL_TimerB_initTimer.
Enumerations
enum DL_TIMERB_COUNTER_IDX {
DL_TIMERB_COUNTER_IDX_0 = 0,
DL_TIMERB_COUNTER_IDX_1 = 1,
DL_TIMERB_COUNTER_IDX_2 = 2,
DL_TIMERB_COUNTER_IDX_3 = 3,
DL_TIMERB_COUNTER_IDX_4 = 4,
DL_TIMERB_COUNTER_IDX_5 = 5,
DL_TIMERB_COUNTER_IDX_6 = 6,
DL_TIMERB_COUNTER_IDX_7 = 7
}
enum DL_TIMERB_CLOCK_SOURCE {
DL_TIMERB_CLOCK_SOURCE_BUSCLK = (0U << BTIMER_CTL0_CLKSEL_OFS),
DL_TIMERB_CLOCK_SOURCE_CNT0_OVERFLOW = (1U << BTIMER_CTL0_CLKSEL_OFS),
DL_TIMERB_CLOCK_SOURCE_CNT1_OVERFLOW = (2U << BTIMER_CTL0_CLKSEL_OFS),
DL_TIMERB_CLOCK_SOURCE_CNT2_OVERFLOW = (3U << BTIMER_CTL0_CLKSEL_OFS),
DL_TIMERB_CLOCK_SOURCE_CNT3_OVERFLOW = (4U << BTIMER_CTL0_CLKSEL_OFS),
DL_TIMERB_CLOCK_SOURCE_CNT4_OVERFLOW = (5U << BTIMER_CTL0_CLKSEL_OFS),
DL_TIMERB_CLOCK_SOURCE_CNT5_OVERFLOW = (6U << BTIMER_CTL0_CLKSEL_OFS),
DL_TIMERB_CLOCK_SOURCE_CNT6_OVERFLOW = (7U << BTIMER_CTL0_CLKSEL_OFS),
DL_TIMERB_CLOCK_SOURCE_EVENT1 = (8U << BTIMER_CTL0_CLKSEL_OFS),
DL_TIMERB_CLOCK_SOURCE_EVENT2 = (9U << BTIMER_CTL0_CLKSEL_OFS),
DL_TIMERB_CLOCK_SOURCE_EVENT3 = (10U << BTIMER_CTL0_CLKSEL_OFS),
DL_TIMERB_CLOCK_SOURCE_EVENT4 = (11U << BTIMER_CTL0_CLKSEL_OFS),
DL_TIMERB_CLOCK_SOURCE_EVENT5 = (12U << BTIMER_CTL0_CLKSEL_OFS),
DL_TIMERB_CLOCK_SOURCE_EVENT6 = (13U << BTIMER_CTL0_CLKSEL_OFS),
DL_TIMERB_CLOCK_SOURCE_EVENT7 = (14U << BTIMER_CTL0_CLKSEL_OFS),
DL_TIMERB_CLOCK_SOURCE_SUBSCRIBER_EVENT = (15U << BTIMER_CTL0_CLKSEL_OFS)
}
enum DL_TIMERB_START_SOURCE {
DL_TIMERB_START_SOURCE_UNUSED = (0U << BTIMER_CTL0_STARTSEL_OFS),
DL_TIMERB_START_SOURCE_CNT0_OVERFLOW = (1U << BTIMER_CTL0_STARTSEL_OFS),
DL_TIMERB_START_SOURCE_CNT1_OVERFLOW = (2U << BTIMER_CTL0_STARTSEL_OFS),
DL_TIMERB_START_SOURCE_CNT2_OVERFLOW = (3U << BTIMER_CTL0_STARTSEL_OFS),
DL_TIMERB_START_SOURCE_CNT3_OVERFLOW = (4U << BTIMER_CTL0_STARTSEL_OFS),
DL_TIMERB_START_SOURCE_CNT4_OVERFLOW = (5U << BTIMER_CTL0_STARTSEL_OFS),
DL_TIMERB_START_SOURCE_CNT5_OVERFLOW = (6U << BTIMER_CTL0_STARTSEL_OFS),
DL_TIMERB_START_SOURCE_CNT6_OVERFLOW = (7U << BTIMER_CTL0_STARTSEL_OFS),
DL_TIMERB_START_SOURCE_EVENT1 = (8U << BTIMER_CTL0_STARTSEL_OFS),
DL_TIMERB_START_SOURCE_EVENT2 = (9U << BTIMER_CTL0_STARTSEL_OFS),
DL_TIMERB_START_SOURCE_EVENT3 = (10U << BTIMER_CTL0_STARTSEL_OFS),
DL_TIMERB_START_SOURCE_EVENT4 = (11U << BTIMER_CTL0_STARTSEL_OFS),
DL_TIMERB_START_SOURCE_EVENT5 = (12U << BTIMER_CTL0_STARTSEL_OFS),
DL_TIMERB_START_SOURCE_EVENT6 = (13U << BTIMER_CTL0_STARTSEL_OFS),
DL_TIMERB_START_SOURCE_EVENT7 = (14U << BTIMER_CTL0_STARTSEL_OFS),
DL_TIMERB_START_SOURCE_SUBSCRIBER_EVENT
}
enum DL_TIMERB_STOP_SOURCE {
DL_TIMERB_STOP_SOURCE_UNUSED = (0U << BTIMER_CTL0_STOPSEL_OFS),
DL_TIMERB_STOP_SOURCE_CNT0_OVERFLOW = (1U << BTIMER_CTL0_STOPSEL_OFS),
DL_TIMERB_STOP_SOURCE_CNT1_OVERFLOW = (2U << BTIMER_CTL0_STOPSEL_OFS),
DL_TIMERB_STOP_SOURCE_CNT2_OVERFLOW = (3U << BTIMER_CTL0_STOPSEL_OFS),
DL_TIMERB_STOP_SOURCE_CNT3_OVERFLOW = (4U << BTIMER_CTL0_STOPSEL_OFS),
DL_TIMERB_STOP_SOURCE_CNT4_OVERFLOW = (5U << BTIMER_CTL0_STOPSEL_OFS),
DL_TIMERB_STOP_SOURCE_CNT5_OVERFLOW = (6U << BTIMER_CTL0_STOPSEL_OFS),
DL_TIMERB_STOP_SOURCE_CNT6_OVERFLOW = (7U << BTIMER_CTL0_STOPSEL_OFS),
DL_TIMERB_STOP_SOURCE_EVENT1 = (8U << BTIMER_CTL0_STOPSEL_OFS),
DL_TIMERB_STOP_SOURCE_EVENT2 = (9U << BTIMER_CTL0_STOPSEL_OFS),
DL_TIMERB_STOP_SOURCE_EVENT3 = (10U << BTIMER_CTL0_STOPSEL_OFS),
DL_TIMERB_STOP_SOURCE_EVENT4 = (11U << BTIMER_CTL0_STOPSEL_OFS),
DL_TIMERB_STOP_SOURCE_EVENT5 = (12U << BTIMER_CTL0_STOPSEL_OFS),
DL_TIMERB_STOP_SOURCE_EVENT6 = (13U << BTIMER_CTL0_STOPSEL_OFS),
DL_TIMERB_STOP_SOURCE_EVENT7 = (14U << BTIMER_CTL0_STOPSEL_OFS),
DL_TIMERB_STOP_SOURCE_SUBSCRIBER_EVENT = (15U << BTIMER_CTL0_STOPSEL_OFS)
}
enum DL_TIMERB_RESET_SOURCE {
DL_TIMERB_RESET_SOURCE_UNUSED = (0U << BTIMER_CTL0_RESETSEL_OFS),
DL_TIMERB_RESET_SOURCE_CNT0_OVERFLOW = (1U << BTIMER_CTL0_RESETSEL_OFS),
DL_TIMERB_RESET_SOURCE_CNT1_OVERFLOW = (2U << BTIMER_CTL0_RESETSEL_OFS),
DL_TIMERB_RESET_SOURCE_CNT2_OVERFLOW = (3U << BTIMER_CTL0_RESETSEL_OFS),
DL_TIMERB_RESET_SOURCE_CNT3_OVERFLOW = (4U << BTIMER_CTL0_RESETSEL_OFS),
DL_TIMERB_RESET_SOURCE_CNT4_OVERFLOW = (5U << BTIMER_CTL0_RESETSEL_OFS),
DL_TIMERB_RESET_SOURCE_CNT5_OVERFLOW = (6U << BTIMER_CTL0_RESETSEL_OFS),
DL_TIMERB_RESET_SOURCE_CNT6_OVERFLOW = (7U << BTIMER_CTL0_RESETSEL_OFS),
DL_TIMERB_RESET_SOURCE_EVENT1 = (8U << BTIMER_CTL0_RESETSEL_OFS),
DL_TIMERB_RESET_SOURCE_EVENT2 = (9U << BTIMER_CTL0_RESETSEL_OFS),
DL_TIMERB_RESET_SOURCE_EVENT3 = (10U << BTIMER_CTL0_RESETSEL_OFS),
DL_TIMERB_RESET_SOURCE_EVENT4 = (11U << BTIMER_CTL0_RESETSEL_OFS),
DL_TIMERB_RESET_SOURCE_EVENT5 = (12U << BTIMER_CTL0_RESETSEL_OFS),
DL_TIMERB_RESET_SOURCE_EVENT6 = (13U << BTIMER_CTL0_RESETSEL_OFS),
DL_TIMERB_RESET_SOURCE_EVENT7 = (14U << BTIMER_CTL0_RESETSEL_OFS),
DL_TIMERB_RESET_SOURCE_SUBSCRIBER_EVENT
}
enum DL_TIMERB_IIDX {
DL_TIMERB_IIDX_ZERO = BTIMER_CPU_INT_IIDX_STAT_NO_INTR,
DL_TIMERB_IIDX_CNT0_OVERFLOW = BTIMER_CPU_INT_IIDX_STAT_CNT0OVF,
DL_TIMERB_IIDX_CNT0_START = BTIMER_CPU_INT_IIDX_STAT_CNT0STRT,
DL_TIMERB_IIDX_CNT0_STOP = BTIMER_CPU_INT_IIDX_STAT_CNT0STOP,
DL_TIMERB_IIDX_CNT1_OVERFLOW = BTIMER_CPU_INT_IIDX_STAT_CNT1OVF,
DL_TIMERB_IIDX_CNT1_START = BTIMER_CPU_INT_IIDX_STAT_CNT1STRT,
DL_TIMERB_IIDX_CNT1_STOP = BTIMER_CPU_INT_IIDX_STAT_CNT1STOP,
DL_TIMERB_IIDX_CNT2_OVERFLOW = BTIMER_CPU_INT_IIDX_STAT_CNT2OVF,
DL_TIMERB_IIDX_CNT2_START = BTIMER_CPU_INT_IIDX_STAT_CNT2STRT,
DL_TIMERB_IIDX_CNT2_STOP = BTIMER_CPU_INT_IIDX_STAT_CNT2STOP,
DL_TIMERB_IIDX_CNT3_OVERFLOW = BTIMER_CPU_INT_IIDX_STAT_CNT3OVF,
DL_TIMERB_IIDX_CNT3_START = BTIMER_CPU_INT_IIDX_STAT_CNT3STRT,
DL_TIMERB_IIDX_CNT3_STOP = BTIMER_CPU_INT_IIDX_STAT_CNT3STOP,
DL_TIMERB_IIDX_CNT4_OVERFLOW = BTIMER_CPU_INT_IIDX_STAT_CNT4OVF,
DL_TIMERB_IIDX_CNT4_START = BTIMER_CPU_INT_IIDX_STAT_CNT4STRT,
DL_TIMERB_IIDX_CNT4_STOP = BTIMER_CPU_INT_IIDX_STAT_CNT4STOP,
DL_TIMERB_IIDX_CNT5_OVERFLOW = BTIMER_CPU_INT_IIDX_STAT_CNT5OVF,
DL_TIMERB_IIDX_CNT5_START = BTIMER_CPU_INT_IIDX_STAT_CNT5STRT,
DL_TIMERB_IIDX_CNT5_STOP = BTIMER_CPU_INT_IIDX_STAT_CNT5STOP,
DL_TIMERB_IIDX_CNT6_OVERFLOW = BTIMER_CPU_INT_IIDX_STAT_CNT6OVF,
DL_TIMERB_IIDX_CNT6_START = BTIMER_CPU_INT_IIDX_STAT_CNT6STRT,
DL_TIMERB_IIDX_CNT6_STOP = BTIMER_CPU_INT_IIDX_STAT_CNT6STOP,
DL_TIMERB_IIDX_CNT7_OVERFLOW = BTIMER_CPU_INT_IIDX_STAT_CNT7OVF,
DL_TIMERB_IIDX_CNT7_START = BTIMER_CPU_INT_IIDX_STAT_CNT7STRT,
DL_TIMERB_IIDX_CNT7_STOP = BTIMER_CPU_INT_IIDX_STAT_CNT7STOP
}
enum DL_TIMERB_CORE_HALT {
DL_TIMERB_CORE_HALT_IMMEDIATE,
DL_TIMERB_CORE_HALT_DELAYED,
DL_TIMERB_CORE_HALT_FREE_RUN
}
Functions
__STATIC_INLINE void DL_TimerB_enablePower (BTIMER_Regs *const timerb)
Enables the Peripheral Write Enable (PWREN) register for the timer.
__STATIC_INLINE void DL_TimerB_disablePower (BTIMER_Regs *const timerb)
Disables the Peripheral Write Enable (PWREN) register for the timer.
__STATIC_INLINE bool DL_TimerB_isPowerEnabled (BTIMER_Regs *const timerb)
Returns if the Peripheral Write Enable (PWREN) register for the timer is enabled.
__STATIC_INLINE void DL_TimerB_reset (BTIMER_Regs *const timerb)
Resets timer peripheral.
__STATIC_INLINE void DL_TimerB_clearResetFlag (BTIMER_Regs *const timerb)
Clear timer peripheral reset assert flag.
__STATIC_INLINE bool DL_TimerB_isReset (BTIMER_Regs *const timerb)
Returns if timer peripheral has been reset.
__STATIC_INLINE void DL_TimerB_setLoadValue (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx, uint16_t value)
Sets timer load value.
__STATIC_INLINE uint16_t DL_TimerB_getLoadValue (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Gets the timer load value.
__STATIC_INLINE void DL_TimerB_setTimerCount (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx, uint16_t value)
Set timer counter value.
__STATIC_INLINE uint16_t DL_TimerB_getTimerCount (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Gets the current counter value of the timer.
void DL_TimerB_initTimer (BTIMER_Regs *const timerb, DL_TimerB_TimerConfig *const config, DL_TIMERB_COUNTER_IDX idx)
Initializes all the configurable options for the Basic Timer.
__STATIC_INLINE void DL_TimerB_startCounter (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Starts timer counter.
__STATIC_INLINE void DL_TimerB_stopCounter (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Stops timer counter.
__STATIC_INLINE bool DL_TimerB_isRunning (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Check if timer is actively running.
__STATIC_INLINE void DL_TimerB_setTimerStartSource (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx, DL_TIMERB_START_SOURCE startSource)
Set timer start source.
__STATIC_INLINE DL_TIMERB_START_SOURCE DL_TimerB_getTimerStartSource (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Gets timer start source.
__STATIC_INLINE void DL_TimerB_setTimerStopSource (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx, DL_TIMERB_STOP_SOURCE stopSource)
Set timer stop source.
__STATIC_INLINE DL_TIMERB_STOP_SOURCE DL_TimerB_getTimerStopSource (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Gets timer stop source.
__STATIC_INLINE void DL_TimerB_setTimerResetSource (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx, DL_TIMERB_RESET_SOURCE resetSource)
Set timer reset source.
__STATIC_INLINE DL_TIMERB_RESET_SOURCE DL_TimerB_getTimerResetSource (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Gets timer reset source.
__STATIC_INLINE void DL_TimerB_setTimerClockSource (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx, DL_TIMERB_CLOCK_SOURCE clockSource)
Set timer clock source.
__STATIC_INLINE DL_TIMERB_CLOCK_SOURCE DL_TimerB_getTimerClockSource (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Gets timer clock source.
__STATIC_INLINE void DL_TimerB_enableInterrupt (BTIMER_Regs *const timerb, uint32_t interruptMask)
Enable timer interrupts.
__STATIC_INLINE void DL_TimerB_disableInterrupt (BTIMER_Regs *const timerb, uint32_t interruptMask)
Disable timer interrupts.
__STATIC_INLINE uint32_t DL_TimerB_getEnabledInterrupts (BTIMER_Regs *const timerb, uint32_t interruptMask)
Check which timer interrupts are enabled.
__STATIC_INLINE uint32_t DL_TimerB_getEnabledInterruptStatus (BTIMER_Regs *const timerb, uint32_t interruptMask)
Check interrupt flag of enabled timer interrupts.
__STATIC_INLINE uint32_t DL_TimerB_getRawInterruptStatus (BTIMER_Regs *const timerb, uint32_t interruptMask)
Check interrupt flag of any timer interrupt.
__STATIC_INLINE DL_TIMERB_IIDX DL_TimerB_getPendingInterrupt (BTIMER_Regs *const timerb)
Get highest priority pending timer interrupt.
__STATIC_INLINE void DL_TimerB_clearInterruptStatus (BTIMER_Regs *const timerb, uint32_t interruptMask)
Clear pending timer interrupts.
__STATIC_INLINE void DL_TimerB_setPublisherChanID (BTIMER_Regs *const timerb, uint8_t chanID)
Sets the event publisher channel ID.
__STATIC_INLINE uint8_t DL_TimerB_getPublisherChanID (BTIMER_Regs *const timerb)
Gets the event publisher channel ID.
__STATIC_INLINE void DL_TimerB_setSubscriberChanID (BTIMER_Regs *const timerb, uint8_t chanID)
Sets the event subscriber channel ID.
__STATIC_INLINE uint8_t DL_TimerB_getSubscriberChanID (BTIMER_Regs *const timerb)
Gets the event subscriber channel ID.
__STATIC_INLINE void DL_TimerB_enableEvent (BTIMER_Regs *const timerb, uint32_t eventMask)
Enable timer event.
__STATIC_INLINE void DL_TimerB_disableEvent (BTIMER_Regs *const timerb, uint32_t eventMask)
Disable timer event.
__STATIC_INLINE uint32_t DL_TimerB_getEnabledEvents (BTIMER_Regs *const timerb, uint32_t eventMask)
Check which timer events are enabled.
__STATIC_INLINE uint32_t DL_TimerB_getEnabledEventStatus (BTIMER_Regs *const timerb, uint32_t eventMask)
Check event flag of enabled timer event.
__STATIC_INLINE uint32_t DL_TimerB_getRawEventsStatus (BTIMER_Regs *const timerb, uint32_t eventMask)
Check interrupt flag of any timer event.
__STATIC_INLINE void DL_TimerB_clearEventsStatus (BTIMER_Regs *const timerb, uint32_t eventMask)
Clear pending timer events.
__STATIC_INLINE void DL_TimerB_setCoreHaltBehavior (BTIMER_Regs *const timerb, DL_TIMERB_CORE_HALT haltMode)
Configures timer behavior when the core is halted.
__STATIC_INLINE DL_TIMERB_CORE_HALT DL_TimerB_getCoreHaltBehavior (BTIMER_Regs *const timerb)
Get timer behavior when the core is halted.
Detailed Description
Overview
The Basic Timer (BTIM) Driver Library allows full configuration of the MSPM0 BTIM module. The BTIM module is an array of counters which can generate periodic interrupts, be concatenated to create longer time durations, and measure timing properties of external events.
Enumeration Type Documentation
DL_TIMERB_COUNTER_IDX
enum DL_TIMERB_COUNTER_IDX
Enumerator
DL_TIMERB_COUNTER_IDX_0
BTimer counter index 0
DL_TIMERB_COUNTER_IDX_1
BTimer counter index 1
DL_TIMERB_COUNTER_IDX_2
BTimer counter index 2
DL_TIMERB_COUNTER_IDX_3
BTimer counter index 3
DL_TIMERB_COUNTER_IDX_4
BTimer counter index 4
DL_TIMERB_COUNTER_IDX_5
BTimer counter index 5
DL_TIMERB_COUNTER_IDX_6
BTimer counter index 6
DL_TIMERB_COUNTER_IDX_7
BTimer counter index 7
DL_TIMERB_CLOCK_SOURCE
enum DL_TIMERB_CLOCK_SOURCE
Enumerator
DL_TIMERB_CLOCK_SOURCE_BUSCLK
Selects BUSCLK as clock source
DL_TIMERB_CLOCK_SOURCE_CNT0_OVERFLOW
Selects overflow from counter 0 as clock source
DL_TIMERB_CLOCK_SOURCE_CNT1_OVERFLOW
Selects overflow from counter 1 as clock source
DL_TIMERB_CLOCK_SOURCE_CNT2_OVERFLOW
Selects overflow from counter 2 as clock source
DL_TIMERB_CLOCK_SOURCE_CNT3_OVERFLOW
Selects overflow from counter 3 as clock source
DL_TIMERB_CLOCK_SOURCE_CNT4_OVERFLOW
Selects overflow from counter 4 as clock source
DL_TIMERB_CLOCK_SOURCE_CNT5_OVERFLOW
Selects overflow from counter 5 as clock source
DL_TIMERB_CLOCK_SOURCE_CNT6_OVERFLOW
Selects overflow from counter 6 as clock source
DL_TIMERB_CLOCK_SOURCE_EVENT1
Selects external event 1 as clock source
DL_TIMERB_CLOCK_SOURCE_EVENT2
Selects external event 2 as clock source
DL_TIMERB_CLOCK_SOURCE_EVENT3
Selects external event 3 as clock source
DL_TIMERB_CLOCK_SOURCE_EVENT4
Selects external event 4 as clock source
DL_TIMERB_CLOCK_SOURCE_EVENT5
Selects external event 5 as clock source
DL_TIMERB_CLOCK_SOURCE_EVENT6
Selects external event 6 as clock source
DL_TIMERB_CLOCK_SOURCE_EVENT7
Selects external event 7 as clock source
DL_TIMERB_CLOCK_SOURCE_SUBSCRIBER_EVENT
Selects subscriber event as clock source
DL_TIMERB_START_SOURCE
enum DL_TIMERB_START_SOURCE
Enumerator
DL_TIMERB_START_SOURCE_UNUSED
Start source is unused
DL_TIMERB_START_SOURCE_CNT0_OVERFLOW
Selects overflow from counter 0 as start source
DL_TIMERB_START_SOURCE_CNT1_OVERFLOW
Selects overflow from counter 1 as start source
DL_TIMERB_START_SOURCE_CNT2_OVERFLOW
Selects overflow from counter 2 as start source
DL_TIMERB_START_SOURCE_CNT3_OVERFLOW
Selects overflow from counter 3 as start source
DL_TIMERB_START_SOURCE_CNT4_OVERFLOW
Selects overflow from counter 4 as start source
DL_TIMERB_START_SOURCE_CNT5_OVERFLOW
Selects overflow from counter 5 as start source
DL_TIMERB_START_SOURCE_CNT6_OVERFLOW
Selects overflow from counter 6 as start source
DL_TIMERB_START_SOURCE_EVENT1
Selects external event 1 as start source
DL_TIMERB_START_SOURCE_EVENT2
Selects external event 2 as start source
DL_TIMERB_START_SOURCE_EVENT3
Selects external event 3 as start source
DL_TIMERB_START_SOURCE_EVENT4
Selects external event 4 as start source
DL_TIMERB_START_SOURCE_EVENT5
Selects external event 5 as start source
DL_TIMERB_START_SOURCE_EVENT6
Selects external event 6 as start source
DL_TIMERB_START_SOURCE_EVENT7
Selects external event 7 as start source
DL_TIMERB_START_SOURCE_SUBSCRIBER_EVENT
Selects subscriber event as start source
DL_TIMERB_STOP_SOURCE
enum DL_TIMERB_STOP_SOURCE
Enumerator
DL_TIMERB_STOP_SOURCE_UNUSED
Stop source is unused
DL_TIMERB_STOP_SOURCE_CNT0_OVERFLOW
Selects overflow from counter 0 as stop source
DL_TIMERB_STOP_SOURCE_CNT1_OVERFLOW
Selects overflow from counter 1 as stop source
DL_TIMERB_STOP_SOURCE_CNT2_OVERFLOW
Selects overflow from counter 2 as stop source
DL_TIMERB_STOP_SOURCE_CNT3_OVERFLOW
Selects overflow from counter 3 as stop source
DL_TIMERB_STOP_SOURCE_CNT4_OVERFLOW
Selects overflow from counter 4 as stop source
DL_TIMERB_STOP_SOURCE_CNT5_OVERFLOW
Selects overflow from counter 5 as stop source
DL_TIMERB_STOP_SOURCE_CNT6_OVERFLOW
Selects overflow from counter 6 as stop source
DL_TIMERB_STOP_SOURCE_EVENT1
Selects external event 1 as stop source
DL_TIMERB_STOP_SOURCE_EVENT2
Selects external event 2 as stop source
DL_TIMERB_STOP_SOURCE_EVENT3
Selects external event 3 as stop source
DL_TIMERB_STOP_SOURCE_EVENT4
Selects external event 4 as stop source
DL_TIMERB_STOP_SOURCE_EVENT5
Selects external event 5 as stop source
DL_TIMERB_STOP_SOURCE_EVENT6
Selects external event 6 as stop source
DL_TIMERB_STOP_SOURCE_EVENT7
Selects external event 7 as stop source
DL_TIMERB_STOP_SOURCE_SUBSCRIBER_EVENT
Selects subscriber event as stop source
DL_TIMERB_RESET_SOURCE
enum DL_TIMERB_RESET_SOURCE
Enumerator
DL_TIMERB_RESET_SOURCE_UNUSED
Reset source is unused
DL_TIMERB_RESET_SOURCE_CNT0_OVERFLOW
Selects overflow from counter 0 as reset source
DL_TIMERB_RESET_SOURCE_CNT1_OVERFLOW
Selects overflow from counter 1 as reset source
DL_TIMERB_RESET_SOURCE_CNT2_OVERFLOW
Selects overflow from counter 2 as reset source
DL_TIMERB_RESET_SOURCE_CNT3_OVERFLOW
Selects overflow from counter 3 as reset source
DL_TIMERB_RESET_SOURCE_CNT4_OVERFLOW
Selects overflow from counter 4 as reset source
DL_TIMERB_RESET_SOURCE_CNT5_OVERFLOW
Selects overflow from counter 5 as reset source
DL_TIMERB_RESET_SOURCE_CNT6_OVERFLOW
Selects overflow from counter 6 as reset source
DL_TIMERB_RESET_SOURCE_EVENT1
Selects external event 1 as reset source
DL_TIMERB_RESET_SOURCE_EVENT2
Selects external event 2 as reset source
DL_TIMERB_RESET_SOURCE_EVENT3
Selects external event 3 as reset source
DL_TIMERB_RESET_SOURCE_EVENT4
Selects external event 4 as reset source
DL_TIMERB_RESET_SOURCE_EVENT5
Selects external event 5 as reset source
DL_TIMERB_RESET_SOURCE_EVENT6
Selects external event 6 as reset source
DL_TIMERB_RESET_SOURCE_EVENT7
Selects external event 7 as reset source
DL_TIMERB_RESET_SOURCE_SUBSCRIBER_EVENT
Selects subscriber event as reset source
DL_TIMERB_IIDX
enum DL_TIMERB_IIDX
Enumerator
DL_TIMERB_IIDX_ZERO
Timer interrupt index for no pending interrupt
DL_TIMERB_IIDX_CNT0_OVERFLOW
Timer interrupt index for counter 0 period match interrupt
DL_TIMERB_IIDX_CNT0_START
Timer interrupt index for counter 0 start interrupt
DL_TIMERB_IIDX_CNT0_STOP
Timer interrupt index for counter 0 stop interrupt
DL_TIMERB_IIDX_CNT1_OVERFLOW
Timer interrupt index for counter 1 period match interrupt
DL_TIMERB_IIDX_CNT1_START
Timer interrupt index for counter 1 start interrupt
DL_TIMERB_IIDX_CNT1_STOP
Timer interrupt index for counter 1 stop interrupt
DL_TIMERB_IIDX_CNT2_OVERFLOW
Timer interrupt index for counter 2 period match interrupt
DL_TIMERB_IIDX_CNT2_START
Timer interrupt index for counter 2 start interrupt
DL_TIMERB_IIDX_CNT2_STOP
Timer interrupt index for counter 2 stop interrupt
DL_TIMERB_IIDX_CNT3_OVERFLOW
Timer interrupt index for counter 3 period match interrupt
DL_TIMERB_IIDX_CNT3_START
Timer interrupt index for counter 3 start interrupt
DL_TIMERB_IIDX_CNT3_STOP
Timer interrupt index for counter 3 stop interrupt
DL_TIMERB_IIDX_CNT4_OVERFLOW
Timer interrupt index for counter 4 period match interrupt
DL_TIMERB_IIDX_CNT4_START
Timer interrupt index for counter 4 start interrupt
DL_TIMERB_IIDX_CNT4_STOP
Timer interrupt index for counter 4 stop interrupt
DL_TIMERB_IIDX_CNT5_OVERFLOW
Timer interrupt index for counter 5 period match interrupt
DL_TIMERB_IIDX_CNT5_START
Timer interrupt index for counter 5 start interrupt
DL_TIMERB_IIDX_CNT5_STOP
Timer interrupt index for counter 5 stop interrupt
DL_TIMERB_IIDX_CNT6_OVERFLOW
Timer interrupt index for counter 6 period match interrupt
DL_TIMERB_IIDX_CNT6_START
Timer interrupt index for counter 6 start interrupt
DL_TIMERB_IIDX_CNT6_STOP
Timer interrupt index for counter 6 stop interrupt
DL_TIMERB_IIDX_CNT7_OVERFLOW
Timer interrupt index for counter 7 period match interrupt
DL_TIMERB_IIDX_CNT7_START
Timer interrupt index for counter 7 start interrupt
DL_TIMERB_IIDX_CNT7_STOP
Timer interrupt index for counter 7 stop interrupt
DL_TIMERB_CORE_HALT
enum DL_TIMERB_CORE_HALT
Enumerator
DL_TIMERB_CORE_HALT_IMMEDIATE
Counter will halt immediately, even if the resultant state will result in corruption if the system is restarted
DL_TIMERB_CORE_HALT_DELAYED
Counter stops on reaching 0. When the debug halt condition is removed, the counter starts from the current value
DL_TIMERB_CORE_HALT_FREE_RUN
Counter ignores the state of the Core Halted input
Function Documentation
DL_TimerB_enablePower()
__STATIC_INLINE void DL_TimerB_enablePower (BTIMER_Regs *const timerb)
Enables the Peripheral Write Enable (PWREN) register for the timer.
Before any peripheral registers can be configured by software, the peripheral itself must be enabled by writing the ENABLE bit together with the appropriate KEY value to the peripheral's PWREN register.
Parameters
timerb Pointer to the register overlay for the peripheral
DL_TimerB_disablePower()
__STATIC_INLINE void DL_TimerB_disablePower (BTIMER_Regs *const timerb)
Disables the Peripheral Write Enable (PWREN) register for the timer.
When the PWREN.ENABLE bit is cleared, the peripheral's registers are not accessible for read/write operations.
Note
This API does not provide large power savings.
Parameters
timerb Pointer to the register overlay for the peripheral
DL_TimerB_isPowerEnabled()
__STATIC_INLINE bool DL_TimerB_isPowerEnabled (BTIMER_Regs *const timerb)
Returns if the Peripheral Write Enable (PWREN) register for the timer is enabled.
Before any peripheral registers can be configured by software, the peripheral itself must be enabled by writing the ENABLE bit together with the appropriate KEY value to the peripheral's PWREN register.
When the PWREN.ENABLE bit is cleared, the peripheral's registers are not accessible for read/write operations.
Parameters
timerb Pointer to the register overlay for the peripheral
Returns
true if peripheral register access is enabled
false if peripheral register access is disabled
DL_TimerB_reset()
__STATIC_INLINE void DL_TimerB_reset (BTIMER_Regs *const timerb)
Resets timer peripheral.
Parameters
timerb Pointer to the register overlay for the peripheral
DL_TimerB_clearResetFlag()
__STATIC_INLINE void DL_TimerB_clearResetFlag (BTIMER_Regs *const timerb)
Clear timer peripheral reset assert flag.
Clear RESETSTKY bit in STAT register that indicates the peripheral was reset.
Parameters
timerb Pointer to the register overlay for the peripheral
DL_TimerB_isReset()
__STATIC_INLINE bool DL_TimerB_isReset (BTIMER_Regs *const timerb)
Returns if timer peripheral has been reset.
Parameters
timerb Pointer to the register overlay for the peripheral
Returns
true if peripheral was reset
false if peripheral wasn't reset
DL_TimerB_setLoadValue()
__STATIC_INLINE void DL_TimerB_setLoadValue (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx, uint16_t value)
Sets timer load value.
Note
Make sure the timer is not running with DL_TimerB_isRunning() and DL_TimerB_stopCounter() before calling this API, otherwise this API will have no effect
The counter index should not exceed the number of counters on the BTimer instance. Passing an out-of-range index will result in reads returning 0, and writes having no effect
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] idx Counter index. One of DL_TIMERB_COUNTER_IDX. Refer to the device datasheet for the number of counters supported on a BTimer instance
[in] value 16-bit load value. Range of [0, 65535]
See also
DL_TimerB_stopCounter
DL_TimerB_isRunning
DL_TimerB_getLoadValue()
__STATIC_INLINE uint16_t DL_TimerB_getLoadValue (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Gets the timer load value.
Note
The counter index should not exceed the number of counters on the BTimer instance. Passing an out-of-range index will result in reads returning 0, and writes having no effect
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] idx Counter index. One of DL_TIMERB_COUNTER_IDX. Refer to the device datasheet for the number of counters supported on a BTimer instance
Returns
Returns the timer load value. Range of [0, 65535]
DL_TimerB_setTimerCount()
__STATIC_INLINE void DL_TimerB_setTimerCount (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx, uint16_t value)
Set timer counter value.
Note
Make sure the timer is not running with DL_TimerB_isRunning() and DL_TimerB_stopCounter() before calling this API, otherwise this API will have no effect
The counter index should not exceed the number of counters on the BTimer instance. Passing an out-of-range index will result in reads returning 0, and writes having no effect
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] idx Counter index. One of DL_TIMERB_COUNTER_IDX. Refer to the device datasheet for the number of counters supported on a BTimer instance
[in] value 16-bit timer counter value. Range of [0, 65535]
See also
DL_TimerB_stopCounter
DL_TimerB_isRunning
DL_TimerB_getTimerCount()
__STATIC_INLINE uint16_t DL_TimerB_getTimerCount (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Gets the current counter value of the timer.
Note
It is recommended to check that the counter is not running with DL_TimerB_isRunning() and DL_TimerB_stopCounter() before calling this API
The counter index should not exceed the number of counters on the BTimer instance. Passing an out-of-range index will result in reads returning 0, and writes having no effect
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] idx Counter index. One of DL_TIMERB_COUNTER_IDX. Refer to the device datasheet for the number of counters supported on a BTimer instance
Returns
Returns the timer counter 16-bit value. Range of [0, 65535]
See also
DL_TimerB_stopCounter
DL_TimerB_isRunning
References DL_TimerB_initTimer().
DL_TimerB_initTimer()
void DL_TimerB_initTimer (BTIMER_Regs *const timerb, DL_TimerB_TimerConfig *const config, DL_TIMERB_COUNTER_IDX idx)
Initializes all the configurable options for the Basic Timer.
Note
The counter index should not exceed the number of counters on the BTimer instance. Passing an out-of-range index will result in reads returning 0, and writes having no effect
Warning
Counter N cannot use the (N+1)th and beyond's counter overflow as the start, stop, reset, or clock source, to prevent combo loops
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] config Pointer to the mode configuration struct DL_TimerB_TimerConfig.
[in] idx Counter index. One of DL_TIMERB_COUNTER_IDX. Refer to the device datasheet for the number of counters supported on a BTimer instance
Referenced by DL_TimerB_getTimerCount().
DL_TimerB_startCounter()
__STATIC_INLINE void DL_TimerB_startCounter (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Starts timer counter.
Note
The counter index should not exceed the number of counters on the BTimer instance. Passing an out-of-range index will result in reads returning 0, and writes having no effect
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] idx Counter index. One of DL_TIMERB_COUNTER_IDX. Refer to the device datasheet for the number of counters supported on a BTimer instance
DL_TimerB_stopCounter()
__STATIC_INLINE void DL_TimerB_stopCounter (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Stops timer counter.
Note
The counter index should not exceed the number of counters on the BTimer instance. Passing an out-of-range index will result in reads returning 0, and writes having no effect
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] idx Counter index. One of DL_TIMERB_COUNTER_IDX. Refer to the device datasheet for the number of counters supported on a BTimer instance
DL_TimerB_isRunning()
__STATIC_INLINE bool DL_TimerB_isRunning (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Check if timer is actively running.
Note
The counter index should not exceed the number of counters on the BTimer instance. Passing an out-of-range index will result in reads returning 0, and writes having no effect
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] idx Counter index. One of DL_TIMERB_COUNTER_IDX. Refer to the device datasheet for the number of counters supported on a BTimer instance
Returns
Returns the running status of the timer
Return values
true Timer is running
false Timer is not running
DL_TimerB_setTimerStartSource()
__STATIC_INLINE void DL_TimerB_setTimerStartSource (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx, DL_TIMERB_START_SOURCE startSource)
Set timer start source.
Note
Make sure the timer is not running with DL_TimerB_isRunning() and DL_TimerB_stopCounter() before calling this API, otherwise this API will have no effect
The counter index should not exceed the number of counters on the BTimer instance. Passing an out-of-range index will result in reads returning 0, and writes having no effect
Warning
Counter N cannot use the (N+1)th and beyond's counter overflow as the start source, to prevent combo loops
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] idx Counter index. One of DL_TIMERB_COUNTER_IDX. Refer to the device datasheet for the number of counters supported on a BTimer instance
[in] startSource Timer start source. One of DL_TIMERB_START_SOURCE
See also
DL_TimerB_stopCounter
DL_TimerB_isRunning
References DL_Common_updateReg().
DL_TimerB_getTimerStartSource()
__STATIC_INLINE DL_TIMERB_START_SOURCE DL_TimerB_getTimerStartSource (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Gets timer start source.
Note
The counter index should not exceed the number of counters on the BTimer instance. Passing an out-of-range index will result in reads returning 0, and writes having no effect
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] idx Counter index. One of DL_TIMERB_COUNTER_IDX. Refer to the device datasheet for the number of counters supported on a BTimer instance
Returns
Returns the timer start source. One of DL_TIMERB_START_SOURCE
DL_TimerB_setTimerStopSource()
__STATIC_INLINE void DL_TimerB_setTimerStopSource (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx, DL_TIMERB_STOP_SOURCE stopSource)
Set timer stop source.
Note
Make sure the timer is not running with DL_TimerB_isRunning() and DL_TimerB_stopCounter() before calling this API, otherwise this API will have no effect
The counter index should not exceed the number of counters on the BTimer instance. Passing an out-of-range index will result in reads returning 0, and writes having no effect
Warning
Counter N cannot use the (N+1)th and beyond's counter overflow as the stop source, to prevent combo loops
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] idx Counter index. One of DL_TIMERB_COUNTER_IDX. Refer to the device datasheet for the number of counters supported on a BTimer instance
[in] stopSource Timer stop source. One of DL_TIMERB_STOP_SOURCE
See also
DL_TimerB_stopCounter
DL_TimerB_isRunning
References DL_Common_updateReg().
DL_TimerB_getTimerStopSource()
__STATIC_INLINE DL_TIMERB_STOP_SOURCE DL_TimerB_getTimerStopSource (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Gets timer stop source.
Note
The counter index should not exceed the number of counters on the BTimer instance. Passing an out-of-range index will result in reads returning 0, and writes having no effect
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] idx Counter index. One of DL_TIMERB_COUNTER_IDX. Refer to the device datasheet for the number of counters supported on a BTimer instance
Returns
Returns the timer stop source. One of DL_TIMERB_STOP_SOURCE
DL_TimerB_setTimerResetSource()
__STATIC_INLINE void DL_TimerB_setTimerResetSource (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx, DL_TIMERB_RESET_SOURCE resetSource)
Set timer reset source.
Note
Make sure the timer is not running with DL_TimerB_isRunning() and DL_TimerB_stopCounter() before calling this API, otherwise this API will have no effect
The counter index should not exceed the number of counters on the BTimer instance. Passing an out-of-range index will result in reads returning 0, and writes having no effect
Warning
Counter N cannot use the (N+1)th and beyond's counter overflow as the reset source, to prevent combo loops
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] idx Counter index. One of DL_TIMERB_COUNTER_IDX. Refer to the device datasheet for the number of counters supported on a BTimer instance
[in] resetSource Timer reset source. One of DL_TIMERB_RESET_SOURCE
See also
DL_TimerB_stopCounter
DL_TimerB_isRunning
References DL_Common_updateReg().
DL_TimerB_getTimerResetSource()
__STATIC_INLINE DL_TIMERB_RESET_SOURCE DL_TimerB_getTimerResetSource (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Gets timer reset source.
Note
The counter index should not exceed the number of counters on the BTimer instance. Passing an out-of-range index will result in reads returning 0, and writes having no effect
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] idx Counter index. One of DL_TIMERB_COUNTER_IDX. Refer to the device datasheet for the number of counters supported on a BTimer instance
Returns
Returns the timer reset source. One of DL_TIMERB_RESET_SOURCE
DL_TimerB_setTimerClockSource()
__STATIC_INLINE void DL_TimerB_setTimerClockSource (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx, DL_TIMERB_CLOCK_SOURCE clockSource)
Set timer clock source.
Note
Make sure the timer is not running with DL_TimerB_isRunning() and DL_TimerB_stopCounter() before calling this API, otherwise this API will have no effect
The counter index should not exceed the number of counters on the BTimer instance. Passing an out-of-range index will result in reads returning 0, and writes having no effect
Warning
Counter N cannot use the (N+1)th and beyond's counter overflow as the clock source, to prevent combo loops
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] idx Counter index. One of DL_TIMERB_COUNTER_IDX. Refer to the device datasheet for the number of counters supported on a BTimer instance
[in] clockSource Timer clock source. One of DL_TIMERB_CLOCK_SOURCE
See also
DL_TimerB_stopCounter
DL_TimerB_isRunning
References DL_Common_updateReg().
DL_TimerB_getTimerClockSource()
__STATIC_INLINE DL_TIMERB_CLOCK_SOURCE DL_TimerB_getTimerClockSource (BTIMER_Regs *const timerb, DL_TIMERB_COUNTER_IDX idx)
Gets timer clock source.
Note
The counter index should not exceed the number of counters on the BTimer instance. Passing an out-of-range index will result in reads returning 0, and writes having no effect
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] idx Counter index. One of DL_TIMERB_COUNTER_IDX. Refer to the device datasheet for the number of counters supported on a BTimer instance
Returns
Returns the timer clock source. One of DL_TIMERB_CLOCK_SOURCE
DL_TimerB_enableInterrupt()
__STATIC_INLINE void DL_TimerB_enableInterrupt (BTIMER_Regs *const timerb, uint32_t interruptMask)
Enable timer interrupts.
Note
Configuring interrupts for counters not available on a BTimer instance will have no effect
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to enable. Bitwise OR of DL_TIMERB_INTERRUPT. Refer to the device datasheet for the counters supported on a BTimer instance
DL_TimerB_disableInterrupt()
__STATIC_INLINE void DL_TimerB_disableInterrupt (BTIMER_Regs *const timerb, uint32_t interruptMask)
Disable timer interrupts.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to enable. Bitwise OR of DL_TIMERB_INTERRUPT. Refer to the device datasheet for the counters supported on a BTimer instance
DL_TimerB_getEnabledInterrupts()
__STATIC_INLINE uint32_t DL_TimerB_getEnabledInterrupts (BTIMER_Regs *const timerb, uint32_t interruptMask)
Check which timer interrupts are enabled.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to enable. Bitwise OR of DL_TIMERB_INTERRUPT. Refer to the device datasheet for the counters supported on a BTimer instance
Returns
Which of the requested timer interrupts are enabled
Return values
Bitwise OR of DL_TIMERB_INTERRUPT values
DL_TimerB_getEnabledInterruptStatus()
__STATIC_INLINE uint32_t DL_TimerB_getEnabledInterruptStatus (BTIMER_Regs *const timerb, uint32_t interruptMask)
Check interrupt flag of enabled timer interrupts.
Checks if any of the timer interrupts that were previously enabled are pending.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to enable. Bitwise OR of DL_TIMERB_INTERRUPT. Refer to the device datasheet for the counters supported on a BTimer instance
Returns
Which of the requested timer interrupts are pending
Return values
Bitwise OR of DL_TIMERB_INTERRUPT values
See also
DL_TimerB_enableInterrupt
DL_TimerB_getRawInterruptStatus()
__STATIC_INLINE uint32_t DL_TimerB_getRawInterruptStatus (BTIMER_Regs *const timerb, uint32_t interruptMask)
Check interrupt flag of any timer interrupt.
Checks if any of the timer interrupts are pending. Interrupts do not have to be previously enabled.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to enable. Bitwise OR of DL_TIMERB_INTERRUPT. Refer to the device datasheet for the counters supported on a BTimer instance
Returns
Which of the requested timer interrupts are pending
Return values
Bitwise OR of DL_TIMERB_INTERRUPT values
DL_TimerB_getPendingInterrupt()
__STATIC_INLINE DL_TIMERB_IIDX DL_TimerB_getPendingInterrupt (BTIMER_Regs *const timerb)
Get highest priority pending timer interrupt.
Checks if any of the timer interrupts are pending. Interrupts do not have to be previously enabled.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
Returns
The highest priority pending timer interrupt. One of DL_TIMERB_IIDX
DL_TimerB_clearInterruptStatus()
__STATIC_INLINE void DL_TimerB_clearInterruptStatus (BTIMER_Regs *const timerb, uint32_t interruptMask)
Clear pending timer interrupts.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to enable. Bitwise OR of DL_TIMERB_INTERRUPT. Refer to the device datasheet for the counters supported on a BTimer instance
DL_TimerB_setPublisherChanID()
__STATIC_INLINE void DL_TimerB_setPublisherChanID (BTIMER_Regs *const timerb, uint8_t chanID)
Sets the event publisher channel ID.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] chanID Channel ID number. Valid range 0-15. If ChanID == 0 publisher is disconnected.
DL_TimerB_getPublisherChanID()
__STATIC_INLINE uint8_t DL_TimerB_getPublisherChanID (BTIMER_Regs *const timerb)
Gets the event publisher channel ID.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
Returns
Event publisher channel ID
DL_TimerB_setSubscriberChanID()
__STATIC_INLINE void DL_TimerB_setSubscriberChanID (BTIMER_Regs *const timerb, uint8_t chanID)
Sets the event subscriber channel ID.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] chanID Channel ID number. Valid range 0-15. If ChanID == 0 subscriber is disconnected.
DL_TimerB_getSubscriberChanID()
__STATIC_INLINE uint8_t DL_TimerB_getSubscriberChanID (BTIMER_Regs *const timerb)
Gets the event subscriber channel ID.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
Returns
Event subscriber channel ID
DL_TimerB_enableEvent()
__STATIC_INLINE void DL_TimerB_enableEvent (BTIMER_Regs *const timerb, uint32_t eventMask)
Enable timer event.
Note
Configuring events for counters not available on a BTimer instance will have no effect
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to enable. Bitwise OR of DL_TIMERB_EVENT. Refer to the device datasheet for the counters supported on a BTimer instance
DL_TimerB_disableEvent()
__STATIC_INLINE void DL_TimerB_disableEvent (BTIMER_Regs *const timerb, uint32_t eventMask)
Disable timer event.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to enable. Bitwise OR of DL_TIMERB_EVENT. Refer to the device datasheet for the counters supported on a BTimer instance
DL_TimerB_getEnabledEvents()
__STATIC_INLINE uint32_t DL_TimerB_getEnabledEvents (BTIMER_Regs *const timerb, uint32_t eventMask)
Check which timer events are enabled.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to enable. Bitwise OR of DL_TIMERB_EVENT. Refer to the device datasheet for the counters supported on a BTimer instance
Returns
Which of the requested timer interrupts are enabled
Return values
Bitwise OR of DL_TIMERB_EVENT values
DL_TimerB_getEnabledEventStatus()
__STATIC_INLINE uint32_t DL_TimerB_getEnabledEventStatus (BTIMER_Regs *const timerb, uint32_t eventMask)
Check event flag of enabled timer event.
Checks if any of the timer events that were previously enabled are pending.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to enable. Bitwise OR of DL_TIMERB_EVENT. Refer to the device datasheet for the counters supported on a BTimer instance
Returns
Which of the requested timer interrupts are pending
Return values
Bitwise OR of DL_TIMERB_EVENT values
See also
DL_TimerB_enableInterrupt
DL_TimerB_getRawEventsStatus()
__STATIC_INLINE uint32_t DL_TimerB_getRawEventsStatus (BTIMER_Regs *const timerb, uint32_t eventMask)
Check interrupt flag of any timer event.
Checks if any events are pending. Events do not have to be previously enabled.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to enable. Bitwise OR of DL_TIMERB_EVENT. Refer to the device datasheet for the counters supported on a BTimer instance
Returns
Which of the requested timer interrupts are pending
Return values
Bitwise OR of DL_TIMERB_EVENT values
DL_TimerB_clearEventsStatus()
__STATIC_INLINE void DL_TimerB_clearEventsStatus (BTIMER_Regs *const timerb, uint32_t eventMask)
Clear pending timer events.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to enable. Bitwise OR of DL_TIMERB_EVENT. Refer to the device datasheet for the counters supported on a BTimer instance
DL_TimerB_setCoreHaltBehavior()
__STATIC_INLINE void DL_TimerB_setCoreHaltBehavior (BTIMER_Regs *const timerb, DL_TIMERB_CORE_HALT haltMode)
Configures timer behavior when the core is halted.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
[in] haltMode Timer halt behavior. One of DL_TIMERB_CORE_HALT.
DL_TimerB_getCoreHaltBehavior()
__STATIC_INLINE DL_TIMERB_CORE_HALT DL_TimerB_getCoreHaltBehavior (BTIMER_Regs *const timerb)
Get timer behavior when the core is halted.
Parameters
[in] timerb Pointer to the register overlay for the peripheral
Returns
Timer behavior when core is halted. One of DL_TIMERB_CORE_HALT
Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale