MSPM0G3507SensoredFOCMotorControlLibrary: abnormalSpeedStallDetect.h File Reference
abnormalSpeedStallDetect.h File Reference
Detailed Description
abnormalSpeedStallDetect Module
Overview
#include "stdint.h"
Data Structures
union ABNORMAL_SPEED_STALL_DETECT_FLAGS_T
Abnormal Speed Detect flags Structure.
struct ABNORMAL_SPEED_STALL_DETECT_FLAGS_T::abnormalSpeedStallDetectFlags
Abnormal Speed Detect flags.
struct ABNORMAL_SPEED_STALL_DETECT_T
Abnormal Speed Detect Working Structure.
Functions
void abnormalSpeedStallDetectInit (ABNORMAL_SPEED_STALL_DETECT_T *pAbnormalSpeed)
Abnormal Speed Detect Init.
void abnormalSpeedStallDetectRun (ABNORMAL_SPEED_STALL_DETECT_T *pAbnormalSpeed)
Abnormal Speed Detect Run.
_Bool getAbnormalSpeedStallDetectStatus (ABNORMAL_SPEED_STALL_DETECT_T *pAbnormalSpeedStall)
Abnormal Speed Detect Status check.
Function Documentation
abnormalSpeedStallDetectInit()
void abnormalSpeedStallDetectInit (ABNORMAL_SPEED_STALL_DETECT_T * pAbnormalSpeed)
Abnormal Speed Detect Init.
Parameters
[in] *pAbnormalSpeed Input Pointer
References ABNORMAL_SPEED_STALL_DETECT_FLAGS_T::b, ABNORMAL_SPEED_STALL_DETECT_T::count, ABNORMAL_SPEED_STALL_DETECT_FLAGS_T::abnormalSpeedStallDetectFlags::enable, FALSE, and ABNORMAL_SPEED_STALL_DETECT_T::flags.
Referenced by stallDetectInit().
abnormalSpeedStallDetectRun()
void abnormalSpeedStallDetectRun (ABNORMAL_SPEED_STALL_DETECT_T * pAbnormalSpeed)
Abnormal Speed Detect Run.
Parameters
[in] *pAbnormalSpeed Input Pointer
References ABNORMAL_SPEED_STALL_DETECT_FLAGS_T::b, ABNORMAL_SPEED_STALL_DETECT_T::count, ABNORMAL_SPEED_STALL_DETECT_T::countMax, ABNORMAL_SPEED_STALL_DETECT_T::flags, ABNORMAL_SPEED_STALL_DETECT_T::maximumSpeed, ABNORMAL_SPEED_STALL_DETECT_T::pSpeed, ABNORMAL_SPEED_STALL_DETECT_FLAGS_T::abnormalSpeedStallDetectFlags::status, and TRUE.
Referenced by stallDetectLowPriorityRun().
getAbnormalSpeedStallDetectStatus()
_Bool getAbnormalSpeedStallDetectStatus (ABNORMAL_SPEED_STALL_DETECT_T * pAbnormalSpeedStall) inline
Abnormal Speed Detect Status check.
Parameters
[in] *pAbnormalSpeedStall Pointer
Returns
Returns the status
References ABNORMAL_SPEED_STALL_DETECT_FLAGS_T::b, ABNORMAL_SPEED_STALL_DETECT_T::flags, and ABNORMAL_SPEED_STALL_DETECT_FLAGS_T::abnormalSpeedStallDetectFlags::status.
Referenced by stallDetectLowPriorityRun().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale