MSPM0G3507SensoredFOCMotorControlLibrary: appInterfaceConfig.h File Reference
appInterfaceConfig.h File Reference
Detailed Description
appInterfaceConfig Module
Overview
APIs for updating the appInterface configurations
#include "application.h"
Macros
#define VOLTAGE_MAGNITUDE_FILTER_CONST _IQ(0.1)
Voltage Magnitude Filter Constant.
Functions
void appInterfaceConfig (SENSORED_FOC_APPLICATION_T *pMC_App)
appInterfaceConfig
void appInterfaceEEpromConfig (SENSORED_FOC_APPLICATION_T *pMC_App)
appInterfaceEEpromConfig
Function Documentation
appInterfaceConfig()
void appInterfaceConfig (SENSORED_FOC_APPLICATION_T * pMC_App)
appInterfaceConfig
Parameters
[in] *pMC_App Input Pointer
References APP_BRAKE, APP_FAULT, APP_IDLE, APP_INIT, MC_DQ_T::d, OUTPUT_DQ_T::d, FOC_T::ddq, filter(), SENSORED_FOC_APPLICATION_T::foc, SENSORED_FOC_APPLICATION_T::pAppInterface, APP_INTERFACE_T::pUserOutputs, MC_DQ_T::q, OUTPUT_DQ_T::q, SENSORED_FOC_APPLICATION_T::state, USER_STATUS_INTERFACE_T::VdqFilt, and VOLTAGE_MAGNITUDE_FILTER_CONST.
Referenced by updateRAMConfigurationParameters().
appInterfaceEEpromConfig()
void appInterfaceEEpromConfig (SENSORED_FOC_APPLICATION_T * pMC_App)
appInterfaceEEpromConfig
Parameters
[in] *pMC_App Input Pointer
References appUserInputRegsConfig(), appUserInputsInterfaceConfig(), SENSORED_FOC_APPLICATION_T::pAppInterface, peri1Config(), APP_INTERFACE_T::userInputs, and APP_INTERFACE_T::userInputsInterface.
Referenced by updateConfigurationParameters().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale