MSPM0G3507SensoredFOCMotorControlLibrary: brake.h File Reference
brake.h File Reference
Detailed Description
brake Module
Overview
#include "stdint.h"
#include "mcLib.h"
#include "measure.h"
Data Structures
union BRAKE_FLAGS_T
Brake Flags Working Structure.
struct BRAKE_FLAGS_T::brakeFlags
Brake Flags Structure.
struct BRAKE_T
Brake variable Working Structure.
Functions
void brakeInit (BRAKE_T *pBrake)
Brake Init.
void brakeRun (BRAKE_T *pBrake)
Brake Run.
void brakeLowPriorityRun (BRAKE_T *pBrake)
Brake Low Priority Run.
_Bool getBrakeStatusCurrent (BRAKE_T *pBrake)
Brake Current Status check.
_Bool getBrakeStatusTimeOut (BRAKE_T *pBrake)
Brake Timout Status check.
Function Documentation
brakeInit()
void brakeInit (BRAKE_T * pBrake)
Brake Init.
Parameters
[in] *pBrake Input Pointer
References BRAKE_FLAGS_T::b, FALSE, BRAKE_T::flags, BRAKE_T::motorStopCount, BRAKE_FLAGS_T::brakeFlags::statusCurrent, BRAKE_FLAGS_T::brakeFlags::statusTimeOut, and BRAKE_T::timeOutCount.
Referenced by loadInit(), and loadRun().
brakeRun()
void brakeRun (BRAKE_T * pBrake)
Brake Run.
Parameters
[in] *pBrake Input Pointer
References BRAKE_FLAGS_T::b, BRAKE_T::currentThresholdSqr, BRAKE_T::flags, BRAKE_T::motorStopCount, BRAKE_T::motorStopCountMax, BRAKE_T::pIMagSqr, BRAKE_FLAGS_T::brakeFlags::statusCurrent, and TRUE.
Referenced by loadRun().
brakeLowPriorityRun()
void brakeLowPriorityRun (BRAKE_T * pBrake)
Brake Low Priority Run.
Parameters
[in] *pBrake Input Pointer
References BRAKE_FLAGS_T::b, BRAKE_FLAGS_T::brakeFlags::enableOnFault, BRAKE_T::flags, BRAKE_FLAGS_T::brakeFlags::statusTimeOut, BRAKE_T::timeOutCount, BRAKE_T::timeOutCountMax, and TRUE.
Referenced by loadLowPriorityRun().
getBrakeStatusCurrent()
_Bool getBrakeStatusCurrent (BRAKE_T * pBrake) inline
Brake Current Status check.
Parameters
[in] *pBrake Pointer
Returns
Returns the status
References BRAKE_FLAGS_T::b, BRAKE_T::flags, BRAKE_FLAGS_T::brakeFlags::statusCurrent, and BRAKE_FLAGS_T::brakeFlags::statusTimeOut.
Referenced by loadRun().
getBrakeStatusTimeOut()
_Bool getBrakeStatusTimeOut (BRAKE_T * pBrake) inline
Brake Timout Status check.
Parameters
[in] *pBrake Pointer
Returns
Returns the status
References BRAKE_FLAGS_T::b, BRAKE_T::flags, and BRAKE_FLAGS_T::brakeFlags::statusTimeOut.
Referenced by loadRun().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale