MSPM0G3507SensoredFOCMotorControlLibrary: gateDriver.h File Reference
gateDriver.h File Reference
Detailed Description
Gate Driver Module.
Overview
defines gateDriver APIs
#include "measure.h"
#include "ti_msp_dl_config.h"
#include "appInputCtrlInterface.h"
Macros
#define FOC_CURR_ADC0_INST (ADC0_INST)
FOC current ADC0 instance.
#define FOC_CURR_ADC1_INST (ADC1_INST)
FOC current ADC1 instance.
#define FOC_ADC0_INST (ADC0_INST)
FOC ADC0 instance.
#define FOC_ADC1_INST (ADC1_INST)
FOC ADC1 instance.
#define ADC0_IDX_0 (ADC0_ADCMEM_0)
ADC 0 IDX 0.
#define ADC0_IDX_1 (ADC0_ADCMEM_1)
ADC 0 IDX 1.
#define ADC0_IDX_2 (ADC0_ADCMEM_2)
ADC 0 IDX 2.
#define ADC1_IDX_0 (ADC1_ADCMEM_0)
ADC 1 IDX 0.
#define ADC1_IDX_1 (ADC1_ADCMEM_1)
ADC 1 IDX 1.
#define ADC1_IDX_2 (ADC1_ADCMEM_2)
ADC 1 IDX 1.
#define FOC_CURR_ADC0_IDX_0 (ADC0_ADCMEM_0)
FOC current ADC0 IDX 0.
#define FOC_CURR_ADC0_IDX_1 (ADC0_ADCMEM_1)
FOC current ADC0 IDX 1.
#define FOC_CURR_ADC0_IDX_2 (ADC0_ADCMEM_2)
FOC current ADC1 IDX 2.
#define FOC_CURR_ADC1_IDX_0 (ADC1_ADCMEM_0)
FOC current ADC1 IDX 0.
#define FOC_CURR_ADC1_IDX_1 (ADC1_ADCMEM_1)
FOC current ADC1 IDX 1.
#define FOC_CURR_ADC1_IDX_2 (ADC1_ADCMEM_2)
FOC current ADC1 IDX 2.
Functions
void HAL_GD_ReadCurrents (HAL_MEASURE_CURRENT_T *pCurrent)
Read Current from gate driver.
void HAL_GD_ReadVoltages (HAL_MEASURE_VOLTAGE_T *pVoltage)
Read phase voltage from gate driver.
void HAL_GD_ConfigureVoltageChannels (void)
Configure phase voltage channels.
void HAL_currentReconstruction (HAL_MEASURE_CURRENT_T *pCurrent, MC_SECTOR_TYPES sector)
Reconstruct phase current from bus current.
void HAL_GD_ConfigureCurrentChannels (CURRENT_SHUNT_TYPES currentShunt)
Configure phase current channels.
void HAL_GD_ReadDCVBusVoltage (HAL_MEASURE_VOLTAGE_T *pVoltage)
Reads DC bus voltage.
void gateDriverConfig (void)
Initializes gat driver register configuration.
void gateDriverClearFault (void)
Clears gate driver fault.
uint32_t gateDriverGetFaultStatus (void)
Gets gate driver fault status.
void gateDriverFaultResponse (HV_DIE_EEPROM_INTERFACE_T *pGateDriverConfig)
Response to any occurred fault.
void gateDriverParamsUpdate (HV_DIE_EEPROM_INTERFACE_T *pGateDriverConfig)
Updates gate driver parameters.
void gateDriverCSACalib (void)
Calibrates gate driver CSA.
void gateDriverOffsetCalibSet (void)
Calibrates gate driver CSA offset.
void gateDriverOffsetCalibReset (void)
Calibrates gate driver CSA offset reset.
void gateDriverInit (void)
Initializes gate drive module.
uint16_t gateDriverRegRead (int16_t regAddr)
Reads any gate driver register, used for testing spi communication.
Variables
uint32_t gateDrivernFaultReport
Extern gate driver fault report.
uint32_t gateDriverFaultAction
Extern gate driver fault action.
Function Documentation
HAL_GD_ReadCurrents()
void HAL_GD_ReadCurrents (HAL_MEASURE_CURRENT_T * pCurrent)
Read Current from gate driver.
Parameters
[in] pCurrent Pointer to measure current structure
Referenced by HAL_ReadCurrents().
HAL_GD_ReadVoltages()
void HAL_GD_ReadVoltages (HAL_MEASURE_VOLTAGE_T * pVoltage)
Read phase voltage from gate driver.
Parameters
[in] pVoltage Pointer to measure voltage structure
HAL_currentReconstruction()
void HAL_currentReconstruction (HAL_MEASURE_CURRENT_T * pCurrent, MC_SECTOR_TYPES sector)
Reconstruct phase current from bus current.
Parameters
[in] pCurrent Pointer to measure current structure
[in] sector Voltage sector
Referenced by HAL_ReadCurrents().
HAL_GD_ConfigureCurrentChannels()
void HAL_GD_ConfigureCurrentChannels (CURRENT_SHUNT_TYPES currentShunt)
Configure phase current channels.
Parameters
[in] currentShunt Current shunt type
Referenced by HAL_SetPhaseCurrentChannels().
HAL_GD_ReadDCVBusVoltage()
void HAL_GD_ReadDCVBusVoltage (HAL_MEASURE_VOLTAGE_T * pVoltage)
Reads DC bus voltage.
Parameters
[in] pVoltage Pointer to measure voltage structure
Referenced by HAL_ReadMotorInputs().
gateDriverGetFaultStatus()
uint32_t gateDriverGetFaultStatus (void)
Gets gate driver fault status.
Returns
Returns gate driver fault status
gateDriverFaultResponse()
void gateDriverFaultResponse (HV_DIE_EEPROM_INTERFACE_T * pGateDriverConfig)
Response to any occurred fault.
Parameters
[in] pGateDriverConfig Pointer to HV_DIE_EEPROM_INTERFACE_T structure
gateDriverParamsUpdate()
void gateDriverParamsUpdate (HV_DIE_EEPROM_INTERFACE_T * pGateDriverConfig)
Updates gate driver parameters.
Parameters
[in] pGateDriverConfig Pointer to HV_DIE_EEPROM_INTERFACE_T structure
gateDriverRegRead()
uint16_t gateDriverRegRead (int16_t regAddr)
Reads any gate driver register, used for testing spi communication.
Parameters
[in] regAddr The register to be read
Returns
Returns the register value
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale