MSPM0G3507SensoredFOCMotorControlLibrary: hallCalib.h File Reference
hallCalib.h File Reference
Detailed Description
HALL Calibration module.
Overview
#include "stdint.h"
#include "mcLib.h"
#include "measure.h"
Data Structures
struct HALL_CALIB_T
Hall Calibration Working Structure.
Macros
#define CALIBRATION_ALIGN_ANGLE _IQ(0.125)
ALIGN ANGLE FORWARD - HALL CALIBRATION Applied Voltage Vector from SVM is 90 Degree Phase advanced from Aligned Rotor Position During Align, compensate the offset.
#define CALIBRATION_ANGLE_STEP _IQ(0.5/360.0)
CALIBRATION ANGLE STEP SIZE.
#define HALL_ANGLE_MASK 0x7FFFFFF
HALL angle mask to reset for 27 bits.
#define HALL_ANGLE_OVERFLOW_MASK 0xF8000000
Hall angle Overflow Mask for 27 bits.
Enumerations
enum HALL_CALIBRATION_STATE_e {
HALL_CALIB_INIT = 0,
HAL_CALIB_ALIGN = 1,
HAL_CALIB_RUN_FORWARD = 2,
HAL_CALIB_RUN_REVERSE = 3,
HAL_CALIB_COMPUTE = 4,
HAL_CALIB_COMPLETE = 5,
HAL_CALIB_FAILED = 6
}
HallCalibration State.
Functions
void hallCalibInit (HALL_CALIB_T *pHallCalibHandle)
Hall Calib Init.
void hallCalibRun (HALL_CALIB_T *pHallCalibHandle)
Hall Calib Run.
_Bool getHallCalibStatus (HALL_CALIB_T *pHallCalibHandle)
Get Calib Status.
Enumeration Type Documentation
HALL_CALIBRATION_STATE_e
enum HALL_CALIBRATION_STATE_e
HallCalibration State.
Enumerator
HALL_CALIB_INIT
Hall Calibration State INIT
HAL_CALIB_ALIGN
Hall Calibration State ALIGN
HAL_CALIB_RUN_FORWARD
Hall Calibration State RUN
HAL_CALIB_RUN_REVERSE
Hall Calibration State RUN
HAL_CALIB_COMPUTE
Hall Calibration State Compute
HAL_CALIB_COMPLETE
Hall Calibration State Done
HAL_CALIB_FAILED
Hall Calibration Failed
Function Documentation
hallCalibInit()
void hallCalibInit (HALL_CALIB_T * pHallCalibHandle)
Hall Calib Init.
Parameters
[in] *pHallCalibHandle Input Pointer
References HALL_CALIB_T::calibSectorCount, HALL_CALIB_T::calibState, HALL_CALIB_T::count, FALSE, HALL_CALIB_INIT, HALL_CALIB_T::idRef, HALL_CALIB_T::iqRef, and HALL_CALIB_T::status.
Referenced by focInit().
hallCalibRun()
void hallCalibRun (HALL_CALIB_T * pHallCalibHandle)
Hall Calib Run.
Parameters
[in] *pHallCalibHandle Input Pointer
Hall Angle Error in PU
Hall Angle Offset
Hall Angle Error in PU
Hall Angle Offset
Hall Angle Error in PU
Hall Angle Offset
Hall Angle Error in PU
Hall Angle Offset
References HALL_CALIB_T::angle, CALIBRATION_ALIGN_ANGLE, CALIBRATION_ANGLE_STEP, HALL_CALIB_T::calibSectorCount, HALL_CALIB_T::calibState, HALL_CALIB_T::count, HALL_CALIB_T::countMaxAlign, HALL_CALIB_T::countMaxCalibRun, HAL_CALIB_ALIGN, HAL_CALIB_COMPLETE, HAL_CALIB_COMPUTE, HAL_CALIB_FAILED, HAL_CALIB_RUN_FORWARD, HAL_CALIB_RUN_REVERSE, HALL_ANGLE_MASK, HALL_ANGLE_SUM, HALL_CALIB_INIT, HALL_CALIB_T::hallIndex, HALL_CALIB_T::hallIndexPrev, MAX_HALL_INDEX, HALL_CALIB_T::pHALLIntHandle, HALL_CALIB_T::pHallSectorPerRev, HALL_CALIB_T::polePairs, HALL_CALIB_T::pTargetVelocity, HALL_CALIB_T::pThetaHallForwardPU, HALL_CALIB_T::pThetaHallReversePU, ReadHallState(), HALL_CALIB_T::status, and TRUE.
Referenced by focLowPriorityRun().
getHallCalibStatus()
_Bool getHallCalibStatus (HALL_CALIB_T * pHallCalibHandle) inline
Get Calib Status.
Parameters
[in] *pHallCalibHandle Pointer
Returns
Returns the status
References HALL_CALIB_T::status.
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale