MSPM0G3507SensoredFOCMotorControlLibrary: idReferencing.h File Reference
idReferencing.h File Reference
Detailed Description
idReferencing Module
Overview
#include "stdint.h"
#include "fluxWeak.h"
#include "mtpa.h"
Data Structures
union ID_REFERENCING_FLAGS_T
Id reference Flags Structure.
struct ID_REFERENCING_FLAGS_T::idReferencingFlags
Id Ref Flags Structure.
struct ID_REF_T
Id reference Working Structure.
Functions
void idRefInit (ID_REF_T *pIdRef)
Id Reference Init Init.
void idRefLowPriorityRun (ID_REF_T *pIdRef)
Id Reference Low Priority Run.
Function Documentation
idRefInit()
void idRefInit (ID_REF_T * pIdRef)
Id Reference Init Init.
Parameters
[in] *pIdRef Input Pointer
References ID_REF_T::fluxWeak, fluxWeakInit(), ID_REF_T::idRef, ID_REF_T::mtpa, and mtpaInit().
Referenced by closeLoopInit().
idRefLowPriorityRun()
void idRefLowPriorityRun (ID_REF_T * pIdRef)
Id Reference Low Priority Run.
Parameters
[in] *pIdRef Input Pointer
References ID_REFERENCING_FLAGS_T::b, ID_REF_T::flags, ID_REFERENCING_FLAGS_T::idReferencingFlags::fluxModeEnable, ID_REF_T::fluxWeak, ID_REFERENCING_FLAGS_T::idReferencingFlags::fluxWeakeningEnable, fluxWeakRun(), FLUX_WEAK_T::idRef, MTPA_T::idRef, ID_REF_T::idRef, MTPA_T::idRefFilt, ID_REF_T::idRefFluxModeSet, PI_T::kiTerm, ID_REF_T::mtpa, ID_REFERENCING_FLAGS_T::idReferencingFlags::mtpaEnable, mtpaRun(), and FLUX_WEAK_T::piFluxWeak.
Referenced by closeLoopLowPriorityRun().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale