MSPM0G3507SensoredFOCMotorControlLibrary: iqNum.h File Reference
iqNum.h File Reference
Detailed Description
IQ Numeric Module.
Overview
defines for IQ
#include "stdint.h"
Data Structures
struct IQ_NUM_T
IQ_NUM structure.
Functions
void float2IQ (IQ_NUM_T *pIqNum, const float setValue)
Float to IQ conversion.
void float2IQx (int32_t *pIqxNum, const float setValue, const int16_t iqScaling)
Float to IQ conversion with scaling.
Function Documentation
float2IQ()
void float2IQ (IQ_NUM_T * pIqNum, const float setValue)
Float to IQ conversion.
Parameters
[in] pIqNum Pointer to IQ value
[in] setValue float value
References GLOBAL_IQ, IQ_NUM_T::iqScaling, and IQ_NUM_T::scaledNum.
Referenced by updateCurrentControlConfigParam(), and updateRAMConfigurationParameters().
float2IQx()
void float2IQx (int32_t * pIqxNum, const float setValue, const int16_t iqScaling)
Float to IQ conversion with scaling.
Parameters
[in] pIqxNum Pointer to IQ value
[in] setValue float value
[in] iqScaling scaling factor
Referenced by updateCloseLoopConfigParam(), updateCurrentControlConfigParam(), updateRAMConfigurationParameters(), and user_config_faults().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale