MSPM0G3507SensoredFOCMotorControlLibrary: measure.h File Reference
measure.h File Reference
Detailed Description
HAL interface for FOC Module.
Overview
HAL Apis used for measurement from ADC
#include "stdint.h"
#include "mcLib.h"
#include "iqNum.h"
#include "main.h"
#include "hal.h"
#include "hallInterface.h"
Data Structures
struct CURRENT_OFFSET_T
Current offset structure.
struct measureCurrentFlags
measureCurrentFlags structure
union MEASURE_CURRENT_FLAGS_T
Measure current flag.
struct HAL_MEASURE_CURRENT_T
Measure current structure.
struct HAL_MEASURE_VOLTAGE_T
Measure voltage structure.
struct HAL_MEASURE_HALL_HANDLE_T
Measure Hall Index.
struct HAL_MEASURE_MOTOR_INPUTS_T
Measure motor inputs structure.
Macros
#define HAL_CURRENT_OFFSET_MEAS_BITS 5
Current offset averaging factor 2^n.
#define HAL_CURRENT_OFFSET_MEAS_COUNT (1 << HAL_CURRENT_OFFSET_MEAS_BITS)
Current offset averaging counts.
#define INV_VDC_IQ_SCALING 25
Inverse Vdc scaling.
#define MAX_HALL_INDEX 7
#define HALL_ANGLE_SUM _IQ(3.0)
Enumerations
enum VOLTAGE_GAIN_TYPES {
VOLTAGE_GAIN_VMAX_BY_4 = 2,
VOLTAGE_GAIN_VMAX_BY_2 = 1,
VOLTAGE_GAIN_VMAX_BY_1 = 0
}
Voltage gain types.
enum HAL_MEASUREMENT_TYPES {
MEASURE_PHASE_CURRENT = 0,
MEASURE_PHASE_VOLTAGE = 1
}
HAL measurement types.
enum CURRENT_SHUNT_TYPES {
CURRENT_INVALID = 0,
CURRENT_THREE_SHUNT_DYNAMIC = 1,
CURRENT_THREE_SHUNT_AB_C = 2,
CURRENT_THREE_SHUNT_A_BC = 3,
CURRENT_TWO_SHUNT_A_B = 4,
CURRENT_TWO_SHUNT_A_C = 5,
CURRENT_TWO_SHUNT_B_C = 6,
CURRENT_SINGLE_SHUNT = 7
}
HAL measurement types.
enum ADC_SAMPLING_RATIO_TYPES {
ADC_SAMPLE_EVERY_PWM = 0,
ADC_SAMPLE_EVERY_2_PWM = 1,
ADC_SAMPLE_EVERY_3_PWM = 2,
ADC_SAMPLE_EVERY_4_PWM = 3,
ADC_SAMPLE_EVERY_5_PWM = 4,
ADC_SAMPLE_EVERY_6_PWM = 5,
ADC_SAMPLE_EVERY_7_PWM = 6,
ADC_SAMPLE_EVERY_8_PWM = 7,
ADC_SAMPLE_EVERY_9_PWM = 8,
ADC_SAMPLE_EVERY_10_PWM = 9,
ADC_SAMPLE_EVERY_11_PWM = 10,
ADC_SAMPLE_EVERY_12_PWM = 11,
ADC_SAMPLE_EVERY_13_PWM = 12,
ADC_SAMPLE_EVERY_14_PWM = 13,
ADC_SAMPLE_EVERY_15_PWM = 14,
ADC_SAMPLE_EVERY_16_PWM = 15
}
ADC sampling ratio types.
enum OFFSET_MEASUREMENT_STATES {
OFFSET_INIT = 0,
COMPUTE_OFFSET = 1,
OFFSET_COMPLETE = 2
}
Offset measurement states.
Functions
void inputsInit (HAL_MEASURE_MOTOR_INPUTS_T *pMotorInputs)
Initializes motor iputs.
void measureCurrentOffset (HAL_MEASURE_MOTOR_INPUTS_T *pMotorInputs)
Measures offset of current input.
_Bool getMeasureOffsetStatus (HAL_MEASURE_MOTOR_INPUTS_T *pMotorInputs)
Status of offset measurement.
uint16_t ReadHallState (HAL_MEASURE_HALL_HANDLE_T *pHallHandle)
ReadHallState.
int32_t getHallFrequency (HAL_MEASURE_HALL_HANDLE_T *pHallHandle)
getHallFrequency
int32_t getHallPhaseError (HAL_MEASURE_HALL_HANDLE_T *pHallHandle, int32_t hallEstimVelocity)
getHallPhaseError
Variables
HAL_MEASURE_MOTOR_INPUTS_T * g_pMotorInputs
Extern motor inputs.
Macro Definition Documentation
MAX_HALL_INDEX
#define MAX_HALL_INDEX 7
Maximum Hall States Index = Hall States + 1
Referenced by focRun(), getHallFrequency(), hallCalibRun(), and update_SystemParams().
HALL_ANGLE_SUM
#define HALL_ANGLE_SUM _IQ(3.0)
Total Electrical Angle Summation
Referenced by hallCalibRun().
Enumeration Type Documentation
VOLTAGE_GAIN_TYPES
enum VOLTAGE_GAIN_TYPES
Voltage gain types.
Enumerator
VOLTAGE_GAIN_VMAX_BY_4
Phase voltage gain of Max Volt / 4
VOLTAGE_GAIN_VMAX_BY_2
Phase voltage gain of Max Volt / 2
VOLTAGE_GAIN_VMAX_BY_1
Phase voltage gain of Max Volt / 1
HAL_MEASUREMENT_TYPES
enum HAL_MEASUREMENT_TYPES
HAL measurement types.
Enumerator
MEASURE_PHASE_CURRENT
Measure Phase Currents
MEASURE_PHASE_VOLTAGE
Measure Phase Voltages
CURRENT_SHUNT_TYPES
enum CURRENT_SHUNT_TYPES
HAL measurement types.
Enumerator
CURRENT_INVALID
Default invalid
CURRENT_THREE_SHUNT_DYNAMIC
Reconstructed three phase current with ignoring phase having max duty
CURRENT_THREE_SHUNT_AB_C
Three phase current with A and C sampled simultaneously / ABC on single ADC if simultaneous sampling disabled
CURRENT_THREE_SHUNT_A_BC
Three phase current with A and B sampled simultaneously
CURRENT_TWO_SHUNT_A_B
Two phase current with A and B sampled simultaneously / AB on single ADC if simultaneous sampling disabled
CURRENT_TWO_SHUNT_A_C
Two phase current with A and C sampled simultaneously / AC on single ADC if simultaneous sampling disabled
CURRENT_TWO_SHUNT_B_C
Two phase current with B and C sampled simultaneously / BC on single ADC if simultaneous sampling disabled
CURRENT_SINGLE_SHUNT
DC bus current reconstructing phase currents
ADC_SAMPLING_RATIO_TYPES
enum ADC_SAMPLING_RATIO_TYPES
ADC sampling ratio types.
Enumerator
ADC_SAMPLE_EVERY_PWM
Sample every PWM
ADC_SAMPLE_EVERY_2_PWM
Sample every 2 PWM
ADC_SAMPLE_EVERY_3_PWM
Sample every 3 PWM
ADC_SAMPLE_EVERY_4_PWM
Sample every 4 PWM
ADC_SAMPLE_EVERY_5_PWM
Sample every 5 PWM
ADC_SAMPLE_EVERY_6_PWM
Sample every 6 PWM
ADC_SAMPLE_EVERY_7_PWM
Sample every 7 PWM
ADC_SAMPLE_EVERY_8_PWM
Sample every 8 PWM
ADC_SAMPLE_EVERY_9_PWM
Sample every 9 PWM
ADC_SAMPLE_EVERY_10_PWM
Sample every 10 PWM
ADC_SAMPLE_EVERY_11_PWM
Sample every 11 PWM
ADC_SAMPLE_EVERY_12_PWM
Sample every 12 PWM
ADC_SAMPLE_EVERY_13_PWM
Sample every 13 PWM
ADC_SAMPLE_EVERY_14_PWM
Sample every 14 PWM
ADC_SAMPLE_EVERY_15_PWM
Sample every 15 PWM
ADC_SAMPLE_EVERY_16_PWM
Sample every 16 PWM
OFFSET_MEASUREMENT_STATES
enum OFFSET_MEASUREMENT_STATES
Offset measurement states.
Enumerator
OFFSET_INIT
Offset init state
COMPUTE_OFFSET
Compute state
OFFSET_COMPLETE
Offset complete state
Function Documentation
inputsInit()
void inputsInit (HAL_MEASURE_MOTOR_INPUTS_T * pMotorInputs)
Initializes motor iputs.
Parameters
[in] pMotorInputs Pointer to motor input
References MEASURE_CURRENT_FLAGS_T::b, HALL_INTERFACE_T::captureInput, HAL_MEASURE_MOTOR_INPUTS_T::current, HAL_MEASURE_CURRENT_T::currentShunt, FALSE, HAL_MEASURE_CURRENT_T::flags, HAL_CAPTURE_TIMER_01, HAL_GPIO_IN_01, HAL_GPIO_IN_02, HAL_GPIO_IN_03, HALL_INTERFACE_T::hallA, HALL_INTERFACE_T::hallB, HALL_INTERFACE_T::hallC, HAL_MEASURE_HALL_HANDLE_T::HallInterface, HAL_MEASURE_CURRENT_T::i1Sum, HAL_MEASURE_CURRENT_T::i2Sum, HAL_MEASURE_CURRENT_T::iaSum, HAL_MEASURE_CURRENT_T::ibADC0Sum, HAL_MEASURE_CURRENT_T::ibADC1Sum, HAL_MEASURE_CURRENT_T::icSum, HAL_MEASURE_MOTOR_INPUTS_T::measureHALL, measureCurrentFlags::offsetAB_CStatus, measureCurrentFlags::offsetGainStatus, HAL_MEASURE_CURRENT_T::offsetMeasCount, measureCurrentFlags::offsetStatus, measureCurrentFlags::threeShuntDynamic, and measureCurrentFlags::threeShuntDynamicSet.
Referenced by measureCurrentOffset().
measureCurrentOffset()
void measureCurrentOffset (HAL_MEASURE_MOTOR_INPUTS_T * pMotorInputs)
Measures offset of current input.
Parameters
[in] pMotorInputs Pointer to motor input
References MC_ABC_T::a, MC_ABC_T::b, MEASURE_CURRENT_FLAGS_T::b, MC_ABC_T::c, COMPUTE_OFFSET, HAL_MEASURE_MOTOR_INPUTS_T::current, CURRENT_SINGLE_SHUNT, CURRENT_THREE_SHUNT_A_BC, CURRENT_THREE_SHUNT_AB_C, CURRENT_THREE_SHUNT_DYNAMIC, CURRENT_TWO_SHUNT_A_B, CURRENT_TWO_SHUNT_B_C, HAL_MEASURE_CURRENT_T::currentShunt, HAL_MEASURE_CURRENT_T::currentShuntSet, HAL_MEASURE_CURRENT_T::flags, HAL_CURRENT_OFFSET_MEAS_BITS, HAL_CURRENT_OFFSET_MEAS_COUNT, HAL_SetPhaseCurrentChannels(), CURRENT_OFFSET_T::i1Offset, HAL_MEASURE_CURRENT_T::i1Sum, CURRENT_OFFSET_T::i2Offset, HAL_MEASURE_CURRENT_T::i2Sum, HAL_MEASURE_CURRENT_T::iabcRaw, CURRENT_OFFSET_T::iaOffset, HAL_MEASURE_CURRENT_T::iaSum, CURRENT_OFFSET_T::ibADC0Offset, HAL_MEASURE_CURRENT_T::ibADC0Sum, CURRENT_OFFSET_T::ibADC1Offset, HAL_MEASURE_CURRENT_T::ibADC1Sum, CURRENT_OFFSET_T::icOffset, HAL_MEASURE_CURRENT_T::icSum, HAL_MEASURE_CURRENT_T::iFirstSample, inputsInit(), HAL_MEASURE_CURRENT_T::iSecondSample, OFFSET_COMPLETE, OFFSET_INIT, measureCurrentFlags::offsetAB_CStatus, HAL_MEASURE_CURRENT_T::offsetGainIMaxBy1, measureCurrentFlags::offsetGainStatus, HAL_MEASURE_CURRENT_T::offsetMeasCount, measureCurrentFlags::offsetStatus, HAL_MEASURE_CURRENT_T::state, and TRUE.
getMeasureOffsetStatus()
_Bool getMeasureOffsetStatus (HAL_MEASURE_MOTOR_INPUTS_T * pMotorInputs) inline
Status of offset measurement.
Parameters
[in] pMotorInputs Pointer to motor input
Returns
Returns the status of offset measurement
Return values
true Offset measurement completed
false Offset measurement not completed
References MEASURE_CURRENT_FLAGS_T::b, HAL_MEASURE_MOTOR_INPUTS_T::current, HAL_MEASURE_CURRENT_T::flags, getHallFrequency(), getHallPhaseError(), measureCurrentFlags::offsetStatus, and ReadHallState().
Referenced by HAL_ReadCurrents().
ReadHallState()
uint16_t ReadHallState (HAL_MEASURE_HALL_HANDLE_T * pHallHandle)
ReadHallState.
Parameters
[in] *pHallHandle Input Pointer
Returns
Hall State
References HAL_readGPIOPin(), HALL_INTERFACE_T::hallA, HALL_INTERFACE_T::hallB, HALL_INTERFACE_T::hallC, HAL_MEASURE_HALL_HANDLE_T::HallInterface, and HAL_MEASURE_HALL_HANDLE_T::hallState.
Referenced by getMeasureOffsetStatus(), hallAngleEstimRun(), hallAngleInit(), and hallCalibRun().
getHallFrequency()
int32_t getHallFrequency (HAL_MEASURE_HALL_HANDLE_T * pHallHandle)
getHallFrequency
Parameters
[in] *pHallHandle Input Pointer
Returns
Motor Speed in Electrical Hertz
References HALL_INTERFACE_T::captureInput, HAL_MEASURE_HALL_HANDLE_T::commCountIndex, HAL_MEASURE_HALL_HANDLE_T::commTimerIndex, HAL_MEASURE_HALL_HANDLE_T::compHallState, HAL_MEASURE_HALL_HANDLE_T::countDiff, HAL_MEASURE_HALL_HANDLE_T::countError, HAL_getCaptureRunningValue(), HAL_getCaptureValue(), HAL_getTimerLoadValue(), HAL_MEASURE_HALL_HANDLE_T::halCapFreqPU, HAL_MEASURE_HALL_HANDLE_T::HallInterface, HAL_MEASURE_HALL_HANDLE_T::hallState, HAL_MEASURE_HALL_HANDLE_T::halMaxFreqCount, and MAX_HALL_INDEX.
Referenced by getMeasureOffsetStatus(), and hallAngleEstimRun().
getHallPhaseError()
int32_t getHallPhaseError (HAL_MEASURE_HALL_HANDLE_T * pHallHandle, int32_t hallEstimVelocity)
getHallPhaseError
Parameters
[in] *pHallHandle Input Pointer
[in] hallEstimVelocity Estimated velocity
Returns
Phase Error
References _IQmpy_mathacl, HAL_MEASURE_HALL_HANDLE_T::countError, HAL_MEASURE_HALL_HANDLE_T::halPhaseError, and HAL_MEASURE_HALL_HANDLE_T::halPhaseErrorConst.
Referenced by getMeasureOffsetStatus(), and hallAngleEstimRun().
Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale