MSPM0G3507SensoredFOCMotorControlLibrary: openLoop.h File Reference
openLoop.h File Reference
Detailed Description
openLoop Module
Overview
#include "stdint.h"
#include <ti/iqmath/include/IQmathLib.h>
#include "IQmath_mathacl.h"
#include "iqNum.h"
Data Structures
union OPEN_LOOP_FLAGS_T
Open Loop flags Structure.
struct OPEN_LOOP_FLAGS_T::openLoopFlags
Open Loop flags.
struct OPEN_LOOP_T
Open Loop Working Structure.
Enumerations
enum FORCED_SPEED_STATE_TYPES { OPEN_LOOP_ACCELERATING_PROFILE = 0 }
Open Loop Ramp Enum Values.
Functions
void openLoopInit (OPEN_LOOP_T *pOpenLoop)
openLoopInit
void openLoopRun (OPEN_LOOP_T *pOpenLoop)
openLoop Run
void openLoopSetInitialVelocity (OPEN_LOOP_T *pOpenLoop)
Open Loop Init Velocity Set.
_Bool getOpenLoopStatus (OPEN_LOOP_T *pOpenLoop)
Open Loop Status check.
Enumeration Type Documentation
FORCED_SPEED_STATE_TYPES
enum FORCED_SPEED_STATE_TYPES
Open Loop Ramp Enum Values.
Enumerator
OPEN_LOOP_ACCELERATING_PROFILE
Open Loop ramp up
Function Documentation
openLoopInit()
void openLoopInit (OPEN_LOOP_T * pOpenLoop)
openLoopInit
Parameters
[in] *pOpenLoop Input Pointer
References OPEN_LOOP_FLAGS_T::b, FALSE, OPEN_LOOP_T::flags, OPEN_LOOP_T::idRef, OPEN_LOOP_T::loopExecutionCount, OPEN_LOOP_T::prevVelocityReference, OPEN_LOOP_T::speedReferenceMax, OPEN_LOOP_T::speedReferenceMaxForwardSet, OPEN_LOOP_FLAGS_T::openLoopFlags::status, OPEN_LOOP_FLAGS_T::openLoopFlags::transitionEnable, OPEN_LOOP_T::velocityReference, and OPEN_LOOP_T::velocityReferenceScaled.
Referenced by focInit(), and focRun().
openLoopRun()
void openLoopRun (OPEN_LOOP_T * pOpenLoop)
openLoop Run
Parameters
[in] *pOpenLoop Input Pointer
References _IQmpy_mathacl, OPEN_LOOP_T::accelRefSlewRateDecel, OPEN_LOOP_T::angle, OPEN_LOOP_FLAGS_T::b, FALSE, OPEN_LOOP_T::flags, OPEN_LOOP_FLAGS_T::openLoopFlags::forceEnable, GLOBAL_IQ, OPEN_LOOP_T::idRef, OPEN_LOOP_T::idRefSlewRate, OPEN_LOOP_T::iqRef, OPEN_LOOP_T::iqRefMax, OPEN_LOOP_T::iqRefSet, OPEN_LOOP_T::iqRefSlewRate, IQ_NUM_T::iqScaling, OPEN_LOOP_T::loopExecutionCount, OPEN_LOOP_FLAGS_T::openLoopFlags::openLoopDirChange, OPEN_LOOP_T::pAccelRefSlewRate, OPEN_LOOP_T::pDeltaT, OPEN_LOOP_T::prevVelocityReference, OPEN_LOOP_T::pSpeedRefSlewRate, OPEN_LOOP_T::pTargetVelocity, IQ_NUM_T::scaledNum, slewRate(), OPEN_LOOP_T::speedReferenceMax, OPEN_LOOP_T::speedReferenceMaxForwardSet, OPEN_LOOP_T::speedReferenceMaxReverseSet, OPEN_LOOP_T::speedRefSlewRateDecel, OPEN_LOOP_FLAGS_T::openLoopFlags::status, OPEN_LOOP_FLAGS_T::openLoopFlags::transitionEnable, TRUE, OPEN_LOOP_T::velocityReference, and OPEN_LOOP_T::velocityReferenceScaled.
Referenced by focRun().
openLoopSetInitialVelocity()
void openLoopSetInitialVelocity (OPEN_LOOP_T * pOpenLoop)
Open Loop Init Velocity Set.
Parameters
[in] *pOpenLoop Input Pointer
References _IQdiv_mathacl, OPEN_LOOP_FLAGS_T::b, OPEN_LOOP_FLAGS_T::openLoopFlags::fastStartEnable, OPEN_LOOP_T::flags, OPEN_LOOP_T::initialSpeedReference, OPEN_LOOP_T::pTargetVelocity, OPEN_LOOP_T::speedReferenceMax, OPEN_LOOP_T::velocityReference, and OPEN_LOOP_T::velocityReferenceScaled.
Referenced by focRun().
getOpenLoopStatus()
_Bool getOpenLoopStatus (OPEN_LOOP_T * pOpenLoop) inline
Open Loop Status check.
Parameters
[in] *pOpenLoop Pointer
Returns
Returns the status
References OPEN_LOOP_FLAGS_T::b, OPEN_LOOP_T::flags, and OPEN_LOOP_FLAGS_T::openLoopFlags::status.
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale