MSPM0G3507SensoredFOCMotorControlLibrary: services.h File Reference
services.h File Reference
Detailed Description
Application Interface services Module.
Overview
Apis for updating the application interface
#include "appInputCtrlInterface.h"
#include "main.h"
#include "appDefs.h"
#include "appUserInputsInterface.h"
#include "appUserInputs.h"
Functions
_Bool update_DirectionStatus (void)
Gets direction status.
_Bool update_BrakeStatus (void)
Gets brake status.
void peri1Config (void)
Set periperal 1 config.
void CurrSenseAmpConfigInit (HAL_MEASURE_MOTOR_INPUTS_T *pMotorInputs)
Initializes Current Sense Amplifier configurations.
Function Documentation
update_DirectionStatus()
_Bool update_DirectionStatus (void)
Gets direction status.
Returns
Returns the state of direction
Return values
true Direction sequence ABC
false Direction sequence ACB
References USER_INPUT_PERI_CFG1_T::b, userInputPeriCfg1::dirInput, FALSE, HAL_getDirPinStatus(), USER_INPUT_INTERFACE_T::periphCfg1, pUserInputRegs, and TRUE.
Referenced by speedProfile().
update_BrakeStatus()
_Bool update_BrakeStatus (void)
Gets brake status.
Returns
Returns the state of brake
Return values
true brake commanded
false brake not commanded
References USER_INPUT_PIN_CFG_T::b, userInputPinCfg::brakeInp, FALSE, HAL_getBrakePinStatus(), USER_INPUT_INTERFACE_T::pinCfg, pUserInputRegs, and TRUE.
CurrSenseAmpConfigInit()
void CurrSenseAmpConfigInit (HAL_MEASURE_MOTOR_INPUTS_T * pMotorInputs)
Initializes Current Sense Amplifier configurations.
Parameters
[in] pMotorInputs Pointer to motor input
References MEASURE_CURRENT_FLAGS_T::b, HAL_MEASURE_MOTOR_INPUTS_T::current, HAL_MEASURE_CURRENT_T::currentShuntSet, HAL_MEASURE_CURRENT_T::flags, and measureCurrentFlags::threeShuntDynamicSet.
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale