MSPM0G3507SensoredFOCMotorControlLibrary: slewRate.h File Reference
slewRate.h File Reference
Detailed Description
slewRate Module
Overview
#include "stdint.h"
#include <ti/iqmath/include/IQmathLib.h>
Functions
void slewRate (int32_t *slewedOut, int32_t setPoint, int32_t slewRate)
Abnormal Speed Detect Init.
Function Documentation
slewRate()
void slewRate (int32_t * slewedOut, int32_t setPoint, int32_t slewRate)
Abnormal Speed Detect Init.
Parameters
[in] *slewedOut Pointer
[in] setPoint Input
[in] slewRate Input
Referenced by closeLoopLowPriorityRun(), closeLoopRun(), focRun(), and openLoopRun().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale