MSPM0G3507SensoredFOCMotorControlLibrary: sourceCurrentLimit.h File Reference
sourceCurrentLimit.h File Reference
Detailed Description
sourceCurrentLimit Module
Overview
#include "stdint.h"
#include "mcLib.h"
Data Structures
union SOURCE_CURRENT_LIMIT_FLAGS_T
Source Current Working Structure.
struct SOURCE_CURRENT_LIMIT_FLAGS_T::sourceCurrentLimitFlags
Source Current Structure.
struct SOURCE_CURRENT_LIMIT_T
Source Current Limit Structure.
Macros
#define SOURCE_CURRENT_LIMIT_THRESHHOLD _IQ(0.95)
Source Current Limit Threshold.
Enumerations
enum SOURCE_CURRENT_LIMIT_STATE_TYPES {
SOURCE_CURRENT_BELOW_LIMIT = 0,
SOURCE_CURRENT_ABOVE_LIMIT = 1
}
Source Current Limit Range Values.
enum SOURCE_CURRENT_LIMIT_STATE_TRANSITION_TYPES {
SOURCE_CURRENT_NO_TRANSITION = 0,
SOURCE_CURRENT_TRANSITION_TO_NORMAL_CURRENT = 1,
SOURCE_CURRENT_TRANSITION_TO_CURRENT_LIMIT = 2
}
Source Current Limit Transition Values.
Functions
void sourceCurrentLimitInit (SOURCE_CURRENT_LIMIT_T *pSourceCurrentLimit)
source Current Limit Init
void sourceCurrentLimitRun (SOURCE_CURRENT_LIMIT_T *pSourceCurrentLimit)
source Current Limit Run
SOURCE_CURRENT_LIMIT_STATE_TRANSITION_TYPES getCurrentLimitTransition (SOURCE_CURRENT_LIMIT_T *pSourceCurrentLimit)
get Current Limit Transition
SOURCE_CURRENT_LIMIT_STATE_TYPES getCurrentLimitState (SOURCE_CURRENT_LIMIT_T *pSourceCurrentLimit)
get Current Limit State
Enumeration Type Documentation
SOURCE_CURRENT_LIMIT_STATE_TYPES
enum SOURCE_CURRENT_LIMIT_STATE_TYPES
Source Current Limit Range Values.
Enumerator
SOURCE_CURRENT_BELOW_LIMIT
Source current in limits
SOURCE_CURRENT_ABOVE_LIMIT
Source current out of limit
SOURCE_CURRENT_LIMIT_STATE_TRANSITION_TYPES
enum SOURCE_CURRENT_LIMIT_STATE_TRANSITION_TYPES
Source Current Limit Transition Values.
Enumerator
SOURCE_CURRENT_NO_TRANSITION
No transition
SOURCE_CURRENT_TRANSITION_TO_NORMAL_CURRENT
Normal current
SOURCE_CURRENT_TRANSITION_TO_CURRENT_LIMIT
Current limit
Function Documentation
sourceCurrentLimitInit()
void sourceCurrentLimitInit (SOURCE_CURRENT_LIMIT_T * pSourceCurrentLimit)
source Current Limit Init
Parameters
[in] *pSourceCurrentLimit Input Pointer
References SOURCE_CURRENT_LIMIT_T::prevState, SOURCE_CURRENT_BELOW_LIMIT, SOURCE_CURRENT_NO_TRANSITION, SOURCE_CURRENT_LIMIT_T::state, and SOURCE_CURRENT_LIMIT_T::transition.
Referenced by sourceLimitsInit().
sourceCurrentLimitRun()
void sourceCurrentLimitRun (SOURCE_CURRENT_LIMIT_T * pSourceCurrentLimit)
source Current Limit Run
Parameters
[in] *pSourceCurrentLimit Input Pointer
References SOURCE_CURRENT_LIMIT_FLAGS_T::b, SOURCE_CURRENT_LIMIT_FLAGS_T::sourceCurrentLimitFlags::enable, SOURCE_CURRENT_LIMIT_T::flags, SOURCE_CURRENT_LIMIT_T::prevState, SOURCE_CURRENT_LIMIT_T::pSourceCurrent, SOURCE_CURRENT_ABOVE_LIMIT, SOURCE_CURRENT_BELOW_LIMIT, SOURCE_CURRENT_LIMIT_THRESHHOLD, SOURCE_CURRENT_NO_TRANSITION, SOURCE_CURRENT_TRANSITION_TO_CURRENT_LIMIT, SOURCE_CURRENT_TRANSITION_TO_NORMAL_CURRENT, SOURCE_CURRENT_LIMIT_T::sourceCurrentLimit, SOURCE_CURRENT_LIMIT_T::state, and SOURCE_CURRENT_LIMIT_T::transition.
Referenced by sourceLimitsRun().
getCurrentLimitTransition()
SOURCE_CURRENT_LIMIT_STATE_TRANSITION_TYPES getCurrentLimitTransition (SOURCE_CURRENT_LIMIT_T * pSourceCurrentLimit) inline
get Current Limit Transition
Parameters
[in] *pSourceCurrentLimit Pointer
Returns
Returns the Transition status
References SOURCE_CURRENT_LIMIT_T::transition.
Referenced by update_FOC_faultStatus().
getCurrentLimitState()
SOURCE_CURRENT_LIMIT_STATE_TYPES getCurrentLimitState (SOURCE_CURRENT_LIMIT_T * pSourceCurrentLimit) inline
get Current Limit State
Parameters
[in] *pSourceCurrentLimit Pointer
Returns
Returns the State
References SOURCE_CURRENT_LIMIT_T::state.
Referenced by update_FOC_faultStatus().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale