MSPM0G3507SensoredFOCMotorControlLibrary: sourceVoltageLimit.h File Reference
sourceVoltageLimit.h File Reference
Detailed Description
Voltage limit Module.
Overview
APIs for voltage limits
#include "stdint.h"
Data Structures
union SOURCE_VOLTAGE_LIMIT_FLAGS_T
Source Voltage flags Structure.
struct SOURCE_VOLTAGE_LIMIT_FLAGS_T::sourceVoltageLimitFlags
Source Voltage Structure.
struct SOURCE_VOLTAGE_LIMIT_T
Source Voltage Structure.
Enumerations
enum SOURCE_VOLTAGE_FAULT_TYPES {
NO_VOLTAGE_FAULT = 0,
UNDER_VOLTAGE = 1,
OVER_VOLTAGE = 2
}
Source Voltage Fault types Structure.
Functions
SOURCE_VOLTAGE_FAULT_TYPES getSourceVoltageFaultStatus (SOURCE_VOLTAGE_LIMIT_T *pSourceVoltageLimit)
Source Voltage Limit Status Check.
void sourceVoltageLimitInit (SOURCE_VOLTAGE_LIMIT_T *pSourceVoltageLimit)
source Voltage Limits Init
void sourceVoltageLimitRun (SOURCE_VOLTAGE_LIMIT_T *pSourceVoltageLimit)
source Voltage Limits Run
Enumeration Type Documentation
SOURCE_VOLTAGE_FAULT_TYPES
enum SOURCE_VOLTAGE_FAULT_TYPES
Source Voltage Fault types Structure.
Enumerator
NO_VOLTAGE_FAULT
No Voltage Fault
UNDER_VOLTAGE
Under Voltage
OVER_VOLTAGE
Over Voltage
Function Documentation
getSourceVoltageFaultStatus()
SOURCE_VOLTAGE_FAULT_TYPES getSourceVoltageFaultStatus (SOURCE_VOLTAGE_LIMIT_T * pSourceVoltageLimit) inline
Source Voltage Limit Status Check.
Parameters
[in] *pSourceVoltageLimit Pointer
Returns
Returns the status
References SOURCE_VOLTAGE_LIMIT_T::faultStatus, sourceVoltageLimitInit(), and sourceVoltageLimitRun().
sourceVoltageLimitInit()
void sourceVoltageLimitInit (SOURCE_VOLTAGE_LIMIT_T * pSourceVoltageLimit)
source Voltage Limits Init
Parameters
[in] *pSourceVoltageLimit Input Pointer
References SOURCE_VOLTAGE_LIMIT_T::count.
Referenced by getSourceVoltageFaultStatus(), and sourceLimitsInit().
sourceVoltageLimitRun()
void sourceVoltageLimitRun (SOURCE_VOLTAGE_LIMIT_T * pSourceVoltageLimit)
source Voltage Limits Run
Parameters
[in] *pSourceVoltageLimit Input Pointer
References SOURCE_VOLTAGE_LIMIT_FLAGS_T::b, SOURCE_VOLTAGE_LIMIT_T::count, SOURCE_VOLTAGE_LIMIT_T::countMax, FALSE, SOURCE_VOLTAGE_LIMIT_T::faultStatus, SOURCE_VOLTAGE_LIMIT_T::flags, SOURCE_VOLTAGE_LIMIT_T::maxDCBusVoltage, NO_VOLTAGE_FAULT, OVER_VOLTAGE, SOURCE_VOLTAGE_LIMIT_FLAGS_T::sourceVoltageLimitFlags::overVoltageFaultAutoClear, SOURCE_VOLTAGE_LIMIT_T::overVoltageFaultClearThreshold, SOURCE_VOLTAGE_LIMIT_FLAGS_T::sourceVoltageLimitFlags::overVoltageFaultEnable, SOURCE_VOLTAGE_LIMIT_FLAGS_T::sourceVoltageLimitFlags::overVoltageFaultStatus, SOURCE_VOLTAGE_LIMIT_T::pVdc, TRUE, UNDER_VOLTAGE, SOURCE_VOLTAGE_LIMIT_FLAGS_T::sourceVoltageLimitFlags::underVoltageFaultAutoClear, SOURCE_VOLTAGE_LIMIT_T::underVoltageFaultClearThreshold, SOURCE_VOLTAGE_LIMIT_FLAGS_T::sourceVoltageLimitFlags::underVoltageFaultEnable, and SOURCE_VOLTAGE_LIMIT_FLAGS_T::sourceVoltageLimitFlags::underVoltageFaultStatus.
Referenced by getSourceVoltageFaultStatus(), and sourceLimitsRun().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale