MSPM0G3507SensoredFOCMotorControlLibrary: triState.h File Reference
triState.h File Reference
Detailed Description
triState Module
Overview
#include "stdint.h"
Data Structures
union TRI_STATE_FLAGS_T
TriState Flags Working Structure.
struct TRI_STATE_FLAGS_T::triStateFlags
TriState Flags Structure.
struct TRISTATE_T
TriState Working Structure.
Functions
void triStateInit (TRISTATE_T *pTriState)
TriState Init.
void triStateRun (TRISTATE_T *pTriState)
TriState Run.
_Bool getTriStateStatus (TRISTATE_T *pTriState)
TriState Status check.
Function Documentation
triStateInit()
void triStateInit (TRISTATE_T * pTriState)
TriState Init.
Parameters
[in] *pTriState Pointer
References TRI_STATE_FLAGS_T::b, TRISTATE_T::count, FALSE, TRISTATE_T::flags, and TRI_STATE_FLAGS_T::triStateFlags::status.
Referenced by loadInit().
triStateRun()
void triStateRun (TRISTATE_T * pTriState)
TriState Run.
Parameters
[in] *pTriState Pointer
References TRI_STATE_FLAGS_T::b, TRISTATE_T::count, TRISTATE_T::countMax, TRISTATE_T::flags, TRI_STATE_FLAGS_T::triStateFlags::status, and TRUE.
Referenced by loadLowPriorityRun().
getTriStateStatus()
_Bool getTriStateStatus (TRISTATE_T * pTriState) inline
TriState Status check.
Parameters
[in] *pTriState Pointer
Returns
Returns the status
References TRI_STATE_FLAGS_T::b, TRISTATE_T::flags, and TRI_STATE_FLAGS_T::triStateFlags::status.
Referenced by loadRun().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale