IQMathLibrary: _IQNasin_acos.c File Reference
_IQNasin_acos.c File Reference
Detailed Description
Functions to compute the inverse sine of the input and return the result, in radians.
#include <stdint.h>
#include "../support/support.h"
#include "_IQNtables.h"
Functions
__STATIC_INLINE int_fast32_t __IQNasin (int_fast32_t iqNInput, const int8_t q_value)
Computes the inverse sine of the IQN input.
int32_t _IQ29asin (int32_t a)
Computes the inverse sine of the IQ29 input.
int32_t _IQ28asin (int32_t a)
Computes the inverse sine of the IQ28 input.
int32_t _IQ27asin (int32_t a)
Computes the inverse sine of the IQ27 input.
int32_t _IQ26asin (int32_t a)
Computes the inverse sine of the IQ26 input.
int32_t _IQ25asin (int32_t a)
Computes the inverse sine of the IQ25 input.
int32_t _IQ24asin (int32_t a)
Computes the inverse sine of the IQ24 input.
int32_t _IQ23asin (int32_t a)
Computes the inverse sine of the IQ23 input.
int32_t _IQ22asin (int32_t a)
Computes the inverse sine of the IQ22 input.
int32_t _IQ21asin (int32_t a)
Computes the inverse sine of the IQ21 input.
int32_t _IQ20asin (int32_t a)
Computes the inverse sine of the IQ20 input.
int32_t _IQ19asin (int32_t a)
Computes the inverse sine of the IQ19 input.
int32_t _IQ18asin (int32_t a)
Computes the inverse sine of the IQ18 input.
int32_t _IQ17asin (int32_t a)
Computes the inverse sine of the IQ17 input.
int32_t _IQ16asin (int32_t a)
Computes the inverse sine of the IQ16 input.
int32_t _IQ15asin (int32_t a)
Computes the inverse sine of the IQ15 input.
int32_t _IQ14asin (int32_t a)
Computes the inverse sine of the IQ14 input.
int32_t _IQ13asin (int32_t a)
Computes the inverse sine of the IQ13 input.
int32_t _IQ12asin (int32_t a)
Computes the inverse sine of the IQ12 input.
int32_t _IQ11asin (int32_t a)
Computes the inverse sine of the IQ11 input.
int32_t _IQ10asin (int32_t a)
Computes the inverse sine of the IQ10 input.
int32_t _IQ9asin (int32_t a)
Computes the inverse sine of the IQ9 input.
int32_t _IQ8asin (int32_t a)
Computes the inverse sine of the IQ8 input.
int32_t _IQ7asin (int32_t a)
Computes the inverse sine of the IQ7 input.
int32_t _IQ6asin (int32_t a)
Computes the inverse sine of the IQ6 input.
int32_t _IQ5asin (int32_t a)
Computes the inverse sine of the IQ5 input.
int32_t _IQ4asin (int32_t a)
Computes the inverse sine of the IQ4 input.
int32_t _IQ3asin (int32_t a)
Computes the inverse sine of the IQ3 input.
int32_t _IQ2asin (int32_t a)
Computes the inverse sine of the IQ2 input.
int32_t _IQ1asin (int32_t a)
Computes the inverse sine of the IQ1 input.
Function Documentation
__IQNasin()
__STATIC_INLINE int_fast32_t __IQNasin (int_fast32_t iqNInput, const int8_t q_value)
Computes the inverse sine of the IQN input.
Parameters
iqNInput IQN type input.
q_value IQ format.
Returns
IQN type result of inverse sine.
References _IQ31sqrt().
Referenced by _IQ10asin(), _IQ11asin(), _IQ12asin(), _IQ13asin(), _IQ14asin(), _IQ15asin(), _IQ16asin(), _IQ17asin(), _IQ18asin(), _IQ19asin(), _IQ1asin(), _IQ20asin(), _IQ21asin(), _IQ22asin(), _IQ23asin(), _IQ24asin(), _IQ25asin(), _IQ26asin(), _IQ27asin(), _IQ28asin(), _IQ29asin(), _IQ2asin(), _IQ3asin(), _IQ4asin(), _IQ5asin(), _IQ6asin(), _IQ7asin(), _IQ8asin(), and _IQ9asin().
_IQ29asin()
int32_t _IQ29asin (int32_t a)
Computes the inverse sine of the IQ29 input.
Parameters
a IQ29 type input.
Returns
IQ29 type result of inverse sine.
References __IQNasin().
_IQ28asin()
int32_t _IQ28asin (int32_t a)
Computes the inverse sine of the IQ28 input.
Parameters
a IQ28 type input.
Returns
IQ28 type result of inverse sine.
References __IQNasin().
_IQ27asin()
int32_t _IQ27asin (int32_t a)
Computes the inverse sine of the IQ27 input.
Parameters
a IQ27 type input.
Returns
IQ27 type result of inverse sine.
References __IQNasin().
_IQ26asin()
int32_t _IQ26asin (int32_t a)
Computes the inverse sine of the IQ26 input.
Parameters
a IQ26 type input.
Returns
IQ26 type result of inverse sine.
References __IQNasin().
_IQ25asin()
int32_t _IQ25asin (int32_t a)
Computes the inverse sine of the IQ25 input.
Parameters
a IQ25 type input.
Returns
IQ25 type result of inverse sine.
References __IQNasin().
_IQ24asin()
int32_t _IQ24asin (int32_t a)
Computes the inverse sine of the IQ24 input.
Parameters
a IQ24 type input.
Returns
IQ24 type result of inverse sine.
References __IQNasin().
_IQ23asin()
int32_t _IQ23asin (int32_t a)
Computes the inverse sine of the IQ23 input.
Parameters
a IQ23 type input.
Returns
IQ23 type result of inverse sine.
References __IQNasin().
_IQ22asin()
int32_t _IQ22asin (int32_t a)
Computes the inverse sine of the IQ22 input.
Parameters
a IQ22 type input.
Returns
IQ22 type result of inverse sine.
References __IQNasin().
_IQ21asin()
int32_t _IQ21asin (int32_t a)
Computes the inverse sine of the IQ21 input.
Parameters
a IQ21 type input.
Returns
IQ21 type result of inverse sine.
References __IQNasin().
_IQ20asin()
int32_t _IQ20asin (int32_t a)
Computes the inverse sine of the IQ20 input.
Parameters
a IQ20 type input.
Returns
IQ20 type result of inverse sine.
References __IQNasin().
_IQ19asin()
int32_t _IQ19asin (int32_t a)
Computes the inverse sine of the IQ19 input.
Parameters
a IQ19 type input.
Returns
IQ19 type result of inverse sine.
References __IQNasin().
_IQ18asin()
int32_t _IQ18asin (int32_t a)
Computes the inverse sine of the IQ18 input.
Parameters
a IQ18 type input.
Returns
IQ18 type result of inverse sine.
References __IQNasin().
_IQ17asin()
int32_t _IQ17asin (int32_t a)
Computes the inverse sine of the IQ17 input.
Parameters
a IQ17 type input.
Returns
IQ17 type result of inverse sine.
References __IQNasin().
_IQ16asin()
int32_t _IQ16asin (int32_t a)
Computes the inverse sine of the IQ16 input.
Parameters
a IQ16 type input.
Returns
IQ16 type result of inverse sine.
References __IQNasin().
_IQ15asin()
int32_t _IQ15asin (int32_t a)
Computes the inverse sine of the IQ15 input.
Parameters
a IQ15 type input.
Returns
IQ15 type result of inverse sine.
References __IQNasin().
_IQ14asin()
int32_t _IQ14asin (int32_t a)
Computes the inverse sine of the IQ14 input.
Parameters
a IQ14 type input.
Returns
IQ14 type result of inverse sine.
References __IQNasin().
_IQ13asin()
int32_t _IQ13asin (int32_t a)
Computes the inverse sine of the IQ13 input.
Parameters
a IQ13 type input.
Returns
IQ13 type result of inverse sine.
References __IQNasin().
_IQ12asin()
int32_t _IQ12asin (int32_t a)
Computes the inverse sine of the IQ12 input.
Parameters
a IQ12 type input.
Returns
IQ12 type result of inverse sine.
References __IQNasin().
_IQ11asin()
int32_t _IQ11asin (int32_t a)
Computes the inverse sine of the IQ11 input.
Parameters
a IQ11 type input.
Returns
IQ11 type result of inverse sine.
References __IQNasin().
_IQ10asin()
int32_t _IQ10asin (int32_t a)
Computes the inverse sine of the IQ10 input.
Parameters
a IQ10 type input.
Returns
IQ10 type result of inverse sine.
References __IQNasin().
_IQ9asin()
int32_t _IQ9asin (int32_t a)
Computes the inverse sine of the IQ9 input.
Parameters
a IQ9 type input.
Returns
IQ9 type result of inverse sine.
References __IQNasin().
_IQ8asin()
int32_t _IQ8asin (int32_t a)
Computes the inverse sine of the IQ8 input.
Parameters
a IQ8 type input.
Returns
IQ8 type result of inverse sine.
References __IQNasin().
_IQ7asin()
int32_t _IQ7asin (int32_t a)
Computes the inverse sine of the IQ7 input.
Parameters
a IQ7 type input.
Returns
IQ7 type result of inverse sine.
References __IQNasin().
_IQ6asin()
int32_t _IQ6asin (int32_t a)
Computes the inverse sine of the IQ6 input.
Parameters
a IQ6 type input.
Returns
IQ6 type result of inverse sine.
References __IQNasin().
_IQ5asin()
int32_t _IQ5asin (int32_t a)
Computes the inverse sine of the IQ5 input.
Parameters
a IQ5 type input.
Returns
IQ5 type result of inverse sine.
References __IQNasin().
_IQ4asin()
int32_t _IQ4asin (int32_t a)
Computes the inverse sine of the IQ4 input.
Parameters
a IQ4 type input.
Returns
IQ4 type result of inverse sine.
References __IQNasin().
_IQ3asin()
int32_t _IQ3asin (int32_t a)
Computes the inverse sine of the IQ3 input.
Parameters
a IQ3 type input.
Returns
IQ3 type result of inverse sine.
References __IQNasin().
_IQ2asin()
int32_t _IQ2asin (int32_t a)
Computes the inverse sine of the IQ2 input.
Parameters
a IQ2 type input.
Returns
IQ2 type result of inverse sine.
References __IQNasin().
_IQ1asin()
int32_t _IQ1asin (int32_t a)
Computes the inverse sine of the IQ1 input.
Parameters
a IQ1 type input.
Returns
IQ1 type result of inverse sine.
References __IQNasin().
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale