IQMathLibrary: _IQNsin_cos.c File Reference
_IQNsin_cos.c File Reference
Detailed Description
Functions to compute the sine and cosine of the input and return the result.
#include <stdint.h>
#include "../support/support.h"
#include "_IQNtables.h"
#include "../include/IQmathLib.h"
Macros
#define PI (3.1415926536)
The value of PI.
#define TYPE_SIN (0)
Used to specify sine operation.
#define TYPE_COS (1)
Used to specify cosine operation.
#define TYPE_RAD (0)
Used to specify result in radians.
#define TYPE_PU (1)
Used to specify per-unit result.
Functions
__STATIC_INLINE int_fast32_t __IQNcalcSin (uint_fast32_t uiq31Input)
Computes the sine of an UIQ31 input.
__STATIC_INLINE int_fast32_t __IQNcalcCos (uint_fast32_t uiq31Input)
Computes the cosine of an UIQ31 input.
__STATIC_INLINE int_fast32_t __IQNsin_cos (int_fast32_t iqNInput, const int8_t q_value, const int8_t type, const int8_t format)
Computes the sine or cosine of an IQN input.
int32_t _IQ29sin (int32_t a)
Computes the cosine of an IQ29 input.
int32_t _IQ28sin (int32_t a)
Computes the sine of an IQ28 input.
int32_t _IQ27sin (int32_t a)
Computes the sine of an IQ27 input.
int32_t _IQ26sin (int32_t a)
Computes the sine of an IQ26 input.
int32_t _IQ25sin (int32_t a)
Computes the sine of an IQ25 input.
int32_t _IQ24sin (int32_t a)
Computes the sine of an IQ24 input.
int32_t _IQ23sin (int32_t a)
Computes the sine of an IQ23 input.
int32_t _IQ22sin (int32_t a)
Computes the sine of an IQ22 input.
int32_t _IQ21sin (int32_t a)
Computes the sine of an IQ21 input.
int32_t _IQ20sin (int32_t a)
Computes the sine of an IQ20 input.
int32_t _IQ19sin (int32_t a)
Computes the sine of an IQ19 input.
int32_t _IQ18sin (int32_t a)
Computes the sine of an IQ18 input.
int32_t _IQ17sin (int32_t a)
Computes the sine of an IQ17 input.
int32_t _IQ16sin (int32_t a)
Computes the sine of an IQ16 input.
int32_t _IQ15sin (int32_t a)
Computes the sine of an IQ15 input.
int32_t _IQ14sin (int32_t a)
Computes the sine of an IQ14 input.
int32_t _IQ13sin (int32_t a)
Computes the sine of an IQ13 input.
int32_t _IQ12sin (int32_t a)
Computes the sine of an IQ12 input.
int32_t _IQ11sin (int32_t a)
Computes the sine of an IQ11 input.
int32_t _IQ10sin (int32_t a)
Computes the sine of an IQ10 input.
int32_t _IQ9sin (int32_t a)
Computes the sine of an IQ9 input.
int32_t _IQ8sin (int32_t a)
Computes the sine of an IQ8 input.
int32_t _IQ7sin (int32_t a)
Computes the sine of an IQ7 input.
int32_t _IQ6sin (int32_t a)
Computes the sine of an IQ6 input.
int32_t _IQ5sin (int32_t a)
Computes the sine of an IQ5 input.
int32_t _IQ4sin (int32_t a)
Computes the sine of an IQ4 input.
int32_t _IQ3sin (int32_t a)
Computes the sine of an IQ3 input.
int32_t _IQ2sin (int32_t a)
Computes the sine of an IQ2 input.
int32_t _IQ1sin (int32_t a)
Computes the sine of an IQ1 input.
int32_t _IQ29cos (int32_t a)
Computes the cosine of an IQ29 input.
int32_t _IQ28cos (int32_t a)
Computes the cosine of an IQ28 input.
int32_t _IQ27cos (int32_t a)
Computes the cosine of an IQ27 input.
int32_t _IQ26cos (int32_t a)
Computes the cosine of an IQ26 input.
int32_t _IQ25cos (int32_t a)
Computes the cosine of an IQ25 input.
int32_t _IQ24cos (int32_t a)
Computes the cosine of an IQ24 input.
int32_t _IQ23cos (int32_t a)
Computes the cosine of an IQ23 input.
int32_t _IQ22cos (int32_t a)
Computes the cosine of an IQ22 input.
int32_t _IQ21cos (int32_t a)
Computes the cosine of an IQ21 input.
int32_t _IQ20cos (int32_t a)
Computes the cosine of an IQ20 input.
int32_t _IQ19cos (int32_t a)
Computes the cosine of an IQ19 input.
int32_t _IQ18cos (int32_t a)
Computes the cosine of an IQ18 input.
int32_t _IQ17cos (int32_t a)
Computes the cosine of an IQ17 input.
int32_t _IQ16cos (int32_t a)
Computes the cosine of an IQ16 input.
int32_t _IQ15cos (int32_t a)
Computes the cosine of an IQ15 input.
int32_t _IQ14cos (int32_t a)
Computes the cosine of an IQ14 input.
int32_t _IQ13cos (int32_t a)
Computes the cosine of an IQ13 input.
int32_t _IQ12cos (int32_t a)
Computes the cosine of an IQ12 input.
int32_t _IQ11cos (int32_t a)
Computes the cosine of an IQ11 input.
int32_t _IQ10cos (int32_t a)
Computes the cosine of an IQ10 input.
int32_t _IQ9cos (int32_t a)
Computes the cosine of an IQ9 input.
int32_t _IQ8cos (int32_t a)
Computes the cosine of an IQ8 input.
int32_t _IQ7cos (int32_t a)
Computes the cosine of an IQ7 input.
int32_t _IQ6cos (int32_t a)
Computes the cosine of an IQ6 input.
int32_t _IQ5cos (int32_t a)
Computes the cosine of an IQ5 input.
int32_t _IQ4cos (int32_t a)
Computes the cosine of an IQ4 input.
int32_t _IQ3cos (int32_t a)
Computes the cosine of an IQ3 input.
int32_t _IQ2cos (int32_t a)
Computes the cosine of an IQ2 input.
int32_t _IQ1cos (int32_t a)
Computes the cosine of an IQ1 input.
int32_t _IQ31sinPU (int32_t a)
Computes the sine of an IQ31 input.
int32_t _IQ30sinPU (int32_t a)
Computes the sine of an IQ30 input.
int32_t _IQ29sinPU (int32_t a)
Computes the sine of an IQ29 input.
int32_t _IQ28sinPU (int32_t a)
Computes the sine of an IQ28 input.
int32_t _IQ27sinPU (int32_t a)
Computes the sine of an IQ27 input.
int32_t _IQ26sinPU (int32_t a)
Computes the sine of an IQ26 input.
int32_t _IQ25sinPU (int32_t a)
Computes the sine of an IQ25 input.
int32_t _IQ24sinPU (int32_t a)
Computes the sine of an IQ24 input.
int32_t _IQ23sinPU (int32_t a)
Computes the sine of an IQ23 input.
int32_t _IQ22sinPU (int32_t a)
Computes the sine of an IQ22 input.
int32_t _IQ21sinPU (int32_t a)
Computes the sine of an IQ21 input.
int32_t _IQ20sinPU (int32_t a)
Computes the sine of an IQ20 input.
int32_t _IQ19sinPU (int32_t a)
Computes the sine of an IQ19 input.
int32_t _IQ18sinPU (int32_t a)
Computes the sine of an IQ18 input.
int32_t _IQ17sinPU (int32_t a)
Computes the sine of an IQ17 input.
int32_t _IQ16sinPU (int32_t a)
Computes the sine of an IQ16 input.
int32_t _IQ15sinPU (int32_t a)
Computes the sine of an IQ15 input.
int32_t _IQ14sinPU (int32_t a)
Computes the sine of an IQ14 input.
int32_t _IQ13sinPU (int32_t a)
Computes the sine of an IQ13 input.
int32_t _IQ12sinPU (int32_t a)
Computes the sine of an IQ12 input.
int32_t _IQ11sinPU (int32_t a)
Computes the sine of an IQ11 input.
int32_t _IQ10sinPU (int32_t a)
Computes the sine of an IQ10 input.
int32_t _IQ9sinPU (int32_t a)
Computes the sine of an IQ9 input.
int32_t _IQ8sinPU (int32_t a)
Computes the sine of an IQ8 input.
int32_t _IQ7sinPU (int32_t a)
Computes the sine of an IQ7 input.
int32_t _IQ6sinPU (int32_t a)
Computes the sine of an IQ6 input.
int32_t _IQ5sinPU (int32_t a)
Computes the sine of an IQ5 input.
int32_t _IQ4sinPU (int32_t a)
Computes the sine of an IQ4 input.
int32_t _IQ3sinPU (int32_t a)
Computes the sine of an IQ3 input.
int32_t _IQ2sinPU (int32_t a)
Computes the sine of an IQ2 input.
int32_t _IQ1sinPU (int32_t a)
Computes the sine of an IQ1 input.
int32_t _IQ31cosPU (int32_t a)
Computes the cosine of an IQ31 input.
int32_t _IQ30cosPU (int32_t a)
Computes the cosine of an IQ30 input.
int32_t _IQ29cosPU (int32_t a)
Computes the cosine of an IQ29 input.
int32_t _IQ28cosPU (int32_t a)
Computes the cosine of an IQ28 input.
int32_t _IQ27cosPU (int32_t a)
Computes the cosine of an IQ27 input.
int32_t _IQ26cosPU (int32_t a)
Computes the cosine of an IQ26 input.
int32_t _IQ25cosPU (int32_t a)
Computes the cosine of an IQ25 input.
int32_t _IQ24cosPU (int32_t a)
Computes the cosine of an IQ24 input.
int32_t _IQ23cosPU (int32_t a)
Computes the cosine of an IQ23 input.
int32_t _IQ22cosPU (int32_t a)
Computes the cosine of an IQ22 input.
int32_t _IQ21cosPU (int32_t a)
Computes the cosine of an IQ21 input.
int32_t _IQ20cosPU (int32_t a)
Computes the cosine of an IQ20 input.
int32_t _IQ19cosPU (int32_t a)
Computes the cosine of an IQ19 input.
int32_t _IQ18cosPU (int32_t a)
Computes the cosine of an IQ18 input.
int32_t _IQ17cosPU (int32_t a)
Computes the cosine of an IQ17 input.
int32_t _IQ16cosPU (int32_t a)
Computes the cosine of an IQ16 input.
int32_t _IQ15cosPU (int32_t a)
Computes the cosine of an IQ15 input.
int32_t _IQ14cosPU (int32_t a)
Computes the cosine of an IQ14 input.
int32_t _IQ13cosPU (int32_t a)
Computes the cosine of an IQ13 input.
int32_t _IQ12cosPU (int32_t a)
Computes the cosine of an IQ12 input.
int32_t _IQ11cosPU (int32_t a)
Computes the cosine of an IQ11 input.
int32_t _IQ10cosPU (int32_t a)
Computes the cosine of an IQ10 input.
int32_t _IQ9cosPU (int32_t a)
Computes the cosine of an IQ9 input.
int32_t _IQ8cosPU (int32_t a)
Computes the cosine of an IQ8 input.
int32_t _IQ7cosPU (int32_t a)
Computes the cosine of an IQ7 input.
int32_t _IQ6cosPU (int32_t a)
Computes the cosine of an IQ6 input.
int32_t _IQ5cosPU (int32_t a)
Computes the cosine of an IQ5 input.
int32_t _IQ4cosPU (int32_t a)
Computes the cosine of an IQ4 input.
int32_t _IQ3cosPU (int32_t a)
Computes the cosine of an IQ3 input.
int32_t _IQ2cosPU (int32_t a)
Computes the cosine of an IQ2 input.
int32_t _IQ1cosPU (int32_t a)
Computes the cosine of an IQ1 input.
Function Documentation
__IQNcalcSin()
__STATIC_INLINE int_fast32_t __IQNcalcSin (uint_fast32_t uiq31Input)
Computes the sine of an UIQ31 input.
Parameters
uiq31Input UIQ31 type input.
Returns
UIQ31 type result of sine.
Referenced by __IQNsin_cos().
__IQNcalcCos()
__STATIC_INLINE int_fast32_t __IQNcalcCos (uint_fast32_t uiq31Input)
Computes the cosine of an UIQ31 input.
Parameters
uiq31Input UIQ31 type input.
Returns
UIQ31 type result of cosine.
Referenced by __IQNsin_cos().
__IQNsin_cos()
__STATIC_INLINE int_fast32_t __IQNsin_cos (int_fast32_t iqNInput, const int8_t q_value, const int8_t type, const int8_t format)
Computes the sine or cosine of an IQN input.
Parameters
iqNInput IQN type input.
q_value IQ format.
type Specifies sine or cosine operation.
format Specifies radians or per-unit operation.
Returns
IQN type result of sin or cosine operation.
References __IQNcalcCos(), __IQNcalcSin(), PI, TYPE_COS, TYPE_PU, and TYPE_SIN.
Referenced by _IQ10cos(), _IQ10cosPU(), _IQ10sin(), _IQ10sinPU(), _IQ11cos(), _IQ11cosPU(), _IQ11sin(), _IQ11sinPU(), _IQ12cos(), _IQ12cosPU(), _IQ12sin(), _IQ12sinPU(), _IQ13cos(), _IQ13cosPU(), _IQ13sin(), _IQ13sinPU(), _IQ14cos(), _IQ14cosPU(), _IQ14sin(), _IQ14sinPU(), _IQ15cos(), _IQ15cosPU(), _IQ15sin(), _IQ15sinPU(), _IQ16cos(), _IQ16cosPU(), _IQ16sin(), _IQ16sinPU(), _IQ17cos(), _IQ17cosPU(), _IQ17sin(), _IQ17sinPU(), _IQ18cos(), _IQ18cosPU(), _IQ18sin(), _IQ18sinPU(), _IQ19cos(), _IQ19cosPU(), _IQ19sin(), _IQ19sinPU(), _IQ1cos(), _IQ1cosPU(), _IQ1sin(), _IQ1sinPU(), _IQ20cos(), _IQ20cosPU(), _IQ20sin(), _IQ20sinPU(), _IQ21cos(), _IQ21cosPU(), _IQ21sin(), _IQ21sinPU(), _IQ22cos(), _IQ22cosPU(), _IQ22sin(), _IQ22sinPU(), _IQ23cos(), _IQ23cosPU(), _IQ23sin(), _IQ23sinPU(), _IQ24cos(), _IQ24cosPU(), _IQ24sin(), _IQ24sinPU(), _IQ25cos(), _IQ25cosPU(), _IQ25sin(), _IQ25sinPU(), _IQ26cos(), _IQ26cosPU(), _IQ26sin(), _IQ26sinPU(), _IQ27cos(), _IQ27cosPU(), _IQ27sin(), _IQ27sinPU(), _IQ28cos(), _IQ28cosPU(), _IQ28sin(), _IQ28sinPU(), _IQ29cos(), _IQ29cosPU(), _IQ29sin(), _IQ29sinPU(), _IQ2cos(), _IQ2cosPU(), _IQ2sin(), _IQ2sinPU(), _IQ30cosPU(), _IQ30sinPU(), _IQ31cosPU(), _IQ31sinPU(), _IQ3cos(), _IQ3cosPU(), _IQ3sin(), _IQ3sinPU(), _IQ4cos(), _IQ4cosPU(), _IQ4sin(), _IQ4sinPU(), _IQ5cos(), _IQ5cosPU(), _IQ5sin(), _IQ5sinPU(), _IQ6cos(), _IQ6cosPU(), _IQ6sin(), _IQ6sinPU(), _IQ7cos(), _IQ7cosPU(), _IQ7sin(), _IQ7sinPU(), _IQ8cos(), _IQ8cosPU(), _IQ8sin(), _IQ8sinPU(), _IQ9cos(), _IQ9cosPU(), _IQ9sin(), and _IQ9sinPU().
_IQ29sin()
int32_t _IQ29sin (int32_t a)
Computes the cosine of an IQ29 input.
Parameters
a IQ29 type input.
Returns
IQ29 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ28sin()
int32_t _IQ28sin (int32_t a)
Computes the sine of an IQ28 input.
Parameters
a IQ28 type input.
Returns
IQ28 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ27sin()
int32_t _IQ27sin (int32_t a)
Computes the sine of an IQ27 input.
Parameters
a IQ27 type input.
Returns
IQ27 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ26sin()
int32_t _IQ26sin (int32_t a)
Computes the sine of an IQ26 input.
Parameters
a IQ26 type input.
Returns
IQ26 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ25sin()
int32_t _IQ25sin (int32_t a)
Computes the sine of an IQ25 input.
Parameters
a IQ25 type input.
Returns
IQ25 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ24sin()
int32_t _IQ24sin (int32_t a)
Computes the sine of an IQ24 input.
Parameters
a IQ24 type input.
Returns
IQ24 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ23sin()
int32_t _IQ23sin (int32_t a)
Computes the sine of an IQ23 input.
Parameters
a IQ23 type input.
Returns
IQ23 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ22sin()
int32_t _IQ22sin (int32_t a)
Computes the sine of an IQ22 input.
Parameters
a IQ22 type input.
Returns
IQ22 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ21sin()
int32_t _IQ21sin (int32_t a)
Computes the sine of an IQ21 input.
Parameters
a IQ21 type input.
Returns
IQ21 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ20sin()
int32_t _IQ20sin (int32_t a)
Computes the sine of an IQ20 input.
Parameters
a IQ20 type input.
Returns
IQ20 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ19sin()
int32_t _IQ19sin (int32_t a)
Computes the sine of an IQ19 input.
Parameters
a IQ19 type input.
Returns
IQ19 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ18sin()
int32_t _IQ18sin (int32_t a)
Computes the sine of an IQ18 input.
Parameters
a IQ18 type input.
Returns
IQ18 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ17sin()
int32_t _IQ17sin (int32_t a)
Computes the sine of an IQ17 input.
Parameters
a IQ17 type input.
Returns
IQ17 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ16sin()
int32_t _IQ16sin (int32_t a)
Computes the sine of an IQ16 input.
Parameters
a IQ16 type input.
Returns
IQ16 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ15sin()
int32_t _IQ15sin (int32_t a)
Computes the sine of an IQ15 input.
Parameters
a IQ15 type input.
Returns
IQ15 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ14sin()
int32_t _IQ14sin (int32_t a)
Computes the sine of an IQ14 input.
Parameters
a IQ14 type input.
Returns
IQ14 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ13sin()
int32_t _IQ13sin (int32_t a)
Computes the sine of an IQ13 input.
Parameters
a IQ13 type input.
Returns
IQ13 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ12sin()
int32_t _IQ12sin (int32_t a)
Computes the sine of an IQ12 input.
Parameters
a IQ12 type input.
Returns
IQ12 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ11sin()
int32_t _IQ11sin (int32_t a)
Computes the sine of an IQ11 input.
Parameters
a IQ11 type input.
Returns
IQ11 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ10sin()
int32_t _IQ10sin (int32_t a)
Computes the sine of an IQ10 input.
Parameters
a IQ10 type input.
Returns
IQ10 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ9sin()
int32_t _IQ9sin (int32_t a)
Computes the sine of an IQ9 input.
Parameters
a IQ9 type input.
Returns
IQ9 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ8sin()
int32_t _IQ8sin (int32_t a)
Computes the sine of an IQ8 input.
Parameters
a IQ8 type input.
Returns
IQ8 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ7sin()
int32_t _IQ7sin (int32_t a)
Computes the sine of an IQ7 input.
Parameters
a IQ7 type input.
Returns
IQ7 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ6sin()
int32_t _IQ6sin (int32_t a)
Computes the sine of an IQ6 input.
Parameters
a IQ6 type input.
Returns
IQ6 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ5sin()
int32_t _IQ5sin (int32_t a)
Computes the sine of an IQ5 input.
Parameters
a IQ5 type input.
Returns
IQ5 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ4sin()
int32_t _IQ4sin (int32_t a)
Computes the sine of an IQ4 input.
Parameters
a IQ4 type input.
Returns
IQ4 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ3sin()
int32_t _IQ3sin (int32_t a)
Computes the sine of an IQ3 input.
Parameters
a IQ3 type input.
Returns
IQ3 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ2sin()
int32_t _IQ2sin (int32_t a)
Computes the sine of an IQ2 input.
Parameters
a IQ2 type input.
Returns
IQ2 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ1sin()
int32_t _IQ1sin (int32_t a)
Computes the sine of an IQ1 input.
Parameters
a IQ1 type input.
Returns
IQ1 type result of sine operation, in radians.
References __IQNsin_cos(), TYPE_RAD, and TYPE_SIN.
_IQ29cos()
int32_t _IQ29cos (int32_t a)
Computes the cosine of an IQ29 input.
Parameters
a IQ29 type input.
Returns
IQ29 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ28cos()
int32_t _IQ28cos (int32_t a)
Computes the cosine of an IQ28 input.
Parameters
a IQ28 type input.
Returns
IQ28 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ27cos()
int32_t _IQ27cos (int32_t a)
Computes the cosine of an IQ27 input.
Parameters
a IQ27 type input.
Returns
IQ27 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ26cos()
int32_t _IQ26cos (int32_t a)
Computes the cosine of an IQ26 input.
Parameters
a IQ26 type input.
Returns
IQ26 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ25cos()
int32_t _IQ25cos (int32_t a)
Computes the cosine of an IQ25 input.
Parameters
a IQ25 type input.
Returns
IQ25 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ24cos()
int32_t _IQ24cos (int32_t a)
Computes the cosine of an IQ24 input.
Parameters
a IQ24 type input.
Returns
IQ24 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ23cos()
int32_t _IQ23cos (int32_t a)
Computes the cosine of an IQ23 input.
Parameters
a IQ23 type input.
Returns
IQ23 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ22cos()
int32_t _IQ22cos (int32_t a)
Computes the cosine of an IQ22 input.
Parameters
a IQ22 type input.
Returns
IQ22 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ21cos()
int32_t _IQ21cos (int32_t a)
Computes the cosine of an IQ21 input.
Parameters
a IQ21 type input.
Returns
IQ21 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ20cos()
int32_t _IQ20cos (int32_t a)
Computes the cosine of an IQ20 input.
Parameters
a IQ20 type input.
Returns
IQ20 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ19cos()
int32_t _IQ19cos (int32_t a)
Computes the cosine of an IQ19 input.
Parameters
a IQ19 type input.
Returns
IQ19 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ18cos()
int32_t _IQ18cos (int32_t a)
Computes the cosine of an IQ18 input.
Parameters
a IQ18 type input.
Returns
IQ18 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ17cos()
int32_t _IQ17cos (int32_t a)
Computes the cosine of an IQ17 input.
Parameters
a IQ17 type input.
Returns
IQ17 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ16cos()
int32_t _IQ16cos (int32_t a)
Computes the cosine of an IQ16 input.
Parameters
a IQ16 type input.
Returns
IQ16 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ15cos()
int32_t _IQ15cos (int32_t a)
Computes the cosine of an IQ15 input.
Parameters
a IQ15 type input.
Returns
IQ15 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ14cos()
int32_t _IQ14cos (int32_t a)
Computes the cosine of an IQ14 input.
Parameters
a IQ14 type input.
Returns
IQ14 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ13cos()
int32_t _IQ13cos (int32_t a)
Computes the cosine of an IQ13 input.
Parameters
a IQ13 type input.
Returns
IQ13 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ12cos()
int32_t _IQ12cos (int32_t a)
Computes the cosine of an IQ12 input.
Parameters
a IQ12 type input.
Returns
IQ12 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ11cos()
int32_t _IQ11cos (int32_t a)
Computes the cosine of an IQ11 input.
Parameters
a IQ11 type input.
Returns
IQ11 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ10cos()
int32_t _IQ10cos (int32_t a)
Computes the cosine of an IQ10 input.
Parameters
a IQ10 type input.
Returns
IQ10 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ9cos()
int32_t _IQ9cos (int32_t a)
Computes the cosine of an IQ9 input.
Parameters
a IQ9 type input.
Returns
IQ9 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ8cos()
int32_t _IQ8cos (int32_t a)
Computes the cosine of an IQ8 input.
Parameters
a IQ8 type input.
Returns
IQ8 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ7cos()
int32_t _IQ7cos (int32_t a)
Computes the cosine of an IQ7 input.
Parameters
a IQ7 type input.
Returns
IQ7 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ6cos()
int32_t _IQ6cos (int32_t a)
Computes the cosine of an IQ6 input.
Parameters
a IQ6 type input.
Returns
IQ6 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ5cos()
int32_t _IQ5cos (int32_t a)
Computes the cosine of an IQ5 input.
Parameters
a IQ5 type input.
Returns
IQ5 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ4cos()
int32_t _IQ4cos (int32_t a)
Computes the cosine of an IQ4 input.
Parameters
a IQ4 type input.
Returns
IQ4 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ3cos()
int32_t _IQ3cos (int32_t a)
Computes the cosine of an IQ3 input.
Parameters
a IQ3 type input.
Returns
IQ3 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ2cos()
int32_t _IQ2cos (int32_t a)
Computes the cosine of an IQ2 input.
Parameters
a IQ2 type input.
Returns
IQ2 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ1cos()
int32_t _IQ1cos (int32_t a)
Computes the cosine of an IQ1 input.
Parameters
a IQ1 type input.
Returns
IQ1 type result of cosine operation, in radians.
References __IQNsin_cos(), TYPE_COS, and TYPE_RAD.
_IQ31sinPU()
int32_t _IQ31sinPU (int32_t a)
Computes the sine of an IQ31 input.
Parameters
a IQ31 type input.
Returns
IQ31 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ30sinPU()
int32_t _IQ30sinPU (int32_t a)
Computes the sine of an IQ30 input.
Parameters
a IQ30 type input.
Returns
IQ30 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ29sinPU()
int32_t _IQ29sinPU (int32_t a)
Computes the sine of an IQ29 input.
Parameters
a IQ29 type input.
Returns
IQ29 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ28sinPU()
int32_t _IQ28sinPU (int32_t a)
Computes the sine of an IQ28 input.
Parameters
a IQ28 type input.
Returns
IQ28 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ27sinPU()
int32_t _IQ27sinPU (int32_t a)
Computes the sine of an IQ27 input.
Parameters
a IQ27 type input.
Returns
IQ27 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ26sinPU()
int32_t _IQ26sinPU (int32_t a)
Computes the sine of an IQ26 input.
Parameters
a IQ26 type input.
Returns
IQ26 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ25sinPU()
int32_t _IQ25sinPU (int32_t a)
Computes the sine of an IQ25 input.
Parameters
a IQ25 type input.
Returns
IQ25 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ24sinPU()
int32_t _IQ24sinPU (int32_t a)
Computes the sine of an IQ24 input.
Parameters
a IQ24 type input.
Returns
IQ24 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ23sinPU()
int32_t _IQ23sinPU (int32_t a)
Computes the sine of an IQ23 input.
Parameters
a IQ23 type input.
Returns
IQ23 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ22sinPU()
int32_t _IQ22sinPU (int32_t a)
Computes the sine of an IQ22 input.
Parameters
a IQ22 type input.
Returns
IQ22 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ21sinPU()
int32_t _IQ21sinPU (int32_t a)
Computes the sine of an IQ21 input.
Parameters
a IQ21 type input.
Returns
IQ21 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ20sinPU()
int32_t _IQ20sinPU (int32_t a)
Computes the sine of an IQ20 input.
Parameters
a IQ20 type input.
Returns
IQ20 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ19sinPU()
int32_t _IQ19sinPU (int32_t a)
Computes the sine of an IQ19 input.
Parameters
a IQ19 type input.
Returns
IQ19 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ18sinPU()
int32_t _IQ18sinPU (int32_t a)
Computes the sine of an IQ18 input.
Parameters
a IQ18 type input.
Returns
IQ18 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ17sinPU()
int32_t _IQ17sinPU (int32_t a)
Computes the sine of an IQ17 input.
Parameters
a IQ17 type input.
Returns
IQ17 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ16sinPU()
int32_t _IQ16sinPU (int32_t a)
Computes the sine of an IQ16 input.
Parameters
a IQ16 type input.
Returns
IQ16 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ15sinPU()
int32_t _IQ15sinPU (int32_t a)
Computes the sine of an IQ15 input.
Parameters
a IQ15 type input.
Returns
IQ15 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ14sinPU()
int32_t _IQ14sinPU (int32_t a)
Computes the sine of an IQ14 input.
Parameters
a IQ14 type input.
Returns
IQ14 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ13sinPU()
int32_t _IQ13sinPU (int32_t a)
Computes the sine of an IQ13 input.
Parameters
a IQ13 type input.
Returns
IQ13 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ12sinPU()
int32_t _IQ12sinPU (int32_t a)
Computes the sine of an IQ12 input.
Parameters
a IQ12 type input.
Returns
IQ12 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ11sinPU()
int32_t _IQ11sinPU (int32_t a)
Computes the sine of an IQ11 input.
Parameters
a IQ11 type input.
Returns
IQ11 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ10sinPU()
int32_t _IQ10sinPU (int32_t a)
Computes the sine of an IQ10 input.
Parameters
a IQ10 type input.
Returns
IQ10 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ9sinPU()
int32_t _IQ9sinPU (int32_t a)
Computes the sine of an IQ9 input.
Parameters
a IQ9 type input.
Returns
IQ9 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ8sinPU()
int32_t _IQ8sinPU (int32_t a)
Computes the sine of an IQ8 input.
Parameters
a IQ8 type input.
Returns
IQ8 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ7sinPU()
int32_t _IQ7sinPU (int32_t a)
Computes the sine of an IQ7 input.
Parameters
a IQ7 type input.
Returns
IQ7 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ6sinPU()
int32_t _IQ6sinPU (int32_t a)
Computes the sine of an IQ6 input.
Parameters
a IQ6 type input.
Returns
IQ6 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ5sinPU()
int32_t _IQ5sinPU (int32_t a)
Computes the sine of an IQ5 input.
Parameters
a IQ5 type input.
Returns
IQ5 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ4sinPU()
int32_t _IQ4sinPU (int32_t a)
Computes the sine of an IQ4 input.
Parameters
a IQ4 type input.
Returns
IQ4 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ3sinPU()
int32_t _IQ3sinPU (int32_t a)
Computes the sine of an IQ3 input.
Parameters
a IQ3 type input.
Returns
IQ3 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ2sinPU()
int32_t _IQ2sinPU (int32_t a)
Computes the sine of an IQ2 input.
Parameters
a IQ2 type input.
Returns
IQ2 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ1sinPU()
int32_t _IQ1sinPU (int32_t a)
Computes the sine of an IQ1 input.
Parameters
a IQ1 type input.
Returns
IQ1 type per-unit result of sine operation.
References __IQNsin_cos(), TYPE_PU, and TYPE_SIN.
_IQ31cosPU()
int32_t _IQ31cosPU (int32_t a)
Computes the cosine of an IQ31 input.
Parameters
a IQ31 type input.
Returns
IQ31 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ30cosPU()
int32_t _IQ30cosPU (int32_t a)
Computes the cosine of an IQ30 input.
Parameters
a IQ30 type input.
Returns
IQ30 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ29cosPU()
int32_t _IQ29cosPU (int32_t a)
Computes the cosine of an IQ29 input.
Parameters
a IQ29 type input.
Returns
IQ29 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ28cosPU()
int32_t _IQ28cosPU (int32_t a)
Computes the cosine of an IQ28 input.
Parameters
a IQ28 type input.
Returns
IQ28 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ27cosPU()
int32_t _IQ27cosPU (int32_t a)
Computes the cosine of an IQ27 input.
Parameters
a IQ27 type input.
Returns
IQ27 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ26cosPU()
int32_t _IQ26cosPU (int32_t a)
Computes the cosine of an IQ26 input.
Parameters
a IQ26 type input.
Returns
IQ26 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ25cosPU()
int32_t _IQ25cosPU (int32_t a)
Computes the cosine of an IQ25 input.
Parameters
a IQ25 type input.
Returns
IQ25 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ24cosPU()
int32_t _IQ24cosPU (int32_t a)
Computes the cosine of an IQ24 input.
Parameters
a IQ24 type input.
Returns
IQ24 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ23cosPU()
int32_t _IQ23cosPU (int32_t a)
Computes the cosine of an IQ23 input.
Parameters
a IQ23 type input.
Returns
IQ23 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ22cosPU()
int32_t _IQ22cosPU (int32_t a)
Computes the cosine of an IQ22 input.
Parameters
a IQ22 type input.
Returns
IQ22 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ21cosPU()
int32_t _IQ21cosPU (int32_t a)
Computes the cosine of an IQ21 input.
Parameters
a IQ21 type input.
Returns
IQ21 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ20cosPU()
int32_t _IQ20cosPU (int32_t a)
Computes the cosine of an IQ20 input.
Parameters
a IQ20 type input.
Returns
IQ20 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ19cosPU()
int32_t _IQ19cosPU (int32_t a)
Computes the cosine of an IQ19 input.
Parameters
a IQ19 type input.
Returns
IQ19 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ18cosPU()
int32_t _IQ18cosPU (int32_t a)
Computes the cosine of an IQ18 input.
Parameters
a IQ18 type input.
Returns
IQ18 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ17cosPU()
int32_t _IQ17cosPU (int32_t a)
Computes the cosine of an IQ17 input.
Parameters
a IQ17 type input.
Returns
IQ17 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ16cosPU()
int32_t _IQ16cosPU (int32_t a)
Computes the cosine of an IQ16 input.
Parameters
a IQ16 type input.
Returns
IQ16 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ15cosPU()
int32_t _IQ15cosPU (int32_t a)
Computes the cosine of an IQ15 input.
Parameters
a IQ15 type input.
Returns
IQ15 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ14cosPU()
int32_t _IQ14cosPU (int32_t a)
Computes the cosine of an IQ14 input.
Parameters
a IQ14 type input.
Returns
IQ14 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ13cosPU()
int32_t _IQ13cosPU (int32_t a)
Computes the cosine of an IQ13 input.
Parameters
a IQ13 type input.
Returns
IQ13 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ12cosPU()
int32_t _IQ12cosPU (int32_t a)
Computes the cosine of an IQ12 input.
Parameters
a IQ12 type input.
Returns
IQ12 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ11cosPU()
int32_t _IQ11cosPU (int32_t a)
Computes the cosine of an IQ11 input.
Parameters
a IQ11 type input.
Returns
IQ11 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ10cosPU()
int32_t _IQ10cosPU (int32_t a)
Computes the cosine of an IQ10 input.
Parameters
a IQ10 type input.
Returns
IQ10 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ9cosPU()
int32_t _IQ9cosPU (int32_t a)
Computes the cosine of an IQ9 input.
Parameters
a IQ9 type input.
Returns
IQ9 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ8cosPU()
int32_t _IQ8cosPU (int32_t a)
Computes the cosine of an IQ8 input.
Parameters
a IQ8 type input.
Returns
IQ8 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ7cosPU()
int32_t _IQ7cosPU (int32_t a)
Computes the cosine of an IQ7 input.
Parameters
a IQ7 type input.
Returns
IQ7 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ6cosPU()
int32_t _IQ6cosPU (int32_t a)
Computes the cosine of an IQ6 input.
Parameters
a IQ6 type input.
Returns
IQ6 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ5cosPU()
int32_t _IQ5cosPU (int32_t a)
Computes the cosine of an IQ5 input.
Parameters
a IQ5 type input.
Returns
IQ5 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ4cosPU()
int32_t _IQ4cosPU (int32_t a)
Computes the cosine of an IQ4 input.
Parameters
a IQ4 type input.
Returns
IQ4 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ3cosPU()
int32_t _IQ3cosPU (int32_t a)
Computes the cosine of an IQ3 input.
Parameters
a IQ3 type input.
Returns
IQ3 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ2cosPU()
int32_t _IQ2cosPU (int32_t a)
Computes the cosine of an IQ2 input.
Parameters
a IQ2 type input.
Returns
IQ2 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
_IQ1cosPU()
int32_t _IQ1cosPU (int32_t a)
Computes the cosine of an IQ1 input.
Parameters
a IQ1 type input.
Returns
IQ1 type per-unit result of cosine operation.
References __IQNsin_cos(), TYPE_COS, and TYPE_PU.
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale