IQMathLibrary: _IQNexp.c File Reference
_IQNexp.c File Reference
Detailed Description
Functions to compute the exponential of the input and return the result.
#include <stdint.h>
#include "../support/support.h"
#include "_IQNtables.h"
Functions
__STATIC_INLINE int_fast32_t __IQNexp (int_fast32_t iqNInput, const uint_fast32_t *iqNLookupTable, uint8_t ui8IntegerOffset, const int_fast32_t iqN_MIN, const int_fast32_t iqN_MAX, const int8_t q_value)
Computes the exponential of an IQN input.
int32_t _IQ30exp (int32_t a)
Computes the exponential of an IQ30 input.
int32_t _IQ29exp (int32_t a)
Computes the exponential of an IQ29 input.
int32_t _IQ28exp (int32_t a)
Computes the exponential of an IQ28 input.
int32_t _IQ27exp (int32_t a)
Computes the exponential of an IQ27 input.
int32_t _IQ26exp (int32_t a)
Computes the exponential of an IQ26 input.
int32_t _IQ25exp (int32_t a)
Computes the exponential of an IQ25 input.
int32_t _IQ24exp (int32_t a)
Computes the exponential of an IQ24 input.
int32_t _IQ23exp (int32_t a)
Computes the exponential of an IQ23 input.
int32_t _IQ22exp (int32_t a)
Computes the exponential of an IQ22 input.
int32_t _IQ21exp (int32_t a)
Computes the exponential of an IQ21 input.
int32_t _IQ20exp (int32_t a)
Computes the exponential of an IQ20 input.
int32_t _IQ19exp (int32_t a)
Computes the exponential of an IQ19 input.
int32_t _IQ18exp (int32_t a)
Computes the exponential of an IQ18 input.
int32_t _IQ17exp (int32_t a)
Computes the exponential of an IQ17 input.
int32_t _IQ16exp (int32_t a)
Computes the exponential of an IQ16 input.
int32_t _IQ15exp (int32_t a)
Computes the exponential of an IQ15 input.
int32_t _IQ14exp (int32_t a)
Computes the exponential of an IQ14 input.
int32_t _IQ13exp (int32_t a)
Computes the exponential of an IQ13 input.
int32_t _IQ12exp (int32_t a)
Computes the exponential of an IQ12 input.
int32_t _IQ11exp (int32_t a)
Computes the exponential of an IQ11 input.
int32_t _IQ10exp (int32_t a)
Computes the exponential of an IQ10 input.
int32_t _IQ9exp (int32_t a)
Computes the exponential of an IQ9 input.
int32_t _IQ8exp (int32_t a)
Computes the exponential of an IQ8 input.
int32_t _IQ7exp (int32_t a)
Computes the exponential of an IQ7 input.
int32_t _IQ6exp (int32_t a)
Computes the exponential of an IQ6 input.
int32_t _IQ5exp (int32_t a)
Computes the exponential of an IQ5 input.
int32_t _IQ4exp (int32_t a)
Computes the exponential of an IQ4 input.
int32_t _IQ3exp (int32_t a)
Computes the exponential of an IQ3 input.
int32_t _IQ2exp (int32_t a)
Computes the exponential of an IQ2 input.
int32_t _IQ1exp (int32_t a)
Computes the exponential of an IQ1 input.
Function Documentation
__IQNexp()
__STATIC_INLINE int_fast32_t __IQNexp (int_fast32_t iqNInput, const uint_fast32_t * iqNLookupTable, uint8_t ui8IntegerOffset, const int_fast32_t iqN_MIN, const int_fast32_t iqN_MAX, const int8_t q_value)
Computes the exponential of an IQN input.
Parameters
iqNInput IQN type input.
iqNLookupTable Integer result lookup table.
ui8IntegerOffset Integer portion offset
iqN_MIN Minimum parameter value.
iqN_MAX Maximum parameter value.
q_value IQ format.
Returns
IQN type result of exponential.
Referenced by _IQ10exp(), _IQ11exp(), _IQ12exp(), _IQ13exp(), _IQ14exp(), _IQ15exp(), _IQ16exp(), _IQ17exp(), _IQ18exp(), _IQ19exp(), _IQ1exp(), _IQ20exp(), _IQ21exp(), _IQ22exp(), _IQ23exp(), _IQ24exp(), _IQ25exp(), _IQ26exp(), _IQ27exp(), _IQ28exp(), _IQ29exp(), _IQ2exp(), _IQ30exp(), _IQ3exp(), _IQ4exp(), _IQ5exp(), _IQ6exp(), _IQ7exp(), _IQ8exp(), and _IQ9exp().
_IQ30exp()
int32_t _IQ30exp (int32_t a)
Computes the exponential of an IQ30 input.
Parameters
a IQ30 type input.
Returns
IQ30 type result of exponential.
References __IQNexp().
_IQ29exp()
int32_t _IQ29exp (int32_t a)
Computes the exponential of an IQ29 input.
Parameters
a IQ29 type input.
Returns
IQ29 type result of exponential.
References __IQNexp().
_IQ28exp()
int32_t _IQ28exp (int32_t a)
Computes the exponential of an IQ28 input.
Parameters
a IQ28 type input.
Returns
IQ28 type result of exponential.
References __IQNexp().
_IQ27exp()
int32_t _IQ27exp (int32_t a)
Computes the exponential of an IQ27 input.
Parameters
a IQ27 type input.
Returns
IQ27 type result of exponential.
References __IQNexp().
_IQ26exp()
int32_t _IQ26exp (int32_t a)
Computes the exponential of an IQ26 input.
Parameters
a IQ26 type input.
Returns
IQ26 type result of exponential.
References __IQNexp().
_IQ25exp()
int32_t _IQ25exp (int32_t a)
Computes the exponential of an IQ25 input.
Parameters
a IQ25 type input.
Returns
IQ25 type result of exponential.
References __IQNexp().
_IQ24exp()
int32_t _IQ24exp (int32_t a)
Computes the exponential of an IQ24 input.
Parameters
a IQ24 type input.
Returns
IQ24 type result of exponential.
References __IQNexp().
_IQ23exp()
int32_t _IQ23exp (int32_t a)
Computes the exponential of an IQ23 input.
Parameters
a IQ23 type input.
Returns
IQ23 type result of exponential.
References __IQNexp().
_IQ22exp()
int32_t _IQ22exp (int32_t a)
Computes the exponential of an IQ22 input.
Parameters
a IQ22 type input.
Returns
IQ22 type result of exponential.
References __IQNexp().
_IQ21exp()
int32_t _IQ21exp (int32_t a)
Computes the exponential of an IQ21 input.
Parameters
a IQ21 type input.
Returns
IQ21 type result of exponential.
References __IQNexp().
_IQ20exp()
int32_t _IQ20exp (int32_t a)
Computes the exponential of an IQ20 input.
Parameters
a IQ20 type input.
Returns
IQ20 type result of exponential.
References __IQNexp().
_IQ19exp()
int32_t _IQ19exp (int32_t a)
Computes the exponential of an IQ19 input.
Parameters
a IQ19 type input.
Returns
IQ19 type result of exponential.
References __IQNexp().
_IQ18exp()
int32_t _IQ18exp (int32_t a)
Computes the exponential of an IQ18 input.
Parameters
a IQ18 type input.
Returns
IQ18 type result of exponential.
References __IQNexp().
_IQ17exp()
int32_t _IQ17exp (int32_t a)
Computes the exponential of an IQ17 input.
Parameters
a IQ17 type input.
Returns
IQ17 type result of exponential.
References __IQNexp().
_IQ16exp()
int32_t _IQ16exp (int32_t a)
Computes the exponential of an IQ16 input.
Parameters
a IQ16 type input.
Returns
IQ16 type result of exponential.
References __IQNexp().
_IQ15exp()
int32_t _IQ15exp (int32_t a)
Computes the exponential of an IQ15 input.
Parameters
a IQ15 type input.
Returns
IQ15 type result of exponential.
References __IQNexp().
_IQ14exp()
int32_t _IQ14exp (int32_t a)
Computes the exponential of an IQ14 input.
Parameters
a IQ14 type input.
Returns
IQ14 type result of exponential.
References __IQNexp().
_IQ13exp()
int32_t _IQ13exp (int32_t a)
Computes the exponential of an IQ13 input.
Parameters
a IQ13 type input.
Returns
IQ13 type result of exponential.
References __IQNexp().
_IQ12exp()
int32_t _IQ12exp (int32_t a)
Computes the exponential of an IQ12 input.
Parameters
a IQ12 type input.
Returns
IQ12 type result of exponential.
References __IQNexp().
_IQ11exp()
int32_t _IQ11exp (int32_t a)
Computes the exponential of an IQ11 input.
Parameters
a IQ11 type input.
Returns
IQ11 type result of exponential.
References __IQNexp().
_IQ10exp()
int32_t _IQ10exp (int32_t a)
Computes the exponential of an IQ10 input.
Parameters
a IQ10 type input.
Returns
IQ10 type result of exponential.
References __IQNexp().
_IQ9exp()
int32_t _IQ9exp (int32_t a)
Computes the exponential of an IQ9 input.
Parameters
a IQ9 type input.
Returns
IQ9 type result of exponential.
References __IQNexp().
_IQ8exp()
int32_t _IQ8exp (int32_t a)
Computes the exponential of an IQ8 input.
Parameters
a IQ8 type input.
Returns
IQ8 type result of exponential.
References __IQNexp().
_IQ7exp()
int32_t _IQ7exp (int32_t a)
Computes the exponential of an IQ7 input.
Parameters
a IQ7 type input.
Returns
IQ7 type result of exponential.
References __IQNexp().
_IQ6exp()
int32_t _IQ6exp (int32_t a)
Computes the exponential of an IQ6 input.
Parameters
a IQ6 type input.
Returns
IQ6 type result of exponential.
References __IQNexp().
_IQ5exp()
int32_t _IQ5exp (int32_t a)
Computes the exponential of an IQ5 input.
Parameters
a IQ5 type input.
Returns
IQ5 type result of exponential.
References __IQNexp().
_IQ4exp()
int32_t _IQ4exp (int32_t a)
Computes the exponential of an IQ4 input.
Parameters
a IQ4 type input.
Returns
IQ4 type result of exponential.
References __IQNexp().
_IQ3exp()
int32_t _IQ3exp (int32_t a)
Computes the exponential of an IQ3 input.
Parameters
a IQ3 type input.
Returns
IQ3 type result of exponential.
References __IQNexp().
_IQ2exp()
int32_t _IQ2exp (int32_t a)
Computes the exponential of an IQ2 input.
Parameters
a IQ2 type input.
Returns
IQ2 type result of exponential.
References __IQNexp().
_IQ1exp()
int32_t _IQ1exp (int32_t a)
Computes the exponential of an IQ1 input.
Parameters
a IQ1 type input.
Returns
IQ1 type result of exponential.
References __IQNexp().
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale