IQMathLibrary: _IQNfrac.c File Reference
_IQNfrac.c File Reference
Detailed Description
Functions to return the fractional portion of the input.
#include <stdint.h>
#include "../support/support.h"
Functions
__STATIC_INLINE int_fast32_t __IQNfrac (int_fast32_t iqNInput, int8_t q_value)
Return the fractional portion of an IQN input.
int32_t _IQ30frac (int32_t a)
Return the fractional portion of an IQ30 input.
int32_t _IQ29frac (int32_t a)
Return the fractional portion of an IQ29 input.
int32_t _IQ28frac (int32_t a)
Return the fractional portion of an IQ28 input.
int32_t _IQ27frac (int32_t a)
Return the fractional portion of an IQ27 input.
int32_t _IQ26frac (int32_t a)
Return the fractional portion of an IQ26 input.
int32_t _IQ25frac (int32_t a)
Return the fractional portion of an IQ25 input.
int32_t _IQ24frac (int32_t a)
Return the fractional portion of an IQ24 input.
int32_t _IQ23frac (int32_t a)
Return the fractional portion of an IQ23 input.
int32_t _IQ22frac (int32_t a)
Return the fractional portion of an IQ22 input.
int32_t _IQ21frac (int32_t a)
Return the fractional portion of an IQ21 input.
int32_t _IQ20frac (int32_t a)
Return the fractional portion of an IQ20 input.
int32_t _IQ19frac (int32_t a)
Return the fractional portion of an IQ19 input.
int32_t _IQ18frac (int32_t a)
Return the fractional portion of an IQ18 input.
int32_t _IQ17frac (int32_t a)
Return the fractional portion of an IQ17 input.
int32_t _IQ16frac (int32_t a)
Return the fractional portion of an IQ16 input.
int32_t _IQ15frac (int32_t a)
Return the fractional portion of an IQ15 input.
int32_t _IQ14frac (int32_t a)
Return the fractional portion of an IQ14 input.
int32_t _IQ13frac (int32_t a)
Return the fractional portion of an IQ13 input.
int32_t _IQ12frac (int32_t a)
Return the fractional portion of an IQ12 input.
int32_t _IQ11frac (int32_t a)
Return the fractional portion of an IQ11 input.
int32_t _IQ10frac (int32_t a)
Return the fractional portion of an IQ10 input.
int32_t _IQ9frac (int32_t a)
Return the fractional portion of an IQ9 input.
int32_t _IQ8frac (int32_t a)
Return the fractional portion of an IQ8 input.
int32_t _IQ7frac (int32_t a)
Return the fractional portion of an IQ7 input.
int32_t _IQ6frac (int32_t a)
Return the fractional portion of an IQ6 input.
int32_t _IQ5frac (int32_t a)
Return the fractional portion of an IQ5 input.
int32_t _IQ4frac (int32_t a)
Return the fractional portion of an IQ4 input.
int32_t _IQ3frac (int32_t a)
Return the fractional portion of an IQ3 input.
int32_t _IQ2frac (int32_t a)
Return the fractional portion of an IQ2 input.
int32_t _IQ1frac (int32_t a)
Return the fractional portion of an IQ1 input.
Function Documentation
__IQNfrac()
__STATIC_INLINE int_fast32_t __IQNfrac (int_fast32_t iqNInput, int8_t q_value)
Return the fractional portion of an IQN input.
Parameters
iqNInput IQN type input.
q_value IQ format.
Returns
IQN type fractional portion of input.
Referenced by _IQ10frac(), _IQ11frac(), _IQ12frac(), _IQ13frac(), _IQ14frac(), _IQ15frac(), _IQ16frac(), _IQ17frac(), _IQ18frac(), _IQ19frac(), _IQ1frac(), _IQ20frac(), _IQ21frac(), _IQ22frac(), _IQ23frac(), _IQ24frac(), _IQ25frac(), _IQ26frac(), _IQ27frac(), _IQ28frac(), _IQ29frac(), _IQ2frac(), _IQ30frac(), _IQ3frac(), _IQ4frac(), _IQ5frac(), _IQ6frac(), _IQ7frac(), _IQ8frac(), and _IQ9frac().
_IQ30frac()
int32_t _IQ30frac (int32_t a)
Return the fractional portion of an IQ30 input.
Parameters
a IQ30 type input.
Returns
IQ30 type fractional portion of input.
References __IQNfrac().
_IQ29frac()
int32_t _IQ29frac (int32_t a)
Return the fractional portion of an IQ29 input.
Parameters
a IQ29 type input.
Returns
IQ29 type fractional portion of input.
References __IQNfrac().
_IQ28frac()
int32_t _IQ28frac (int32_t a)
Return the fractional portion of an IQ28 input.
Parameters
a IQ28 type input.
Returns
IQ28 type fractional portion of input.
References __IQNfrac().
_IQ27frac()
int32_t _IQ27frac (int32_t a)
Return the fractional portion of an IQ27 input.
Parameters
a IQ27 type input.
Returns
IQ27 type fractional portion of input.
References __IQNfrac().
_IQ26frac()
int32_t _IQ26frac (int32_t a)
Return the fractional portion of an IQ26 input.
Parameters
a IQ26 type input.
Returns
IQ26 type fractional portion of input.
References __IQNfrac().
_IQ25frac()
int32_t _IQ25frac (int32_t a)
Return the fractional portion of an IQ25 input.
Parameters
a IQ25 type input.
Returns
IQ25 type fractional portion of input.
References __IQNfrac().
_IQ24frac()
int32_t _IQ24frac (int32_t a)
Return the fractional portion of an IQ24 input.
Parameters
a IQ24 type input.
Returns
IQ24 type fractional portion of input.
References __IQNfrac().
_IQ23frac()
int32_t _IQ23frac (int32_t a)
Return the fractional portion of an IQ23 input.
Parameters
a IQ23 type input.
Returns
IQ23 type fractional portion of input.
References __IQNfrac().
_IQ22frac()
int32_t _IQ22frac (int32_t a)
Return the fractional portion of an IQ22 input.
Parameters
a IQ22 type input.
Returns
IQ22 type fractional portion of input.
References __IQNfrac().
_IQ21frac()
int32_t _IQ21frac (int32_t a)
Return the fractional portion of an IQ21 input.
Parameters
a IQ21 type input.
Returns
IQ21 type fractional portion of input.
References __IQNfrac().
_IQ20frac()
int32_t _IQ20frac (int32_t a)
Return the fractional portion of an IQ20 input.
Parameters
a IQ20 type input.
Returns
IQ20 type fractional portion of input.
References __IQNfrac().
_IQ19frac()
int32_t _IQ19frac (int32_t a)
Return the fractional portion of an IQ19 input.
Parameters
a IQ19 type input.
Returns
IQ19 type fractional portion of input.
References __IQNfrac().
_IQ18frac()
int32_t _IQ18frac (int32_t a)
Return the fractional portion of an IQ18 input.
Parameters
a IQ18 type input.
Returns
IQ18 type fractional portion of input.
References __IQNfrac().
_IQ17frac()
int32_t _IQ17frac (int32_t a)
Return the fractional portion of an IQ17 input.
Parameters
a IQ17 type input.
Returns
IQ17 type fractional portion of input.
References __IQNfrac().
_IQ16frac()
int32_t _IQ16frac (int32_t a)
Return the fractional portion of an IQ16 input.
Parameters
a IQ16 type input.
Returns
IQ16 type fractional portion of input.
References __IQNfrac().
_IQ15frac()
int32_t _IQ15frac (int32_t a)
Return the fractional portion of an IQ15 input.
Parameters
a IQ15 type input.
Returns
IQ15 type fractional portion of input.
References __IQNfrac().
_IQ14frac()
int32_t _IQ14frac (int32_t a)
Return the fractional portion of an IQ14 input.
Parameters
a IQ14 type input.
Returns
IQ14 type fractional portion of input.
References __IQNfrac().
_IQ13frac()
int32_t _IQ13frac (int32_t a)
Return the fractional portion of an IQ13 input.
Parameters
a IQ13 type input.
Returns
IQ13 type fractional portion of input.
References __IQNfrac().
_IQ12frac()
int32_t _IQ12frac (int32_t a)
Return the fractional portion of an IQ12 input.
Parameters
a IQ12 type input.
Returns
IQ12 type fractional portion of input.
References __IQNfrac().
_IQ11frac()
int32_t _IQ11frac (int32_t a)
Return the fractional portion of an IQ11 input.
Parameters
a IQ11 type input.
Returns
IQ11 type fractional portion of input.
References __IQNfrac().
_IQ10frac()
int32_t _IQ10frac (int32_t a)
Return the fractional portion of an IQ10 input.
Parameters
a IQ10 type input.
Returns
IQ10 type fractional portion of input.
References __IQNfrac().
_IQ9frac()
int32_t _IQ9frac (int32_t a)
Return the fractional portion of an IQ9 input.
Parameters
a IQ9 type input.
Returns
IQ9 type fractional portion of input.
References __IQNfrac().
_IQ8frac()
int32_t _IQ8frac (int32_t a)
Return the fractional portion of an IQ8 input.
Parameters
a IQ8 type input.
Returns
IQ8 type fractional portion of input.
References __IQNfrac().
_IQ7frac()
int32_t _IQ7frac (int32_t a)
Return the fractional portion of an IQ7 input.
Parameters
a IQ7 type input.
Returns
IQ7 type fractional portion of input.
References __IQNfrac().
_IQ6frac()
int32_t _IQ6frac (int32_t a)
Return the fractional portion of an IQ6 input.
Parameters
a IQ6 type input.
Returns
IQ6 type fractional portion of input.
References __IQNfrac().
_IQ5frac()
int32_t _IQ5frac (int32_t a)
Return the fractional portion of an IQ5 input.
Parameters
a IQ5 type input.
Returns
IQ5 type fractional portion of input.
References __IQNfrac().
_IQ4frac()
int32_t _IQ4frac (int32_t a)
Return the fractional portion of an IQ4 input.
Parameters
a IQ4 type input.
Returns
IQ4 type fractional portion of input.
References __IQNfrac().
_IQ3frac()
int32_t _IQ3frac (int32_t a)
Return the fractional portion of an IQ3 input.
Parameters
a IQ3 type input.
Returns
IQ3 type fractional portion of input.
References __IQNfrac().
_IQ2frac()
int32_t _IQ2frac (int32_t a)
Return the fractional portion of an IQ2 input.
Parameters
a IQ2 type input.
Returns
IQ2 type fractional portion of input.
References __IQNfrac().
_IQ1frac()
int32_t _IQ1frac (int32_t a)
Return the fractional portion of an IQ1 input.
Parameters
a IQ1 type input.
Returns
IQ1 type fractional portion of input.
References __IQNfrac().
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale