IQMathLibrary: _atoIQN.c File Reference
_atoIQN.c File Reference
Detailed Description
Functions to convert a string to an IQN number.
#include <stdint.h>
#include "../support/support.h"
Functions
__STATIC_INLINE int_fast32_t __atoIQN (const char *string, int_fast32_t q_value)
Converts string to an IQN number.
int32_t _atoIQ31 (const char *string)
Converts string to IQ31 number.
int32_t _atoIQ30 (const char *string)
Converts string to IQ30 number.
int32_t _atoIQ29 (const char *string)
Converts string to IQ29 number.
int32_t _atoIQ28 (const char *string)
Converts string to IQ28 number.
int32_t _atoIQ27 (const char *string)
Converts string to IQ27 number.
int32_t _atoIQ26 (const char *string)
Converts string to IQ26 number.
int32_t _atoIQ25 (const char *string)
Converts string to IQ25 number.
int32_t _atoIQ24 (const char *string)
Converts string to IQ24 number.
int32_t _atoIQ23 (const char *string)
Converts string to IQ23 number.
int32_t _atoIQ22 (const char *string)
Converts string to IQ22 number.
int32_t _atoIQ21 (const char *string)
Converts string to IQ21 number.
int32_t _atoIQ20 (const char *string)
Converts string to IQ20 number.
int32_t _atoIQ19 (const char *string)
Converts string to IQ19 number.
int32_t _atoIQ18 (const char *string)
Converts string to IQ18 number.
int32_t _atoIQ17 (const char *string)
Converts string to IQ17 number.
int32_t _atoIQ16 (const char *string)
Converts string to IQ16 number.
int32_t _atoIQ15 (const char *string)
Converts string to IQ15 number.
int32_t _atoIQ14 (const char *string)
Converts string to IQ14 number.
int32_t _atoIQ13 (const char *string)
Converts string to IQ13 number.
int32_t _atoIQ12 (const char *string)
Converts string to IQ12 number.
int32_t _atoIQ11 (const char *string)
Converts string to IQ11 number.
int32_t _atoIQ10 (const char *string)
Converts string to IQ10 number.
int32_t _atoIQ9 (const char *string)
Converts string to IQ9 number.
int32_t _atoIQ8 (const char *string)
Converts string to IQ8 number.
int32_t _atoIQ7 (const char *string)
Converts string to IQ7 number.
int32_t _atoIQ6 (const char *string)
Converts string to IQ6 number.
int32_t _atoIQ5 (const char *string)
Converts string to IQ5 number.
int32_t _atoIQ4 (const char *string)
Converts string to IQ4 number.
int32_t _atoIQ3 (const char *string)
Converts string to IQ3 number.
int32_t _atoIQ2 (const char *string)
Converts string to IQ2 number.
int32_t _atoIQ1 (const char *string)
Converts string to IQ1 number.
Function Documentation
__atoIQN()
__STATIC_INLINE int_fast32_t __atoIQN (const char * string, int_fast32_t q_value)
Converts string to an IQN number.
Parameters
string Pointer to the string to be converted.
q_value IQ format.
Returns
Conversion of string to IQN type.
Referenced by _atoIQ1(), _atoIQ10(), _atoIQ11(), _atoIQ12(), _atoIQ13(), _atoIQ14(), _atoIQ15(), _atoIQ16(), _atoIQ17(), _atoIQ18(), _atoIQ19(), _atoIQ2(), _atoIQ20(), _atoIQ21(), _atoIQ22(), _atoIQ23(), _atoIQ24(), _atoIQ25(), _atoIQ26(), _atoIQ27(), _atoIQ28(), _atoIQ29(), _atoIQ3(), _atoIQ30(), _atoIQ31(), _atoIQ4(), _atoIQ5(), _atoIQ6(), _atoIQ7(), _atoIQ8(), and _atoIQ9().
_atoIQ31()
int32_t _atoIQ31 (const char * string)
Converts string to IQ31 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ31 type.
References __atoIQN().
_atoIQ30()
int32_t _atoIQ30 (const char * string)
Converts string to IQ30 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ30 type.
References __atoIQN().
_atoIQ29()
int32_t _atoIQ29 (const char * string)
Converts string to IQ29 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ29 type.
References __atoIQN().
_atoIQ28()
int32_t _atoIQ28 (const char * string)
Converts string to IQ28 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ28 type.
References __atoIQN().
_atoIQ27()
int32_t _atoIQ27 (const char * string)
Converts string to IQ27 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ27 type.
References __atoIQN().
_atoIQ26()
int32_t _atoIQ26 (const char * string)
Converts string to IQ26 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ26 type.
References __atoIQN().
_atoIQ25()
int32_t _atoIQ25 (const char * string)
Converts string to IQ25 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ25 type.
References __atoIQN().
_atoIQ24()
int32_t _atoIQ24 (const char * string)
Converts string to IQ24 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ24 type.
References __atoIQN().
_atoIQ23()
int32_t _atoIQ23 (const char * string)
Converts string to IQ23 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ23 type.
References __atoIQN().
_atoIQ22()
int32_t _atoIQ22 (const char * string)
Converts string to IQ22 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ22 type.
References __atoIQN().
_atoIQ21()
int32_t _atoIQ21 (const char * string)
Converts string to IQ21 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ21 type.
References __atoIQN().
_atoIQ20()
int32_t _atoIQ20 (const char * string)
Converts string to IQ20 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ20 type.
References __atoIQN().
_atoIQ19()
int32_t _atoIQ19 (const char * string)
Converts string to IQ19 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ19 type.
References __atoIQN().
_atoIQ18()
int32_t _atoIQ18 (const char * string)
Converts string to IQ18 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ18 type.
References __atoIQN().
_atoIQ17()
int32_t _atoIQ17 (const char * string)
Converts string to IQ17 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ17 type.
References __atoIQN().
_atoIQ16()
int32_t _atoIQ16 (const char * string)
Converts string to IQ16 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ16 type.
References __atoIQN().
_atoIQ15()
int32_t _atoIQ15 (const char * string)
Converts string to IQ15 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ15 type.
References __atoIQN().
_atoIQ14()
int32_t _atoIQ14 (const char * string)
Converts string to IQ14 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ14 type.
References __atoIQN().
_atoIQ13()
int32_t _atoIQ13 (const char * string)
Converts string to IQ13 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ13 type.
References __atoIQN().
_atoIQ12()
int32_t _atoIQ12 (const char * string)
Converts string to IQ12 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ12 type.
References __atoIQN().
_atoIQ11()
int32_t _atoIQ11 (const char * string)
Converts string to IQ11 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ11 type.
References __atoIQN().
_atoIQ10()
int32_t _atoIQ10 (const char * string)
Converts string to IQ10 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ10 type.
References __atoIQN().
_atoIQ9()
int32_t _atoIQ9 (const char * string)
Converts string to IQ9 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ9 type.
References __atoIQN().
_atoIQ8()
int32_t _atoIQ8 (const char * string)
Converts string to IQ8 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ8 type.
References __atoIQN().
_atoIQ7()
int32_t _atoIQ7 (const char * string)
Converts string to IQ7 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ7 type.
References __atoIQN().
_atoIQ6()
int32_t _atoIQ6 (const char * string)
Converts string to IQ6 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ6 type.
References __atoIQN().
_atoIQ5()
int32_t _atoIQ5 (const char * string)
Converts string to IQ5 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ5 type.
References __atoIQN().
_atoIQ4()
int32_t _atoIQ4 (const char * string)
Converts string to IQ4 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ4 type.
References __atoIQN().
_atoIQ3()
int32_t _atoIQ3 (const char * string)
Converts string to IQ3 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ3 type.
References __atoIQN().
_atoIQ2()
int32_t _atoIQ2 (const char * string)
Converts string to IQ2 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ2 type.
References __atoIQN().
_atoIQ1()
int32_t _atoIQ1 (const char * string)
Converts string to IQ1 number.
Parameters
string Pointer to the string to be converted.
Returns
Conversion of string to IQ1 type.
References __atoIQN().
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale