EnergyMetrology: TIDA-010243
TIDA-010243
Data Structures
struct TIDA_instance
Defines TIDA instance.
Macros
#define INITIAL_ZERO_CROSSINGS_TO_SKIP 10
Defines Number of cycles to skip initially.
Enumerations
enum EVENTS0 {
PHASE_ONE_ACTIVE_POWER_NEGATIVE = 0x00000001,
PHASE_TWO_ACTIVE_POWER_NEGATIVE = 0x00000002,
PHASE_THREE_ACTIVE_POWER_NEGATIVE = 0x00000004,
TOTAL_ACTIVE_POWER_NEGATIVE = 0x00000008,
PHASE_ONE_REACTIVE_POWER_NEGATIVE = 0x00000010,
PHASE_TWO_REACTIVE_POWER_NEGATIVE = 0x00000020,
PHASE_THREE_REACTIVE_POWER_NEGATIVE = 0x00000040,
TOTAL_REACTIVE_POWER_NEGATIVE = 0x00000080,
PHASE_ONE_CYCLE_COUNT_DONE = 0x00000100,
PHASE_TWO_CYCLE_COUNT_DONE = 0x00000200,
PHASE_THERE_CYCLE_COUNT_DONE = 0x00000400
}
enum EVENTS1 {
ZERO_CROSSING_PHASE_ONE = 0x00000001,
ZERO_CROSSING_PHASE_TWO = 0x00000002,
ZERO_CROSSING_PHASE_THREE = 0x00000004,
SAG_EVENT_PHASE_ONE = 0x00000008,
SAG_EVENT_PHASE_TWO = 0x00000010,
SAG_EVENT_PHASE_THREE = 0x00000020
}
Functions
void TIDA_calculateMetrologyParameters (TIDA_instance *tidaHandle, metrologyData *workingData, ADS_Instance *adsHandle, DLT645Buf *dlt645)
TIDA calculate metrology parameters.
void TIDA_init (TIDA_instance *tidaHandle, metrologyData *workingData, ADS_Instance *adsHandle)
TIDA initialization.
void debugInit (void)
Debug init initializes the lookup table.
Variables
ADS_Instance gADSHandle
Defines ADS instance.
metrologyData gMetrologyworkingData
Defines metrology working data.
DLT645Buf gDLT645
Defines DLT645 instance.
TIDA_instance gTidaHandle
Defines TIDA handle instance.
Detailed Description
Enumeration Type Documentation
EVENTS0
enum EVENTS0
Enumerator
PHASE_ONE_ACTIVE_POWER_NEGATIVE
Defines Phase 1 active power is negative.
PHASE_TWO_ACTIVE_POWER_NEGATIVE
Defines Phase 2 active power is negative.
PHASE_THREE_ACTIVE_POWER_NEGATIVE
Defines Phase 3 active power is negative.
TOTAL_ACTIVE_POWER_NEGATIVE
Defines total active power is negative.
PHASE_ONE_REACTIVE_POWER_NEGATIVE
Defines Phase 1 reactive power is negative.
PHASE_TWO_REACTIVE_POWER_NEGATIVE
Defines Phase 2 reactive power is negative.
PHASE_THREE_REACTIVE_POWER_NEGATIVE
Defines Phase 3 reactive power is negative.
TOTAL_REACTIVE_POWER_NEGATIVE
Defines total reactive power is negative.
PHASE_ONE_CYCLE_COUNT_DONE
Defines phase 1 cycle count is done.
PHASE_TWO_CYCLE_COUNT_DONE
Defines phase 2 cycle count is done.
PHASE_THERE_CYCLE_COUNT_DONE
Defines phase 3 cycle count is done.
EVENTS1
enum EVENTS1
Enumerator
ZERO_CROSSING_PHASE_ONE
Defines zero crossing is missed in phase 1.
ZERO_CROSSING_PHASE_TWO
Defines zero crossing is missed in phase 2.
ZERO_CROSSING_PHASE_THREE
Defines zero crossing is missed in phase 3.
SAG_EVENT_PHASE_ONE
Defines sag event occured in phase 1.
SAG_EVENT_PHASE_TWO
Defines sag event occured in phase 2.
SAG_EVENT_PHASE_THREE
Defines sag event occured in phase 3.
Function Documentation
TIDA_calculateMetrologyParameters()
void TIDA_calculateMetrologyParameters (TIDA_instance * tidaHandle, metrologyData * workingData, ADS_Instance * adsHandle, DLT645Buf * dlt645)
TIDA calculate metrology parameters.
Parameters
[in] tidaHandle The TIDA Instance
[in] workingData The Metrology Data
[in] adsHandle The ADS handle
[in] dlt645 The DLT645 buffer
References phaseReadings::activePower, phaseParams::cycleSkipCount, phaseMetrology::cycleStatus, DLT645_service(), INITIAL_ZERO_CROSSINGS_TO_SKIP, TIDA_instance::intr0Enable, TIDA_instance::intr0Status, MAX_PHASES, Metrology_calculatePhaseReadings(), Metrology_sagSwellDetection(), phaseMetrology::params, PHASE_ONE_ACTIVE_POWER_NEGATIVE, PHASE_ONE_CYCLE_COUNT_DONE, PHASE_ONE_REACTIVE_POWER_NEGATIVE, PHASE_STATUS_NEW_LOG, metrologyData::phases, phaseReadings::reactivePower, phaseMetrology::readings, SAG_EVENT_PHASE_ONE, phaseParams::sagSwellState, and phaseMetrology::status.
TIDA_init()
void TIDA_init (TIDA_instance * tidaHandle, metrologyData * workingData, ADS_Instance * adsHandle)
TIDA initialization.
Parameters
[in] tidaHandle The TIDA Instance
[in] workingData The Metrology Data
[in] adsHandle The ADS handle
References ACTIVE_ENERGY_SUPPORT, ACTIVE_POWER_SUPPORT, metrologyData::activePulse, ADS_CRC_ENABLE, ADS_CRC_TYPE_CCITT, APPARENT_ENERGY_SUPPORT, APPARENT_POWER_SUPPORT, ADS_Instance::crcEnable, ADS_Instance::crcType, CURRENT_THD_SUPPORT, CURRENT_VECTOR_SUM, FREQUENCY_SUPPORT, FUNDAMENTAL_ACTIVE_ENERGY_SUPPORT, FUNDAMENTAL_ACTIVE_POWER_SUPPORT, FUNDAMENTAL_APPARENT_ENERGY_SUPPORT, FUNDAMENTAL_APPARENT_POWER_SUPPORT, FUNDAMENTAL_IRMS_SUPPORT, FUNDAMENTAL_LINETOLINE_VOLTAGE_SUPPORT, FUNDAMENTAL_REACTIVE_ENERGY_SUPPORT, FUNDAMENTAL_REACTIVE_POWER_SUPPORT, FUNDAMENTAL_VRMS_SUPPORT, HAL_GPIO_IN_00, HAL_GPIO_OUT_00, HAL_GPIO_OUT_02, HAL_GPIO_OUT_03, HAL_SPI_CHAN_0, HAL_SPI_CS_0, TIDA_instance::intr0Enable, TIDA_instance::intr0Status, TIDA_instance::intr1Enable, TIDA_instance::intr1Status, IRMS_SUPPORT, LINETOLINE_VOLTAGE_SUPPORT, PHASE_ONE_ACTIVE_POWER_NEGATIVE, PHASE_ONE_CYCLE_COUNT_DONE, PHASE_ONE_REACTIVE_POWER_NEGATIVE, PHASE_THERE_CYCLE_COUNT_DONE, PHASE_THREE_ACTIVE_POWER_NEGATIVE, PHASE_THREE_REACTIVE_POWER_NEGATIVE, PHASE_TWO_ACTIVE_POWER_NEGATIVE, PHASE_TWO_CYCLE_COUNT_DONE, PHASE_TWO_REACTIVE_POWER_NEGATIVE, POWER_FACTOR_SUPPORT, REACTIVE_ENERGY_SUPPORT, REACTIVE_POWER_SUPPORT, metrologyData::reactivePulse, ADS_Instance::ready, SAG_EVENT_PHASE_ONE, SAG_EVENT_PHASE_THREE, SAG_EVENT_PHASE_TWO, ADS_Instance::spiChan, ADS_Instance::spiCs, metrologyData::supportedParams, ADS_Instance::sync, TOTAL_ACTIVE_POWER_NEGATIVE, TOTAL_ACTIVE_POWER_SUPPORT, TOTAL_APPARENT_POWER_SUPPORT, TOTAL_FUNDAMENTAL_ACTIVE_POWER_SUPPORT, TOTAL_FUNDAMENTAL_APPARENT_POWER_SUPPORT, TOTAL_FUNDAMENTAL_REACTIVE_POWER_SUPPORT, TOTAL_REACTIVE_POWER_NEGATIVE, TOTAL_REACTIVE_POWER_SUPPORT, VOLTAGE_OVER_DEVIATION, VOLTAGE_THD_SUPPORT, VOLTAGE_UNDER_DEVIATION, VRMS_SUPPORT, ZERO_CROSSING_PHASE_ONE, ZERO_CROSSING_PHASE_THREE, and ZERO_CROSSING_PHASE_TWO.
© Copyright 1995-2023, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale