MSPM0G3519SensoredFOCMotorControlLibrary: deadTimeCompute.h File Reference
deadTimeCompute.h File Reference
Detailed Description
Dead Time Computation Module.
Overview
Implements FOC state machine
#include "stdint.h"
#include "mcLib.h"
Data Structures
union DEAD_TIME_COMP_FLAGS_T
Dead Time Comp flags Structure.
struct DEAD_TIME_COMP_FLAGS_T::deadTimeCompFlags
Dead Time Comp.
struct DEAD_TIME_COMPUTE_T
Dead Time Comp Working Structure.
Macros
#define DEAD_TIME_COMP_MAX_FREQ_HZ 80.0
Dead Time COMP Freq Lim.
Functions
void deadTimeComputeReInit (DEAD_TIME_COMPUTE_T *)
Dead Time Compute Init.
void deadTimeComputeInit (DEAD_TIME_COMPUTE_T *)
Dead Time Compute Re Init.
void deadTimeComputeRun (DEAD_TIME_COMPUTE_T *)
Dead Time Compute Run.
void deadTimeComputeLowPriorityRun (DEAD_TIME_COMPUTE_T *)
Dead Time Compute Low Priority Run.
Variables
DEAD_TIME_COMPUTE_T deadTimeComp
Dead Time Comp Variable.
Function Documentation
deadTimeComputeReInit()
void deadTimeComputeReInit (DEAD_TIME_COMPUTE_T *)
Dead Time Compute Init.
Parameters
[in] * Input Pointer
Referenced by focLowPriorityRun().
deadTimeComputeInit()
void deadTimeComputeInit (DEAD_TIME_COMPUTE_T *)
Dead Time Compute Re Init.
Parameters
[in] * Input Pointer
deadTimeComputeRun()
void deadTimeComputeRun (DEAD_TIME_COMPUTE_T *)
Dead Time Compute Run.
Parameters
[in] * Input Pointer
Referenced by focRun().
deadTimeComputeLowPriorityRun()
void deadTimeComputeLowPriorityRun (DEAD_TIME_COMPUTE_T *)
Dead Time Compute Low Priority Run.
Parameters
[in] * Input Pointer
Referenced by focLowPriorityRun().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale