MSPM0G3519SensoredFOCMotorControlLibrary: fluxWeak.h File Reference
fluxWeak.h File Reference
Detailed Description
fluxWeak Module
Overview
#include "mcLib.h"
#include "motor.h"
#include "pi.h"
#include "main.h"
Data Structures
struct FLUX_WEAK_T
Flux Weakening Working Structure.
Functions
void fluxWeakInit (FLUX_WEAK_T *pFluxWeak)
Flux weakening Init.
void fluxWeakRun (FLUX_WEAK_T *pFluxWeak)
Flux weakening Run.
Function Documentation
fluxWeakInit()
void fluxWeakInit (FLUX_WEAK_T * pFluxWeak)
Flux weakening Init.
Parameters
[in] *pFluxWeak Input Pointer
References FLUX_WEAK_T::idRef, FLUX_WEAK_T::piFluxWeak, and piInit().
Referenced by idRefInit().
fluxWeakRun()
void fluxWeakRun (FLUX_WEAK_T * pFluxWeak)
Flux weakening Run.
Parameters
[in] *pFluxWeak Input Pointer
References FLUX_WEAK_T::idRef, PI_T::out, FLUX_WEAK_T::piFluxWeak, and piRun_LowPriority().
Referenced by idRefLowPriorityRun().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale