MSPM0G3519SensoredFOCMotorControlLibrary: hallEstimator.h File Reference
hallEstimator.h File Reference
Detailed Description
HallEstimator Module.
Overview
#include <ti/iqmath/include/IQmathLib.h>
#include "IQmath_mathacl.h"
#include "iqNum.h"
#include "motor.h"
#include "mcLib.h"
#include "measure.h"
Data Structures
struct HALL_ESTIMATOR_OBJ_T
Hall Estimator structure.
struct HALL_INVALID_STALL_DETECT_T
Hall Invalid Stall structure.
Macros
#define HALL_SPEED_FILTER_CONST _IQ(0.005)
Hall SPEED FILTER CONSTANT.
#define HALL_ANGLE_MASK 0x7FFFFFF
HALL angle mask to reset for 27 bits.
#define HALL_ANGLE_OVERFLOW_MASK 0xF8000000
Hall angle Overflow Mask for 27 bits.
Typedefs
typedef struct HALL_ESTIMATOR_OBJ_T HALL_ESTIMATOR_OBJ_T
Hall Estimator structure.
typedef struct HALL_INVALID_STALL_DETECT_T HALL_INVALID_STALL_DETECT_T
Hall Invalid Stall structure.
Enumerations
enum HALL_State_e {
HALL_IDLE = 0,
HALL_CALIBRATION = 1,
HALL_CALIBRATION_DONE = 2
}
Hall State Enumeration.
Functions
void hallAngleEstimRun (HALL_ESTIMATOR_OBJ_T *pHallHandle)
Hall Angle Estimator run.
int32_t hallForcedAngleRun (HALL_ESTIMATOR_OBJ_T *pHallHandle)
Hall Angle Forced open Loop run.
void hallAngleInit (HALL_ESTIMATOR_OBJ_T *pHallHandle)
Hall Angle Finit.
void hallSinCosEstim (MC_SINCOS_T *pFOCSinCos, HALL_ESTIMATOR_OBJ_T *pHallHandle)
Hall Angle Estim - Sine & Cosine.
bool hallInvalidStallDetectRun (uint16_t *pHallSector)
Invalid Hall Check.
Enumeration Type Documentation
HALL_State_e
enum HALL_State_e
Hall State Enumeration.
Enumerator
HALL_IDLE
State for Idle
HALL_CALIBRATION
State for Derived Hall Calibration
HALL_CALIBRATION_DONE
State for completed Hall Calibration
Function Documentation
hallAngleEstimRun()
void hallAngleEstimRun (HALL_ESTIMATOR_OBJ_T * pHallHandle)
Hall Angle Estimator run.
Parameters
[in] *pHallHandle Pointer
References _IQmpy_mathacl, FALSE, HALL_ESTIMATOR_OBJ_T::freqTs, getHallFrequency(), getHallPhaseError(), HALL_ANGLE_MASK, HALL_ANGLE_OVERFLOW_MASK, HALL_ESTIMATOR_OBJ_T::hallEstimFluxAngle, HALL_ESTIMATOR_OBJ_T::hallEstimSpeedFilt, HALL_ESTIMATOR_OBJ_T::hallEstimVelocity, HALL_ESTIMATOR_OBJ_T::hallEstimVelocityFilt, HALL_ESTIMATOR_OBJ_T::hallIndex, HALL_ESTIMATOR_OBJ_T::hallIndexNext, HALL_ESTIMATOR_OBJ_T::hallIndexPrev, HALL_ESTIMATOR_OBJ_T::hallNextIndexAngle, HALL_ESTIMATOR_OBJ_T::hallSectorChange, HALL_ESTIMATOR_OBJ_T::hallSectorCount, HALL_ESTIMATOR_OBJ_T::hallSpeedPWMCount, HALL_ESTIMATOR_OBJ_T::hallSpeedPWMRatio, HALL_ESTIMATOR_OBJ_T::pDeltaT, HALL_ESTIMATOR_OBJ_T::pHALLIntHandle, HALL_ESTIMATOR_OBJ_T::pTargetVelocity, HALL_ESTIMATOR_OBJ_T::pThetaHallIndexPU, ReadHallState(), and TRUE.
Referenced by focRun().
hallForcedAngleRun()
int32_t hallForcedAngleRun (HALL_ESTIMATOR_OBJ_T * pHallHandle)
Hall Angle Forced open Loop run.
Parameters
[in] *pHallHandle Pointer
Returns
Returns the Hall Flux angle
References HALL_ESTIMATOR_OBJ_T::hallIndex, and HALL_ESTIMATOR_OBJ_T::pThetaHallIndexPU.
Referenced by focRun().
hallAngleInit()
void hallAngleInit (HALL_ESTIMATOR_OBJ_T * pHallHandle)
Hall Angle Finit.
Parameters
[in] *pHallHandle Pointer
References HALL_ESTIMATOR_OBJ_T::gainEst, HALL_ESTIMATOR_OBJ_T::hallEstimFluxAngle, HALL_ESTIMATOR_OBJ_T::hallIndex, HALL_ESTIMATOR_OBJ_T::hallSectorCount, HALL_ESTIMATOR_OBJ_T::pHALLIntHandle, HALL_ESTIMATOR_OBJ_T::pThetaHallIndexPU, and ReadHallState().
Referenced by focRun().
hallSinCosEstim()
void hallSinCosEstim (MC_SINCOS_T * pFOCSinCos, HALL_ESTIMATOR_OBJ_T * pHallHandle)
Hall Angle Estim - Sine & Cosine.
Parameters
[in] *pFOCSinCos MC Sine Cos Pointer
[in] *pHallHandle Hall Input Pointer
References _IQmpy_mathacl, MC_SINCOS_T::cos, HALL_ESTIMATOR_OBJ_T::freqTs, HALL_ESTIMATOR_OBJ_T::gainEst, HALL_ESTIMATOR_OBJ_T::omegaTs, HALL_ESTIMATOR_OBJ_T::prevSinCos, MC_SINCOS_T::sin, HALL_ESTIMATOR_OBJ_T::sinCos, and HALL_ESTIMATOR_OBJ_T::sinErr.
Referenced by focRun().
hallInvalidStallDetectRun()
bool hallInvalidStallDetectRun (uint16_t * pHallSector)
Invalid Hall Check.
Parameters
[in] *pHallSector Pointer
Returns
Returns true if invalid Hall state is detected
Referenced by stallDetectRun().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale