MSPM0G3519SensoredFOCMotorControlLibrary: load.h File Reference
load.h File Reference
Detailed Description
load Module
Overview
#include "brake.h"
#include "stdint.h"
#include "softStop.h"
#include "measure.h"
#include "triState.h"
Data Structures
union LOAD_FLAGS_T
Load Flags Working Structure.
struct LOAD_FLAGS_T::loadFlags
Load Flags Struct.
struct LOAD_T
Load Working Structure.
Enumerations
enum LOAD_STATE_TYPES {
LOAD_INIT = 0,
LOAD_TRISTATE = 1,
LOAD_BRAKE = 2,
LOAD_START = 3,
LOAD_RUN = 4,
LOAD_STOP_INIT = 5,
LOAD_SOFT_STOP = 6,
LOAD_STOP = 7,
LOAD_FAULT = 8,
LOAD_ALIGN_STOP = 9
}
Load State Machine Values.
enum LOAD_FAULT_TYPES { LOAD_NO_FAULT = 0 }
Load Fault Values.
Functions
void loadInit (LOAD_T *pLoad)
Load Init.
void loadRun (LOAD_T *pLoad)
Load Run.
void loadLowPriorityRun (LOAD_T *pLoad)
Load Low Priority Run.
_Bool getLoadStartReadyStatus (LOAD_T *pLoad)
LoadStartReadyStatus Status check.
_Bool getLoadStopReadyStatus (LOAD_T *pLoad)
Load Stop Status check.
_Bool getLoadStallStatus (LOAD_T *pLoad)
Load Stall Status check.
_Bool runMotorDuringStop (LOAD_T *pLoad)
Motor Run Status check.
Enumeration Type Documentation
LOAD_STATE_TYPES
enum LOAD_STATE_TYPES
Load State Machine Values.
Enumerator
LOAD_INIT
Initialize load
LOAD_TRISTATE
Open all switches
LOAD_BRAKE
Brake the motor
LOAD_START
Start the load
LOAD_RUN
Running of load
LOAD_STOP_INIT
Stop Initialization
LOAD_SOFT_STOP
Soft stop the load
LOAD_STOP
Load stopped
LOAD_FAULT
Load Fault
LOAD_ALIGN_STOP
Align Stop
LOAD_FAULT_TYPES
enum LOAD_FAULT_TYPES
Load Fault Values.
Enumerator
LOAD_NO_FAULT
No fault on load
Function Documentation
loadInit()
void loadInit (LOAD_T * pLoad)
Load Init.
Parameters
[in] *pLoad Input Pointer
References LOAD_FLAGS_T::b, BRAKE_FLAGS_T::b, LOAD_T::brake, brakeInit(), BRAKE_FLAGS_T::brakeFlags::enableOnStop, FALSE, BRAKE_T::flags, LOAD_T::flags, LOAD_FLAGS_T::loadFlags::loadStartReadyStatus, LOAD_FLAGS_T::loadFlags::loadStopReadyStatus, SOFT_STOP_T::minimumSpeed, SOFT_STOP_T::minimumSpeedBrake, SOFT_STOP_T::minimumSpeedSoftStop, LOAD_T::softStop, softStopInit(), LOAD_T::triState, and triStateInit().
Referenced by loadRun().
loadRun()
void loadRun (LOAD_T * pLoad)
Load Run.
Parameters
[in] *pLoad Input Pointer
References SOFT_STOP_FLAGS_T::b, LOAD_FLAGS_T::b, BRAKE_FLAGS_T::b, MEASURE_CURRENT_FLAGS_T::b, LOAD_T::brake, BRAKE_FLAGS_T::brakeFlags::brakeCheckCurrentFault, BRAKE_FLAGS_T::brakeFlags::brakeCheckCurrentStart, BRAKE_FLAGS_T::brakeFlags::brakeCheckCurrentStop, BRAKE_FLAGS_T::brakeFlags::brakeCheckOnCurrent, brakeInit(), BRAKE_FLAGS_T::brakeFlags::brakeOnStart, brakeRun(), HAL_MEASURE_MOTOR_INPUTS_T::current, HAL_MEASURE_CURRENT_T::currentShunt, SOFT_STOP_FLAGS_T::softStopFlags::enable, SOFT_STOP_FLAGS_T::softStopFlags::enableOnBrake, BRAKE_FLAGS_T::brakeFlags::enableOnFault, BRAKE_FLAGS_T::brakeFlags::enableOnStart, BRAKE_FLAGS_T::brakeFlags::enableOnStop, FALSE, SOFT_STOP_T::flags, BRAKE_T::flags, LOAD_T::flags, HAL_MEASURE_CURRENT_T::flags, getBrakeStatusCurrent(), getBrakeStatusTimeOut(), getSoftStopStatus(), getTriStateStatus(), HAL_EnableLowSideBrake(), HAL_SetPhaseCurrentChannels(), LOAD_BRAKE, LOAD_FAULT, LOAD_INIT, LOAD_RUN, LOAD_SOFT_STOP, LOAD_START, LOAD_STOP, LOAD_STOP_INIT, LOAD_TRISTATE, loadInit(), LOAD_FLAGS_T::loadFlags::loadStartReadyStatus, LOAD_FLAGS_T::loadFlags::loadStopReadyStatus, LOAD_T::pMotorInputs, LOAD_T::softStop, softStopRun(), LOAD_T::state, measureCurrentFlags::threeShuntDynamic, BRAKE_T::timeOutCountMax, BRAKE_T::timeOutCountMaxOnStart, BRAKE_T::timeOutCountMaxOnStop, LOAD_T::triState, and TRUE.
loadLowPriorityRun()
void loadLowPriorityRun (LOAD_T * pLoad)
Load Low Priority Run.
Parameters
[in] *pLoad Input Pointer
References LOAD_T::brake, brakeLowPriorityRun(), LOAD_BRAKE, LOAD_TRISTATE, LOAD_T::state, LOAD_T::triState, and triStateRun().
getLoadStartReadyStatus()
_Bool getLoadStartReadyStatus (LOAD_T * pLoad) inline
LoadStartReadyStatus Status check.
Parameters
[in] *pLoad Pointer
Returns
Returns the status
References LOAD_FLAGS_T::b, LOAD_T::flags, and LOAD_FLAGS_T::loadFlags::loadStartReadyStatus.
getLoadStopReadyStatus()
_Bool getLoadStopReadyStatus (LOAD_T * pLoad) inline
Load Stop Status check.
Parameters
[in] *pLoad Pointer
Returns
Returns the status
References LOAD_FLAGS_T::b, LOAD_T::flags, and LOAD_FLAGS_T::loadFlags::loadStopReadyStatus.
getLoadStallStatus()
_Bool getLoadStallStatus (LOAD_T * pLoad) inline
Load Stall Status check.
Parameters
[in] *pLoad Pointer
Returns
Returns the status
References LOAD_T::faultStatus, and LOAD_NO_FAULT.
runMotorDuringStop()
_Bool runMotorDuringStop (LOAD_T * pLoad) inline
Motor Run Status check.
Parameters
[in] *pLoad Pointer
Returns
Returns the status
References LOAD_ALIGN_STOP, LOAD_SOFT_STOP, LOAD_STOP_INIT, and LOAD_T::state.
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale