MSPM0G3519SensoredFOCMotorControlLibrary: mtpa.h File Reference
mtpa.h File Reference
Detailed Description
mtpa Module
Overview
#include "stdint.h"
#include "iqNum.h"
#include "main.h"
Data Structures
struct MTPA_T
MTPA Working Structure.
Functions
void mtpaInit (MTPA_T *pMtpa)
MTPA Init.
void mtpaRun (MTPA_T *pMtpa)
MTPA Run.
Function Documentation
mtpaInit()
void mtpaInit (MTPA_T * pMtpa)
MTPA Init.
Parameters
[in] *pMtpa Input Pointer
References MTPA_T::idRefFilt.
Referenced by idRefInit().
mtpaRun()
void mtpaRun (MTPA_T * pMtpa)
MTPA Run.
Parameters
[in] *pMtpa Input Pointer
References filter(), GLOBAL_IQ, MTPA_T::idFiltConst, MTPA_T::idRef, MTPA_T::idRefFilt, IQ_NUM_T::iqScaling, MTPA_T::L1, MTPA_T::pidRefMin, MTPA_T::pInvKe, MTPA_T::pInvKeScaling, MTPA_T::pIq, and IQ_NUM_T::scaledNum.
Referenced by idRefLowPriorityRun().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale