MSPM0G3519SensoredFOCMotorControlLibrary: noMotorStallDetect.h File Reference
noMotorStallDetect.h File Reference
Detailed Description
noMotorStallDetect Module
Overview
#include "stdint.h"
#include "mcLib.h"
Data Structures
union NO_MOTOR_STALL_DETECT_FLAGS_T
No Motor Stall Working Structure.
struct NO_MOTOR_STALL_DETECT_FLAGS_T::noMotorStallDetectFlags
No Motor Stall Flags Struct.
struct NO_MOTOR_STALL_DETECT_T
No Motor Detect Working Structure.
Functions
void noMotorStallDetectInit (NO_MOTOR_STALL_DETECT_T *pNoMotorStall)
No Motor Stall Init.
void noMotorStallDetectRun (NO_MOTOR_STALL_DETECT_T *pNoMotorStall)
No Motor Stall Run.
_Bool getNoMotorStallDetectStatus (NO_MOTOR_STALL_DETECT_T *pNoMotorStall)
No Motor Stall Status check.
Function Documentation
noMotorStallDetectInit()
void noMotorStallDetectInit (NO_MOTOR_STALL_DETECT_T * pNoMotorStall)
No Motor Stall Init.
Parameters
[in] *pNoMotorStall Input Pointer
References NO_MOTOR_STALL_DETECT_FLAGS_T::b, NO_MOTOR_STALL_DETECT_T::countA, NO_MOTOR_STALL_DETECT_T::countB, NO_MOTOR_STALL_DETECT_T::countC, NO_MOTOR_STALL_DETECT_FLAGS_T::noMotorStallDetectFlags::enable, FALSE, and NO_MOTOR_STALL_DETECT_T::flags.
Referenced by stallDetectInit().
noMotorStallDetectRun()
void noMotorStallDetectRun (NO_MOTOR_STALL_DETECT_T * pNoMotorStall)
No Motor Stall Run.
Parameters
[in] *pNoMotorStall Input Pointer
References MC_ABC_T::a, NO_MOTOR_STALL_DETECT_FLAGS_T::b, MC_ABC_T::b, MC_ABC_T::c, NO_MOTOR_STALL_DETECT_T::countA, NO_MOTOR_STALL_DETECT_T::countB, NO_MOTOR_STALL_DETECT_T::countC, NO_MOTOR_STALL_DETECT_T::countMax, FALSE, NO_MOTOR_STALL_DETECT_T::flags, NO_MOTOR_STALL_DETECT_T::minimumCurrent, NO_MOTOR_STALL_DETECT_FLAGS_T::noMotorStallDetectFlags::phaseADisconnect, NO_MOTOR_STALL_DETECT_FLAGS_T::noMotorStallDetectFlags::phaseBDisconnect, NO_MOTOR_STALL_DETECT_FLAGS_T::noMotorStallDetectFlags::phaseCDisconnect, NO_MOTOR_STALL_DETECT_T::pIabc, NO_MOTOR_STALL_DETECT_FLAGS_T::noMotorStallDetectFlags::status, and TRUE.
Referenced by stallDetectRun().
getNoMotorStallDetectStatus()
_Bool getNoMotorStallDetectStatus (NO_MOTOR_STALL_DETECT_T * pNoMotorStall) inline
No Motor Stall Status check.
Parameters
[in] *pNoMotorStall Pointer
Returns
Returns the status
References NO_MOTOR_STALL_DETECT_FLAGS_T::b, NO_MOTOR_STALL_DETECT_T::flags, and NO_MOTOR_STALL_DETECT_FLAGS_T::noMotorStallDetectFlags::status.
Referenced by stallDetectRun().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale