MSPM0G3519SensoredFOCMotorControlLibrary: pi.h File Reference
pi.h File Reference
Detailed Description
pi Module
Overview
#include "stdint.h"
#include <ti/iqmath/include/IQmathLib.h>
#include "IQmath_mathacl.h"
#include "iqNum.h"
Data Structures
union PI_FLAGS_T
PI Flags Working Structure.
struct PI_FLAGS_T::piFlags
PI flags Structure.
struct PI_T
PI Working Structure.
Macros
#define KP_IQ_SCALING 24
KP IQ Scaling.
#define KP_TERM_SAT (((int32_t)1) << (30 - GLOBAL_IQ + KP_IQ_SCALING))
KP Term Saturation Lim.
Functions
void piInit (PI_T *pPI)
PI Init.
void piRun (PI_T *pPI)
PI Run.
void piRun_LowPriority (PI_T *pPI)
PI Low Priority Run.
Function Documentation
piInit()
void piInit (PI_T * pPI)
PI Init.
Parameters
[in] *pPI Input Pointer
References PI_FLAGS_T::b, PI_FLAGS_T::piFlags::externalSaturation, FALSE, PI_T::flags, PI_T::kiTerm, PI_T::out, and PI_FLAGS_T::piFlags::saturation.
Referenced by closeLoopInit(), fluxWeakInit(), and focInit().
piRun()
void piRun (PI_T * pPI)
PI Run.
Parameters
[in] *pPI Input Pointer
References _IQmpy_mathacl, PI_FLAGS_T::b, PI_FLAGS_T::piFlags::externalSaturation, FALSE, PI_T::flags, GLOBAL_IQ, PI_T::ki, PI_T::kiTerm, PI_T::kp, KP_IQ_SCALING, KP_TERM_SAT, PI_T::out, PI_T::outMax, PI_T::outMin, PI_T::pFeedback, PI_T::pReference, PI_FLAGS_T::piFlags::saturation, and TRUE.
Referenced by closeLoopRun(), and focRun().
piRun_LowPriority()
void piRun_LowPriority (PI_T * pPI)
PI Low Priority Run.
Parameters
[in] *pPI Input Pointer
References PI_FLAGS_T::b, PI_FLAGS_T::piFlags::externalSaturation, FALSE, PI_T::flags, GLOBAL_IQ, PI_T::ki, PI_T::kiTerm, PI_T::kp, KP_IQ_SCALING, KP_TERM_SAT, PI_T::out, PI_T::outMax, PI_T::outMin, PI_T::pFeedback, PI_T::pReference, PI_FLAGS_T::piFlags::saturation, and TRUE.
Referenced by fluxWeakRun().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale