MSPM0G3519SensoredFOCMotorControlLibrary: sourceLimits.h File Reference
sourceLimits.h File Reference
Detailed Description
sourceLimits Module
Overview
#include "sourceCurrentEstim.h"
#include "sourceCurrentLimit.h"
#include "sourceVoltageLimit.h"
#include "overCurrent.h"
Data Structures
struct SOURCE_LIMITS_T
Source Limit Structure Values.
Functions
void sourceLimitsInit (SOURCE_LIMITS_T *pSourceLimits)
source Limits Init
void sourceLimitsRun (SOURCE_LIMITS_T *pSourceLimits)
source Limits Run
Function Documentation
sourceLimitsInit()
void sourceLimitsInit (SOURCE_LIMITS_T * pSourceLimits)
source Limits Init
Parameters
[in] *pSourceLimits Input Pointer
References SOURCE_LIMITS_T::overCurrent, overCurrentInit(), SOURCE_LIMITS_T::sourceCurrentEstim, sourceCurrentEstimInit(), SOURCE_LIMITS_T::sourceCurrentLimit, sourceCurrentLimitInit(), SOURCE_LIMITS_T::sourceVoltageLimit, and sourceVoltageLimitInit().
sourceLimitsRun()
void sourceLimitsRun (SOURCE_LIMITS_T * pSourceLimits)
source Limits Run
Parameters
[in] *pSourceLimits Input Pointer
References SOURCE_LIMITS_T::sourceCurrentEstim, sourceCurrentEstimRun(), SOURCE_LIMITS_T::sourceCurrentLimit, sourceCurrentLimitRun(), SOURCE_LIMITS_T::sourceVoltageLimit, and sourceVoltageLimitRun().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale