MSPM0G3519SensoredFOCMotorControlLibrary: stallDetect.h File Reference
stallDetect.h File Reference
Detailed Description
stallDetect Module
Overview
#include "iqNum.h"
#include "stdint.h"
#include "mcLib.h"
#include "noMotorStallDetect.h"
#include "hallEstimator.h"
#include "abnormalSpeedStallDetect.h"
Data Structures
struct STALL_DETECT_T
Stall Working Structure.
Enumerations
enum STALL_TYPES {
NO_STALL = 0,
HALL_INVALID_STALL = 1,
NO_MOTOR_STALL = 2,
ABNORMAL_SPEED_STALL = 3
}
Stall Type Enums.
Functions
void stallDetectInit (STALL_DETECT_T *pStall)
Stall Detect Init.
void stallDetectRun (STALL_DETECT_T *pStall)
Stall Detect Run.
void stallDetectLowPriorityRun (STALL_DETECT_T *pStall)
Stall Detect Low Priority.
_Bool getStallStatusForAction (STALL_DETECT_T *pStall)
Stall Status check.
_Bool getStallStatusForReport (STALL_DETECT_T *pStall)
Stall Report Status check.
Enumeration Type Documentation
STALL_TYPES
enum STALL_TYPES
Stall Type Enums.
Enumerator
NO_STALL
Motor is not stalled
HALL_INVALID_STALL
HALL Sensor Invalid stall detected
NO_MOTOR_STALL
No motor stall detected
ABNORMAL_SPEED_STALL
Abnormal speed stall detected
Function Documentation
stallDetectInit()
void stallDetectInit (STALL_DETECT_T * pStall)
Stall Detect Init.
Parameters
[in] *pStall Input Pointer
References STALL_DETECT_T::abnormalSpeedStall, abnormalSpeedStallDetectInit(), STALL_DETECT_T::noMotorStall, and noMotorStallDetectInit().
Referenced by focInit().
stallDetectRun()
void stallDetectRun (STALL_DETECT_T * pStall)
Stall Detect Run.
Parameters
[in] *pStall Input Pointer
References NO_MOTOR_STALL_DETECT_FLAGS_T::b, NO_MOTOR_STALL_DETECT_FLAGS_T::noMotorStallDetectFlags::enable, NO_MOTOR_STALL_DETECT_T::flags, getNoMotorStallDetectStatus(), HALL_INVALID_STALL, STALL_DETECT_T::hallInvalidStall, hallInvalidStallDetectRun(), NO_MOTOR_STALL, STALL_DETECT_T::noMotorStall, noMotorStallDetectRun(), HALL_INVALID_STALL_DETECT_T::pHallIndex, HALL_INVALID_STALL_DETECT_T::stallDetectEn, and STALL_DETECT_T::status.
Referenced by focRun().
stallDetectLowPriorityRun()
void stallDetectLowPriorityRun (STALL_DETECT_T * pStall)
Stall Detect Low Priority.
Parameters
[in] *pStall Input Pointer
References ABNORMAL_SPEED_STALL, STALL_DETECT_T::abnormalSpeedStall, abnormalSpeedStallDetectRun(), ABNORMAL_SPEED_STALL_DETECT_FLAGS_T::b, ABNORMAL_SPEED_STALL_DETECT_FLAGS_T::abnormalSpeedStallDetectFlags::enable, ABNORMAL_SPEED_STALL_DETECT_T::flags, getAbnormalSpeedStallDetectStatus(), and STALL_DETECT_T::status.
Referenced by focLowPriorityRun().
getStallStatusForAction()
_Bool getStallStatusForAction (STALL_DETECT_T * pStall) inline
Stall Status check.
Parameters
[in] *pStall Pointer
Returns
Returns the status
References STALL_DETECT_T::abnormalSpeedStall, ABNORMAL_SPEED_STALL_DETECT_FLAGS_T::b, NO_MOTOR_STALL_DETECT_FLAGS_T::b, ABNORMAL_SPEED_STALL_DETECT_T::flags, NO_MOTOR_STALL_DETECT_T::flags, HALL_INVALID_STALL, STALL_DETECT_T::noMotorStall, ABNORMAL_SPEED_STALL_DETECT_FLAGS_T::abnormalSpeedStallDetectFlags::reportOnly, NO_MOTOR_STALL_DETECT_FLAGS_T::noMotorStallDetectFlags::reportOnly, ABNORMAL_SPEED_STALL_DETECT_FLAGS_T::abnormalSpeedStallDetectFlags::status, NO_MOTOR_STALL_DETECT_FLAGS_T::noMotorStallDetectFlags::status, and STALL_DETECT_T::status.
Referenced by focRun().
getStallStatusForReport()
_Bool getStallStatusForReport (STALL_DETECT_T * pStall) inline
Stall Report Status check.
Parameters
[in] *pStall Pointer
Returns
Returns the status
References NO_STALL, and STALL_DETECT_T::status.
Referenced by focLowPriorityRun().
© Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale