MSPM0Lxx2xEnergyMetrology: AMC131M0x
AMC131M0x
Data Structures
struct AMC_channelData
Defines AMC Channel data.
struct AMC_Errors
Structure to store the amc error counts.
struct AMC_Instance
AMC_Instance.
Macros
#define AMC131M02_CLOCK_ADDRESS_DATA CLOCK_CH1_EN_ENABLED | CLOCK_CH0_EN_ENABLED | CLOCK_XTAL_DIS_ENABLED | CLOCK_EXTREF_EN_DISABLED | CLOCK_OSR_512 | CLOCK_PWR_HR
Default clock address data.
#define AMC131M02_MODE_ADDRESS_DATA MODE_REG_CRC_EN_DISABLED | MODE_RX_CRC_EN_DISABLED | MODE_CRC_TYPE_16BIT_CCITT | MODE_RESET_NO_RESET | MODE_WLENGTH_24BIT | MODE_TIMEOUT_ENABLED | MODE_DRDY_SEL_MOST_LAGGING | MODE_DRDY_HiZ_LOGIC_HIGH | MODE_DRDY_FMT_LOGIC_LOW
Default mode address data.
#define AMC131M02_GAIN1_ADDRESS_DATA GAIN1_PGAGAIN1_1 | GAIN1_PGAGAIN0_1
Default gain1 address data.
#define AMC131M02_CFG_ADDRESS_DATA CFG_GC_DLY_16 | CFG_GC_EN_DISABLED | CFG_CD_ALLCH_ANY_CHANNEL | CFG_CD_NUM_1 | CFG_CD_LEN_128 | CFG_CD_EN_DISABLED
Default CFG address data.
#define AMC131M02_THRSHLD_MSB_ADDRESS_DATA THRSHLD_MSB_DEFAULT
Default THRSHLD MSB address data.
#define AMC131M02_THRSHLD_LSB_ADDRESS_DATA THRSHLD_LSB_DCBLOCK_DISABLED
Default THRSHLD LSB address data.
#define AMC131M02_CH0_CFG_ADDRESS_DATA CH0_CFG_DEFAULT
Default CH0_CFG address data.
#define AMC131M02_CH0_OCAL_MSB_ADDRESS_DATA CH0_OCAL_MSB_DEFAULT
Default CH0 OCAL_MSB address data.
#define AMC131M02_CH0_OCAL_LSB_ADDRESS_DATA CH0_OCAL_LSB_DEFAULT
Default CH0 OCAL_LSB address data.
#define AMC131M02_CH0_GCAL_MSB_ADDRESS_DATA CH0_GCAL_MSB_DEFAULT
Default CH0 GCAL_MSB address data.
#define AMC131M02_CH0_GCAL_LSB_ADDRESS_DATA CH0_GCAL_LSB_DEFAULT
Default CH0 GCAL_LSB address data.
#define AMC131M02_CH1_CFG_ADDRESS_DATA CH1_CFG_DEFAULT
Default CH1_CFG address data.
#define AMC131M02_CH1_OCAL_MSB_ADDRESS_DATA CH1_OCAL_MSB_DEFAULT
Default CH1 OCAL_MSB address data.
#define AMC131M02_CH1_OCAL_LSB_ADDRESS_DATA CH1_OCAL_LSB_DEFAULT
Default CH1 OCAL_LSB address data.
#define AMC131M02_CH1_GCAL_MSB_ADDRESS_DATA CH1_GCAL_MSB_DEFAULT
Default CH1 GCAL_MSB address data.
#define AMC131M02_CH1_GCAL_LSB_ADDRESS_DATA CH1_GCAL_LSB_DEFAULT
Default CH1 GCAL_LSB address data.
#define AMC131M02_DCD_CTRL_REGISTER REGMAP_DCDC_DEFAULT | FREQ_0 | STATUS_DCDC_EN
Default DCD_CTRL_register data.
#define AMC131M03_CLOCK_ADDRESS_DATA CLOCK_CH2_EN_DISABLED | CLOCK_CH1_EN_ENABLED | CLOCK_CH0_EN_ENABLED | CLOCK_XTAL_DIS_ENABLED | CLOCK_EXTREF_EN_DISABLED | CLOCK_OSR_512 | CLOCK_PWR_HR
Default clock address data.
#define AMC131M03_MODE_ADDRESS_DATA MODE_REG_CRC_EN_DISABLED | MODE_RX_CRC_EN_DISABLED | MODE_CRC_TYPE_16BIT_CCITT | MODE_RESET_NO_RESET | MODE_WLENGTH_24BIT | MODE_TIMEOUT_ENABLED | MODE_DRDY_SEL_MOST_LAGGING | MODE_DRDY_HiZ_LOGIC_HIGH | MODE_DRDY_FMT_LOGIC_LOW
Default mode address data.
#define AMC131M03_GAIN1_ADDRESS_DATA GAIN1_PGAGAIN3_1 | GAIN1_PGAGAIN2_1 | GAIN1_PGAGAIN1_1 | GAIN1_PGAGAIN0_1
Default gain1 address data.
#define AMC131M03_CFG_ADDRESS_DATA CFG_GC_DLY_16 | CFG_GC_EN_DISABLED | CFG_CD_ALLCH_ANY_CHANNEL | CFG_CD_NUM_1 | CFG_CD_LEN_128 | CFG_CD_EN_DISABLED
Default CFG address data.
#define AMC131M03_THRSHLD_MSB_ADDRESS_DATA THRSHLD_MSB_DEFAULT
Default THRSHLD MSB address data.
#define AMC131M03_THRSHLD_LSB_ADDRESS_DATA THRSHLD_LSB_DCBLOCK_DISABLED
Default THRSHLD LSB address data.
#define AMC131M03_CH0_CFG_ADDRESS_DATA CH0_CFG_DEFAULT
Default CH0_CFG address data.
#define AMC131M03_CH0_OCAL_MSB_ADDRESS_DATA CH0_OCAL_MSB_DEFAULT
Default CH0 OCAL_MSB address data.
#define AMC131M03_CH0_OCAL_LSB_ADDRESS_DATA CH0_OCAL_LSB_DEFAULT
Default CH0 OCAL_LSB address data.
#define AMC131M03_CH0_GCAL_MSB_ADDRESS_DATA CH0_GCAL_MSB_DEFAULT
Default CH0 GCAL_MSB address data.
#define AMC131M03_CH0_GCAL_LSB_ADDRESS_DATA CH0_GCAL_LSB_DEFAULT
Default CH0 GCAL_LSB address data.
#define AMC131M03_CH1_CFG_ADDRESS_DATA CH1_CFG_DEFAULT
Default CH1_CFG address data.
#define AMC131M03_CH1_OCAL_MSB_ADDRESS_DATA CH1_OCAL_MSB_DEFAULT
Default CH1 OCAL_MSB address data.
#define AMC131M03_CH1_OCAL_LSB_ADDRESS_DATA CH1_OCAL_LSB_DEFAULT
Default CH1 OCAL_LSB address data.
#define AMC131M03_CH1_GCAL_MSB_ADDRESS_DATA CH1_GCAL_MSB_DEFAULT
Default CH1 GCAL_MSB address data.
#define AMC131M03_CH1_GCAL_LSB_ADDRESS_DATA CH1_GCAL_LSB_DEFAULT
Default CH1 GCAL_LSB address data.
#define AMC131M03_CH2_CFG_ADDRESS_DATA CH2_CFG_DEFAULT
Default CH2_CFG address data.
#define AMC131M03_CH2_OCAL_MSB_ADDRESS_DATA CH2_OCAL_MSB_DEFAULT
Default CH2 OCAL_MSB address data.
#define AMC131M03_CH2_OCAL_LSB_ADDRESS_DATA CH2_OCAL_LSB_DEFAULT
Default CH2 OCAL_LSB address data.
#define AMC131M03_CH2_GCAL_MSB_ADDRESS_DATA CH2_GCAL_MSB_DEFAULT
Default CH2 GCAL_MSB address data.
#define AMC131M03_CH2_GCAL_LSB_ADDRESS_DATA CH2_GCAL_LSB_DEFAULT
Default CH2 GCAL_LSB address data.
#define AMC131M03_DCD_CTRL_REGISTER REGMAP_DCDC_DEFAULT | FREQ_0 | STATUS_DCDC_EN
Default DCD_CTRL_register data.
#define AMC_CHANNELCOUNT (8)
AMC channel count.
#define AMC_DMA_TRANSFER_DONE 0x01
AMC DMA Transfer Done.
#define AMC_DMA_TRANSFER_READY 0x00
AMC DMA Ready to transfer.
#define AMC_DMA_WAITING 0x01
AMC DMA waiting for dma interrupt.
#define AMC_DMA_IDLE 0x00
AMC DMA is in idle state.
#define AMC_REG_WORD_LENGTH_16BIT (2)
AMC register word length 16 bit.
#define AMC_REG_WORD_LENGTH_24BIT (3)
AMC register word length 24 bit.
#define AMC_REG_WORD_LENGTH_32BIT_SIGN_EXTEND (4)
AMC register word length 32 bit sign extended.
#define AMC_REG_WORD_LENGTH_32BIT_ZERO_PADDED (4)
AMC register word length 16 bit zero padded.
#define AMC_CMDLENGTH (1)
AMC command word length.
#define AMC_CRCLENGTH (1)
AMC CRC word length.
#define AMC_WORDLENGTH AMC_REG_WORD_LENGTH_24BIT
AMC data word length.
#define NUM_REGISTERS (64)
AMC number of registers.
#define AMC_BYTELENGTH ((AMC_CMDLENGTH + AMC_CRCLENGTH + AMC_CHANNELCOUNT) * AMC_WORDLENGTH)
AMC byte length.
#define AMC_CRC_INITAL_VALUE (0xFFFF)
AMC CRC initial value.
#define AMC_UPPER_BYTE_MASK (0xFF00)
upper byte mask for uint16_t
#define AMC_LOWER_BYTE_MASK (0x00FF)
lower byte mask for uint16_t
#define AMC_RESET_US (300)
AMC reset time.
#define AMC_WAKEUP_US (35)
AMC wakeup time.
#define AMC_SYNC_US (1)
AMC sync pulse time.
#define ID_ADDRESS ((uint8_t) 0x00)
Defines ID register address.
#define AMC_ID_DEFAULT ((uint16_t) 0x2000 | (AMC_CHANNELCOUNT << 8))
Defines ID register defaults.
#define ID_RESERVED_MASK ((uint16_t) 0xF000)
Defines ID register reserved mask.
#define ID_CHANCNT_MASK ((uint16_t) 0x0F00)
Defines ID register channel count mask.
#define ID_CHANCNT_4CH ((uint16_t) 0x0004 << 8)
Defines ID register channel count 4.
#define ID_CHANCNT_6CH ((uint16_t) 0x0006 << 8)
Defines ID register channel count 6.
#define ID_CHANCNT_8CH ((uint16_t) 0x0008 << 8)
Defines ID register channel count 8.
#define ID_REVID_MASK ((uint16_t) 0x00FF)
Defines ID register reserved mask.
#define ID_REVID_REVA ((uint16_t) 0x0000 << 0) /* DEFAULT */
Defines ID register reserved default.
#define STATUS_ADDRESS ((uint8_t) 0x01)
Defines status register address.
#define STATUS_DEFAULT ((uint16_t) 0x0500)
Defines status register default value.
#define STATUS_LOCK_MASK ((uint16_t) 0x8000)
Defines status register lock mask.
#define STATUS_LOCK_UNLOCKED ((uint16_t) 0x0000 << 15) /* DEFAULT */
Defines status register unlocked.
#define STATUS_LOCK_LOCKED ((uint16_t) 0x0001 << 15)
Defines status register locked.
#define STATUS_F_RESYNC_MASK ((uint16_t) 0x4000)
Defines status register resync mask.
#define STATUS_F_RESYNC_NO_FAULT ((uint16_t) 0x0000 << 14) /* DEFAULT */
Defines status register resync no fault.
#define STATUS_F_RESYNC_FAULT ((uint16_t) 0x0001 << 14)
Defines status register resync fault.
#define STATUS_REG_MAP_MASK ((uint16_t) 0x2000)
Defines status register reg map mask.
#define STATUS_REG_MAP_NO_CHANGE_CRC ((uint16_t) 0x0000 << 13) /* DEFAULT */
Defines status register reg map no CRC change.
#define STATUS_REG_MAP_CHANGED_CRC ((uint16_t) 0x0001 << 13)
Defines status register reg map CRC change.
#define STATUS_CRC_ERR_MASK ((uint16_t) 0x1000)
Defines status register CRC error mask.
#define STATUS_CRC_ERR_NO_CRC_ERROR ((uint16_t) 0x0000 << 12) /* DEFAULT */
Defines status register no CRC error.
#define STATUS_CRC_ERR_INPUT_CRC_ERROR ((uint16_t) 0x0001 << 12)
Defines status register CRC error.
#define STATUS_CRC_TYPE_MASK ((uint16_t) 0x0800)
Defines status register CRC type mask.
#define STATUS_CRC_TYPE_16BIT_CCITT ((uint16_t) 0x0000 << 11) /* DEFAULT */
Defines status register CRC type 16 bit CCITT.
#define STATUS_CRC_TYPE_16BIT_ANSI ((uint16_t) 0x0001 << 11)
Defines status register CRC type 16 bit ANSI.
#define STATUS_RESET_MASK ((uint16_t) 0x0400)
Defines status register reset mask.
#define STATUS_RESET_NO_RESET ((uint16_t) 0x0000 << 10)
Defines status register no reset.
#define STATUS_RESET_RESET_OCCURRED ((uint16_t) 0x0001 << 10) /* DEFAULT */
Defines status register reset.
#define STATUS_WLENGTH_MASK ((uint16_t) 0x0300)
Defines status register word length mask.
#define STATUS_WLENGTH_16BIT ((uint16_t) 0x0000 << 8)
Defines status register word length 16 bit.
#define STATUS_WLENGTH_24BIT ((uint16_t) 0x0001 << 8) /* DEFAULT */
Defines status register word length 24 bit.
#define STATUS_WLENGTH_32BIT_LSB_ZEROES ((uint16_t) 0x0002 << 8)
Defines status register word length 32 bits.
#define STATUS_WLENGTH_32BIT_MSB_SIGN_EXT ((uint16_t) 0x0003 << 8)
Defines status register word length 32 bit.
#define STATUS_FUSE_FAIL_MASK ((uint16_t) 0x0080)
Defines status register Fuse parity mask.
#define STATUS_FUSE_FAIL_OK ((uint16_t) 0x0000 << 7)
Defines status register Fuse parity OK.
#define STATUS_FUSE_FAIL_NOT_OK ((uint16_t) 0x0001 << 7)
Defines status register Fuse parity not OK.
#define STATUS_SEC_FAIL_MASK ((uint16_t) 0x0040)
Defines status register DRDY6 mask.
#define STATUS_SEC_FAIL_OK ((uint16_t) 0x0000 << 6)
Defines status register High-side supply OK.
#define STATUS_SEC_FAIL_NOT_OK ((uint16_t) 0x0001 << 6)
Defines status register High-side supply not OK.
#define STATUS_DRDY3_MASK ((uint16_t) 0x0008)
Defines status register DRDY3 mask.
#define STATUS_DRDY3_NO_NEW_DATA ((uint16_t) 0x0000 << 3)
Defines status register DRDY3 no new data.
#define STATUS_DRDY3_NEW_DATA ((uint16_t) 0x0001 << 3)
Defines status register DRDY3 new data.
#define STATUS_DRDY2_MASK ((uint16_t) 0x0004)
Defines status register DRDY2 mask.
#define STATUS_DRDY2_NO_NEW_DATA ((uint16_t) 0x0000 << 2)
Defines status register DRDY2 no new data.
#define STATUS_DRDY2_NEW_DATA ((uint16_t) 0x0001 << 2)
Defines status register DRDY2 new data.
#define STATUS_DRDY1_MASK ((uint16_t) 0x0002)
Defines status register DRDY1 mask.
#define STATUS_DRDY1_NO_NEW_DATA ((uint16_t) 0x0000 << 1)
Defines status register DRDY1 no new data.
#define STATUS_DRDY1_NEW_DATA ((uint16_t) 0x0001 << 1)
Defines status register DRDY1 new data.
#define STATUS_DRDY0_MASK ((uint16_t) 0x0001)
Defines status register DRDY0 mask.
#define STATUS_DRDY0_NO_NEW_DATA ((uint16_t) 0x0000 << 0)
Defines status register DRDY0 no new data.
#define STATUS_DRDY0_NEW_DATA ((uint16_t) 0x0001 << 0)
Defines status register DRDY0 new data.
#define MODE_ADDRESS ((uint8_t) 0x02)
Defines mode register address.
#define MODE_DEFAULT ((uint16_t) 0x0510)
Defines mode register default.
#define MODE_RESERVED0_MASK ((uint16_t) 0xC000)
Defines mode register reserved mask.
#define MODE_REG_CRC_EN_MASK ((uint16_t) 0x2000)
Defines mode register CRC EN mask.
#define MODE_REG_CRC_EN_DISABLED ((uint16_t) 0x0000 << 13) /* DEFAULT */
Defines mode register CRC EN disabled.
#define MODE_REG_CRC_EN_ENABLED ((uint16_t) 0x0001 << 13)
Defines mode register CRC EN enabled.
#define MODE_RX_CRC_EN_MASK ((uint16_t) 0x1000)
Defines mode register RX CRC EN mask.
#define MODE_RX_CRC_EN_DISABLED ((uint16_t) 0x0000 << 12) /* DEFAULT */
Defines mode register RX CRC EN disabled.
#define MODE_RX_CRC_EN_ENABLED ((uint16_t) 0x0001 << 12)
Defines mode register RX CRC EN enabled.
#define MODE_CRC_TYPE_MASK ((uint16_t) 0x0800)
Defines mode register CRC type mask.
#define MODE_CRC_TYPE_16BIT_CCITT ((uint16_t) 0x0000 << 11) /* DEFAULT */
Defines mode register CRC type 16 bit CCITT.
#define MODE_CRC_TYPE_16BIT_ANSI ((uint16_t) 0x0001 << 11)
Defines mode register CRC type 16 bit ANSI.
#define MODE_RESET_MASK ((uint16_t) 0x0400)
Defines mode register reset mask.
#define MODE_RESET_NO_RESET ((uint16_t) 0x0000 << 10)
Defines mode register no reset.
#define MODE_RESET_RESET_OCCURRED ((uint16_t) 0x0001 << 10) /* DEFAULT */
Defines mode register reset occured.
#define MODE_WLENGTH_MASK ((uint16_t) 0x0300)
Defines mode register word length mask.
#define MODE_WLENGTH_16BIT ((uint16_t) 0x0000 << 8)
Defines mode register word length 16 bit.
#define MODE_WLENGTH_24BIT ((uint16_t) 0x0001 << 8)
Defines mode register word length 24 bit.
#define MODE_WLENGTH_32BIT_LSB_ZEROES ((uint16_t) 0x0002 << 8)
Defines mode register word length 32 bits.
#define MODE_WLENGTH_32BIT_MSB_SIGN_EXT ((uint16_t) 0x0003 << 8)
Defines mode register word length 32 bit.
#define MODE_RESERVED1_MASK ((uint16_t) 0x00E0)
Defines mode register reserved mask.
#define MODE_TIMEOUT_MASK ((uint16_t) 0x0010)
Defines mode register timeout mask.
#define MODE_TIMEOUT_DISABLED ((uint16_t) 0x0000 << 4)
Defines mode register timeout disabled.
#define MODE_TIMEOUT_ENABLED ((uint16_t) 0x0001 << 4) /* DEFAULT */
Defines mode register timeout enabled.
#define MODE_DRDY_SEL_MASK ((uint16_t) 0x000C)
Defines mode register DRDY_SEL mask.
#define MODE_DRDY_SEL_MOST_LAGGING ((uint16_t) 0x0000 << 2) /* DEFAULT */
Defines mode register DRDY_SEL most lagging.
#define MODE_DRDY_SEL_LOGIC_OR ((uint16_t) 0x0001 << 2)
Defines mode register DRDY_SEL logic OR.
#define MODE_DRDY_SEL_MOST_LEADING ((uint16_t) 0x0002 << 2)
Defines mode register DRDY_SEL most leading.
#define MODE_DRDY_HiZ_MASK ((uint16_t) 0x0002)
Defines mode register DRDY_HiZ mask.
#define MODE_DRDY_HiZ_LOGIC_HIGH ((uint16_t) 0x0000 << 1) /* DEFAULT */
Defines mode register DRDY_HiZ logic high.
#define MODE_DRDY_HiZ_HIGH_IMPEDANCE ((uint16_t) 0x0001 << 1)
Defines mode register DRDY_HiZ high impedence.
#define MODE_DRDY_FMT_MASK ((uint16_t) 0x0001)
Defines mode register DRDY_FMT mask.
#define MODE_DRDY_FMT_LOGIC_LOW ((uint16_t) 0x0000 << 0) /* DEFAULT */
Defines mode register DRDY_FMT low.
#define MODE_DRDY_FMT_NEG_PULSE_FIXED_WIDTH ((uint16_t) 0x0001 << 0)
Defines mode register DRDY_FMT neg pulse fixed width.
#define CLOCK_ADDRESS ((uint8_t) 0x03)
Defines clock register address.
#define AMC_CLOCK_DEFAULT ((uint16_t) 0xFF0E)
AMC default clock setting.
#define CLOCK_CH7_EN_MASK ((uint16_t) 0x8000)
Defines clock register CH7 EN mask.
#define CLOCK_CH7_EN_DISABLED ((uint16_t) 0x0000 << 15)
Defines clock register CH7 EN Disabled.
#define CLOCK_CH7_EN_ENABLED ((uint16_t) 0x0001 << 15)
Defines clock register CH7 EN enabled.
#define CLOCK_CH6_EN_MASK ((uint16_t) 0x4000)
Defines clock register CH6 EN mask.
#define CLOCK_CH6_EN_DISABLED ((uint16_t) 0x0000 << 14)
Defines clock register CH6 EN Disabled.
#define CLOCK_CH6_EN_ENABLED ((uint16_t) 0x0001 << 14)
Defines clock register CH6 EN enabled.
#define CLOCK_CH5_EN_MASK ((uint16_t) 0x2000)
Defines clock register CH5 EN mask.
#define CLOCK_CH5_EN_DISABLED ((uint16_t) 0x0000 << 13)
Defines clock register CH5 EN Disabled.
#define CLOCK_CH5_EN_ENABLED ((uint16_t) 0x0001 << 13)
Defines clock register CH5 EN enabled.
#define CLOCK_CH4_EN_MASK ((uint16_t) 0x1000)
Defines clock register CH4 EN mask.
#define CLOCK_CH4_EN_DISABLED ((uint16_t) 0x0000 << 12)
Defines clock register CH4 EN Disabled.
#define CLOCK_CH4_EN_ENABLED ((uint16_t) 0x0001 << 12)
Defines clock register CH4 EN enabled.
#define CLOCK_CH3_EN_MASK ((uint16_t) 0x0800)
Defines clock register CH3 EN mask.
#define CLOCK_CH3_EN_DISABLED ((uint16_t) 0x0000 << 11)
Defines clock register CH3 EN Disabled.
#define CLOCK_CH3_EN_ENABLED ((uint16_t) 0x0001 << 11)
Defines clock register CH3 EN enabled.
#define CLOCK_CH2_EN_MASK ((uint16_t) 0x0400)
Defines clock register CH2 EN mask.
#define CLOCK_CH2_EN_DISABLED ((uint16_t) 0x0000 << 10)
Defines clock register CH2 EN Disabled.
#define CLOCK_CH2_EN_ENABLED ((uint16_t) 0x0001 << 10)
Defines clock register CH2 EN enabled.
#define CLOCK_CH1_EN_MASK ((uint16_t) 0x0200)
Defines clock register CH1 EN mask.
#define CLOCK_CH1_EN_DISABLED ((uint16_t) 0x0000 << 9)
Defines clock register CH1 EN Disabled.
#define CLOCK_CH1_EN_ENABLED ((uint16_t) 0x0001 << 9)
Defines clock register CH1 EN enabled.
#define CLOCK_CH0_EN_MASK ((uint16_t) 0x0100)
Defines clock register CH0 EN mask.
#define CLOCK_CH0_EN_DISABLED ((uint16_t) 0x0000 << 8)
Defines clock register CH0 EN Disabled.
#define CLOCK_CH0_EN_ENABLED ((uint16_t) 0x0001 << 8) /* DEFAULT */
Defines clock register CH0 EN enabled.
#define CLOCK_RESERVED_MASK_M04 ((uint16_t) 0x00E0)
Defines clock register reserved mask 04.
#define CLOCK_RESERVED_MASK_M08 ((uint16_t) 0x0020)
Defines clock register reserved mask 08.
#define CLOCK_XTAL_DIS_MASK ((uint16_t) 0x0080)
Defines clock register XTAL DIS mask.
#define CLOCK_XTAL_DIS_ENABLED ((uint16_t) 0x0000 << 7) /* DEFAULT */
Defines clock register XTAL DIS enabled.
#define CLOCK_XTAL_DIS_DISABLED ((uint16_t) 0x0001 << 7)
Defines clock register XTAL DIS disabled.
#define CLOCK_EXTREF_EN_MASK ((uint16_t) 0x0040)
Defines clock register EXTREF_EN mask.
#define CLOCK_EXTREF_EN_DISABLED ((uint16_t) 0x0000 << 6) /* DEFAULT */
Defines clock register EXTREF_EN disabled.
#define CLOCK_EXTREF_EN_ENABLED ((uint16_t) 0x0001 << 6)
Defines clock register EXTREF_EN enabled.
#define CLOCK_OSR_MASK ((uint16_t) 0x001C)
Defines clock register OSR mask.
#define CLOCK_OSR_128 ((uint16_t) 0x0000 << 2)
Defines clock register 128 mask.
#define CLOCK_OSR_256 ((uint16_t) 0x0001 << 2)
Defines clock register 256 mask.
#define CLOCK_OSR_512 ((uint16_t) 0x0002 << 2)
Defines clock register 512 mask.
#define CLOCK_OSR_1024 ((uint16_t) 0x0003 << 2) /* DEFAULT */
Defines clock register 1024 mask.
#define CLOCK_OSR_2048 ((uint16_t) 0x0004 << 2)
Defines clock register 2048 mask.
#define CLOCK_OSR_4096 ((uint16_t) 0x0005 << 2)
Defines clock register 4096 mask.
#define CLOCK_OSR_8192 ((uint16_t) 0x0006 << 2)
Defines clock register 8192 mask.
#define CLOCK_OSR_16384 ((uint16_t) 0x0007 << 2)
Defines clock register 16384 mask.
#define CLOCK_PWR_MASK ((uint16_t) 0x0003)
Defines clock register PWR mask.
#define CLOCK_PWR_VLP ((uint16_t) 0x0000 << 0)
Defines clock register PWR VLP.
#define CLOCK_PWR_LP ((uint16_t) 0x0001 << 0)
Defines clock register PWR LP.
#define CLOCK_PWR_HR ((uint16_t) 0x0002 << 0) /* DEFAULT */
Defines clock register PWR HR.
#define GAIN1_ADDRESS ((uint8_t) 0x04)
Defines GAIN1 register Address.
#define GAIN1_DEFAULT ((uint16_t) 0x0000)
Defines GAIN1 register Defaults.
#define GAIN1_RESERVED0_MASK ((uint16_t) 0x8000)
Defines GAIN1 register reserved0 mask.
#define GAIN1_PGAGAIN3_MASK ((uint16_t) 0x7000)
Defines GAIN1 register PGAGAIB3 mask.
#define GAIN1_PGAGAIN3_1 ((uint16_t) 0x0000 << 12) /* DEFAULT */
Defines GAIN1 register PGAGAIB3 1.
#define GAIN1_PGAGAIN3_2 ((uint16_t) 0x0001 << 12)
Defines GAIN1 register PGAGAIB3 2.
#define GAIN1_PGAGAIN3_4 ((uint16_t) 0x0002 << 12)
Defines GAIN1 register PGAGAIB3 4.
#define GAIN1_PGAGAIN3_8 ((uint16_t) 0x0003 << 12)
Defines GAIN1 register PGAGAIB3 8.
#define GAIN1_PGAGAIN3_16 ((uint16_t) 0x0004 << 12)
Defines GAIN1 register PGAGAIB3 16.
#define GAIN1_PGAGAIN3_32 ((uint16_t) 0x0005 << 12)
Defines GAIN1 register PGAGAIB3 32.
#define GAIN1_PGAGAIN3_64 ((uint16_t) 0x0006 << 12)
Defines GAIN1 register PGAGAIB3 64.
#define GAIN1_PGAGAIN3_128 ((uint16_t) 0x0007 << 12)
Defines GAIN1 register PGAGAIB3 mas128k.
#define GAIN1_RESERVED1_MASK ((uint16_t) 0x0800)
Defines GAIN1 register reserved1 mask.
#define GAIN1_PGAGAIN2_MASK ((uint16_t) 0x0700)
Defines GAIN1 register PGAGAIB2 mask.
#define GAIN1_PGAGAIN2_1 ((uint16_t) 0x0000 << 8) /* DEFAULT */
Defines GAIN1 register PGAGAIB2 1.
#define GAIN1_PGAGAIN2_2 ((uint16_t) 0x0001 << 8)
Defines GAIN1 register PGAGAIB2 2.
#define GAIN1_PGAGAIN2_4 ((uint16_t) 0x0002 << 8)
Defines GAIN1 register PGAGAIB2 4.
#define GAIN1_PGAGAIN2_8 ((uint16_t) 0x0003 << 8)
Defines GAIN1 register PGAGAIB2 8.
#define GAIN1_PGAGAIN2_16 ((uint16_t) 0x0004 << 8)
Defines GAIN1 register PGAGAIB2 16.
#define GAIN1_PGAGAIN2_32 ((uint16_t) 0x0005 << 8)
Defines GAIN1 register PGAGAIB2 32.
#define GAIN1_PGAGAIN2_64 ((uint16_t) 0x0006 << 8)
Defines GAIN1 register PGAGAIB2 64.
#define GAIN1_PGAGAIN2_128 ((uint16_t) 0x0007 << 8)
Defines GAIN1 register PGAGAIB2 128.
#define GAIN1_RESERVED2_MASK ((uint16_t) 0x0080)
Defines GAIN1 register reserved2 mask.
#define GAIN1_PGAGAIN1_MASK ((uint16_t) 0x0070)
Defines GAIN1 register PGAGAIB1 mask.
#define GAIN1_PGAGAIN1_1 ((uint16_t) 0x0000 << 4) /* DEFAULT */
Defines GAIN1 register PGAGAIB1 1.
#define GAIN1_PGAGAIN1_2 ((uint16_t) 0x0001 << 4)
Defines GAIN1 register PGAGAIB1 2.
#define GAIN1_PGAGAIN1_4 ((uint16_t) 0x0002 << 4)
Defines GAIN1 register PGAGAIB1 4.
#define GAIN1_PGAGAIN1_8 ((uint16_t) 0x0003 << 4)
Defines GAIN1 register PGAGAIB1 8.
#define GAIN1_PGAGAIN1_16 ((uint16_t) 0x0004 << 4)
Defines GAIN1 register PGAGAIB1 16.
#define GAIN1_PGAGAIN1_32 ((uint16_t) 0x0005 << 4)
Defines GAIN1 register PGAGAIB1 32.
#define GAIN1_PGAGAIN1_64 ((uint16_t) 0x0006 << 4)
Defines GAIN1 register PGAGAIB1 64.
#define GAIN1_PGAGAIN1_128 ((uint16_t) 0x0007 << 4)
Defines GAIN1 register PGAGAIB1 128.
#define GAIN1_RESERVED3_MASK ((uint16_t) 0x0008)
Defines GAIN1 register reserved3 mask.
#define GAIN1_PGAGAIN0_MASK ((uint16_t) 0x0007)
Defines GAIN1 register PGAGAIB0 mask.
#define GAIN1_PGAGAIN0_1 ((uint16_t) 0x0000 << 0) /* DEFAULT */
Defines GAIN1 register PGAGAIB0 1.
#define GAIN1_PGAGAIN0_2 ((uint16_t) 0x0001 << 0)
Defines GAIN1 register PGAGAIB0 2.
#define GAIN1_PGAGAIN0_4 ((uint16_t) 0x0002 << 0)
Defines GAIN1 register PGAGAIB0 4.
#define GAIN1_PGAGAIN0_8 ((uint16_t) 0x0003 << 0)
Defines GAIN1 register PGAGAIB0 8.
#define GAIN1_PGAGAIN0_16 ((uint16_t) 0x0004 << 0)
Defines GAIN1 register PGAGAIB0 16.
#define GAIN1_PGAGAIN0_32 ((uint16_t) 0x0005 << 0)
Defines GAIN1 register PGAGAIB0 32.
#define GAIN1_PGAGAIN0_64 ((uint16_t) 0x0006 << 0)
Defines GAIN1 register PGAGAIB0 64.
#define GAIN1_PGAGAIN0_128 ((uint16_t) 0x0007 << 0)
Defines GAIN1 register PGAGAIB0 128.
#define GAIN2_ADDRESS ((uint8_t) 0x05)
Defines GAIN2 register Address.
#define GAIN2_DEFAULT ((uint16_t) 0x0000)
Defines GAIN2 register Default.
#define GAIN2_RESERVED0_MASK ((uint16_t) 0x8000)
Defines GAIN2 register reserved0 mask.
#define GAIN2_PGAGAIN7_MASK ((uint16_t) 0x7000)
Defines GAIN2 register PGAGAIN7 mask.
#define GAIN2_PGAGAIN7_1 ((uint16_t) 0x0000 << 12) /* DEFAULT */
Defines GAIN2 register PGAGAIN7 1.
#define GAIN2_PGAGAIN7_2 ((uint16_t) 0x0001 << 12)
Defines GAIN2 register PGAGAIN7 2.
#define GAIN2_PGAGAIN7_4 ((uint16_t) 0x0002 << 12)
Defines GAIN2 register PGAGAIN7 4.
#define GAIN2_PGAGAIN7_8 ((uint16_t) 0x0003 << 12)
Defines GAIN2 register PGAGAIN7 8.
#define GAIN2_PGAGAIN7_16 ((uint16_t) 0x0004 << 12)
Defines GAIN2 register PGAGAIN7 16.
#define GAIN2_PGAGAIN7_32 ((uint16_t) 0x0005 << 12)
Defines GAIN2 register PGAGAIN7 32.
#define GAIN2_PGAGAIN7_64 ((uint16_t) 0x0006 << 12)
Defines GAIN2 register PGAGAIN7 64.
#define GAIN2_PGAGAIN7_128 ((uint16_t) 0x0007 << 12)
Defines GAIN2 register PGAGAIN7 128.
#define GAIN2_RESERVED1_MASK ((uint16_t) 0x0800)
Defines GAIN2 register reserved1 mask.
#define GAIN2_PGAGAIN6_MASK ((uint16_t) 0x0700)
Defines GAIN2 register PGAGAIN6 mask.
#define GAIN2_PGAGAIN6_1 ((uint16_t) 0x0000 << 8) /* DEFAULT */
Defines GAIN2 register PGAGAIN6 1.
#define GAIN2_PGAGAIN6_2 ((uint16_t) 0x0001 << 8)
Defines GAIN2 register PGAGAIN6 2.
#define GAIN2_PGAGAIN6_4 ((uint16_t) 0x0002 << 8)
Defines GAIN2 register PGAGAIN6 4.
#define GAIN2_PGAGAIN6_8 ((uint16_t) 0x0003 << 8)
Defines GAIN2 register PGAGAIN6 8.
#define GAIN2_PGAGAIN6_16 ((uint16_t) 0x0004 << 8)
Defines GAIN2 register PGAGAIN6 16.
#define GAIN2_PGAGAIN6_32 ((uint16_t) 0x0005 << 8)
Defines GAIN2 register PGAGAIN6 32.
#define GAIN2_PGAGAIN6_64 ((uint16_t) 0x0006 << 8)
Defines GAIN2 register PGAGAIN6 64.
#define GAIN2_PGAGAIN6_128 ((uint16_t) 0x0007 << 8)
Defines GAIN2 register PGAGAIN6 128.
#define GAIN2_RESERVED2_MASK ((uint16_t) 0x0080)
Defines GAIN2 register reserved2 mask.
#define GAIN2_PGAGAIN5_MASK ((uint16_t) 0x0070)
Defines GAIN2 register PGAGAIN5 mask.
#define GAIN2_PGAGAIN5_1 ((uint16_t) 0x0000 << 4) /* DEFAULT */
Defines GAIN2 register PGAGAIN5 1.
#define GAIN2_PGAGAIN5_2 ((uint16_t) 0x0001 << 4)
Defines GAIN2 register PGAGAIN5 2.
#define GAIN2_PGAGAIN5_4 ((uint16_t) 0x0002 << 4)
Defines GAIN2 register PGAGAIN5 4.
#define GAIN2_PGAGAIN5_8 ((uint16_t) 0x0003 << 4)
Defines GAIN2 register PGAGAIN5 8.
#define GAIN2_PGAGAIN5_16 ((uint16_t) 0x0004 << 4)
Defines GAIN2 register PGAGAIN5 16.
#define GAIN2_PGAGAIN5_32 ((uint16_t) 0x0005 << 4)
Defines GAIN2 register PGAGAIN5 32.
#define GAIN2_PGAGAIN5_64 ((uint16_t) 0x0006 << 4)
Defines GAIN2 register PGAGAIN5 64.
#define GAIN2_PGAGAIN5_128 ((uint16_t) 0x0007 << 4)
Defines GAIN2 register PGAGAIN5 128.
#define GAIN2_RESERVED3_MASK ((uint16_t) 0x0008)
Defines GAIN2 register reserved3 mask.
#define GAIN2_PGAGAIN4_MASK ((uint16_t) 0x0007)
Defines GAIN2 register PGAGAIN4 mask.
#define GAIN2_PGAGAIN4_1 ((uint16_t) 0x0000 << 0) /* DEFAULT */
Defines GAIN2 register PGAGAIN4 1.
#define GAIN2_PGAGAIN4_2 ((uint16_t) 0x0001 << 0)
Defines GAIN2 register PGAGAIN4 2.
#define GAIN2_PGAGAIN4_4 ((uint16_t) 0x0002 << 0)
Defines GAIN2 register PGAGAIN4 4.
#define GAIN2_PGAGAIN4_8 ((uint16_t) 0x0003 << 0)
Defines GAIN2 register PGAGAIN4 8.
#define GAIN2_PGAGAIN4_16 ((uint16_t) 0x0004 << 0)
Defines GAIN2 register PGAGAIN4 16.
#define GAIN2_PGAGAIN4_32 ((uint16_t) 0x0005 << 0)
Defines GAIN2 register PGAGAIN4 32.
#define GAIN2_PGAGAIN4_64 ((uint16_t) 0x0006 << 0)
Defines GAIN2 register PGAGAIN4 64.
#define GAIN2_PGAGAIN4_128 ((uint16_t) 0x0007 << 0)
Defines GAIN2 register PGAGAIN4 128.
#define CFG_ADDRESS ((uint8_t) 0x06)
Defines CFG register Address.
#define CFG_DEFAULT ((uint16_t) 0x0600)
Defines CFG register defaults.
#define CFG_RESERVED0_MASK ((uint16_t) 0xE000)
Defines CFG register reserved mask.
#define CFG_GC_DLY_MASK ((uint16_t) 0x1E00)
Defines CFG register GC DLY mask.
#define CFG_GC_DLY_2 ((uint16_t) 0x0000 << 9)
Defines CFG register GC DLY 2.
#define CFG_GC_DLY_4 ((uint16_t) 0x0001 << 9)
Defines CFG register GC DLY 4.
#define CFG_GC_DLY_8 ((uint16_t) 0x0002 << 9)
Defines CFG register GC DLY 8.
#define CFG_GC_DLY_16 ((uint16_t) 0x0003 << 9) /* DEFAULT */
Defines CFG register GC DLY 16.
#define CFG_GC_DLY_32 ((uint16_t) 0x0004 << 9)
Defines CFG register GC DLY 32.
#define CFG_GC_DLY_64 ((uint16_t) 0x0005 << 9)
Defines CFG register GC DLY 64.
#define CFG_GC_DLY_128 ((uint16_t) 0x0006 << 9)
Defines CFG register GC DLY 128.
#define CFG_GC_DLY_256 ((uint16_t) 0x0007 << 9)
Defines CFG register GC DLY 256.
#define CFG_GC_DLY_512 ((uint16_t) 0x0008 << 9)
Defines CFG register GC DLY 512.
#define CFG_GC_DLY_1024 ((uint16_t) 0x0009 << 9)
Defines CFG register GC DLY 1024.
#define CFG_GC_DLY_2048 ((uint16_t) 0x000A << 9)
Defines CFG register GC DLY 2048.
#define CFG_GC_DLY_4096 ((uint16_t) 0x000B << 9)
Defines CFG register GC DLY 4096.
#define CFG_GC_DLY_8192 ((uint16_t) 0x000C << 9)
Defines CFG register GC DLY 8192.
#define CFG_GC_DLY_16484 ((uint16_t) 0x000D << 9)
Defines CFG register GC DLY 16484.
#define CFG_GC_DLY_32768 ((uint16_t) 0x000E << 9)
Defines CFG register GC DLY 32768.
#define CFG_GC_DLY_65536 ((uint16_t) 0x000F << 9)
Defines CFG register GC DLY 65536.
#define CFG_GC_EN_MASK ((uint16_t) 0x0100)
Defines CFG register GC EN mask.
#define CFG_GC_EN_DISABLED ((uint16_t) 0x0000 << 8) /* DEFAULT */
Defines CFG register GC EN disabled.
#define CFG_GC_EN_ENABLED ((uint16_t) 0x0001 << 8)
Defines CFG register GC EN enabled.
#define CFG_CD_ALLCH_MASK ((uint16_t) 0x0080)
Defines CFG register CD ALLCH mask.
#define CFG_CD_ALLCH_ANY_CHANNEL ((uint16_t) 0x0000 << 7) /* DEFAULT */
Defines CFG register CD ALLCH any.
#define CFG_CD_ALLCH_ALL_CHANNELS ((uint16_t) 0x0001 << 7)
Defines CFG register CD ALLCH all.
#define CFG_CD_NUM_MASK ((uint16_t) 0x0070)
Defines CFG register CD NUM mask.
#define CFG_CD_NUM_1 ((uint16_t) 0x0000 << 4) /* DEFAULT */
Defines CFG register CD NUM 1.
#define CFG_CD_NUM_2 ((uint16_t) 0x0001 << 4)
Defines CFG register CD NUM 2.
#define CFG_CD_NUM_4 ((uint16_t) 0x0002 << 4)
Defines CFG register CD NUM 4.
#define CFG_CD_NUM_8 ((uint16_t) 0x0003 << 4)
Defines CFG register CD NUM 8.
#define CFG_CD_NUM_16 ((uint16_t) 0x0004 << 4)
Defines CFG register CD NUM 16.
#define CFG_CD_NUM_32 ((uint16_t) 0x0005 << 4)
Defines CFG register CD NUM 32.
#define CFG_CD_NUM_64 ((uint16_t) 0x0006 << 4)
Defines CFG register CD NUM 64.
#define CFG_CD_NUM_128 ((uint16_t) 0x0007 << 4)
Defines CFG register CD NUM 128.
#define CFG_CD_LEN_MASK ((uint16_t) 0x000E)
Defines CFG register CD LEn mask.
#define CFG_CD_LEN_128 ((uint16_t) 0x0000 << 1) /* DEFAULT */
Defines CFG register CD LEn 128.
#define CFG_CD_LEN_256 ((uint16_t) 0x0001 << 1)
Defines CFG register CD LEn 256.
#define CFG_CD_LEN_512 ((uint16_t) 0x0002 << 1)
Defines CFG register CD LEn 512.
#define CFG_CD_LEN_768 ((uint16_t) 0x0003 << 1)
Defines CFG register CD LEn 768.
#define CFG_CD_LEN_1280 ((uint16_t) 0x0004 << 1)
Defines CFG register CD LEn 1280.
#define CFG_CD_LEN_1792 ((uint16_t) 0x0005 << 1)
Defines CFG register CD LEn 1790.
#define CFG_CD_LEN_2560 ((uint16_t) 0x0006 << 1)
Defines CFG register CD LEn 2560.
#define CFG_CD_LEN_3584 ((uint16_t) 0x0007 << 1)
Defines CFG register CD LEn 3584.
#define CFG_CD_EN_MASK ((uint16_t) 0x0001)
Defines CFG register CD EN mask.
#define CFG_CD_EN_DISABLED ((uint16_t) 0x0000 << 0) /* DEFAULT */
Defines CFG register CD EN disabled.
#define CFG_CD_EN_ENABLED ((uint16_t) 0x0001 << 0)
Defines CFG register CD EN enabled.
#define THRSHLD_MSB_ADDRESS ((uint8_t) 0x07)
Defines THRSHLD_MSB register address.
#define THRSHLD_MSB_DEFAULT ((uint16_t) 0x0000)
Defines THRSHLD_MSB register default.
#define THRSHLD_MSB_CD_TH_MSB_MASK ((uint16_t) 0xFFFF)
Defines THRSHLD_MSB register mask.
#define THRSHLD_LSB_ADDRESS ((uint8_t) 0x08)
Defines THRSHLD_LSB register address.
#define THRSHLD_LSB_DEFAULT ((uint16_t) 0x0000)
Defines THRSHLD_LSB register default.
#define THRSHLD_LSB_CD_TH_LSB_MASK ((uint16_t) 0xFF00)
Defines THRSHLD_LSB register mask.
#define THRSHLD_LSB_RESERVED0_MASK ((uint16_t) 0x00F0)
Defines THRSHLD_LSB register reserved mask.
#define THRSHLD_LSB_DCBLOCK_MASK ((uint16_t) 0x000F)
Defines THRSHLD_LSB register DCBLOCk mask.
#define THRSHLD_LSB_DCBLOCK_DISABLED ((uint16_t) 0x0000 << 0)
Defines THRSHLD_LSB register DCBLOCk disabled.
#define THRSHLD_LSB_DCBLOCK_181P0Hz ((uint16_t) 0x0001 << 0)
Defines THRSHLD_LSB register DCBLOCk 181P0.
#define THRSHLD_LSB_DCBLOCK_84p8Hz ((uint16_t) 0x0002 << 0)
Defines THRSHLD_LSB register DCBLOCk 84P8.
#define THRSHLD_LSB_DCBLOCK_41p1Hz ((uint16_t) 0x0003 << 0)
Defines THRSHLD_LSB register DCBLOCk 41P1.
#define THRSHLD_LSB_DCBLOCK_20p2Hz ((uint16_t) 0x0004 << 0)
Defines THRSHLD_LSB register DCBLOCk 20P2.
#define THRSHLD_LSB_DCBLOCK_10p0Hz ((uint16_t) 0x0005 << 0)
Defines THRSHLD_LSB register DCBLOCk 10P0.
#define THRSHLD_LSB_DCBLOCK_4p99Hz ((uint16_t) 0x0006 << 0)
Defines THRSHLD_LSB register DCBLOCk 4P99.
#define THRSHLD_LSB_DCBLOCK_2p49Hz ((uint16_t) 0x0007 << 0)
Defines THRSHLD_LSB register DCBLOCk 2P49.
#define THRSHLD_LSB_DCBLOCK_1p24Hz ((uint16_t) 0x0008 << 0)
Defines THRSHLD_LSB register DCBLOCk 1P24.
#define THRSHLD_LSB_DCBLOCK_622mHz ((uint16_t) 0x0009 << 0)
Defines THRSHLD_LSB register DCBLOCk 622m.
#define THRSHLD_LSB_DCBLOCK_311mHz ((uint16_t) 0x000A << 0)
Defines THRSHLD_LSB register DCBLOCk 311m.
#define THRSHLD_LSB_DCBLOCK_155mHz ((uint16_t) 0x000B << 0)
Defines THRSHLD_LSB register DCBLOCk 155m.
#define THRSHLD_LSB_DCBLOCK_77p7mHz ((uint16_t) 0x000C << 0)
Defines THRSHLD_LSB register DCBLOCk 77P7m.
#define THRSHLD_LSB_DCBLOCK_38p9mHz ((uint16_t) 0x000D << 0)
Defines THRSHLD_LSB register DCBLOCk 38p9m.
#define THRSHLD_LSB_DCBLOCK_19p4mHz ((uint16_t) 0x000F << 0)
Defines THRSHLD_LSB register DCBLOCk 19P4m.
#define THRSHLD_LSB_DCBLOCK_9p70mHz ((uint16_t) 0x0007 << 0)
Defines THRSHLD_LSB register DCBLOCk 9P7m.
#define CH0_CFG_ADDRESS ((uint8_t) 0x09)
Define CH0 CFG register Address.
#define CH0_CFG_DEFAULT ((uint16_t) 0x0000)
Define CH0 CFG register deafult.
#define CH0_CFG_PHASE0_MASK ((uint16_t) 0xFFC0)
Define CH0 CFG register Phase0 mask.
#define PHASEn_SHIFT (6)
Define CH0 CFG register Phase0 shift.
#define SET_PHASE_REGISTER_VALUE(phase_shift) ((phase_shift)<<PHASEn_SHIFT)
Define CH0 CFG register Phase0 register value.
#define CH0_CFG_RESERVED0_MASK ((uint16_t) 0x003C)
Define CH0 CFG register reserved mask.
#define CH0_CFG_MUX0_MASK ((uint16_t) 0x0003)
Define CH0 CFG register MUX0 mask.
#define CH0_CFG_MUX0_AIN0P_AIN0N ((uint16_t) 0x0000 << 0) /* DEFAULT */
Define CH0 CFG register MUX0 AIN0P_AIN0N.
#define CH0_CFG_MUX0_ADC_INPUT_SHORT ((uint16_t) 0x0001 << 0)
Define CH0 CFG register MUX0 ADC input short.
#define CH0_CFG_MUX0_DC_DIAGNOSTIC ((uint16_t) 0x0002 << 0)
Define CH0 CFG register MUX0 DC DIAGNOSTIC.
#define CH0_CFG_MUX0_AC_DIAGNOSTIC ((uint16_t) 0x0003 << 0)
Define CH0 CFG register MUX0 AC DIAGNOSTIC.
#define CH0_OCAL_MSB_ADDRESS ((uint8_t) 0x0A)
Define CH0 OCAL MSB register Address.
#define CH0_OCAL_MSB_DEFAULT ((uint16_t) 0x0000)
Define CH0 OCAL MSB register default.
#define CH0_OCAL_MSB_OCAL0_MSB_MASK ((uint16_t) 0xFFFF)
Define CH0 OCAL MSB register mask.
#define CH0_OCAL_LSB_ADDRESS ((uint8_t) 0x0B)
Define CH0 OCAL LSB register Address.
#define CH0_OCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH0 OCAL LSB register default.
#define CH0_OCAL_LSB_OCAL0_LSB_MASK ((uint16_t) 0xFF00)
Define CH0 OCAL LSB register mask.
#define CH0_OCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH0 OCAL LSB register reserved mask.
#define CH0_GCAL_MSB_ADDRESS ((uint8_t) 0x0C)
Define CH0 GCAL MSB register Address.
#define CH0_GCAL_MSB_DEFAULT ((uint16_t) 0x8000)
Define CH0 GCAL MSB register default.
#define CH0_GCAL_MSB_GCAL0_MSB_MASK ((uint16_t) 0xFFFF)
Define CH0 GCAL MSB register mask.
#define CH0_GCAL_LSB_ADDRESS ((uint8_t) 0x0D)
Define CH0 GCAL LSB register Address.
#define CH0_GCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH0 GCAL LSB register default.
#define CH0_GCAL_LSB_GCAL0_LSB_MASK ((uint16_t) 0xFF00)
Define CH0 GCAL LSB register mask.
#define CH0_GCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH0 GCAL LSB register reserved mask.
#define CH1_CFG_ADDRESS ((uint8_t) 0x0E)
Define CH1 CFG register Address.
#define CH1_CFG_DEFAULT ((uint16_t) 0x0000)
Define CH1 CFG register Default.
#define CH1_CFG_PHASE1_MASK ((uint16_t) 0xFFC0)
Define CH1 CFG register phase1 mask.
#define CH1_CFG_RESERVED0_MASK ((uint16_t) 0x003C)
Define CH1 CFG register reserved mask.
#define CH1_CFG_MUX1_MASK ((uint16_t) 0x0003)
Define CH1 CFG register MUX1 mask.
#define CH1_CFG_MUX1_AIN1P_AIN1N ((uint16_t) 0x0000 << 0) /* DEFAULT */
Define CH1 CFG register MUX1 AIN1P_AIN1N.
#define CH1_CFG_MUX1_ADC_INPUT_SHORT ((uint16_t) 0x0001 << 0)
Define CH1 CFG register MUX1 ADC input short.
#define CH1_CFG_MUX1_DC_DIAGNOSTIC ((uint16_t) 0x0002 << 0)
Define CH1 CFG register MUX1 dc diagnostic.
#define CH1_CFG_MUX1_AC_DIAGNOSTIC ((uint16_t) 0x0003 << 0)
Define CH1 CFG register MUX1 ac diagnostic.
#define CH1_OCAL_MSB_ADDRESS ((uint8_t) 0x0F)
Define CH1 OCAL MSB register Address.
#define CH1_OCAL_MSB_DEFAULT ((uint16_t) 0x0000)
Define CH1 OCAL MSB register default.
#define CH1_OCAL_MSB_OCAL1_MSB_MASK ((uint16_t) 0xFFFF)
Define CH1 OCAL MSB register mask.
#define CH1_OCAL_LSB_ADDRESS ((uint8_t) 0x10)
Define CH1 OCAL LSB register Address.
#define CH1_OCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH1 OCAL LSB register Defaullt.
#define CH1_OCAL_LSB_OCAL1_LSB_MASK ((uint16_t) 0xFF00)
Define CH1 OCAL LSB register mask.
#define CH1_OCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH1 OCAL LSB register reserved mask.
#define CH1_GCAL_MSB_ADDRESS ((uint8_t) 0x11)
Define CH1 GCAL MSB register Address.
#define CH1_GCAL_MSB_DEFAULT ((uint16_t) 0x8000)
Define CH1 GCAL MSB register default.
#define CH1_GCAL_MSB_GCAL1_MSB_MASK ((uint16_t) 0xFFFF)
Define CH1 GCAL MSB register mask.
#define CH1_GCAL_LSB_ADDRESS ((uint8_t) 0x12)
Define CH1 GCAL LSB register Address.
#define CH1_GCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH1 GCAL LSB register default.
#define CH1_GCAL_LSB_GCAL1_LSB_MASK ((uint16_t) 0xFF00)
Define CH1 GCAL LSB register mask.
#define CH1_GCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH1 GCAL LSB register reserved mask.
#define CH2_CFG_ADDRESS ((uint8_t) 0x13)
Define CH2 CFG register Address.
#define CH2_CFG_DEFAULT ((uint16_t) 0x0000)
Define CH2 CFG register Default.
#define CH2_CFG_PHASE2_MASK ((uint16_t) 0xFFC0)
Define CH2 CFG register Phase2 mask.
#define CH2_CFG_RESERVED0_MASK ((uint16_t) 0x003C)
Define CH2 CFG register reserved0 mask.
#define CH2_CFG_MUX2_MASK ((uint16_t) 0x0003)
Define CH2 CFG register MUX mask.
#define CH2_CFG_MUX2_AIN2P_AIN2N ((uint16_t) 0x0000 << 0) /* DEFAULT */
Define CH2 CFG register MUX AIN2P_AIN2N.
#define CH2_CFG_MUX2_ADC_INPUT_SHORT ((uint16_t) 0x0001 << 0)
Define CH2 CFG register MUX ADC input short.
#define CH2_CFG_MUX2_DC_DIAGNOSTIC ((uint16_t) 0x0002 << 0)
Define CH2 CFG register MUX dc diagnostic.
#define CH2_CFG_MUX2_AC_DIAGNOSTIC ((uint16_t) 0x0003 << 0)
Define CH2 CFG register MUX ac diagnostic.
#define CH2_OCAL_MSB_ADDRESS ((uint8_t) 0x14)
Define CH2 OCAL MSB register Address.
#define CH2_OCAL_MSB_DEFAULT ((uint16_t) 0x0000)
Define CH2 OCAL MSB register default.
#define CH2_OCAL_MSB_OCAL2_MSB_MASK ((uint16_t) 0xFFFF)
Define CH2 OCAL MSB register mask.
#define CH2_OCAL_LSB_ADDRESS ((uint8_t) 0x15)
Define CH2 OCAL LSB register Address.
#define CH2_OCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH2 OCAL LSB register default.
#define CH2_OCAL_LSB_OCAL2_LSB_MASK ((uint16_t) 0xFF00)
Define CH2 OCAL LSB register mask.
#define CH2_OCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH2 OCAL LSB register reserved0 mask.
#define CH2_GCAL_MSB_ADDRESS ((uint8_t) 0x16)
Define CH2 GCAL MSB register Address.
#define CH2_GCAL_MSB_DEFAULT ((uint16_t) 0x8000)
Define CH2 GCAL MSB register default.
#define CH2_GCAL_MSB_GCAL2_MSB_MASK ((uint16_t) 0xFFFF)
Define CH2 GCAL MSB register mask.
#define CH2_GCAL_LSB_ADDRESS ((uint8_t) 0x17)
Define CH2 GCAL LSB register Address.
#define CH2_GCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH2 GCAL LSB register default.
#define CH2_GCAL_LSB_GCAL2_LSB_MASK ((uint16_t) 0xFF00)
Define CH2 GCAL LSB register mask.
#define CH2_GCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH2 GCAL LSB register reserved mask.
#define CH3_CFG_ADDRESS ((uint8_t) 0x18)
Define CH3 CFG register Address.
#define CH3_CFG_DEFAULT ((uint16_t) 0x0000)
Define CH3 CFG register Default.
#define CH3_CFG_PHASE3_MASK ((uint16_t) 0xFFC0)
Define CH3 CFG register phase3 mask.
#define CH3_CFG_RESERVED0_MASK ((uint16_t) 0x003C)
Define CH3 CFG register resereved mask.
#define CH3_CFG_MUX3_MASK ((uint16_t) 0x0003)
Define CH3 CFG register MUX3 mask.
#define CH3_CFG_MUX3_AIN3P_AIN3N ((uint16_t) 0x0000 << 0) /* DEFAULT */
Define CH3 CFG register MUX3 AIN3P_AIN3N.
#define CH3_CFG_MUX3_ADC_INPUT_SHORT ((uint16_t) 0x0001 << 0)
Define CH3 CFG register MUX3 ADC input short.
#define CH3_CFG_MUX3_DC_DIAGNOSTIC ((uint16_t) 0x0002 << 0)
Define CH3 CFG register MUX3 dc diagnostic.
#define CH3_CFG_MUX3_AC_DIAGNOSTIC ((uint16_t) 0x0003 << 0)
Define CH3 CFG register MUX3 ac diagnostic.
#define CH3_OCAL_MSB_ADDRESS ((uint8_t) 0x19)
Define CH3 OCAL MSB register Address.
#define CH3_OCAL_MSB_DEFAULT ((uint16_t) 0x0000)
Define CH3 OCAL MSB register Deafault.
#define CH3_OCAL_MSB_OCAL3_MSB_MASK ((uint16_t) 0xFFFF)
Define CH3 OCAL MSB register mask.
#define CH3_OCAL_LSB_ADDRESS ((uint8_t) 0x1A)
Define CH3 OCAL LSB register Address.
#define CH3_OCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH3 OCAL LSB register default.
#define CH3_OCAL_LSB_OCAL3_LSB_MASK ((uint16_t) 0xFF00)
Define CH3 OCAL LSB register mask.
#define CH3_OCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH3 OCAL LSB register reserved mask.
#define CH3_GCAL_MSB_ADDRESS ((uint8_t) 0x1B)
Define CH3 GCAL MSB register Address.
#define CH3_GCAL_MSB_DEFAULT ((uint16_t) 0x8000)
Define CH3 GCAL MSB register default.
#define CH3_GCAL_MSB_GCAL3_MSB_MASK ((uint16_t) 0xFFFF)
Define CH3 GCAL MSB register mask.
#define CH3_GCAL_LSB_ADDRESS ((uint8_t) 0x1C)
Define CH3 GCAL LSB register Address.
#define CH3_GCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH3 GCAL MSB register default.
#define CH3_GCAL_LSB_GCAL3_LSB_MASK ((uint16_t) 0xFF00)
Define CH3 GCAL MSB register mask.
#define CH3_GCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH3 GCAL MSB register reserved mask.
#define CH4_CFG_ADDRESS ((uint8_t) 0x1D)
Define CH4 CFG register Address.
#define CH4_CFG_DEFAULT ((uint16_t) 0x0000)
Define CH4 CFG register default.
#define CH4_CFG_PHASE4_MASK ((uint16_t) 0xFFC0)
Define CH4 CFG register phase 4 mask.
#define CH4_CFG_RESERVED0_MASK ((uint16_t) 0x003C)
Define CH4 CFG register reserved mask.
#define CH4_CFG_MUX4_MASK ((uint16_t) 0x0003)
Define CH4 CFG register mux4 mask.
#define CH4_CFG_MUX4_AIN4P_AIN4N ((uint16_t) 0x0000 << 0) /* DEFAULT */
Define CH4 CFG register mux4 AIN4P_AIN4N.
#define CH4_CFG_MUX4_ADC_INPUT_SHORT ((uint16_t) 0x0001 << 0)
Define CH4 CFG register mux4 adc input short.
#define CH4_CFG_MUX4_DC_DIAGNOSTIC ((uint16_t) 0x0002 << 0)
Define CH4 CFG register mux4 dc diagnostic.
#define CH4_CFG_MUX4_AC_DIAGNOSTIC ((uint16_t) 0x0003 << 0)
Define CH4 CFG register mux4 ac diagnostic.
#define CH4_OCAL_MSB_ADDRESS ((uint8_t) 0x1E)
Define CH4 OCAL MSB register Address.
#define CH4_OCAL_MSB_DEFAULT ((uint16_t) 0x0000)
Define CH4 OCAL MSB register default.
#define CH4_OCAL_MSB_OCAL4_MSB_MASK ((uint16_t) 0xFFFF)
Define CH4 OCAL MSB register mask.
#define CH4_OCAL_LSB_ADDRESS ((uint8_t) 0x1F)
Define CH4 OCAL LSB register Address.
#define CH4_OCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH4 OCAL LSB register default.
#define CH4_OCAL_LSB_OCAL4_LSB_MASK ((uint16_t) 0xFF00)
Define CH4 OCAL LSB register mask.
#define CH4_OCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH4 OCAL LSB register reserved mask.
#define CH4_GCAL_MSB_ADDRESS ((uint8_t) 0x20)
Define CH4 GCAL MSB register Address.
#define CH4_GCAL_MSB_DEFAULT ((uint16_t) 0x8000)
Define CH4 GCAL MSB register default.
#define CH4_GCAL_MSB_GCAL4_MSB_MASK ((uint16_t) 0xFFFF)
Define CH4 GCAL MSB register mask.
#define CH4_GCAL_LSB_ADDRESS ((uint8_t) 0x21)
Define CH4 GCAL LSB register Address.
#define CH4_GCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH4 GCAL LSB register default.
#define CH4_GCAL_LSB_GCAL4_LSB_MASK ((uint16_t) 0xFF00)
Define CH4 GCAL LSB register mask.
#define CH4_GCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH4 GCAL LSB register reserved mask.
#define CH5_CFG_ADDRESS ((uint8_t) 0x22)
Define CH5 CFG register Address.
#define CH5_CFG_DEFAULT ((uint16_t) 0x0000)
Define CH5 CFG register default.
#define CH5_CFG_PHASE5_MASK ((uint16_t) 0xFFC0)
Define CH5 CFG register mask.
#define CH5_CFG_RESERVED0_MASK ((uint16_t) 0x003C)
Define CH5 CFG register reserved mask.
#define CH5_CFG_MUX5_MASK ((uint16_t) 0x0003)
Define CH5 CFG register MUX5 mask.
#define CH5_CFG_MUX5_AIN5P_AIN5N ((uint16_t) 0x0000 << 0) /* DEFAULT */
Define CH5 CFG register MUX5 AIN5P_AIN5N.
#define CH5_CFG_MUX5_ADC_INPUT_SHORT ((uint16_t) 0x0001 << 0)
Define CH5 CFG register MUX5 adc input short.
#define CH5_CFG_MUX5_DC_DIAGNOSTIC ((uint16_t) 0x0002 << 0)
Define CH5 CFG register MUX5 dc diagnostic.
#define CH5_CFG_MUX5_AC_DIAGNOSTIC ((uint16_t) 0x0003 << 0)
Define CH5 CFG register MUX5 ac diagnostic.
#define CH5_OCAL_MSB_ADDRESS ((uint8_t) 0x23)
Define CH5 OCAL MSB register Address.
#define CH5_OCAL_MSB_DEFAULT ((uint16_t) 0x0000)
Define CH5 OCAL MSB register default.
#define CH5_OCAL_MSB_OCAL5_MSB_MASK ((uint16_t) 0xFFFF)
Define CH5 OCAL MSB register mask.
#define CH5_OCAL_LSB_ADDRESS ((uint8_t) 0x24)
Define CH5 OCAL LSB register Address.
#define CH5_OCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH5 OCAL LSB register default.
#define CH5_OCAL_LSB_OCAL5_LSB_MASK ((uint16_t) 0xFF00)
Define CH5 OCAL LSB register mask.
#define CH5_OCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH5 OCAL LSB register reserved mask.
#define CH5_GCAL_MSB_ADDRESS ((uint8_t) 0x25)
Define CH5 GCAL MSB register Address.
#define CH5_GCAL_MSB_DEFAULT ((uint16_t) 0x8000)
Define CH5 GCAL MSB register default.
#define CH5_GCAL_MSB_GCAL5_MSB_MASK ((uint16_t) 0xFFFF)
Define CH5 GCAL MSB register mask.
#define CH5_GCAL_LSB_ADDRESS ((uint8_t) 0x26)
Define CH5 GCAL LSB register Address.
#define CH5_GCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH5 GCAL LSB register default.
#define CH5_GCAL_LSB_GCAL5_LSB_MASK ((uint16_t) 0xFF00)
Define CH5 GCAL LSB register mask.
#define CH5_GCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH5 GCAL LSB register reserved mask.
#define CH6_CFG_ADDRESS ((uint8_t) 0x27)
Define CH6 CFG register Address.
#define CH6_CFG_DEFAULT ((uint16_t) 0x0000)
Define CH6 CFG register defaults.
#define CH6_CFG_PHASE6_MASK ((uint16_t) 0xFFC0)
Define CH6 CFG register phase6 mask.
#define CH6_CFG_RESERVED0_MASK ((uint16_t) 0x003C)
Define CH6 CFG register reserved mask.
#define CH6_CFG_MUX6_MASK ((uint16_t) 0x0003)
Define CH6 CFG register MUX6 mask.
#define CH6_CFG_MUX6_AIN6P_AIN6N ((uint16_t) 0x0000 << 0) /* DEFAULT */
Define CH6 CFG register MUX6 AIN6P_AIN6N.
#define CH6_CFG_MUX6_ADC_INPUT_SHORT ((uint16_t) 0x0001 << 0)
Define CH6 CFG register MUX6 adc input short.
#define CH6_CFG_MUX6_DC_DIAGNOSTIC ((uint16_t) 0x0002 << 0)
Define CH6 CFG register MUX6 dc diagnostic.
#define CH6_CFG_MUX6_AC_DIAGNOSTIC ((uint16_t) 0x0003 << 0)
Define CH6 CFG register MUX6 ac diagnostic.
#define CH6_OCAL_MSB_ADDRESS ((uint8_t) 0x28)
Define CH6 OCAL MSB register Address.
#define CH6_OCAL_MSB_DEFAULT ((uint16_t) 0x0000)
Define CH6 OCAL MSB register default.
#define CH6_OCAL_MSB_OCAL6_MSB_MASK ((uint16_t) 0xFFFF)
Define CH6 OCAL MSB register mask.
#define CH6_OCAL_LSB_ADDRESS ((uint8_t) 0x29)
Define CH6 OCAL LSB register Address.
#define CH6_OCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH6 OCAL LSB register default.
#define CH6_OCAL_LSB_OCAL6_LSB_MASK ((uint16_t) 0xFF00)
Define CH6 OCAL LSB register mask.
#define CH6_OCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH6 OCAL LSB register reserved mask.
#define CH6_GCAL_MSB_ADDRESS ((uint8_t) 0x2A)
Define CH6 GCAL MSB register Address.
#define CH6_GCAL_MSB_DEFAULT ((uint16_t) 0x8000)
Define CH6 GCAL MSB register default.
#define CH6_GCAL_MSB_GCAL6_MSB_MASK ((uint16_t) 0xFFFF)
Define CH6 GCAL MSB register mask.
#define CH6_GCAL_LSB_ADDRESS ((uint8_t) 0x2B)
Define CH6 GCAL LSB register Address.
#define CH6_GCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH6 GCAL LSB register default.
#define CH6_GCAL_LSB_GCAL6_LSB_MASK ((uint16_t) 0xFF00)
Define CH6 GCAL LSB register mask.
#define CH6_GCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH6 GCAL LSB register reserved mask.
#define CH7_CFG_ADDRESS ((uint8_t) 0x2C)
Define CH7 CFG register Address.
#define CH7_CFG_DEFAULT ((uint16_t) 0x0000)
Define CH7 CFG register default.
#define CH7_CFG_PHASE7_MASK ((uint16_t) 0xFFC0)
Define CH7 CFG register phase7 mask.
#define CH7_CFG_RESERVED0_MASK ((uint16_t) 0x003C)
Define CH7 CFG register reserved mask.
#define CH7_CFG_MUX7_MASK ((uint16_t) 0x0003)
Define CH7 CFG register MUX7 mask.
#define CH7_CFG_MUX7_AIN7P_AIN7N ((uint16_t) 0x0000 << 0) /* DEFAULT */
Define CH7 CFG register MUX7 AIN7P_AIN7N.
#define CH7_CFG_MUX7_ADC_INPUT_SHORT ((uint16_t) 0x0001 << 0)
Define CH7 CFG register MUX7 adc input short.
#define CH7_CFG_MUX7_DC_DIAGNOSTIC ((uint16_t) 0x0002 << 0)
Define CH7 CFG register MUX7 dc diagnostic.
#define CH7_CFG_MUX7_AC_DIAGNOSTIC ((uint16_t) 0x0003 << 0)
Define CH7 CFG register MUX7 ac diagnostic.
#define CH7_OCAL_MSB_ADDRESS ((uint8_t) 0x2D)
Define CH7 OCAL MSB register Address.
#define CH7_OCAL_MSB_DEFAULT ((uint16_t) 0x0000)
Define CH7 OCAL MSB register default.
#define CH7_OCAL_MSB_OCAL7_MSB_MASK ((uint16_t) 0xFFFF)
Define CH7 OCAL MSB register mask.
#define CH7_OCAL_LSB_ADDRESS ((uint8_t) 0x2E)
Define CH7 OCAL LSB register Address.
#define CH7_OCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH7 OCAL LSB register default.
#define CH7_OCAL_LSB_OCAL7_LSB_MASK ((uint16_t) 0xFF00)
Define CH7 OCAL LSB register mask.
#define CH7_OCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH7 OCAL LSB register reserved mask.
#define CH7_GCAL_MSB_ADDRESS ((uint8_t) 0x2F)
Define CH7 GCAL MSB register Address.
#define CH7_GCAL_MSB_DEFAULT ((uint16_t) 0x8000)
Define CH7 GCAL MSB register default.
#define CH7_GCAL_MSB_GCAL7_MSB_MASK ((uint16_t) 0xFFFF)
Define CH7 GCAL MSB register mask.
#define CH7_GCAL_LSB_ADDRESS ((uint8_t) 0x30)
Define CH7 GCAL LSB register Address.
#define CH7_GCAL_LSB_DEFAULT ((uint16_t) 0x0000)
Define CH7 GCAL LSB register default.
#define CH7_GCAL_LSB_GCAL7_LSB_MASK ((uint16_t) 0xFF00)
Define CH7 GCAL LSB register mask.
#define CH7_GCAL_LSB_RESERVED0_MASK ((uint16_t) 0x00FF)
Define CH7 GCAL LSB register reserved mask.
#define REGMAP_DCDC_ADDRESS ((uint8_t) 0x31)
Define Regmap DC-DC register Address.
#define REGMAP_DCDC_DEFAULT ((uint16_t) 0x0000)
Define Regmap DC-DC register default.
#define REGMAP_DCDC_RESERVED_MASK ((uint16_t) 0xF0FE)
Define Regmap DC-DC register reserved mask.
#define STATUS_DCDC_MASK ((uint16_t) 0x0001)
Define Regmap DC-DC register status mask.
#define STATUS_DCDC_OFF ((uint16_t) 0x0000 << 0)
Define Regmap DC-DC register status off.
#define STATUS_DCDC_EN ((uint16_t) 0x0001 << 0)
Define Regmap DC-DC register status enable.
#define REGMAP_DCDC_FREQ_MASK ((uint16_t) 0x0F00)
Define Regmap DC-DC register frequency mask.
#define FREQ_0 ((uint16_t) 0x0000 << 8) /* DEFAULT */
Define Regmap DC-DC register frequency 0.
#define FREQ_1 ((uint16_t) 0x0001 << 8)
Define Regmap DC-DC register frequency 1.
#define FREQ_2 ((uint16_t) 0x0002 << 8)
Define Regmap DC-DC register frequency 2.
#define FREQ_3 ((uint16_t) 0x0003 << 4)
Define Regmap DC-DC register frequency 3.
#define FREQ_4 ((uint16_t) 0x0004 << 4)
Define Regmap DC-DC register frequency 4.
#define FREQ_5 ((uint16_t) 0x0005 << 4)
Define Regmap DC-DC register frequency 5.
#define FREQ_6 ((uint16_t) 0x0006 << 4)
Define Regmap DC-DC register frequency 6.
#define FREQ_7 ((uint16_t) 0x0007 << 4)
Define Regmap DC-DC register frequency 7.
#define FREQ_8 ((uint16_t) 0x0008 << 4)
Define Regmap DC-DC register frequency 8.
#define FREQ_9 ((uint16_t) 0x0009 << 8)
Define Regmap DC-DC register frequency 9.
#define FREQ_10 ((uint16_t) 0x000a << 8)
Define Regmap DC-DC register frequency 10.
#define FREQ_11 ((uint16_t) 0x000b << 8)
Define Regmap DC-DC register frequency 11.
#define FREQ_12 ((uint16_t) 0x000c << 4)
Define Regmap DC-DC register frequency 12.
#define FREQ_13 ((uint16_t) 0x000d << 4)
Define Regmap DC-DC register frequency 13.
#define FREQ_14 ((uint16_t) 0x000e << 4)
Define Regmap DC-DC register frequency 14.
#define FREQ_15 ((uint16_t) 0x000f << 4)
Define Regmap DC-DC register frequency 15.
#define REGMAP_CRC_ADDRESS ((uint8_t) 0x3E)
Define REGMAP CRC register Address.
#define REGMAP_CRC_DEFAULT ((uint16_t) 0x0000)
Define REGMAP CRC register default.
#define REGMAP_CRC_REG_CRC_MASK ((uint16_t) 0xFFFF)
Define REGMAP CRC register mask.
#define CHANCNT(x) ((uint8_t) ((getRegisterValue(ID_ADDRESS, x) & ID_CHANCNT_MASK) >> 8))
Return channel count.
#define REVISION_ID(x) ((uint8_t) ((getRegisterValue(ID_ADDRESS, x) & ID_REVID_MASK) >> 0))
Return revID.
#define SPI_LOCKED(x) ((bool) (getRegisterValue(STATUS_ADDRESS, x) & STATUS_LOCK_LOCKED))
Return SPI locked.
#define WLENGTH(x) ((uint8_t) ((getRegisterValue(MODE_ADDRESS, x) & STATUS_WLENGTH_MASK) >> 8))
Return word length.
#define REGMAP_CRC_ENABLED(x) ((bool) (getRegisterValue(MODE_ADDRESS, x) & MODE_REG_CRC_EN_ENABLED))
Return CRC status.
#define SPI_CRC_ENABLED(x) ((bool) (getRegisterValue(MODE_ADDRESS, x) & MODE_RX_CRC_EN_ENABLED))
Return SPI CRC status.
#define SPI_CRC_TYPE(x) ((bool) (getRegisterValue(MODE_ADDRESS, x) & MODE_CRC_TYPE_MASK))
Return CRC type.
#define OSR_INDEX(x) ((uint8_t) ((getRegisterValue(CLOCK_ADDRESS, x) & CLOCK_OSR_MASK) >> 2))
Return OSR index.
#define POWER_MODE(x) ((uint8_t) ((getRegisterValue(CLOCK_ADDRESS, x) & CLOCK_PWR_MASK) >> 0))
Return power mode.
Enumerations
enum AMC_CRC_TYPE {
AMC_CRC_TYPE_CCITT = 0,
AMC_CRC_TYPE_ANSI
}
enum AMC_CRC {
AMC_CRC_DISABLE = 0,
AMC_CRC_ENABLE
}
enum AMC_OPCODES {
AMC_OPCODE_NULL = 0x0000,
AMC_OPCODE_RESET = 0x0011,
AMC_OPCODE_STANDBY = 0x0022,
AMC_OPCODE_WAKEUP = 0x0033,
AMC_OPCODE_LOCK = 0x0555,
AMC_OPCODE_UNLOCK = 0x0655,
AMC_OPCODE_RREG = 0xA000,
AMC_OPCODE_WREG = 0x6000
}
Functions
bool AMC131M02_init (volatile AMC_Instance *amcHandle)
Initialize AMC131M02 Registers.
bool AMC131M03_init (volatile AMC_Instance *amcHandle)
Initialize AMC131M03 Registers.
bool AMC_writeSingleSPIReg (volatile AMC_Instance *amcHandle, uint8_t regAddr, uint16_t data, bool readCheck)
Write to a single register.
uint16_t AMC_readSingleSPIReg (volatile AMC_Instance *amcHandle, uint8_t regAddr)
Read a single register.
void AMC_resetDevice (volatile AMC_Instance *amcHandle)
Reset AMC.
bool AMC_lockRegisters (volatile AMC_Instance *amcHandle)
Lock AMC Registers.
bool AMC_unlockRegisters (volatile AMC_Instance *amcHandle)
Unlock AMC Registers.
void AMC_standbymode (volatile AMC_Instance *amcHandle)
AMC standby mode.
void AMC_wakeupCommand (volatile AMC_Instance *amcHandle)
Wakeup AMC.
void AMC_reset (volatile AMC_Instance *amcHandle)
Reset AMC.
void AMC_toggleSYNC (volatile AMC_Instance *amcHandle)
Sync AMC.
void AMC_startDataCollection (volatile AMC_Instance *amcHandle)
Start Data Collection.
void AMC_startDMADataTransfer (volatile AMC_Instance *amcHandle)
Start DMA Transfer.
void AMC_getChannelData (volatile AMC_Instance *amcHandle)
Get AMC Channel Data.
void AMC_initalizeAMCRegisters (volatile AMC_Instance *amcHandle)
Initialize AMC Registers.
void AMC_verifyAMCCRC (volatile AMC_Instance *amcHandle, volatile AMC_channelData *amcData)
verify CRC for channel data
void AMC_checkStatusRegister (volatile AMC_Errors error, uint16_t data)
check status registers for faults
Detailed Description
Enumeration Type Documentation
AMC_CRC_TYPE
enum AMC_CRC_TYPE
Enumerator
AMC_CRC_TYPE_CCITT
AMC CRC type CCITT.
AMC_CRC_TYPE_ANSI
AMC CRC type ANSI.
AMC_CRC
enum AMC_CRC
Enumerator
AMC_CRC_DISABLE
AMC CRC disable.
AMC_CRC_ENABLE
AMC CRC enable.
AMC_OPCODES
enum AMC_OPCODES
;
Enumerator
AMC_OPCODE_NULL
opcode to read status register
AMC_OPCODE_RESET
opcode to reset AMC
AMC_OPCODE_STANDBY
opcode to set AMC in standby mode
AMC_OPCODE_WAKEUP
opcode to wakeup the AMC
AMC_OPCODE_LOCK
opcode to lock AMC
AMC_OPCODE_UNLOCK
opcode to unlock AMC
AMC_OPCODE_RREG
opcode to read AMC registers
AMC_OPCODE_WREG
opcode to write AMC registers
Function Documentation
AMC131M02_init()
bool AMC131M02_init (volatile AMC_Instance * amcHandle)
Initialize AMC131M02 Registers.
Parameters
[in] amcHandle The AMC Instance
Returns
status
References AMC131M02_CFG_ADDRESS_DATA, AMC131M02_CH0_CFG_ADDRESS_DATA, AMC131M02_CH0_GCAL_LSB_ADDRESS_DATA, AMC131M02_CH0_GCAL_MSB_ADDRESS_DATA, AMC131M02_CH0_OCAL_LSB_ADDRESS_DATA, AMC131M02_CH0_OCAL_MSB_ADDRESS_DATA, AMC131M02_CH1_CFG_ADDRESS_DATA, AMC131M02_CH1_GCAL_LSB_ADDRESS_DATA, AMC131M02_CH1_GCAL_MSB_ADDRESS_DATA, AMC131M02_CH1_OCAL_LSB_ADDRESS_DATA, AMC131M02_CH1_OCAL_MSB_ADDRESS_DATA, AMC131M02_CLOCK_ADDRESS_DATA, AMC131M02_DCD_CTRL_REGISTER, AMC131M02_GAIN1_ADDRESS_DATA, AMC131M02_MODE_ADDRESS_DATA, AMC_unlockRegisters(), AMC_writeSingleSPIReg(), CFG_ADDRESS, CH0_CFG_ADDRESS, CH0_GCAL_LSB_ADDRESS, CH0_GCAL_MSB_ADDRESS, CH0_OCAL_LSB_ADDRESS, CH0_OCAL_MSB_ADDRESS, CH1_CFG_ADDRESS, CH1_GCAL_LSB_ADDRESS, CH1_GCAL_MSB_ADDRESS, CH1_OCAL_LSB_ADDRESS, CH1_OCAL_MSB_ADDRESS, CLOCK_ADDRESS, GAIN1_ADDRESS, MODE_ADDRESS, REGMAP_DCDC_ADDRESS, and TRUE.
AMC131M03_init()
bool AMC131M03_init (volatile AMC_Instance * amcHandle)
Initialize AMC131M03 Registers.
Parameters
[in] amcHandle The AMC Instance
Returns
status
References AMC131M03_CFG_ADDRESS_DATA, AMC131M03_CH0_CFG_ADDRESS_DATA, AMC131M03_CH0_GCAL_LSB_ADDRESS_DATA, AMC131M03_CH0_GCAL_MSB_ADDRESS_DATA, AMC131M03_CH0_OCAL_LSB_ADDRESS_DATA, AMC131M03_CH0_OCAL_MSB_ADDRESS_DATA, AMC131M03_CH1_CFG_ADDRESS_DATA, AMC131M03_CH1_GCAL_LSB_ADDRESS_DATA, AMC131M03_CH1_GCAL_MSB_ADDRESS_DATA, AMC131M03_CH1_OCAL_LSB_ADDRESS_DATA, AMC131M03_CH1_OCAL_MSB_ADDRESS_DATA, AMC131M03_CH2_CFG_ADDRESS_DATA, AMC131M03_CH2_GCAL_LSB_ADDRESS_DATA, AMC131M03_CH2_GCAL_MSB_ADDRESS_DATA, AMC131M03_CH2_OCAL_LSB_ADDRESS_DATA, AMC131M03_CH2_OCAL_MSB_ADDRESS_DATA, AMC131M03_CLOCK_ADDRESS_DATA, AMC131M03_DCD_CTRL_REGISTER, AMC131M03_GAIN1_ADDRESS_DATA, AMC131M03_MODE_ADDRESS_DATA, AMC_unlockRegisters(), AMC_writeSingleSPIReg(), CFG_ADDRESS, CH0_CFG_ADDRESS, CH0_GCAL_LSB_ADDRESS, CH0_GCAL_MSB_ADDRESS, CH0_OCAL_LSB_ADDRESS, CH0_OCAL_MSB_ADDRESS, CH1_CFG_ADDRESS, CH1_GCAL_LSB_ADDRESS, CH1_GCAL_MSB_ADDRESS, CH1_OCAL_LSB_ADDRESS, CH1_OCAL_MSB_ADDRESS, CH2_CFG_ADDRESS, CH2_GCAL_LSB_ADDRESS, CH2_GCAL_MSB_ADDRESS, CH2_OCAL_LSB_ADDRESS, CH2_OCAL_MSB_ADDRESS, CLOCK_ADDRESS, GAIN1_ADDRESS, MODE_ADDRESS, REGMAP_DCDC_ADDRESS, and TRUE.
AMC_writeSingleSPIReg()
bool AMC_writeSingleSPIReg (volatile AMC_Instance * amcHandle, uint8_t regAddr, uint16_t data, bool readCheck)
Write to a single register.
Parameters
[in] amcHandle The AMC Instance
[in] regAddr The register address
[in] data Data to be written
[in] readCheck write check
Returns
Write status
References AMC_BYTELENGTH, AMC_DMA_TRANSFER_DONE, AMC_DMA_TRANSFER_READY, AMC_DMA_WAITING, AMC_OPCODE_WREG, AMC_readSingleSPIReg(), AMC_Instance::DMAStatus, AMC_Instance::DMAWait, HAL_startSPIDataTransfer(), AMC_Instance::spiChan, and AMC_Instance::spiCs.
Referenced by AMC131M02_init(), and AMC131M03_init().
AMC_readSingleSPIReg()
uint16_t AMC_readSingleSPIReg (volatile AMC_Instance * amcHandle, uint8_t regAddr)
Read a single register.
Parameters
[in] amcHandle The AMC Instance
[in] regAddr The register address
Returns
Register Data
References AMC_BYTELENGTH, AMC_DMA_TRANSFER_DONE, AMC_DMA_TRANSFER_READY, AMC_DMA_WAITING, AMC_OPCODE_RREG, AMC_Instance::DMAStatus, AMC_Instance::DMAWait, HAL_startSPIDataTransfer(), AMC_Instance::spiChan, and AMC_Instance::spiCs.
Referenced by AMC_lockRegisters(), AMC_unlockRegisters(), and AMC_writeSingleSPIReg().
AMC_resetDevice()
void AMC_resetDevice (volatile AMC_Instance * amcHandle)
Reset AMC.
Parameters
[in] amcHandle The AMC Instance
References AMC_BYTELENGTH, AMC_DMA_TRANSFER_DONE, AMC_DMA_TRANSFER_READY, AMC_DMA_WAITING, AMC_OPCODE_RESET, AMC_Instance::DMAStatus, AMC_Instance::DMAWait, HAL_startSPIDataTransfer(), AMC_Instance::spiChan, and AMC_Instance::spiCs.
AMC_lockRegisters()
bool AMC_lockRegisters (volatile AMC_Instance * amcHandle)
Lock AMC Registers.
Parameters
[in] amcHandle The AMC Instance
Returns
Register status
References AMC_BYTELENGTH, AMC_DMA_TRANSFER_DONE, AMC_DMA_TRANSFER_READY, AMC_DMA_WAITING, AMC_OPCODE_LOCK, AMC_readSingleSPIReg(), AMC_Instance::DMAStatus, AMC_Instance::DMAWait, HAL_startSPIDataTransfer(), AMC_Instance::spiChan, AMC_Instance::spiCs, STATUS_ADDRESS, and STATUS_LOCK_MASK.
AMC_unlockRegisters()
bool AMC_unlockRegisters (volatile AMC_Instance * amcHandle)
Unlock AMC Registers.
Parameters
[in] amcHandle The AMC Instance
Returns
Register status
References AMC_BYTELENGTH, AMC_DMA_TRANSFER_DONE, AMC_DMA_TRANSFER_READY, AMC_DMA_WAITING, AMC_OPCODE_UNLOCK, AMC_readSingleSPIReg(), AMC_Instance::DMAStatus, AMC_Instance::DMAWait, HAL_startSPIDataTransfer(), AMC_Instance::spiChan, AMC_Instance::spiCs, STATUS_ADDRESS, and STATUS_LOCK_MASK.
Referenced by AMC131M02_init(), and AMC131M03_init().
AMC_standbymode()
void AMC_standbymode (volatile AMC_Instance * amcHandle)
AMC standby mode.
Parameters
[in] amcHandle The AMC Instance
References AMC_BYTELENGTH, AMC_DMA_TRANSFER_DONE, AMC_DMA_TRANSFER_READY, AMC_DMA_WAITING, AMC_OPCODE_STANDBY, AMC_Instance::DMAStatus, AMC_Instance::DMAWait, HAL_startSPIDataTransfer(), AMC_Instance::spiChan, and AMC_Instance::spiCs.
AMC_wakeupCommand()
void AMC_wakeupCommand (volatile AMC_Instance * amcHandle)
Wakeup AMC.
Parameters
[in] amcHandle The AMC Instance
References AMC_BYTELENGTH, AMC_DMA_TRANSFER_DONE, AMC_DMA_TRANSFER_READY, AMC_DMA_WAITING, AMC_OPCODE_WAKEUP, AMC_Instance::DMAStatus, AMC_Instance::DMAWait, HAL_startSPIDataTransfer(), AMC_Instance::spiChan, and AMC_Instance::spiCs.
AMC_reset()
void AMC_reset (volatile AMC_Instance * amcHandle)
Reset AMC.
Parameters
[in] amcHandle The AMC Instance
References AMC_RESET_US, AMC_WAKEUP_US, HAL_delayMicroSeconds(), HAL_GPIO_PIN_HIGH, HAL_GPIO_PIN_LOW, HAL_writeGPIOPin(), and AMC_Instance::sync.
AMC_toggleSYNC()
void AMC_toggleSYNC (volatile AMC_Instance * amcHandle)
Sync AMC.
Parameters
[in] amcHandle The AMC Instance
References AMC_SYNC_US, HAL_delayMicroSeconds(), HAL_GPIO_PIN_HIGH, HAL_GPIO_PIN_LOW, HAL_writeGPIOPin(), and AMC_Instance::sync.
Referenced by AMC_startDataCollection().
AMC_startDataCollection()
void AMC_startDataCollection (volatile AMC_Instance * amcHandle)
Start Data Collection.
Parameters
[in] amcHandle The AMC Instance
References AMC_toggleSYNC(), AMC_Instance::datacollectionStatus, HAL_enableGPIOInterrupt(), and AMC_Instance::ready.
AMC_startDMADataTransfer()
void AMC_startDMADataTransfer (volatile AMC_Instance * amcHandle)
Start DMA Transfer.
Parameters
[in] amcHandle The AMC Instance
References AMC_BYTELENGTH, HAL_startSPIDataTransfer(), AMC_Instance::rawdata, AMC_Instance::spiChan, and AMC_Instance::spiCs.
AMC_getChannelData()
void AMC_getChannelData (volatile AMC_Instance * amcHandle)
Get AMC Channel Data.
Parameters
[in] amcHandle The AMC Instance
References AMC_CHANNELCOUNT, AMC_checkStatusRegister(), AMC_CMDLENGTH, AMC_verifyAMCCRC(), AMC_channelData::chan0, AMC_channelData::chan1, AMC_channelData::chan2, AMC_channelData::chan3, AMC_channelData::chan4, AMC_channelData::chan5, AMC_channelData::chan6, AMC_channelData::chan7, AMC_Instance::channelData, AMC_channelData::crc, AMC_Instance::errors, AMC_Instance::rawdata, and AMC_channelData::response.
AMC_initalizeAMCRegisters()
void AMC_initalizeAMCRegisters (volatile AMC_Instance * amcHandle)
Initialize AMC Registers.
Parameters
[in] amcHandle The AMC Instance
References AMC_DMA_TRANSFER_DONE, AMC_DMA_TRANSFER_READY, AMC_DMA_WAITING, AMC_Instance::AMC_initRegData, AMC_Instance::DMAStatus, AMC_Instance::DMAWait, HAL_startSPIDataTransfer(), NUM_REGISTERS, AMC_Instance::spiChan, and AMC_Instance::spiCs.
AMC_verifyAMCCRC()
void AMC_verifyAMCCRC (volatile AMC_Instance * amcHandle, volatile AMC_channelData * amcData)
verify CRC for channel data
Parameters
[in] amcHandle The AMC Instance
[in] amcData The AMC channel data
References AMC_CHANNELCOUNT, AMC_CMDLENGTH, AMC_channelData::crc, CRC_IN_ADDRESS, AMC_Instance::crcFailCount, AMC_Instance::crcFailFlag, AMC_Instance::crcPassCount, FALSE, HAL_CRC_0, HAL_getCRCOut(), HAL_setCRCSeed(), AMC_Instance::rawdata, and TRUE.
Referenced by AMC_getChannelData().
AMC_checkStatusRegister()
void AMC_checkStatusRegister (volatile AMC_Errors error, uint16_t data)
check status registers for faults
Parameters
[in] error The AMC errors
[in] data status register data
References AMC_Errors::crcErrorCount, AMC_Errors::fResyncCount, AMC_Errors::fuseFailCount, AMC_Errors::regMapCount, AMC_Errors::resetCount, AMC_Errors::rstAckCount, AMC_Errors::rstnAckCount, AMC_Errors::secFailCount, AMC_Errors::secFailStrike, STATUS_CRC_ERR_MASK, STATUS_F_RESYNC_MASK, STATUS_FUSE_FAIL_MASK, STATUS_REG_MAP_MASK, STATUS_RESET_MASK, STATUS_SEC_FAIL_MASK, and AMC_Errors::totalComparisions.
Referenced by AMC_getChannelData().
Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale