MSPM0Lxx2xEnergyMetrology: ENERGY_LIBRARY_M0L2228_HAL
ENERGY_LIBRARY_M0L2228_HAL
Data Structures
struct HAL_GPIO_Instance_
Defines a GPIO instance.
struct HAL_SPIInstance_
Defines a SPI instance.
struct HAL_UARTInstance_
Defines a UART instance.
struct HAL_LCDInstance_
Defines a LCD instance.
struct HAL_CRCInstance_
Defines a CRC instance.
Macros
#define TRUE 0x1
Define 1.
#define FALSE 0x0
Defines 0.
#define HAL_SYSTEM_FREQ_MHZ ((int32_t)32)
Defines the system clock frequency, MHz.
#define CRC_IN_ADDRESS 0x40441800
Defines CRC_IN memory address.
#define GEN_GPIO_OUT_PINO_01_PORT GEN_GPIO_OUT_PORT
Defines output port for pin 1.
#define GEN_GPIO_OUT_PINO_02_PORT GEN_GPIO_OUT_PORT
Defines output port for pin 2.
#define GEN_GPIO_OUT_PINO_03_PORT GEN_GPIO_OUT_PORT
Defines output port for pin 3.
#define GEN_GPIO_OUT_PINO_04_PORT GEN_GPIO_OUT_PORT
Defines output port for pin 4.
#define GEN_GPIO_IN_PINI_01_PORT GEN_GPIO_IN_PORT
Defines input port for pin 1.
#define GEN_GPIO_IN_PINI_02_PORT GEN_GPIO_IN_PORT
Defines input port for pin 2.
#define GEN_GPIO_IN_PINI_03_PORT GEN_GPIO_IN_PORT
Defines input port for pin 3.
#define GEN_GPIO_IN_PINI_04_PORT GEN_GPIO_IN_PORT
Defines input port for pin 4.
#define GEN_GPIO_IN_INT_IRQN GPIO_MULTIPLE_GPIOA_INT_IRQN
Defines the GPIO_IN IRQN.
#define GEN_GPIO_GROUP_A_IIDX GPIO_MULTIPLE_GPIOA_INT_IIDX
Defines the GPIO_A IIDX.
#define GEN_GPIO_GROUP_B_IIDX GPIO_GRP_0_GPIOB_INT_IIDX
Defines the GPIO_B IIDX.
#define GEN_GPIO_GROUP_A_IRQN GPIO_MULTIPLE_GPIOA_INT_IRQN
Defines the GPIO_A IRQN.
#define GEN_GPIO_GROUP_B_IRQN GPIO_GRP_0_GPIOB_INT_IRQN
Defines the GPIO_B IRQN.
Typedefs
typedef struct HAL_GPIO_Instance_ HAL_GPIOInstance
Defines a GPIO instance.
typedef struct HAL_SPIInstance_ HAL_SPIInstance
Defines a SPI instance.
typedef struct HAL_UARTInstance_ HAL_UARTInstance
Defines a UART instance.
typedef struct HAL_LCDInstance_ HAL_LCDInstance
Defines a LCD instance.
typedef struct HAL_CRCInstance_ HAL_CRCInstance
Defines a CRC instance.
Enumerations
enum HAL_MEMORY_BLOCK_STARTADDR { HAL_MEMORY_BLOCK_STARTADDR01 = 0x0003FC00 }
HAL_MEMORY_BLOCK_STARTADDR.
enum HAL_GPIO_STATE {
HAL_GPIO_PIN_LOW = 0,
HAL_GPIO_PIN_HIGH
}
HAL_GPIO_STATE.
enum HAL_GPIO_IN {
HAL_GPIO_IN_00 = 0,
HAL_GPIO_IN_01,
HAL_GPIO_IN_02,
HAL_GPIO_IN_03,
HAL_GPIO_IN_04,
HAL_GPIO_IN_MAX
}
HAL_GPIO_IN.
enum HAL_GPIO_OUT {
HAL_GPIO_OUT_00 = 0,
HAL_GPIO_OUT_01,
HAL_GPIO_OUT_02,
HAL_GPIO_OUT_03,
HAL_GPIO_OUT_MAX
}
HAL_GPIO_OUT.
enum HAL_SPI_CHAN {
HAL_SPI_CHAN_0 = 0,
HAL_SPI_CHAN_1,
HAL_SPI_CHAN_MAX
}
HAL_SPI_CHAN.
enum HAL_UART_CHAN {
HAL_UART_CHAN_0 = 0,
HAL_UART_CHAN_1,
HAL_UART_CHAN_MAX
}
HAL_UART_CHAN.
enum HAL_SPI_CS {
HAL_SPI_CS_0 = 0,
HAL_SPI_CS_1,
HAL_SPI_CS_2,
HAL_SPI_CS_3,
HAL_SPI_CS_MAX
}
HAL_SPI_CS.
enum HAL_DMA_CHAN {
HAL_DMA_CHAN_0 = DMA_CH0_CHAN_ID,
HAL_DMA_CHAN_1 = DMA_CH1_CHAN_ID,
HAL_DMA_CHAN_MAX
}
HAL_DMA_CHAN.
enum HAL_LCD_CHAN {
HAL_LCD_CHAN_0 = 0,
HAL_LCD_CHAN_MAX
}
HAL_LCD_CHAN.
enum HAL_CRC {
HAL_CRC_0 = 0,
HAL_CRC_MAX
}
HAL_CRC.
Functions
__STATIC_INLINE void HAL_delayMicroSeconds (uint32_t microSeconds)
Delays for specific time in microseconds.
void HAL_init ()
Initializes the hal object.
bool HAL_readGPIOPin (HAL_GPIO_IN pin)
reads a gpio
void HAL_writeGPIOPin (HAL_GPIO_OUT pin, HAL_GPIO_STATE pinState)
write to a gpio
void HAL_enableGPIOInterrupt (HAL_GPIO_IN pin)
enables GPIO Interrupt
uint32_t HAL_getGPIOEnabledInterruptStatus (HAL_GPIO_IN pin)
get gpio enabled interrupt status
void HAL_clearGPIOInterruptStatus (HAL_GPIO_IN pin)
clear gpio interrupt status
void HAL_startSPIDataTransfer (uint8_t dataTx[], volatile uint8_t dataRx[], uint8_t byteLength, HAL_SPI_CHAN chan, HAL_SPI_CS cs)
Start SPI data transfer through DMA.
void HAL_startUARTDMARecieve (HAL_UART_CHAN chan, uint8_t dataRx[], uint8_t byteLength)
Start UART Receive DMA.
void HAL_startUARTDMATransmit (HAL_UART_CHAN chan, uint8_t dataTx[], uint8_t byteLength)
Start UART Transmit DMA.
void HAL_clearMemoryBlock (HAL_MEMORY_BLOCK_STARTADDR startAddr)
clear Memory block
void HAL_secureMemoryBlock (HAL_MEMORY_BLOCK_STARTADDR startAddr)
secure Memory block
int HAL_copyMemoryBlock (void *dstAddr, void *srcAddr, int len, HAL_MEMORY_BLOCK_STARTADDR startAddr)
copy block data to flash
void HAL_getRTC (uint8_t buf[6])
Get real time clock.
void HAL_setRTC (const uint8_t buf[6])
Set real time clock.
uint16_t HAL_getCRCOut (HAL_CRC chan)
Get CRC out.
void HAL_setCRCSeed (HAL_CRC chan, uint16_t value)
Set CRC Seed.
uint32_t HAL_getLCDMemory (HAL_LCD_CHAN chan, uint32_t memIndex)
Get LCD memory.
void HAL_writeLCDMemory (HAL_LCD_CHAN chan, uint32_t memIndex, uint32_t mask)
write to LCD memory register
void HAL_enableUARTInterrupt (HAL_UART_CHAN Chan)
Enable UART interrupt.
Variables
HAL_GPIOInstance gpioInputPin [HAL_GPIO_IN_MAX]
Array for storing the input GPIO pin instances.
Detailed Description
Enumeration Type Documentation
HAL_MEMORY_BLOCK_STARTADDR
enum HAL_MEMORY_BLOCK_STARTADDR
HAL_MEMORY_BLOCK_STARTADDR.
Enumerator
HAL_MEMORY_BLOCK_STARTADDR01
Memory block start address.
HAL_GPIO_STATE
enum HAL_GPIO_STATE
HAL_GPIO_STATE.
Enumerator
HAL_GPIO_PIN_LOW
GPIO set to low.
HAL_GPIO_PIN_HIGH
GPIO set to high.
HAL_GPIO_IN
enum HAL_GPIO_IN
HAL_GPIO_IN.
Enumerator
HAL_GPIO_IN_00
Index associated to input GPIO PIN 0.
HAL_GPIO_IN_01
Index associated to input GPIO PIN 1.
HAL_GPIO_IN_02
Index associated to input GPIO PIN 2.
HAL_GPIO_IN_03
Index associated to input GPIO PIN 3.
HAL_GPIO_IN_04
Index associated to input GPIO PIN 4.
HAL_GPIO_IN_MAX
Total number of input GPIO pins.
HAL_GPIO_OUT
enum HAL_GPIO_OUT
HAL_GPIO_OUT.
Enumerator
HAL_GPIO_OUT_00
Index associated to output GPIO PIN 0.
HAL_GPIO_OUT_01
Index associated to output GPIO PIN 1.
HAL_GPIO_OUT_02
Index associated to output GPIO PIN 2.
HAL_GPIO_OUT_03
Index associated to output GPIO PIN 3.
HAL_GPIO_OUT_MAX
Total number of output GPIO pins.
HAL_SPI_CHAN
enum HAL_SPI_CHAN
HAL_SPI_CHAN.
Enumerator
HAL_SPI_CHAN_0
Index associated to SPI channel 0.
HAL_SPI_CHAN_1
Index associated to SPI channel 1.
HAL_SPI_CHAN_MAX
Total number of SPI channels.
HAL_UART_CHAN
enum HAL_UART_CHAN
HAL_UART_CHAN.
Enumerator
HAL_UART_CHAN_0
Index associated to UART channel 0.
HAL_UART_CHAN_1
Index associated to UART channel 1.
HAL_UART_CHAN_MAX
Total number of UART channels.
HAL_SPI_CS
enum HAL_SPI_CS
HAL_SPI_CS.
Enumerator
HAL_SPI_CS_0
Index associated to chip select 0.
HAL_SPI_CS_1
Index associated to chip select 0.
HAL_SPI_CS_2
Index associated to chip select 0.
HAL_SPI_CS_3
Index associated to chip select 0.
HAL_SPI_CS_MAX
Total number of chip select pins.
HAL_DMA_CHAN
enum HAL_DMA_CHAN
HAL_DMA_CHAN.
Enumerator
HAL_DMA_CHAN_0
Index associated to DMA Channel 0.
HAL_DMA_CHAN_1
Index associated to DMA Channel 1.
HAL_DMA_CHAN_MAX
Total number of DMA Channels.
HAL_LCD_CHAN
enum HAL_LCD_CHAN
HAL_LCD_CHAN.
Enumerator
HAL_LCD_CHAN_0
Index associated to LCD 0.
HAL_LCD_CHAN_MAX
Total number of LCDs.
HAL_CRC
enum HAL_CRC
HAL_CRC.
Enumerator
HAL_CRC_0
Index associated to CRC 0.
HAL_CRC_MAX
CRC count.
Function Documentation
HAL_delayMicroSeconds()
__STATIC_INLINE void HAL_delayMicroSeconds (uint32_t microSeconds)
Delays for specific time in microseconds.
Parameters
[in] microSeconds delayed time in microseconds
References HAL_clearGPIOInterruptStatus(), HAL_clearMemoryBlock(), HAL_copyMemoryBlock(), HAL_enableGPIOInterrupt(), HAL_enableUARTInterrupt(), HAL_getCRCOut(), HAL_getGPIOEnabledInterruptStatus(), HAL_getLCDMemory(), HAL_getRTC(), HAL_init(), HAL_readGPIOPin(), HAL_secureMemoryBlock(), HAL_setCRCSeed(), HAL_setRTC(), HAL_startSPIDataTransfer(), HAL_startUARTDMARecieve(), HAL_startUARTDMATransmit(), HAL_SYSTEM_FREQ_MHZ, HAL_writeGPIOPin(), HAL_writeLCDMemory(), and HAL_GPIO_Instance_::pin.
Referenced by ADS_reset(), ADS_toggleSYNC(), AMC_reset(), and AMC_toggleSYNC().
HAL_init()
void HAL_init ()
Initializes the hal object.
Initializes the hal object.
References HAL_SPIInstance_::dmaChanIdRx, HAL_UARTInstance_::dmaChanIdRx, HAL_SPIInstance_::dmaChanIdTx, HAL_UARTInstance_::dmaChanIdTx, GEN_GPIO_IN_INT_IRQN, GEN_GPIO_IN_PINI_01_PORT, GEN_GPIO_IN_PINI_02_PORT, GEN_GPIO_IN_PINI_03_PORT, GEN_GPIO_IN_PINI_04_PORT, GEN_GPIO_OUT_PINO_01_PORT, GEN_GPIO_OUT_PINO_02_PORT, GEN_GPIO_OUT_PINO_03_PORT, GEN_GPIO_OUT_PINO_04_PORT, HAL_CRC_0, HAL_GPIO_IN_00, HAL_GPIO_IN_01, HAL_GPIO_IN_02, HAL_GPIO_IN_03, HAL_GPIO_OUT_00, HAL_GPIO_OUT_01, HAL_GPIO_OUT_02, HAL_GPIO_OUT_03, HAL_LCD_CHAN_0, HAL_SPI_CHAN_0, HAL_SPI_CHAN_1, HAL_SPI_CS_0, HAL_SPI_CS_1, HAL_SPI_CS_2, HAL_SPI_CS_3, HAL_UART_CHAN_0, HAL_UART_CHAN_1, HAL_SPIInstance_::inst, HAL_UARTInstance_::inst, HAL_LCDInstance_::inst, HAL_CRCInstance_::inst, HAL_GPIO_Instance_::iomux, HAL_GPIO_Instance_::IRQn, HAL_GPIO_Instance_::pin, and HAL_GPIO_Instance_::port.
Referenced by HAL_delayMicroSeconds().
HAL_readGPIOPin()
bool HAL_readGPIOPin (HAL_GPIO_IN pin)
reads a gpio
Parameters
[in] pin gpiopin
Returns
status of pin
Referenced by HAL_delayMicroSeconds().
HAL_writeGPIOPin()
void HAL_writeGPIOPin (HAL_GPIO_OUT pin, HAL_GPIO_STATE pinState)
write to a gpio
Parameters
[in] pin gpiopin
[in] pinState pin state
References HAL_GPIO_PIN_HIGH, and HAL_GPIO_PIN_LOW.
Referenced by ADS_reset(), ADS_toggleSYNC(), AMC_reset(), AMC_toggleSYNC(), HAL_delayMicroSeconds(), and Metrology_ddsSinLookup().
HAL_enableGPIOInterrupt()
void HAL_enableGPIOInterrupt (HAL_GPIO_IN pin)
enables GPIO Interrupt
Parameters
[in] pin gpiopin
Referenced by ADS_startDataCollection(), AMC_startDataCollection(), and HAL_delayMicroSeconds().
HAL_getGPIOEnabledInterruptStatus()
uint32_t HAL_getGPIOEnabledInterruptStatus (HAL_GPIO_IN pin)
get gpio enabled interrupt status
Parameters
[in] pin gpiopin
Returns
gpio interrupt status
Referenced by HAL_delayMicroSeconds().
HAL_clearGPIOInterruptStatus()
void HAL_clearGPIOInterruptStatus (HAL_GPIO_IN pin)
clear gpio interrupt status
Parameters
[in] pin gpiopin
Referenced by HAL_delayMicroSeconds().
HAL_startSPIDataTransfer()
void HAL_startSPIDataTransfer (uint8_t dataTx[], volatile uint8_t dataRx[], uint8_t byteLength, HAL_SPI_CHAN chan, HAL_SPI_CS cs)
Start SPI data transfer through DMA.
Parameters
[in] dataTx[] The transfer data
[in] dataRx[] The receive data
[in] byteLength Number of bytes transfered
[in] chan The SPI channel
[in] cs The SPI Chip select pin
References HAL_SPIInstance_::dmaChanIdRx, HAL_SPIInstance_::dmaChanIdTx, and HAL_SPIInstance_::inst.
Referenced by ADS_initalizeADSRegisters(), ADS_lockRegisters(), ADS_readSingleSPIReg(), ADS_resetDevice(), ADS_standbymode(), ADS_startDMADataTransfer(), ADS_unlockRegisters(), ADS_wakeupCommand(), ADS_writeSingleSPIReg(), AMC_initalizeAMCRegisters(), AMC_lockRegisters(), AMC_readSingleSPIReg(), AMC_resetDevice(), AMC_standbymode(), AMC_startDMADataTransfer(), AMC_unlockRegisters(), AMC_wakeupCommand(), AMC_writeSingleSPIReg(), and HAL_delayMicroSeconds().
HAL_startUARTDMARecieve()
void HAL_startUARTDMARecieve (HAL_UART_CHAN chan, uint8_t dataRx[], uint8_t byteLength)
Start UART Receive DMA.
Parameters
[in] chan The UART channel
[in] dataRx[] Array to store received data
[in] byteLength Number of bytes transfered
References HAL_UARTInstance_::dmaChanIdRx, and HAL_UARTInstance_::inst.
Referenced by HAL_delayMicroSeconds().
HAL_startUARTDMATransmit()
void HAL_startUARTDMATransmit (HAL_UART_CHAN chan, uint8_t dataTx[], uint8_t byteLength)
Start UART Transmit DMA.
Parameters
[in] chan The UART channel
[in] dataTx[] The transmit data
[in] byteLength Number of bytes to transfer
References HAL_UARTInstance_::dmaChanIdTx, and HAL_UARTInstance_::inst.
Referenced by HAL_delayMicroSeconds().
HAL_clearMemoryBlock()
void HAL_clearMemoryBlock (HAL_MEMORY_BLOCK_STARTADDR startAddr)
clear Memory block
Parameters
[in] startAddr The start address of Memory block
Referenced by HAL_delayMicroSeconds(), Metrology_clearCalibrationData(), and Metrology_updateCalibrationData().
HAL_secureMemoryBlock()
void HAL_secureMemoryBlock (HAL_MEMORY_BLOCK_STARTADDR startAddr)
secure Memory block
Parameters
[in] startAddr The start address of Memory block
Referenced by HAL_delayMicroSeconds(), Metrology_clearCalibrationData(), and Metrology_updateCalibrationData().
HAL_copyMemoryBlock()
int HAL_copyMemoryBlock (void * dstAddr, void * srcAddr, int len, HAL_MEMORY_BLOCK_STARTADDR startAddr)
copy block data to flash
Parameters
[in] dstAddr The pointer to destination address
[in] srcAddr The pointer to source address
[in] len The length of data
[in] startAddr The start address of Memory block
Returns
status
Referenced by HAL_delayMicroSeconds(), Metrology_clearCalibrationData(), and Metrology_updateCalibrationData().
HAL_getRTC()
void HAL_getRTC (uint8_t buf[6])
Get real time clock.
Parameters
[in] buf[] buffer to store clock data
Referenced by HAL_delayMicroSeconds().
HAL_setRTC()
void HAL_setRTC (const uint8_t buf[6])
Set real time clock.
Parameters
[in] buf[] buffer to store clock data
Referenced by HAL_delayMicroSeconds().
HAL_getCRCOut()
uint16_t HAL_getCRCOut (HAL_CRC chan)
Get CRC out.
Parameters
[in] chan The CRC module
Returns
CRC data
References HAL_CRCInstance_::inst.
Referenced by ADS_verifyADSCRC(), AMC_verifyAMCCRC(), and HAL_delayMicroSeconds().
HAL_setCRCSeed()
void HAL_setCRCSeed (HAL_CRC chan, uint16_t value)
Set CRC Seed.
Parameters
[in] chan The CRC module
[in] value CRC SEED value
References HAL_CRCInstance_::inst.
Referenced by ADS_verifyADSCRC(), AMC_verifyAMCCRC(), and HAL_delayMicroSeconds().
HAL_getLCDMemory()
uint32_t HAL_getLCDMemory (HAL_LCD_CHAN chan, uint32_t memIndex)
Get LCD memory.
Parameters
[in] chan The LCD module
[in] memIndex Index of LCDMx register to read from.
Returns
32 bit LCDM register value
References HAL_LCDInstance_::inst.
Referenced by HAL_delayMicroSeconds(), LCD_clearCA(), LCD_clearDP(), LCD_showCA(), LCD_showChar(), and LCD_showDP().
HAL_writeLCDMemory()
void HAL_writeLCDMemory (HAL_LCD_CHAN chan, uint32_t memIndex, uint32_t mask)
write to LCD memory register
Parameters
[in] chan The LCD module
[in] memIndex Index of LCDMx register to write to
[in] mask LCDM register data
References HAL_LCDInstance_::inst.
Referenced by HAL_delayMicroSeconds(), LCD_clearCA(), LCD_clearDP(), LCD_showCA(), LCD_showChar(), and LCD_showDP().
HAL_enableUARTInterrupt()
void HAL_enableUARTInterrupt (HAL_UART_CHAN Chan)
Enable UART interrupt.
Parameters
[in] Chan UART Channel
References HAL_UARTInstance_::inst.
Referenced by HAL_delayMicroSeconds().
Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale