MSPM0L122X_L222X Driver Library: Low Frequeuncy Sub-System (LFSS)
Low Frequeuncy Sub-System (LFSS)
Modules
DL_LFSS_TAMPERIO_INTERRUPT
DL_LFSS_TAMPERIO_EVENT
Macros
#define LFSS_TAMPER_IO_PIN_ENABLE 0x1
Individual Tamper IO pin enable.
#define LFSS_TAMPER_IO_PIN_MASK 0x1
Individual Tamper IO pin mask.
Enumerations
enum DL_LFSS_TAMPERIO {
DL_LFSS_TAMPERIO_0 = 0x0000,
DL_LFSS_TAMPERIO_1 = 0x0001,
DL_LFSS_TAMPERIO_2 = 0x0002,
DL_LFSS_TAMPERIO_3 = 0x0003,
DL_LFSS_TAMPERIO_4 = 0x0004,
DL_LFSS_TAMPERIO_5 = 0x0005,
DL_LFSS_TAMPERIO_6 = 0x0006,
DL_LFSS_TAMPERIO_7 = 0x0007,
DL_LFSS_TAMPERIO_8 = 0x0008,
DL_LFSS_TAMPERIO_9 = 0x0009,
DL_LFSS_TAMPERIO_10 = 0x000A,
DL_LFSS_TAMPERIO_11 = 0x000B,
DL_LFSS_TAMPERIO_12 = 0x000C,
DL_LFSS_TAMPERIO_13 = 0x000D,
DL_LFSS_TAMPERIO_14 = 0x000E,
DL_LFSS_TAMPERIO_15 = 0x000F
}
enum DL_LFSS_TAMPERIO_VALUE {
DL_LFSS_TAMPERIO_VALUE_0 = 0x00000,
DL_LFSS_TAMPERIO_VALUE_1 = 0x0001
}
enum DL_LFSS_TAMPERIO_OUTPUT_SOURCE {
DL_LFSS_TAMPERIO_OUTPUT_SOURCE_TOUT = LFSS_TIOCTL_TOUTSEL_TOUT,
DL_LFSS_TAMPERIO_OUTPUT_SOURCE_LFCLK = LFSS_TIOCTL_TOUTSEL_LFCLKEXT,
DL_LFSS_TAMPERIO_OUTPUT_SOURCE_HEARTBEAT = LFSS_TIOCTL_TOUTSEL_HEARTBEAT,
DL_LFSS_TAMPERIO_OUTPUT_SOURCE_TIME_STAMP_EVENT = LFSS_TIOCTL_TOUTSEL_TSEVTSTAT
}
enum DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH {
DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH_NONE = LFSS_TIOCTL_FILTEREN_NO_FLT,
DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH_30_USEC = LFSS_TIOCTL_FILTEREN_FLT_1,
DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH_100_USEC = LFSS_TIOCTL_FILTEREN_FLT_2,
DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH_200_USEC = LFSS_TIOCTL_FILTEREN_FLT_3
}
enum DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY {
DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY_DISABLE = LFSS_TIOCTL_POLARITY_DISABLE,
DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY_RISE = LFSS_TIOCTL_POLARITY_RISE,
DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY_FALL = LFSS_TIOCTL_POLARITY_FALL,
DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY_BOTH = LFSS_TIOCTL_POLARITY_BOTH
}
enum DL_LFSS_TAMPERIO_MODE {
DL_LFSS_TAMPERIO_MODE_TAMPER = LFSS_TIOCTL_IOMUX_TAMPER,
DL_LFSS_TAMPERIO_MODE_IOMUX = LFSS_TIOCTL_IOMUX_IOMUX
}
enum DL_LFSS_HEARTBEAT_INTERVAL {
DL_LFSS_HEARTBEAT_INTERVAL_0_125_SEC = LFSS_HEARTBEAT_HBINTERVAL_HBINT0P125,
DL_LFSS_HEARTBEAT_INTERVAL_0_25_SEC = LFSS_HEARTBEAT_HBINTERVAL_HBINT0P25,
DL_LFSS_HEARTBEAT_INTERVAL_05_SEC = LFSS_HEARTBEAT_HBINTERVAL_HBINT0P5,
DL_LFSS_HEARTBEAT_INTERVAL_1_SEC = LFSS_HEARTBEAT_HBINTERVAL_HBINT1,
DL_LFSS_HEARTBEAT_INTERVAL_2_SEC = LFSS_HEARTBEAT_HBINTERVAL_HBINT2,
DL_LFSS_HEARTBEAT_INTERVAL_4_SEC = LFSS_HEARTBEAT_HBINTERVAL_HBINT4,
DL_LFSS_HEARTBEAT_INTERVAL_8_SEC = LFSS_HEARTBEAT_HBINTERVAL_HBINT8,
DL_LFSS_HEARTBEAT_INTERVAL_16_SEC = LFSS_HEARTBEAT_HBINTERVAL_HBINT16
}
enum DL_LFSS_HEARTBEAT_PULSE_WIDTH {
DL_LFSS_HEARTBEAT_PULSE_WIDTH_1_MSEC = LFSS_HEARTBEAT_HBWIDTH_HBPWDTH1,
DL_LFSS_HEARTBEAT_PULSE_WIDTH_2_MSEC = LFSS_HEARTBEAT_HBWIDTH_HBPWDTH2,
DL_LFSS_HEARTBEAT_PULSE_WIDTH_4_MSEC = LFSS_HEARTBEAT_HBWIDTH_HBPWDTH4,
DL_LFSS_HEARTBEAT_PULSE_WIDTH_8_MSEC = LFSS_HEARTBEAT_HBWIDTH_HBPWDTH8,
DL_LFSS_HEARTBEAT_PULSE_WIDTH_16_MSEC = LFSS_HEARTBEAT_HBWIDTH_HBPWDTH16,
DL_LFSS_HEARTBEAT_PULSE_WIDTH_32_MSEC = LFSS_HEARTBEAT_HBWIDTH_HBPWDTH32,
DL_LFSS_HEARTBEAT_PULSE_WIDTH_64_MSEC = LFSS_HEARTBEAT_HBWIDTH_HBPWDTH64,
DL_LFSS_HEARTBEAT_PULSE_WIDTH_128_MSEC = LFSS_HEARTBEAT_HBWIDTH_HBPWDTH128
}
enum DL_LFSS_HEARTBEAT_MODE {
DL_LFSS_HEARTBEAT_MODE_DISABLED = LFSS_HEARTBEAT_HBMODE_HB_DIS,
DL_LFSS_HEARTBEAT_MODE_ALWAYS_ON = LFSS_HEARTBEAT_HBMODE_HB_ALLWAYS,
DL_LFSS_HEARTBEAT_MODE_TIME_STAMP = LFSS_HEARTBEAT_HBMODE_HB_TS,
DL_LFSS_HEARTBEAT_MODE_POWER_FAIL = LFSS_HEARTBEAT_HBMODE_HB_VDDFAIL
}
enum DL_LFSS_TAMPERIO_IIDX {
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_0 = LFSS_CPU_INT_IIDX_STAT_TIO0,
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_1 = LFSS_CPU_INT_IIDX_STAT_TIO1,
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_2 = LFSS_CPU_INT_IIDX_STAT_TIO2,
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_3 = LFSS_CPU_INT_IIDX_STAT_TIO3,
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_4 = LFSS_CPU_INT_IIDX_STAT_TIO4,
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_5 = LFSS_CPU_INT_IIDX_STAT_TIO5,
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_6 = LFSS_CPU_INT_IIDX_STAT_TIO6,
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_7 = LFSS_CPU_INT_IIDX_STAT_TIO7,
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_8 = LFSS_CPU_INT_IIDX_STAT_TIO8,
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_9 = LFSS_CPU_INT_IIDX_STAT_TIO9,
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_10 = LFSS_CPU_INT_IIDX_STAT_TIO10,
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_11 = LFSS_CPU_INT_IIDX_STAT_TIO11,
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_12 = LFSS_CPU_INT_IIDX_STAT_TIO12,
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_13 = LFSS_CPU_INT_IIDX_STAT_TIO13,
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_14 = LFSS_CPU_INT_IIDX_STAT_TIO14,
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_15 = LFSS_CPU_INT_IIDX_STAT_TIO15
}
enum DL_LFSS_SCRATCHPAD_MEM_WORD {
DL_LFSS_SCRATCHPAD_MEM_WORD_0 = 0x0000,
DL_LFSS_SCRATCHPAD_MEM_WORD_1 = 0x0001,
DL_LFSS_SCRATCHPAD_MEM_WORD_2 = 0x0002,
DL_LFSS_SCRATCHPAD_MEM_WORD_3 = 0x0003,
DL_LFSS_SCRATCHPAD_MEM_WORD_4 = 0x0004,
DL_LFSS_SCRATCHPAD_MEM_WORD_5 = 0x0005,
DL_LFSS_SCRATCHPAD_MEM_WORD_6 = 0x0006,
DL_LFSS_SCRATCHPAD_MEM_WORD_7 = 0x0007
}
enum DL_LFSS_SCRATCHPAD_MEM_BYTE {
DL_LFSS_SCRATCHPAD_MEM_BYTE_0 = 0x0000,
DL_LFSS_SCRATCHPAD_MEM_BYTE_1 = 0x0001,
DL_LFSS_SCRATCHPAD_MEM_BYTE_2 = 0x0002,
DL_LFSS_SCRATCHPAD_MEM_BYTE_3 = 0x0003
}
enum DL_LFSS_IWDT_CLOCK_DIVIDE {
DL_LFSS_IWDT_CLOCK_DIVIDE_1 = 0x00000000,
DL_LFSS_IWDT_CLOCK_DIVIDE_2 = 0x00000001,
DL_LFSS_IWDT_CLOCK_DIVIDE_3 = 0x00000002,
DL_LFSS_IWDT_CLOCK_DIVIDE_4 = 0x00000003,
DL_LFSS_IWDT_CLOCK_DIVIDE_5 = 0x00000004,
DL_LFSS_IWDT_CLOCK_DIVIDE_6 = 0x00000005,
DL_LFSS_IWDT_CLOCK_DIVIDE_7 = 0x00000006,
DL_LFSS_IWDT_CLOCK_DIVIDE_8 = 0x00000007
}
enum DL_LFSS_IWDT_TIMER_PERIOD {
DL_LFSS_IWDT_TIMER_PERIOD_6_BITS = LFSS_WDTCTL_PER_PER_EN_6,
DL_LFSS_IWDT_TIMER_PERIOD_8_BITS = LFSS_WDTCTL_PER_PER_EN_8,
DL_LFSS_IWDT_TIMER_PERIOD_10_BITS = LFSS_WDTCTL_PER_PER_EN_10,
DL_LFSS_IWDT_TIMER_PERIOD_12_BITS = LFSS_WDTCTL_PER_PER_EN_12,
DL_LFSS_IWDT_TIMER_PERIOD_15_BITS = LFSS_WDTCTL_PER_PER_EN_15,
DL_LFSS_IWDT_TIMER_PERIOD_18_BITS = LFSS_WDTCTL_PER_PER_EN_18,
DL_LFSS_IWDT_TIMER_PERIOD_21_BITS = LFSS_WDTCTL_PER_PER_EN_21,
DL_LFSS_IWDT_TIMER_PERIOD_25_BITS = LFSS_WDTCTL_PER_PER_EN_25
}
Functions
__STATIC_INLINE void DL_LFSS_TamperIO_enableOutputInversion (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Enable output inversion for the specified Tamper IO.
__STATIC_INLINE bool DL_LFSS_TamperIO_isOutputInversionEnabled (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Checks if output inversion is enabled for the specified Tamper IO.
__STATIC_INLINE void DL_LFSS_TamperIO_disableOutputInversion (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Disable output inversion for the specified Tamper IO.
__STATIC_INLINE void DL_LFSS_TamperIO_setOutputSource (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO, DL_LFSS_TAMPERIO_OUTPUT_SOURCE source)
Selects the source for the tamper output (TOUT) control for the specified Tamper IO.
__STATIC_INLINE DL_LFSS_TAMPERIO_OUTPUT_SOURCE DL_LFSS_TamperIO_getOutputSource (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Gets the source for the tamper output (TOUT) control for the specified Tamper IO.
__STATIC_INLINE void DL_LFSS_TamperIO_setGlitchFilterWidth (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO, DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH width)
Selects the filter width for the digital glitch filter for the specified Tamper IO.
__STATIC_INLINE DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH DL_LFSS_TamperIO_getGlitchFilterWidth (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Gets the filter width for the digital glitch filter for the specified Tamper IO.
__STATIC_INLINE void DL_LFSS_TamperIO_setEdgeDetectionPolarity (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO, DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY polarity)
Selects the edge detection polarity for the specified Tamper IO.
__STATIC_INLINE DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY DL_LFSS_TamperIO_getEdgeDetectionPolarity (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Gets the edge detection polarity for the specified Tamper IO.
__STATIC_INLINE void DL_LFSS_TamperIO_enableInternalPullUp (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Enable internal pull-up resistor for the specified Tamper IO.
__STATIC_INLINE bool DL_LFSS_TamperIO_isInternalPullUpEnabled (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Checks if internal pull-up resistor is enabled for the specified Tamper IO.
__STATIC_INLINE void DL_LFSS_TamperIO_disableInternalPullUp (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Disable internal pull-up resistor for the specified Tamper IO.
__STATIC_INLINE void DL_LFSS_TamperIO_enableInternalPullDown (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Enable internal pull-down resistor for the specified Tamper IO.
__STATIC_INLINE bool DL_LFSS_TamperIO_isInternalPullDownEnabled (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Checks if internal pull-down resistor is enabled for the specified Tamper IO.
__STATIC_INLINE void DL_LFSS_TamperIO_disableInternalPullDown (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Disable internal pull-down resistor for the specified Tamper IO.
__STATIC_INLINE void DL_LFSS_TamperIO_enableInput (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Enable input path for the specified Tamper IO.
__STATIC_INLINE bool DL_LFSS_TamperIO_isInputEnabled (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Checks if input is enabled for the specified Tamper IO.
__STATIC_INLINE void DL_LFSS_TamperIO_disableInput (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Disable input path for the specified Tamper IO.
__STATIC_INLINE void DL_LFSS_TamperIO_setMode (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO, DL_LFSS_TAMPERIO_MODE mode)
Selects the mode for the specified Tamper IO.
__STATIC_INLINE DL_LFSS_TAMPERIO_MODE DL_LFSS_TamperIO_getMode (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Gets the mode for the specified Tamper IO.
__STATIC_INLINE void DL_LFSS_TamperIO_enableOutput (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Enable data output for the specified Tamper IO.
__STATIC_INLINE void DL_LFSS_TamperIO_disableOutput (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Disable data output for the specified Tamper IO.
__STATIC_INLINE uint32_t DL_LFSS_TamperIO_isOutputEnabled (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Checks if data output for the specified Tamper IO is enabled.
__STATIC_INLINE void DL_LFSS_TamperIO_setOutputValue (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO, DL_LFSS_TAMPERIO_VALUE outVal)
Enable data output value as zero for the specified Tamper IO.
__STATIC_INLINE DL_LFSS_TAMPERIO_VALUE DL_LFSS_TamperIO_getOutputValue (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Gets the output data value for the specified Tamper IO.
__STATIC_INLINE DL_LFSS_TAMPERIO_VALUE DL_LFSS_TamperIO_getInputValue (LFSS_Regs *lfss, DL_LFSS_TAMPERIO tamperIO)
Gets the input data value for the specified Tamper IO.
__STATIC_INLINE void DL_LFSS_TamperIO_setHeartBeatInterval (LFSS_Regs *lfss, DL_LFSS_HEARTBEAT_INTERVAL interval)
Sets the interval for the heart beat generator.
__STATIC_INLINE DL_LFSS_HEARTBEAT_INTERVAL DL_LFSS_TamperIO_getHeartBeatInterval (LFSS_Regs *lfss)
Gets the interval for the heart beat generator.
__STATIC_INLINE void DL_LFSS_TamperIO_setHeartBeatPulseWidth (LFSS_Regs *lfss, DL_LFSS_HEARTBEAT_PULSE_WIDTH width)
Sets the pulse width for the heart beat generator.
__STATIC_INLINE DL_LFSS_HEARTBEAT_PULSE_WIDTH DL_LFSS_TamperIO_getHeartBeatPulseWidth (LFSS_Regs *lfss)
Gets the pulse width for the heart beat generator.
__STATIC_INLINE void DL_LFSS_TamperIO_setHeartBeatMode (LFSS_Regs *lfss, DL_LFSS_HEARTBEAT_MODE mode)
Sets the mode for the heart beat generator.
__STATIC_INLINE DL_LFSS_HEARTBEAT_MODE DL_LFSS_TamperIO_getHeartBeatMode (LFSS_Regs *lfss)
Gets the pulse mode for the heart beat generator.
__STATIC_INLINE void DL_LFSS_TamperIO_enableWriteProtectLock (LFSS_Regs *lfss)
Enable write protection lock of the TIOCTL and HEARTBEAT registers from accidental updates.
__STATIC_INLINE bool DL_LFSS_TamperIO_isWriteProtectLockEnabled (LFSS_Regs *lfss)
Checks if write protection lock of the TIOCTL and HEARTBEAT registers is enabled for the specified Tamper IO.
__STATIC_INLINE void DL_LFSS_TamperIO_disableWriteProtectLock (LFSS_Regs *lfss)
Disable write protection lock of the TIOCTL and HEARTBEAT registers.
__STATIC_INLINE void DL_LFSS_IWDT_enableModule (LFSS_Regs *lfss)
Enables the Watchdog module.
__STATIC_INLINE void DL_LFSS_IWDT_disableModule (LFSS_Regs *lfss)
Disables the Watchdog module.
__STATIC_INLINE bool DL_LFSS_IWDT_isModuleEnabled (LFSS_Regs *lfss)
Returns if Watchdog module is on.
__STATIC_INLINE void DL_LFSS_IWDT_enableFreeRun (LFSS_Regs *lfss)
Enables the Watchdog free run control.
__STATIC_INLINE void DL_LFSS_IWDT_disableFreeRun (LFSS_Regs *lfss)
Disables the Watchdog free run control.
__STATIC_INLINE bool DL_LFSS_IWDT_isFreeRunEnabled (LFSS_Regs *lfss)
Returns if Watchdog free run control is enabled.
__STATIC_INLINE void DL_LFSS_IWDT_setClockDivider (LFSS_Regs *lfss, DL_LFSS_IWDT_CLOCK_DIVIDE divider)
Sets the clock divider for the WDT module.
__STATIC_INLINE DL_LFSS_IWDT_CLOCK_DIVIDE DL_LFSS_IWDT_getClockDivider (LFSS_Regs *lfss)
Gets the clock divider for the WDT module.
__STATIC_INLINE void DL_LFSS_IWDT_setTimerPeriod (LFSS_Regs *lfss, DL_LFSS_IWDT_TIMER_PERIOD period)
Sets the timer period for the WDT module.
__STATIC_INLINE DL_LFSS_IWDT_TIMER_PERIOD DL_LFSS_IWDT_getTimerPeriod (LFSS_Regs *lfss)
Get the timer period for the WDT module.
__STATIC_INLINE void DL_LFSS_IWDT_restart (LFSS_Regs *lfss)
Restarts the Watchdog.
__STATIC_INLINE bool DL_LFSS_IWDT_isWatchdogRunning (LFSS_Regs *lfss)
Returns if Watchdog module is running.
__STATIC_INLINE void DL_LFSS_IWDT_enableWriteProtect (LFSS_Regs *lfss)
Enable write protection lock of the WDTEN and WDTCTL registers from accidental updates.
__STATIC_INLINE bool DL_LFSS_IWDT_isWriteProtectEnabled (LFSS_Regs *lfss)
Checks if write protection lock of the WDTEN and WDTCTL registers is enabled.
__STATIC_INLINE void DL_LFSS_IWDT_disableWriteProtect (LFSS_Regs *lfss)
Disable write protection lock of the WDTEN and WDTCTL registers.
__STATIC_INLINE void DL_LFSS_writeScratchPadData32 (LFSS_Regs *lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, uint32_t data)
Write a word in scratch pad memory.
__STATIC_INLINE void DL_LFSS_writeScratchPadData8 (LFSS_Regs *lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, DL_LFSS_SCRATCHPAD_MEM_BYTE byteIndex, uint32_t data)
Write to a single byte in scratch pad memory.
__STATIC_INLINE uint32_t DL_LFSS_readScratchPadDataWord (LFSS_Regs *lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex)
Read the specified word in scratch pad memory.
__STATIC_INLINE uint8_t DL_LFSS_readScratchPadDataByte (LFSS_Regs *lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, DL_LFSS_SCRATCHPAD_MEM_BYTE byteIndex)
Read the specified byte in scratch pad memory.
__STATIC_INLINE void DL_LFSS_enableScratchPadWriteProtectByte (LFSS_Regs *lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, DL_LFSS_SCRATCHPAD_MEM_BYTE byteIndex)
Enable write protection lock of the specified byte in scratch pad memory from accidental updates.
__STATIC_INLINE bool DL_LFSS_isScratchPadWriteProtectByteEnabled (LFSS_Regs *lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, DL_LFSS_SCRATCHPAD_MEM_BYTE byteIndex)
Checks if write protection is enabled for the specified byte in scratch pad memory.
__STATIC_INLINE void DL_LFSS_disableScratchPadWriteProtectByte (LFSS_Regs *lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, DL_LFSS_SCRATCHPAD_MEM_BYTE byteIndex)
Disable write protection lock of the specified byte in scratch pad memory.
__STATIC_INLINE void DL_LFSS_enableScratchPadTamperEraseByte (LFSS_Regs *lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, DL_LFSS_SCRATCHPAD_MEM_BYTE byteIndex)
Enable tamper erase of the specified byte in scratch pad memory.
__STATIC_INLINE bool DL_LFSS_isScratchPadTamperEraseByteEnabled (LFSS_Regs *lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, DL_LFSS_SCRATCHPAD_MEM_BYTE byteIndex)
Checks if tamper erase is enabled for the specified byte in scratch pad memory.
__STATIC_INLINE void DL_LFSS_disableScratchPadTamperEraseByte (LFSS_Regs *lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, DL_LFSS_SCRATCHPAD_MEM_BYTE byteIndex)
Disable tamper erase of the specified byte in scratch pad memory.
__STATIC_INLINE void DL_LFSS_TamperIO_enableInterrupt (LFSS_Regs *lfss, uint32_t interruptMask)
Enable LFSS Tamper Interrupts.
__STATIC_INLINE void DL_LFSS_TamperIO_disableInterrupt (LFSS_Regs *lfss, uint32_t interruptMask)
Disable LFSS Tamper interrupts.
__STATIC_INLINE uint32_t DL_LFSS_TamperIO_getEnabledInterrupts (LFSS_Regs *lfss, uint32_t interruptMask)
Check which LFSS Tamper interrupts are enabled.
__STATIC_INLINE uint32_t DL_LFSS_TamperIO_getEnabledInterruptStatus (LFSS_Regs *lfss, uint32_t interruptMask)
Check interrupt flag of enabled LFSS Tamper interrupts.
__STATIC_INLINE uint32_t DL_LFSS_TamperIO_getRawInterruptStatus (LFSS_Regs *lfss, uint32_t interruptMask)
Check interrupt flag of any LFSS Tamper interrupt.
__STATIC_INLINE DL_LFSS_TAMPERIO_IIDX DL_LFSS_TamperIO_getPendingInterrupt (LFSS_Regs *lfss)
Get highest priority pending LFSS interrupt.
__STATIC_INLINE void DL_LFSS_TamperIO_clearInterruptStatus (LFSS_Regs *lfss, uint32_t interruptMask)
Clear pending LFSS Tamper interrupts.
__STATIC_INLINE void DL_LFSS_TamperIO_enableEvent (LFSS_Regs *lfss, uint32_t eventMask)
Enable LFSS Tamper event.
__STATIC_INLINE void DL_LFSS_TamperIO_disableEvent (LFSS_Regs *lfss, uint32_t eventMask)
Disable LFSS Tamper event.
__STATIC_INLINE uint32_t DL_LFSS_TamperIO_getEnabledEvents (LFSS_Regs *lfss, uint32_t eventMask)
Check which LFSS Tamper events are enabled.
__STATIC_INLINE uint32_t DL_LFSS_TamperIO_getEnabledEventStatus (LFSS_Regs *lfss, uint32_t eventMask)
Check event flag of enabled LFSS Tamper event.
__STATIC_INLINE uint32_t DL_LFSS_TamperIO_getRawEventsStatus (LFSS_Regs *lfss, uint32_t eventMask)
Check interrupt flag of any LFSS Tamper event.
__STATIC_INLINE void DL_LFSS_TamperIO_clearEventsStatus (LFSS_Regs *lfss, uint32_t eventMask)
Clear pending LFSS Tamper events.
__STATIC_INLINE void DL_LFSS_TamperIO_setPublisherChanID (LFSS_Regs *lfss, uint8_t chanID)
Sets the LFSS Tamper event publisher channel ID.
__STATIC_INLINE uint8_t DL_LFSS_TamperIO_getPublisherChanID (LFSS_Regs *lfss)
Gets the event publisher channel ID.
__STATIC_INLINE void DL_LFSS_reset (LFSS_Regs *lfss)
Requests a reset to the LFSS module.
Detailed Description
Overview
The Low Frequency Sub-System (LFSS) Driver Library allows full configuration of the MSPM0 LFSS module. The LFSS IP enables a separate, dedicated battery supply used for maintaining continuous operation of real time clock (RTC), tamper detection input / output (TIO) module, an independent asynchronous watchdog timer (IWDT) and a small scratchpad memory storage (SPM).
Enumeration Type Documentation
DL_LFSS_TAMPERIO
enum DL_LFSS_TAMPERIO
Enumerator
DL_LFSS_TAMPERIO_0
LFSS Tamper IO 0
DL_LFSS_TAMPERIO_1
LFSS Tamper IO 1
DL_LFSS_TAMPERIO_2
LFSS Tamper IO 2
DL_LFSS_TAMPERIO_3
LFSS Tamper IO 3
DL_LFSS_TAMPERIO_4
LFSS Tamper IO 4
DL_LFSS_TAMPERIO_5
LFSS Tamper IO 5
DL_LFSS_TAMPERIO_6
LFSS Tamper IO 6
DL_LFSS_TAMPERIO_7
LFSS Tamper IO 7
DL_LFSS_TAMPERIO_8
LFSS Tamper IO 8
DL_LFSS_TAMPERIO_9
LFSS Tamper IO 9
DL_LFSS_TAMPERIO_10
LFSS Tamper IO 10
DL_LFSS_TAMPERIO_11
LFSS Tamper IO 11
DL_LFSS_TAMPERIO_12
LFSS Tamper IO 12
DL_LFSS_TAMPERIO_13
LFSS Tamper IO 13
DL_LFSS_TAMPERIO_14
LFSS Tamper IO 14
DL_LFSS_TAMPERIO_15
LFSS Tamper IO 15
DL_LFSS_TAMPERIO_VALUE
enum DL_LFSS_TAMPERIO_VALUE
Enumerator
DL_LFSS_TAMPERIO_VALUE_0
LFSS Tamper IO Value is 0
DL_LFSS_TAMPERIO_VALUE_1
LFSS Tamper IO Value is 1
DL_LFSS_TAMPERIO_OUTPUT_SOURCE
enum DL_LFSS_TAMPERIO_OUTPUT_SOURCE
Enumerator
DL_LFSS_TAMPERIO_OUTPUT_SOURCE_TOUT
The TOUT register is the source for the tamper output (TOUT) control
DL_LFSS_TAMPERIO_OUTPUT_SOURCE_LFCLK
LFCLK is the source for the tamper output (TOUT) control
DL_LFSS_TAMPERIO_OUTPUT_SOURCE_HEARTBEAT
The heart beat generator is the source for the tamper output (TOUT) control
DL_LFSS_TAMPERIO_OUTPUT_SOURCE_TIME_STAMP_EVENT
The time stamp event is the source for the tamper output (TOUT) control
DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH
enum DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH
Enumerator
DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH_NONE
No filtering on the Tamper IO beyond CDS synchronization sample
DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH_30_USEC
Pulses on the Tamper IO less than 30us are filtered
DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH_100_USEC
Pulses on the Tamper IO less than 100us are filtered
DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH_200_USEC
Pulses on the Tamper IO less than 200us are filtered
DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY
enum DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY
Enumerator
DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY_DISABLE
Edge detection polarity is disabled
DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY_RISE
Enables rising edge detection of input event
DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY_FALL
Enables falling edge detection of input event
DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY_BOTH
Enables both rising and falling edge detection of input event
DL_LFSS_TAMPERIO_MODE
enum DL_LFSS_TAMPERIO_MODE
Enumerator
DL_LFSS_TAMPERIO_MODE_TAMPER
The Tamper IO is set to tamper mode
DL_LFSS_TAMPERIO_MODE_IOMUX
The Tamper IO is set to IOMUX mode
DL_LFSS_HEARTBEAT_INTERVAL
enum DL_LFSS_HEARTBEAT_INTERVAL
Enumerator
DL_LFSS_HEARTBEAT_INTERVAL_0_125_SEC
Heart beat generator interval is 0.125 sec
DL_LFSS_HEARTBEAT_INTERVAL_0_25_SEC
Heart beat generator interval is 0.25 sec
DL_LFSS_HEARTBEAT_INTERVAL_05_SEC
Heart beat generator interval is 0.5 sec
DL_LFSS_HEARTBEAT_INTERVAL_1_SEC
Heart beat generator interval is 1 sec
DL_LFSS_HEARTBEAT_INTERVAL_2_SEC
Heart beat generator interval is 2 sec
DL_LFSS_HEARTBEAT_INTERVAL_4_SEC
Heart beat generator interval is 4 sec
DL_LFSS_HEARTBEAT_INTERVAL_8_SEC
Heart beat generator interval is 8 sec
DL_LFSS_HEARTBEAT_INTERVAL_16_SEC
Heart beat generator interval is 16 sec
DL_LFSS_HEARTBEAT_PULSE_WIDTH
enum DL_LFSS_HEARTBEAT_PULSE_WIDTH
Enumerator
DL_LFSS_HEARTBEAT_PULSE_WIDTH_1_MSEC
Heart beat generator pulse width is 1 msec
DL_LFSS_HEARTBEAT_PULSE_WIDTH_2_MSEC
Heart beat generator pulse width is 2 msec
DL_LFSS_HEARTBEAT_PULSE_WIDTH_4_MSEC
Heart beat generator pulse width is 4 msec
DL_LFSS_HEARTBEAT_PULSE_WIDTH_8_MSEC
Heart beat generator pulse width is 8 msec
DL_LFSS_HEARTBEAT_PULSE_WIDTH_16_MSEC
Heart beat generator pulse width is 16 msec
DL_LFSS_HEARTBEAT_PULSE_WIDTH_32_MSEC
Heart beat generator pulse width is 32 msec
DL_LFSS_HEARTBEAT_PULSE_WIDTH_64_MSEC
Heart beat generator pulse width is 64 msec
DL_LFSS_HEARTBEAT_PULSE_WIDTH_128_MSEC
Heart beat generator pulse width is 128 msec
DL_LFSS_HEARTBEAT_MODE
enum DL_LFSS_HEARTBEAT_MODE
Enumerator
DL_LFSS_HEARTBEAT_MODE_DISABLED
Heart beat generator mode is disabled
DL_LFSS_HEARTBEAT_MODE_ALWAYS_ON
Heart beat generator mode is always enabled
DL_LFSS_HEARTBEAT_MODE_TIME_STAMP
Heart beat generator mode is enabled when time stamp event is detected
DL_LFSS_HEARTBEAT_MODE_POWER_FAIL
Heart beat generator mode is enabled when the main power supply fails
DL_LFSS_TAMPERIO_IIDX
enum DL_LFSS_TAMPERIO_IIDX
Enumerator
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_0
LFSS Tamper interrupt index for Tamper IO 0
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_1
LFSS Tamper interrupt index for Tamper IO 1
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_2
LFSS Tamper interrupt index for Tamper IO 2
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_3
LFSS Tamper interrupt index for Tamper IO 3
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_4
LFSS Tamper interrupt index for Tamper IO 4
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_5
LFSS Tamper interrupt index for Tamper IO 5
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_6
LFSS Tamper interrupt index for Tamper IO 6
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_7
LFSS Tamper interrupt index for Tamper IO 7
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_8
LFSS Tamper interrupt index for Tamper IO 8
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_9
LFSS Tamper interrupt index for Tamper IO 9
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_10
LFSS Tamper interrupt index for Tamper IO 10
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_11
LFSS Tamper interrupt index for Tamper IO 11
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_12
LFSS Tamper interrupt index for Tamper IO 12
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_13
LFSS Tamper interrupt index for Tamper IO 13
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_14
LFSS Tamper interrupt index for Tamper IO 14
DL_LFSS_TAMPERIO_IIDX_TAMPER_IO_15
LFSS Tamper interrupt index for Tamper IO 15
DL_LFSS_SCRATCHPAD_MEM_WORD
enum DL_LFSS_SCRATCHPAD_MEM_WORD
Enumerator
DL_LFSS_SCRATCHPAD_MEM_WORD_0
LFSS Scratch Pad memory word 0
DL_LFSS_SCRATCHPAD_MEM_WORD_1
LFSS Scratch Pad memory word 1
DL_LFSS_SCRATCHPAD_MEM_WORD_2
LFSS Scratch Pad memory word 2
DL_LFSS_SCRATCHPAD_MEM_WORD_3
LFSS Scratch Pad memory word 3
DL_LFSS_SCRATCHPAD_MEM_WORD_4
LFSS Scratch Pad memory word 4
DL_LFSS_SCRATCHPAD_MEM_WORD_5
LFSS Scratch Pad memory word 5
DL_LFSS_SCRATCHPAD_MEM_WORD_6
LFSS Scratch Pad memory word 6
DL_LFSS_SCRATCHPAD_MEM_WORD_7
LFSS Scratch Pad memory word 7
DL_LFSS_SCRATCHPAD_MEM_BYTE
enum DL_LFSS_SCRATCHPAD_MEM_BYTE
Enumerator
DL_LFSS_SCRATCHPAD_MEM_BYTE_0
LFSS Scratch Pad memory byte 0 of the given Scratch Pad memory word
DL_LFSS_SCRATCHPAD_MEM_BYTE_1
LFSS Scratch Pad memory byte 1 of the given Scratch Pad memory word
DL_LFSS_SCRATCHPAD_MEM_BYTE_2
LFSS Scratch Pad memory byte 2 of the given Scratch Pad memory word
DL_LFSS_SCRATCHPAD_MEM_BYTE_3
LFSS Scratch Pad memory byte 3 of the given Scratch Pad memory word
DL_LFSS_IWDT_CLOCK_DIVIDE
enum DL_LFSS_IWDT_CLOCK_DIVIDE
Enumerator
DL_LFSS_IWDT_CLOCK_DIVIDE_1
WDT Clock divide by 1
DL_LFSS_IWDT_CLOCK_DIVIDE_2
WDT Clock divide by 2
DL_LFSS_IWDT_CLOCK_DIVIDE_3
WDT Clock divide by 3
DL_LFSS_IWDT_CLOCK_DIVIDE_4
WDT Clock divide by 4
DL_LFSS_IWDT_CLOCK_DIVIDE_5
WDT Clock divide by 5
DL_LFSS_IWDT_CLOCK_DIVIDE_6
WDT Clock divide by 6
DL_LFSS_IWDT_CLOCK_DIVIDE_7
WDT Clock divide by 7
DL_LFSS_IWDT_CLOCK_DIVIDE_8
WDT Clock divide by 8
DL_LFSS_IWDT_TIMER_PERIOD
enum DL_LFSS_IWDT_TIMER_PERIOD
Enumerator
DL_LFSS_IWDT_TIMER_PERIOD_6_BITS
WDT 2^6 timer period count
DL_LFSS_IWDT_TIMER_PERIOD_8_BITS
WDT 2^8 timer period count
DL_LFSS_IWDT_TIMER_PERIOD_10_BITS
WDT 2^10 timer period count
DL_LFSS_IWDT_TIMER_PERIOD_12_BITS
WDT 2^12 timer period count
DL_LFSS_IWDT_TIMER_PERIOD_15_BITS
WDT 2^15 timer period count
DL_LFSS_IWDT_TIMER_PERIOD_18_BITS
WDT 2^18 timer period count
DL_LFSS_IWDT_TIMER_PERIOD_21_BITS
WDT 2^21 timer period count
DL_LFSS_IWDT_TIMER_PERIOD_25_BITS
WDT 2^25 timer period count
Function Documentation
DL_LFSS_TamperIO_enableOutputInversion()
__STATIC_INLINE void DL_LFSS_TamperIO_enableOutputInversion (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Enable output inversion for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO.
DL_LFSS_TamperIO_isOutputInversionEnabled()
__STATIC_INLINE bool DL_LFSS_TamperIO_isOutputInversionEnabled (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Checks if output inversion is enabled for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO
Returns
Returns if output inversion is enabled
Return values
true Output inversion for the Tamper I/O is enabled
false Output inversion for the Tamper I/O is disabled
DL_LFSS_TamperIO_disableOutputInversion()
__STATIC_INLINE void DL_LFSS_TamperIO_disableOutputInversion (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Disable output inversion for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO
DL_LFSS_TamperIO_setOutputSource()
__STATIC_INLINE void DL_LFSS_TamperIO_setOutputSource (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO, DL_LFSS_TAMPERIO_OUTPUT_SOURCE source)
Selects the source for the tamper output (TOUT) control for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO
[in] source The source for the tamper output control. One of DL_LFSS_TAMPERIO_OUTPUT_SOURCE.
References DL_Common_updateReg().
DL_LFSS_TamperIO_getOutputSource()
__STATIC_INLINE DL_LFSS_TAMPERIO_OUTPUT_SOURCE DL_LFSS_TamperIO_getOutputSource (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Gets the source for the tamper output (TOUT) control for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO. One of DL_LFSS_TAMPERIO
Returns
The output source of the tamper IO
Return values
One of DL_LFSS_TAMPERIO_OUTPUT_SOURCE
DL_LFSS_TamperIO_setGlitchFilterWidth()
__STATIC_INLINE void DL_LFSS_TamperIO_setGlitchFilterWidth (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO, DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH width)
Selects the filter width for the digital glitch filter for the specified Tamper IO.
The tamper event detection allows to configure one or more tamper IOs to trigger a timestamp event and to generate an interrupt to the CPU. To minimize false triggers, a digital filter circuit is inserted into the IO path. Only pulses that are longer than the configured filter width will be registered as a tamper event.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO
[in] width The width of the digital glitch filter. Pulses smaller than this width will be filtered. One of DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH.
References DL_Common_updateReg().
DL_LFSS_TamperIO_getGlitchFilterWidth()
__STATIC_INLINE DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH DL_LFSS_TamperIO_getGlitchFilterWidth (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Gets the filter width for the digital glitch filter for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO. One of DL_LFSS_TAMPERIO
Returns
The digital glitch filter width
Return values
One of DL_LFSS_TAMPERIO_GLITCH_FILTER_WIDTH
DL_LFSS_TamperIO_setEdgeDetectionPolarity()
__STATIC_INLINE void DL_LFSS_TamperIO_setEdgeDetectionPolarity (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO, DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY polarity)
Selects the edge detection polarity for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO
[in] polarity The edge detection polarity. One of DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY.
References DL_Common_updateReg().
DL_LFSS_TamperIO_getEdgeDetectionPolarity()
__STATIC_INLINE DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY DL_LFSS_TamperIO_getEdgeDetectionPolarity (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Gets the edge detection polarity for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO. One of DL_LFSS_TAMPERIO
Returns
The edge detection polarity for the specified Tamper IO
Return values
One of DL_LFSS_TAMPERIO_EDGE_DETECTION_POLARITY
DL_LFSS_TamperIO_enableInternalPullUp()
__STATIC_INLINE void DL_LFSS_TamperIO_enableInternalPullUp (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Enable internal pull-up resistor for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO.
DL_LFSS_TamperIO_isInternalPullUpEnabled()
__STATIC_INLINE bool DL_LFSS_TamperIO_isInternalPullUpEnabled (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Checks if internal pull-up resistor is enabled for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO
Returns
Returns the internal pull-up resistor enabled status
Return values
true Internal pull-up resistor for the Tamper I/O is enabled
false Internal pull-up resistor for the Tamper I/O is disabled
DL_LFSS_TamperIO_disableInternalPullUp()
__STATIC_INLINE void DL_LFSS_TamperIO_disableInternalPullUp (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Disable internal pull-up resistor for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO
DL_LFSS_TamperIO_enableInternalPullDown()
__STATIC_INLINE void DL_LFSS_TamperIO_enableInternalPullDown (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Enable internal pull-down resistor for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO.
DL_LFSS_TamperIO_isInternalPullDownEnabled()
__STATIC_INLINE bool DL_LFSS_TamperIO_isInternalPullDownEnabled (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Checks if internal pull-down resistor is enabled for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO
Returns
Returns the internal pull-down resistor enabled status
Return values
true Internal pull-down resistor for the Tamper I/O is enabled
false Internal pull-down resistor for the Tamper I/O is disabled
DL_LFSS_TamperIO_disableInternalPullDown()
__STATIC_INLINE void DL_LFSS_TamperIO_disableInternalPullDown (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Disable internal pull-down resistor for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO
DL_LFSS_TamperIO_enableInput()
__STATIC_INLINE void DL_LFSS_TamperIO_enableInput (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Enable input path for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO.
DL_LFSS_TamperIO_isInputEnabled()
__STATIC_INLINE bool DL_LFSS_TamperIO_isInputEnabled (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Checks if input is enabled for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO
Returns
Returns the input enabled status
Return values
true Input for the Tamper I/O is enabled
false Input for the Tamper I/O is disabled
DL_LFSS_TamperIO_disableInput()
__STATIC_INLINE void DL_LFSS_TamperIO_disableInput (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Disable input path for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO
DL_LFSS_TamperIO_setMode()
__STATIC_INLINE void DL_LFSS_TamperIO_setMode (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO, DL_LFSS_TAMPERIO_MODE mode)
Selects the mode for the specified Tamper IO.
The tamper IOs have two modes of operation:
In IOMUX mode (DL_LFSS_TAMPERIO_MODE_IOMUX), the tamper IO input and output path are connected to the SoC IOMUX module and the IO can be used as a second function.
In tamper mode (DL_LFSS_TAMPERIO_MODE_TAMPER), the tamper IO is completely controlled by the VBAT IP and will remain functional during the power loss of the main supply or during SHUTDOWN mode.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO
[in] mode The mode for the specified tamper IO. One of DL_LFSS_TAMPERIO_MODE.
References DL_Common_updateReg().
DL_LFSS_TamperIO_getMode()
__STATIC_INLINE DL_LFSS_TAMPERIO_MODE DL_LFSS_TamperIO_getMode (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Gets the mode for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO. One of DL_LFSS_TAMPERIO
Returns
The mode for the specified Tamper IO
Return values
One of DL_LFSS_TAMPERIO_MODE
DL_LFSS_TamperIO_enableOutput()
__STATIC_INLINE void DL_LFSS_TamperIO_enableOutput (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Enable data output for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO.
References LFSS_TAMPER_IO_PIN_ENABLE.
DL_LFSS_TamperIO_disableOutput()
__STATIC_INLINE void DL_LFSS_TamperIO_disableOutput (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Disable data output for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO.
References LFSS_TAMPER_IO_PIN_ENABLE.
DL_LFSS_TamperIO_isOutputEnabled()
__STATIC_INLINE uint32_t DL_LFSS_TamperIO_isOutputEnabled (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Checks if data output for the specified Tamper IO is enabled.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO. One of DL_LFSS_TAMPERIO
Returns
If data output for the specified Tamper IO is enabled
Return values
true Data output for the tamper IO is enabled
false Data output for the tamper IO is disabled
References LFSS_TAMPER_IO_PIN_ENABLE, and LFSS_TAMPER_IO_PIN_MASK.
DL_LFSS_TamperIO_setOutputValue()
__STATIC_INLINE void DL_LFSS_TamperIO_setOutputValue (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO, DL_LFSS_TAMPERIO_VALUE outVal)
Enable data output value as zero for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO to configure. One of DL_LFSS_TAMPERIO.
[in] outVal The data value to set the tamper IO output to. One of DL_LFSS_TAMPERIO_VALUE.
References DL_Common_updateReg(), and LFSS_TAMPER_IO_PIN_MASK.
DL_LFSS_TamperIO_getOutputValue()
__STATIC_INLINE DL_LFSS_TAMPERIO_VALUE DL_LFSS_TamperIO_getOutputValue (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Gets the output data value for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO. One of DL_LFSS_TAMPERIO
Returns
The output data value for the specified tamper IO
Return values
One of DL_LFSS_TAMPERIO_VALUE
References LFSS_TAMPER_IO_PIN_MASK.
DL_LFSS_TamperIO_getInputValue()
__STATIC_INLINE DL_LFSS_TAMPERIO_VALUE DL_LFSS_TamperIO_getInputValue (LFSS_Regs * lfss, DL_LFSS_TAMPERIO tamperIO)
Gets the input data value for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] tamperIO Specifies the tamper IO. One of DL_LFSS_TAMPERIO
Returns
The input data value for the specified tamper IO
Return values
One of DL_LFSS_TAMPERIO_VALUE
References LFSS_TAMPER_IO_PIN_MASK.
DL_LFSS_TamperIO_setHeartBeatInterval()
__STATIC_INLINE void DL_LFSS_TamperIO_setHeartBeatInterval (LFSS_Regs * lfss, DL_LFSS_HEARTBEAT_INTERVAL interval)
Sets the interval for the heart beat generator.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] interval The interval of the heart beat generator. One of DL_LFSS_HEARTBEAT_INTERVAL
References DL_Common_updateReg().
DL_LFSS_TamperIO_getHeartBeatInterval()
__STATIC_INLINE DL_LFSS_HEARTBEAT_INTERVAL DL_LFSS_TamperIO_getHeartBeatInterval (LFSS_Regs * lfss)
Gets the interval for the heart beat generator.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
Returns
The interval for the heart beat generator.
Return values
One of DL_LFSS_HEARTBEAT_INTERVAL
DL_LFSS_TamperIO_setHeartBeatPulseWidth()
__STATIC_INLINE void DL_LFSS_TamperIO_setHeartBeatPulseWidth (LFSS_Regs * lfss, DL_LFSS_HEARTBEAT_PULSE_WIDTH width)
Sets the pulse width for the heart beat generator.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] width The pulse width of the heart beat generator. One of DL_LFSS_HEARTBEAT_PULSE_WIDTH
References DL_Common_updateReg().
DL_LFSS_TamperIO_getHeartBeatPulseWidth()
__STATIC_INLINE DL_LFSS_HEARTBEAT_PULSE_WIDTH DL_LFSS_TamperIO_getHeartBeatPulseWidth (LFSS_Regs * lfss)
Gets the pulse width for the heart beat generator.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
Returns
The pulse width for the heart beat generator.
Return values
One of DL_LFSS_HEARTBEAT_PULSE_WIDTH
DL_LFSS_TamperIO_setHeartBeatMode()
__STATIC_INLINE void DL_LFSS_TamperIO_setHeartBeatMode (LFSS_Regs * lfss, DL_LFSS_HEARTBEAT_MODE mode)
Sets the mode for the heart beat generator.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] mode The mode of the heart beat generator. One of DL_LFSS_HEARTBEAT_MODE
References DL_Common_updateReg().
DL_LFSS_TamperIO_getHeartBeatMode()
__STATIC_INLINE DL_LFSS_HEARTBEAT_MODE DL_LFSS_TamperIO_getHeartBeatMode (LFSS_Regs * lfss)
Gets the pulse mode for the heart beat generator.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
Returns
The pulse mode for the heart beat generator.
Return values
One of DL_LFSS_HEARTBEAT_MODE
DL_LFSS_TamperIO_enableWriteProtectLock()
__STATIC_INLINE void DL_LFSS_TamperIO_enableWriteProtectLock (LFSS_Regs * lfss)
Enable write protection lock of the TIOCTL and HEARTBEAT registers from accidental updates.
When enabled, the TIOCTL and HEARTBEAT registers will have read-only access.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
DL_LFSS_TamperIO_isWriteProtectLockEnabled()
__STATIC_INLINE bool DL_LFSS_TamperIO_isWriteProtectLockEnabled (LFSS_Regs * lfss)
Checks if write protection lock of the TIOCTL and HEARTBEAT registers is enabled for the specified Tamper IO.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
Returns
Returns the enabled status of the write protection lock
Return values
true Write protection lock is enabled
false Write protection lock is disabled
DL_LFSS_TamperIO_disableWriteProtectLock()
__STATIC_INLINE void DL_LFSS_TamperIO_disableWriteProtectLock (LFSS_Regs * lfss)
Disable write protection lock of the TIOCTL and HEARTBEAT registers.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
DL_LFSS_IWDT_enableModule()
__STATIC_INLINE void DL_LFSS_IWDT_enableModule (LFSS_Regs * lfss)
Enables the Watchdog module.
Parameters
lfss Pointer to the register overlay for the peripheral
DL_LFSS_IWDT_disableModule()
__STATIC_INLINE void DL_LFSS_IWDT_disableModule (LFSS_Regs * lfss)
Disables the Watchdog module.
Parameters
lfss Pointer to the register overlay for the peripheral
DL_LFSS_IWDT_isModuleEnabled()
__STATIC_INLINE bool DL_LFSS_IWDT_isModuleEnabled (LFSS_Regs * lfss)
Returns if Watchdog module is on.
Parameters
lfss Pointer to the register overlay for the peripheral
Returns
true Watchdog is enabled
false Watchdog is disabled
DL_LFSS_IWDT_enableFreeRun()
__STATIC_INLINE void DL_LFSS_IWDT_enableFreeRun (LFSS_Regs * lfss)
Enables the Watchdog free run control.
When enabled, the Watchdog will continue to free run and ignores the state of the CPU halted debug state
Parameters
lfss Pointer to the register overlay for the peripheral
DL_LFSS_IWDT_disableFreeRun()
__STATIC_INLINE void DL_LFSS_IWDT_disableFreeRun (LFSS_Regs * lfss)
Disables the Watchdog free run control.
Parameters
lfss Pointer to the register overlay for the peripheral
DL_LFSS_IWDT_isFreeRunEnabled()
__STATIC_INLINE bool DL_LFSS_IWDT_isFreeRunEnabled (LFSS_Regs * lfss)
Returns if Watchdog free run control is enabled.
Parameters
lfss Pointer to the register overlay for the peripheral
Returns
true Watchdog free run control is enabled
false Watchdog free run control is disabled
DL_LFSS_IWDT_setClockDivider()
__STATIC_INLINE void DL_LFSS_IWDT_setClockDivider (LFSS_Regs * lfss, DL_LFSS_IWDT_CLOCK_DIVIDE divider)
Sets the clock divider for the WDT module.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] divider The WDT clock divider to set. One of DL_LFSS_IWDT_CLOCK_DIVIDE.
References DL_Common_updateReg().
DL_LFSS_IWDT_getClockDivider()
__STATIC_INLINE DL_LFSS_IWDT_CLOCK_DIVIDE DL_LFSS_IWDT_getClockDivider (LFSS_Regs * lfss)
Gets the clock divider for the WDT module.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
Returns
The clock divider for the WDT module
Return values
One of DL_LFSS_IWDT_CLOCK_DIVIDE
DL_LFSS_IWDT_setTimerPeriod()
__STATIC_INLINE void DL_LFSS_IWDT_setTimerPeriod (LFSS_Regs * lfss, DL_LFSS_IWDT_TIMER_PERIOD period)
Sets the timer period for the WDT module.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] period The WDT timer period to set. One of DL_LFSS_IWDT_TIMER_PERIOD.
References DL_Common_updateReg().
DL_LFSS_IWDT_getTimerPeriod()
__STATIC_INLINE DL_LFSS_IWDT_TIMER_PERIOD DL_LFSS_IWDT_getTimerPeriod (LFSS_Regs * lfss)
Get the timer period for the WDT module.
Parameters
[in] lfss Pointer to the register overlay for peripheral
Returns
The current timer period for the WDT module
Return values
One of DL_LFSS_IWDT_TIMER_PERIOD
DL_LFSS_IWDT_restart()
__STATIC_INLINE void DL_LFSS_IWDT_restart (LFSS_Regs * lfss)
Restarts the Watchdog.
Parameters
[in] lfss Pointer to the register overlay for peripheral
DL_LFSS_IWDT_isWatchdogRunning()
__STATIC_INLINE bool DL_LFSS_IWDT_isWatchdogRunning (LFSS_Regs * lfss)
Returns if Watchdog module is running.
Parameters
lfss Pointer to the register overlay for the peripheral
Returns
true Watchdog module is running
false Watchdog counter has stopped
DL_LFSS_IWDT_enableWriteProtect()
__STATIC_INLINE void DL_LFSS_IWDT_enableWriteProtect (LFSS_Regs * lfss)
Enable write protection lock of the WDTEN and WDTCTL registers from accidental updates.
When enabled, the WDTEN and WDTCTL registers will have read-only access.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
DL_LFSS_IWDT_isWriteProtectEnabled()
__STATIC_INLINE bool DL_LFSS_IWDT_isWriteProtectEnabled (LFSS_Regs * lfss)
Checks if write protection lock of the WDTEN and WDTCTL registers is enabled.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
Returns
Returns the enabled status of the write protection lock
Return values
true Write protection lock is enabled
false Write protection lock is disabled
DL_LFSS_IWDT_disableWriteProtect()
__STATIC_INLINE void DL_LFSS_IWDT_disableWriteProtect (LFSS_Regs * lfss)
Disable write protection lock of the WDTEN and WDTCTL registers.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
DL_LFSS_writeScratchPadData32()
__STATIC_INLINE void DL_LFSS_writeScratchPadData32 (LFSS_Regs * lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, uint32_t data)
Write a word in scratch pad memory.
The VBAT scratch pad memory is register based memory that will retain data as long as VBAT is supplied. Refer to the device TRM for details on the specific size and implementation of the scratch pad memory.
This API wil write 32-bit data to the selected word in the scratch pad memory.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] memIndex The specified scratch pad memory word to write to. One of DL_LFSS_SCRATCHPAD_MEM_WORD
[in] data The 32-bit data to write to the specified scratch pad memory word. Value in range of [0x0, 0xFFFFFFF].
DL_LFSS_writeScratchPadData8()
__STATIC_INLINE void DL_LFSS_writeScratchPadData8 (LFSS_Regs * lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, DL_LFSS_SCRATCHPAD_MEM_BYTE byteIndex, uint32_t data)
Write to a single byte in scratch pad memory.
The VBAT scratch pad memory is register based memory that will retain data as long as VBAT is supplied. Refer to the device TRM for details on the specific size and implementation of the scratch pad memory.
This API will write 8-bit data to the selected byte in the scratch pad memory. The byte to write to is given in context of the scratch pad memory word that contains that byte. For example, to write to BYTE5 of scratch pad memory, the user will call this API with parameters DL_LFSS_SCRATCHPAD_MEM_WORD_1 and DL_LFSS_SCRATCHPAD_MEM_BYTE_1.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] memIndex The specified scratch pad memory word to write to. One of DL_LFSS_SCRATCHPAD_MEM_WORD
[in] byteIndex The specified scratch pad memory byte to write to. One of DL_LFSS_SCRATCHPAD_MEM_BYTE
[in] data The 8-bit data to write to the specified scratch pad memory byte. Value in range of [0x0, 0xFF].
References DL_Common_updateReg().
DL_LFSS_readScratchPadDataWord()
__STATIC_INLINE uint32_t DL_LFSS_readScratchPadDataWord (LFSS_Regs * lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex)
Read the specified word in scratch pad memory.
The VBAT scratch pad memory is register based memory that will retain data as long as VBAT is supplied. Refer to the device TRM for details on the specific size and implementation of the scratch pad memory.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] memIndex The specified scratch pad memory word to read. One of DL_LFSS_SCRATCHPAD_MEM_WORD
Returns
The 32-bit data in the specified scratch pad memory word
DL_LFSS_readScratchPadDataByte()
__STATIC_INLINE uint8_t DL_LFSS_readScratchPadDataByte (LFSS_Regs * lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, DL_LFSS_SCRATCHPAD_MEM_BYTE byteIndex)
Read the specified byte in scratch pad memory.
The VBAT scratch pad memory is register based memory that will retain data as long as VBAT is supplied. Refer to the device TRM for details on the specific size and implementation of the scratch pad memory.
This API will read 8-bit data from the selected byte in the scratch pad memory. The byte to read to is given in context of the scratch pad memory word that contains that byte. For example, to read BYTE5 of scratch pad memory, the user will call this API with parameters DL_LFSS_SCRATCHPAD_MEM_WORD_1 and DL_LFSS_SCRATCHPAD_MEM_BYTE_1.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] memIndex The specified scratch pad memory word to read. One of DL_LFSS_SCRATCHPAD_MEM_WORD
[in] byteIndex The specified scratch pad memory byte to read. One of DL_LFSS_SCRATCHPAD_MEM_BYTE
Returns
The 8-bit data in the specified scratch pad memory byte
DL_LFSS_enableScratchPadWriteProtectByte()
__STATIC_INLINE void DL_LFSS_enableScratchPadWriteProtectByte (LFSS_Regs * lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, DL_LFSS_SCRATCHPAD_MEM_BYTE byteIndex)
Enable write protection lock of the specified byte in scratch pad memory from accidental updates.
When enabled, the specified byte in scratch pad memory will have read-only access.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] memIndex The specified scratch pad memory word. One of DL_LFSS_SCRATCHPAD_MEM_WORD
[in] byteIndex The specified byte in scratch pad memory word to enable write protection for
DL_LFSS_isScratchPadWriteProtectByteEnabled()
__STATIC_INLINE bool DL_LFSS_isScratchPadWriteProtectByteEnabled (LFSS_Regs * lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, DL_LFSS_SCRATCHPAD_MEM_BYTE byteIndex)
Checks if write protection is enabled for the specified byte in scratch pad memory.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] memIndex The specified scratch pad memory word. One of DL_LFSS_SCRATCHPAD_MEM_WORD
[in] byteIndex The specified scratch pad memory byte. One of DL_LFSS_SCRATCHPAD_MEM_BYTE
Returns
Returns if write protection is enabled for the specified byte
Return values
true Write protection for the specified byte is enabled
false Write protection for the specified byte is disabled
DL_LFSS_disableScratchPadWriteProtectByte()
__STATIC_INLINE void DL_LFSS_disableScratchPadWriteProtectByte (LFSS_Regs * lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, DL_LFSS_SCRATCHPAD_MEM_BYTE byteIndex)
Disable write protection lock of the specified byte in scratch pad memory.
When disables, the specified byte in scratch pad memory will have read-only access.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] memIndex The specified scratch pad memory word. One of DL_LFSS_SCRATCHPAD_MEM_WORD
[in] byteIndex The specified byte in scratch pad memory word to disable write protection for. One of DL_LFSS_SCRATCHPAD_MEM_BYTE
DL_LFSS_enableScratchPadTamperEraseByte()
__STATIC_INLINE void DL_LFSS_enableScratchPadTamperEraseByte (LFSS_Regs * lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, DL_LFSS_SCRATCHPAD_MEM_BYTE byteIndex)
Enable tamper erase of the specified byte in scratch pad memory.
When enabled, the specified byte in scratch pad memory will be erased in the event of a tamper detect.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] memIndex The specified scratch pad memory word. One of DL_LFSS_SCRATCHPAD_MEM_WORD
[in] byteIndex The specified byte in scratch pad memory word to enable tamper erase for. One of DL_LFSS_SCRATCHPAD_MEM_BYTE
DL_LFSS_isScratchPadTamperEraseByteEnabled()
__STATIC_INLINE bool DL_LFSS_isScratchPadTamperEraseByteEnabled (LFSS_Regs * lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, DL_LFSS_SCRATCHPAD_MEM_BYTE byteIndex)
Checks if tamper erase is enabled for the specified byte in scratch pad memory.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] memIndex The specified scratch pad memory word. One of DL_LFSS_SCRATCHPAD_MEM_WORD
[in] byteIndex The specified byte in scratch pad memory byte. One of DL_LFSS_SCRATCHPAD_MEM_BYTE
Returns
Returns if tamper erase is enabled for the specified byte
Return values
true Tamper erase for the specified byte is enabled
false tamper erase for the specified byte is disabled
DL_LFSS_disableScratchPadTamperEraseByte()
__STATIC_INLINE void DL_LFSS_disableScratchPadTamperEraseByte (LFSS_Regs * lfss, DL_LFSS_SCRATCHPAD_MEM_WORD memIndex, DL_LFSS_SCRATCHPAD_MEM_BYTE byteIndex)
Disable tamper erase of the specified byte in scratch pad memory.
The specified byte in scratch pad memory will not be erased in the event of a tamper detect.
Parameters
[in] lfss Pointer to the register overlay for the LFSS peripheral
[in] memIndex The specified scratch pad memory word to write to. One of DL_LFSS_SCRATCHPAD_MEM_WORD
[in] byteIndex The specified byte in scratch pad memory word to disable tamper erase for. One of DL_LFSS_SCRATCHPAD_MEM_BYTE
DL_LFSS_TamperIO_enableInterrupt()
__STATIC_INLINE void DL_LFSS_TamperIO_enableInterrupt (LFSS_Regs * lfss, uint32_t interruptMask)
Enable LFSS Tamper Interrupts.
Parameters
[in] lfss Pointer to the register overlay for the LFSS Tamper peripheral
[in] interruptMask Bit mask of interrupts to enable. Logical OR of DL_LFSS_TAMPERIO_INTERRUPT.
DL_LFSS_TamperIO_disableInterrupt()
__STATIC_INLINE void DL_LFSS_TamperIO_disableInterrupt (LFSS_Regs * lfss, uint32_t interruptMask)
Disable LFSS Tamper interrupts.
Parameters
[in] lfss Pointer to the register overlay for the LFSS Tamper peripheral
[in] interruptMask Bit mask of interrupts to enable. Logical OR of DL_LFSS_TAMPERIO_INTERRUPT
DL_LFSS_TamperIO_getEnabledInterrupts()
__STATIC_INLINE uint32_t DL_LFSS_TamperIO_getEnabledInterrupts (LFSS_Regs * lfss, uint32_t interruptMask)
Check which LFSS Tamper interrupts are enabled.
Parameters
[in] lfss Pointer to the register overlay for the LFSS Tamper peripheral
[in] interruptMask Bit mask of interrupts to check. Logical OR of DL_LFSS_TAMPERIO_INTERRUPT
Returns
Which of the requested LFSS interrupts are enabled
Return values
Logical OR of DL_LFSS_TAMPERIO_INTERRUPT values
DL_LFSS_TamperIO_getEnabledInterruptStatus()
__STATIC_INLINE uint32_t DL_LFSS_TamperIO_getEnabledInterruptStatus (LFSS_Regs * lfss, uint32_t interruptMask)
Check interrupt flag of enabled LFSS Tamper interrupts.
Checks if any of the LFSS Tamper interrupts that were previously enabled are pending.
Parameters
[in] lfss Pointer to the register overlay for the LFSS Tamper peripheral
[in] interruptMask Bit mask of interrupts to check. Logical OR of DL_LFSS_TAMPERIO_INTERRUPT
Returns
Which of the requested LFSS Tamper interrupts are pending
Return values
Logical OR of DL_LFSS_TAMPERIO_INTERRUPT values
See also
DL_LFSS_TAMPERIO_enableInterrupt
DL_LFSS_TamperIO_getRawInterruptStatus()
__STATIC_INLINE uint32_t DL_LFSS_TamperIO_getRawInterruptStatus (LFSS_Regs * lfss, uint32_t interruptMask)
Check interrupt flag of any LFSS Tamper interrupt.
Checks if any of the LFSS Tamper interrupts are pending. Interrupts do not have to be previously enabled.
Parameters
[in] lfss Pointer to the register overlay for the LFSS Tamper peripheral
[in] interruptMask Bit mask of interrupts to check. Logical OR of DL_LFSS_TAMPERIO_INTERRUPT
Returns
Which of the requested LFSS Tamper interrupts are pending
Return values
Logical OR of DL_LFSS_TAMPERIO_INTERRUPT values
DL_LFSS_TamperIO_getPendingInterrupt()
__STATIC_INLINE DL_LFSS_TAMPERIO_IIDX DL_LFSS_TamperIO_getPendingInterrupt (LFSS_Regs * lfss)
Get highest priority pending LFSS interrupt.
Checks if any of the LFSS interrupts are pending. Interrupts do not have to be previously enabled.
Parameters
[in] lfss Pointer to the register overlay for the LFSS Tamper peripheral
Returns
The highest priority pending LFSS Tamper interrupt
Return values
One of DL_LFSS_TAMPERIO_IIDX
DL_LFSS_TamperIO_clearInterruptStatus()
__STATIC_INLINE void DL_LFSS_TamperIO_clearInterruptStatus (LFSS_Regs * lfss, uint32_t interruptMask)
Clear pending LFSS Tamper interrupts.
Parameters
[in] lfss Pointer to the register overlay for the LFSS Tamper peripheral
[in] interruptMask Bit mask of interrupts to check. Logical OR of DL_LFSS_TAMPERIO_INTERRUPT
DL_LFSS_TamperIO_enableEvent()
__STATIC_INLINE void DL_LFSS_TamperIO_enableEvent (LFSS_Regs * lfss, uint32_t eventMask)
Enable LFSS Tamper event.
Parameters
[in] lfss Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to enable. Bitwise OR of DL_LFSS_TAMPERIO_EVENT.
DL_LFSS_TamperIO_disableEvent()
__STATIC_INLINE void DL_LFSS_TamperIO_disableEvent (LFSS_Regs * lfss, uint32_t eventMask)
Disable LFSS Tamper event.
Parameters
[in] lfss Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to enable. Bitwise OR of DL_LFSS_TAMPERIO_EVENT.
DL_LFSS_TamperIO_getEnabledEvents()
__STATIC_INLINE uint32_t DL_LFSS_TamperIO_getEnabledEvents (LFSS_Regs * lfss, uint32_t eventMask)
Check which LFSS Tamper events are enabled.
Parameters
[in] lfss Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to check. Bitwise OR of DL_LFSS_TAMPERIO_EVENT.
Returns
Which of the requested LFSS Tamper interrupts are enabled
Return values
Bitwise OR of DL_LFSS_TAMPERIO_EVENT values
DL_LFSS_TamperIO_getEnabledEventStatus()
__STATIC_INLINE uint32_t DL_LFSS_TamperIO_getEnabledEventStatus (LFSS_Regs * lfss, uint32_t eventMask)
Check event flag of enabled LFSS Tamper event.
Checks if any of the LFSS Tamper events that were previously enabled are pending.
Parameters
[in] lfss Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to check. Bitwise OR of DL_LFSS_TAMPERIO_EVENT.
Returns
Which of the requested LFSS Tamper interrupts are pending
Return values
Bitwise OR of DL_LFSS_TAMPERIO_EVENT values
See also
DL_LFSS_TamperIO_enableInterrupt
DL_LFSS_TamperIO_getRawEventsStatus()
__STATIC_INLINE uint32_t DL_LFSS_TamperIO_getRawEventsStatus (LFSS_Regs * lfss, uint32_t eventMask)
Check interrupt flag of any LFSS Tamper event.
Checks if any events are pending. Events do not have to be previously enabled.
Parameters
[in] lfss Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to check. Bitwise OR of DL_LFSS_TAMPERIO_EVENT.
Returns
Which of the requested LFSS Tamper interrupts are pending
Return values
Bitwise OR of DL_LFSS_TAMPERIO_EVENT values
DL_LFSS_TamperIO_clearEventsStatus()
__STATIC_INLINE void DL_LFSS_TamperIO_clearEventsStatus (LFSS_Regs * lfss, uint32_t eventMask)
Clear pending LFSS Tamper events.
Parameters
[in] lfss Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to clear. Bitwise OR of DL_LFSS_TAMPERIO_EVENT.
DL_LFSS_TamperIO_setPublisherChanID()
__STATIC_INLINE void DL_LFSS_TamperIO_setPublisherChanID (LFSS_Regs * lfss, uint8_t chanID)
Sets the LFSS Tamper event publisher channel ID.
Parameters
[in] lfss Pointer to the register overlay for the peripheral
[in] chanID Channel ID number. Valid range 0-15. If ChanID == 0 publisher is disconnected.
DL_LFSS_TamperIO_getPublisherChanID()
__STATIC_INLINE uint8_t DL_LFSS_TamperIO_getPublisherChanID (LFSS_Regs * lfss)
Gets the event publisher channel ID.
Parameters
[in] lfss Pointer to the register overlay for the peripheral
Returns
Event publisher channel ID
DL_LFSS_reset()
__STATIC_INLINE void DL_LFSS_reset (LFSS_Regs * lfss)
Requests a reset to the LFSS module.
Parameters
[in] lfss Pointer to the register overlay for the peripheral
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale