MSPM0L11XX_L13XX Driver Library: Factory Region (FACTORYREGION)
Factory Region (FACTORYREGION)
Functions
__STATIC_INLINE uint16_t DL_FactoryRegion_getMAINFlashSize (void)
Get the size of the MAIN Flash region.
__STATIC_INLINE uint16_t DL_FactoryRegion_getSRAMFlashSize (void)
Get the size of the SRAM Flash region.
__STATIC_INLINE uint8_t DL_FactoryRegion_getDATAFlashSize (void)
Get the size of the DATA Flash region.
__STATIC_INLINE uint8_t DL_FactoryRegion_getNumBanks (void)
Get the number of Flash banks on the device.
__STATIC_INLINE uint32_t DL_FactoryRegion_getTraceID (void)
Get the trace ID of the device.
__STATIC_INLINE uint16_t DL_FactoryRegion_getManufacturerCode (void)
Get JEDEC bank and company code.
__STATIC_INLINE uint16_t DL_FactoryRegion_getPartNumber (void)
Get the part number of the device.
__STATIC_INLINE uint8_t DL_FactoryRegion_getVersion (void)
Get the version of the device.
__STATIC_INLINE uint16_t DL_FactoryRegion_getUserIDPart (void)
Get the bit pattern identifying the part.
__STATIC_INLINE uint8_t DL_FactoryRegion_getUserIDVariant (void)
Get the bit pattern identifying a variant of a part.
__STATIC_INLINE uint8_t DL_FactoryRegion_getUserIDMinorRev (void)
Get the value that preserves compatibility with lesser minorrev values.
__STATIC_INLINE uint8_t DL_FactoryRegion_getUserIDMajorRev (void)
Get the value that preserves compatibility with lesser majorrev values.
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinUARTRXDPad (void)
Get the UART RXD PIN used by BSL.
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinUARTRXDFunction (void)
Get the UART RXD Pin function selection value used by BSL.
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinUARTTXDPad (void)
Get the UART TXD PIN used by BSL.
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinUARTTXDFunction (void)
Get the UART TXD Pin function selection value used by BSL.
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinI2CSDAPad (void)
Get the I2C SDA Pin used by BSL.
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinI2CSDAFunction (void)
Get the I2C SDA Pin function selection value used by BSL.
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinI2CSCLPad (void)
Get the I2C SCL Pin used by BSL.
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinI2CSCLFunction (void)
Get the I2C SCL Pin function selection value used by BSL.
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinInvokeGPIOLevel (void)
Get the GPIO level used by BSL pin invocation.
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinInvokeGPIOPin (void)
Get the GPIO Pin selection value used by BSL pin invocation.
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinInvokeGPIOModule (void)
Get the GPIO module selection used by BSL pin invocation.
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinInvokeGPIOModulePad (void)
Get the BSL invocation pin number.
__STATIC_INLINE uint32_t DL_FactoryRegion_getTemperatureVoltage (void)
Get the ADC conversion results of temperature sensor output voltage.
__STATIC_INLINE uint32_t DL_FactoryRegion_getBOOTCRCData (void)
Get the BOOTCRC value.
Detailed Description
Overview
Function Documentation
DL_FactoryRegion_getMAINFlashSize()
__STATIC_INLINE uint16_t DL_FactoryRegion_getMAINFlashSize (void)
Get the size of the MAIN Flash region.
Returns
The size of the MAIN Flash region in number of kB.
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
Referenced by DL_FlashCTL_getFlashSectorNumberInBank().
DL_FactoryRegion_getSRAMFlashSize()
__STATIC_INLINE uint16_t DL_FactoryRegion_getSRAMFlashSize (void)
Get the size of the SRAM Flash region.
Returns
The size of the SRAM Flash region in number of kB.
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getDATAFlashSize()
__STATIC_INLINE uint8_t DL_FactoryRegion_getDATAFlashSize (void)
Get the size of the DATA Flash region.
Returns
The size of the DATA Flash region in number of kB.
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getNumBanks()
__STATIC_INLINE uint8_t DL_FactoryRegion_getNumBanks (void)
Get the number of Flash banks on the device.
Returns
The number of flash banks. A value between [1, 4].
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
Referenced by DL_FlashCTL_getFlashSectorNumberInBank().
DL_FactoryRegion_getTraceID()
__STATIC_INLINE uint32_t DL_FactoryRegion_getTraceID (void)
Get the trace ID of the device.
Returns
The trace ID of the device.
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getManufacturerCode()
__STATIC_INLINE uint16_t DL_FactoryRegion_getManufacturerCode (void)
Get JEDEC bank and company code.
Returns
TI's JEDEC bank and company code
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getPartNumber()
__STATIC_INLINE uint16_t DL_FactoryRegion_getPartNumber (void)
Get the part number of the device.
Returns
The part number of the device
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getVersion()
__STATIC_INLINE uint8_t DL_FactoryRegion_getVersion (void)
Get the version of the device.
Returns
The version of the device
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getUserIDPart()
__STATIC_INLINE uint16_t DL_FactoryRegion_getUserIDPart (void)
Get the bit pattern identifying the part.
Returns
The bit pattern identifying the part
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getUserIDVariant()
__STATIC_INLINE uint8_t DL_FactoryRegion_getUserIDVariant (void)
Get the bit pattern identifying a variant of a part.
Returns
The bit pattern identifying a variant of a part
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getUserIDMinorRev()
__STATIC_INLINE uint8_t DL_FactoryRegion_getUserIDMinorRev (void)
Get the value that preserves compatibility with lesser minorrev values.
Monotonic increasing value indicating a new revision that preserves compatibility with lesser minorrev values. New capability may be introduced such that lesser minorrev numbers may not be compatible with greater if the new capability is used
Returns
The value that preserves compatibility with lesser minorrev values
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getUserIDMajorRev()
__STATIC_INLINE uint8_t DL_FactoryRegion_getUserIDMajorRev (void)
Get the value that preserves compatibility with lesser majorrev values.
Monotonic increasing value indicating a new revision significant enough that users of the device may have to revise PCB or or software design
Returns
The value that tells users they may have to revise PCB or majorrev design
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getBSLPinUARTRXDPad()
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinUARTRXDPad (void)
Get the UART RXD PIN used by BSL.
Returns
The UART RXD PIN used by BSL
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getBSLPinUARTRXDFunction()
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinUARTRXDFunction (void)
Get the UART RXD Pin function selection value used by BSL.
Returns
The UART RXD Pin function selection value used by BSL
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getBSLPinUARTTXDPad()
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinUARTTXDPad (void)
Get the UART TXD PIN used by BSL.
Returns
The UART TXD PIN used by BSL
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getBSLPinUARTTXDFunction()
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinUARTTXDFunction (void)
Get the UART TXD Pin function selection value used by BSL.
Returns
The UART TXD Pin function selection value used by BSL
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getBSLPinI2CSDAPad()
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinI2CSDAPad (void)
Get the I2C SDA Pin used by BSL.
Returns
The I2C SDA Pin used by BSL
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getBSLPinI2CSDAFunction()
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinI2CSDAFunction (void)
Get the I2C SDA Pin function selection value used by BSL.
Returns
The I2C SDA Pin function selection value used by BSL
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getBSLPinI2CSCLPad()
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinI2CSCLPad (void)
Get the I2C SCL Pin used by BSL.
Returns
The I2C SCL Pin used by BSL
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getBSLPinI2CSCLFunction()
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinI2CSCLFunction (void)
Get the I2C SCL Pin function selection value used by BSL.
Returns
The I2C SCL Pin function selection value used by BSL
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getBSLPinInvokeGPIOLevel()
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinInvokeGPIOLevel (void)
Get the GPIO level used by BSL pin invocation.
Returns
The GPIO level used by BSL pin invocation
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getBSLPinInvokeGPIOPin()
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinInvokeGPIOPin (void)
Get the GPIO Pin selection value used by BSL pin invocation.
Returns
The GPIO Pin selection value used by BSL pin invocation
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getBSLPinInvokeGPIOModule()
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinInvokeGPIOModule (void)
Get the GPIO module selection used by BSL pin invocation.
Returns
The GPIO module selection used by BSL pin invocation
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getBSLPinInvokeGPIOModulePad()
__STATIC_INLINE uint8_t DL_FactoryRegion_getBSLPinInvokeGPIOModulePad (void)
Get the BSL invocation pin number.
Returns
The BSL invocation pin number
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getTemperatureVoltage()
__STATIC_INLINE uint32_t DL_FactoryRegion_getTemperatureVoltage (void)
Get the ADC conversion results of temperature sensor output voltage.
Returns
The ADC conversion results of temperature sensor output voltage
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
DL_FactoryRegion_getBOOTCRCData()
__STATIC_INLINE uint32_t DL_FactoryRegion_getBOOTCRCData (void)
Get the BOOTCRC value.
The 32-bit CRC of all locations in OPEN including reserved locations.
Returns
The BOOTCRC value
References DL_CORE_CACHE_DISABLED, DL_CORE_configInstruction(), DL_CORE_getInstructionConfig(), DL_CORE_LITERAL_CACHE_ENABLED, and DL_CORE_PREFETCH_ENABLED.
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale