MSPM0L111X Driver Library: Keystore Controller (KEYSTORECTL)
Keystore Controller (KEYSTORECTL)
Modules
DL_KEYSTORECTL_KEY_SLOT
Data Structures
struct DL_KEYSTORECTL_KeyWrConfig
Configuration struct for DL_KEYSTORECTL_writeKey.
struct DL_KEYSTORECTL_Config
Configuration struct for DL_KEYSTORECTL_transferKey.
Enumerations
enum DL_KEYSTORECTL_NUM_256_KEYS {
DL_KEYSTORECTL_NUM_256_KEYS_ZERO = KEYSTORECTL_CFG_NK256_ZERO,
DL_KEYSTORECTL_NUM_256_KEYS_ONE = KEYSTORECTL_CFG_NK256_ONE,
DL_KEYSTORECTL_NUM_256_KEYS_TWO = KEYSTORECTL_CFG_NK256_TWO,
DL_KEYSTORECTL_NUM_256_KEYS_THREE = KEYSTORECTL_CFG_NK256_THREE,
DL_KEYSTORECTL_NUM_256_KEYS_FOUR = KEYSTORECTL_CFG_NK256_FOUR
}
enum DL_KEYSTORECTL_KEY_SIZE {
DL_KEYSTORECTL_KEY_SIZE_128_BITS = KEYSTORECTL_KEYWR_KEYSZSEL_K128,
DL_KEYSTORECTL_KEY_SIZE_256_BITS = KEYSTORECTL_KEYWR_KEYSZSEL_K256
}
enum DL_KEYSTORECTL_NUM_SLOTS {
DL_KEYSTORECTL_NUM_SLOTS_TWO = KEYSTORECTL_STATUS_NKEYSLOTS_TWO,
DL_KEYSTORECTL_NUM_SLOTS_THREE = KEYSTORECTL_STATUS_NKEYSLOTS_THREE,
DL_KEYSTORECTL_NUM_SLOTS_FOUR = KEYSTORECTL_STATUS_NKEYSLOTS_FOUR
}
enum DL_KEYSTORECTL_CRYPTO_SEL { DL_KEYSTORECTL_CRYPTO_SEL_AES = KEYSTORECTL_KEYRD_CRYPTOSEL_AES }
enum DL_KEYSTORECTL_STATUS {
DL_KEYSTORECTL_STATUS_VALID = KEYSTORECTL_STATUS_STAT_VALID,
DL_KEYSTORECTL_STATUS_NO_CONFIG = KEYSTORECTL_STATUS_STAT_NO_CFG,
DL_KEYSTORECTL_STATUS_INVALID_NUM_KEYS,
DL_KEYSTORECTL_STATUS_BUSY_RX = KEYSTORECTL_STATUS_STAT_BUSY_RECEIVE,
DL_KEYSTORECTL_STATUS_BUSY_TX = KEYSTORECTL_STATUS_STAT_BUSY_TRANSMIT,
DL_KEYSTORECTL_STATUS_INVALID_SLOT_WR,
DL_KEYSTORECTL_STATUS_INVALID_SLOT_RD,
DL_KEYSTORECTL_STATUS_WRITE_FAILED = 0x0BAD
}
Functions
__STATIC_INLINE void DL_KEYSTORECTL_setNumberOf256Keys (KEYSTORECTL_Regs *keystorectl, DL_KEYSTORECTL_NUM_256_KEYS numKeys)
Sets the number of combined 256 key slots.
__STATIC_INLINE DL_KEYSTORECTL_NUM_256_KEYS DL_KEYSTORECTL_getNumberOf256Keys (const KEYSTORECTL_Regs *keystorectl)
Returns the current number of combined 256 key slots.
__STATIC_INLINE void DL_KEYSTORECTL_setDestinationKeySlot (KEYSTORECTL_Regs *keystorectl, uint32_t keySlot)
Sets the intended destination key slot for the next write.
__STATIC_INLINE uint32_t DL_KEYSTORECTL_getDestinationKeySlot (const KEYSTORECTL_Regs *keystorectl)
Returns the intended destination key slot for the next write.
__STATIC_INLINE void DL_KEYSTORECTL_setDestinationKeySize (KEYSTORECTL_Regs *keystorectl, DL_KEYSTORECTL_KEY_SIZE keySize)
Sets the intended destination key slot size for next write.
__STATIC_INLINE DL_KEYSTORECTL_KEY_SIZE DL_KEYSTORECTL_getDestinationKeySize (const KEYSTORECTL_Regs *keystorectl)
Returns the intended destination key size for the next write.
void DL_KEYSTORECTL_loadKey (KEYSTORECTL_Regs *keystorectl, uint32_t *key)
Sets the intended destination key slot size for next write.
__STATIC_INLINE void DL_KEYSTORECTL_setSourceKeySlot (KEYSTORECTL_Regs *keystorectl, uint32_t keySlot)
Gets the intended source key slot for the next transfer.
__STATIC_INLINE uint32_t DL_KEYSTORECTL_getSourceKeySlot (const KEYSTORECTL_Regs *keystorectl)
Gets the intended source key slot for the next transfer.
__STATIC_INLINE void DL_KEYSTORECTL_setSourceKeySize (KEYSTORECTL_Regs *keystorectl, DL_KEYSTORECTL_KEY_SIZE keySize)
Gets the intended source key slot size for next transfer.
__STATIC_INLINE DL_KEYSTORECTL_KEY_SIZE DL_KEYSTORECTL_getSourceKeySize (const KEYSTORECTL_Regs *keystorectl)
Gets the intended source key size for the next transfer.
__STATIC_INLINE DL_KEYSTORECTL_STATUS DL_KEYSTORECTL_getStatus (const KEYSTORECTL_Regs *keystorectl)
Gets the current status of the KEYSTORECTL module.
__STATIC_INLINE uint32_t DL_KEYSTORECTL_getValidKeySlots (const KEYSTORECTL_Regs *keystorectl)
Gets currently written key slots.
__STATIC_INLINE DL_KEYSTORECTL_NUM_SLOTS DL_KEYSTORECTL_getNumSlots (const KEYSTORECTL_Regs *keystorectl)
Gets the total number of 128-bit key slots in HW on the device.
DL_KEYSTORECTL_STATUS DL_KEYSTORECTL_writeKey (KEYSTORECTL_Regs *keystorectl, DL_KEYSTORECTL_KeyWrConfig *keyWrConfig)
Writes a key into the KEYSTORE.
DL_KEYSTORECTL_STATUS DL_KEYSTORECTL_transferKey (KEYSTORECTL_Regs *keystorectl, const DL_KEYSTORECTL_Config *config)
Transfers key loaded in KEYSTORE into intended crypto.
Detailed Description
Overview
The Keystore Controller (KEYSTORECTL) DriverLib allows full configuration of the MSPM0 KEYSTORECTL Module.
Enumeration Type Documentation
DL_KEYSTORECTL_NUM_256_KEYS
enum DL_KEYSTORECTL_NUM_256_KEYS
Enumerator
DL_KEYSTORECTL_NUM_256_KEYS_ZERO
No 256-bit keys
DL_KEYSTORECTL_NUM_256_KEYS_ONE
One 256-bit keys
DL_KEYSTORECTL_NUM_256_KEYS_TWO
Two 256-bit keys
DL_KEYSTORECTL_NUM_256_KEYS_THREE
Three 256-bit keys
DL_KEYSTORECTL_NUM_256_KEYS_FOUR
Four 256-bit keys
DL_KEYSTORECTL_KEY_SIZE
enum DL_KEYSTORECTL_KEY_SIZE
Enumerator
DL_KEYSTORECTL_KEY_SIZE_128_BITS
Key size set to 128
DL_KEYSTORECTL_KEY_SIZE_256_BITS
Key size set to 256
DL_KEYSTORECTL_NUM_SLOTS
enum DL_KEYSTORECTL_NUM_SLOTS
Enumerator
DL_KEYSTORECTL_NUM_SLOTS_TWO
Two 128-bit key slots present on device
DL_KEYSTORECTL_NUM_SLOTS_THREE
Three 128-bit key slots present on device
DL_KEYSTORECTL_NUM_SLOTS_FOUR
Four 128-bit key slots present on device
DL_KEYSTORECTL_CRYPTO_SEL
enum DL_KEYSTORECTL_CRYPTO_SEL
Enumerator
DL_KEYSTORECTL_CRYPTO_SEL_AES
Transfer the key from keystore KEYSTORECTL to the AES engine
DL_KEYSTORECTL_STATUS
enum DL_KEYSTORECTL_STATUS
Enumerator
DL_KEYSTORECTL_STATUS_VALID
Valid status bit. Configuration is valid or operation completed.
DL_KEYSTORECTL_STATUS_NO_CONFIG
No Configuration Status bit, no number of 256 keys has been identified. The user must call DL_KEYSTORECTL_setNumberOf256Keys.
DL_KEYSTORECTL_STATUS_INVALID_NUM_KEYS
Invalid number set during DL_KEYSTORECTL_setNumberOf256Keys
DL_KEYSTORECTL_STATUS_BUSY_RX
Busy RX status bit. The engine is busy receiving a key deposit.
DL_KEYSTORECTL_STATUS_BUSY_TX
Busy TX status bit. The engine is busy transmitting a key to a crypto engine
DL_KEYSTORECTL_STATUS_INVALID_SLOT_WR
Invalid key write configuration. This means one or more of the following: the selected slot exceeds available slots, the selected slot already contains a valid programmed key, the selected slot has a mismatched key size compared to the KEYSTORECTL configuration.
DL_KEYSTORECTL_STATUS_INVALID_SLOT_RD
Invalid key read configuration (transmitting a key). This means one or more of the following: the selected slot exceeds available slots, the selected slot does not contain a valid programmed key, the selected slot has a mismatched key size
DL_KEYSTORECTL_STATUS_WRITE_FAILED
Key slots are not valid after a write. Write failed during the DL_KEYSTORECTL_writeKey (driver library specific).
Function Documentation
DL_KEYSTORECTL_setNumberOf256Keys()
__STATIC_INLINE void DL_KEYSTORECTL_setNumberOf256Keys (KEYSTORECTL_Regs * keystorectl, DL_KEYSTORECTL_NUM_256_KEYS numKeys)
Sets the number of combined 256 key slots.
For a given number of 128-bit key slots n, there can be up to n/2 slots combined to work as one 256-bit key slot. These larger slots are added to earlier slots first. Thus, a 4-slot device with one 256-key slot will have slots 0 and 1 combined, and slot 2 and 3 will remain 128-bit key slots. Refer to the device datasheet for the specific number of key slots.
Parameters
[in] keystorectl Pointer to the register overlay for the peripheral
[in] numKeys Number of 256-bit keys, one of DL_KEYSTORECTL_NUM_256_KEYS. Must be less than the total key slots on the device divided by two
Note
this function can only be written in a secure operating state before the INITDONE signal is asserted.
References DL_Common_updateReg().
DL_KEYSTORECTL_getNumberOf256Keys()
__STATIC_INLINE DL_KEYSTORECTL_NUM_256_KEYS DL_KEYSTORECTL_getNumberOf256Keys (const KEYSTORECTL_Regs * keystorectl)
Returns the current number of combined 256 key slots.
Parameters
[in] keystorectl Pointer to the register overlay for the peripheral
Returns
number of 256-bit keys. One of DL_KEYSTORECTL_NUM_256_KEYS
See also
DL_KEYSTORECTL_setNumberOf256Keys
DL_KEYSTORECTL_setDestinationKeySlot()
__STATIC_INLINE void DL_KEYSTORECTL_setDestinationKeySlot (KEYSTORECTL_Regs * keystorectl, uint32_t keySlot)
Sets the intended destination key slot for the next write.
Sets the destination key slot for a data write to that region. In the case of 128-bit key slot, only one slot should be selected. In the case of a 256- bit key slot, both registers should be selected and the key size should also reflect this change. If 256- it keys are desired, they should be configured using DL_KEYSTORECTL_NUM_256_KEYS. Refer to the device datasheet for the specific number of key slots.
Parameters
[in] keystorectl Pointer to the register overlay for the peripheral
[in] keySlot The intended key slot. Can be 128-bit or a 256-bit. One of DL_KEYSTORECTL_KEY_SLOT
Note
this function can only be written in a secure operating state before the INITDONE signal is asserted.
See also
DL_KEYSTORECTL_setNumberOf256Keys
DL_KEYSTORECTL_setDestinationKeySize
References DL_Common_updateReg().
DL_KEYSTORECTL_getDestinationKeySlot()
__STATIC_INLINE uint32_t DL_KEYSTORECTL_getDestinationKeySlot (const KEYSTORECTL_Regs * keystorectl)
Returns the intended destination key slot for the next write.
Refer to the device datasheet for the specific number of key slots.
Parameters
[in] keystorectl Pointer to the register overlay for the peripheral
Returns
The intended key slot. Can be 128-bit or a 256-bit. One of DL_KEYSTORECTL_KEY_SLOT
Note
this function can only be read in a secure operating state before the INITDONE signal is asserted.
See also
DL_KEYSTORECTL_setDestinationKeySlot
DL_KEYSTORECTL_setDestinationKeySize()
__STATIC_INLINE void DL_KEYSTORECTL_setDestinationKeySize (KEYSTORECTL_Regs * keystorectl, DL_KEYSTORECTL_KEY_SIZE keySize)
Sets the intended destination key slot size for next write.
Sets the destination key slot size for a data write to that region. If 256- bit keys are desired, they should be configured using DL_KEYSTORECTL_NUM_256_KEYS. Refer to the device datasheet for the specific number of key slots.
Parameters
[in] keystorectl Pointer to the register overlay for the peripheral
[in] keySize The intended key size. One of DL_KEYSTORECTL_KEY_SIZE
Note
this function can only be written in a secure operating state before the INITDONE signal is asserted.
See also
DL_KEYSTORECTL_setNumberOf256Keys
DL_KEYSTORECTL_setDestinationKeySlot
References DL_Common_updateReg().
DL_KEYSTORECTL_getDestinationKeySize()
__STATIC_INLINE DL_KEYSTORECTL_KEY_SIZE DL_KEYSTORECTL_getDestinationKeySize (const KEYSTORECTL_Regs * keystorectl)
Returns the intended destination key size for the next write.
Parameters
[in] keystorectl Pointer to the register overlay for the peripheral
Returns
The intended key size. One of DL_KEYSTORECTL_KEY_SIZE
Note
this function can only be read in a secure operating state before the INITDONE signal is asserted.
See also
DL_KEYSTORECTL_setDestinationKeySize
References DL_KEYSTORECTL_loadKey().
DL_KEYSTORECTL_loadKey()
void DL_KEYSTORECTL_loadKey (KEYSTORECTL_Regs * keystorectl, uint32_t * key)
Sets the intended destination key slot size for next write.
Loads a key of the provided size into the KEYSTORECTL provided there is a valid bit set. The specific intended slot and size should already be set by the user before using this. Refer to the device datasheet for the specific number of key slots.
Parameters
[in] keystorectl Pointer to the register overlay for the peripheral
[in] key Pointer to an uint32_t array containing the key.
Note
this function can only be written in a secure operating state before the INITDONE signal is asserted.
See also
DL_KEYSTORECTL_setDestinationKeySlot
DL_KEYSTORECTL_setDestinationKeySize
Referenced by DL_KEYSTORECTL_getDestinationKeySize().
DL_KEYSTORECTL_setSourceKeySlot()
__STATIC_INLINE void DL_KEYSTORECTL_setSourceKeySlot (KEYSTORECTL_Regs * keystorectl, uint32_t keySlot)
Gets the intended source key slot for the next transfer.
Sets the source key slot for a data transfer to another crypto peripheral. In the case of 128-bit key slot, only one slot should be selected. In the case of a 256-bit key slot, both registers should be selected and the key size should also reflect this change. If 256- it keys are desired, they can be accessed using DL_KEYSTORECTL_getNumberOf256Keys. Refer to the device datasheet for the specific number of key slots.
Parameters
[in] keystorectl Pointer to the register overlay for the peripheral
[in] keySlot The intended key slot. Can be 128-bit or a 256-bit. One of DL_KEYSTORECTL_KEY_SLOT
See also
DL_KEYSTORECTL_getNumOf256Keys
DL_KEYSTORECTL_setSourceKeySize
References DL_Common_updateReg().
DL_KEYSTORECTL_getSourceKeySlot()
__STATIC_INLINE uint32_t DL_KEYSTORECTL_getSourceKeySlot (const KEYSTORECTL_Regs * keystorectl)
Gets the intended source key slot for the next transfer.
Refer to the device datasheet for the specific number of key slots.
Parameters
[in] keystorectl Pointer to the register overlay for the peripheral
Returns
The intended key slot. Can be 128-bit or a 256-bit. One of DL_KEYSTORECTL_KEY_SLOT
See also
DL_KEYSTORECTL_setSourceKeySlot
DL_KEYSTORECTL_setSourceKeySize()
__STATIC_INLINE void DL_KEYSTORECTL_setSourceKeySize (KEYSTORECTL_Regs * keystorectl, DL_KEYSTORECTL_KEY_SIZE keySize)
Gets the intended source key slot size for next transfer.
Sets the source key slot size for a data transfer to that region. If 256- bit keys are desired, they should be configured using DL_KEYSTORECTL_NUM_256_KEYS. Refer to the device datasheet for the specific number of key slots.
Parameters
[in] keystorectl Pointer to the register overlay for the peripheral
[in] keySize The intended key size. One of DL_KEYSTORECTL_KEY_SIZE
See also
DL_KEYSTORECTL_setNumberOf256Keys
DL_KEYSTORECTL_setSourceKeySlot
References DL_Common_updateReg().
DL_KEYSTORECTL_getSourceKeySize()
__STATIC_INLINE DL_KEYSTORECTL_KEY_SIZE DL_KEYSTORECTL_getSourceKeySize (const KEYSTORECTL_Regs * keystorectl)
Gets the intended source key size for the next transfer.
Parameters
[in] keystorectl Pointer to the register overlay for the peripheral
Returns
The intended key size. One of DL_KEYSTORECTL_KEY_SIZE
See also
DL_KEYSTORECTL_setSourceKeySize
DL_KEYSTORECTL_getStatus()
__STATIC_INLINE DL_KEYSTORECTL_STATUS DL_KEYSTORECTL_getStatus (const KEYSTORECTL_Regs * keystorectl)
Gets the current status of the KEYSTORECTL module.
Parameters
[in] keystorectl Pointer to the register overlay for the peripheral
Returns
The status of the keystorectl. One of DL_KEYSTORECTL_STATUS
DL_KEYSTORECTL_getValidKeySlots()
__STATIC_INLINE uint32_t DL_KEYSTORECTL_getValidKeySlots (const KEYSTORECTL_Regs * keystorectl)
Gets currently written key slots.
To understand the key slot configuration, consider the configuration of the keys including the number of 256-bit keys, and the number of available key slots
Parameters
[in] keystorectl Pointer to the register overlay for the peripheral
Returns
Bitwise OR of all valid slots, corresponding to DL_KEYSTORECTL_KEY_SLOT values.
DL_KEYSTORECTL_getNumSlots()
__STATIC_INLINE DL_KEYSTORECTL_NUM_SLOTS DL_KEYSTORECTL_getNumSlots (const KEYSTORECTL_Regs * keystorectl)
Gets the total number of 128-bit key slots in HW on the device.
This is the number of key slots that the KEYSTORECTL module has in HW on the device. It does not reflect the configuration or the number of 256-bit keys, only the total number of slots. This also governs the valid configurations, and the number of 256-bit keys must be less than or equal to half the value.
Parameters
[in] keystorectl Pointer to the register overlay for the peripheral
Returns
The number of 128-bit slots on the device. One of DL_KEYSTORECTL_NUM_SLOTS
References DL_KEYSTORECTL_transferKey(), and DL_KEYSTORECTL_writeKey().
DL_KEYSTORECTL_writeKey()
DL_KEYSTORECTL_STATUS DL_KEYSTORECTL_writeKey (KEYSTORECTL_Regs * keystorectl, DL_KEYSTORECTL_KeyWrConfig * keyWrConfig)
Writes a key into the KEYSTORE.
The sequence this function will follow:
Confirm valid status on the KEYSTORECTL
Configure the key write by writing size and slot to the key that is to be written. Passed in via DL_KEYSTORECTL_KeyWrConfig
Confirm a valid write configuration
Write key to the input buffer
Loop until status is back to valid
Confirm key slots are successfully written
Parameters
[in] keystorectl Pointer to the register overlay for the peripheral
[in] keyWrConfig Pointer to the write key configuration struct DL_KEYSTORECTL_KeyWrConfig
Returns
Status of the operation of type DL_KEYSTORECTL_STATUS. Type will be DL_KEYSTORECTL_STATUS_VALID if successful, or return the error status.
Note
The function DL_KEYSTORECTL_setNumberOf256Keys must be run before this can be executed.
It is not possible to overwrite a previously configured key. A full BOOTRST must be executed before the KEYSTORECTL is erased and can be re-initialized and written.
this function can only be written in a secure operating state before the INITDONE signal is asserted.
Referenced by DL_KEYSTORECTL_getNumSlots().
DL_KEYSTORECTL_transferKey()
DL_KEYSTORECTL_STATUS DL_KEYSTORECTL_transferKey (KEYSTORECTL_Regs * keystorectl, const DL_KEYSTORECTL_Config * config)
Transfers key loaded in KEYSTORE into intended crypto.
Combination of previous functions in order to give the entire operation. Expected runtime sequence:
Confirm valid status on the KEYSTORECTL
Configure the read transfer by writing size, slot, and recipient This is passed in via the struct DL_KEYSTORECTL_Config
Confirm a valid status and transfer configuration of the KEYSTORECTL
Loop until status is back to valid
Parameters
[in] keystorectl Pointer to the register overlay for the peripheral
[in] config Pointer to a filled out config struct of type DL_KEYSTORECTL_Config
Returns
Status of the operation of type DL_KEYSTORECTL_STATUS. Type will be DL_KEYSTORECTL_STATUS_VALID if successful, or return the error status.
Referenced by DL_KEYSTORECTL_getNumSlots().
Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale