MSPM0G1X0X_G3X0X TI-Driver Library: UART driver APIs
UART driver APIs
Universal Asynchronous Receiver-Transmitter (UART)
Data Structures
struct UARTMSP_HWAttrs
Private Metadata structure for a UART instance supporting hardware parameters.
Macros
#define UART_RX_ERRS
UART receive errors.
Functions
__STATIC_INLINE UART_Object * UART_Obj_Ptr (UART_Handle handle)
This function returns a pointer to UART object.
__STATIC_INLINE UARTMSP_HWAttrs * UART_HWAttrs_Ptr (UART_Handle handle)
This function returns a pointer to UART hardware Attribute.
__STATIC_INLINE UART_Buffers_Object * UART_buffersObject (UART_Object *object)
This function returns a pointer to UART buffers object.
__STATIC_INLINE UART_EventCallback_Object * UART_eventCallbackObject (UART_Object *object)
This function returns a pointer to UART event callback object.
__STATIC_INLINE UART_Callback_Object * UART_callbackObject (UART_Object *object)
This function returns a pointer to UART callback object.
void UARTMSP_interruptHandler (UART_Handle handle)
This function handles the UART interrupts.
void UARTMSP_dmaTx (UART_Handle handle)
This function configures and starts DMA transfer.
void UARTMSP_dmaRx (UART_Handle handle, bool copyfifo)
This function configures and starts DMA receive.
void UARTMSP_dmaStopRx (UART_Handle handle)
This function stops DMA rx and disables the channel.
uint32_t UARTMSP_dmaStopTx (UART_Handle handle)
This function stops DMA tx and disables the channel.
void UARTMSP_enableInts (UART_Handle handle)
This function enables receive, receive timeout, and error interrupts.
Variables
const UARTSupport_Fxns UARTMSPSupportFxns
UART support function pointers.
Detailed Description
Overview
Refer to ti_drivers_UART_Overview for a complete description of APIs and examples of use.
Macro Definition Documentation
UART_RX_ERRS
#define UART_RX_ERRS
Value:
(DL_UART_INTERRUPT_OVERRUN_ERROR | DL_UART_INTERRUPT_BREAK_ERROR | \
        DL_UART_INTERRUPT_PARITY_ERROR |                                  \
        DL_UART_INTERRUPT_FRAMING_ERROR)
UART receive errors.
Function Documentation
UART_Obj_Ptr()
__STATIC_INLINE UART_Object* UART_Obj_Ptr (UART_Handle handle)
This function returns a pointer to UART object.
Precondition
Config Parameters. Calling context: function
Parameters
handle A UART handle return by UART_open()
Returns
Return a UART object pointer.
References UART_Config_::object.
UART_HWAttrs_Ptr()
__STATIC_INLINE UARTMSP_HWAttrs* UART_HWAttrs_Ptr (UART_Handle handle)
This function returns a pointer to UART hardware Attribute.
Precondition
Config Parameters. Calling context: function
Parameters
handle A UART handle return by UART_open().
Returns
Return a UART HWAttrs pointer.
References UART_Config_::hwAttrs.
UART_buffersObject()
__STATIC_INLINE UART_Buffers_Object* UART_buffersObject (UART_Object * object)
This function returns a pointer to UART buffers object.
Precondition
Config Parameters. Calling context: function
Parameters
*object A UART object pointer.
Returns
Return a UART buffers object pointer.
Referenced by UART_eventCallbackObject().
UART_eventCallbackObject()
__STATIC_INLINE UART_EventCallback_Object* UART_eventCallbackObject (UART_Object * object)
This function returns a pointer to UART event callback object.
Precondition
Config Parameters. Calling context: function
Parameters
*object A UART object pointer.
Returns
Return a UART event callback object pointer.
References UART_buffersObject().
Referenced by UART_callbackObject().
UART_callbackObject()
__STATIC_INLINE UART_Callback_Object* UART_callbackObject (UART_Object * object)
This function returns a pointer to UART callback object.
Precondition
Config Parameters. Calling context: function
Parameters
*object A UART object pointer.
Returns
Return a UART callback object pointer.
References UART_eventCallbackObject(), UARTMSP_dmaRx(), UARTMSP_dmaStopRx(), UARTMSP_dmaStopTx(), UARTMSP_dmaTx(), UARTMSP_enableInts(), and UARTMSP_interruptHandler().
UARTMSP_interruptHandler()
void UARTMSP_interruptHandler (UART_Handle handle)
This function handles the UART interrupts.
Precondition
Config Parameters.
Parameters
handle A UART handle return by UART_open().
Returns
void
Referenced by UART_callbackObject().
UARTMSP_dmaTx()
void UARTMSP_dmaTx (UART_Handle handle)
This function configures and starts DMA transfer.
Precondition
Config Parameters. Calling context: Task
Parameters
handle A UART handle return by UART_open().
Returns
void
See also
UART_open()
Referenced by UART_callbackObject().
UARTMSP_dmaRx()
void UARTMSP_dmaRx (UART_Handle handle, bool copyfifo)
This function configures and starts DMA receive.
Precondition
Config Parameters. Calling context: Task
Parameters
handle A UART handle return by UART_open().
copyfifo true: copy fifo. false: don't copy fifo.
Returns
void
See also
UART_open()
Referenced by UART_callbackObject().
UARTMSP_dmaStopRx()
void UARTMSP_dmaStopRx (UART_Handle handle)
This function stops DMA rx and disables the channel.
Precondition
Config Parameters. Calling context: Task
Parameters
handle A UART handle return by UART_open().
Returns
void
See also
UART_open()
Referenced by UART_callbackObject().
UARTMSP_dmaStopTx()
uint32_t UARTMSP_dmaStopTx (UART_Handle handle)
This function stops DMA tx and disables the channel.
Precondition
Config Parameters. Calling context: Task
Parameters
handle A UART handle return by UART_open().
Returns
Returns the remaining bytes to transmit.
See also
UART_open()
Referenced by UART_callbackObject().
UARTMSP_enableInts()
void UARTMSP_enableInts (UART_Handle handle)
This function enables receive, receive timeout, and error interrupts.
Precondition
Config Parameters. Calling context: Task
Parameters
handle A UART handle return by UART_open().
Returns
void
See also
UART_open()
Referenced by UART_callbackObject().
© Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale