MSPM0G1X0X_G3X0X Driver Library: Real Time Clock (RTC)
Real Time Clock (RTC)
Modules
DL_RTC_INTERRUPT
DL_RTC_EVENT
Data Structures
struct DL_RTC_CalendarAlarm
Alarm struct to use in DL_RTC_setCalendarAlarm.
struct DL_RTC_Calendar
Calendar struct to use in DL_RTC_initCalendar()
Enumerations
enum DL_RTC_STATUS {
DL_RTC_STATUS_READY = RTC_STA_RTCRDY_READY,
DL_RTC_STATUS_NOT_READY = RTC_STA_RTCRDY_NOT_READY
}
enum DL_RTC_COMPENSATION_STATUS {
DL_RTC_COMPENSATION_STATUS_READY = RTC_STA_RTCTCRDY_READY,
DL_RTC_COMPENSATION_STATUS_NOT_READY = RTC_STA_RTCTCRDY_NOT_READY
}
enum DL_RTC_COMPENSATION_WRITE_RESULT {
DL_RTC_COMPENSATION_WRITE_RESULT_OK = RTC_STA_RTCTCOK_OK,
DL_RTC_COMPENSATION_WRITE_RESULT_NOT_OK = RTC_STA_RTCTCOK_NOT_OK
}
enum DL_RTC_OFFSET_CALIBRATION_SIGN {
DL_RTC_OFFSET_CALIBRATION_SIGN_DOWN = RTC_CAL_RTCOCALS_DOWN,
DL_RTC_OFFSET_CALIBRATION_SIGN_UP = RTC_CAL_RTCOCALS_UP
}
enum DL_RTC_OFFSET_CALIBRATION_FREQUENCY {
DL_RTC_OFFSET_CALIBRATION_FREQUENCY_OFF = RTC_CAL_RTCCALFX_OFF,
DL_RTC_OFFSET_CALIBRATION_FREQUENCY_512 = RTC_CAL_RTCCALFX_F512HZ,
DL_RTC_OFFSET_CALIBRATION_FREQUENCY_256 = RTC_CAL_RTCCALFX_F256HZ,
DL_RTC_OFFSET_CALIBRATION_FREQUENCY_1 = RTC_CAL_RTCCALFX_F1HZ
}
enum DL_RTC_TEMP_CALIBRATION {
DL_RTC_TEMP_CALIBRATION_DOWN1PPM = RTC_TCMP_RTCTCMPS_DOWN,
DL_RTC_TEMP_CALIBRATION_UP1PPM = RTC_TCMP_RTCTCMPS_UP
}
enum DL_RTC_FORMAT {
DL_RTC_FORMAT_BINARY = RTC_CTL_RTCBCD_BINARY,
DL_RTC_FORMAT_BCD = RTC_CTL_RTCBCD_BCD
}
enum DL_RTC_INTERVAL_ALARM {
DL_RTC_INTERVAL_ALARM_MINUTECHANGE = RTC_CTL_RTCTEVTX_MINUTE,
DL_RTC_INTERVAL_ALARM_HOURCHANGE = RTC_CTL_RTCTEVTX_HOUR,
DL_RTC_INTERVAL_ALARM_NOON = RTC_CTL_RTCTEVTX_NOON,
DL_RTC_INTERVAL_ALARM_MIDNIGHT = RTC_CTL_RTCTEVTX_MIDNIGHT
}
enum DL_RTC_PRESCALER0_DIVIDE {
DL_RTC_PRESCALER0_DIVIDE_8 = RTC_PSCTL_RT0IP_DIV8,
DL_RTC_PRESCALER0_DIVIDE_16 = RTC_PSCTL_RT0IP_DIV16,
DL_RTC_PRESCALER0_DIVIDE_32 = RTC_PSCTL_RT0IP_DIV32,
DL_RTC_PRESCALER0_DIVIDE_64 = RTC_PSCTL_RT0IP_DIV64,
DL_RTC_PRESCALER0_DIVIDE_128 = RTC_PSCTL_RT0IP_DIV128,
DL_RTC_PRESCALER0_DIVIDE_256 = RTC_PSCTL_RT0IP_DIV256
}
enum DL_RTC_PRESCALER1_DIVIDE {
DL_RTC_PRESCALER1_DIVIDE_2 = RTC_PSCTL_RT1IP_DIV2,
DL_RTC_PRESCALER1_DIVIDE_4 = RTC_PSCTL_RT1IP_DIV4,
DL_RTC_PRESCALER1_DIVIDE_8 = RTC_PSCTL_RT1IP_DIV8,
DL_RTC_PRESCALER1_DIVIDE_16 = RTC_PSCTL_RT1IP_DIV16,
DL_RTC_PRESCALER1_DIVIDE_32 = RTC_PSCTL_RT1IP_DIV32,
DL_RTC_PRESCALER1_DIVIDE_64 = RTC_PSCTL_RT1IP_DIV64,
DL_RTC_PRESCALER1_DIVIDE_128 = RTC_PSCTL_RT1IP_DIV128,
DL_RTC_PRESCALER1_DIVIDE_256 = RTC_PSCTL_RT1IP_DIV256
}
enum DL_RTC_IIDX {
DL_RTC_IIDX_ALARM1 = RTC_CPU_INT_IIDX_STAT_RTCA1,
DL_RTC_IIDX_ALARM2 = RTC_CPU_INT_IIDX_STAT_RTCA2,
DL_RTC_IIDX_PRESCALER0 = RTC_CPU_INT_IIDX_STAT_RT0PS,
DL_RTC_IIDX_PRESCALER1 = RTC_CPU_INT_IIDX_STAT_RT1PS,
DL_RTC_IIDX_INTERVAL_TIMER = RTC_CPU_INT_IIDX_STAT_RTCTEV,
DL_RTC_IIDX_READY = RTC_CPU_INT_IIDX_STAT_RTCRDY
}
Functions
__STATIC_INLINE void DL_RTC_enablePower (RTC_Regs *rtc)
Enable power to the RTC module.
__STATIC_INLINE void DL_RTC_disablePower (RTC_Regs *rtc)
Disable power to the RTC module.
__STATIC_INLINE bool DL_RTC_isPowerEnabled (RTC_Regs *rtc)
Returns if power is enabled for the RTC module.
__STATIC_INLINE void DL_RTC_reset (RTC_Regs *rtc)
Resets all registers in the RTC module.
__STATIC_INLINE bool DL_RTC_isReset (RTC_Regs *rtc)
Returns if the RTC module was reset.
__STATIC_INLINE void DL_RTC_enableClockControl (RTC_Regs *rtc)
Enables the supply of the 32kHz clock to the RTC. It will not power up the 32kHz crystal oscillator. This needs to be done in the Clock System Module.
__STATIC_INLINE void DL_RTC_disableClockControl (RTC_Regs *rtc)
Disables the supply of the 32kHz clock to the RTC.
__STATIC_INLINE void DL_RTC_enableDebugInterrupts (RTC_Regs *rtc)
Enables interrupts when the CPU is in debug mode. Interrupt requests are signaled to the interrupt controller.
__STATIC_INLINE void DL_RTC_disableDebugInterrupts (RTC_Regs *rtc)
Disables interrupts when the CPU is in debug mode. Interrupts of the RTC module will not be captured. There will be no updates to the RTCRIS, RTCMISC and RTCIIDX registers.
__STATIC_INLINE void DL_RTC_enableDebugMode (RTC_Regs *rtc)
Enables the RTC modules debug mode.
__STATIC_INLINE void DL_RTC_disableDebugMode (RTC_Regs *rtc)
Disables the RTC modules debug mode.
__STATIC_INLINE void DL_RTC_setClockFormat (RTC_Regs *rtc, DL_RTC_FORMAT formatSelect)
Set the format of the real-time clock.
__STATIC_INLINE DL_RTC_FORMAT DL_RTC_getClockFormat (RTC_Regs *rtc)
Get the format currently being used for counting the real-time clock.
__STATIC_INLINE void DL_RTC_setIntervalAlarm (RTC_Regs *rtc, DL_RTC_INTERVAL_ALARM alarmEvent)
Sets the interval alarm event condition.
__STATIC_INLINE DL_RTC_INTERVAL_ALARM DL_RTC_getIntervalAlarm (RTC_Regs *rtc)
Gets the interval alarm event condition.
__STATIC_INLINE bool DL_RTC_isSafetoRead (RTC_Regs *rtc)
Checks if RTC is safe for reading.
__STATIC_INLINE bool DL_RTC_isReadyToCalibrate (RTC_Regs *rtc)
Checks if RTC is ready to get new calibration values.
__STATIC_INLINE bool DL_RTC_isCalibrationWriteResultOK (RTC_Regs *rtc)
Checks if RTC new calibration values were written OK.
__STATIC_INLINE void DL_RTC_setOffsetCalibrationFrequency (RTC_Regs *rtc, DL_RTC_OFFSET_CALIBRATION_FREQUENCY offsetFrequency)
Sets output frequency for offset calibration.
__STATIC_INLINE void DL_RTC_setOffsetCalibrationAdjValue (RTC_Regs *rtc, DL_RTC_OFFSET_CALIBRATION_SIGN offsetSign, uint8_t offsetValue)
Sets the offset error calibration adjustment value.
__STATIC_INLINE void DL_RTC_setOffsetCalibration (RTC_Regs *rtc, DL_RTC_OFFSET_CALIBRATION_FREQUENCY offsetFrequency, DL_RTC_OFFSET_CALIBRATION_SIGN offsetSign, uint8_t offsetValue)
Sets the offset error calibration.
__STATIC_INLINE DL_RTC_OFFSET_CALIBRATION_FREQUENCY DL_RTC_getOffsetCalibrationFrequency (RTC_Regs *rtc)
Gets the offset calibration frequency.
__STATIC_INLINE DL_RTC_OFFSET_CALIBRATION_SIGN DL_RTC_getOffsetCalibrationSign (RTC_Regs *rtc)
Gets the offset calibration sign.
__STATIC_INLINE uint32_t DL_RTC_getOffsetCalibrationValue (RTC_Regs *rtc)
Gets the offset error calibration value.
__STATIC_INLINE void DL_RTC_setTemperatureCompensation (RTC_Regs *rtc, DL_RTC_TEMP_CALIBRATION offsetDirection, uint32_t offsetValue)
Set the specified RTC temperature compensation.
__STATIC_INLINE uint32_t DL_RTC_getTemperatureCompensation (RTC_Regs *rtc)
Get the RTC temperature compensation.
__STATIC_INLINE void DL_RTC_setCalendarSecondsBCD (RTC_Regs *rtc, uint8_t seconds)
Set the seconds in BCD in the RTC calendar.
__STATIC_INLINE uint8_t DL_RTC_getCalendarSecondsBCD (RTC_Regs *rtc)
Get the seconds in in BCD the RTC calendar.
__STATIC_INLINE void DL_RTC_setCalendarMinutesBCD (RTC_Regs *rtc, uint8_t minutes)
Set the minutes in in BCD the RTC calendar.
__STATIC_INLINE uint8_t DL_RTC_getCalendarMinutesBCD (RTC_Regs *rtc)
Get the minutes in in BCD the RTC calendar.
__STATIC_INLINE void DL_RTC_setCalendarHoursBCD (RTC_Regs *rtc, uint8_t hours)
Set the hours in in BCD the RTC calendar.
__STATIC_INLINE uint8_t DL_RTC_getCalendarHoursBCD (RTC_Regs *rtc)
Get the hours in in BCD the RTC calendar.
__STATIC_INLINE void DL_RTC_setCalendarDayOfWeekBCD (RTC_Regs *rtc, uint8_t day)
Set the day of the week in BCD in the RTC calendar.
__STATIC_INLINE uint8_t DL_RTC_getCalendarDayOfWeekBCD (RTC_Regs *rtc)
Get the day of the week in BCD in the RTC calendar.
__STATIC_INLINE void DL_RTC_setCalendarDayOfMonthBCD (RTC_Regs *rtc, uint8_t day)
Set the day of the month in BCD in the RTC calendar.
__STATIC_INLINE uint8_t DL_RTC_getCalendarDayOfMonthBCD (RTC_Regs *rtc)
Get the day of the month in BCD in the RTC calendar.
__STATIC_INLINE void DL_RTC_setCalendarMonthBCD (RTC_Regs *rtc, uint8_t month)
Set the month in in BCD the RTC calendar.
__STATIC_INLINE uint8_t DL_RTC_getCalendarMonthBCD (RTC_Regs *rtc)
Get the month of the year in BCD in the RTC calendar.
__STATIC_INLINE void DL_RTC_setCalendarYearBCD (RTC_Regs *rtc, uint16_t year)
Set the year in in BCD the RTC calendar.
__STATIC_INLINE uint16_t DL_RTC_getCalendarYearBCD (RTC_Regs *rtc)
Get the year in in BCD the RTC calendar.
__STATIC_INLINE void DL_RTC_enableAlarm1MinutesBCD (RTC_Regs *rtc)
Enable minutes in BCD for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_disableAlarm1MinutesBCD (RTC_Regs *rtc)
Disable minutes in BCD for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_setAlarm1MinutesBCD (RTC_Regs *rtc, uint8_t minutes)
Set the minutes in BCD for RTC Calendar Alarm 1.
__STATIC_INLINE uint8_t DL_RTC_getAlarm1MinutesBCD (RTC_Regs *rtc)
Get the minutes in BCD for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_enableAlarm1HoursBCD (RTC_Regs *rtc)
Enable hours in BCD for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_disableAlarm1HoursBCD (RTC_Regs *rtc)
Disable hours in BCD for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_setAlarm1HoursBCD (RTC_Regs *rtc, uint8_t hours)
Set the hours in BCD for RTC Calendar Alarm 1.
__STATIC_INLINE uint8_t DL_RTC_getAlarm1HoursBCD (RTC_Regs *rtc)
Get the hours in BCD for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_enableAlarm1DayOfWeekBCD (RTC_Regs *rtc)
Enable day of the week in BCD for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_disableAlarm1DayOfWeekBCD (RTC_Regs *rtc)
Disable day of the week in BCD for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_setAlarm1DayOfWeekBCD (RTC_Regs *rtc, uint8_t day)
Set the day of the week in BCD for RTC Calendar Alarm 1.
__STATIC_INLINE uint8_t DL_RTC_getAlarm1DayOfWeekBCD (RTC_Regs *rtc)
Get the day of the week in BCD for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_enableAlarm1DayOfMonthBCD (RTC_Regs *rtc)
Enable day of the month in BCD for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_disableAlarm1DayOfMonthBCD (RTC_Regs *rtc)
Disable day of the month in BCD for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_setAlarm1DayOfMonthBCD (RTC_Regs *rtc, uint8_t day)
Set the day of the month in BCD for RTC Calendar Alarm 1.
__STATIC_INLINE uint8_t DL_RTC_getAlarm1DayOfMonthBCD (RTC_Regs *rtc)
Get the day of the month in BCD for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_enableAlarm2MinutesBCD (RTC_Regs *rtc)
Enable minutes in BCD for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_disableAlarm2MinutesBCD (RTC_Regs *rtc)
Disable minutes in BCD for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_setAlarm2MinutesBCD (RTC_Regs *rtc, uint8_t minutes)
Set the minutes in BCD for RTC Calendar Alarm 2.
__STATIC_INLINE uint8_t DL_RTC_getAlarm2MinutesBCD (RTC_Regs *rtc)
Get the minutes in BCD for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_enableAlarm2HoursBCD (RTC_Regs *rtc)
Enable hours in BCD for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_disableAlarm2HoursBCD (RTC_Regs *rtc)
Disable hours in BCD for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_setAlarm2HoursBCD (RTC_Regs *rtc, uint8_t hours)
Set the hours in BCD for RTC Calendar Alarm 2.
__STATIC_INLINE uint8_t DL_RTC_getAlarm2HoursBCD (RTC_Regs *rtc)
Get the hours in BCD for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_enableAlarm2DayOfWeekBCD (RTC_Regs *rtc)
Enable day of the week in BCD for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_disableAlarm2DayOfWeekBCD (RTC_Regs *rtc)
Disable day of the week in BCD for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_setAlarm2DayOfWeekBCD (RTC_Regs *rtc, uint8_t day)
Set the day of the week in BCD for RTC Calendar Alarm 2.
__STATIC_INLINE uint8_t DL_RTC_getAlarm2DayOfWeekBCD (RTC_Regs *rtc)
Get the day of the week in BCD for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_enableAlarm2DayOfMonthBCD (RTC_Regs *rtc)
Enable day of the month in BCD for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_disableAlarm2DayOfMonthBCD (RTC_Regs *rtc)
Disable day of the month in BCD for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_setAlarm2DayOfMonthBCD (RTC_Regs *rtc, uint8_t day)
Set the day of the month in BCD for RTC Calendar Alarm 2.
__STATIC_INLINE uint8_t DL_RTC_getAlarm2DayOfMonthBCD (RTC_Regs *rtc)
Get the day of the month in BCD for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_setCalendarSecondsBinary (RTC_Regs *rtc, uint8_t seconds)
Set the seconds in binary the RTC calendar.
__STATIC_INLINE uint8_t DL_RTC_getCalendarSecondsBinary (RTC_Regs *rtc)
Get the seconds in binary in the RTC calendar.
__STATIC_INLINE void DL_RTC_setCalendarMinutesBinary (RTC_Regs *rtc, uint8_t minutes)
Set the minutes in binary in the RTC calendar.
__STATIC_INLINE uint8_t DL_RTC_getCalendarMinutesBinary (RTC_Regs *rtc)
Get the minutes in binary in the RTC calendar.
__STATIC_INLINE void DL_RTC_setCalendarHoursBinary (RTC_Regs *rtc, uint8_t hours)
Set the hours in binary in the RTC calendar.
__STATIC_INLINE uint8_t DL_RTC_getCalendarHoursBinary (RTC_Regs *rtc)
Get the hours in binary in the RTC calendar.
__STATIC_INLINE void DL_RTC_setCalendarDayOfWeekBinary (RTC_Regs *rtc, uint8_t day)
Set the day of the week in binary in the RTC calendar.
__STATIC_INLINE uint8_t DL_RTC_getCalendarDayOfWeekBinary (RTC_Regs *rtc)
Get the day of the week in binary in the RTC calendar.
__STATIC_INLINE void DL_RTC_setCalendarDayOfMonthBinary (RTC_Regs *rtc, uint8_t day)
Set the day of the month in binary in the RTC calendar.
__STATIC_INLINE uint8_t DL_RTC_getCalendarDayOfMonthBinary (RTC_Regs *rtc)
Get the day of the month in binary in the RTC calendar.
__STATIC_INLINE void DL_RTC_setCalendarMonthBinary (RTC_Regs *rtc, uint8_t month)
Set the month in binary in the RTC calendar.
__STATIC_INLINE uint8_t DL_RTC_getCalendarMonthBinary (RTC_Regs *rtc)
Get the month of the year in binary in the RTC calendar.
__STATIC_INLINE void DL_RTC_setCalendarYearBinary (RTC_Regs *rtc, uint16_t year)
Set the year in binary in the RTC calendar.
__STATIC_INLINE uint16_t DL_RTC_getCalendarYearBinary (RTC_Regs *rtc)
Get the year in binary in the RTC calendar.
__STATIC_INLINE void DL_RTC_enableAlarm1MinutesBinary (RTC_Regs *rtc)
Enable minutes in binary in binary for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_disableAlarm1MinutesBinary (RTC_Regs *rtc)
Disable minutes in binary for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_setAlarm1MinutesBinary (RTC_Regs *rtc, uint8_t minutes)
Set the minutes in binary for RTC Calendar Alarm 1.
__STATIC_INLINE uint8_t DL_RTC_getAlarm1MinutesBinary (RTC_Regs *rtc)
Get the minutes in binary for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_enableAlarm1HoursBinary (RTC_Regs *rtc)
Enable hours in binary for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_disableAlarm1HoursBinary (RTC_Regs *rtc)
Disable hours in binary for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_setAlarm1HoursBinary (RTC_Regs *rtc, uint8_t hours)
Set the hours in binary for RTC Calendar Alarm 1.
__STATIC_INLINE uint8_t DL_RTC_getAlarm1HoursBinary (RTC_Regs *rtc)
Get the hours in binary for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_enableAlarm1DayOfWeekBinary (RTC_Regs *rtc)
Enable day of the week in binary for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_disableAlarm1DayOfWeekBinary (RTC_Regs *rtc)
Disable day of the week in binary for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_setAlarm1DayOfWeekBinary (RTC_Regs *rtc, uint8_t day)
Set the day of the week in binary for RTC Calendar Alarm 1.
__STATIC_INLINE uint8_t DL_RTC_getAlarm1DayOfWeekBinary (RTC_Regs *rtc)
Get the day of the week in binary for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_enableAlarm1DayOfMonthBinary (RTC_Regs *rtc)
Enable day of the month in binary for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_disableAlarm1DayOfMonthBinary (RTC_Regs *rtc)
Disable day of the month in binary for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_setAlarm1DayOfMonthBinary (RTC_Regs *rtc, uint8_t day)
Set the day of the month in binary for RTC Calendar Alarm 1.
__STATIC_INLINE uint8_t DL_RTC_getAlarm1DayOfMonthBinary (RTC_Regs *rtc)
Get the day of the month in binary for RTC Calendar Alarm 1.
__STATIC_INLINE void DL_RTC_enableAlarm2MinutesBinary (RTC_Regs *rtc)
Enable minutes in binary for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_disableAlarm2MinutesBinary (RTC_Regs *rtc)
Disable minutes in binary for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_setAlarm2MinutesBinary (RTC_Regs *rtc, uint8_t minutes)
Set the minutes in binary for RTC Calendar Alarm 2.
__STATIC_INLINE uint8_t DL_RTC_getAlarm2MinutesBinary (RTC_Regs *rtc)
Get the minutes in binary for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_enableAlarm2HoursBinary (RTC_Regs *rtc)
Enable hours in binary for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_disableAlarm2HoursBinary (RTC_Regs *rtc)
Disable hours in binary for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_setAlarm2HoursBinary (RTC_Regs *rtc, uint8_t hours)
Set the hours in binary for RTC Calendar Alarm 2.
__STATIC_INLINE uint8_t DL_RTC_getAlarm2HoursBinary (RTC_Regs *rtc)
Get the hours in binary for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_enableAlarm2DayOfWeekBinary (RTC_Regs *rtc)
Enable day of the week in binary for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_disableAlarm2DayOfWeekBinary (RTC_Regs *rtc)
Disable day of the week in binary for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_setAlarm2DayOfWeekBinary (RTC_Regs *rtc, uint8_t day)
Set the day of the week in binary for RTC Calendar Alarm 2.
__STATIC_INLINE uint8_t DL_RTC_getAlarm2DayOfWeekBinary (RTC_Regs *rtc)
Get the day of the week in binary for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_enableAlarm2DayOfMonthBinary (RTC_Regs *rtc)
Enable day of the month in binary for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_disableAlarm2DayOfMonthBinary (RTC_Regs *rtc)
Disable day of the month in binary for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_setAlarm2DayOfMonthBinary (RTC_Regs *rtc, uint8_t day)
Set the day of the month in binary for RTC Calendar Alarm 2.
__STATIC_INLINE uint8_t DL_RTC_getAlarm2DayOfMonthBinary (RTC_Regs *rtc)
Get the day of the month in binary for RTC Calendar Alarm 2.
__STATIC_INLINE void DL_RTC_setPrescalerEvents (RTC_Regs *rtc, DL_RTC_PRESCALER0_DIVIDE prescaler0Divider, DL_RTC_PRESCALER1_DIVIDE prescaler1Divider)
Set prescale interrupt interval for timer 0 and 1.
__STATIC_INLINE void DL_RTC_setPeriodicAlarm0 (RTC_Regs *rtc, DL_RTC_PRESCALER0_DIVIDE prescaler0Divider)
Set periodic alarm 0.
__STATIC_INLINE void DL_RTC_setPeriodicAlarm1 (RTC_Regs *rtc, DL_RTC_PRESCALER1_DIVIDE prescaler1Divider)
Set periodic alarm 1.
__STATIC_INLINE DL_RTC_PRESCALER0_DIVIDE DL_RTC_getPrescaler0 (RTC_Regs *rtc)
Get prescaler 0 interrupt interval.
__STATIC_INLINE DL_RTC_PRESCALER1_DIVIDE DL_RTC_getPrescaler1 (RTC_Regs *rtc)
Get prescaler 1 interrupt interval.
__STATIC_INLINE void DL_RTC_enableInterrupt (RTC_Regs *rtc, uint32_t interruptMask)
Enable RTC interrupts.
__STATIC_INLINE void DL_RTC_disableInterrupt (RTC_Regs *rtc, uint32_t interruptMask)
Disable RTC interrupts.
__STATIC_INLINE uint32_t DL_RTC_getEnabledInterrupts (RTC_Regs *rtc, uint32_t interruptMask)
Check which RTC interrupts are enabled.
__STATIC_INLINE uint32_t DL_RTC_getEnabledInterruptStatus (RTC_Regs *rtc, uint32_t interruptMask)
Check interrupt flag of enabled RTC interrupts.
__STATIC_INLINE uint32_t DL_RTC_getRawInterruptStatus (RTC_Regs *rtc, uint32_t interruptMask)
Check interrupt flag of any RTC interrupt.
__STATIC_INLINE DL_RTC_IIDX DL_RTC_getPendingInterrupt (RTC_Regs *rtc)
Get highest priority pending RTC interrupt.
__STATIC_INLINE void DL_RTC_clearInterruptStatus (RTC_Regs *rtc, uint32_t interruptMask)
Clear pending RTC interrupts.
__STATIC_INLINE void DL_RTC_enableEvent (RTC_Regs *rtc, uint32_t eventMask)
Enable RTC event.
__STATIC_INLINE void DL_RTC_disableEvent (RTC_Regs *rtc, uint32_t eventMask)
Disable RTC event.
__STATIC_INLINE uint32_t DL_RTC_getEnabledEvents (RTC_Regs *rtc, uint32_t eventMask)
Check which RTC events are enabled.
__STATIC_INLINE uint32_t DL_RTC_getEnabledEventStatus (RTC_Regs *rtc, uint32_t eventMask)
Check event flag of enabled RTC event.
__STATIC_INLINE uint32_t DL_RTC_getRawEventsStatus (RTC_Regs *rtc, uint32_t eventMask)
Check interrupt flag of any RTC event.
__STATIC_INLINE void DL_RTC_clearEventsStatus (RTC_Regs *rtc, uint32_t eventMask)
Clear pending RTC events.
__STATIC_INLINE void DL_RTC_setPublisherChanID (RTC_Regs *rtc, uint8_t chanID)
Sets the event publisher channel ID.
__STATIC_INLINE uint8_t DL_RTC_getPublisherChanID (RTC_Regs *rtc)
Gets the event publisher channel ID.
void DL_RTC_initCalendar (RTC_Regs *rtc, DL_RTC_Calendar calendarTime, DL_RTC_FORMAT formatSelect)
Initializes the settings to operate the RTC in Calendar mode.
DL_RTC_Calendar DL_RTC_getCalendarTime (RTC_Regs *rtc)
Returns the Calendar Time.
void DL_RTC_setCalendarAlarm1 (RTC_Regs *rtc, DL_RTC_CalendarAlarm alarmTime)
Set calendar alarm 1.
DL_RTC_CalendarAlarm DL_RTC_getCalendarAlarm1 (RTC_Regs *rtc)
Get calendar alarm 1.
void DL_RTC_enableCalendarAlarm1 (RTC_Regs *rtc)
Enable calendar alarm 1.
void DL_RTC_disableCalendarAlarm1 (RTC_Regs *rtc)
Disable calendar alarm 1.
void DL_RTC_setCalendarAlarm2 (RTC_Regs *rtc, DL_RTC_CalendarAlarm alarmTime)
Set calendar alarm 2.
DL_RTC_CalendarAlarm DL_RTC_getCalendarAlarm2 (RTC_Regs *rtc)
Get calendar alarm 2.
void DL_RTC_enableCalendarAlarm2 (RTC_Regs *rtc)
Enable calendar alarm 2.
void DL_RTC_disableCalendarAlarm2 (RTC_Regs *rtc)
Disable calendar alarm 2.
Detailed Description
Overview
The RTC Driver Library allows full configuration of the MSPM0 RTC module. The real-time clock (RTC) module provides clock counters with calendar mode, a flexible programmable alarm, offset calibration, and a provision for temperature compensation.
Enumeration Type Documentation
DL_RTC_STATUS
enum DL_RTC_STATUS
Enumerator
DL_RTC_STATUS_READY
RTC is safe for reading
DL_RTC_STATUS_NOT_READY
RTC is not safe for reading
DL_RTC_COMPENSATION_STATUS
enum DL_RTC_COMPENSATION_STATUS
Enumerator
DL_RTC_COMPENSATION_STATUS_READY
RTC ready to get new compensation values
DL_RTC_COMPENSATION_STATUS_NOT_READY
RTC not ready to get new compensaiton values
DL_RTC_COMPENSATION_WRITE_RESULT
enum DL_RTC_COMPENSATION_WRITE_RESULT
Enumerator
DL_RTC_COMPENSATION_WRITE_RESULT_OK
Compensation write successful
DL_RTC_COMPENSATION_WRITE_RESULT_NOT_OK
Compensation write unsuccessful
DL_RTC_OFFSET_CALIBRATION_SIGN
enum DL_RTC_OFFSET_CALIBRATION_SIGN
Enumerator
DL_RTC_OFFSET_CALIBRATION_SIGN_DOWN
Calibration frequency adjusted down
DL_RTC_OFFSET_CALIBRATION_SIGN_UP
Calibration frequency adjusted up
DL_RTC_OFFSET_CALIBRATION_FREQUENCY
enum DL_RTC_OFFSET_CALIBRATION_FREQUENCY
Enumerator
DL_RTC_OFFSET_CALIBRATION_FREQUENCY_OFF
No frequency output to RTCCLK pin
DL_RTC_OFFSET_CALIBRATION_FREQUENCY_512
512 Hz frequency output to RTCLK pin
DL_RTC_OFFSET_CALIBRATION_FREQUENCY_256
256 Hz frequency output to RTCLK pin
DL_RTC_OFFSET_CALIBRATION_FREQUENCY_1
1 Hz frequency output to RTCLK pin
DL_RTC_TEMP_CALIBRATION
enum DL_RTC_TEMP_CALIBRATION
Enumerator
DL_RTC_TEMP_CALIBRATION_DOWN1PPM
Calibrate at steps of -1
DL_RTC_TEMP_CALIBRATION_UP1PPM
Calibrate at steps of +1
DL_RTC_FORMAT
enum DL_RTC_FORMAT
Enumerator
DL_RTC_FORMAT_BINARY
Select binary format for the real-time clock
DL_RTC_FORMAT_BCD
Select BCD format for the real-time clock
DL_RTC_INTERVAL_ALARM
enum DL_RTC_INTERVAL_ALARM
Enumerator
DL_RTC_INTERVAL_ALARM_MINUTECHANGE
Assert Calendar interrupt on every minute
DL_RTC_INTERVAL_ALARM_HOURCHANGE
Assert Calendar interrupt on every hour
DL_RTC_INTERVAL_ALARM_NOON
Assert Calendar interrupt when hour is 12
DL_RTC_INTERVAL_ALARM_MIDNIGHT
Assert Calendar interrupt when hour is 0
DL_RTC_PRESCALER0_DIVIDE
enum DL_RTC_PRESCALER0_DIVIDE
Enumerator
DL_RTC_PRESCALER0_DIVIDE_8
Prescaler 0 Divide by 8
DL_RTC_PRESCALER0_DIVIDE_16
Prescaler 0 Divide by 16
DL_RTC_PRESCALER0_DIVIDE_32
Prescaler 0 Divide by 32
DL_RTC_PRESCALER0_DIVIDE_64
Prescaler 0 Divide by 64
DL_RTC_PRESCALER0_DIVIDE_128
Prescaler 0 Divide by 128
DL_RTC_PRESCALER0_DIVIDE_256
Prescaler 0 Divide by 256
DL_RTC_PRESCALER1_DIVIDE
enum DL_RTC_PRESCALER1_DIVIDE
Enumerator
DL_RTC_PRESCALER1_DIVIDE_2
Prescaler 1 Divide by 2
DL_RTC_PRESCALER1_DIVIDE_4
Prescaler 1 Divide by 4
DL_RTC_PRESCALER1_DIVIDE_8
Prescaler 1 Divide by 8
DL_RTC_PRESCALER1_DIVIDE_16
Prescaler 1 Divide by 16
DL_RTC_PRESCALER1_DIVIDE_32
Prescaler 1 Divide by 32
DL_RTC_PRESCALER1_DIVIDE_64
Prescaler 1 Divide by 64
DL_RTC_PRESCALER1_DIVIDE_128
Prescaler 1 Divide by 128
DL_RTC_PRESCALER1_DIVIDE_256
Prescaler 1 Divide by 256
DL_RTC_IIDX
enum DL_RTC_IIDX
Enumerator
DL_RTC_IIDX_ALARM1
RTC interrupt index for alarm 1
DL_RTC_IIDX_ALARM2
RTC interrupt index for alarm 2
DL_RTC_IIDX_PRESCALER0
RTC interrupt index for prescaler 0
DL_RTC_IIDX_PRESCALER1
RTC interrupt index for prescaler 1
DL_RTC_IIDX_INTERVAL_TIMER
RTC interrupt index for interval timer
DL_RTC_IIDX_READY
RTC interrupt index for RTC ready
Function Documentation
DL_RTC_enablePower()
__STATIC_INLINE void DL_RTC_enablePower (RTC_Regs * rtc)
Enable power to the RTC module.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disablePower()
__STATIC_INLINE void DL_RTC_disablePower (RTC_Regs * rtc)
Disable power to the RTC module.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_isPowerEnabled()
__STATIC_INLINE bool DL_RTC_isPowerEnabled (RTC_Regs * rtc)
Returns if power is enabled for the RTC module.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
true if power is enabled
false if power is disabled
DL_RTC_reset()
__STATIC_INLINE void DL_RTC_reset (RTC_Regs * rtc)
Resets all registers in the RTC module.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_isReset()
__STATIC_INLINE bool DL_RTC_isReset (RTC_Regs * rtc)
Returns if the RTC module was reset.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
true if module was reset
false if module was not reset
DL_RTC_enableClockControl()
__STATIC_INLINE void DL_RTC_enableClockControl (RTC_Regs * rtc)
Enables the supply of the 32kHz clock to the RTC. It will not power up the 32kHz crystal oscillator. This needs to be done in the Clock System Module.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableClockControl()
__STATIC_INLINE void DL_RTC_disableClockControl (RTC_Regs * rtc)
Disables the supply of the 32kHz clock to the RTC.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_enableDebugInterrupts()
__STATIC_INLINE void DL_RTC_enableDebugInterrupts (RTC_Regs * rtc)
Enables interrupts when the CPU is in debug mode. Interrupt requests are signaled to the interrupt controller.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableDebugInterrupts()
__STATIC_INLINE void DL_RTC_disableDebugInterrupts (RTC_Regs * rtc)
Disables interrupts when the CPU is in debug mode. Interrupts of the RTC module will not be captured. There will be no updates to the RTCRIS, RTCMISC and RTCIIDX registers.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_enableDebugMode()
__STATIC_INLINE void DL_RTC_enableDebugMode (RTC_Regs * rtc)
Enables the RTC modules debug mode.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableDebugMode()
__STATIC_INLINE void DL_RTC_disableDebugMode (RTC_Regs * rtc)
Disables the RTC modules debug mode.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setClockFormat()
__STATIC_INLINE void DL_RTC_setClockFormat (RTC_Regs * rtc, DL_RTC_FORMAT formatSelect)
Set the format of the real-time clock.
The format must be selected before the time is set.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] formatSelect Selectable format the RTC peripheral will provide time in. One of DL_RTC_FORMAT
DL_RTC_getClockFormat()
__STATIC_INLINE DL_RTC_FORMAT DL_RTC_getClockFormat (RTC_Regs * rtc)
Get the format currently being used for counting the real-time clock.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
Format for counting the real-time clock.
Return values
One of DL_RTC_FORMAT
DL_RTC_setIntervalAlarm()
__STATIC_INLINE void DL_RTC_setIntervalAlarm (RTC_Regs * rtc, DL_RTC_INTERVAL_ALARM alarmEvent)
Sets the interval alarm event condition.
The interval alarm can be configured to generate an interval alarm event when one of the following events occurs:
MIN changes
HOUR changes
Every day at midnight (00:00:00)
Every day at noon (12:00:00)
The interval alarm sources the DL_RTC_INTERRUPT_INTERVAL_ALARM interrupt
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] alarmEvent The interval alarm interrupt condition. One of DL_RTC_INTERVAL_ALARM
References DL_Common_updateReg().
DL_RTC_getIntervalAlarm()
__STATIC_INLINE DL_RTC_INTERVAL_ALARM DL_RTC_getIntervalAlarm (RTC_Regs * rtc)
Gets the interval alarm event condition.
The interval alarm can be configured to generate an interval alarm event when one of the following events occurs:
MIN changes
HOUR changes
Every day at midnight (00:00:00)
Every day at noon (12:00:00)
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
DL_RTC_INTERVAL_ALARM
DL_RTC_isSafetoRead()
__STATIC_INLINE bool DL_RTC_isSafetoRead (RTC_Regs * rtc)
Checks if RTC is safe for reading.
This API checks if the counter/calender registers can be safely read.
The RTC counter/calendar registers are updated once per second. To prevent reading any counter/calendar register at the time of an update (which could result in an invalid time being read), a keep-out window is provided. The keep-out window is approximately 128/32768 seconds before the counters update.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
true if RTC is safe for reading
false if RTC values are in transition
DL_RTC_isReadyToCalibrate()
__STATIC_INLINE bool DL_RTC_isReadyToCalibrate (RTC_Regs * rtc)
Checks if RTC is ready to get new calibration values.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
true if RTC can get new calibration values
false if RTC is not ready to get new calibration values
DL_RTC_isCalibrationWriteResultOK()
__STATIC_INLINE bool DL_RTC_isCalibrationWriteResultOK (RTC_Regs * rtc)
Checks if RTC new calibration values were written OK.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
true if calibration write was successful
false if calibration write was unsuccessful
DL_RTC_setOffsetCalibrationFrequency()
__STATIC_INLINE void DL_RTC_setOffsetCalibrationFrequency (RTC_Regs * rtc, DL_RTC_OFFSET_CALIBRATION_FREQUENCY offsetFrequency)
Sets output frequency for offset calibration.
Sets the frequency output to RTC_OUT pin for calibration measurement. The corresponding port must be configured for the peripheral module function.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] offsetFrequency The frequency of offset calibration. Valid values are one of DL_RTC_OFFSET_CALIBRATION_FREQUENCY
References DL_Common_updateReg().
DL_RTC_setOffsetCalibrationAdjValue()
__STATIC_INLINE void DL_RTC_setOffsetCalibrationAdjValue (RTC_Regs * rtc, DL_RTC_OFFSET_CALIBRATION_SIGN offsetSign, uint8_t offsetValue)
Sets the offset error calibration adjustment value.
Each LSB represents approximately +1ppm (RTCOCALXS = 1) or -1ppm (RTCOCALXS = 0) adjustment in frequency. Maximum effective calibration value is +/-240ppm. Excess values written above +/-240ppm will be ignored by hardware.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] offsetSign The sign of offset calibration. Valid values are one of DL_RTC_OFFSET_CALIBRATION_SIGN
[in] offsetValue The value that the offset will be a factor of. Must be any integer from 1-240.
References DL_Common_updateReg().
DL_RTC_setOffsetCalibration()
__STATIC_INLINE void DL_RTC_setOffsetCalibration (RTC_Regs * rtc, DL_RTC_OFFSET_CALIBRATION_FREQUENCY offsetFrequency, DL_RTC_OFFSET_CALIBRATION_SIGN offsetSign, uint8_t offsetValue)
Sets the offset error calibration.
Each LSB represents approximately +1ppm (RTCOCALXS = 1) or -1ppm (RTCOCALXS = 0) adjustment in frequency. Maximum effective calibration value is +/-240ppm. Excess values written above +/-240ppm will be ignored by hardware.
Sets the frequency output to RTCCLK pin for calibration measurement. The corresponding port must be configured for the peripheral module function.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] offsetFrequency The frequency of offset calibration. Valid values are one of DL_RTC_OFFSET_CALIBRATION_FREQUENCY
[in] offsetSign The sign of offset calibration. Valid values are one of DL_RTC_OFFSET_CALIBRATION_SIGN
[in] offsetValue The value that the offset will be a factor of. Must be any integer from 1-240.
DL_RTC_getOffsetCalibrationFrequency()
__STATIC_INLINE DL_RTC_OFFSET_CALIBRATION_FREQUENCY DL_RTC_getOffsetCalibrationFrequency (RTC_Regs * rtc)
Gets the offset calibration frequency.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
Frequency used in offset calibration.
Return values
One of DL_RTC_OFFSET_CALIBRATION_FREQUENCY
DL_RTC_getOffsetCalibrationSign()
__STATIC_INLINE DL_RTC_OFFSET_CALIBRATION_SIGN DL_RTC_getOffsetCalibrationSign (RTC_Regs * rtc)
Gets the offset calibration sign.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
Sign used in offset calibration.
Return values
One of DL_RTC_OFFSET_CALIBRATION_SIGN
DL_RTC_getOffsetCalibrationValue()
__STATIC_INLINE uint32_t DL_RTC_getOffsetCalibrationValue (RTC_Regs * rtc)
Gets the offset error calibration value.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
Offset value used in offset calibration.
Return values
0 - 240 The effective offset error calibration.
DL_RTC_setTemperatureCompensation()
__STATIC_INLINE void DL_RTC_setTemperatureCompensation (RTC_Regs * rtc, DL_RTC_TEMP_CALIBRATION offsetDirection, uint32_t offsetValue)
Set the specified RTC temperature compensation.
This function sets the calibration offset to make the RTC as accurate as possible. The offsetDirection can be either +1-ppm or -1-ppm, and the offsetValue should be from 1-240 and is multiplied by the direction setting (i.e. +1-ppm * 8 (offsetValue) = +8-ppm).
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] offsetDirection The direction that the calibration offset will go. Valid values are one of DL_RTC_TEMP_CALIBRATION
[in] offsetValue The value that the offset will be a factor of. Must be any integer from 1-240.
DL_RTC_getTemperatureCompensation()
__STATIC_INLINE uint32_t DL_RTC_getTemperatureCompensation (RTC_Regs * rtc)
Get the RTC temperature compensation.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The cumulative temperature compensation
Return values
Signed addition of RTCOCALX and RTCTCMPX values, and the updated sign bit (RTCTCMPS) of the addition result.
DL_RTC_setCalendarSecondsBCD()
__STATIC_INLINE void DL_RTC_setCalendarSecondsBCD (RTC_Regs * rtc, uint8_t seconds)
Set the seconds in BCD in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] seconds Value for the seconds of the RTC calendar Valid values are 0x0-0x59.
DL_RTC_getCalendarSecondsBCD()
__STATIC_INLINE uint8_t DL_RTC_getCalendarSecondsBCD (RTC_Regs * rtc)
Get the seconds in in BCD the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_isSafetoRead to ensure that the registers are safe to read.
Returns
The seconds in the RTC calendar
Return values
Value in range: 0x0-0x59
DL_RTC_setCalendarMinutesBCD()
__STATIC_INLINE void DL_RTC_setCalendarMinutesBCD (RTC_Regs * rtc, uint8_t minutes)
Set the minutes in in BCD the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] minutes Value for the minutes of the RTC calendar Valid values are 0x0-0x59.
DL_RTC_getCalendarMinutesBCD()
__STATIC_INLINE uint8_t DL_RTC_getCalendarMinutesBCD (RTC_Regs * rtc)
Get the minutes in in BCD the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_isSafetoRead to ensure that the registers are safe to read.
Returns
The minutes in the RTC calendar
Return values
Value in range: 0x0-0x59
DL_RTC_setCalendarHoursBCD()
__STATIC_INLINE void DL_RTC_setCalendarHoursBCD (RTC_Regs * rtc, uint8_t hours)
Set the hours in in BCD the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] hours Value for the hours of the RTC calendar Valid values are 0x0-0x23
DL_RTC_getCalendarHoursBCD()
__STATIC_INLINE uint8_t DL_RTC_getCalendarHoursBCD (RTC_Regs * rtc)
Get the hours in in BCD the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_isSafetoRead to ensure that the registers are safe to read.
Returns
The hours in the RTC calendar
Return values
Value in range: 0x0-0x23
DL_RTC_setCalendarDayOfWeekBCD()
__STATIC_INLINE void DL_RTC_setCalendarDayOfWeekBCD (RTC_Regs * rtc, uint8_t day)
Set the day of the week in BCD in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] day Value for the day of the week of the RTC calendar Valid values are 0x0-0x6
References DL_Common_updateReg().
DL_RTC_getCalendarDayOfWeekBCD()
__STATIC_INLINE uint8_t DL_RTC_getCalendarDayOfWeekBCD (RTC_Regs * rtc)
Get the day of the week in BCD in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_isSafetoRead to ensure that the registers are safe to read.
Returns
The day of the week in the RTC calendar
Return values
Value in range: 0x0-0x6
DL_RTC_setCalendarDayOfMonthBCD()
__STATIC_INLINE void DL_RTC_setCalendarDayOfMonthBCD (RTC_Regs * rtc, uint8_t day)
Set the day of the month in BCD in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] day Value for the day of the month of the RTC calendar Valid values are 0x1-0x31
References DL_Common_updateReg().
DL_RTC_getCalendarDayOfMonthBCD()
__STATIC_INLINE uint8_t DL_RTC_getCalendarDayOfMonthBCD (RTC_Regs * rtc)
Get the day of the month in BCD in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_isSafetoRead to ensure that the registers are safe to read.
Returns
The day of the month in the RTC calendar
Return values
Value in range: 0x1-0x31
DL_RTC_setCalendarMonthBCD()
__STATIC_INLINE void DL_RTC_setCalendarMonthBCD (RTC_Regs * rtc, uint8_t month)
Set the month in in BCD the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] month Value for the month of the RTC calendar Valid values are 0x1-0x12
DL_RTC_getCalendarMonthBCD()
__STATIC_INLINE uint8_t DL_RTC_getCalendarMonthBCD (RTC_Regs * rtc)
Get the month of the year in BCD in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_isSafetoRead to ensure that the registers are safe to read.
Returns
The month of the year in the RTC calendar
Return values
Value in range: 0x1-0x12
DL_RTC_setCalendarYearBCD()
__STATIC_INLINE void DL_RTC_setCalendarYearBCD (RTC_Regs * rtc, uint16_t year)
Set the year in in BCD the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] year Value for the year of the RTC calendar Valid values are 0x0-0x4095
DL_RTC_getCalendarYearBCD()
__STATIC_INLINE uint16_t DL_RTC_getCalendarYearBCD (RTC_Regs * rtc)
Get the year in in BCD the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_isSafetoRead to ensure that the registers are safe to read.
Returns
The year in the RTC calendar
Return values
Value in range: 0x0-0x4095
DL_RTC_enableAlarm1MinutesBCD()
__STATIC_INLINE void DL_RTC_enableAlarm1MinutesBCD (RTC_Regs * rtc)
Enable minutes in BCD for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableAlarm1MinutesBCD()
__STATIC_INLINE void DL_RTC_disableAlarm1MinutesBCD (RTC_Regs * rtc)
Disable minutes in BCD for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setAlarm1MinutesBCD()
__STATIC_INLINE void DL_RTC_setAlarm1MinutesBCD (RTC_Regs * rtc, uint8_t minutes)
Set the minutes in BCD for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] minutes Value for the minutes of alarm 1 Valid values are 0x0-0x59
DL_RTC_getAlarm1MinutesBCD()
__STATIC_INLINE uint8_t DL_RTC_getAlarm1MinutesBCD (RTC_Regs * rtc)
Get the minutes in BCD for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The minutes of alarm 1
Return values
Value in range: 0x0-0x59
DL_RTC_enableAlarm1HoursBCD()
__STATIC_INLINE void DL_RTC_enableAlarm1HoursBCD (RTC_Regs * rtc)
Enable hours in BCD for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableAlarm1HoursBCD()
__STATIC_INLINE void DL_RTC_disableAlarm1HoursBCD (RTC_Regs * rtc)
Disable hours in BCD for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setAlarm1HoursBCD()
__STATIC_INLINE void DL_RTC_setAlarm1HoursBCD (RTC_Regs * rtc, uint8_t hours)
Set the hours in BCD for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] hours Value for the hours of alarm 1 Valid values are 0x0-0x23
DL_RTC_getAlarm1HoursBCD()
__STATIC_INLINE uint8_t DL_RTC_getAlarm1HoursBCD (RTC_Regs * rtc)
Get the hours in BCD for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The hours of alarm 1
Return values
Value in range: 0x0-0x23
DL_RTC_enableAlarm1DayOfWeekBCD()
__STATIC_INLINE void DL_RTC_enableAlarm1DayOfWeekBCD (RTC_Regs * rtc)
Enable day of the week in BCD for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableAlarm1DayOfWeekBCD()
__STATIC_INLINE void DL_RTC_disableAlarm1DayOfWeekBCD (RTC_Regs * rtc)
Disable day of the week in BCD for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setAlarm1DayOfWeekBCD()
__STATIC_INLINE void DL_RTC_setAlarm1DayOfWeekBCD (RTC_Regs * rtc, uint8_t day)
Set the day of the week in BCD for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] day Value for the day of the week of the RTC calendar Valid values are 0x0-0x6
References DL_Common_updateReg().
DL_RTC_getAlarm1DayOfWeekBCD()
__STATIC_INLINE uint8_t DL_RTC_getAlarm1DayOfWeekBCD (RTC_Regs * rtc)
Get the day of the week in BCD for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The day of the week in the RTC calendar
Return values
Value in range: 0x0-0x6
DL_RTC_enableAlarm1DayOfMonthBCD()
__STATIC_INLINE void DL_RTC_enableAlarm1DayOfMonthBCD (RTC_Regs * rtc)
Enable day of the month in BCD for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableAlarm1DayOfMonthBCD()
__STATIC_INLINE void DL_RTC_disableAlarm1DayOfMonthBCD (RTC_Regs * rtc)
Disable day of the month in BCD for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setAlarm1DayOfMonthBCD()
__STATIC_INLINE void DL_RTC_setAlarm1DayOfMonthBCD (RTC_Regs * rtc, uint8_t day)
Set the day of the month in BCD for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] day Value for the day of the month of the RTC calendar Valid values are 0x1-0x31
References DL_Common_updateReg().
DL_RTC_getAlarm1DayOfMonthBCD()
__STATIC_INLINE uint8_t DL_RTC_getAlarm1DayOfMonthBCD (RTC_Regs * rtc)
Get the day of the month in BCD for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The day of the month in the RTC calendar
Return values
Value in range: 0x1-0x31
DL_RTC_enableAlarm2MinutesBCD()
__STATIC_INLINE void DL_RTC_enableAlarm2MinutesBCD (RTC_Regs * rtc)
Enable minutes in BCD for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableAlarm2MinutesBCD()
__STATIC_INLINE void DL_RTC_disableAlarm2MinutesBCD (RTC_Regs * rtc)
Disable minutes in BCD for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setAlarm2MinutesBCD()
__STATIC_INLINE void DL_RTC_setAlarm2MinutesBCD (RTC_Regs * rtc, uint8_t minutes)
Set the minutes in BCD for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] minutes Value for the minutes of alarm 2 Valid values are 0x0-0x59
DL_RTC_getAlarm2MinutesBCD()
__STATIC_INLINE uint8_t DL_RTC_getAlarm2MinutesBCD (RTC_Regs * rtc)
Get the minutes in BCD for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The minutes of alarm 2
Return values
Value in range: 0x0-0x59
DL_RTC_enableAlarm2HoursBCD()
__STATIC_INLINE void DL_RTC_enableAlarm2HoursBCD (RTC_Regs * rtc)
Enable hours in BCD for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableAlarm2HoursBCD()
__STATIC_INLINE void DL_RTC_disableAlarm2HoursBCD (RTC_Regs * rtc)
Disable hours in BCD for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setAlarm2HoursBCD()
__STATIC_INLINE void DL_RTC_setAlarm2HoursBCD (RTC_Regs * rtc, uint8_t hours)
Set the hours in BCD for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] hours Value for the hours of alarm 2 Valid values are 0x0-0x23
DL_RTC_getAlarm2HoursBCD()
__STATIC_INLINE uint8_t DL_RTC_getAlarm2HoursBCD (RTC_Regs * rtc)
Get the hours in BCD for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The hours of alarm 2
Return values
Value in range: 0x0-0x23
DL_RTC_enableAlarm2DayOfWeekBCD()
__STATIC_INLINE void DL_RTC_enableAlarm2DayOfWeekBCD (RTC_Regs * rtc)
Enable day of the week in BCD for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableAlarm2DayOfWeekBCD()
__STATIC_INLINE void DL_RTC_disableAlarm2DayOfWeekBCD (RTC_Regs * rtc)
Disable day of the week in BCD for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setAlarm2DayOfWeekBCD()
__STATIC_INLINE void DL_RTC_setAlarm2DayOfWeekBCD (RTC_Regs * rtc, uint8_t day)
Set the day of the week in BCD for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] day Value for the day of the week of the RTC calendar Valid values are 0x0-0x6
References DL_Common_updateReg().
DL_RTC_getAlarm2DayOfWeekBCD()
__STATIC_INLINE uint8_t DL_RTC_getAlarm2DayOfWeekBCD (RTC_Regs * rtc)
Get the day of the week in BCD for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The day of the week in the RTC calendar
Return values
Value in range: 0x0-0x6
DL_RTC_enableAlarm2DayOfMonthBCD()
__STATIC_INLINE void DL_RTC_enableAlarm2DayOfMonthBCD (RTC_Regs * rtc)
Enable day of the month in BCD for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableAlarm2DayOfMonthBCD()
__STATIC_INLINE void DL_RTC_disableAlarm2DayOfMonthBCD (RTC_Regs * rtc)
Disable day of the month in BCD for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setAlarm2DayOfMonthBCD()
__STATIC_INLINE void DL_RTC_setAlarm2DayOfMonthBCD (RTC_Regs * rtc, uint8_t day)
Set the day of the month in BCD for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] day Value for the day of the month of the RTC calendar Valid values are 0x1-0x31
References DL_Common_updateReg().
DL_RTC_getAlarm2DayOfMonthBCD()
__STATIC_INLINE uint8_t DL_RTC_getAlarm2DayOfMonthBCD (RTC_Regs * rtc)
Get the day of the month in BCD for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The day of the month in the RTC calendar
Return values
Value in range: 0x1-0x31
DL_RTC_setCalendarSecondsBinary()
__STATIC_INLINE void DL_RTC_setCalendarSecondsBinary (RTC_Regs * rtc, uint8_t seconds)
Set the seconds in binary the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] seconds Value for the seconds of the RTC calendar Valid values are 0-59
DL_RTC_getCalendarSecondsBinary()
__STATIC_INLINE uint8_t DL_RTC_getCalendarSecondsBinary (RTC_Regs * rtc)
Get the seconds in binary in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_isSafetoRead to ensure that the registers are safe to read.
Returns
The seconds in the RTC calendar
Return values
Value in range: 0-59
DL_RTC_setCalendarMinutesBinary()
__STATIC_INLINE void DL_RTC_setCalendarMinutesBinary (RTC_Regs * rtc, uint8_t minutes)
Set the minutes in binary in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] minutes Value for the minutes of the RTC calendar Valid values are 0-59
DL_RTC_getCalendarMinutesBinary()
__STATIC_INLINE uint8_t DL_RTC_getCalendarMinutesBinary (RTC_Regs * rtc)
Get the minutes in binary in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_isSafetoRead to ensure that the registers are safe to read.
Returns
The minutes in the RTC calendar
Return values
Value in range: 0-59
DL_RTC_setCalendarHoursBinary()
__STATIC_INLINE void DL_RTC_setCalendarHoursBinary (RTC_Regs * rtc, uint8_t hours)
Set the hours in binary in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] hours Value for the hours of the RTC calendar Valid values are 0-23
DL_RTC_getCalendarHoursBinary()
__STATIC_INLINE uint8_t DL_RTC_getCalendarHoursBinary (RTC_Regs * rtc)
Get the hours in binary in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_isSafetoRead to ensure that the registers are safe to read.
Returns
The hours in the RTC calendar
Return values
Value in range: 0-23
DL_RTC_setCalendarDayOfWeekBinary()
__STATIC_INLINE void DL_RTC_setCalendarDayOfWeekBinary (RTC_Regs * rtc, uint8_t day)
Set the day of the week in binary in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] day Value for the day of the week of the RTC calendar Valid values are 0-6
References DL_Common_updateReg().
DL_RTC_getCalendarDayOfWeekBinary()
__STATIC_INLINE uint8_t DL_RTC_getCalendarDayOfWeekBinary (RTC_Regs * rtc)
Get the day of the week in binary in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_isSafetoRead to ensure that the registers are safe to read.
Returns
The day of the week in the RTC calendar
Return values
Value in range: 0-6
DL_RTC_setCalendarDayOfMonthBinary()
__STATIC_INLINE void DL_RTC_setCalendarDayOfMonthBinary (RTC_Regs * rtc, uint8_t day)
Set the day of the month in binary in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] day Value for the day of the month of the RTC calendar Valid values are 1-31
References DL_Common_updateReg().
DL_RTC_getCalendarDayOfMonthBinary()
__STATIC_INLINE uint8_t DL_RTC_getCalendarDayOfMonthBinary (RTC_Regs * rtc)
Get the day of the month in binary in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_isSafetoRead to ensure that the registers are safe to read.
Returns
The day of the month in the RTC calendar
Return values
Value in range: 1-31
DL_RTC_setCalendarMonthBinary()
__STATIC_INLINE void DL_RTC_setCalendarMonthBinary (RTC_Regs * rtc, uint8_t month)
Set the month in binary in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] month Value for the month of the RTC calendar Valid values are 1-12
DL_RTC_getCalendarMonthBinary()
__STATIC_INLINE uint8_t DL_RTC_getCalendarMonthBinary (RTC_Regs * rtc)
Get the month of the year in binary in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_isSafetoRead to ensure that the registers are safe to read.
Returns
The month of the year in the RTC calendar
Return values
Value in range: 1-12
DL_RTC_setCalendarYearBinary()
__STATIC_INLINE void DL_RTC_setCalendarYearBinary (RTC_Regs * rtc, uint16_t year)
Set the year in binary in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] year Value for the year of the RTC calendar Valid values are 0-4095
DL_RTC_getCalendarYearBinary()
__STATIC_INLINE uint16_t DL_RTC_getCalendarYearBinary (RTC_Regs * rtc)
Get the year in binary in the RTC calendar.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Precondition
To prevent reading any counter/calendar registers while those registers are being updated, the user can call DL_RTC_isSafetoRead to ensure that the registers are safe to read.
Returns
The year in the RTC calendar
Return values
Value in range: 0-4095
DL_RTC_enableAlarm1MinutesBinary()
__STATIC_INLINE void DL_RTC_enableAlarm1MinutesBinary (RTC_Regs * rtc)
Enable minutes in binary in binary for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableAlarm1MinutesBinary()
__STATIC_INLINE void DL_RTC_disableAlarm1MinutesBinary (RTC_Regs * rtc)
Disable minutes in binary for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setAlarm1MinutesBinary()
__STATIC_INLINE void DL_RTC_setAlarm1MinutesBinary (RTC_Regs * rtc, uint8_t minutes)
Set the minutes in binary for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] minutes Value for the minutes of alarm 1 Valid values are 0-59
DL_RTC_getAlarm1MinutesBinary()
__STATIC_INLINE uint8_t DL_RTC_getAlarm1MinutesBinary (RTC_Regs * rtc)
Get the minutes in binary for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The minutes of alarm 1
Return values
Value in range: 0-59
DL_RTC_enableAlarm1HoursBinary()
__STATIC_INLINE void DL_RTC_enableAlarm1HoursBinary (RTC_Regs * rtc)
Enable hours in binary for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableAlarm1HoursBinary()
__STATIC_INLINE void DL_RTC_disableAlarm1HoursBinary (RTC_Regs * rtc)
Disable hours in binary for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setAlarm1HoursBinary()
__STATIC_INLINE void DL_RTC_setAlarm1HoursBinary (RTC_Regs * rtc, uint8_t hours)
Set the hours in binary for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] hours Value for the hours of alarm 1 Valid values are 0-23
DL_RTC_getAlarm1HoursBinary()
__STATIC_INLINE uint8_t DL_RTC_getAlarm1HoursBinary (RTC_Regs * rtc)
Get the hours in binary for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The hours of alarm 1
Return values
Value in range: 0-23
DL_RTC_enableAlarm1DayOfWeekBinary()
__STATIC_INLINE void DL_RTC_enableAlarm1DayOfWeekBinary (RTC_Regs * rtc)
Enable day of the week in binary for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableAlarm1DayOfWeekBinary()
__STATIC_INLINE void DL_RTC_disableAlarm1DayOfWeekBinary (RTC_Regs * rtc)
Disable day of the week in binary for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setAlarm1DayOfWeekBinary()
__STATIC_INLINE void DL_RTC_setAlarm1DayOfWeekBinary (RTC_Regs * rtc, uint8_t day)
Set the day of the week in binary for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] day Value for the day of the week of the RTC calendar Valid values are 0-6
References DL_Common_updateReg().
DL_RTC_getAlarm1DayOfWeekBinary()
__STATIC_INLINE uint8_t DL_RTC_getAlarm1DayOfWeekBinary (RTC_Regs * rtc)
Get the day of the week in binary for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The day of the week in the RTC calendar
Return values
Value in range: 0-6
DL_RTC_enableAlarm1DayOfMonthBinary()
__STATIC_INLINE void DL_RTC_enableAlarm1DayOfMonthBinary (RTC_Regs * rtc)
Enable day of the month in binary for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableAlarm1DayOfMonthBinary()
__STATIC_INLINE void DL_RTC_disableAlarm1DayOfMonthBinary (RTC_Regs * rtc)
Disable day of the month in binary for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setAlarm1DayOfMonthBinary()
__STATIC_INLINE void DL_RTC_setAlarm1DayOfMonthBinary (RTC_Regs * rtc, uint8_t day)
Set the day of the month in binary for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] day Value for the day of the month of the RTC calendar Valid values are 1-31
References DL_Common_updateReg().
DL_RTC_getAlarm1DayOfMonthBinary()
__STATIC_INLINE uint8_t DL_RTC_getAlarm1DayOfMonthBinary (RTC_Regs * rtc)
Get the day of the month in binary for RTC Calendar Alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The day of the month in the RTC calendar
Return values
Value in range: 1-31
DL_RTC_enableAlarm2MinutesBinary()
__STATIC_INLINE void DL_RTC_enableAlarm2MinutesBinary (RTC_Regs * rtc)
Enable minutes in binary for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableAlarm2MinutesBinary()
__STATIC_INLINE void DL_RTC_disableAlarm2MinutesBinary (RTC_Regs * rtc)
Disable minutes in binary for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setAlarm2MinutesBinary()
__STATIC_INLINE void DL_RTC_setAlarm2MinutesBinary (RTC_Regs * rtc, uint8_t minutes)
Set the minutes in binary for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] minutes Value for the minutes of alarm 2 Valid values are 0-59
DL_RTC_getAlarm2MinutesBinary()
__STATIC_INLINE uint8_t DL_RTC_getAlarm2MinutesBinary (RTC_Regs * rtc)
Get the minutes in binary for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The minutes of alarm 2
Return values
Value in range: 0-59
DL_RTC_enableAlarm2HoursBinary()
__STATIC_INLINE void DL_RTC_enableAlarm2HoursBinary (RTC_Regs * rtc)
Enable hours in binary for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableAlarm2HoursBinary()
__STATIC_INLINE void DL_RTC_disableAlarm2HoursBinary (RTC_Regs * rtc)
Disable hours in binary for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setAlarm2HoursBinary()
__STATIC_INLINE void DL_RTC_setAlarm2HoursBinary (RTC_Regs * rtc, uint8_t hours)
Set the hours in binary for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] hours Value for the hours of alarm 2 Valid values are 0-23
DL_RTC_getAlarm2HoursBinary()
__STATIC_INLINE uint8_t DL_RTC_getAlarm2HoursBinary (RTC_Regs * rtc)
Get the hours in binary for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The hours of alarm 2
Return values
Value in range: 0-23
DL_RTC_enableAlarm2DayOfWeekBinary()
__STATIC_INLINE void DL_RTC_enableAlarm2DayOfWeekBinary (RTC_Regs * rtc)
Enable day of the week in binary for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableAlarm2DayOfWeekBinary()
__STATIC_INLINE void DL_RTC_disableAlarm2DayOfWeekBinary (RTC_Regs * rtc)
Disable day of the week in binary for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setAlarm2DayOfWeekBinary()
__STATIC_INLINE void DL_RTC_setAlarm2DayOfWeekBinary (RTC_Regs * rtc, uint8_t day)
Set the day of the week in binary for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] day Value for the day of the week of the RTC calendar Valid values are 0-6
References DL_Common_updateReg().
DL_RTC_getAlarm2DayOfWeekBinary()
__STATIC_INLINE uint8_t DL_RTC_getAlarm2DayOfWeekBinary (RTC_Regs * rtc)
Get the day of the week in binary for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The day of the week in the RTC calendar
Return values
Value in range: 0-6
DL_RTC_enableAlarm2DayOfMonthBinary()
__STATIC_INLINE void DL_RTC_enableAlarm2DayOfMonthBinary (RTC_Regs * rtc)
Enable day of the month in binary for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_disableAlarm2DayOfMonthBinary()
__STATIC_INLINE void DL_RTC_disableAlarm2DayOfMonthBinary (RTC_Regs * rtc)
Disable day of the month in binary for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
DL_RTC_setAlarm2DayOfMonthBinary()
__STATIC_INLINE void DL_RTC_setAlarm2DayOfMonthBinary (RTC_Regs * rtc, uint8_t day)
Set the day of the month in binary for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] day Value for the day of the month of the RTC calendar Valid values are 1-31
References DL_Common_updateReg().
DL_RTC_getAlarm2DayOfMonthBinary()
__STATIC_INLINE uint8_t DL_RTC_getAlarm2DayOfMonthBinary (RTC_Regs * rtc)
Get the day of the month in binary for RTC Calendar Alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The day of the month in the RTC calendar
Return values
Value in range: 1-31
DL_RTC_setPrescalerEvents()
__STATIC_INLINE void DL_RTC_setPrescalerEvents (RTC_Regs * rtc, DL_RTC_PRESCALER0_DIVIDE prescaler0Divider, DL_RTC_PRESCALER1_DIVIDE prescaler1Divider)
Set prescale interrupt interval for timer 0 and 1.
Set prescale timer interrupt interval to DL_RTC_PRESCALE_NONE to keep the timer disabled.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] prescaler0Divider Value to set for prescaler 0 interrupt interval One of DL_RTC_PRESCALER0_DIVIDE
[in] prescaler1Divider Value to set for prescaler 1 interrupt interval One of DL_RTC_PRESCALER1_DIVIDE
DL_RTC_setPeriodicAlarm0()
__STATIC_INLINE void DL_RTC_setPeriodicAlarm0 (RTC_Regs * rtc, DL_RTC_PRESCALER0_DIVIDE prescaler0Divider)
Set periodic alarm 0.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] prescaler0Divider Value to set for prescaler 0 interrupt interval. One of DL_RTC_PRESCALER0_DIVIDE
References DL_Common_updateReg().
DL_RTC_setPeriodicAlarm1()
__STATIC_INLINE void DL_RTC_setPeriodicAlarm1 (RTC_Regs * rtc, DL_RTC_PRESCALER1_DIVIDE prescaler1Divider)
Set periodic alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] prescaler1Divider Value to set for prescaler 1 interrupt interval. One of DL_RTC_PRESCALER1_DIVIDE
References DL_Common_updateReg().
DL_RTC_getPrescaler0()
__STATIC_INLINE DL_RTC_PRESCALER0_DIVIDE DL_RTC_getPrescaler0 (RTC_Regs * rtc)
Get prescaler 0 interrupt interval.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
Value for prescaler 0 interrupt interval
Return values
One of DL_RTC_PRESCALER0_DIVIDE
DL_RTC_getPrescaler1()
__STATIC_INLINE DL_RTC_PRESCALER1_DIVIDE DL_RTC_getPrescaler1 (RTC_Regs * rtc)
Get prescaler 1 interrupt interval.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
Value for prescaler 1 interrupt interval
Return values
One of DL_RTC_PRESCALER1_DIVIDE
DL_RTC_enableInterrupt()
__STATIC_INLINE void DL_RTC_enableInterrupt (RTC_Regs * rtc, uint32_t interruptMask)
Enable RTC interrupts.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] interruptMask Bit mask of interrupts to enable. Logical OR of DL_RTC_INTERRUPT.
DL_RTC_disableInterrupt()
__STATIC_INLINE void DL_RTC_disableInterrupt (RTC_Regs * rtc, uint32_t interruptMask)
Disable RTC interrupts.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] interruptMask Bit mask of interrupts to enable. Logical OR of DL_RTC_INTERRUPT
DL_RTC_getEnabledInterrupts()
__STATIC_INLINE uint32_t DL_RTC_getEnabledInterrupts (RTC_Regs * rtc, uint32_t interruptMask)
Check which RTC interrupts are enabled.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] interruptMask Bit mask of interrupts to check. Logical OR of DL_RTC_INTERRUPT
Returns
Which of the requested RTC interrupts are enabled
Return values
Logical OR of DL_RTC_INTERRUPT values
DL_RTC_getEnabledInterruptStatus()
__STATIC_INLINE uint32_t DL_RTC_getEnabledInterruptStatus (RTC_Regs * rtc, uint32_t interruptMask)
Check interrupt flag of enabled RTC interrupts.
Checks if any of the RTC interrupts that were previously enabled are pending.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] interruptMask Bit mask of interrupts to check. Logical OR of DL_RTC_INTERRUPT
Returns
Which of the requested RTC interrupts are pending
Return values
Logical OR of DL_RTC_INTERRUPT values
See also
DL_RTC_enableInterrupt
DL_RTC_getRawInterruptStatus()
__STATIC_INLINE uint32_t DL_RTC_getRawInterruptStatus (RTC_Regs * rtc, uint32_t interruptMask)
Check interrupt flag of any RTC interrupt.
Checks if any of the RTC interrupts are pending. Interrupts do not have to be previously enabled.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] interruptMask Bit mask of interrupts to check. Logical OR of DL_RTC_INTERRUPT
Returns
Which of the requested RTC interrupts are pending
Return values
Logical OR of DL_RTC_INTERRUPT values
DL_RTC_getPendingInterrupt()
__STATIC_INLINE DL_RTC_IIDX DL_RTC_getPendingInterrupt (RTC_Regs * rtc)
Get highest priority pending RTC interrupt.
Checks if any of the RTC interrupts are pending. Interrupts do not have to be previously enabled.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
The highest priority pending RTC interrupt
Return values
One of DL_RTC_IIDX
DL_RTC_clearInterruptStatus()
__STATIC_INLINE void DL_RTC_clearInterruptStatus (RTC_Regs * rtc, uint32_t interruptMask)
Clear pending RTC interrupts.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] interruptMask Bit mask of interrupts to check. Logical OR of DL_RTC_INTERRUPT
DL_RTC_enableEvent()
__STATIC_INLINE void DL_RTC_enableEvent (RTC_Regs * rtc, uint32_t eventMask)
Enable RTC event.
Parameters
[in] rtc Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to enable. Bitwise OR of DL_RTC_EVENT.
DL_RTC_disableEvent()
__STATIC_INLINE void DL_RTC_disableEvent (RTC_Regs * rtc, uint32_t eventMask)
Disable RTC event.
Parameters
[in] rtc Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to enable. Bitwise OR of DL_RTC_EVENT.
DL_RTC_getEnabledEvents()
__STATIC_INLINE uint32_t DL_RTC_getEnabledEvents (RTC_Regs * rtc, uint32_t eventMask)
Check which RTC events are enabled.
Parameters
[in] rtc Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to check. Bitwise OR of DL_RTC_EVENT.
Returns
Which of the requested RTC interrupts are enabled
Return values
Bitwise OR of DL_RTC_EVENT values
DL_RTC_getEnabledEventStatus()
__STATIC_INLINE uint32_t DL_RTC_getEnabledEventStatus (RTC_Regs * rtc, uint32_t eventMask)
Check event flag of enabled RTC event.
Checks if any of the RTC events that were previously enabled are pending.
Parameters
[in] rtc Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to check. Bitwise OR of DL_RTC_EVENT.
Returns
Which of the requested RTC interrupts are pending
Return values
Bitwise OR of DL_RTC_EVENT values
See also
DL_RTC_enableInterrupt
DL_RTC_getRawEventsStatus()
__STATIC_INLINE uint32_t DL_RTC_getRawEventsStatus (RTC_Regs * rtc, uint32_t eventMask)
Check interrupt flag of any RTC event.
Checks if any events are pending. Events do not have to be previously enabled.
Parameters
[in] rtc Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to check. Bitwise OR of DL_RTC_EVENT.
Returns
Which of the requested RTC interrupts are pending
Return values
Bitwise OR of DL_RTC_EVENT values
DL_RTC_clearEventsStatus()
__STATIC_INLINE void DL_RTC_clearEventsStatus (RTC_Regs * rtc, uint32_t eventMask)
Clear pending RTC events.
Parameters
[in] rtc Pointer to the register overlay for the peripheral
[in] eventMask Bit mask of interrupts to clear. Bitwise OR of DL_RTC_EVENT.
DL_RTC_setPublisherChanID()
__STATIC_INLINE void DL_RTC_setPublisherChanID (RTC_Regs * rtc, uint8_t chanID)
Sets the event publisher channel ID.
Parameters
[in] rtc Pointer to the register overlay for the peripheral
[in] chanID Channel ID number. Valid range 0-15. If ChanID == 0 publisher is disconnected.
DL_RTC_getPublisherChanID()
__STATIC_INLINE uint8_t DL_RTC_getPublisherChanID (RTC_Regs * rtc)
Gets the event publisher channel ID.
Parameters
[in] rtc Pointer to the register overlay for the peripheral
Returns
Event publisher channel ID
References DL_RTC_disableCalendarAlarm1(), DL_RTC_disableCalendarAlarm2(), DL_RTC_enableCalendarAlarm1(), DL_RTC_enableCalendarAlarm2(), DL_RTC_getCalendarAlarm1(), DL_RTC_getCalendarAlarm2(), DL_RTC_getCalendarTime(), DL_RTC_initCalendar(), DL_RTC_setCalendarAlarm1(), and DL_RTC_setCalendarAlarm2().
DL_RTC_initCalendar()
void DL_RTC_initCalendar (RTC_Regs * rtc, DL_RTC_Calendar calendarTime, DL_RTC_FORMAT formatSelect)
Initializes the settings to operate the RTC in Calendar mode.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] calendarTime Structure containing the values for the Calendar to be initialized to
[in] formatSelect Selectable format the RTC peripheral will provide time in. DL_RTC_FORMAT
Referenced by DL_RTC_getPublisherChanID().
DL_RTC_getCalendarTime()
DL_RTC_Calendar DL_RTC_getCalendarTime (RTC_Regs * rtc)
Returns the Calendar Time.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
This function returns the current Calendar Time in the form of a Calendar structure. The time returned will be in the previously selected format.
Returns
A Calendar structure containing the current time.
Referenced by DL_RTC_getPublisherChanID().
DL_RTC_setCalendarAlarm1()
void DL_RTC_setCalendarAlarm1 (RTC_Regs * rtc, DL_RTC_CalendarAlarm alarmTime)
Set calendar alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] alarmTime Structure containing the values for the alarm to be set to
Referenced by DL_RTC_getPublisherChanID().
DL_RTC_getCalendarAlarm1()
DL_RTC_CalendarAlarm DL_RTC_getCalendarAlarm1 (RTC_Regs * rtc)
Get calendar alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
A Alarm structure containing the set time for alarm 1
Referenced by DL_RTC_getPublisherChanID().
DL_RTC_enableCalendarAlarm1()
void DL_RTC_enableCalendarAlarm1 (RTC_Regs * rtc)
Enable calendar alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Referenced by DL_RTC_getPublisherChanID().
DL_RTC_disableCalendarAlarm1()
void DL_RTC_disableCalendarAlarm1 (RTC_Regs * rtc)
Disable calendar alarm 1.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Referenced by DL_RTC_getPublisherChanID().
DL_RTC_setCalendarAlarm2()
void DL_RTC_setCalendarAlarm2 (RTC_Regs * rtc, DL_RTC_CalendarAlarm alarmTime)
Set calendar alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
[in] alarmTime Structure containing the values for the alarm to be set to
Referenced by DL_RTC_getPublisherChanID().
DL_RTC_getCalendarAlarm2()
DL_RTC_CalendarAlarm DL_RTC_getCalendarAlarm2 (RTC_Regs * rtc)
Get calendar alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Returns
A Alarm structure containing the set time for alarm 2
Referenced by DL_RTC_getPublisherChanID().
DL_RTC_enableCalendarAlarm2()
void DL_RTC_enableCalendarAlarm2 (RTC_Regs * rtc)
Enable calendar alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Referenced by DL_RTC_getPublisherChanID().
DL_RTC_disableCalendarAlarm2()
void DL_RTC_disableCalendarAlarm2 (RTC_Regs * rtc)
Disable calendar alarm 2.
Parameters
[in] rtc Pointer to the register overlay for the RTC peripheral
Referenced by DL_RTC_getPublisherChanID().
Copyright 1995-2023, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale