MSPM0G511xTinyUSBLibrary: CDC_HOST
CDC_HOST
Macros
#define CFG_TUH_CDC_LINE_CONTROL_ON_ENUM 0
Controls DTR/RTS line states set during device enumeration.
#define CFG_TUH_CDC_RX_BUFSIZE USBH_EPSIZE_BULK_MAX
Size of CDC host receive buffer.
#define CFG_TUH_CDC_RX_EPSIZE USBH_EPSIZE_BULK_MAX
Maximum CDC endpoint size for receiving data.
#define CFG_TUH_CDC_TX_BUFSIZE USBH_EPSIZE_BULK_MAX
Size of CDC host transmit buffer.
#define CFG_TUH_CDC_TX_EPSIZE USBH_EPSIZE_BULK_MAX
Maximum CDC endpoint size for transmitting data.
Functions
uint8_t tuh_cdc_itf_get_index (uint8_t daddr, uint8_t itf_num)
Get CDC interface index from device address and interface number.
bool tuh_cdc_itf_get_info (uint8_t idx, tuh_itf_info_t *info)
Get detailed information about a CDC interface.
bool tuh_cdc_mounted (uint8_t idx)
Check if a CDC device is mounted.
bool tuh_cdc_get_dtr (uint8_t idx)
Get current DTR (Data Terminal Ready) status.
bool tuh_cdc_get_rts (uint8_t idx)
Get current RTS (Request To Send) status.
static TU_ATTR_ALWAYS_INLINE bool tuh_cdc_connected (uint8_t idx)
Check if a terminal client is connected to the CDC device.
bool tuh_cdc_get_local_line_coding (uint8_t idx, cdc_line_coding_t *line_coding)
Get locally cached line coding parameters.
uint32_t tuh_cdc_write_available (uint8_t idx)
Get the number of bytes available for writing.
uint32_t tuh_cdc_write (uint8_t idx, void const *buffer, uint32_t bufsize)
Write data to CDC interface.
uint32_t tuh_cdc_write_flush (uint8_t idx)
Flush data in the transmit buffer to the CDC device.
bool tuh_cdc_write_clear (uint8_t idx)
Clear the transmit buffer.
uint32_t tuh_cdc_read_available (uint8_t idx)
Get the number of bytes available for reading.
uint32_t tuh_cdc_read (uint8_t idx, void *buffer, uint32_t bufsize)
Read data from CDC interface.
bool tuh_cdc_peek (uint8_t idx, uint8_t *ch)
Peek at the next byte in the receive buffer without removing it.
bool tuh_cdc_read_clear (uint8_t idx)
Clear the receive buffer for a CDC interface.
bool tuh_cdc_set_control_line_state (uint8_t idx, uint16_t line_state, tuh_xfer_cb_t complete_cb, uintptr_t user_data)
Set control line state (DTR/RTS) for a CDC interface.
bool tuh_cdc_set_baudrate (uint8_t idx, uint32_t baudrate, tuh_xfer_cb_t complete_cb, uintptr_t user_data)
Set the baud rate for a CDC interface.
bool tuh_cdc_set_data_format (uint8_t idx, uint8_t stop_bits, uint8_t parity, uint8_t data_bits, tuh_xfer_cb_t complete_cb, uintptr_t user_data)
Set the data format parameters for a CDC interface.
bool tuh_cdc_set_line_coding (uint8_t idx, cdc_line_coding_t const *line_coding, tuh_xfer_cb_t complete_cb, uintptr_t user_data)
Set the line coding parameters for a CDC interface.
static TU_ATTR_ALWAYS_INLINE bool tuh_cdc_connect (uint8_t idx, tuh_xfer_cb_t complete_cb, uintptr_t user_data)
Connect to a CDC device by setting both DTR and RTS signals.
static TU_ATTR_ALWAYS_INLINE bool tuh_cdc_disconnect (uint8_t idx, tuh_xfer_cb_t complete_cb, uintptr_t user_data)
Disconnect from a CDC device by clearing both DTR and RTS signals.
TU_ATTR_WEAK void tuh_cdc_mount_cb (uint8_t idx)
Callback invoked when a device with CDC interface is mounted.
TU_ATTR_WEAK void tuh_cdc_umount_cb (uint8_t idx)
Callback invoked when a device with CDC interface is unmounted.
TU_ATTR_WEAK void tuh_cdc_rx_cb (uint8_t idx)
Callback invoked when new data is received from a CDC device.
TU_ATTR_WEAK void tuh_cdc_tx_complete_cb (uint8_t idx)
Callback invoked when a transmit operation completes.
bool cdch_init (void)
Initialize CDC Host driver.
bool cdch_deinit (void)
De-initialize CDC Host driver.
bool cdch_open (uint8_t rhport, uint8_t dev_addr, tusb_desc_interface_t const *itf_desc, uint16_t max_len)
Open a CDC interface for communication.
bool cdch_set_config (uint8_t dev_addr, uint8_t itf_num)
Configure a CDC interface after device is configured.
bool cdch_xfer_cb (uint8_t dev_addr, uint8_t ep_addr, xfer_result_t event, uint32_t xferred_bytes)
Process transfer completion for CDC host endpoints.
void cdch_close (uint8_t dev_addr)
Close a CDC interface and release its resources.
Detailed Description
Macro Definition Documentation
CFG_TUH_CDC_LINE_CONTROL_ON_ENUM
#define CFG_TUH_CDC_LINE_CONTROL_ON_ENUM 0
Controls DTR/RTS line states set during device enumeration.
This configuration defines what control line states (DTR and RTS) should be set when a CDC device is mounted after enumeration.
Note
Values are bit-mapped: bit 0 = DTR, bit 1 = RTS
0x00: No lines asserted
0x01: DTR asserted
0x02: RTS asserted
0x03: Both DTR and RTS asserted
Default value is 0 (no lines asserted) if not defined
CFG_TUH_CDC_RX_BUFSIZE
#define CFG_TUH_CDC_RX_BUFSIZE USBH_EPSIZE_BULK_MAX
Size of CDC host receive buffer.
This configuration defines the size in bytes of the buffer used to store data received from CDC devices. A larger buffer allows handling more data before the application needs to process it, but consumes more RAM.
CFG_TUH_CDC_RX_EPSIZE
#define CFG_TUH_CDC_RX_EPSIZE USBH_EPSIZE_BULK_MAX
Maximum CDC endpoint size for receiving data.
This configuration defines the maximum endpoint size in bytes that the CDC host driver will use when communicating with CDC devices. This should be set to accommodate the largest endpoint size of any CDC device you intend to support.
CFG_TUH_CDC_TX_BUFSIZE
#define CFG_TUH_CDC_TX_BUFSIZE USBH_EPSIZE_BULK_MAX
Size of CDC host transmit buffer.
This configuration defines the size in bytes of the buffer used to store data waiting to be transmitted to CDC devices. A larger buffer allows the application to queue more data for transmission at once, but consumes more RAM.
CFG_TUH_CDC_TX_EPSIZE
#define CFG_TUH_CDC_TX_EPSIZE USBH_EPSIZE_BULK_MAX
Maximum CDC endpoint size for transmitting data.
This configuration defines the maximum endpoint size in bytes that the CDC host driver will use when sending data to CDC devices. This should be set to accommodate the largest endpoint size of any CDC device you intend to support.
Function Documentation
tuh_cdc_itf_get_index()
uint8_t tuh_cdc_itf_get_index (uint8_t daddr, uint8_t itf_num)
Get CDC interface index from device address and interface number.
This function searches for a CDC interface matching the specified device address and interface number, returning its index within the CDC interface table.
Parameters
[in] daddr Device address
[in] itf_num Interface number
Returns
Global instance index (0 to CFG_TUH_CDC-1) if found
TUSB_INDEX_INVALID_8 (0xFF) if the interface is not found
tuh_cdc_itf_get_info()
bool tuh_cdc_itf_get_info (uint8_t idx, tuh_itf_info_t * info)
Get detailed information about a CDC interface.
This function retrieves detailed information about a CDC interface identified by its index, populating the provided interface info structure. The information includes device address and interface descriptor details.
Parameters
[in] idx CDC interface index (from tuh_cdc_itf_get_index)
[out] info Pointer to interface information structure to be filled
Returns
true if successful and interface is mounted
false if index is invalid or interface is not mounted
tuh_cdc_mounted()
bool tuh_cdc_mounted (uint8_t idx)
Check if a CDC device is mounted.
This function checks whether a CDC device with the specified interface index is currently mounted and ready for communication.
Parameters
[in] idx CDC interface index
Returns
true if the CDC interface is mounted and ready
false if the interface is not mounted or the index is invalid
tuh_cdc_get_dtr()
bool tuh_cdc_get_dtr (uint8_t idx)
Get current DTR (Data Terminal Ready) status.
This function retrieves the current state of the DTR (Data Terminal Ready) control signal for the specified CDC interface.
Parameters
[in] idx CDC interface index
Returns
true if DTR is active (asserted)
false if DTR is inactive or the interface index is invalid
Referenced by tuh_cdc_connected().
tuh_cdc_get_rts()
bool tuh_cdc_get_rts (uint8_t idx)
Get current RTS (Request To Send) status.
This function retrieves the current state of the RTS (Request To Send) control signal for the specified CDC interface.
Parameters
[in] idx CDC interface index
Returns
true if RTS is active (asserted)
false if RTS is inactive or the interface index is invalid
tuh_cdc_connected()
static TU_ATTR_ALWAYS_INLINE bool tuh_cdc_connected (uint8_t idx) inline static
Check if a terminal client is connected to the CDC device.
This function checks if a terminal client is connected to the CDC device by examining the DTR (Data Terminal Ready) signal. A terminal is considered connected when DTR is active.
Parameters
[in] idx CDC interface index
Returns
true if a terminal is connected (DTR is active)
false if no terminal is connected or the interface index is invalid
References tuh_cdc_get_dtr(), tuh_cdc_get_local_line_coding(), tuh_cdc_peek(), tuh_cdc_read(), tuh_cdc_read_available(), tuh_cdc_read_clear(), tuh_cdc_set_baudrate(), tuh_cdc_set_control_line_state(), tuh_cdc_set_data_format(), tuh_cdc_set_line_coding(), tuh_cdc_write(), tuh_cdc_write_available(), tuh_cdc_write_clear(), and tuh_cdc_write_flush().
tuh_cdc_get_local_line_coding()
bool tuh_cdc_get_local_line_coding (uint8_t idx, cdc_line_coding_t * line_coding)
Get locally cached line coding parameters.
This function retrieves the locally cached line coding parameters for the specified CDC interface. These parameters include baud rate, stop bits, parity, and data bits.
Parameters
[in] idx CDC interface index
[out] line_coding Pointer to a structure where line coding parameters will be stored
Returns
true if successful and line coding parameters are valid
false if the interface index is invalid
Note
This function returns cached values and does not make any USB transfers
Values will be valid if tuh_cdc_set_line_coding() was previously called, or if CFG_TUH_CDC_LINE_CODING_ON_ENUM is defined
Referenced by tuh_cdc_connected().
tuh_cdc_write_available()
uint32_t tuh_cdc_write_available (uint8_t idx)
Get the number of bytes available for writing.
This function returns the amount of space available in the transmit buffer for the specified CDC interface. Applications can use this to determine how much data can be written without overflowing the buffer.
Parameters
[in] idx CDC interface index
Returns
The number of bytes available in the transmit buffer
0 if the interface index is invalid
Referenced by tuh_cdc_connected().
tuh_cdc_write()
uint32_t tuh_cdc_write (uint8_t idx, void const * buffer, uint32_t bufsize)
Write data to CDC interface.
This function writes data to the transmit buffer of the specified CDC interface. The data will be sent to the connected CDC device when appropriate.
Parameters
[in] idx CDC interface index
[in] buffer Pointer to the data to be written
[in] bufsize Number of bytes to write
Returns
The number of bytes actually written to the buffer
0 if the interface index is invalid or if write failed
Referenced by tuh_cdc_connected().
tuh_cdc_write_flush()
uint32_t tuh_cdc_write_flush (uint8_t idx)
Flush data in the transmit buffer to the CDC device.
This function initiates the actual transfer of data from the transmit buffer to the connected CDC device. It should be called after tuh_cdc_write() to ensure data is sent, especially when the buffer is not filled completely.
Parameters
[in] idx CDC interface index
Returns
true if the flush operation was successfully initiated
false if the interface index is invalid or if the device is not ready
Referenced by tuh_cdc_connected().
tuh_cdc_write_clear()
bool tuh_cdc_write_clear (uint8_t idx)
Clear the transmit buffer.
This function clears all data in the transmit buffer for the specified CDC interface, discarding any data that has not yet been sent to the device.
Parameters
[in] idx CDC interface index
Returns
true if the buffer was successfully cleared
false if the interface index is invalid
Referenced by tuh_cdc_connected().
tuh_cdc_read_available()
uint32_t tuh_cdc_read_available (uint8_t idx)
Get the number of bytes available for reading.
This function returns the number of bytes available in the receive buffer for the specified CDC interface. Applications can use this to determine how much data can be read without blocking.
Parameters
[in] idx CDC interface index
Returns
The number of bytes available to read from the receive buffer
0 if the interface index is invalid or no data is available
Referenced by tuh_cdc_connected().
tuh_cdc_read()
uint32_t tuh_cdc_read (uint8_t idx, void * buffer, uint32_t bufsize)
Read data from CDC interface.
This function reads data from the receive buffer of the specified CDC interface. The data is copied from the internal buffer to the provided destination buffer.
Parameters
[in] idx CDC interface index
[out] buffer Pointer to the destination buffer where data will be stored
[in] bufsize Maximum number of bytes to read
Returns
The number of bytes actually read
0 if the interface index is invalid or no data is available
Referenced by tuh_cdc_connected().
tuh_cdc_peek()
bool tuh_cdc_peek (uint8_t idx, uint8_t * ch)
Peek at the next byte in the receive buffer without removing it.
This function examines the next byte in the receive buffer without removing it. The data remains in the buffer and can be later read using tuh_cdc_read().
Parameters
[in] idx CDC interface index
[out] ch Pointer to store the peeked character
Returns
true if a character was successfully peeked
false if the interface index is invalid or no data is available
Referenced by tuh_cdc_connected().
tuh_cdc_read_clear()
bool tuh_cdc_read_clear (uint8_t idx)
Clear the receive buffer for a CDC interface.
This function discards all data in the receive buffer of the specified CDC interface. Any pending data waiting to be read will be lost.
Parameters
[in] idx CDC interface index
Returns
true if the buffer was successfully cleared
false if the interface index is invalid
Referenced by tuh_cdc_connected().
tuh_cdc_set_control_line_state()
bool tuh_cdc_set_control_line_state (uint8_t idx, uint16_t line_state, tuh_xfer_cb_t complete_cb, uintptr_t user_data)
Set control line state (DTR/RTS) for a CDC interface.
This function sends a SET_CONTROL_LINE_STATE request to the CDC device to control the DTR (Data Terminal Ready) and RTS (Request To Send) signals.
Parameters
[in] idx CDC interface index
[in] line_state Control line state bitmap:
Bit 0: DTR (CDC_CONTROL_LINE_STATE_DTR)
Bit 1: RTS (CDC_CONTROL_LINE_STATE_RTS)
[in] complete_cb Callback function to be invoked when the request completes (can be NULL for blocking operation)
[in] user_data User data to be passed to the callback function
Returns
true if the request was successfully submitted
false if the interface index is invalid or request submission failed
Referenced by tuh_cdc_connect(), tuh_cdc_connected(), and tuh_cdc_disconnect().
tuh_cdc_set_baudrate()
bool tuh_cdc_set_baudrate (uint8_t idx, uint32_t baudrate, tuh_xfer_cb_t complete_cb, uintptr_t user_data)
Set the baud rate for a CDC interface.
This function sends a request to set the baud rate of the specified CDC interface. The actual implementation depends on the CDC device type (ACM, FTDI, CP210X, or CH34X).
Parameters
[in] idx CDC interface index
[in] baudrate The desired baud rate in bits per second (e.g., 9600, 115200)
[in] complete_cb Callback function to be invoked when the request completes (can be NULL for blocking operation)
[in] user_data User data to be passed to the callback function
Returns
true if the request was successfully submitted
false if the interface index is invalid or request submission failed
Referenced by tuh_cdc_connected().
tuh_cdc_set_data_format()
bool tuh_cdc_set_data_format (uint8_t idx, uint8_t stop_bits, uint8_t parity, uint8_t data_bits, tuh_xfer_cb_t complete_cb, uintptr_t user_data)
Set the data format parameters for a CDC interface.
This function configures the data format parameters (stop bits, parity, and data bits) for the specified CDC interface. The actual implementation depends on the CDC device type (ACM, FTDI, CP210X, or CH34X). Note that not all device types support this operation.
Parameters
[in] idx CDC interface index
[in] stop_bits Number of stop bits (e.g., CDC_LINE_CODING_STOP_BITS_1)
[in] parity Parity setting (e.g., CDC_LINE_CODING_PARITY_NONE)
[in] data_bits Number of data bits (e.g., 8)
[in] complete_cb Callback function to be invoked when the request completes (can be NULL for blocking operation)
[in] user_data User data to be passed to the callback function
Returns
true if the request was successfully submitted
false if the interface index is invalid or request submission failed
Referenced by tuh_cdc_connected().
tuh_cdc_set_line_coding()
bool tuh_cdc_set_line_coding (uint8_t idx, cdc_line_coding_t const * line_coding, tuh_xfer_cb_t complete_cb, uintptr_t user_data)
Set the line coding parameters for a CDC interface.
This function configures all line coding parameters (baud rate, stop bits, parity, and data bits) for the specified CDC interface in a single call. The actual implementation depends on the CDC device type, with full support in ACM and CH34x devices, but limited or no support in FTDI and CP210x devices.
Parameters
[in] idx CDC interface index
[in] line_coding Pointer to a cdc_line_coding_t structure containing the desired parameters:
bit_rate: Baud rate in bits per second (e.g., 115200)
stop_bits: Number of stop bits (e.g., CDC_LINE_CODING_STOP_BITS_1)
parity: Parity setting (e.g., CDC_LINE_CODING_PARITY_NONE)
data_bits: Number of data bits (e.g., 8)
[in] complete_cb Callback function to be invoked when the request completes (can be NULL for blocking operation)
[in] user_data User data to be passed to the callback function
Returns
true if the request was successfully submitted
false if the interface index is invalid or request submission failed
Note
This function is only fully implemented for ACM and CH34x devices. FTDI and CP210x devices have limited or no support for this operation.
Referenced by tuh_cdc_connected().
tuh_cdc_connect()
static TU_ATTR_ALWAYS_INLINE bool tuh_cdc_connect (uint8_t idx, tuh_xfer_cb_t complete_cb, uintptr_t user_data) inline static
Connect to a CDC device by setting both DTR and RTS signals.
This function establishes a connection to the specified CDC interface by setting both the DTR (Data Terminal Ready) and RTS (Request To Send) control signals. This is a common way to initialize communication with a CDC device.
Parameters
[in] idx CDC interface index
[in] complete_cb Callback function to be invoked when the request completes (can be NULL for blocking operation)
[in] user_data User data to be passed to the callback function
Returns
true if the request was successfully submitted
false if the interface index is invalid or request submission failed
References tuh_cdc_set_control_line_state().
tuh_cdc_disconnect()
static TU_ATTR_ALWAYS_INLINE bool tuh_cdc_disconnect (uint8_t idx, tuh_xfer_cb_t complete_cb, uintptr_t user_data) inline static
Disconnect from a CDC device by clearing both DTR and RTS signals.
This function terminates the connection to the specified CDC interface by clearing both the DTR (Data Terminal Ready) and RTS (Request To Send) control signals. This is a common way to properly disconnect from a CDC device.
Parameters
[in] idx CDC interface index
[in] complete_cb Callback function to be invoked when the request completes (can be NULL for blocking operation)
[in] user_data User data to be passed to the callback function
Returns
true if the request was successfully submitted
false if the interface index is invalid or request submission failed
References cdch_close(), cdch_deinit(), cdch_init(), cdch_open(), cdch_set_config(), cdch_xfer_cb(), tuh_cdc_mount_cb(), tuh_cdc_rx_cb(), tuh_cdc_set_control_line_state(), tuh_cdc_tx_complete_cb(), and tuh_cdc_umount_cb().
tuh_cdc_mount_cb()
TU_ATTR_WEAK void tuh_cdc_mount_cb (uint8_t idx)
Callback invoked when a device with CDC interface is mounted.
This callback is triggered when a USB device with a CDC interface is successfully enumerated and configured. It provides an opportunity for the application to initialize communication with the newly connected CDC device.
Parameters
[in] idx Index of the CDC interface in the internal pool
Referenced by tuh_cdc_disconnect().
tuh_cdc_umount_cb()
TU_ATTR_WEAK void tuh_cdc_umount_cb (uint8_t idx)
Callback invoked when a device with CDC interface is unmounted.
This callback is triggered when a USB device with a CDC interface is disconnected or otherwise becomes unavailable to the host. It provides an opportunity for the application to clean up any resources associated with the CDC interface.
Parameters
[in] idx Index of the CDC interface that was unmounted
Referenced by tuh_cdc_disconnect().
tuh_cdc_rx_cb()
TU_ATTR_WEAK void tuh_cdc_rx_cb (uint8_t idx)
Callback invoked when new data is received from a CDC device.
This callback is triggered when data has been received from a CDC device and is available to be read. The application should implement this callback to process incoming data from the device.
Parameters
[in] idx Index of the CDC interface that received data
Referenced by tuh_cdc_disconnect().
tuh_cdc_tx_complete_cb()
TU_ATTR_WEAK void tuh_cdc_tx_complete_cb (uint8_t idx)
Callback invoked when a transmit operation completes.
This callback is triggered when a transmit operation to a CDC device completes, indicating that space has become available in the transmit buffer. The application can implement this callback to queue more data for transmission when buffer space becomes available.
Parameters
[in] idx Index of the CDC interface that completed transmission
Referenced by tuh_cdc_disconnect().
cdch_init()
bool cdch_init (void)
Initialize CDC Host driver.
This function initializes the CDC Host driver internal structures and buffers. It clears the CDC interface data structures and sets up the endpoint streams for transmit and receive operations.
Returns
true if initialization was successful
false if initialization failed
Referenced by tuh_cdc_disconnect().
cdch_deinit()
bool cdch_deinit (void)
De-initialize CDC Host driver.
This function de-initializes the CDC Host driver, releasing resources allocated during initialization. It cleans up endpoint streams for all CDC interfaces.
Returns
true if de-initialization was successful
false if de-initialization failed
Referenced by tuh_cdc_disconnect().
cdch_open()
bool cdch_open (uint8_t rhport, uint8_t dev_addr, tusb_desc_interface_t const * itf_desc, uint16_t max_len)
Open a CDC interface for communication.
This function is called during device enumeration when a CDC interface is detected. It analyzes the interface descriptor to determine if it's a supported CDC interface (ACM subclass or vendor-specific with matching VID/PID) and initializes the appropriate driver for the device.
Parameters
[in] rhport Root hub port where the CDC device is connected
[in] dev_addr Address of the USB device
[in] itf_desc Pointer to the CDC interface descriptor
[in] max_len Maximum length of the descriptor in bytes
Returns
true if the interface was successfully opened
false if the interface could not be opened or is not supported
Referenced by tuh_cdc_disconnect().
cdch_set_config()
bool cdch_set_config (uint8_t dev_addr, uint8_t itf_num)
Configure a CDC interface after device is configured.
This function is called after the device has been configured during the enumeration process. It creates a fake transfer to initiate the configuration process for the specific CDC interface. The actual configuration is handled by the appropriate serial driver based on the device type (ACM, FTDI, CP210X, or CH34X).
Parameters
[in] dev_addr Device address
[in] itf_num Interface number
Returns
true if the configuration process was successfully initiated
false if the interface was not found or the configuration process failed
Referenced by tuh_cdc_disconnect().
cdch_xfer_cb()
bool cdch_xfer_cb (uint8_t dev_addr, uint8_t ep_addr, xfer_result_t event, uint32_t xferred_bytes)
Process transfer completion for CDC host endpoints.
This function is called when a transfer on a CDC endpoint completes. It handles different types of endpoints:
For TX endpoints: Invokes the tx_complete callback and initiates more transfers if data is available, or sends a ZLP if needed
For RX endpoints: Processes received data (with special handling for FTDI devices), invokes the rx callback, and prepares for the next transfer
For notification endpoints: Handles device status notifications
Parameters
[in] dev_addr Device address
[in] ep_addr Endpoint address including direction bit
[in] event Transfer result (success, failed, stalled)
[in] xferred_bytes Number of bytes transferred
Returns
true if the transfer was handled successfully
false if an error occurred during transfer handling
Referenced by tuh_cdc_disconnect().
cdch_close()
void cdch_close (uint8_t dev_addr)
Close a CDC interface and release its resources.
This function is called when a CDC device is disconnected or when the host needs to close communication with a CDC device. It performs the following tasks:
Invokes the application unmount callback
Resets the CDC interface data
Closes the endpoint streams for TX and RX
Parameters
[in] dev_addr Device address of the CDC device to close
Referenced by tuh_cdc_disconnect().
Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale