MSPM0G511xTinyUSBLibrary: HID_DEVICE
HID_DEVICE
Macros
#define CFG_TUD_HID_EP_BUFSIZE 64
Set size of HID endpoint buffer.
#define TUD_HID_REPORT_DESC_KEYBOARD(...)
Keyboard Report Descriptor Template.
#define TUD_HID_REPORT_DESC_MOUSE(...)
Mouse Report Descriptor Template.
#define TUD_HID_REPORT_DESC_ABSMOUSE(...)
Absolute Mouse Report Descriptor Template.
#define TUD_HID_REPORT_DESC_CONSUMER(...)
Consumer Control Report Descriptor Template.
#define TUD_HID_REPORT_DESC_SYSTEM_CONTROL(...)
System Control Report Descriptor Template.
#define TUD_HID_REPORT_DESC_GAMEPAD(...)
Gamepad Report Descriptor Template.
#define TUD_HID_REPORT_DESC_FIDO_U2F(report_size, ...)
FIDO U2F Authenticator Descriptor Template.
#define TUD_HID_REPORT_DESC_GENERIC_INOUT(report_size, ...)
HID Generic Input & Output.
#define TUD_HID_REPORT_DESC_LIGHTING(report_id)
HID Lighting and Illumination Report Descriptor Template.
Functions
bool tud_hid_n_ready (uint8_t instance)
Check if the HID interface is ready to use.
uint8_t tud_hid_n_interface_protocol (uint8_t instance)
Get the interface protocol of a HID device.
uint8_t tud_hid_n_get_protocol (uint8_t instance)
Get the current HID protocol mode.
bool tud_hid_n_report (uint8_t instance, uint8_t report_id, void const *report, uint16_t len)
Send HID report to host.
bool tud_hid_n_keyboard_report (uint8_t instance, uint8_t report_id, uint8_t modifier, const uint8_t keycode[6])
Send keyboard HID report to host.
bool tud_hid_n_mouse_report (uint8_t instance, uint8_t report_id, uint8_t buttons, int8_t x, int8_t y, int8_t vertical, int8_t horizontal)
Send mouse HID report to host.
bool tud_hid_n_abs_mouse_report (uint8_t instance, uint8_t report_id, uint8_t buttons, int16_t x, int16_t y, int8_t vertical, int8_t horizontal)
Send absolute mouse HID report to host.
bool tud_hid_n_gamepad_report (uint8_t instance, uint8_t report_id, int8_t x, int8_t y, int8_t z, int8_t rz, int8_t rx, int8_t ry, uint8_t hat, uint32_t buttons)
Send gamepad HID report to host.
static TU_ATTR_ALWAYS_INLINE bool tud_hid_ready (void)
Check if the default HID interface is ready to use.
static TU_ATTR_ALWAYS_INLINE uint8_t tud_hid_interface_protocol (void)
Get the interface protocol of a HID device.
static TU_ATTR_ALWAYS_INLINE uint8_t tud_hid_get_protocol (void)
Get the current HID protocol mode.
static TU_ATTR_ALWAYS_INLINE bool tud_hid_report (uint8_t report_id, void const *report, uint16_t len)
Send HID report to host.
static TU_ATTR_ALWAYS_INLINE bool tud_hid_keyboard_report (uint8_t report_id, uint8_t modifier, const uint8_t keycode[6])
Send keyboard HID report to host.
static TU_ATTR_ALWAYS_INLINE bool tud_hid_mouse_report (uint8_t report_id, uint8_t buttons, int8_t x, int8_t y, int8_t vertical, int8_t horizontal)
Send mouse HID report to host.
static TU_ATTR_ALWAYS_INLINE bool tud_hid_abs_mouse_report (uint8_t report_id, uint8_t buttons, int16_t x, int16_t y, int8_t vertical, int8_t horizontal)
Send absolute mouse HID report to host.
static TU_ATTR_ALWAYS_INLINE bool tud_hid_gamepad_report (uint8_t report_id, int8_t x, int8_t y, int8_t z, int8_t rz, int8_t rx, int8_t ry, uint8_t hat, uint32_t buttons)
Send gamepad HID report to host.
uint8_t const * tud_hid_descriptor_report_cb (uint8_t instance)
Callback for USB HID Report Descriptor request.
uint16_t tud_hid_get_report_cb (uint8_t instance, uint8_t report_id, hid_report_type_t report_type, uint8_t *buffer, uint16_t reqlen)
Callback for USB HID GET_REPORT control request.
void tud_hid_set_report_cb (uint8_t instance, uint8_t report_id, hid_report_type_t report_type, uint8_t const *buffer, uint16_t bufsize)
Callback for USB HID SET_REPORT control request.
void tud_hid_set_protocol_cb (uint8_t instance, uint8_t protocol)
Callback for USB HID SET_PROTOCOL control request.
bool tud_hid_set_idle_cb (uint8_t instance, uint8_t idle_rate)
Callback for USB HID SET_IDLE control request.
void tud_hid_report_complete_cb (uint8_t instance, uint8_t const *report, uint16_t len)
Callback invoked when a HID report has been successfully sent to host.
void tud_hid_report_failed_cb (uint8_t instance, hid_report_type_t report_type, uint8_t const *report, uint16_t xferred_bytes)
Callback invoked when a HID report transmission to host fails.
void hidd_init (void)
Initialize the HID Device driver.
bool hidd_deinit (void)
De-initialize the HID Device driver.
void hidd_reset (uint8_t rhport)
Reset the HID Device driver state.
uint16_t hidd_open (uint8_t rhport, tusb_desc_interface_t const *itf_desc, uint16_t max_len)
Open and initialize a HID interface.
bool hidd_control_xfer_cb (uint8_t rhport, uint8_t stage, tusb_control_request_t const *request)
Process HID-specific control transfers.
bool hidd_xfer_cb (uint8_t rhport, uint8_t ep_addr, xfer_result_t event, uint32_t xferred_bytes)
Process HID data transfers.
Detailed Description
Macro Definition Documentation
TUD_HID_REPORT_DESC_CONSUMER
#define TUD_HID_REPORT_DESC_CONSUMER (...)
Value:
HID_USAGE_PAGE (HID_USAGE_PAGE_CONSUMER)              ,\
  HID_USAGE      ( HID_USAGE_CONSUMER_CONTROL )              ,\
  HID_COLLECTION ( HID_COLLECTION_APPLICATION )              ,\
    /* Report ID if any */\
    __VA_ARGS__ \
    HID_LOGICAL_MIN  ( 0x00                                ) ,\
    HID_LOGICAL_MAX_N( 0x03FF, 2                           ) ,\
    HID_USAGE_MIN    ( 0x00                                ) ,\
    HID_USAGE_MAX_N  ( 0x03FF, 2                           ) ,\
    HID_REPORT_COUNT ( 1                                   ) ,\
    HID_REPORT_SIZE  ( 16                                  ) ,\
    HID_INPUT        ( HID_DATA | HID_ARRAY | HID_ABSOLUTE ) ,\
  HID_COLLECTION_END \
Consumer Control Report Descriptor Template.
TUD_HID_REPORT_DESC_SYSTEM_CONTROL
#define TUD_HID_REPORT_DESC_SYSTEM_CONTROL (...)
Value:
HID_USAGE_PAGE (HID_USAGE_PAGE_DESKTOP)        ,\
  HID_USAGE      ( HID_USAGE_DESKTOP_SYSTEM_CONTROL )        ,\
  HID_COLLECTION ( HID_COLLECTION_APPLICATION       )        ,\
    /* Report ID if any */\
    __VA_ARGS__ \
    /* 2 bit system power control */ \
    HID_LOGICAL_MIN  ( 1                                   ) ,\
    HID_LOGICAL_MAX  ( 3                                   ) ,\
    HID_REPORT_COUNT ( 1                                   ) ,\
    HID_REPORT_SIZE  ( 2                                   ) ,\
    HID_USAGE        ( HID_USAGE_DESKTOP_SYSTEM_POWER_DOWN ) ,\
    HID_USAGE        ( HID_USAGE_DESKTOP_SYSTEM_SLEEP      ) ,\
    HID_USAGE        ( HID_USAGE_DESKTOP_SYSTEM_WAKE_UP    ) ,\
    HID_INPUT        ( HID_DATA | HID_ARRAY | HID_ABSOLUTE ) ,\
    /* 6 bit padding */ \
    HID_REPORT_COUNT ( 1                                   ) ,\
    HID_REPORT_SIZE  ( 6                                   ) ,\
    HID_INPUT        ( HID_CONSTANT                        ) ,\
  HID_COLLECTION_END \
System Control Report Descriptor Template.
0x00 - do nothing 0x01 - Power Off 0x02 - Standby 0x03 - Wake Host
TUD_HID_REPORT_DESC_GAMEPAD
#define TUD_HID_REPORT_DESC_GAMEPAD (...)
Gamepad Report Descriptor Template.
Creates a standard HID report descriptor for a gamepad device with the following layout: | X | Y | Z | Rz | Rx | Ry (1 byte each) | hat/DPAD (1 byte) | Button Map (4 bytes) |
The gamepad includes:
2 analog joysticks (X, Y for left stick, Z, Rz for right stick)
2 analog triggers (Rx, Ry)
1 hat/DPAD (8 directions)
32 buttons (in a 4-byte bitmap)
TUD_HID_REPORT_DESC_FIDO_U2F
#define TUD_HID_REPORT_DESC_FIDO_U2F (report_size, ...)
Value:
HID_USAGE_PAGE_N (HID_USAGE_PAGE_FIDO, 2) ,\
  HID_USAGE      ( HID_USAGE_FIDO_U2FHID                       ) ,\
  HID_COLLECTION ( HID_COLLECTION_APPLICATION                  ) ,\
    /* Report ID if any */ \
    __VA_ARGS__ \
    /* Usage Data In */ \
    HID_USAGE         ( HID_USAGE_FIDO_DATA_IN                 ) ,\
    HID_LOGICAL_MIN   ( 0                                      ) ,\
    HID_LOGICAL_MAX_N ( 0xff, 2                                ) ,\
    HID_REPORT_SIZE   ( 8                                      ) ,\
    HID_REPORT_COUNT  ( report_size                            ) ,\
    HID_INPUT         ( HID_DATA | HID_VARIABLE | HID_ABSOLUTE ) ,\
    /* Usage Data Out */ \
    HID_USAGE         ( HID_USAGE_FIDO_DATA_OUT                ) ,\
    HID_LOGICAL_MIN   ( 0                                      ) ,\
    HID_LOGICAL_MAX_N ( 0xff, 2                                ) ,\
    HID_REPORT_SIZE   ( 8                                      ) ,\
    HID_REPORT_COUNT  ( report_size                            ) ,\
    HID_OUTPUT        ( HID_DATA | HID_VARIABLE | HID_ABSOLUTE ) ,\
  HID_COLLECTION_END \
FIDO U2F Authenticator Descriptor Template.
1st parameter is report size, which is 64 bytes maximum in U2F
2nd parameter is HID_REPORT_ID(n) (optional)
TUD_HID_REPORT_DESC_GENERIC_INOUT
#define TUD_HID_REPORT_DESC_GENERIC_INOUT (report_size, ...)
Value:
HID_USAGE_PAGE_N (HID_USAGE_PAGE_VENDOR, 2),\
    HID_USAGE        ( 0x01                       ),\
    HID_COLLECTION   ( HID_COLLECTION_APPLICATION ),\
      /* Report ID if any */\
      __VA_ARGS__ \
      /* Input */ \
      HID_USAGE       ( 0x02                                   ),\
      HID_LOGICAL_MIN ( 0x00                                   ),\
      HID_LOGICAL_MAX_N ( 0xff, 2                              ),\
      HID_REPORT_SIZE ( 8                                      ),\
      HID_REPORT_COUNT( report_size                            ),\
      HID_INPUT       ( HID_DATA | HID_VARIABLE | HID_ABSOLUTE ),\
      /* Output */ \
      HID_USAGE       ( 0x03                                    ),\
      HID_LOGICAL_MIN ( 0x00                                    ),\
      HID_LOGICAL_MAX_N ( 0xff, 2                               ),\
      HID_REPORT_SIZE ( 8                                       ),\
      HID_REPORT_COUNT( report_size                             ),\
      HID_OUTPUT      ( HID_DATA | HID_VARIABLE | HID_ABSOLUTE  ),\
    HID_COLLECTION_END \
HID Generic Input & Output.
1st parameter is report size (mandatory)
2nd parameter is report id HID_REPORT_ID(n) (optional)
TUD_HID_REPORT_DESC_LIGHTING
#define TUD_HID_REPORT_DESC_LIGHTING (report_id)
HID Lighting and Illumination Report Descriptor Template.
1st parameter is report id (required) Creates 6 report ids for lighting HID usages in the following order: report_id+0: HID_USAGE_LIGHTING_LAMP_ARRAY_ATTRIBUTES_REPORT report_id+1: HID_USAGE_LIGHTING_LAMP_ATTRIBUTES_REQUEST_REPORT report_id+2: HID_USAGE_LIGHTING_LAMP_ATTRIBUTES_RESPONSE_REPORT report_id+3: HID_USAGE_LIGHTING_LAMP_MULTI_UPDATE_REPORT report_id+4: HID_USAGE_LIGHTING_LAMP_RANGE_UPDATE_REPORT report_id+5: HID_USAGE_LIGHTING_LAMP_ARRAY_CONTROL_REPORT
Function Documentation
tud_hid_n_ready()
bool tud_hid_n_ready (uint8_t instance)
Check if the HID interface is ready to use.
This function checks if the specified HID interface is ready to send reports to the host. It verifies that:
The device is ready (connected and configured)
The interface has a valid IN endpoint
The IN endpoint is not currently busy with a transfer
Parameters
[in] instance The HID interface instance.
Returns
true If the interface is ready to send reports
false If the interface is not ready (device not mounted, endpoint not available, or endpoint busy)
Referenced by tud_hid_ready().
tud_hid_n_interface_protocol()
uint8_t tud_hid_n_interface_protocol (uint8_t instance)
Get the interface protocol of a HID device.
This function returns the interface protocol value (bInterfaceProtocol) for the specified HID interface instance.
Parameters
[in] instance The HID interface instance.
Returns
Interface protocol value from hid_interface_protocol_enum_t
Referenced by tud_hid_interface_protocol().
tud_hid_n_get_protocol()
uint8_t tud_hid_n_get_protocol (uint8_t instance)
Get the current HID protocol mode.
This function returns the current protocol mode (boot or report) for the specified HID interface instance.
Parameters
[in] instance The HID interface instance.
Returns
HID_PROTOCOL_BOOT (0) for Boot Protocol or HID_PROTOCOL_REPORT (1) for Report Protocol
Referenced by tud_hid_get_protocol().
tud_hid_n_report()
bool tud_hid_n_report (uint8_t instance, uint8_t report_id, void const * report, uint16_t len)
Send HID report to host.
This function sends a HID report to the host through the specified HID interface. It handles the proper formatting of the report data, including prepending the report ID if necessary.
Parameters
[in] instance The HID interface instance.
[in] report_id The report ID. Use 0 if report ID is not used in the HID descriptor.
[in] report Pointer to the report data buffer.
[in] len Length of the report data in bytes.
Returns
true if the report was successfully scheduled for transmission
false if the report could not be sent (e.g., device not ready, endpoint busy)
Referenced by tud_hid_report().
tud_hid_n_keyboard_report()
bool tud_hid_n_keyboard_report (uint8_t instance, uint8_t report_id, uint8_t modifier, const uint8_t keycode[6])
Send keyboard HID report to host.
This function sends a keyboard HID report to the host through the specified HID interface. It uses the standard boot keyboard report format as defined in HID specification.
Parameters
[in] instance The HID interface instance.
[in] report_id The report ID. Use 0 if report ID is not used in the HID descriptor.
[in] modifier Keyboard modifier keys bitmask.
[in] keycode Array of 6 key codes (HID usage codes from HID usage tables). Use 0 for unused positions.
Returns
true if the report was successfully scheduled for transmission
false if the report could not be sent (e.g., device not ready, endpoint busy)
Referenced by tud_hid_keyboard_report().
tud_hid_n_mouse_report()
bool tud_hid_n_mouse_report (uint8_t instance, uint8_t report_id, uint8_t buttons, int8_t x, int8_t y, int8_t vertical, int8_t horizontal)
Send mouse HID report to host.
This function sends a mouse HID report to the host through the specified HID interface. It uses the standard mouse report format with relative positioning as defined in HID specification.
Parameters
[in] instance The HID interface instance.
[in] report_id The report ID. Use 0 if report ID is not used in the HID descriptor.
[in] buttons Mouse buttons bitmask.
[in] x Relative X movement (-127 to 127)
[in] y Relative Y movement (-127 to 127)
[in] vertical Vertical wheel movement (-127 to 127)
[in] horizontal Horizontal wheel movement (-127 to 127)
Returns
true if the report was successfully scheduled for transmission
false if the report could not be sent (e.g., device not ready, endpoint busy)
Referenced by tud_hid_mouse_report().
tud_hid_n_abs_mouse_report()
bool tud_hid_n_abs_mouse_report (uint8_t instance, uint8_t report_id, uint8_t buttons, int16_t x, int16_t y, int8_t vertical, int8_t horizontal)
Send absolute mouse HID report to host.
This function sends an absolute positioning mouse HID report to the host through the specified HID interface. Unlike the standard mouse report which uses relative movement, this report uses absolute coordinates.
Parameters
[in] instance The HID interface instance.
[in] report_id The report ID. Use 0 if report ID is not used in the HID descriptor.
[in] buttons Mouse buttons bitmask.
[in] x Absolute X position (-32768 to 32767)
[in] y Absolute Y position (-32768 to 32767)
[in] vertical Vertical wheel movement (-127 to 127)
[in] horizontal Horizontal wheel movement (-127 to 127)
Returns
true if the report was successfully scheduled for transmission
false if the report could not be sent (e.g., device not ready, endpoint busy)
Referenced by tud_hid_abs_mouse_report().
tud_hid_n_gamepad_report()
bool tud_hid_n_gamepad_report (uint8_t instance, uint8_t report_id, int8_t x, int8_t y, int8_t z, int8_t rz, int8_t rx, int8_t ry, uint8_t hat, uint32_t buttons)
Send gamepad HID report to host.
This function sends a gamepad HID report to the host through the specified HID interface. It formats the data according to the standard gamepad report descriptor layout defined by TUD_HID_REPORT_DESC_GAMEPAD.
Parameters
[in] instance The HID interface instance.
[in] report_id The report ID. Use 0 if report ID is not used in the HID descriptor.
[in] x Left analog stick X-axis position (-127 to 127)
[in] y Left analog stick Y-axis position (-127 to 127)
[in] z Right analog stick X-axis position (-127 to 127)
[in] rz Right analog stick Y-axis position (-127 to 127)
[in] rx Left trigger position (-127 to 127)
[in] ry Right trigger position (-127 to 127)
[in] hat D-pad/hat switch position (1-8 for directions, 0 for released)
[in] buttons Button states as a bitmap (up to 32 buttons)
Returns
true if the report was successfully scheduled for transmission
false if the report could not be sent (e.g., device not ready, endpoint busy)
Referenced by tud_hid_gamepad_report().
tud_hid_ready()
static TU_ATTR_ALWAYS_INLINE bool tud_hid_ready (void) inline static
Check if the default HID interface is ready to use.
This function checks if the default HID interface is ready to send reports to the host. It verifies that:
The device is ready (connected and configured)
The interface has a valid IN endpoint
The IN endpoint is not currently busy with a transfer
Returns
true If the interface is ready to send reports
false If the interface is not ready (device not mounted, endpoint not available, or endpoint busy)
References tud_hid_n_ready().
tud_hid_interface_protocol()
static TU_ATTR_ALWAYS_INLINE uint8_t tud_hid_interface_protocol (void) inline static
Get the interface protocol of a HID device.
This function returns the interface protocol value (bInterfaceProtocol) for the default HID interface.
Returns
Interface protocol value from hid_interface_protocol_enum_t
References tud_hid_n_interface_protocol().
tud_hid_get_protocol()
static TU_ATTR_ALWAYS_INLINE uint8_t tud_hid_get_protocol (void) inline static
Get the current HID protocol mode.
This function returns the current protocol mode (boot or report) for the default HID interface.
Returns
HID_PROTOCOL_BOOT (0) for Boot Protocol or HID_PROTOCOL_REPORT (1) for Report Protocol
References tud_hid_n_get_protocol().
tud_hid_report()
static TU_ATTR_ALWAYS_INLINE bool tud_hid_report (uint8_t report_id, void const * report, uint16_t len) inline static
Send HID report to host.
This function sends a HID report to the host through the default HID interface. It handles the proper formatting of the report data, including prepending the report ID if necessary.
Parameters
[in] report_id The report ID. Use 0 if report ID is not used in the HID descriptor.
[in] report Pointer to the report data buffer.
[in] len Length of the report data in bytes.
Returns
true if the report was successfully scheduled for transmission
false if the report could not be sent (e.g., device not ready, endpoint busy)
References tud_hid_n_report().
tud_hid_keyboard_report()
static TU_ATTR_ALWAYS_INLINE bool tud_hid_keyboard_report (uint8_t report_id, uint8_t modifier, const uint8_t keycode[6]) inline static
Send keyboard HID report to host.
This function sends a keyboard HID report to the host through the default HID interface. It uses the standard boot keyboard report format as defined in HID specification.
Parameters
[in] report_id The report ID. Use 0 if report ID is not used in the HID descriptor.
[in] modifier Keyboard modifier keys bitmask.
[in] keycode Array of 6 key codes (HID usage codes from HID usage tables). Use 0 for unused positions.
Returns
true if the report was successfully scheduled for transmission
false if the report could not be sent (e.g., device not ready, endpoint busy)
References tud_hid_n_keyboard_report().
tud_hid_mouse_report()
static TU_ATTR_ALWAYS_INLINE bool tud_hid_mouse_report (uint8_t report_id, uint8_t buttons, int8_t x, int8_t y, int8_t vertical, int8_t horizontal) inline static
Send mouse HID report to host.
This function sends a mouse HID report to the host through the default HID interface. It uses the standard mouse report format with relative positioning as defined in HID specification.
Parameters
[in] report_id The report ID. Use 0 if report ID is not used in the HID descriptor.
[in] buttons Mouse buttons bitmask.
[in] x Relative X movement (-127 to 127)
[in] y Relative Y movement (-127 to 127)
[in] vertical Vertical wheel movement (-127 to 127)
[in] horizontal Horizontal wheel movement (-127 to 127)
Returns
true if the report was successfully scheduled for transmission
false if the report could not be sent (e.g., device not ready, endpoint busy)
References tud_hid_n_mouse_report().
tud_hid_abs_mouse_report()
static TU_ATTR_ALWAYS_INLINE bool tud_hid_abs_mouse_report (uint8_t report_id, uint8_t buttons, int16_t x, int16_t y, int8_t vertical, int8_t horizontal) inline static
Send absolute mouse HID report to host.
This function sends an absolute positioning mouse HID report to the host through the default HID interface. Unlike the standard mouse report which uses relative movement, this report uses absolute coordinates.
Parameters
[in] report_id The report ID. Use 0 if report ID is not used in the HID descriptor.
[in] buttons Mouse buttons bitmask.
[in] x Absolute X position (-32768 to 32767)
[in] y Absolute Y position (-32768 to 32767)
[in] vertical Vertical wheel movement (-127 to 127)
[in] horizontal Horizontal wheel movement (-127 to 127)
Returns
true if the report was successfully scheduled for transmission
false if the report could not be sent (e.g., device not ready, endpoint busy)
References tud_hid_n_abs_mouse_report().
tud_hid_gamepad_report()
static TU_ATTR_ALWAYS_INLINE bool tud_hid_gamepad_report (uint8_t report_id, int8_t x, int8_t y, int8_t z, int8_t rz, int8_t rx, int8_t ry, uint8_t hat, uint32_t buttons) inline static
Send gamepad HID report to host.
This function sends a gamepad HID report to the host through the default HID interface. It formats the data according to the standard gamepad report descriptor layout defined by TUD_HID_REPORT_DESC_GAMEPAD.
Parameters
[in] report_id The report ID. Use 0 if report ID is not used in the HID descriptor.
[in] x Left analog stick X-axis position (-127 to 127)
[in] y Left analog stick Y-axis position (-127 to 127)
[in] z Right analog stick X-axis position (-127 to 127)
[in] rz Right analog stick Y-axis position (-127 to 127)
[in] rx Left trigger position (-127 to 127)
[in] ry Right trigger position (-127 to 127)
[in] hat D-pad/hat switch position (1-8 for directions, 0 for released)
[in] buttons Button states as a bitmap (up to 32 buttons)
Returns
true if the report was successfully scheduled for transmission
false if the report could not be sent (e.g., device not ready, endpoint busy)
References tud_hid_descriptor_report_cb(), tud_hid_get_report_cb(), tud_hid_n_gamepad_report(), tud_hid_report_complete_cb(), tud_hid_report_failed_cb(), tud_hid_set_idle_cb(), tud_hid_set_protocol_cb(), and tud_hid_set_report_cb().
tud_hid_descriptor_report_cb()
uint8_t const* tud_hid_descriptor_report_cb (uint8_t instance)
Callback for USB HID Report Descriptor request.
This callback is invoked when the USB host requests the HID Report Descriptor via a GET_DESCRIPTOR request. The application must return a pointer to the appropriate descriptor based on the interface instance.
Parameters
[in] instance The HID interface instance for which the descriptor is requested. For devices with multiple HID interfaces, this parameter identifies which interface's descriptor should be returned.
Returns
A pointer to the HID Report Descriptor for the specified interface instance. The descriptor must remain valid in memory until the transfer completes.
Referenced by tud_hid_gamepad_report().
tud_hid_get_report_cb()
uint16_t tud_hid_get_report_cb (uint8_t instance, uint8_t report_id, hid_report_type_t report_type, uint8_t * buffer, uint16_t reqlen)
Callback for USB HID GET_REPORT control request.
This callback is invoked when the USB host sends a GET_REPORT control request to retrieve a specific HID report from the device. The application must fill the provided buffer with the requested report data and return the actual length of the report.
Parameters
[in] instance The HID interface instance for which the report is requested.
[in] report_id The Report ID being requested. If report IDs are not used in the HID descriptor, this parameter will be zero.
[in] report_type Type of report requested (INPUT, OUTPUT, or FEATURE).
[out] buffer Buffer where the application should write the report data.
[in] reqlen Maximum length of the buffer provided by the host.
Returns
The actual number of bytes written to the buffer. Return zero to cause the stack to STALL the request, indicating the report is not supported or not available.
Referenced by tud_hid_gamepad_report().
tud_hid_set_report_cb()
void tud_hid_set_report_cb (uint8_t instance, uint8_t report_id, hid_report_type_t report_type, uint8_t const * buffer, uint16_t bufsize)
Callback for USB HID SET_REPORT control request.
This callback is invoked when:
The USB host sends a SET_REPORT control request to set a specific HID report
Data is received on the OUT endpoint (for Report ID = 0, Type = OUTPUT)
The application should process the report data provided by the host and update the device state accordingly.
Parameters
[in] instance The HID interface instance for which the report is being set.
[in] report_id The Report ID being set. If report IDs are not used in the HID descriptor, this parameter will be zero.
[in] report_type Type of report being set (INPUT, OUTPUT, or FEATURE).
[in] buffer Buffer containing the report data from the host.
[in] bufsize Size of the report data in bytes.
Referenced by tud_hid_gamepad_report().
tud_hid_set_protocol_cb()
void tud_hid_set_protocol_cb (uint8_t instance, uint8_t protocol)
Callback for USB HID SET_PROTOCOL control request.
This callback is invoked when the USB host sends a SET_PROTOCOL control request to switch between Boot Protocol and Report Protocol modes. The device should adjust its behavior according to the requested protocol mode.
Parameters
[in] instance The HID interface instance for which the protocol mode is being set.
[in] protocol The protocol mode being set:
HID_PROTOCOL_BOOT (0): Boot Protocol
HID_PROTOCOL_REPORT (1): Report Protocol
Referenced by tud_hid_gamepad_report().
tud_hid_set_idle_cb()
bool tud_hid_set_idle_cb (uint8_t instance, uint8_t idle_rate)
Callback for USB HID SET_IDLE control request.
This callback is invoked when the USB host sends a SET_IDLE control request to configure the idle rate for HID reports. The idle rate determines how often the device should send reports even when there are no changes in the data.
Parameters
[in] instance The HID interface instance for which the idle rate is being set.
[in] idle_rate The idle rate value:
0: Only send report if there are changes (i.e., skip duplicates)
1-255: Send at least one report every (idle_rate 4) ms, even if there are no changes in the data.
Returns
true to accept the idle rate setting.
false to stall the request, indicating the device does not support the requested idle rate.
Referenced by tud_hid_gamepad_report().
tud_hid_report_complete_cb()
void tud_hid_report_complete_cb (uint8_t instance, uint8_t const * report, uint16_t len)
Callback invoked when a HID report has been successfully sent to host.
This callback is invoked when a HID report has been successfully transmitted to the host over the USB IN endpoint. The application can use this callback to send the next report or perform other actions after a successful transfer.
Parameters
[in] instance The HID interface instance that completed the report transfer.
[in] report Pointer to the report data that was sent. For reports using report IDs, report[0] contains the report ID.
[in] len Length of the report in bytes.
Referenced by tud_hid_gamepad_report().
tud_hid_report_failed_cb()
void tud_hid_report_failed_cb (uint8_t instance, hid_report_type_t report_type, uint8_t const * report, uint16_t xferred_bytes)
Callback invoked when a HID report transmission to host fails.
This callback is invoked when a HID report transmission to the host fails due to errors such as bus errors, NAK handling timeout, or other USB transmission issues. The application can use this callback to handle the error, retry the transmission, or take other corrective actions.
Parameters
[in] instance The HID interface instance that experienced the failed report transfer.
[in] report_type Type of report that failed (INPUT, OUTPUT, or FEATURE).
[in] report Pointer to the report data that failed to send. For reports using report IDs, report[0] contains the report ID.
[in] xferred_bytes Number of bytes transferred before the failure occurred.
Referenced by tud_hid_gamepad_report().
hidd_init()
void hidd_init (void)
Initialize the HID Device driver.
This internal function initializes the HID Device driver component of the TinyUSB stack. It sets up the necessary data structures and state for handling HID device functionality, including report endpoints, interface settings, and protocol state.
This function is called automatically by the TinyUSB device stack during device initialization. It prepares the HID class driver to handle HID-specific USB requests and report transfers.
hidd_deinit()
bool hidd_deinit (void)
De-initialize the HID Device driver.
This internal function de-initializes the HID Device driver component of the TinyUSB stack. It releases resources and cleans up any state used by the HID device functionality.
This function is called automatically by the TinyUSB device stack during device de-initialization or when the device is being detached from the bus. It ensures proper cleanup of HID-specific resources.
Returns
true if the de-initialization is successful
false if the de-initialization fails
hidd_reset()
void hidd_reset (uint8_t rhport)
Reset the HID Device driver state.
This internal function resets the HID Device driver's internal state when a USB reset is detected on the specified root hub port. It clears all interface-specific data structures and prepares the driver for a new enumeration sequence.
Parameters
[in] rhport Root Hub Port index (USB controller index) where the reset occurred
hidd_open()
uint16_t hidd_open (uint8_t rhport, tusb_desc_interface_t const * itf_desc, uint16_t max_len)
Open and initialize a HID interface.
This internal function is called during device enumeration when the host configures a HID interface. It parses the interface descriptor, initializes the interface-specific data structures, and prepares endpoints for data transfer.
The function validates that the interface is a HID class interface, finds an available interface slot in the driver's internal array, and configures the endpoints according to the interface descriptor.
Parameters
[in] rhport Root Hub Port index (USB controller index)
[in] itf_desc Pointer to the interface descriptor
[in] max_len Maximum length of the descriptor set
Returns
The number of bytes processed from the descriptor set, or 0 if the interface couldn't be configured
hidd_control_xfer_cb()
bool hidd_control_xfer_cb (uint8_t rhport, uint8_t stage, tusb_control_request_t const * request)
Process HID-specific control transfers.
This internal callback function handles control transfers targeted at HID interfaces. It processes standard and class-specific HID requests according to the USB HID specification, including descriptor requests, report requests, protocol mode selection, and idle rate control.
The function is invoked by the USB device stack during different stages of control transfers (setup, data, acknowledgment) and responds appropriately to each request type.
Parameters
[in] rhport Root Hub Port index (USB controller index)
[in] stage Current stage of the control transfer (setup, data, or ACK)
[in] request Pointer to the USB control request structure
Returns
true if the request was processed successfully
false to stall the control endpoint (unsupported request)
hidd_xfer_cb()
bool hidd_xfer_cb (uint8_t rhport, uint8_t ep_addr, xfer_result_t event, uint32_t xferred_bytes)
Process HID data transfers.
This internal callback function handles data transfer completion events for HID endpoints. It is invoked by the USB device stack when data has been transmitted or received on a HID endpoint, and it dispatches the appropriate callbacks based on the endpoint direction and transfer result.
For IN endpoints (device-to-host), it calls the report completion or failure callbacks. For OUT endpoints (host-to-device), it processes received reports and prepares the endpoint for the next transfer.
Parameters
[in] rhport Root Hub Port index (USB controller index)
[in] ep_addr Endpoint address on which the transfer occurred
[in] event Result of the transfer (success or error code)
[in] xferred_bytes Number of bytes transferred
Returns
true to continue with further processing
false to halt further processing
Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale