MSPM0L211X_L112X Driver Library: Unified Communication Module (UNICOMM) - Inter-Integrated Circuit Controller (I2CC)
Unified Communication Module (UNICOMM) - Inter-Integrated Circuit Controller (I2CC)
Modules
DL_I2CC_STATUS
DL_I2CC_INTERRUPT
DL_I2CC_DMA_INTERRUPT
Data Structures
struct DL_I2CC_ClockConfig
Configuration struct for DL_I2CC_setClockConfig.
Macros
#define DL_I2CC_TX_FIFO_COUNT_MAXIMUM ((uint32_t)UNICOMMI2CC_SYS_FENTRIES << 8)
I2CC number of bytes which could be put into the TX FIFO.
#define DL_I2CC_RX_FIFO_COUNT_MAXIMUM ((uint32_t)UNICOMMI2CC_SYS_FENTRIES)
I2CC number of bytes which could be put into the RX FIFO.
Enumerations
enum DL_I2CC_EVENT_ROUTE {
DL_I2CC_EVENT_ROUTE_1 = 0,
DL_I2CC_EVENT_ROUTE_2 = 12
}
enum DL_I2CC_CLOCK {
DL_I2CC_CLOCK_BUSCLK = UNICOMMI2CC_CLKSEL_BUSCLK_SEL_ENABLE,
DL_I2CC_CLOCK_MFCLK = UNICOMMI2CC_CLKSEL_MFCLK_SEL_ENABLE,
DL_I2CC_CLOCK_ASYNC_SYSCLK = UNICOMMI2CC_CLKSEL_ASYNC_SYSCLK_SEL_ENABLE,
DL_I2CC_CLOCK_ASYNC_HFCLK = UNICOMMI2CC_CLKSEL_ASYNC_HFCLK_SEL_ENABLE,
DL_I2CC_CLOCK_ASYNC_PLL = UNICOMMI2CC_CLKSEL_ASYNC_PLL_SEL_ENABLE
}
enum DL_I2CC_CLOCK_DIVIDE {
DL_I2CC_CLOCK_DIVIDE_1 = UNICOMMI2CC_CLKDIV_RATIO_DIV_BY_1,
DL_I2CC_CLOCK_DIVIDE_2 = UNICOMMI2CC_CLKDIV_RATIO_DIV_BY_2,
DL_I2CC_CLOCK_DIVIDE_3 = UNICOMMI2CC_CLKDIV_RATIO_DIV_BY_3,
DL_I2CC_CLOCK_DIVIDE_4 = UNICOMMI2CC_CLKDIV_RATIO_DIV_BY_4,
DL_I2CC_CLOCK_DIVIDE_5 = UNICOMMI2CC_CLKDIV_RATIO_DIV_BY_5,
DL_I2CC_CLOCK_DIVIDE_6 = UNICOMMI2CC_CLKDIV_RATIO_DIV_BY_6,
DL_I2CC_CLOCK_DIVIDE_7 = UNICOMMI2CC_CLKDIV_RATIO_DIV_BY_7,
DL_I2CC_CLOCK_DIVIDE_8 = UNICOMMI2CC_CLKDIV_RATIO_DIV_BY_8
}
enum DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH {
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH_DISABLED,
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_1,
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_2,
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_3,
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_4,
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_8,
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_16,
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_31
}
enum DL_I2CC_DIRECTION {
DL_I2CC_DIRECTION_TX = UNICOMMI2CC_TA_DIR_TRANSMIT,
DL_I2CC_DIRECTION_RX = UNICOMMI2CC_TA_DIR_RECEIVE
}
enum DL_I2CC_ADDRESSING_MODE {
DL_I2CC_ADDRESSING_MODE_7_BIT = UNICOMMI2CC_TA_MODE_MODE7,
DL_I2CC_ADDRESSING_MODE_10_BIT = UNICOMMI2CC_TA_MODE_MODE10
}
enum DL_I2CC_PEC_STATUS {
DL_I2CC_PEC_STATUS_CHECKED = UNICOMMI2CC_PECSR_PECSTS_CHECK_SET,
DL_I2CC_PEC_STATUS_NOT_CHECKED = UNICOMMI2CC_PECSR_PECSTS_CHECK_CLEARED
}
enum DL_I2CC_PEC_CHECK_ERROR {
DL_I2CC_PEC_CHECK_ERROR_SET = UNICOMMI2CC_PECSR_PECSTS_ERROR_SET,
DL_I2CC_PEC_CHECK_ERROR_CLEARED = UNICOMMI2CC_PECSR_PECSTS_ERROR_CLEARED
}
enum DL_I2CC_SCL {
DL_I2CC_SCL_HIGH = UNICOMMI2CC_BMON_SCL_SET,
DL_I2CC_SCL_LOW = UNICOMMI2CC_BMON_SCL_CLEARED
}
enum DL_I2CC_SDA {
DL_I2CC_SDA_HIGH = UNICOMMI2CC_BMON_SDA_SET,
DL_I2CC_SDA_LOW = UNICOMMI2CC_BMON_SDA_CLEARED
}
enum DL_I2CC_START {
DL_I2CC_START_ENABLE = UNICOMMI2CC_CTR_START_ENABLE,
DL_I2CC_START_DISABLE = UNICOMMI2CC_CTR_START_DISABLE
}
enum DL_I2CC_STOP {
DL_I2CC_STOP_ENABLE = UNICOMMI2CC_CTR_STOP_ENABLE,
DL_I2CC_STOP_DISABLE = UNICOMMI2CC_CTR_STOP_DISABLE
}
enum DL_I2CC_ACK {
DL_I2CC_ACK_ENABLE = UNICOMMI2CC_CTR_ACK_ENABLE,
DL_I2CC_ACK_DISABLE = UNICOMMI2CC_CTR_ACK_DISABLE
}
enum DL_I2CC_TX_FIFO_LEVEL {
DL_I2CC_TX_FIFO_LEVEL_3_4_EMPTY = UNICOMMI2CC_IFLS_TXIFLSEL_LVL_3_4,
DL_I2CC_TX_FIFO_LEVEL_1_2_EMPTY = UNICOMMI2CC_IFLS_TXIFLSEL_LVL_1_2,
DL_I2CC_TX_FIFO_LEVEL_1_4_EMPTY = UNICOMMI2CC_IFLS_TXIFLSEL_LVL_1_4,
DL_I2CC_TX_FIFO_LEVEL_ONE_ENTRY = UNICOMMI2CC_IFLS_TXIFLSEL_LVL_NOT_FULL,
DL_I2CC_TX_FIFO_LEVEL_EMPTY = UNICOMMI2CC_IFLS_TXIFLSEL_LVL_EMPTY,
DL_I2CC_TX_FIFO_LEVEL_ALMOST_EMPTY,
DL_I2CC_TX_FIFO_LEVEL_ALMOST_FULL
}
enum DL_I2CC_RX_FIFO_LEVEL {
DL_I2CC_RX_FIFO_LEVEL_3_4_FULL = UNICOMMI2CC_IFLS_RXIFLSEL_LVL_3_4,
DL_I2CC_RX_FIFO_LEVEL_1_2_FULL = UNICOMMI2CC_IFLS_RXIFLSEL_LVL_1_2,
DL_I2CC_RX_FIFO_LEVEL_1_4_FULL = UNICOMMI2CC_IFLS_RXIFLSEL_LVL_1_4,
DL_I2CC_RX_FIFO_LEVEL_ONE_ENTRY = UNICOMMI2CC_IFLS_RXIFLSEL_LVL_NOT_EMPTY,
DL_I2CC_RX_FIFO_LEVEL_FULL = UNICOMMI2CC_IFLS_RXIFLSEL_LVL_FULL,
DL_I2CC_RX_FIFO_LEVEL_ALMOST_FULL,
DL_I2CC_RX_FIFO_LEVEL_ALMOST_EMPTY
}
enum DL_I2CC_IIDX {
DL_I2CC_IIDX_NO_INT = UNICOMMI2CC_IIDX_STAT_NO_INTR,
DL_I2CC_IIDX_RX_DONE = UNICOMMI2CC_IIDX_STAT_RXDONEFG,
DL_I2CC_IIDX_TX_DONE = UNICOMMI2CC_IIDX_STAT_TXDONEFG,
DL_I2CC_IIDX_RXFIFO_TRIGGER = UNICOMMI2CC_IIDX_STAT_RXTRG,
DL_I2CC_IIDX_TXFIFO_TRIGGER = UNICOMMI2CC_IIDX_STAT_TXTRG,
DL_I2CC_IIDX_RXFIFO_FULL = UNICOMMI2CC_IIDX_STAT_RXFULL,
DL_I2CC_IIDX_TXFIFO_EMPTY = UNICOMMI2CC_IIDX_STAT_TXEMPTY,
DL_I2CC_IIDX_NACK = UNICOMMI2CC_IIDX_STAT_NACKFG,
DL_I2CC_IIDX_START = UNICOMMI2CC_IIDX_STAT_STARTFG,
DL_I2CC_IIDX_STOP = UNICOMMI2CC_IIDX_STAT_STOPFG,
DL_I2CC_IIDX_ARBITRATION_LOST = UNICOMMI2CC_IIDX_STAT_ARBLOSTFG,
DL_I2CC_IIDX_EVENT1_DMA_DONE = UNICOMMI2CC_IIDX_STAT_DMA_DONE_TX,
DL_I2CC_IIDX_EVENT2_DMA_DONE = UNICOMMI2CC_IIDX_STAT_DMA_DONE_RX,
DL_I2CC_IIDX_PREEMPT_INT_TX = UNICOMMI2CC_IIDX_STAT_DMA_PREIRQ_TX,
DL_I2CC_IIDX_PREEMPT_INT_RX = UNICOMMI2CC_IIDX_STAT_DMA_PREIRQ_RX,
DL_I2CC_IIDX_PEC_RX_ERROR = UNICOMMI2CC_IIDX_STAT_PEC_RX_ERR,
DL_I2CC_IIDX_TIMEOUT_A = UNICOMMI2CC_IIDX_STAT_TIMEOUTA,
DL_I2CC_IIDX_TIMEOUT_B = UNICOMMI2CC_IIDX_STAT_TIMEOUTB
}
Functions
void DL_I2CC_setClockConfig (UNICOMM_Inst_Regs *unicomm, DL_I2CC_ClockConfig *config)
Configure I2CC source clock.
void DL_I2CC_getClockConfig (UNICOMM_Inst_Regs *unicomm, DL_I2CC_ClockConfig *config)
Get I2CC source clock configuration.
uint16_t DL_I2CC_fillTXFIFO (UNICOMM_Inst_Regs *unicomm, uint8_t *buffer, uint16_t count)
Fills the TX FIFO with data.
void DL_I2CC_flushTXFIFO (UNICOMM_Inst_Regs *unicomm)
Flushes/removes all elements in the TX FIFO.
void DL_I2CC_flushRXFIFO (UNICOMM_Inst_Regs *unicomm)
Flushes/removes all elements in the RX FIFO.
__STATIC_INLINE void DL_I2CC_stopFlushTXFIFO (UNICOMM_Inst_Regs *unicomm)
Stop TX FIFO flush.
__STATIC_INLINE void DL_I2CC_startFlushTXFIFO (UNICOMM_Inst_Regs *unicomm)
Start TX FIFO flush.
__STATIC_INLINE void DL_I2CC_stopFlushRXFIFO (UNICOMM_Inst_Regs *unicomm)
Stop RX FIFO flush.
__STATIC_INLINE void DL_I2CC_startFlushRXFIFO (UNICOMM_Inst_Regs *unicomm)
Start RX FIFO flush.
__STATIC_INLINE bool DL_I2CC_isTXFIFOFull (UNICOMM_Inst_Regs *unicomm)
Checks if TX FIFO is full.
__STATIC_INLINE bool DL_I2CC_isTXFIFOEmpty (UNICOMM_Inst_Regs *unicomm)
Checks if TX FIFO is empty.
__STATIC_INLINE bool DL_I2CC_isRXFIFOFull (UNICOMM_Inst_Regs *unicomm)
Checks if RX FIFO is full.
__STATIC_INLINE bool DL_I2CC_isRXFIFOEmpty (UNICOMM_Inst_Regs *unicomm)
Checks if RX FIFO is empty.
__STATIC_INLINE void DL_I2CC_resetTransfer (UNICOMM_Inst_Regs *unicomm)
Reset transfers from from UNICOMMI2CC.
__STATIC_INLINE void DL_I2CC_startTransfer (UNICOMM_Inst_Regs *unicomm, uint32_t targetAddr, DL_I2CC_DIRECTION direction, uint16_t length)
Sets up a transfer from UNICOMMI2CC.
__STATIC_INLINE void DL_I2CC_startTransferAdvanced (UNICOMM_Inst_Regs *unicomm, uint32_t targetAddr, DL_I2CC_DIRECTION direction, uint16_t length, DL_I2CC_START start, DL_I2CC_STOP stop, DL_I2CC_ACK ack)
Sets up a transfer from I2CC with control of START, STOP and ACK.
__STATIC_INLINE void DL_I2CC_enablePower (UNICOMM_Inst_Regs *unicomm)
Enables power on UNICOMM I2C module.
__STATIC_INLINE void DL_I2CC_disablePower (UNICOMM_Inst_Regs *unicomm)
Disables power on UNICOMM I2C module.
__STATIC_INLINE bool DL_I2CC_isPowerEnabled (UNICOMM_Inst_Regs *unicomm)
Returns if power on UNICOMM I2C module.
__STATIC_INLINE void DL_I2CC_reset (UNICOMM_Inst_Regs *unicomm)
Resets UNICOMM I2C peripheral.
__STATIC_INLINE bool DL_I2CC_isReset (UNICOMM_Inst_Regs *unicomm)
Returns if UNICOMM I2C peripheral was reset.
__STATIC_INLINE void DL_I2CC_selectClockSource (UNICOMM_Inst_Regs *unicomm, DL_I2CC_CLOCK clockSource)
Set Clock Source.
__STATIC_INLINE void DL_I2CC_selectClockDivider (UNICOMM_Inst_Regs *unicomm, DL_I2CC_CLOCK_DIVIDE clockDivider)
Set Clock Divider.
__STATIC_INLINE DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH DL_I2CC_getDigitalGlitchFilterPulseWidth (UNICOMM_Inst_Regs *unicomm)
Get Digital Glitch Suppression Pulse Width.
__STATIC_INLINE void DL_I2CC_setDigitalGlitchFilterPulseWidth (UNICOMM_Inst_Regs *unicomm, DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH filterWidth)
Set Digital Glitch Suppression Pulse Width.
__STATIC_INLINE void DL_I2CC_disableAnalogGlitchFilter (UNICOMM_Inst_Regs *unicomm)
Disable Analog Glitch Suppression.
__STATIC_INLINE bool DL_I2CC_isAnalogGlitchFilterEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if analog glitch suppression is enabled.
__STATIC_INLINE void DL_I2CC_enableAnalogGlitchFilter (UNICOMM_Inst_Regs *unicomm)
Enable Analog Glitch Suppression.
__STATIC_INLINE DL_I2CC_DIRECTION DL_I2CC_getDirection (UNICOMM_Inst_Regs *unicomm)
Get direction of next operation.
__STATIC_INLINE void DL_I2CC_setDirection (UNICOMM_Inst_Regs *unicomm, DL_I2CC_DIRECTION direction)
Set direction of next operation.
__STATIC_INLINE uint32_t DL_I2CC_getTargetAddress (UNICOMM_Inst_Regs *unicomm)
Get the address of the target being addressed when configured as an UNICOMMI2CC.
__STATIC_INLINE void DL_I2CC_setTargetAddress (UNICOMM_Inst_Regs *unicomm, uint32_t targetAddress)
Set the address of the target being addressed when configured as an UNICOMMI2CC.
__STATIC_INLINE DL_I2CC_ADDRESSING_MODE DL_I2CC_getAddressingMode (UNICOMM_Inst_Regs *unicomm)
Get addressing mode.
__STATIC_INLINE void DL_I2CC_setAddressingMode (UNICOMM_Inst_Regs *unicomm, DL_I2CC_ADDRESSING_MODE mode)
Set addressing mode between 7-bit and 10-bit mode.
__STATIC_INLINE void DL_I2CC_disableACKOverride (UNICOMM_Inst_Regs *unicomm)
Disable ACK override.
__STATIC_INLINE bool DL_I2CC_isACKOverrideEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if ACK override is enabled.
__STATIC_INLINE void DL_I2CC_enableACKOverride (UNICOMM_Inst_Regs *unicomm)
Enable ACK override.
__STATIC_INLINE void DL_I2CC_disableReadOnTXEmpty (UNICOMM_Inst_Regs *unicomm)
Disable read on TX empty.
__STATIC_INLINE bool DL_I2CC_isReadOnTXEmptyEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if read on TX empty is enabled.
__STATIC_INLINE void DL_I2CC_enableReadOnTXEmpty (UNICOMM_Inst_Regs *unicomm)
Enable read on TX empty.
__STATIC_INLINE uint32_t DL_I2CC_getPECCountValue (UNICOMM_Inst_Regs *unicomm)
Get the SMBus/PMBus Packet Error Checking (PEC) count value.
__STATIC_INLINE void DL_I2CC_setPECCountValue (UNICOMM_Inst_Regs *unicomm, uint32_t count)
Set the SMBus/PMBus Packet Error Checking (PEC) count value.
__STATIC_INLINE void DL_I2CC_disablePEC (UNICOMM_Inst_Regs *unicomm)
Disable SMBus/PMBus Packet Error Checking (PEC)
__STATIC_INLINE bool DL_I2CC_isPECEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if SMBus/PMBus Packet Error Checking (PEC) is enabled.
__STATIC_INLINE void DL_I2CC_enablePEC (UNICOMM_Inst_Regs *unicomm)
Enable SMBus/PMBus Packet Error Checking (PEC)
__STATIC_INLINE uint32_t DL_I2CC_getCurrentPECCount (UNICOMM_Inst_Regs *unicomm)
Get the current SMBus/PMBus PEC byte count of the state machine.
__STATIC_INLINE DL_I2CC_PEC_STATUS DL_I2CC_getPECCheckedStatus (UNICOMM_Inst_Regs *unicomm)
If SMBus/PMBus PEC was checked in last transaction.
__STATIC_INLINE DL_I2CC_PEC_CHECK_ERROR DL_I2CC_getPECCheckError (UNICOMM_Inst_Regs *unicomm)
Get the status of the SMBus/PMBus PEC Check error.
__STATIC_INLINE void DL_I2CC_disableStartCondition (UNICOMM_Inst_Regs *unicomm)
Disable I2CC START generation.
__STATIC_INLINE bool DL_I2CC_isStartConditionEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if I2CC START generation is enabled.
__STATIC_INLINE void DL_I2CC_enableStartCondition (UNICOMM_Inst_Regs *unicomm)
Enable I2CC START generation.
__STATIC_INLINE void DL_I2CC_disableStopCondition (UNICOMM_Inst_Regs *unicomm)
Disable I2CC STOP generation.
__STATIC_INLINE bool DL_I2CC_isStopConditionEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if I2CC STOP generation is enabled.
__STATIC_INLINE void DL_I2CC_enableStopCondition (UNICOMM_Inst_Regs *unicomm)
Enable I2CC STOP generation.
__STATIC_INLINE void DL_I2CC_disableACK (UNICOMM_Inst_Regs *unicomm)
Disable I2CC data acknowledge (ACK or NACK)
__STATIC_INLINE bool DL_I2CC_isACKEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if I2CC data acknowledge (ACK or NACK) is enabled.
__STATIC_INLINE void DL_I2CC_enableACK (UNICOMM_Inst_Regs *unicomm)
Enable I2CC data acknowledge (ACK or NACK)
__STATIC_INLINE uint32_t DL_I2CC_getTransactionLength (UNICOMM_Inst_Regs *unicomm)
Get transaction length in bytes.
__STATIC_INLINE void DL_I2CC_setTransactionLength (UNICOMM_Inst_Regs *unicomm, uint32_t length)
Set transaction length in bytes.
__STATIC_INLINE uint32_t DL_I2CC_getStatus (UNICOMM_Inst_Regs *unicomm)
Get status of I2CC bus for.
__STATIC_INLINE uint16_t DL_I2CC_getTransactionCount (UNICOMM_Inst_Regs *unicomm)
Get transaction count in bytes.
__STATIC_INLINE uint8_t DL_I2CC_receiveData (UNICOMM_Inst_Regs *unicomm)
Get byte of data from UNICOMMI2CC.
__STATIC_INLINE void DL_I2CC_transmitData (UNICOMM_Inst_Regs *unicomm, uint8_t data)
Set next byte to be transferred during the next transaction.
__STATIC_INLINE uint8_t DL_I2CC_getTimerPeriod (UNICOMM_Inst_Regs *unicomm)
Get timer period This field is used in the equation to configure SCL_PERIOD:
__STATIC_INLINE void DL_I2CC_setTimerPeriod (UNICOMM_Inst_Regs *unicomm, uint8_t period)
Set timer period This field is used in the equation to configure SCL_PERIOD:
__STATIC_INLINE void DL_I2CC_disableMultiMode (UNICOMM_Inst_Regs *unicomm)
Disable multimode.
__STATIC_INLINE bool DL_I2CC_isMultiModeEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if multimode is enabled.
__STATIC_INLINE void DL_I2CC_enableMultiMode (UNICOMM_Inst_Regs *unicomm)
Enable multimode.
__STATIC_INLINE void DL_I2CC_disable (UNICOMM_Inst_Regs *unicomm)
Disable controller.
__STATIC_INLINE bool DL_I2CC_isEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if controller is enabled.
__STATIC_INLINE void DL_I2CC_enable (UNICOMM_Inst_Regs *unicomm)
Enable controller.
__STATIC_INLINE void DL_I2CC_disableClockStretching (UNICOMM_Inst_Regs *unicomm)
Disable clock stretching.
__STATIC_INLINE bool DL_I2CC_isClockStretchingEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if clock stretching is enabled.
__STATIC_INLINE void DL_I2CC_enableClockStretching (UNICOMM_Inst_Regs *unicomm)
Enable clock stretching.
__STATIC_INLINE DL_I2CC_SCL DL_I2CC_getSCLStatus (UNICOMM_Inst_Regs *unicomm)
Get SCL signal status.
__STATIC_INLINE DL_I2CC_SDA DL_I2CC_getSDAStatus (UNICOMM_Inst_Regs *unicomm)
Get SDA signal status.
__STATIC_INLINE DL_I2CC_TX_FIFO_LEVEL DL_I2CC_getTXFIFOThreshold (UNICOMM_Inst_Regs *unicomm)
Get TX FIFO threshold level.
__STATIC_INLINE void DL_I2CC_setTXFIFOThreshold (UNICOMM_Inst_Regs *unicomm, DL_I2CC_TX_FIFO_LEVEL level)
Set TX FIFO threshold level.
__STATIC_INLINE DL_I2CC_RX_FIFO_LEVEL DL_I2CC_getRXFIFOThreshold (UNICOMM_Inst_Regs *unicomm)
Get RX FIFO threshold level.
__STATIC_INLINE void DL_I2CC_setRXFIFOThreshold (UNICOMM_Inst_Regs *unicomm, DL_I2CC_RX_FIFO_LEVEL level)
Set RX FIFO threshold level.
__STATIC_INLINE uint32_t DL_I2CC_getRXFIFOCounter (UNICOMM_Inst_Regs *unicomm)
Get number of bytes which can be read from RX FIFO.
__STATIC_INLINE uint32_t DL_I2CC_getTXFIFOCounter (UNICOMM_Inst_Regs *unicomm)
Get number of bytes which can be put into TX FIFO.
__STATIC_INLINE void DL_I2CC_enableInterrupt (UNICOMM_Inst_Regs *unicomm, uint32_t interruptMask)
Enable I2CC interrupts.
__STATIC_INLINE void DL_I2CC_disableInterrupt (UNICOMM_Inst_Regs *unicomm, uint32_t interruptMask)
Disable I2CC interrupts.
__STATIC_INLINE uint32_t DL_I2CC_getEnabledInterrupts (UNICOMM_Inst_Regs *unicomm, uint32_t interruptMask)
Check which I2CC interrupts are enabled.
__STATIC_INLINE uint32_t DL_I2CC_getEnabledInterruptStatus (UNICOMM_Inst_Regs *unicomm, uint32_t interruptMask)
Check interrupt flag of enabled I2CC interrupts.
__STATIC_INLINE uint32_t DL_I2CC_getRawInterruptStatus (UNICOMM_Inst_Regs *unicomm, uint32_t interruptMask)
Check interrupt flag of any I2CC interrupt.
__STATIC_INLINE DL_I2CC_IIDX DL_I2CC_getPendingInterrupt (UNICOMM_Inst_Regs *unicomm)
Get highest priority pending I2CC interrupt.
__STATIC_INLINE void DL_I2CC_clearInterruptStatus (UNICOMM_Inst_Regs *unicomm, uint32_t interruptMask)
Clear pending I2CC interrupts.
__STATIC_INLINE void DL_I2CC_enableDMAEvent (UNICOMM_Inst_Regs *unicomm, DL_I2CC_EVENT_ROUTE index, uint32_t interrupt)
Enables I2CC interrupt for triggering DMA events.
__STATIC_INLINE void DL_I2CC_disableDMAEvent (UNICOMM_Inst_Regs *unicomm, DL_I2CC_EVENT_ROUTE index, uint32_t interrupt)
Disables I2CC interrupt from triggering DMA events.
__STATIC_INLINE uint32_t DL_I2CC_getEnabledDMAEvents (UNICOMM_Inst_Regs *unicomm, DL_I2CC_EVENT_ROUTE index, uint32_t interruptMask)
Check which I2CC interrupt for DMA receive events is enabled.
__STATIC_INLINE uint32_t DL_I2CC_getEnabledDMAEventStatus (UNICOMM_Inst_Regs *unicomm, DL_I2CC_EVENT_ROUTE index, uint32_t interruptMask)
Check interrupt flag of enabled I2CC interrupt for DMA event.
__STATIC_INLINE uint32_t DL_I2CC_getRawDMAEventStatus (UNICOMM_Inst_Regs *unicomm, DL_I2CC_EVENT_ROUTE index, uint32_t interruptMask)
Check interrupt flag of any I2CC interrupt for DMA event.
__STATIC_INLINE uint32_t DL_I2CC_getTimeoutACount (UNICOMM_Inst_Regs *unicomm)
Get the Timeout Counter A value.
__STATIC_INLINE void DL_I2CC_setTimeoutACount (UNICOMM_Inst_Regs *unicomm, uint32_t count)
Set the Timeout Counter A value.
__STATIC_INLINE void DL_I2CC_disableTimeoutA (UNICOMM_Inst_Regs *unicomm)
Disable Timeout Counter A.
__STATIC_INLINE bool DL_I2CC_isTimeoutAEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if Timeout Counter A is enabled.
__STATIC_INLINE void DL_I2CC_enableTimeoutA (UNICOMM_Inst_Regs *unicomm)
Enable Timeout Counter A.
__STATIC_INLINE uint32_t DL_I2CC_getCurrentTimeoutACounter (UNICOMM_Inst_Regs *unicomm)
Get the current Timer Counter A value.
__STATIC_INLINE uint32_t DL_I2CC_getTimeoutBCount (UNICOMM_Inst_Regs *unicomm)
Get the Timeout Counter B value.
__STATIC_INLINE void DL_I2CC_setTimeoutBCount (UNICOMM_Inst_Regs *unicomm, uint32_t count)
Set the Timeout Counter B value.
__STATIC_INLINE void DL_I2CC_disableTimeoutB (UNICOMM_Inst_Regs *unicomm)
Disable Timeout Counter B.
__STATIC_INLINE bool DL_I2CC_isTimeoutBEnabled (UNICOMM_Inst_Regs *unicomm)
Checks if Timeout Counter B is enabled.
__STATIC_INLINE void DL_I2CC_enableTimeoutB (UNICOMM_Inst_Regs *unicomm)
Enable Timeout Counter B.
__STATIC_INLINE uint32_t DL_I2CC_getCurrentTimeoutBCounter (UNICOMM_Inst_Regs *unicomm)
Get the current Timer Counter B value.
Detailed Description
Overview
Unified Communication Module Inter-Integrated Circuit Controller Driver Library allows full configuration of the UNICOMM I2CC module.
This Inter-Integrated Circuit Controller (I2CC) module provides a standardized interface to transfer data, as a controller, between devices and other external devices with the I2C interface.
Macro Definition Documentation
DL_I2CC_TX_FIFO_COUNT_MAXIMUM
#define DL_I2CC_TX_FIFO_COUNT_MAXIMUM ((uint32_t)UNICOMMI2CC_SYS_FENTRIES << 8)
I2CC number of bytes which could be put into the TX FIFO.
This variable is device specific and is calculated using the system parameter UNICOMMI2CC_SYS_FENTRIES defined in each devices header file.
DL_I2CC_RX_FIFO_COUNT_MAXIMUM
#define DL_I2CC_RX_FIFO_COUNT_MAXIMUM ((uint32_t)UNICOMMI2CC_SYS_FENTRIES)
I2CC number of bytes which could be put into the RX FIFO.
This variable is device specific and is calculated using the system parameter UNICOMMI2CC_SYS_FENTRIES defined in each devices header file.
Enumeration Type Documentation
DL_I2CC_EVENT_ROUTE
enum DL_I2CC_EVENT_ROUTE
Enumerator
DL_I2CC_EVENT_ROUTE_1
I2CC event route 1
DL_I2CC_EVENT_ROUTE_2
I2CC event route 2
DL_I2CC_CLOCK
enum DL_I2CC_CLOCK
Enumerator
DL_I2CC_CLOCK_BUSCLK
BUSCLK enabled as I2CC clock source
DL_I2CC_CLOCK_MFCLK
MFCLK enabled as I2CC clock source
DL_I2CC_CLOCK_ASYNC_SYSCLK
Asynchronous SYSCLK enabled as I2CC clock source
DL_I2CC_CLOCK_ASYNC_HFCLK
Asynchronous HFCLK enabled as I2CC clock source
DL_I2CC_CLOCK_ASYNC_PLL
Asynchronous PLL enabled as I2CC clock source
DL_I2CC_CLOCK_DIVIDE
enum DL_I2CC_CLOCK_DIVIDE
Enumerator
DL_I2CC_CLOCK_DIVIDE_1
I2CC Clock Divided by 1
DL_I2CC_CLOCK_DIVIDE_2
I2CC Clock Divided by 2
DL_I2CC_CLOCK_DIVIDE_3
I2CC Clock Divided by 3
DL_I2CC_CLOCK_DIVIDE_4
I2CC Clock Divided by 4
DL_I2CC_CLOCK_DIVIDE_5
I2CC Clock Divided by 5
DL_I2CC_CLOCK_DIVIDE_6
I2CC Clock Divided by 6
DL_I2CC_CLOCK_DIVIDE_7
I2CC Clock Divided by 7
DL_I2CC_CLOCK_DIVIDE_8
I2CC Clock Divided by 8
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH
enum DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH
Enumerator
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH_DISABLED
Pulses filtering disabled.
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_1
Pulses shorter than 1 functional clock tick in length are filtered.
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_2
Pulses shorter than 2 functional clock ticks in length are filtered.
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_3
Pulses shorter than 3 functional clock ticks in length are filtered.
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_4
Pulses shorter than 4 functional clock ticks in length are filtered.
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_8
Pulses shorter than 8 functional clock ticks in length are filtered.
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_16
Pulses shorter than 16 functional clock ticks in length are filtered.
DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH_CLOCKS_31
Pulses shorter than 31 functional clock ticks in length are filtered.
DL_I2CC_DIRECTION
enum DL_I2CC_DIRECTION
Enumerator
DL_I2CC_DIRECTION_TX
Set direction to transmitting to target
DL_I2CC_DIRECTION_RX
Set direction to receiving from target
DL_I2CC_ADDRESSING_MODE
enum DL_I2CC_ADDRESSING_MODE
Enumerator
DL_I2CC_ADDRESSING_MODE_7_BIT
Enable in 7-bit addressing mode
DL_I2CC_ADDRESSING_MODE_10_BIT
Enable in 10-bit addressing mode
DL_I2CC_PEC_STATUS
enum DL_I2CC_PEC_STATUS
Enumerator
DL_I2CC_PEC_STATUS_CHECKED
I2CC SMBus/PMBus PEC was checked in the transaction that occurred before the last Stop
DL_I2CC_PEC_STATUS_NOT_CHECKED
I2CC SMBus/PMBus PEC was not checked in the transaction that occurred the last Stop
DL_I2CC_PEC_CHECK_ERROR
enum DL_I2CC_PEC_CHECK_ERROR
Enumerator
DL_I2CC_PEC_CHECK_ERROR_SET
I2CC SMBus/PMBus PEC check error occurred in the transaction before the last stop
DL_I2CC_PEC_CHECK_ERROR_CLEARED
I2CC SMBus/PMBus PEC check error did not occur in the transaction before the last stop
DL_I2CC_SCL
enum DL_I2CC_SCL
Enumerator
DL_I2CC_SCL_HIGH
I2CC SCL signal high
DL_I2CC_SCL_LOW
I2CC SCL signal low
DL_I2CC_SDA
enum DL_I2CC_SDA
Enumerator
DL_I2CC_SDA_HIGH
I2CC SDA signal high
DL_I2CC_SDA_LOW
I2CC SDA signal low
DL_I2CC_START
enum DL_I2CC_START
Enumerator
DL_I2CC_START_ENABLE
generates START condition
DL_I2CC_START_DISABLE
doesn't generate START condition
DL_I2CC_STOP
enum DL_I2CC_STOP
Enumerator
DL_I2CC_STOP_ENABLE
generates STOP condition
DL_I2CC_STOP_DISABLE
doesn't generate STOP condition
DL_I2CC_ACK
enum DL_I2CC_ACK
Enumerator
DL_I2CC_ACK_ENABLE
Last received data byte of a transaction is not ACKed automatically
DL_I2CC_ACK_DISABLE
Last received data byte of a transaction is ACKed automatically
DL_I2CC_TX_FIFO_LEVEL
enum DL_I2CC_TX_FIFO_LEVEL
Enumerator
DL_I2CC_TX_FIFO_LEVEL_3_4_EMPTY
Interrupt triggers when FIFO <= 3/4 empty
DL_I2CC_TX_FIFO_LEVEL_1_2_EMPTY
Interrupt triggers when FIFO <= 1/2 empty
DL_I2CC_TX_FIFO_LEVEL_1_4_EMPTY
Interrupt triggers when FIFO <= 1/4 empty
DL_I2CC_TX_FIFO_LEVEL_ONE_ENTRY
Interrupt triggers when FIFO is not full
DL_I2CC_TX_FIFO_LEVEL_EMPTY
Interrupt triggers when FIFO is empty
DL_I2CC_TX_FIFO_LEVEL_ALMOST_EMPTY
Interrupt triggers when FIFO is almost empty (FIFO <= 1)
DL_I2CC_TX_FIFO_LEVEL_ALMOST_FULL
Interrupt triggers when FIFO is almost full (FIFO >= (MAX_FIFO_LEN - 1))
DL_I2CC_RX_FIFO_LEVEL
enum DL_I2CC_RX_FIFO_LEVEL
Enumerator
DL_I2CC_RX_FIFO_LEVEL_3_4_FULL
Interrupt triggers when FIFO >= 3/4 full
DL_I2CC_RX_FIFO_LEVEL_1_2_FULL
Interrupt triggers when FIFO >= 1/2 full
DL_I2CC_RX_FIFO_LEVEL_1_4_FULL
Interrupt triggers when FIFO >= 1/4 full
DL_I2CC_RX_FIFO_LEVEL_ONE_ENTRY
Interrupt triggers when FIFO is not empty
DL_I2CC_RX_FIFO_LEVEL_FULL
Interrupt triggers when FIFO is full
DL_I2CC_RX_FIFO_LEVEL_ALMOST_FULL
Interrupt triggers when FIFO is almost full (FIFO >= (MAX_FIFO_LEN - 1))
DL_I2CC_RX_FIFO_LEVEL_ALMOST_EMPTY
Interrupt triggers when FIFO is almost empty (FIFO <= 1)
DL_I2CC_IIDX
enum DL_I2CC_IIDX
Enumerator
DL_I2CC_IIDX_NO_INT
Interrupt index for I2CC if no interrupt is pending
DL_I2CC_IIDX_RX_DONE
Interrupt index for I2CC Receive Transaction completed
DL_I2CC_IIDX_TX_DONE
Interrupt index for Transmit Transaction completed
DL_I2CC_IIDX_RXFIFO_TRIGGER
Interrupt index for I2CC Receive FIFO Trigger
DL_I2CC_IIDX_TXFIFO_TRIGGER
Interrupt index for I2CC Transmit FIFO Trigger
DL_I2CC_IIDX_RXFIFO_FULL
Interrupt index for I2CC Receive when FIFO is full
DL_I2CC_IIDX_TXFIFO_EMPTY
Interrupt index for I2CC when Transmit FIFO is empty
DL_I2CC_IIDX_NACK
Interrupt index for Address/Data NACK
DL_I2CC_IIDX_START
Interrupt index for I2CC START Detection
DL_I2CC_IIDX_STOP
Interrupt index for I2CC STOP Detection
DL_I2CC_IIDX_ARBITRATION_LOST
Interrupt index for I2CC Arbitration Lost
DL_I2CC_IIDX_EVENT1_DMA_DONE
Interrupt index for I2CC Event 1 DMA Done
DL_I2CC_IIDX_EVENT2_DMA_DONE
Interrupt index for I2CC Event 2 DMA Done
DL_I2CC_IIDX_PREEMPT_INT_TX
Interrupt index for I2CC receive pre-emptive interrupt
DL_I2CC_IIDX_PREEMPT_INT_RX
Interrupt index for I2CC receive pre-emptive interrupt
DL_I2CC_IIDX_PEC_RX_ERROR
Interrupt index for I2CC SMBus/PMBus PEC Receive Error Event
DL_I2CC_IIDX_TIMEOUT_A
Interrupt index for I2CC Timeout A Event
DL_I2CC_IIDX_TIMEOUT_B
Interrupt index for I2CC Timeout B Event
Function Documentation
DL_I2CC_setClockConfig()
void DL_I2CC_setClockConfig (UNICOMM_Inst_Regs * unicomm, DL_I2CC_ClockConfig * config)
Configure I2CC source clock.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] config Pointer to the clock configuration struct DL_I2CC_ClockConfig.
DL_I2CC_getClockConfig()
void DL_I2CC_getClockConfig (UNICOMM_Inst_Regs * unicomm, DL_I2CC_ClockConfig * config)
Get I2CC source clock configuration.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] config Pointer to the clock configuration struct DL_I2CC_ClockConfig.
DL_I2CC_fillTXFIFO()
uint16_t DL_I2CC_fillTXFIFO (UNICOMM_Inst_Regs * unicomm, uint8_t * buffer, uint16_t count)
Fills the TX FIFO with data.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] buffer Pointer to buffer of bytes
[in] count Number of bytes to fill TX FIFO from buffer [0x00, 0xFFF]
Returns
Number of bytes that were successfully written
DL_I2CC_flushTXFIFO()
void DL_I2CC_flushTXFIFO (UNICOMM_Inst_Regs * unicomm)
Flushes/removes all elements in the TX FIFO.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_flushRXFIFO()
void DL_I2CC_flushRXFIFO (UNICOMM_Inst_Regs * unicomm)
Flushes/removes all elements in the RX FIFO.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_stopFlushTXFIFO()
__STATIC_INLINE void DL_I2CC_stopFlushTXFIFO (UNICOMM_Inst_Regs * unicomm)
Stop TX FIFO flush.
Before stopping the flush, check if DL_I2CC_isTXFIFOEmpty, indicating flush is complete.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_startFlushTXFIFO()
__STATIC_INLINE void DL_I2CC_startFlushTXFIFO (UNICOMM_Inst_Regs * unicomm)
Start TX FIFO flush.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_stopFlushRXFIFO()
__STATIC_INLINE void DL_I2CC_stopFlushRXFIFO (UNICOMM_Inst_Regs * unicomm)
Stop RX FIFO flush.
Before stopping the flush, check if DL_I2CC_isRXFIFOEmpty, indicating flush is complete.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_startFlushRXFIFO()
__STATIC_INLINE void DL_I2CC_startFlushRXFIFO (UNICOMM_Inst_Regs * unicomm)
Start RX FIFO flush.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_isTXFIFOFull()
__STATIC_INLINE bool DL_I2CC_isTXFIFOFull (UNICOMM_Inst_Regs * unicomm)
Checks if TX FIFO is full.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If TX FIFO is full
Return values
true if TX FIFO is full
false if TX FIFO is not full
DL_I2CC_isTXFIFOEmpty()
__STATIC_INLINE bool DL_I2CC_isTXFIFOEmpty (UNICOMM_Inst_Regs * unicomm)
Checks if TX FIFO is empty.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If TX FIFO is empty
Return values
true if TX FIFO is empty
false if TX FIFO is not empty
DL_I2CC_isRXFIFOFull()
__STATIC_INLINE bool DL_I2CC_isRXFIFOFull (UNICOMM_Inst_Regs * unicomm)
Checks if RX FIFO is full.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If RX FIFO is full
Return values
true if RX FIFO is full
false if RX FIFO is not full
DL_I2CC_isRXFIFOEmpty()
__STATIC_INLINE bool DL_I2CC_isRXFIFOEmpty (UNICOMM_Inst_Regs * unicomm)
Checks if RX FIFO is empty.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If RX FIFO is empty
Return values
true if RX FIFO is empty
false if RX FIFO is not empty
DL_I2CC_resetTransfer()
__STATIC_INLINE void DL_I2CC_resetTransfer (UNICOMM_Inst_Regs * unicomm)
Reset transfers from from UNICOMMI2CC.
Resets transfer register to initialize UNICOMMI2CC
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_startTransfer()
__STATIC_INLINE void DL_I2CC_startTransfer (UNICOMM_Inst_Regs * unicomm, uint32_t targetAddr, DL_I2CC_DIRECTION direction, uint16_t length)
Sets up a transfer from UNICOMMI2CC.
Set target address, transfer direction, burst length, START+STOP generation.
Note
Reading/writing data must be done separately.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] targetAddr Target address [0x00, 0x3FF]
[in] direction One of DL_I2CC_DIRECTION
[in] length Intended burst length in number of bytes [0x00, 0xFFF]
References DL_Common_updateReg().
DL_I2CC_startTransferAdvanced()
__STATIC_INLINE void DL_I2CC_startTransferAdvanced (UNICOMM_Inst_Regs * unicomm, uint32_t targetAddr, DL_I2CC_DIRECTION direction, uint16_t length, DL_I2CC_START start, DL_I2CC_STOP stop, DL_I2CC_ACK ack)
Sets up a transfer from I2CC with control of START, STOP and ACK.
Note
Reading/writing data must be done separately.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] targetAddr 7-bit target address [0x00, 0x7f]
[in] direction One of DL_I2CC_DIRECTION
[in] length Intended burst length in number of bytes
[in] start One of DL_I2CC_START
[in] stop One of DL_I2CC_STOP
[in] ack One of DL_I2CC_ACK
References DL_Common_updateReg().
DL_I2CC_enablePower()
__STATIC_INLINE void DL_I2CC_enablePower (UNICOMM_Inst_Regs * unicomm)
Enables power on UNICOMM I2C module.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
References DL_UNICOMM_enablePower(), DL_UNICOMM_I2C_CONTROLLER, and DL_UNICOMM_setIPMode().
DL_I2CC_disablePower()
__STATIC_INLINE void DL_I2CC_disablePower (UNICOMM_Inst_Regs * unicomm)
Disables power on UNICOMM I2C module.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
References DL_UNICOMM_disablePower().
DL_I2CC_isPowerEnabled()
__STATIC_INLINE bool DL_I2CC_isPowerEnabled (UNICOMM_Inst_Regs * unicomm)
Returns if power on UNICOMM I2C module.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
true if power is enabled
false if power is disabled
References DL_UNICOMM_isPowerEnabled().
DL_I2CC_reset()
__STATIC_INLINE void DL_I2CC_reset (UNICOMM_Inst_Regs * unicomm)
Resets UNICOMM I2C peripheral.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
References DL_UNICOMM_reset().
DL_I2CC_isReset()
__STATIC_INLINE bool DL_I2CC_isReset (UNICOMM_Inst_Regs * unicomm)
Returns if UNICOMM I2C peripheral was reset.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
true if peripheral was reset
false if peripheral wasn't reset
References DL_UNICOMM_isReset().
DL_I2CC_selectClockSource()
__STATIC_INLINE void DL_I2CC_selectClockSource (UNICOMM_Inst_Regs * unicomm, DL_I2CC_CLOCK clockSource)
Set Clock Source.
Clock sources depend on device and clock should be enabled
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] clockSource One of DL_I2CC_CLOCK.
References DL_Common_updateReg().
DL_I2CC_selectClockDivider()
__STATIC_INLINE void DL_I2CC_selectClockDivider (UNICOMM_Inst_Regs * unicomm, DL_I2CC_CLOCK_DIVIDE clockDivider)
Set Clock Divider.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] clockDivider One of DL_I2CC_CLOCK_DIVIDE.
References DL_Common_updateReg().
DL_I2CC_getDigitalGlitchFilterPulseWidth()
__STATIC_INLINE DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH DL_I2CC_getDigitalGlitchFilterPulseWidth (UNICOMM_Inst_Regs * unicomm)
Get Digital Glitch Suppression Pulse Width.
Pulse width for the digital glitch suppression on SCL/SDA lines. Values are in terms of functional clock ticks.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Digital glitch suppression pulse width
Return values
One of DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH.
DL_I2CC_setDigitalGlitchFilterPulseWidth()
__STATIC_INLINE void DL_I2CC_setDigitalGlitchFilterPulseWidth (UNICOMM_Inst_Regs * unicomm, DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH filterWidth)
Set Digital Glitch Suppression Pulse Width.
Pulse width for the digital glitch suppression on SCL/SDA lines. Values are in terms of functional clock ticks.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] filterWidth One of DL_I2CC_DIGITAL_GLITCH_FILTER_WIDTH.
References DL_Common_updateReg().
DL_I2CC_disableAnalogGlitchFilter()
__STATIC_INLINE void DL_I2CC_disableAnalogGlitchFilter (UNICOMM_Inst_Regs * unicomm)
Disable Analog Glitch Suppression.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_isAnalogGlitchFilterEnabled()
__STATIC_INLINE bool DL_I2CC_isAnalogGlitchFilterEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if analog glitch suppression is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If analog glitch suppression is enabled
Return values
true if analog glitch suppression is enabled
false if analog glitch suppression is disabled
DL_I2CC_enableAnalogGlitchFilter()
__STATIC_INLINE void DL_I2CC_enableAnalogGlitchFilter (UNICOMM_Inst_Regs * unicomm)
Enable Analog Glitch Suppression.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_getDirection()
__STATIC_INLINE DL_I2CC_DIRECTION DL_I2CC_getDirection (UNICOMM_Inst_Regs * unicomm)
Get direction of next operation.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Direction of next operation
Return values
One of DL_I2CC_DIRECTION
DL_I2CC_setDirection()
__STATIC_INLINE void DL_I2CC_setDirection (UNICOMM_Inst_Regs * unicomm, DL_I2CC_DIRECTION direction)
Set direction of next operation.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] direction Direction of next operation. One of DL_I2CC_DIRECTION.
References DL_Common_updateReg().
DL_I2CC_getTargetAddress()
__STATIC_INLINE uint32_t DL_I2CC_getTargetAddress (UNICOMM_Inst_Regs * unicomm)
Get the address of the target being addressed when configured as an UNICOMMI2CC.
Specifies bits A9 through A0 of the target address. In 7-bit addressing mode as selected by DL_I2CC_setAddressingMode, the top 3 bits are don't care.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
The target address
Return values
[0x00,0x07FE]
See also
DL_I2CC_setAddressingMode
DL_I2CC_setTargetAddress()
__STATIC_INLINE void DL_I2CC_setTargetAddress (UNICOMM_Inst_Regs * unicomm, uint32_t targetAddress)
Set the address of the target being addressed when configured as an UNICOMMI2CC.
Specifies bits A9 through A0 of the target address. In 7-bit addressing mode as selected by DL_I2CC_setAddressingMode, the top 3 bits are don't care.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] targetAddress Target address to set [0x00, 0x07FE]
See also
DL_I2CC_setAddressingMode
References DL_Common_updateReg().
DL_I2CC_getAddressingMode()
__STATIC_INLINE DL_I2CC_ADDRESSING_MODE DL_I2CC_getAddressingMode (UNICOMM_Inst_Regs * unicomm)
Get addressing mode.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Addressing mode the is set to
Return values
One of DL_I2CC_ADDRESSING_MODE
DL_I2CC_setAddressingMode()
__STATIC_INLINE void DL_I2CC_setAddressingMode (UNICOMM_Inst_Regs * unicomm, DL_I2CC_ADDRESSING_MODE mode)
Set addressing mode between 7-bit and 10-bit mode.
Selects the addressing mode between 7-bit and 10-bit mode to be used when device is configured as a
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] mode Addressing mode to set the target to. One of DL_I2CC_ADDRESSING_MODE.
References DL_Common_updateReg().
DL_I2CC_disableACKOverride()
__STATIC_INLINE void DL_I2CC_disableACKOverride (UNICOMM_Inst_Regs * unicomm)
Disable ACK override.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_isACKOverrideEnabled()
__STATIC_INLINE bool DL_I2CC_isACKOverrideEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if ACK override is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If ACK override is enabled
Return values
true if ACK override is enabled
false if ACK override is disabled
DL_I2CC_enableACKOverride()
__STATIC_INLINE void DL_I2CC_enableACKOverride (UNICOMM_Inst_Regs * unicomm)
Enable ACK override.
When enabled and the is receiving data and the number of bytes indicated in CTR.MBLEN have been received, the state machine will generate an RXDONE interrupt and wait at the start of the ACK for FW to indicate if an ACK or NACK should be sent. The ACK or NACK is selected by writing the CTR register and setting ACK accordingly. The other fields in this register can also be written at this time to continue on with the transaction. If a NACK is sent the state machine will automatically send a Stop.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
See also
DL_I2CC_setTransactionLength
DL_I2CC_disableReadOnTXEmpty()
__STATIC_INLINE void DL_I2CC_disableReadOnTXEmpty (UNICOMM_Inst_Regs * unicomm)
Disable read on TX empty.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_isReadOnTXEmptyEnabled()
__STATIC_INLINE bool DL_I2CC_isReadOnTXEmptyEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if read on TX empty is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If read on TX empty is enabled
Return values
true if read on TX empty is enabled
false if read on TX empty is disabled
DL_I2CC_enableReadOnTXEmpty()
__STATIC_INLINE void DL_I2CC_enableReadOnTXEmpty (UNICOMM_Inst_Regs * unicomm)
Enable read on TX empty.
When enabled, the will transmit all bytes from the TX FIFO before continuing with the programmed Burst Run Read. If the DIR is not set to Read in the MSA then this bit is ignored. The Start must be set in the CTR for proper I2CC protocol. The will first send the Start Condition, I2CC Address with R/W bit set to write, before sending the bytes in the TX FIFO. When the TX FIFO is empty, the I2CC transaction will continue as programmed in MTCR and MSA without sending a Stop Condition. This is intended to be used to perform simple I2CC command based reads transition that will complete after initiating them without having to get an interrupt to turn the bus around.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_getPECCountValue()
__STATIC_INLINE uint32_t DL_I2CC_getPECCountValue (UNICOMM_Inst_Regs * unicomm)
Get the SMBus/PMBus Packet Error Checking (PEC) count value.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
The value the PEC count is set to
Return values
Value between [0x0, 0x01FF]
DL_I2CC_setPECCountValue()
__STATIC_INLINE void DL_I2CC_setPECCountValue (UNICOMM_Inst_Regs * unicomm, uint32_t count)
Set the SMBus/PMBus Packet Error Checking (PEC) count value.
When this field is non zero, the number of I2CC data bytes are counted. Refer to the device TRM for more details.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] count The value to set the PEC count to. Value between [0x0, 0x01FF]
References DL_Common_updateReg().
DL_I2CC_disablePEC()
__STATIC_INLINE void DL_I2CC_disablePEC (UNICOMM_Inst_Regs * unicomm)
Disable SMBus/PMBus Packet Error Checking (PEC)
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_isPECEnabled()
__STATIC_INLINE bool DL_I2CC_isPECEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if SMBus/PMBus Packet Error Checking (PEC) is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If PEC is enabled
Return values
true if PEC is enabled
false if PEC is disabled
DL_I2CC_enablePEC()
__STATIC_INLINE void DL_I2CC_enablePEC (UNICOMM_Inst_Regs * unicomm)
Enable SMBus/PMBus Packet Error Checking (PEC)
When enabled, the PEC is calculated on all bits accept the Start, Stop, ACK and NACK. The PEC LSFR and the Byte Counter is set to 0 when the State Machine is in the IDLE state, which occurs following a Stop or when a timeout occurs. The Counter is also set to 0 after the PEC byte is sent or received. Note that the NACK is automatically sent following a PEC byte that results in a PEC error. The PEC Polynomial is x^8 + x^2 + x^1 + 1.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_getCurrentPECCount()
__STATIC_INLINE uint32_t DL_I2CC_getCurrentPECCount (UNICOMM_Inst_Regs * unicomm)
Get the current SMBus/PMBus PEC byte count of the state machine.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
The current PEC byte count of the state machine
Return values
Value between [0x0, 0x01FF]
DL_I2CC_getPECCheckedStatus()
__STATIC_INLINE DL_I2CC_PEC_STATUS DL_I2CC_getPECCheckedStatus (UNICOMM_Inst_Regs * unicomm)
If SMBus/PMBus PEC was checked in last transaction.
The status of if the PEC was checked in the transaction that occurred before the last Stop. Latched on Stop.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Status of PEC checked in last transaction
Return values
One of DL_I2CC_PEC_STATUS
DL_I2CC_getPECCheckError()
__STATIC_INLINE DL_I2CC_PEC_CHECK_ERROR DL_I2CC_getPECCheckError (UNICOMM_Inst_Regs * unicomm)
Get the status of the SMBus/PMBus PEC Check error.
The status of if a PEC check error occurred in the transaction that occurred before the last Stop. Latched on Stop.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Status of PEC check error
Return values
One of DL_I2CC_PEC_CHECK_ERROR
DL_I2CC_disableStartCondition()
__STATIC_INLINE void DL_I2CC_disableStartCondition (UNICOMM_Inst_Regs * unicomm)
Disable I2CC START generation.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_isStartConditionEnabled()
__STATIC_INLINE bool DL_I2CC_isStartConditionEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if I2CC START generation is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If I2CC START generation is enabled
Return values
true if I2CC START generation is enabled
false if I2CC START generation is disabled
DL_I2CC_enableStartCondition()
__STATIC_INLINE void DL_I2CC_enableStartCondition (UNICOMM_Inst_Regs * unicomm)
Enable I2CC START generation.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_disableStopCondition()
__STATIC_INLINE void DL_I2CC_disableStopCondition (UNICOMM_Inst_Regs * unicomm)
Disable I2CC STOP generation.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_isStopConditionEnabled()
__STATIC_INLINE bool DL_I2CC_isStopConditionEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if I2CC STOP generation is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If I2CC STOP generation is enabled
Return values
true if I2CC STOP generation is enabled
false if I2CC STOP generation is disabled
DL_I2CC_enableStopCondition()
__STATIC_INLINE void DL_I2CC_enableStopCondition (UNICOMM_Inst_Regs * unicomm)
Enable I2CC STOP generation.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_disableACK()
__STATIC_INLINE void DL_I2CC_disableACK (UNICOMM_Inst_Regs * unicomm)
Disable I2CC data acknowledge (ACK or NACK)
When the I2CC module operates in receiver mode, the ACK bit can be cleared when no further data needs to be received from the target transmitter.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_isACKEnabled()
__STATIC_INLINE bool DL_I2CC_isACKEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if I2CC data acknowledge (ACK or NACK) is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If I2CC data acknowledge is enabled
Return values
true if I2CC data acknowledge is enabled
false if I2CC data acknowledge is disabled
DL_I2CC_enableACK()
__STATIC_INLINE void DL_I2CC_enableACK (UNICOMM_Inst_Regs * unicomm)
Enable I2CC data acknowledge (ACK or NACK)
When the I2CC module operates in receiver mode, the ACK bit is normally set causing the I2CC bus to transmit an acknowledge automatically after each byte.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_getTransactionLength()
__STATIC_INLINE uint32_t DL_I2CC_getTransactionLength (UNICOMM_Inst_Regs * unicomm)
Get transaction length in bytes.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Length of I2CC transaction in bytes
Return values
[0x000,0xfff]
DL_I2CC_setTransactionLength()
__STATIC_INLINE void DL_I2CC_setTransactionLength (UNICOMM_Inst_Regs * unicomm, uint32_t length)
Set transaction length in bytes.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] length Length of I2CC transaction in bytes [0x000, 0xfff]
References DL_Common_updateReg().
DL_I2CC_getStatus()
__STATIC_INLINE uint32_t DL_I2CC_getStatus (UNICOMM_Inst_Regs * unicomm)
Get status of I2CC bus for.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Status of I2CC bus for
Return values
Bitwise OR of DL_I2CC_STATUS
DL_I2CC_getTransactionCount()
__STATIC_INLINE uint16_t DL_I2CC_getTransactionCount (UNICOMM_Inst_Regs * unicomm)
Get transaction count in bytes.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Current 12-bit countdown value of the transaction
Return values
[0x000,0xfff]
DL_I2CC_receiveData()
__STATIC_INLINE uint8_t DL_I2CC_receiveData (UNICOMM_Inst_Regs * unicomm)
Get byte of data from UNICOMMI2CC.
If using FIFO, it is first byte from the RX FIFO.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Last received byte of data
Return values
[0x00,0xff]
DL_I2CC_transmitData()
__STATIC_INLINE void DL_I2CC_transmitData (UNICOMM_Inst_Regs * unicomm, uint8_t data)
Set next byte to be transferred during the next transaction.
Does not transmit data until DL_I2CC_startTransfer
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] data Data to be transferred during the next transaction. [0x00, 0xff]
DL_I2CC_getTimerPeriod()
__STATIC_INLINE uint8_t DL_I2CC_getTimerPeriod (UNICOMM_Inst_Regs * unicomm)
Get timer period This field is used in the equation to configure SCL_PERIOD:
SCL_PERIOD = (1 + TPR) * (SCL_LP + SCL_HP) * INT_CLK_PRD
where: SCL_PRD is the SCL line period (I2CC clock)
TPR is the Timer Period register value (range of 1 to 127)
SCL_LP is the SCL Low period (fixed at 6) SCL_HP is the SCL High period (fixed at 4)
CLK_PRD is the functional clock period in ns
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Timer period
Return values
[0x00,0x7f]
DL_I2CC_setTimerPeriod()
__STATIC_INLINE void DL_I2CC_setTimerPeriod (UNICOMM_Inst_Regs * unicomm, uint8_t period)
Set timer period This field is used in the equation to configure SCL_PERIOD:
SCL_PERIOD = (1 + TPR) * (SCL_LP + SCL_HP) * INT_CLK_PRD
where: SCL_PRD is the SCL line period (I2CC clock)
TPR is the Timer Period register value (range of 1 to 127)
SCL_LP is the SCL Low period (fixed at 6) SCL_HP is the SCL High period (fixed at 4)
CLK_PRD is the functional clock period in ns
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] period Timer period [0x00, 0x7f]
DL_I2CC_disableMultiMode()
__STATIC_INLINE void DL_I2CC_disableMultiMode (UNICOMM_Inst_Regs * unicomm)
Disable multimode.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_isMultiModeEnabled()
__STATIC_INLINE bool DL_I2CC_isMultiModeEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if multimode is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If multimode is enabled
Return values
true if multimode is enabled
false if multimode is disabled
DL_I2CC_enableMultiMode()
__STATIC_INLINE void DL_I2CC_enableMultiMode (UNICOMM_Inst_Regs * unicomm)
Enable multimode.
In multimode, the SCL high time counts once the SCL line has been detected high. If this is not enabled, the high time counts as soon as the SCL line has been set high by the UNICOMMI2CC
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_disable()
__STATIC_INLINE void DL_I2CC_disable (UNICOMM_Inst_Regs * unicomm)
Disable controller.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_isEnabled()
__STATIC_INLINE bool DL_I2CC_isEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if controller is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If is enabled
Return values
true if is enabled
false if is disabled
DL_I2CC_enable()
__STATIC_INLINE void DL_I2CC_enable (UNICOMM_Inst_Regs * unicomm)
Enable controller.
After has enabled, it should not be re-enabled unless it has been disabled or by a reset, otherwise transfer failures may occur.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_disableClockStretching()
__STATIC_INLINE void DL_I2CC_disableClockStretching (UNICOMM_Inst_Regs * unicomm)
Disable clock stretching.
Clock stretching can be disabled if no target on the bus supports clock stretching; however, it should be typically enabled to be compliant with I2CC specification.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_isClockStretchingEnabled()
__STATIC_INLINE bool DL_I2CC_isClockStretchingEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if clock stretching is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If clock stretching is enabled
Return values
true if clock stretching is enabled
false if clock stretching is disabled
DL_I2CC_enableClockStretching()
__STATIC_INLINE void DL_I2CC_enableClockStretching (UNICOMM_Inst_Regs * unicomm)
Enable clock stretching.
Clock stretching can be disabled if no target on the bus supports clock stretching; however, it should be typically enabled to be compliant with UNICOMMI2CC specification.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_getSCLStatus()
__STATIC_INLINE DL_I2CC_SCL DL_I2CC_getSCLStatus (UNICOMM_Inst_Regs * unicomm)
Get SCL signal status.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Status of SCL signal
Return values
One of DL_I2CC_SCL
DL_I2CC_getSDAStatus()
__STATIC_INLINE DL_I2CC_SDA DL_I2CC_getSDAStatus (UNICOMM_Inst_Regs * unicomm)
Get SDA signal status.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Status of SDA signal
Return values
One of DL_I2CC_SDA
DL_I2CC_getTXFIFOThreshold()
__STATIC_INLINE DL_I2CC_TX_FIFO_LEVEL DL_I2CC_getTXFIFOThreshold (UNICOMM_Inst_Regs * unicomm)
Get TX FIFO threshold level.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Indicates at what fill level in the TX FIFO a threshold will be generated
Return values
One of DL_I2CC_TX_FIFO_LEVEL
DL_I2CC_setTXFIFOThreshold()
__STATIC_INLINE void DL_I2CC_setTXFIFOThreshold (UNICOMM_Inst_Regs * unicomm, DL_I2CC_TX_FIFO_LEVEL level)
Set TX FIFO threshold level.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] level Indicates at what fill level in the TX FIFO a threshold will be generated. One of DL_I2CC_TX_FIFO_LEVEL.
References DL_Common_updateReg().
DL_I2CC_getRXFIFOThreshold()
__STATIC_INLINE DL_I2CC_RX_FIFO_LEVEL DL_I2CC_getRXFIFOThreshold (UNICOMM_Inst_Regs * unicomm)
Get RX FIFO threshold level.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Indicates at what fill level in the RX FIFO a threshold will be generated
Return values
One of DL_I2CC_RX_FIFO_LEVEL
DL_I2CC_setRXFIFOThreshold()
__STATIC_INLINE void DL_I2CC_setRXFIFOThreshold (UNICOMM_Inst_Regs * unicomm, DL_I2CC_RX_FIFO_LEVEL level)
Set RX FIFO threshold level.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] level Indicates at what fill level in the RX FIFO a threshold will be generated. One of DL_I2CC_RX_FIFO_LEVEL.
References DL_Common_updateReg().
DL_I2CC_getRXFIFOCounter()
__STATIC_INLINE uint32_t DL_I2CC_getRXFIFOCounter (UNICOMM_Inst_Regs * unicomm)
Get number of bytes which can be read from RX FIFO.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Number of bytes which can be read from RX FIFO
Return values
[0x0,0x8]
DL_I2CC_getTXFIFOCounter()
__STATIC_INLINE uint32_t DL_I2CC_getTXFIFOCounter (UNICOMM_Inst_Regs * unicomm)
Get number of bytes which can be put into TX FIFO.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
Number of bytes which can be put into TX FIFO
Return values
[0x0,0x8]
DL_I2CC_enableInterrupt()
__STATIC_INLINE void DL_I2CC_enableInterrupt (UNICOMM_Inst_Regs * unicomm, uint32_t interruptMask)
Enable I2CC interrupts.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to enable. Bitwise OR of DL_I2CC_INTERRUPT.
DL_I2CC_disableInterrupt()
__STATIC_INLINE void DL_I2CC_disableInterrupt (UNICOMM_Inst_Regs * unicomm, uint32_t interruptMask)
Disable I2CC interrupts.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to disable. Bitwise OR of DL_I2CC_INTERRUPT.
DL_I2CC_getEnabledInterrupts()
__STATIC_INLINE uint32_t DL_I2CC_getEnabledInterrupts (UNICOMM_Inst_Regs * unicomm, uint32_t interruptMask)
Check which I2CC interrupts are enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2CC_INTERRUPT.
Returns
Which of the requested I2CC interrupts are enabled
Return values
Bitwise OR of DL_I2CC_INTERRUPT values
DL_I2CC_getEnabledInterruptStatus()
__STATIC_INLINE uint32_t DL_I2CC_getEnabledInterruptStatus (UNICOMM_Inst_Regs * unicomm, uint32_t interruptMask)
Check interrupt flag of enabled I2CC interrupts.
Checks if any of the I2CC interrupts that were previously enabled are pending.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2CC_INTERRUPT.
Returns
Which of the requested I2CC interrupts are pending
Return values
Bitwise OR of DL_I2CC_INTERRUPT values
See also
DL_I2CC_enableInterrupt
DL_I2CC_getRawInterruptStatus()
__STATIC_INLINE uint32_t DL_I2CC_getRawInterruptStatus (UNICOMM_Inst_Regs * unicomm, uint32_t interruptMask)
Check interrupt flag of any I2CC interrupt.
Checks if any of the I2CC interrupts are pending. Interrupts do not have to be previously enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2CC_INTERRUPT.
Returns
Which of the requested I2CC interrupts are pending
Return values
Bitwise OR of DL_I2CC_INTERRUPT values
DL_I2CC_getPendingInterrupt()
__STATIC_INLINE DL_I2CC_IIDX DL_I2CC_getPendingInterrupt (UNICOMM_Inst_Regs * unicomm)
Get highest priority pending I2CC interrupt.
Checks if any of the I2CC interrupts are pending. Interrupts do not have to be previously enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
The highest priority pending I2CC interrupt
Return values
One of DL_I2CC_IIDX
DL_I2CC_clearInterruptStatus()
__STATIC_INLINE void DL_I2CC_clearInterruptStatus (UNICOMM_Inst_Regs * unicomm, uint32_t interruptMask)
Clear pending I2CC interrupts.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] interruptMask Bit mask of interrupts to clear. Bitwise OR of DL_I2CC_INTERRUPT.
DL_I2CC_enableDMAEvent()
__STATIC_INLINE void DL_I2CC_enableDMAEvent (UNICOMM_Inst_Regs * unicomm, DL_I2CC_EVENT_ROUTE index, uint32_t interrupt)
Enables I2CC interrupt for triggering DMA events.
Enables the I2CC interrupt to be used as the condition to generate an event to directly trigger the DMA.
Each event publisher DL_I2CC_EVENT_ROUTE can set any one of DL_I2CC_DMA_INTERRUPT.
Note
Only one interrupt source should be enabled at a time.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] index Specifies the register event publisher to configure
[in] interrupt Interrupt to enable as the trigger condition for the DMA. One of DL_I2CC_DMA_INTERRUPT.
References DL_I2CC_EVENT_ROUTE_1, and DL_I2CC_EVENT_ROUTE_2.
DL_I2CC_disableDMAEvent()
__STATIC_INLINE void DL_I2CC_disableDMAEvent (UNICOMM_Inst_Regs * unicomm, DL_I2CC_EVENT_ROUTE index, uint32_t interrupt)
Disables I2CC interrupt from triggering DMA events.
Disables the I2CC interrupt from being used as the condition to generate an event to directly trigger the DMA.
Each event publisher DL_I2CC_EVENT_ROUTE can set any one of DL_I2CC_DMA_INTERRUPT.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] index Specifies the register event publisher to configure
[in] interrupt Interrupt to disable as the trigger condition for the DMA. One of DL_I2CC_DMA_INTERRUPT.
References DL_I2CC_EVENT_ROUTE_1, and DL_I2CC_EVENT_ROUTE_2.
DL_I2CC_getEnabledDMAEvents()
__STATIC_INLINE uint32_t DL_I2CC_getEnabledDMAEvents (UNICOMM_Inst_Regs * unicomm, DL_I2CC_EVENT_ROUTE index, uint32_t interruptMask)
Check which I2CC interrupt for DMA receive events is enabled.
This API checks the event publisher register as selected by DL_I2CC_EVENT_ROUTE, which are used for triggering the DMA for or Target and receive or transmit events.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] index Specifies the register event publisher to configure
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2CC_DMA_INTERRUPT.
Note
Only one interrupt source should be enabled at a time.
Returns
The requested I2CC interrupt status
Return values
One of DL_I2CC_DMA_INTERRUPT
DL_I2CC_getEnabledDMAEventStatus()
__STATIC_INLINE uint32_t DL_I2CC_getEnabledDMAEventStatus (UNICOMM_Inst_Regs * unicomm, DL_I2CC_EVENT_ROUTE index, uint32_t interruptMask)
Check interrupt flag of enabled I2CC interrupt for DMA event.
Checks if any of the I2CC interrupts for the DMA receive event that were previously enabled are pending. This API checks the event publisher register as selected by DL_I2CC_EVENT_ROUTE, which are used for triggering the DMA for or Target and receive or transmit events.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] index Specifies the register event publisher to configure
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2CC_DMA_INTERRUPT.
Note
Only one interrupt source should be enabled at a time.
Returns
The requested I2CC interrupt status
Return values
One of DL_I2CC_DMA_INTERRUPT
See also
DL_I2CC_enableDMAEvent
DL_I2CC_getRawDMAEventStatus()
__STATIC_INLINE uint32_t DL_I2CC_getRawDMAEventStatus (UNICOMM_Inst_Regs * unicomm, DL_I2CC_EVENT_ROUTE index, uint32_t interruptMask)
Check interrupt flag of any I2CC interrupt for DMA event.
Checks if any of the I2CC interrupts for DMA receive event are pending. Interrupts do not have to be previously enabled. This API checks the event publisher register as selected by DL_I2CC_EVENT_ROUTE, which are used for triggering the DMA for or Target and receive or transmit events.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] index Specifies the register event publisher to configure
[in] interruptMask Bit mask of interrupts to check. Bitwise OR of DL_I2CC_DMA_INTERRUPT.
Returns
Which of the requested I2CC interrupts are pending
Return values
Bitwise OR of DL_I2CC_DMA_INTERRUPT values
DL_I2CC_getTimeoutACount()
__STATIC_INLINE uint32_t DL_I2CC_getTimeoutACount (UNICOMM_Inst_Regs * unicomm)
Get the Timeout Counter A value.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
The Timeout A counter value
Return values
Value between [0x0, 0xFF]
DL_I2CC_setTimeoutACount()
__STATIC_INLINE void DL_I2CC_setTimeoutACount (UNICOMM_Inst_Regs * unicomm, uint32_t count)
Set the Timeout Counter A value.
Timeout A is used for SCL low detection. This field contains the upper 8 bits of a 12-bit pre-load value for the Timeout A count. NOTE: The value of the counter must be greater than 1 to enable the timeout. Each count is equal to 520 times the timeout period of the functional clock. For example, with 8MHz functional clock and a 100KHz operating I2CC clock, one timeout period will be equal to (1 / 8MHz) * 520 = 65us.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] count The value to set the Timeout A counter to. Value between [0x0, 0xFF]
References DL_Common_updateReg().
DL_I2CC_disableTimeoutA()
__STATIC_INLINE void DL_I2CC_disableTimeoutA (UNICOMM_Inst_Regs * unicomm)
Disable Timeout Counter A.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_isTimeoutAEnabled()
__STATIC_INLINE bool DL_I2CC_isTimeoutAEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if Timeout Counter A is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If Timeout Counter A is enabled
Return values
true if Timeout Counter A is enabled
false if Timeout Counter A is disabled
DL_I2CC_enableTimeoutA()
__STATIC_INLINE void DL_I2CC_enableTimeoutA (UNICOMM_Inst_Regs * unicomm)
Enable Timeout Counter A.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_getCurrentTimeoutACounter()
__STATIC_INLINE uint32_t DL_I2CC_getCurrentTimeoutACounter (UNICOMM_Inst_Regs * unicomm)
Get the current Timer Counter A value.
This field contains the upper 8 bits of a 12-bit current counter for Timeout Counter A.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
The Timeout A counter value
Return values
Value between [0x0, 0xFF]
DL_I2CC_getTimeoutBCount()
__STATIC_INLINE uint32_t DL_I2CC_getTimeoutBCount (UNICOMM_Inst_Regs * unicomm)
Get the Timeout Counter B value.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
The Timeout B counter value
Return values
Value between [0x0, 0xFF]
DL_I2CC_setTimeoutBCount()
__STATIC_INLINE void DL_I2CC_setTimeoutBCount (UNICOMM_Inst_Regs * unicomm, uint32_t count)
Set the Timeout Counter B value.
Timeout B is used for SCL high detection. This field contains the upper 8 bits of a 12-bit pre-load value for the Timeout A count. NOTE: The value of the counter must be greater than 1 to enable the timeout. Each count is equal to 1* clock period. For example, with 10MHz functional clock one timeout period will be equal to 1 * 10ns.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
[in] count The value to set the Timeout A counter to. Value between [0x0, 0xFF]
References DL_Common_updateReg().
DL_I2CC_disableTimeoutB()
__STATIC_INLINE void DL_I2CC_disableTimeoutB (UNICOMM_Inst_Regs * unicomm)
Disable Timeout Counter B.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_isTimeoutBEnabled()
__STATIC_INLINE bool DL_I2CC_isTimeoutBEnabled (UNICOMM_Inst_Regs * unicomm)
Checks if Timeout Counter B is enabled.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
If Timeout Counter B is enabled
Return values
true if Timeout Counter B is enabled
false if Timeout Counter B is disabled
DL_I2CC_enableTimeoutB()
__STATIC_INLINE void DL_I2CC_enableTimeoutB (UNICOMM_Inst_Regs * unicomm)
Enable Timeout Counter B.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
DL_I2CC_getCurrentTimeoutBCounter()
__STATIC_INLINE uint32_t DL_I2CC_getCurrentTimeoutBCounter (UNICOMM_Inst_Regs * unicomm)
Get the current Timer Counter B value.
This field contains the upper 8 bits of a 12-bit current counter for Timeout Counter B.
Parameters
[in] unicomm Pointer to the register overlay for the peripheral
Returns
The Timeout B counter value
Return values
Value between [0x0, 0xFF]
Copyright 1995-2025, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale