SensorlessFOCMotorControlLibrary: _IQNsqrt_mathacl.c File Reference
_IQNsqrt_mathacl.c File Reference
Detailed Description
Functions to compute square root, inverse square root and the magnitude of two IQN inputs.
#include <stdint.h>
#include <ti/devices/msp/msp.h>
Macros
#define TYPE_ISQRT (0)
Specifies inverse square root operation type.
#define TYPE_SQRT (1)
Specifies square root operation type.
#define TYPE_MAG (2)
Specifies magnitude operation type.
#define TYPE_IMAG (3)
Specifies inverse magnitude operation type.
Functions
__STATIC_INLINE int_fast32_t __IQNsqrt_mathacl (int_fast32_t iqNInputX, const int8_t q_value)
Calculate square root of an IQN input, using MathACL.
int32_t _IQ31sqrt_mathacl (int32_t a)
Calculate square root of an IQ31 input, using MathACL.
int32_t _IQ30sqrt_mathacl (int32_t a)
Calculate square root of an IQ30 input, using MathACL.
int32_t _IQ29sqrt_mathacl (int32_t a)
Calculate square root of an IQ29 input, using MathACL.
int32_t _IQ28sqrt_mathacl (int32_t a)
Calculate square root of an IQ28 input, using MathACL.
int32_t _IQ27sqrt_mathacl (int32_t a)
Calculate square root of an IQ27 input, using MathACL.
int32_t _IQ26sqrt_mathacl (int32_t a)
Calculate square root of an IQ26 input, using MathACL.
int32_t _IQ25sqrt_mathacl (int32_t a)
Calculate square root of an IQ25 input, using MathACL.
int32_t _IQ24sqrt_mathacl (int32_t a)
Calculate square root of an IQ24 input, using MathACL.
int32_t _IQ23sqrt_mathacl (int32_t a)
Calculate square root of an IQ23 input, using MathACL.
int32_t _IQ22sqrt_mathacl (int32_t a)
Calculate square root of an IQ22 input, using MathACL.
int32_t _IQ21sqrt_mathacl (int32_t a)
Calculate square root of an IQ21 input, using MathACL.
int32_t _IQ20sqrt_mathacl (int32_t a)
Calculate square root of an IQ20 input, using MathACL.
int32_t _IQ19sqrt_mathacl (int32_t a)
Calculate square root of an IQ19 input, using MathACL.
int32_t _IQ18sqrt_mathacl (int32_t a)
Calculate square root of an IQ18 input, using MathACL.
int32_t _IQ17sqrt_mathacl (int32_t a)
Calculate square root of an IQ17 input, using MathACL.
int32_t _IQ16sqrt_mathacl (int32_t a)
Calculate square root of an IQ16 input, using MathACL.
int32_t _IQ15sqrt_mathacl (int32_t a)
Calculate square root of an IQ15 input, using MathACL.
int32_t _IQ14sqrt_mathacl (int32_t a)
Calculate square root of an IQ14 input, using MathACL.
int32_t _IQ13sqrt_mathacl (int32_t a)
Calculate square root of an IQ13 input, using MathACL.
int32_t _IQ12sqrt_mathacl (int32_t a)
Calculate square root of an IQ12 input, using MathACL.
int32_t _IQ11sqrt_mathacl (int32_t a)
Calculate square root of an IQ11 input, using MathACL.
int32_t _IQ10sqrt_mathacl (int32_t a)
Calculate square root of an IQ10 input, using MathACL.
int32_t _IQ9sqrt_mathacl (int32_t a)
Calculate square root of an IQ9 input, using MathACL.
int32_t _IQ8sqrt_mathacl (int32_t a)
Calculate square root of an IQ8 input, using MathACL.
int32_t _IQ7sqrt_mathacl (int32_t a)
Calculate square root of an IQ7 input, using MathACL.
int32_t _IQ6sqrt_mathacl (int32_t a)
Calculate square root of an IQ6 input, using MathACL.
int32_t _IQ5sqrt_mathacl (int32_t a)
Calculate square root of an IQ5 input, using MathACL.
int32_t _IQ4sqrt_mathacl (int32_t a)
Calculate square root of an IQ4 input, using MathACL.
int32_t _IQ3sqrt_mathacl (int32_t a)
Calculate square root of an IQ3 input, using MathACL.
int32_t _IQ2sqrt_mathacl (int32_t a)
Calculate square root of an IQ2 input, using MathACL.
int32_t _IQ1sqrt_mathacl (int32_t a)
Calculate square root of an IQ1 input, using MathACL.
int32_t _IQ0sqrt_mathacl (int32_t a)
Calculate square root of an IQ0 input, using MathACL.
Function Documentation
__IQNsqrt_mathacl()
__STATIC_INLINE int_fast32_t __IQNsqrt_mathacl (int_fast32_t iqNInputX, const int8_t q_value)
Calculate square root of an IQN input, using MathACL.
Parameters
iqNInputX IQN type input.
q_value IQ format.
Returns
IQN type result of the square root operation.
Referenced by _IQ0sqrt_mathacl(), _IQ10sqrt_mathacl(), _IQ11sqrt_mathacl(), _IQ12sqrt_mathacl(), _IQ13sqrt_mathacl(), _IQ14sqrt_mathacl(), _IQ15sqrt_mathacl(), _IQ16sqrt_mathacl(), _IQ17sqrt_mathacl(), _IQ18sqrt_mathacl(), _IQ19sqrt_mathacl(), _IQ1sqrt_mathacl(), _IQ20sqrt_mathacl(), _IQ21sqrt_mathacl(), _IQ22sqrt_mathacl(), _IQ23sqrt_mathacl(), _IQ24sqrt_mathacl(), _IQ25sqrt_mathacl(), _IQ26sqrt_mathacl(), _IQ27sqrt_mathacl(), _IQ28sqrt_mathacl(), _IQ29sqrt_mathacl(), _IQ2sqrt_mathacl(), _IQ30sqrt_mathacl(), _IQ31sqrt_mathacl(), _IQ3sqrt_mathacl(), _IQ4sqrt_mathacl(), _IQ5sqrt_mathacl(), _IQ6sqrt_mathacl(), _IQ7sqrt_mathacl(), _IQ8sqrt_mathacl(), and _IQ9sqrt_mathacl().
_IQ31sqrt_mathacl()
int32_t _IQ31sqrt_mathacl (int32_t a)
Calculate square root of an IQ31 input, using MathACL.
Parameters
a IQ31 type input.
Returns
IQ31 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ30sqrt_mathacl()
int32_t _IQ30sqrt_mathacl (int32_t a)
Calculate square root of an IQ30 input, using MathACL.
Parameters
a IQ30 type input.
Returns
IQ30 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ29sqrt_mathacl()
int32_t _IQ29sqrt_mathacl (int32_t a)
Calculate square root of an IQ29 input, using MathACL.
Parameters
a IQ29 type input.
Returns
IQ29 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ28sqrt_mathacl()
int32_t _IQ28sqrt_mathacl (int32_t a)
Calculate square root of an IQ28 input, using MathACL.
Parameters
a IQ28 type input.
Returns
IQ28 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ27sqrt_mathacl()
int32_t _IQ27sqrt_mathacl (int32_t a)
Calculate square root of an IQ27 input, using MathACL.
Parameters
a IQ27 type input.
Returns
IQ27 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ26sqrt_mathacl()
int32_t _IQ26sqrt_mathacl (int32_t a)
Calculate square root of an IQ26 input, using MathACL.
Parameters
a IQ26 type input.
Returns
IQ26 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ25sqrt_mathacl()
int32_t _IQ25sqrt_mathacl (int32_t a)
Calculate square root of an IQ25 input, using MathACL.
Parameters
a IQ25 type input.
Returns
IQ25 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ24sqrt_mathacl()
int32_t _IQ24sqrt_mathacl (int32_t a)
Calculate square root of an IQ24 input, using MathACL.
Parameters
a IQ24 type input.
Returns
IQ24 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ23sqrt_mathacl()
int32_t _IQ23sqrt_mathacl (int32_t a)
Calculate square root of an IQ23 input, using MathACL.
Parameters
a IQ23 type input.
Returns
IQ23 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ22sqrt_mathacl()
int32_t _IQ22sqrt_mathacl (int32_t a)
Calculate square root of an IQ22 input, using MathACL.
Parameters
a IQ22 type input.
Returns
IQ22 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ21sqrt_mathacl()
int32_t _IQ21sqrt_mathacl (int32_t a)
Calculate square root of an IQ21 input, using MathACL.
Parameters
a IQ21 type input.
Returns
IQ21 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ20sqrt_mathacl()
int32_t _IQ20sqrt_mathacl (int32_t a)
Calculate square root of an IQ20 input, using MathACL.
Parameters
a IQ20 type input.
Returns
IQ20 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ19sqrt_mathacl()
int32_t _IQ19sqrt_mathacl (int32_t a)
Calculate square root of an IQ19 input, using MathACL.
Parameters
a IQ19 type input.
Returns
IQ19 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ18sqrt_mathacl()
int32_t _IQ18sqrt_mathacl (int32_t a)
Calculate square root of an IQ18 input, using MathACL.
Parameters
a IQ18 type input.
Returns
IQ18 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ17sqrt_mathacl()
int32_t _IQ17sqrt_mathacl (int32_t a)
Calculate square root of an IQ17 input, using MathACL.
Parameters
a IQ17 type input.
Returns
IQ17 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ16sqrt_mathacl()
int32_t _IQ16sqrt_mathacl (int32_t a)
Calculate square root of an IQ16 input, using MathACL.
Parameters
a IQ16 type input.
Returns
IQ16 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ15sqrt_mathacl()
int32_t _IQ15sqrt_mathacl (int32_t a)
Calculate square root of an IQ15 input, using MathACL.
Parameters
a IQ15 type input.
Returns
IQ15 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ14sqrt_mathacl()
int32_t _IQ14sqrt_mathacl (int32_t a)
Calculate square root of an IQ14 input, using MathACL.
Parameters
a IQ14 type input.
Returns
IQ14 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ13sqrt_mathacl()
int32_t _IQ13sqrt_mathacl (int32_t a)
Calculate square root of an IQ13 input, using MathACL.
Parameters
a IQ13 type input.
Returns
IQ13 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ12sqrt_mathacl()
int32_t _IQ12sqrt_mathacl (int32_t a)
Calculate square root of an IQ12 input, using MathACL.
Parameters
a IQ12 type input.
Returns
IQ12 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ11sqrt_mathacl()
int32_t _IQ11sqrt_mathacl (int32_t a)
Calculate square root of an IQ11 input, using MathACL.
Parameters
a IQ11 type input.
Returns
IQ11 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ10sqrt_mathacl()
int32_t _IQ10sqrt_mathacl (int32_t a)
Calculate square root of an IQ10 input, using MathACL.
Parameters
a IQ10 type input.
Returns
IQ10 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ9sqrt_mathacl()
int32_t _IQ9sqrt_mathacl (int32_t a)
Calculate square root of an IQ9 input, using MathACL.
Parameters
a IQ9 type input.
Returns
IQ9 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ8sqrt_mathacl()
int32_t _IQ8sqrt_mathacl (int32_t a)
Calculate square root of an IQ8 input, using MathACL.
Parameters
a IQ8 type input.
Returns
IQ8 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ7sqrt_mathacl()
int32_t _IQ7sqrt_mathacl (int32_t a)
Calculate square root of an IQ7 input, using MathACL.
Parameters
a IQ7 type input.
Returns
IQ7 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ6sqrt_mathacl()
int32_t _IQ6sqrt_mathacl (int32_t a)
Calculate square root of an IQ6 input, using MathACL.
Parameters
a IQ6 type input.
Returns
IQ6 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ5sqrt_mathacl()
int32_t _IQ5sqrt_mathacl (int32_t a)
Calculate square root of an IQ5 input, using MathACL.
Parameters
a IQ5 type input.
Returns
IQ5 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ4sqrt_mathacl()
int32_t _IQ4sqrt_mathacl (int32_t a)
Calculate square root of an IQ4 input, using MathACL.
Parameters
a IQ4 type input.
Returns
IQ4 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ3sqrt_mathacl()
int32_t _IQ3sqrt_mathacl (int32_t a)
Calculate square root of an IQ3 input, using MathACL.
Parameters
a IQ3 type input.
Returns
IQ3 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ2sqrt_mathacl()
int32_t _IQ2sqrt_mathacl (int32_t a)
Calculate square root of an IQ2 input, using MathACL.
Parameters
a IQ2 type input.
Returns
IQ2 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ1sqrt_mathacl()
int32_t _IQ1sqrt_mathacl (int32_t a)
Calculate square root of an IQ1 input, using MathACL.
Parameters
a IQ1 type input.
Returns
IQ1 type result of the square root operation.
References __IQNsqrt_mathacl().
_IQ0sqrt_mathacl()
int32_t _IQ0sqrt_mathacl (int32_t a)
Calculate square root of an IQ0 input, using MathACL.
Parameters
a IQ0 type input.
Returns
IQ0 type result of the square root operation.
References __IQNsqrt_mathacl().
Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale