SensorlessFOCMotorControlLibrary: appUserInputsConfig.h File Reference
appUserInputsConfig.h File Reference
Detailed Description
Application input config apis.
Overview
defines application input configuration apis
#include "appInputCtrlInterface.h"
#include "appUserInputs.h"
Functions
int32_t openLoopAccelDecelRate (uint16_t index)
Gets the open loop acceleration and deceleration rate.
int32_t closeLoopAccelDecelRate (uint16_t index)
Gets the close loop acceleration and deceleration rate.
void update_ISDConfig (USER_INPUTS_T *pUserInputs)
Updates ISD configurations.
void update_RvsDrvConfig (USER_INPUTS_T *pUserInputs)
Updates reverse drive configurations.
void update_MotorStartUp1Config (USER_INPUTS_T *pUserInputs)
Updates startup1 configurations.
void update_MotorStartUp2Config (USER_INPUTS_T *pUserInputs)
Updates startup2 configurations.
void update_CloseLoop1Config (USER_INPUTS_T *pUserInputs)
Updates close loop 1 configurations.
void update_SystemParams (USER_INPUTS_T *pUserInputs)
Updates motor configurations.
void update_FaultCfg1Config (USER_INPUTS_T *pUserInputs)
Updates fault config 1 configurations.
void update_FaultCfg2Config (USER_INPUTS_T *pUserInputs)
Updates fault config 2 configurations.
void update_MiscAlgoConfig (USER_INPUTS_T *pUserInputs)
Updates Misc algo configurations.
void appUserInputRegsConfig (USER_INPUTS_T *pUserInputs)
Updates all Input Registers configurations.
void appUserInputsInit (USER_INPUTS_T *pUserInputs)
Initializes user inputs.
Function Documentation
openLoopAccelDecelRate()
int32_t openLoopAccelDecelRate (uint16_t index)
Gets the open loop acceleration and deceleration rate.
Parameters
[in] index Set Index
Returns
Returns acceleration and deceleration rate from the config table
References tbl1_olAccA1A2_centiHzPerSec, and tbl2_olAccA1A2_HzPerSec.
Referenced by update_MotorStartUp2Config(), and update_RvsDrvConfig().
closeLoopAccelDecelRate()
int32_t closeLoopAccelDecelRate (uint16_t index)
Gets the close loop acceleration and deceleration rate.
Parameters
[in] index Set Index
Returns
Returns acceleration and deceleration rate from the config table
References tbl1_clDecClAcc_deciHzPerSec, and tbl2_clDecClAcc_HzPerSec.
Referenced by update_CloseLoop1Config().
update_ISDConfig()
void update_ISDConfig (USER_INPUTS_T * pUserInputs)
Updates ISD configurations.
Parameters
[in] pUserInputs Pointer to user Inputs
References USER_INPUT_ISDCFG_T::b, USER_INPUT_INTERFACE_T::isdCfg, USER_INPUTS_T::isdMaxStopBemfPU, pUserInputRegs, USER_INPUTS_T::reverseTransitionSpeedPerMil, userInputISD::statDetectThr, tbl_revDrvHandOffThr_pMil, and tbl_StatDetectThr_pu.
Referenced by appUserInputRegsConfig().
update_RvsDrvConfig()
void update_RvsDrvConfig (USER_INPUTS_T * pUserInputs)
Updates reverse drive configurations.
Parameters
[in] pUserInputs Pointer to user Inputs
References userInputRvrDrvCfg::activeBrakeKi, userInputRvrDrvCfg::activeBrakeKp, USER_INPUT_RVSDRVCFG_T::b, USER_INPUT_MTR_STARTUP2_T::b, USER_INPUTS_T::kiPlug, USER_INPUTS_T::kpPlug, USER_INPUT_INTERFACE_T::mtrStartUp2, userInputMotorStartUp2::olAcc1, userInputMotorStartUp2::olAcc2, openLoopAccelDecelRate(), USER_INPUTS_T::openLoopSlowAccelAccelSlewRateCentiHzPerSecPerSec, USER_INPUTS_T::openLoopSlowAccelSpeedSlewRateCentiHzPerSec, pUserInputRegs, userInputRvrDrvCfg::revDrvConfig, userInputRvrDrvCfg::revDrvOpenLoopAccelA1, userInputRvrDrvCfg::revDrvOpenLoopAccelA2, and USER_INPUT_INTERFACE_T::rvsDrvCfg.
Referenced by appUserInputRegsConfig().
update_MotorStartUp1Config()
void update_MotorStartUp1Config (USER_INPUTS_T * pUserInputs)
Updates startup1 configurations.
Parameters
[in] pUserInputs Pointer to user Inputs
References USER_INPUTS_T::ipdPulseToPulseTimeMsec, pUserInputRegs, and tbl_ipdClkFreq_Hz.
Referenced by appUserInputRegsConfig().
update_MotorStartUp2Config()
void update_MotorStartUp2Config (USER_INPUTS_T * pUserInputs)
Updates startup2 configurations.
Parameters
[in] pUserInputs Pointer to user Inputs
References USER_INPUTS_T::angleErrorSlewRateMilliDegreesPerMsec, USER_INPUT_MTR_STARTUP2_T::b, USER_INPUTS_T::forwardTransitionSpeedPerMil, USER_INPUT_INTERFACE_T::mtrStartUp2, userInputMotorStartUp2::olAcc2, userInputMotorStartUp2::olClHandOffThr, openLoopAccelDecelRate(), USER_INPUTS_T::openLoopFastAccelAccelSlewRateCentiHzPerSecPerSec, pUserInputRegs, and tbl_thetaErrRampRate_mili.
Referenced by appUserInputRegsConfig().
update_CloseLoop1Config()
void update_CloseLoop1Config (USER_INPUTS_T * pUserInputs)
Updates close loop 1 configurations.
Parameters
[in] pUserInputs Pointer to user Inputs
References USER_INPUT_CLOSE_LOOP1_T::b, userInputCloseLoop1::clAcc, userInputCloseLoop1::clDec, userInputCloseLoop1::clDecCfg, USER_INPUT_INTERFACE_T::closeLoop1, closeLoopAccelDecelRate(), USER_INPUTS_T::closeLoopFastAccelSpeedSlewRateDeciHzPerSec, USER_INPUTS_T::closeLoopFastDecelSpeedSlewRateDeciHzPerSec, pUserInputRegs, and userInputCloseLoop1::speedLoopDis.
Referenced by appUserInputRegsConfig().
update_SystemParams()
void update_SystemParams (USER_INPUTS_T * pUserInputs)
Updates motor configurations.
Parameters
[in] pUserInputs Pointer to user Inputs
References SYSTEM_PARAMETERS_T::currentBase, SYSTEM_PARAMETERS_T::currLoopKi, SYSTEM_PARAMETERS_T::currLoopKp, SYSTEM_PARAMETERS_T::fluxWeakeningKi, SYSTEM_PARAMETERS_T::fluxWeakeningKp, USER_INPUTS_T::fullScalePhaseCurrentAmp, USER_INPUTS_T::KeMilliVoltPhasePkPerHz, USER_INPUTS_T::kiCurrent, USER_INPUTS_T::kiFluxWeak, USER_INPUTS_T::kiSpeed, USER_INPUTS_T::kpCurrent, USER_INPUTS_T::kpFluxWeak, USER_INPUTS_T::kpSpeed, USER_INPUTS_T::LdMicroHenry, USER_INPUTS_T::LqMicroHenry, USER_INPUTS_T::maximumSpeedHz, SYSTEM_PARAMETERS_T::maxMotorSpeed, SYSTEM_PARAMETERS_T::mtrBemfConst, SYSTEM_PARAMETERS_T::mtrInductance, SYSTEM_PARAMETERS_T::mtrResist, SYSTEM_PARAMETERS_T::mtrSaliency, pUserInputRegs, USER_INPUTS_T::rsMilliOhms, SYSTEM_PARAMETERS_T::speedLoopKi, SYSTEM_PARAMETERS_T::speedLoopKp, USER_INPUTS_T::systemDCBusVoltageVolts, USER_INPUT_INTERFACE_T::systemParams, and SYSTEM_PARAMETERS_T::voltageBase.
Referenced by appUserInputRegsConfig().
update_FaultCfg1Config()
void update_FaultCfg1Config (USER_INPUTS_T * pUserInputs)
Updates fault config 1 configurations.
Parameters
[in] pUserInputs Pointer to user Inputs
Referenced by appUserInputRegsConfig().
update_FaultCfg2Config()
void update_FaultCfg2Config (USER_INPUTS_T * pUserInputs)
Updates fault config 2 configurations.
Parameters
[in] pUserInputs Pointer to user Inputs
References userInputFaultCfg2::abnBemfThr, USER_INPUTS_T::abnormalSpeedLimitPerMil, moduleEnableFlags::abnormalSpeedStallDetectEnable, MODULE_ENABLE_FLAGS_T::b, USER_INPUT_FAULT_CFG2_T::b, USER_INPUT_INTERFACE_T::faultCfg2, userInputFaultCfg2::lock1En, userInputFaultCfg2::lock2En, userInputFaultCfg2::lock3En, userInputFaultCfg2::lockAbnSpeed, USER_INPUTS_T::lowBemfEmagThresholdPerMil, moduleEnableFlags::lowBemfStallDetectEnable, USER_INPUTS_T::moduleFlags, USER_INPUTS_T::noMotorLimitPU, moduleEnableFlags::noMotorStallDetectEnable, userInputFaultCfg2::noMtrThr, pUserInputRegs, tbl_AbnormalBEMFThr_pMil, and tbl_pu.
Referenced by appUserInputRegsConfig().
update_MiscAlgoConfig()
void update_MiscAlgoConfig (USER_INPUTS_T * pUserInputs)
Updates Misc algo configurations.
Parameters
[in] pUserInputs Pointer to user Inputs
References USER_INPUT_MISC_ALGO_T::b, USER_INPUTS_T::closeLoopSlowAccelSpeedSlewRateDeciHzPerSec, userInputMiscAlgo::clSlowAcc, USER_INPUT_INTERFACE_T::miscAlgo, USER_INPUTS_T::openLoopDecelToSlowAccelSlewRateRatioPerMil, pUserInputRegs, tbl_avsRevDrvOLDec_pMil, and tbl_clSlowAcc_deci.
Referenced by appUserInputRegsConfig().
appUserInputRegsConfig()
void appUserInputRegsConfig (USER_INPUTS_T * pUserInputs)
Updates all Input Registers configurations.
Parameters
[in] pUserInputs Pointer to user Inputs
References update_CloseLoop1Config(), update_FaultCfg1Config(), update_FaultCfg2Config(), update_ISDConfig(), update_MiscAlgoConfig(), update_MotorStartUp1Config(), update_MotorStartUp2Config(), update_RvsDrvConfig(), and update_SystemParams().
appUserInputsInit()
void appUserInputsInit (USER_INPUTS_T * pUserInputs)
Initializes user inputs.
Parameters
[in] pUserInputs Pointer to user Inputs
References USER_INPUTS_T::overVoltageHystPU, and USER_INPUTS_T::underVoltageHystPU.
© Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale