SensorlessFOCMotorControlLibrary: MSPM0G3507 - Hardware Abstraction Layer (HAL)
MSPM0G3507 - Hardware Abstraction Layer (HAL)
Data Structures
struct HAL_SPI
Define SPI instance.
struct HAL_ADC
Define ADC instance.
struct HAL_PWM
Define PWM instance.
struct HAL_CAPTURE
Define Capture instance.
struct HAL_TIM
Define TIM instance.
struct HAL_GPIO
Define GPIO instance.
struct HAL_COMP
Define COMP instance.
Macros
#define HAL_MCU_CLK_SPEED_HZ (80000000)
MCU clock frequency.
#define HAL_CYCLES_TO_1_MS_DELAY (HAL_MCU_CLK_SPEED_HZ/1000)
Cycles for 1 ms delay.
#define HAL_ADC_MAX_VALUE (4095)
Maximum value of data from the ADC.
#define HAL_ADC_DEFAULT_REF_VOLTAGE (3.3f)
Value of default ADC reference voltage in volts.
#define HAL_TIM_PERIPHERAL_CLOCK_SOURCE_MHZ (80)
Value of the source clock for the timer peripherals.
#define CRC_BYTES_TO_WORD_RSHIFT (2)
Right shift to convert bytes to words.
Enumerations
enum HAL_PWM_CHANNEL {
HAL_PWM_CHANNEL_0 = 0,
HAL_PWM_CHANNEL_1,
HAL_PWM_CHANNEL_2,
HAL_PWM_CHANNEL_3,
HAL_PWM_CHANNEL_MAX
}
enum HAL_CAPTURE_CHANNEL {
HAL_CAPTURE_CHANNEL_0 = 0,
HAL_CAPTURE_CHANNEL_MAX
}
enum HAL_PWM_FAULT {
HAL_PWM_FAULT_0 = 0,
HAL_PWM_FAULT_MAX
}
enum HAL_ADC_CHANNEL {
HAL_ADC_CHANNEL_0 = 0,
HAL_ADC_CHANNEL_1,
HAL_ADC_CHANNEL_2,
HAL_ADC_CHANNEL_3,
HAL_ADC_CHANNEL_MAX
}
enum HAL_GPIO_IN_PIN {
HAL_GPIO_IN_PIN_0 = 0,
HAL_GPIO_IN_PIN_MAX
}
enum HAL_GPIO_OUT_PIN {
HAL_GPIO_OUT_PIN_0 = 0,
HAL_GPIO_OUT_PIN_MAX
}
enum HAL_COMP_CHANNEL {
HAL_COMP_CHANNEL_0 = 0,
HAL_COMP_CHANNEL_1,
HAL_COMP_CHANNEL_2,
HAL_COMP_CHANNEL_MAX
}
enum HAL_SPI_CHANNEL {
HAL_SPI_CHANNEL_0 = 0,
HAL_SPI_CHANNEL_MAX
}
enum HAL_SPI_CS {
HAL_SPI_CS_0 = 0,
HAL_SPI_CS_1,
HAL_SPI_CS_2,
HAL_SPI_CS_3,
HAL_SPI_CS_MAX
}
enum HAL_GPIO_VALUE {
HAL_GPIO_VALUE_LOW = 0,
HAL_GPIO_VALUE_HIGH
}
enum HAL_MEMORY {
HAL_MEMORY_FLASH_PARAMS_BASE_ADDRESS = 0x0001FC00,
HAL_MEMORY_SRAM_PARAMS_BASE_ADDRESS = 0x20207C00
}
Functions
void HAL_init (void)
Initializes the hal module.
void HAL_setADCRefVoltage (HAL_ADC_CHANNEL adcChan, _iq15 value)
Sets the ADC reference voltage.
_iq15 HAL_getADCRefVoltage (HAL_ADC_CHANNEL adcChan)
Gets the ADC reference voltage.
void HAL_setADCSf (void)
Sets the ADC scale factor.
void HAL_checkAndEnableIRQ (IRQn_Type irqn)
If the IRQ is disabled it is enabled.
void HAL_enableADCInterrupt (HAL_ADC_CHANNEL adcChan)
Enable ADC interrupt.
void HAL_disableADCInterrupt (HAL_ADC_CHANNEL adcChan)
Disable ADC interrupt.
void HAL_enablePWMInterrupt (HAL_PWM_CHANNEL pwmChan)
Enable PWM interrupt.
void HAL_disablePWMInterrupt (HAL_PWM_CHANNEL pwmChan)
Disable PWM interrupt.
void HAL_enableCaptureInterrupt (HAL_CAPTURE_CHANNEL captureChan)
Enable Capture interrupt.
void HAL_disableCaptureInterrupt (HAL_CAPTURE_CHANNEL captureChan)
Disable Capture interrupt.
void HAL_setGPIOVal (HAL_GPIO_OUT_PIN gpioPin, HAL_GPIO_VALUE value)
Set value to GPIO pin.
HAL_GPIO_VALUE HAL_readGPIOVal (HAL_GPIO_IN_PIN gpioPin)
Read GPIO pin.
uint32_t HAL_getPWMLoadValue (HAL_PWM_CHANNEL pwmChan)
Gets the Load value of the timer associated with the PWM channel.
uint16_t HAL_setDeadband (HAL_PWM_CHANNEL pwmChan, uint16_t deadband)
Set deadband to the PWM channel.
__STATIC_INLINE void HAL_setPWMCcValue (HAL_PWM_CHANNEL pwmChan, uint32_t ccVal)
Set Compare to the PWM channel.
void HAL_setPWMFreq (HAL_PWM_CHANNEL pwmChan, uint32_t freq)
Set the frequency of the timer associated with the PWM channel.
void HAL_setFreq (GPTIMER_Regs *timerInst, uint32_t freq)
Set the frequency for timer peripheral.
void HAL_setLoadVal (GPTIMER_Regs *timerInst, uint32_t loadValue)
Set the Load value of a timer peripheral.
_iq15 HAL_getADCVoltage (HAL_ADC_CHANNEL adcChan)
Gets the ADC reading converted to voltage.
__STATIC_INLINE uint16_t HAL_getADCData (HAL_ADC_CHANNEL adcChan)
Gets the ADC sampled value.
__STATIC_INLINE uint16_t HAL_getADCValue (HAL_ADC_CHANNEL adcChan)
Gets the raw value read from adc.
__STATIC_INLINE DL_ADC12_IIDX HAL_processADCIRQ (ADC12_Regs *adcInst)
Collects the ADC data if the adc conversion is over.
void HAL_delayMilliSeconds (uint32_t num_ms)
Blocks for the specified delay time.
bool HAL_isSPIRxFifoEmpty (HAL_SPI_CHANNEL spiPeripheral)
Gets status of RX Fifo.
uint16_t HAL_receiveSPIData16 (HAL_SPI_CHANNEL spiPeripheral, HAL_SPI_CS cs)
Reads 16 bit data in SPI peripheral.
void HAL_transmitSPIData16 (HAL_SPI_CHANNEL spiPeripheral, HAL_SPI_CS cs, uint16_t data)
Writes 16 bit data in SPI peripheral.
bool HAL_isSPIBusy (HAL_SPI_CHANNEL spiPeripheral)
Gets busy status of SPI peripheral.
__STATIC_INLINE void HAL_SPI_clearRXFifo (HAL_SPI_CHANNEL spiPeripheral, HAL_SPI_CS cs)
Clears the RX Fifo if the SPI peripheral.
void HAL_PWMEnableChannel (HAL_PWM_CHANNEL pwmChan)
Enables the PWM channel.
void HAL_PWMDisableChannel (HAL_PWM_CHANNEL pwmChan)
Disables the PWM channel and overrides the channel and complementary outputs to low.
void HAL_PWMForceHigh (HAL_PWM_CHANNEL pwmChan)
Force the PWM out to high and complement out to low.
void HAL_PWMForceLow (HAL_PWM_CHANNEL pwmChan)
Force the PWM out to low and complement out to high.
void HAL_clearPWMFault (HAL_PWM_FAULT pwmFault)
Clears the PWM timer fault status.
bool HAL_getPWMFaultStatus (HAL_PWM_FAULT pwmFault)
Gets the PWM timer fault status.
void HAL_unprotectFLASH (uint32_t baseAddress)
Unprotects the sector with the given base address.
void HAL_eraseFLASH (uint32_t baseAddress)
Erase the sector with the given base address.
int32_t HAL_copyMemoryBlock (void *dstAddr, void *srcAddr, uint32_t len, uint32_t startAddr)
Copies the SRAM memory block to flash.
uint32_t HAL_getCRC (uint32_t seed, void *ptr, uint32_t size)
Returns the 32bit CRC value.
void HAL_supressCompEvent (HAL_PWM_CHANNEL pwmChan)
Suppresses the compare event.
__STATIC_INLINE void HAL_setRepeatCounter (HAL_PWM_CHANNEL pwmChan, uint8_t value)
Set the Load value for the repeat counter.
void HAL_setCaptureCount (HAL_CAPTURE_CHANNEL captureChan, uint32_t count)
Set value to counter register of timer.
uint32_t HAL_getCaptureValue (HAL_CAPTURE_CHANNEL captureChan)
Get the captured counter value.
void HAL_setCaptureSubChannel (HAL_CAPTURE_CHANNEL captureChan, uint8_t value)
Set subscriber channel id to capture channel.
uint32_t HAL_getCaptureLoadValue (HAL_CAPTURE_CHANNEL captureChan)
Gets the load value of the timer associated with the capture channel.
void HAL_clearCaptureInterruptStatus (HAL_CAPTURE_CHANNEL captureChan)
Clears the interrupt status of the capture channel.
void HAL_setCOMPDAC (HAL_COMP_CHANNEL compChan, uint8_t value)
Set the DAC value for the comp associated with the COMP channel.
uint8_t HAL_getCOMPPubChannelID (HAL_COMP_CHANNEL compChan)
Gets the publisher channel id for the COMP channel.
Variables
HAL_PWM halPwm [HAL_PWM_CHANNEL_MAX]
Array for storing the PWM instances.
HAL_SPI halSpi [HAL_SPI_CHANNEL_MAX]
Array for storing the SPI instances.
DL_SPI_CHIP_SELECT halSpiCS [HAL_SPI_CS_MAX]
Array for storing chip selects for spi peripheral.
HAL_ADC halAdc [HAL_ADC_CHANNEL_MAX]
Array for storing the ADC instances.
HAL_GPIO halGpioIN [HAL_GPIO_IN_PIN_MAX]
Array for storing the input GPIO pin instances.
HAL_GPIO halGpioOUT [HAL_GPIO_OUT_PIN_MAX]
Array for storing the ouput GPIO pin instances.
Detailed Description
Overview
The HAL module provides micro-controller agnostic set of application programming interfaces (APIs) to be used by other module's in the library as well as in the user's application code.
Enumeration Type Documentation
HAL_PWM_CHANNEL
enum HAL_PWM_CHANNEL
Enumerator
HAL_PWM_CHANNEL_0
Index associated to PWM channel 0
HAL_PWM_CHANNEL_1
Index associated to PWM channel 1
HAL_PWM_CHANNEL_2
Index associated to PWM channel 2
HAL_PWM_CHANNEL_3
Index associated to PWM channel 3
HAL_PWM_CHANNEL_MAX
Total number of PWM channels
HAL_CAPTURE_CHANNEL
enum HAL_CAPTURE_CHANNEL
Enumerator
HAL_CAPTURE_CHANNEL_0
Index associated to capture channel 0
HAL_CAPTURE_CHANNEL_MAX
Total number of capture channels
HAL_PWM_FAULT
enum HAL_PWM_FAULT
Enumerator
HAL_PWM_FAULT_0
Index associated to PWM fault input 0
HAL_PWM_FAULT_MAX
Total number of PWM Fault Inputs
HAL_ADC_CHANNEL
enum HAL_ADC_CHANNEL
Enumerator
HAL_ADC_CHANNEL_0
Index associated to ADC channel 0
HAL_ADC_CHANNEL_1
Index associated to ADC channel 1
HAL_ADC_CHANNEL_2
Index associated to ADC channel 2
HAL_ADC_CHANNEL_3
Index associated to ADC channel 3
HAL_ADC_CHANNEL_MAX
Total number of ADC channels
HAL_GPIO_IN_PIN
enum HAL_GPIO_IN_PIN
Enumerator
HAL_GPIO_IN_PIN_0
Index associated to input GPIO PIN 0
HAL_GPIO_IN_PIN_MAX
Total number of input GPIO pins
HAL_GPIO_OUT_PIN
enum HAL_GPIO_OUT_PIN
Enumerator
HAL_GPIO_OUT_PIN_0
Index associated to output GPIO PIN 0
HAL_GPIO_OUT_PIN_MAX
Total number of output GPIO pins
HAL_COMP_CHANNEL
enum HAL_COMP_CHANNEL
Enumerator
HAL_COMP_CHANNEL_0
Index associated to COMP channel 0
HAL_COMP_CHANNEL_1
Index associated to COMP channel 1
HAL_COMP_CHANNEL_2
Index associated to COMP channel 2
HAL_COMP_CHANNEL_MAX
Total number of COMP channels
HAL_SPI_CHANNEL
enum HAL_SPI_CHANNEL
Enumerator
HAL_SPI_CHANNEL_0
Index associated to SPI channel 0
HAL_SPI_CHANNEL_MAX
Total number of SPI channels
HAL_SPI_CS
enum HAL_SPI_CS
Enumerator
HAL_SPI_CS_0
Index associated to chip select 0
HAL_SPI_CS_1
Index associated to chip select 1
HAL_SPI_CS_2
Index associated to chip select 2
HAL_SPI_CS_3
Index associated to chip select 3
HAL_SPI_CS_MAX
Total number of chip select pins
HAL_GPIO_VALUE
enum HAL_GPIO_VALUE
Enumerator
HAL_GPIO_VALUE_LOW
GPIO set to low
HAL_GPIO_VALUE_HIGH
GPIO set to high
HAL_MEMORY
enum HAL_MEMORY
Enumerator
HAL_MEMORY_FLASH_PARAMS_BASE_ADDRESS
FLASH motor parameters base address
HAL_MEMORY_SRAM_PARAMS_BASE_ADDRESS
SRAM motor parameters base address
Function Documentation
HAL_setADCRefVoltage()
void HAL_setADCRefVoltage (HAL_ADC_CHANNEL adcChan, _iq15 value)
Sets the ADC reference voltage.
Parameters
[in] adcChan An ADC Channel. One of HAL_ADC_CHANNEL
[in] value Reference voltage to be set in IQ
References HAL_ADC::refVoltage.
Referenced by HAL_init().
HAL_getADCRefVoltage()
_iq15 HAL_getADCRefVoltage (HAL_ADC_CHANNEL adcChan)
Gets the ADC reference voltage.
Parameters
[in] adcChan An ADC Channel. One of HAL_ADC_CHANNEL
Returns
Returns the value of the adc reference voltage in iq15
References HAL_ADC::refVoltage.
Referenced by DRV8323RS_getIA(), DRV8323RS_getIB(), and DRV8323RS_getIC().
HAL_checkAndEnableIRQ()
void HAL_checkAndEnableIRQ (IRQn_Type irqn)
If the IRQ is disabled it is enabled.
Parameters
[in] irqn An IRQn.
Referenced by HAL_enableADCInterrupt(), HAL_enableCaptureInterrupt(), and HAL_enablePWMInterrupt().
HAL_enableADCInterrupt()
void HAL_enableADCInterrupt (HAL_ADC_CHANNEL adcChan)
Enable ADC interrupt.
Parameters
[in] adcChan An ADC Channel. One of HAL_ADC_CHANNEL
References HAL_checkAndEnableIRQ().
HAL_disableADCInterrupt()
void HAL_disableADCInterrupt (HAL_ADC_CHANNEL adcChan)
Disable ADC interrupt.
Parameters
[in] adcChan An ADC Channel. One of HAL_ADC_CHANNEL
HAL_enablePWMInterrupt()
void HAL_enablePWMInterrupt (HAL_PWM_CHANNEL pwmChan)
Enable PWM interrupt.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
References HAL_checkAndEnableIRQ().
HAL_disablePWMInterrupt()
void HAL_disablePWMInterrupt (HAL_PWM_CHANNEL pwmChan)
Disable PWM interrupt.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
HAL_enableCaptureInterrupt()
void HAL_enableCaptureInterrupt (HAL_CAPTURE_CHANNEL captureChan)
Enable Capture interrupt.
Parameters
[in] captureChan A capture channel. One of HAL_CAPTURE_CHANNEL
References HAL_checkAndEnableIRQ().
HAL_disableCaptureInterrupt()
void HAL_disableCaptureInterrupt (HAL_CAPTURE_CHANNEL captureChan)
Disable Capture interrupt.
Parameters
[in] captureChan A capture channel. One of HAL_CAPTURE_CHANNEL
HAL_setGPIOVal()
void HAL_setGPIOVal (HAL_GPIO_OUT_PIN gpioPin, HAL_GPIO_VALUE value)
Set value to GPIO pin.
Parameters
[in] gpioPin A GPIO pin. One of HAL_GPIO_OUT_PIN
[in] value Value to be set to pin. One of HAL_GPIO_VALUE
References HAL_GPIO_VALUE_HIGH.
Referenced by DRV8323RS_disable(), and DRV8323RS_enable().
HAL_readGPIOVal()
HAL_GPIO_VALUE HAL_readGPIOVal (HAL_GPIO_IN_PIN gpioPin)
Read GPIO pin.
Parameters
[in] gpioPin A GPIO pin. One of HAL_GPIO_IN_PIN
Returns
Returns the value of the GPIO pin. One of HAL_GPIO_VALUE
References HAL_GPIO_VALUE_HIGH, and HAL_GPIO_VALUE_LOW.
HAL_getPWMLoadValue()
uint32_t HAL_getPWMLoadValue (HAL_PWM_CHANNEL pwmChan)
Gets the Load value of the timer associated with the PWM channel.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
Returns
Returns the load register value of the timer instance of the specified PWM channel
Referenced by FOC_setPara().
HAL_setDeadband()
uint16_t HAL_setDeadband (HAL_PWM_CHANNEL pwmChan, uint16_t deadband)
Set deadband to the PWM channel.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
[in] deadband Deadtime in nanoseconds
Returns
Returns the deadtime in PWM cycles
References HAL_TIM_PERIPHERAL_CLOCK_SOURCE_MHZ.
Referenced by FOC_setPara().
HAL_setPWMCcValue()
__STATIC_INLINE void HAL_setPWMCcValue (HAL_PWM_CHANNEL pwmChan, uint32_t ccVal)
Set Compare to the PWM channel.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
[in] ccVal Compare value to be set. One of HAL_PWM_CHANNEL
References HAL_getADCVoltage(), HAL_setFreq(), HAL_setLoadVal(), and HAL_setPWMFreq().
Referenced by FOC_loop(), FOC_run(), and FOC_setADCTrig().
HAL_setPWMFreq()
void HAL_setPWMFreq (HAL_PWM_CHANNEL pwmChan, uint32_t freq)
Set the frequency of the timer associated with the PWM channel.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
[in] freq PWM frequency to be set.
References HAL_setFreq().
Referenced by FOC_setPara(), and HAL_setPWMCcValue().
HAL_setFreq()
void HAL_setFreq (GPTIMER_Regs * timerInst, uint32_t freq)
Set the frequency for timer peripheral.
Parameters
[in] timerInst Pointer to a timer peripheral.
[in] freq Frequency to be set to peripheral.
References HAL_setLoadVal(), and HAL_TIM_PERIPHERAL_CLOCK_SOURCE_MHZ.
Referenced by HAL_setPWMCcValue(), and HAL_setPWMFreq().
HAL_setLoadVal()
void HAL_setLoadVal (GPTIMER_Regs * timerInst, uint32_t loadValue)
Set the Load value of a timer peripheral.
Parameters
[in] timerInst Pointer to a timer peripheral.
[in] loadValue Load value to be set to the timer peripheral.
Referenced by HAL_setFreq(), and HAL_setPWMCcValue().
HAL_getADCVoltage()
_iq15 HAL_getADCVoltage (HAL_ADC_CHANNEL adcChan)
Gets the ADC reading converted to voltage.
Parameters
[in] adcChan An ADC Channel. One of HAL_ADC_CHANNEL
Returns
Returns the ADC voltage reading in iq15
Referenced by DRV8323RS_getIA(), DRV8323RS_getIB(), DRV8323RS_getIC(), DRV8323RS_getVM(), and HAL_setPWMCcValue().
HAL_getADCData()
__STATIC_INLINE uint16_t HAL_getADCData (HAL_ADC_CHANNEL adcChan)
Gets the ADC sampled value.
Parameters
[in] adcChan An ADC Channel. One of HAL_ADC_CHANNEL
Returns
Returns the ADC sampled value
Referenced by HAL_processADCIRQ().
HAL_getADCValue()
__STATIC_INLINE uint16_t HAL_getADCValue (HAL_ADC_CHANNEL adcChan)
Gets the raw value read from adc.
Parameters
[in] adcChan An ADC Channel. One of HAL_ADC_CHANNEL
Returns
Returns the raw value read from adc
References HAL_ADC::value.
Referenced by DRV8323RS_getIARaw(), DRV8323RS_getIBRaw(), DRV8323RS_getICRaw(), and DRV8323RS_getVMRaw().
HAL_processADCIRQ()
__STATIC_INLINE DL_ADC12_IIDX HAL_processADCIRQ (ADC12_Regs * adcInst)
Collects the ADC data if the adc conversion is over.
Parameters
[in] adcInst Pointer to a ADC peripheral
Returns
DL_ADC12_IIDX returns interrupt information that caused the IRQ to fire.
References HAL_ADC_CHANNEL_MAX, HAL_delayMilliSeconds(), HAL_getADCData(), HAL_isSPIBusy(), HAL_isSPIRxFifoEmpty(), HAL_receiveSPIData16(), HAL_transmitSPIData16(), and HAL_ADC::value.
HAL_delayMilliSeconds()
void HAL_delayMilliSeconds (uint32_t num_ms)
Blocks for the specified delay time.
Parameters
[in] num_ms Delay in ms
References HAL_CYCLES_TO_1_MS_DELAY.
Referenced by DRV8323RS_disable(), DRV8323RS_enable(), and HAL_processADCIRQ().
HAL_isSPIRxFifoEmpty()
bool HAL_isSPIRxFifoEmpty (HAL_SPI_CHANNEL spiPeripheral)
Gets status of RX Fifo.
Parameters
[in] spiPeripheral A SPI peripheral. One of HAL_SPI_CHANNEL
Returns
Returns empty status of RX Fifo
Return values
true The RX FIFO is empty
false The RX FIFO is not empty
Referenced by HAL_processADCIRQ(), and HAL_SPI_clearRXFifo().
HAL_receiveSPIData16()
uint16_t HAL_receiveSPIData16 (HAL_SPI_CHANNEL spiPeripheral, HAL_SPI_CS cs)
Reads 16 bit data in SPI peripheral.
Parameters
[in] spiPeripheral A SPI peripheral. One of HAL_SPI_CHANNEL
[in] cs A SPI chip select. One of HAL_SPI_CS
Returns
Data received in SPI peripheral
References halSpiCS.
Referenced by DRV8323RS_spiRead(), HAL_processADCIRQ(), and HAL_SPI_clearRXFifo().
HAL_transmitSPIData16()
void HAL_transmitSPIData16 (HAL_SPI_CHANNEL spiPeripheral, HAL_SPI_CS cs, uint16_t data)
Writes 16 bit data in SPI peripheral.
Parameters
[in] spiPeripheral A SPI peripheral. One of HAL_SPI_CHANNEL
[in] cs A SPI chip select. One of HAL_SPI_CS
[in] data Data to be written in to the SPI peripheral
References halSpiCS.
Referenced by DRV8323RS_spiRead(), DRV8323RS_spiWrite(), and HAL_processADCIRQ().
HAL_isSPIBusy()
bool HAL_isSPIBusy (HAL_SPI_CHANNEL spiPeripheral)
Gets busy status of SPI peripheral.
Parameters
[in] spiPeripheral A SPI peripheral. One of HAL_SPI_CHANNEL
Returns
Returns busy status of RX Fifo
Return values
true The SPI peripheral is currently busy with transmitting data
false The SPI peripheral is in idle
Referenced by DRV8323RS_spiRead(), DRV8323RS_spiWrite(), and HAL_processADCIRQ().
HAL_SPI_clearRXFifo()
__STATIC_INLINE void HAL_SPI_clearRXFifo (HAL_SPI_CHANNEL spiPeripheral, HAL_SPI_CS cs)
Clears the RX Fifo if the SPI peripheral.
Parameters
[in] spiPeripheral A SPI peripheral. One of HAL_SPI_CHANNEL
[in] cs A SPI chip select. One of HAL_SPI_CS
References HAL_clearPWMFault(), HAL_copyMemoryBlock(), HAL_eraseFLASH(), HAL_getCRC(), HAL_getPWMFaultStatus(), HAL_isSPIRxFifoEmpty(), HAL_PWMDisableChannel(), HAL_PWMEnableChannel(), HAL_PWMForceHigh(), HAL_PWMForceLow(), HAL_receiveSPIData16(), HAL_supressCompEvent(), and HAL_unprotectFLASH().
Referenced by DRV8323RS_spiRead().
HAL_PWMEnableChannel()
void HAL_PWMEnableChannel (HAL_PWM_CHANNEL pwmChan)
Enables the PWM channel.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
Referenced by FOC_loop(), FOC_run(), and HAL_SPI_clearRXFifo().
HAL_PWMDisableChannel()
void HAL_PWMDisableChannel (HAL_PWM_CHANNEL pwmChan)
Disables the PWM channel and overrides the channel and complementary outputs to low.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
Referenced by FOC_init(), FOC_loop(), FOC_run(), FOC_setFault(), and HAL_SPI_clearRXFifo().
HAL_PWMForceHigh()
void HAL_PWMForceHigh (HAL_PWM_CHANNEL pwmChan)
Force the PWM out to high and complement out to low.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
Referenced by HAL_SPI_clearRXFifo().
HAL_PWMForceLow()
void HAL_PWMForceLow (HAL_PWM_CHANNEL pwmChan)
Force the PWM out to low and complement out to high.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
Referenced by HAL_SPI_clearRXFifo().
HAL_clearPWMFault()
void HAL_clearPWMFault (HAL_PWM_FAULT pwmFault)
Clears the PWM timer fault status.
Parameters
[in] pwmFault A PWM fault input. One of HAL_PWM_FAULT
References HAL_PWM::inst.
Referenced by DRV8323RS_clearFaults(), and HAL_SPI_clearRXFifo().
HAL_getPWMFaultStatus()
bool HAL_getPWMFaultStatus (HAL_PWM_FAULT pwmFault)
Gets the PWM timer fault status.
Parameters
[in] pwmFault A PWM fault input. One of HAL_PWM_FAULT
Returns
Returns PWM timer fault status
Return values
true Fault occurred
false No fault occurred
References HAL_PWM::inst.
Referenced by DRV8323RS_isFaultOccurred(), and HAL_SPI_clearRXFifo().
HAL_unprotectFLASH()
void HAL_unprotectFLASH (uint32_t baseAddress)
Unprotects the sector with the given base address.
Parameters
[in] baseAddress Base address of the sector
Referenced by FOC_writeFLASH(), HAL_eraseFLASH(), and HAL_SPI_clearRXFifo().
HAL_eraseFLASH()
void HAL_eraseFLASH (uint32_t baseAddress)
Erase the sector with the given base address.
Parameters
[in] baseAddress Base address of the sector
References HAL_unprotectFLASH().
Referenced by FOC_writeFLASH(), and HAL_SPI_clearRXFifo().
HAL_copyMemoryBlock()
int32_t HAL_copyMemoryBlock (void * dstAddr, void * srcAddr, uint32_t len, uint32_t startAddr)
Copies the SRAM memory block to flash.
Parameters
[in] dstAddr Starting address in FLASH
[in] srcAddr Starting address in SRAM
[in] len Length of the data in bytes
[in] startAddr Starting address of the memory section
Returns
Returns stauts for copy
Return values
0 No error
-1 Error in copy
Referenced by FOC_writeFLASH(), and HAL_SPI_clearRXFifo().
HAL_getCRC()
uint32_t HAL_getCRC (uint32_t seed, void * ptr, uint32_t size)
Returns the 32bit CRC value.
Parameters
[in] seed The seed for the CRC to start generating a signature from
[in] ptr Pointer to the data to compute CRC
[in] size Size of the block of data in bytes
Returns
Returns the CRC value
References CRC_BYTES_TO_WORD_RSHIFT.
Referenced by FOC_initFLASH(), FOC_writeFLASH(), and HAL_SPI_clearRXFifo().
HAL_supressCompEvent()
void HAL_supressCompEvent (HAL_PWM_CHANNEL pwmChan)
Suppresses the compare event.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
Referenced by FOC_init(), and HAL_SPI_clearRXFifo().
HAL_setRepeatCounter()
__STATIC_INLINE void HAL_setRepeatCounter (HAL_PWM_CHANNEL pwmChan, uint8_t value)
Set the Load value for the repeat counter.
Parameters
[in] pwmChan A PWM channel. One of HAL_PWM_CHANNEL
[in] value Load value to be set.
References HAL_clearCaptureInterruptStatus(), HAL_getCaptureLoadValue(), HAL_getCaptureValue(), HAL_getCOMPPubChannelID(), HAL_setCaptureCount(), HAL_setCaptureSubChannel(), and HAL_setCOMPDAC().
Referenced by FOC_setPara().
HAL_setCaptureCount()
void HAL_setCaptureCount (HAL_CAPTURE_CHANNEL captureChan, uint32_t count)
Set value to counter register of timer.
Parameters
[in] captureChan A capture channel. One of HAL_CAPTURE_CHANNEL
[in] count Value to set in the counter register
Referenced by HAL_setRepeatCounter().
HAL_getCaptureValue()
uint32_t HAL_getCaptureValue (HAL_CAPTURE_CHANNEL captureChan)
Get the captured counter value.
Parameters
[in] captureChan A capture channel. One of HAL_CAPTURE_CHANNEL
Returns
Returns the captured counter value
Referenced by HAL_setRepeatCounter().
HAL_setCaptureSubChannel()
void HAL_setCaptureSubChannel (HAL_CAPTURE_CHANNEL captureChan, uint8_t value)
Set subscriber channel id to capture channel.
Parameters
[in] captureChan A capture channel. One of HAL_CAPTURE_CHANNEL
[in] value Value of channel id to be set
Referenced by HAL_setRepeatCounter().
HAL_getCaptureLoadValue()
uint32_t HAL_getCaptureLoadValue (HAL_CAPTURE_CHANNEL captureChan)
Gets the load value of the timer associated with the capture channel.
Parameters
[in] captureChan A capture channel. One of HAL_CAPTURE_CHANNEL
Returns
Returns the load register value of the timer instance of the specified capture channel
Referenced by HAL_setRepeatCounter().
HAL_clearCaptureInterruptStatus()
void HAL_clearCaptureInterruptStatus (HAL_CAPTURE_CHANNEL captureChan)
Clears the interrupt status of the capture channel.
Parameters
[in] captureChan A capture channel. One of HAL_CAPTURE_CHANNEL
Referenced by HAL_setRepeatCounter().
HAL_setCOMPDAC()
void HAL_setCOMPDAC (HAL_COMP_CHANNEL compChan, uint8_t value)
Set the DAC value for the comp associated with the COMP channel.
Parameters
[in] compChan A COMP channel. One of HAL_COMP_CHANNEL
[in] value DAC code value to be set
Referenced by HAL_setRepeatCounter().
HAL_getCOMPPubChannelID()
uint8_t HAL_getCOMPPubChannelID (HAL_COMP_CHANNEL compChan)
Gets the publisher channel id for the COMP channel.
Parameters
[in] compChan A COMP channel. One of HAL_COMP_CHANNEL
Returns
Returns the publisher channel id for the comp instance of the specified COMP channel
References HAL_COMP::pubChannelID.
Referenced by HAL_setRepeatCounter().
Copyright 1995-2023, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale