SensorlessFOCMotorControlLibrary: FOC_PARAMETER/PARAMETER
FOC_PARAMETER/PARAMETER
Enumerations
enum PARA_IDX {
PARA_IDX_USER_RS = 0,
PARA_IDX_USER_LS,
PARA_IDX_USER_KE,
PARA_IDX_USER_MAX_FREQ,
PARA_IDX_USER_PWMFREQ,
PARA_IDX_USER_DEADBAND,
PARA_IDX_USER_AMP_GAIN,
PARA_IDX_USER_OUTER_LOOP,
PARA_IDX_USER_DIRECTION_REVERSE,
PARA_IDX_USER_STARTUP_METHOD,
PARA_IDX_USER_SLOW_FIRST_CYC_FREQ,
PARA_IDX_USER_ALIGN_CURRENT,
PARA_IDX_USER_ALIGN_TIME,
PARA_IDX_USER_IPD_CURRENT_THRESHOLD,
PARA_IDX_USER_IPD_FREQ,
PARA_IDX_USER_RAMPUP_CURRENT,
PARA_IDX_USER_RAMPUP_RATE,
PARA_IDX_USER_RAMPUP_TARGET,
PARA_IDX_USER_SPDREF_RAMP_RATE,
PARA_IDX_USER_PISPD_KP,
PARA_IDX_USER_PISPD_KI,
PARA_IDX_USER_PISPD_DIV,
PARA_IDX_USER_PIIQ_KP,
PARA_IDX_USER_PIIQ_KI,
PARA_IDX_USER_PIID_KP,
PARA_IDX_USER_PIID_KI,
PARA_IDX_USER_OVER_VOLTAGE_LIMIT,
PARA_IDX_USER_UNDER_VOLTAGE_LIMIT,
PARA_IDX_USER_OVER_CURRENT_LIMIT,
PARA_IDX_USER_MAX,
PARA_IDX_SYS_DEADBAND_CYC,
PARA_IDX_SYS_PWMPERIOD,
PARA_IDX_SYS_TS,
PARA_IDX_SYS_SAMPLE_FREQ,
PARA_IDX_MAX
}
Enumeration for the FOC parameter.
Functions
void PARA_checkEST (uint32_t *parameter, EST_Instance *handle, PARA_IDX idx)
Check for EST parameter changes.
void PARA_checkPISPD (uint32_t *parameter, PI_Instance *handle, PARA_IDX idx)
Check for PISPD parameter changes.
void PARA_checkPIIQ (uint32_t *parameter, PI_Instance *handle, PARA_IDX idx)
Check for PIIQ parameter changes.
void PARA_checkPIID (uint32_t *parameter, PI_Instance *handle, PARA_IDX idx)
Check for PIID parameter changes.
void PARA_checkRC (uint32_t *parameter, RMPCNTL_Instance *handle, PARA_IDX idx)
Check for RC parameter changes.
void PARA_checkRG (uint32_t *parameter, RAMPGEN_Instance *handle, PARA_IDX idx)
Check for RG parameter changes.
void PARA_checkPWMGEN (uint32_t *parameter, PWMGEN_Instance *handle, PARA_IDX idx)
Check for PWMGEN parameter changes.
void PARA_checkIPD (uint32_t *parameter, IPD_Instance *handle, PARA_IDX idx)
Check for IPD parameter changes.
Detailed Description
Enumeration Type Documentation
PARA_IDX
enum PARA_IDX
Enumeration for the FOC parameter.
Enumerator
PARA_IDX_USER_RS
Index associated to motor stator resistance
PARA_IDX_USER_LS
Index associated to motor stator inductance
PARA_IDX_USER_KE
Index associated to motor backemf constant
PARA_IDX_USER_MAX_FREQ
Index associated to motor maximum frequency
PARA_IDX_USER_PWMFREQ
Index associated to pwm frequency
PARA_IDX_USER_DEADBAND
Index associated to deadband in ns
PARA_IDX_USER_AMP_GAIN
Index associated to amplifier gain
PARA_IDX_USER_OUTER_LOOP
Index associated to outer loop
PARA_IDX_USER_DIRECTION_REVERSE
Index associated to direction reverse
PARA_IDX_USER_STARTUP_METHOD
Index associated to startup method
PARA_IDX_USER_SLOW_FIRST_CYC_FREQ
Index associated to slow first cycle frequency
PARA_IDX_USER_ALIGN_CURRENT
Index associated to align current in Ampere
PARA_IDX_USER_ALIGN_TIME
Index associated to align time in seconds
PARA_IDX_USER_IPD_CURRENT_THRESHOLD
Index associated to IPD current threshold
PARA_IDX_USER_IPD_FREQ
Index associated to IPD frequency in Hz
PARA_IDX_USER_RAMPUP_CURRENT
Index associated to rampup current in Ampere
PARA_IDX_USER_RAMPUP_RATE
Index associated to rampup rate
PARA_IDX_USER_RAMPUP_TARGET
Index associated to rampup target in Hz/sec
PARA_IDX_USER_SPDREF_RAMP_RATE
Index associated to speed reference ramp rate in Hz
PARA_IDX_USER_PISPD_KP
Index associated to proportional gain for speed pi controller
PARA_IDX_USER_PISPD_KI
Index associated to integral gain for speed pi controller
PARA_IDX_USER_PISPD_DIV
Index associated to execution divider for speed pi controller
PARA_IDX_USER_PIIQ_KP
Index associated to proportional gain for iq pi controller
PARA_IDX_USER_PIIQ_KI
Index associated to integral gain for iq pi controller
PARA_IDX_USER_PIID_KP
Index associated to proportional gain for id pi controller
PARA_IDX_USER_PIID_KI
Index associated to integral gain for id pi controller
PARA_IDX_USER_OVER_VOLTAGE_LIMIT
Index associated to over voltage limit
PARA_IDX_USER_UNDER_VOLTAGE_LIMIT
Index associated to under voltage limit
PARA_IDX_USER_OVER_CURRENT_LIMIT
Index associated to over current limit
PARA_IDX_USER_MAX
Total number of user parameters
PARA_IDX_SYS_DEADBAND_CYC
Index for system parameter deadband cycles
PARA_IDX_SYS_PWMPERIOD
Index for system parameter PWM period
PARA_IDX_SYS_TS
Index for system parameter sampling time
PARA_IDX_SYS_SAMPLE_FREQ
Index for system parameter sampling frequency
PARA_IDX_MAX
Total number of user and system parameters
Function Documentation
PARA_checkEST()
void PARA_checkEST (uint32_t * parameter, EST_Instance * handle, PARA_IDX idx)
Check for EST parameter changes.
Parameters
[in] parameter Pointer to the parameter array.
[in] handle A pointer to est instance
[in] idx Index of the parameter changed. One of PARA_IDX
References PARA_IDX_SYS_TS, PARA_IDX_USER_KE, PARA_IDX_USER_LS, PARA_IDX_USER_PWMFREQ, and PARA_IDX_USER_RS.
Referenced by FOC_setPara().
PARA_checkPISPD()
void PARA_checkPISPD (uint32_t * parameter, PI_Instance * handle, PARA_IDX idx)
Check for PISPD parameter changes.
Parameters
[in] parameter Pointer to the parameter array.
[in] handle A pointer to pi instance
[in] idx Index of the parameter changed. One of PARA_IDX
References PI_PARA::Ki, PI_PARA::Kp, PARA_IDX_USER_PISPD_KI, PARA_IDX_USER_PISPD_KP, and PI_UpdateParams().
Referenced by FOC_setPara().
PARA_checkPIIQ()
void PARA_checkPIIQ (uint32_t * parameter, PI_Instance * handle, PARA_IDX idx)
Check for PIIQ parameter changes.
Parameters
[in] parameter Pointer to the parameter array.
[in] handle A pointer to pi instance
[in] idx Index of the parameter changed. One of PARA_IDX
References PI_PARA::Ki, PI_PARA::Kp, PARA_IDX_USER_PIIQ_KI, PARA_IDX_USER_PIIQ_KP, and PI_UpdateParams().
Referenced by FOC_setPara().
PARA_checkPIID()
void PARA_checkPIID (uint32_t * parameter, PI_Instance * handle, PARA_IDX idx)
Check for PIID parameter changes.
Parameters
[in] parameter Pointer to the parameter array.
[in] handle A pointer to pi instance
[in] idx Index of the parameter changed. One of PARA_IDX
References PI_PARA::Ki, PI_PARA::Kp, PARA_IDX_USER_PIID_KI, PARA_IDX_USER_PIID_KP, and PI_UpdateParams().
Referenced by FOC_setPara().
PARA_checkRC()
void PARA_checkRC (uint32_t * parameter, RMPCNTL_Instance * handle, PARA_IDX idx)
Check for RC parameter changes.
Parameters
[in] parameter Pointer to the parameter array.
[in] handle A pointer to rc instance
[in] idx Index of the parameter changed. One of PARA_IDX
References RMPCNTL_PARA::maxFreq, PARA_IDX_SYS_TS, PARA_IDX_USER_MAX_FREQ, PARA_IDX_USER_PWMFREQ, PARA_IDX_USER_SPDREF_RAMP_RATE, RMPCNTL_PARA::RampDelta, RMPCNTL_UpdateParams(), and RMPCNTL_PARA::Ts.
Referenced by FOC_setPara().
PARA_checkRG()
void PARA_checkRG (uint32_t * parameter, RAMPGEN_Instance * handle, PARA_IDX idx)
Check for RG parameter changes.
Parameters
[in] parameter Pointer to the parameter array.
[in] handle A pointer to rg instance
[in] idx Index of the parameter changed. One of PARA_IDX
References PARA_IDX_SYS_TS, PARA_IDX_USER_PWMFREQ, RAMPGEN_UpdateParams(), and RAMPGEN_PARA::Ts.
Referenced by FOC_setPara().
PARA_checkPWMGEN()
void PARA_checkPWMGEN (uint32_t * parameter, PWMGEN_Instance * handle, PARA_IDX idx)
Check for PWMGEN parameter changes.
Parameters
[in] parameter Pointer to the parameter array.
[in] handle A pointer to pwmgen instance
[in] idx Index of the parameter changed. One of PARA_IDX
References PWMGEN_PARA::deadband, PARA_IDX_SYS_DEADBAND_CYC, PARA_IDX_SYS_PWMPERIOD, PARA_IDX_USER_DEADBAND, PARA_IDX_USER_PWMFREQ, PWMGEN_UpdateParams(), and PWMGEN_PARA::pwmPeriod.
Referenced by FOC_setPara().
PARA_checkIPD()
void PARA_checkIPD (uint32_t * parameter, IPD_Instance * handle, PARA_IDX idx)
Check for IPD parameter changes.
Parameters
[in] parameter Pointer to the parameter array.
[in] handle A pointer to ipd instance
[in] idx Index of the parameter changed. One of PARA_IDX
References PARA_IDX_SYS_SAMPLE_FREQ, PARA_IDX_USER_IPD_CURRENT_THRESHOLD, PARA_IDX_USER_IPD_FREQ, and PARA_IDX_USER_PWMFREQ.
Referenced by FOC_setPara().
© Copyright 1995-2023, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale