SensorlessFOCMotorControlLibrary: Motor_Module
Motor_Module
Macros
#define MOTOR_PARA_NUM_POLE_PAIRS (MOTOR_PARA_POLES/2)
Pole pairs of the motor.
Functions
float MOTOR_getBaseFreq (float baseRpm, float poles)
Calculates the base frequency from base rpm and number of poles.
Detailed Description
Function Documentation
MOTOR_getBaseFreq()
float MOTOR_getBaseFreq (float baseRpm, float poles)
Calculates the base frequency from base rpm and number of poles.
Parameters
[in] baseRpm Base rpm of motor
[in] poles Number of poles of motor
Returns
Returns the calculated base frequency
Referenced by PARA_checkESMO(), PARA_checkRG(), and PARA_checkSPDEST().
© Copyright 1995-2023, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale