SensorlessFOCMotorControlLibrary: FOC_MATH/RMP_CNTL
FOC_MATH/RMP_CNTL
Data Structures
struct RMPCNTL_Instance
Define rmpcntrl structure.
struct RMPCNTL_PARA
Define ramp control parameter structure.
Macros
#define RMPCNTL_DEFAULTS
Default values for RMPCNTL instance.
Functions
__STATIC_INLINE void RMPCNTL_UpdateParams (RMPCNTL_Instance *handle, RMPCNTL_PARA *para)
Update the ramp control parameters.
__STATIC_INLINE void RC_run (RMPCNTL_Instance *handle)
Run ramp control.
__STATIC_INLINE void RC_reset (RMPCNTL_Instance *handle)
Reset ramp control variables.
Detailed Description
Macro Definition Documentation
RMPCNTL_DEFAULTS
#define RMPCNTL_DEFAULTS
Value:
{  0,            \
                            1,           \
                           _IQ(-1),  \
                           _IQ(1),   \
                            0,       \
                                0,       \
                                0,       \
                            0,       \
                                  }
Default values for RMPCNTL instance.
Function Documentation
RMPCNTL_UpdateParams()
__STATIC_INLINE void RMPCNTL_UpdateParams (RMPCNTL_Instance * handle, RMPCNTL_PARA * para)
Update the ramp control parameters.
Parameters
[in] handle A pointer to ramp control instance
[in] para A pointer to parameter array
References _IQmpy_rts, RMPCNTL_PARA::maxFreq, RMPCNTL_Instance::RampDelta, RMPCNTL_PARA::RampDelta, RMPCNTL_Instance::RampHighLimit, RMPCNTL_Instance::RampLowLimit, and RMPCNTL_PARA::Ts.
Referenced by PARA_checkRC().
RC_run()
__STATIC_INLINE void RC_run (RMPCNTL_Instance * handle)
Run ramp control.
Parameters
[in] handle A pointer to rmpcntrl instance
References RMPCNTL_Instance::RampDelayCount, RMPCNTL_Instance::RampDelayMax, RMPCNTL_Instance::RampDelta, RMPCNTL_Instance::RampHighLimit, RMPCNTL_Instance::RampLowLimit, RMPCNTL_Instance::SetpointValue, RMPCNTL_Instance::TargetValue, and RMPCNTL_Instance::Tmp.
Referenced by FOC_run().
RC_reset()
__STATIC_INLINE void RC_reset (RMPCNTL_Instance * handle)
Reset ramp control variables.
Parameters
[in] handle A pointer to ramp control instance
References RMPCNTL_Instance::SetpointValue, and RMPCNTL_Instance::TargetValue.
Referenced by FOC_CONTROL_run().
© Copyright 1995-2023, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale