SensorlessFOCMotorControlLibrary: FOC_MATH/PI
FOC_MATH/PI
Data Structures
struct PI_Instance
Define pi structure.
struct PI_PARA
Define pi parameter structure.
Macros
#define PI_DEFAULTS
Default values for pi instance.
Functions
__STATIC_INLINE void PI_UpdateParams (PI_Instance *handle, PI_PARA *para)
Update the pi parameters.
__STATIC_INLINE void PI_run (PI_Instance *handle)
Run pi controller.
__STATIC_INLINE void PI_POS_run (PI_Instance *handle)
PI Angle tracking macro, used with angle as input and has error rollup.
Detailed Description
Macro Definition Documentation
PI_DEFAULTS
#define PI_DEFAULTS
Value:
{                                                                                                                  \
                                                   0,                                                                                              \
                           0,                                                                                              \
                                                   0,                                                                                              \
                           _IQ(1.0),                                                                               \
                           0,                                                                                              \
                           _IQ(1.0),                                                                               \
                           _IQ(-1.0),                                                                              \
                           0,                                                                                              \
                           0,                                                                                              \
                           0,                                                                                              \
                           0,                                                                                              \
                           _IQ(1.0)                                                                                \
                                  }
Default values for pi instance.
Function Documentation
PI_UpdateParams()
__STATIC_INLINE void PI_UpdateParams (PI_Instance * handle, PI_PARA * para)
Update the pi parameters.
Parameters
[in] handle A pointer to pi instance
[in] para A pointer to parameter array
References PI_Instance::Ki, PI_PARA::Ki, PI_Instance::Kp, PI_PARA::Kp, PI_PARA::Max, PI_PARA::Min, PI_Instance::Umax, and PI_Instance::Umin.
Referenced by PARA_checkPIID(), PARA_checkPIIQ(), and PARA_checkPISPD().
PI_run()
__STATIC_INLINE void PI_run (PI_Instance * handle)
Run pi controller.
Parameters
[in] handle A pointer to pi instance
References PI_Instance::Fbk, PI_Instance::i1, PI_Instance::Ki, PI_Instance::Kp, PI_Instance::Out, PI_Instance::Ref, PI_Instance::ui, PI_Instance::Umax, PI_Instance::Umin, PI_Instance::up, and PI_Instance::v1.
Referenced by FOC_run().
PI_POS_run()
__STATIC_INLINE void PI_POS_run (PI_Instance * handle)
PI Angle tracking macro, used with angle as input and has error rollup.
Parameters
[in] handle A pointer to pi instance
References ANGLE_WRAP(), PI_Instance::Fbk, PI_Instance::i1, PI_Instance::Ki, PI_Instance::Kp, PI_Instance::Out, PI_Instance::Ref, PI_Instance::ui, PI_Instance::Umax, PI_Instance::Umin, PI_Instance::up, and PI_Instance::v1.
© Copyright 1995-2023, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale