SensorlessFOCMotorControlLibrary: FOC_MATH/SPEED_EST
FOC_MATH/SPEED_EST
Data Structures
struct SPDEST_Instance
Define speed estimator structure.
struct SPDEST_PARA
Define speed estimator parameter structure.
Macros
#define SPDEST_PI (3.14159265358979)
Define speed estimator structure.
#define SPDEST_FILTER_CUTOFF_FREQ (5)
Cutodf frequency for the low pass filter in speed estimator.
#define SPDEST_DEFAULTS { 0, 0, 0, 0, 0, 0, 0, 0, 0 }
Default values for SPEED_ESTIMATION object.
Functions
__STATIC_INLINE void SPDEST_UpdateParams (SPDEST_Instance *handle, SPDEST_PARA *para)
Update the speed estimator parameters.
__STATIC_INLINE void SPDEST_run (SPDEST_Instance *handle)
Run speed estimator.
Detailed Description
Function Documentation
SPDEST_UpdateParams()
__STATIC_INLINE void SPDEST_UpdateParams (SPDEST_Instance * handle, SPDEST_PARA * para)
Update the speed estimator parameters.
Parameters
[in] handle A pointer to speed estimator instance
[in] para A pointer to parameter array
References SPDEST_PARA::baseFreq, SPDEST_Instance::BaseRpm, SPDEST_PARA::baseRpm, SPDEST_Instance::K1, SPDEST_Instance::K2, SPDEST_Instance::K3, SPDEST_FILTER_CUTOFF_FREQ, SPDEST_PI, and SPDEST_PARA::Ts.
Referenced by PARA_checkSPDEST().
SPDEST_run()
__STATIC_INLINE void SPDEST_run (SPDEST_Instance * handle)
Run speed estimator.
Parameters
[in] handle A pointer to speed estimator instance
References ANGLE_WRAP(), SPDEST_Instance::BaseRpm, SPDEST_Instance::EstimatedSpeed, SPDEST_Instance::EstimatedSpeedRpm, SPDEST_Instance::EstimatedTheta, SPDEST_Instance::K1, SPDEST_Instance::K2, SPDEST_Instance::K3, SPDEST_Instance::OldEstimatedTheta, and SPDEST_Instance::Temp.
Referenced by FOC_run().
© Copyright 1995-2023, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale