SensorlessFOCMotorControlLibrary: FOC_MATH/PWMGEN
FOC_MATH/PWMGEN
Data Structures
struct PWMGEN_Instance
Define pwmgen structure.
struct PWMGEN_PARA
Define pwmgen parameter structure.
Macros
#define PWMGEN_DEFAULTS { 0,0,0,0,0,0,0,0,0 }
Default values for pwmgen instance.
#define PWMGEN_ADC_SETTLE_DELAY (20)
Delay for the ADC value to settle all low side turn on.
Functions
__STATIC_INLINE void PWMGEN_UpdateParams (PWMGEN_Instance *handle, PWMGEN_PARA *para)
Update the pwmgen parameters.
__STATIC_INLINE void PWMGEN_checkLimits (uint16_t *duty, uint16_t maxduty, uint16_t minduty)
Limit to max and min duty limits.
__STATIC_INLINE void PWMGEN_run (PWMGEN_Instance *handle)
Run pwmgen algorithm.
Detailed Description
Function Documentation
PWMGEN_UpdateParams()
__STATIC_INLINE void PWMGEN_UpdateParams (PWMGEN_Instance * handle, PWMGEN_PARA * para)
Update the pwmgen parameters.
Parameters
[in] handle A pointer to pwmgen instance
[in] para A pointer to parameter array
References PWMGEN_PARA::adcSampleCycles, PWMGEN_PARA::deadband, PWMGEN_Instance::dutyMax, PWMGEN_Instance::dutyMin, PWMGEN_Instance::HalfPerMax, PWMGEN_ADC_SETTLE_DELAY, and PWMGEN_PARA::pwmPeriod.
Referenced by PARA_checkPWMGEN().
PWMGEN_checkLimits()
__STATIC_INLINE void PWMGEN_checkLimits (uint16_t * duty, uint16_t maxduty, uint16_t minduty)
Limit to max and min duty limits.
Parameters
[in] duty Dutycycle input to limit
[in] maxduty Max dutycycle to limit to
[in] minduty Min dutycycle to limit to
Referenced by PWMGEN_run().
PWMGEN_run()
__STATIC_INLINE void PWMGEN_run (PWMGEN_Instance * handle)
Run pwmgen algorithm.
Parameters
[in] handle A pointer to pwmgen instance
References PWMGEN_Instance::dutyA, PWMGEN_Instance::dutyB, PWMGEN_Instance::dutyC, PWMGEN_Instance::dutyMax, PWMGEN_Instance::dutyMin, PWMGEN_Instance::HalfPerMax, PWMGEN_Instance::MfuncC1, PWMGEN_Instance::MfuncC2, PWMGEN_Instance::MfuncC3, and PWMGEN_checkLimits().
Referenced by FOC_run().
© Copyright 1995-2023, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale