SensorlessFOCMotorControlLibrary: FOC_MATH/ANGLE_MATH
FOC_MATH/ANGLE_MATH
Macros
#define ANGLE_MATH_0P5_IQ _IQ(0.5)
0.5 in IQ
#define ANGLE_MATH_1P0_IQ _IQ(1.0)
1.0 in IQ
Functions
__STATIC_INLINE void ANGLE_WRAP (_iq *angle)
Wraps angle within _IQ(-0.5) and _IQ(0.5)
Detailed Description
Function Documentation
ANGLE_WRAP()
__STATIC_INLINE void ANGLE_WRAP (_iq * angle)
Wraps angle within _IQ(-0.5) and _IQ(0.5)
Parameters
[in] angle Angle input to wrap within _IQ(-0.5) and _IQ(0.5)
References ANGLE_MATH_0P5_IQ, and ANGLE_MATH_1P0_IQ.
Referenced by PI_POS_run(), RG_run(), and SPDEST_run().
© Copyright 1995-2023, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale