SensorlessFOCMotorControlLibrary: FOC_MATH/RAMPGEN
FOC_MATH/RAMPGEN
Data Structures
struct RAMPGEN_Instance
Define rampgen structure.
struct RAMPGEN_PARA
Define ramp generator estimator parameter structure.
Macros
#define RAMPGEN_DEFAULTS {0, 0, 0, 0 }
Default values for RAMPGEN instance.
Functions
__STATIC_INLINE void RAMPGEN_UpdateParams (RAMPGEN_Instance *handle, RAMPGEN_PARA *para)
Update the ramp generator parameters.
__STATIC_INLINE void RG_run (RAMPGEN_Instance *handle)
Run RAMP(Sawtooth) Generator.
void RG_reset (RAMPGEN_Instance *handle)
Reset RAMP(Sawtooth) Generator.
Detailed Description
Function Documentation
RAMPGEN_UpdateParams()
__STATIC_INLINE void RAMPGEN_UpdateParams (RAMPGEN_Instance * handle, RAMPGEN_PARA * para)
Update the ramp generator parameters.
Parameters
[in] handle A pointer to ramp generator instance
[in] para A pointer to parameter array
References RAMPGEN_Instance::StepAngleMax, and RAMPGEN_PARA::Ts.
Referenced by PARA_checkRG().
RG_run()
__STATIC_INLINE void RG_run (RAMPGEN_Instance * handle)
Run RAMP(Sawtooth) Generator.
Parameters
[in] handle A pointer to ramp generator instance
References _ANGLE_IQtoIQ32, RAMPGEN_Instance::Angle, RAMPGEN_Instance::Freq, RAMPGEN_Instance::Out, RG_reset(), and RAMPGEN_Instance::StepAngleMax.
Referenced by FOC_run().
RG_reset()
void RG_reset (RAMPGEN_Instance * handle)
Reset RAMP(Sawtooth) Generator.
Parameters
[in] handle A pointer to ramp generator instance
References RAMPGEN_Instance::Angle, and RAMPGEN_Instance::Out.
Referenced by FOC_CONTROL_run(), and RG_run().
© Copyright 1995-2023, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale