SensorlessFOCMotorControlLibrary: servicesHAL.h File Reference
servicesHAL.h File Reference
Detailed Description
Application services HAL Module.
Overview
Handles the HAL for services module
#include "services.h"
Functions
void HAL_setDeadTime (uint32_t value)
Sets deadtime.
uint16_t gateDriverGetMinOnDutySineMod (void)
Gets minimum on duty for sine modulation.
uint16_t gateDriverGetMinOnDutyOverMod (void)
Gets minimum on duty for over modulation.
int32_t gateDriverGetPropagationDelay (void)
Gets the gate driver propagation delay.
Function Documentation
HAL_setDeadTime()
void HAL_setDeadTime (uint32_t value)
Sets deadtime.
Parameters
[in] value Value for Deadtime configuration
References gateDriverGetMinOnDutyOverMod(), gateDriverGetMinOnDutySineMod(), and gateDriverGetPropagationDelay().
Referenced by peri1Config().
gateDriverGetMinOnDutySineMod()
uint16_t gateDriverGetMinOnDutySineMod (void)
Gets minimum on duty for sine modulation.
Returns
Returns the minimum on duty
Referenced by HAL_setDeadTime().
gateDriverGetMinOnDutyOverMod()
uint16_t gateDriverGetMinOnDutyOverMod (void)
Gets minimum on duty for over modulation.
Returns
Returns the minimum on duty
Referenced by HAL_setDeadTime().
gateDriverGetPropagationDelay()
int32_t gateDriverGetPropagationDelay (void)
Gets the gate driver propagation delay.
Returns
Returns the gate driver propagation delay
Referenced by HAL_setDeadTime().
© Copyright 1995-2024, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale